### ISSUE TITLE
Feature Request: Dynamically add ng-message to ng-messages

### ISSUE THREAD

**Issue by adrianandreias** [angular/angular.js#10036]
Add the ability to programaticaly add ngMessage item to an existing ngMessages directive.

I am trying to show the field error returned by an AJAX form submit. This way frontend errors and backend errors displaying would be done the same way.

Do you this is the right approach or you would just create another way to insert the server side error in the DOM?

**Comment by wendellm** [comment]
Bah Bah, I was trying to get this to work the whole day, thinking it was me. My forms are build completely at runtime by meta data so yeah I need it. Thanks!

**Comment by matsko** [comment]
Here's a work in progress: http://plnkr.co/edit/EqxV25DMumMR9fPiBdnZ?p=preview

**Comment by matsko** [comment]
@adrianandreias @jesselpalmer @wendellm this feature no exists in a PR and it's tested and functional, but we're just taking this week to decide on a proper naming convention.

**Comment by jessemorton** [comment]
Thanks @matsko!

**Comment by adrianandreias** [comment]
That's great @matsko :)

**Comment by adrianandreias** [comment]
Will this be included in 1.4?

**Comment by matsko** [comment]
The goal is to have it for both 1.3 and 1.4 so long as it doesn't break anything.

**Comment by adrianandreias** [comment]
I think this didn't make into v1.4.0-beta.2 and v1.3.10, right?

**Comment by matsko** [comment]
Not yet. Still negotiating a proper naming convention.

**Comment by matsko** [comment]
We're almost there. Just waiting on a final review for #10676.
