### ISSUE TITLE
Proposal: .ng-prefilled class helper

### ISSUE THREAD

**Issue by luisfarzati** [angular/angular.js#10050]
This would be handy in the following use case:

You want to show validation messages either

* after the form is submitted

* on field touch, **provided the field has already a value**. In this case I'd like the user to notice the validity of the new value right after touch -- instead of waiting until form submission.

So it would work like this (relevant classes mentioned):

1. the field is in a *untouched state*, but has a value: `ng-untouched` `ng-pristine` `ng-prefilled`
2. user *changes* field value: `ng-untouched` `ng-dirty` `ng-prefilled`
3. user *blurs* field: `ng-touched` `ng-dirty` `ng-prefilled`

Does this makes sense to you, guys?

**Comment by petebacondarwin** [comment]
OK, so ngModel already has a method called `$isEmpty()`, which is special cased for things like checkboxes and selects. We should be able to add CSS classes for `ng-empty`, `ng-not-empty` based on the value of calls to this method. I think that would be sufficient to do what @luisfarzati wants to achieve.
