### ISSUE TITLE
perf: optimimize compilation of directives with templateUrl

### ISSUE THREAD

**Issue by g00fy-** [angular/angular.js#10055]
even when the template is cached using `$templateCache` the compilation of directive that has `templateUrl` delays rendering by approximate 8ms (more if multiple directives are used, but the cost is `log(n)` rather than `o(n)`. 
This is especially notable when there is a large number of nested directives using `templateUrl`. 
One way of solving this would be to mutate the `DDO` in following way: when the `templateUrl` is fetched, the `DDO` would have `template` instead of `templateUrl` (sequential compilations would run synchronously without the delay). Other idea would be to optimize production version of the app by changing the `directiveProvider` so it would replace the `template` during config time. This gets a bit tricky because `templateUrl` can be a function, but either way it can be done quite simply.
I will try to add a plunkr demonstrating the problem and the first solution ASAP.

**Comment by Narretz** [comment]
I agree that this is probably not a good idea. You can always change templateUrl -> template in a build step if you want.
