### ISSUE TITLE
Add ng-prop-* to one-way bind an expression to arbitrary element properties

### ISSUE THREAD

**Issue by ewinslow** [angular/angular.js#10072]
ng-prop-* could take an expression and bind to arbitrary properties:

```
ng-prop-checked="some.expression"
```

This would be similar to the current ng-attr-*:
```
ng-attr-x="{{interpolation}}"
```

Reasoning:
 1. Angular 2.0 is going this sort of direction. So this will help ease migration. Migration pain is one of the main complaints right now for 2.0, it seems to me.
 2. Get the benefits of the Angular 2.0 approach without waiting 1.5 years.
   * ng-prop-* would always takes an expression, so it's clear what format the right hand side should be, regardless what property is being modified
   * ng-prop-* would work on all properties (like ng-attr-*), even from custom web components
   * etc.?
 3. (Minor) Provides nice symmetry from jQuery API to Angular API: $.fn.prop and $.fn.attr
 4. Binding to arbitrary properties requires custom compiler support to recognize all ng-prop-* attributes without explicitly adding each as separate directives, so this is why I think it belongs in core.

**Comment by lgalfaso** [comment]
Closing in favor of #12197 and #12198

**Comment by ewinslow** [comment]
Sounds good!
