### ISSUE TITLE
$submitted is not set on sub ng-form

### ISSUE THREAD

**Issue by luboid** [angular/angular.js#10071]
Hi,

I have &lt;form&gt; with inner &lt;ng-form&gt; 
when form is submitted inner &lt;ng-form&gt;.$submitted is not set to true only parent

**Comment by awerlang** [comment]
Another approach is using css:

```css
.ng-submitted .ng-invalid {
.... styles styles styles ...
}
```

or looping through all parent forms:

```js
while (form) form = form.$$parentForm;
```

**Comment by stryju** [comment]
possible workaround:

```es6
.directive( ‘ngForm’, function () {
  return {
    restrict : 'EA',

    require : [ '?^^form', 'form' ],

    link( scope, element, attrs, [ form, ctrl ] ) {
      if ( form ) {
        scope.$watch( () => form.$submitted, ( v ) => v && ctrl.$setSubmitted() );
      }
    }
  };
})
```

**Comment by kwypchlo** [comment]
:+1: I would like to see that too

My rl scenario is that I have a form where I have directive that uses ng-form and inside it I also have another directive with some input fields. That second (most inner) directive requires form controller in link function and it is the form controller from the ng-form directive. I have validation messages showing on submitted form but the only form that gets $submitted flag is the most outer form. The ng-form controller has $submitted set to false and the validation messages are not shown.

**Comment by awerlang** [comment]
@kwypchlo does the css I posted above solve your issue?

**Comment by stryju** [comment]
real life use-case:

some form:
```html
<form ng-form="form1" ng-submit="save(form1)">
  <custom-fieldset model="model.firstname" required></custom-fieldset>
  <custom-fieldset model="model.lastname" required></custom-fieldset>
  <button>save</button>
</form>
```

`custom-fieldset.html`:
```html
<fieldset ng-form="form">
  <input name="name" required ng-model="ctrl.model">
  <ng-messages role="alert"
    for="(form.$submitted || form.name.$touched) &amp;&amp; form.name.$error">
    <ng-message when="required">please enter a name</ng-message>
  </ng-messages>
</fieldset>
```

**Comment by ckniffen** [comment]
@stryju This is similar to the use case I had.

**Comment by kwypchlo** [comment]
@awerlang nope, I need this functionality in js, inside my directive

**Comment by ashleahhill** [comment]
:+1: for including this.

I have a setup similar to @stryju 's above. I added a watch to the child forms for now to watch the parent form's  $submitted property, but It does feel hacky.

**Comment by fromi** [comment]
I ran into this issue as well. I have a subform that I reuse in many forms, there it is excluded to refer to parent form name to know if it was submitted or not.

For example, when I submit my user form, obviouly my subform for user address is submitted as well. However, userForm.$submitted becomes true, but userForm.addressForm.$submitted stays to false.

user-form.html:
```html
<form name="userForm" novalidate>
	<div ng-class="{ 'has-error' : userForm.$submitted &amp;&amp; userForm.firstName.$invalid}">
		<label>First name</label>
		<input type="text" ng-model="user.firstName" name="firstName" required>
	</div>
	<div ng-class="{ 'has-error' : userForm.$submitted &amp;&amp;  userForm.lastName.$invalid}">
		<label>Last name</label>
		<input type="text" ng-model="user.lastName" name="lastName" required>
	</div>
	<fieldset ng-form="addressForm" class="address" ng-include="'address/address-fields.html'"></fieldset>
</form>
```
address-fields.html:
```html
<div ng-class="{ 'has-error' : addressForm.$submitted &amp;&amp;  addressForm.postcode.$invalid}">
	<label>Postcode</label>
	<input type="text" ng-model="address.postcode" ng-required="true" name="postcode">
</div>
<div ng-class="{ 'has-error' : addressForm.$submitted &amp;&amp;  addressForm.city.$invalid}">
	<label>City</label>
	<input type="text" ng-model="address.city" ng-required="true" name="city">
</div>
<div ng-class="{ 'has-error' : addressForm.$submitted &amp;&amp;  addressForm.country.$invalid}">
	<label>Country</label>
	<input type="text" ng-model="address.country" ng-required="true" name="country">
</div>
```

**Comment by nettino** [comment]
+1

**Comment by santhony7** [comment]
Yes please!

**Comment by nettino** [comment]
quick workaround I've found somewhere and modified:
```javascript
// sets all children ng-forms submitted (no such default functionality)
function setSubmitted(form) {
    form.$setSubmitted();
    angular.forEach(form, function(item) {
        if(item && item.$$parentForm === form && item.$setSubmitted) {
            setSubmitted(item);
        }
    });
}
```
so ie. instead of scope.form.$setSubmitted(); use:
```javascript
setSubmitted(scope.form);
```

**Comment by stevemao** [comment]
A workaround: http://stackoverflow.com/a/30138961/2075423

Note this only works if `formCtrl.$submitted` is changed. So it might not work with dynamic nested `ng-form`.

**Comment by jtougas** [comment]
:+1:

**Comment by bolemeus** [comment]
I have thesame issue. I made the following workaround based on awerlang's suggestion...

In my directive.
```
ctrl.isSubmitted = function() {
    var form = ctrl.form;
    while (!!form) {
        if (form.$submitted) return true;
        form = form.$$parentForm;
    }
    return false;
};
```

In the view...
```
<div class="has-feedback" ng-class="{'has-error': ctrl.isSubmitted() && ctrl.form[ctrl.name].$invalid}">
	...
</div>
```

I do agree that this feels a bit hacky though, but it works...
The css rules would work as well I think, but the has-error class is defined in bootstrap, and I don't really want to duplicate the css from bootstrap for a custom css rule. That can get messy when migrating to newer bootstrap versions.

**Comment by pbrain19** [comment]
will this issue be resolved before Trump takes office?

**Comment by ygilliot** [comment]
nope...

**Comment by nmschulte** [comment]
"_bump_"

> while (form) form = form.$$parentForm;

FYI: This doesn't actually work -- the root `FormController` has a "noop form" set as its parent; different looping and/or conditional are required. (e.g. `while (form.hasOwnProperty('$submitted')) form = form.$$parentForm` or such).

**Comment by Larvalis** [comment]
Another workaround I used was a watch:
```
$scope.$watch('form.$$parentForm.$submitted', function (submitted) {
    if (submitted) {
        $scope.form.$setSubmitted(true);
    }
});
```

**Comment by andremw** [comment]
My team got into a situation where we really need the change from https://github.com/angular/angular.js/pull/15778, so what we did was to create a copy of angular.js (say, angular-mod.js) that includes the change from the PR and use the npm script _postinstall_ to overwrite the angular.js file in node_modules (a simple `cp angular-mod.js node_modules/angular/angular.js`).

Worked like a charm.
