### ISSUE TITLE
Lets re-do the docs app with Material!

### ISSUE THREAD

**Issue by caitp** [angular/angular.js#10075]
It's not a huge priority, but I feel it would help to do a few things:

1. eat (more of) the dogfood
2. help make the accessibility demos work with real-world components so that they're more meaningful
3. look great, feel great
4. get docs contributors comfortable with material.

So, this is just a kind of meta-thing, the actual effort involved to convert the app to do this may take a fair bit of work and is maybe not the biggest priority, but I think it's worth doing.

Lets put it on the backburner :>

**Comment by wesleycho** [comment]
I think this isn't likely to get done given that the lion share of attention is being given to Angular 2.

**Comment by petebacondarwin** [comment]
This keeps being talked about by various community groups. But I agree that there is little point in tracking this as an issue.
