### ISSUE TITLE
Improve *.angularjs.org logging

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular.js#10102]
There have been a couple of occasions where logs have silently failed to rotate, resulting in performance issues. While the underlying causes have been fixed, this should be prevented in the future.

This could be solved in one of two ways:
- Add a script that runs at least daily on each VM and sends a pass/fail email to angular-dev. The script should check that the previous days' logs have been rotated (i.e. check that code-error.log-2014-11-17.gz exists), should report if a particular error log is logging more frequently than expected
- Or log all logs to a logging service that can be configured to send alerts for these cases

**Comment by Narretz** [comment]
Since we are switching to Firebase hosting, this doesn't apply anmore.
