### ISSUE TITLE
Improve angularjs.org speed

### ISSUE THREAD

**Issue by frfancha** [angular/angular.js#10109]
The web site angularjs.org is slow. Displaying the first page is slow, going to blog is slow,...
To be honest, I don't care personaly about this, but I think that for people discovering the technology it can be a (false!) general indication that angularjs itself is slow.

**Comment by Narretz** [comment]
I think a big part of this "slow feeling" came from the fact that there was no loading indicator when switching pages. This has been implemented a while ago. The overall speed seems good to me.
