### ISSUE TITLE
[new functionality] Form validation - behaviour when error appear - mix blur / regular

### ISSUE THREAD

**Issue by kwladyka** [angular/angular.js#10108]
First i describe scenario when user suffer because of bad User Expirence connected with form validation in AngularJS.

1) user fill field with bad value.
a) blur - it's ok in my opinion
b) regular - it is problem when example user have to write e-mail or something else, he start with good value and see error because he is still typing and not finish yet.

2) user correcting field with bad value, the error message appeared on the bottom of this field like in bootstrap twitter framework. It mean when error will hide the content after error message will jump up!
a) blur - user corrected value and now he is clicking on submit button or another field. Error message hide, content jump up and oh... he clicked on something else, damn it was link with another action... have to fill all form again.

b) regular - error message hide imidielty when user type correct value and user can click where they want.

**Solution:**
When field doesn't have error status it should checking with blur.
When field has error status it should be checking with regular.

**Comment by Narretz** [comment]
If I understood correctly, this should be possible with dynamically changing the updateOn options on the ngModel controller: http://plnkr.co/edit/ZF61CvdGW07NvS4S8pqq?p=preview
