### ISSUE TITLE
Possible memory leak in ngRepeat

### ISSUE THREAD

**Issue by daanporon** [angular/angular.js#10121]
I think i found a memory leak issue in angular 1.2.x at first we where working on 1.2.23 where i had the issue then i saw we where behind and updated to 1.2.26. But the issue was not resolved.

I created a plunkr where it's possible to reproduce the problem.
http://plnkr.co/edit/pA43qJd92eCxMLbtWUf5?p=preview

I have 2 states, state A and state B and on state B i have an ng-repeat. When i transition from state A to state B and then back to state A. The scope of the controller of state B is still in memory. When i put my ng-repeat inside another directive which creates it's own scope (isolated or regular) it's also leaking the scopes of every item in the ng-repeat. When i remove the ng-repeat from my state- or directive template the controller is GC'd correctly. 

Also tested this with an ng-if and ng-switch and couldn't reproduce the problem with them.

Also tested it by upgrading to the latest angular 1.3 and there the issue seems resolved, but i still have to support IE8 so :(

I thought it had something to do with this PR (https://github.com/angular/angular.js/pull/9281) so i tried backporting the changes to an 1.2.26 version, but this doesn't solve it.

Anyone any idea what could be the issue or can someone point me in the right direction? Already spent a few hours trying to solve this, and i'm a bit stuck :(

**Comment by mrmarktyy** [comment]
Having very similar experience, just wondering what's the status of this issue ? thanks

**Comment by Narretz** [comment]
Closing, as this is an old issue without a clear repro applying to old versions.
