### ISSUE TITLE
$provide.decorator to extend directive scope no longer works in 1.3.x

### ISSUE THREAD

**Issue by sumigoma** [angular/angular.js#10149]
I'm using a directive that has an isolated scope, but I would like to expose an additional member so that I can bind to its value from the parent scope. Since the directive is from a third party I would like to do so without modifying the original code. In Angular 1.2.x, I used to be able to do *this* to decorate the existing directive with a new two-way binding.

```javascript
app.config(function($provide) {
    $provide.decorator('mycustomDirective',['$delegate','$controller', function($delegate, $controller) {
      
        var directive = $delegate[0];
        angular.extend(directive.scope, { 
            othervar: "=" 
        }); 
        
        return $delegate;  
    }]);
});   
```

However, in Angular 1.3.x, extending the scope this way no longer seems to work. This is evident in this **simplified plunkr**: [http://plnkr.co/edit/bwgwGm6IcoRfLjIL8K9X?p=info](http://plnkr.co/edit/bwgwGm6IcoRfLjIL8K9X?p=info). 

Changing the script tag to 1.3.x breaks the behavior. It seems all other properties of the directive can still be modified using $provide.decorator, but the scope in particular no longer seems to get updated.

Is this a bug? What changed in Angular 1.3.x to cause this specific behavior? And what is the recommended way of extending the scope of an existing directive (with an isolated scope)?

**Comment by yangchristian** [comment]
+1. My use case is around directive templates: I'm using a 3rd party directive and want to alter some standard markup in its template to work with other directives. Here's the concrete scenario since that last sentence was a bit abstract:

- The 3rd party directive template has some simple `<a>` tags with an `href` binding, e.g. `<a href="{{ href }}">`
- I want to supply a [ui-router](https://github.com/angular-ui/ui-router) `state`, e.g. `<a ui-sref="{{ state }}">`
- I used to decorate the directive like OP, now I'm using the `.$$isolateBindings` workaround

**Comment by arjunasuresh3** [comment]
+1

**Comment by iainreid820** [comment]
As @sumigoma noted, appending 'Directive' after youe directive name allows you to then decorate that directive. I'm currently using this method in Angular 1.4.x.

**Comment by Wlada** [comment]
+1

**Comment by newmesiss** [comment]
as I solve this if I need to execute a method in controlling father?
which is ativado with ng-click within the directive used

**Comment by nmccready** [comment]
This is a serious limitation please see the linked issue to ui-leaflet. This is one of the proposed ways that we are looking to support leaflet plugins. That way our directive can be extended to support other attribute directives with one isolated scope directive. 

That way we avoid this ugly beast for every added plugin.

https://github.com/angular-ui/ui-leaflet/blob/master/src/directives/leaflet.js#L9-L21

Is this even considered a real bug yet?

**Comment by Narretz** [comment]
I don't think it has been considered a bug yet, simply because the behavior was essentally undocumented and the use cases aren't that common.

**Comment by jbedard** [comment]
And it is still possible, it's just uglier then before. Well worth the performance improvement every time the linker runs (on an isolated directive)...

**Comment by yahyaKacem** [comment]
:thumbsup: @iainreid820, @sumigoma.

**Comment by deividfortuna** [comment]
+1 
I really need this feature.
