### ISSUE TITLE
Filter issue when using negated int

### ISSUE THREAD

**Issue by adi-ads** [angular/angular.js#10141]
Use case - While manipulation dataset with id as int values you run into problems when trying to use negated and strict comparison.

http://jsfiddle.net/pdvhwd26/2/

In the example I want to delete a user with id 1
not using strict deletes 11 as well
using strict doesn't delete anything as types don't match
The third option is the desired result I am after.

The problem is I am being forced to convert to string to be able to negate the id.

Suggesting either to allow negation in a way that doesn't change type. Or handle this scenario in another way using a shorthand.

**Comment by petebacondarwin** [comment]
Closing this as won't fix. See the discussion at #10147
