### ISSUE TITLE
ngRoute is still resolving dependency for a route even when ngView is hidden with ngIf

### ISSUE THREAD

**Issue by slavafomin** [angular/angular.js#10152]
Hello!

I'm observing probably undesirable behavior with `ngView` and `ngIf` directives.

I have an `ngView` directive hidden by `ngIf` directive, but `ngRoute` is still starting to resolve the dependencies for activated route.

I've created a Plunk to demonstrate the issue:
http://plnkr.co/edit/9hYdSNc0NufTAbr8SOxa?p=preview

When `ngView` directive is missing from the document, `ngRoute` is not doing anything, but when `ngView` is removed from the document by `ngIf`, `ngRoute` is still trying to match the route and launch the controller.

I know it's a corner-case, but I thought I should report it nevertheless.

**Comment by Narretz** [comment]
@slavafomin This is currently not really possible. I personally set up some data before I bootstrap angular manually. You can also add a set of resolves to each route, which is only resolved by the first route that is matched when the app is loaded. You can also voice your support for https://github.com/angular/angular.js/issues/4003
