### ISSUE TITLE
Form control is overridden when nesting with ng-form and ng-repeat

### ISSUE THREAD

**Issue by hanneskaeufler** [angular/angular.js#10165]
Say I have a form which creates nested forms via `ng-repeat` and `ng-form`.

```html
  <form name="categoryForm">
    <div ng-repeat="item in items">
      <ng-form name="tags">
        Tag Name: <input name="name" ng-model="item.name" required>
        <div ng-if="tags.name.$invalid">This is great from the inside!</div>
      </ng-form>
    </div>
  </form>
```

This is great for accessing the form control `tags.name` inside the `ng-form` block. But from the outside, say in the controller, there is no way to get the same control.

`$scope.categoryForm.tags` is always set to the last control created by the repeated `ng-form`.

See http://plnkr.co/edit/SvBAxJFioTIgfs7Wvvk1?p=preview

It seems `$scope.categoryForm.tags` should rather be an array of `FormControllers` or something instead of only the last FormController.

Currently this has me creating ugly workarounds like

```html
<ng-repeat="...">
     <ng-form name="tags[{{ $index }}]">...</ng-form>
</ng-repeat>
```

which is possible since https://github.com/angular/angular.js/issues/1404 got closed.

Could we support something like an array of `FormControllers` or is this creating any other problems I´m not thinking of?

**Comment by philBrown** [comment]
I'd love to see nested forms used in `ng-repeat` added to an array as well.

We use server-side validation in our app and the validation contexts reference the controls using something like `resource.collection[0].field`. As it stands, I'm using the `ng-init` idea above but this means I need to transform the context paths into something like `resource.collection_0.field` when resolving form controls. It would be much cleaner if I could simply run the response string through `$parse` to resolve the form control without having to transform it.

**Comment by Sriram143** [comment]
I Updated the Sample
I Added a Add Button and i am adding new item to the collection then the form is not creating
http://jsfiddle.net/2ewe3uct/5/
It has tags 0 to 9 but its not adding tag10,tag11 by clicking on add button.

**Comment by abobwhite** [comment]
I've just run across this issue. It appears this worked at one point as recently as last March via http://stackoverflow.com/questions/22248733/angularjs-form-validation-within-ng-repeat.

**Comment by gkalpak** [comment]
@abobwhite, can you provide a demo of what is not working ?

**Comment by dohomi** [comment]
+1 I'm looking for this for a while now. Would be great if a syntax like this would be supported:
```
<div ng-repeat="exercise in training.exercises">
<input  max="60" min="0" type="number"
       ng-model="training.exercises[$index].duration"
       name="duration">
<div ng-messages="form.duration.$error"
     ng-if="trainingForm.$submitted || form.duration.$touched">
    <div ng-message="number">
        <span translate="MESSAGE_NUMBER"></span>
    </div>
    <div ng-message="min">
        <span translate="MESSAGE_MIN"></span>
    </div>
    <div ng-message="max">
        <span translate="MESSAGE_MAX"></span>
    </div>
</div>
</div>
```

**Comment by dohomi** [comment]
I just found a good temporary solution in here: https://github.com/angular/angular.js/issues/1404 
Now it works as expected.

**Comment by piyushchauhan2011** [comment]
Is it possible that nesting `ng-form` inside `ng-form` can override the properties of `mainForm` control ? Not sure, but had the problem of `$validity` being updated of `ng-form` with sub `ng-form` inside.

**Comment by gkalpak** [comment]
I'm going to close this, since we are not likely to change the current behavior and it is already possible to have something very similar to the requested.

In addition to the above mentioned solutions, you could even have a array-ish object by using a wrapper `ngForm` like this:

```html
<form name="categoryForm">
  ...
  <ng-form name="tags"><!-- Wrapper `ngForm` to collect all tags -->
    <div ng-repeat="item in items">
      <ng-form name="{{ $index }}"><!-- Use `$index` as the key, so tags can be accessed by index -->
        Tag name: <input name="name" ng-model="item.name" required />
        <div ng-if="categoryForm.tags[$index].name.$invalid">This is great from the inside !</div>
      </ng-form>
    </div>
  </ng-form>
</form>
```

[Demo fiddle][1]

Caveats:
- `categoryForm.tags` is not a real Array. It is an object that look like indexes. You can still access them as if it where an array: `categoryForm.tags[42]`
- An extra `tags` property is created on the current scope.

--
@piyushchauhan2011, yours sounds like a general support question. Please, use one of the [appropriate support channels][2] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: http://jsfiddle.net/a7cnLno0/
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
