### ISSUE TITLE
input[number] increments twice if change handler is slow

### ISSUE THREAD

**Issue by antelle** [angular/angular.js#10160]
If the user clicks increment button on numeric input and change handler hangs, the value is incremented twice in Chrome. Change handler is called twice as well: [jsbin](http://jsbin.com/kolipemaza/1/edit?html,js,output).
This is not a bug of standard HTML input control: [jsbin](http://jsbin.com/zolowukodi/1/edit).

**Comment by Narretz** [comment]
I jut tested this again and cannot repro the problem with Chrome 45. Closing.
