### ISSUE TITLE
Dynamically change ng-repeat template after compile/linking is done

### ISSUE THREAD

**Issue by coli** [angular/angular.js#1017]
This is probably a feature request (for performance reasons).

I have 

```
<tr ng-repeat>
  <td templates>
  <td templates>
</tr>
```

I'd like to be able to change the content of ng-repeat, and have the change reflected.

Right now, the alternative is 

```
<tr ng-repeat>
<td ng-repeat="col in columns" ng-include="col.inlineSrc"/>
</tr>
```

and the performance is horrid (eg: 700ms for 100 rows). ng-repeat with static template <td> with 100 row is more reasonable 150ms.

**Comment by Narretz** [comment]
There's still a difference in 1.6, but since there's a run-time template change, this is to be expected.
