### ISSUE TITLE
make $document a constant rather than service

### ISSUE THREAD

**Issue by jzacsh** [angular/angular.js#10218]
`$document` should be available at `config` time, so we can test with it as we do elsewhere, eg:

``` javascript
angular.module('myApp', []).config(function(wellTestedProvider, $document) {
  wellTestedProvider.doSomething($document, 'foo bar');
})
```

my 2 cents: we just make [`$document`](https://github.com/angular/angular.js/blob/v1.2.x/src/ng/document.js#L29) available via `.constant()` rather than `.provider()` as it is now

**Comment by jongunter** [comment]
I would agree with this sentiment. I cannot understand why `$document` would not be a constant, and for that matter, `$window`, too. Perhaps I need to configure something that needs access to the `document` or `window` globals in a provider, before my modules run?  

It's not like `document` and `window` need to be configured, so I just can't understand why they can't be made available as soon as humanly possible (so `config()` blocks and providers can use them).

Excluding these available globals from the DI system for config blocks and providers makes testing such functions/classes more difficult/confusing.

**Comment by gkalpak** [comment]
Just wanted to point out that making them constants in one's app is as easy as:

```js
.constant('$window', window)
.constant('$document', angular.element(window.document))
```

<sub>Although note that making `$document` a constant you lose the ability to derive it from `$window`.</sub>

**Comment by mgol** [comment]
I think it's a won't fix at this point. Having `$document` as a value has its use cases as well, I'm sure lots of code is decorating that, especially in unit tests. It doesn't seem worth to break it after it being a value for so long (and so short before we get into maintenance mode).
