### ISSUE TITLE
angular.copy doesn't work with typed arrays

### ISSUE THREAD

**Issue by digitalillusion** [angular/angular.js#10210]
Hello, please consider the following plunker:

http://plnkr.co/edit/AgjiBp2YtFKt8VfqBosT?p=preview

The call to angular.copy() passing a typed array as parameter throws exception:  length method called on incompatible Object at isArrayLike.
Using Firefox 33 on Linux

Thanks for the support

**Comment by pkozlowski-opensource** [comment]
This was fixed in master via aa0f64496a66d2a5d1a4d033f2eb075a8b084a78
