### ISSUE TITLE
generate *-node modules upon release

### ISSUE THREAD

**Issue by boneskull** [angular/angular.js#10239]
In reply to @IgorMinar's tweet:

> @bclinkinbeard @misterhiller @briantford should we just generate and update these *-node packages during our release process?

:+1: for this.  It also probably makes sense to do these for each of the official modules (animate, cookies, sanitize, etc.).  

If you wish, I can provide some sort of scaffold that each module can leverage to provide and test itself, so setup would be minimal.  ngMock and angular proper are both unique, but the rest can likely use it.

cc @btford @bclinkinbeard

**Comment by petebacondarwin** [comment]
I believe that all our releases are published to npm modules and support CommonJS importing.
