### ISSUE TITLE
"ng-mouseenter" broken in SVG template in Internet Explorer 9-11

### ISSUE THREAD

**Issue by askuzminov** [angular/angular.js#10259]
IE breaks on the line 3047

    if (!related || (related !== target && !target.contains(related))) {

SVG in IE has no "contains" method

example http://jsfiddle.net/4pe5pyn3/

Angular version - 1.3.4

**Comment by ionut-ai** [comment]
I know is more of a hack but until this gets permanently fixed I added a small shim.

```javascript
    if (typeof SVGElement.prototype.contains == 'undefined') {
        SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
    }

It does the job and doesn't require any core (jqLite) modification.

**Comment by Pryscy** [comment]
@ionut-ai Thx for this fix ! It works for me (ng-show buggy on svg element in IE10).

**Comment by miktav** [comment]
@ionut-ai Where does one put the shim?

**Comment by stefek99** [comment]
I've just spent all morning *(2+ hours)* investigating the issue.

I'm working in a secure corporate environment with many security policies / restrictions.

On IE11 ```window.Node``` is ```undefined``` on files loaded from the local file system.

It works on **localhost** it works on **plnkr** but when using **file** protocol it fails...

It took me a while to figure out.

**Comment by SalilLambe** [comment]
@ionut-ai @Pryscy i am still confused.. do i need to replace the buggy code

var jqLiteContains = window.Node.prototype.contains || /** @this */ function(arg) {
  // eslint-disable-next-line no-bitwise
  return !!(this.compareDocumentPosition(arg) & 16);
};

with if (typeof SVGElement.prototype.contains == 'undefined') {
        SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
    }  

or do it need to place it somewhere
