### ISSUE TITLE
ngAnimate applying transition style to element causes undesirable behavior

### ISSUE THREAD

**Issue by oste** [angular/angular.js#10281]
I am fading an element in when shown. The issue I am facing is that ngAnimate is adding ```transition``` style to the element. This is causing undesirable results because the element is given additional styles after this transition style is applied.

Here is a simple example showing how a small delay in adding ```height``` style will cause the height to transition as well. http://plnkr.co/edit/zeyoWWYfLlXcVMM67XiH

If this is the expected behavior how would I prevent the height from animating as well. Once again, the desired result is to only have the element fadeIn and not have the height transition.

Here is the line of code that adds the transition style I am referring to https://github.com/angular/angular.js/blob/master/src/ngAnimate/animate.js#L1915

Thanks!

**Comment by Narretz** [comment]
This actually doesn't happen in 1.4.9 anymore. (I don't know when exactly it was fixed)
