### ISSUE TITLE
Including CSS with a directive

### ISSUE THREAD

**Issue by Jon889** [angular/angular.js#10294]
It seems like it should be easier to include CSS with a directive, it would be great if the directive definition object had a cssUrl field so that you could do:

```
app.directive('myDirective', function () {
    return {
        templateUrl:'templates/myTemplate.html',
        cssUrl: 'css/myCSS.css',    
        link: function (scope, elm, attrs, ctrl) {

        }
    };
});
```

Then an link element would be inserted in the head with the href to the cssUrl URL.

**Comment by Narretz** [comment]
Duplicate of #15014
