### ISSUE TITLE
Combining attributes with expressions (e.g. ng-show conditions) in a directive with replace = true fails

### ISSUE THREAD

**Issue by koningskristof** [angular/angular.js#10323]
If both the div in the parent view does have a ng-show and the div of a directive with replace = true does have a ng-show, those conditions are bad merged.

Bug in action: http://jsfiddle.net/koningskristof/x69qwm8q/1/

**Comment by matsko** [comment]
@angrytoro the code that you posted is to prevent other animations from overriding the `hide` style when the `.ng-hide` class is present on the element.

**Comment by Narretz** [comment]
Essentially the same as #5695
