### ISSUE TITLE
bug(ngAria): ng-click adds keypress event to buttons which already fire a click event on "enter"

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#10388]
Originally discussed [here](https://github.com/angular/angular.js/pull/10288#issuecomment-66345338) in pull #10288 

 > Hmmmm. Looks like this introduces [a bug](http://jsbin.com/relejeguke/2/edit)? Looks like this is a problem in Chrome, Firefox, and Safari. Tab to the button (turns red) and hit "Enter" and the alert pops up twice. This is because (I believe) that the aforementioned browsers will fire a "clicked" event when the "enter" key is pressed.

Fix suggested by @marcysutton:

> Ahh, I see that. Good catch! It should only bind on a custom control that doesn't already have keyboard support. The approach used for adding roles in this PR would work:
> https://github.com/angular/angular.js/pull/10318/files#diff-91e9129201746ba107348c9a0a7735edR333

**Comment by marcysutton** [comment]
So I still haven't figured out how to test this in unit or end-to-end tests, but I was able to repro the original bug and see it fixed in a live demo: 

http://codepen.io/marcysutton/pen/ogYNPM

The fix proposed is to only bind the additional keypress event if the element is not a `<button>` or `<a>`. Are there any other elements we should be considering for this? Here is the proposed code change: https://github.com/marcysutton/angular.js/compare/ngaria-ngclick-bugfix 

If we're okay with this change going in without tests repro'ing the bug, I can submit a PR.

**Comment by caitp** [comment]
there might be other elements that need to be considered, I'm not sure. I'll look at writing a test for this after le meeting

**Comment by kentcdodds** [comment]
Thanks for your work @marcysutton. I'll look forward to upgrading when this fix is released! :D

**Comment by marcysutton** [comment]
We could also do it as an opt-in instead of an opt-out, and give people a config. Start with `<div>` and `<li>`, and let people add others. There was a request to add a better config for ngMessages: https://github.com/angular/angular.js/pull/9834#issuecomment-65970805

**Comment by marcysutton** [comment]
@caitp any update on that test? I've updated my code to be opt-in, so it only applies the keypress to DIV elements.

**Comment by caitp** [comment]
> @caitp any update on that test? I've updated my code to be opt-in, so it only applies the keypress to DIV elements. https://github.com/marcysutton/angular.js/compare/ngaria-ngclick-bugfix

I think I've long lost the branch I was working on for that. I'll have another go at it tomorrow, making a note to do that

**Comment by caitp** [comment]
> so it only applies the keypress to DIV elements. https://github.com/marcysutton/angular.js/compare/ngaria-ngclick-bugfix

Wasn't it opt-in before? based on the `bindKeypress` flag and the lack of a custom keypress handler. My understanding was that this was only needed for non-buttons (and one other thing?)

What are the correct semantics for this?

**Comment by caitp** [comment]
anyways, test PR sent that fails without your patch and passes with it, that should be good enough

**Comment by marcysutton** [comment]
It is opt-in in terms of the flag, but the `keypress` event is also bound for all elements with `ng-click` regardless of whether they needed it (resulting in two events on `button`). The common thing we're trying to fix with this is ng-click on `<div>`, which doesn't fire keypress by default. I think we should also consider adding `<li>` since people love to put `:hover` and `ng-click` on it.

If the [PR for adding roles](https://github.com/angular/angular.js/issues/10012) goes in, it should not add `role="button"` to `<li>` since those already have semantics. `<div role="button">` is pretty safe.

**Comment by marcysutton** [comment]
@caitp do you have a PR I can look at somewhere? I have submitted my code here: https://github.com/angular/angular.js/pull/10766

I added an array to the config so developers can change which elements receive keypress. I considered making a truthy `$aria.config('bindKeypress')` value the array itself, but to preserve backwards compatibility I opted to make a second config value that holds the array of element names: `$aria.config.keypressEls : ['DIV', 'LI']`. It can totally be renamed or changed if there is something that works better. The way it works now, the array will simply be ignored if `bindKeypress` is set to false.

**Comment by caitp** [comment]
@marcysutton I have a PR open aganst your ng-click fix branch

**Comment by caitp** [comment]
you'd have to pick out parts of it manually, it's just a suggestion to get a test in there, but it looks like you've got some now

**Comment by jorupp** [comment]
Not wiring in the keypress handling for `button` makes complete sense.  However, from my testing, an `a` tag with a `href` attribute triggers click when using the `enter` key, but *not* when using the `spacebar`.  Additionally, an `a` tag without an `href` attribute doesn't trigger `click` for `enter` or `spacebar`.

Am I testing this wrong, or should there be some handling for `a` tags for ng-click?

**Comment by marcysutton** [comment]
@jorupp a valid `a` already has a click event. This code is wiring up keypress events for elements that don't already have them, such as `div` or `some-button`. By filtering out `a` and `button`, we won't get duplicate events, which is the reason this bug existed. 

`a` tags require an `href` to be valid links, and they weren't the goal of this feature in ngAria. We could consider adding behavior to anchors without hrefs, but it should be in a separate Github issue.

**Comment by marcysutton** [comment]
Also you should really use `ng-href` and routing for `a` elements. If you're putting `ng-click` on an anchor and not using `href`, it should probably be a button.

**Comment by dylanb** [comment]
An anchor tag with an href (even an empty one) will fire a click upon an ENTER. That is accurate and expected. Button and input (type="submit", "button" or "image") will act the same as a button (fire click on ENTER or SPACE).
