### ISSUE TITLE
Empty hash at the end of URL causes page reload in HTML5 mode

### ISSUE THREAD

**Issue by dtritus** [angular/angular.js#10397]
For example, If I open `http://localhost/#`, page is reloaded to `http://localhost/`.

Looks like issue happens here: https://github.com/angular/angular.js/blob/master/src/ng/location.js#L882

When `http://localhost/#` loaded `$location.absUrl()` returns `http://localhost/` and `$browser.url($location.absUrl(), true)` called, which causes page reloading.

**Comment by petebacondarwin** [comment]
@dritus - would you like to try to fix this? We need a unit test the demonstrates the issue and then the fix, which is to strip empty hashes from the initialUrl before testing.

**Comment by dtritus** [comment]
I can try to fix this, but right now I don't have time.
