### ISSUE TITLE
Redirection causing infinite digest loop in old android versions

### ISSUE THREAD

**Issue by m3kka** [angular/angular.js#10405]
**Overview of the Issue**
Apparently this route configuration

```javascript
.when('/:test*.html', { redirectTo: function () { return 'test'; }});
```

is causing infinite digest loop in old android version (versions that require the hashbang mode to be enabled) with new versions of angular (problem appeared since we moved to 1.3.x).

The resulting URL should be 
`http://myBaseUrl/#/test` 
but we get something like 
`http://myBaseUrl/test#/test.html`

**Angular Version**
Tested on 1.3.6

**Browsers and Operating System**
Every browser that requires hashbang, ie, with an UA similar to:
`Mozilla/5.0 (Linux; U; Android 2.1; en-us; GT-I9000 Build/ECLAIR) AppleWebKit/525.10+ (KHTML, like Gecko) Version/3.0.4 Mobile Safari/523.12.2`

**Reproduce the Error**
http://jsbin.com/vifisu/1/edit?html,js,output
(Sorry Plunker is unreachable since this morning)

1. Open Chrome developer tools
2. Select old enough phone model (I used `Samsung Galaxy S, SII, W`)
3. Reload the page for the UA to be 'applied'
4. Click on 'Redirect' in the Output window
5. Check the browser console for the error

**Comment by julianjelfs** [comment]
Very disappointing that this keeps getting bumped. We are getting a great deal of errors caused by this regression.

**Comment by weases** [comment]
@julianjelfs yeah, same here

**Comment by mzgol** [comment]
In which Android versions is this a problem? The original report mentions Android 2.1, I don't think anything below 2.3 is in any way supported.

**Comment by julianjelfs** [comment]
I don't think it's actually anything to do do with android. It's any browser that falls back to hash bang routing. Its been broken for so long now that I don't believe anyone has any intention of fixing it.

**Comment by Narretz** [comment]
Closing as an old issue. It's likely that this has been fixed in later versions, or can be handled by setting a hashPrefix in the locationProvider. And Android 2.1 is not supported, should it be only a problem on these devices.
