### ISSUE TITLE
As of v1.3.6, "./" links have different (buggy?) behaviour

### ISSUE THREAD

**Issue by lukehorvat** [angular/angular.js#10412]
A link referencing `./` (root of current directory) has different behaviour in v1.3.6 than it did in v1.3.5. It used to reload the current page (making it ideal for a "reset everything" link), but it doesn't do that anymore. Is the new behaviour a bug or by design? 

Plunker: http://plnkr.co/edit/5OGa4p?p=preview (toggle the version of Angular to see the difference)

**Comment by petebacondarwin** [comment]
Still appears in 1.4.x.

**Comment by petebacondarwin** [comment]
This has a workaround by using `target="_self"` on the link in question.
