### ISSUE TITLE
Align behavior of deep $watch and $watchCollection

### ISSUE THREAD

**Issue by johnstrickler** [angular/angular.js#10426]
Deep $watch'es rely on angular.equals which ignore object properties that begin with '$'.  

Is there any reason $watchCollection can't follow this behavior too?  Currently, watch listeners are triggered when a property of an object is changed that begins w/ '$'.

**Comment by petebacondarwin** [comment]
I think I am in agreement with @caitp and @lgalfaso that we should actually change `angular.equals` but I am scared that this will break lots of apps.

**Comment by petebacondarwin** [comment]
Bumping to 1.4.x as this is not a regression preventing 1.4.0 release
