### ISSUE TITLE
Angular have problems with Object.prototype

### ISSUE THREAD

**Issue by Akxe** [angular/angular.js#10469]
The bug stated (and is **not yet fixed** as of 1.3.6) when upgraded from **1.3.0-rc.0** to **1.3.0-rc.1**. Sorry to report this late, but I couldn't figure it out.
The bug is easily reproduced by:
Object.prototype.x = function(){};

I think this is a bug, since prevent the user from using prototypes.

**Comment by Akxe** [comment]
I saw it is work in progress, I would like to ask how is it going... I can't really do much else

**Comment by enigma1** [comment]
I am not sure why this is a bug. From what I see you set the native prototype with an enumerable property. This means any object now has the property x and this property can be enumerated.
If you want to see the angular error try the equivalent:

```javascript
Object.defineProperty(Object.prototype, "x", {enumerable: true})
```

**Comment by caitp** [comment]
apparently someone had the brilliant idea to totally screw up the tree without asking anyone's opinion. So, new patch is up that accommodates this.

**Comment by Akxe** [comment]
I have updated plunker to 1.4.0-beta.0. http://plnkr.co/edit/ZDKnJJAOsng5dBlPv7s7?p=preview

**Comment by realityking** [comment]
Honestly, I don't think it can be expected that code work with enumerable properties on a built in prototype. Especially modifying ``Object.prototype`` can cause all kinds of "interesting" issues.

The easiest fix would be to declare the method in the following way:
```
Object.defineProperty(Object.prototype.x, 'x', {
  value: function(){},
  writable: true,
  configurable: true
});
```

**Comment by Akxe** [comment]
Well it is a working workaround, but forcing people to use different syntax isn't a really good solution to problem.

**Comment by realityking** [comment]
Just to be clear, this is a best practice (see for example [here](http://www.2ality.com/2011/07/js-properties.html)) and not specific to Angular. Extending ``Object.prototype`` is dangerous but extending it with a enumerable method is just asking for trouble.

To a lesser extend the same holds true for ``Array.prototype``, ``Date.prototype`` and all other build-ins.

**Comment by Akxe** [comment]
Allright, I'll redo it, but it should be noted in the docs too.
