### ISSUE TITLE
angular-i18n has wrong dateformat in Thai.

### ISSUE THREAD

**Issue by sixteenevils** [angular/angular.js#10503]
The fulldate format in **angular-locale_th-th.js** and **angular-locale_th.js** are wrong.
Current value is "fullDate": "EEEE\u0e17\u0e35\u0e48 d MMMM G y",

Example : <dd id="checkIn">{{landingViewModel.bookingInfo.checkIn | date : 'fullDate'}}</dd>
It will generate a date like this "วันพุธที่ 17 ธันวาคม G 2014", 
which the G letter should be "พ.ศ." if year is 2557 Buddhist Era (BE)
and for A.D. 2014 it should be "ค.ศ."
or you can remove the G letter it will correct as well.

**Comment by lvarayut** [comment]
Would it be possible to change year format from AD to BE? It might be very useful for a lot of people if there is an option in date filter to choose an era format.
