### ISSUE TITLE
$animate service requests unnecessary animation frames

### ISSUE THREAD

**Issue by dmcquillan314** [angular/angular.js#10506]
I'm creating a large collection of product-like objects and am noticing multiple performance issues when using a combination of ng-animate and any ng-* directive that has interaction with the $animate service. 

When inspecting the performance of the application on load of product cells I'm noticing a significant drop in performance when I have the ngAnimate module included:
![screen shot 2014-12-17 at 11 29 14 am](https://cloud.githubusercontent.com/assets/2671966/5475604/114bdf36-85e0-11e4-8c34-f9a50213e713.png)

On average for a collection of ~100 products loading at once this seems to be adding ~200ms to the load of the page.

Based on the angularJS documentation we should be able to do something like the following to disable animations on an element:
        ```
       $animateProvider.classNameFilter(/^(?!.*disable\-animations).*$/i);
       ```

which would disable the animations on an element such as this:
        ```
        <div class="some-element disable-animations" ng-if="condition">show/hide me</div>
        ```

However when I inspect the application I do see that the animate module disables the animation but it does not disable the request for an animation frame which is causing issues.  

From a bit a research into the animate module this seems to be the offending piece of code:
        ```
        //skip the animation if animations are disabled, a parent is already being animated,
        //the element is not currently attached to the document body or then completely close
        //the animation if any matching animations are not found at all.
        //NOTE: IE8 + IE9 should close properly (run closeAnimation()) in case an animation was found.
        if (animationsDisabled(element, parentElement)) {
          fireDOMOperation();
          fireBeforeCallbackAsync();
          fireAfterCallbackAsync();
          closeAnimation();
          return noopCancel;
        }
        ```

**Comment by matsko** [comment]
Hey @dmcquillan314. The call to requestAnimationFrame only happens after `animationsDisabled` is called. And if the function returns false then it shouldn't call it at all.

This is tricky to guess based on output. Would you be able tomorrow or next week to have a hangout so I can see a demonstration of this? It would speed up the debugging process.

**Comment by dmcquillan314** [comment]
Sure that wouldn't be a problem.  When is good for you?

**Comment by dmcquillan314** [comment]
After doing a bit more research on this issue I discovered that the issue has to do with the $$AsyncCallbackProvider:

``` js
function $$AsyncCallbackProvider() {
  this.$get = ['$$rAF', '$timeout', function($$rAF, $timeout) {
    return $$rAF.supported
      ? function(fn) { return $$rAF(fn); }
      : function(fn) {
        return $timeout(fn, 0, false);
      };
  }];
}
```

This is a problem since when the animations are "cancelled" in this call (offending methods are commented:
``` js
        if (!runner) {
          fireDOMOperation();
          fireBeforeCallbackAsync(); // triggers request
          fireAfterCallbackAsync(); // triggers request
          closeAnimation();
          return noopCancel;
        }
```
which is supposedly set up to cancel an animation but however the fireDOMCallback(animationPhase) method:
``` js
function fireDOMCallback(animationPhase) {
          var eventName = '$animate:' + animationPhase;
          if (elementEvents && elementEvents[eventName] && elementEvents[eventName].length > 0) {
            $$asyncCallback(function() {
              element.triggerHandler(eventName, {
                event: animationEvent,
                className: className
              });
            });
          }
        }
```
makes a call to the $$asyncCallback even when the animations have been disabled which transitively triggers the request for an unnecessary animation frame.  

A simple fix could be something as simple as checking to see if the animation was disabled before making the call to the asyncCallback method.  Or possible parameterizing the $$asyncCallback to support a disableRAF property.  

I'll keep doing more investigation and possibly open a PR shortly.

**Comment by matsko** [comment]
@dmcquillan314 sorry for falling off the map with this. For the last couple of months we've been building a refactor for 1.4's animations. That is now complete and merged in.

The callbacks and animation frame sequencing is completely different in 1.4 than 1.3. Would you mind testing it out to see if the issues still exist with the new code? There's not much we can do to improve things in 1.3, but 1.4 is far more powerful.

For some odd reason `code.angularjs.org/snapshot` hasn't updated yet with the latest commit on master. If you wait a bit later today until the RC comes out for 1.4 then you can test on top of that.

**Comment by dmcquillan314** [comment]
Sure, I'll test this later today or tomorrow and get back to you. Thanks for taking a look at this.

**Comment by matsko** [comment]
OK it's on `code.angularjs.org` now. Please use the files in here to test: https://code.angularjs.org/1.4.0-rc.0/

**Comment by dmcquillan314** [comment]
The issue still seems to be present.  The issue was not only present when animations are disabled, it also occurs when a regular element is directed to enter using the $animate module and there are no animations configured via CSS or JS for this element.  Let me know if you want to set up a time to discuss this further.

**Comment by Narretz** [comment]
I've inspected the performance of a list of 50 ng repeated items which each contain an ng-if and an input (which has a class based animation), and I couldn't see any sign of such an extreme number of requestAnimationFrame. This was in the snapshot, 1.4.x should be the same. If this issue is still relevant, please provide a demo that can be inspected.
