### ISSUE TITLE
Memory leak with $setValidity

### ISSUE THREAD

**Issue by dlongley** [angular/angular.js#10509]
If ```ng-model``` is used within a form and toggled with ```ng-if``` and ```$setValidity``` is called on the ```ngModelController```, then a memory leak occurs.

Specifically, the ```$setValidity``` call in ```ngModel``` ([line 3172](https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L3172)) adds a validity entry to the parent form controller that keeps a reference to the ```ngModelController```. There's nothing in place to remove this entry if that controller gets destroyed, so these references stick around. Worse, the ```$setValidity``` call is added to the ```ngModelController``` by creating a closure that wraps the ```ngModel```'s element, which can result in leaking quite a bit of memory in complex applications.

This [plunker](http://plnkr.co/edit/WJlfWnHzxsnVNWate7Gz?p=preview) demonstrates the issue by printing out the number of ```ngModelController``` references maintained by the form controller each time you toggle a form input off/on.

**Comment by manikantag** [comment]
Correct line number referred by @dlongley is in v1.3.7: https://github.com/angular/angular.js/blob/v1.3.7/src/ng/directive/input.js#L3172
