### ISSUE TITLE
$location.path() and $location.url() fail silently without html5Mode

### ISSUE THREAD

**Issue by s-d-p** [angular/angular.js#10505]
Angular v1.3.3...

After digging through the source, I figured out why `$location.path()` and `$location.url()` were returning nothing... html5Mode was not enabled. This is not well documented and no errors are thrown, so the result is a pretty big "gotcha".

Suggested fixes: 
* Clarify documentation to explain which of `$location`'s methods depend on html5Mode
* Log error or warning when they are called *without* html5Mode so the developer isn't left guessing

**Comment by pkozlowski-opensource** [comment]
@s-d-p what I've meant that if you look at the URL in non-HTML5 mode, ex.: `http://example.com/base/index.html#!/new?x=y` you can see that there are 2 parts of this URL-one before the `#` and one after.

In the non-HTML5 (hashbang) mode AngularJS will only interpret the part after the `#` (that is, `/new?x=y` here) and call to the `$location.path()` is going to return `/new` and not `/base/index.html`). Once again, this is all nicely explained here: https://docs.angularjs.org/guide/$location
