### ISSUE TITLE
One time binding config proposal/feature request

### ISSUE THREAD

**Issue by swirlycheetah** [angular/angular.js#10518]
I'm proposing adding a config option to be able to switch between one time binding being an opt in feature (as it is currently with `::`) and an opt out feature (e.g. you have to explicitly opt in if you want to watch a value for changes).

I envision the setting being implemented in a similar way to the `$interpolateProvider` config options (https://docs.angularjs.org/api/ng/provider/$interpolateProvider).

The benefits would include:

* No wasted watchers for values which never change unless explicitly set
* Improved performance (I'd presume(...?))
* The ability to change the current `::` syntax to a customised one (as with `$interpolateProvider.startSymbol` & `$interpolateProvider.endSymbol`)

Possible issues:

* Could be confusing for developers who join a project where one time binding is opt out but it isn't clear
* Would `::` still be the correct syntax if the defaults were switched?
* Should you be able to change the syntax if desired?

Would love to hear some thoughts and feedback on this proposal and whether it seems a logical feature to provide.

I'm certainly willing to implement the feature, I understand where the one time binding check takes place but would perhaps need some guidance in creating & reading a config option if that was seen as the correct way to implement.

//cc @rodyhaddad

**Comment by lgalfaso** [comment]
I feel that pushing one-time binding always can cause just too many issues. That said, I am sure that something like this can be implemented on an external module using decorators. Closing this as I see no point in making this part of the core
