### ISSUE TITLE
ngAnimate doesn't cleanup correctly when on root Element

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#10527]
When you have something like

```<body ng-app="myApp"></body>```

and do
```$animate.addClass(body, 'abc');```

the `ng-animate` class is not removed after the animation finishes. This is because cleanup has a special path if it's the root element: https://github.com/angular/angular.js/blob/master/src/ngAnimate/animate.js#L1512 
(Simple) animations work anyway, so it looks like a minor thing - although the default path does a little more stuff.

**Comment by matsko** [comment]
@Narretz this is fixed in 1.4 as of now. We should fix this in 1.3 however.

**Comment by Narretz** [comment]
1.3 is not worked on anymore.
