### ISSUE TITLE
Removing the cloned element which is transcluded destroys two-way binding in IE8

### ISSUE THREAD

**Issue by eight04** [angular/angular.js#10521]
Angular version: 1.2.28
[Demo](https://rawgit.com/eight04/end2end/master/test/ie8test.html)

I was testing in IE 11 emulation mode. No error was thrown.

After removing the cloned element by `.remove()` or `.empty()`, the view doesn't update anymore.

I found this bug during cloning a list. After removing the cloned list, the original list stopped working.

I guess it's a jQLite bug. If you use jQuery everything works well. Using native `.innerHTML = ""` works too.

**Comment by Narretz** [comment]
I am gonna close this, as 1.2.x is a legacy branch (the last one to support IE8) and only receives critical bug fixes.
