### ISSUE TITLE
ngOptions: non-grouped options shouldn't float to the top when using group by

### ISSUE THREAD

**Issue by tdakhla** [angular/angular.js#10531]
Example fiddle where non-grouped options incorrectly always float to the top: http://jsfiddle.net/raxzauyL/  (against 1.3.7)

The expected behavior is that the `options` should be interspersed between the `optgroups`, not bunched at the top.  I've tried setting the `group` by value to '', undefined, null, and even removing the key from the obj completely, but none seem to work.

**Comment by petebacondarwin** [comment]
This is fixed by #10639

See http://jsfiddle.net/su61n9m9/
