### ISSUE TITLE
ngAnimate doesn't trigger enter method on first page load

### ISSUE THREAD

**Issue by EEGL** [angular/angular.js#10536]
After upgrading to v1.3.8 ngAnimate doesn't trigger enter method on first page load.
I'm using Javascript based animations with the standard Angular Router. 

Like:
```
ngModule.animation('.an-reveal', function () {
    return {
      enter: function(element, done) {
        element.velocity('fadeIn', { delay: 300, duration: 600, complete: done })
        return function() {
          element.stop()
        }
      },
      leave: function(element, done) {
        element.velocity('fadeOut', { duration: 300, complete: done })
        return function() {
          element.stop()
        }
      }
    }
  })
```
and I have `<main ng-view class="an-reveal"></main>`

**Comment by lgalfaso** [comment]
from the comments, it is my understanding that there is nothing else to be done for this issue. If there is something else that needs attention, feel free to reopen the issue

**Comment by glebmachine** [comment]
year passed... 
This is still a problem, does anybody have any news?

**Comment by gkalpak** [comment]
@glebmachine, what news do you expect? Based on the comments, the conclusion was that this is working as expected, there is a way to change the default behavior if you wish and there is nothing more to do.

If you are having issues with latest versions, please open a new issue describing the problem (and please reference this issue for context).

**Comment by hejiaji** [comment]
@glebmachine The best way for now is using setTimeout as a workround

**Comment by glebmachine** [comment]
Yeah, looks fair.

I hoped that there is any option to trigger animation on element appear, but it's triggered only on change by design(

**Comment by oemueller** [comment]
Using this snippet animations are also played on page load:
`myModule.run(function($animate) {
  $animate.enabled(true);
});`
[Source](http://devdocs.io/angularjs~1.6/guide/animations)
