### ISSUE TITLE
using ngResource when property name starts with @

### ISSUE THREAD

**Issue by ronaldjeremy** [angular/angular.js#10533]
I have objects that have properties that begin with @.  Example "@itemID" (this from the BadgerFish convention of turning an XML document into JSON, so i need to stick with this namaing convention)

I cannot figure out how to get a configuration object that ngResource will accept.  For example i have tried:
$scope.menuResource = $resource(url + "/restapi/items/:itemID", {itemID: "@@itemID"});
and Angular will throw an error:badmember exception.

How can I escape the @ in the property name to get it to work with ngResource?

**Comment by gkalpak** [comment]
You can submit a [Pull Request][1] (including the fix and appropriate test-coverage).
For more details, take a look at [CONTRIBUTING.md#submitting-a-pull-request][2].

[1]: https://help.github.com/articles/creating-a-pull-request/
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-a-pull-request

**Comment by ronaldjeremy** [comment]
@gkalpak I am following your instructions on Pull Requests and it says i need to create a new branch -- but it does not appear i am allowed to create a new branch at https://github.com/angular/bower-angular-resource

It it something you have permission to do?

**Comment by gkalpak** [comment]
You need to fork the repo (the main `angular.js`, not `bower-angular-xyz`), create a branch on your fork, make the changes and submit a pull request against the original (forked) repo.

The process is discribed in more detail [here][1].

[1]: https://docs.angularjs.org/misc/contribute

**Comment by mustela** [comment]
Just pushed a [PR](https://github.com/angular/angular.js/pull/11473) for this one.
