### ISSUE TITLE
ngRepeat fails with sparse Arrays

### ISSUE THREAD

**Issue by cavanm** [angular/angular.js#10544]
ngRepeat iterates over the spaces in a sparse array. If the array is missing one element this leads to an extra element being created by ngRepeat. If the array has more than one element missing the ngRepeat fails because it sees the missing elements as duplicates. 

See Plunk: http://plnkr.co/edit/uvzROas6NHVzOzmfSoJi?p=preview

This is in contrast to the behavior of for(x in array) which only iterates over the elements that are actually present in the array.

Tested with angularjs 1.3.8.

**Comment by caitp** [comment]
I've got a patch for this... I think it will do things that people won't like though (particularly, making $index not representative of the original array index...).

I think this will also harm performance, so it's not ideal for anyone :(* But someone else can make the call on that.

**Comment by caitp** [comment]
i don't think e want to fix this, it does too many weird things to fix it. so basically just don't use a holey array

**Comment by syndicatedshannon** [comment]
I second that. I came here hoping it would be fixed so I could take a shortcut and avoid some other design issues, but it's not really necessary. Basically, my issue was I wanted to iterated objects uniquely indexed by a numeric id, and be able to retrieve that object from the same model later by its id. Handling numbers on as object property names is just a little messy so I was looking to avoid it. Ultimately, though, the id wouldn't have to be a number, it might be a GUID or other type. So trying to coerce the system to handle the number with less effort in my case would have been a short-term gain.

**Comment by felixcollins** [comment]
I have a situation where I need ng-repeat to ignore undefined entires in a sparse array. I'm populating the array asynchronously with items in a certain order.  The order is given by the index of an id in another array. I can't guarantee the order the array will be filled in but it will eventually be filled. My work around will be nasty as I'll have to figure out where it insert each item as it comes in rather than just putting it where it will eventually end up right at the start.

**Comment by petebacondarwin** [comment]
@felixcollins - how about you create an array with a "blank" placeholder in each of the entries. This will be repeated over correctly by the `ng-repeat` directive as an array. You can then put an `ng-if` directive in the template to not display the entry if it is a placeholder.

```html
    <div ng-repeat="item in items" ng-if="item.name">
      <h1>{{item.index}}: {{item.name}}</h1>
    </div>
```

See http://plnkr.co/edit/KpV0GOCtTZKDaCD9AJIJ?p=preview

**Comment by felixcollins** [comment]
@petebacondarwin Yeah that would work. Not the neatest solution though. I'd prefer that the view markup does not need to worry about foibles of ng-repeat. In my case the loading of items in the array is being done in a generic domain object service so every consumer of the service would have to remember to do that. The solution I went with was to insert the items into the array in the correct locations as they come in. Inefficient I know but we are probably never dealing with more than a few dozen objects.

**Comment by caitp** [comment]
if you need to deal with sparse arrays, and you're aware of the performance implications, why not fork the ngRepeat directive and publish it as a third party module, which will not transclude holes in the array? Doing this in core has a pretty profound impact on the benchmarks in the tree, for what it's worth

**Comment by felixcollins** [comment]
@caitp I believe you! Maybe instead of making ngRepeat handle sparse arrays it should throw an error or output a warning that makes more sense when it comes across one. That would be nicer for consumers of the framework than the "duplicate item 'undefined' " message currently returned. Just a thought.

**Comment by caitp** [comment]
Then we'd eat the same cost we'd eat handling sparse arrays

**Comment by felixcollins** [comment]
Oh right...   I guess I should really put my money where my mouth is and dig into the code myself! :-)
