### ISSUE TITLE
Putting a scope var in an input's `name` attribute adds the var name in 1.2.x

### ISSUE THREAD

**Issue by Saturn2888** [angular/angular.js#10546]
I went to 1.2 from 1.3 bc of IE8 compatibility and only one thing seems to be broken, custom name values on inputs.

For instance:
```
<form name="form">
    <input name="{{field.name}}>
</form>
```

This will cause the form object to have {{field.name}} added to it instead of whatever the value of field.name is.

To confirm, this works in 1.3, just not 1.2.

I tested 1.2.0, 1.2.10, 1.2.26, 1.2.27, and 1.2.28.

**Comment by yaffeweb** [comment]
I'm new to angular and I'm having a similar issue but backwards. It works in 1.2.28 but not in 1.3.8. Maybe something is different in these versions I'm not aware as the training I'm doing is using a legacy version. Here is my code:

<html ng-app>

    <script src="angular.js"></script>
    <script>
        function CostCtrl($scope) {
            $scope.cost = 1000.1;
        }
    </script>
</head>
<body ng-controller="CostCtrl">
    Cost: <input type="text"  ng-model="cost" placeholder="cost" />
<p>
    This is your cost: {{cost|currency}}
</p>
</body>
</html>
 When previewed in a browser, the {{cost|currency}} doesn't change to reflect the $scope it just stays the same. Is there a new say to use controllers that has changed between the version upgrades that I'm not away of?

**Comment by pkozlowski-opensource** [comment]
@yaffeweb - your problem has nothing to do with the issue discussed here - simply global controllers are not allowed any more in 1.3. Please make sure to check breaking changes section in the [changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md)

**Comment by yaffeweb** [comment]
Thanks for the reply, I will try to see if I can figure how to make this work the correct way

**Comment by Narretz** [comment]
Generally, we don't backport features to 1.2.x, so I don't think we should do it. Especially because workarounds exist.

**Comment by petebacondarwin** [comment]
I agree with @Narretz - we are not backporting features to 1.2.x.
