### ISSUE TITLE
nested svg directives doesn't work in FF (31.0) and Safari

### ISSUE THREAD

**Issue by YansongZang** [angular/angular.js#10553]
Hi all,

I'm trying to draw a gobang board with 'svg'.
My code on plunker: http://plnkr.co/edit/znkQzCZSPQnckrO4d6gY

It works as expected on Chrome. So if you run it on Chrome, you will know what I'm trying to do.
But somehow the 'gbCircle' directive doesn't render properly on FF.

Do I use directives incorrectly somewhere here? Or this is a bug?

Thank you my genius!

**Comment by Narretz** [comment]
I've tested this against Safari 9 and the bug is fixed. I doubt that we will fix it for Safari 8, but I'll leave it open anyway.

**Comment by Narretz** [comment]
Another year means even fewer people on Safari 8, so I'm closing this. ;)
