### ISSUE TITLE
ngSanitize linky filter incorrectly converts query key html entities to entity numbers.

### ISSUE THREAD

**Issue by KurtWagner** [angular/angular.js#10565]
URL query parameters like `&center=` have the `&cent` part converted to `¢`, which results in `¢er=`

For example:

```
'http://test.com/?arg=10&quote=10&center=10' | linky
```

Becomes

```
<a href="http://test.com/?arg=10&#34;e=10&#162;er=10">http://test.com/?arg=10&amp;quote=10&amp;center=10</a>
```

i.e, a link of

```
http://test.com/?arg=10"e=10¢er=10
```

See [jsfiddle](http://jsfiddle.net/4479b27v/). Similar issue when using `ngBindHtml` ([jsfiddle](http://jsfiddle.net/4479b27v/1/)). So I'm guessing it all comes down to `$sanitize` ([jsfiddle](http://jsfiddle.net/4479b27v/2/))

**Comment by caitp** [comment]
I was thinking we could use URLUtils or an anchor's href attribute rather than the pre, when dealing with URLs.

But there's a problem! (derp). https://www.w3.org/Bugs/Public/show_bug.cgi?id=26431 there's some unspecified and non-interop behaviour which breaks a few tests when done this way :(

**Comment by caitp** [comment]
I think ngSanitize is due for a rewrite.

The trouble is, right now it's really non-flexible, and it's hard to introduce flexibility here without also exponentially increasing complexity, and likely breaking many other parts.

I think it would be worth figuring out the various threat models that ngSanitize is meant to protect against, and make it deal with those specifically, without breaking usability

**Comment by kevinrenskers** [comment]
This is a huge issue for us. We have a chat application and now sometimes the links in messages simply don't work anymore. Users are unhappy and we don't really see a workaround. Is there anything we can do short term to solve this problem, short of disabling SCE altogether?

**Comment by kevinrenskers** [comment]
It seems that even disabling SCE doesn't work. Quick test: http://plnkr.co/edit/42b4KxSiPSR4qsoMF8oh?p=preview

**Comment by richterb** [comment]
What's the status on this issue? I can't even figure out a workaround in the meantime, apart from rewriting my own linky filter (ergh)

**Comment by lorenzhs** [comment]
This just crept up for us again (Glowing Bear, an IRC web frontend), and just like for @kevinrenskers it's a big deal for us as well. Multiple users have run into that issue now. Is there anything we can do about it?

**Comment by trisk** [comment]
Bad workaround suggestion: insert `&amp`

**Comment by kevinrenskers** [comment]
My workaround: I stopped using angular-sanitize and the linky filter. Too many problems. I am now using the [linkifyjs](https://github.com/SoapBox/linkifyjs) library with my own linky filter wrapping it.

**Comment by petebacondarwin** [comment]
`ngSanitize` got a big rewrite around 1.5 - is this still broken?

**Comment by gkalpak** [comment]
I tried with v1.7.4 and this issue has been fixed (somewhere along the way :grin:).
