### ISSUE TITLE
Log levels

### ISSUE THREAD

**Issue by hanifbbz** [angular/angular.js#10560]
Angular `$log` is a great debugging tool. However there is crucial feature of many popular logging APIs that it is missing: log levels.

After the application is stable enough, I would like to disable most of the log messages without actually going into the code and physically remove them.

Angular itself has a `debugEnabled()` which comes quite handy: https://docs.angularjs.org/api/ng/provider/$logProvider

However, at the moment there is no way to say:

* Show me only the error messages (omit warnings, info and log messages)
* Show me only warnings and errors

A typical log library allows you to specify what **level** of log you are interested to and only shows the log messages that have the requested level of seriousness that are prioritized like this:

1. Error
2. Warning
3. Info
4. Debug

It is understandable that since `$log` is merely a wrapper on top of `console`, it tries to stick to the API of the `console` but adding a function shouldn't ruin the whole idea. `console` itself has various "extra" function from browser to browser. Clearly it is possible to write a service that does that but I was curious to know if having it built-in to angular will empower it even more.

**Comment by lgalfaso** [comment]
as @novice3030 said, this is something planned for 1.4. There are also several issues just like this, so I am going to close this as a duplicate
