### ISSUE TITLE
new camelCase feature for ngAttr broken by jquery

### ISSUE THREAD

**Issue by jaawerth** [angular/angular.js#10572]
Hi!

I noticed this today: the new functionality for ngAttr allowing for camelCased attributes appears to be overridden when jquery is included on the project.

For example, `$scope.foo = '0 0 24 24'`, `ng-attr-view_box="{{foo}}"` without jquery becomes `viewBox="0 0 24 24` as expected, but when jquery is added to the code, it becomes `viewbox="0 0 24 24"`.

[Working plnkr (no jquery)](http://plnkr.co/edit/pOw538rss8P1YChSsWfQ?p=preview)
[Broken plnkr (with jquery)](http://plnkr.co/edit/IF4Eaj2fWvDBSpYdGuxV?p=preview)

I'll try and follow up with a PR if I can make time to dig into the code, but figured I'd get this reported in the meantime. Thanks!

**Comment by lgalfaso** [comment]
I do not have a specific implementation in mind (I am sure there are several ways to work around the jQuery limitation without making any change to the core using an external module/library). The one thing that I am sure about is that angular should not hack around jQuery.

I am going to keep this issue open a few more days to get some feedback

**Comment by caitp** [comment]
i think we should actually hack around jQuery here. this isn't a jQuery feature, it's an angular feature. the fact that jQuery breaks it just shows that our current implementation of the feature is broken.

**Comment by travissimon** [comment]
@caitp I've just encountered this 'in the wild' nearly a year later. Did you ever manage to look into this? I'm guessing by the elapsed time that I should work around this issue?

**Comment by kschaefe** [comment]
I changed my approach to add a $watch for my svg viewBox size and manually set the value using
`element[0].setAttribute('viewBox', newValue)`

Not a fan of having to resort to the low-level JavaScript DOM bindings.  What's the timeframe on this?

**Comment by bhantol** [comment]
I am having this same issue

**Comment by timmywil** [comment]
This seems to work now with jQuery 3.0: http://plnkr.co/edit/n7dKDitTeg8SgJQznCqs?p=preview

**Comment by mgol** [comment]
Yup, jQuery 3.0.0 has stopped lowercasing the attribute (due to no longer having to workaround old IE or keeping compatibility with jQuery 1.x). The ticket for that is https://github.com/jquery/jquery/issues/2914. I'm closing this issue then.
