### ISSUE TITLE
step attribute doesn't trigger validity classes

### ISSUE THREAD

**Issue by Mouvedia** [angular/angular.js#10597]
When you are using `step="1"` a float value enables `validity.stepMismatch`. This is not reflected by the ng classes on the input.
e.g.

    <input ng-model="example" type="number" step="1" />

steps to reproduce:

1. enter a float value
2. check `validity.stepMismatch` of the input (true)
3. check lack of ng-invalid class on the input

Affected version: 1.3.5

**Comment by jimmywarting** [comment]
Should work on date month week datetime datetime-local time range number

**Comment by mohitadwani** [comment]
+1
