### ISSUE TITLE
AngularJS 1.3 breaks if a scope property is an ES6 Set

### ISSUE THREAD

**Issue by mvolkmann** [angular/angular.js#10600]
We use Traceur on my project. traceur-runtime.js defines the ES6 Set class. The digest cycle makes a copy of all scope properties. This fails if any of them are Set objects. It blows up on line 327 in version 1.3.8. This is in the forEach function where it attempts to call forEach on a Set object.

**Comment by ilanbiala** [comment]
@caitp If I had a PR for ES6 Set equality comparison, would that be merged in?

**Comment by ilanbiala** [comment]
@caitp would the PR need to include Maps and other ES6 structures, or can we just start with sets and expand from there?

**Comment by caitp** [comment]
I think you (or whoever is interested) should wait about 2 weeks (minimum). At the meeting on monday I'm going to get feedback on a new strategy for community feedback, which will hopefully give us more information on how badly this feature is really needed. I think many of our users are not taking advantage of these features yet, but maybe I'll be surprised.

**Comment by ilanbiala** [comment]
@caitp currently I'm using ES6 sets in production with no transpilation, so it would be awesome to have support for this. Hopefully we'll also get a better way of giving feedback, too. Keep me posted about what comes out of the meeting. :)

**Comment by caitp** [comment]
@ilanbiala there is no question that there are a few people who would benefit, but consider:

1. there is a cost (in terms of code-size) to supporting it.
1. it's not available in most of our target browsers, without polyfills.
1. many of our users will not use it as they need to target older browsers, and do not use traceur or 6to5, so it may not provide a benefit for everyone.

it's something we can talk about, but we need to weigh all of these things and figure out the best thing to do

**Comment by ilanbiala** [comment]
@caitp yep it definitely isn't fully supported in Angular's supported browsers, but it is already in the last few versions of Chrome, Firefox, almost fully in Safari and iOS, and partially in IE11, so it is (same with Maps and WeakMaps) starting to become the first prevalent structure in evergreen browsers.

**Comment by caitp** [comment]
unfortunately people who need to support IE9 don't care a whole lot about things that M41 can do. But it's besides the point, we can get feedback, figure out how many people care about it, how much of a pain it will be to support, and how much it will upset people who don't need it, and we can weigh these things.

**Comment by ilanbiala** [comment]
Thanks for being open to it! Let me know if there's anything I can do wrt testing/reviewing if any code is put together.

**Comment by wesleycho** [comment]
Is this a particular issue anymore? Tracer is far behind the main used transpilers of TypeScript and Babel, and if it is doing something wrong, that would be a Tracer problem, not an Angular one.

**Comment by mgol** [comment]
Sets have a `forEach` method so I'm not sure if this issue is still relevant. If it is, please open a new one with a test case showing what breaks.
