### ISSUE TITLE
ng-repeat performance hit with big objects

### ISSUE THREAD

**Issue by pico7** [angular/angular.js#10616]
When I use ng-repeat with big objects I get a huge performance hit.

Example:
var largeObjects=[
    {
        id: 5151,
        title: 'test',
        logLines: [
            {
                id: 448,
                info: 'bla',
               // 50 more fields
            },
            // 10 of these objects
        ],
        // 50 more fields...with more arrays of arrays
    },
    // 60 of these objects
];

If i use the large objects and simply output the titles it runs allot slower than if I had a simple array of titles. Is this an expected behavior?

li ng-repeat="largeObject in largeObjects"
{{ largeObject.title }} 
li

// this outputs 60 titles and takes 1.4 seconds on my desktop.. to long on mobile, if I use a simple list of titles it appears right away. 

Thank you!

**Comment by lgalfaso** [comment]
Hi, what happens if you use "track by"?
>
>

**Comment by pico7** [comment]
I do use "track by" and there is no difference in performance.
Any other ideas why?
Thanks

**Comment by lgalfaso** [comment]
@pico7 can you create a plunker that shows this issue?

**Comment by pico7** [comment]
I don't see any differences, weither I use it or not the performance
remains the same. Doesn't "track by" improve long lists; should it also
improve short lists with fat objects.

Like i described initially when i move from fat to slim objects the
performance improvements are very significant. Where i notice the most is
on a mobile device; from 2+ seconds to instant.

**Comment by lgalfaso** [comment]
if you create a plunker that shows this issue, then I can take a look at it, but with just the information provided I cannot reproduce the slowness

**Comment by pico7** [comment]
I will have that for in you in the next 24hours
Thanks for your help

**Comment by pico7** [comment]
Hi Lucas,
I am running a huge application and have been trying to isolate a
performance issue, after a week of searching I really thought it all boiled
down with ng-repeat but I now realize *(after playing around with plunker)*
that it does not.

Sorry for wasting your time :)

Thanks for your help, keep up the good work!
