### ISSUE TITLE
Feature Request One Time Binding Manually Update

### ISSUE THREAD

**Issue by navneet77** [angular/angular.js#10614]
Hi I have an array of thousand items and I am binding it in an ng-repeat. I would like to use one time binding for performance reason however I need an option for the user to refresh this list so I cannot use one time binding as there is no way to manually update the list is I use one time binding.

It would be great if there is a function which can be used to manually update the dom for one way binding

**Comment by lgalfaso** [comment]
this is a duplicate of several other options. If you would like to see something now, there are several modules that provide a similar functionality. Eg https://github.com/kseamon/fast-bind
