### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by vgrazi** [angular/angular.js#10625]
The documentation and tutorials on AngularJS testing describe a sumptuous testing environment around Jasmine and Karma. 

However installing these leaves something to be desired. I have tried it on my office Windows 7 machine, and that was a disaster. I tried it on my own, but when Jasmine loads the angular.js files, it craps out with an error about unknown variable 'window'. 

I tried using Yeoman but that also failed. I thought the problem was the proxy server or local admin, but I got local admin rights for the install and I enabled the relevant url's in our corporate proxy server, but things failed around the installation of Phantom.

Assuming something further needed to be opened in the proxy server, I gave up and decided to try at home on my Mac. That ended in pretty much the same place, with the failed installation of Phantom, which I then tried manually to no avail.

Next I tried installing the angular seed master, but that also failed.

And bottom line, even after we get all this working, we still need to figure out how to hook it into Maven to run on Bamboo, so that the tests run but are excluded from the production builds.

Is it just me, or are millions of Angular users going through the same pain, and is there a tutorial for getting an angular environment up and running, including test directories and CI server integration?

**Comment by ilanbiala** [comment]
AngularJS testing is pretty confusing. Karma isn't as well documented as it could be for setup, and it doesn't seem very simple even after copying and pasting angular's karma configuration.

**Comment by pkozlowski-opensource** [comment]
@ilanbiala @vgrazi let's keep this discussion constructive and technical - instead of offering general impressions could you please narrow down problems to specific details in relevant projects? Otherwise this is not very actionable, I'm afraid. While it is true that setting up those tools / workflows requires some up-front effort it is impossible to improve things without more specific details.

**Comment by ilanbiala** [comment]
@pkozlowski-opensource here are some issues I'm noticing that are more specific to Angular's docs right now.

Angular is mostly tested through Jasmine, which is fine, but it would be nice to at least have one example of other popular frameworks like Mocha/Should etc.
Angular's docs don't show how the code should be set up. One of the most confusing things is how is `module('app')` possible in the test when there is no indication that the angular files are part of the test. How are they part of the test? Why just `module('app')` and not the standard `angular.module('app')`?

Just some thoughts off the top of my head.

**Comment by pkozlowski-opensource** [comment]
@ilanbiala AngularJS uses Jasmine and as such has all the code examples / helpers for Jasmine. While it is possible to run tests using other testing frameworks you won't benefit from all the helpers and we can't possibly maintain all the examples / helpers for all the popular testing libraries. This is something best tackled at the community level and we could assist if needed.

Regarding `angular.module` vs. `module` those are 2 different things:
* https://docs.angularjs.org/api/ng/function/angular.module - _declare_ module
* https://docs.angularjs.org/api/ngMock/function/angular.mock.module - _load_ a given module into injector created for tests

I know that there are new concepts / tools / workflows here but at the same time there are number of tutorials / books / sample projects covering those now.

**Comment by ilanbiala** [comment]
@pkozlowski-opensource I definitely wouldn't expect all but at least 1-2 examples would be nice for other frameworks just to show it's possible if necessary. The issue with tutorials and books is I find they get outdated pretty quickly with the quick release cycle Angular has, but some of them are really good and make up for some confusion in other parts of Angular.

**Comment by pkozlowski-opensource** [comment]
@ilanbiala well, yeh, resources get outdated so if you are really into using Mocha than I would suggest digging into it and then writing / maintaing your blog about it. We are really stretched maintaining all the current resources and we are not using Mocha on the daily basis so it would get as well.

@vgrazi I hear what you are saying but there are many items that are outside of AngularJS control (package managers, PhantomJS, CI servers etc.) and we can't possibly provide step-by-step instructions for all the combinations of technologies used. What is great about the large AngularJS community, though, is that probably there are other people using setups similar to yours and could give you a hand. This is why I would suggest contacting one of the support forums: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

I can see that you've opened another issue (#10624) which has more technical details, so let's move the discussion in there.

**Comment by vgrazi** [comment]
Not sure why you closed the issue. Did you move it somewhere else?

InfoQ <http://www.infoq.com> Java Queue Lead Editor
Twitter: @vgrazi
LinkedIn: www.linkedin.com/in/victorgrazi/
Java Concurrent Animated: http://sourceforge.net/projects/javaconcurrenta/
Skype: vgrazi2
Google Plus <https://plus.google.com/+VictorGrazi/>

**Comment by pkozlowski-opensource** [comment]
@vgrazi I've closed this as this issue, as it stands, its not very much actionable, see my [comment above](https://github.com/angular/angular.js/issues/10625#issuecomment-68636780).

#10624 has more details that can be eventually actionable, let's move the discussion in there.

**Comment by ilanbiala** [comment]
@pkozlowski-opensource using angular-mocks isn't very clear. Do I declare it as a module? Where do I put it in script order? Right now I keep getting this error when running karma:
```
TypeError: 'undefined' is not an object (evaluating 'angular.mock = {}')
  at /Users/Eytan/Desktop/hths-lunch/public/lib/angular-mocks/angular-mocks.js:17
```

The script comes after `angular.js` but before everything else. What else do I have to do...? The instructions skip over setting up the environment and go straight to the code.

**Comment by caitp** [comment]
these are the kinds of questions you can get instantaneous answers to in [#angularjs](http://webchat.freenode.net/?channels=angularjs), [stackoverflow]( http://stackoverflow.com/questions/tagged/angularjs), or just by reading code from some popular angular modules, like ui-router or bootstrap.

You don't need to at `ngMock` as a module dependency **if** you are using the helper function `window.inject()`, because that will automatically create an injector with the `ngMock` module.

**Comment by ilanbiala** [comment]
@caitp I looked at angular-seed and followed that structure, but I still get the error.

**Comment by caitp** [comment]
you will get better help if you host your code somewhere, but for now it is a friday night and time to do the other thing
