### ISSUE TITLE
Support for native template tag

### ISSUE THREAD

**Issue by Akxe** [angular/angular.js#10626]
Today I found nice tag useful for this kind of libraries. The template tag is great, that it won't parse it's contents. And it probably could be optimalized by browsers since it is suppose to be template, to be copied and reused.
Sorry if it support is done already, I couldn't find it in doc...

**Comment by pkozlowski-opensource** [comment]
@Akxe could you please elaborate how would you like AngularJS to support the `<template>` tag? " nice tag useful for this kind of libraries" is a bit vague...

**Comment by Akxe** [comment]
Well there should be support for that (possibility to use this) and I fought that it should be in the angularjs docs.

**Comment by pkozlowski-opensource** [comment]
@Akxe I'm sorry, but I really don't understand what you mean by "should be support for that (possibility to use this)". How would you like to use the `<template>` tag in your code? How would you expect AngularJS to handle it?

**Comment by Akxe** [comment]
As the specs says. It would use it to clone content parse it and add it to DOM.

**Comment by Akxe** [comment]
As http://www.html5rocks.com/en/tutorials/webcomponents/template/ says : " Security issues - encourages the use of .innerHTML. Run-time string parsing of user-supplied data can easily lead to XSS vulnerabilities."

**Comment by pkozlowski-opensource** [comment]
@Akxe I hope you've played already with the current version of AngularJS and you understand that it is special kind of animal when it comes to handling DOM - and the process is definitively not as simple as "parse it and add it to DOM" - rather AngularJS uses its own way of processing templates with the $compile service. So I'm not sure how a `<template>` tag would play here. At the end of a day the `<template>` tag itself is just a way of keeping an inert DOM in the document itself. It could be used to hold templates but how those templates are processed is completely up to the framework. 

The only thing that comes close to the `<template>` tag in the current version of AngularJS is https://docs.angularjs.org/api/ng/directive/script  

Now, I don't think there is anything actionable here in 1.x - Angular2 that is cooking [here](https://github.com/angular/angular) is going to use `<template>` tags, but then again, this tag is just a container.

The last thing - I'm not sure why you bringing "Run-time string parsing" and XSS issues here as in AngularJS templates are parsed to the DOM by a browser. If you are aware of any security holes in the current implementation please share them using this address: security@angularjs.org.

Going to close this one as I'm not sure there is anything actionable here.

**Comment by lgalfaso** [comment]
@Akxe the use of `<template>` was discussed several times. In all cases, the conclusion was:
* IE does not support it (as a *template* tag, it does as a custom tag)
* We will need to support both mechanisms anyhow
* We end up with two ways to do the same thing

This leaned most to think that the time is not right for `<template>` in 1.x, at least not now. As @pkozlowski-opensource wrote, Angular 2 is taking a fresh look at this problem and they are implementing templates using `<template>`
