### ISSUE TITLE
angular seed instructions broken?

### ISSUE THREAD

**Issue by vgrazi** [angular/angular.js#10624]
I downloaded the angularjs seed master, and am trying to run through the readme.md on my Macbook pro

Things do not run as specified, and in some cases I had to sudo to complete the instruction, and in other cases the directory needed to be changed. In some cases, nothing works.

Here's what I found:
bower install did not work as instructed. I had to do the following and that worked:
```
    sudo npm install -g bower
```
Then from the project root dir:
```
    bower install --allow-root
```
When I run 
```
sudo npm test
```
 that works, but when I run 
```
npm run test-single-run
```
 (with or without sudo) a browser comes up briefly, I get a quick flash of some red tests, and then the browser exits.

Further down the readme.md I do 
```
npm run update-webdriver
```
which never stops. I stop it manually and restart it, and I am told that it was already installed successfully, (thank you very much!)

Now come the real problems...
I am running npm start from the seed root dir. It is correctly running on port 8000.
I go to a different command shell and launch 
```
angular-seed-master$ sudo npm run protractor
```
That spits out the message
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
but times out after a few minutes with the message 
```
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1

angular-seed-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
      throw error;
            ^
Error: Timed out waiting for the WebDriver server at http://192.168.1.3:65067/wd/hub
    at Error (<anonymous>)
    at onResponse (angular-seed-master/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:87:11)
    at angular-seed-master/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:42:21
    at angular-seed-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
    at ClientRequest.<anonymous> (angular-seed-master/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:7)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)

npm ERR! angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 protractor script.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! cwd angular-seed-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     angular-seed-master/npm-debug.log
npm ERR! not ok code 0
```
Not sure where to go from here!

**Comment by vgrazi** [comment]
All of this might just be overkill. Instead of using the angular seed master, I wonder if there is a basic set of tools I can just move into place and have things run.

For example, I installed node, npm, and bower, karma and Jasmine, and I launched npm and see it is running. 

I  have a web-inf directory containing my angular html (and jsp pages). 

I set up a directory called spec and put a simple script there:
require("../angular/angular.min.js");
require("../main/myController.js");
require("../main/my-utils.js");
describe("blank test", function()
{
    it("blank unit test", function() {

    })
});

Now, this very simple basically empty test, crashes because the angular.min.js is missing "window", I presume because it is running outside of a browser environment.

If someone can address that point, I think I will be well on my way.

**Comment by Narretz** [comment]
Hi, can you please re-post this in the angular-seed repository? https://github.com/angular/angular-seed/issues

Regarding your second issue - you cannot use angular as a module, you can only use it in the browser. The angular-seed readme specifies how to run unit tests. Loading files is handled by karma, and you specify the files in the karma conf.
