### ISSUE TITLE
About scope.$eval 

### ISSUE THREAD

**Issue by jBox** [angular/angular.js#10636]
I get *value* from 
```
scope.$parent.$parent.$parent.$parent.$parent.$parent.$parent.$eval("abc")
```
but get *undefined* from 
```
scope.$eval("abc")
```
is that a defect?

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines;](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) these types of questions are ill-suited for GitHub. Thanks!

**Comment by pkozlowski-opensource** [comment]
@jBox it is impossible to say without a reproduce scenario and @lgalfaso is right that such questions should be directed to support forums. But there is no bug in AngularJS - you are probably having an isolated scope somewhere in the chain, see: http://plnkr.co/edit/XCNjEKonB4eAZqwxCZdX?p=preview

BTW:  if you've got `scope.$parent.$parent.$parent.$parent.$parent.$parent.$parent.$eval("abc")` in a real-life application than you are asking for trouble...
