### ISSUE TITLE
Load and bootstrap Angular within web worker without manually creating window and document objects

### ISSUE THREAD

**Issue by michalc** [angular/angular.js#10635]
It is currently (Angular 1.3.17) possible to load Angular, and bootstrap a module within a web-worker, but it needs `window` and `document` with a few stub properties/functions that Angular assumes is in place. The following example is in `worker.js` and loaded by `new Worker("worker.js");`

    // Angular needs a global window object
    var window = self;

    // Skeleton properties to get Angular to load and bootstrap.
    self.history = {};
    var document = {
      readyState: 'complete',
      querySelector: function() {},
      createElement: function() {
        return {
          pathname: '',
          setAttribute: function() {}
        }
      }
    };

    // Load Angular: must be on same domain as this script
    importScripts('angular.js');

    // Put angular on global scope
    angular = window.angular;

    // Standard angular module definition in separate file (so can be loaded by Karma/other test runner)
    importScripts('worker-app.js');

    // No root element seems to work fine
    angular.bootstrap(null, ['worker-app']);

I suspect Angular should itself support being loaded in the web worker environment, so it doesn't need `window` / `document`, and can just use `self` (perhaps then injectable as `$self`?).

**Comment by lgalfaso** [comment]
I think it might be possible to load angular in a web worker. Maybe if you explain the issue that you are having, it would ease things up

**Comment by michalc** [comment]
Ah sorry I was unclear. Yes, it is possible, but only if you create the window and document objects in the global scope as in the code in the issue. If this isn't done, at various stages in the loading/bootstrapping process, exceptions are thrown due to undefined objects/properties.

It seems a bit hacky to have to do this, so my issue/suggestion is that Angular should support being loaded without window and document being present in the global scope. The web worker environment has `self` as the global object, so Angular could use that, and then test for the presence of document when required?

**Comment by lgalfaso** [comment]
Hi, I would like to know is what are you trying to achieve by loading
Angular in a web worker. This is, why do you need this
>
>

**Comment by michalc** [comment]
I'm writing a Javascript JPEG decoder (yes, I know others exist), and the bulk of the processing is done in a web worker. Doing it in Angular service(s) allows me to use the dependency injection system, $q, and unit test the worker code much like any other service. It would also (I suspect, I haven't needed to so far) allow code, as Angular modules, be used in both the worker and UI environments.

**Comment by lgalfaso** [comment]
I created a minimal patch that would make angular boot inside a web worker. You can find it at https://github.com/lgalfaso/angular.js/commit/acd3e479d737d6f3a1bd8c0ec0f2587daf42d5f8. There are several things that I doubt that they will work as expected (eg `$location`, same origin `$http`, cookies)
Now, I doubt that will get a lot of traction, but will let @petebacondarwin decide

**Comment by Narretz** [comment]
We've recently removed all direct references to window but you still need to provide a window object with a functional document. I don't think there are plans to make angular 1.x fully "universal".
