### ISSUE TITLE
angularjs automatically bootstrapping not working when navigate to page

### ISSUE THREAD

**Issue by Mirodil** [angular/angular.js#10643]
Angularjs doesn't automatically bootstrapping when newly navigate to page from other pages. if refreshing page angularjs automatically bootstrapping the app. For example:
```html
<html ng-app="app">
....
</html>
```

if we navigate from `/`(static page) to `/login`(login page is building with angularjs) angularjs doesn't bootstrapping but if we refresh this page '/login' then it bootstrapping the app.

**Comment by Narretz** [comment]
Are `/` and `/login` served by the server and if so do they resolve to the same file / different files? Or do you handle the routing with Javascript?

Are there any errors logged in the console?

And can you provide a reproduction of this issue?

**Comment by Mirodil** [comment]
`/` and '/login' are served by the server and they are different files. There is not any error in console.

**Comment by pkozlowski-opensource** [comment]
@Mirodil this info is not enough and we can't fix issues that we can't reproduce. Please prepare a minimal, runnable reproduce scenario using plunker, jsbin or similar.

**Comment by Narretz** [comment]
I am gonna close this issue due to lack of response - feel free to reopen once you can provide a reproduction.

**Comment by Mirodil** [comment]
As far as I can see, it depend from hostname. if `localhost:3000` the app does not bootstrap every time, if `127.0.0.1:3000` the app bootstraps as expected.
