### ISSUE TITLE
Highcharts directive inside ng-repeat

### ISSUE THREAD

**Issue by qbdpwereq** [angular/angular.js#10648]
I am trying to insert line graphs within each day cell of a month-view calendar. The calendar itself is a pure Angularjs implementation rendered with ng-repeat. Inside ng-repeat, I have the Highcharts directive instantiated, so presently, each cell gets the same data points for the chart as follows:

<div ng-repeat="day in monthGrid" class="{{day.css}}"  >
 <div class="dayHead" ng-bind="day.dateTitle"></div>   
 <chart options="sparkline.options" default="{{sparkline.default}}"></chart>
</div>
The data for the sparkline comes in from 'options'. My question is, how could I render separate data for each day cell based on the 'dateTitle'?

**Comment by arpit2438735** [comment]
Can you show some code what you tried so far? It's not the right place to issue a bug ,it's specific to high chart which angular doesn't provide.Please bug a issue/concern to [Stackoverfow](http://stackoverflow.com/)

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines;](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) these types of questions are ill-suited for GitHub. Thanks!
