### ISSUE TITLE
How to get the scope which is outside of the form directive

### ISSUE THREAD

**Issue by akshath4u** [angular/angular.js#10650]
Hi,

There is one scenario where am accessing a ngModel value inside a form directive but the parent scope is not getting inside this form directive. How can i access the parent scope inside this form. The code look like below,
<html>
       <form>
      </form>

       <form sf-schema="schema" sf-form="form"> {{$scope.customVal}}</form>

</html>

In the above code sf-schema is an directive used for dynamic form building, $scope,customVal which is defined inside parent scope. While am trying to print the value of parent scope inside form directive its not getting accessed. So what is the reason behind this issue. Could anyone help me to sort out this issue.

Regards,

Akshath

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines;](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) these types of questions are ill-suited for GitHub. Thanks!
