### ISSUE TITLE
Rules for Angular route variables

### ISSUE THREAD

**Issue by pidupuis** [angular/angular.js#10654]
Hi everybody,

Is there a way to add constraints/rules/check on route variables before loading page ?

For instance, in my case, I have several distinct databases (with same structure) and I want my interface to use one according to user selection.
For example: the routes /db1/search and /db2/search will display the same form page, but the first one will talk to database db1 and the second to db2.
So I created the dynamic route /:db/search and I use the route param db to know which database to use.

However, I don't know how to prevent the user to try /db3/search while db3 does not exist.

I could handle the server error obtained by trying db3 and display a smooth message but that's not what I want. I would prefer an automated check on client-side for every page (not only those with a server request...).

In a way my route verification problem is similar to an authentification verification problem so I looked around $routeChangeStart events, and also $routeProvider resolve function. That's a solution but if I could simply say "The route param db should be 'db1' or 'db2'" it would be perfect.

Thanks in advance for your help!

**Comment by arpit2438735** [comment]
Wrong place.If you have issue specific to angular.js implementation bugs, then only file it to this forum

**Comment by lgalfaso** [comment]
Hi, please use StackOverflow or some of the forums about questions. Please read the [contributing guidelines;](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) these types of questions are ill-suited for GitHub. Thanks!
