### ISSUE TITLE
ng-attr-title problem with me

### ISSUE THREAD

**Issue by mario56** [angular/angular.js#10666]
Code:
1.Jade code  : span(ng-bind="hips.description" ng-attr-title='{{hips.description}}')

2.Html code in browser:

![f87f8421-ad98-49c9-9287-c764da3e1752](https://cloud.githubusercontent.com/assets/7720722/5642776/67d68274-968a-11e4-9d0f-4013ab83dd3d.png)

Problem:
1.On mac os, in chrome browser, it show like this: 
![fadad291-4054-40ae-86d0-ac6fa0598b23](https://cloud.githubusercontent.com/assets/7720722/5642728/923ef07e-9689-11e4-8aa7-2f2fb07d58aa.png)
 

2.On ubuntu 14.04. in chrome browser ,it will show like this:
![bd1aa4c1-466c-476c-8b67-e475ffb06572](https://cloud.githubusercontent.com/assets/7720722/5642736/aa0cb330-9689-11e4-9188-a7d4d0a53337.png)

**Comment by Narretz** [comment]
Is the title attribute correctly set? (You can check this in the developer tools). So far, this could simply be a display bug unrelated to angular.

**Comment by mario56** [comment]
I not set the title attribute.only ng-attr-title attribute.Bunt on ubuntu 14.04. in firefox browser ,it will show OK.

**Comment by mario56** [comment]
![780f439a-5171-42a3-8803-e9e3c786bf6f](https://cloud.githubusercontent.com/assets/7720722/5643901/a10015de-9698-11e4-8a81-d0376e045dfa.png)

**Comment by mario56** [comment]
use the developer tools in elements tab ,I got the same code with title attribute..

![](https://cloud.githubusercontent.com/assets/7720722/5642776/67d68274-968a-11e4-9d0f-4013ab83dd3d.png)

**Comment by mario56** [comment]
in the span has one style->overflow:hidden

**Comment by Narretz** [comment]
What happens when you don't use angular and set the title directly? Is it then displayed correctly?

**Comment by mario56** [comment]
I try span(title='ssssssssssssssssssssjjjsss') test.It not displayed correctly

**Comment by Narretz** [comment]
Then this doesn't seem to be a problem with angular, but rather with your html code or with Chrome on Mac. I'm gonna close this issue.
