### ISSUE TITLE
one-time binding ng-options

### ISSUE THREAD

**Issue by jhudzik** [angular/angular.js#10687]
According to docs, when using a directive that takes an expression, we are able set one-time binding as so:
`<ul>
  <li ng-repeat="item in ::items">{{item.name}};</li>
</ul>`

However, this doesn't seem to work with ng-options, tried (1.3.0 - 1.38)
`ng-options="o as o for o in ::things"`

If I place ::things in a binding it works. 
`ng-options="o as o for o in {{::things}}" `

**Comment by lgalfaso** [comment]
can you please create a plunker that shows this issue? Thanks!

**Comment by jhudzik** [comment]
http://plnkr.co/edit/AklGzbtB3TsjfuPA0L6M?p=preview

**Comment by lgalfaso** [comment]
Ok, I am able to reproduce this and know what is wrong

**Comment by AliAdravi** [comment]
Why cannot we use
ng-options="::o as o for o in ::things"
It is working for me.

**Comment by petebacondarwin** [comment]
I am not sure if this will provide a performance benefit as the expression `things` will continue to be evaluated, even though the actual option expression is one time bound.
