### ISSUE TITLE
$q always calls $exceptionHandler on throw, even if the exception is handled

### ISSUE THREAD

**Issue by bluepnume** [angular/angular.js#10683]
Please see the following:

https://github.com/angular/angular.js/blob/master/src/ng/q.js#L323

This means the exception in the following code will be handled in two different places, assuming I have defined an `$exceptionHandler`:

                        $q.when().then(function() {
                            throw new Error('doowop');
                        }).catch(function(err) {
                            console.log(err.toString());
                        });

This makes it very difficult to catch errors in the correct places, and not have the global exception hander kick in...

**Comment by pkozlowski-opensource** [comment]
@bluepnume yeh, this is unfortunate, we are aware of the thing, there is a duplicate issue: #7992
I'm going to close this one as a duplicate, let's centralise the discussion in  #7992
