### ISSUE TITLE
Extend form directive / ng-model to allow focus state

### ISSUE THREAD

**Issue by hrodic** [angular/angular.js#10682]
I had the need to add a "focused" class in every form of my application when any of their internal inputs/selects.. had the user focus. Also to remove the class when no elements had the focus.
The idea is, that using CSS selectors and only one form class, you are able to change the opacity of all the other elements so the customer gets focused on what is doing.

I am pretty new to AngularJS (1-2 months), so i expect to have found a sub optimal solution for the problem although it worked. I basically decorated formDirective and ngModelDirectives.

```javascript
app.config(['$provide', function ($provide) {
			$provide.decorator('formDirective', ['$delegate', '$animate',
				function ($delegate, $animate) {
					var compile,
							FOCUSED_CLASS = 'focused',
							directive = $delegate[0];
					compile = directive.compile;

					directive.compile = function (tElement, tAttrs) {
						var link = compile.apply(this, arguments);
						return {
							pre: function (scope, element, attr, controller) {
								// execute directive native pre
								link.pre.apply(this, arguments);
								// extend
								controller.setFocused = function () {
									controller.focused = true;
									$animate.setClass(element, FOCUSED_CLASS, '');
								};
								controller.setUnfocused = function () {
									controller.focused = false;
									$animate.setClass(element, '', FOCUSED_CLASS);
								};
							}
						};
					};

					return $delegate;
				}]);

			$provide.decorator('ngModelDirective', ['$delegate', '$rootScope', function ($delegate, $rootScope) {
					var directive, compile;
					directive = $delegate[0];
					compile = directive.compile;

					directive.compile = function (tElement, tAttrs) {
						var link = compile.apply(this, arguments);
						return {
							pre: function (scope, element, attrs, ctrls) {
								// execute directive native pre
								link.pre.apply(this, arguments);
							},
							post: function (scope, element, attrs, ctrls) {
								var formController = ctrls[1];
								// execute directive native post
								link.post.apply(this, arguments);
								// extend
								element.on('focus', function () {
									if ($rootScope.$$phase) {
										scope.$evalAsync(formController.setFocused);
									} else {
										scope.$apply(formController.setFocused);
									}
								});
								element.on('blur', function () {
									if ($rootScope.$$phase) {
										scope.$evalAsync(formController.setUnfocused);
									} else {
										scope.$apply(formController.setUnfocused);
									}
								});
							}
						};
					};
					return $delegate;
				}]);
		}]);
```

**Comment by Narretz** [comment]
Hi, this is something that was proposed a few times, although mainly aimed at setting `$focussed` on the ngModel element itself (see e.g. https://github.com/angular/angular.js/pull/10215), but it was decided that the costs of having this in core outweigh the benefits (since every focus causes another digest).
I like your solution - for the ngModel decorator it's also possible to not use decorators, but rather a custom directive that adds the eventListeners. So you can decide on a per case basis if you want the state or not.
I'll leave this open for other opinions, as I quite like the idea of having this customizable.

**Comment by lgalfaso** [comment]
I see this as an interesting functionality, but not for the core. A third party module would be ideal

**Comment by hrodic** [comment]
Thanks for the input, indeed the $apply on every event seems an unecessary overhead for the core since this is an optional feature. I also like your idea of the customizable directive, and based on the #10215 discussion, there might be some issues also having to add the directive in every input, so probably a form-level directive that adds listeners automatically could be another option.

**Comment by lgalfaso** [comment]
as said before, I find this to be an interesting functionality, but not for the core. If would would still like this to be part of the code, there will be a new process next week for proposals. In the meanwhile I will close this issue
