### ISSUE TITLE
Access id of element from within ng-class.

### ISSUE THREAD

**Issue by ambrt** [angular/angular.js#10691]
How to access id of the html element from within ng-class?

**Comment by caitp** [comment]
you can't (unless, you've put the id of the element in scope somewhere, in which case you can).

This was an easy one =)

If you're interested in proposing this as a feature, should rename the issue to reflect that. I've got a scheme for proposing new features and getting feedback from the rest of the community, which I hope to launch next week, so you can be filled in on details in a bit

**Comment by caitp** [comment]
@pkozlowski-opensource I don't think people are likely to need it, no

**Comment by pkozlowski-opensource** [comment]
@caitp agreed. Let's wait and hear from @ambrt on his functional use-case - maybe there is something that we can do better. If we don't hear back from him we are going to close this as won't fix.

**Comment by ambrt** [comment]
Compare two example:
    ```<div  id = "my1" ng-class="{active: myMethod( 'my1' )}"> lorem...</div>```
and
    ```<div  id = "my1" ng-class="{active: myMethod( this.id )}"> lorem...</div>```

In first example if i will change id then i would have to also  change the string i pass to myMethod, 
because its hardcoded.
In second example i can change id and the ng-class will use it automatically.

**Comment by pkozlowski-opensource** [comment]
@ambrt we understand _what_ you are trying to do (technically speaking), we just don't understand _why_ (functionally speaking). In both your examples `my1` is static, it is just provided as part of a different attribute. But it really doesn't change much - I mean - those are still just strings being part of HTML on the same element.

BTW: `this` doesn't reference a HTML element but a scope. 

It would be easier to help you if you could explain what is a functional problem you are trying to solve here.

**Comment by ambrt** [comment]
It doesn't change much. I agree. The one reason for having it dynamically is code re-usage. By coping whole base page to new project i would have edit code for each differently named ids, twice (once for id and once for element in myMethod()).

I'd like to thank you for taking time to answer this. Maybe i'd ask if it would take too much time or effort to make such feature. If it would,  then i accept it - you got more important things to do. But if its not, maybe someone besides me would use it, down the road.

Regards

**Comment by pkozlowski-opensource** [comment]
@ambrt it is not about time it would take to implement - it is just that driving expressions based on DOM properties goes against the very nature of AngularJS where we want to drive displayed DOM from the JS model and not other way around.

The way of removing code duplication in HTML would be to write a custom directive where you are free to encapsulate repeating parts of HTML.

I'm going to close this issue as I don't think we want to allow DOM properties as part of AngularJS expressions.
