### ISSUE TITLE
Included Karma breaks the build on Node 0.11.14

### ISSUE THREAD

**Issue by mzgol** [angular/angular.js#10699]
Karma from @vojtajina's fork had to be forked before https://github.com/karma-runner/karma/pull/1182 landed which means currently Angular can't be tested on Node 0.11.14.

Node 0.12 is supposed to [ship soon](http://blog.nodejs.org/2014/12/05/listening-to-the-community/) so it'd be good to update the fork.

**Comment by vivekimsit** [comment]
+1 Hi facing the same issue on my local.

**Comment by mzgol** [comment]
This has been fixed recently, now Karma 0.12.32 is included.
