### ISSUE TITLE
select ng-options not selectable

### ISSUE THREAD

**Issue by Bakhrom** [angular/angular.js#10704]
if html header script tags ordered as below:
&lt;script type="text/javascript" charset="utf-8" src="jquery-2.1.1.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" charset="utf-8" src="angular-v1.3.8.js"&gt;&lt;/script&gt;
select options not selectable

if script tags ordered as
&lt;script type="text/javascript" charset="utf-8" src="angular-v1.3.8.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" charset="utf-8" src="jquery-2.1.1.js"&gt;&lt;/script&gt;
select working properly

**Comment by pkozlowski-opensource** [comment]
@Bakhrom changing order means that jQuery is used or not - in the second case jQuery is not used by internal AngularJS functions. This gives us some info but we still don't know what is your exact scenario where this bug occurs. Could you please share a reproduce scenario using plunker, jsfiddle or similar?

**Comment by Bakhrom** [comment]
@pkozlowski-opensource I'm sorry, when rename a variable I broke local JQuery, so the selectbox stopped working. Now I replaced jQuery, works, thank you.

**Comment by pkozlowski-opensource** [comment]
@Bakhrom ok, cool. Does it mean that this issue can be closed now?

**Comment by Bakhrom** [comment]
Yes, of course.
