### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by jesselpalmer** [angular/angular.js#10709]
Any plans to store HTTP status codes as constants in Angular?

**Comment by pkozlowski-opensource** [comment]
Do you mean something like https://github.com/jshttp/statuses/blob/master/codes.json ?

No, I don't think we want to add this to the core - this would increase library size adding info that is readily available elsewhere.

Why would you think it is useful as part of the core?

**Comment by jesselpalmer** [comment]
Just for convenience really. Yes, I don't want to add more code in the library than we need to. I was just curious to see if there were any plans to add them. Thanks @pkozlowski-opensource.
