### ISSUE TITLE
Multiple inheriting scopes on a parent scope will all share the same scope

### ISSUE THREAD

**Issue by bcherny** [angular/angular.js#10702]
I would think that they should each have distinct scopes that are children of and inherit from the parent scope, and are siblings of one another. Instead, they both share the same inheriting scope!

Is this my misunderstanding of Angular, or a bug?

Plunkr here: http://plnkr.co/edit/RMzvF7l7ijuqhRXPdt1F?p=preview

**Comment by caitp** [comment]
technically that's supposed to be an error, you're not supposed to be able to have 2 directives on a single element that create a new scope. It should throw :) But, we've had trouble making it throw consistently, so mostly it only does that if there are new + isolate scopes

**Comment by bcherny** [comment]
got it. what's the rationale behind not allowing this? in my mind this is similar to:

```js
<foo>
  <bar>
    {{ fooVar }}
  </bar>
</foo>
```

In that it's ambiguous where `fooVar` comes from (from `foo` or from `bar`?). This behavior is allowed, so why not allow multiple inheriting scopes on a single element?

**Comment by frfancha** [comment]
@ bcherny
2 directives on the same element are not at all similar to one directive containing the other one.
In this later case, described in your last post, fooVar as you say is not ambiguous: it follows the rule from javascript prototype, no more than that (read from bar if it exists in bar, otherwise try foo, and when write do in bar than foo.fooVar (if any) is hidden)
If both directives are on the same element; then it is impossible to make 2 inheriting scopes, exactly for the reason you describe in your last post: which one would be the context of the angular expressions contained in the element?
Fred

**Comment by bcherny** [comment]
If both directives on an element use inheriting scope, they would not be able to inherit from each other (because they are siblings). Because of that, resolving a variable name in a directives scope would follow the same process as you described.

**Comment by frfancha** [comment]
@bcherny 
No: if sibling scopes would be created there is no rule/process to know what scope to use in the "zone" covered by both scopes. This is why angular doesn't create sibling scopes which would be impossible to use, but instead share the newly created inherited scope between the directives asking for inherited scope when several of such directives exist on the same element.
(The process I describe earlier is used for embedded scope and not at all for sibling one, again if sibling would exist, there is no possible logic process to know which scope to use)
(And calling that a process is a big word, that's just plain simple javascript inheritance)

**Comment by bcherny** [comment]
Ah, that makes sense. Thanks for the explanation! What if the directives use a `controllerAs` syntax - would that solve the ambiguity issue?

**Comment by petebacondarwin** [comment]
I think that you would find `controllerAs` helpful for removing the ambiguity of where a property on the scope is coming from. We are not going to implement sibling scopes (other than because of transclusion) on a single element.
