### ISSUE TITLE
Can't update angular view from legacy code

### ISSUE THREAD

**Issue by liadlivnat** [angular/angular.js#10715]
I'm facing the following problem

broadcast event from legacy code.
use $scope.$on for getting the event.
the event call api method that resolve new data.
update the view result in - nothing happens.
I used all the technique i was able to find:

$scope.$apply - was resulted in $digest is already in progress
used $timeout function, nothing happens
used scope apply inside $timeout - nothing happens.
I'm not sure what to do if someone can help i appreciate it.

this is the code:

```
var injector;
angular.element(document).ready(function() {
    injector = angular.bootstrap(document, ['myApp']);
});
```

on javascript legacy code:
```
function sendRefresh()
{
    injector.invoke(['CommonService', function(CommonService){
        CommonService.broadcast_from_legacy('refresh-content');
    }]);
}
```
on controller:

```
$scope.$on('refresh-content',
            function () {
                $scope.refresh_data(true);
            });

$scope.refresh_data = function()
        {
            CommonService.get_homepage_from_server().then(function(result_data){
                $scope.messages = result_data.messages;
            });
        };
```

i see the function is getting called, the new data arrived, but the view is not refreshed.
I tried also:
```
$scope.refresh_data = function(shouldApply)
        {
            CommonService.get_homepage_from_server().then(function(result_data){

                if (shouldApply == true)
                {
                    $timeout(function() {
                        $scope.$apply(function(){
                            $scope.messages = null;
                        });
                    });
                }
                else
                {
                    $scope.messages = result_data.messages;
                }
            });
        };
```
and:

```
  $scope.refresh_data = function()
    {
        CommonService.get_homepage_from_server().then(function(result_data){
            $timeout(function() {
                $scope.messages = result_data.messages[0];
            });
        });
        };
```

result_data can be anything you like, it's not really matter cause i tried to set even null there, null should break the view and it didn't effect, didn't do anything.
.
If anyone have an idea why my angular actions are not effecting anything, when i trigger the actions from legacy code, please let me know.

**Comment by lgalfaso** [comment]
Hi, please use the forums and StackOverflow for [these kind of questions](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)

**Comment by liadlivnat** [comment]
it's an angular bug, i already post it on stackoverflow.

**Comment by lgalfaso** [comment]
@liadlivnat I do not want to be harsh, but from the description it looks like you are having difficulties using Angular, and not reporting a bug. If you still think this is a bug, please follow [these guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue)
