### ISSUE TITLE
input[time] renders with milliseconds if the browser does not support time input

### ISSUE THREAD

**Issue by chris-rock** [angular/angular.js#10721]
Whenever a browser does not support input[time] natively, angular falls back to text field. It renders nicely in Chrome (e.g. 07:15 AM), but in Firefox it will display 07:15:00.000 instead. There are some quick hacks out there: http://mark.zealey.org/2015/01/08/formatting-time-inputs-nicely-with-angularjs

It would be nice, if we could configure the date format whenever angular switches in fallback mode.

The problem is located in [input.js](https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L385) where we set the format to 'HH:mm:ss.sss'

**Comment by mightydes** [comment]
+1 for this feature

**Comment by kyro38** [comment]
+1

**Comment by wilgert** [comment]
+1

**Comment by simonbuehler** [comment]
it would be great if the formatter of the input could be overridden, in one project i need the time(span) to be entered as 'mm:ss.sss' without hours which would be possible with a custom formatter

**Comment by ismarslomic** [comment]
+1

**Comment by heroInCommunity** [comment]
+1

**Comment by bsandrow** [comment]
Update to [input.js link](https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L447-L449) in the original bug report.

**Comment by SamMorrowDrums** [comment]
This isn't really a feature request, this is a regularly occurring bug. The fallback behaviour should surely mimic the behaviour of the standard HTML 5 time input, adding milliseconds doesn't really seem like a useful fallback, it's got to be the niche case!

**Comment by Nickproger** [comment]
+1

**Comment by hubo1016** [comment]
AngularJS should respect HTML5 "step" attributes on the input element. According to HTML5 standard, when step is set to "60", value of the input should only contains minutes "11:23", while when step is set to "1" or some number less than 60, value should contains seconds e.g. "11:23:34"

**Comment by Narretz** [comment]
@hubo1016 This is a different issue. You can open a new issue as a separate feature request.

**Comment by pgnjidic** [comment]
The problem can be solved by the directive on this link:

[](https://markandruth.co.uk/2015/01/08/formatting-time-inputs-nicely-with-angularjs)

**Comment by waqasilyas** [comment]
Worked with v1.0.3 it seems... http://jsfiddle.net/yk29zeLz/1/

**Comment by roxolan** [comment]
+1 for this feature

**Comment by petebacondarwin** [comment]
Note that this issue has had the `PRs plz` label for almost a year. It is probably not that hard to fix. Does someone in the community - perhaps someone affected by the problem? - want to step up and provide a PR?
