### ISSUE TITLE
$rootScope:infdig triggers with no model change

### ISSUE THREAD

**Issue by ittayd** [angular/angular.js#10738]
Please look at http://jsfiddle.net/qvkyrg7k/8/. The model is a constant array that goes through 2 filters inside an ngRepeat. 

Furthermore, the message is not clear saying something like: regularInterceptedExpression","newVal":15,"oldVal":13

**Comment by jbedard** [comment]
The `groupByFamily` filter returns an object containing *new* arrays each time so `$watchCollection` (used by ng-repeat) detects that as a change since the collection data is different.

You could avoid creating nested objects: http://jsfiddle.net/qvkyrg7k/15/, although that requires running the filter twice...

**Comment by ittayd** [comment]
Isn't the point of filters that they are pure functions so you know they don't change the model? Besides, the error is very confusing and the help page doesn't suggest this case.

**Comment by ittayd** [comment]
and besides, why does that lead to an infinite loop?

**Comment by jbedard** [comment]
The digest loop continues until the model is stable. The `groupByFamily` filter creates new array instances every digest so it never becomes stable.

Unfortunately the pure function logic doesn't work on arrays/objects since comparing them is so expensive :(

**Comment by caitp** [comment]
I think the source of the confusion is this, `data` might be stable, but `data | filter:search | groupByFamily"` is not, and that's what is being watched.

**Comment by ittayd** [comment]
Why watch the result of filters? You watch the data. If it didn't change, the result of applying the filters doesn't change. More accurately, you need to watch the root value (the one before the first pipe) and the arguments to the filters. If none of these change, the end result is the same.

**Comment by caitp** [comment]
@ittayd because if we didn't watch the result of the filters, then ngRepeat wouldn't know it needed to update when the filter produced a different result

**Comment by caitp** [comment]
@jbedard I'm a bit surprised though, that we're re-running non-stateful filters when the identity of the input array and all inputs are identical to what they were before. That seems wrong.

**Comment by ittayd** [comment]
@caitp ngRepeat needs to watch `[data, search]`, not `data | filter:search | groupByFamily`.

**Comment by jbedard** [comment]
@caitp that's correct, it's because the array/object content might have changed and it's just too expensive to check if a collection has changed - that means you have to clone the array to store the "last value" and basically do the same as $watchCollection...

**Comment by caitp** [comment]
@ittayd no, I'm sorry but that's not correct :(

**Comment by ittayd** [comment]
@caitp why?

**Comment by jbedard** [comment]
@ittayd because it is too expensive basically, even though it is logically correct...

**Comment by ittayd** [comment]
@jbedard sorry, but I don't get it. If you interpreted me writing `[data, search]` as meaning to create an array to watch then this is not my point. Instead, ngRepeat needs to watch data and search. If any of them changes, then re-render.

**Comment by ittayd** [comment]
If you're worried about watching n data elements (data and search in my case) instead of one, then maybe an optimization is allowing to tag a filter as "doesn't create new values" (which is an advanced setting), then if all filters have this tag, you watch the end result. Otherwise, you watch each element (or you watch the part of pipe that is composed of such "strict" filters and the rest of elements for filters that are not)

**Comment by jbedard** [comment]
I meant the `data` array.

What you are suggesting is basically already implemented but it doesn't work with non-primitives at this time. Mainly because there are too many situations where it will make performance worse rather then better.

**Comment by ittayd** [comment]
you watch the collection at the end of the pipe, why is it more expensive to watch the collection at the start? 

in other words, if I change to `<tr ng-repeat-start="item in data ">` will everything slow down because now ngRepeat needs to watch `data`?

**Comment by jbedard** [comment]
Who said the end result is a collection? Maybe all my filter does is take the first item out, or returns the length, or returns the first 5 items. Then watching the full collection (containing N items to watch) will be way slower...

**Comment by ittayd** [comment]
sure it will be slower, but that is an application thing. If I do ng-repeat on an array of 1000 items it will obviously be slower than over an array of 2 items. some filters may reduce data, some filters may increase data. The decision to watch the end pipe doesn't immediately mean you'll get something more efficient. 

The most important bit is that it is surprising that it works that way (not only intuitively, but because the documentation suggests otherwise), the errors make it hard to understand what happens, and working around this is not trivial.

BTW, it is also not clear why watching on one thing creates a redraw of everything. So `data | filter:search | groupByFamily` changed. Why does it lead to re-evaluating the pipe (which will cause another change and re-evaluation again)?

**Comment by ittayd** [comment]
Also, since `data` is in the scope, don't you watch it anyway? Meaning in general wouldn't you watch the root value to a pipe any way? wouldn't you watch the arguments to filters anyway?

**Comment by jbedard** [comment]
> the errors make it hard to understand what happens, and working around this is not trivial.

I agree. I was just trying to explain why this was happening :|

Something being on the scope doesn't mean it gets watched.

**Comment by ittayd** [comment]
well, is there a way for me to tell angular to not watch the expression and let me call $apply when required?

**Comment by NevilleS** [comment]
Yup. Move the filtering & grouping logic out of the template and into:
  1. Your controller
  1. Your own directive

In either case, you now can directly control what gets watched and what doesn't. You can make your logic take the =data= array, group it up, and then place the result onto the scope. You can use watch the =data= and =search= models to control when you need to update the results, and let =ng-repeat= behave normally.

**Comment by Narretz** [comment]
It seems that this is resolved as "works as expected". I am gonna close this.
