### ISSUE TITLE
1.3.9 doesn't have a tag yet

### ISSUE THREAD

**Issue by thatguyyoulove** [angular/angular.js#10737]
As of this writing, there isn't a git tag for v1.3.9, so it doesn't show up in Bower yet.

**Comment by btford** [comment]
1.3.9 hasn't been released yet; it's also not available on npm or via angularjs.org.

**Comment by thatguyyoulove** [comment]
@btford Ok, that makes sense. I had always thought that whenever it went into the changelog with a date then that date was its release.
