### ISSUE TITLE
memory leak on firefox

### ISSUE THREAD

**Issue by senateurritchie** [angular/angular.js#10734]
![screen](https://cloud.githubusercontent.com/assets/8276344/5720896/7d5426e6-9b22-11e4-9fc4-80f7425e7567.jpg)
Hi, i use Anguar1.2.28, when in run the same app on chrome and firefox
chrome takes 58.5 Mo of memory and firefox 237.5 Mo
and firefox is freezing i note that chrome works well.
it is an AngularJs problem or not ??  please help.

**Comment by Narretz** [comment]
Hi, there's no way we can determine if this is a genuine memory leak without a reproduction. Please try to reduce the freezing problem to a minimal example that you host somewhere, e.g. in a plnkr.co or similar. Thanks!

**Comment by Narretz** [comment]
I'm gonna close this issue due to lack of response. Feel free to reopen once you can provide more information.
