### ISSUE TITLE
Allow Google Docs style comments/suggests to make improving the docs easier

### ISSUE THREAD

**Issue by fredsa** [angular/angular.js#10743]
Developers who would like to help improve the docs are currently required to either propose a specific change (pull request), or file an issue explaining the problem they encountered.

The latter case introduces unnecessary friction:
- The issue filer must spend time linking to the specific doc page and explaining which section cause them a problem and why.
- Everyone who then has to read the issue or follow up needs to read this context, in order to understand where the problem is. Only then can they focus on the real issue: what the actual problem is.
- Extra friction means that valuable contributions or comments may not be made. (I know I would contribute more if friction were reduced.)

It would be really nice if we allowed developers to simply highlight the affected text, then type in their comment (e.g. what's broken, what's confusing, how we could make the docs better). This allows the submitter and all subsequent readers to immediately understand the context of the comment, and to comment in context.

**Comment by Narretz** [comment]
Out of scope at this point of development.
