### ISSUE TITLE
What is good semantics?

### ISSUE THREAD

**Issue by filipedeschamps** [angular/angular.js#10749]
Hi, I have a question about AngularJS semantics.

I've watched tons of videos with Miško talking about `semantics` and how it's important. I love to use AngularJS, more than any other software, and I assume that this is related to the semantics subject. Wiki defines semantics in computer science as:

> In computer science, the term semantics refers to the meaning of languages, as opposed to their form (syntax). According to Euzenat, semantics "provides the rules for interpreting the syntax which do not provide the meaning directly but constrains the possible interpretations of what is declared."[14] In other words, semantics is about interpretation of an expression.

> ...the following statements use different syntaxes, but cause the same instructions to be executed:
> * `x += y`
> * `x := x + y`
> * `ADD x, y`

But it is related to the syntax, right? One of the moves from 1.x to 2.x is about syntax.

So what exactly is a good semantic? How one can identify a good semantic from a bad one?

Best regards.

**Comment by lgalfaso** [comment]
Hi, I find your question very interesting, but I think this is not the place to have this conversation. Please use the angular forum as that is a suitable place for this discussion
