### ISSUE TITLE
Angularjs website footer needs updating

### ISSUE THREAD

**Issue by casoetan** [angular/angular.js#10746]
The angularjs website copyright needs to be updated to 2015. Currently showing - Super-powered by Google ©2010-2014

**Comment by prajuritbs** [comment]
What about a date.now() Function ? o.O

**Comment by Narretz** [comment]
Thanks, I sent a PR. The website has a special repository btw - https://github.com/angular/angularjs.org/ (although a lot of content is created from the docs in this repo)
