### ISSUE TITLE
Cannot use curly brackets in <OPTION> tag

### ISSUE THREAD

**Issue by mjesun** [angular/angular.js#10753]
I am trying to use the `{{...}}` syntax for a value inside an `<OPTION>` tag (both as a value and as a textContent), but it is automatically parsed by Angular. If I use the `ng-non-bindable` then it renders fine, but the option is not automatically selected based on `ng-model`. What I would like to render is:

```
<select ng-model="myValue">
<option value="{{test}}">{{test}}</option>
</select>
```

And, if `myValue` equals `{{test}}`, then it will be shown as selected.

Working with angular 1.3.0.

**Comment by Narretz** [comment]
Hi, what do you mean with "it is automatically parsed by angular"? 
There's actually a special directive for this, `ng-value`. Have you tried that?

**Comment by mjesun** [comment]
That won't work as well. What I'm trying to do is to render a list as a `<SELECT>` like this:

```js
["{{opened}}", "yes", "no"]
```

The problem is that the first item renders in the corresponding `<OPTION>` with an empty value and an empty inner text, because it is interpolated by Angular, instead of being rendered as-is. If I use `ng-non-bindable`, then it renders perfectly, but then none of the options is selected based on value of `ng-model` of the `<SELECT>`.

**Comment by Narretz** [comment]
This is a limitation of the current parser. Interpolations cannot contain the interpolation signs (default {{ and }}). Fortunately, you can use ngOptions to set up your options: http://plnkr.co/edit/he9MTT6HZxM9V1RASoMQ?p=preview
Does this work for you?

**Comment by mjesun** [comment]
This is strange; I also tried to use `ng-options` and it didn't work initially; however on your example it seems to work. I will try it tomorrow and come back with more information.

**Comment by mjesun** [comment]
My problem is that I would like to have the list statically defined, so what I'm doing is to use `ng-options`, but passing the array as a stringified JSON. So the syntax looks like:

```
n for n in ["{{options}}", "yes", "no"]
```

Which of course makes the `options` to be interpolated from the model, and set up as an empty string. TBH it's a corner case, but it'd be nice to be able to select non-interpolable attributes as well as we have non-interpolable elements (through `ng-non-bindable`).

**Comment by Narretz** [comment]
Ah, I see what you mean. Can you open a new issue and reformulate this a feature request (something like "Allow non-bindable attributes") and add your use-case? I don't see a huge chance for this, but it'll get more attention like this.

**Comment by gkalpak** [comment]
@mjesun: Not sure if it works for your usecase, but you can escape interpolation symbols like this: `\{\{...}}`. So, the following would work:

    o for o in ['\{\{test}}', 'yes', 'no']

[Demo][1]
[1]: http://plnkr.co/edit/tUk3A1AuGXHZJ7FeIHjd?p=preview

**Comment by Narretz** [comment]
Once again, @gkalpak has another good alternative. :) :+1: 

I think we can close this now - feel free to open a new issue as a feature request.
