### ISSUE TITLE
transclude: 'element' causes ng-model not to work for input elements.

### ISSUE THREAD

**Issue by Zerocaliber** [angular/angular.js#10754]
The best way to demonstrate this issue is simply to show it. You can find a very simple plunker of the problem in action here: http://plnkr.co/edit/3WJiVaEzvGHSEt0FKEDR?p=preview.

Essentially, if I add a directive to an input element that has an ng-model and the directive is using transclude: 'element' and replace: true, the element's ng-model no longer keeps in sync.

If, on the other hand, I first wrap it in a span, the element keeps in sync until a value is entered into the input, as though it were a one way data binding.

ng-click doesn't seem to have any issues (as demonstrated by the button), so I assume this is likely true for other directives. 

I'm not sure whether this is all intended behavior or a bug.

**Comment by frfancha** [comment]
Using replace=true (deprecated) causes philosophical problems (and in angular code also ;-) ).
Do not use replace=true, do transclude=true instead of 'element' and then this runs fine:
`<div directive><input ng-model="input"></div>

**Comment by caitp** [comment]
i mean, there are a number of problems with this, but you can hack this to "work" for your purposes, by 1) using the rule of thumb to always use a period in your models (you're working with multiple scopes, so you need this) --- and 2), to increase the priority of your custom directive higher than that of ngModel, which is running first and not being subsequently applied during transclusion (although the reason why it's not being applied to the transcluded element is probably a bug, it's not really a supported use case so I don't expect it to be fixed).

http://plnkr.co/edit/RIiK9bSJUlvTKTOS4CJ1?p=preview here's a working copy.

**Comment by Narretz** [comment]
I'm inclined to close this as "won't fix", since replace: true is deprecated. Wdyt @caitp ?

**Comment by caitp** [comment]
I wouldn't use the word "won't fix", but maybe more "angular 2 should do this better". I think we can close it, though.
