### ISSUE TITLE
docs.angularjs.org is down again

### ISSUE THREAD

**Issue by briantully** [angular/angular.js#10755]
angular version does not seem to be specified when sourcing from googleapis.com

**Comment by briantully** [comment]
addTag('script', {src: '//ajax.googleapis.com/ajax/libs/angularjs/null/angular.min.js' }, sync);
      addTag('script', {src: '//ajax.googleapis.com/ajax/libs/angularjs/null/angular-resource.min.js' }, sync);
      addTag('script', {src: '//ajax.googleapis.com/ajax/libs/angularjs/null/angular-route.min.js' }, sync);
      addTag('script', {src: '//ajax.googleapis.com/ajax/libs/angularjs/null/angular-cookies.min.js' }, sync);
      addTag('script', {src: '//ajax.googleapis.com/ajax/libs/angularjs/null/angular-sanitize.min.js' }, sync);
      addTag('script', {src: '//ajax.googleapis.com/ajax/libs/angularjs/null/angular-touch.min.js' }, sync);
      addTag('script', {src: '//ajax.googleapis.com/ajax/libs/angularjs/null/angular-animate.min.js' }, sync);

**Comment by nlwillia** [comment]
Direct links to a specific version still work (for anyone needing to look something up right now):
https://code.angularjs.org/1.2.28/docs/api
https://code.angularjs.org/1.3.8/docs/api

**Comment by arielspear** [comment]
It seems better now.

**Comment by Narretz** [comment]
Thanks, it's up again. The release is causing some unforeseen problems, but we'll try very hard not to break it again. :)
