### ISSUE TITLE
bower-angular-resource broken with browserify

### ISSUE THREAD

**Issue by slively** [angular/angular.js#10760]
index.js is being generated with this (which is not valid javascript):
```javascript
require('./angular-resource');
module.exports = angular-resource;
```

Changing it to this fixes it:
```javascript
module.exports = require('./angular-resource');
```

It also looks like package.json used to have the below instead of using the index.js:
```
"main": "angular-resource.js",
```

**Comment by caitp** [comment]
yep, apparently the bower stuff got published before it the npm release change was reverted, although I'm not sure why. So, we need to unpublish that stuff and fix it :\

**Comment by Aourin** [comment]
happens in animate, sanitize, and I think a few other ones as well.

**Comment by caitp** [comment]
it happens with all of them --- @btford does it look safe to unpublish and just republish the bower builds, or would it have to be a bit more of a hands-on fix?

**Comment by caitp** [comment]
so @petebacondarwin's position on this is to just leave it broken until the next release :( I know that's inconvenient for anyone using the ^ operator in their package.json, but a workaround is to just use 1.3.8 for a while :(
