### ISSUE TITLE
[website] Incomplete thought on page "Running an AngularJS App in Production"

### ISSUE THREAD

**Issue by KamBha** [angular/angular.js#10762]
The very first sentence in the section "Disabling debug data" is:-

"By default AngularJS attaches information about scopes to DOM nodes, and adds CSS classes to data-bound elements. _The information that is not included is:_"

The emphasised text is the issue.  There is no further information on what angular does not include.  I **think** the emphasised phrase should be removed, but not sure if there was some value in describing what information is not included.

**Comment by Narretz** [comment]
I also can't think of what should come after that. I'll leave it open for a while, maybe someone has an idea.
