### ISSUE TITLE
ngOptions and ngRepeat don't have the same behavior with empty value on <select>

### ISSUE THREAD

**Issue by 5im0n** [angular/angular.js#10777]
Hey Angular community:

I use the ngOptions directive to fill my selectbox. This selectbox is use to filter value on a list. I set an empty element on the selectbox to retrieve all value of the list.
But when I select the empty element it return anything.
When I fill my select box with the ngRepeat directive the empty value return all element of the list.

Please check this jsfiddle *(Angular 1.3.9)*
http://jsbin.com/yeqayajizo/1/edit?html,js,output

**ngOptions:** *Empty value return anything*
```html
    <select class="form-control" ng-model="demo.filterplots.district" ng-options="p.id as p.name for p in demo.plots">
      <option value="">-- All entries --</option>
    </select>
    
        
    <ul>
      <li ng-repeat="c in demo.contacts | filter:demo.filterplots">
        {{c.firstname}} {{c.name}}
      </li>
    </ul>
```

**ngRepeat:** *Empty value return all elements*
```html   
    <select class="form-control" ng-model="demo.filterplots_2.district">
      <option value="">-- All entries --</option>
      <option ng-repeat="p in demo.plots" value="{{p.id}}">{{p.name}}</option>
    </select>
    
    
    <ul>
      <li ng-repeat="c in demo.contacts | filter:demo.filterplots_2">
        {{c.firstname}} {{c.name}}
      </li>
    </ul>
```

**Comment by Narretz** [comment]
Hi, to be sure - you mean when you have `ngOptions` and select `All entries` it **doesn't** return anything? This is what I see in the jsbin.
And what is the behavior you want? Return all elements or return nothing?

Anyway, there are two things happening here:
1. when you add a hardcoded "empty" option inside an `ngOptions` select (`<option value="">--Select all--</option>`), this value becomes `null`on the model.
2. When you do the same, in without ngOptions, the `value` is not transformed to `null`, and stays empty string on the model.

Second, the filter behaves differently depending on the value that is passed:
1. `null` tries to match the `district` against `null`, and that doesn't produce any results
2. `''` however matches against any string, so this returns all entries. One could consider this one a bug (https://github.com/angular/angular.js/blob/master/src/ng/filter/filter.js#L169)

Quick fix is to add a  `$parser` to your ngModel that transforms null to empty string, see http://jsbin.com/vuqevayusu/3/edit

**Comment by gkalpak** [comment]
> 2. `''` however matches against any string, so this returns all entries. One could consider this one a bug [....]

FWIW, I don't think it's a bug, since it works as prescribed (converting to string and doing case-insensitive substring-matching), so `''` **should** match any string (by definition).

**Comment by 5im0n** [comment]
Hi @Narretz @gkalpak ,

I understand that it works as prescribed, but I think it's weird.
To my mind the most logical behavior, is that the empty string return all elements.
I don't see an examples where we need to retrieve any element.

It's common to use a select box to filter data.

**Comment by gkalpak** [comment]
> To my mind the most logical behavior, is that the empty string return all elements.

It does.

The issue arises from the fact that (when using `ngOptions`) selecting `<option value="">...</option>` will set the model to `null`, not `''`.

I would probably use a custom comparator function, that matches anything against an expected value of `null`:

```js
vm.nullMatchesAnything = function nullMatchesAnything(actual, expected) {
    return (expected === null) || (actual === expected);
};
```

```html
<li ng-repeat="c in demo.contacts | filter:demo.filterplots:demo.nullMatchesAnything">...</li>
```

[Demo][1]

[1]: http://jsbin.com/qazucejapa/1/edit?html,js,output

**Comment by Narretz** [comment]
I'm gonna close this - @gkalpak has explained why the filter works as it does, and you have now two ways to overcome your issue.
