### ISSUE TITLE
Issue in IE9 with custom filter and dropdown.

### ISSUE THREAD

**Issue by VasylVuy** [angular/angular.js#10782]
Hi All, 

I have an issue with custom angular filter and select element. 

I created simplified version of my application in jsfiddle: http://jsfiddle.net/98cnbv1x/6/. Tested with angular 1.3.9.

Here is what it does:
there is a notion of items and hosts, items can be in two states: "Not started" and "In progress".
To bring item to "In progress" item needs to use one of the hosts. If the host is already in use it should not be available for items that are still in "Not started".

I update available hosts after each transition of Items between states.

Steps to reproduce the issue:
1) use IE9;
2) for ThirsItem select Host3 from dropdown;
3) press "To In Progress" button on ThirdItem, item should be moved to InProgress state;
4) expand dropdown of SecondItem (don't touch FirstItem), it contains 2 hosts now, because 1 is in use;
5) press "To Not Started" on ThirdItem.

expected behavior: all dropdowns should contain all 3 hosts;
bug: SecondItem has only 2 hosts, because it was expanded;

Cannot reproduce this issue in Chrome and Mozilla.

**Comment by aabenoja** [comment]
Something must be going down if I'm still seeing three items in the first select by step 4.

**Comment by pkozlowski-opensource** [comment]
@aabenoja I can still reproduce it with 1.3.9.
@VasylVuy I've just tried the latest version from master and it seems to be working fine: http://jsfiddle.net/8j5er1yp/. Could you please confirm?

**Comment by VasylVuy** [comment]
Hosts do not filter when you move items to "In Progress" in your version http://jsfiddle.net/8j5er1yp/

**Comment by VasylVuy** [comment]
Actually you fixed that bug with this version: http://jsfiddle.net/8j5er1yp/
But introduced new:
after steps of the previous bug just move ThirdItem to "In Progress" again and it will contain all three hosts, but shoul contain only two. 

It happens in IE9 only.

**Comment by petebacondarwin** [comment]
I think this is something to do with IE9 not repainting correctly. If you actually the bind the `availableHosts` property to the template then this doesn't happen... We might be able to find a place where we need to hit some DOM property to force IE9 to do this repaint.

**Comment by wesleycho** [comment]
This sounds possibly related to the prior IE bugs reported on this issue #4749, #7692.

**Comment by Narretz** [comment]
Can't repro in 1.4.9 or 1.5.3
