### ISSUE TITLE
ng-repeat cannot be exit in between the loop

### ISSUE THREAD

**Issue by ranrolls** [angular/angular.js#10787]
Hi, Myself Ranjan
I have more than 10 years experience in web world.
In core js programming it is more than 3 years as on 17th jan 2015.
Angular great at outer. Performance is issue.
But what i have seen while working on it that it lacks a major directive which could end the ng-repeat loop in between loop on some condition.
And the other thing ng-repeat do not give a chance to exit. i have searched this issue around 2 to 3 hours on internet before submitting it.
Hope you will find the same issue.

greatwebist@outlook.com
greatwebist.wordpress.com

**Comment by ranrolls** [comment]
This problem can solved by using multiple ng-if statements in ng-repeat.

**Comment by ranrolls** [comment]
This problem can solved by using multiple ng-if statements in ng-repeat.

**Comment by Taewa** [comment]
@ranrolls I could resolve by your solution. Thank you.
