### ISSUE TITLE
How to save data bindings when changing DOM outside angular (for instance jquery)

### ISSUE THREAD

**Issue by prady00** [angular/angular.js#10781]
I have got a problem for loosing data binding when I change DOM outside of angular.
How can I preserve it. 
I was trying to do this : https://github.com/FezVrasta/bootstrap-material-design/issues/366

**Comment by pkozlowski-opensource** [comment]
@prady00 please direct support questions like this one to one of the support channels mentioned here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

We want to keep GitHub issues for bug reports and feature requests only. Thnx for your understanding!

**Comment by prady00** [comment]
@pkozlowski-opensource will keep in mind, thanks :)
