### ISSUE TITLE
angular-mocks npm package for 1.3.9 is broken

### ISSUE THREAD

**Issue by nullstyle** [angular/angular.js#10785]
I've got a webpack-based angular project that uses the angular-mocks package for our test suite.  Did a fresh install today and got the 1.3.9 package of angular-mocks and started getting the error on launch:

`ReferenceError: mocks is not defined`

Looking at angular-mocks/index.js, it's entire content is:

```
require('./angular-mocks');

module.exports = angular-mocks;
```

**Comment by caitp** [comment]
all the npm modules for 1.3.9 are broken, @petebacondarwin wanted to just fix it for the next release :(

To work around it, you can manually use angular-mocks/angular-mocks.js, but index.js isn't gonna work

**Comment by nullstyle** [comment]
cool, thanks!

**Comment by pkozlowski-opensource** [comment]
@caitp if I understand correctly what @petebacondarwin is suggesting this one is "won't fix" as we are not planning to amend 1.3.9, right? I guess the situation will get back to normal in 1.3.10 to be released tomorrow / Tue. If so I'm going to close this one as non-actionable.

New releases should have the working `index.js` in the next weekly release.

**Comment by caitp** [comment]
it might be back to normal or it might not, who knows

**Comment by pkozlowski-opensource** [comment]
@caitp do you want to keep this one open till the next release then?

**Comment by caitp** [comment]
i think we should keep it open until we have a decision beyond just "release the revert"

**Comment by pkozlowski-opensource** [comment]
OK, let's do this.

**Comment by spacepluk** [comment]
I think this should fix it #10802

**Comment by kentcdodds** [comment]
For projects using UMD, some of them look like this:

```js
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['angular'], function (angular) {
      return (root.returnExportsGlobal = factory(angular));
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like enviroments that support module.exports,
    // like Node.
    module.exports = factory(require('angular'));
  } else {
    factory(root.angular);
  }
}(this, function (angular) {
  // create angular module here and do stuff
});
```

I just updated to 1.3.10 and it broke one of my dependencies because `require('angular')` no longer exports `angular`. Just FYI.

**Comment by caitp** [comment]
this has technically been fixed as the npm format releases have been reverted to their original states, but may change again next week
