### ISSUE TITLE
ngAnimate interfering in IE11 

### ISSUE THREAD

**Issue by georgebatalinski** [angular/angular.js#10795]
Rating component is behaving unexpectedly in IE11 with ngAnimate in the page -
 angular-ui.github.io/bootstrap/#/rating

This behaviour only happens when ngAnimate is available on the page. Note: IF ngAnimate is removed from the page - the rating component behaves as expected.

with ngAnimate - To replicate this issue - GO TO in IE11 on Windows (w/ ngAnimate) 

http://plnkr.co/edit/QsMFDCtnxo62xoBYbulN?p=preview 

Note: Pass/Move your mouse over any of the stars - from top to bottom - slowly in IE11 - the ng-class is applied (even if you have not clicked) Note: Disabling animation on elements does not work.

Expected behaviour - stars should not get ng-class unless clicked* ![Pass your mouse from bottom to top slowly over the stars - you will notice that a new css class is applied - NOT expected behaviour][1]

Is it possible that ngAnimate is interfering in some way?

**Comment by VitalyTomilov** [comment]
Any chance this is related to this? - https://github.com/angular/angular.js/issues/10156#issuecomment-67792928

There is a solution there at the bottom offered, although somewhat temporary, I believe.

**Comment by georgebatalinski** [comment]
I tried the temp solutions with no luck - however downgrading seemed to work well. 

Thank you for your help

------Don't laugh, but this one was the final stroke after which I downgraded 1.3.3 to 1.2.27. I saw this issue described here in my own UI constantly, and it's irritating. It doesn't happen in 1.2.27, so much for 1.3 production readiness...it's just not there yet.
