### ISSUE TITLE
Cut, Copy, Paste using angularjs

### ISSUE THREAD

**Issue by Bhimisetty** [angular/angular.js#10799]
Is there any possibility to perform Cut, Copy and Paste using the anuglarjs. I have seen the ng-clip to copy the data into the clipboard.But that copies total model. I want to work with selected text need to be cut and copy and need to paste that in the particular control after the cursor focused.And it should works in all browsers

**Comment by Narretz** [comment]
There are directives that wrap these events: https://docs.angularjs.org/api/ng/directive/ngCut, https://docs.angularjs.org/api/ng/directive/ngCopy, https://docs.angularjs.org/api/ng/directive/ngPaste

Beyong that, this is really a question that is not suited for this repo - please read the contribution guidelines on where to find support: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md
