### ISSUE TITLE
Unable to add dynamic content

### ISSUE THREAD

**Issue by CKGrafico** [angular/angular.js#10796]
When you work with Apache Cordova or Winjs with Windows apps you can see this error

![Image of error](http://i.imgur.com/yr5L78U.png)

This error appears on the version 1.3.6 at the final line https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js

but I can't find this in the repository.. to fix the error only change

```javascript
!window.angular.$$csp() && window.angular.element(document).find('head').prepend('<style type="text/css">@charset "UTF-8";[ng\\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\\:form{display:block;}</style>');
```
 
with

```javascript
!window.angular.$$csp() && window.angular.element(document).find('head').prepend(window.toStaticHTML('<style type="text/css">@charset "UTF-8";[ng\\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide:not(.ng-hide-animate){display:none !important;}ng\\:form{display:block;}</style>'));
```

**Comment by lgalfaso** [comment]
Hi, This is just one of the limitations when running in an environment with csp enabled. The proper way for this is to enable angular is csp mode [ngCsp](https://docs.angularjs.org/api/ng/directive/ngCsp), and be sure that you
```
CSP forbids JavaScript to inline stylesheet rules. In non CSP mode Angular automatically includes some CSS rules (e.g. ngCloak). To make those directives work in CSP mode, include the angular-csp.css manually.
```

**Comment by CKGrafico** [comment]
O wait... this is one of the limitations when you inject html with no the best form to do that.. but is not my library
