### ISSUE TITLE
ngResource multiple deletion DELETE 

### ISSUE THREAD

**Issue by iyel** [angular/angular.js#10801]
HI, is there any way to pass data with $delete or $remove actions?

For example: I need to do multiple deletion, the method and url are: DELETE /api/v1/user/
and along with I need to send array of ids to be deleted.

**Comment by pkozlowski-opensource** [comment]
@iyel please direct support questions like this one to one of those [support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). We want to keep GitHub issues for bug reports and feature requests only. Thnx!
