### ISSUE TITLE
ngAnimate and CLOSING_TIME_BUFFER value

### ISSUE THREAD

**Issue by jlowcs** [angular/angular.js#10806]
I was wondering why the promise returned by ```$animate.enter``` function was taking so much time to be resolved (approx half of the time of the animation). Even with a 250ms animation, it is very perceptible.

Searching the code, I found the **CLOSING_TIME_BUFFER** variable which is used as a multiplier to the animation time parsed from the CSS. That variable is set to **1.5**, which explains the observed delay.

I assume that this is used to ensure that the animation is done when resolving the promise.

Any reason why this specific value is used?

**Comment by petebacondarwin** [comment]
@matsko - can you take a look at this one, please?

**Comment by matsko** [comment]
@jlowcs the closing time buffer is only there as the last resort to catch if any an animation fails to render. This can happen for example if a transition doesn't kick off (like if you try to transition `red` to `red`) or if some CSS specificity overpowers some other CSS code which triggers an animation. Bottom line, if the closing time buffer passes then your CSS code is problematic and should be fixed.

Do you have a working plnkr example of the animation? Mind putting that together?

**Comment by matsko** [comment]
@jlowcs if this is still an issue (even with 1.4) please post a reply here. It's been almost half a year since any activity occurred on this. I'm closing it for now.
