### ISSUE TITLE
ngModel:numfmt error

### ISSUE THREAD

**Issue by TheAJ** [angular/angular.js#10808]
I am trying to assign a model a number value, and get the following error:

    Error: [ngModel:numfmt] http://errors.angularjs.org/1.3.9/ngModel/numfmt?p0=4055

HTML:

    <input type="number" class="form-control" placeholder="Value"  
        ng-model="newTax.value" name="value" required>

When I try to assign a value programatically:

    $scope.newTax.value = 4055;

It works, but when i try this, it does not:

    $scope.newTax.value = ($scope.component.adjustedValue * ($scope.newTax.percent * 0.01)).toFixed();

Browser: Chrome 39
AngularJS 1.3.9

**Comment by VitalyTomilov** [comment]
And where do you assign an object to $scope.newTax? Your code doesn't show, the first guess is whether you do that at all, 'cos if not, there's a problem right there.

But that's nothing to do with Angular, that's Javascript 1-0-1 ;)

**Comment by aabenoja** [comment]
`toFixed()` will return a string representation of your desired result.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

**Comment by aabenoja** [comment]
Also, [here is the link to input[number] docs](https://docs.angularjs.org/api/ng/input/input%5Bnumber%5D), stating that an exception will be thrown if the model is not a number.

**Comment by TheAJ** [comment]
@aabenoja Thanks. I figured this out 5 minutes after I posted this... Should have researched a little longer :+1:
