### ISSUE TITLE
Controller argument description in directive link function documentation is wrong

### ISSUE THREAD

**Issue by dorellang** [angular/angular.js#10815]
The docs say in the link function argument list (https://docs.angularjs.org/api/ng/service/$compile)
> `controller` - a controller instance - A controller instance if at least one directive on the element defines a controller. The controller is shared among all the directives, which allows the directives to use the controllers as a communication channel.

But this is not true as of version 1.3.x. Currently the value of this argument depends on whether the directive `require` list has been defined; if it has, then `controller` is actually a list in which the i-th value is the controller instance of the i-th directive in the `require` list. Else, `controller` is just the directive's controller instance (or `undefined` if it doesn't have one).

Probably I should have sent a PR or something with the correction, but since my English kind of sucks I haven't.

**Comment by Narretz** [comment]
Yeah, that's true:
One correction to your correction:
If you use 
`require: 'ngModel'`
then controller is not an array. It's only an array if require is an array.
