### ISSUE TITLE
compare-master-to-stable.js script doesn't work properly after switch to 1.4

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular.js#10816]
The output says that it compares master with 1.2.x (instead of 1.3.x). To be investigated / fixed.

**Comment by rphv** [comment]
The tag on the latest version is `v1.4.0-beta.0`. The prerelease tag ("beta") causes it to be excluded from the set of versions that's checked - see documentation for [semver](https://github.com/npm/node-semver#prerelease-tags).  

Specifically, `semver.satisfies('1.4.0-beta.0','1.x')` returns false:

https://github.com/angular/angular.js/blob/master/compare-master-to-stable.js#L109

One possible fix to ensure the most recent version is included:
```javascript
function (tags) {
  var currentTag = tags[0];
  var major = tags[0].split('.')[0] + '.x';
  return tags.
    filter(function (ver) {
      return semver.satisfies(ver, major) || ver == currentTag;
    });
}
```

**Comment by petebacondarwin** [comment]
This is fixed by https://github.com/angular/angular.js/commit/452d1cd66e8109fd5d19189207ac4be16ad827b5

**Comment by Narretz** [comment]
Closing since it seems fixed.
