### ISSUE TITLE
One-time binding - strange behavior

### ISSUE THREAD

**Issue by walter-psjr** [angular/angular.js#10814]
I am developing an application where angular realized that the number of watchers was high despite being using one-time binding. I created a test page with a listing in table and realized that when I use http: // localhost one-time binding does not work and when I change the address for the machine name, for example, works correctly:

http://localhost/angular/repeater2.html
![image](https://cloud.githubusercontent.com/assets/8856322/5822902/3c73e006-a0bf-11e4-94b1-05dfa2a443a1.png)

http://ucb-walterdev/angular/repeater2.html
![image](https://cloud.githubusercontent.com/assets/8856322/5822925/71f6ba3c-a0bf-11e4-82e9-61766f0a7e47.png)

The detail is that this is only happening in Chrome (I'm using version 39.0.2171.99 m, Windows 8.1 64-bit). In Firefox and Internet Explorer rendering occurs perfectly.

The code to generate the table:

```
    <table class="table table-bordered table-striped table-hover tablesorter" id="tblOcuppation">
        <thead>
            <tr>
                <th>Id</th>
                <th>Occupation Name</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <tr data-ng-repeat="occupation in occupations">
                <td>{{::occupation.Id}}</td>
                <td>{{::occupation.Name}}</td>
                <td>
                    <button type="button" class="btn btn-default btn-sm" data-ng-show="::occupation.Name.indexOf('a') > -1" data-ng-click="delete(occupation.Id)">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td>Total:</td>
                <td>{{occupations.length}}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>
```

**Comment by lgalfaso** [comment]
Clean your cache?

**Comment by walter-psjr** [comment]
Sorry, forgot to inform the version of Angular I'm using. Yesterday tested with the 1.3.9 version, now just testing with version 1.3.10 and the problem persists. I tried clearing the cache but nothing changed. This test was done with a list of 855 items.

Are having difficulties with this problem, lists about 100, 150 items, in some cases, are having a very bad performance in Chrome.

It has been tested in Internet Explorer 11,  Opera 26.0.1656.60, Firefox 35, Safari 5.1.7 and is running smoothly at all without crashes in rendering process.

**Comment by lgalfaso** [comment]
Hi, Would it be possible to have a plunker that shows this issue?

**Comment by walter-psjr** [comment]
http://plnkr.co/edit/5JVje6dVS37khmIbqTDJ?p=preview

**Comment by lgalfaso** [comment]
I am testing this with Chrome 39.0.2171.95 and in your page, the number of watches is 2. The test I did is the following
```js
function countWatchers(scope) {
  var r = scope.$$watchers ? scope.$$watchers.length : 0;
  scope = scope.$$childHead;
  while(scope) {
    r += countWatchers(scope);
    scope = scope.$$nextSibling;
  }
  return r;
}

countWatchers(angular.element(document).injector().get('$rootScope'));
```


Are you using batarang?

**Comment by walter-psjr** [comment]
Strange, I downloaded the Plunker and performed here and also work, but the first example I showed the print screens and our project, which is running locally on http: // localhost: 7142, still does not work.

The Plunker and first example are the same code, the only difference is that in the first example the data are brought by an ajax request.

Yes, I'm using the Batarang extension, it may be interfering? Tested in another development machine but it had the same problem and also had the installed extension.

**Comment by lgalfaso** [comment]
There were some issues with batarang, but I am not an expert in it so I am not sure if it can cause this specific issue or not. Can you try using a profile that does not have batarang installed?

**Comment by walter-psjr** [comment]
I disabled the extension Batarang and it worked, if I will activate the one-time binding stops working again.

**Comment by lgalfaso** [comment]
I would say this is an issue with batarang, you can open an issue there (or
check if updating to a later version fixes this). Unless there is anything
else, I think this issue can be closed

**Comment by walter-psjr** [comment]
I checked and I already have the latest version. I'll close this issue and open another there. Thank you for following this problem.
