### ISSUE TITLE
On using the local custom filter in angular slows the performance on backspace

### ISSUE THREAD

**Issue by piu** [angular/angular.js#10812]
Hi there,

 I am using angular version (1.2.26) and facing issue with performance for custom filter. 
 I need to filter data on each property of object I am using hence I have created a custom filter which does this, but when backspace is used the query gets changed and filter takes lots of time to return data.

I tried setting the timeout on watch of my query but still it does not work :( 

Is there any way out to achieve filtering on all properties of object I am binding (on an avg 6/8 properties) without hampering the performance?

**Comment by pkozlowski-opensource** [comment]
@piu you need to be aware of the fact that all filters are re-calculated as part of each $digest cycle (in your case apparently triggered by a DOM event). There are no miracles here, really - if you filter takes substantial amount of time to execute than it is going to slow down the application. 

You might want to try to switch to 1.3.x that has number of perf optimizations but even in 1.3.x if your dataset is large and operations on this data-set slow this won't change much. 

It is really hard to say more as this is kind of a support questions and as such should be asked [elsewhere](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).
