### ISSUE TITLE
angular-cookies.js modify browser cookies,but i can not find the result in the browser

### ISSUE THREAD

**Issue by changjiasheng** [angular/angular.js#10824]
Hi :

          The version of angular that  i used is v1.3.4.The code i used like this .
```javascript
<script src="angular.js"></script>
<script src="angular-cookies.js"></script>

<script>

	angular.module('validateApp', ['ngCookies'])
.controller('validateCtrl', ['$cookies', function($cookies) {
  // Retrieving a cookie
  var favoriteCookie = $cookies.myFavorite;
  // Setting a cookie
  $cookies.myFavorite = 'oatmeal';
}]);
</script>
```
                 but ,when i press F12 in the chrome browser,i can not find the result in the browser.

![piccc](https://cloud.githubusercontent.com/assets/3156889/5832978/3563ff70-a188-11e4-8a0d-e33538f1bb3d.png)

**Comment by petebacondarwin** [comment]
@shahata - you have been working on Cookies recently. Can you take a look at this?

**Comment by shahata** [comment]
@changjiasheng you cannot set cookies from a `file:///` url, you have to open your application using http or https url in order to be able to work with cookies. This is not Angular related, you will see the same issue if you try to work with `document.cookie` directly.
