### ISSUE TITLE
docs: step 6 of tutorial use a href rather than an ng-href

### ISSUE THREAD

**Issue by EthanLozano** [angular/angular.js#10828]
[step_06.ngdoc](https://github.com/angular/angular.js/blob/master/docs/content/tutorial/step_06.ngdoc) uses a dynamically generated link with the href attribute rather than the [ng-href](https://docs.angularjs.org/api/ng/directive/ngHref) attribute.

**Comment by EthanLozano** [comment]
The [Phonecat](https://github.com/angular/angular-phonecat/blob/step-6/app/index.html) tutorial source code and tag needs to be changed first. So, I went ahead and created an [issue](https://github.com/angular/angular-phonecat/issues/226) for that repo.

**Comment by dguzzo** [comment]
@Narretz hmm, not sure how https://github.com/angular/angular.js/issues/10850 being merged will fix the issue with the docs here; regardless of parsing, shouldn't the example in the tutorial still use `ng-href` for the dynamic link? I'm probably missing something.

**Comment by Narretz** [comment]
It looks like I referenced the wrong issue to close.

**Comment by petebacondarwin** [comment]
This is not really necessary as it is unlikely that the user will click on a link before Angular has had time to fill it correctly.
