### ISSUE TITLE
ngPluralize example has problem when a value >3 is deleted

### ISSUE THREAD

**Issue by mrsoto** [angular/angular.js#10836]
In this page
https://code.angularjs.org/1.3.10/docs/api/ng/directive/ngPluralize

Change the number of peoples to 3 or more and then clear the field.

typing 3 and cleaning get -2 other peoples...

**Comment by caitp** [comment]
yeah, that's kind of weird --- @petebacondarwin do you think ngPluralize should support signed values by default? or maybe there's a better way

**Comment by gkalpak** [comment]
FWIW, I can't reproduce on Chrome/Firefox on Windows, but it sounds reasonable to (properly) handle negative values as 0.
On what browsers/platforms do you see this ?

**Comment by caitp** [comment]
you can see it in chrome and safari on a mac, i expect you can see it on windows too

**Comment by mrsoto** [comment]
I've the problem in Windows Chrome

**Comment by mrsoto** [comment]
This example start assuming that blank is zero and this assumption remain
for 1 and 2 after the field is cleared but if you type 3 or more and then
clear the field got negative values.

**Comment by gkalpak** [comment]
I can reproduce it with 4 or more but not 3. Weird...

**Comment by gkalpak** [comment]
I think the problem is that `lastCount` was assumed to always be numeric (thus assuming that `isNaN(lastCount)===true` means `lastCount -> NaN` (which isn't true)).

**Comment by Narretz** [comment]
:sparkles: Don't forget to label / milestone everyone! :sparkles:

**Comment by petebacondarwin** [comment]
+1 Narretz!
