### ISSUE TITLE
How to post data as json from request payload?

### ISSUE THREAD

**Issue by lilan123** [angular/angular.js#10838]
Here is my code sample, though i set the method as post it will set Request Method to OPTIONS and request payload won't be set. 

angular.module('httpExample', []).controller('FetchController', ['$scope', '$http', '$templateCache',
            function($scope, $http, $templateCache) {

                $scope.headers= {
                    'Accept': '*/*',
                    'Content-Type': 'application/json; charset=UTF-8'
                };
                $scope.method = 'POST';
                $scope.url = 'http://localhost:56652/reqresp.svc/json/post';
                $scope.data={"requests":[{"__type":"AuthenticateAndGetProsties:#LabOra.ProsteModul.ReqResp.Requests", "Authentication":{ "__type":"UserAuthentication:#LabOra.ProsteModul.ReqResp","Username":"xxx","Password":"yyyy" }}]};

                $scope.fetch = function() {
                    $scope.code = null;
                    $scope.response = null;

                    $http({method: $scope.method, url: $scope.url,data: JSON.stringify($scope.data),headers:$scope.headers, cache: $templateCache}).
                        success(function(data,status) {
                            $scope.status = status;
                            //$scope.data =x2js.xml_str2json(data);
                            $scope.data =data;
                        }).
                        error(function( status) {
                            $scope.data = "Request failed";
                            $scope.status = status;
                        });
                };
            }]);
})(window.angular);

**Comment by Narretz** [comment]
Please don't open any further issues about this. You are having problems with you CORS setup on the server side.

**Comment by lilan123** [comment]
There is no problem with CORS since it is working with Postman and Rest Console. i have checked both tools requested to server is request method:post, Content-Type:applicaion/json and data in $scope.data will be set to request payload. what would be the reason?
