### ISSUE TITLE
Materialize the Docs: Left pane updates

### ISSUE THREAD

**Issue by jesselpalmer** [angular/angular.js#10830]
Thoughts from @caitp:

The scrollbar on the left pane is a bit awkward, I like the grouping style used in material.angularjs.org to avoid that (although tbh the performance of that thing is terrible in Safari)

**Comment by caitp** [comment]
they are in the document, I believe :) do you have any plans to go about the left pane issues? those are more important than the colour scheme, imo

**Comment by jesselpalmer** [comment]
sounds good, i'll work on the left pane issues.

**Comment by jesselpalmer** [comment]
since these thoughts are already documented elsewhere, i'll go ahead and change the scope of this particular issue just to cover the left pane issue.

**Comment by jesselpalmer** [comment]
@marcysutton @ThomasBurleson Is there a method for toggling those button groups vertically are on the Angular Material left nav built into the library? I see there is a way to toggle the [sidebar left and right](https://material.angularjs.org/#/demo/material.components.sidenav), but I haven't come across anything about toggling groups up and down. I'm look for something like `toggleUp()`, `toggleDown()`, or `toggleVertically()`, etc. Thank you for your help!

**Comment by marcysutton** [comment]
The toggles and the sidenav are separate components. There is a redesign of the docs launching this week that will do away with those toggles (which are not actually components) in favor of the list item control in the Material Design spec: https://github.com/angular/material/pull/1116. The formal component for list item control is forthcoming in https://github.com/angular/material/issues/985.

**Comment by jesselpalmer** [comment]
Great, exactly what I needed to know. Thank you!
