### ISSUE TITLE
Angular date filter can't have the used timezone globally configured

### ISSUE THREAD

**Issue by denislins** [angular/angular.js#10834]
A great feature of AngularJS 1.3 is the third parameter of the date filter, in which we can specify UTC, and it will remove the offset of the local timezone.

But there's currently no way to configure this timezone globally, so, if you decide that you'll be passing UTC as timezone, you'll have to do this every single time.

It would be convenient to have one single place to configure the timezone, avoiding waste of time and code. What do you guys think about it?

I'm willing to write the PR, but I'll need some discussion first, as I'm kinda new to AngularJS and not sure of some things yet, like where would be the best place to configure this globally.

I searched the issues before posting this, and didn't find anything related. If there is already an issue for that, I apologize.

**Comment by pkozlowski-opensource** [comment]
Yes, this is true - as of today there is no configuration to default to `UTC` time zone. But it would be very easy to work-around this on the application side by decorating the existing filter and always supplying the time-zone param.

**Comment by denislins** [comment]
Agreed, and I ended up doing that. But I do think that this is a thing that makes more sense to be somewhere inside the framework. I'm not adding custom functionality, I'm just configuring a filter. What do you think? In case you agrees with me, where would be a good place to configure this?

**Comment by pkozlowski-opensource** [comment]
If we want to push this into the core the "right" way to do it would be in a provider. So what we would have to do is to create a `dateFilterProvider` and expose some property ex.: `defaultTimeZone`. This is easily doable but would add some bytes to the core so this is why I was hesitating about doing it in the first place (that is - the cost of additional bytes for a not-so-common feature).

But yeh, this is technically doable without too much pain.

**Comment by denislins** [comment]
I see your point. Additionally, as Angular currently supports only UTC, it may be an overkill to create a provider just to do this. But the provider idea seems to have potential, because some more stuff could be configured in there, besides the default timezone.

Anyway, I'm not sure if now is the time to do this, since it'll be bundled with the Angular core, therefore making the code a bit bigger. I guess I'll leave this decision to you :)

**Comment by aesnyder** [comment]
I currently do this as a workaround to globally default to UTC....

https://gist.github.com/aesnyder/4f5ee12bffd5369b385c

Hope it helps!

**Comment by LeleDev** [comment]
+1

**Comment by fferraris** [comment]
+1

**Comment by mightydes** [comment]
+1

**Comment by ray-kay** [comment]
+1

**Comment by nadavhury** [comment]
+1

**Comment by petebacondarwin** [comment]
This is trivial to implement outside the core (see https://github.com/angular/angular.js/issues/10834#issuecomment-83674196), so we do not intend to modify AngularJS with a configuration option.
