### ISSUE TITLE
Polish chars and angular variables in templates - IE Only

### ISSUE THREAD

**Issue by colejarczyk** [angular/angular.js#10835]
This is a very specific bug. Variable placed after polish character is not resolved by angular. Instead it is just plain text. When I remove this char, everything is good. This happens only in Internet Explorer and only if variable is right after special char. Here is an example.
```
var some_variable = 1;
var currency = 'PLN';

ść [[ some_variable ]] # not work, output "ść [[ some_variable ]]"
zł [[ currency ]] # not work, output "zł [[ currency ]]"
sc [[ some_variable ]] # works, output "sc 1"
zl [[ currency ]] # works, output "zl PLN"
```
I'm using AngularJs version 1.3.10 with custom start and end symbol ($interpolateProvider), IE version 11 on Windows 7.

**Comment by pkozlowski-opensource** [comment]
@colejarczyk could you please put together a plunker that shows the issue? There are certain pieces of info that are missing, ex.: encoding used on the page.

**Comment by colejarczyk** [comment]
Well, probably I came to this conclusion too early. After many attempts I couldn't repeat this error in plunker. In my current project this problem is still unresolved and it seems related to ui-router nested views or jquery nicescroll plugin. What is especially weird is that only variables after polish chars are not resolved and only in IE (version doesn't matter). I need some more time to find is it really angular bug, ui-router or maybe jquery plugin. If it is a problem, then this issue can be closed.

**Comment by pkozlowski-opensource** [comment]
@colejarczyk thnx for coming back with more info. I think we can close this one till we've got reproduce scenario. But I would be more than happy to re-open it / fix the pb as soon as we know what is going on and it is actionable in AngularJS.
