### ISSUE TITLE
feat(ngMessages): allow including client-side defined message templates

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular.js#10844]
`ngMessages` directive comes with an optional attribute `ng-messages-include` or just `include` to reference to a template that contains predefined messages to be included.

```html
<script type="text/ng-template" id="my-custom-messages">
  <div ng-message="required">This field is required</div>
  <div ng-message="minlength">This field is too short</div>
</script>

<ng-messages ng-messages-include="my-custom-messages">
...
</ng-messages>
```

However, it turns out that `my-custom-messages` is used to make a `$templateRequest` in order to process the template. This means, it is required to have the predefined template somewhere on a server, to it can be requested.

Of course, one could also just write this template into `$templateCache` in order to prevent Angular making an actual request. But I wonder if it wouldn't be nicer to also allow templates that are just defined in the document already. So instead of always making a `$http` request, a template like `my-custom-messages` can just be included and referenced as it is defined in the document.

Not sure what's the best way to go here, since Angular would then need to decide to either check `$templateCache` and make `$http` call if necessary, or look up the template with the id in the current document. Maybe we could just say that Angular always looks in the document first (then also writes into `$templateCache`) and only if there's nothing present it tries to load it from a server?

Would love to hear your thoughts on this. And if you think it's a good thing, I'd help implementing it.

**Comment by petebacondarwin** [comment]
@PascalPrecht - Have you taken a look at @matsko's imminent update, where you can define your `ng-message` elements dynamically: #10676.

**Comment by PascalPrecht** [comment]
@petebacondarwin having a look now!

**Comment by PascalPrecht** [comment]
@petebacondarwin Okay I've read the issue. It doesn't cover my use case here. Whenever `ng-messages-include` is used, the referenced template is fetched from a server. I'm asking if it would be helpful to let users define templates **within** the document, without putting them on the server at all.

**Comment by matsko** [comment]
Why not just make an inline template using `<script type="text/ng-template" id="remote-file.html">` at the top of the page/view and then use that for `ng-messages-include="remote-file.html"`.

**Comment by matsko** [comment]
Oh sorry, I just noticed your first message.

**Comment by matsko** [comment]
We should figure out why `<script>` or `$templateRequest` isn't working first

**Comment by matsko** [comment]
Looking into it.

**Comment by PascalPrecht** [comment]
@matsko well, `$templateRequest` **is** working. Whenever there's an `include` attribute the directive first tries to load it from a server as we can see right here: https://github.com/angular/angular.js/blob/master/src/ngMessages/messages.js#L297-L299

**Comment by petebacondarwin** [comment]
Are you sure that your online scripts are within the ng-app tag?

**Comment by PascalPrecht** [comment]
@petebacondarwin  @matsko it seems like there's something wrong with Angular `1.3.1` because there it's not working. Here's a plunker with a newer version and it works: http://plnkr.co/edit/HZUJ4c?p=preview

Thank you for your attention, going to close this now!
