### ISSUE TITLE
ng-model not updated when pasting using KeySnail

### ISSUE THREAD

**Issue by zovt** [angular/angular.js#10848]
Hi! I'm using Angular in an application I'm developing, and I've noticed that pasting using the KeySnail shortcut Ctrl-Y doesn't cause the ng-model to update. However, pasting using the right click menu in Firefox 34.0.1 and Angular 1.3.10 does trigger the update, which leads me to believe that there is a conflict between KeySnail and Angular. Is this the right place to report this issue, or should I post it on the KeySnail repo?

Thanks for your help.

**Comment by caitp** [comment]
the input directive will respond to `cut` and `paste` events, if they're available. If keysnail isn't issuing such events, then they won't be seen.
