### ISSUE TITLE
feat(ngMessages): allow using template tags for included messages

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular.js#10846]
Since we're able to predefine messages in `<script>` tags and include them at later time at different places using `ng-messages-include` (more detail here: https://github.com/angular/angular.js/issues/10844), wouldn't it be cool to also being able to use `<template>` tags instead of only hacky `<script type="text/ng-template">` tags? Because, this is what they are designed for. Templates.

In order to clone the contents of a `<template>` we just need to access it's `content` property, so it shouldn't be too hard to implement it.

Wdyt?

(also, Angular 1.x would then have official support for some Web Components technology then :))

**Comment by petebacondarwin** [comment]
So the HTML5 `<template>` element is not supported in IE. So how would we ensure that this works across the board?

If we did do this then we would want to do it for all templates (i.e. for directive and ng-include) too.

**Comment by just-boris** [comment]
It's a good feature for 2.0 version

**Comment by matsko** [comment]
This won't be going into 1.x. Please make a comment inside `angular/angular` for it to go into 2.0.

**Comment by PascalPrecht** [comment]
Oh just seeing that there've been a discussion on that one. Okay, I'm going to open one up on the angular 2 repository.
