### ISSUE TITLE
Grunt tasks slow due to synchronous network calls

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular.js#10859]
Our build is, unfortunately, not lightening-fast and part of the problem is [that line](https://github.com/angular/angular.js/blob/9f7c5ceba74a5e22a706b38dc7f538b6199cb89b/Gruntfile.js#L5) that is executed on each and every Grunt run. This line will trigger call a network call to Google's CDN every time, while probably only needed during the release time.

We should see which expensive operations could deferred to the very last moment (that is, executed as part of a task that needs them instead of executing those operations systematically)

**Comment by Narretz** [comment]
We've introdcued a flag to disable this call: https://github.com/angular/angular.js/commit/6a134605f1904098022f4e25ade67d0a91a52621
Turns out it's not that time intensive anyway
