### ISSUE TITLE
Currency symbol of Lithuania

### ISSUE THREAD

**Issue by Agrumas** [angular/angular.js#10855]
Lithuania adopted the euro on January 1, 2015. [Google closure library](https://github.com/google/closure-library/commit/47bbd7a9b31d962106f9299019fa6f430a97a9b1) already have related changes.
When locales will be regenerated? Maybe PR with changes should be made?

**Comment by pkozlowski-opensource** [comment]
@Agrumas if you can run the re-generation script and send a PR this would be awesome

**Comment by Agrumas** [comment]
@pkozlowski-opensource here you go
