### ISSUE TITLE
ng-click does not work in directive

### ISSUE THREAD

**Issue by ThiagoJem** [angular/angular.js#10863]
I use the structure provided by the yeoman with angular generator.

The ng-click does not work in my application when I put the html directly in main.html. Put an example in [jsFiddle](http://jsfiddle.net/ThiagoJem/5t57n/67/) , When angular use 1.1 on [jsFiddle](http://jsfiddle.net/ThiagoJem/5t57n/67/) operate normally, with 1.2 or higher does not work. In my application I use the angular 1.3.10 .

How could make it work in my application? Can be with some ' compile ' or otherwise who knows.

**Comment by VitalyTomilov** [comment]
You cannot expect your issue to be taken seriously when you say that in jsFiddle everything works but not in your application, only proving that your app is doing something wrong, not Angular.

And you are using Angular 1.1 in your jsFiddle, which is not likely to be changed/fixed at this point, no matter what issues it may have.

**Comment by ThiagoJem** [comment]
I use angular 1.3.10. when i put in jsfiddle the version 1.3.8 or 1.3.10 do not work.

**Comment by Narretz** [comment]
It does look like you have a usage problem here. We want to keep github for features and bugs only - please read the contribution guidelines on where to find support: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md
