### ISSUE TITLE
ng-include prevents the further triggerings of $watch

### ISSUE THREAD

**Issue by yaojingguo** [angular/angular.js#10868]
I am using AngularJS 1.3.10. I have two filles.

main.html:
```
<html>
<head>
<meta charset="utf-8"/>
<script src="/angular.js"></script>
</head>
<body>
<div ng-app="my_app" ng-controller="my_controller">
  <div ng-include="'div.html'"></div>
</div>
</body>
<script>
var app = angular.module("my_app", []);
app.controller("my_controller", ["$scope", function($scope) {
  $scope.num = 0;
  $scope.$watch("num", function () {
    console.log($scope.num);
  });
}]);
</script>
</html>
```
div.html:
```
<div>
  <input type="text" ng-model="num">
  <p>{{ num }}
</div>
```
`console.log($scope.num)` is invoked only once with these two files. If I remove `ng-include` and put the contents of div.html to main.html, I have:
```
<html>
<head>
<meta charset="utf-8"/>
<script src="/angular.js"></script>
</head>
<body>
<div ng-app="my_app" ng-controller="my_controller">
<div>
  <input type="text" ng-model="num">
  <p>{{ num }}
</div>
</div>
</body>
<script>
var app = angular.module("my_app", []);
app.controller("my_controller", ["$scope", function($scope) {
  $scope.num = 0;
  $scope.$watch("num", function () {
    console.log($scope.num);
  });
}]);
</script>
</html>
```
With this change, whenever the content of the input is changed, `console.log($scope.num)` is invoked.

**Comment by Narretz** [comment]
Hi, this is because `ng-include` creates a new child scope. The easiest way to remedy is to put num into its own object: `scope.data = {num: 0}`
Basically, your watch looks on scope 1 for changes to num; but when you set num on scope 2, it is only set on this scope 2 - the change does not propagate to scope 1, because child scopes only read primitives from the parent, but never write them to the parent. (prototypical inheritance)

**Comment by amejiarosario** [comment]
True... Listening for `data` will do. I just verify it... http://plnkr.co/edit/VKsYosyjn9GZv3FWGqKI

**Comment by geosmart** [comment]
now I face the same situation，and have a note for this question [how to $watch ng-include dom ](https://gist.github.com/geosmart/73011f1023efa0117d134f09b50af80f) ,hope this helps someone else
