### ISSUE TITLE
Logs failed to rotate

### ISSUE THREAD

**Issue by anthony-ng** [angular/angular.js#10860]
It is observed that logs have sometimes failed to rotate, resulting in performance issues. While the underlying causes have been fixed, this should be prevented in the future.

Anyone else experienced that?

**Comment by pkozlowski-opensource** [comment]
@anthony-ng I'm not sure I understand... Is it an issue AngularJS? Or one of it websites? Could you please be more specific?

**Comment by pkozlowski-opensource** [comment]
@anthony-ng haven't heard from you and this issue doesn't seem to be AngularJS related so closing.
