### ISSUE TITLE
feat: add custom `angular.hasOwnProperty()`?

### ISSUE THREAD

**Issue by diosney** [angular/angular.js#10874]
It makes sense to have a custom `angular.hasOwnProperty()` method? This way inside an Angular app we can call it instead the native one, protecting from code injection.

I know `sce` manage this well, but this will add another layer of protection when iterating over non-escaped data.

Hope makes sense.

**Comment by caitp** [comment]
what exactly would it protect against?

**Comment by pkozlowski-opensource** [comment]
@diosney like @caitp I'm not sure what would be added benefit / additional protection here. But in any case we are trying to limit helper-like APIs in AngularJS so we are going to skip this one as well....

**Comment by diosney** [comment]
@caitp It could protect against `.hasOwnProperty()` overriding in a field that accept user input and an internal code call `.hasOwnProperty()` to do some checking. 

That way if the user writes `{hasOwnProperty:function(){}}` or something similar in the field, the internal checking will be overriden with the attacker function. The internal code could be something like:

```js
for (var i in obj) {
   if (obj.hasOwnProperty(i)) { // In this line the user override will be executed, not the native method.
   }
}
```

Of course, this only happens if the fields are not protected against code injection, that is why I mentioned `sce` earlier.

I'm accustomed to define my own `hasOwnProperty()` method, with something like this:

```js
var has = function (obj, property) {
  return Object.prototype.hasOwnPropert.call(obj, property);
};
```

to shield the app against this attack, but that is when coding usual webpages, not SPAs and since I'm in the process to learn Angularjs I don't really know if this makes sense here.

@pkozlowski-opensource I understand.
