### ISSUE TITLE
[One Time Binding] Does not reduce $$watchers at the first time

### ISSUE THREAD

**Issue by lovedota** [angular/angular.js#10877]
Hi friends
Please take a look into my comments. http://jsfiddle.net/lovedota/f4neo3rq/
At the first time the $$watchers.count is 3, after I key something in textbox, or click button, $$watchers.count is 2.
It seems a bug of angular one time binding not reducing $$watchers at the first time. Thanks !

**Comment by gkalpak** [comment]
Well, not exactly :)
The watchers are removed correctly from the first time. The "issue" is that the watchers are removed at the end of the $digest, meaning that no more bindings are updated until the next $digest.

Clicking on a button, triggers a new $digest and that is why the bindings are updated in the view. But even without clicking on a button, if you open the console, grad on of the scopes and check it's `$$watchers` property, you will see that it has indeed only 2 watchers.

So, this works as expected (i.e. correctly :)).
