### ISSUE TITLE
angular cannot read property '1' of null  is not a useful error message.

### ISSUE THREAD

**Issue by steowens** [angular/angular.js#10875]
What does this error even mean.  Error message is not actionable.

**Comment by lgalfaso** [comment]
can you create a plunker tat shows the error? without this there is not a lot that can be done

**Comment by caitp** [comment]
betting this is coming from https://github.com/angular/angular.js/blob/master/src/ng/parse.js#L920

**Comment by steowens** [comment]
I think it was caused by the following syntax error on a div tag

<div .... ng-controller="SignupFormController as signupFormCtrl>

Missing trailing quote from ng-controller.

**Comment by caitp** [comment]
angular isn't the one parsing the DOM, that's your web browser.

**Comment by steowens** [comment]
Why is the error message generated in the angular call stack?

**Comment by steowens** [comment]
TypeError: Cannot read property '1' of null
    at angular.js:8411
    at angular.js:7592
    at forEach (angular.js:331)
    at nodeLinkFn (angular.js:7579)
    at compositeLinkFn (angular.js:7075)
    at nodeLinkFn (angular.js:7717)
    at angular.js:7953
    at processQueue (angular.js:13171)
    at angular.js:13187
    at Scope.$get.Scope.$eval (angular.js:14384)

**Comment by caitp** [comment]
Betting on this https://github.com/angular/bower-angular/blob/ecf0435da949836c63ebf048ea8b7710542e33ce/angular.js#L8414-L8416

**Comment by steowens** [comment]
The relevant materials to repro are as follows add the following to index.html

`
<section id="signUpSection" signup-form ng-show="signupVisible()"></section>
`

Add the following to the top level module:
`
.directive('signupForm', function(){
	return {
		restrict: 'A',
		templateUrl: '/static/templates/signup-section.html'
	}
})
`

Add the following to signup-section.html

`
<div class="content" data-section-content ng-controller="SignupFormController as signupFormCtrl>
</div>
`

**Comment by caitp** [comment]
it's pretty clear what the problem is, but we still can't really say where the error happened in your code, we have no way of knowing. best we can do is say "hey, you screwed up your controller name somewhere"

**Comment by steowens** [comment]
Here is the code where the exception gets thrown:

`
 if (isString(expression)) {
        match = expression.match(CNTRL_REG),
        constructor = match[1],
        identifier = identifier || match[3];
        expression = controllers.hasOwnProperty(constructor)
`

It fails on expression.match tossing an error way up the stack.

The input to the function contains the following value in expression:
```
"SignupFormController as signupFormCtrl>
	<div class="
```
So rather than punting the exception up the stack if you were to do something about catching the exeption in match, then wrapping it with contextual information provided by the value of expression you could make the error a thousand times more informative.
