### ISSUE TITLE
$parse gives lexer error parsing this "Ahsan's birthday"

### ISSUE THREAD

**Issue by ahsan-ayaz** [angular/angular.js#10879]
Lexer Error: Unterminated quote at columns 295-303 ["Ahsan] in expression [{....,"title":"Ahsan].

where obj = 
{.....,"title":"Ahsan's birthday"}

**Comment by jamm** [comment]
Version of Angular? Plunkr to reproduce? Expression should be string, not array.

**Comment by lgalfaso** [comment]
I am not able to reproduce this with the given information, would it be possible to get a plunker that shows this issue?

**Comment by lgalfaso** [comment]
After one week without any feedback, I am closing this issue. If you are still experiencing this issue, feel free to reopen it.
