### ISSUE TITLE
Rename ngModel to a more fitting name.

### ISSUE THREAD

**Issue by BenMorganIO** [angular/angular.js#10878]
After using Angular for a while, `ngModel` appears to me to have nothing to do with models. It feels more like a pipeline to transfer data two ways. Its description is:

    The ngModel directive binds an input,select, textarea (or custom form control) to a property on the
    scope using NgModelController, which is created and exposed by this directive.

I feel like a model in Angular should be a place to store and query your data. Tutorials often teach you to manipulate and store your data via `$resource`, but `$resource`, to my understanding, is for HTTP and not for data modelling. `$resource` was also used as the premise for a data modelling course on [EggHead](https://egghead.io/lessons/angularjs-using-resource-for-data-models) which may further the confusion for new Angular developers.

This leads a developer to have to break the separation of concerns from HTTP to models. I've noted, in the previous paragraph, that there's two issues: the first with models being treated as transferring data and the second being the use of `$resource` for models.

Are we able to rename `ngModel` to something else such as `ngTransfer` or `ngScope`. I don't beleve those two names have been used yet and I think it would help improve Angular.

---

I'm posting this issue because I'm finding it exceedingly difficult to understand how to structure, facilitate, and modularize Angular applications. The reasons behind this difficulty is not a lack in tutorials, but in a difficulty in understanding how to store and query large amounts of JSON documents passed down from a server to Angular. It feels like there's a glass roof in the way when it comes to storing JSON with Angular. When googling for models with Angular, I'm receiving the wrong posts about a subject, that inappropriately named.

**Comment by VitalyTomilov** [comment]
Data Model has everything to do with models, and this is how Angular interprets it. Having said so, I agree there is a share of confusion here. Let's consider for a moment the types of binding in Angular...

1. Static binding: ng-bind='value'
2. One-way binding: ng-bind='variable'
3. Once-off binding: ng-bind='::variable'
4. Two-way binding: ng-model='variable'

It is easy to see that somehow item 4 suddenly falls out of what otherwise is a logical way to binding declaration, so one has to ask - why deviate from using ng-bind all-of-a-sudden?

Why not use something that fits the common ng-bind declaration approach? Just like ng-bind was done for once-off binding we can intriduce another symbol in front of the variable to symbolize two-way binding, the only question is - what should it be? Well, there is answer to that too...

There is an existing syntax in Angular for binding in directives:
'@' - constant binding;
'&' - one-way or function binding;
'=' - two-way binding;

Surely, ng-bind must be made into something thats consistent with that... ;)

**Comment by jamm** [comment]
@BenMorganIO ngModel is exactly model, object with data. $resource is REST endpoints wrapper, not related to ngModel at all.

**Comment by pkozlowski-opensource** [comment]
@BenMorganIO as noted by @jamm there seems to be a bit of confusion here... In AngularJS model is any JavaScript object that is exposed on a scope. $resource, on the other hand is just a fancy method of retrieving data (JSON) from a RESTful back-end and converting them to JS objects . Those objects can be exposed on a scope, then, to form model accessible to templates.

Now `ngModel` propagates input values from the DOM to model and from model to DOM. We could always think of a better name but I don't think we can realistically expect to change the name of the one of the most used directives like this. It would be a massive breaking change and we would need to have really good reasons....

Naming things is hard and there is always a risk that a chosen name won't fit mental model of a person mapping this name to some concept. But here we are - a name was chosen and I think we are stuck with it for good...

I'm not sure there is any action we could take here, going to keep this issue opened for few days to see what people think, but yeh, don't hold your breath...

**Comment by BenMorganIO** [comment]
@VitalyTomilov I actually really understood that explanation of ng-bind. For what its worth, I think some of your explanations for the current functionality of ngBind should probably be carried over to the documentation. People getting started with Angular (people like me) would enjoy hearing your explanations. Can the documentation/examples be updated to cover the `@`, `&`, and `::` as well?

@jamm This is exactly what I was thinking as well. From reading the online tutorials, I was deeply confused about how models and data storage in Angular worked without a `$resource`.

@pkozlowski-opensource The definition of a model being that it exposes a scope is a nice definition. You could say that in Rails a model may be something that can expose a table's data to a ruby object. `$resource` maps to a RESTful API? Love that.

A lot of the times, you can identify a name in programming as good or bad is by breaking it down into verbs, nouns, adjectives, adverbs, prepositions, and so on...

When you say model, you're talking about a noun. When you describe models, you begin describing them as a "structure" or "representation". When you go to describe actions or the movement of the data, you use things like "get", "push", "transfer", "grab", "delegate". The argument here is that `ngModel` is used to "propagate". Its used as a verb.

So, I decided to look at [dictionary.com](http://dictionary.reference.com/browse/model?s=t). Maybe we might be able to get away with the `ngModel` name...

You'll notice that the word model can't be used as a verb, but it can be used "without referring to an object" via "modeled, modeling or (especially British) modelled, modelling."

I wonder what the best route is for minimizing the confusion. I'm also wondering what other peoples thoughts are.

**Comment by pkozlowski-opensource** [comment]
@BenMorganIO I don't think there was any intention for the "model" from the ngModel to be a verb. If would like to express it like it verb it would be more like "ng-make-sure-that-JS-object-on-a-scope-and-DOM-are-in-synce-when-any-of-those-change".

**Comment by VitalyTomilov** [comment]
@pkozlowski-opensource, it is true that ng-bind is used as a verb, while ng-model is a noun, which only adds confusion :)

**Comment by jaawerth** [comment]
A lot of the confusion has to do with people thinking of Angular as an MVC, whereas it's more of an MVVM. The ng-model (and other data attached to $scope) is the View-Model part of MVVM.

**Comment by matthewjh** [comment]
I find the name of ngModel to be great just the way it is. Modal as in 'data model' / 'model object'.

**Comment by VitalyTomilov** [comment]
I take it from the last couple posts people didn't really read the first two posts to understand the nature of the problem that's explained, the illogical mixture of ng-model vs ng-bind and the prefix use in model variables vs directive scope variables.

**Comment by BenMorganIO** [comment]
@VitalyTomilov I can agree with that...

**Comment by Narretz** [comment]
I see how this can be confusing. However, given that the term ngModel is established, and has even made its way into angular2, there's no real gain changing the name at this point. Aliasing to a new name also would cause more confusion than anything else. The only thing I think we could do is update the documentation to make things clearer. If anyone wants to provide this update, I'm happy to look at it.
