### ISSUE TITLE
Angular Resourec file problem in I.E 10

### ISSUE THREAD

**Issue by SRIRAM0905** [angular/angular.js#10873]
Hi all,

I am getting the following error while loading  the Angular resource file "v1.3.10" .
" JavaScript runtime error: Unable to get property '$$minErr' of undefined or null reference"
i tried in all possible ways.. its wonder even it not working in Chrome to hese is  my code. can any body help me on this...

<html ng-app="registrationModule">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=10">
    <title>Credit Watch</title>
    <script src="/Scripts/jquery-2.1.3.min.js"></script>
    <link href="/Content/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="/Content/bootstrap/bootstrap-slate.min.css" rel="stylesheet" />
    <link href="/Content/app.css" rel="stylesheet" />
    
    <script src="/Scripts/angular-min.js"></script>
    <script src="/Scripts/angular-route-min.js"></script>
    <script src="/Scripts/angular-resource.min.js"></script>
    
    <script src="/Scripts/bootstrap.min.js"></script>
    
    <script src="/app/registration-module.js"></script>
    <script src="/app/Createeditborrower/borrower-controller.js"></script>
    <script src="/app/utilities/dropdown-repository.js"></script>
    <script src="/app/Createeditborrower/borrower-repository.js"></script>
    <script src="/app/directives/ValidationDirective.js"></script>
    
    

    
    
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="navbar navbar-inverse">
                <div class="navbar-header">
                    <ul class="nav navbar-nav">
                        <li><span class="navbar-brand">Credit Watch</span></li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/Registration/Courses">Browse Catalog</a></li>
                        <li><a href="/Registration/Instructors">Browse Instructors</a></li>
                        <li><a href="/Registration/SearchBorrower">Search Borrower</a></li>
                        <li><a href="/Registration/CreateAccount">Create Borrower</a></li>
                    </ul>
                </div>

            </div>
            <div class="span1" ng-view>
            </div>
        </div>
    </div>
</body>
</html>

**Comment by Narretz** [comment]
It looks like you have typos in your html, where you include angular. It generally is `angular.min.js`, not `angular-min.js` Anyway, questions like these are better asked elsewhere, see the contributing guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md We want to keep github for bugs and features only.

**Comment by SRIRAM0905** [comment]
thanks for ur help, but I am using .NET mvc 5 through nugget... I  will
post mu entire code...
