### ISSUE TITLE
ngClass doesn't support Bootstrap classes which contain '-'

### ISSUE THREAD

**Issue by mrsoto** [angular/angular.js#10889]
Using this directive

ng-class="{text-danger:myForm.razon.$invalid}"

I've got the following error:

Syntax Error: Token '-' is unexpected, expecting [:] at column 6 of the expression [{text-danger:myForm.razon.NaNnvalid}] starting at [{4}].

http://errors.angularjs.org/1.3.10/$parse/syntax?p0=-&p1=is%20unexpected%2C%20expecting%20%5B%3A%5D&p2=6&p3=%7Btext-danger%3AmyForm.razon.NaNnvalid%7D&p4=-danger%3AmyForm.razon.%invalid%7D

Are classes which have '-' character invalid to ngClass?

Later,
mrsoto

**Comment by caitp** [comment]
The expression is an object literal, follows the same rules as JS (not including new extensions to object literals)

**Comment by caitp** [comment]
Aka, you need to wrap the key in quotes
