### ISSUE TITLE
AngularJS 1.4 browser support

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular.js#10885]
What will browser support be like for 1.4?

**Comment by pkozlowski-opensource** [comment]
Same as 1.3, no changes planned in this respect.

**Comment by ilanbiala** [comment]
@pkozlowski-opensource how come browser support was changed from 1.2 to 1.3? I was just expecting some changes because only requiring >=IE10 would probably allow us to add new features and remove some code. Also It's been almost a year since 1.3 initially was put together and I'm sure people are more hopeful of seeing some ES5/ES6 code replacing old code.

**Comment by lgalfaso** [comment]
@ilanbiala 1.4 is designed to be an easy migration for existing 1.3 developers without any fear of browser support
