### ISSUE TITLE
IE9 $stateChangeSuccess triggered one additional time than Chrome

### ISSUE THREAD

**Issue by Sivakumaresan** [angular/angular.js#10891]
I am using v1.3.2 and trying to load my app in IE9 and I see all my controllers getting called twice. But the same works perfect in Chrome, when I try to debug, I see below code in angular.js file triggering one extra $stateChangeSuccess event. Due to current.$$nextSibling not null when the same is null in Chrome.

// Insanity Warning: scope depth-first traversal
// yes, this code is a bit crazy, but it works and we have tests to prove it!
// this piece should be kept in sync with the traversal in $digest
// (though it differs due to having the extra check for $$listenerCount)
if (!(next = ((current.$$listenerCount[name] && current.$$childHead) ||
	(current !== target && current.$$nextSibling)))) {
	while (current !== target && !(next = current.$$nextSibling)) {
	  current = current.$parent;
	}
}

Can someone help?

**Comment by pkozlowski-opensource** [comment]
@Sivakumaresan my _wild_ guess is that you are using an app with routing in HTML5 mode. But this is really just a stab in the dark as there is not enough of the details and it sounds more like a support question that should be better asked elsewhere: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Going to close for now but would be happy to re-open if you can provide a clear, minimal and live reproduce scenario using plunker, jsfiddle or similar.

**Comment by Sivakumaresan** [comment]
Sorry for putting this question in a wrong place. I found the problem, the issue was with my HTML
<div ui-view />
To
<div ui-view></div>

**Comment by Sivakumaresan** [comment]
Sorry for putting this question in a wrong place. I found the problem, the issue was with my HTML
`<div ui-view /> To <div ui-view></div>`
