### ISSUE TITLE
ngModelSet in NgModelController, v1.3.10

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/angular.js#10897]
Hi,

This is a low (no) priority issue, but the ngModelSet function as set under the this.$$setOptions function should probably be written as:

```
ngModelSet = function($scope, newValue) {
        if (isFunction(parsedNgModel($scope))) {
          invokeModelSetter($scope, {$$$p: newValue});
        } else {
          parsedNgModelAssign($scope, newValue);
        }
      };
```

In v1.3.10, the newValue isn't actually used. I don't think it makes any difference in execution, but it does "look" more consistent with how it is later called in the this.$$writeModelToScope function.

**Comment by pkozlowski-opensource** [comment]
@OpenSiteMobile indeed, the `newValue` var is not used which looks odd in a setter, I agree. Would you be up to sending a PR with the proposed change?

**Comment by Narretz** [comment]
newValue is actually used in master
