### ISSUE TITLE
select displaying null values from ng-options collection

### ISSUE THREAD

**Issue by gaui** [angular/angular.js#10892]
When `ng-options` is provided with a collection containing null, it displays `null` (the string) as an `<option>` element.

Isn't this a bug?

One solution is to do, but in my opinion this is a ugly hack:

```
<select ng-model="foomodel" ng-options="f for f in foo | filter: '!null'"></select>
```

Plunker describing the problem:
http://plnkr.co/edit/ZGbkbtQ2xNQuoaowUK5z?p=preview

**Comment by Hrafnkellos** [comment]
:+1:

**Comment by pkozlowski-opensource** [comment]
@gaui what would you expect to be displayed in this case? An empty string? Or the option not present at all? I can imagine situations where having `null` bound to the model would be a valid use-case (but then people would probably have a label)

**Comment by gaui** [comment]
@pkozlowski-opensource The option not present at all or at least an empty string. It makes no sense to display the string `null`?

**Comment by pkozlowski-opensource** [comment]
@gaui in your case it doesn't I agree. But we need to be careful as not to limit other use-cases that are already supported. Honestly I don't think that your solution with a filter is that bad - you just want to skip one option (that happens to be `null`). I don't think we can make select / ngOption automatically filter all the values that would result in the null model as it would break some of the existing use-cases.

Putting it in the backlog but for now I'm not sure what would be the best solution here...

**Comment by gaui** [comment]
Thank you for this. The filter works and solves this problem, but personally I find it strange that when there is a null in the collection, it is displayed as the string 'null'. If null should not be ignored, it should at least be displayed as an empty string. Consider this. Thank you again.

**Comment by VitalyTomilov** [comment]
It is arguable what should be the default action - to show an empty string or to skip it, although i think the former.

If the author has such situation, he can either remove or replace null-s, which is trivial.

**Comment by timo0** [comment]
I have a composite of first- and last name. in some cases the first name is empty/null. an empty string would be nice...

**Comment by Narretz** [comment]
This is browser dependent behavior - FF displays an empty string, Chrome displays null. Since we cannot know what the devs want to display, it's best to let them handle this as they see fit. null can be filtered out if it should not appear at all. null as a display value can be modified on the fly, as seen here: http://plnkr.co/edit/vnSXLKLgL1oMHXWWYyZU?p=preview
