### ISSUE TITLE
Is there a conflict between angular 1.3 and angular-translate 2.5.2

### ISSUE THREAD

**Issue by lovedota** [angular/angular.js#10900]
Hi friends
- Sorry I just want to ask is there anything conflicts with angular 1.3
- This is the code of Version 2.5.2. We can see **Ctrl1 Of Watchers: 3**
http://jsfiddle.net/lovedota/f4neo3rq/

- This is the code of Version 2.2.0 We can see **Ctrl1 Of Watchers: 1**
http://jsfiddle.net/lovedota/bq7jpm3w/

Is it a bug about performance here ? Please help !

**Comment by lgalfaso** [comment]
Hi, I think it is better if you open this issue at angular-translate, they should be able to help you
