### ISSUE TITLE
RFC 6648: SHOULD NOT prefix their parameter names with "X-" 

### ISSUE THREAD

**Issue by arty-name** [angular/angular.js#10903]
[Angular has built-in support for sending XSRF token back in a header](https://docs.angularjs.org/api/ng/service/$http). It uses header `X-XSRF-TOKEN`. [RFC 6648 recommends against using `X-` prefix for non-standard HTTP headers](http://www.ietf.org/rfc/rfc6648.txt). Would be nice of angular to switch to header `XSRF-Token`, recommend its use in the documentation and link to RFC 6648.

**Comment by lgalfaso** [comment]
I am not sure about changing this. RFC 6648 is not a standard nor a proposed standard (as oppose to the http/1.1 standard that defines all headers starting with `X-` as extensions). On top, this can be configured using `$httpProvider.defaults.xsrfHeaderName`. If there was a standard that defines this, then it would be a clear cut that this needs to change, but this is not the case

**Comment by arty-name** [comment]
The points in this RFC look quite convincing to me.

**Comment by lgalfaso** [comment]
Hi, sorry if I was not clear. The question is "is the chance convincing enough to break the app for people that check the use X-XSRF-TOKEN now?". This is a hard question as there is no standard that would make any header name better than the other. Some libraries default to `CSRF-TOKEN` (check that there is a `C` and not an `X`) and some to other header names.

If a standard or a proposed standard was in place, then this is easier to decide, but there is no such a standard. Sorry, I still feel that this change is not worth breaking existing applications. Anyhow, would not oppose if other members decide that this is right and the way to go

**Comment by arty-name** [comment]
I understand your concerns, but it's definitely not the first breaking change Angular introduces. Also it's not subtle: all the POSTs will stop working and it's hard to miss that during the upgrade. The fix on the server side is also minimal: just a string change. 

Would you mind implementing that at least in Angular 2.0 which already promises to break almost everything?

**Comment by lgalfaso** [comment]
Hi, Angular 2 is a different story, but they are tracking the issues at https://github.com/angular/angular

**Comment by arty-name** [comment]
Thanks for the link @lgalfaso!

**Comment by Narretz** [comment]
At this point in the AngularJS lifecycle, this would be a quite an annoying BC with little value, so we should not do it.
