### ISSUE TITLE
Insanity Warning?

### ISSUE THREAD

**Issue by essadji** [angular/angular.js#10908]
(SPOILER ALERT: I'm an angular noob and what follows may just emphasize that very fact ...)
This is what my debugger tells me after throwing an exception:
// Insanity Warning: scope depth-first traversal
// yes, this code is a bit crazy, but it works and we have tests to prove it!
// this piece should be kept in sync with the traversal in $digest
// (though it differs due to having the extra check for $$listenerCount)
if (!(next = ((current.$$listenerCount[name] && current.$$childHead) ||
(current !== target && current.$$nextSibling)))) {
while (current !== target && !(next = current.$$nextSibling)) {
current = current.$parent;
}
Does that mean I have found proof that it IS crazy or at least not working flawlessly?
The actual error in Chrome:
Uncaught TypeError: Cannot read property '$$nextSibling' of null (angular.js:14714)

**Comment by pkozlowski-opensource** [comment]
@essadji please see my [previous comments](https://github.com/angular/angular/issues/493#issuecomment-72012137) regarding reproduce scenario and support questions.

**Comment by pkozlowski-opensource** [comment]
@essadji I haven't heard from you and we can't progress much on the problem without a live reproduce scenario. Closing this issue but happy to re-open when you've got more info.
