### ISSUE TITLE
Retrive math symbols

### ISSUE THREAD

**Issue by msnpr567** [angular/angular.js#10901]
I have to use math symbols in my text box . how can i use this feature in angularjs . Im not getting any toolbars . can any one suggest good plugins or toolbars for getting math symbols like square roots, sigma etc.. thanks in advance

**Comment by pkozlowski-opensource** [comment]
Support questions like this one should be asked elsewhere: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
