### ISSUE TITLE
ngKeypress wont trigger escape key on chrome

### ISSUE THREAD

**Issue by cgarnier** [angular/angular.js#10905]
I cant make work ngKeypress for detect escape key event on chrome.
It s work on firefox.
ngKeydown trigger it. 

Chrome Version 40.0.2214.93 m

**Comment by cgarnier** [comment]
It doesnt work on firefox too. It s saying key 0. Nvm.

**Comment by pkozlowski-opensource** [comment]
I don't think we can do anything about this in AngularJS - the best advice is to use ngKeyup / ngKeydown instead:
* http://stackoverflow.com/questions/719537/capture-an-escape-keypress-in-webkit-browsers
* http://stackoverflow.com/questions/3901063/jquerys-keypress-doesnt-work-for-some-keys-in-chrome-how-to-work-around

**Comment by cgarnier** [comment]
OK ty
