### ISSUE TITLE
Possible extra quotes in Developer Guide - Scope $watch Depths

### ISSUE THREAD

**Issue by mrsoto** [angular/angular.js#10911]
I can't see any diffrence between $watch by reference and $whatch by value in  https://docs.angularjs.org/guide/scope , secction Scope $watch Depths

I fieel that there are more quotes than required in this example.

https://docs.angularjs.org/img/guide/concepts-scope-watch-strategies.png

Later
MS

**Comment by caitp** [comment]
what is confusing?

It is saying:

With the third parameter of `$watch()` not set to true, then if the object has the same identity, it will not result in a change notification even if properties are changed (eg by pushing an array or changing a property of a nested object). If the third parameter is set to true, then it will recursively look at each property of an object, and alert you if any of them change.

**Comment by caitp** [comment]
I feel like the picture illustrates this nicely, but perhaps you could offer suggestions for improving it that we could look at, in a new issue.
