### ISSUE TITLE
"Unknown provider: $compileProvider" when the angular creates an injector of my module with directives

### ISSUE THREAD

**Issue by nervgh** [angular/angular.js#10914]
Hi!

I have two code snippet:
* [first](http://jsfiddle.net/zyvbozj3/) works fine
```js
angular
    .module('app', [])
    .factory('foo', function() {
        return 'test';
    });

try {
    alert(angular.injector(['app']).get('foo'));
} catch(e) {
    alert(e.message);
}
```
* [second](http://jsfiddle.net/zyvbozj3/1/) throws exception
```js
angular
    .module('app', [])
    .factory('foo', function() {
        return 'test';
    })
    .directive('bar', function() {
        return {};
    });

try {
    alert(angular.injector(['app']).get('foo'));
} catch(e) {
    alert(e.message);
}
```

**Question**: Why second code sample throws exception?

Thanks =)

**Comment by petebacondarwin** [comment]
This is because you had not included the `ng` module (which contains the $compile service) in your list of modules to load into the injector.

**Comment by nervgh** [comment]
@petebacondarwin thank you so much :smiley_cat:
