### ISSUE TITLE
nested model is overwriting parent model with the same name

### ISSUE THREAD

**Issue by Maiti** [angular/angular.js#10927]
I have nested tree (from mongodb) like this:

```javascript
var nodes = {"name": "test 1", "children": [{"name": "test 1.1", "children": [{"name": "test 1.1.1", "children": [{"name": "test 1.1.1.1", "children": [/*...*/]}]}]}]}
```

my html:
```javascript
<ol>
    <li data-ng-repeat="node in nodes" data-ng-include="'renderer.html'"></li>
</ol>

<script type="text/ng-template" id="renderer.html">
    <!-- html -->

    <ol data-ng-model="node.children">
        <li data-ng-repeat="node in node.children" data-ng-include="'renderer.html'"></li>
    </ol>
</script>
```

nested models do not have functions for work with db (such as $update)

**Comment by lgalfaso** [comment]
Hi, from the description, it is not clear what the issue. Would it be possible for you to create a plunker?

**Comment by VitalyTomilov** [comment]
By the way, documentation for ngRepeat doesn't include information about the maximum supported depth in nested repeats ;)

**Comment by caitp** [comment]
the nested model will attach to the closest parent form control, and will overwrite whatever was there before --- so, you should use the new interpolated model name feature to work around this

**Comment by caitp** [comment]
> By the way, documentation for ngRepeat doesn't include information about the maximum supported depth in nested repeats ;)

There is no "maximum supported depth", if you recurse indefinitely, you'll get an infdig error for sure, or possibly crash the browser depending on how the recursion is set up. otherwise, you'll just hurt performance as you add more levels

**Comment by Maiti** [comment]
I will have to create a render ```renderer.html``` template for each depth models with different names?

**Comment by lgalfaso** [comment]
@Maiti there are two issues
* resolving a recursive directive (there are many blogs and solution out there, just check any)
* having an isolated directive will allow you not to have to create different templates

One way or another, these are not issues, so please use the appropriate channels to get support, this place is not for question
