### ISSUE TITLE
Animate promises not firing from directive inside a view

### ISSUE THREAD

**Issue by fatlinesofcode** [angular/angular.js#10929]
I've created a custom directive that fires $animate.enter when its created. Works fine until I place the directive within a view and then it only works sporadically. The only way I can get it work is to use a very long timeout or change the parent container to the body. Why?

This is the directive and animation
```
app.directive('ngCustom',  function ($animate, $timeout, $rootScope) {

  return function(scope, element, attrs) {
    var parent = element.parent();//angular.element(document.body);
    $timeout(function(){
      $animate.enter(element, parent);
    });
  }
});

app.animation('.animate-custom', [ function () {
    var obj = {};
    obj.enter = function(element){          
      TweenMax.from(element.find("h1"), 0.5, {delay:1, opacity:0, x:"+=100"});
    }
    return obj;
}]);
```

and a sample app with the directive outside and inside a view

http://plnkr.co/edit/HEDUIAifPEB6TbKNdm48?p=preview

I've also tried the addClass method and have a similar issue

 http://plnkr.co/edit/VIGYpOfu6QIknZJBKEKi?p=preview

**Comment by matsko** [comment]
Add `ng-animate-children` to `<div ng-view>`.

http://plnkr.co/edit/nxu3bF9q1b0gthKNkH7d?p=preview

**Comment by matsko** [comment]
There will be a much better API for this in 1.4.

**Comment by fatlinesofcode** [comment]
sweet, thanks for that. Any docs 1.4 animate api yet?

**Comment by matsko** [comment]
@fatlinesofcode there's a giant refactor going on for 1.4. This refactor will open up more possibilities with animate and it will make parent/child parallel and blocked animations much easier to do. So far it's in the prototypical stage.

**Comment by fatlinesofcode** [comment]
@matsko Looking forward to it, any tie in with whats happening with angularjs-gsTimelines ? https://github.com/ThomasBurleson/angularjs-gsTimelines

**Comment by matsko** [comment]
@fatlinesofcode there is a 100% tie in with that, but the outcome of it will be more automated with how angular works and the DSL will change a bit.
