### ISSUE TITLE
Nested directives generate extra dom elements 

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/angular.js#10921]
When nested *element* directives both use templates and transclude operations, then extra DOM nodes are incorrectly generated:

Consider the html:

```html
<my-test>
  <my-checkbox ng-model="notified">     
    {{user.email}} 
  </my-checkbox>
<my-test>
```

where **both** `myTest` and `myCheckbox` transclude to template areas.

The expected output should be:

```html
<my-test>
 <div class="funny" >
    <my-checkbox>     
      <button >
          <span > ipsum@lorem.com  </span>
      </button>
    </my-checkbox>
 </div>
</my-test>
```

But the actual is:

```html
<my-test>
 <div class="funny" >
    <my-checkbox>
     
      <button >
          <span > ipsum@lorem.com  </span>
     </button>

    </my-checkbox>
 </div>

 <!-- Blank EXTRA DOM incorrectly replicated here -->
 <my-test>
    <div class="funny">
    </div>
 </my-test>

</my-test>
```

See CodePen [Nested Transclusion Errors in Angular](http://codepen.io/ThomasBurleson/pen/MYvdNv) for live sample

**Comment by ThomasBurleson** [comment]
Here is the dirty-simple DDOs:

```js
.directive("myTest", function() {
  
  return {
    restrict:"E",
    replace: false,
    transclude:true,
    template:"<div class='funny' ng-transclude></div>"
  };  
})
.directive("myCheckbox", function(){
  return {
    restrict: 'E',
    replace: false,
    transclude: true,
    template: '<button class="md-button" ng-transclude></button>'
  };
  
});
```

**Comment by lgalfaso** [comment]
Hi, thanks for reporting this. Any chance you can create a plunker that shows the error?

**Comment by rtpmatt** [comment]
I believe the problem is that you did not close your <my-test>

<my-test>
  <my-checkbox ng-model="notified">     
    {{user.email}} 
  </my-checkbox>
<my-test>      <------------------------------

http://plnkr.co/edit/p8CHTY1MMqHOftT6EWJi

**Comment by frfancha** [comment]
@rtpmatt Indeed, I tried to close the tag in the reported CodePen and then the behavior is correct.

**Comment by rtpmatt** [comment]
Set it up here, it is much easier to work with.

http://plnkr.co/edit/?p=catalogue

On Sun, Feb 1, 2015 at 3:55 AM, frfancha <notifications@github.com> wrote:

> @rtpmatt <https://github.com/rtpmatt> Indeed, I tried to close the tag in
> the reported CodePen and then the behavior is correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/issues/10921#issuecomment-72356919>
> .
>



-- 
After years I have updated my sig:
http://www.dilbert.com/dyn/str_strip/000000000/00000000/0000000/000000/90000/2000/700/92768/92768.strip.sunday.gif

Here is the old one for people who are feeling nostalgic:
http://www.foo.be/photo/dilbert/dilbert20012211860201.gif

**Comment by ThomasBurleson** [comment]
@rtpmatt - 
Now it makes sense the directive fires 2x: 1st with content. 2nd withOUT content.
(facepalm)

**Comment by lgalfaso** [comment]
thanks @rtpmatt for spotting this!

**Comment by ThomasBurleson** [comment]
@tbosch - So disregard my bug report. The second dom element was valid (considering my invalid markup) and the transclusion errors are no longer occurring.
