### ISSUE TITLE
selected select option not updating when model change

### ISSUE THREAD

**Issue by KthProg** [angular/angular.js#10939]
Plunker: http://plnkr.co/edit/U0N3VzU1CCb5LZuevBX3?p=preview

Version: 1.3.0-beta.18

The basics are:

3 selects

select 1 is the parent of select 2
select 2 is the parent of select 3

select 1 -> select 2 -> select 3

when select 1's value changes, the options for select 2 change, and are fetched asynchronously.
when select 2's value changes, the options for select 3 change, and are fetched asynchronously.

these asynchronous updates are accomplished using several $watch()es.

$watch("select 1", function(n){
[select 2].getOptions(n);
});

$watch("select 2", function(n){
[select 3].getOptions(n);
});

all the selects have values before their options change

the options for each select look like this:
[{k: 0, v : 'a'},
{k: 2, v: 'c'},
{k: 3, v: 'b'},
... etc.]

select 1's displayed option is correct
select 2's, 3's, 4's, etc. displayed option is NOT correct (it just displays the first option in the list)

the model value matches one of the option values, however that option is not displayed.

**Comment by Narretz** [comment]
Without a reproduction, there's very littel we can do about this. Also, which version of angular are you using?

**Comment by KthProg** [comment]
I will try to reproduce the error minimally in a plunker and will let you know. It will take some time though.
What is the purgatory milestone?

The basics are:

3 selects

select 1 is the parent of select 2
select 2 is the parent of select 3

select 1 -> select 2 -> select 3

when select 1's value changes, the options for select 2 change, and are fetched asynchronously.
when select 2's value changes, the options for select 3 change, and are fetched asynchronously.

these asynchronous updates are accomplished using several $watch()es.

$watch("select 1", function(n){
    [select 2].getOptions(n);
});

$watch("select 2", function(n){
    [select 3].getOptions(n);
});

all the selects have values before their options change

the options for each select look like this:
[{k: 0, v : 'a'},
{k: 2, v: 'c'},
{k: 3, v: 'b'},
... etc.]

The selects look like this:
(A directive where field is in the local scope)

<select ng-model="field.value">
        <option ng-repeat="op in field.options | orderBy: 'v'" value="{{op.k}}">{{op.v}}</option>
</select>

$apply() makes no difference, as a digest cycle is running anyways.

select 1's displayed option is correct
select 2's displayed option is correct
select 3's, 4's, 5's, etc. displayed option is NOT correct

the value matches one of op.k, but the corresponding op.v is not displayed.

**Comment by KthProg** [comment]
Here's a basic plunker showing the issue:

http://plnkr.co/edit/U0N3VzU1CCb5LZuevBX3?p=preview

**Comment by KthProg** [comment]
You probably shouldn't have marked it with that milestone so quickly. Now no-one is taking a look at the issue anymore.

**Comment by Narretz** [comment]
With a title like this, you are only so very slightly increasing your chances that somebody looks at this. Please understand that this is an open source project and our time is limited.

This seems like a valid issue, though.

**Comment by Narretz** [comment]
Well, actually, the [documentation for select](https://docs.angularjs.org/api/ng/directive/select) notes specifically that ngOptions instead of repeated option elements should be used when the model is bound to a non-string value (like in your case, value is an integer). 
Have your tried the same with ngOptions?

**Comment by KthProg** [comment]
The user above tried ng-options with v1.4 and the lists were empty.

**Comment by boyfunky** [comment]
i have the code in my angularjs - ionic project but on iOS9 upon clicking on selecting from the dropdownlist , it doesn't bind to the model unless the user clicks somewhere else. 

<label class="item item-input item-border-bottom item-select">
            <span class="input-label state-input-label">State</span>
              <select name="state"  class="form-control state-options-style" ng-options="state.name for state in states track by state.id" style=" border-top: solid 1px #ccc;" ng-model="user.state">
              </select>
          </label>

wht is wrong wt the code why wouldn't it bind to the model when selected. This happens only on ios9.
