### ISSUE TITLE
$parseFunctionCall tries to dereference null

### ISSUE THREAD

**Issue by zeroflagL** [angular/angular.js#10935]
The  `functionCall` method of the `Parser` prototype contains the following code:

    var args = argsFn.length ? [] : null;
    ...
    return function $parseFunctionCall(scope, locals) {
      ...
      if (args) {
        ...
      }
      ...
      // IE doesn't have apply for some native functions
      var v = fn.apply
                ? fn.apply(context, args)
                : fn(args[0], args[1], args[2], args[3], args[4]);

`args[0]` in the last line would obviously throw an exception if `args` is `null`. Not sure if this code is still needed.

**Comment by lgalfaso** [comment]
The only function that I am aware of that IE does not expose *apply*
to is *console.log*. The code for 1.4 changed a lot, so this is not an
issue there, but I think this is a valid issue in the 1.3.x branch

**Comment by lgalfaso** [comment]
This is no longer an issue with 1.4 and older branches are only open for regression
