### ISSUE TITLE
How to bind json file in ng-grid in button click event 

### ISSUE THREAD

**Issue by jagadiz61** [angular/angular.js#10932]

**Comment by Narretz** [comment]
I guess you'll want to open this issue here: https://github.com/angular-ui/ng-grid

**Comment by jagadiz61** [comment]
Hello Narretz i need one help  add summary row in  footer for all columns

**Comment by pkozlowski-opensource** [comment]
Please direct support questions like this one to one of the [support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question)
