### ISSUE TITLE
$sanitize Bug

### ISSUE THREAD

**Issue by SimeonC** [angular/angular.js#10943]
I have found a bug whereby script and style tags with newlines in them are not correctly removed.
Demo here: http://codepen.io/anon/pen/pvWWjz

Example Snippet:

```html
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px Times; color: #232323; -webkit-text-stroke: #232323}
</style>
<script type="script/javascript">
function bad(){return false;}
</script>

<p>This Should be the first content!!</p>
```

First discovered over at textAngular: https://github.com/fraywing/textAngular/issues/533

I'm going to investigate a bit more and I'll post up if I can figure a solution.

**Comment by lgalfaso** [comment]
mmm... looks like a real bug... should be an easy fix with the provided example

**Comment by SimeonC** [comment]
I manually patched the fix into my sanitise file locally and it works, thanks!
