### ISSUE TITLE
angular directives do not work when i keep them seperately in another js file and use it in the html template.

### ISSUE THREAD

**Issue by ipsitam** [angular/angular.js#10945]
I want to use a date picker directive. So i wrote it in a seperate js file. And called it in html directly. It did not work. but when i put it inside the js which contains my controller it ; its starts working. Unable to figure out where the issue can be. Can anyone help on this?

**Comment by ipsitam** [comment]
.directive('myDatepicker', function ($parse) {
   return {
      restrict: "E",
      replace: true,
      transclude: false,
      compile: function (element, attrs) {
         var modelAccessor = $parse(attrs.ngModel);

         var html = "<input type='text' id='" + attrs.id + "' >" +
            "</input>";

         var newElem = $(html);
         element.replaceWith(newElem);

         return function (scope, element, attrs, controller) {

            var processChange = function () {
               var date = new Date(element.datepicker("getDate"));

               scope.$apply(function (scope) {
                  // Change bound variable
                  modelAccessor.assign(scope, date);
               });
            };

            element.datepicker({
               inline: true,
               onClose: processChange,
               onSelect: processChange
            });

            scope.$watch(modelAccessor, function (val) {
               var date = new Date(val);
               element.datepicker("setDate", date);
            });

         };

      }
   };
})(window.angular);


This works.

**Comment by ipsitam** [comment]
/**
 * 
 */
(function(){
'use strict';
angular.module("exportcompliance", ['assignEccnController']).directive('myDatepicker', function ($parse) {
   console.log("Hiiii--- Directive called!!!")
	return {
      restrict: "E",
      replace: true,
      transclude: false,
      compile: function (element, attrs) {
         var modelAccessor = $parse(attrs.ngModel);

         var html = "<input type='text' id='" + attrs.id + "' >" +
            "</input>";

         var newElem = $(html);
         element.replaceWith(newElem);

         return function (scope, element, attrs, controller) {

            var processChange = function () {
               var date = new Date(element.datepicker("getDate"));

               scope.$apply(function (scope) {
                  // Change bound variable
                  modelAccessor.assign(scope, date);
               });
            };

            element.datepicker({
               inline: true,
               onClose: processChange,
               onSelect: processChange
            });

            scope.$watch(modelAccessor, function (val) {
               var date = new Date(val);
               element.datepicker("setDate", date);
            });

         };

      }
   };
})})();


This does not work

**Comment by Narretz** [comment]
Please read the contributing guidelines. These types of question are ill-suited for Github. If you think you've found a bug, please open a new issue with a complete description.

That said, in your not working example, you've put the directive in a module - maybe you haven't required this module in your app module.
