### ISSUE TITLE
Scope range

### ISSUE THREAD

**Issue by goodseller** [angular/angular.js#10942]
Is there any way I can toggle the outer scope button?
Thanks.

http://plnkr.co/edit/9VwDhOM8Ww5GV838iqds?p=preview

**Comment by Narretz** [comment]
Please read the [contributing guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md). These types of question are ill-suited for Github. If you think you've found a bug, please open a new issue with a complete description.
