### ISSUE TITLE
asdf

### ISSUE THREAD

**Issue by asfafedfsa** [angular/angular.js#10940]
{
  "excludeFiles": ["src/ngLocale/**"],
  "disallowKeywords": ["with"],
  "disallowKeywordsOnNewLine": ["else"],
  "disallowMixedSpacesAndTabs": true,
  "disallowMultipleLineStrings": true,
  "disallowNewlineBeforeBlockStatements": true,
  "disallowSpaceAfterObjectKeys": true,
  "disallowSpaceAfterPrefixUnaryOperators": ["++", "--", "+", "-", "~", "!"],
  "disallowSpaceBeforeBinaryOperators": [","],
  "disallowSpaceBeforePostfixUnaryOperators": ["++", "--"],
  "disallowSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true
  },
  "disallowSpacesInCallExpression": true,
  "disallowSpacesInFunctionDeclaration": {
    "beforeOpeningRoundBrace": true
  },
  "disallowSpacesInNamedFunctionExpression": {
    "beforeOpeningRoundBrace": true
  },
  "disallowSpacesInsideArrayBrackets": true,
  "requireSpaceBeforeKeywords": [
    "else",
    "while",
    "catch"
  ],
  "disallowSpacesInsideParentheses": true,
  "disallowTrailingComma": true,
  "disallowTrailingWhitespace": true,
  "requireCommaBeforeLineBreak": true,
  "requireLineFeedAtFileEnd": true,
  "requireSpaceAfterBinaryOperators": ["?", ":", "+", "-", "/", "*", "%", "==", "===", "!=", "!==", ">", ">=", "<", "<=", "&&", "||"],
  "requireSpaceBeforeBinaryOperators": ["?", ":", "+", "-", "/", "*", "%", "==", "===", "!=", "!==", ">", ">=", "<", "<=", "&&", "||"],
  "requireSpaceAfterKeywords": ["if", "else", "for", "while", "do", "switch", "return", "try", "catch"],
  "requireSpaceBeforeBlockStatements": true,
  "requireSpacesInConditionalExpression": {
    "afterTest": true,
    "beforeConsequent": true,
    "afterConsequent": true,
    "beforeAlternate": true
  },
  "requireSpacesInForStatement": true,
  "requireSpacesInFunction": {
    "beforeOpeningCurlyBrace": true
  },
  "validateLineBreaks": "LF"
}

**Comment by shindoh** [comment]
humm...
