### ISSUE TITLE
publish event before router selects next view

### ISSUE THREAD

**Issue by hesamwls** [angular/angular.js#10946]
Hi
I'm trying to implement some kind of dynamic routing using Angular.
by dynamic I mean, user clicks on a link that refers to a possibly new view.
I have to check if that view exists in somewhere and if exists, load all dependencies , etc ...
everything's ok except that I need a listener just before router is selecting the next view. 
so I can safely register a listener and do all my work there.
something like:
$rootScope.$broadcast('$beforeRouteUpdate');
right in the beginning of prepareRoute() will do the trick.

thanks

**Comment by frfancha** [comment]
What about $locationChangeStart ?

**Comment by pkozlowski-opensource** [comment]
I believe that we've got all the mechanism already in place to handle the described use-case:
* synchronous events ($location / $route change start / success)
* `resolve` property of a route if some work needs to be done asynchronously

Closing based on the above but I'm happy to reopen if @hesamwls can provide a detailed description of his use-case + info why the current mechanism are not sufficient.
