### ISSUE TITLE
Suggestion / Feature request

### ISSUE THREAD

**Issue by DumboJet** [angular/angular.js#10947]
I think it would be nice if you could return a class type from :

    angular.module('myModule')

... so that, one developing directives/services/etc could extend its prototype like so:

    NgModule.prototype.addNgHiddenDirective = function(){
        return this.directive('ng-hidden', ...);
    }

...and use chaining for including directives instead of doing things like this:

    function addNgHiddenDirective(module){
          module.directive('ng-hidden', ...);
    }

Right now I think there is no way to achieve this in a clean and modular way, and including directives (and other stuff) in applications seems quite ugly.
At least, this is my take on this.

Thanks! :)

**Comment by frfancha** [comment]
A module is a singleton. So what?

**Comment by pkozlowski-opensource** [comment]
> In my humble opinion, the new module thing seems like an overkill for just to ship a single directive and the function thing seems too ugly

Modules in AngularJS 1.x are "cheep" so creating a module for things to re-destribute is definitively not an overkill - it is the way to go.
