### ISSUE TITLE
$ControllerProvider is no longer easily overridden

### ISSUE THREAD

**Issue by cspeper** [angular/angular.js#10951]
The inline [$ControllerProvider](https://github.com/angular/angular.js/blob/master/src/ng/controller.js) documentation notes that 

``` javascript
  * Its just a simple call to {@link AUTO.$injector $injector}, but extracted into
  * a service, so that one can override this service with {@link https://gist.github.com/1649788
  * BC version}.
```

Back in V1.0, this was fairly accurate, and the $ControllerProvider could be overridden fairly easily with a decorator.  With some more recent updates, the scope of this service has grown considerably and overriding it now requires duplicating a lot of additional behavior.

Can this service be refactored to allow the logic for resolving the controller's constructor to be targeted for overriding?

Specifically, this section: 

``` javascript
expression = controllers.hasOwnProperty(constructor)
    ? controllers[constructor]
    : getter(locals.$scope, constructor, true) ||
      (globals ? getter($window, constructor, true) : undefined);
```

represents the original logic of the service, which seems to have been broken out to allow for such an override.

I can think of a couple of solutions:
1. Create a separate $ControllerResolver service that resembles the original $ControllerProvider service, which $ControllerProvider would inject.
2. Allow the resolution logic to be configured, with a new method like:

``` javascript
  this.setResolver = function(customResolver) {
    resolver = customResolver;
  };
```
1. Move the recently added behavior in the $ControllerProvider somewhere private, or break it out into its own service.

I'm happy to get to to work on a pull request if I can get some guidance on what is the solution most likely to be approved.

**Comment by lgalfaso** [comment]
Hi, I think that knowing what the use case is would help a lot. BTW, I would start by writing a proposal to the angular-dev mailing list and get some feedback

**Comment by cspeper** [comment]
Hi, 
Thanks for the advice.  I'll reach out to the dev list.

My use case is pretty particular.  I am passing a function that returns a constructor for a controller to `module.factory` instead of a function that returns a controller to `module.controller` when defining my controllers. 

For example, in coffeescript:

```coffeescript
app.factory "MyCtrl", (BaseCtrl, modalFactory, $state) ->
  class MyCtrl extends BaseCtrl
    constructor: (@$scope, user ) ->
      super
      @$scope.user ?= user
```

This allows me to use class inheritance and to use a somewhat cleaner class definition in Coffeescript.

However, in order to support this dual layer of dependency injection, I'd need to override the existing controller resolution logic:

```javascript
expression = controllers.hasOwnProperty(constructor)
    ? controllers[constructor]
    : getter(locals.$scope, constructor, true) ||
      (globals ? getter($window, constructor, true) : undefined);
```

to do something like:

```javascript
if (controllers.hasOwnProperty(constructor))
    expression = controllers[constructor];
else if ($injector.has(constructor))
    expression = $injector.get(constructor);
else
    expression = getter(locals.$scope, constructor, true) || getter($window, constructor, true);
```

I understand this breaks from the normal angular way, but it does have its advantages.

**Comment by Narretz** [comment]
Closing because this is a very rare use case.
