### ISSUE TITLE
why the variables do not exist

### ISSUE THREAD

**Issue by humingx** [angular/angular.js#10957]
**issue:**
the version of angularjs is 1.2.9 , 
when i write a test file, 
![screenshot from 2015-02-03 18 06 30](https://cloud.githubusercontent.com/assets/7880018/6035434/66333c38-ac6e-11e4-8463-1b5f7d54e640.png)
---
**the html file**
![screenshot from 2015-02-03 18 08 57](https://cloud.githubusercontent.com/assets/7880018/6035437/785994e8-ac6e-11e4-956b-4d330ece74e7.png)
---
**but when i debug in the firefox**
![screenshot from 2015-02-03 18 06 55](https://cloud.githubusercontent.com/assets/7880018/6035445/8e8e46aa-ac6e-11e4-8857-49e191410471.png)

**Comment by pkozlowski-opensource** [comment]
@humingx it is impossible to say just based on the provided info. At any rate this typo of support questions should be asked using one of the support channels, and not as part of GitHub issues, see https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
