### ISSUE TITLE
ng-pattern show valid on invalid input

### ISSUE THREAD

**Issue by lazychino** [angular/angular.js#10958]
while doing a registration form i cant with this problem, a pattern with `\w` was valid having non-alphanumeric characters, so did some test and found that ng-pattern is doing a partial match like running RegExp.test(str), so shows valid while some part of the input maches the pattern

here is what happening -> http://plnkr.co/edit/uLE9P41Yg5lyyDH9zvDu?p=preview

I first notice on 1.2.26, did plunk with 1.4 still happening

**Comment by matsko** [comment]
`\w` only matches **one or more characters**. Not the entire string. If you add `^` and `$` (so `^\w+$`) then the pattern validation works as expected. http://plnkr.co/edit/HUEldIu1VVOGd1CROp4L?p=preview

**Comment by lazychino** [comment]
ok got it, thanks :+1:
