### ISSUE TITLE
1.3 CORS problem with iOS8 safari - works with jQuery.ajax, not angular $http.get

### ISSUE THREAD

**Issue by rkoberg** [angular/angular.js#10954]
This is probably a Safari bug or idiosyncrasy, but even after the latest update it is still not working in angular. For some background you see this thread: https://groups.google.com/forum/#!topic/angular/3hP4JpTHLYY

Not sure the best way to present this because there would need to be server side setup to handle a withCredentials call from a specific domain. My apache .htaccess CORS config is pasted below. This is further complicated because my local testing shows it working in things like the devtools iPad emulator and Safari's emulation mode of iOS 8x. It is only when it is on the server where I can test with the iPad that it fails. I can't test locally from an iPad because I would need to set a /etc/hosts file or something to my local dev domains. For local development I use grunt to serve the angular app and apache to serve the api end point app. My /etc/hosts file for local dev is configured to give these sites the same cookie domain (important for CORS withCredentials) -- for example: www.mylocal.dev and api.mylocal.dev. For production, I use an AWS S3 to serve the angular app and Elastic Beanstalk managed EC2s for the app servers.

Another thread related to this was opened today -- https://groups.google.com/forum/#!topic/angular/B5ZCYUhPxd8 . So there are at least three people with this problem. That is the code works in all browsers except Safari in iOS 8+. It works in Chrome on iOS 8+. It works with Safari in iOS 7x.

My last post to that thread shows working code for jQuery and not working code for Angular. For the Angular code, the Authorization header is set like so:

```
(function () {

  'use strict';

  AuthRequest.$inject = ['User'];
  function AuthRequest(User) {

    return {
      request: function($config) {
        if (User.getAuth()) {
          $config.headers.Authorization = User.getAuth();
        }
        return $config;
      }
    };
  }

  angular.module('app.user.auth', [
  ])
    .factory('AuthRequest', AuthRequest)
  ;
})();
```
Making a request with an Authorization header when the server has not yet responded with a session cookie fails. In other words, when authenticating a user at login or on page load to see if their session is still active.

.htaccess CORS config:
```
# with AJAX withCredentials=true (cookies sent, SSL allowed...)
SetEnvIfNoCase ORIGIN (.*) ORIGIN=$1
Header always set Access-Control-Allow-Methods "POST, GET, PUT, OPTIONS, PATCH, DELETE"
Header always set Access-Control-Allow-Origin "http://www.myserver.com:9002"
#Header always set Access-Control-Allow-Origin "%{ORIGIN}e"
Header always set Access-Control-Allow-Credentials "true"
Header always set Access-Control-Allow-Headers "X-Accept-Charset,X-Accept,Content-Type,Authorization,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers"
Header always set Access-Control-Max-Age "2000000"
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L,E=HTTP_ORIGIN:%{HTTP:ORIGIN}]
```

**Comment by pkozlowski-opensource** [comment]
@rkoberg since it is hard to reproduce in a plunker, could you please investigate what is different when it comes to the request sent via $http vs. one sent from jQuery? At the end of the day $http just sents a XHR request so we should be able to have the same one as coming out of jQuery.

**Comment by pkozlowski-opensource** [comment]
@rkoberg haven't heard from so closing. The only reasonable way of moving forward on this one would be to compare requests coming from the 2 frameworks but we need you for this...

**Comment by yadvendar** [comment]
FYI
I was also facing a similar issue. Angularjs app calling the API server (CORS). All browsers were working fine except for Safari on iOS and OSX, that too only when Safari called the API server on HTTPS. Safari calling API server on HTTP worked fine. It was not an angular specific issue as jquery ajax implementation also reproduced the issue. Finally, when the response header - "Connection": "close" was removed (connections were kept alive), it started working for Safari with HTTPS. 

Hope this will help anyone stuck with the same issue.
