### ISSUE TITLE
Automatically resolve promises

### ISSUE THREAD

**Issue by nkt** [angular/angular.js#10956]
I want to suggest automatically resolve promises inside `ng-repeat`, `ng-bind` and other directives with the same behavior.
Now I have to write something in this way:
```js
$http.get('/api/users').success(function(users) {
    $scope.users = users;
});
```
It would be better to replace this with:
```js
$scope.users = $http.get('/api/users');
```

**Comment by matsko** [comment]
This used to be the case early on with Angular (something called Promise unwrapping), but it lead to a lot of issues. There's a full description here as to why it was removed: https://github.com/angular/angular.js/pull/4317

**Comment by pkozlowski-opensource** [comment]
This used to work as you are proposing and was removed later on as it was causing all sort of confusion and corner cases (ex.: what to do when a promise fails?). I don't think we want to go back on this one.

**Comment by nkt** [comment]
@pkozlowski-opensource promises allows to chain methods:
```js
$scope.users = $http.get('/api/users').error((e) => console.error(e));
```

**Comment by lgalfaso** [comment]
@nkt as @pkozlowski-opensource stated before, this was the original behavior in Angular 1.0, this behavior caused too many issue and side-effects that developers were not expecting. The current behavior is simpler to understand and works better. You just have to do

```js
$http.get(...).then(
function(users) {
  $scope.users = users;
}
```
