### ISSUE TITLE
$parse regression in 1.4.0-beta.3

### ISSUE THREAD

**Issue by alexlamsl** [angular/angular.js#10968]
```
var s = {c:function() {return {b:1}}};

// this works as before
$parse("[a=c(),d=a.b+1]")(s)
// [ { b: 1 }, 2 ]
s
// { c: [Function], a: { b: 1 }, d: 2 }

// this used to give the same result as above
$parse("e=1;[a=c(),d=a.b+1]")(s)
// [ { b: 1 }, 1 ]
s
// { c: [Function], e: 1, a: { b: 1 }, d: 1 }
```

**Comment by lgalfaso** [comment]
Thanks for reporting this! I do not think this is a regression, but for sure worth fixing.

The change should be simple, do not lazy construct each of the elements in the array and enforce a strict left-to-right initialization

**Comment by alexlamsl** [comment]
Tested and working as expected - thanks!

On an unrelated note, I notice one of them don't produce `inputs`

```
> $parse("[d=a(),e=d.b+1]")
{ [Function]
  inputs: [ [Function], [Function] ],
  literal: true,
  constant: false }


> $parse("f=0;[d=a(),e=d.b+1]")
{ [Function] literal: false, constant: false }
```

Is this expected behaviour?

**Comment by lgalfaso** [comment]
not producing inputs is the expected behavior for expressions with multiple statements. Adding this inputs would be a simple change, but have some small side-effects that need to be properly evaluated. Anyhow, now that the PR landed, this issue can be closed.

Once again, thanks for reporting this
