### ISSUE TITLE
$http cache hardcoded

### ISSUE THREAD

**Issue by glispajon** [angular/angular.js#10961]
Is there a reason why https://github.com/angular/angular.js/blob/master/src/ng/http.js#L1032-L1037 looks the way it does?

``` javascript
 if ((config.cache || defaults.cache) && config.cache !== false &&
(config.method === 'GET' || config.method === 'JSONP')) {
cache = isObject(config.cache) ? config.cache
: isObject(defaults.cache) ? defaults.cache
: defaultCache;
}
```

At least OPTIONS and HEAD should be allowed to use cache, and in general wouldn't it be better to be able to configure what methods to cache and maybe have GET and JSONP as the default ones?

**Comment by petebacondarwin** [comment]
@pkozlowski-opensource - can you take a look at this and give your view?

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin I think that @glispajon is right - there are already multiple similar issues opened (ex.: should headers be part of the cache etc.). the bottom line is that with the current design users got vary limited value over what / when gets cached. I must say that I'm not entirely happy with the current cache strategy for $http as indeed it is fairly arbitrary.

The "right" thing to do would be to move all the caching logic to a $http decorator that users could override but this might be non-trivial. The alternative is to have a new config param in the config object passed to $http calls. This new param ('cacheStrategy' ?) would be a function that could generate a key to be used in the cache (this function would take a config + request / response object) and generate a key to be used in a cache. Not sure if this would cover all the use-cases people are coming with but I was planning to have a deeper look into caching strategy in 1.5.

Let's move it to the 1.5 milestone?

**Comment by petebacondarwin** [comment]
SGTM

**Comment by Narretz** [comment]
Duplictae, Special cases are tracked elsewhere [allow other methods](https://github.com/angular/angular.js/issues/3031), [include headers in cache decision](https://github.com/angular/angular.js/issues/5028)
