### ISSUE TITLE
ng-model doesn't change the value of input tag (case type is hidden)

### ISSUE THREAD

**Issue by m-amr** [angular/angular.js#10966]
i have an input tag type='hidden' ng-model='name' 
Inside the controller i changed the value of name variable 
$scope.name='test-1';
i found that the value attribute in this input tag is not updated
but it works when i used ng-value
input tag type='hidden' ng-value='name'

Should ng-model directive update the value attribute of the input tag (in case type is hidden ) ?

**Comment by pkozlowski-opensource** [comment]
@m-amr I've [answered your question already](https://github.com/angular/angular/issues/536#issuecomment-72863852) and the response is still the same - ngModel does not and should not work on hidden inputs.
