### ISSUE TITLE
Check var in current $scope

### ISSUE THREAD

**Issue by giolvani** [angular/angular.js#10962]
Hi, I need to check if a var is defined in current $scope, and not in $parent. Let's me try explain it better..

I have a factory that checks a custom var called 'hasChange', and this var can be undefined in my current $scope, but when I check if it is undefined, it always is defined, because this var is always in my $parent scope.

There is any way to check var is defined ignoring the $parent scope?

I tried $scope.this, but it also have $parent value.

**Comment by pkozlowski-opensource** [comment]
@giolvani scope is just an ordinary JavaScript object so you can check presence of a variable by using any standard JS tricks, ex.: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty

**Comment by giolvani** [comment]
Ouuch...
I really doesn't had attention for this way.

Thanks a lot
