### ISSUE TITLE
' redirectTo ' problem in $routeProvider

### ISSUE THREAD

**Issue by yancd** [angular/angular.js#10963]
I config app with code below in page **http://example/bb**.
```js
app.config(['$routeProvider',function($routeProvider){
					$routeProvider.when('/',{
						templateUrl:'xx-tpl',
						controller:'xxCtl',
					}).when('/aa',{
						templateUrl:'aa-tpl',
						controller:'aaCtl'
					}).otherwise({
						redirectTo:'/'
					});
}]);
```
when i access the http://example/bb from other url such as http://example/cc, it can redirect to 'http://example/bb#/' and use controller xxCtl. While in this page with url 'http://example/bb#/' or 'http://example/bb#/aa' , it redirect to 'http://example/bb#' instead of 'http://example/bb#/' and it doesn't use xxCtl. I think it should redirect 'http://example/bb' to 'http://example/bb#/' no matter what current url is.

**Comment by bruunofco** [comment]
Hello, how are accessing this url? link or by typing the url?
try typing http://example/#/bb and check that will call the correct controller.
If you want to remove '#' from your url use $locationProvider.html5Mode(true);

Hope this helps

**Comment by diestrin** [comment]
I think this explain the issue. http://plnkr.co/edit/IVdMvjqZiiXw7QnH27Va?p=preview
I'm trying to track down the issue.

**Comment by bruunofco** [comment]
Hello,

The link is wrong, you should always use '#' before.
Do you have a .htaccess file to always redirect to the main file?
That would solve the problem when someone enter an invalid URL.

see example
http://plnkr.co/edit/B5nQtVsJWViJSRThd1Y5?p=preview

**Comment by pkozlowski-opensource** [comment]
@diestrin @bruunofco is right, you need to use links that matches your URL schema. In practice it means that you need to have # in hashbang mode.
