### ISSUE TITLE
Directive: when templateUrl is a nonexistent url then the whole app is loded instead of the template

### ISSUE THREAD

**Issue by jrencz** [angular/angular.js#10965]
I just had the followin experience:
I have created an element directive like this:

```
(function () {
    'use strict';

    angular
        .module('myDirective', [])

        .directive('myDirective', function () {
            return {
                restrict: 'E',
                templateUrl: '/templates/my-directive',
            };
        });
})();
```

And I misped the `temlateUrl`. There should be `.html` at the end off course.
The strange thing that happened was that my whole application was loaded ad many times as this directive was used

I off course had `WARNING: Tried to load angular more than once.` and `Uncaught Error: [ng:btstrpd] App Already Bootstrapped with this Element '&lt;html class="ng-scope" lang="en-US" dir="ltr"&gt;'` but I don't find this particular behaviour very intuitive. There might have been a better solution for handling nonexistent templates. Or at least I'd expect for angular NOT to load the app again.

Environment details:
angular 1.3.11
templateCache is on

**Comment by pkozlowski-opensource** [comment]
@jrencz isn't your web-server configured in the way that non-existent URLs are resolved to index.html or something? Is your server correctly returning 404 for  /templates/my-directive ?

If you get index.html and 200 as a response, I don't think AngularJS has any way of knowing that this particular template is missing...

**Comment by jrencz** [comment]
Ok, you're right: 'Error: [$compile:tpload] Failed to load template: /templates/myy-directive.html' when I misspell the template file name but `.html` it there.

It's due to my `connect` setting.

**Comment by mzgol** [comment]
We redirect files without extensions to `/index.html` (this is needed for `pushState`-based routing to work) so this was expected if the extension was missing. :) Angular couldn't behave differently here.
