### ISSUE TITLE
npm doesn't install node_modules

### ISSUE THREAD

**Issue by ggamzang** [angular/angular.js#10974]
I tried "npm install" in angular-phonecat folder.
but, it executed only "bower install" like below.

![20150205_171120](https://cloud.githubusercontent.com/assets/10557013/6056854/22b7545c-ad5a-11e4-8ad1-2d2cceeeaa1e.png)

so, i tried "npm install [modulename]". It worked and created node_modules directory.
why does it work like this?

{
  "name": "angular-phonecat",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-phonecat",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "1.3.x",
    "angular-mocks": "1.3.x",
    "jquery": "~2.1.1",
    "bootstrap": "~3.1.1",
    "angular-route": "1.3.x",
    "angular-resource": "1.3.x",
    "angular-animate": "1.3.x"
  }
}

**Comment by pkozlowski-opensource** [comment]
@ggamzang could you please open this issue in the respective repo: https://github.com/angular/angular-phonecat ? Thnx!
