### ISSUE TITLE
Milestones 1.4.0-beta.2 / 1.3.11 was closed, but still uncompleted

### ISSUE THREAD

**Issue by Tobyee** [angular/angular.js#10971]
![qq 20150205111425](https://cloud.githubusercontent.com/assets/1400574/6054456/41430cb8-ad28-11e4-8b77-830d6521de32.jpg)

See [Milestones 1.4.0-beta.2 / 1.3.11](https://github.com/angular/angular.js/issues?q=milestone%3A%221.4.0-beta.2+%2F+1.3.11%22)

Are you guys going to ignore the issues or something ?

**Comment by VitalyTomilov** [comment]
Yes, totally, and they are gonna start by ignoring this post of yours. Welcome to Angular development ring (of insanity). :)

**Comment by lgalfaso** [comment]
@Tobyee thanks for bringing this up, just moved the issues to a proper milestone.

@VitalyTomilov please be professional.
