### ISSUE TITLE
watching scope 2-way bound to directive not working

### ISSUE THREAD

**Issue by jangbora** [angular/angular.js#10973]
From controller, I need to watch variable which is 2-way bound to directive scope.

As I tested in JsFiddle, angular 1.1 works well, but angular1.2 does not.

How can I fix it?

http://jsfiddle.net/4091qg9r/3/

**Comment by Narretz** [comment]
I don't know exactly when it changed, but in 1.2.x and beyond, only the template of an isolated scope directive has access to the isolated scope (+ bindings) In your example, ng-click operates on the controller scope, but addItem is on the isolate scope. See https://code.angularjs.org/1.4.0-beta.0/docs/guide/migration#isolate-scope-only-exposed-to-directives-with-scope-property

**Comment by jangbora** [comment]
Thank you very much!
