### ISSUE TITLE
$animation.enter/leave don't trigger onDone/onCancel callback.

### ISSUE THREAD

**Issue by dorellang** [angular/angular.js#10972]
The docs say that when you define a javascript animation you can define an onDone/onCancel callback in order to do some cleanup when the animation is done. For instance:
```
var ngModule = angular.module('YourApp', ['ngAnimate']);
ngModule.animation('.my-crazy-animation', function() {
  return {
    enter: function(element, done) {
      //run the animation here and call done when the animation is complete
      return function(cancelled) {
        //this (optional) function will be called when the animation
        //completes or when the animation is cancelled (the cancelled
        //flag will be set to true if cancelled).
      };
    },
    ...
  };
});
```

However, in [this plunker](http://plnkr.co/edit/RzT5fjJ3pEXvTpgglMqD) the returned callbacks are never called (I think it should log 'animation done' when toggling but it doesn't).

**Comment by dorellang** [comment]
Finally I could get the callback invoked by calling `done()` with `$timeout`.

Oddly enough, now it seems that  the leave finished callback is called twice (see [this plunker](http://plnkr.co/edit/pInr3wfr7xzLTBkwrC2F)), so I guess something fishy is going on anyway.

**Comment by dorellang** [comment]
Further testing showed me that the callbacks (except for the second call to the leave callback) don't wait for the CSS animation to finish, as shown in [this plunker](http://plnkr.co/edit/Ot5kVT5ThLoqit89CKku). I think this could be workarounded by writing a wrapping animation which then triggers the css animation and sets the action to do after animation completes through the promise, but this is cumbersome... it should work out of the box IMO

**Comment by dorellang** [comment]
So far, so good, I've done the workaround I said and it works :) But for some reason the "ng-animate" class is not removed after finishing the enter animation. So, it's not like it matters in practice, but it's weird and unexpected nevertheless.

**Comment by Narretz** [comment]
It looks like this specific part of the docs / code was removed in 1.4. I'm gonna close this issue. If this is still a problem in 1.4.x, or if there's an API missing, please open a new issue. Thanks!
