### ISSUE TITLE
Scope receives $destroy event twice

### ISSUE THREAD

**Issue by ttencate** [angular/angular.js#10979]
Plunk: http://plnkr.co/edit/jRfQYftZSykHJZdjpDxR?p=preview I couldn't find a simpler way to reproduce this.

From what I can tell, `ngView` destroys the scope when the route changes, which broadcasts a `$destroy` event on the scope of the view. Then it calls `$animate.leave()` on the view element, which triggers `$destroy` on the element. That somehow ends up sending another `$destroy` event to one of the scopes, despite the first line of the `$destroy()` method bailing out if `$$destroyed` is set -- so I'm guessing `$$destroyed` isn't correctly set/inherited on all the scopes that received the first `$destroy` event.

**Comment by lgalfaso** [comment]
In the 1.2 branch, listeners should be able to handle multiple calls to destroy, your example is just one of many ways on how this is possible. In the 1.3 branch, this behavior changed and is no longer possible for the $destroy event to be generated twice in the same scope.

This is not going to be backported to the 1.2.x branch, so I am closing this
