### ISSUE TITLE
Ng-if for about 3ms is rendering content into the DOM twice -- Intended behavior?

### ISSUE THREAD

**Issue by bobber205** [angular/angular.js#10984]
I was tasked with adding an iframe tag for analytics tracking for a 3rd party consumer of our app. I added it when conditions, using an ng-if, to the appropriate part of the document like so.

```html
<div ng-if="mode == 'success'>
<iframe ng-if="campaignTag == 'testData'" src="https://somesitehere.org">
</div>
```

Whenever mode is 'success', but campaignTag does not match 'testData', I get a "Canceled" request in the dom.

Is this expected behavior? I would expect unless my inner ng-if conditions were satisfied that the iframe would NEVER appear in the dom.

**Comment by VitalyTomilov** [comment]
Nothing good would be expected when your tags contain srongly defined attributes, that's for sure...
````
ng=if="mode == 'success'
````

**Comment by bobber205** [comment]
Ha. Yes that's very correct. I was typing this code hastily by hand and didn't copy pasta. :)

**Comment by lgalfaso** [comment]
Hi, you should use `ng-src`
