### ISSUE TITLE
Angular plans for Virtual DOM

### ISSUE THREAD

**Issue by demisx** [angular/angular.js#10993]
Hi. I am an active member of Southern California Angular community. I've noticed the trend lately that Angular starts loosing traction to ReactJS. The impression that's being formed in the minds of developers that Angular is too slow for large apps due to its direct DOM manipulation. 

Are there any plans for Angular to switch to the virtual DOM in the view layer similar to how ReactJS does this? I think this would be a huge win that will minimize the number of developers we loose to frameworks like React. Please share your vision, so I can share it with the SoCal Angularians. 

Thank you.

**Comment by mod3st** [comment]
+1

**Comment by Narretz** [comment]
This is not something that will happen in angular 1.x. I'll suggest you'll open this issue (or search for related issues) in https://github.com/angular/angular/issues (the angular 2.x repo).
