### ISSUE TITLE
Filter : issue when some properties are null (deep object filter)

### ISSUE THREAD

**Issue by ElephantRose** [angular/angular.js#10991]
When using filter (filterFilter function) with deep object and optional properties (means nullable), filter throws an error "TypeError: Cannot read property 'x' of null '
I believe that a null value property check is missing when dealing with object
By the way the orderBy filter is not concerned by this issue.

I solved it in my project by replacing the following line in the deepCompare function used by filterFilter function.

```javascript
var actualVal = matchAnyProperty ? actual : actual[key];
```
with 

```javascript
var actualVal = (matchAnyProperty || actual == null) ? actual : actual[key];
```

The issue is on `actual[key]` 

Angular version : 1.3.12
Reproducible: Always
Jsfiddle : http://jsfiddle.net/k25y4bg2/

**Comment by gkalpak** [comment]
This is a valid issue. I have left a comment on what I consider to be an appropriate fix at https://github.com/angular/angular.js/pull/10992#issuecomment-73227008
