### ISSUE TITLE
input type="number" without angular's validations

### ISSUE THREAD

**Issue by ericmdantas** [angular/angular.js#10997]
Is there a way to use an input with type "number" and not have angular to validate it?

I want the input to be number so when the user focus it on mobile, it'll show the keyboard as numbers only.

But on the other hand, I want to do my own validations on the value of such input; like, not allowing anything but numbers and stuff like that.

I'm using version 1.2.26, by the way.

Thanks!

**Comment by jbedard** [comment]
"not allowing anything but numbers" is HTML5 (http://www.w3.org/html/wg/drafts/html/master/forms.html#number-state-%28type=number%29). Even without angular (modern) browsers will do the same validation...

**Comment by ericmdantas** [comment]
Actually, what angular [will allow characters other than digits, but the ng-model won't be valid/displayed/filled](http://plnkr.co/edit/gHUgMyQ5W9yLjYwYjwXe?p=preview). That's why I'm not allowing the user to insert non digits by myself.

**Comment by jbedard** [comment]
Again that's HTML5, not angular... An input[type=number] might allow non-numeric keys to be typed but fetching the value from that input will give a blank string unless it is a valid number.

**Comment by ericmdantas** [comment]
>  An input[type=number] might allow non-numeric keys to be typed but fetching the value from that input will give a blank string unless it is a valid number.

Didn't know about that one, thanks!

Closing this.
