### ISSUE TITLE
Non-blocking UI's with interface previews

### ISSUE THREAD

**Issue by Superlukec** [angular/angular.js#11002]
Does anyone has any idea how to do this with Angular:

[Example](http://www.callumhart.com/blog/non-blocking-uis-with-interface-previews)

Thanks,
Luka

**Comment by pkozlowski-opensource** [comment]
Please direct support questions like this one to one of the [support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question)
