### ISSUE TITLE
Multiple Directives in same page is possilbe in Angular js

### ISSUE THREAD

**Issue by SRIRAM0905** [angular/angular.js#11010]
Hi all,

I have problem in my page as i am using two directivies. 1 for valuidtions  2 nd one for datetimepicker.

so my second diretive is not at all fiing all the time i guess its beacuse of my scop issue? can't we use two  directives. here is my HTML and ref code.please help me out.

<form name="commentsdtls_form" novalidate role="form">
    <fieldset>
        <legend>{{formhedding}}</legend>

    </fieldset>
    <input type="hidden" ng-model="commentdtls.brrCommentsIDPK" />
    <div class="row">
        <div class="col-md-5 form-group" show-errors>
            <label>Borrower Name</label>
            <select class="form-control" data-ng-model="commentdtls.borroweridfk" data-ng-options="item.borrowerIDPK as item.borrowerName for item in getallborrowers"
                    ng-required="true" name="ddlborrowername">
                <option value="">-- Select--</option>
            </select>
            <span class="help-block small" ng-if="commentsdtls_form.ddlborrowername.$error.required">Borrower name is required</span>
        </div>
        <div class="col-md-5 form-group" datedirectives>
            <label>Report Date</label>
            <input type="text" class="form-control" name="txtrptdate" />
        </div>
        </div>

            <div class="row">
                <div class="form-group col-md-5" show-errors>
                    <label>Risk Focus</label>
                    <select class="form-control" data-ng-model="commentdtls.riskTrendOutlook" data-ng-options="item.comboDetailID as item.comboDetailName for item in trend"
                            ng-required="true" name="ddlriskfocus">
                        <option value="">-- Select--</option>
                    </select>
                    <span class="help-block small" ng-if="commentsdtls_form.ddlriskfocus.$error.required">Risk Focus is required</span>
                </div>
                <div class="col-md-5 form-group">
                    <label>Status</label>
                    <select class="form-control" data-ng-model="commentdtls.isActive" data-ng-options="item.comboDetailID as item.comboDetailName for item in status" id="ddlstatus">
                        <option value="">-- Select--</option>
                    </select>
                    <span class="help-block small" ng-if="commentsdtls_form.ddlstatus.$error.required">Status is required</span>
                </div>

            </div>
            <div class="row">

                <div class="form-group">
                    <label>Comments</label>
                </div>
                <div class="form-group">
                    <textarea data-ng-model="commentdtls.devComments" placeholder="Please enter the comments." spellcheck="true" rows="5"
                              class="textarea"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label>Action Plan</label>
                </div>
                <div class="form-group">
                    <textarea data-ng-model="commentdtls.actionplanComments" placeholder="Please enter the Action plan comments." spellcheck="true" rows="5"
                              class="textarea"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label>CIA Comments</label>
                </div>
                <div class="form-group">
                    <textarea data-ng-model="commentdtls.bankComments" placeholder="Please enter the CIA-CEA comments." spellcheck="true" rows="5"
                              class="textarea"></textarea>
                </div>
            </div>
            <div class="row col-md-10 form-group">
                <button class="btn btn-primary" ng-click="saveComments(commentdtls)" id="btnvavecomments">Submit</button>
            </div>
            <div class="alert alert-success row col-md-10" ng-show="showsuccessalert">{{formSuccess}}</div>
            <div class="alert alert-danger row col-md-10" ng-if="hasFormError">{{formErrors}}</div>

</form>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Credit Watch</title>
    <script src="/Scripts/jquery-2.1.3.min.js"></script>
    <script src="/Scripts/angular.min.js"></script>
    
    <link href="/Content/bootstrap/bootstrap-combined.min.css" rel="stylesheet" />
    <script data-require="angular-ui-bootstrap@0.3.0" data-semver="0.3.0" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.3.0.min.js"></script>

    <link href="/Content/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="/Content/app.css" rel="stylesheet" />
    <link href="/Content/bootstrap/bootstrap-slate.min.css" rel="stylesheet" />

    <script src="/Scripts/angular-route.min.js"></script>
    <script src="/Scripts/angular-resource.min.js"></script>
    <script src="/Scripts/bootstrap.min.js"></script>

    <script src="/app/registration-module.js"></script>
    <script src="/app/Createeditborrower/borrower-controller.js"></script>
    <script src="/app/Createeditborrower/borrower-repository.js"></script>
    <script src="/app/utilities/dropdown-repository.js"></script>
    <script src="/app/directives/ValidationDirective.js"></script>
    <script src="/app/directives/DateDirective.js"></script>
    
    <script src="/app/Createeditborrower/borrowersch-controller.js"></script>
    <script src="/app/Comments/comments-controller.js"></script>
    <script src="/app/Comments/commentsch-controller.js"></script>
    <script src="/app/Comments/comments-repository.js"></script>

**Comment by pkozlowski-opensource** [comment]
@SRIRAM0905 please ask general support questions like this one on one of the dedicated support forums, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
