### ISSUE TITLE
namedListeners array elements are nulled out instead of spliced from the array

### ISSUE THREAD

**Issue by struckm** [angular/angular.js#11013]
In $rootScope.Scope#$on the function that is returned, when called nulls out the listener from the namedListeners array. I believe that instead of nulling out the element it should be splicing the element from the array. The side effect of nulling out the element reference is that the array will continue to grow for directives that have listeners that are continually created and destroyed which I have seen in my application.

**Comment by Narretz** [comment]
Do you think this is a performance problem or does it have any other adverse effects?

**Comment by struckm** [comment]
I would consider it a performance problem but a minor one. I created a jsperf here.. http://jsperf.com/indexof-speed-test. The perf difference iterating over a a couple of elements or a 100 elements is large but the speed in iterating over a 100 is still very fast. After looking over the code and testing it locally I don't see any adverse effects. There is another issue I came across while debugging the code. Is $$listenerCount necessary anymore if the elements are spliced from namedListeners/$$listeners arrays? Can't the check for $$listeners[name].length be used in place of the existence check for $$listenerCount[name]? I don't see much value in $$listenerCount. From what code I've seen anyway.

**Comment by RobiFerentz** [comment]
Looking into this a bit, and it seems like $emit and $broadcast will actually splice out any null values from the listeners array next time they are called on the same named event. Not sure *why*  it's done like that, but there are actual tests for that functionality. Changing the code to splice as suggested above will crash those tests.

https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L1179

https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L1252

**Comment by Narretz** [comment]
We are going to do something different now, which should prevent the array from growing: https://github.com/angular/angular.js/pull/16358
