### ISSUE TITLE
No route base url

### ISSUE THREAD

**Issue by Kenterfie** [angular/angular.js#11019]
I havn't found anything about it, but i cant believe it. Why it is not possible to change the templateUrl source domain? No route provider setting oder http setting to change the source of files, which are loaded.

Templates are not hosted on the same server, but i can't change the global url source, where is the option for it?
When i use templateUrl: "views/test.html"`, then it is ever requested from the current url (sample.com), but i want that it is changed to "external.sample.com", but i cant find anything on the internet and i dont want to write on every template url the complete url.

**Comment by bruunofco** [comment]
Hello,

try using templateUrl: "http://external.sample.com/view.tpl".
you may have trouble CROSS ORIGIN.

I have helped.

**Comment by VitalyTomilov** [comment]
So, you host your Angular app on one server, and its routing views on another? That's looking at SPA upside down.

If you have a justifiable use for non-routing views, use either ng-include or your own directive to generate the path.

**Comment by Kenterfie** [comment]
@bruunofco this is what i don't want. this is possible but is not very comfortable.

@VitalyTomilov yes, the view files are on a static file host with another domain. do you have a sample for a ng-include/directive way?

**Comment by lgalfaso** [comment]
It is not possible to have all possible variations supported on every parameter. `templateUrl` can be a function and you can build the URL using predefined constants the way you would need in your app. With this in mind, this is a wontfix
