### ISSUE TITLE
ng-click + $event.ctrlKey not working

### ISSUE THREAD

**Issue by moeHaydar** [angular/angular.js#11024]
`$event.ctrlKey` is not updated with ng-click.

altKey and shiftKey properties are updated just fine

**Comment by Narretz** [comment]
Do you mean that `$event.ctrlKey` is undefined when you press `ctrl` while clicking? I can't reproduce this here http://plnkr.co/edit/NkQonjujxbzcTcIn9j0v

**Comment by moeHaydar** [comment]
it is always set to `false`

tested on osx chrome and safari

**Comment by Narretz** [comment]
Is there a difference when using angular without jquery and using with jquery?

**Comment by Narretz** [comment]
And have you tried with pure jquery / vanilla javascript? Does that work as expected?

**Comment by sandeshdamkondwar** [comment]
```html
<div class="click-message">Click to Select<span ng-hide="$event.ctrlKey === true"> Template</span></div>
```
In this case it should hide the span containing "Template" keyword when ctrl key is on hold, but it is not hiding.

**Comment by Narretz** [comment]
if $event is not a property on the scope, this will not work. `$event` is only available in the context of event handler functions.

**Comment by Narretz** [comment]
I'm gonna close this as it looks like a usage error (and no additional info has been provided)

**Comment by virtual-dev** [comment]
Hi, I don't understand. The plunker provided above does not work as expected in Chrome 40, OSX Yosemite.

the "Ctrl" key in OSX is the "Cmd" key. Yet whether or not I hold that key, it logs me `false`.

**Comment by LeonardoBraga** [comment]
@virtual-dev On OSX, the Command key state is returned in the property `metaKey` of the event: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

**Comment by virtual-dev** [comment]
Ow sorry I just happened to see that. Thanks

**Comment by dw2** [comment]
`$event.ctrlKey` always returns false for me
