### ISSUE TITLE
Firefox: adding "disabled" attribute to empty option leads to "change on blur" behaviour

### ISSUE THREAD

**Issue by privideph** [angular/angular.js#11022]
I have an issue with inconsistent behaviour of the "select" directive. 

### Identified issue

When I set my own option for empty value but add "disabled" attribute to it, in Firefox model is being updated even it shouldn't be.

### Steps to reproduce the issue:

1. open this page in Firefox: http://plnkr.co/edit/Ha2xyTaYupuyfvAqxGOd?p=preview
2. open First selectbox and hover mouse pointer over some option other than "- - -"
3. do not select this option, instead click anywhere else on the page to hide options list
4. click again outside the select to make sure you took off focus

Result: selection model stays empty

1. repeat above steps for Second (disabled) select box and Third (ng-disabled)

Result: model gets updated with value of the last option that was hovered

### Expected behaviour

Model should not be updated in both cases - this behaviour is consistent between other tested browsers: Chrome 40.0.2214.111 & IE 11.

### Tested on

Angular version: 1.3.10+ & 1.4.beta
System: Windows 8.1
Browser: Firefox 35.0.1

**Comment by Frizi** [comment]
I reproduced this issue. It only happens when the state of checkbox you are operating on has the disabled option selected. Once you select a valid option, it works as expected.

**Comment by Narretz** [comment]
That's weird ...

still, couldn't you just skip the "not selected" option? Because angular will add one anyway if the model is initially undefined, and so the user cannot go back to the empty state (if that's what you are trying to do)

**Comment by Narretz** [comment]
This seems to be a relevant stackoverflow http://stackoverflow.com/questions/6923135/html-select-with-disabled-option-returns-wrong-selectedindex-in-firefox: when the select is blurred, Firefox checks if the currently selected option is disabled. Apparently this is not cool for Firefox (even though the default selected option was disabled ...), and so it updates the select with the last "hovered" option.

In my opinion, we should not fix this in angular, as we have a workaround for this.

**Comment by Narretz** [comment]
It's not the first time we had some cross-browser differences in select behavior. It might even be that FF follows the spec (although I doubt it) or that the spec is not good enough for this case. Anyway, I opened a bug - let's see what happens: https://bugzilla.mozilla.org/show_bug.cgi?id=1134900

**Comment by Narretz** [comment]
Resolved at least since 43.0.4, see the bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1134900
