### ISSUE TITLE
ngMessages does not play animation when declared as tag in Chrome browser

### ISSUE THREAD

**Issue by jseto** [angular/angular.js#11025]
When using the tag form

```
<ng-messages....>...</ng-messages>
```
instead the attribute form, the animations are not played. _This behaviour is seen in chrome but not in firefox_.

You can see the bug in the following plunker http://plnkr.co/edit/ADhaXB?p=preview

__Browsers__: Chrome
__angular versions__: 1.3.x and 1.4.x
__severity__: very low :-1:

**Comment by matsko** [comment]
`<ng-message>` and `<ng-messages>` are both custom tags. Therefore they don't have a default styling of `display:block`. You'll need to set that for the animations to kick in: http://plnkr.co/edit/DZjgsyOeXagbZs2QwHBQ?p=preview
