### ISSUE TITLE
Extract browserTrigger from ngScenario

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#11033]
browserTrigger currently lives under https://github.com/angular/angular.js/blob/master/src/ngScenario/browserTrigger.js

Before ngScenario is removed, we need to move browserTrigger to a place where tests can use it like before.

Tentatively assigning @petebacondarwin

**Comment by petebacondarwin** [comment]
Putting in the backlog for now until we get round to doing this.

**Comment by petebacondarwin** [comment]
We should move browserTrigger to `ngMock` right? @Narretz ?

**Comment by Narretz** [comment]
Yes, we (I) can do it. That would also mean we have to document it - atm it's not a public API.

**Comment by petebacondarwin** [comment]
Do we have to document it and make it public? Can't we just move it for now?

**Comment by Narretz** [comment]
That's also an option of course ...

**Comment by thorn0** [comment]
#14718 was merged. Seems like this issue can be closed.
