### ISSUE TITLE
JQLite issue setting attributes on comments ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#11038]
Here's [a demo](http://jsbin.com/rojexo/2/edit) of the issue (open the console) and you'll see something like this (asside from all the jsbin logs):

![screen shot 2015-02-11 at 5 31 22 pm](https://cloud.githubusercontent.com/assets/1500684/6151083/d323639a-b213-11e4-9997-804ed18da784.png)

This is referencing [this line](https://github.com/angular/angular.js/blob/d5b1d6edde194da75f235349783a0712aaab5f7e/src/jqLite.js#L607) which chokes if the element is a comment (evidently). jQuery proper handles this (somehow). If you edit the jsbin, simply uncomment the script tag to include jQuery and you'll see that the error is now gone.

I apologize if the demo is a little contrived, it was how I discovered the bug.

**Comment by Pumpuli** [comment]
jQuery bails on comment elements https://github.com/jquery/jquery/blob/0c466438d1feaec302fec13eafeeb063bbfd6a19/src/attributes/attr.js#L30

**Comment by kentcdodds** [comment]
Thanks @Pumpuli

**Comment by Narretz** [comment]
Okay, so we should probably do the same thing. At first I thought this was an ngMessages bug, but this isn't so bad.

**Comment by RobiFerentz** [comment]
I'm trying to push a branch with a fix for this issue so I can create a pull request. (gotta start somewhere with the contributing thing.)
Getting a 403 when trying. Who do I need to bribe to get permission?

**Comment by Narretz** [comment]
Hi @RobiFerentz, it usually works like this: you fork angular.js on Github. Then you set your fork as a remote on your local repo and push your bug fix branch to your fork. Back on github, you can now open a PR.

**Comment by RobiFerentz** [comment]
Yeah, forgot that part. Too early in the morning.

**Comment by kentcdodds** [comment]
Thanks for the PR @RobiFerentz! It'll be nice to get this fixed.

**Comment by kentcdodds** [comment]
:clap: Thanks!

**Comment by twogood** [comment]
Any chance of a backport to 1.3.x?
