### ISSUE TITLE
Did someone make a mistake editing the docs for ng-disabled

### ISSUE THREAD

**Issue by abilitest** [angular/angular.js#11032]
Just noticed in large bold letters at the top:

"We shouldn't do this, because it will make the button enabled on Chrome/Firefox but not on IE8 and older IEs:"

Looks like this was added as a passing comment by someone and not part of the doc page.

**Comment by Narretz** [comment]
It looks like it was put in to clarify that the following code block is an example of what not to do, but as it is it's very confusing and should definitely be rewritten.
