### ISSUE TITLE
Firefox error on webcomponents.js with angularJS ng-repeat-start

### ISSUE THREAD

**Issue by pienikrz** [angular/angular.js#11047]
I put problematic code to http://jsbin.com/pimiji/1/edit?html,js,console,output and error description on http://stackoverflow.com/questions/28466622/polymer-with-angularjs-ng-repeat-start-ng-repeat-end-firefox-issue

**Comment by Narretz** [comment]
Hi, I understand from the stackoverflow question that this is not an angular issue, so I'm gonna close this.
