### ISSUE TITLE
Select ng-transclude

### ISSUE THREAD

**Issue by YourDeveloperFriend** [angular/angular.js#11040]
On version 1.3.13, ng-transcluding options into a select causes a thrown error.

The relevant code is [the following](https://github.com/angular/angular.js/blob/master/src/ng/directive/select.js#L73)

```Javascript
  // Write the value to the select control, the implementation of this changes depending
  // upon whether the select can have multiple values and whether ngOptions is at work.
  self.writeValue = function writeSingleValue(value) {
    if (self.hasOption(value)) {
      self.removeUnknownOption();
      $element.val(value);
      if (value === '') self.emptyOption.prop('selected', true); // to make IE9 happy
    } else {
      if (isUndefined(value) && self.emptyOption) {
        $element.val('');
      } else {
        self.renderUnknownOption(value);
      }
    }
  };
```

With `ng-transclude`, `emptyOption` never gets initialized (I'm assuming because there are no options on `link`, which occurs before `ng-transclude`.

Check out this [jsfiddle](http://jsfiddle.net/8y5cswwu/1/)

It doesn't seem to have any averse affects on my program, but it is annoying clutter to my console.

**Comment by Narretz** [comment]
Any chance you could throw together a small plnkr.co etc. that shows the problem?

**Comment by YourDeveloperFriend** [comment]
The jsfiddle doesn't work?

**Comment by Narretz** [comment]
Oh, I didn't see the jsfiddle. Probably because I prefer plnkr. ;)

**Comment by YourDeveloperFriend** [comment]
[plnkr](http://plnkr.co/edit/PZB8AEtnsmi0oAtjIyEP?p=preview)

**Comment by Narretz** [comment]
Thanks! Looks like the line that's not working is IE9 specific, so it's possible that your code doesn't work in IE9, i.e. the empty option is not selected.

**Comment by YourDeveloperFriend** [comment]
Either way, it is throwing an error that shouldn't be thrown, so even though I don't notice a problem now, it's possible for that error to sneak through and disrupt the system. I'd think there should be a revised way to look for the empty option, but I'm not an expert.

**Comment by Narretz** [comment]
This doesn't throw in 1.4.6 anymore: http://plnkr.co/edit/8xbRBNBTEXPcvC5eiMzY?p=preview
