### ISSUE TITLE
controllerAs in directives not working with Isolate Scope

### ISSUE THREAD

**Issue by iaakash** [angular/angular.js#11045]
Here is very Basic Plunk:

http://plnkr.co/edit/oNWoPiCd0TLU15Es1Tne?p=preview

**Comment by Narretz** [comment]
What exactly should I see? When I click on "Knight me", the function `UCC.assignRank` is called, which is definitely defined inside the isolate scope directive's controller which uses controllerAs.

**Comment by Narretz** [comment]
I'm gonna close this due to lack of info. Feel free to reopen if you can provide more info.
