### ISSUE TITLE
See how much we can save if we remove filters etc

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#11041]

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin is it about moving filters to their dedicated file / module to save bytes in the "core" file?

**Comment by lgalfaso** [comment]
check-size.sh
>
>   ?

**Comment by petebacondarwin** [comment]
@pkozlowski-opensource  -  precisely

**Comment by petebacondarwin** [comment]
Running a build with the number, currency and date filters removed:

|        | angular.js | angular.min.js | angularjs.min.js.zip |
| --- | --- | --- | --- |
| with filters | 988237 (100%) | 140855 (100%) | 50201 (100%) |
| without filters | 969925 (98.15%) | 137452 (97.58%) | 48730 (97.07%) |

**Comment by petebacondarwin** [comment]
cc @IgorMinar - we would save around 1.4KB on the zip file.

**Comment by petebacondarwin** [comment]
It seems that we added quite a lot between 1.4.0-beta.2 (46844) and 1.4.0-beta.3 (50699).
Is this due to the $parse refactor maybe?

**Comment by pkozlowski-opensource** [comment]
1.4KB doesn't sound like it is wort the trouble, considering that most of applications will probably use one of the filters. What are your thoughts @petebacondarwin ?

**Comment by petebacondarwin** [comment]
Yes, I think I agree; although I am not sure I agree that most applications would be using `date`, `currency` and `number` filters.

I think that we should still be looking for ways to keep the size of the core file down.

**Comment by pkozlowski-opensource** [comment]
Yeh, I think that most applications would be using `filter` and `orderBy`. Agree that we should put the core on some form of diet, not sure what it would be, though...

**Comment by lgalfaso** [comment]
@petebacondarwin for $parse, we can create a versions when csp is enabled/disabled, in case the user already knows that one configuration is needed

**Comment by petebacondarwin** [comment]
@lgalfaso - I think that might be a good idea

**Comment by alexlamsl** [comment]
Just FYI - I tried a custom version with CSP feature removed, and the uncompressed `angular.js` is at 938632 bytes.

So that's about 50kB.

**Comment by petebacondarwin** [comment]
We'll come back to this for 1.5 I think.
