### ISSUE TITLE
ngCookies does not work on android phonegap app.

### ISSUE THREAD

**Issue by TanaseButcaru** [angular/angular.js#11066]
As described <a href="http://stackoverflow.com/questions/28518309/phonegap-angularjs-cookiestore-before-routechange-issue-on-android">here</a> I cannot set cookies on android phonegap app (tried with both kitkat and lollipop versions of android).

Just made some tests with older versions of 1.3.x and the same thing occurs - undefined cookie variable. This also happens with $cookie, not just with $cookieStore.

For any matter, I'm using the latest version of phonegap/cordova. Might this be a phonegap issue or angularjs related?

**Comment by Narretz** [comment]
Have your tried setting the cookies without angular?

**Comment by TanaseButcaru** [comment]
I haven't tried that yet.
For the moment I'm using localStorage & sessionStorage for what I need, but I'm still curious about this issue. I made two services to make this "the angular way".
```js
MYAPP.factory('storageLocal', ['$window', function($window){
    var storageLocalMethods = {};

    //fn: set
    //desc: set a local storage variable
    storageLocalMethods.set = function(name, value){
        $window.localStorage.setItem(name, angular.toJson(value));
    }

    //fn: get
    //desc: get a local storage variable
    storageLocalMethods.get = function(name){
        return angular.fromJson($window.localStorage.getItem(name));
    }

    //fn: remove
    //desc: remove a variable from local storage
    storageLocalMethods.remove = function(name){
        $window.localStorage.removeItem(name);
    }

    return storageLocalMethods;

}]);

MYAPP.factory('storageSession', ['$window', function($window){
    var storageSessionMethods = {};

    //fn: set
    //desc: set a session storage variable
    storageSessionMethods.set = function(name, value){
        $window.sessionStorage.setItem(name, angular.toJson(value));
    }

    //fn: get
    //desc: get a session storage variable
    storageSessionMethods.get = function(name){
        return angular.fromJson($window.sessionStorage.getItem(name));
    }

    //fn: remove
    //desc: remove a variable from session storage
    storageSessionMethods.remove = function(name){
        $window.sessionStorage.removeItem(name);
    }

    return storageSessionMethods;

}]);
```
I'll be back after same tests with native cookie :)

**Comment by TanaseButcaru** [comment]
Just made some tests with document.cookie and I have the same problem.
I guess I should address this issue to Phonegap community.

**Comment by Narretz** [comment]
Thanks for testing. I'm gonna close this, but feel free to open a new issue if it turns out to be an angular issue after all.
