### ISSUE TITLE
[angular.module.run] - does not wait for resolve load to start the app

### ISSUE THREAD

**Issue by vfa-dunghn** [angular/angular.js#11064]
Hi friends.
Please take a look into my repo: http://jsfiddle.net/lovedota/qpwwm8bn/
I have an run callback.
```
  .run(['AuthService', function(AuthService){
        return AuthService.fetchUser();
    }])
```
But it never wait for the deferred function.
my console log always be.
```
"locationChangeStart trigger: " undefined show:57
"Has User:[object Object]"
```
Is it a bug of angular ?

**Comment by marcalj** [comment]
Not sure if it's possible, but it's something I always miss on AngularJS.
Some kind of **global resolve** for the app initialization.
It will really help bootstrap things coming from external APIs, and to configure Auth roles, permissions, etc in time. For something only needed after full page refresh or first time visit.

**Comment by Narretz** [comment]
Yes, this is currently not possible. The main +1 thread is here: https://github.com/angular/angular.js/issues/4003
