### ISSUE TITLE
angular scope variable not bound inside bootstrap/jquery modal

### ISSUE THREAD

**Issue by sousarka** [angular/angular.js#11060]
I'm working with bootstrap (v3.2.0), angular (v1.3.13) and jquery (v2.1.3) and this issue is appearing when I'm trying to upgrade the bootstrap version to 3.3.2. We've a bootstrap modal which is toggled with angular route. The modal has $scope bound variables.

In v3.2.0, the $scope bound variables are appearing fine in the modal, but in v3.3.2 angular compiler is throwing an error TypeError: Cannot read property 'childNodes' of undefined

I've created two examples also:

With bootstrap v3.2.0 ($scope vars working) : http://plnkr.co/edit/cGf3C2gHR0GOK5JBido1?p=preview

With bootstrap v3.3.2 ($scope vars not working) : http://plnkr.co/edit/kj66Gal5s5Yczyom1PHC?p=preview

Is there something wrong with angular/jquery/bootstrap combination or I'm doing something wrong here?

**Comment by Narretz** [comment]
I assume there's a race condition between the angular compiler and the bootstrap modal function. If you wrap your call to $('#myModal') into a setTimeout, it works. You'll have to check the bootstrap changelogs etc. to find out why this happens after you upgrade. I don't think this is an issue with angular.
Another tip: it's not a good idea to do DOM manipulation inside controllers - this is what directives are for. See this example, which also doesn't cause the error: http://plnkr.co/edit/A9bmqR5cMa4tVguM6hLB?p=preview

**Comment by sousarka** [comment]
Thank you. We're in the process of converting bootstrap/jquery related code to angular-ui-bootstrap so that we can use directives as you recommended.
