### ISSUE TITLE
bug(select): switching from invalid to valid ngModel value not working correctly

### ISSUE THREAD

**Issue by tdakhla** [angular/angular.js#11068]
In 1.2 and 1.3, whenever a `<select>` had its ngModel switched from an invalid to valid ngModel value (after a timeout of some sort), the "?" option was removed and the dropdown was set correctly:
1.2.28: http://jsfiddle.net/ydhv8xc5/
1.3.13: http://jsfiddle.net/p6w2d3p2/

However, given the same scenario in 1.4 (snapshot), the "?" value still remains and the dropdown isn't set correctly:
snapshot: http://jsfiddle.net/6j83jh3n/

**Comment by Narretz** [comment]
Yeah, something about this was changed in 1.4.0-beta.0, and is also documented in the changelog: https://github.com/angular/angular.js/blob/master/CHANGELOG.md. But I'm actually not so sure if this should happen when you don't use ngOptions. @petebacondarwin might know what's going on here.

**Comment by petebacondarwin** [comment]
This is because select values are string and you are assigning a number. Since we now use strict equality it doesn't match. Changing it to a string works.

**Comment by Narretz** [comment]
'Doh! Yeah, that's right. It's also document in `select`, so I think we can close this as "works as expected".

**Comment by tdakhla** [comment]
You guys are absolutely right - I forgot that it's different with `option` vs `ng-option` (it's a shame, but that's just how it is I guess).  I should be setting the value as a string and not expect number assignment to work.  This can be closed.

**Comment by tdakhla** [comment]
@Narretz @petebacondarwin  I think this scenario is broken:  http://jsfiddle.net/xek8wqk1/

Resetting back to empty string is fine, but resetting to undefined doesn't remove the "?" value.

**Comment by petebacondarwin** [comment]
@tdakhla - yes, that looks like a bug. Can you open a new issue for it?

**Comment by tdakhla** [comment]
Sure, created https://github.com/angular/angular.js/issues/11078 for it.
