### ISSUE TITLE
Bug in EMAIL_REGEX case sensitvity

### ISSUE THREAD

**Issue by jpulec** [angular/angular.js#11076]
It seems that the regex used in angular for validating emails, only allows lowercase characters.

```/^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i ```
from the latest commit.

Although this is consistent with Chromium's implementation, the HTML5 spec states that uppercase characters should be allowed.

**Comment by gkalpak** [comment]
The `i` at the end means that the match is _case-insensitive_, so uppercase letters are accepted as well.

**Comment by jpulec** [comment]
Wow. Turns out it was a bug with the library I was using, and I totally didn't see the ```i``` at the end. Thanks!
