### ISSUE TITLE
How to handle Up/Down arrow button events in input[number]

### ISSUE THREAD

**Issue by VenkatRamNDD** [angular/angular.js#11072]
I am having a input[number] element in my page if i click up arrow the down arrow should be disabled and when i refresh the page now if i click down arrow up one should be disabled. Is there any way to implement this in angularjs ?

This is my plunker with input[number] :http://plnkr.co/edit/K64LNKF5CwlBU0vIjh5L?p=preview

**Comment by Narretz** [comment]
To my knowledge, the browsers don't expose the DOM for these buttons, so it's not possible to style them, regardless of angular.The solution is simply to set the correct upper and lower limit for the input. you can do this dynamically via ngMax / ngMin. Also, if the button is clicked, the `input` event should be fired.

**Comment by Narretz** [comment]
I searched a bit, and while it's possible to remove the input "spinners" (arrows) (see http://css-tricks.com/snippets/css/turn-off-number-input-spinners/ http://stackoverflow.com/questions/23372903/hide-spinner-in-input-number-firefox-29), there is no way to disable them.
You could possibly implement a $parser that "fakes" disabling the input by immediately resetting it based on some condition - but I don't advise that, as it is confusing to the user. input[number] will stop the user from incrementing the number below / above the defined limits anyway - in other cases, it's better to just display the error or a hint.
