### ISSUE TITLE
Original variable VS Angular variable

### ISSUE THREAD

**Issue by jolinfish** [angular/angular.js#11071]
Hi, all:
   I am a beginner in angular.js. I was deeply troubled by the variable of angular. like this: 
native variable:
var globalVal = { deviceType : 'android' };

angular variable:
var app = angular.module('myapp', [])
     .run(function($rootScope) {
             $rootScope.deviceType = 'android';
      });
});
    I can use globalVal.deviceType or $rootScope.deviceType. So, anyone can tell me what's the difference between native variable and angular variable? By the way, what's the best way to use variable in angular?

**Comment by Narretz** [comment]
The $rootScope is only available inside the angular application, which is better than having a global variable that might mess with 3rd party code or legacy applications. That said, it's not the best idea to store this info inside the $rootScope. Consider using a service that is injected into those controllers / directives etc. of your app that actually need the deviceType. With the rootScope, it's possible that you accidentially overwrite the property.
That said, we want to keep this repo for feature / bug reports only - you can find support channels in the https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md
