### ISSUE TITLE
Purpose of terminal on ng-repeat

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular.js#11077]
Hello! I am writing a directives book and I cannot explain why `terminal` exists on `ng-repeat`. I see no reason for that and the tests passes without it. I remember that priorities worked differently in the past (the order of post-link executions) so I don't really know if that is a leftover of 1.0.x or if there is any real reason to have it.

Thank you.

**Comment by lgalfaso** [comment]
If you have a directive that is at the same element as an ng-repeat and this directive expects to get a DOM element (and not a comment that is what you would get given that there is an ng-repeat), then without `terminal: true` you would get a failure

**Comment by Foxandxss** [comment]
I don't see it. If I put a directive with more priority than `ng-repeat` it will get the comment yes or yes (with or without `terminal`).

At the end of the day, `terminal` avoids the execution of directives with less priority so in the cases where a directive has more priority, `terminal` won't do anything.

On the cases where the directives has less priority, the internal `transclude: 'element'` mechanism will simply stop processing directives with less priority until I use `transcludeFN` and in that case I will get the proper element (with or without `terminal`).

Cheers.
