### ISSUE TITLE
bug(select): switching from an invalid to undefined model value keeps invalid option in list

### ISSUE THREAD

**Issue by tdakhla** [angular/angular.js#11078]
In 1.4 snapshot, given a select box without ng-options, switching from an invalid to undefined model value doesn't remove the '?' option (even though the value is correctly selected to the empty option): http://jsfiddle.net/xek8wqk1/

Resetting back to empty string is fine, but resetting to undefined doesn't remove the "?" value.

**Comment by lgalfaso** [comment]
@petebacondarwin can you look into this?

**Comment by petebacondarwin** [comment]
will do
