### ISSUE TITLE
Why does the next element after a spliced element in an array reuse the spliced element's scope?

### ISSUE THREAD

**Issue by moneytree-doug** [angular/angular.js#11070]
This demonstration maybe overkill.

After clicking delete to splice an array, the next element that takes its place will actually re-use its scope which is an unexpected behaviour, IMO. http://plnkr.co/edit/dLRfdcQhyFDB2MYuTj1p?p=preview

I tried dumping the scope variable before and after the delete, and they both use the same scope id. Why  is this case? I thought all the children have their own scopes? So I would expect the next element to reference its original scope instead of the spliced element's scope.

**Comment by lgalfaso** [comment]
This is the expected behavior as you are using `track by $index`
