### ISSUE TITLE
Filter OrderBy behaves differently when expression changed to Array from String

### ISSUE THREAD

**Issue by brahmgupta** [angular/angular.js#11080]
I am trying to order list by using filter - 'orderBy' on property 'name' of following type of data
 $scope.friends = [ { name: 'Adam'}, { name: 'Mary'}, { name: 'alpha'}, { name: 'beta'}....

When in predicate I pass string expression with 'name' it is sorting it as expected but when I update predicate with array expression it is sorting names with upper-case followed by lower-cased names.

Here is plunker to test this:
http://plnkr.co/edit/rkeOevNXvQK0Heh3WaXC?p=preview

**Comment by Mosho1** [comment]
That is not an array. Should be ['name'] rather than '[name]'. I'm not sure why it behaves the way it does for your example, but it is undefined behavior at best.

**Comment by gkalpak** [comment]
@Mosho1 is right. It is just returning the items in the original order (because there is no `[name]` property to short by.

**Comment by brahmgupta** [comment]
Thanks for comment @Mosho1. It's working now creating proper array.
