### ISSUE TITLE
Error: $templateRequest - older browsers

### ISSUE THREAD

**Issue by dbabaioff** [angular/angular.js#11089]
Getting an error on Android 2.3.x (and some other older browsers): Uncaught SystaxError: Unexpected token finally

The cause of the error: #10780 
2b8baf7e109ab0bbd35da82170f460644f0297d3

This should fix the problem: #11088 (3bcdec33a5b5f53a8cd87551acfc6070cb53cd71)

**Comment by dbabaioff** [comment]
@petebacondarwin @pkozlowski-opensource Can you merge this commit also on version 1.3.14? (I think it's only on 1.4.0-beta.5)

**Comment by petebacondarwin** [comment]
@Diabaig sorry about that. It must have missed being cherry picked. It'll go into the next release.

**Comment by petebacondarwin** [comment]
I have cherry picked it

**Comment by dbabaioff** [comment]
:+1:
