### ISSUE TITLE
Optional, multi-type parameters not labelled as optional in the docs

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#11095]
Some optional parameters to functions are not labelled as optional in the docs, inspite being documented as such. This seems to be related to the format used for optional, multi-type parameters.
E.g.:

    @param {string=} xyz ...   ---> Appears correctly in the docs 
    @param {(string|number)=} xyz ...   ---> Appears correctly in the docs 
    @param {string|number=} xyz ...   ---> Does NOT appear correctly in the docs 

(E.g. `toJson`'s `pretty` parameter: [docs][1] vs [source][2])

--
Could this be an issue with dgeni or should all `{x|y=}` occurences be replaced with `{(x|y)=}` ?

[1]: https://docs.angularjs.org/api/ng/function/angular.toJson
[2]: https://github.com/angular/angular.js/blob/master/src/Angular.js#L1038

**Comment by petebacondarwin** [comment]
Got a fix in the works
