### ISSUE TITLE
$http cache docs are not clear

### ISSUE THREAD

**Issue by Fonger** [angular/angular.js#11101]
According to the [docs](https://docs.angularjs.org/api/ng/service/$http),
it says 
> To enable caching, set the request configuration cache property to true (to use default cache) or to a custom cache object (built with $cacheFactory)
You can change the default cache to a new object (built with $cacheFactory) by updating the $http.defaults.cache property. All requests who set their cache property to true will now use this cache object.
If you set the default cache to false then only requests that specify their own custom cache object will be cached.

I'm confused by the default value. The doc doesn't specify this.
So I run `$http.defaults.cache` and gets `undefined`. So will it ignore all `cache-control` header? It seems that this is not true.

I have the following question:
1. If cache is `true`, it will follow the http cache-control header and store the cache in browser cache. Is this correct? If it's `true` but the server doesn't reply `cache-control` header, it won't cache.
2. If cache is `false` it won't cache even if the server reply `cache-control` header.
3. If it's a CacheFactory object, then the object will handle it. Also ignore the cache-control header.

**Comment by pkozlowski-opensource** [comment]
@Fonger I can sense confusion about how $http cache works in AngularJS atm. So, in short, it is a simple cache that doesn't inspect response headers. You simply tell it to cache responses and if it will do so if asked, regardless of the response content, headers etc. So the `cache-control` header has no effect on the AngularJS cache.

Does it clarify things? Would you be up to sending us a doc update PR with the clarification you would like to see in the docs?

**Comment by ryanhart2** [comment]
I have submitted PR#13003 to address this.
