### ISSUE TITLE
module.directive('FirstLetterCapitalized', ...) does not work and does not log an error.

### ISSUE THREAD

**Issue by jamestalmage** [angular/angular.js#11109]
```javascript
//app.js
angular.module('myModule', []).directive('MyDirective', function() {
  console.log('Hello World!');
  /* ....  make a directive .... */
});
```
```html
<!--- index.html -->
<my-directive></my-directive>
```
This produces absolutely zero output on the console. Changing the directive name to start with a lower case letter fixes the problem. IMO, it should either log an error that I capitalized the first letter, or just work.

**Comment by pkozlowski-opensource** [comment]
Yeh, kind of corner case, but you are right...
