### ISSUE TITLE
$http.get is not working in versions greater than 1.2.9

### ISSUE THREAD

**Issue by nikhiljohn10** [angular/angular.js#11105]
The issue was observed when changing the version of angular js in the link http://www.w3schools.com/angular/tryit.asp?filename=try_ng_customers_mysql

**Comment by pkozlowski-opensource** [comment]
@nikhiljohn10 cold you please be more precise? What do you mean by "not working"? I can see _some_ results displayed and no error on the console. What is the expected vs. buggy behavior?

**Comment by bruunofco** [comment]
Hello,

In versions below 1.3 was not necessary to instantiate a module, after version 1.3 is required and changes the declaration of a controller.
The way you set up the controller when you change to a newer version the controller is not recognized.

example:

angular.module var app = ('App' []);

app.controller ('customersController', function ($ scope, $ http) {
   $ http.get ("http://www.w3schools.com//website/Customers_mysql.php")
   .success (function (response) {$ response = scope.names;});
});

In this link you can find more of information about the migration of 1.2 to 1.3.
https://docs.angularjs.org/guide/migration

Hope this helps.

**Comment by pkozlowski-opensource** [comment]
@bruunofco is right, this is the most likely issue. Closing for now as we don't have any valid reproduce scenario. Happy to reopen when one surfaces.

**Comment by nikhiljohn10** [comment]
I guess that a change not much beginner people would notice while using tutorials older versions with newer ng js file. Anyway, the issue is closed.
