### ISSUE TITLE
$animate.enabled(true, element) does nothing

### ISSUE THREAD

**Issue by marshallbrekka** [angular/angular.js#11100]
When re-enabling animations on an element the call to enabled doesn't actually do anything.

It calls `cleanup` here
https://github.com/angular/angular.js/blob/v1.3.9/src/ngAnimate/animate.js#L1247-L1249

and it fails to match either of these conditions, so no action is performed and animations are still disabled.
https://github.com/angular/angular.js/blob/v1.3.9/src/ngAnimate/animate.js#L1513
https://github.com/angular/angular.js/blob/v1.3.9/src/ngAnimate/animate.js#L1518

**Comment by Narretz** [comment]
The docs are ambiguous about this - the description says it's for 'globally enabling animations', the arg description says for element "If provided then the element will be used to represent the enable/disable operation" - not really sure what that's supposed to mean.

**Comment by marshallbrekka** [comment]
Currently you can call `$animate.enabled(false, element)` and it will only disable animations on that element and its children, while still leaving global animations untouched. So it would seem to me that it is intended to allow scoping the enabled/disabled flag to a specific element.

**Comment by matsko** [comment]
Yes the API in 1.3 is a bit unfortunate since `disabled()` only disables children. 1.4 fixes this fully (where both the children and the element itself are disabled). Would you be OK with waiting on this fix to come into release next week and using 1.4?

**Comment by matsko** [comment]
1.4 (master) now properly fixes this.

```js
$animate.enabled(element, false);
```

**Comment by Narretz** [comment]
Then we can close this :)
