### ISSUE TITLE
feat(filter): capitalize

### ISSUE THREAD

**Issue by Gaffney** [angular/angular.js#11118]
Currently there are "lowercase" and "uppercase" [filters](https://docs.angularjs.org/api/ng/filter).  Another super common thing to do is to capitalize a string.  Would be nice if this was added as another provided filter.

**Comment by pkozlowski-opensource** [comment]
Not sure how common it is but given that it is very easy to do I would probably say that it is better handled as a 3rd party module. AngularJS size is growing and we were even pondering moving filters out of the core...

I would say it gets timid -1 from me.

**Comment by wesleycho** [comment]
I don't think this should be in core - in this case, it is an easy to create filter if a developer needs it, but it is not something that will necessarily be used by the majority of Angular applications.

**Comment by matheussampaio** [comment]
You can use [angular-filter](https://github.com/a8m/angular-filter#ucfirst).

**Comment by Gaffney** [comment]
@wesalvaro You can also uppercase/lowercase with CSS.  My point was that *given* the current filter functionality, being able to capitalize makes sense as it is in the same category as the others.

That said, if I had to choose between removing filters from the core **completely** or keeping them and adding more, I would go with removing them.  At the time of posting I did not know the former was a consideration.

So -1 to my own issue in favor of stripping filters.

**Comment by lgalfaso** [comment]
Agree with @pkozlowski-opensource, this does not belong to the core

**Comment by wesalvaro** [comment]
lol, why am I mentioned? what am I missing...

**Comment by wesleycho** [comment]
@wesalvaro I think he meant to mention me
