### ISSUE TITLE
impossible to use twitcam objects in angularjs way

### ISSUE THREAD

**Issue by batphil** [angular/angular.js#11114]
While developing my directive https://github.com/batphil/angular-streamlist, i meat a problem with twitcam code http://twitcam.livestream.com/.

In the embed tag, it's impossible to put the src in a angularjs way.

You can see the problem in this simple example : http://www.strapontins.org/angucam/index.html

My SO question : http://stackoverflow.com/questions/28591000/invalid-url-in-angularjs-directive 

I tried $timeout and link operations in directive, to change the src after, but nothing change.

Help is welcome, the only solution for me for the moment is to use PHP and echo the decode json data.

**Comment by Narretz** [comment]
There's an old old issue about this: https://github.com/angular/angular.js/issues/339 Seems like `ngSrc`/ regular `src` interpolation will never work. Your best bet is to try out IgorMinar's approach / some of the workarounds found in the linked issue.
