### ISSUE TITLE
ng-controller not working in the latest version of Angular js file

### ISSUE THREAD

**Issue by ChandranMuthu** [angular/angular.js#11113]
I downloaded the below versions of Angular js file and used in my html code shown below. The ng-controller in the below code snippet not working. It works in the version 1.2.26. Please look into this and advise.

1.4.0-beta.4
1.3.13
<html>
<head>
<script src = "C:\Users\xbbkp3v\Documents\Angular JS Learning\angular.js"></script>

</head>
<div ng-app= "" ng-controller="personController">

First Name: <input type="text" ng-model="firstName"><br>
Last Name: <input type="text" ng-model="lastName"><br>
<br>
Full Name: {{fullName()}}

</div>

<script>
function personController($scope) {
    $scope.firstName = "John",
    $scope.lastName = "Doe",
    $scope.fullName = function() {
        return $scope.firstName + " " + $scope.lastName
    }
}
</script>
</html>

**Comment by pkozlowski-opensource** [comment]
This is due to a breaking change in 1.3 described here:
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-21
