### ISSUE TITLE
Ability to reset directive

### ISSUE THREAD

**Issue by piernik** [angular/angular.js#11123]
One time bindings are great feature. It reduces watchers.
But sometimes You have to change some directives parameters.
Great solution would be to reset directive and force to init directive once more.
The new setting would be in game as well as one time bindings. 
Can You think about that?

**Comment by VitalyTomilov** [comment]
Only the directive itself should have the knowledge of and the ability for un-registering watches, which means you'd have to de-register it from within itself. And that means you might as well implement your own initialization function to change the behaviour completely, there is no need to involve Angular's directive repository to do just that.

**Comment by pkozlowski-opensource** [comment]
@piernik we are debating similar problematic in https://github.com/angular/angular.js/pull/10658

There is a general consensus that _some_ kind of freezing / un-freezing of watches on scopes would be beneficial, but we can't think of a solution that would work for most / all use-cases and wouldn't be a foot-gun.

Please share any ideas you might have in #10658
