### ISSUE TITLE
Does viewValue always have to be a string?

### ISSUE THREAD

**Issue by demisx** [angular/angular.js#11121]
I am reading https://docs.angularjs.org/api/ng/type/ngModel.NgModelController and it says that `$setViewValue(value, trigger)` may take value as an object, string or number.  But then below description (and in some  other places) it says `viewValue` is string. I am confused. Does the `viewValue` always have to be a string or not? Perhaps the docs need to be updated too to be consistent.

**Comment by Narretz** [comment]
In angular core, $setViewValue is generally called with strings, because getting values from `input`  elements etc. always returns string. However, it is possible that  someone writes a custom "control", e.g. a datepicker that passes an object to $setViewValue.

**Comment by demisx** [comment]
Thank you for clarification. This is what I thought, but was thrown off by the docs that specifically mention $viewValue being a string. I think the docs should have the type as { string | Object }, since in custom controls I can set the view value to what I need. Another good example, is the '<input file="type"> component, where view value contains `FileList` object attached by the user.

**Comment by wesleycho** [comment]
Inputs with type="file" are not a great example, since one cannot actually set a value to a file input due to browser restrictions (the official spec I believe?).  $viewValue can be anything a person wants though when creating custom components IIRC.

**Comment by demisx** [comment]
@wesleycho The browser has no restriction of what `$viewValue` can be set to. This is part of angular.
