### ISSUE TITLE
Can't start End 2 End tests

### ISSUE THREAD

**Issue by eshangin** [angular/angular.js#11129]
Hi. I can't start End to End tests as described in https://docs.angularjs.org/tutorial
When I start "npm run protractor" I get next in the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
6 info preprotractor angular-phonecat@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info protractor angular-phonecat@0.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-phonecat@0.0.0 Failed to exec protractor script
11 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1008:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
12 verbose pkgid angular-phonecat@0.0.0
13 verbose cwd d:\Projects\Temp\AngularTutorials\Phonecat
14 error Windows_NT 6.1.7601
15 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
16 error node v0.12.0
17 error npm  v2.5.1
18 error code ELIFECYCLE
19 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
19 error Exit status 1
20 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
20 error This is most likely a problem with the angular-phonecat package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     protractor test/protractor-conf.js
20 error You can get their info via:
20 error     npm owner ls angular-phonecat
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]

**Comment by rhorber** [comment]
same here (also nodejs 0.12.0 and npm 2.5.1)

I tried the solution in this issue: https://github.com/angular/angular-phonecat/issues/230.
Now the tests run (2 are failing), but protractor exits with code 1.

**Comment by KloseD** [comment]
I get the same error (node 0.12.0, npm 2.5.1 & bower 1.3.12) and unfortunaly [rhorber's link](https://github.com/angular/angular-phonecat/issues/230) does not help.

**Comment by Onizuka89** [comment]
The way I do the E2E tests which seem to have worked without issue so far, is to install protractor with npm with the -g option run web-drivemanager, and then run
```protractor test/protractor-conf.js```
from the root folder of the project whenever I want to run the tests, not the ```npm run protractor``` command since it will use the protractor in the node_module folder, which gives the errors described.
I have tested this on both Windows and OS X and had no issue since.

**Comment by petebacondarwin** [comment]
I think that this might be a problem with the Protractor version in angular-phonecat. We should be using Protractor v2.0 really. Can you create an issue over on that repository?
