### ISSUE TITLE
Directive synonyms + encapsulation.

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular.js#11136]
Similar to a C++ class, a directive can represent a simple element as well as a concept or approach, one that can be parametrized through either additional attributes or the directive's name. The latter suggests support for multiple directive names with a single implementation.

Example:

````
app.directive(null, [function () {
    return {
        names: ['encSh128', 'encSh256', 'encSh512'],
        scope: {
            salt: '@'
        },
        restrict: 'E',
        link: function (scope, element, attrs, name) {
            switch(name){
                case 'enc-sh128':
                    break;
                case 'enc-sh256':
                    break;
                case 'enc-sh512':
                    break;
                default:
                    break;
            }
        }
    }
}]);
````
Note that null is passed for directive name, while supported names are specified via 'names' attribute.
This way a library can be implemented in two ways, depending on semantics (mostly), as well as your preferences - through attributes or through names.

And it wouldn't be a breaking change, just registering the same directive under multiple names. And having just one name in the array would be the same as the standard name approach.

An alternative, and maybe more elegant way would be to support Array of strings as the directive name, instead of just one string.

Also, the current 'name' can be made available through 'scope' object instead, to avoid extending the link/controller functions.

So, the same but cleaner example would be:
````
app.directive(['encSh128', 'encSh256', 'encSh512'], [function () {
    return {
        scope: {
            salt: '@'
        },
        restrict: 'E',
        link: function (scope) {
            /* generic parts first */
            
            if(scope.getName() === 'enc-sh128'){
                /* do something special */
            }
        }
    }
}]);
````

**Comment by pkozlowski-opensource** [comment]
@VitalyTomilov what you are asking for here is syntactic sugar, right? Because you can do this already like so:

```javascript
var myDirectiveFactoryFn = function () {
    return {
        scope: {
            salt: '@'
        },
        restrict: 'E',
        link: function (scope, element) {
            /* generic parts first */

            if(element[0].nodeName === 'enc-sh128'){
                /* do something special */
            }
        }
    }
};

app.directive('encSh128', myDirectiveFactoryFn);
app.directive('encSh256', myDirectiveFactoryFn);
app.directive('encSh512', myDirectiveFactoryFn);
```  

Having said this I'm not super-fan of such design of directives  which tend to have gigantic switch inside. IMO there are more elegant solutions here, for example - cooperating directives.

Personally this would be -1 from me as things are already possible and adding this type of aliasing might encourage people to write directives that are not very well structured. I would be happy to revisit my decision based on the solid, real-life use-case where this type of aliasing is the most elegant solution. @VitalyTomilov care to share one?

**Comment by Narretz** [comment]
Closing because no feedback and also not really needed in core.
