### ISSUE TITLE
Using SessionStorage as a store for $cacheFactory

### ISSUE THREAD

**Issue by corporatepiyush** [angular/angular.js#11135]
currently $cacheFactory makes use of browser memory which does not last after whole page refresh.
it would be nice to have facility to register SessionStorage or LocalStorage as cache store/keeper.

**Comment by pkozlowski-opensource** [comment]
@corporatepiyush I think that this is an excellent idea for a 3rd party module which would decorate [$cacheFactory](https://docs.angularjs.org/api/ng/service/$cacheFactory) and return [Cache](https://docs.angularjs.org/api/ng/type/$cacheFactory.Cache) instances backed by local / session storage. 

I'm not sure we want to add something like this to the core, though... I'm going to close this one for now as "not core" for now, but if there is enough interest from others and there are particular benefits of adding it to the core, we can revisit it in 1.5

**Comment by SateeshKumarBheemsetty** [comment]
is storing data on client browser is secure ? is there any security concerns over using the localStorage ?
