### ISSUE TITLE
ngMockE2E with request in .config

### ISSUE THREAD

**Issue by shawnmclean** [angular/angular.js#11130]
Hello,

I have http requests happening in the `.config` method that is basically loading i18n dictionaries. How can I do a passthrough for this when the `$httpBackend` is being executed in the `run` method?

I'm also dynamically adding the angular-mock file and a new file with the `run` method with the `$httpBackend` param if its the dev environment. This means I can't include something like an `$httpBackendProvider` (if there is one) in the config, because it will not exist in production.

Is there a way to tell my $translateProvider in the config to wait until the `.run($httpBackend)` has finished executing or any other solution is welcomed.

**Comment by petebacondarwin** [comment]
@shawnmclean - I am not clear what you are trying to achieve here. You cannot use any Angular services in the `config` phase of an application. This is purely for setting up services before they are created.

Also, in Angular 1 the idea of loading code after the application has started is not yet supported. So if you want to have `angular-mocks` loaded then this needs to be done statically before the application starts.

**Comment by shawnmclean** [comment]
So my issue was fixed by removing http calls from the `.config` phase.

**Comment by petebacondarwin** [comment]
Glad you got it working.
