### ISSUE TITLE
Directives override

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular.js#11137]
As Angular community grows, and the number of libraries that extend it, the issue of directive override becomes more relevant. As of now, there is only support for 'priority', which doesn't override, rather combines directives according to the priority. And when needed a plain override isn't straightforward at all.

It would be nice that such a mechanism was provided in a simple way. For example, add attribute 'override:boolean' that would work in combination with 'priority', so the override happens according to the priority, i.e. higher priority can thus override an already registered directive as opposed to extending it by default.

Also, right now if a directive is registered twice, there is no meaningful error being logged. I'm getting the following error: <i>Uncaught TypeError: undefined is not a function</i>

<b>The most typical scenario is as follows:</b>

You are using a library where you have found a bug in one of the directives. And you do not have the time and/or desire of going through GitHub and the community to get the fix out. With a simple override in place you just copy the directive locally, fix the bug and declare it as an override - fast and simple fix, until the day the fix is finally released in that library. Patching otherwise the source is a very dangerous approach which way too often results in changes lost over automatic code updates and project re-installations.

**Comment by btford** [comment]
I think `npm link` and `bower link` both tackle this use case better.

Both of these tools also support installing from a github repo (e.g. `npm install btford/my-directive`) or from a zip/tar.

It's also possible to use decorators to patch just part of a module.

I wouldn't be opposed to adding a `thereCanBeOnlyOne:bool` flag to the directive definition that throws if another directive with the same name is registered. But I'm worried that adding a flag that changes which directives are used is going to result in a system that's difficult to reason about.

**Comment by awerlang** [comment]
I would suggest that such feature never make into AngularJS. It does not put emphasis on good design.

That does exists for instance in ExtJS. I don't see that as a good approach. You never know if the next version corrects the original problem, it could be too much code to compare. But if you fork and install off of it, its way better I think. Its not a patch.

In practice, most of the time I was able to create another directive to extend the original directive.

**Comment by Narretz** [comment]
If you really need this feature, you can use a decorator to modify the directives before they are applied.
