### ISSUE TITLE
Original stacktrace and/or error line/file lost.

### ISSUE THREAD

**Issue by rcollette** [angular/angular.js#11145]
Given code like

``` javascript
angular.module("app", []);

angular.module("app").controller('MyController', MyController);

var MyController = (function() {
  function MyController() {}
  return MyController;
})();
```

http://plnkr.co/edit/hnLuNs6523K1X3rx4xja

I get the error message

```
 Error: [ng:areq] Argument 'MyController' is not a function, got undefined
http://errors.angularjs.org/1.3.13/ng/areq?p0=MyController&p1=not%20a%20function%2C%20got%20undefined
    at REGEX_STRING_REGEXP (angular.js:63)
    at assertArg (angular.js:1580)
    at assertArgFn (angular.js:1590)
    at angular.js:8431
    at angular.js:7599
    at forEach (angular.js:331)
    at nodeLinkFn (angular.js:7586)
    at compositeLinkFn (angular.js:7078)
    at compositeLinkFn (angular.js:7081)
    at compositeLinkFn (angular.js:7081)angular.js:11607 (anonymous function)angular.js:8557 $getangular.js:14502 $get.Scope.$applyangular.js:1448 bootstrapApplyangular.js:4185 invokeangular.js:1446 doBootstrapangular.js:1466 bootstrapangular.js:1360 angularInitangular.js:26125 (anonymous function)angular.js:2744 triggerangular.js:3014 eventHandler
```

The location of the line that triggered the error is nowhere to be found in the logged stack trace.   Not only that, but it doesn't even list the initial angular function, `ngModule.controller(....)`, where the error initiated.  

Is there any way this can be improved?

I know in this simple example the problem is obvious but when you are dealing with a larger project, with TypeScript generating the code, the issue becomes less obvious and more so for someone will less Angular experience.

**Comment by pkozlowski-opensource** [comment]
@rcollette yeh, this is far from being ideal... The trouble is, though, that it is not JS that triggers controller instantiation but a template. This happens during the compilation / linking phase and at this point we've got only this info: `<div ng-controller="MyController">`.

The only thing I can think of being done easily here is to throw when trying to pass `undefined` as a second arg to `.controller`.

**Comment by rcollette** [comment]
I agree, when the second argument is `undefined`, `.controller` should throw.  I'm doing some refactoring right now.  When you get a controller not found error, it's a trek to find out whether it's an incorrect file reference, incorrect ordering, module mismatch, etc.

**Comment by Narretz** [comment]
This throws a more informative error in 1.6 (possibly earlier)
