### ISSUE TITLE
enable backtick for strings in $parse

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#11149]
With ES6, I can change this:

```javascript
var x = 'Hello ' + name + '! How are you ' + emotion + ' ' + timeOfDay + '?'
```

To this:

```javascript
var x = `Hello ${name}! How are you ${emotion} ${timeOfDay}?`
```

Which is easier to compose/read/maintain/etc.

I would love to be able to do this in my templates and other expressions:

```html
{{`Hello ${name}! How are you ${emotion} ${timeOfDay}?`}}
```

I haven't looked at what it would take to make this possible in the parser yet, but I thought I'd put this here to see how people feel about it before I look into the implementation.

**Comment by gkalpak** [comment]
I think in many (most? all?) cases, you can use `Hello {{name}}! How are you {{emotion}} {{timeOfDay}}?` (which is quite similar).

**Comment by kentcdodds** [comment]
True in templates, not true in javascript using the $parse service when
accepting an expression as an API to a function or something like that.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by gkalpak** [comment]
Not sure what you mean by _"when accepting an expression as an API to a function"_ :disappointed:

**Comment by kentcdodds** [comment]
Sure. Specifically, I'm the author of [angular-formly](https://github.com/formly-js/angular-formly) which allows you to [specify angular expressions](https://github.com/formly-js/angular-formly#expressions) to do some things. So, I would like users (and myself) of my library to be able to change this:

```javascript
{
  expressionProperties: {
    'data.someProp': "'Hello ' + name + '! How are you ' + emotion + ' ' + timeOfDay + '?'"
  }
}
```

with this

```javascript
{
  expressionProperties: {
    'data.someProp': '`Hello ${name}! How are you ${emotion} ${timeOfDay}?`'
  }
}
```

**Comment by kentcdodds** [comment]
But more than my just my library (and other people using the `$parse` service), I just think that with the way that the frontend is moving, it makes sense to me that the `$parse` service support this style.

**Comment by gkalpak** [comment]
So, while parsing ``'`Hello ${name}! How are you ${emotion} ${timeOfDay}?`'``, where is `name` etc coming from.
I am not sure how you use those expression properties, but wouldn't `$interpolate` be more appropriate ? 

<sub>I don't mean to imply this is not a useful feature. I am just trying to understand what it is about and make sure it is not already possible.</sub>

**Comment by kentcdodds** [comment]
They would be in scope. Like so:

```javascript
$parse(`Hello ${name}! How are you ${emotion} ${timeOfDay}?`)({
  name: 'World',
  emotion: 'feeling',
  timeOfDay: 'this morning'
});
```

Would result in:

```javascript
Hello World! How are you feeling this morning?
```

Which can [currently be accomplished](http://jsbin.com/bodemu/edit?js,console,output) with

```javascript
$parse("'Hello ' + name + '! How are you ' + emotion + ' ' + timeOfDay + '?'")({
  name: 'World',
  emotion: 'feeling',
  timeOfDay: 'this morning'
});
```

**Comment by gkalpak** [comment]
Why not use `$interpolate` with `{{...}}` (instead of `${...}`) ?
Wouldn't that work ?

**Comment by kentcdodds** [comment]
Ah, you mean [like this](http://jsbin.com/mixehu/edit?js,console,output):

```javascript
angular.module('app', []).run(function($interpolate) {
  var result = $interpolate("Hello {{name}}! How are you {{emotion}} {{timeOfDay}}?")({
    name: 'World',
    emotion: 'feeling',
    timeOfDay: 'this morning'
  });
  console.log(result);
});
```

That makes sense. Except I'm using `scope.$eval` and I would have to get all the properties of the scope to add to the locals for the interpolation which for some reason I feel like is not super straight forward to do. Suggestions? Either way that'd be a breaking change.

But like I said, let's not focus on my library or libraries like mine and let's just think about the concept in general I would like the ability to use backticks in expression. Do you think the use case is big enough that others would like to as well?

**Comment by gkalpak** [comment]
There is nothing wrong with using the `$scope` itself as `locals` or using `$scope.$eval()`.
E.g. assuming:

```js
$scope.name = 'World';
$scope.emotion = 'feeling';
$scope.timeOfDay = 'this morning';
var text = 'Hello {{name}}! How are you {{emotion}} {{timeOfDay}}?';
```
both of the following work fine:

```js
console.log($interpolate(text)($scope));
console.log($scope.$eval($interpolate(text)));
```

--
To be honest, I don't see how using backticks in epressions can be useful. Backticks only apply to strings and `$parse`'s job is not to build strings.
If I understand correctly, the purpose of this feature request is to be able to easily convert a string template into a string instance based on some locals (which happen to be properties on `$scope`, but could really be any object). This is exactly what `$interpolate` does, though :smiley:
<sub>Do I miss something ?</sub>

**Comment by kentcdodds** [comment]
No, I think you're right. This is sufficient. Thanks for the discussion @gkalpak.
