### ISSUE TITLE
angular-resource use synchronous http requests

### ISSUE THREAD

**Issue by MiladSadinam** [angular/angular.js#11141]
My angularjs version: 1.2.16

ngResource uses hardcoded asynchronous http requests. This is almost always desirable but will not work in onload/beforeunload events for some browsers (e.g. on chrome 40.0.2214.115). A quick test shows that synchronous request will instead work:

    $(window).on('beforeunload', 	function()
							{	
								var xmlhttp = new XMLHttpRequest();
								xmlhttp.open('PUT', 'my_url', false);
								xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
								xmlhttp.send("test");
							});

Is there another solution I am missing? Is there a chance that an option for synchronous requests will be implemented in future releases?

**Comment by pkozlowski-opensource** [comment]
Nope, sorry, we are not planning on adding synchronous XHR option as it is most probably going to disappear from the standard in the (near) future. Some browsers even warn you if people use sync XHR and rightly so as it usually leads to pretty bad user experience.
