### ISSUE TITLE
grunt with new npm:install has problems on Windows

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#11143]
The new npm install / caching behavior in grunt is causing some issues. Basically, when the new npm-install scripts tries to remove the contents of the node_modules folder I am getting a whole lot of cannot remove <really long path>: File or Path name too long. 
This is the stupid Windows restriction on very long file paths, I think. 
Because of this, the following npm install + shrinkwrap copy is never called, so I am ending up with a half empty node_modules folder.
I can empty the node_modules folder manually and call `scripts/npm/install-dependencies.sh` directly and this works, but I'd be running into this problem every time the shrinkwrap changes. 
Is it possible to delete the contents of node_modules differently?

cc @IgorMinar

**Comment by IgorMinar** [comment]
if rm fails, we don't want to try to install because npm will almost certainly not install all the files. so you'll see random errors at runtime.

can you figure out what needs to be done on windows to make the rm command just work?

I don't have easy access to windows nor the required expertise 😞

**Comment by Narretz** [comment]
It seems we can't use the rm command because Windows has a stupid 260 char restriction on file paths. It's a wontfix on joyents's side: https://github.com/joyent/node/issues/6960
There exists a module that emulates rm -rf specifically for node: https://github.com/isaacs/rimraf but I am not sure what would happen if it removes itself.
Or could we use npm uninstall x for all registered modules? I just checked, this works perfectly
That is, we'd need to get a list of modules in the package.json and then uninstall each of them manually

**Comment by IgorMinar** [comment]
try `rimraf`. measure if it adds significant overhead. if it does use it only on windows.

`npm uninstall` sounds very unefficient, but I don't know if it actually is.

**Comment by Bit-Rot** [comment]
rimraf doesn't seem to like deleting itself.  I get build errors attempting this.

I've found success in replacing the rm -rf call in install-dependencies.sh with:

```
npm ls --depth=0 --parseable=true | xargs npm remove
```

I'm not confident that this is solution in all environments, however.

**Comment by Narretz** [comment]
@Bit-Rot have you tried the code in this PR, and if not can you test if it works? https://github.com/angular/angular.js/pull/11353

**Comment by Bit-Rot** [comment]
@Narretz Just verified that the code in #11353 works for me.  Thanks :)

**Comment by xie-qianyue** [comment]
@Narretz I also tested the commit in #11353, it works for me. But why nobody solve the merge problem to make the pull request success?

**Comment by AmazingJaze** [comment]
Is this any closer to being resolved. It is also impacting my ability to build Angular on Windows.

**Comment by rebornix** [comment]
+1
