### ISSUE TITLE
Angular 1.3 doesn't work on android 2.3.3

### ISSUE THREAD

**Issue by hilahersko** [angular/angular.js#11153]
on my app i got:
SyntaxError: Parse error at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.js:16035

on the angularjs website, with the emulator built in browser, i got a broken page:
![angularjs_emulator](https://cloud.githubusercontent.com/assets/11165513/6336347/a6dc1a02-bbaa-11e4-9e9f-2cab0be93b7d.png)

**Comment by Narretz** [comment]
Hi, this will be fixed in the next release (1.3.14) which will land later this week.

**Comment by ericz** [comment]
@Narretz  Looks like 1.3.14 has dropped and I'm still seeing this issue:
http://cl.ly/image/3F1e0D2B0f0Z

And the log output: http://cl.ly/image/3U1I0b0N1V3C

**Comment by dmitryshepelev** [comment]
The same problem.
http://postimg.org/image/ue78k4iw3/

**Comment by isellsoap** [comment]
Then this issue should be reopened, right?

**Comment by dbabaioff** [comment]
It's fixed on 1.3.15
