### ISSUE TITLE
npm install on tutorial fails

### ISSUE THREAD

**Issue by dlaub123** [angular/angular.js#11151]
I'm following the first steps for installing the tutorial - install git, nodejs, cloned repo with no problems, but then get stuck here:

C:\Users\laubd\angular-phonecat>npm install
npm WARN package.json karma-chrome-launcher@0.1.7 No README data

> angular-phonecat@0.0.0 postinstall C:\Users\laubd\angular-phonecat
> bower install

bower not-cached    git://github.com/angular/bower-angular.git#1.3.x
bower resolve       git://github.com/angular/bower-angular.git#1.3.x
bower not-cached    git://github.com/angular/bower-angular-mocks.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-mocks.git#1.3.x
bower not-cached    git://github.com/jquery/jquery.git#~2.1.1
bower resolve       git://github.com/jquery/jquery.git#~2.1.1
bower not-cached    git://github.com/twbs/bootstrap.git#~3.1.1
bower resolve       git://github.com/twbs/bootstrap.git#~3.1.1
bower not-cached    git://github.com/angular/bower-angular-route.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-route.git#1.3.x
bower not-cached    git://github.com/angular/bower-angular-resource.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-resource.git#1.3.x
bower not-cached    git://github.com/angular/bower-angular-animate.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-animate.git#1.3.x
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github
.com/angular/bower-angular-animate.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=No error

npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install

**Comment by pkozlowski-opensource** [comment]
@dlaub123 this issue should be opened in the relevant repo, that is: https://github.com/angular/angular-phonecat

But there is no point of opening an issue for this particular case, as the error is clear:
> fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=No error

which basically means that your git client can't reach GitHub. This is a problem with your git setup - something that we can't fix on our end, I'm afraid....

**Comment by dlaub123** [comment]
clearly that isn't so - so the problem is more subtle than you might think:
 i.e. i CAN connect to github for this file with a partial command (see
below)  also I have no problem with this git command: npm install
angular-animate

C:\Users\laubd\angular-phonecat>git ls-remote --tags --heads
From https://github.com/angular/angular-phonecat.git
6701a1bd43deeed73d761bf0d1cf93a1d485c77b        refs/heads/fix-travis
395ebb2000a9e408083c142c8b3bca1b0c6a680b        refs/heads/gh-pages
fb0deab6a0b27d0bc23ec47bf95af22e4819b1e5        refs/heads/master
63a8ac6771e60763ac8b87a429c69ce385477010        refs/heads/v1.0-update
96a9b5b7fa5e5667e099d25c20a4bb19992c0f72        refs/tags/step-0
9d49dd95bdaca2c10f803e57e9fffb2c7d2905f6        refs/tags/step-1
ed4c127fefdccfe58e91b40daa2d5dd8dd19eedf        refs/tags/step-10
0b5bb30647e421617a0d0000103f4123f8597ff5        refs/tags/step-11
fb0deab6a0b27d0bc23ec47bf95af22e4819b1e5        refs/tags/step-12
ca46e1fd8dc13314152f22df1d8be3ceab9b4023        refs/tags/step-2
117af67a324f2aeffb4d1c1aa7b830cd0c162861        refs/tags/step-3
2d7b6547bd8667b3728997a9aca87434070569ee        refs/tags/step-4
1d084d35b6564cd63cab3beb3ced32d93ba77275        refs/tags/step-5
fb1b54084e60b1150a985cf8e316cff22cdec93e        refs/tags/step-6
2fe56e1a2bd9c8a3fb3fc5a0327e82bd18d44bc2        refs/tags/step-7
8564fb40c78507b4496a714f3aa5b93f7426292d        refs/tags/step-8
4147d18be0309c54282bc1c5f921c262897a110e        refs/tags/step-9
