### ISSUE TITLE
Add breaking change notes to docs for commit 531a8de72c439d8ddd064874bf364c00cedabb11

### ISSUE THREAD

**Issue by dnchristiansen** [angular/angular.js#11163]
Commit 531a8de72c439d8ddd064874bf364c00cedabb11 introduced a breaking change where the $observe function no longer gets called even for attributes that aren't defined. There is a note about this on the github page, but there is nothing about it in either the changelog or the migration guide.

I have been working on migrating from 1.2 to 1.3 and it took me a while to track down an issue because of this new behavior. I think it's worth adding a breaking change note to the change log and adding this to the migration guide (https://docs.angularjs.org/guide/migration), so people can be made aware of this breaking change.

**Comment by ilanbiala** [comment]
Anything happening with this?

**Comment by Narretz** [comment]
I've added a BC note. Due to the nature of the docs, this will however only appear in the next 1.4 and 1.5 versions, not in the 1.3 version.
