### ISSUE TITLE
Merge two different objects by a key

### ISSUE THREAD

**Issue by lilan123** [angular/angular.js#11166]
it might be best to have feature like linq query that we can merge different objects by a key and return new object without using foreach and create a different object. 

ex: 
$scope.obj1={id:001, name:jone};
$scope.obj2={empid:001, employeeType: permanent }

Expect : $scope.obj3={id:001,name:jone, empid:001, employeeType: permanent} 

to get this we have to write foEach, compare keys and push. but if we have something like below would be great 

data-ng-options="o.id for o in obj1 JOIN obj2 | where:  obj1 .id==obj2.empid"
{{o.id}} {{o.name}} {{o.employeeType}}

**Comment by pkozlowski-opensource** [comment]
@lilan123 yes, this sounds like a handy utility, but it is probably better done outside of the core. We are trying to limit number of utilities in the framework to keep in lean and focused.

I'm afraid that we are going to pass on this one...

**Comment by lilan123** [comment]
when you think of an application performance if we do this outside of the core will be leaded to performance issues. lets say if it is a huge data set comes from the API where API no longer accessible for modification this kind of features will lead the much user friendly framework. why wouldn't be added this to core and it won't break anything?

**Comment by pkozlowski-opensource** [comment]
@lilan123 the same work needs to be done, inside or outside of the core - I don't see how embedding the same code in the framework make it more performant... 

The downside of embedding it in the core is that it makes the core bigger for everyone, even for people that don't need this feature....

**Comment by gkalpak** [comment]
Just a heads-up: You don't necessarily need a `forEach` to accomplish property merging into a new object (in the controller).
Based on the nature of your objects, `angular.extend()` might do the trick (in a less verbose way): 

```js
var obj1 = {...};
var obj2 = {...};
var obj3 = angular.extend({}, obj1, obj2);
```

**Comment by lilan123** [comment]
Well, it is not really, var obj3 = angular.extend({}, obj1, obj2); will give a new merge object without compare the keys of merging objects. it has to be in forEach. :)

ex: 
$scope.obj1={id:001, name:jone};
$scope.obj2=[{empid:001, employeeType: permanent },{empid:002, employeeType: permanent }]

Expect : $scope.obj3={id:001,name:jone, empid:001, employeeType: permanent}

**Comment by gkalpak** [comment]
That's why I said _"based on the nature of your objects"_ :)

In your initial example `obj2` was an object. If it is an array of objects, the logic needs to be changed (the same holds when using `forEach`).

For your second example, the following might work (still being less verbose than `forEach`ing):

```js
var obj3 = angular.extend.apply(null, [{}, obj1].concat(obj2));
```

**Comment by lilan123** [comment]
I am really sorry, feel like i forgot my manners. Thanks a lot for the help. 

But anyway not only this purpose like looping and merging. If we can have something like Lambda Expressions from angularJs core will be great feature for developers. :)

**Comment by gkalpak** [comment]
Based on the description of #11175, it seems like I totally misunderstood your usecase.
My suggested solution (using `angular.extend()`) is invalid.
Sorry for that :)
