### ISSUE TITLE
$http request with date parameter crashes on IE8 on toISOString()

### ISSUE THREAD

**Issue by vincentsels** [angular/angular.js#11165]
On IE8, any $http request that passes a `date` parameter will crash with error message `Object doesn't support this property or method` because the `buildUrl` method uses the `toISOString()` method which only got introduced in IE9. Tested with Angular v1.2.24.

Offending line of code: https://github.com/angular/angular.js/blob/v1.2.x/src/ng/http.js#L1088

Easily fixed with [a polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString), but I'm not sure what Angular's point of view is regarding polyfills, I can't seem to find any other.

**Comment by pkozlowski-opensource** [comment]
@vincentsels oh, that's bad... At this point 1.2.x branch only gets critical bug fixes, memory leaks and security fixes... But I can see how this is breaking IE8 compatibility (albeit for a specific use-case only...).

[The polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) is a bit big, could you investigate if we could the same effect using a date filter? If we can come up with a minimal patch we could probably merge it.

But yeh, you probably the fasters way of dealing with the pb for you is to include the polyfill in your app...

**Comment by Narretz** [comment]
I am gonna close this, as 1.2.x is a legacy branch (also the last one to support IE8) and only receives critical bug fixes.
