### ISSUE TITLE
Select don't show the selected option with ngOptions label equals the $viewValue

### ISSUE THREAD

**Issue by felixcoto** [angular/angular.js#11170]
Go to this JSFiddle:
http://jsfiddle.net/felixcoto/v450hf7o/
1. Push in the button "Load Options"
2. The first select doesn't show the correct option

This issue is tested in Angular 1.3.13

**Comment by littleMing** [comment]
The value of two select is not the same. If you want to use one variable to set the value.You can write the html like this:
<select name="errorSelect" ng-model="testSelectCtrl.value" ng-options="option.name for option in testSelectCtrl.optionList track by option.name"></select>

**Comment by littleMing** [comment]
The value of two select is not the same.You should write the html like this:
```
<select name="errorSelect" ng-model="testSelectCtrl.value" ng-options="option.name for option in testSelectCtrl.optionList track by option.name"></select>
```

**Comment by Narretz** [comment]
Interesting. I see the bug in Chrome, but not in Firefox.It also works in 14.0 snapshot

**Comment by petebacondarwin** [comment]
I think this is one of the reasons that I completely rewrote the ngOptions directive in 1.4.

**Comment by petebacondarwin** [comment]
This is fixed n 1.4.x - see http://jsfiddle.net/jdt6s5sm/
It is going to be a right pain to fix properly in 1.3.x, which is why we did a complete rewrite of the directive for 1.4.0. @felixcoto could you consider migrating to 1.4? It is in release candidate and will be fully released in just a week or so.

**Comment by cyl3392207** [comment]
I think I met the same issue . Going to try the 1.4 version. Is there a workaround for a fix in 1.3.X?

This is a common scenario when I need to select the string value of a list of options instead of getting the Id. So typically I need to use " item.Name as Item.Name for item in items".

**Comment by cyl3392207** [comment]
OK. I found a ugly workaround:).  " item.Name as Item.Name+' ' for item in items". In this way the select and label are not identical. God, this took me a few hours to find out it is a bug....hoho

**Comment by Narretz** [comment]
We've decided not to fix this issue. See https://github.com/angular/angular.js/issues/11835#issuecomment-139913620 for more info
