### ISSUE TITLE
memory leak using the defer api of $q

### ISSUE THREAD

**Issue by noamkatzir** [angular/angular.js#11176]
HI there,

I'm working on a large SPA, and we use promises all over the application.
Lately in the invigoration on a major memory leak in the application, I discovered that if the defer object is never resolved/rejected and the closure on the promise keep reference to layout object which may include callbacks to trigger some logic, you can end up having serious memory leak. I guess it because the promises use setTimeout/setInterval in their implementation and the queue of the event loop of the browser  is keeping the reference from GC.

My solution to this issue was to subscribe to the $destroy event of the scope and reject the defer on destruction.

This make me wonder if we can have better angular api  out of the box, which will create defer object and promises and will make sure that the promises are rejected on scope destroy.

what do you think?

**Comment by lgalfaso** [comment]
Would it be possible to have a plunker that shows this issue? there is no global directory of all the promises, and a promise is just kept in memory as long as there is a reference to it. This is, a promise will be kept in memory as long as your application keeps a reference to it. There might be some circumstances that I am not aware that would prevent a promise not being GCed, but without some working example, there is not a lot to work with to fix this issue

**Comment by lgalfaso** [comment]
No plunker in 3 weeks that shows the issue, so I am closing this. If you are able to create a plunker that shows the issue, then feel free to reopen this issue
