### ISSUE TITLE
$rootScope:infdig error for deep nested jsons

### ISSUE THREAD

**Issue by vradder** [angular/angular.js#11186]
Hi All,
I am developing a tree control in angular, for this passing nested json in tree structure.
but getting $rootScope:infdig error if the nesting count is more than 10. 

After some research found that, this is cause of unstable module, But i am sure that using same module every time(Not using direct function to get the data or don't have any $watch expressions in this module change). 

 Could any please let me know how i can solve this ?

Thanks in advance, vradder.

**Comment by Narretz** [comment]
There's no way to assess this problem without a reproduction on a plnkr.co or similar. If you can provide this, please feel free to reopen the issue.
