### ISSUE TITLE
API documentation — readability enhancement

### ISSUE THREAD

**Issue by logeshpaul** [angular/angular.js#11187]
I was going through the API documentation, and figured out there is some readability issues. Before making a pull request I though of checking with the community for views.

**Existing Documentation**
- Improper vertical alignment
- Content look distorted makes little confusing to the user
![existing](https://cloud.githubusercontent.com/assets/41541/6387919/343be200-bdb9-11e4-9aed-9c8ceac67af0.png)

**Proposed Solution**
- Vertically aligning to top
- Give table borders to set boundaries and show information in a neat manner.
![proposal](https://cloud.githubusercontent.com/assets/41541/6387926/45af17f0-bdb9-11e4-99be-588b7269f302.png)

**Comment by Narretz** [comment]
Vertically align to top is a good idea. Not a big fan of borders all-around. Horizontal will probably help already to separate the sections.

**Comment by logeshpaul** [comment]
Hey @Narretz 

Thanks for the comments, Will work on it and update here.

**Comment by pkozlowski-opensource** [comment]
@logeshpaul cool, we like your changes. I'm not sure there is any point in keeping this issue open, just send us a pull request as soon you've got something that generates a better site! 

Thnx for stepping in and improving things!

**Comment by logeshpaul** [comment]
@pkozlowski-opensource sure thing!
