### ISSUE TITLE
https://blog.angularjs.org cannot load http content from blogspot

### ISSUE THREAD

**Issue by youpiwaza** [angular/angular.js#11191]
In the module tutorial there's a link "We've also written a document on how we organize large apps at Google." > https://docs.angularjs.org/guide/module

Sounds really interesting but the article just doesn't load on the blog :/

Consider put it back (I'd like to read it !) or remove the link.

Cheers

**Comment by Narretz** [comment]
It works with this address: http://angularjs.blogspot.de/2014/02/an-angularjs-style-guide-and-best.html

Strange. But then again, blogspot isn't Google's finest piece of software.

**Comment by MasamuneCode** [comment]
Thanks :)

**Comment by Narretz** [comment]
Looks like the angularjs.org forces `https`, but the content is `http`, and modern browser don't like that.

**Comment by gkalpak** [comment]
The link has been replaced by a link to @johnpapa's style-guide, so nothing to fix any more :smile:
