### ISSUE TITLE
Root 'a' tag causes: Template for directive '*' must have exactly one root element.

### ISSUE THREAD

**Issue by BastiHo** [angular/angular.js#11195]
My directive contains an `a` tag as the root element with several `a` tags inside. AngularJS shows this error:

```
Template for directive 'example' must have exactly one root element.
```

directive template:

```html
<a href="#!/examples/show/{{vm.example.id}}" class="example">
    ...
    <div svg-icon class="example__icon"></div>
    <div class="example__info">
        <ul class="menu">
            <li class="item">
                <a href="#!{{vm.path}}?edit={{vm.example.id}}">edit</a>
            </li>
            <li class="item">
                <a href="#!{{vm.path}}?delete={{vm.example.id}}">delete</a>
            </li>
        </ul>
    </div>
    ...
</a>
```

directive js:

```javascript
angular
    .module('examples')
    .directive('example', example);

function example() {
    var directive = {
        restrict: 'E',
        replace: 'true',
        templateUrl: 'components/examples/views/example.directive.html',
        scope: {
            example: '=',
            index: '=',
            examples: '='
        },
        link: link,
        controller: ExampleDirectiveCtrl,
        controllerAs: 'vm',
        bindToController: true
    };

    return directive;

    function link(scope, $el, attr) { ... }

}

ExampleDirectiveCtrl.$inject = [ ... ];

function ExampleDirectiveCtrl( ... ) { ... }
```

I traced the issue back to the function `removeComments` on line 8312. In this function, `jqLite` is called with the template's content as the only argument, which returns an array of three elements instead of one element:

```
0: a.example
1: div.example__info
2: text
```

The directive won't cause any errors if I replace the root `a` tag with a `div` or remove all child `a` tags. 
I'm using AngularJS v1.3.12.

**Comment by pkozlowski-opensource** [comment]
@BastiHo you can't have links within links and divs within links might be problematic depending on the HTML version used. If you put your HTML fragment into a doc and let a browser parse it you will see that it re-organizes elements so you effectively 3 nodes (a, div, text), see: http://plnkr.co/edit/HTRmPV72Vxrr3sI37xmM?p=preview

This is really a browser trying to "fix" your HTML even before AngularJS has any chance of processing it. Please remember that AngularJS processes "live DOM" as processed / seen by a browser and not a textual representation of a template.

Closing as invalid.
