### ISSUE TITLE
ng-options group by property not updated in AngularJS 1.3.12

### ISSUE THREAD

**Issue by m99coder** [angular/angular.js#11190]
If I use `ng-options` with group by syntax and afterwards the specified property is updated, there is no digest cycle fired for updating the `opt-group` tag. You can reproduce this by using viewing http://jsfiddle.net/m99coder/xof2s0b5/1/. If the AngularJS source is changed to 1.1.4 it works as expected.

What I would assume should happen is, that without selecting an option the `opt-group` value is updated after 3 seconds as implemented in controller.

Probably it would be possible to refactor it using `ng-repeat`, but then I would have to reimplement filtering, ordering and grouping by myself.

**Comment by pkozlowski-opensource** [comment]
Sounds like a valid bug.

**Comment by Narretz** [comment]
Embedding interpolation markup into expressions is not supported: https://code.angularjs.org/snapshot/docs/guide/interpolation
