### ISSUE TITLE
ngTouch in iPad did not improve tap handling

### ISSUE THREAD

**Issue by Elijahqm** [angular/angular.js#11197]
I know mobile safari handles ng-mouseover, ng-click and ng-mouseleave separately, but I supposed that ngTouch would fix this.
Here's a plunker with my testings. In mobile safari, ng-mouseover triggers first and then ng-click.
http://plnkr.co/edit/DcA73t1VSdrcQtGDCCRB?p=preview

**Comment by AdriVanHoudt** [comment]
I am having this trouble as well any way to fix?
