### ISSUE TITLE
googleapis cdn blocked in china.  Please can you host angular and jquery in angularjs.org domain?

### ISSUE THREAD

**Issue by hughperkins** [angular/angular.js#11209]
Hi,

googleapis is blocked in china, meaning angularjs.org docs are not viewable.  Please can you:
- either make angularjs.org docs have a non-angular fallback, so can view without angular, or
- host angular and jquery directly on angularjs.org servers, so viewable in China.

Hugh

PS Angular is awesome :-)

**Comment by jimaek** [comment]
If you want you can also use http://www.jsdelivr.com/#!angularjs
We are not banned in China and we are actually working with Chinese providers to add multiple locations there

**Comment by pkozlowski-opensource** [comment]
@jimaek my impression is that @hughperkins is trying to say that the doc site (https://docs.angularjs.org/api) is referencing AngularJS library from ajax.googleapis.com, making the doc site effectively unusable from placeless where ajax.googleapis.com is not reachable. 

@petebacondarwin @IgorMinar does it makes sense to switch to https://code.angularjs.org/?

**Comment by hughperkins** [comment]
@pkozlowski-opensource , yes right :-)  Screenshot:
![angularinthailand](https://cloud.githubusercontent.com/assets/123560/6426269/76a514fe-bf85-11e4-8e74-e1d7daba2426.png)

**Comment by petebacondarwin** [comment]
This is easy enough to get around. The docs application has a number of different index files that you can use as the starting point. By default the https://doc.angularjs.org maps to the `angular-production.html` file which loads angular from the CDN.

Instead you can use `https://docs.angularjs.org/index.html`, which loads the minified angular files locally or you can use `https://docs.angularjs.org/index-debug.html`, which loads the un-minified files locally. You can see the deployment setup for each of these files here: https://github.com/angular/angular.js/tree/master/docs/config/services/deployments

Once the docs application has loaded, it will remove the index.html filename from the URL, but as it is an SPA you can navigate around without any problems. Just realise that if you reload the page (or link to a docs page from outside the app) it will default back to loading the CDN based version.

**Comment by hughperkins** [comment]
That works great! Thanks! 

-------- Original message --------

**Comment by petebacondarwin** [comment]
I'm going to close this then, if that is OK.
