### ISSUE TITLE
ngOpen will not work or appear on Mozilla Firefox (Needs Bug fix)

### ISSUE THREAD

**Issue by taylormi** [angular/angular.js#11208]
ngOpen will not work or appear on Mozilla Firefox.

In order to duplicate this issue visit  https://docs.angularjs.org/api/ng/directive/ngOpen and click on the "Edit in Plunker" button in a Mozilla Firefox browser.

I think ngOpen most likely needs a bug fix.

**Comment by pkozlowski-opensource** [comment]
`ngOpen` just manages the HTML's 5 `open` attribute on the `<details>` element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) and FF doesn't support this element / attribute: http://caniuse.com/#feat=details

It looks like they are working on adding support for it, though: https://bugzilla.mozilla.org/show_bug.cgi?id=591737

Closing this one as there is not much we can do about this situation in Angular. You can vote on the FFox bug though.
