### ISSUE TITLE
Form email validation issue

### ISSUE THREAD

**Issue by VizuaaLOG** [angular/angular.js#11207]
I was looking through the guide on forms within angular and noticed that in the first example the email field validates if the value is like the following "myemail@mail", this is still not a valid email.#https://docs.angularjs.org/guide/forms

**Comment by Narretz** [comment]
It is a valid email. Emails don't need top level domains, only a valid host name see e.g. http://en.wikipedia.org/wiki/Email_address#Domain_part

**Comment by VizuaaLOG** [comment]
Ah ok, thanks for the info I understand it now :)
