### ISSUE TITLE
Invalid cookies decoder.

### ISSUE THREAD

**Issue by dangreen** [angular/angular.js#11216]
When i put cyrillic string in cookie, `$cookies` (`$browser.cookies()`) give me that:

    ÐÐµÐ²ÐµÑÐ½ÑÐ¹+email+Ð¸Ð»Ð¸+Ð¿Ð°ÑÐ¾Ð»Ñ

**Comment by pkozlowski-opensource** [comment]
@dangreen how do you set those cookies? What is the document encoding that you are using? What is the initial value of a cookie? We would need more details to progress on this one....

If you are not able to provide the reduced scenario, maybe you could help us debugging this pb in your environment? Cookies reading is happening in https://github.com/angular/angular.js/blob/master/src/ng/cookieReader.js (at least in the latest version from master)

**Comment by pkozlowski-opensource** [comment]
@dangreen I haven't heard from you so going to close this one for now. Feel free to re-open if / when you've got more info.
