### ISSUE TITLE
dynamic function in ng-repeat not working.

### ISSUE THREAD

**Issue by rajzshkr** [angular/angular.js#11218]
Hi I am facing one problem in ng-repeat. 
When I iterate an a list using ng-repeat and binding a dynamic function using ng-click. 

When I click on that list, the function binded through ng-repeat is not getting triggered. Instead throwing some error.

Please help in solving this . Thanks.

**Comment by veerendrakumar-github** [comment]
Hi rajzshkr,can u give example here then easily i can understand will solve your problem.

**Comment by veerendrakumar-github** [comment]
this is html
============
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.5/angular.js"></script>
<script src="test.js"></script>
<form ng-app="testApp" ng-controller="testController">
    <table>
        <tr ng-repeat="dt in data" ng-click="clickMe(dt)">
            <td>{{dt.name}}</td>
        </tr>
    </table>
</form>


js file looks like(test.js)
--------------------------------
angular.module("testApp", []).controller('testController', function(
    $scope, messageService)
{
    $scope.data = [
    {
        "name": "veeru",
        "function": "one()"
    },
    {
        "name": "veeru1",
        "function": "two()"
    },
    {
        "name": "veeru2",
        "function": "three()"
    },
    {
        "name": "veeru3",
        "function": "four()"
    },
    {
        "name": "veeru4",
        "function": "five()"
    },
    {
        "name": "veeru5",
        "function": "six()"
    }, ]
    $scope.clickMe = function(data)
    {
        console.log(data);//here you will get trigger what ever you clicked that object data will come.
    }
});

this is dynamicallu binding ng-click and getting current triggered object.i think this useful useful for you if you not clear please ping me mail vallepu.veeru@gmail.com

**Comment by Narretz** [comment]
Hi, please ask support questions on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Btw, you'll increase the chance of getting help by including the error message and a runnable example of your problem in a plnkr.co or similar.

**Comment by veerendrakumar-github** [comment]
I did not find out here how to ask support question in this https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question, site.
can u give please give exact place in this site.

**Comment by rajzshkr** [comment]
http://jsbin.com/fofelu/1/.

Please check the above bin. Still it is not working.

**Comment by veerendrakumar-github** [comment]
here we cant this way because what ever u mentioned inside json  "action":
"test1()"
it will take string type only but not function
so here i did example please see this.
http://jsfiddle.net/veerendrakumarfiddle/nkuDW/77/



*Thank Q,with your regards..*

*vallepu veerendra kumar.*
