### ISSUE TITLE
DispHTMLDOMTextNode Object doesn't support this property or method

### ISSUE THREAD

**Issue by drpicox** [angular/angular.js#11227]
Affects: IE8 Angular v1.2.28 

I have found which seems an historical bug, I'm not clear the origin (but I know perfectly how to reproduce) , I didn't found any previous issue like this.

This happens only in IE8.

Problematic code: ( http://jsfiddle.net/yfg1kjhf/1/ )

```html
<div ng-app="demo">
    <div ng-controller="DemoController as vm">
        <div test>
            Bar: -{{vm.bar}}- <br/>  
            <input ng-model="vm.bar" /> <br>  
        </div>
    </div>
</div>
```

Test template is `"<div ng-transclude></div>"`. 
Reporte error: Object doesn't support this property or method. References to test template element.

*The problem is* the space between `<input>` and `<br>`.

*How to reproduce*:
- open http://jsfiddle.net/yfg1kjhf/1/embedded/result/ with IE10 in IE8 compatibility mode (it should fail)

Contraexample which works (does not have the space):
- http://jsfiddle.net/yfg1kjhf/embedded/result/ (it should work)

*Where seems to be originated*?

While debugging I found the function jqLiteExpandoStore which has as element a DispHTMLDOMTextNode and it tries to assign a new property for that object: `element.ng339 = value;` but IE8 does not allows to add/modify ng339 property. In this point fails.

What I do not know why only fails in this case. And not sure that it is because ng-transclude also.

**Comment by gkalpak** [comment]
I am not sure if this is fixable in Angular 1.2.x (nor do I remember the exact cause of this), but happens under the following circumstances:

> When there is white-space before and/or after (can't recall) certain elements:
  * `<input>` is affected for sure
  * `<select>` might be affected also

--
You can see a version of your fiddle working in IE8 by removing the white-space around `<input>` [here][1].
<sub>(Of course, this is just a workaround, not a proper solution.)</sub>

[1]: http://jsfiddle.net/yfg1kjhf/3/embedded/result/

**Comment by drpicox** [comment]
Yep,
this workaround is just the same that I have apported.

The problem is that the error is difficult to understand, and of course, it is IE8/10, difficult to debug. May be a try {} catch with better error message can be added.

**Comment by Narretz** [comment]
I am gonna close this, as 1.2.x is a legacy branch (the last one to support IE8) and only receives critical bug fixes.
