### ISSUE TITLE
When I use the directive ngBlur, it occurs twice.

### ISSUE THREAD

**Issue by alexandremaeda** [angular/angular.js#11226]
I researched about it, but found nothing, and also can not understand why this occurs. Has anyone experienced this?

**Comment by gkalpak** [comment]
This is a support question and should be directed to the [appropriate channels][1].
GitHub is reserved for Angular bug reports and feature requests.
<sub>
BTW, with the provided info it is impossible to diagnose the problem.
You should provide a more detailed description (and preferrably a runnable reproduction, e.g. using JSFiddle, Plnkr etc).
</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
