### ISSUE TITLE
How to de-bootstrap angular application

### ISSUE THREAD

**Issue by vikasnawal** [angular/angular.js#11224]
Hi Guys,

I am integrating angularjs with backbone.js application for better code quality and performance.
Now i am facing only one issue with that.how can i de-bootstrap angular application which i added manually on trigger of click event.so whenever i click on link,the boostrap code attached to link and i am getting error like angularjs application already bootstrapped

Please let me know any suggestion on this issue so that on click on link or button, i could check that angular application start or not.

Any help on this is highly appreciated.

**Comment by pkozlowski-opensource** [comment]
@vikasnawal putting aside serious reservations I would have about your proposed architecture (that is, continuously bootstrapping and destroying an AngularJS app), it is not currently possible to cleanly shut-down an app. But we've got an issue for this already (#7578) so closing as a duplicate.
