### ISSUE TITLE
Bad 'vo' locale translations

### ISSUE THREAD

**Issue by malafaya** [angular/angular.js#11229]
In angular-locale_vo.js (and also ...vo-001.js), the names of months are incorrect:

    "MONTH": [
      "janul",
      "febul",
      "m\u00e4zil",
      "prilul",
      "mayul",
      "yunul",
      "yulul",
      "gustul",
      "setul",
      "tobul",
      "novul",
      "dekul"
    ],

<i>janul</i> should be <b><i>yanul</i></b> and <i>mäzil</i> should be <b><i>mäzul</i></b>.
You can check https://pt.wiktionary.org/wiki/Categoria:M%C3%AAs_%28Volapuque%29 for all months.
Thanks.

**Comment by pkozlowski-opensource** [comment]
@malafaya we are talking about [Volapük](http://en.wikipedia.org/wiki/Volap%C3%BCk) language, right? 

In fact we are pulling those translations from the [CLDR](http://cldr.unicode.org/) repository (hopping through the [closure library](https://github.com/google/closure-library/tree/master/closure/goog/i18n) so this will have to be corrected upstream.

**Comment by malafaya** [comment]
OK, thank you.
I'll try to remember that for the next CLDR review.

**Comment by Narretz** [comment]
I'm curious, why does you app support Volapük? Even among constructed languages this one is quite exotic. ;)

**Comment by malafaya** [comment]
I'm not using Volapük in my apps. I'm just starting with AngularJS. I happen to be a (weak) Volapük enthusiast so I was intrigued to see Volapük was supported. Having seen the mistakes, I thought it was my obligation to try and correct them (if I don't who will?) :)) .

**Comment by lgalfaso** [comment]
Volapük was moved at the CLDR from `common` to `seed`, this implies that there is a high chance that it will just get removed from the closure library (and then from Angular). With this info, I think there are not a lot of reasons on why to keep this issue open

**Comment by lgalfaso** [comment]
Just in case, here is the relevant information http://unicode.org/cldr/trac/changeset/11278/trunk/common
