### ISSUE TITLE
ng-if no longer works with ng-messages as of 1.4.0beta5

### ISSUE THREAD

**Issue by lytnus** [angular/angular.js#11220]
Hello,

Upgrading to the latest angular beta has seemed to break my use of ng-if's on ng-message directives.

Plunkr reproducing the issue (type something then click off to fire the error):

http://plnkr.co/edit/grWkyzLNg39osNrJ5wGi

The error:

```
[$compile:ctreq] Controller 'ngMessages', required by directive 'ngMessage', can't be found!
```

This seems to be the case even if there is an ng-if higher up eg:

http://plnkr.co/edit/Fc6bJ5vNMF5LGYJ2dGhZ

(sorry if this is the wrong place to bring this up; I realise ngMessages is separate from angular core!)

**Comment by Narretz** [comment]
No worries, `ngMessage` is a separate module, but it lives in this repo. Can you please test with the latest snapshot (//code.angularjs.org/snapshot/angular-message.js)? I think this is fixed in master.

**Comment by lytnus** [comment]
Thanks for the quick response, I have no more issues with the latest snapshot and both of the plunkr's are equally happy!

**Comment by Narretz** [comment]
Great! I'm gonna close this then - the next release should come this week.
