### ISSUE TITLE
Angular Feature Request

### ISSUE THREAD

**Issue by atki4564** [angular/angular.js#11231]
create browser.main.view.html which creates (or updates) all app/data/design object types as part of 1 universe model object, and related database server operation -- that is, as 1 data object list (or universe, oVar, etc) of many nested data object lists of instance data objects of object type in 1 universe model object, and thus circularly (or reflectively), which, in circular turn, automatically
creates (or updates) each angular.webpage.html of each app/data/design object type which
creates (or updates) each mongoose/mongodb object type of each app/data/design object type which
creates (or updates) each instance data object of each app/data/design object type in the database server operation, and thus enables a 6-year-old programmer to automatically
create (or update) variable naming operation, and related renaming (or refactoring) operation, in database server operation, 
create (or update) function naming operation, and related /renaming (or refactoring) operation, in database server operation, including automatically creating (or updating) operations (or functions) of
logical function operation of 
if branching operation and
loop branching operation of
for loop operation and
while loop operation
and
mathematical function operation of 
add, 
subtract, 
multiply, 
divide
etc 
why; because creating (or updating) all app/data/design object types, and related instance data objects, as part of 1 universe model object, and related database server operation, operated from browser.main.view.html will circularly result in substantially less manual coding operation and substantially more individual/business analysis operation, which analysis, not coding (or design), is the true value of any app (or business)
note: this is a difficult app to create for the initial programmer because of its circular logic operation, but thereafter, it’s not difficult for subsequent 6-year-old programmers to operate who will thereafter have a software development operation which they can easily and quickly operate quantitative analysis operation, qualitative analysis operation, etc, using automatic coding operation

**Comment by pkozlowski-opensource** [comment]
@atki4564 I'm afraid that I don't exactly understand what you are asking for here... but it seems to me like you are asking for a out-of-the-box support for all the CRUD operations, with view and server-side integrations. If this is the case I'm afraid that this is something outside of the angular core scope. ngResource is a step in this direction, but you seem to be asking for much more.

What I would suggest is that you start off by publishing a 3rd party module doing what you require and if it gets enough traction / captures interesting use-cases, parts of it (or the whole) could be incorporated into the core. For example a new router is following this pattern where a 3rd party ui-router paved the path to the new Agnular router.

Closing as "not core" for now.

**Comment by gkalpak** [comment]
@pkozlowski-opensource: :bow: You understood all that from this post ?
<sub>(All I understood was that someone is employing under-aged developers (which is illegal, btw).)</sub>

**Comment by pkozlowski-opensource** [comment]
@gkalpak I was using my imagination :-)

**Comment by atki4564** [comment]
I already created a prototype CRUD app using goog app script at
http://www.strategicinternationalsystems.com/entrepreneurial-workflow-engine-1
; however, it doesn't have all the features I suggested yet and it needs to
be redone in nodejs/mongoose/mongodb (on the back-end to drive html
creation in angular on the front-end) next, but you're right, this is
something I need to do myself as an extension of angular so that myself and
others can quickly write angular html (which is exactly what I must do to
speed CRUD programming in favor of business analysis of that CRUD as I
said). I emailed the above general spec and above app (just now) to see if
you have any plans for this angular html grneration of CRUD; if not (as you
said), I'll do it for angular as an fork of your open source site; that's
the least I can do for your fine app is to extend it so that a 6-year-old
can program CRUD angular html. However, I think that CRUD angular html
generation is definitely "core", which is why I asked. Thank for your time
and consideration.

On Tue, Mar 3, 2015 at 9:18 AM, Pawel Kozlowski <notifications@github.com>
wrote:

> @gkalpak <https://github.com/gkalpak> I was using my imagination :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/issues/11231#issuecomment-76952749>
> .
>



-- 
Thank you for your time and consideration,
Eric Atkinson
Chief Technology Officer
MoneyOnTrees.net

**Comment by atki4564** [comment]
btw, I'm not employing 6-year-olds (and with parental consent there is nothing "illegal" about it if I did). What I said was that  "a 6-year-old could program" a CRUD app using angular html generation  if the "core" had an angular html generator tied to a database. If you don't understand what I'm saying, fine, but "don't mock what you don't understand" (please)

**Comment by atki4564** [comment]
Click the 'enlist' button to see the prototype app I had in mind for
angular html generation

On Thu, Mar 5, 2015 at 8:41 PM, Eric Atkinson <
eric.atkinson@strategicinternationalsystems.com> wrote:

> I already created a prototype CRUD app using goog app script at
> http://www.strategicinternationalsystems.com/entrepreneurial-workflow-engine-1
> ; however, it doesn't have all the features I suggested yet and it needs to
> be redone in nodejs/mongoose/mongodb (on the back-end to drive html
> creation in angular on the front-end) next, but you're right, this is
> something I need to do myself as an extension of angular so that myself and
> others can quickly write angular html (which is exactly what I must do to
> speed CRUD programming in favor of business analysis of that CRUD as I
> said). I emailed the above general spec and above app (just now) to see if
> you have any plans for this angular html grneration of CRUD; if not (as you
> said), I'll do it for angular as an fork of your open source site; that's
> the least I can do for your fine app is to extend it so that a 6-year-old
> can program CRUD angular html. However, I think that CRUD angular html
> generation is definitely "core", which is why I asked. Thank for your time
> and consideration.
>
> On Tue, Mar 3, 2015 at 9:18 AM, Pawel Kozlowski <notifications@github.com>
> wrote:
>
>> @gkalpak <https://github.com/gkalpak> I was using my imagination :-)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/angular/angular.js/issues/11231#issuecomment-76952749>
>> .
>>
>
>
>
> --
> Thank you for your time and consideration,
> Eric Atkinson
> Chief Technology Officer
> MoneyOnTrees.net
>
>


-- 
Thank you for your time and consideration,
Eric Atkinson
Chief Technology Officer
MoneyOnTrees.net

**Comment by atki4564** [comment]
Prototype application operation meaning:


   1.

   In the object type window
   <http://www.strategicinternationalsystems.com/entrepreneurial-workflow-engine-1>
   (after clicking the ‘enlist’ button), you, as a programmer, select
   ‘Create’ (in the first dropdown box) to create new object types, or select
   an old object type in the object types window to update an old object type,
   such that...
   2.

   An additional dropdown box called ‘Operation?’ is then shown in the
   object type window whereby you select one of many operations to create (or
   update) that object type, such that...
   3.

   You create (or update) all object types (ideally) in your application
   first, such as the human object type, as well as its related subtypes of
   taxpayer identification, password, etc in the subtypes window thereunder,
   such that…
   4.

   If you select ‘Update’, ‘Query’, or ‘Delete’ (in the first dropdown box)
   and ‘Data’ (in the second dropdown box), then you and/or others, as users,
   can update, query, or delete data object(s), such as your human data
   object (or account).
   5.

   Finally, the object code window shows your selected object type, and
   related subtypes, as javascript/json code


On Thu, Mar 5, 2015 at 9:08 PM, Eric Atkinson <
eric.atkinson@strategicinternationalsystems.com> wrote:

> Click the 'enlist' button to see the prototype app I had in mind for
> angular html generation
>
> On Thu, Mar 5, 2015 at 8:41 PM, Eric Atkinson <
> eric.atkinson@strategicinternationalsystems.com> wrote:
>
>> I already created a prototype CRUD app using goog app script at
>> http://www.strategicinternationalsystems.com/entrepreneurial-workflow-engine-1
>> ; however, it doesn't have all the features I suggested yet and it needs to
>> be redone in nodejs/mongoose/mongodb (on the back-end to drive html
>> creation in angular on the front-end) next, but you're right, this is
>> something I need to do myself as an extension of angular so that myself and
>> others can quickly write angular html (which is exactly what I must do to
>> speed CRUD programming in favor of business analysis of that CRUD as I
>> said). I emailed the above general spec and above app (just now) to see if
>> you have any plans for this angular html grneration of CRUD; if not (as you
>> said), I'll do it for angular as an fork of your open source site; that's
>> the least I can do for your fine app is to extend it so that a 6-year-old
>> can program CRUD angular html. However, I think that CRUD angular html
>> generation is definitely "core", which is why I asked. Thank for your time
>> and consideration.
>>
>> On Tue, Mar 3, 2015 at 9:18 AM, Pawel Kozlowski <notifications@github.com
>> > wrote:
>>
>>> @gkalpak <https://github.com/gkalpak> I was using my imagination :-)
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/angular/angular.js/issues/11231#issuecomment-76952749>
>>> .
>>>
>>
>>
>>
>> --
>> Thank you for your time and consideration,
>> Eric Atkinson
>> Chief Technology Officer
>> MoneyOnTrees.net
>>
>>
>
>
> --
> Thank you for your time and consideration,
> Eric Atkinson
> Chief Technology Officer
> MoneyOnTrees.net
>
>


-- 
Thank you for your time and consideration,
Eric Atkinson
Chief Technology Officer
MoneyOnTrees.net
