### ISSUE TITLE
how to generate thumbnail using video url for jquery jplayer

### ISSUE THREAD

**Issue by udayaravi** [angular/angular.js#11237]
i need create to show thumbnail image in poster by using video url for jquery j-player.i have seek in forum.but i didn't got any useful information related to thumbnail.anyone can give me some ideas to do it..
Thanks Advance..

 $("#jquery_jplayer_2"+playid).jPlayer({
        ready: function () {
			//console.log(playpath);
			
			
			
			
            $(this).jPlayer("setMedia", {
                /*m4v: "media/tokyo.m4v",
                ogv: "media/tokyo.ogv",
                poster: "media/poster.jpg"*/
				m4v: playpath,
                ogv: playpath,
                poster: playpath
            });
        },
        ended: function (event) {
            $("#jquery_jplayer_2"+playid).jPlayer("pause", 0);
			//$("#jquery_jplayer_2"+playid).jPlayer( "destroy" );
        },
        swfPath: "player/example45/swf/Jplayer.swf",
        supplied: "m4v, ogv",
        cssSelectorAncestor: "#jp_interface_2"
    })
    .bind($.jPlayer.event.play, function() { // pause other instances of player when current one play
            $(this).jPlayer("pauseOthers");
    });

**Comment by Narretz** [comment]
For support questions, please use the channels described here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
