### ISSUE TITLE
Problem with binding in 1.4.0

### ISSUE THREAD

**Issue by v21k93** [angular/angular.js#11234]
Im not sure if this is bug or something but in older version( AngularJS v1.2.24 ) this way of binding works fine and was printing 
```HTML
<div ng-controller="AngularIndexController">
    <h2>Message - AngularIndex</h2>
</div>
```

My code is:
```javascript
'use strict';

/* Controllers */

angular.module('AngularIndex', [])
	.controller('AngularIndexController', function ($scope, $http, userService) {
		if (userService.AngularIndex === undefined) {
		    userService.AngularIndex = {
		        Text: "AngularIndex",
                ObjectText: "AngularIndex"
		    }
		}

		$scope.this = userService.AngularIndex;
});
````

I also have factory for that userService and its working fine im sure

```javascript
.factory('userService', function () {
    var _UserService = {};

    return _UserService;
})
```

And the HTML is that

```HTML
<div ng-controller="AngularIndexController">
    <h2>Message - {{this.Text}}</h2>
</div>
```

Like i said in the older version ( AngularJS v1.2.24 ) this code was working fine. Please let me know if im doing something wrong or it's just a bug. 

Thanks.

**Comment by pkozlowski-opensource** [comment]
This is a [documented](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#130-rc4-unicorn-hydrafication-2014-10-01) breaking change in 1.3.0-rc.4.

**Comment by v21k93** [comment]
Thank u : ))
