### ISSUE TITLE
angular.isNumber() does not check for NaN

### ISSUE THREAD

**Issue by jparmar** [angular/angular.js#11230]
The current code for isNumber function only checks for value data type.

The issue is : typeOf NaN is also 'number'

there should be additional check to return false when value for isNumber function is NaN

**Comment by pkozlowski-opensource** [comment]
@jparmar I'm not convinced we should add the proposed change. What is your motivation for proposing this change - that is - what is the practical use-case that you are facing in your day-to-day life?

**Comment by pkozlowski-opensource** [comment]
BTW: this would be a breaking change so shouldn't be taken lightly...

**Comment by jparmar** [comment]
the simple use case would be read a textbox value and check for its number validation.

consider my model is question and question.value is bind to a textbox.
assume user has entered text value in that text box, then my model would be <code>question.value = 'xyz' </code> for example.

here If I assume that user has entered number then my validation would fail as follows.

<code>   var v = parseFloat(question.value, 10);  // v would be NaN </code>
 <code>  
   if(!angular.isNumber(v)) {  // this test will not fail as angular.isNumber(NaN) returns true
		question.hasError = true;
   }
</code>

**Comment by petebacondarwin** [comment]
But `angular.isNumber(question.value) === false`.

Calling `parseFloat` is converting the given `value` to a number, so one can argue that `angular.isNumber(parseFloat(anything)) === true` is a reasonable convention.

**Comment by wesleycho** [comment]
`NaN` is a number, this sounds like it would be a bad change to `angular.isNumber`.  Libraries such as Underscore and Lodash handle it the same way, as seen [here](http://underscorejs.org/#isNumber) and [here](https://lodash.com/docs#isNumber).

**Comment by petebacondarwin** [comment]
Thanks @wesleycho  - I updated the docs to clarify this and that one can use `isFinite` instead.
