### ISSUE TITLE
ngMessageExp should be documented

### ISSUE THREAD

**Issue by lgalfaso** [angular/angular.js#11240]
There is no documentation entry for ng-message-exp

**Comment by petebacondarwin** [comment]
It is in the docs here: https://docs.angularjs.org/api/ngMessages/directive/ngMessage

![screen shot 2015-03-04 at 18 59 11](https://cloud.githubusercontent.com/assets/15655/6490779/adf2f0ac-c2a0-11e4-83a1-531cb395e1ec.png)

**Comment by lgalfaso** [comment]
then it would be nice to have a link at the side menu and the title changed to also mention ngMessagesExp

**Comment by petebacondarwin** [comment]
But it is an attribute on the `ngMessage` directive not a directive of its own.

**Comment by petebacondarwin** [comment]
Oh, I see. It is an alias of the `ngMessage` directive.

**Comment by petebacondarwin** [comment]
Fixed at 2d0eda10e43f6b079b531c507282fad082ea0762
