### ISSUE TITLE
Angular cannot read cookies in http post response

### ISSUE THREAD

**Issue by santoshkt** [angular/angular.js#11247]
Similar question has been answered https://groups.google.com/forum/#!topic/angular/yc8tODmDm18 and many other places. The solution is to set a timeout to call a digest so that response cookies sync with browser. I had this solution working perfectly in 1.2.8 but got it broken in 1.3.14. Any idea if this has changed ?

I'm not posting any code here because the problem is same as in the link provided and it is working in 1.2.8 Angular version and 1.2.28 version.

I had to change my interceptors for upgrading to 1.3.14 but they all work fine except for the cookies. I can see cookies in browser.

**Comment by santoshkt** [comment]
This is same as https://github.com/angular/angular.js/issues/7631 and https://github.com/angular/angular.js/issues/10861

But I can't get it working using timeout as well.

**Comment by santoshkt** [comment]
I did this before access cookies

$cookies = $browser.cookies();

Looks to be a very dirty fix as I'm not really directly using browser at all places. Just once place which breaks my application, I did above. Not sure of the impact of changing the dependency variable.

**Comment by lgalfaso** [comment]
The `$cookies`service is async (with all its pros and cons) and issues like this are the reason why it is deprecated in 1.4. The synchronous mechanism, this is `$browser.cookies()` works best in this case
