### ISSUE TITLE
How to display only + and - signs for input[type = number] instead of numbers using spinners

### ISSUE THREAD

**Issue by swathi1029** [angular/angular.js#11253]
Hi,

 I had a requirement of showing + and - signs in the input control with spinners i.e., if I click on up arrow of the spinner it should show '+' sign and by clicking on down arrow it should show '-' sign. How can I do this?

**Comment by Narretz** [comment]
`input[number]` does not allow any way to customize or hook into the behavior of the spinners - this is browser specific and has nothing to do with angular. You can only hide them, see https://github.com/angular/angular.js/issues/11072#issuecomment-75141678

That said, for future support questions, please refer them to the channels described in https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#SUPPORT

**Comment by gkalpak** [comment]
Just to avoid confusion, I believe this question is about showing +/- as the *value* of the input (not as spinner button labels), in which case the linked comment won't help.
This is still a support question, so what @Narretz said still holds :)
