### ISSUE TITLE
docs: $filter('filter')  Migration 1.2.x to 1.3.x ; Broken change

### ISSUE THREAD

**Issue by guilbep** [angular/angular.js#11254]
Here are the facts:

```js
ng-repeat="el in list | filter:{'key': undefined}"
```

Does not behave the same on 1.2 and 1.3; here are some jsfiddles:
for angular 1.2.x (http://jsfiddle.net/guilbep/2w8ouzr0/)
for angular 1.3.x (http://jsfiddle.net/guilbep/3kj5ug98/)

I've seen nothing in /guide/migration nor in that section 'Angular Expression Parsing'  .. Maybe it is; But it is not clear enough;

I'd be glad to have direction on how and where to improve the docs for this part.

Thank you.

**Comment by gkalpak** [comment]
This was a regression (introduced in v1.3.6). It has been fixed with 63b9956 and will be fixed with the next 1.3.x release.
(In fact, it is [working as expected][1] in master.)

[1]: http://jsfiddle.net/ExpertSystem/3kj5ug98/3/

**Comment by Narretz** [comment]
Thanks @gkalpak - I think we can close this issue then.

**Comment by guilbep** [comment]
@gkalpak @Narretz Good :) thank you for being that fast.
