### ISSUE TITLE
$transclude() results inconsistent between jqLite and jQuery

### ISSUE THREAD

**Issue by ktiedt** [angular/angular.js#11259]
As odd as the subject sounds it is appears to be the case. I do not have a plnkr that I could easily setup for this but it is fairly easy to describe clearly. Take a directive markup like this: (which has transclude:true) (the actual JS and template for my-table appear to be irrelevant to this case)
```
 <table my-table>
	<tr>
		<th>Column1</th>
		<th>Column2</th>
	</tr>
</table>
```

with jqLite `$transclude()` returns `[#text, tbody]` (where tbody is a `<tbody>` element that is now magically wrapping the `<tr>`)
with jQuery `$transclude()` returns `[tr]` (where tr is the `<tr>` from the markup as expected)

this causes discrepancies in things like `$transclude().find()` since with jqLite `.find("tr")` would work and in jQuery `.find("tr")` would fail since... `$("tr").find("tr")` is pretty obviously wrong

**Comment by lgalfaso** [comment]
Hi, thanks for reporting this. A plunker is always welcome, even if the issue is easy to reproduce. Without some extra context, it is not possible to know if this is a valid scenario, the reason being that all browsers add the `tbody` element anyhow, so there is a high chance that the content of `<table my-table>` starts with a `<tbody>`

**Comment by ktiedt** [comment]
I am digging into this further myself, I made a very basic plnkr, but it seems to work as expected, so I am looking for what else I am missing that may be different from my actuall use case, I can very easily reproduce it on our work project but... that isnt the easiest thing to share.

**Comment by Narretz** [comment]
Closing for lack of response. Feel free to reopen with more information.
