### ISSUE TITLE
Error URL broken

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular.js#11258]
https://docs.angularjs.org/error/$resource/badcfg?p0=array&p1=object has some issues on the rendered page.

**Comment by zhongsp** [comment]
This url is missing action param, it should like this: https://docs.angularjs.org/error/$resource/badcfg?p0=query&p1=array&p2=object , then
```
Error in resource configuration for action `query`. Expected response to contain an array but got an object
```

**Comment by ilanbiala** [comment]
@zhongsp I am aware of that, but that is the exact URL I got from the console.

**Comment by Narretz** [comment]
Can you provide a code repro that produces this error?

**Comment by ilanbiala** [comment]
@Narretz not sure what code I had since it changed, but it was with 1.3.14 I believe.

**Comment by Narretz** [comment]
@ilanbiala We need a runnable code example, e.g. a plnkr.co that repdrocudes the broken error url. Otherwise we cannot act on this.

**Comment by Narretz** [comment]
Closing due to lack of response. Feel free to reopen with more information.
