### ISSUE TITLE
Enable downloading Dart version from "Download" link

### ISSUE THREAD

**Issue by almstrand** [angular/angular.js#11260]
From the ng-conf talks it is clear that the Dart version of angular is going to be well supported moving forward, however when I click the download link on the angular.js webpage I am not presented with steps on how to download and use the Dart version (which steps would presumably include adding as line to the pubspec.yaml file.)

**Comment by pkozlowski-opensource** [comment]
@almstrand from now on https://angular.io/ will be the entry point to various Angular versions. If you go to the [download section](https://angular.io/download/) you will see a link to the Dart version. The https://angularjs.org/ website is still going to be dedicated to the JS version only.

@naomiblack is it about right?
