### ISSUE TITLE
ng-repeat doesn't trigger $destroy on specific element

### ISSUE THREAD

**Issue by zishanj** [angular/angular.js#11263]
I have created a directive and using inside ng-repeat. I am using remove button also to remove specific element from the list. The issue is, whenever I remove specific element from list, it always trigger $destroy in my directive on the last element in the list instead of specific element.

For example, I have 4 elements in the list like [1,2,3,4]. My directive displays 2 text boxes. I uses ng-repeat to iterate over list and display directive with 2 textboxes and remove button in every row. Now I clicked the remove button on 2nd row, but it triggers the $destroy on 4th row in my directive instead of 2nd.

**Comment by gkalpak** [comment]
It is (next to) impossible to diagnose the problem without more info.

That said, this is a support question and should be directed to the [appropriate channels][1].
GitHub is reserved for bug reports and feature requests.

--
<sub>If I had to take a guess, I would say you are using `track by $index`, which would explain the observed behaviour.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by zishanj** [comment]
Thanks for the reply... You are right that I was using track by $index and I have changed that and it works perfect. Any detail why track by $index is always removing the last row in list?

**Comment by lgalfaso** [comment]
If you are doing `track by $index` then this is working as intended.
