### ISSUE TITLE
Drop down list not displaying selected item till mouse Over in IE 10

### ISSUE THREAD

**Issue by hbiniwale** [angular/angular.js#11262]
AngularjS 1.2.10
IE 10

Hi All,

I am populating country list in drop down list/ select which gets populated with one country default selected.
in IE 10 the selected country is not displayed till user moves mouse over the drop down control.

**Comment by wesleycho** [comment]
This is not enough information to act on.  Can you give information about how the drop down list/select is set up?  A minimal reproduction on [Plunker](http://plnkr.co/) would be most helpful.

**Comment by Narretz** [comment]
@wesleycho is correct, there's not enough information. Feel free to reopen if you can provide more info.
