### ISSUE TITLE
[$http transformRequest] : data cannot be modified in transformRequest

### ISSUE THREAD

**Issue by Yappli** [angular/angular.js#11277]
Issue : http://jsfiddle.net/uqr74s7g/4/

transformRequest doesn't receive the data in case of a GET request (first parameter is always undefined).

For POST request, the same code works as expected. I tried with the branch 1.2.x, 1.3.x, 1.4.x

Maybe it's a "normal" behaviour but in this case I'd like to know why. The documentation never mention that.

Thanks

**Comment by Narretz** [comment]
When you create a resource action with the GET method, you don't get to set the request body, only the request parameters.
Sending a request body with a GET request, is kind of an edge case, as it is possible but not very useful in most cases - as far as I understand from this here Stackoverflow answer for example: http://stackoverflow.com/a/983458/787333

I assume we could add the possibility to add a request body to GEt requests, but it's probably not very useful.

**Comment by Yappli** [comment]
In my case it seams to be a GET that I need : I get

**Comment by Yappli** [comment]
Feedback : TansformRequest make sense to send an array through a GET query when the backend expect ```foo[]=1&foo[]=2``` instance of ```foo=1&foo=2```.

As @pkozlowski-opensource said <a href="https://github.com/angular/angular.js/issues/3740#issuecomment-35757676">here</a> : ```Adding [] (to the key name) is definitively and option, just a bit of pain when you've got your object ready.```

Releated to #3740

**Comment by pkozlowski-opensource** [comment]
@Yappli there is not much point in sending GET requests with body, see http://stackoverflow.com/a/983458, so the current `$resource` behavior is correct here.

On the other hand formatting request params with `[]` is not much easier after 6c8464ad14dd308349f632245c1a064c9aae242a landed.

Closing, as I don't think there us anything actionable here.
