### ISSUE TITLE
$animate's animation() addClass/removeClass callback

### ISSUE THREAD

**Issue by fxck** [angular/angular.js#11276]
So I'm animating stuff with `ng-class="{}"`, but I need some aditional tweeks possible only via javascript(temporaty setting parent's height to that of the element being animation), which I'm doing with `.animation()`, now after animating is done, I'd like to remove that height from the parent, but I can't really seem to find a proper way to do it. 

Unlike `enter`, `leave`, `move` it looks like it's not possible to return done function(https://docs.angularjs.org/guide/animations#how-they-work). I can't really use `$animate` DOM events, since `addClass` is only being called when ng-class adds classes.

So how should I go about this, other than using `$animate.addClass()`(so still utilizing ng-class)?

**Comment by wesleycho** [comment]
On the bottom of the example block for using `.animation()`, it shows an example of passing in the `done` function to the callback - does this not work?

**Comment by matsko** [comment]
Mind putting up a plnkr code example? There was a big refactor that was merged in and I'm trying to conceptualize how we can do this using the new code.

**Comment by fxck** [comment]
So I tried, using RC, but it's apparently working in a different way now.. 

See http://plnkr.co/edit/6bpRYcbu5myuArjv6DJa?p=preview

---

Anyway, here's kinda what I tried to do using beta6 http://plnkr.co/edit/XhVtS6FTvefx9eq2OU26?p=preview (click on the image to change items)

Here particularly I want the callback

```javascript
app.animation('.item', function() {
  return {
    addClass : function(element, className, done) {
      var parent = closest(element[0], '.wrap');
      parent.style.height = element[0].clientHeight + 'px';

      done();
      
      setTimeout(function() {
        parent.style.height = '';
      }, 200);
      
    }
  }
});
```

so instead of having to use `setTimeout` and stress about having to have the same delay in js and css, I'd just do something like 

```javascript
return function() {
  parent.style.height = '';
}
```

**Comment by fxck** [comment]
I see
![image](https://cloud.githubusercontent.com/assets/1303561/7101378/79c205b4-e057-11e4-8687-27436f526526.png)

**Comment by matsko** [comment]
Yes this has changed.

Just inject `$animateCss` and use that to drive the animation:

```js
app.animation('.item', function() {
  return {
    addClass : function(element, className, doneFn) {
      var node = element[0];
      var parent = closest(node, '.wrap');
      var animator = $animateCss(element, {
          to: { height: node.clientHeight + 'px' },
          from: { height: '0px' }
      });
      if (!animator) return doneFn();
      animator.start().done(function() {
         node.style.removeProperty('height');
         doneFn();
      });
    }
  }
});
```

**Comment by Narretz** [comment]
@fxck It looks like it's now possible to do what you want, so I'm gonna close this issue.
