### ISSUE TITLE
Offer to Google

### ISSUE THREAD

**Issue by kogarashisan** [angular/angular.js#11279]
Dear Google developers,
this offer may seem a bit bold for an unknown person,
but you know, that sometimes even one man can create impressive things.

I claim, that my own framework is in fact a better alternative to Angular and Ember.
So I offer Angular team to review it and reply if your company is interested in it.
http://www.lava-framework.com/

LiquidLava is new, still alpha, but already integrates a thousand of different requirements.
It may become basis for your own products, or save you great amount of human-hours.
I also perfectly understand what I'm offering and for whom.

If you have questions - feel free to ask.

Yours sincerely, Alex Galashov

**Comment by pkozlowski-opensource** [comment]
@kogarashisan this is not an appropriate place for such discussion - we want to keep GitHub issues for bug reports and feature requests. See https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

Thnx!
