### ISSUE TITLE
Minlength and Maxlength Validators Can Cause "undefined" to Appear in Input Field

### ISSUE THREAD

**Issue by bmbell** [angular/angular.js#11286]
I've tested the following with the minlength and maxlength validators.  I have yet to see if this issue occurs with other validators.  

Please take a look at the following jsfiddle:

http://jsfiddle.net/Fizzleban/tkocvkhv/

In this fiddle, I've set ng-minlength="3".  Now, try the following:

1.) Click on the input box and input a single character (such as "a")
2.) Click the "Change Model" button to update the model while it is in an invalid state
3.) Observe that the input field now displays "undefineda"

I would expect that I should be able to update the model in the controller and this would be reflected in the input correctly, even if it was currently in an error state.

**Comment by jbedard** [comment]
When an `ng-model` input value is invalid the model is set to `undefined`. The `changeModel` method is then appending "a" to that undefined value...

**Comment by bmbell** [comment]
I was attempting to simplify a more complex scenario, and thought that this fiddle nailed down the issue.  In my complex scenario, setting the model explicitly to "aa" rather than doing "+=" a is also producing the undefined as well, but this doesn't happen in the simpler case.  

So, it's probably something that I'm doing incorrectly in my specific scenario.  Thanks for pointing out my error in the fiddle.
