### ISSUE TITLE
Undebuggable message / Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by fipartners** [angular/angular.js#11288]
I have this Undebuggable message with no detail

    Uncaught TypeError: undefined is not a function

It comes from a function (`get`) that does not exist on $cookies (mixing v1.3.14 & 1.4.0)

Why don't i have an explicit message (object, line or module...) ?

**Comment by pkozlowski-opensource** [comment]
@fipartners I think that we don't have any info from browsers... A plunk / jsfiddle / jsbin would allow us to confirm. But yeh, based on the info provided, I'm not positive that we can do anything about it in Angular itself...

**Comment by fipartners** [comment]
In this jsfiddle, http://jsfiddle.net/scpwhweL/6/, i have the detail
     
     TypeError: undefined is not a function
        at new <anonymous> ((index):34)
 When running in local, I don't have the second line. Maybe a question of parameter ?

**Comment by pkozlowski-opensource** [comment]
@fipartners Could you please share a fiddle that actually shows the error? The one you've linked works OK and doesn't log anything in the console...

**Comment by fipartners** [comment]
http://jsfiddle.net/scpwhweL/11/

I have changed `$cookieStore.get('lastValue')`in `$cookieStore.getD('lastValue')`

**Comment by pkozlowski-opensource** [comment]
So, this is pure JS error reporting which has nothing to do with AngularJS. This is browser-dependent. In FFox, for example, you will get:

> "Error: $cookieStore.getD is not a function
@http://fiddle.jshell.net/scpwhweL/11/show/:34:22
e@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:36:313
Fe/this.$get</</<@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:75:449
A/<@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:58:476
s@https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:7:406
...

while Chrome is less explicit (this should improve soon...):

> TypeError: undefined is not a function
    at new <anonymous> ((index):34)
    at Object.e [as invoke] (angular.js:4185)
    at w.instance (angular.js:8454)
    ... 

Closing, as I really don't see what we could do on the Angular side - those errors are reported by the JS engine....
