### ISSUE TITLE
No $getPristine for form elements

### ISSUE THREAD

**Issue by prettycode** [angular/angular.js#11289]
Let's say I have a form with 10 fields. I have a "Save" button that submits the form. When I save though, I only want to submit fields with changed **values**. There is no facility to support this--to know whether a **value** has changed.

In other words, I can tell if a form **field** is `$dirty`, but I don't know whether that form field's **value** has changed. If the form **field** is `$dirty` but the **value** is pristine (what it was before it became `$dirty`), I don't want to include that form field when the form is submitted.

As a workaround, I have to copy all the original values of form fields into an object in my controller, and check whether the field value matches that original value copy in the controller.

There should be a `$getPristine()`. :)

**Comment by pkozlowski-opensource** [comment]
@prettycode why does `$pristine` property on https://docs.angularjs.org/api/ng/type/form.FormController doesn't do a trick for you?

**Comment by prettycode** [comment]
The form is not pristine, but the values haven't changed. In other words, a user enters the field, changes it, then reverts their change, then leaves the field. I have no way, using Angular, of knowing that the form value hasn't changed.

**Comment by pkozlowski-opensource** [comment]
OK, but in this case the only way of doing this would be to remember an initial value and systematically compare it with the current input value / model. This can by easily done in the user-land but I don't think AngularJS should be doing this by default as this would require increased memory usage and penalise users that don't need this functionality... 

IMO it should be "not in core", but let's hear what others got to say...

**Comment by prettycode** [comment]
That's what I'm saying--is I have to do this in userland, and I know multiple other devs. who have done the exact same thing because there is no `$getPristine()`. The scenario that I'm describing is very common and should be supported. Anyone who has used Angular to do a lot of form work has encountered this.

**Comment by kylecordes** [comment]
I am mostly in the "keep core small" camp, but I think there is a decent argument for this. ngForm has to know about the original data anyway, to implement its features - it would be polite of ngForm to expose this data.

**Comment by gkalpak** [comment]
I too don't think this should be a core feature.

First and foremost, having it work by default, would mean using (considerably?) more memory than required in apps that don't use this feature (which afaict is the majority out there).

Having this in core as an opt-in functionality, would avoid the above problem, but increase the code size (which we are looking to reduce instead); again for providing a feature to few people.

--
Also, note that:

1. This functionality can be easily implemented as an external module.
2. Although I've been also tempted to implement such a feature in the past, I have found out that (imo) it doesn't really add anything to the user experience.

Considering all the above, I don't think it belongs to core.

(<sub>Just m2c...</sub>)

**Comment by prettycode** [comment]
Why would this feature consume any more memory than `form.FormController` already does? The fact that `$rollbackViewValue()` exist shows that the original value is *already being stored*.

**Comment by gkalpak** [comment]
@prettycode: `$rollbackViewValue()` doesn't do what you probably think it does. It is meant to update the `$viewValue`, based on the latest `$modelValue` if you have a debounced update (using `ngModelOptions`) and you decide that you want to discard the latest change to the `$viewValue`.

Once the `$viewValue` is committed (i.e. propagated to the `$modelValue`), no reference to the previous `$modelValue` is kept (or at least it shouldn't).

Anyway, `$rollbackViewValue` is useful **only** when you are using debounced updates.

**Comment by prettycode** [comment]
You're right. I was mistaken about `$rollbackViewValue()`. I see that it restores to `$$lastCommittedViewValue` and not the original model state value.

The only reason I opened this issue is I've had three developers now come up to me and ask me how to get the pristine value, at two different companies.  It just struck me as odd that one of the first things a new Angular developer notices when using Angular for forms is that they don't have a `$$pristineValue` or such if they need it.

**Comment by GoNode5** [comment]
One  service/factory with angular.copy when start and save2scope (with compare function) and a general resource function is not that dramatic as you make it sounds? I have 30 forms that only need this little factory/service. You have an architectural problem I think.

**Comment by prettycode** [comment]
@GoNode5 I'm not sure I completely understand what you're saying. All I'm trying to do is document that I believe there's a missing feature in ngModel/ngForm, and that there is a legitimate case for this being in the framework itself. You apparently have come across this shortcoming too, after all. We're not the only ones, and I'm trying to bring attention to that.

**Comment by wesleycho** [comment]
I do not believe this should be in core either - this sounds like a specific user case and is not all that common that I have seen.  Core needs to be slimmer/simpler if anything.

**Comment by rpocklin** [comment]
I've implemented similar code as a **memento** pattern for forms (ie. cancel reverts to original state) - agree not the sort of thing core needs.

**Comment by jrharshath** [comment]
@rpocklin could you share your code/repo link here, that would be helpful. I went through the list of your repositories and couldn't locate it.

I agree with @prettycode that this is something devs repeatedly need when building apps, and I'm personally using code from this other repository [angular-input-modified](https://github.com/betsol/angular-input-modified). I'd love it if this was supported in angular natively.

I also think @gkalpak makes a valid point about how this would add additional overhead to all apps and that this should be an opt-in feature. The [angular-input-modified](https://github.com/betsol/angular-input-modified) repository makes that possible by allowing configuration options that lets the developer enable/disable this "reset form"/"reset input" behaviour globally, and enable it on individual forms using a `bs-modifiable` attribute.

@pkozlowski-opensource I urge you to revisit this problem. Save/Cancel is a regularly used pattern everywhere. Most developers rely on maintaining copies of their models and using them to reset forms when needed. I urge you to look at the [angular-input-modified repository](https://github.com/betsol/angular-input-modified) that I mentioned earlier and check out its approach - it's hardly 300 lines. 

It would be amazing if this was a part of angular's core. It would solve a repeatedly occurring developer problem, and would make it easy to implement a repeatedly used form pattern.

**Comment by jrharshath** [comment]
@prettycode Would you agree that this issue would be better named "No $resetInput() and $resetForm() in ngModelController and ngFormController"?

**Comment by rpocklin** [comment]
@jrharshath I didn't get to open-sourcing it, thought I could :P  If you're implementing consistent form actions like `reset` across your app something like this makes sense.  Give me a couple of weeks ...

**Comment by jrharshath** [comment]
@prettycode @rpocklin I found that the angular-input-modified project provides a `reset()` method on `ngForm`. Perfect for this exact use case.

**Comment by Narretz** [comment]
Closing. Not going to happen in AngularJS Core.
