### ISSUE TITLE
AngularJS select with lot of options - slow rendering

### ISSUE THREAD

**Issue by johntechie1985** [angular/angular.js#11282]
Hi,

I started exploring AngularJS but wasn't really happy with the time Angular takes to render a select element with huge number of options.

http://plnkr.co/edit/lCeqaG91PeHjltT9AhBq?p=preview

The plunker above demonstrates a simple select element with 2000 options takes about a second to render.

On adding two more select elements, the screen rendering time got tripled.

Any help in reducing the screen rendering time is appreciated.

Thanks.

**Comment by RobiFerentz** [comment]
Takes about 0.6 seconds on my mac pro.  
Have you tried one time binding on it? Seems to help a bit on the plunker, but not by much.:disappointed:

**Comment by gkalpak** [comment]
FWIW, it seems to be 3.5x faster with 1.4.0-beta.5 (probably due to `ngOptions` refactoring).

**Comment by lgalfaso** [comment]
It is very fast on my machine, and comparable with a JS version that populates a <select> without Angular.
