### ISSUE TITLE
scope not updating in navbar after user login?

### ISSUE THREAD

**Issue by satyanani40** [angular/angular.js#11296]
I am implemented nav bar using directives
in index page i just used 

               '<div navbar></div>'

navbar directive is show bellow.
 
'use strict';

/**
 * @ngdoc function
 * @name weberApp.controller:NavbarCtrl
 * @description
 * # NavbarCtrl
 * Controller of the weberApp
 */
angular.module('weberApp')
.directive('navbar', function () {
    return {
        restrict: 'A', //This menas that it will be used as an attribute and NOT as an element. I don't like creating custom HTML elements
        replace: true,
        scope:true,
        templateUrl: "/static/app/views/navbar.html",
        controller: "navbarcontroller"
  }
})
    .controller('navbarcontroller',function($scope, $auth, CurrentUser) {
               $http.get('/api/me', {
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': $auth.getToken()
                    }
                }).success(function(user_id) {
                    Restangular.one('people',JSON.parse(user_id)).get({seed: Math.random()})
                    .then(function(user) {
                         $scope.currentuser = user;
                    });

                });

in navbar html page $scope not updating. while refresh after login it was updating correctly.

**Comment by Narretz** [comment]
Hi, please use these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem Thanks!
