### ISSUE TITLE
Number format without group separator

### ISSUE THREAD

**Issue by ssamsundar** [angular/angular.js#11295]
Hi,

I'm new to anuglar.js. I like to know, how to specify a number without group separation format.

For e.g:
12345678.01234

If I specify particular {{ var1 | number }} , comes with comma(,) separation for en and  dot(.) separation for es locale. 

Please help me out!!

**Comment by gkalpak** [comment]
This is a support question and should be directed to the [appropriate channels][1].
GitHub is reserved for bug reports and feature requests.

--
<sub>That said, there isn't any filter/option for removing the group separator. You could either define your own filter, expose a function on the scope or formatting the value in the controller (before displaying).</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
