### ISSUE TITLE
Fields that are touched but do not change in value are not validated and set touched later

### ISSUE THREAD

**Issue by pjwalmsley** [angular/angular.js#11299]
Here is the senerio; If i were to set required on a field, click into, then click to another field it would not validate.  

Typically this is not an issue, but with certain libraries rely on the dirty flag set when a model changes.  When nothing changes this flag is not set.

I see a few ways of addressing this.  

The first would be to set touched in the commitViewValue function rather then just returning tif rthe value has not changed.  This seems logical.  Nothing has changed thus nothing needs to be validated, but the field has been touched.  Is there a function that calls this that would be a better place to set touched.  Where is touched set currently?  Perhaps it would be possible somehow to delay the validation until touched has been set.
https://github.com/angular/angular.js/blob/master/src/ng/directive/ngModel.js#L645

The other would be to provide an option in ng-model-options to always fire validations even if values have not changed.  I assume this would be a performance hit. 

To read more about our particular situation, see the link below. Thanks! :)

https://github.com/jonsamwell/angular-auto-validate/issues/44

**Comment by Narretz** [comment]
So basically you want angular to run the validation even if the input has been ' touched', but not 'dirtied'?

**Comment by pjwalmsley** [comment]
Yes, or more ideally to set touched when it evaluates if validation is needed because it does indeed know that it has been touched.

**Comment by Narretz** [comment]
`touched` is only ever set when the element is `blurred`. The validation should not set `touched`, this doesn't sound right.

**Comment by Narretz** [comment]
It sounds more like you want some sort of $focused state on the input (see https://github.com/angular/angular.js/issues/12447). The validation is currently coupled to input changes, so if you don't enter anything, nothing happens. You can of course add you own directive that validates the input on focus / blur. Overall, I don't see any clear change we could make from you info.
