### ISSUE TITLE
Add packaging for Meteor.js

### ISSUE THREAD

**Issue by Urigo** [angular/angular.js#11291]
Hi!

As you maybe know, it is now possible to use AngularJS and Meteor together with the help of the [angular-meteor](https://github.com/Urigo/angular-meteor) package.

The package does a few things to make that possible and is dependent on an [Angular package](https://atmospherejs.com/angularjs/angular) - a separate package that just holds all the AngularJS releases.
But right now we do it manually, which is hard for each of the releases ([angular-animate](https://atmospherejs.com/angularjs/angular-animate), [angular-sanitize](https://atmospherejs.com/angularjs/angular-sanitize) etc...)

There is an effort right now to pull request popular libraries to support the Meteor release as part of their release process.
Top examples of popular libraries that already doing that are:
- d3
- Bootstrap
- moment

and even AngularUI's google maps directive...

I would create this issue as a pull request but it looks like your release process is much more complex than the others.
The only thing that needs to be done is to add one file named package.js and I would love to help you do that anytime that is suitable for you.

Thank you so much for building such a great framework,
Urigo

**Comment by Narretz** [comment]
To clarify, this is a additional packaging per angular "module" - core, animate, route etc. - that includes the whole release history, right?
If so, couldn't this package use bower / npm / github releases?

**Comment by Urigo** [comment]
@Narretz yes it can and until recently we did just that.

The reason for adding Meteor Packaging is that Npm and Bower doesn't really have a good version solver like Rails bundler or Scala, and Meteor does have that support.
That's a big difference for Angular developers working on Meteor, it makes their development process much more streamlined and simpler than falling back to Npm or Bower (what we did until recently).

Maybe in the future Npm will use something similar (if they want to support FrontEnd dependencies in a good way) or even use Meteor's solver, but unfortunately right now they not.

For more information I would really recommend @dgreensp 's talk about the constraint solver, especially the Npm part - https://youtu.be/IWSaZfSVnFM?t=5m58s

**Comment by Urigo** [comment]
@Narretz also, there is no need to publish all history, we already published that (including versions 2.0.0-alpha.x)
Also we moved to the 'angular' namespace instead of 'angularjs' so it will better fit the official angular releases

**Comment by DmitryEfimenko** [comment]
+1.
I'd really love to develop against [latest `angular-material`](https://material.angularjs.org/latest/) (which is right now 1.0.0-RC7).
However, the [latest `angular-material` package available on atmosphere](https://atmospherejs.com/angular/angular-material) is currently 0.11.4

**Comment by Narretz** [comment]
This never really got traction, and at this point in the AngularJS lifecycle it's probably not worth the effort to include this in the build.

**Comment by Urigo** [comment]
@Narretz thanks, I guess the main reason it didn't got traction is that Meteor supports `npm` completely for the past year or so, so if anyone end up into this PR, know that the only thing you need to do in order to install angular is just to get it from `npm`. :)
