### ISSUE TITLE
Unpublish all 1.3.36 npm packages

### ISSUE THREAD

**Issue by bendrucker** [angular/angular.js#11309]
It's not enough to `npm deprecate` all the 1.3.36 packages that were published. `npm outdated`, which powers `npm update`, looks for the latest version matching what your package.json asks for. Given `angular@1.3.14` installed, `npm update` will result in `angular@1.3.36`.

In order to behave correctly, `npm unpublish angular@1.3.36` should be run, along with all the other npm packages.

**Comment by petebacondarwin** [comment]
I fink I did done dis

**Comment by bendrucker** [comment]
:smile: :+1: !

**Comment by btford** [comment]
:+1:

**Comment by keirlawson** [comment]
1.3.36 is currently being installed by npm for me when I depend upon ~1.3.17

**Comment by mzgol** [comment]
@keirlawson Which npm & Node version? Could you try to clear the npm cache (`npm cache clean`), remove `node_modules` & try again?

This version is unpublished now, it's physically not in the registry so it shouldn't be possible to install unless you have it cached.

**Comment by keirlawson** [comment]
Ah my bad, it was cached in our private npm repo
