### ISSUE TITLE
ngAria : aria-checked attribute for components with role=checkbox 

### ISSUE THREAD

**Issue by RaphStein** [angular/angular.js#11317]
Hello,
It seem's that the last version of ngAria (1.3.14 and 1.4.0beta5 ) has a regression for components with role=checkbox.
Even if the component is not checked the value of aria-check is always set to true.
I used the plunker from the Angular Accessibility Developper guide to test it.
In the plunker when I set the version of ngAria to 1.4.0beta4 it works.

**Comment by Narretz** [comment]
Okay, I'm pretty sure I broke this when I fixed some edge cases for normal checkboxes and radios.

**Comment by RaphStein** [comment]
Hi, component with role=menuitemcheckbox has also the same regression (Even if the component is not checked the value of aria-check is always set to true).
