### ISSUE TITLE
Angular Loses Binding in IE When Using Keyboard to Make a Selection

### ISSUE THREAD

**Issue by usefulBee** [angular/angular.js#11316]
If we attempt to select a state by Keyboard in Internet Explorer, both $scope.selectedStateName and  $scope.selectedStateCode binding are lost, or often they bind but lose binding in a split of a second.

Demo: http://codepen.io/anon/pen/azROdJ

**Comment by lgalfaso** [comment]
This is not a support forum. Now, there is a very high chance that IE is not generating an event for this. Did you try with https://github.com/tbosch/autofill-event ??
