### ISSUE TITLE
Setting model to NaN causes infdig if $asyncValidators is used

### ISSUE THREAD

**Issue by tepez** [angular/angular.js#11315]
An infinite digest error is thrown when a model is set to `NaN` and there is an asynchronous validator. 

Please check plunker at http://plnkr.co/edit/u9Sq12?p=preview.
When we set `model` to a string or to null - everything works as expected.
When we set `model` to `NaN` there is an infdig error:

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.14/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:63
    at Scope.$digest (angular.js:14281)
    at Scope.$apply (angular.js:14506)
    at HTMLButtonElement.<anonymous> (angular.js:21443)
    at HTMLButtonElement.eventHandler (angular.js:3014)
angular.js:63 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.14/$rootScope/infdig?p0=10&p1=%5B%5D
```

This happens because [`ngModelWatch`](https://github.com/angular/angular.js/blob/59205d7809630fb061c849171aad9c6b2a22f09a/src/ng/directive/ngModel.js#L813) checks that `modelValue !== ctrl.$modelValue`, which is true for `NaN`.

Thus, when we set the model to `NaN`, `$$runValidators` is called in every digest cycle. If we have an async validator, it causes a push to `asyncQueue` and so another cycle is needed.

`ngModelWatch` returns `modelValue`, which is `NaN` so the watch is not considered dirty because [`$digest()`](https://github.com/angular/angular.js/blob/59205d7809630fb061c849171aad9c6b2a22f09a/src/ng/rootScope.js#L766) treats `NaN` as equal to `NaN`.

I think a good solution would be to treat `NaN` as equal to `NaN` in `ngModelWatch`
Edit: 
Check http://plnkr.co/edit/aZZmyP?p=preview
`ngModelWatch` is changed to
```
if (modelValue !== ctrl.$modelValue &&
      !(typeof modelValue === 'number' && typeof ctrl.$modelValue === 'number' && isNaN(modelValue) && isNaN(ctrl.$modelValue))) {
      ctrl.$modelValue = ctrl.$$rawModelValue = modelValue;
```
and this indeed solved the infdig

**Comment by zhongsp** [comment]
In [ngModelWatch](https://github.com/angular/angular.js/blob/59205d7809630fb061c849171aad9c6b2a22f09a/src/ng/directive/ngModel.js#L813) , we could update to `modelValue` and `ctrl.$modelValue` are not equal, and any of both is not `NaN`.
```js
    // if (modelValue !== ctrl.$modelValue)
    if (modelValue !== ctrl.$modelValue && 
        (modelValue === modelValue || ctrl.$modelValue === ctrl.$modelValue)) {
```

**Comment by wesleycho** [comment]
It would be better to do
<pre>
if (equals(modelValue, ctrl.$modelValue)) {
...
}
</pre>
I think - `angular.equals` already has a check for NaN, so it would screen out this case and do a more proper check.

**Comment by gkalpak** [comment]
I don't think using the (potentially expensive) `equals` in a rathr critical path is a good idea.

**Comment by Narretz** [comment]
I opened #11411 for your consideration. `equals` is too expensive, but @zhongsp solution works.
