### ISSUE TITLE
AngularJs validation directive with pattern & boolean returned

### ISSUE THREAD

**Issue by benavern** [angular/angular.js#11313]
# Hello, 
*I would like to do something with input validation.*

I have a page with a lot of scope variables and for exemple I have an input that has a `ng-pattern` plus a condition (`isValid`) to verify (always has to return a boolean)

I made a jsBon so that you'll understand me better: http://jsbin.com/qugomugelo/4/

my issue is that when the pattern is verified, the value is defined and undefined when not verified, but for my directive the behaviour is not the same : it's always defined (condition verified or not)

I would like to have the same behaviour than the ng-pattern and to make them work together (not adding a ngPattern condition in the directive...)

I'll probably have to change something there:

```javascript
    if(isValid === true){
        //set valid true
         ngModel.$setValidity(attr.id, true);
    }
    else{
        //set valid false
        ngModel.$setValidity(attr.id, false);
    }

```
Is that possible ? how can I achieve that ? (I'm working without form is that a big problem ?)

*Thank you in advance!*

**Comment by lgalfaso** [comment]
Hi, this is not a support forum, so please as this at SO. BTW, look an ngModelOptions.
