### ISSUE TITLE
select ng-model not binding correctly when using ng-if

### ISSUE THREAD

**Issue by evanwong** [angular/angular.js#11323]
While I was trying to bind the model to the select dropdown using ng-model and ng-options, the model wasn't binding correctly if I was also using ng-if at the same time.

In the jsfiddle example, if you change the dropdown to test2, the popup is still showing test1 if the ng-if="true" is present. Once you remove the ng-if, the popup will be correctly showing test2 as expected.

jsfiddle link:
http://jsfiddle.net/qn321tpz/

Without ng-if:
![screen shot 2015-03-13 at 5 10 00 pm](https://cloud.githubusercontent.com/assets/1258612/6647353/cdfab2f4-c9a3-11e4-8aef-0630b99531d1.png)

With ng-if
![screen shot 2015-03-13 at 5 09 36 pm](https://cloud.githubusercontent.com/assets/1258612/6647354/cdfac294-c9a3-11e4-923b-5ff48960953b.png)

**Comment by pkozlowski-opensource** [comment]
This is a scoping issue in your template, please check https://github.com/angular/angular.js/wiki/Understanding-Scopes for more info.
