### ISSUE TITLE
$locale service should expose info about locale

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular.js#11325]
The `$locale` service seems to keep track of some nice stuff like the locale id, currency, and date format. It would be nice if those values were exposed in a public API so I could find out very easily what the currency code is for each user and do things like that.

**Comment by petebacondarwin** [comment]
It is available via the $locale service:

Default locale: http://plnkr.co/edit/emuqiC3MfgPKrMmDgwum?p=preview
ar-ma locale: http://plnkr.co/edit/Yqr79YAxJJoNSw8U44Da?p=preview

**Comment by ilanbiala** [comment]
Then shouldn't the docs be updated?

**Comment by petebacondarwin** [comment]
Each locale is free to provide whatever information it likes. We don't really have control over that.
The only thing we specify is the `id`. See https://docs.angularjs.org/api/ng/service/$locale

**Comment by ilanbiala** [comment]
@petebacondarwin maybe I'm confused, but how do locales work exactly? Each locale is a separate angular file, right? Shouldn't each locale expose at least the id, currency symbol and abbreviation, and locale?

**Comment by petebacondarwin** [comment]
Each locale exists in its own file. These files are generated, with very little human intervention from the Google Closure Library i18n files.

At a minimum they must expose an `id`. In general they expose a load of other stuff such as number and date information. But Angular does not guarantee that this is the case.

If you look through the locale files you will see they all contain the same general information. If you would like to check that they all contain certain properties and that future regeneration of these files would also contain these properties then I would be happy to merge a PR that updated our documentation.

**Comment by ilanbiala** [comment]
Thanks for the info!
