### ISSUE TITLE
Subarray filter dosn't work after 1.3.1 

### ISSUE THREAD

**Issue by bkhurram** [angular/angular.js#11332]
Hii,
After angular 1.3.1 my sub array filter don't work.
Example. http://plnkr.co/edit/XjGyppLgiR0mxqt4JShk?p=preview
When you change <b>FROM</b>
https://code.angularjs.org/1.3.1/angular.js 
<b>TO</b>
https://code.angularjs.org/1.3.10/angular.js
Stop to work.

how can i resolve it?

Thanks
Khurram

**Comment by Narretz** [comment]
With which version have you tested this? Have you checked 1.3.14? Have you tested the latest 1.3.x snapshot?

**Comment by bkhurram** [comment]
yes, i have test with 1.3.14, 1.3.9 and 1.4.0-beta.5 but not work.

**Comment by Narretz** [comment]
@gkalpak Mind taking a look?

**Comment by ozsay** [comment]
Hi, 
After a quick research, found out that a breaking change was introduced in [1.3.6](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-6).
The way `filterFilter` is treating deep object filtering was changed.

**Comment by Narretz** [comment]
Thx @ozsay for taking a look at this. We unfortunately introduced a breaking change in 1.3.6.

You can use `<input ng-model="filtervalue.Factors.$"/> so that the filter tries to match on every property of every factors item, to any depth.

**Comment by bkhurram** [comment]
Thank you very much
