### ISSUE TITLE
$templateRequestProvider <- $templateRequest <- $route <- ngViewDirective

### ISSUE THREAD

**Issue by wangxuq** [angular/angular.js#11335]
how to resolve the problem:
 <pre>Error: [$injector:unpr] Unknown provider: $templateRequestProvider <- $templateRequest <- $route <- ngViewDirective
http://errors.angularjs.org/1.2.25/$injector/unpr?p0=%24templateRequestProvider%20%3C-%20%24templateRequest%20%3C-%20%24route%20%3C-%20ngViewDirective
    at VALIDITY_STATE_PROPERTY (angular.js:78)
    at angular.js:3802
    at Object.getService [as get] (angular.js:3930)
    at angular.js:3807
    at getService (angular.js:3930)
    at Object.invoke (angular.js:3957)
    at angular.js:3808
    at getService (angular.js:3930)
    at Object.invoke (angular.js:3957)
  </pre>

**Comment by Narretz** [comment]
$templateRequest is not in 1.2.x. I'm pretty sure you are using ngRoute 1.3.x together with angular core 1.2.x

**Comment by Narretz** [comment]
(they are not compatible)

**Comment by wangxuq** [comment]
yes,they are not compatible,and I have replace the angular version to fit the ngRoute.
