### ISSUE TITLE
Status of declarative plurals in 1.4 beta?

### ISSUE THREAD

**Issue by brycecr** [angular/angular.js#11338]
Does 1.4.0-beta.5 have support for declarative plurals? The talk at ng-conf seemed to suggest that 1.4 might already have support for writing this syntax, but I keep getting lexer errors on the following:

```
<span>
   <!--i18n: Plural Fun-->
   {{model.numMessages, plural,
         =0 { You have no new messages }
         =1 { You have one new message }
      other { You have # new messages }}}
   <!--/i18n-->
</span>
```

I was curious if this is because declarative plural support isn't in any angular release yet (including beta), or because I was doing something wrong.

Thanks!

**Comment by brycecr** [comment]
I see #11152 now, which, if I understand correctly, indicates that this support is yet to be merged into beta, but it would be great to get a read on when i can start playing with this.

**Comment by chirayuk** [comment]
That PR should get merged in sometime soon.  Definitely this week.  Feel free to patch the PR in—there's not many significant changes that are expected to be made to it.

**Comment by brycecr** [comment]
Thanks, Chirayu!
