### ISSUE TITLE
xhr.response used instead of xhr.responseText for IE9

### ISSUE THREAD

**Issue by sharanmunyal** [angular/angular.js#11339]
I see a bug over here https://github.com/angular/angular.js/blob/v1.3.14/src/ng/httpBackend.js#L63. 

I am facing an issue in IE9 where xhr.response is empty for me in IE9 and xhr.responseText happens to have the expected response. Also I see a note mentioned just above that line 

```
// responseText is the old-school way of retrieving response (supported by IE8 & 9). 
```

According to me that line should be 

```
var response = ('response' in xhr && msie !== 9 ) ? xhr.response : xhr.responseText; //considering angular-1.3.x doesn't support IE8
```
Let me know if I am missing something here.

**Comment by lgalfaso** [comment]
Hi, a little more context would help here. The reason is that IE9 xhr does
not have the property 'response'
>
>

**Comment by sharanmunyal** [comment]
Yes even I expect the xhr object not to have the response field. However in my case I see an array of random numbers in the xhr.response something like

xhr.response = [123,34,95,95,116,131,112,101];

Hence wondering if I am missing something.

**Comment by petebacondarwin** [comment]
It would be helpful if you could provide more information about how the response is being created, since IE9 does not normally contain this property.

**Comment by pkozlowski-opensource** [comment]
@sharanmunyal we haven't heard from you and it is hard to progress on this one without clear reproduce scenario :-( I'm going to close this one for now, but will be more than happy to re-open if you've got a minimal, live reproduce scenario.
