### ISSUE TITLE
Proposed feature: inject required parent/sibling directive controllers as locals

### ISSUE THREAD

**Issue by jamestalmage** [angular/angular.js#11337]
See [this commit](https://github.com/jamestalmage/angular.js/commit/326df0468d857c208cd58de2a09387a05138f221) for a better idea where I am headed.

The basic idea would be to allow the following syntax:

```javascript
app.directive('child', function() {
return {
  require: 'parent',
  controller: function(parentController) {
   // parentController is automatically injected
  }
}
```

This feels more straightforward than a separate linking function that sets the parent controller on the child.

**Comment by jamestalmage** [comment]
pinging @caitp since I think this is his domain.

**Comment by caitp** [comment]
Her domain, but I'm not sure if we want to do this. For something like this, I'd suggest sending an intent to implement email to the angular Google group, and get some discussion happening first

**Comment by jamestalmage** [comment]
Will do, and apologies.

closing in favor of Google group discussion.
