### ISSUE TITLE
bindToController does not bind correctly for multiple directives

### ISSUE THREAD

**Issue by jtorbicki** [angular/angular.js#11343]
The problem occurs when defining multiple directives on the same element. All of the directives use bindToController as an object and scope: true. Only the first directive's controller gets scope bound.

Here is a fiddle showing the bug: https://jsfiddle.net/rds5muzk/

Current console output:
```
first = 2
second = undefined
```

Expected console output:
```
first = 2
second = 4
```

**Comment by JWGmeligMeyling** [comment]
Can confirm this issue.

**Comment by majello** [comment]
can confirm this issue too. this seems only to refer to bindToController, no dependency on other factors as far as i can tell.
