### ISSUE TITLE
"track by" for ng-repeat over an object's properties does not work

### ISSUE THREAD

**Issue by tsclaus** [angular/angular.js#11348]
There currently seems to be no way to ng-repeat over an object's properties if the object is created anew in the ng-repeat expression.

    <button ng-click="console.log(key)" ng-repeat="(key, value) in localStorage.getItem('ls.accountKeys') track by value">

throws:

    Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: (key, value) in localStorage.getItem('ls.accountKeys') track by value, Duplicate key: o, Duplicate value: "o"

Removing the "track by" part of the expression causes the digest limit to be reached with every cycle, as a new object is returned by localStorage every time.

**Comment by andrewaustin** [comment]
localStorage is a key value store, so you must serialize your objects with ```JSON.stringify()``` first before storing them. Here is an example: https://jsfiddle.net/aqvrx9q9/

In case localStorage is just an example here, here is another simple example that illustrates things seem to be working as intended: https://jsfiddle.net/c298m629/

If this is not what you were asking, can you please provide an executable example?

**Comment by tsclaus** [comment]
My object stored in localStorage (which is indeed an example, in my code I transformed the string into an object) is an array-like object containing objects, with each child object containing only literals. It can be found here: http://codebeautify.org/jsonviewer/daf62c. 

I have not tested making a scope variable an object reference that never changes and then overwriting it's values with the object stored in local storage; I believe that will work, but it seems very un-angular.

I will be able to post the code tomorrow.

**Comment by lgalfaso** [comment]
Hi, `track by` must point to an expression that uniquely identifies an element in the collection. Are you sure that you did not intend to write `track by key` ?

**Comment by Narretz** [comment]
Closing because of lack of response.
