### ISSUE TITLE
ngTouch doesn't work

### ISSUE THREAD

**Issue by mato75** [angular/angular.js#11358]
When clicking on input and using ngTouch to remove the 300ms delay, it doesn't open up a keyboard. 

What happens:
- touchstart event gets triggered and there is no touchend/click event after that, because touchcancel and touchmove are called and they reset the state.  
- keyboard only opens up on click event

v1.3.15 - angularjs

**Comment by kidqn** [comment]
Do you have any examples to explain how you use ngTouch to remove 300ms delay?

**Comment by pocesar** [comment]
happens to all unfocused inputs, on Android it's even worse, need to touch the input many times before it's focused

**Comment by steven10172** [comment]
Here is an example of the issue. mbenford/ngTagsInput#512

Here is an example: http://embed.plnkr.co/edBdpUbM4UWI6a5Pdr7d/preview

**Comment by steven10172** [comment]
Not sure if I have the best solution, but it seems to fix the issues present in the example above.

Example using code from pull request:  http://embed.plnkr.co/4e0owINFEsWFNOap1SSs/preview
