### ISSUE TITLE
$scope.$on("$destroy") when $scope is destroyed by $location.path() assignment [firefox]

### ISSUE THREAD

**Issue by birdcw** [angular/angular.js#11362]
When I added a ```$scope.$on("$destroy")``` function, Firefox unexpectedly started changing my view to the ```$routeProvider.otherwise``` following a ```$location.path()``` assignment.

The problem was fixed when I repeated the same ```$location.path()``` assignment at the end of my ```$scope.$on("$destroy")``` function. I haven't seen this behavior in other browsers.

**Comment by bruunofco** [comment]
Please have any examples of your code in Plunker or similar?

**Comment by havenchyk** [comment]
@birdcw could you please create sample app to show this error on jsbin or plnkr.co?

**Comment by lgalfaso** [comment]
No feedback in several months, no way to reproduce the error and not enough information to know what the error is. Closing, but if there is more information to be able to diagnose this issue, feel free to reopen.
