### ISSUE TITLE
Derogatory language in comments

### ISSUE THREAD

**Issue by RomanS886** [angular/angular.js#11364]
Please remove derogatory language from the comments of jsonpReq function 

![function](https://cloud.githubusercontent.com/assets/11544062/6717047/0e710e48-cd80-11e4-8f52-544d5498210d.jpg)

**Comment by andrewaustin** [comment]
I suggest using angular.min.js which doesn't have this issue. See https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js
