### ISSUE TITLE
Data binding breaks for checkboxes nested in anchor tags

### ISSUE THREAD

**Issue by garkbit** [angular/angular.js#11366]
In situations like this:
```html
<a>
  <input type="checkbox" ng-model="checked" />
</a>
```
data binding seems to break. Upon clicking the checkbox, the model is updated, but the onscreen checkbox remains unchanged, then subsequent clicks no longer update the model. This would appear to be an interaction between the anchor and checkbox, as it can be worked around by either removing the anchor tag:
```html
<span> <!-- or just remove entirely -->
  <input type="checkbox" ng-model="checked" />
</span>
```
Or by calling stopPropagation() on the input:
```html
<a>
  <input type="checkbox" ng-model="checked" ng-click="$event.stopPropagation()" />
</a>
```
A jsfiddle demonstrating the behavior: https://jsfiddle.net/fvdurx56/1/

------------------

All that said, wrapping inputs in anchor tags is at best inadvisable, so unless this proves to be a more general problem, it may not warrant further effort.

**Comment by andrewaustin** [comment]
The reason for this is the ```htmlAnchorDirective```.

It has this bit of code:
```
element.on('click', function(event){
        // if we have no href url, then don't navigate anywhere.
        if (!element.attr('href')) {
          event.preventDefault();
        }
      });
```

If you add an ```href``` element, things magically work. See https://jsfiddle.net/64kw1x5d/

I'm not sure if it's worth fixing.

**Comment by Narretz** [comment]
This is invalid HTML, see https://github.com/angular/angular.js/issues/12917#issuecomment-142323240
