### ISSUE TITLE
check if a custom service function has been called in $asyncValidators

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular.js#11368]
Hi, 
I am pretty new to AngularJS and I have a question to ask, if anyone could help me through this one.
I made a custom directive to check whether a user name is unique and I used the $asyncValidators to perform an asynchronous validation
eg:  
control.$asyncValidators.uniqueName = function() { 
      User.checkUniqueName()
};

But in my test, I spyOn the checkUniqueName function, but
expect(User.checkUniqueName).toHaveBeenCalled()
would always to throw an error.

How could I do this test?

**Comment by Narretz** [comment]
Hi, please use these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem Thanks!
