### ISSUE TITLE
ngSubmit does not validate model before submit when using custom update triggers

### ISSUE THREAD

**Issue by sajal** [angular/angular.js#11360]
When using `ngModelOptions` to update only on blur, submitting the form without loosing focus does not take freshly validated data into account.

I am updating on blur because i dont want to annoy user while they type, also my intention is to use http for validation and don't want to fire too many ajax calls.

example: http://jsfiddle.net/ms5uxw12/1/

reproduce:
1. Select the textbox, enter valid data (lowercase alpha only minimum 3 characters).
2. Without loosing focus, click submit

alternatively:
1. Fill numbers in textbox
2. Leave focus, you should see error message.
3. Replace numbers with alpha, click submit without leaving focus of textbox.

The `$scope.something.$valid` test does not pass because the form gets submitted before the models gets re-validated.

https://docs.angularjs.org/api/ng/directive/ngModelOptions - "Any pending changes will take place immediately when an enclosing form is submitted via the submit event. Note that ngClick events will occur before the model is updated. Use ngSubmit to have access to the updated model."

**Comment by vitaly-t** [comment]
+ 1

We are using x-editable library, and have to keep counter for focus and blur events to see when it is ok to enable the submit button, because otherwise you make a change and hit Enter or submit button, and the model fails to apply the current value in the edit box.

**Comment by Narretz** [comment]
So the actual bug is that ngSubmit only sets the model, but does not call validate if custom update triggers are set, is that correct?

**Comment by sajal** [comment]
hmm... my bad

It appears like this is a ui glitch. When I try to click the submit, it unbinds the input as needed, the validation error pushes the submit button lower leaving it unclicked.

http://jsfiddle.net/ms5uxw12/2/

Ive moved the submit button so it doesnt bounce around, then it works fine.

Is there some way to make the original click go thru even if the button moves?

-Sajal

**Comment by Narretz** [comment]
Oh, I see. That's unfortunate. I don't see that angular can handle this automatically.
I had a similar problem, where I solved this by additionally listening to `mousedown` on the button (which is called before blur) and triggering whatever I need after a 0ms second timeout.

**Comment by awerlang** [comment]
A "click" is a mousedown (A) followed by a mouseup (B) on the same element. Only (A) occurs. I believe is out of scope of angular try to be cleverer on this thing.

From the UX point of view, I'd recommend avoiding a design where an element moves like this. From the second fiddle, remove the <br> between input and button and it would look better.
