### ISSUE TITLE
$location can't find the query parameter if the parameter is before '#'

### ISSUE THREAD

**Issue by zsong** [angular/angular.js#11377]
If the URL is in this format, $location.search().code will return nothing

    http://localhost/app?code=abcde#/myview/

**Comment by wesleycho** [comment]
I don't think this is a bug - anything before the # is part of the base url of the application, which Angular does not touch or handle.  Angular ignores it as far as its concerned.  You should grab the information you need directly from `window.location` in this case.

**Comment by RyuuChan** [comment]
i dont understand what you said 


     Pada Minggu, 22 Maret 2015 0:54, Wesley Cho <notifications@github.com> menulis:
   

 I don't think this is a bug - anything before the # is part of the base url of the application, which Angular does not touch or handle. Angular ignores it as far as its concerned. You should grab the information you need directly from window.location in this case.—

**Comment by Heddy147** [comment]
@wesleycho I don't agree.
`// given url http://example.com/#/some/path?foo=bar&baz=xoxo
var searchObject = $location.search();
// => {foo: 'bar', baz: 'xoxo'}`

is a good example ;)

**Comment by gkalpak** [comment]
@Heddy147: What @wesleycho said, is that (supposing you are in [hashbang mode][1]), everything before the hashbang symbol is **not** considered part of what `$location` sees as URL. E.g.:

```js
// http://example.com?param=value#/some/path
$location.search() ---> {}

// http://example.com#/some/path?param=value
$location.search() ---> {param: 'value'}
```

[1]: https://docs.angularjs.org/guide/$location#hashbang-mode-default-mode-

**Comment by pkozlowski-opensource** [comment]
@gkalpak and @wesleycho are right here (as usual!). Closing as things work as expected.
