### ISSUE TITLE
i18n: Translation of dynamic data?

### ISSUE THREAD

**Issue by brycecr** [angular/angular.js#11375]
Apologies if I just haven't read the docs in enough detail, but I did not see a clear answer for this: how is dynamic data that needs to be translated supported in the angular i18n proposal?

E.g. for a simple example, take:
```
<div>{{ user.status }}</div>
```
Where status can be selected from a set of known possibilities.

Another example, if I have a select over a set of attributes that are set dynamically:
```
<select ng-options="region.code as region.name for region in regions" ng-model="region">
   <option style="display:none" value="">select a region</option>
</select>
```

In something like angular-localization (similar to angular translate, dynamic i18n resolution system), these are handled as
```
<div>{{ user.status | i18n }}</div>
```
and
```
<select ng-options="region.code as (region.name | i18n) for region in regions" ng-model="region">
   <option style="display:none" value="">select a region</option>
</select>
```
This data cannot be known statically, at least not without significantly restructuring the surrounding code, but it's not clear to me that the current dynamic support proposal covers a situation like this, so I'm curious what the thinking is currently.

Thanks!

**Comment by pkozlowski-opensource** [comment]
@brycecr could we please move this discussion to https://github.com/angular/i18n ? Thnx!
