### ISSUE TITLE
Transclude + Ng-Repeat: Unable to Access Parent Directive's Controller/Scope from Transcluded Directive

### ISSUE THREAD

**Issue by nkoterba** [angular/angular.js#11376]
I'm trying to use nested directives + transclude + ng-repeat.  

In my inner directive (which is cloned via the `ng-repeat` directive), I need access to my outer directive's controller.  However, using 'require' on the DDO fails because in order to provide the necessary scope to `ng-repeat`, I must pass my `$scope.parent` to the transclude function which then omits my outer directive's scope/controller from the scope/controller tree.

It's much easier to show with an example.  The example has stripped out all my application code to show the basic concept. Open the Code Pen below, Open the browser's console, then refresh page to see error thrown by angular in console: 

http://codepen.io/anon/pen/PwXbGQ?editors=101.

Is this impossible to achieve using Angular 1.3?

**Comment by gkalpak** [comment]
Without going to deep, I wonder why you _need_ to pass `$scope.parent`. What prevents `ngRepeat`-created scopes from accessing the list o devices through prototypal inheritance ?
Could you share some code demonstrating the issue (when passing `$scope` instead of `$scope.parent`) ?
<sub>
Alternatively, you might want to look into `controllerAs` (assign the list to `devicesCtrl` and access it as `devicesCtrl.devices`).
</sub>

**Comment by wesleycho** [comment]
Have you tried structuring your tabs similar to [UI Bootstrap](http://angular-ui.github.io/bootstrap/#/tabs)?

**Comment by nkoterba** [comment]
@gkalpak 

So I've created a new CodePen to show why I can't just pass `scope` instead of `scope.$parent`.

Here is what I've changed:
1) I removed the goldenLayout from the goldenLayoutTab require statement (so pen runs without errors)
2) I added a console.log statement into the link function of the goldenLayoutTab directive.

If the link function in goldenLayout directive is:
```transclude(scope.$parent);```

the console log prints out 'getting called' twice (as it should since there are two objects in my my devices list).

If I switch the transclude to be:
```transclude(scope)```

No console output occurs meaning my ng-repeat was not called.  View forked CodePen here: http://codepen.io/anon/pen/OPrdzZ?editors=101

So just switch the transclude back and forth from `scope` to `scope.$parent` and you'll see I need to pass `scope.$parent` for my goldenLayoutTab directive link function to be called.

As for using controllerAs, here's a forked CodePen using controllerAs syntax and passing `scope` and you can see the `console.log('getting called')` statements still do **not** get called: http://codepen.io/anon/pen/QwzYQY?editors=101

**Comment by nkoterba** [comment]
@wesleycho Thanks for the suggestion. I will take a look.  I was actually using the `<md-tabs>` and `<md-tab>` syntax used by the Angular Material Design project as my model and there's seems to work fine:

<md-tabs> (which is equivalent to my <golden-layout>):
https://github.com/angular/material/blob/master/src/components/tabs/js/tabsDirective.js#L144-146

<md-tab> (which is equivalent to my <golden-layout-tab>):
https://github.com/angular/material/blob/master/src/components/tabs/js/tabItemDirective.js#L58-66,89-92

But I will see how Angular UI Bootstrap does it...perhaps that will show me another way to handle this scenario.

**Comment by gkalpak** [comment]
@nkoterba: It is still not clear (to me at least), why you need to pass `scope.$parent`.
You are manually transcluding and falling to actually append `goldenTab`'s content to the DOM (so no wonder you don't see any logs).

If you replace `transclude(scope)` with `transclude(function (clone) { element.append(clone); });`, it should work fine (no need to explicitly pass `scope` or `scope.$parent`).
It is also not clear, why `ngTransclude` wont work here.

**Comment by ibigbug** [comment]
+1

**Comment by Narretz** [comment]
Based on @gkalpak 's comments and the lack of feedback from @nkoterba I'm going to close this issue.
