### ISSUE TITLE
ng-if resolves strings "false" and "no" as (boolean) false

### ISSUE THREAD

**Issue by harunsmrkovic** [angular/angular.js#11371]
If I have an object 'note' with string 'title', and string is either "false" or "no", ng-if directive will resolve following query ```ng-if="note.title"``` as ```false```

**Comment by Narretz** [comment]
Are you on angular 1.2.x? Until 1.3.x, ngIf uses the same logic as ngShow for detecting `falsy`values: https://code.angularjs.org/1.2.28/docs/api/ng/directive/ngShow
This is working as expected.

**Comment by harunsmrkovic** [comment]
Was not aware of this... sorry... so ngIf in 1.3.x does not use this ```falsy``` logic anymore? Cool, thanks.
