### ISSUE TITLE
Support `<content>` in templates in place of `ng-transclude`

### ISSUE THREAD

**Issue by ewinslow** [angular/angular.js#11382]
`<content>` is the web-standards-compliant element that ng2 will be using for this sort of thing. It's really meant to be used in the context of shadow dom but I imagine it wouldn't be so bad to adopt it in ng1 to help ease migration, especially since it is the direct conceptual successor to ng-transclude.

One difference, IIRC, is that `<content>` element would be _replaced_ by transcluded content, rather than becoming the parent of the transcluded content, as ng-transclude does today.

**Comment by pkozlowski-opensource** [comment]
This sounds like a potential candidate for 1.5!

**Comment by ewinslow** [comment]
That's what I was going for! Though I would hope it could be pulled off without breaking changes?

**Comment by petebacondarwin** [comment]
Angular does not support `<content>` as an element directive any more. It is `ng-content`.
Adding `ng-content` as an alias for `ng-transclude` is not a particularly beneficial so we do not intend to implement this.
