### ISSUE TITLE
Email type is not validated properly in angularjs 1.3.4 version 

### ISSUE THREAD

**Issue by jkpatil211** [angular/angular.js#11385]
I am using form validation using angularjs version 1.3.14.
but the email is not validated properly 
when I type "jkpatil211@gmail" it accepts it as valid email format (actually it is not).
When I use version 1.2.6 it validates email properly.
You can check the code at following link.
Try changing angular version.
http://plnkr.co/edit/lCRwhj?p=preview

**Comment by Narretz** [comment]
Actually it is a valid email. You don't need a top level domain (e.g. intranet email). If you want to harden your validation, you can use ngPattern or modify the built-in validator, see https://docs.angularjs.org/guide/forms
