### ISSUE TITLE
Support creating new factories with different dependencies

### ISSUE THREAD

**Issue by dustyrockpyle** [angular/angular.js#11407]
In angular 1.3 the source for the factory provider is as follows:

```
function factory(name, factoryFn, enforce) {
  return provider(name, {
    $get: enforce !== false ? enforceReturnValue(name, factoryFn) : factoryFn
  });
}
```

enforceReturnValue shadows the factoryFn from being exposed, which prevents doing something like:

```
module.config(function($provide, $injector, myFactoryProvider) {
  $provide.factory('myNewCoexistingFactory', function(){
    var newDependencies = {oldDependency: $injector.get('newDependency')};
    return $injector.invoke(myFactoryProvider.$get, null, newDependencies);
  });
});
```

I'd like it if factory passed something like {$get: ..., $factoryFn: factoryFn} to provider. 

Is this an acceptable change? If so I'd be happy to submit a pull request.

Thanks.

**Comment by lgalfaso** [comment]
Hi, sorry for taking this long to answer. Do you understand that this has the potential that you will end up with multiple instances of `myFactory`, and that this has implications to Angular *flat* injector/services are singletons mechanism? A simpler solution would be to decorate `oldDependency` (even when that would change it for all services that depend on this)

I am leaning towards making this a non-issue

**Comment by pkozlowski-opensource** [comment]
Agree with @lgalfaso here. The solution with the current DI is to register a custom factory function as a service, inject this function into your objects and invoke the registered factory function to get different object instances on each call.

My call here would be to close this one as "won't fix".

**Comment by Narretz** [comment]
I agree with @lgalfaso and @pkozlowski-opensource. Also, no answer from OP.
