### ISSUE TITLE
$location.url() doesn't redirect to right URL

### ISSUE THREAD

**Issue by Heddy147** [angular/angular.js#11400]
Hello,

I want to use the $location-object to redirect to a specific URL but it doesn't work as expected.
Let's say I'm on the page with URL `http://www.test.de/my-page/#my-template/123`
When I call the function `url()` of the $location-object with parameter `/my-second-page/#my-second-template`, Angular redirect me to this URL:
`http://www.test.de/my-page/#my-template/#my-second-template`

What I'm doing wrong?

Thanks

**Comment by gkalpak** [comment]
When in [hashbang mode][1] (default), `$location.url()` refers to the part **after** the hashbang.

[1]: https://docs.angularjs.org/guide/$location#hashbang-mode-default-mode-

**Comment by Heddy147** [comment]
Thanks, it looks like what I want.
Now I have one problem:
I can't use hashbang mode AND html5Mode together.
I want to have only a forwarding to a "hasbang-mode" URL.
I think I have to use the native JavaScript-object `location.href`

**Comment by pkozlowski-opensource** [comment]
> I can't use hashbang mode AND html5Mode together.

Right, you have to use one mode consistently across the application. 

> I want to have only a forwarding to a "hasbang-mode" URL.
I think I have to use the native JavaScript-object location.href

Not sure I follow but if you want to update "path" in the hasbang mode you should use `$location.path(...)`

Closing as this seems to be more of a support question that would be better asked here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
