### ISSUE TITLE
ngStyle one-time binding regression

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#11403]
There's a regression in `ngStyle` that breaks lazy one-time binding  (when a property value is initially undefined), caused by https://github.com/angular/angular.js/commit/4c8d8ad5083d9dd17c0b8480339d5f95943f1b71

Example: http://jsbin.com/tuyetahaxi/2/edit - change the version to 1.3.9, and the background-color will not be applied.

The cause for this break is that $watchCollection passes its own changeDetector function to $watch, which does not return the actual changed values, but only a changeDetected counter. However, $parse has a special path for one-time bound object literals, where it unwatches only when all object properties /  array elements are defined (see https://github.com/angular/angular.js/commit/c024f28217cf8eedd695dd4b933ecf2ba4243c15). With watchCollection, the binding watch is now removed instantly as the value that is passed to $watch is not the actual object / array but the changeDetected count from $watchCollection. 
I worked around this by returning the actual newValue / oldValue from inside $watchCollection's changeDetected. I'll have to test if this breaks anything, though.

**Comment by daldegam** [comment]
+1

**Comment by lgalfaso** [comment]
it looks like 4c8d8ad5083d9dd17c0b8480339d5f95943f1b71 was simply wrong and should be reverted.
PR (with a test) welcome

**Comment by mzgol** [comment]
Shouldn't the revert add a test as well?

**Comment by Narretz** [comment]
The test was added in the commit before the revert. Not ideal, but hey. I thought I added it after it.

----- Ursprüngliche Nachricht -----
Von: "Michał Gołębiowski" <notifications@github.com>
Gesendet: ‎31.‎03.‎2015 14:03
An: "angular/angular.js" <angular.js@noreply.github.com>
Cc: "Martin Staffa" <mjstaffa@googlemail.com>
Betreff: Re: [angular.js] ngStyle one-time binding regression (#11403)

Shouldn't the revert add a test as well?
