### ISSUE TITLE
Controller 'ngMessages', required by directive 'ngMessagesInclude', can't be found!

### ISSUE THREAD

**Issue by xbagir** [angular/angular.js#11404]
Does not work directive ngMessagesInclude.
[Plnkr.co](http://plnkr.co/edit/Poc5QWn10Vi7fqfY2kzQ)

**Comment by gkalpak** [comment]
There has been a breaking change in 1.4.0-beta.5. Now `ngMessagesInclude` must be on its own element. For more details refer to the [changelog][1].

[1]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by Narretz** [comment]
Thx @gkalpak, you're right. Feel free to close such issues in the future. :)

**Comment by aaronroberson** [comment]
Can someone add the breaking change information to the following page:

https://docs.angularjs.org/error/$compile/ctreq?p0=ngMessages&p1=ngMessagesInclude

**Comment by KeyKrusher** [comment]
Sure I can do it.

**Comment by nawlbergs** [comment]
For the visual learners like myself....

this:
<div ng-messages="requestForm.email.$error" ng-messages-include="form-messages"></div>
now needs to be:
<div ng-messages="requestForm.email.$error">
    <div ng-messages-include="form-messages"></div>
</div>

**Comment by agriboz** [comment]
I had the same issue, however, @nawlbergs suggestion solved my problem :)

**Comment by videde** [comment]
Thank you @nawlbergs

**Comment by saurius** [comment]
Thanks @nawlbergs

**Comment by RezaRahmati** [comment]
Thanks @nawlbergs

**Comment by irvingellan** [comment]
Thanks @nawlbergs
