### ISSUE TITLE
@param docs missing for $routeChangeStart, $routeChange…

### ISSUE THREAD

**Issue by fredsa** [angular/angular.js#11418]
See latest docs: https://docs.angularjs.org/api/ngRoute/service/$route
See latest source: https://github.com/angular/angular.js/edit/master/src/ngRoute/route.js

Note that `$routeChangeStart`, `$routeChangeSuccess`, `$routeChangeError`, `$routeUpdate` each have documented parameters (via `@param`), but these parameters are missing from the published docs.

**Comment by petebacondarwin** [comment]
Feel free to send in further PRs for these docs @fredsa. Thanks

**Comment by Narretz** [comment]
@petebacondarwin Actually this seems to be a systemic problem: the event params are also missing from location and ngInclude. Is it possible that dgeni is not rendering these?

**Comment by Narretz** [comment]
@petebacondarwin It's not a dgeni issue yet, since I am not sure if it is actually a dgeni problem.

**Comment by petebacondarwin** [comment]
The change has landed in dgeni-packages. Will update automatically when we publish the next version and update angular.js npm-shrinkwrap.
