### ISSUE TITLE
Are filters really supposed to be idempotent?

### ISSUE THREAD

**Issue by dbmikus** [angular/angular.js#11417]
The documentation states that filters are supposed to be pure functions: stateless and idempotent. I believe this is incorrect. A pure function is not necessarily idempotent.

In the [example](https://docs.angularjs.org/guide/filter) in the docs, a filter called `"myReverseFilterApp"` is defined. It reverses the input. The definition of an idempotent function is that:

```
f(f(x)) = f(x)
```

Reversing a string twice is not equal to reversing it once. So, unless I'm misunderstanding something, the reference to idempotent functions should be removed. I don't know of the correct term to replace it, but I think it was trying to say that:

``` javascript
var a = f(x);
some_other_code_here();
var b = f(x);
assert(a === b);
```

The two files that affected are:

- [rootScope.js](https://github.com/angular/angular.js/blob/f8c8cf698aa23640249d79fd405605694478e4f7/src/ng/rootScope.js#L262)
- [filter.ngdoc](https://github.com/angular/angular.js/blob/4f12ed0e4ea2acbcd8ea85ee59aa8ed12c13337f/docs/content/guide/filter.ngdoc#L91)

**Comment by realityking** [comment]
Unfortunately some parts of computer sience have adoptet a somewhat different defintion of idempotency than mathematics. Here an idempotent function is one that produces the same result whether it's executed once or more than once.

The better term to describe what filters are supposed to be is probably "nullipotent", but that's not in very common use so it's probably not something to put in the documentation.

**Comment by dbmikus** [comment]
Ah, I see. Gotta love overloaded definitions.

**Comment by lgalfaso** [comment]
With the explanation from https://github.com/angular/angular.js/issues/11417#issuecomment-85968499 I think there is nothing else to follow-up on this
