### ISSUE TITLE
$http.get callback not be called on IE11 and cross domain

### ISSUE THREAD

**Issue by jamie2015** [angular/angular.js#11424]
I am developing a small application use angularJS. The html pages are local file which will not deploy on web server. I defined a service module which will call the remote webapi to get the json data, however my success callback not be invoked. 

Here is the code:
        $http({ method: 'GET', url: remoteServiceUri }).
            success(function (data, status) {
                var response = data;
            }).
            error(function (data, status) {
                var error = data;
            });

it always call into the error method. how can I resolve this issue please?

**Comment by jamie2015** [comment]
I can sure that the service is work, as I tried if I deploy the pages and service on same site, then it works fine. 

Is this caused by the cross domain or other configuration required?
Thanks

**Comment by Narretz** [comment]
Have you tried other browsers? This is usually a sign of missing CORS configuration on your backend server

**Comment by jamie2015** [comment]
Thanks. It works now after configuration the backend server to support CROS.
