### ISSUE TITLE
Declarative way to disable ngAnimate on element.

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular.js#11422]
I need a way to easily disable ngAnimate on a particular element via a declarative attribute.  Sometimes I don't have easy access to a particular DOM element through my javascript and desperately need to disable an animation.  The reason I need to disable it is that I need immediate removal of DOM element via ng-if or others.  Instead it waits about half a second or so to apply the ngAnimate classes at the appropriate interval.  It would be helpful if there was an attribute directive built in, like ng-animate-disable that would be able to keep this element from going through the animation process and would simply work as if ngAnimate was not included in the project.

**Comment by lgalfaso** [comment]
I think you are looking for https://docs.angularjs.org/api/ng/provider/$animateProvider#classNameFilter

**Comment by Guardiannw** [comment]
Does this enable the checking against the element's name, or the element's class attributes?  If it only works matching against the element name then I don't think it solves the problem, if it matches against the class attributes then I could selectively add a class and that would work fine, although a directive would be more ideal, as this applies to functionality that I am disabling and not styling.

**Comment by lgalfaso** [comment]
This is a match to the class... and you can always create a directive that
adds the class
>
>
