### ISSUE TITLE
Regression: cannot extend headers in requestTransform fn

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#11438]
Before https://github.com/angular/angular.js/commit/5da1256fc2812d5b28fb0af0de81256054856369, it used to be possible to do this:

```
        function requestTransform(data, headers) {
            headers = angular.extend(headers(), {
              'X-MY_HEADER': 'abcd'
            });
          }
          return angular.isObject(data) ? angular.toJson(data) : data;
        }
```

This is because the headersGetter used to re-use the argument instead of declaring a new one: https://github.com/angular/angular.js/commit/5da1256fc2812d5b28fb0af0de81256054856369#diff-748e0a1e1a7db3458d5f95d59d7e16c9L71

/cc @pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
I would argue that this is incorrect usage since the idea behind `transformRequest` is to transform _data_ to be sent - if I understand its intention correctly. In this sense it is like a filter so it really shouldn't assume that it can have side effects on its arguments....

My vote would be to documenting it as a breaking change.

**Comment by pkozlowski-opensource** [comment]
If someone wants to modify headers it should be done via a header being a function.

**Comment by Narretz** [comment]
I guess it's pretty weird to use it that way, yes.
You could basically change the whole headers object if you wanted to ... you can still to this with an interceptor, so that use case is covered.
An adding headers in the config is obviously the preferred way.

**Comment by pkozlowski-opensource** [comment]
Right, so my proposal is this:
- let's write an explicit tests that shows that we are not allowing this
- let's update the changelog with a breaking change (I'm on a fence here)

How does it sound @Narretz ?

**Comment by Narretz** [comment]
We've had breaking change notes for very minor things, so we should definitely do it. I'm not sure a test is needed, but it can't hurt.

**Comment by pkozlowski-opensource** [comment]
@Narretz I've sent #11503 to close this one. Mind having a look?
