### ISSUE TITLE
Error in Routes function use

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/angular.js#11436]
<html data-ng-app="demoApp">
 <head> 
   <title> Demo </title>
   

 </head>
 <body >
	<div>
		<div data-ng-view=""></div>
	</div>
	
   <script src="angular.min.js"></script>	
	
	<script type="text/javascript">

   var demoApp = angular.module('demoApp', []);
   

	demoApp.config(function ($routerProvider) {
	   $routerProvider
		.when('/view1',
		{
			controller : 'SimpleController',
			templateUrl: 'View1.html'
		})

		.when('/view2',
		{
			controller : 'SimpleController',
			templateUrl: 'View2.html'
		})
		.otherwise({redirectTo: '/'});
	});
	
	demoApp.controller('SimpleController', function SimpleController($scope)
	{
		$scope.customers = [
			{name : 'Gajendrasinh Zala', city : 'Ahemdabad'}, 
			{name : 'Hook', city : 'Morbi'}, 
			{name : 'Abby', city : 'Baroda'}, 
			{name: 'Swati Bathani', city : 'junagadh'}
		];
		
	$scope.addCustomer = function(){
	  $scope.customers.push(
		{
			name : $scope.newCustomer.name,
				city : $scope.newCustomer.city,
			});
	   };
	}); 
	
	</script>
 
 </body>
</html> 

This is my code and error is given below

Error: [$injector:modulerr] http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=demoApp&p1=%5B%24injector%3Aunpr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.14%2F%24injector%2Funpr%3Fp0%3D%2524routerProvider%0AM%2F%3C%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A6%3A417%0Aab%2Fp.%24injector%3C%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A38%3A7%0Ad%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A36%3A13%0Ae%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A36%3A283%0Ad%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A34%3A490%0Ag%2F%3C%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A35%3A117%0As%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A7%3A300%0Ag%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A34%3A399%0Aab%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A38%3A135%0Atc%2Fd%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A17%3A381%0Atc%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A18%3A179%0AJd%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A17%3A1%0A%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A249%3A428%0Aa%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A163%3A399%0Alf%2Fc%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A32%3A384%0A
	

...of e?JSON.stringify(e):e;c+=d(e)}return Error(c)}}function Ta(b){if(null==b||Ua(...

	
angular.min.js (line 6, col 416)

how can i solve this

**Comment by Narretz** [comment]
You need to require the `ngRoute` module: `var demoApp = angular.module('demoApp', ['ngRoute']);`

The error page would have shown you this ...

**Comment by ericmdantas** [comment]
I guess you'll have to add a dependency to ngRoute:

Download it using bower:

```

$ bower install angular-route --save

```

Or manually: https://code.angularjs.org/1.3.14/angular-route.min.js

add it to your index.html, and then require it on your module:

```

var app = angular.module('demoApp', ['ngRoute']);

```

From there, things should work as expected.
