### ISSUE TITLE
ngShow not working on stable versions

### ISSUE THREAD

**Issue by atishaybaid** [angular/angular.js#11430]
ng-show/ng-hide not working on stable versions, i tried with 1.3.13 and 1.3.15,however it works fine with CDN

**Comment by pkozlowski-opensource** [comment]
@atishaybaid not sure I understand. Could you please share a reproduce scenario using http://plnkr.co/edit/?p=preview ?

**Comment by pkozlowski-opensource** [comment]
Closing due to the lack of reproduce scenario.
