### ISSUE TITLE
$location.search() parameters

### ISSUE THREAD

**Issue by hurkanakbiyik** [angular/angular.js#11437]
When i send this url to controller: 
"http://localhost/match/result/?id=1234"
"$location.search()" gives me null ! But when i use like that 
http://localhost/match/result/#?id=1234
it gives me "{id: "1234"}" .
Is that a issue or trick ?

**Comment by pkozlowski-opensource** [comment]
It works as expected. AngularJS $location is concerned wit _cient-side_ routing and search params. You seem to be running in the hash-bang mode so the client-side part of the URL comes after #.

See https://docs.angularjs.org/guide/$location for more.
