### ISSUE TITLE
Weird behaviour with checkboxes model and ng-repeat

### ISSUE THREAD

**Issue by simonjodet** [angular/angular.js#11434]
Hello,
I've noticed a weird behaviour with a checkboxes model. If I use the same model for checkboxes in an ng-repeat and "hardcoded" checkboxes, checking a box in the ng-repeat loop won't work.
Please check this jsFiddle: http://jsfiddle.net/simonjodet/z1r2217e/

Is it due to some scope limitation I'm missing or is it a genuine bug?

Thanks.

**Comment by Narretz** [comment]
A few things:
* Very old version of angular (1.2.1). Update to 1.2.26
* You initialized `$scope.selection.ids` outside of a controller
*  `$scope.selection.ids` will throw, because selection is undefined

I currently cannot update the jsfiddle, but with 1.2.26 and this script, it works as expected:

```
var app = angular.module('app', []);

function Ctrl($scope) {
    $scope.selection = {
        ids : {
            '50d5ad' : false,
            '678ffr' : false
        }
    }

    $scope.categories = [ { "name": "Sport", "id": "50d5ad" } , {"name": "General", "id": "678ffr" } ];
    
}
```

**Comment by simonjodet** [comment]
I reproduced the issue with Angular 1.3.14 locally.

I've fixed the jsFiddle and when I initialise $scope.selection.ids, there is no issue. The issue is that without initialisation, it works for the "hardcoded" checkboxes but not for the "ng-repeat" ones. The issue is that the behaviour defers depending on how the checkboxes are created.

**Comment by Narretz** [comment]
It's always a good idea to provide an example that shows the problem by default, and uses the most recent patch version of your desired minor version.
Now I believe this is a classic case of prototypical scope inheritance. ngRepeat creates a new scope, and when you click the checkbox inside ngRepeat, it will create `selection` inside the new scope, not on the parent scope. If you initalize selection on the parent scope, it uses this because it is inherited.

**Comment by simonjodet** [comment]
You're probably right, that was my guess but I wonder why the checkbox doesn't even checks itself in the jsFiddle. Very weird. Anyway, I've worked around it by using 2 different models for the hardcoded boxes and generated ones and initialising the second model in my controller.

About the version issue, I didn't find how to select my version in jsFiddle so I selected the highest one.

**Comment by Narretz** [comment]
@simonjodet That's becasue angular 1.2.1 throws somewhere inside parse. It checks with 1.2.26. 
jsfiddle is stuck with 1.2.1 in the select, but you can simply include an url in the external Resources tab: https://code.angularjs.org/1.3.15/angular.js
Or use https://plnkr.co for an overall better experience.

**Comment by simonjodet** [comment]
Thanks for the answers and help!
