### ISSUE TITLE
filter Filter will convert null and undefined to strings

### ISSUE THREAD

**Issue by rince1013** [angular/angular.js#11432]
filterFilter will convert null and undefined to strings and use that to filter
This makes the default comparator unusable with arrays that have fields with null or undefined values.
This seems to be a regression - it works as expected in <=1.3.5

Here is plnkr
http://plnkr.co/edit/P67JlZv83ea8J5ZFw9Ce?p=preview

**Comment by Narretz** [comment]
I don't see it, maybe I don't understand the problem.
If you have `search.name = null`, it will filter correctly. If you have `search.name = undefined`, it will not match something with `name: undefined` , neither <= 1.3.5 nor after.

**Comment by pkozlowski-opensource** [comment]
This sounds somehow similar to https://github.com/angular/angular.js/issues/11312 - different filter but the same root cause.

**Comment by rince1013** [comment]
Maybe this update plunker will make it a bit clearer
http://plnkr.co/edit/f7trY8?p=preview

I have two values in the array where name is not a string - one is null and one is undefined
```javascript
[{name:null, phone:'The value of name is null'},
{name:undefined, phone:'The value of name is undefined'},
{name:'Mike', phone:'555-4321'},
{name:'Adam', phone:'555-5678'},
{name:'Julie', phone:'555-8765'},
{name:'Juliette', phone:'555-5678'}]
```

If I search this array for names with 'u', you would expect only J**u**lie and J**u**liette to return. But, also the null and undefined results are returned. The filter filter is treating null and undefined as strings, and then using the converted string value to determine if the array matches the search.

**Comment by rince1013** [comment]
And here is the offending line
https://github.com/angular/angular.js/blob/master/src/ng/filter/filter.js
in function createPredicateFn
```javascript
actual = lowercase('' + actual);
```
This line implicitly converts null into "null" and undefined into "undefined"

**Comment by hamfastgamgee** [comment]
Agree that it's very similar to my bug, #11312.  Sadly, the broken code isn't shared. :)

**Comment by pkozlowski-opensource** [comment]
Yeh, this is a valid one.

**Comment by gkalpak** [comment]
I always have a hard time differentiating between bug fixes and breaking changes when it comes to `filterFilter`. So, if I understand correctly, this is considered a bug/regression.

The desired behaviour is:

1. `null` item property | any string filter expression -> NO MATCH
2. `null` item property | `null` filter expression -> MATCH 
3. `undefined` item property | any string filter expression -> NO MATCH
4. `undefined` item property | `undefined` filter expression -> (irrelevant; no filtering anyway)

(Currently, (1) and (3) match if the filter expression is a subtring of `"null"`/`"undefined"` respectively.)

--
Do I miss something ?

**Comment by hamfastgamgee** [comment]
I think it's probably expected behavior that null/undefined filter
expressions will match everything as they do today.  (I don't think that's
directly stated in Georgios' post.)

On Thu, Mar 26, 2015 at 4:24 PM, Georgios Kalpakas <notifications@github.com

**Comment by gkalpak** [comment]
They don't do that today (nor did they do it pre 1.3.6) and I don't think they (both) should.

An `undefined` property of the filter expression is indeed ignored, so it will effectively match anything, since there is no filtering going on (this is mentioned in my previous comment and is what happens today).

A `null` property of the filter expression, should imo only match against a `null` property. I don't think `null` should match anything, since it is specific value and there are cases where you want to find `null`s. (I also think this has been discussed and agreed upon during/after the v1.3.6 refactoring of `filterFilter`, but I am not 100% sure.)
Note, that `null` did **not** match anything before the v1.3.6 refactoring either.

**Comment by hamfastgamgee** [comment]
I think I got confused and probably was conflating explicit null in a filter with the empty string.  Yes, I agree that what you say here.
