### ISSUE TITLE
orderBy: some string values break ordering (e.g. minus, plus, slash, ...)

### ISSUE THREAD

**Issue by m99coder** [angular/angular.js#11435]
Hi guys,

using built-in `orderBy` filter with some not so common string values representing keys in objects breaks ordering and also has different default sort order.

Basically a construct like the following doesn’t work currently by toggling sort order. It remains sorted descending always.

```html
<li data-ng-repeat="item in items | orderBy:'key-with-dashes':sortOrder">{{ item | json }}</li>
<a data-ng-click="sortOrder = !sortOrder">toggle sort order</a>
```

Additionally using `key/with/slashes` results in being sorted ascending always.

JSFiddle: http://jsfiddle.net/m99coder/82fj4vcs/3/

**Comment by gkalpak** [comment]
I am not sure this is an issue with `orderBy` (or filters in general), `$parse` or both.

The problem (if it is not obvious yet), it that in `| orderBy:<expr>:<reverse>`, `<expr>` is `$parse`d as an Angular expression, resulting to the following (semi-)unexpected behaviour:

```js
$parse('key-with-dashes')(item)
  Expected: item['key-with-dashes']
  Actual:   item.key - item.with - item.dashes
```

--
One possible work-around, is to wrap the key-string in an extra pair of quotes, to "force" the parser to interpret it correctly, but that not a real solution (imo). Not sure if a more appropriate solution/fix is actually possible.

Work-arounds:

```html
// Replace:
item in items | orderBy:criterion:reverse

// With:
item in items | orderBy:'\''+criterion+'\'':reverse
// Or:
item in items | orderBy:(criterion | json):reverse
```

**Comment by lgalfaso** [comment]
@gkalpak is spot on. This works as expected and the provided solutions should take care in case of this specific case
