### ISSUE TITLE
$injector.invoke(Object, this) fails with strict DI

### ISSUE THREAD

**Issue by daniel-white** [angular/angular.js#11444]
I have an inheritance graph for services that eventually fails with the equivalent of:

    $injector.invoke(Object, this);

when strict DI mode is on since `Object` does not have a `$inject` property.

Is `Object` something in 1.3.x `$injector.invoke` could bypass the strict check looking for `$inject`?

**Edit** For some reason `Object.length === 1`.

**Comment by daniel-white** [comment]
If I modify `annotate` from

    if (fn.length)

to including a check for `Object`

    if (fn.length && fn !== Object)

my code is able to work.

**Comment by jasonmobley** [comment]
Many (all?) of the other native constructors have the same problem. All of these constructor functions have a non-zero ```length``` property but show no formal arguments in ```toString()``` (at least in Chrome Canary where I tested): Object, Array, Date, RegExp, String, Number, Boolean.

Could ```annotate``` just check to make sure ```fn``` isn't a native constructor?

I don't know how reliable it is to check for the value ```[native code]``` in fn.toString(), but that's the first idea I would want to try.

**Comment by daniel-white** [comment]
@jasonmobley i found this - it seems to be a lot of code to effectively get at it. http://davidwalsh.name/detect-native-function

**Comment by lgalfaso** [comment]
I am not sure how is it possible to end up in a situation that you are asking Angular to instanciate `Object`. Without this, there is not a lot that can be done

**Comment by gkalpak** [comment]
This no longer fails (tested in 1.5.5). Closing...
