### ISSUE TITLE
IE11 win7, over CPU usage

### ISSUE THREAD

**Issue by pranaydutta89** [angular/angular.js#11440]
i am running a full fledged angular app on version  1.3.15 , while running on IE11 my cpu utilization is touching 100% , please mark me what all diagnostic screenshot you need i will attach the same

**Comment by andrewaustin** [comment]
Can you attach a code sample that recreates the issue? I do a lot of IE11 testing and I cannot recreate your issue.

**Comment by pranaydutta89** [comment]
thanks @andrewaustin  but it seems that its a third party directive error ,thanks for response
