### ISSUE TITLE
ES6 modules syntax with Angular 1.x.x

### ISSUE THREAD

**Issue by nervgh** [angular/angular.js#11454]
Hi!

I use [Babel](http://babeljs.io/) for writing es6 code. It looks like this:
```js
import Bar from 'path';

class Foo extends Bar {
    constructor() {
        super();
    }
}

export default Foo;
```
When I write angular module, I must wrap my class into function to make it work:
```js
// ----class----
export default function __(Bar) {

    class Foo extends Bar {
        constructor() {
            super();
        }
    }

    return Foo;
}

__.$inject = [
    'Bar'
];

// ----module----
import Foo from 'path';

angular
    .module('test', [])
    .factory('Foo', Foo);
```
I thought I found solution without wrapping, but it not works with `extends` ([sandbox](http://jsfiddle.net/5noshsgw/)):
```js
function Foo() {
    Foo.__['$rootScope'].x = 1;
}

Foo.__ = function($rootScope) {
    Foo.__['$rootScope'] = $rootScope;
    return Foo;
};

Foo.__.$inject = [
    '$rootScope'
];


angular
    .module('test', [])
    .factory('Foo', Foo.__)
    .run([
        'Foo',
        function(Foo) {
            console.log(new Foo());
        }
    ])
```
I tried to use `angular.injector()` but in this case the view not updates ([sandbox](http://jsfiddle.net/5noshsgw/1/)):
```js
var ng = angular.injector(['ng']);
var $rootScope = ng.get('$rootScope');

function Foo() {
    console.log('Foo#constructor');
    $rootScope.x = 1;
    // $rootScope.$apply();
}

Foo.__ = function() {
    console.log('Foo.__');
    return Foo;
};

angular
    .module('test', [])
    .factory('Foo', Foo.__)
    .run([
        'Foo',
        function(Foo) {
            console.log(new Foo());
        }
    ])
```
Is there way write angular code without wrapping?

Thanks =)

**Comment by wesleycho** [comment]
Ideally, Angular should support doing something like [this](http://jsfiddle.net/5uq7y0a1/) - I would say that maybe a modification in the injector to support this would be nice.

**Comment by wesleycho** [comment]
The problem here is that the `class` syntax in ES6 transpiles down to an object, and Angular has specific support for what arguments it supports in the module syntax. There is no avoiding having a wrapper function otherwise.

**Comment by nervgh** [comment]
> There is no avoiding having a wrapper function otherwise.
See my second examlpe. But in this case Angular don't update scopes =(

The problem is that Angular 1.x.x breaks syntax of ES6 modules.
Sadly.

**Comment by pkozlowski-opensource** [comment]
This doesn't sound right - if you plan on registering classes into ng 1.x DI system you should be using `.service` syntax instead of `.factory`. Also, I'm not sure why you would have to specify `Bar` as a dependency in DI if `Foo` simply extends `Bar` - this doesn't make sense.

Could you please put together a minimal plunk with the transpiled output you get with simple Foo and Bar classes without any additional "magic"?

**Comment by nervgh** [comment]
For example:

1. I have an `angular-some-module.js` which contains the `Bar` class.
2. I want create and inherit my class `Foo` from `Bar`.

```html
<script src="angular-some-module.js"></script>
<script src="angular-my-module.js"></script>
```
```js
angular
    .module('my', ['some'])
    .factory('Foo', [
        'Bar',                      // from angular-some-module.js
        function(Bar) {

            class Foo extends Bar {
                /**
                 * @param options
                 */
                constructor(options) {
                    super(options);
                }
            }

            return Foo;
        }
    ])
    .factory('instance', [
        'Foo',
        'options',
        function(Foo, options) {
            return new Foo(options);
        }
    ])
    .run([
        '$rootScope',
        'instance',
        function($scope, instance) {
            $scope.app = instance;
        }
    ]);
```

> This doesn't sound right - if you plan on registering classes into ng 1.x DI system you should be using .service syntax instead of .factory

Sorry for `.factory` in example.

What would you do in this case?

**Comment by wesleycho** [comment]
You can do
```javascript
class Foo {}

class Bar extends Foo {
  get $inject() {
    return ['$http'];
  }
  constructor(http) {
    super();
    this._http = http;
  }
}

angular.module('foo', [])
.service('foo', Foo)
.service('bar', Bar)
```

This keeps Foo and Bar decoupled from Angular completely if you so wish, or use an angular specific class that inherits from a completely decoupled class.

**Comment by nervgh** [comment]
@wesleycho , thanks, but subject of my question is

> 
I have an `angular-some-module.js` which contains the `Bar` class.
I want create and inherit my class `Foo` from `Bar`.

I think what there are not other solutions than the use of a wrapper function. I close this issue.

Example: [wrapper](https://github.com/nervgh/angular-file-upload/blob/master/src/services/FileSelect.js#L7) & [inheritance](https://github.com/nervgh/angular-file-upload/blob/master/src/services/FileSelect.js#L10).

Thanks to all for comments.
