### ISSUE TITLE
ng-options disable [beta 1.4]

### ISSUE THREAD

**Issue by fulup-bzh** [angular/angular.js#11453]
I'm trying to use ng-options with disable to prevent a user from selecting twice the same input value in two deferent select fields. 

While usage of a share object with select/ng-option works fine, when passing an option to "disable" after it was selected erase the option from the input field.

In my code extract, I have two selects [right & left channel]. They share a common pool of options (scope.linepools) each select has its own ng-model and I use the ng-click to activate a call back that move to disable an option as soon it is selected. My goal is to make sure that an option is only use once.

Problem, when I move an option to disable. It remove the option from the avaliable list on the other select [that's expected]. But is also remove the current selection from the original select [that's not what I want].

Question: how to implement multiple selects that share a pool of option, in such a way that an option can only be selected once with all the pool of select ?

```
 var template
   = '<div class="small-1 columns analog-inputs ajg-stereo-fader"> <p> {{leftModel.id}}</p><br>'
   + '<select title="leftChannel.name" class="ajg-stereo-fader-input-name ajg-select-left"  ng-options="linein.name disable  when linein.active for linein in linespool"  ng-model="leftModel"  ng-click="selected(1)"></select>'
   + '<select title="rightChannel.name" class="ajg-stereo-fader-input-name ajg-select-right" ng-options="linein.name disable when linein.active for linein in linespool" ng-model="rightModel" ng-click="selected(2)"></select>'
   + '<input type="text" class="ajg-stereo-fader-input-name" value="{{label}}">'
   + '</div>';
```

**Comment by Narretz** [comment]
Can you please post a reduction on http://plnkr.co or similar? Thanks!

**Comment by fulup-bzh** [comment]
I do not have a plkr for this, but I have a demo that use those options/selector at http://breizhme.net/alsajson/mixers/ajg#/scarlett?card=2

Each input line [top of UI] and output line [bottom] are unique ressources and when they are taken, no other select should be able to take them.

As I fail to use new angular option 'disable' capability, I rebuilt a componant from scratch. The source code is avaliable at https://github.com/fulup-bzh/AlsaJsonMixer/blob/master/src/common-ui/js/MatrixSourceMod.js

**Comment by Narretz** [comment]
Sorry for the late response. I don't think your use case is something that should be supported by angular core. I would probably use two different lists, and modify the second when the first select changes and vice versa, to implement your selection constraints.
