### ISSUE TITLE
Proposal: HTML5 mode becomes the default for Angular 1.5

### ISSUE THREAD

**Issue by btford** [angular/angular.js#11451]
See https://github.com/angular/router/issues/147#issue-59770128

**Comment by SanderElias** [comment]
I think this is the way forward! :+1:

**Comment by dpogue** [comment]
This definitely needs testing with Phonegap/Cordova apps to make sure it works properly. In Phonegap, all files are loaded using `file://` URLs and HTML5 mode has caused even basic Angular examples to fail when deployed to mobile devices in the past.

Right now the general rule is that if you're using Phonegap, you need to turn off HTML5 mode.

**Comment by SanderElias** [comment]
@dpogue Well, it is a breaking change, that's why it is proposed for 1.5. However, it has a very low impact on existing apps, the only change they need to make, is turn HTML5 routing off. 
Perhaps it is a good idea to make a notification in the documentation about that phonegap/cordova seem unable to handle HTML5 routing!

**Comment by frfancha** [comment]
Until now, there is no default in angular which forces to "know" in the server that there is angular at the other end.
Using HTML5 forces to configure the routing on the server to collaborate, and to become "angular" specific. Therefore I find this a very bad idea.

**Comment by SanderElias** [comment]
@frfancha I would argue that this is not a angular specific problem. It is the same problem for every other framework too. Every spa has the same issue. 
If you server can't handle this HTML5 spec, just turn this future off.

**Comment by frfancha** [comment]
@SanderElias It is not a question to be able to support it or not in the server, it is a question to make special routing config in the server or not.

**Comment by SanderElias** [comment]
@frfancha, I know. But believe me or not, there are servers that do NOT support this. But that is not an reason to keep Angular's default. Angular should move forward. It is about time to make HTML5 mode the default mode. As I said, it's a breaking change, but it will have very low impact. (As long as the docs are a bit updated, and point to the fact that not all servers are configured right to support this out of the box)
What I said was that, if your AngualrJS app must support an server that can't be configured rightly, you need to turn HTML5 mode off.  And that this is the same for every front-end solution, angular or not.

**Comment by ericmdantas** [comment]
:+1:

**Comment by realityking** [comment]
Would this mean dropping browsers that don't support the History API or are very buggy?

Currently [blacklisted]( https://github.com/angular/angular.js/blob/66ceecc2956ae4550cb3c2493be760184bc18777/src/ng/sniffer.js#L64) are Android < 4 and Boxee and it's [not supported](http://caniuse.com/#search=history) by Internet Explorer 9.

**Comment by pkozlowski-opensource** [comment]
@realityking why? My understanding is that the request is about flipping the _default_ configuration option, not the removal of the option altogether.

**Comment by SanderElias** [comment]
@realityking, @pkozlowski-opensource is right. we are proposing switching to HTML5 as default. Not removing anything. If you don't w/can't use it, flip the switch and your back in the past ;)
It also would line up more with the ngNewRouter(or whatever it's name will be).

**Comment by realityking** [comment]
@pkozlowski-opensource That's why I'm asking. Technically there's nothing wrong with just flipping the default

However I'm not sure how intuitive it is for the URLs to change in different browsers. We use HTML5 mode in our apps, and I noticed that devs new to angular would often just write a `href` instead of a `ui-sref` (we use UI Router). I'm sure plenty of people learning Angular would fall into the same trap.

Certainly not a killer argument, but IMO something that should be considered.

**Comment by pkozlowski-opensource** [comment]
@SanderElias right. Having said this I'm also not sure how flipping this switch makes the situation better for new router users. As a side remark - I was never been able to make an application, one deployed "in the wild" (so older IEs / android) to work in the HTML5 mode.... There is just too much pain in practice with old browsers switching between modes that it is not worth in practice IMO. In this sense I side with @realityking here.

**Comment by SanderElias** [comment]
@pkozlowski-opensource @realityking,
Well, there was a request to let the router be HTML5 mode default. That would require the router to use a config to flip the default behavior of AngalarJS itself. That is not something that we would want (see [the discussion in the router repo](https://github.com/angular/router/issues/147#issue-59770128))

I think 1.5 is the right place to do a switch like this. 1.5 is about migration. I think that with the browsers that NG2 targets, it won't be an issue anymore, so if you want to prepare yourself for that, its a good diea to get used to HTML5 routing.

Also, with [the current state of browsers ](http://gs.statcounter.com/#browser_version_partially_combined-ww-weekly-201512-201513-bar) I believe it's about time to make the switch! At least for new projects!

**Comment by theodorejb** [comment]
Why not default to HTML5 mode, and automatically fall back to hash mode if the browser doesn't support the history API?

**Comment by realityking** [comment]
@theodorejb That's already happening. My point is, that that behavior mid very confusing to developers new to Angular.

**Comment by wesleycho** [comment]
It should be noted, this is a huge breaking change with regards to build config for local development servers and server config.

**Comment by rohanrehman** [comment]
I haven't seen any examples with html5 mode. In 1.3 was
```Javascript
 $locationProvider.html5Mode(true) 
```
how is it done now?

**Comment by ericmdantas** [comment]
@rohanrehman, I'd say this is the same as you wrote (1.3~):

```js

$locationProvider.html5Mode({  enabled: true,  requireBase: false});

```

Which leads me to a question: would requireBase also be required by default? I mean, like this:

```js

$locationProvider.html5Mode({  enabled: true,  requireBase: true}); // this is the default

```

**Comment by rohanrehman** [comment]
@ericmdantas injecting $locationProvider throws an unknown Provider error. Ultimately I doubt $locationProvider is actually retrievable in 1.4 when using the new router. have you gotten html5 mode to work? I've yet to see any hmtl5 routing example using the new router

**Comment by ericmdantas** [comment]
@rohanrehman, I have this project that I guess I have it working. I'm not sure about the versions, though - I'll check it later today and I'll let you know.

**Comment by rohanrehman** [comment]
@ericmdantas had to be in a .config call.

```javascript
    .config(['$locationProvider', function ($locationProvider) {
        $locationProvider.html5Mode({  enabled: true,  requireBase: true});
    }])
```

**Comment by ericmdantas** [comment]
@rohanrehman, yeah, that's where you can get the providers.

[I was going to show you how I did it](https://github.com/ericmdantas/shoulders_of_giants/blob/master/client/dev/js/application/app.js) - nothing different, really.

**Comment by Narretz** [comment]
Unlikely to change at this point - we already changed the prefix to be '!' by default, changing to html5 mode could probably wreck havoc on many apps without a clear benefit
