### ISSUE TITLE
 double <li> nested   Unable to display 

### ISSUE THREAD

**Issue by cnlinjie** [angular/angular.js#11462]
Bug ? double <li> nested  ，Unable to display 。
<ul>
                <li ng-repeat="phone in phones" >
                    <li>{{phone.name}}</li>
                </li>
</ul>
Generation html  doc is :  
<ul class="phones">
                <li ng-repeat="phone in phones" class="ng-scope">
                    </li><li ng-repeat="phone in phones" class="ng-scope">
                    </li><li ng-repeat="phone in phones" class="ng-scope">
                    </li><li class="ng-binding"></li>
                
            </ul>

help!!!
so , my english is poor!!

**Comment by pkozlowski-opensource** [comment]
You can't nest `<li>` elements within `<li>` elements - this is not a valid HTML and browsers will "auto-correct" it.

Anyway, this is a general support question and as such it should be asked using one of the support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by cnlinjie** [comment]
I  see ,Thanks. ！！
