### ISSUE TITLE
Bug: select chooses null option when empty option is selected. 

### ISSUE THREAD

**Issue by smithscripts** [angular/angular.js#11468]
I have the following model

    function TodoCtrl($scope) {
        $scope.choices = [
            { value: true, label: 'True' },
            { value: false, label: 'False' },
            { value: null, label: 'Null' }
        ];
    }

and markup:

    <div ng-app>
      <div ng-controller="TodoCtrl">
        <select 
          ng-model="selected" data-ng-options="x.value as x.label for x in choices">
              <option value=""> </option>
        </select>  
      </div>
    </div>

When I select the empty option the null value is selected.

[Fiddle](http://jsfiddle.net/xQ9Mu/5/)

**Comment by Narretz** [comment]
Hm, it's also in the latest beta: http://jsfiddle.net/xQ9Mu/7/

**Comment by jeaxelrod** [comment]
Hi. I'm trying to solve this bug. I can't recreate the issue within a test. I wrote this within ngOptionsSpec.js https://gist.github.com/jeaxelrod/4e45293efe6077932bbf and it currently passes.

**Comment by smithscripts** [comment]
It does not look like you created an empty option in your test...

**Comment by jeaxelrod** [comment]
I added the helper function createSelect(attrs, blank, unknown) to the gist that is included in the original spec file. When I call it, I set blank=true creating the empty option.

**Comment by Narretz** [comment]
Works in 1.4.0: http://jsfiddle.net/xQ9Mu/9/
