### ISSUE TITLE
new `$q(executor)` does not catch exceptions

### ISSUE THREAD

**Issue by lapo-luchini** [angular/angular.js#11472]
The following code prints `UErr`.

        try{
            $q(function (res, rej) {
                throw new Error('Wrong.');
            }).then(function () { $log.info('OK?');
            }).catch(function (e) { $log.info('Err', e);
            });
        } catch (e) { $log.info('UErr'); }

I'm not sure I understand the [ES6 specs](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise-executor) but in [BlueBird](https://github.com/petkaantonov/bluebird) (`new Promise(executor)`) and in [Q](https://github.com/kriskowal/q) (`new Q.Promise(executor)`) this prints `Err [Error: Wrong.]`.

**Comment by lapo-luchini** [comment]
Does not seem related to #3174 and could probably be solved in [q.js#L558](https://github.com/angular/angular.js/blob/master/src/ng/q.js#L558) like this:

    try {
        resolver(resolveFn, rejectFn);
    } catch (e) {
        deferred.reject(e);
    }

**Comment by petebacondarwin** [comment]
I think you might be right. From the ES6 spec:

```
10. Let completion be Call(executor, undefined, «resolvingFunctions.[[Resolve]], resolvingFunctions.[[Reject]]»).
11. If completion is an abrupt completion, then
  a. Let status be Call(resolvingFunctions.[[Reject]], undefined, «completion.[[value]]»).
  b. ReturnIfAbrupt(status).
```

My reading of this is that if the call of `executor` returns **abruplty**, e.g. throws, then it should call the reject function.

@caitp - you know about this stuff. Does that sound right to you?

**Comment by caitp** [comment]
@petebacondarwin technically yes, per spec, this should be a rejection.

It shouldn't be a rejection for a lot of better reasons (early errors are less likely to be missed if they explicitly throw).

Native promises in Chromium work around this now by reporting uncaught rejections (and Bluebird does this as well), but it wasn't popular with Igor.

I think it's better to leave it as-is, because A) we avoid the try/catch deopt, and B) we make it possible for developers to catch their early errors.

**Comment by petebacondarwin** [comment]
I agree with @caitp - we should leave it throwing. It is simple enough to work around this in application code if you wish by wrapping your own executor function:

```js
    try{
        $q(function (res, rej) {
            try {
              throw new Error('Wrong.');
            } catch(x) {
              rej(x);
            }
        }).then(function () { $log.info('OK?');
        }).catch(function (e) { $log.info('Err', e);
        });
    } catch (e) { $log.info('UErr'); }
```

**Comment by petebacondarwin** [comment]
@IgorMinar do you want to chime in here too?

**Comment by caitp** [comment]
I'm not strongly opposed to a patch to fix it though, I just worry that it might lead people to ignore incorrect code

**Comment by lapo-luchini** [comment]
If it is chosen not to adhere to the ES6 specs, I'd suggest to add some comment in the documentation, to avoid the "unexpected" factor. (or at least, unexpected behavior could still bite people, but then they could check the docs and find the reason)

**Comment by IgorMinar** [comment]
@caitp just to clarify, I wasn't a big fan of the implementation we had. I do like the feature.

I think for now we should document the deviation from the spec as well as the workaround. In 1.5 we can take a look at this and see if we can do better.

**Comment by stucox** [comment]
Raised PR #13101 to document this.
