### ISSUE TITLE
Loading angular-route.js asynchronously throws error, no routes load

### ISSUE THREAD

**Issue by jerryorta-dev** [angular/angular.js#11489]
Overview of the Issue:
Utilizing the asynchronous version of the angular seed app updated to angular 1.3.15, angular-route throws the error "Uncaught TypeError: undefined is not a function". No views are rendered.

Motivation for or Use Case:
Forking the angular-seed app to have a version updated to angular-1.3.x using the async loader.

Angular Versions:
1.3.15

Browsers and Operating System:
Chrome Version 41.0.2272.118 (64-bit) -- Mac

Reproduce the Error
See Plunker: http://embed.plnkr.co/0EnOXPHKuOic84EdLoI4/preview
DO NOT ENABLE BATARANG. Loading works when Batarang is enabled.

Related Issues:
None.

Suggest a Fix:
None. But I temporarily have a version working when I change line 27 of the distributed (bower) angular-route.js file from 
    $routeMinErr = angular.$$minErr('ngRoute');

    to

    $routeMinErr = angular.$minErr('ngRoute');

   Note the $minErr change.

**Comment by petebacondarwin** [comment]
@jerryorta-dev I think you are using an invalid version of the loader.js in your index.html.
When I copy the one directly from the latest 1.3.x build it works fine: http://plnkr.co/edit/JznGQyt7URwY4bX39zWH?p=preview

**Comment by jerryorta-dev** [comment]
Thank you, changing the loader version from 1.3.15 to 1.3.16-build.102+sha.40441f6 fixed the issue.

For completeness in case other people are having this issue, I've updated the bower.json in my forked seed to:

"dependencies": {
    "angular": "1.3.16-build.102+sha.40441f6",
    "angular-route": "1.3.16-build.102+sha.40441f6",
    "angular-loader": "1.3.16-build.102+sha.40441f6",
    "angular-mocks": "1.3.16-build.102+sha.40441f6",
    "html5-boilerplate": "~4.3.0"
  }

@petebacondarwin, if I may leave it to you to close this issue if think this is a sufficient fix, because I would still consider this a bug for v1.3.15 until v1.3.16 is released.

**Comment by jerryorta-dev** [comment]
Just learned by accident async loader does work with version 1.3.15. It only fails when I have devTools open upon loading or refreshing the page. I always have devTools open when developing, so never occurred to me to try loading when devTools is closed.

**Comment by petebacondarwin** [comment]
Actually using the 1.3.15 version of loader.js (taken from https://code.angularjs.org/1.3.15/angular-loader.min.js) works too.
See http://plnkr.co/edit/HQZ2gGujAeY7y4j8el8L?p=preview
I wonder if there was something weird with the loader that you had originally?

**Comment by jerryorta-dev** [comment]
I learned It failed because I had devTools open while loading / refreshing
the page. Seems like I have an issue with my environment. Thanks for your
help.

On Thu, Apr 2, 2015 at 3:04 PM, Pete Bacon Darwin <notifications@github.com>
wrote:

> Actually using the 1.3.15 version of loader.js (taken from
> https://code.angularjs.org/1.3.15/angular-loader.min.js) works too.
> See http://plnkr.co/edit/HQZ2gGujAeY7y4j8el8L?p=preview
> I wonder if there was something weird with the loader that you had
> originally?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/issues/11489#issuecomment-89027360>
> .
>



-- 
Jerry Orta
UI / UX Engineer
512-381-9852
