### ISSUE TITLE
datetime-local How to change NO locale datetime

### ISSUE THREAD

**Issue by hurkanakbiyik** [angular/angular.js#11496]
<input type="datetime-local" name="name" class="form-control"  ng-model="matchDay">

When i insert datetime result look like = Fri Oct 20 2000 20:20:00 GMT+0300 (Turkey Daylight Time)

I want to change this to no locale like Fri Oct 20 2000 20:20:00 GMT+0000 (UTC) because of when i post this value to my php then send to mysql result look like = 2000-10-20T17:20:00.000Z

How can i change this or how i can use datetime without locale ?

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem); these types of questions are ill-suited for GitHub. Thanks!
