### ISSUE TITLE
IE Window loses focus on start of Angular app with any XMLHttpRequest

### ISSUE THREAD

**Issue by zimmul** [angular/angular.js#11491]
Framework versions:
Angular (and angular-resource) - 1.2.x, 1.3.x
JQuery - 1.11.x and 2.1.x

I am seeing some bizarre behavior with IE 9, 10 and 11 where, upon loading an AngularJS app, the window loses focus.  It only happens when any XMLHttpRequest request is made while the page is initially loading.  Any application interaction, with or without ajax, after that is normal.  To be clear, it happens when loading an HTML template for a directive using 'templateUrl' as well as using $resource or $http to load JSON data from an endpoint.  An example of how I am using $resource is below:

    /**
     * Resource module
     */
    angular.module('appname.resources.sampleData', ['ngResource'])
      .service('sampleDataResource', ['$resource', 'restUrl', SampleRestResource])
      .constant('restUrl', '/url/path/to/rest/data/:id');

    /**
     * Resource definition
     */
    function SampleRestResource ($resource, restUrl) {
      this.resource = $resource(restUrl);
    }

    /**
     * Resource query function
     */
    SampleRestResource.prototype.query = function () {
      return this.resource.query().$promise;
    };

The page controller that uses the rest resource is defined as:

    /**
     * Page module definition
     */
     angular.module('appname.pages.defaultpage', [])
       .constant('strTitle', 'Page Title')
       .controller('defaultPageController', ['$scope', 'strTitle', 'sampleDataResource', DefaultPageController]);

    /**
     * Page controller definition
     */
    function DefaultPageController($scope, strTitle, sampleDataResource) {

        $scope.pageTitle = strTitle;

        sampleDataResource.query().then(function(data) {
            $scope.sampleDataFromResource = data;
        });

    }

If I swap out the ajax request in the controller with a JQuery equivalent the window does not lose focus.  The controller then becomes:

    /**
     * Page controller definition
     */
    function DefaultPageController($scope, strTitle, sampleDataResource) {
    
      $scope.pageTitle = strTitle;

      $.get("/url/path/to/rest/data").done(
          function(data){
              $scope.sampleDataFromResource = data;
          }
      );

    }

As I mentioned in my introduction to this issue, I see the same results when making requests of HTML templates within $routeProvider configuration or directive definitions using 'templateUrl'.  A dirrective sample looks like:

    /**
     * Directive module definition
     */
    angular.module('appname.directives.content', [])
        .directive('showContent', ShowContent);

    /**
     * Directive definition
     */
    function ShowContent() {
        return {
            restrict: 'E',
            controller: 'directiveController',
            templateUrl: '/directory/to/html/template.html'
        };
    }

**Comment by pkozlowski-opensource** [comment]
@zimmul I would suspect that you've got an interceptor or UI binding that makes focus changes - I can't think of anything in AngularJS that could cause this behavior. 

Could you please provide a minimal, runnable scenario using plunker, jsbin or similar, so we can see this bug "in action"?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by zimmul** [comment]
Eureka!  Your comment about "an interceptor or UI binding" prompted me to remove angular-block-ui from my app.  That plugin is causing the lose focus event.  Thank you very much!
