### ISSUE TITLE
ngAria: tabIndex unnecessarily added to buttons & other interactive elements

### ISSUE THREAD

**Issue by marcysutton** [angular/angular.js#11500]
As it is currently written, ngAria is a bit too generous about adding `tabindex="0"` to elements. It adds the attribute to any element with `ngModel` or `ngClick` without checking whether it should actually do that. This includes buttons, inputs and other elements that might not need it. Adding unnecessary `tabindex` contributes to code bloat and is generally a poor practice.

**Comment by thebuilder** [comment]
This is still an issue on Radio buttons, where it sets `tabindex` to `-1`. The selected radio button gets `0`, but this still prevents you from tabbing to the other radio buttons. 
See: https://github.com/angular/angular.js/issues/12492#issuecomment-146304876
