### ISSUE TITLE
$scope push doesn't work

### ISSUE THREAD

**Issue by vinsvins** [angular/angular.js#11506]
Hey everyone!! I have an issue with this code.

In my controller I have this.    
```javascript
    $scope.spiagge = [];
    var distanza = function(info, posizione) {
		    var request = {
			    origin : posizione,
			   destination : new google.maps.LatLng(info.latitudine, info.longitudine),
			   travelMode : google.maps.TravelMode.DRIVING
		   };
		   directionsService.route(request, function(response, status) {
			   if (status == google.maps.DirectionsStatus.OK) {
				   //$scope.directionsDisplay.setDirections(response);

				   info.distanza = response.routes[0].legs[0].distance.text;

				   //distanza= response.routes[0].legs[0].distance.value/1000 ;
			   }

			riempi(info);

		});
//riempi(info);
	}
	var riempi = function(spiaggia) {
		//alert("distanza " + spiaggia.distanza);
		$scope.spiagge.push(spiaggia);
	}
```
If I put riempi(info) outside the directionsService function $scope.spiagge.push works without info.distanza, I think because info.distanza is a local variable of directionService . If i put inside,like in the code here, doesn't works at all but the riempi function sees every value of info, distanza included.
I don't know what to do. 
This is the view 
``` html
    <div class="lista_home" ng-repeat= "spiaggia in spiagge">
        <h1>{{spiaggia.nome}}</h1> <p>distanza {{spiaggia.distanza}} km </p>
      </div>
```
Sorry for my english.
Any idea?

Thanks.

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem); these types of questions are ill-suited for GitHub. Thanks!
