### ISSUE TITLE
SyntaxError: Unexpected token ; When making an http request.

### ISSUE THREAD

**Issue by AskYous** [angular/angular.js#11513]
(I'm new to submitting issues).

I have some code in my js files where data is loaded using a local array for **$scope**:

    $scope.carouselItems = [{
			header: 'Televisions',
			description: 'Explore the future of picture quality with this 60" 3D UHD 4K Smart TV that features a 3840 x 2160 native resolution for viewing high-resolution content. You can even upscale lower resolution material to near-4K picture quality.',
			href: '#/Learn More',
			img: 'img/TV-4k-Curved.jpg',
			btnText: 'Learn more'			
		}, ... ];

Everything works fine at this point. But then I moved this array into it's own `json` file, and used **Angular's http service** to retrieve the data. This code caused an error:

    $http.get('data/carousel-items.json').success(function (data) {
		$scope.carouselItems = data;
	});

And this is my **carousel-items.json** file:

    [{
	"header": "Televisions",
	"description": "Explore the future of picture quality with this 60\" 3D UHD 4K Smart TV that features a 3840 x 2160 native resolution for viewing high-resolution content. You can even upscale lower resolution material to near-4K picture quality.",
	"href": "#/Learn More",
	"img": "img/TV-4k-Curved.jpg",
	"btnText": "Learn more"	
    },{
	"header": "Notebooks",
	"description": "Boots in seconds. Nothing complicated to learn. Comes with your favorite Google apps. Built for everyday use and perfect for sharing with others. Starting at $199.",
	"href": "#/Learn More",
	"img": "img/chromebook-hp-14.jpg",
	"btnText": "Learn more"			
    },{
	"header": "Wearables",
	"description": "Android Wear organizes your information, suggests what you need, and shows it to you before you even ask. Get messages from your friends, meeting notifications, and weather updates at a glance.",
	"href": "#/Learn More",
	"img": "img/wear.jpg",
	"btnText": "Learn more"			
    }];

And this is a snippet of my my **index.html** file:

    
        <div ng-repeat="item in carouselItems" class="item" ng-class="{active: $index == 0}">
          <img ng-src="{{item.img}}">
          <div class="container">
            <div class="carousel-caption">
              <h1>{{item.header}}</h1>
              <p>{{item.description}}</p>
              <p><a class="btn btn-lg btn-primary" href="{{item.href}}" role="button">{{item.btnText}}</a></p>
            </div>
          </div>
        </div>

When I refreshed the page, I received the following error in **Google Chrome's JavaScript console**:

    SyntaxError: Unexpected token ;
    at Object.parse (native)
    at pc (http://localhost:3000/xerorex/bower_components/angular/angular.min.js:14:208)
    at Zb (http://localhost:3000/xerorex/bower_components/angular/angular.min.js:76:379)
    at http://localhost:3000/xerorex/bower_components/angular/angular.min.js:77:237
    at s (http://localhost:3000/xerorex/bower_components/angular/angular.min.js:7:302)
    at Zc (http://localhost:3000/xerorex/bower_components/angular/angular.min.js:77:219)
    at c (http://localhost:3000/xerorex/bower_components/angular/angular.min.js:78:349)
    at http://localhost:3000/xerorex/bower_components/angular/angular.min.js:112:20
    at l.$get.l.$eval (http://localhost:3000/xerorex/bower_components/angular/angular.min.js:125:305)
    at l.$get.l.$digest (http://localhost:3000/xerorex/bower_components/angular/angular.min.js:122:398)

It looks like an error on Angular's side, so I submitted it here.

**Comment by pkozlowski-opensource** [comment]
The problem is in your JSON file - notice `;` at the end - this makes the JSON invalid.

Please use a dedicated support channel for questions like this in the future:
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by supriyanatrajan** [comment]
while making http request for external
![angularerror](https://cloud.githubusercontent.com/assets/16098810/12814395/c7c85ac6-cb64-11e5-8d5e-249b6d2cf5e8.PNG)
 json file everytime i am getting SyntaxError: Unexpected token } in angular.min.js line number 108.i tried with different versions of angular.js and angular.min.js files.Stll i am getting the error.

**Comment by gkalpak** [comment]
@supriyanatrajan, it is probably a problem with your JSON data. Feel free to ask for help on one of the [support channels][1].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by sibascodeking** [comment]
The json packet was not properly arranged.

**Comment by saleemalidev** [comment]
I got error when i am callging json file  Unexpected token < in JSON at position 0  please help me..
