### ISSUE TITLE
Have $q.fail to mimic kriskowal Q's fail

### ISSUE THREAD

**Issue by syndbg** [angular/angular.js#11516]
As title suggests,

currently $q has a `catch` method as Kriskowal's Q, but no `fail` method.

Any specific reasons for not including it ?

**Comment by pkozlowski-opensource** [comment]
Yes, this is explained in "Differences between Kris Kowal's Q and $q" section of https://docs.angularjs.org/api/ng/service/$q:
> Q has many more features than $q, but that comes at a cost of bytes. $q is tiny, but contains all the important functionality needed for common async tasks.

In short - we want to keep $q as small as possible.

**Comment by lgalfaso** [comment]
Agree with @pkozlowski-opensource we are trying to keep `$q` as small as possible. Closing this issue
