### ISSUE TITLE
ngOptions documentation for API reference < 1.4.x does not exists

### ISSUE THREAD

**Issue by samy100** [angular/angular.js#11522]
ngOptions documentation for API reference < 1.4.x does not exists for some reason.

Ok:
https://docs.angularjs.org/api/ng/directive/ngOptions
Error Page:
https://code.angularjs.org/1.3.15/docs/api/ng/directive/ngOptions
Error Page:
https://code.angularjs.org/1.2.28/docs/api/ng/directive/ngOptions

**Comment by lgalfaso** [comment]
It used to be under [`select`](https://code.angularjs.org/1.3.15/docs/api/ng/directive/select) as in 1.4 was refactored to be a proper directive

**Comment by samy100** [comment]
Changing the angular version on the dropdown should send you to directive/select then not directive/ngOptions for all versions. It's not obvious. Thanks for the notice though, now I know where to look.
