### ISSUE TITLE
Lexer Error: Unexpected next character  at columns 1-1 [ª] in expression [4ª Bda C Mec/TO].

### ISSUE THREAD

**Issue by dsansao** [angular/angular.js#11536]
I´m using a expression in html after a ng-repeat like:

<li ng-repeat="item in itens">{{item.name}}</li> and this problem happens.

somebody knows why?

**Comment by Stephn-R** [comment]
Please provide more context. Can you submit a plnkr link?

**Comment by pkozlowski-opensource** [comment]
@dsansao as commented by @Stephn-R it is impossible to action on this one - we are lacking essential context information. Please see our bug reporting guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by dsansao** [comment]
i resolve the problem. At really the problem was in orderBy.  :/
Cause i pass the object to filter instead of passing the name of the colunm

thnx for help

**Comment by pkozlowski-opensource** [comment]
@dsansao thnx for the info. Could you please close the issues that you've opened and determined not to be a bug? This would save us time. Thnx!
