### ISSUE TITLE
Anchor tag click is not working in a form, if the form input field has focus and has validation errors

### ISSUE THREAD

**Issue by vikrambabu2** [angular/angular.js#11532]
Please use the following plunker to reproduce issue.
Please focus input field and click on anchor tag. You can see, the anchor tag click is not working as the input field validation is triggered on blur. I am seeing the issue is due to using form.input.$touched in ng-show. I have created a plunker to reproduce the issue.

http://plnkr.co/edit/0NMhxP18EhBjLyKrJQV5?p=preview

To reproduce the issue, first focus input field and then click on anchor tag.

**Comment by nhodges** [comment]
This really has more to do with the placement of your error message -- the click behavior still triggers when you actually click the anchor tag.

**Comment by Narretz** [comment]
@nhodges is right. The `blur` event of the input is fired before the click event of the anchor. Because the error message is shown on blur, the click is registered on the error message and not on the anchor. (Because the error message takes the place of the anchor)
