### ISSUE TITLE
ng-modal problem

### ISSUE THREAD

**Issue by hirengajjar** [angular/angular.js#11537]
Ng-modal is not able to work with dynamic data. When I filled up form and if  I peers add more button to make duplicate form then after I can't submit the records to database.

**Comment by hirengajjar** [comment]
Can any one provide the solution for my problem

**Comment by pkozlowski-opensource** [comment]
@hirengajjar your question is totally not clear and in this form no one can help you really. There is no `ng-modal` in AngularJS (did you mean `ng-model`???) and we are lacking tons of context (AngularJS version, browser used, exact reproduce scenario etc.).

But above all, support questions like this should be asked on the dedicated support channel, see:  
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by hirengajjar** [comment]
Need to find way to submit dynamic data which is automatically generated
