### ISSUE TITLE
Log warning when attempting to use registered directive in wrong modality

### ISSUE THREAD

**Issue by matthewjh** [angular/angular.js#11538]
Hi,

So earlier today I had an issue using `ngTransclude` in Angular 1.2 as if it were an E-restricted directive. In 1.2, `ngTransclude`'s `restrict` is `AC`. In 1.3, it is `EAC`. Of course, I was unaware of this discrepancy, and my app failed silently.

I think it would be valuable for `$compile` to log a warning when encountering an attempt to utilise a directive in a manner incompatible with its `restrict` property.

Thoughts?

**Comment by pkozlowski-opensource** [comment]
This is definitively doable but would add extra processing to the compiler. So we need to be careful and decide if this additional, nice error reporting, is worth the perf penalty (if one is significant).

**Comment by matthewjh** [comment]
@pkozlowski-opensource:

Thought about this some more, and I don't think it's implementable unfortunately. 

If you were to register an E-restricted directive named 'style', then `$compile` would spit out warnings for every occurrence of `style` attributes.

Can you think of any workaround or should we close this?

**Comment by pkozlowski-opensource** [comment]
Right. One could argue that no one should create a directive named `style` but yes, there is potential for many false alarms here.

IMO it is not worth it, I would vote for closing this one.

**Comment by matthewjh** [comment]
@pkozlowski-opensource 

Angular does. :p

https://github.com/angular/angular.js/blob/c94329a891a1c082567c490ccf58ba8592b464ad/src/ng/directive/style.js

I have no idea why though.

**Comment by Narretz** [comment]
Okay, let's close this then.
