### ISSUE TITLE
$touched does not work on Android OS for hybrid application

### ISSUE THREAD

**Issue by meetrajatgupta** [angular/angular.js#11531]
Hi,

I created a form using angularJS validators in IBM Worklight and installed it on android. But i encountered a strange issue that $touched validator is not working. Where as other validators like $dirty/$valid/$invalid are working properly. But if i create a html page with form and $touched validator and open in desktop browser or android chrome browser $touched works properly.

Thanks for the help.

**Comment by petebacondarwin** [comment]
The `$touched` property is triggered by a `blur` event on the element. Perhaps this is not triggered on ann Android application?

**Comment by petebacondarwin** [comment]
According to this: https://developer.mozilla.org/en-US/docs/Web/Events/blur, the support on mobile devices is "unknown".

**Comment by petebacondarwin** [comment]
Can you try to create a test that reacts directly to a blur event in your IBM Worklight setup?

**Comment by Narretz** [comment]
Closing due to lack of feedback.
