### ISSUE TITLE
'Wire up a Backend' example doesn't work in JSFiddle

### ISSUE THREAD

**Issue by ndjordjevic** [angular/angular.js#11542]
Uncaught Error: Firebase.set failed: First argument contains undefined - firebase.js:32

**Comment by Youdaman** [comment]
The example doesn't seem to work on the home page for Angular either.

**Comment by ndjordjevic** [comment]
Hmmm, I can see the list of projects on the angular home page.

**Comment by Youdaman** [comment]
Try adding one though.

**Comment by gkalpak** [comment]
I think this is an issue for https://github.com/angular/angularjs.org.
Could you reopen there ?

**Comment by ndjordjevic** [comment]
Reopened in angularjs.org repo.
