### ISSUE TITLE
AngularJs Bootstrap Application Dead slow in IE11

### ISSUE THREAD

**Issue by kpalaniy** [angular/angular.js#11543]

**Comment by kpalaniy** [comment]
Can any one help me to resolve this issue?

**Comment by pkozlowski-opensource** [comment]
Please use one of the support channels for those types of questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

If you believe that the perceived slowness is due to a bug in AngularJS, prepare a minimal reproduce scenario using plunker or similar.
