### ISSUE TITLE
$httpBackend coersion of falsy values to null before xhr.send()

### ISSUE THREAD

**Issue by johnhoffman** [angular/angular.js#11552]
Can anyone explain why this line in $httpBackend should coerce falsy values to null?

    xhr.send(post || null);
https://github.com/angular/angular.js/blob/master/src/ng/httpBackend.js#L112

This means that, if I need to POST, PUT, etc. an actual boolean false to a web service, I have to work around AngularJS.

I'd like the line to read something like this:

    xhr.send(post);

or if it just can't be undefined or something:

    xhr.send(isDefined(post) ? post : null);

**Comment by pkozlowski-opensource** [comment]
@johnhoffman I think that your analysis is correct, we are too eager with falsy checks here. Would you be up to sending us a PR. The line to be modified is [this one](https://github.com/angular/angular.js/blob/2a156c2d7ec825ff184480de9aac4b0d7fbd5275/src/ng/httpBackend.js#L112)

**Comment by johnhoffman** [comment]
I've initiated PR https://github.com/angular/angular.js/pull/11567. I had trouble resolving an recurring error while attempting to run the tests on my local machine (```Error: Cannot find module 'es6-symbol'```), so I'm not sure if it will pass the Travis CI check.

**Comment by johnhoffman** [comment]
I've closed https://github.com/angular/angular.js/pull/11567 initiated a new PR https://github.com/angular/angular.js/pull/11582 to get the Travis CI tests to run again (sorry if there was a better way to do this).

**Comment by johnhoffman** [comment]
Last try before trying to dig into what the test results are saying... PR https://github.com/angular/angular.js/pull/11593
