### ISSUE TITLE
$animateProvider.classNameFilter() broken with angular 1.4.0 rc0

### ISSUE THREAD

**Issue by LeleDev** [angular/angular.js#11555]
I'm using the following code to enable ng-animate only for certain elements:
```
.config(function($animateProvider) {
   $animateProvider.classNameFilter(/ng-animation/);
})
```

It was working fine with all the previous angular versions, but with the new rc0 it breaks up everything: all the hidden elements (with ng-hide="true" or ng-show="false") are ALWAYS showing up

**Comment by foglerek** [comment]
Have the same issue. Actually can't get any ngHide/show animations to work in 1.4, the animation just does not happen.

**Comment by matsko** [comment]
@LeleDev @foglerek mind providing a plnkr example? This issue may be caused by #11566.

**Comment by matsko** [comment]
This fix should do it: https://github.com/angular/angular.js/pull/11569

**Comment by adametry** [comment]
For what it's worth, here's a [plnkr example](http://embed.plnkr.co/YWkjmEaHYKNxVm1n074c/preview).
