### ISSUE TITLE
ngPluralize: undefined 'count' fallback

### ISSUE THREAD

**Issue by loicoudot** [angular/angular.js#11556]
It could be handy when 'count' is `null` or `undefined` to have the choice to write something instead of nothing.
 ```
<ng-pluralize count="personCount"
                 when="{'0': 'Nobody is viewing.',
                     'one': '1 person is viewing.',
                     'other': '{} people are viewing.',
                     'undefined': 'Nobody is viewing.'}"> or 'null' or 'default' or ...
</ng-pluralize>
```
The use case i'm blocked with, is optional `input` :  the model is undefined and i still want to write the units after the input because it's an important source of informations (and i don't want to use placeholder here) eg:
`after ____ years`
Actually, when input is empty i see
`after ____`

**Comment by gkalpak** [comment]
There are a couple of ways to achieve this, e.g.:

1. Initialize `personCount` to 0.
2. Change `count="personCount"` to `count="personCount||0"`.

So, considering that:

* There are easy work-arounds/solutions.
* `ngPluralize`'s `count` is designed to expect numeric values.
* `ngPluralize` is possibly going to be deprecated in favor of the more powerful [ngMessageFormat][1].

I would vote for this to be closed as a _won't fix_.

[1]: https://docs.angularjs.org/api/ngMessageFormat

**Comment by loicoudot** [comment]
2 is great solution (sad to not have find this myself)

ok for _won't fix_
