### ISSUE TITLE
ngOptions does not update value when binding to not a child of an object...

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [angular/angular.js#11557]
```html
<select ng-model="example"></select>
```
does not work, whereas :
```html
<select ng-model="data.example"></select>
```
does... I'm just curious about what is going on here ;)

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular.js/wiki/Understanding-Scopes for the explanation on what is going on here.

And please, use a dedicated support channel for general support question like this one: 
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
