### ISSUE TITLE
deregister $on handlers on $destroy

### ISSUE THREAD

**Issue by secrettriangle** [angular/angular.js#11563]
If an event handler is registered like so:
```js
$scope.$on('evt', function () {/* do stuff */});
```

Angular should add the handler to an array internally and deregister it when the scope is destroyed:
```js
$scope.$on('$destroy', function () {
    deregisterFns.forEach(function (deregister) { deregister(); });
});
```

**Comment by nhodges** [comment]
Can you create a plunkr that demonstrates this? It looks like $destroy does this cleanup: https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L873

(I've only recently started familiarizing myself with the AngularJS codebase, so I could be mistaken.)

**Comment by secrettriangle** [comment]
Ah, you're right! Closing.
