### ISSUE TITLE
Migration from 1.3 to 1.4 docs?

### ISSUE THREAD

**Issue by pocesar** [angular/angular.js#11562]
When the compilation of breaking changes and the guide for migrating from 1.3 to 1.4 is coming to the angularjs.org website docs?

**Comment by petebacondarwin** [comment]
They will be in place before we go to full 1.4.0

**Comment by pocesar** [comment]
alright, just asking because I couldn't seen any dates or milestones for it

**Comment by matsko** [comment]
This PR is the basis of the migration log: https://github.com/angular/angular.js/pull/11584

**Comment by petebacondarwin** [comment]
You can now see these migration notes on the angularjs.org site: https://docs.angularjs.org/guide/migration

**Comment by pocesar** [comment]
:+1:
