### ISSUE TITLE
No "PUT" or "PATCH" to update a record

### ISSUE THREAD

**Issue by mattoz0** [angular/angular.js#11571]
https://docs.angularjs.org/api/ngResource/service/$resource

for this to be a true RESTful service it should support PUT/PATCH

This could be implemented using *.$put() and *.$patch() much like the .$save() function

**Comment by adrianconte** [comment]
+1

**Comment by nhodges** [comment]
The semantic "correctness" of PUT vs PATCH is the topic of long, drawn-out debates, which is probably why they aren't default actions. The internals allow for (and test) these methods, so I've just made a PR that includes these as default actions.

**Comment by Narretz** [comment]
There's more discussion here: https://github.com/angular/angular.js/issues/11571 I personally wouldn't hold my breath that this gets included.

**Comment by Narretz** [comment]
Correct issue is https://github.com/angular/angular.js/issues/9807
