### ISSUE TITLE
When using select with ng-repeated options, first option in list is selected if model is populated before options

### ISSUE THREAD

**Issue by garkbit** [angular/angular.js#11583]
As stated in the title, when using ng-repeat with a list of options, like this:

```html
<select ng-model="model">
  <option ng-repeat="option in options" value="{{option.value}}">
    {{option.display}}
  </option>
</select>
```

The select does not show the correct option as selected if the model is populated before the options.

A example illustrating the problem: http://plnkr.co/edit/4edczxmoJzivzON0V7EK?p=preview

This is easily worked around using ng-options, unless there is some specific reason the option tag needs to be used.

**Comment by Narretz** [comment]
This will be fixed in 1.4.6, see http://plnkr.co/edit/xKYSZxp7G7P3NF4ZFOBw?p=preview
