### ISSUE TITLE
Router does not work if ng-view is not defined.

### ISSUE THREAD

**Issue by shuLhan** [angular/angular.js#11586]
#### Overview

The only way to make route to work is to define the "ng-view" attribute.

#### Why is this a bug?

Not every route is to change the view, sometimes developer want to process the content using javascript, for example pagination. When user click "#/page/1" the router load new data while no view is changing.

#### Environment

**Angular version:** 1.3.15
**Angular route version:** 1.3.15
**Browser:** Firefox 37.0.1

#### Step to Reproduce
* Create html file with content below,

```html
<!DOCTYPE html>
<html ng-app="ngApp">
	<head>
		<script type="text/javascript" src="https://code.angularjs.org/1.3.15/angular.js"></script>
		<script type="text/javascript" src="https://code.angularjs.org/1.3.15/angular-route.js"></script>
	</head>

	<body>
		<!-- Uncomment this to let the route working.
		<div ng-view=""></div>
		-->
		<a href="#/page/1">page 1</a>
		<script type="text/javascript">
			var ngApp = angular.module('ngApp', ['ngRoute']);
	
			ngApp
			.config (['$routeProvider',
				function ($routeProvider)
				{
					$routeProvider
						.when ("/page/:pid", {
							template: ""
						,	controller: "UsersPageCtrl"
						})
						.otherwise ({
							redirectTo: "/"
						});
				}
			]);
	
			ngApp
			.controller ('UsersPageCtrl', function ($scope, $routeParams)
			{
				console.log ($routeParams.pid);
			});
		</script>
	</body>
</html>
```
* Open javascript console in browser
* Open the html file in browser.
* Click on link at "page 1"

**Result**: -
**Expected result:** "1"

**Comment by petebacondarwin** [comment]
Hi @shuLhan 

The router is designed to map URLs to views. If you have no `ng-view` then there is no place (i.e. scope) for the router to attach the controller in which you have put the `console.log`.

Moreover, we chose that the router would always have a one-to-one mapping between the URL and the view. So again, it is not in its design to only run code when the URL changes.

If you just want to use the URL to trigger code to run in your application then you should watch the `$location.path()` value.

```js
            ngApp.controller('PaginationController', function($location, $scope) {
              var ctrl = this;
              $scope.$watch(function() {
                return $location.path();
              }, function(path) {
                var match = /\/page\/(.+)/.exec(path);
                if(match) {
                  // Extract the current page
                  ctrl.currentPage = match[1];
                  console.log(ctrl.currentPage);
                } else {
                  // Redirect
                  $location.path('/');
                }
              })
            });
```

See this for a runnable example: http://plnkr.co/edit/ocOKKy9Tas7XPuQBtxn4?p=preview
