### ISSUE TITLE
Contenteditable modelValue when deleting inner html

### ISSUE THREAD

**Issue by Duskfall** [angular/angular.js#11599]
Taken the custom directive from here:
https://docs.angularjs.org/api/ng/type/ngModel.NgModelController
which implements the contenteditable directive,
if we select all contents of the contenteditable and delete them then the $modelValue gets undefined.
$rawModelValue is as normal an empty string.
Shouldn't the $modelValue also be an empty string?

**Comment by Narretz** [comment]
The contenteditable field has the `required` attribute, which means when you empty it, it is invalid, and ngModel will set undefined values to undefined. It's possible to set invalid values with ngModelOptions: https://code.angularjs.org/snapshot/docs/api/ng/directive/ngModelOptions
