### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by higorvaz** [angular/angular.js#11603]
I would like to see the list of supported browsers and the compatibility level for each.
Today I found one service that runs Angular that worked only on Google Chrome bu not on Mozilla Firefox.

Eu gostaria de ver a lista de navegadores compatíveis e o nível de compatibilidade para cada um. 
Hoje encontrei um serviço que roda Angular que funciona apenas com Google Chrome mas não no Mozilla Firefox.

![angular bug 2015-04-15 09_32_41](https://cloud.githubusercontent.com/assets/9384127/7167222/bf8222ac-e389-11e4-98e1-0385b9100dc8.png)

**Comment by pkozlowski-opensource** [comment]
@higorvaz when it comes to the supported browsers what it guaranted is that all the functionality works correctly on the browsers that execute unit tests, currently:

chrome 39
safari 8 (OS X 10.10)
firefox 31
internet explorer 9 (Windows 2008)
internet explorer 10 (Windows 2012)
internet explorer 11 (Windows 8.1)
iphone 8.1 (OS X 10.10)

Other browsers might work but we are not actively testing against them. 

> Today I found one service that runs Angular that worked only on Google Chrome bu not on Mozilla Firefox.

Obviously we can't guarantee anything about the 3rd party modules. Are you referring to a service from the framework itself (in this case this is a bug and you need to provide more details) or some 3rd party service (in this case you need to contact an author of this one).

**Comment by pkozlowski-opensource** [comment]
Closing as I believe I've answered the original question and don't see any further actions on our side.
