### ISSUE TITLE
input[type=number] doesn't respect the scientific notation

### ISSUE THREAD

**Issue by stryju** [angular/angular.js#11602]
Hi.

just today, I came across a weird behavior - angular's `input[type="number"]` directive doesn't see scientific number notation (like `1e2`) as a valid one, despite the fact, that browsers do.

is that on purpose?

**Comment by Narretz** [comment]
Do you mean when setting on the model or in the input?

**Comment by stryju** [comment]
input

**Comment by stryju** [comment]
screenshots of failed validation - just to confirm that it works:

- ![invalid value](https://cloud.githubusercontent.com/assets/25367/7252851/8d668318-e838-11e4-9bd4-af954f0ceda6.png)
- ![empty value](https://cloud.githubusercontent.com/assets/25367/7252850/8d668264-e838-11e4-89a1-c2edc521f693.png)

**Comment by RogerJFX** [comment]
Simply change angular.js as a workaround, until it is fixed. It works for me. By the way this might already be some kind of fix. Maybe a '+' is missing, if someone wants to write e.g. 1E+12

    var NUMBER_REGEXP = /^\s*(\-|\+)?(\d+|(\d*(\.\d*)))([eE]+[-]?\d+)?\s*$/;

**Comment by Narretz** [comment]
@RogerJFX would you mind sending a PR with this change and a test for it?

**Comment by RogerJFX** [comment]
Ok, I can do this. Anyways one issue will remain. Current browsers can not interpret the step attribute of input[type="number"], if value is in scientific notation, but not step and vice versa. 
So anything like this
        \<input type="number" step="1" value="1e2" /\>
will not work as expected.
As far as I remember, all browser fail here.

**Comment by stryju** [comment]
works in chrome - converts to "normal" notation tho

**Comment by Narretz** [comment]
fixed in https://github.com/angular/angular.js/commit/ebd0fbba8ff90bee0cd016d574643d56a7f81ed0

**Comment by zvuv** [comment]
the trick seems to be to add the decimal point.     1.0e-7   seems to work on most browsers
