### ISSUE TITLE
ngAnimate: lookUpAnimations function breaks if CSS class is an Array.prototype function name.

### ISSUE THREAD

**Issue by rvignacio** [angular/angular.js#11619]
Hello, I'm having a problem with the lookUpAnimations function in [src/ngAnimate/animateJs.js](https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateJs.js#L236). It iterates over the CSS classes of the element and gets the [registered animation provider](https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateJs.js#L241):

```javascript
// Extract from src/ngAnimate/animateJs.js#L241
var klass = classes[i],
    animationFactory = $animateProvider.$$registeredAnimations[klass];
if (animationFactory && !flagMap[klass]) {
  matches.push($injector.get(animationFactory));
  flagMap[klass] = true;
}
```
My element has a CSS class named "filter" so, when doing:
`animationFactory = $animateProvider.$$registeredAnimations[klass];`
the `animationFactory` variable ends up being a reference to `Array.prototype.filter` (because `$$registeredAnimations` [is of type Array](https://github.com/angular/angular.js/blob/master/src/ng/animate.js#L166)). After that, I got an unknown provider exception because it calls `$injector.get()` with the filter function.

I already changed the CSS class, but shouldn't $$registeredAnimations be just a plain object (like Object.create(null)) instead of an Array if it's going to be used that way?

Thoughts?

**Comment by nicoabie** [comment]
@matsko is the guru of the animations, he will help us out!

**Comment by matsko** [comment]
This is fixed now. Thank you for pointing this out.

**Comment by rvignacio** [comment]
You're welcome, thanks for the quick fix!
