### ISSUE TITLE
Error: [$rootScope:infdig]  http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10 ...

### ISSUE THREAD

**Issue by hjzheng** [angular/angular.js#11610]
The error happened when I  sort table. 
the example: http://jsfiddle.net/hjzheng/oww0b4ws/
Please help me and give some better solution for the example.

**Comment by Narretz** [comment]
Github is only for bugs and feature requests; please direct support questions to these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
