### ISSUE TITLE
Exception when using "watch" as isolated scope binding variable in Firefox

### ISSUE THREAD

**Issue by randing89** [angular/angular.js#11627]
Firefox throws "Error: can't convert undefined to object" exception when using "watch" as a isolated scope binding.
Reproduced in Firefox 35 and Angular 1.4.0-rc.0

See: http://plnkr.co/edit/Hu8t5THUimqXJBZ2BusM?p=preview

**Comment by lgalfaso** [comment]
landed as a6339d30d1379689da5eec9647a953f64821f8b0
