### ISSUE TITLE
"Referencing DOM nodes" error for non-DOM node

### ISSUE THREAD

**Issue by Falci** [angular/angular.js#11629]
If you create an object with ```nodeName``` and ```children``` propeties, and try use as view function args, Angular will throw a ```Referencing DOM nodes in Angular expressions is disallowed!``` error.

[Plunker example](http://plnkr.co/edit/O2HSQqd20OahnxQFQNfb?p=preview)

All content that I can find about this error is about coffee script problem.. returning DOM. But it's not the case.

**Comment by Narretz** [comment]
This is a security feature. I am not sure if it's possible / feasible for the parser to check that the context is not actually a DOM node. Maybe @caitp or @lgalfaso can say.

**Comment by caitp** [comment]
in general, no matter what we do it's possible for there to be false positives and false negatives, that's the nature of ECMAScript.

In general, all DOM nodes should inherit from `Node`, so we could do an `instanceof` check --- but this breaks when nodes originate from a different context. We could also check `getOwnPropertyDescriptor` to make sure that `nodeType` and `nodeName` are accessor functions, but this is a performance cost and still has the potential for false negatives.

Realistically, I don't think there's much we can do about this except maybe add some additional properties to test.

**Comment by Narretz** [comment]
> Realistically, I don't think there's much we can do about this except maybe add some additional properties to test.

@caitp Do you mean unit tests or tests inside the parser? I agree that additional checks that impair performance are not worth it.

**Comment by caitp** [comment]
tests as in "we are testing the presence of these properties to determine that this is a Node", not "unit testing"

**Comment by gkalpak** [comment]
Currently (v1.5.x) we only check for `nodeName`. Although this is quite strict (assuming that a `nodeName` property means DOM node), changing the check would be a (security related) BC. Besides, as @caitp mentioned, there is no reliable way to detect this, so I think it's better to stay on the safe side here.

Maybe we should add a notice/known issue in the docs.

**Comment by gkalpak** [comment]
Thinking about it again, I don't think there is any real security concern with adding extra checks (as long as we can come-up with cross-browser properties to check). Typically, it would still be a BC though.

I'm going to add it to the ice-box, but if anyone feels like submitting a PR, please do :smiley:

**Comment by Narretz** [comment]
This error has just been removed via the expression sandbox removal. That means in 1.6 you should be able to use the object with these properties.
