### ISSUE TITLE
$http request on data

### ISSUE THREAD

**Issue by leibale** [angular/angular.js#11625]
catch returns data batch after batch
```javascript
$http.post('/any/path/').on('data', function (data) {
  console.log(data);
});
```
or
```javascript
$http.post('/any/path/').data(function (data) {
  console.log(data);
});
```

thanks

**Comment by Narretz** [comment]
It's not clear what the issue is here. Please direct support questions to one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem 
If you have found a bug or want a feature, please add more information.
Thanks!

**Comment by leibale** [comment]
polling data.. when the server write any data and not close the connection
