### ISSUE TITLE
ngModel is not correctly updated in Internet Explorer

### ISSUE THREAD

**Issue by aartek** [angular/angular.js#11634]
Hello, I have found strange issue with input and ngModel. I try to update ngModel of input manually 
(by using ngModel.$setViewValue) but in IE  it is changed only for some milliseconds and then it is overridden with current elem value (with typed string).

The problem occurs only with Angular 1.3 in Internet Explorer 11. It works fine with Angular 1.2 on every browser and with AngularJS 1.3 in Firefox and Chrome 

Problematic code:

	app.directive('myInput',function(){
		return{
			restrict: 'A',
			require: 'ngModel',
			scope: {},
			priority: 1,
			link: function(scope, elem, attrs, ngModel){
				elem.off('input');
				elem.off('change');

				ngModel.$render = function(){
					var model = {
						'sampleData': 'sampleData',
						value: ''
					}                                   
					ngModel.$setViewValue(model);
					elem.val(model.value);
				}

				elem.on('input', function(){
				   var val = elem.val();
					ngModel.$setViewValue({
						'sampleData': new Date().getTime(),
						value: val
					});
					scope.$apply();
				});
			}
		}
	});

Examples: 
AngularJS 1.2: http://jsfiddle.net/aartek/e6Lvpqj3/ (works in IE, Chrome, and Firefox),

AngularJS 1.3: http://jsfiddle.net/aartek/mvx9dbyu/2/ (doesn't work in IE, works in Chrome and Firefox)

**Comment by Narretz** [comment]
You are really not supposed to use `setViewValue` this way. 
1) When you are deregistering the default listeners, you are disconnecting the original setViewValue from functions such as commitViewValue etc.
2) $render should never call setViewValue, only write the value into the control

Whats your use case for this?

**Comment by aartek** [comment]
Thanks for your answer. As I think, I should use `$formatters` and `$parsers` instead of `setViewValue` in `$render` method and I shouldn't remove the event handlers. I've updated my code but I still have one problem.

My case is to build suggestions directive, which keeps selected `object` in `ngModel`. 
The problem is that if I don't remove the `change` event handler, parser function is called twice - first time with `object` as an value and second time with the `string`. This causes that my model is set to `string` because `string` value comes later.

I can fix this behavior by:
- using `elem.off('change')` - but as you said, it is not good idea to turn off default events
- wrapping `$setViewValue` with `$timeout` - but for me it rather looks like a hack than a correct solution.

So the question is - what is the correct way to achieve my goal?

Here is my updated code: http://jsfiddle.net/aartek/5ujgor91/ (it uses `autocomplete` component from uikit framework, wrapped with my directive). To see the difference in behavior just comment `elem.off('change')` in 56 line.


(According to my first post, whether or not I was doing it right, it's not good when the same code works in another way in different browsers. I've also found a solution for my problem. It is removing `keydown` handler with `elem.off('keydown')` - [source](http://stackoverflow.com/questions/29698836/ngmodel-is-not-correctly-updated-in-internet-explorer-angularjs-1-3))

**Comment by Narretz** [comment]
Sorry, I never got back to you. I'll guess you've solved your problem one way or the other.
Still, I just wanted to explain how this could be done better.
First, it's important to note that you should only call $setViewValue for an input element with the value that is currently your actual DOM value. You should then use a $parser to transform this value to whatever you need.
I updated your example to reflect that: it now simply caches the last autocomplete value and the $parser accesses it: http://jsfiddle.net/3o7ghmL4/

**Comment by aartek** [comment]
Thanks it helped a lot. It works great but what if I need to store only one property of selected data as an ngModel? 
For example after selecting item I would like to set its `short` property as a`ngModel.$modelValue`. I know I have to return this property in parser (`return lastAutoCompleteVal.short`), but there is a problem on first run. To fill my input I need to pass an object with properties `{short: 'LV', value: 'Las Vegas'}`  (`value` will be displayed in input field and `short` should be `$modelValue`), but on the first run `$modelValue` is the whole object. So what is the correct way to make the conversion? Formatter only sets `$viewValue`, and parser won't be run until I call `ngModel.$setViewValue`. But I don't know where should I call it (you said I shouldn't do it in $render).  (Also I'd like to do it without creating isolated scope and setting watch)

Scenario:
In contoller I set the model:

    model = {"value": "Las Vegas", "short": "LV"}

formatter do its job and sets following values:

    ngModel.$viewValue = "Las Vegas";
    ngModel.$modelValue = {"value": "Las Vegas", "short": "LV"} 

But `$modelValue` should be `"LV"`
