### ISSUE TITLE
ng-submit on ng-form

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#11639]
Is there a reason that ng-submit cannot work on an ng-form? If there's interest, I would happily work on integrating my solution into angular core: https://gist.github.com/kentcdodds/47c76d3e579ae10b9c2d

(obviously, my solution is a little specific to my use case, but could easily be altered to be more general).

Let me know if I'm missing some reason why this is a bad idea. If not, I can create a PR to do it.

**Comment by Narretz** [comment]
I think the main reason is that `ng-form` should only be used for nesting forms, though I know that it has other applications.
The basic problem with providing all functionality of a native form inside an ng-form is that it must work to spec, and while it's probably not impossible, it'll add a lot of code that is not useful for the majority of developers.
So if there was a 3rd party module for that which integrates well with forms, that would be ideal  imo.

**Comment by kentcdodds** [comment]
Thanks for the response. Maybe I'll make a small lib that does this for people who want the functionality. Thanks!
