### ISSUE TITLE
Tree structure construction is breaking( problem with $digest()) 

### ISSUE THREAD

**Issue by Venkata-Kolla** [angular/angular.js#11630]
We are constructing a tree structure using ng-repeat, for this we are making visual force remote action call to get some large(11000 records) Json data from the back end ,Once we get the data we are binding to scope variable by calling $scope.$apply() to let angular know about this model object(scope variable) change,when $scope.$apply method is called my page is taking too long and even breaking after sometime at $rootscope.$digest() (which is in $apply())...
Any suggestions ?

**Comment by frfancha** [comment]
$http which is used to retrieve your JSON data will call the digest for you after retrieval.
You don't need to (and may not infact) call $apply yourself in this case.

**Comment by Narretz** [comment]
This is more of a support question, so please use the IRC, Google Groups or Stackoverflow. Thanks!
