### ISSUE TITLE
Allow ng-trim to work on password inputs

### ISSUE THREAD

**Issue by miraage** [angular/angular.js#11632]
Would be great to see password inputs being affected by trim, for example

```html
<!-- no trim -->
<input type="password" ng-model="data.password"> 
<!-- trim -->
<input type="password" ng-model="data-password" ng-trim="true">
```

**Comment by frfancha** [comment]
As passwords can contain white space, this is a very bad idea

**Comment by miraage** [comment]
Maybe yes.
I love to use whitespace and special characters in my passwords. :confused:

**Comment by frfancha** [comment]
Love it or not, this is often enforced by company rules.

**Comment by Narretz** [comment]
This was specifically changed to not work with trim here: https://github.com/angular/angular.js/commit/a7fb357fa122e0a056ce1de838a2dfaf1ebc2953 The commit message is misleading: ngTrim will never trim passwords. I don't see a compelling reason to change this back, but I'll keep it open for further comments.

**Comment by miraage** [comment]
I agree, that in most cases password should be trimmed, but not so rarely we have to allow user to use password that he wants.

**Comment by gkalpak** [comment]
I don't think that trimming a password is ever a good idea.

**Comment by miraage** [comment]
Updated topic. Sorry, I wrote the wrong code. :cry:

**Comment by lgalfaso** [comment]
I have to agree with all the ones that claim that trimming inputs of type password is a bad idea. Closing
