### ISSUE TITLE
set Header incorrect in $http

### ISSUE THREAD

**Issue by 21paradox** [angular/angular.js#11641]
I want to send the request without returning 304 when user refresh.
Also i need to cache the current request when hash change.

I configure like this.

```javascript
 $http.defaults.headers.common['Cache-Control'] = 'no-cache';
 $http.defaults.headers.common['If-Modified-Since'] = 'Mon, 26 Jul 1997 05:00:00 GMT';
```

But after that request can not be send.
Reproduced here:

http://plnkr.co/edit/M5iZjr5MurgXbQiU0I16?p=preview

**Comment by pkozlowski-opensource** [comment]
@21paradox the request fails since https://api.github.com/repos doesn't allow `Cache-Control` headers in their CORS configuration. The exact error is:

> XMLHttpRequest cannot load https://api.github.com/repos/vmg/redcarpet/issues?state=closed. Request header field Cache-Control is not allowed by Access-Control-Allow-Headers.

This is about github servers configuration and has nothing to do with AngularJS.

**Comment by 21paradox** [comment]
@pkozlowski-opensource Thanks for the response!
This is indeed **not  AngularJS's issue**. 

Finally i can up with solution.
```javascript
        app.config(['$httpProvider', function($httpProvider) {
            $httpProvider.interceptors.push('noCacheInterceptor');
        }])

        .factory('noCacheInterceptor', function () {

            var current = new Date().getTime();
            return {
                request: function (config) {
                    if(config.method=='GET'){
                        var separator = config.url.indexOf('?') === -1 ? '?' : '&';
                        config.url = config.url + separator + 'noCache=' + current;
                    }
                    return config;
                }
            };
        })

```
This is inspired by http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http#19771501

Just need to add another static timestamp and will work just fine now.

If any body have the same problem's about prevent cache when refresh, you can do something like this.
