### ISSUE TITLE
ng-route + web-components crashes Chrome

### ISSUE THREAD

**Issue by mskrajnowski** [angular/angular.js#11654]
Chrome tab crashes during `ng-repeat` compilation when:
- it's content includes a custom element, which has `@import` inside it's shadow's inline styles
- it's inside a `ng-route` template

Example:

```html
<!DOCTYPE html>
<html>
<body ng-app="app">
  <ng-view></ng-view>

  <template id='my-component-template'>
    <style>
      @import url('whatever...');
    </style>
  </template>

  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-route.js"></script>

  <script>
    function MyComponent() {}
    MyComponent.prototype = Object.create(HTMLElement.prototype);
    MyComponent.prototype.createdCallback = function() {
      var template = document.getElementById('my-component-template');
      var clone = document.importNode(template.content, true);

      var shadow = this.createShadowRoot();
      shadow.appendChild(clone); // this line crashes Chrome 42.0.2311.90
    };

    document.registerElement('my-component', MyComponent);

    angular
    .module('app', ['ngRoute'])
    .config(function($routeProvider) {
      $routeProvider.otherwise({
        template: '<div ng-repeat="item in list"><my-component></my-component></div>'
      });
    });
  </script>
</body>
</html>
```
[gist](https://gist.github.com/mskrajnowski/81ca99c080020b27e1bb) | [output](https://rawgit.com/mskrajnowski/81ca99c080020b27e1bb/raw/7c6a97a70cecaa92f1df7c9efeda29c5251e9226/ng-route-web-components-crash.html)

Angular 1.3.15
Chrome 42.0.2311.90 (64-bit)
Ubuntu Linux 14.10 64-bit

I'm almost sure it's a [Chrome (42.0.2311.90) bug](https://code.google.com/p/chromium/issues/detail?id=478699), but since it manifests itself when using angular, I've decided to report it here too.

**Comment by petebacondarwin** [comment]
@mskrajnowski - the link to the Chrome issue fails with a 403 forbidden error for me. Any idea why?
@caitp - any thoughts one what is causing this?

**Comment by petebacondarwin** [comment]
The actual explosion occurs on this line:

https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L2501

```js
parent.replaceChild(newNode, firstElementToRemove);
```

where `newNode` is the `ng-repeat` comment and `firstElementToRemove` is the WebComponent

**Comment by caitp** [comment]
Re: the 403, It's most likely been deemed sec-critical and marked private (@google.com/@chromium.org only) to prevent it from being abused by authors who stumble upon it. But that's just a guess.

As for what's causing it, probably a bug.  The good news is I can't reproduce this in M45

**Comment by petebacondarwin** [comment]
OK, so this is not a bug, per se, with Angular as I can reproduce it without Angular loaded.
See https://gist.github.com/petebacondarwin/442f842b6a49d76dbcf5

```html
<!DOCTYPE html>
<html>
<body>
  
  <template id='my-component-template'>
    <style>
      @import url('whatever...');
    </style>
  </template>
 
  <div id="parent"><my-component></my-component></div>
 
  <script>
    function MyComponent() {}
    MyComponent.prototype = Object.create(HTMLElement.prototype);
    MyComponent.prototype.createdCallback = function() {
      var template = document.getElementById('my-component-template');
      var clone = document.importNode(template.content, true);

      var shadow = this.createShadowRoot();
      shadow.appendChild(clone); // this line crashes Chrome 42.0.2311.90
    };

    document.registerElement('my-component', MyComponent);

    var parent = document.getElementById('parent');
    var webComponent = parent.firstElementChild;
    var newNode = document.createElement('div');
    parent.replaceChild(newNode, webComponent);

  </script>
</body>
</html>
```
