### ISSUE TITLE
losing textbox value while postback

### ISSUE THREAD

**Issue by rajgaikwad008** [angular/angular.js#11655]
hi,
I am using AngularJS with asp.net.
Please see the below code:
" <div data-ng-app="">
        <asp:TextBox ID="txtName" runat="server" data-ng-model="name"></asp:TextBox>
        <p>{{name}}</p>
    </div>"

but when page gets postback, value in the textbox is getting cleared.
if I remove "data-ng-model" then I am getting the value on postback.
Please help me.

Regards,
Rajkumar

**Comment by Narretz** [comment]
Please direct support questions to one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem Thanks!
