### ISSUE TITLE
angular.copy does not update input box value immediately

### ISSUE THREAD

**Issue by spyalert01** [angular/angular.js#11666]
Hi, 
I have a sample code : http://codepen.io/anon/pen/PqYdqm
after I angular.copy $scope of input from source, to $scope of input at desitincation 
//  $scope.ship = angular.copy($scope.bill); <- like this
I tried to get the value of input box using $('#inputid').val(), it doesn't get the latest value, in fact, It only get the previous value.

I need the inputid.val values updated instantly.

I know timeout can solve the problem, but it is not an ideal solution because we don't know when we need to use timeout, and when we don't need to use timeout.

Please help.

**Comment by pkozlowski-opensource** [comment]
@spyalert01 I'm not sure what you are trying to do but this is _not_ how AngularJS is supposed to work - the whole point of the framework is to focus on the model and DOM manipulation is a big no-no. You could simply do: http://codepen.io/anon/pen/KpKKNa

In any case this is a basic learning / support question and as such should be asked using a dedicated support channel:  https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
