### ISSUE TITLE
ngAnimate breaks ngShow/ngHide when $animateProvider.classNameFilter is used

### ISSUE THREAD

**Issue by jsdw** [angular/angular.js#11664]
Hello,

This problem happens angular 1.4.0.rc0 (but not in beta6).

Upon upgrading, I noticed that all of my ngShow/ngHide directives were broken. I tracked it down to the ngAnimate module; either removing the module from the dependency list entirely, or removing this line in my code:

```
$animateProvider.classNameFilter(/\s+animate\s+/);
```

Seems to fix the problem. 

I am assuming it arose in the recent $animate refactor, as a result of the fact that $animate.addClass/removeClass are used by ngShow/Hide and at a guess, the classNameFilter might prevent them from actually performing the add/remove.

I would consider this to be quite a serious regression. Sorry I have no plunkr example as yet!

**Comment by jsdw** [comment]
I believe the problem is line 2022 of angular-0animate.js (1.4.0.rc0)

removing this if statement makes things work again, so I suspect it should be bypassed in select cases.

**Comment by gkalpak** [comment]
There have been several fixes to `ngAnimate` since `1.4.0-rc.0`.
Can you check if the problem still exists using the latest code from master:

-  https://code.angularjs.org/snapshot/angular.js
-  https://code.angularjs.org/snapshot/angular-animate.js

**Comment by jsdw** [comment]
Seems to be fixed in those snapshots, thanks :)
