### ISSUE TITLE
Can we change url without reload the page ?

### ISSUE THREAD

**Issue by MartelBenjamin** [angular/angular.js#11663]
Hi everyone,

I have an app with jquery for changing url without reloading ( with history pushstate) but i want to do it with angularJS and i don't know how to do.
I want do change because i have a problem, when i click on a button i change images on my page and the url but if i reclick on it i lost the link of images ... bad for me.

So my question is : is it possible that we can change url without reloading the page ? 

Ben

**Comment by pkozlowski-opensource** [comment]
Nope, it is not currently possible, see https://github.com/angular/angular.js/issues/1699
Vote / add your use-case to the referenced issue, please.

Closing as duplicate.
