### ISSUE TITLE
add caller line to console when used $log

### ISSUE THREAD

**Issue by leonardopaiva** [angular/angular.js#11660]
Hello, i would like to see the line calling my $log.warn() on console. Currently it show the angular line, 

Example:

calling $log.warn('page not found!') from my script on line 10, will result on:
"Page not found" angular.js:11602

i would like to see:
"Page not found" myscript.js:10

I'm sorry if I was not clear enough, thanks.

**Comment by petebacondarwin** [comment]
The easiest solution is to blackbox the angular.js code. See https://gist.github.com/paulirish/c307a5a585ddbcc17242

**Comment by wesleycho** [comment]
There is nothing really to be done in Angular for this, [this isn't possible](http://stackoverflow.com/a/32928812).

This should probably be closed.

**Comment by gkalpak** [comment]
I agree that there is no way we can do this and still retain our custom error formatting.
Considering there are easy workarounds available (e.g. https://github.com/angular/angular.js/issues/11660#issuecomment-96639550 or using `console` directly or overwriting `$log` etc), I'm going to close this as won't fix (for now :smiley:).
