### ISSUE TITLE
memory leak (Chrome only) in unit tests when upgrading to > 1.3.beta18

### ISSUE THREAD

**Issue by ffesseler** [angular/angular.js#11679]
We have an app that use angular 1.2.26 and we'd like to upgrade to 1.3.15.
When switching to 1.3.15, our test suite (3000 tests) slows down a lot and makes Chrome crash after a while.

After investigation, the suite slows down when the memory consumption reaches 1.5GB.
With the 1.2 version, it never goes over 1.0GB.

Another thing : The test suite work well until angular 1.3.0-beta18. All newer versions have the problem.

**Comment by wesleycho** [comment]
This requires more information, as there is nothing actionable based on what is said so far.

**Comment by Narretz** [comment]
Closing due to lack of response. Feel free to reopen with more information.

**Comment by rvignacio** [comment]
@Narretz, @wesleycho, I'm having the same issue with PhantomJS, the memory consumption steadily grows after each test which leads me to think that something isn't being reclaimed by the garbage collector. Any ideas about how to look for this and submit a report?
Thanks,

**Comment by rodoabad** [comment]
@rvignacio what test framework are you using?

**Comment by rvignacio** [comment]
@rodoabad, just for the record, I was using Karma with Jasmine 2.x. But I've moved on with that project and haven't had that problem with others.
