### ISSUE TITLE
Directive: Pass data by element attribute, the attribute name starts with "x", the second character is uppercase

### ISSUE THREAD

**Issue by jasonjifly** [angular/angular.js#11687]
When we create a directive like the following way, scope.xA is always undefined, I found that the rule is when define an attribute starts with "x" and followed with an uppercase character, this attribute can never get data, maybe this is a bug(my version is v1.3.15):
html:
```
<my-chart x-a="99"></my-chart>
```
javascript:
```
       .directive("myChart", function() {
         console.log("Directive is invoked");
         function link(scope) {
             console.log(scope);
             //scope.xA is undefined
             console.log(scope.xA);
         }

        return {
            restrict: "E",
            link: link,
            scope: {
                xA: "="
            },
            replace: true,
            template: "<div></div>"
        }
    });
```

**Comment by ganarajpr** [comment]
This is expected behaviour in angular. 

See https://docs.angularjs.org/guide/directive#normalization

> Strip x- and data- from the front of the element/attributes.

**Comment by gkalpak** [comment]
As a sidenote, if you still want to use such a property name, you have to prepend the attribute with `x-` or `data`; e.g.: `<my-chart data-x-a="99"></my-chart>`

**Comment by jasonjifly** [comment]
Oh, got it. Thank you very much though I'm still curious why angular strip "x-" from the front of the attributes.
