### ISSUE TITLE
Angular factory service getting instantiated every time view changes. 

### ISSUE THREAD

**Issue by bsamudrala** [angular/angular.js#11682]
Hello,

I was under assumption that services are singleton which intialized per app but for i see its loading every time i refresh the view or change to diferent view. Here is code i used angular .js. I'm using angular js with MVC 5

(function () {
    var app = angular.module('MyStore', []).service('cartService', function () {

        console.log('inside service');
        
        var cartItems = [];
        
        this.addCartItem = function (newitem) {
                cartItems.push(newitem);
                console.log(cartItems);
            };

        this.getShoppingCartItems = function () {
                console.log(cartItems);
                return cartItems;
            };
    });

    app.controller('CartController', ['$scope', 'cartService', function ($scope, cartService) {
        $scope.cartItems = cartService.getShoppingCartItems();
        
    }]);

    app.controller('ProductController', ['$scope', 'cartService', function ($scope, cartService) {
        $scope.cartItems = cartService.getShoppingCartItems();

        $scope.addToShoppingCart = function (id, name, price, qty) {
            var newitem = { id: id, name: name, price: price, quantity: qty };
            cartService.addCartItem(newitem);
           
        };

        $scope.products = [];

        $scope.products.push({ id: 1, name: 'G1', price: 2.85, description: 'description for G1' });
        $scope.products.push({ id: 2, name: 'G2', price: 5.85, description: 'description for G2' });
        $scope.products.push({ id: 3, name: 'G3', price: 5.85, description: 'description for G3' });

     
        
    }]);
        
  
})();

**Comment by pkozlowski-opensource** [comment]
Could you please narrow it down and put a live reproduce scenario using http://plnkr.co/edit/?p=preview or similar? I think that you are wrongly interpreting what you are seeing... but it is hard to be sure without a live reproduce scenario.

**Comment by bsamudrala** [comment]
I have uploaded just the products page with required scripts. So when i open javascript console and click add to cart on products i see the array product items in console and once i refresh the page array is reset to empty. Not sure if this issue is related using mvc with angular JS

http://plnkr.co/edit/mD4jT8ItqgB0MqRMAFt1?p=preview\

**Comment by lgalfaso** [comment]
Hi,
  After looking at the plunker, I find that what @pkozlowski-opensource mention is right. You are misinterpreting your observations. I am closing this issue, and recommend that you ask this question in a support forum.
