### ISSUE TITLE
returning anything from a controller breaks controllerAs (1.4 only)

### ISSUE THREAD

**Issue by purge** [angular/angular.js#11683]
Previously, this was ok but using 1.4-rc.0 the return value causes any bindings in the controller to fail. See https://jsfiddle.net/purge/8vjpgm3h/1/
This is particularly a problem for coffeescript which automatically returns the last statement.

**Comment by purge** [comment]
Ah, this is to do with https://github.com/angular/angular.js/pull/10502 so it is a breaking change and should probably be mentioned in the upgrade guide.

**Comment by petebacondarwin** [comment]
@purge - I don't see the problem in your fiddle - you are not returning anything from either controller. What you are doing is trying to attach two directives that define a new scope to a single element, which does not work.

**Comment by purge** [comment]
@petebacondarwin sorry, for some reason the fiddle has been reset to the one that was forked - see a proper example of the issue here:
https://jsfiddle.net/purge/8vjpgm3h/1/
Thanks

**Comment by caitp** [comment]
@purge it's working 100% correctly there. here's a clearer example: https://jsfiddle.net/z65qqtu7/
