### ISSUE TITLE
element.data('$isolateScopeNoTemplate') undefined if $compileProvider.debugInfoEnabled(false)

### ISSUE THREAD

**Issue by motiejuss** [angular/angular.js#11691]
If I disable debuginfo, I can't access `element.data('$isolateScopeNoTemplate')` anymore. 

Angular 1.3.4

**Comment by gkalpak** [comment]
This by design (I think). You shouldn't access that for anything but debugging purposes (which you can still do using [`angular.reloadWithDebugInfo`][1]).

[1]: https://docs.angularjs.org/api/ng/function/angular.reloadWithDebugInfo
