### ISSUE TITLE
1.4 directive is not refreshing after redirect

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular.js#11707]
Hello,

i have another issue with 1.4. Am not sure if this is issue or this is new 1.4 behavior.
Scenario: 
i have a button click in firs screen 
```
addMessage = () => {
        var test: ISpaGlobalMessage = {
            messageType: SpaGlobalMessageType.Error,
            text: 'test message'
    }

        this.$spaGlobalMessages.add(test);
    }

    testClick = () => {
        this.addMessage();
        this.$state.go(impStates.login.login);
    }
```

$spaGlobalMessages is service and store messages in array nothing fancy.

Also i have directive wich responsable for showing those messages (will paste only code that matters):

```
 template: string = 'messages from directive: {{globalMessages[0].text}}

controller: 
if ($scope.globalMessages == null) {
            $scope.globalMessages = <ISpaGlobalMessage[]>[];
        }

$scope.$on('globalMessageAdded', () => {
            $scope.globalMessages = $spaGlobalMessages.getMessages();
        });
```

When i press button in screen 1 and redirect to screen 2 $scope.globalMessages is not empty but they are not shown in template. (This used to work with AngularJs 1.3). Debugger shows that $scope.globalMessages contains one message (the one i have added in screen one before redirect and it is not empty because just before redirection it was shown in screen 1 because of $scope.$on - since directive is singleton $scope transfers to screen 2 after redirection). 

And it fails to work until I add this line to controller:

```
$scope.globalMessages = $spaGlobalMessages.getMessages();
```

which basically creates I dont know what, local scope variable maybe??? But why:
1) It worked in 1.3.0
2) Debuger shows that $scope.globalMessages is not empty

Also if I add button to the same screen it works perfectly without that line.

**Comment by pkozlowski-opensource** [comment]
@vytautas-pranskunas- could you please provide a plunker with a minimal reproduce scenario? It would be much easier to understand what is going on, determine if this is a bug and fix it eventually. Thnx!

**Comment by vytautas-pranskunas-** [comment]
Amm dont think i have time for this :( sry
But basic idea is very simple. As far as directive is singleton and is injected into page 1 and 2. 
1) Add value to directive scope in page 1
2) Redirect to page 2
3) Same directive is not showing added value on page 2

**Comment by matthiasg** [comment]
i created a plunkr but it does not show the error: http://plnkr.co/edit/tBth2b?p=preview

did i understand this issue correctly @vytautas-pranskunas-  ?

directives get new scopes whenever they are instantiated, e.g. upon navigation. shared state would have to be kept outside (e.g in a service) and that works in my plunkr

**Comment by vytautas-pranskunas-** [comment]
Can you replace ngRouter wit ui.router? after if it will still work i will fork and trye to modify the code one to one scenario as i have

**Comment by vytautas-pranskunas-** [comment]
I was playing around with your example:
Added controller as syntax, add storing sharedValue in $rootScope (my case), then accessing it in directive directly {{storedValue}} without invoking getSharedValue and cannot reproduce issue.

In my case service stores value in $rootScope and after redirecting to another view debugger sees that value ($scope.sharedValue) but directive template {{sharedValue}} does not render anything.

If you can only add ui.router to your example so i can play around and see maybe this causes that bug

**Comment by matthiasg** [comment]
@vytautas-pranskunas-  I updated it to use ui-router and it  works for me -- http://plnkr.co/edit/tBth2b?p=preview

http://plnkr.co/edit/tBth2b?p=preview

Dont forget that all controllers are rebuilt on navigation though, if you removed line 10 from the plunkr it would always reset the root variable after each navigation for example.

**Comment by vytautas-pranskunas-** [comment]
Line 10 in which file? 
I think it may be because of lazy loading. But logically when controller lazy loaded it is registered to angular and is not loading any more so second time rootScope should not be reset.
Hmm seems like it is our system issue and i will solve it other ways. 
We can close this ticket. 
Thanks for your time.

**Comment by matthiasg** [comment]
In Module.js the if statement that initiates the shared variable

Von meinem Windows Phone gesendet

-----Original Message-----
