### ISSUE TITLE
 (bug) Problems running tests - toThrow() need not be implemented in matchers.js

### ISSUE THREAD

**Issue by dmitriz** [angular/angular.js#11705]
Running `grunt autotest` throws this error:
```
Chrome 42.0.2311 (Mac OS X 10.8.5) ERROR
  Uncaught TypeError: Cannot set property 'toThrow' of undefined
  at /Users/dmitrizaitsev/Repos/angular.js/test/helpers/matchers.js:236
```

From `/Users/dmitrizaitsev/Repos/angular.js/test/helpers/matchers.js:236`:

```js
// TODO(vojta): remove this once Jasmine in Karma gets updated
// https://github.com/pivotal/jasmine/blob/c40b64a24c607596fa7488f2a0ddb98d063c872a/src/core/Matchers.js#L217-L246
// This toThrow supports RegExps.
jasmine.Matchers.prototype.toThrow = function(expected) {
  ...
```

`jasmine.Matchers` is  **deprecated** and the matcher `toThrow()` is [included in Jasmine 1.3](http://jasmine.github.io/1.3/introduction.html), so need not be implemented:

https://github.com/jasmine/jasmine/commit/c40b64a24c607596fa7488f2a0ddb98d063c872a

**Comment by petebacondarwin** [comment]
I cannot reproduce this problem locally. Are you trying to use a different version of karma-jasmine than specified in our package.json (0.1.5)?

**Comment by dmitriz** [comment]
Yes, the version is correct:

<pre>
npm ls karma-jasmine -d
npm info it worked if it ends with ok
npm info using npm@2.7.4
npm info using node@v0.12.2
angularjs@ /Users/dmitrizaitsev/Repos/angular.js
└── karma-jasmine@0.1.5 
</pre>

Still the same test errors:

<pre>
karma start karma-jqlite.conf.js 
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 42.0.2311 (Mac OS X 10.8.5)]: Connected on socket USVGzZS1Ha2uEYlhCt9y with id 89236372
Chrome 42.0.2311 (Mac OS X 10.8.5) ERROR
  Uncaught TypeError: Cannot read property 'prototype' of undefined
  at /Users/dmitrizaitsev/Repos/angular.js/test/helpers/matchers.js:236
</pref>

**Comment by petebacondarwin** [comment]
I don't suppose you have installed a global version of karma-jasmine as well?

**Comment by dmitriz** [comment]
Uh oh! It is installed to the latest version 0.3.5!
Changed now to 0.1.5 and it works! ;-)

Would find it cleaner if local `karma-jasmine` were used instead, but at least it works!

Many thanks for the right hint :)

**Comment by petebacondarwin** [comment]
I think that is an issue with npm not karma ;-)

**Comment by petebacondarwin** [comment]
Glad it is working now.
