### ISSUE TITLE
ngAnimate in conjunction with classNameFilter causes strange side effect in angular 1.4.x

### ISSUE THREAD

**Issue by bbasic** [angular/angular.js#11709]
I have an application where I use font-awesome spinners to indicate a work in progress.
In angular version < 1.4.x I used `$animateProvider.classNameFilter(/^((?!(fa-spin)).)*$/)` in order to exclude font-awesome spinner elements from ngAnimate animations.

However, in version 1.4.x there is a strange effect in using **class name filter**. The spinners are permanently shown, although they should be hidden (ngShow/ngHide).

[plunker] (http://plnkr.co/edit/ysMTs2VmtJ1bwDOvf6XF?p=preview)

By commenting the line `app.js:19` out one gets the functionality almost as expected. The only problem now, of course, is that the "spinners" are extra animated by the ngAnimate.

**Comment by adamweeks** [comment]
Adding a little more info (not a solution), surrounding the `<i>` with a span that uses ng-show seems to behave properly.

[plunker](http://plnkr.co/edit/2hEYUgy5B5Ik9sgKF1J3?p=preview)

**Comment by matsko** [comment]
This issue was fixed and is working in RC1. Here are two demos below (1.4.0 RC1 and 1.3.15) to show that it works as expected:

1.4.0-RC1 = http://plnkr.co/edit/dZAMEjaWoFWft7hxRqiZ?p=preview
1.3.15 = http://plnkr.co/edit/ysMTs2VmtJ1bwDOvf6XF?p=preview

Please reopen if I'm missing something.
