### ISSUE TITLE
Documentation: $formatters

### ISSUE THREAD

**Issue by wlingke** [angular/angular.js#11714]
It was really unclear as to when $formatters vs $parsers in ngModelController are called.

It took a long time to realize $parsers are called from user inputs whereas $formatters are called from programatic model changes.

It would be nice to have some examples in the documentation demonstrating how to use these properly.

**Comment by pkozlowski-opensource** [comment]
@wlingke would be up to sending us a pull request with the exact doc changes that you would love to see while looking for answers?
