### ISSUE TITLE
ngShow gives inconsistent results with ngAnimate

### ISSUE THREAD

**Issue by dubejf** [angular/angular.js#11717]
`ng-show` gives inconsistent results when the watched valued is changed multiple time in the same digest cycle and `ngAnimate` is included.

Here is a simple reproduction with `1.4.0-rc.0`: http://jsfiddle.net/dubejf/xz6ppj9v/2/

- The controller has a flag, `vm.showIt`.
- This flag controls a red div using a `ng-show` directive, with `ng-show="vm.showIt"`.
- Clicking on the button toggles the flag, twice. First to set it to `true`, then to set it to `false`. The value are changed using a `$timeout`, in the hope that the `ng-show` watch will update twice in the same digest.

Expected behavior: Click on 'Click me'. At the end of the digest, `vm.showIt` should always be `false`. The red div should always be invisible.

Actual behavior: `vm.showIt` is always `false` at the end of the cycle (good). The red div is sometime visible, sometime invisible (bad).

The behavior is easier to observe in Firefox r37, where the fiddle gives the wrong results half the time. The bad behavior can also be observed in Chrome r42, with less consistency - I haven't been able to figure the pattern, you may need a few dozen push of the button to make it fail.

When the test fails (red div visible), the class 'ng-hide' is missing on the div. The class should be set, because the condition for `ng-show` is `false`.

The root of the problem appears to be the handling of classes inside the `$animate` service, specifically when successive calls to `removeClass` \ `addClass` are made.

The problem only occurs when the `ngAnimate` module is included. Tested with `1.4.0-rc.0` and `1.4.0-build.3988`.

**Comment by dubejf** [comment]
You can see the commenting `'ngAnimate'` in the fiddle resolves the issue. The bug is easier to demonstrate with Firefox.

**Comment by Narretz** [comment]
Did that happen before (in 1.3.x)?

**Comment by dubejf** [comment]
Still a problem in the latest rc `1.4.0-rc.1` http://jsfiddle.net/dubejf/xz6ppj9v/3/
I'm not able to reproduce it in `1.3.15` http://jsfiddle.net/dubejf/xz6ppj9v/4/

**Comment by matsko** [comment]
This PR should fix it: https://github.com/angular/angular.js/pull/11755

**Comment by dubejf** [comment]
Great! I ported the PR to my local copy. It does fix the issue.
