### ISSUE TITLE
Native scroll doesn't work properly with ngTouch in iOS 8

### ISSUE THREAD

**Issue by fretman92** [angular/angular.js#11715]
Hello,

I have 2 test devices running the same cordova webapp with Angular 1.3.9

On iPhone 4, iOS 7, momentum scrolling works perfectly.
On iPhone 4S, iOS 8, the view only scrolls as long as my finger moves, the scroll seems laggy.

**Comment by pkozlowski-opensource** [comment]
@fretman92 please direct support questions to an appropriate support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
