### ISSUE TITLE
Inconsistency in ng-bind and interpolate

### ISSUE THREAD

**Issue by just-boris** [angular/angular.js#11716]
Here is example:
http://plnkr.co/edit/C95zazjXx5jfDrMqIE67?p=preview
Same data gives diffrerent output in interpolate and ng-bind
```
ng-bind: [object Object]
interpolate {"a":1,"b":2,"c":3}
```
I expected that `ng-bind` will render the same result that interpolate does.

**Comment by mhartington** [comment]
From my understanding, `ng-bind` is used internally for `$interpolate` to convert the data in to a string.

So in your example, `ng-bind` is pulling in the raw object, which is not converted to a string. 
With `{{data}}` we're essentially saying bind to the raw data object and print it out a string.

Hope this helps a little bit

http://jsbin.com/jedete/4/edit?js,console,output

**Comment by gkalpak** [comment]
I am not really sure what @mhartington means, but I don't think `ngBind` is used by `$interpolate.
The difference is that `ngBind` assigns a value to `element.textValue` (which implicitly converts the value to a string; and calling `someObj.toString()` returns `[object Object]`).
`$interpolate` on the other hand uses a custom "stringify" function that converts objects to JSON.

This merely confirms what OP already pointed out: that the behaviour of `ngBind` is different from that of `$interpolate`.
I am not sure why that is, but note that (a) `$interpolate` is not exclusively used in the view and (b) they shouldn't necessarily behave the same.

**Comment by just-boris** [comment]
So, there is few thoughts:
* Difference in behaviour should be noted in documentation. Now there is just said that "[is similar but less verbose](https://github.com/angular/angular.js/blob/2a156c2d7ec825ff184480de9aac4b0d7fbd5275/src/ng/directive/ngBind.js#L13-14)".
* I need a directive version for interpolate behaviour. Now I can write a custom one, but why not to include it in the core.

**Comment by pkozlowski-opensource** [comment]
@gkalpak would there be any reason for:
> they shouldn't necessarily behave the same.

Honestly I'm not sure we've got this inconsistency and I can't think of any reason.

**Comment by gkalpak** [comment]
@pkozlowski-opensource: There might some reasons (for the nconsistency); but I wouldn't know.
I can't think of any either. 

Changing `$interpolate` or text-interpolation would be too much of a breaking change though.
Chanigng `ngBind` to make it consistent with interpolation wouldn't hurt I guess (unless someone is relying on getting `[object Object]` back or passing very large objects to `ngBind`).

**Comment by pkozlowski-opensource** [comment]
Right, I was thinking of eventually having `ngBind` following the logic of `$interpolate`

**Comment by lgalfaso** [comment]
This looks like a valid issue and I have to agree that `ngBind` should follow the same logic that `$interpolate` has. Doing this without code duplication might turn to be a patch larger than expected, but given that it is a small breaking change, it would be ideal that if a fix lands, that it would be before we cut 1.4

@petebacondarwin WDYT?

**Comment by petebacondarwin** [comment]
I agree that we should fix `ngBind`. I would prefer to prioritize fixing regressions for 1.4.0 before we make this change though. It is fairly low priority given that one can always work around it by writing a directive.
Also one can use [`ngBindTemplate`](https://docs.angularjs.org/api/ng/directive/ngBindTemplate) too to get the same result.

**Comment by petebacondarwin** [comment]
Actually I think this would be pretty straightforward. Just extract the `stringify` function from the [`$interpolate` service factory](https://github.com/angular/angular.js/blob/master/src/ng/interpolate.js#L106-L118) and change the `ngBind` watch handler to:

```js
        scope.$watch(attr.ngBind, function ngBindWatchAction(value) {
          element.textContent = stringify(value);
        });
```

**Comment by alexey-sh** [comment]
[small crutch](http://plnkr.co/edit/shxijPuQGLA7cx0IbXOm?p=preview):
```
ng-bind="data|json"
```

**Comment by gkalpak** [comment]
@alexey-sh: The output is not exactly the same (this is more visible in elements that preserve whitespace; such as `<pre>`).
As @petebacondarwin already mentioned, `ngBindTemplate="{{...}}"` can be used (as a temporary workaround).

[Updated plnkr][1]

[1]: http://plnkr.co/edit/3aSvYOsMzzXwHxuymfPR?p=preview

**Comment by TheCulliganMan** [comment]
Unsubscribe

**Comment by Zehra-89** [comment]
Hi please help me out, there is angular code, I want to verify h1 tag value.
I write protractor code=  var ContactManager=element(by.binding('{::vm.oppDetails.managedBy.name}')).getText();
but it says location binding not found.

angular js code: 
<div flex="60"
                      flex-gt-lg="70"
                      class="employee-desc">
                      <h1 class="ng-binding">{{::vm.oppDetails.managedBy.name}}</h1>
                      <p class="ng-binding">{{::vm.oppDetails.managedBy.title}}</p>
                      <p class="ng-binding"> Time: {{::vm.oppDetails.managedBy.officeHours}}</p>
                      <p>
                        <a class="mail-icon"></a>
                        <a class="call-icon"></a>
                      </p>
                    </div>

**Comment by FrailWords** [comment]
Hi All, 

I came across an alternate problem that might be related to this?  Please correct me if not.

While answering a question - http://stackoverflow.com/questions/34574448/filtering-some-data-with-two-kind-of-filter-in-angularjs-but-not-working/34576905, I replaced the `{{ }}` bindings with `ng-bind` in the results section of the plunkr in this post and the search result filtering started working fine.  I was going by best practice and not exactly trying to figure out why this solved the problem.  

I did take a look at `ngBind.js` code and was lead in the direction of `$watch` and `$observe` - one's on scope and the other's on the attribute.  Is this something that affects how the values inside an ng-repeat show up and behave?

I felt like this is the best place for this question.  Thank you.

**Comment by petebacondarwin** [comment]
@FrailWords - I don't believe this is a problem with Angular. See my comment on SO.

**Comment by FrailWords** [comment]
@petebacondarwin thanks a lot for the correction.
