### ISSUE TITLE
Add isStrictDi to $injector

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#11728]
I'm writing a utility library where I have a use case to know when strict DI is enabled on a given `$injector`. I could really use some reasonable way of knowing without having to do something crazy like:

```javascript
function isStrictDi($injector) {
  try {
    $injector.invoke(function(a) {});
    return false;
  } catch(e) {
    return true;
  }
}
```

I'm thinking that we could just add a line that says `instanceInjector.strictDi = strictDi` right [here](https://github.com/angular/angular.js/blob/0baa17a3b7ad2b242df2b277b81cebdf75b04287/src/auto/injector.js#L649) before the `instanceInjector` is returned.

I would happily open a PR with tests which would do this. Just want to make sure this is the correct approach.

**Comment by petebacondarwin** [comment]
@kentcdodds what is the use case?

**Comment by kentcdodds** [comment]
I'm building a tool to validate injectable functions. I would like to know if strictDi is turned on for the injector so I know whether to allow a simple function.

**Comment by kentcdodds** [comment]
Here's the beginnings of the tool/lib: https://github.com/alianza-dev/angular-scope-types

**Comment by btford** [comment]
Is this something that you'd ship with the production app, or just something you'd use while developing?

**Comment by kentcdodds** [comment]
@btford, the library can be disabled (so it is a no-op for production). But it validates your DDO and I wanted to know whether your DDO should be using explicit annotation based on whether strict di is enabled (which I have enabled in development).

But thinking about it further, angular will throw an error if something's not using explicit annotation when it should be so I don't think it's valuable for me to validate that with this library. I'll go ahead and close this. Thanks!
