### ISSUE TITLE
Value cannot be null. Parameter name: type with $expand clausole on REST url

### ISSUE THREAD

**Issue by MassimoGiambona** [angular/angular.js#11724]
Using <b>$expand</b> clausole on REST url return the error above: <em>"Value cannot be null. Parameter name: type"</em>

Here a simple code to reproduce:

<samp>
var url = "https://sitename.sharepoint.com/_api/web/lists?$filter=Hidden eq false&$expand=Fields&$select=Id,Title,Fields/TypeAsString,Fields/Title,Fields/ID,Fields/Choices,Fields/InternalName,Fields/JSLink";
</samp>

<samp>
$http.get(url, { Accept: "application/json; odata=verbose" })
	.success(function (data) {
		console.log(data);
	})
	.error(function (error, status) {
		console.error(error);
	});
</samp>

**Comment by pkozlowski-opensource** [comment]
The only error I can reproduce with a simple plunk (http://plnkr.co/edit/00yhqkOtCAcKzuWFgAJJ?p=preview) is `ERR_NAME_NOT_RESOLVED` as it looks like the provided URL is not valid (try to open in a browser tab without Angular).

@MassimoGiambona could you please provide a reproduce scenario in a plunk (you can modify mine) that would show a problem in AngularJS?

**Comment by MassimoGiambona** [comment]
Hi, thank you for your response, the link is deliberately wrong, replace <b>sitename</b> with other value of valid SharePoint site. I'm trying to create ad-hoc site for this dbg.

**Comment by pkozlowski-opensource** [comment]
@MassimoGiambona I'm sorry but I don't think I've got access to any SharePoint site, so you will have to setup a debug site if you need help on this. Or you can debug $http code to see which part breaks - and this way reproduce it under unit test.
