### ISSUE TITLE
ng-options include array properties

### ISSUE THREAD

**Issue by wulfsberg** [angular/angular.js#11733]
If an array contains additional properties (notably, as when fetched with Restangular, which adds several functions to the array), these extra properties are included in the iteration for ng-options, leading to unexpected "junk" entries in the select dropdown.

This differs from the iteration when using ng-repeat over the same array, which does not include such properties.

(This is new behavior in v1.4 rc0 and rc1. v1.3 does not show this behavior)

**Comment by Narretz** [comment]
You mean props starting with `$` and `$$`?

**Comment by wulfsberg** [comment]
Functions as well, yielding some very bizarre <options> when inspecting the HTML.

**Comment by superasn** [comment]
If it is of any help:

Please take a look at this fiddle:

http://jsfiddle.net/fggx31k7/

Open the extended Array drop-down (SELECT), you will see all sorts of things like functions, length, etc. 

![Preview](http://i.imgur.com/mPmomXf.png)

This was not happening until Angular 1.3.

https://jsfiddle.net/superasn/k2uwdjh5/ **(working fine)**

**Comment by Narretz** [comment]
Thanks, this is helpful. (although both your fiddles have 1.4.0-rc.1. You can also use plnkr.co, where it's simpler to switch dependencies)

**Comment by superasn** [comment]
Sorry about that.. I've updated the second fiddle, please try it here:

https://jsfiddle.net/superasn/k2uwdjh5/1/

**Comment by petebacondarwin** [comment]
This is a bug. Let's fix it.
To be clear, though, there are a few different scenarios here:

* A real array containing a function as one of its items
* An **extended array** object containing a function as an instance property
* An **extended array** object with a function on its prototype
* An **extended array** object containing a non-function as an instance property
* An **extended array** object with a non-function on its prototype
* An **array-like** object containing a function as an instance property
* An **array-like** object with a function on its prototype
* An **array-like** object containing a property as an instance property
* An **array-like** object with a property on its prototype
* A **non-array-like** object containing a function as an instance property
* A **non-array-like** object with a custom function on its prototype

What do you think should happen in each of these cases?

**Comment by wulfsberg** [comment]
My somewhat fast and cheap answer would be "the same as `ng-repeat`". It makes sense that those two treat iterating over objects the same way.

**Comment by caitp** [comment]
ng-repeat doesn't deal with non-arraylike objects anymore

**Comment by caitp** [comment]
wait I'm wrong, it totally still does. how did we not get rid of that yet

**Comment by petebacondarwin** [comment]
Here is a fix that makes `ngOptions` follow the same logic as `ngRepeat`. @wulfsberg & @superasn can you see if this fixes your problems?

There is a tiny breaking change. @Narretz & @caitp what do you think - is that too big a BC to get it into 1.4.0?

**Comment by Narretz** [comment]
Breaking Change is okay, as there's a pretty simple workaround. And it doesn't affect many people.

**Comment by superasn** [comment]
> My somewhat fast and cheap answer would be "the same as ng-repeat".

Yes, that would be great. For example, *filterFilter* also doesn't work with Array like objects anymore, like it used to before.

Please take a look at this fiddle:

Works like it should with previous version of Angular (v1.2):
https://jsfiddle.net/superasn/gznzjgmb/ 

Breaks with newer versions of Angular (v1.3 and above):
https://jsfiddle.net/superasn/c15yvq6g/

**Comment by petebacondarwin** [comment]
@gkalpak is there any reason why we can't support array-like collection with `filterFilter`?
@superasn could you create a separate issue for that so that we can track it when this issue gets closed?

**Comment by superasn** [comment]
@petebacondarwin i have created a new issue here: 

https://github.com/angular/angular.js/issues/11782
