### ISSUE TITLE
Is it possible to show errors inside a tooltip with ng-messages?

### ISSUE THREAD

**Issue by danicomas** [angular/angular.js#11737]
I would need to overload ng-message or exist some interceptor to do it?

Regards!

**Comment by pkozlowski-opensource** [comment]
Please direct general support questions like this to an appropriate support channel, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by danicomas** [comment]
Ok @pkozlowski-opensource I have opened. http://stackoverflow.com/questions/29892169/is-it-possible-to-show-errors-inside-a-tooltip-with-ng-messages

**Comment by danicomas** [comment]
But @pkozlowski-opensource exists the functionallity? @PascalPrecht @btford

**Comment by pkozlowski-opensource** [comment]
@danicomas it is not really clear what are you asking for, what kind of tooltip you want to use etc. I would _highly_ suggest providing more context in the SO question - I doubt anyone will be able to answer it in the current form.

In any case GitHub is _not_ a support forum.

**Comment by danicomas** [comment]
I have updated the description. I don't want to do a forum topic. I explain a problem that this directive not have!

**Comment by danicomas** [comment]
It is possible to do something like this: https://github.com/seito2014/angularjs-study2-seito/blob/master/index.html#L97 but you have to do statically.
