### ISSUE TITLE
templateCache/cacheFactory missing "has" method

### ISSUE THREAD

**Issue by ragsnas** [angular/angular.js#11748]
Shouldn't the templateCache have a has method, returning true if the template exists in the cache and false if it doesn't?
This would be quite helpfull to have "override template by convention" solutions.

**Comment by pkozlowski-opensource** [comment]
We could add `has` but it would be close to (at least for templates) doing `if ($templateCache.get(path)`

**Comment by pkozlowski-opensource** [comment]
BTW, we'got an issue for this already: https://github.com/angular/angular.js/issues/8692

Closing as a duplicate, please add your use-case to #8692
