### ISSUE TITLE
$timeout gets invoked more than once (repeatedly)

### ISSUE THREAD

**Issue by leolux** [angular/angular.js#11750]
I am using angular version 1.3.14. The following $timeout function gets invoked every 3 seconds:
```
$timeout(function () {
      console.log('should be called only once');
    }, 3000);
```

**Comment by pkozlowski-opensource** [comment]
Can't reproduce with a simple plunk: http://plnkr.co/edit/fbZ4APsGwH6VF6GZVJL5?p=preview
Please share exact reproduce scenario - otherwise this one is not really actionable....

**Comment by leolux** [comment]
When I replace the code with pure Javascript
```
setTimeout(function(){
    console.log('should be called only once');
    }, 300);
```
Then the function gets called only once.
I'll try to make a reproducer.

**Comment by leolux** [comment]
Very strange: 
During creation of the plunker the function has been called multiple times while nothing on on the code. After that I changed the code a little bit and now the issue has  disappeared
Maybe there is some caching of hte $timeout service involved?

**Comment by pkozlowski-opensource** [comment]
Nope, there is no caching for `$timeout`.  I guess there is some other code interacting.

**Comment by leolux** [comment]
Ok thanks!

**Comment by stilllife00** [comment]
Same issue here, I'll add more info if I find something
