### ISSUE TITLE
ngLocalStorage/SessionStorage service

### ISSUE THREAD

**Issue by pranaydutta89** [angular/angular.js#11759]
how about if angular provide us an service injector to getting/setting of local/session storage ,including the events which storage emits on setting ??

**Comment by pkozlowski-opensource** [comment]
I would say that it is an excellent idea for a third-party module. Hay, it even looks like some exist already, ex.:
* https://github.com/grevory/angular-local-storage
* https://github.com/gsklee/ngStorage

My vote would go to "yes, but not in core"

**Comment by Narretz** [comment]
I think ng2 is also going to have better "data" support, which includes localStorage and goes beyond cookies / xhr requests as in ng1.

**Comment by pranaydutta89** [comment]
:+1:

**Comment by SateeshKumarBheemsetty** [comment]
is storing data on client browser is secure ? is there any security concerns over using the localStorage ?

**Comment by Narretz** [comment]
Out of scope of Core, especially since we are moving to LTS.
