### ISSUE TITLE
ngResource instance methods fail when isArray is set to true.

### ISSUE THREAD

**Issue by apolishch** [angular/angular.js#11767]
Instance methods fail when isArray is set to true.

For example:

I am attempting to build a generic filter which needs to be able to handle, based on configuration parameters both a resource instance, and a service.

I have the following factory code:

    angular.module('sample').factory('Sample', function($resource) {
      var methods = {
        search: {
          method: 'POST',
          isArray: true
        }
      }
      var Sample = new $resource('/sample', methods);

      Sample.prototype.elasticFilter = function (search) {
        var query = {
          query: {
            filtered: {
              query: {
                wildcard: {
                  name: '*' + search.toLowerCase() + '*'
                }
              }
            }
          }
        }
        return this.$search(query);
      }
      return Sample;
    });

Now if I do the following in my directive:

    scope.search = function (search) {
      Sample.elasticFilter(search).$promise.then(function () {
        handle
      });

this results in 

      TypeError: Cannot read property 'then' of undefined

printing out Sample.elasticFilter(search), the result is directly a `Promise.

modifying the directive to read directily off `Sample.elasticFilter(search).then` results in:

`TypeError: value.push is not a function`.

Drilling into the code, this is happening as interplay between:

https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L556 (isInstanceCall is true)

and 

https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L592 (trying to push onto resource).

While I understand that this may be in fact "working as intended (don't use resources in this manner)" I would point out that this could use a significantly more informative error message and/or a mention in the documentation

**Comment by gkalpak** [comment]
I don't think it is an issue with `ngResource`. You seem to be using it in the wrong way.
<sub>
There are also a lot of other errors in the code you provided, but I assume they are copy/paste errors.
In any case, I would suggest going over the docs and making sure you understand the difference between "class" methods and "instance" methods.
</sub>

--
It's not clear how you intend to use `elasticFilter`, but if you are trying use it as a "static" function (i.e. `Sample.elasticFilter`), it should look like this:

```js
.factory('Sample', function SampleFactory($resource) {
  var methods = {...};

  var Sample = new $resource('/sample', {}, methods);
  Sample.elasticFilter = function (search) {
    var query = {...};
    return Sample.search(query);
  };

  return Sample;
})

[Live demo][1]

--
So, afaict, this is working as expected.

[1]: http://codepen.io/ExpertSystem/pen/oXXYXj?editors=101
