### ISSUE TITLE
bug: ngAnimate - ngSwitch not working

### ISSUE THREAD

**Issue by karol-f** [angular/angular.js#11769]
### Overview of issue
Animation of ngSwitch stopped working in 1.4

### Version
1.4 (e.g. RC0, RC1)

##### Not working (example in documentation of current 1.4 version) 
https://docs.angularjs.org/api/ng/directive/ngSwitch#example

##### Working (example in documentation of current 1.3 version) 
https://code.angularjs.org/1.3.15/docs/api/ng/directive/ngSwitch#example

### Expected
Expecting ngSwitch animation working when ngAnimate module is loaded.

**Comment by matsko** [comment]
Thank you for finding this issue. This is pretty important bug. There is a PR ready which fixes it #11804.
