### ISSUE TITLE
no Module error with angular 1.4 in Internet Explorer 9

### ISSUE THREAD

**Issue by Skuriles** [angular/angular.js#11776]
![screen2](https://cloud.githubusercontent.com/assets/7985622/7415849/a7233c0e-ef5b-11e4-83b4-18f1af0d5727.jpg)

I get this error in an angular app when I try to load the website:

http://errors.angularjs.org/1.4.0-beta.6/$injector/modulerr?p0=app&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.0-beta.6%2F%24injector%2Fnomod%3Fp0%3Dapp

It says there is an error which prevents the module to be loaded correctly. In Mozilla, Chrome and IE10/11 all works fine.

I tried to downgrade to 1.3 but there are still the same errors. I updated all external modules but still the same error.

Any ideas why this error occurs:

Start of the module is;
(function() {
    var app = angular.module('app', [
        'ngRoute',
        'ngCookies',
        'ui.bootstrap',
        'iso-3166-country-codes',
        'pascalprecht.translate'
    ]);

Any ideas why this error occurs? 
Can I add some more information which maybe helpful?

Reagrads Sku

**Comment by Narretz** [comment]
The first step should be to remove the dependencies one by and see if the errors persists. Start with the third party modules.

**Comment by petebacondarwin** [comment]
The error is that module `app` is not available. I find that when this happens it is not usually due to a missing dependency. It is normally that there is a syntax error in the app code somewhere that is stopping Angular from instantiating the module. Check your code.

**Comment by Skuriles** [comment]
Hey,

after loads of tests, delete all dependencies and a nearby breakdown I found the error:

I worked with head.js to load all js/css files. This seems to occur in an error in IE 9 because the loading seems to be a little bit different....

Just added the files directly in the index.html -> Works. Load the app with head.js -> error

Thanks
