### ISSUE TITLE
Error message on directive namespace conflict

### ISSUE THREAD

**Issue by sod** [angular/angular.js#11775]
I got this error message today:

```
Error: [$compile:multidir] Multiple directives [pagination, pagination] asking for new/isolated scope on: <pagination>
http://errors.angularjs.org/1.4.0-rc.1/$compile/multidir?p0=pagination&p1=pagination&p2=new%2Fisolated%20scope&p3=%3Cpagination%3E
```

Took me a while to debug whats wrong with my `pagination` directive. Until I discovered another directive with the exact same name `pagination` from ui.bootstrap. It wasn't obvious as I didn't include `ui.boostrap` myself.

If the error message would include the module name the directive came from, this had helped a lot. Something like:

```
Error: [$compile:multidir] Multiple directives [pagination (module: foundation), pagination (module: ui.bootstrap)] asking for new/isolated scope on: <pagination>
```

Example code: http://plnkr.co/edit/Mgxutpvfr4ngqRD6fV1F?p=preview
Version: angular.js/1.4.0-rc.1

**Comment by petebacondarwin** [comment]
Feel free to provide a PR for this. Otherwise we will try to get to it in 1.5. At the moment there is no link back from injectable components to their originating modules.

**Comment by kentcdodds** [comment]
Trying my hand at a PR #11793. Would love some feedback to make sure I'm taking this the right direction. A little iffy on the idea of passing the module to all the invoke queue. But I can't think of any other way to accomplish this.

**Comment by lugovsky** [comment]
@kentcdodds Probably there could be other solution to do this. I'm just not 100% sure if this is possible, cuz I'm fairly new to angular.js sources. 

I assume, that each directive is an object. If so, there could probably be a way to find module in which directive is defined by using object comparison. Even if this solution is not good in terms of performance, I think it could be quite okay during exception throwing.

And again, it's only an assumption, so don't judge me strictly please :)

As well I can provide pull request, if this solution is implementable and somebody will tell me which parts of this solution are not implemented at all.

**Comment by petebacondarwin** [comment]
It would be better find a way to search the loaded modules for directives with a given name.

**Comment by kentcdodds** [comment]
That could be reasonably done. I've [done this before](http://kent.doddsfamily.us/kcd-angular/#/) (the list on the left is auto-generated based on the contents of the `_invokeQueue`). That would also touch much less of the entire library.

**Comment by lugovsky** [comment]
Yeah, I see that. But in your example you have root module hardcoded:
```javascript
var allTheThings = [];
  _.each(angular.module('kcd').requires, function(submoduleName) {
    allTheThings = _.union(allTheThings, getThings(angular.module(submoduleName)));
  });
```
As from what I understand, in real application this information is available only on injector level. That's why from my point of view, the only way to achieve what we want is to make injector expose list of loaded modules here: https://github.com/angular/angular.js/blob/master/src/auto/injector.js#L838

Guys, am I heading in the right direction? Can I go on with that and create a pull request?

**Comment by petebacondarwin** [comment]
@lugovsky if you have a solution that does not impact the runtime performance and is cleanly implemented then by all means make a pull request.

**Comment by lugovsky** [comment]
Hey guys. I finally created a pull request for this issue. Please check it out and tell, does it look good enough for you. I will be happy to do any modifications
