### ISSUE TITLE
changelog has html unescaped after 1.2.14 feisty-cryokinesis (2014-03-01)

### ISSUE THREAD

**Issue by jonricaurte** [angular/angular.js#11777]
If you look in changelog after 1.2.14 feisty-cryokinesis (2014-03-01), you will see a bunch of html displayed.

**Comment by gkalpak** [comment]
Interesting...

**Comment by pkozlowski-opensource** [comment]
I think we've got another issue for this already... From what I understand it is GitHub processing of md that fails...

**Comment by Narretz** [comment]
Yes, there's another issue. But the question is, what makes the parsing fail?

**Comment by Narretz** [comment]
This should do it, what do you think? https://github.com/angular/angular.js/pull/11778
