### ISSUE TITLE
angular.foreach object instance assignment issue

### ISSUE THREAD

**Issue by tgfactor** [angular/angular.js#11785]
I don't know if this has been fixed in later versions, but in a project using angujarjs v1.2.4, I came across a situation with an angular.foreach going through a device array of objects, and assigning a string to an attribute of an object instance:

```
angular.forEach($scope.deviceArray, function(device, di) {
	$scope.deviceArray[di]._value = dataArray[di];
});
```

This is what I found through this method.  Let's say we have an object in the deviceArray at row 2, and it has the same attributes and attribute values as another object in that deviceArray (at row 4 and 5).  When we get to row 5 in this loop, if we assign deviceArray[5]._value to dataArray[5], then what happens is that the _value attribute in rows deviceArray[2] and deviceArray[4] gets assigned to what deviceArray[5]'s _value attribute is assigned, overwriting their previously assigned values.  I would assume that each object in this array would have its own uniqueness, primarily by index, but for some reason, when using an angular.forEach, it doesn't matter if I'm assigning row 2 or row 5, assigning the attribute of one updates all other ones in that array.

The way I fixed it was this way:
```
for (var a = 0; a < $scope.deviceArray.length; a++) {
	$scope.deviceArray[a]._value = dataArray[a];
}
```

Somehow, this worked and solved my problem, but I can't help but feel there is a problem with the angular.forEach in how it treats objects in arrays uniquely from each other.

**Comment by kentcdodds** [comment]
Do you think that you could reproduce this issue? I'm not sure I understand what you're asking and could probably help if I did. I created a starter jsbin for you: http://jsbin.com/batiqi/edit

**Comment by Narretz** [comment]
Closing due to lack of response. Feel free to reopen if you can provide more info.
