### ISSUE TITLE
Having issue in angular js intellisense for Visual Studio 2013 

### ISSUE THREAD

**Issue by jaiminprajapati88** [angular/angular.js#11798]
Hello Everyone,

Currently i'm working in a project having AngularJS v1.2.21. I'm using VS 2012 and recently upgrade to VS2013 for better intellisense support. But this step is not worth for me to achieve our goal.

I'm getting intellisense in html but not in javascript files.

I tried to install AngularJS.Intellisense using nuget package(https://www.nuget.org/packages/AngularJS.Intellisense/1.0.3) but it requires angularjs version to 1.3 and less than 1.4 which does not exist in my current system.

So can you guys please guide me to get better intellisense support in javascript file as well?

**Comment by Narretz** [comment]
Sorry, we are not the creators of AngularJS.Intellisense/1.0.3. You'll have to address your problems with the developers.

**Comment by rdpatelcygnet** [comment]
Hi,
As AngularJS.Intellisense 1.0.3 is dependent on AngularJs verson greater the or equal to 1.3 , so it won't work. Uninstall  AngularJS.Intellisense 1.0.3  and install AngularJS.Intellisense 1.0.2 ,which supports version less then 1.3. 
Then, it will work fine.

**Comment by jaiminprajapati88** [comment]
Installing AngularJS.Intellisense 1.0.2 also tries to resolve dependency of AngularJS.Core (≥ 1.3.8).
Is there any other way to get intellisense? 

@Narretz  the ultimate objective is to get intellisense. either by using AngularJS.Intellisense or some thing else.
