### ISSUE TITLE
  angular ng-click triigered 3 times, why this happens?

### ISSUE THREAD

**Issue by redguardtoo** [angular/angular.js#11806]
Environment:
Windows 7
Angular 1.3.15
Firefox 37.0.2

After I click the "Click Me" button the getMessage() is call three times, why this happens?

Here is the complete html:
```html
<!DOCTYPE html>
<html ng-app="myApp">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <title>Angular Sandbox</title>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js"></script>
    <style type="text/css">.nav, .pagination, .carousel, .panel-title a { cursor: pointer; } /* angular ui bootstrap hack */</style>
  </head>
  <body>
    <div class="container" ng-controller="MainCtrl">
      <h1>{{ getMessage() }}</h1>
      <button ng-click="clickMe()" >Click Me</button>
    </div>

    <script type="text/javascript">
     var app= angular.module('myApp', []);
     app.controller('MainCtrl', function ($scope) {
       var that = this;
       that.count = 1;
       that.message = 'Hello World';
       that.userName = 'Chen';

       $scope.getMessage = function( ) {
         var rlt = '';
         console.log('$scope.getMessage called!');
         console.trace();
         rlt += that.userName + ', ';
         rlt += that.message + ' ';
         rlt += that.count + (that.count>1? ' times':' time');
         return rlt;
       };

       $scope.clickMe = function() {
         that.count++;
       };
     });
    </script>
  </body>
</html>

```

**Comment by caitp** [comment]
guessing, but I'm pretty sure `getMessage()` is called once on startup during the first digest, and twice when the button is clicked (ng-click causes the digest, so it's called once, and then called again to make sure the value is stabilized).

It might actually be called 4 times, that would make more sense

**Comment by caitp** [comment]
I'm wrong, it's actually called 3 times during your initial bootstrap to make sure the model stabilizes

**Comment by goblortikus** [comment]
Your question is asking why ng-click is clicked 3 times... it's actually not... as caitp pointed out, that is the digest loop going through and checking on the return value of getMessage(). Take a look at this jsfiddle to which I added a console.log when the ng-click is actually called. It is only called once.

http://jsfiddle.net/vzd06xyq/

**Comment by caitp** [comment]
anyways, this is pretty much working as expected, dirtychecking will check the expression (`getMessage()`) multiple times to make sure the value stays the same. If that's a problem for you, consider storing the message in a value and updating the message entirely on ng-click() instead of just the count.

**Comment by redguardtoo** [comment]
Thanks.
