### ISSUE TITLE
cloneNode(DeepCopy) + Nested ngRepeat => Fails

### ISSUE THREAD

**Issue by Dorian-Fusco** [angular/angular.js#11818]
I encountered an issue where cloneNode wouldn't clone the content of a table :

This table uses ng-repeat on every row (tr) and inside every row, on every cell (td).
I tried to clone it and got all of my rows, but not any of my rows contains a cell !

EDIT : actually, it seems it's 'just' that the angularjs expressions in my DOM element aren't evaluated, and thus, the ng-repeat doesn't create anything (no row nor cell) on the first clone (not the others) most likely because my code is evaluated before the angular expressions in my HTML... Not sure how to deal with this...

EDIT2 : $timeout did the trick :)

**Comment by lgalfaso** [comment]
A plunker showing what you are trying to do would be mostly helpful
