### ISSUE TITLE
How to get all the score objects in an array using angular.forEach from below json 

### ISSUE THREAD

**Issue by rkori215** [angular/angular.js#11815]
{
"Type": null,
"Id": null,
"Date": null,
"reportCategories": [{
"categoryName": "x",
"categoryDescription": "cgcvc",
"specDescription": "sdsdsd",
"subCategories": [],
"score": 1.9,
"rating": "Low"
}, {
"categoryName": "y",
"categoryDescription": "dfdf.",
"specDescription": "fdfdf.",
"subCategories": [],
"score": 1.9,
"rating": "Low"
}, {
"categoryName": "z",
"categoryDescription": "Pdfdfdfd",
"specDescription": "dfdfd.",
"subCategories": [],
"score": 2.3,
"rating": "Low"
}]
}

**Comment by Narretz** [comment]
Please read the contributing guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#SUPPORT
