### ISSUE TITLE
Firefox ignores 'watch' class name in ng-class directive.

### ISSUE THREAD

**Issue by joshmatz** [angular/angular.js#11813]
I'm not sure if this is an Angular or Firefox bug (or maybe I'm just missing something else) because no other browsers are having this problem...

But given a code snippet like:

```
<div ng-class="{className: true, watch: true, sympathy: true}">
```

Firefox will generate:
```
<div class="className sympathy"><div>
```

You can see this using the following Pen (Angular 1.3.2):
http://codepen.io/joshmatz/pen/Xbmame

**Comment by caitp** [comment]
firefox has a nonstandard property 'watch' in Object.prototype. Some version of this bug has been solved, please check if it's still an issue in 1.4.0

**Comment by caitp** [comment]
hmm, I think ngClass is still affected

**Comment by caitp** [comment]
I've got a quick fix for this, http://plnkr.co/edit/7KYx6HKx8EeOcWUIT4gu?p=preview

**Comment by softsimon** [comment]
I have stumbled across this "watch" limitation at several occasions in 1.4.
I can't send a parameter called 'watch' as a POST var to ngResource, it gets ignored. I can't create a state called 'watch' in ui-router.

**Comment by caitp** [comment]
Could you file individual bugs for each issue you're running into? It's much easier to track them that way. As for this one in particular, It's been fixed

**Comment by caitp** [comment]
Not for the ui-router issue though open that on their repo
