### ISSUE TITLE
AngularJS ng-grid- To show 'No Data Available' inside grid when its has empty data

### ISSUE THREAD

**Issue by vijender1256** [angular/angular.js#11811]
Can you please provide a workaround to show a message to display something if the grid is empty, instead of showing a blank grid, it doesn't look good at all, I have tried to put <div> inside the div but my page is complex and the message is not shown where i wanted. how to fix this issue ?

**Comment by pkozlowski-opensource** [comment]
@vijender1256 I guess you wanted to open this issue in the relevant repo: https://github.com/angular-ui/ng-grid
