### ISSUE TITLE
Strange behavior of select options

### ISSUE THREAD

**Issue by jo-soft** [angular/angular.js#11819]
I recognized some strange behavior  in a select input, using providing a pre-selected value.

If I provide the key as Integer, angular adds a new empty option. If the key is passed as string, everything works as expected.

This behavior appears in Angular 1.3.2 and above, but it works in Angular  1.3.1

Example:
https://jsfiddle.net/pu27bL7v/3/

**Comment by petebacondarwin** [comment]
This is working as expected. When you iterate over an object's keys, those keys are strings. This is not angular specific but just how JavaScript object keys are stored. In Angular 1.3.2, I believe that we switched over to strict equality for comparing the option value to the model.

You have a couple of options to deal with this:

1) Use strings in your model. See https://jsfiddle.net/g56dokf0/
2) Convert the number to a string and back again using a $formatter/$parser pair via a directive. See https://jsfiddle.net/kd1shg1w/

Hope that helps.

**Comment by jo-soft** [comment]
ok, thnx.  but it seem's like it's not done in all places, because if I use an array of objects  it works again.

see https://jsfiddle.net/3ywvgk6y/

**Comment by petebacondarwin** [comment]
In this second fiddle, you are not iterating over an object's properties; you are iterating over an array of objects. The point is that a property's name is always a string. In your case the "value" of the id property is a number.
