### ISSUE TITLE
No Cache-Control header for image request when using ng-src

### ISSUE THREAD

**Issue by seb0zz** [angular/angular.js#11828]
I am using version 1.3.13 within an ionic project. For all images that get their `src` attribute trough the `ng-src` attribute my browser does not send any Cache-Control headers. Does anyone have any debugging hints or suggestions where the problem could come from? This is maybe related to this issue on stackoverflow: 

http://stackoverflow.com/questions/20074864/no-if-modified-since-header-when-using-ng-src-for-caching

**Comment by pkozlowski-opensource** [comment]
I can't see Chrome sending `Cache-Control` headers with regular `img` tags (without using AngularJS): http://plnkr.co/edit/SgDCXaSrYgd1ra2ZX2Jp?p=preview, while FFox seems to send this header for both regular img tags and tags using `ngSrc`.

In short: the behavior seems to be browser-dependent and `ngSrc` behavior doesn't differ from the regular `src`. Closing as it doesn't look like Angular is a culprit here.
