### ISSUE TITLE
routeProvider templateUrl accepting custom $http config

### ISSUE THREAD

**Issue by chiu0602** [angular/angular.js#11821]
As 'templateUrl' may be request for json or html, different http "accept" value will cause for different return results. So it is suggested that custom $http config for $routeProvider

**Comment by pkozlowski-opensource** [comment]
> As 'templateUrl' may be request for json or html

How come? How would you write a template in JSON? Are you using special templates format / pre-processor? 

In any case, if any configuration is to be added for template request it should be done on the https://github.com/angular/angular.js/blob/master/src/ng/templateRequest.js level. But before thinking about such conf options we need to better understand the use case.

@chiu0602 could you please provide more details on what you are trying to do?

**Comment by chiu0602** [comment]
When templateUrl is specified, http get with 'Accept' = 'application/json, text/plain, */*' ($httpProvider.headers.common) as request header. But for the page I enquired, different content will be returned when accept header with value "application/json" or "text/plain" comes first

For my case, 'text/plain' should come first, now I have to set it on $httpProvider.headers.common, but this affect global setting of $http. So I fail to achieve my aim with current release of AngularJS.

Thanks.

**Comment by pkozlowski-opensource** [comment]
OK, this sounds reasonable.

**Comment by pkozlowski-opensource** [comment]
We should allow people enhancing [httpOptions](https://github.com/angular/angular.js/blob/0681a5400e4150a961f9c8651e55623ca23b0cc2/src/ng/templateRequest.js#L37) in a provider.

**Comment by Narretz** [comment]
That has been possible for a while: https://github.com/angular/angular.js/commit/b2fc39d2ddac64249b4f2961ee18b878a1e98251
