### ISSUE TITLE
Using $httpBackend the whenGET().respond() method doesn't trigger $http's callback methods

### ISSUE THREAD

**Issue by micahblu** [angular/angular.js#11823]
I expected the following to work (I have commonly seen the usage)

```js
$httpBackend.whenGET('/users').respond(function () {
  return [{ name: "Alice" }, { name: "Bob" }];
});

$http.get('/users').then(function (response) {
  console.log(response);
});
```

The issue is the `then` method is never invoked, however if I use:

```js
$httpBackend.whenGET('/users').respond([{ name: "Alice" }, { name: "Bob" }])
```
or

```js
$httpBackend.whenGET('/users').respond(function () {
  return [{ name: "Alice" }, { name: "Bob" }];
}());
```
The `then` method will work and the data is passed as expected. Perhaps anonymous functions aren't supported here anymore?

**Comment by gkalpak** [comment]
According to [the docs][1]:

> **respond**
>> `function([status, ]data[, headers[, statusText]])`
>> OR
>> `function(function(method, url, data, headers)`

> The `respond` method takes a _set of static data_ to be returned or a _function_ that can return _an array_ containing response status (number), response data (string), response headers (Object), and the text for the status (string). [...]

Although, the `status` argument is optional in the _static data_ version, in the _array-returning function_ version it isn't.

What this means, is that if you chose to use a function, it should return an array containing _status_, _data_ etc. E.g.:

```js
$httpBackend.whenGET('/users').respond(function () {
  return [200, /* the data goes here, e.g.: [{name: 'Alice'}, {name: 'Bob'}] */];
});
```

--
[CodePen demo][2]

[1]: https://docs.angularjs.org/api/ngMock/service/$httpBackend#when
[2]: http://codepen.io/ExpertSystem/pen/yNYZOj?editors=001

**Comment by micahblu** [comment]
Thanks for the clarity, totally missed that :)

**Comment by abiodun0** [comment]
```         $httpBackend.whenGET(/\/api\/v1\/mentors\/(.+)/)

              return [400, 'phone', {}];
  });```
This method on use with httpintercept or responseError returns a function whenever its a bad request please look into this

**Comment by gkalpak** [comment]
@abiodun0, your code isn't valid JS (maybe some copy-paste error).
Please provide the correct code that doesn't work :smiley:

**Comment by abiodun0** [comment]
@gkalpak I just updated the code. My bad i wasn't looking at it directly.

**Comment by gkalpak** [comment]
@abiodun0, not sure what the issue is. Please create a live demo of the issue (you can use [this pen][1] as a starting point).

[1]: https://codepen.io/ExpertSystem/pen/rxEKPq?editors=0010
