### ISSUE TITLE
[ng-aria] 'aria-disabled' attribute must not be set along with the 'disabled'

### ISSUE THREAD

**Issue by damiengarbarino** [angular/angular.js#11830]
Hello,

When using angular aria, if the ng-disabled directive is set on an element and the condition is resolved to 'true', the aria-disabled element is also set automatically.

The W3C mentions that the aria-disabled attribute must not set if the disabled attribute (installed by ng-disabled) is already supported by the DOM element (ex: button).

See: http://www.w3.org/TR/aria-in-html/ look for "disabled"

>Use the disabled attribute on any element that is allowed the disabled attribute in HTML5.
>Only use the aria-disabled attribute for elements that are not allowed to have a disabled attribute in HTML5

Regards

**Comment by Narretz** [comment]
We should only set `aria-disabled` "for elements that are not allowed to have a disabled attribute in HTML5". I assume the allowed elements are these: http://www.w3.org/TR/html5/disabled-elements.html
