### ISSUE TITLE
Updating two different inside the same attribute

### ISSUE THREAD

**Issue by mwils-bp** [angular/angular.js#11831]
I've just posted a question about this on stackoverflow, but haven't received anything near what im looking for:

How could I update these scopes
```
    $scope.name = "";
    $scope.username = "";
```
Inside of one ```ng-model```?

    <input type="text" ng-model="name && username"/>

http://stackoverflow.com/questions/30105340/update-two-objects-in-ng-model

**Comment by pkozlowski-opensource** [comment]
@manuel-woelker actually you did get a good answer: http://stackoverflow.com/a/30105826/1418796
Using $parsers and $formatters is the way to go

**Comment by mwils-bp** [comment]
Yes, I only just seen this!

**Comment by pkozlowski-opensource** [comment]
Not sure if it should land in core. But if someone can come up with a good syntax and small impl, this could be considered. Till we've got very solid proposal, it is better to keep it as user-extension.

**Comment by gkalpak** [comment]
It really seems unnecessary/out-of-scope to have two-way databinding to 2 properties (I can't even think of any reasonable usecase).

I also find `$parsers`/`$formatters` to be a little too much for this.

How about "plain old" `ngModelOptions`'s `getterSetter` ?

**Comment by Narretz** [comment]
@gkalpak parsers are older than getterSetter ;)

**Comment by gkalpak** [comment]
@Narretz, true (but still missing your point :smiley: - it's not like it is an old question/answer).

Ah, I see; you are referring to my `"plain old"`. Yeah, it's not actually `plain old`, that's why it is inside quotes :stuck_out_tongue:

**Comment by mwils-bp** [comment]
Here is a great answer for using ```getterSetter```:

http://stackoverflow.com/questions/30105340/update-two-objects-in-ng-model/30109606#30109606

**Comment by gkalpak** [comment]
Hey, that guy's using my avatar :stuck_out_tongue: 

<sub>I just wanted to also add this approach for completeness :)</sub>

**Comment by mwils-bp** [comment]
I did notice that and wasn't too sure if it was you :)

Its a lot cleaner to work this way and is really customisable.
