### ISSUE TITLE
Feature Request: add introspection hooks or perf metrics or strict mode for $parseProvider for dev build

### ISSUE THREAD

**Issue by erwinmombay** [angular/angular.js#11844]
(my apologies if i should have broken out the request into smaller requests)
hello, I'm a new contributor to https://github.com/angular/angular-hint which is a dependency of https://github.com/angular/angularjs-batarang

We usually have to decorate core services and monkey patch prototype methods to be able to introspect application metrics like watch expression performance etc. Now one problem we have is that, to do this we usually intercept the expression a user is passing into `$watch` and replace it with a function (that runs the perf timers around the expression) and of course this function gets passed into `$parse` but this whole behavior breaks down if the original expression was a one time binding since `$parse` will run its `oneTimeWatchDelegate` function and will always treat it as a normal watch. We do have some solutions to get around this but we thought at this point we might as well ask the angular team if it would be possible to implement some hooks or perf metrics in the development build.

Another feature we would like to have if possible is a strict parse mode in development where the user will get an error for accessing properties on null/undefined (i believe @btford has implemented an experimental for of this before?).

let me know if you guys need any more information and of course we are more than happy with any compromised solution or advice on how to get these metrics.

**Comment by petebacondarwin** [comment]
@erwinmombay are you still interested in working on this?

**Comment by gkalpak** [comment]
Closing due to lack of interest :smiley:
<sub>(Glad to re-open if anyone is still interested.)</sub>
