### ISSUE TITLE
Allow ng-trim to work on radio buttons

### ISSUE THREAD

**Issue by Drarok** [angular/angular.js#11859]
I'd like to have the option to use ng-trim on radio inputs, not just text inputs. I'm using Angular 1.2.x, but have confirmed the feature is not available in 1.3.x or 1.4.x.

JSFiddle example against 1.4.x: http://jsfiddle.net/rgewfgbL/5/

**Comment by Narretz** [comment]
`ngTrim` is used to trim user input, i.e. trailing / leading whitespace in text inputs. If the value for radio buttons contains white space is in 90% of all cases at the discretion of the developer. If you use user defined values for your radio, I can see whitespace being an annoyance, but this is simply not what ngTrim is about. It's about trimming user input text. So I don't think ngTrim for radios is something we want.

**Comment by pkozlowski-opensource** [comment]
@Narretz while I agree with your analysis, it looks odd that this radio button is not selected, no?

**Comment by Narretz** [comment]
Yeah, that's odd ...

**Comment by Narretz** [comment]
When the `value` is retrieved from the element, whitespace is automatically trimmed by the browser (Firefox at least). We could trim the $viewValue in this case, too  to match this behavior. However, I don't know what the spec says about this.

**Comment by Narretz** [comment]
It's also possible that the trimming happens when angular creates the `attrs` for the directive.

**Comment by Drarok** [comment]
I've created an updated fiddle that shows the value as seen by the browser, and proves this to be an _Angular_ problem, not a browser one: http://jsfiddle.net/rgewfgbL/6/

**Comment by flatr0ze** [comment]
Please fix this one.

` <input type="radio" ng-model="format" ng-trim="false" value=" " /> ` sets $scope.format to an empty string (""), not to a " ". Using the &amp;nbsp; and similar tricks does not work.
