### ISSUE TITLE
materialize production deployment config does not include angular-material assets

### ISSUE THREAD

**Issue by philBrown** [angular/angular.js#11857]
As it looks like somebody deployed the *materialized* version of docs to production (see https://github.com/angular/angular.js/issues/11856), I thought I'd take the opportunity to point out that the [`docs/config/services/deployments/production.js`](https://github.com/angular/angular.js/blob/11601c7eb28b918a41dc369f0d61d013c3f292de/docs/config/services/deployments/production.js) script does not include any of the required angular-material assets or dependencies (angular-aria) or themes.

**Comment by caitp** [comment]
The materialize branch isn't meant to be deployed at the moment, this is most likely an issue in one of the jenkins scripts not checking the branch. We don't want to "fix" this by incorporating the material stuff on master

**Comment by philBrown** [comment]
@caitp I was more pointing out that `production.js` should look more like `default.js`.

Just something that seems to have been overlooked in the materialize branch.
