### ISSUE TITLE
Online documents down

### ISSUE THREAD

**Issue by LearnShare** [angular/angular.js#11856]
<https://docs.angularjs.org/>

![image](https://cloud.githubusercontent.com/assets/3265208/7579159/ea0affea-f891-11e4-9322-dabf846425d9.png)

>Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.0-rc.1/$injector/modulerr?p0=docsApp&p1=Err…pis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0-rc.1%2Fangular.min.js%3A18%3A381)

**Need documents now?**

Goto <https://code.angularjs.org/>, get documents like <https://code.angularjs.org/1.3.15/docs/api>.

Or you can download a release pack like <https://code.angularjs.org/1.3.15/angular-1.3.15.zip>, and run it on your computer.

**Comment by mattoz0** [comment]
Silly me clicked the link and was disappointed to not be able to see what error :dancer:

**Comment by LearnShare** [comment]
@mattoz0 maybe you should "Disable cache" and try `Ctrl+R` ?

**Comment by jintoppy** [comment]
Same error for me as well.

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.0-rc.1/$injector/modulerr?p0=docsApp&p1=Err…pis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.0-rc.1%2Fangular.min.js%3A18%3A381)

**Comment by mattoz0** [comment]
no dice. emptied the cache and hard refreshed. Error persists.

**Comment by jintoppy** [comment]
@LearnShare I think what @mattoz0  meant is clicking on the error link ie. http://errors.angularjs.org also pointing to the same doc site which is down.  That is funny :-)

**Comment by mattoz0** [comment]
Thats exactly what i meant :) Yes it is quite funny! Except all angular error messages point through this system, so sorry for anyone currently debugging :+1:

**Comment by LearnShare** [comment]
@jintoppy @mattoz0  yeah, I got that now, really funny :laughing:

**Comment by philBrown** [comment]
The docsApp has a dependency on `ngMaterial` but that script isn't there.

**Comment by caitp** [comment]
I don't think any human deployed the materialize branch, but yes, it looks like jenkins pushed it up to the docs site. That's not ideal :( The weird thing is that the materialize branch has been around for a while and hasn't broken anything yet, so what changed?

**Comment by philBrown** [comment]
@caitp I get the feeling nobody runs the materialize branch in prod mode :)

**Comment by jeffbcross** [comment]
Blegh. Ci job that updates docs hadn't been running for over a week, so when I brought the ci server back online, it built again and broke something. Working on restoring now

**Comment by jeffbcross** [comment]
Temporarily fixed by restoring 1.4.0-rc.1 on all instances, and disabled the ci job that re-builds the docs. I'm not sure what went wrong in the build process, but I'll discuss with @petebacondarwin in the morning, so we can re-enable the build to have latest docs.

**Comment by gkalpak** [comment]
This is strange. The materialize branch is lying there for months. How come it didn't cause problems before ?

**Comment by jeffbcross** [comment]
Someone duplicated the angular master jenkins job that automatically pushes build artifacts to docs.*, with the only change being that it built from the material branch :/. So it was building from material branch and then pushing assets to the docs production endpoint. I've disabled this job as well.

**Comment by jeffbcross** [comment]
I'm looking at the update script now, and it should never pull from a workspace other than the master job, so I'm a little confused. But the snapshot folder is definitely from this build: https://ci.angularjs.org/job/materialize-angular/9/

The zip file from the old snapshot folder in production is angular-1.4.0-build.9+sha.e203264.zip, which is the build number and revision from the materialize-angular job.

I'll have to look at it with fresh eyes in the morning :)

**Comment by petebacondarwin** [comment]
When Jenkins was not available externally, I changed the build scripts to push directly to the code.angularjs.org repository.

**Comment by jeffbcross** [comment]
That makes sense

**Comment by Narretz** [comment]
This is resolved, right?
