### ISSUE TITLE
ng-include-template

### ISSUE THREAD

**Issue by pranaydutta89** [angular/angular.js#11861]
at present we are passing url in ngInclude can we have a feature so that we can pass static templates     or variables containing templates ,the same way we do it in ngRoute

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean by "static templates" exactly, I believe that this is already covered by: ability to embed templates inside HTML using `<script>` directive: https://docs.angularjs.org/api/ng/directive/script

Please provide more info if this doesn't work for you.

**Comment by pranaydutta89** [comment]
ngInclude require's a src, if i keep the html in a variable can we bind that particular variable to ngInclude

**Comment by Narretz** [comment]
That's not very angular like. It would require you to have the template on a scope property or in a string literal, no?

**Comment by pranaydutta89** [comment]
ya in my project we are serializing the html and keeping it in a variable that works good when passing to template in ngRoute but the same i wanna do in ngInclude but seems not feasible at this point. i think this feature can be usefull

**Comment by guillaume86** [comment]
You can manually put your template in the $templateCache with an id and ng-include will be able to pick it up.

**Comment by Narretz** [comment]
@guillaume86 is right, this is the way to go.
