### ISSUE TITLE
Angular Js Controller

### ISSUE THREAD

**Issue by skdeli** [angular/angular.js#11869]
I am trying to get a dialog with list items, but once the ng-controller is added to list items, or the table tag, none of the items are click-able, how can I solve this problem? Why does the ng-controller disable clicking?

**Comment by nosideeffects** [comment]
Please direct questions like this to the mailing list: https://groups.google.com/forum/#!forum/angular

**Comment by pkozlowski-opensource** [comment]
@nosideeffects is right: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
