### ISSUE TITLE
orderBy doesn't reverse order if no predicate specified.

### ISSUE THREAD

**Issue by wawyed** [angular/angular.js#11866]
According to the documentation: https://docs.angularjs.org/api/ng/filter/orderBy.
> If no property is provided, (e.g. '+') then the array element itself is used to compare where sorting.

This seems to be working fine in 1.3.5 but it seems to have been broken in 1.3.6+.

Probably caused by: https://github.com/angular/angular.js/commit/8bfeddb5d671017f4a21b8b46334ac816710b143

Plnkr with the issue: http://plnkr.co/edit/vaOJzuDdkJUookDVSuDK?p=preview

**Comment by hena-3** [comment]
I also checked this issue -
In 1.4 -  
1. If no property given then its giving in same order (ascending of array elements) (correct according to doc)
2. if '-'is given even then its giving in same order(ascending of array elements) (Bug)

In 1.3 -  
1. If no property given then its giving in reverse order (descending of array elements) (Bug)
2. if '+'is given even then its giving in reverse order(descending of array elements) (Bug)

**Comment by hena-3** [comment]
In this issue -  
Its working fine when using simple array element(string array or number array), but does not work with array of objects .
For array of objects we can JSON.stringify the object and then compare, as .toString() will not work for objects.
I have checked its working with JSON.stringify. 
Please let me know if this approach is ok, I will send the pull request.

**Comment by Narretz** [comment]
Hi @hena-3 feel free to submit a PR, we'll review it. Though JSON.stringify sounds a bit unperformant, but we'll see.
