### ISSUE TITLE
Problem with <input type="email" /> and ngAnimate

### ISSUE THREAD

**Issue by sravenhorst** [angular/angular.js#11862]
Hi!

There was a bug reported about ngAnimate killing the email validation. The model gets updated correctly, but the classes aren't: https://github.com/angular/angular.js/issues/11652

This bug still exists unfortunately. The jsbin by @gkalpak in the other post does load angular-animate.js, but doesn't inject the "ngAnimate" module into the app module. Thats why it seems to work in his jsbin.

I forked & updated his jsbin to reproduce the bug: http://jsbin.com/tiwijowiza/3/edit

didn't know if the old one can be re-opened, so thats why i added this as a new issue.

Thanks in advance!

Cheers,
Sander

**Comment by gkalpak** [comment]
Closing as a duplicate if #11652 (since the other issue has a little more context).
Copied the jsbin that show the issue.
