### ISSUE TITLE
$httpBackend.wenGET() no longer supports .passThrough()?

### ISSUE THREAD

**Issue by victorwoo** [angular/angular.js#11879]
I'm using karma to do a **unit test** on an angular.js application, and have included "`angular-mock.js`" & injected `ngMock` module to my app's module. If I don't do anything else, the $http.get() in the tested code doesn't make any action. After a search, I found this resolution:

Add the following code to testing code:

```javascript
$httpBackend.whenGET(/.*/).passThrough();
```

But it produces the following error:

    $httpBackend.whenGET(...).passThrough is not a function

I'm using angular 1.3.15 & angular-mocks 1.3.15

**Comment by gkalpak** [comment]
`passThrough()` is **not supported** by `ngMock` as it is not intended for unit test.
It is intended for e2e tests and therefore only provided by `ngMockE2E`.

You can find several examples of how to use `$httpBackend` in uit tests on the relevant [docs page][1].

--
Closing this as _working as expected_. Feel free to reopen if you determine there is indeed some issue in `ngMock`.

[1]: https://docs.angularjs.org/api/ngMock/service/$httpBackend

**Comment by victorwoo** [comment]
But if I need to use the real online data, what's the best practice?

**Comment by gkalpak** [comment]
There are two best practices regarding real online data in tests I think:

1. Don't use them in unit tests (unit tests do not need real online data, they need to be fast and use mock data if necessary).

2. Use them in e2e tests if you have/want to.

<sub>(I am speaking for myself, of course, but I think those are commonly accepted best practices.)</sub>

**Comment by gkalpak** [comment]
BTW, #1434 has a little more context and some work-arounds. (I wouldn't recommend them though.)
