### ISSUE TITLE
How get a list of available modules in within some parent module?

### ISSUE THREAD

**Issue by diosney** [angular/angular.js#11884]
**Setup:**

Several angularjs modules declared as:

    angular.module('a', ['a.b']);

    angular.module('a.b', ['a.b.c1', 'a.b.c2']);

    angular.module('a.b.c1', []);

    angular.module('a.b.c2', []);

**Question:**

Is there a way to get all children modules from a specific parent module?
I mean something like:

    angular.module.getChildrenFromParent('a.b');

That should return an array of strings or an array of references to the modules `a.b.c1` and `a.b.c2`.

Thanks

**Comment by petebacondarwin** [comment]
Here: http://plnkr.co/edit/6xEzK2lSAxbsEBHcHq54?p=preview

**Comment by diosney** [comment]
Thanks! I missed that from documentation.
