### ISSUE TITLE
directive.link() + $compile = Infinite Loop 

### ISSUE THREAD

**Issue by Davidx7** [angular/angular.js#11889]
Will create an infinite loop and block the browser. 

```javascript
function bigView($timeout, $compile, $rootScope) {
		return {
				restrict: "AE",
				scope: {
					source      : "=Source",
				},
				transclude: true,
				link: function($scope, $element, $attrs) {
                    $compile($element)($scope); 
                }
       }
}

angular.module('xx').directive('bigView', bigView) 
```

**Comment by caitp** [comment]
But of course it creates an infinite loop, as your link function creates and calls a new link function for the same element. There's no way for us to know you're doing this, but it makes no sense to do it, so don't

**Comment by caitp** [comment]
But of course it creates an infinite loop, as your link function creates and calls a new link function for the same element. There's no way for us to know you're doing this, but it makes no sense to do it, so don't
