### ISSUE TITLE
$logProvider bug

### ISSUE THREAD

**Issue by furyscript** [angular/angular.js#11882]
Hi all 
I found this possible bug with enable/disable $log with $logProvider.
As you can see in this fiddle
```
http://plnkr.co/edit/HZCAoS?p=preview
```
When you set false debugEnabled always display log.
Why??

**Comment by gkalpak** [comment]
You were setting `debugEnabled(true)` (which means "enable debug logs").
If you set `debugEnabled(false)`, the debug logs are suppressed ([plnkr][1]).

[1]: http://plnkr.co/edit/LqIYLl2jKNwLkpAlweCX?p=preview
