### ISSUE TITLE
ng-repeat on tr won't generate proper columns

### ISSUE THREAD

**Issue by megh1207** [angular/angular.js#11886]
<div ng-app="app" ng-controller='testController as ctrl'>
<table>
  <tr ng-repeat='col in ctrl.columns' >
      <td>{{col.name}}</td>
    </tr>
</table>
</div>

angular.module('app', [])
.controller('testController', function() {
    this.columns = [{name:'test1'},{name:'test11'}];
});

I am using this method to generate columns dynamically but every time I tries angular generate rows, please review my and let me know.

**Comment by ircnelson** [comment]
Hi @megh1207, you are using "this.columns", try $scope.columns and use in the "ng-repeat":

<ul> <li ng-repeat="column in columns">{{column.name}}</li></ul>

**Comment by megh1207** [comment]
I am using table tag to generate tr

**Comment by ircnelson** [comment]
ok @megh1207, keep focus on the **$scope.columns** instead of this.columns...

**Comment by megh1207** [comment]
I have used both but result remain same.

**Comment by ircnelson** [comment]
try the code below, but if you can put more of your code in gist, I would be grateful.

```
angular.module('app', [])
.controller('testController', TestController);

TestController.$inject = ['$scope'];

function TestController($scope) {
$scope.columns = [{name:'test1'},{name:'test11'}];
}
```

**Comment by megh1207** [comment]
here check my code,

http://jsfiddle.net/megh1207/r2L064md/1/

I need to render value column wise but it rendering row wise that is my issue.

**Comment by gkalpak** [comment]
You are `ngRepeat`ing the `<tr>` element (i.e. the rows). You should put `ngRepeat` on the `<td>` or `<th>` elements (i.e. the cells).

E.g.:

```html
<table>
  <tr>
    <th ng-repeat="col in ctrl.columns">
      {{ col.name }}
    </th>
  </tr>
</table>
```

--
That said, this is a general support question and should have been directed to the [appropriate channels][1].
(GithHub is reserved for bug reports and feature requests.)

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
