### ISSUE TITLE
Email validation cleaning input using $compile

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [angular/angular.js#11892]
Hello! I have an input of type email, with required attribute, if I type, for example, "asd@asd." the input's value is cleared. But it only happen, if using a directive that recompile the DOM fragment the input stands.

Here's the issue simulated:

http://plnkr.co/edit/zhaTr0KCCLH4ALD6pGkb?p=preview

If use ng-pattern="/^[_a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/" on the input, the problem does not happen anymore (for just ".com", not ".com.br").

**Comment by Narretz** [comment]
You are not supposed to recompile already compiled nodes; in fact, it's not supported by the compiler. I assume some validator or such gets added again during validation and messes with the input.

**Comment by raphaelduartepinheiro** [comment]
@Narretz, I understand, but in this case the compiler should not be intelligent enough to not mess things up? Since you have to compile a node, and inside this node, have already compiled elements, some inputs can stop working properly.

**Comment by raphaelduartepinheiro** [comment]
AFAIK, it only happen with email type.

**Comment by Narretz** [comment]
Sorry, like I said, recompiling already compiled conent is not supported and we don't plan on doing this.
