### ISSUE TITLE
Bug: Directive Object attributes  <mydirective attributes="{test: myArray}" /> generates an error

### ISSUE THREAD

**Issue by aug-riedinger** [angular/angular.js#11893]
I have been struggling debugging this.

Here's a [fiddle](http://jsfiddle.net/00h1Lf6f/) reproducing the bug.

Basically, with the following controller code:

```
    $scope.myArray = [3, 4, 5, 6, 7];
    $scope.object = {test: $scope.myArray};
```
The following template:
```
  <mydirective attributes="myObject"></mydirective>
```
Should be equivalent to:
```
  <mydirective attributes="{test: myArray}"></mydirective>
```

The second example *works*, but generates an error in the console.

In the fiddle, it is:
`angularjs.org/angular-1.0.1.js:5526 Error: 10 $digest() iterations reached. `
but in my code it was `RangeError: Maximum call stack size exceeded` on the `equals` method.

It seems like some useless evaluation is done in that case. Don't know exactly why.

**Comment by ryanhart2** [comment]
Any reason you are using version 1.0.1? I got your fiddle to work by using version 1.3.15 and adding the line ```myApp.controller('MyCtrl', MyCtrl);```

**Comment by aug-riedinger** [comment]
No reason indeed... I must have forked an old fiddle.

It means I haven't reproduced the bug because in my app, I'm using `1.3.13`. And I tried with it also, and it also works.

I guess I should close the issue as there are very few chances now I can reproduce the bug.
