### ISSUE TITLE
tabs inside of toolbar

### ISSUE THREAD

**Issue by dohomi** [angular/angular.js#11902]
Hi Guys,

Is there any plan of giving tabs a stylesheet that it fits to the background of toolbars, or that tabs would be placed inside of the toolbar? According to the specs http://www.google.com/design/spec/components/tabs.html#tabs-types-of-tabs it seems to be quite heavily used. I've seen this behavior now on several apps. Thanks for looking into this.

**Comment by gkalpak** [comment]
I think you are looking for _Angular Material_ repo. (This one is the core AngularJS repo.) 
Please reopen in https://github.com/angular/material.

**Comment by dohomi** [comment]
@gkalpak sorry my bad, too many tabs open
