### ISSUE TITLE
angularjs Error: [ngModel:numfmt]  

### ISSUE THREAD

**Issue by erajay** [angular/angular.js#11909]
angularjs Error: [ngModel:numfmt]  Shows Errors when i pass data from controller to model in Input type =Number... Any solution for this problem..Please reply

**Comment by Narretz** [comment]
`input[number]` requires your model to always be a number. You can transform your model data before you set it on the scope, or implement a custom formatter that runs before the built-in formatter.

**Comment by erajay** [comment]
Any example hows we can use formatter for number . Even i have used a number from controller to model in input[number] but its shows error
