### ISSUE TITLE
Broken transformer in 1.4rc2

### ISSUE THREAD

**Issue by arcanis** [angular/angular.js#11906]
Hi,

I'm uploading binary data with something like this:

```js
$httpProvider.defaults.transformRequest = [ function ( data, getHeaders ) {
    var headers = getHeaders( );
    headers[ 'content-type' ] = undefined;
    return new FormData();
} ];
```

It doesn't work anymore. Angular seems to always send it as application/json.

**Comment by Narretz** [comment]
Can I get that as Javascript? I think it's because of this: https://code.angularjs.org/snapshot/docs/guide/migration#server-requests-http-

**Comment by arcanis** [comment]
Sure, I've edited my post.

However, despite not being documented, this behavior was (as far as I know) the only way to correctly send binary data to a server without having to set the header manually each time. It's really comes handy when an application has to send binary data "all over the place".

An alternative which would be fine by me would be to give Angular the knowledge to automatically create a FormData instance and use the multipart/form-data content-type when the data contains at least one Blob (since they cannot be sent via json anyway).

For reference, here is my current custom request transformer (in es6):

```js
export var httpTransformerSetup = [ '$httpProvider', ( $httpProvider ) => {

    $httpProvider.defaults.transformRequest = [ ( data, getHeaders ) => {

        if ( typeof data !== 'object' )
            return data;

        var keys = Object.keys( data ).filter( key => typeof data[ key ] !== 'function' );
        var deep = false, blobs = false;

        for ( var key of keys ) {
            if ( data[ key ] instanceof Blob ) {
                blobs = true;
            } else if ( typeof data[ key ] === 'object' ) {
                deep = true;
            }
        }

        if ( deep && blobs )
            throw new Error( 'Cannot send blobs while using deep json structures' );

        if ( ! blobs )
            return data;

        var headers = getHeaders( );

        headers[ 'Content-Type' ] = undefined;

        var formData = new FormData( );

        for ( var key of keys )
            formData.append( key, data[ key ] );

        return formData;

    }, data => {

        if ( typeof data !== 'object' )
            return data;

        if ( data instanceof FormData )
            return data;

        return JSON.stringify( data );

    } ];

} ];
```

**Comment by pkozlowski-opensource** [comment]
@arcanis you can still have this logic in an interceptor which is free to modify any property of a config object.

**Comment by Narretz** [comment]
I agree with @pkozlowski-opensource
