### ISSUE TITLE
Get directive instance (for Webpack hot module replacement)

### ISSUE THREAD

**Issue by jgoux** [angular/angular.js#11904]
Hello,
I'm experimenting with Webpack hot module replacement (http://webpack.github.io/docs/hot-module-replacement.html) and Angular.
I want to be able to modify a directive's template or controller without reloading the browser.
For this purpose, I think I need to find a way to get the directive instance from the module where it's registered, then I could apply patches to the instance and maybe rerender the directive.
So, is it possible to get a directive instance ? :)
I think this could be a really interesting project but I need some help.

EDIT : Here are two projects using hot module replacement : 
- https://github.com/jlongster/monkey-hot-loader
- https://github.com/gaearon/react-hot-loader

**Comment by yargalot** [comment]
Been playing around with that [here](https://github.com/yargalot/Angular-HMR) for angular apps in webpack.

Seems to work with Directives and controllers, trying to get factory and services going.

**Comment by matt-d-rat** [comment]
+1 ideally we need something that can hook into the entire AngularJS ecosystem, so whether I change a directive, controller, a property on scope or a template used, we should be able to hot load those changes into the application.

**Comment by timkindberg** [comment]
+1

**Comment by monteirocode** [comment]
+1

**Comment by yargalot** [comment]
Well one of the issue is the internal cache on the providers. You cant get to it in its current implementation.

**Comment by lucaslago** [comment]
+1

**Comment by glebmachine** [comment]
+1

**Comment by karlhorky** [comment]
+1 would love to get support for hot module replacement in Angular.

**Comment by petebacondarwin** [comment]
I am afraid that hot-module replacement is not going to get into Angular 1.
It would require too much internal restructuring of the code base and major breaking changes to the public API to make it worth the effort. It would be better to consider trying Angular 2 instead, which will have much better support for this.
