### ISSUE TITLE
FIRSTDAYOFWEEK and WEEKENDRANGE defaults missing from ngLocale

### ISSUE THREAD

**Issue by poshest** [angular/angular.js#11922]
Are `$locale.DATETIME_FORMATS.FIRSTDAYOFWEEK` and `WEEKENDRANGE` defaults missing from [ngLocale](https://github.com/angular/angular.js/blob/master/src/ng/locale.js)?  

Those are present in each of the [locale data files](https://github.com/angular/angular.js/tree/master/src/ngLocale).  It seems to me that those are supposed to be added to the defaults, but just haven't yet?  Or did I miss something?

**Comment by Narretz** [comment]
Hi, both props have been added to the 1.4.x branch (1.4.0 release pending). They won't be backported to 1.3.x though, sorry!

**Comment by poshest** [comment]
Cool, thanks Narretz!  Wasn't expecting it to be backported.  :)
