### ISSUE TITLE
add support for shallow watch (&*) for 1-way bindings

### ISSUE THREAD

**Issue by bcherny** [angular/angular.js#11926]
```js
// works
scope: {
  foo: '=*'
}

// doesn't work
scope: {
  foo: '&*'
}
```

**Comment by matthewjh** [comment]
Maybe I'm misunderstanding something here, what makes you refer to &-bindings as one-way bindings?

Docs:
````
& or &attr - provides a way to execute an expression in the context of the parent scope.
````

`$scope.foo` would be assigned a getter for the expression in the foo attribute. I don't really see how deep/shallow watches are applicable here if what's being watched is a string (the expression).

**Comment by gkalpak** [comment]
There is no `$watch`ing involved in `&` bindings (neither deep, nor shallow).
@bcherny, could give an example of the issue you are running into or what your are trying to achieve ?

**Comment by bcherny** [comment]
according to the [docs](https://docs.angularjs.org/api/ng/service/$compile#-scope-):

> If you want to shallow watch for changes (i.e. $watchCollection instead of $watch) you can use =* or =*attr (=*? or =*?attr if the property is optional).

is far as i understand this is referring to bindings like:

```js
angular
.directive('myFoo', () => {
  return {
    scope: {
      foo: '=*',
      bar: '&'
    },
    template: `
      <div ng-repeat="f in foo"> ... </div>
      <div ng-repeat="b in bar()"> ... </div>
    `
  }
})
```

the first `ng-repeat` will re-render when a shallow equality check on `scope.foo` returns false. the second `ng-repeat` will re-render when a *deep* equality check on `scope.bar` returns false, which is less efficient than a shallow check.

**Comment by gkalpak** [comment]
@bcherny: Not quite :)

You seem to be under the impression that there is one binding from the parent scope to the `ngRepeat`, but there are actually 2 independent bindings (in each case). Namely, there is a binding between the isolate scope and its parent scope (either `@`, `=`, `=*` or `&`) and there is a binding between the isolate scope and the view (e.g `foo` or `bar()` in this case).

`ngRepeat` uses`$watchCollection` internally to watch the list of items to render, so as far as this binding is concerned, it makes no difference whether the data came into the isolate scope via a 2-way binding, a 1-way binding, direct assignment or whatever.

Regarding the isolate scope bindings, `=*` implies `$watchCollection` and `&` implies no watch (just a way to evaluate an expression in the context of the parent scope). So, there is nothing watch-related to optimize here.

--
In your example:

1. `foo: '=*'` + `ng-repeat...foo` = 2 x `$watchCollection`
2. `bar: '&'` + `ng-repeat...bar()` = 1 x `$watchCollection` (+ 1 extra function call, which should be negligible as long as `bar()` is _lightweight_)

Generally, when you don't need 2-way binding (i.e. you don't need to write back to the parent scope), a `&` binding should be more efficient. But, depending on your exact usecase, throwing in some one-time bindings would make both options even more efficient.

**Comment by bcherny** [comment]
thanks for the explanation @gkalpak! makes much more sense now!!
