### ISSUE TITLE
ionic cordova android $http.post 

### ISSUE THREAD

**Issue by vurgun533** [angular/angular.js#11921]
$http.get('http://192.168.1.58/api/service/GetList').then(function(resp) {
            alert(resp.status);
        }, function(err) {
            alert(err.statu); 
        })

internet explorer - chroom is working.
apk android run does not work

**Comment by atulrungta** [comment]
http://stackoverflow.com/questions/29826971/ionic-requests-return-404-only-on-android-in-chrome-it-works-fine

Just add whitelist plugin.. it will work.. It worked for me.. I was stucked from a week into this..!!

**Comment by pkozlowski-opensource** [comment]
OK, so this one sounds like a general support question that was answered on SO, and the initial problem seems to come from changes in Cordova. Closing, as it doesn't seem to be AngularJS specific problem.

**Comment by vurgun533** [comment]
http plugin
cordova plugin add cordova-plugin-whitelist 
I solved the problem by adding plugin

**Comment by shadesoflight** [comment]
+1 whitelist worked for me.

**Comment by emmychen** [comment]
@vurgun533 Yes.  add whitelist works!
