### ISSUE TITLE
Different behavior between $timeout and setTimeout in reading function input

### ISSUE THREAD

**Issue by cl-** [angular/angular.js#11924]
Different behavior between $timeout and setTimeout in reading function input.

    function aFunctionName(){
      console.log("this works");
    }
    setTimeout("aFunctionName()",1000); //this works in regular javascript

    $timeout(aFunctionName,1000); //this works
    $timeout("aFunctionName()",1000); //this does not work and throws error: TypeError: fn is not a function

**Comment by pkozlowski-opensource** [comment]
The $timeout service is [documented](https://docs.angularjs.org/api/ng/service/$timeout) as accepting only a function as an argument. Personally I don't think we should accept strings (and call eval on them), even if it works in JS (didn't check).

**Comment by Kadajett** [comment]
Yeah, maybe it should be kept explicitly. Having to call $timeout(namespace["aFunctionName"], 1000) Is much more strict. I would think it could help prevent bugs. You should probably know if a function exists before calling it and stuff.

**Comment by matthewjh** [comment]
In my opinion `$timeout` and `$interval` should align exactly with `setTimeout` and `setInterval` in terms of what params they accept.

**Comment by Narretz** [comment]
I am pretty sure we don't want this. `setTimeout('functionString()', 1000)` is bad practice, akin to using eval(), which is exactly what angulars expression parser / scope tree tries to prevent.
