### ISSUE TITLE
Selected dropdown option is not displayed by the browser (Chrome, IE)

### ISSUE THREAD

**Issue by juristr** [angular/angular.js#11929]
Hi,

I have a strange issue in that the selected option doesn't get displayed in Chrome and IE (while it works in Firefox):

![image](https://cloud.githubusercontent.com/assets/542458/7770056/678efa16-008a-11e5-9169-21f27df8c574.png)

although in the HTML it is selected:

![image](https://cloud.githubusercontent.com/assets/542458/7770061/7bcbffba-008a-11e5-9db3-4b137adfb727.png)

Here's the plunker to reproduce the case:
http://plnkr.co/edit/zYY8wwyVYbNUE5pwyYan?p=preview

**Note,** it also only happens in the mentioned browsers when I set the data asynchronously, that is, in the Plunkr (for demoing) through a $timeout, while in my production code it is fetched through an $http call.

I'm not quite sure whether it is due to some strange binding in my code or an issue within Angular itself, and since also the guys on the IRC channel were not able to help me, I'm posting it here :smiley: .

**Does not work in**

- Chrome (latest stable)
- Chrome 45.0.2409.0 canary
- Internet Explorer 11.0.9600.17801 (Win7)

**Works in Firefox 37.0.2 and 38.0.1**.

**Comment by ericmdantas** [comment]
As answered on the other issue, [this](http://plnkr.co/edit/NUIfW7G0JlGHvEUTEyZt?p=preview) might do the trick.

**Comment by juristr** [comment]
ya, this might eventually work. But it's still kinda strange it already works in IE and FF without this change of the code..

**Comment by Narretz** [comment]
This is fixed in the upcoming 1.4. Can you upgrade? It's problematic to fix this in 1.3.x, so it's unlikely that it will be fixed.

**Comment by juristr** [comment]
Ok, I see. I'll check whether I can upgrade. Thx

**Comment by Narretz** [comment]
We've decided not fo fix this issue in 1.3. See https://github.com/angular/angular.js/issues/11835#issuecomment-139913620 for more info
