### ISSUE TITLE
angular-sanitize.js strips id attribute for img tag

### ISSUE THREAD

**Issue by poonambaviskar** [angular/angular.js#11942]
Can we just include 'id' in the whitelist, i.e htmlAttrs variable in angular-sanitize.js?? Doing this does not  remove id attribute from img tag.

**Comment by petebacondarwin** [comment]
It looks like the commit that put this in is not well documented. See https://github.com/angular/angular.js/issues/8719

**Comment by mhevery** [comment]
the reason why we strip out `id` and `name` is that browsers put them on `window`

`<div id="angular">` would overwrite the `window.angular` with an element. This is considered a security issue and so we don't allow it.
