### ISSUE TITLE
Input type Date writes null to model on submit even on $pristine state

### ISSUE THREAD

**Issue by awerlang** [angular/angular.js#11940]
I have some input fields that are available to user when s/he clicks a button, they're disabled otherwise. That button creates a model. User will then submit a form.

The problem is when user doesn't clicks the button. I don't want the model to be implicitly created in that case. Angular creates because it runs `$commitViewValue()` on each control if `button[type=submit]`.

I believe it is a bug because it only happens if any input is a date. It won't happen with other fields.

**Angular Version(s)**: from v1.3 up to latest
**Browsers and Operating System**: tested on Chrome, IE 11
**Reproduce the Error** - http://plnkr.co/edit/OnVeASvzzHGXkeaEAaO5?p=preview

**Suggested Fix**: 

Either check if input is in `$pristine` state before writing to model, or have untouched date input have initial view value = null, instead of "".

**Comment by Narretz** [comment]
Not technically a bug, rather a limitation of the model $parsers api. A parser that returns `undefined` is considered invalid, so empty date inputs return `null`. It's far from perfect. :|
Here's a workaround. http://plnkr.co/edit/ruq3clPALPxovfZS1fxh?p=preview It's a bit clunky. However, why don't you want the model to be created implicitly in the first place?

**Comment by awerlang** [comment]
I can't let AngularJS creating my object implicitly, because, my ngModel looks like this:

```
ng-model="ctrl.currentRecord.phones[ctrl.lastIndex].phoneNumber"
```

It's an object inside an array, but AngularJS is only able to construct an `Object`, if `phones` is missing. This is also somewhat inconvenient and makes my back-end break. If it looks like an array access it should construct an array, if necessary. I'd open an issue for that but I guess that would be a breaking change.

Thanks for your hints.

**Comment by MiguelMike** [comment]
Actually it's much more severe.

Because the model value of a date input us changed to null, that input becomes dirty. I have a form where one of the date inputs can be initialized empty. When users clicks a button, the form is checked for dirty inputs. Because the model value of empty and untouched date input is changed it is considered dirty even though it shouldn't.
