### ISSUE TITLE
how to create folder/directory with auto generated id/name for each and every folder in AngularJs? AngularJs, MongoDB, Javascript, HTML, MKDir, Folder

### ISSUE THREAD

**Issue by JaayK** [angular/angular.js#11949]
down vote
favorite
I've got trapped in one more issue.

i want to create folder/directory automatically, whenever the user upload his/her image file from their system.

it should saved in server system in particular folder which should created automatically for each and every uploads with auto generated ID/ name for folders. well am okay with Javascript code also, but it could be if it is in AngularJs

if it is possible means. please share the codes.

Thanks a lot in advance guys. the following thing is my piece of code. code anyone tell me what's wrong in that?

router.post('/photo',[ multer(
  { 
    dest:'./uploads/',
        rename: function (fieldname, filename, req, res) {
           console.log(fieldname);
        console.log("=============");
       // console.log(req.body.can);
        console.log("=============");

        console.log(filename);
            //return filename.replace(/\W+/g, '-').toLowerCase() + Date.now()
                return filename
        },
        onFileUploadComplete: function (file, req, res) {
                 console.log(file.fieldname + ' uploaded to  ' + file.path)
               // res.json({"responseCode":1});
        },
        changeDest: function(dest, req, res) {
                 dest += '/uploads'+req.body.can;
                  if (!fs.existsSync(dest)) fs.mkdirSync(dest);
                  return dest;
        }

})
]);
  router.post('/photo', function (req, res) {
    id     : req.body.can
//console.log(req.body.can)
//;return;
        var form = {
            body: req.body,
            files: req.files
        }
        res.send(form);
    });

**Comment by Narretz** [comment]
This is a support question, and does not belong into this repo.
