### ISSUE TITLE
Directive resolution breaks in FF and Safari, if webcomponents.js is added to the page.

### ISSUE THREAD

**Issue by nicroto** [angular/angular.js#11954]
I have already posted the issue in the repo of Webcomponents.js, [here](https://github.com/webcomponents/webcomponentsjs/issues/321).

**Update:** I've made this, so you can test it even faster (check in Chrome - should work, and FF and Safari fail): http://plnkr.co/edit/r2GE2x4vTPBZscMTrn2u?p=preview

**Without** the webcomponents.js script, the `<custom-container>` from this markup:
```html
<!DOCTYPE html>
<html lang="en"><head>
	<title>Repro angular/webcomponents.js problem</title>

	<!-- It's OK when not using webcomponents.js -->
	<!-- <script src="bower_components/webcomponentsjs/webcomponents.js"></script>-->

</head>
<body ng-app="app">

	<custom-container></custom-container>

<script src="bower_components/angular/angular.js"></script>
<script src="js/app.js"></script>
</body>
</html>
```
is resolved to:
```html
<div>
    <span>Resolved!</span>
</div>
```
Here is my angular code:
```javascript
var app = angular.module( "app", [
  "custom-container-module"
] );

angular.module( "custom-container-module", [
    "inner-container-module"
  ] )
  .directive( "customContainer", function() {
    return {
      restrict: "E",
      replace: true,
      template: "<div><inner-container></inner-container></div>"
    };
  } );

angular.module( "inner-container-module", [] )
  .directive( "innerContainer", function() {
    return {
      restrict: "E",
      replace: true,
      template: "<span>Resolved!</span>"
    };
  } );
```

**The problem:**
 - If I uncomment this:
```html
 <!-- <script src="bower_components/webcomponentsjs/webcomponents.js"></script> -->
```

Only the first-level template is resolved (**Safari & FF**, haven't tested in IE or Opera and of course Chrome is OK). So, I just get this:
```html
<div>
   <inner-container></inner-container>
</div>
```

I've been debugging Angular since yesterday and I see that the inner template is found, but there is something weird about adding the elements to element.childNodes - element.childNodes seems to be immutable in Safari and FF...

Any help would be appreciated. Thank you very much for your time and effort.

**Comment by nicroto** [comment]
I believe I've narrowed the problem down to a specific function (line) in angular.js: https://github.com/angular/angular.js/blob/bab474aa8b146f6732857c3af1a8b3b010fda8b0/src/ng/compile.js#L1777

The significant part of the callstack is:
```
replaceWith
applyDirectivesToNode
compileNodes
compile
```

Although replaceWith transfers successfully the parsed nodes into the provided dom element, after applyDirectivesToNode finishes, and the selector is back in the compileNodes function, `nodeList[ i ].childNodes` is empty. The `childNodes`, that's been edited in `replaceWith<-applyDirectivesToNode` is the one that is actually rendered since the first directive is resolved and successfully rendered. But the one that `compileNodes` continues its work with seems like an outdated **copy**.

What is more childNodes seems to be an immutable property and `nodeList[i].childNodes === nodeList[i].childNodes` produces `false`...

My guesses, at this point are 2:
 * Either Node.replaceChild (which is replaced by webcomponents.js) does something wrong;
 * Or node.childNodes is to blame.

I am aware there is always a third option - I'm only observing a symptom of a far-away cause. That's why I am hoping someone from the contributors would jump in.

I'll keep the updates on my progress (will not just sit and wait for someone to help), but if you have an idea, please do chime in. Thanks!

**Comment by nicroto** [comment]
I'm 95% sure that the problem is Node.childNodes.

`replaceWith<-applyDirectivesToNode` successfully updates the DOM. But after the selector returns in the `compileNodes` function, it continues work with an outdated `nodeList`, where the `<custom-container>` element is not replaced with a `div`, so it doesn't have its child `<inner-container>`. And therefore the `<inner-container>` isn't resolved.

**Comment by nicroto** [comment]
100% sure `Node.childNodes` is the problem.

If I renew the collection `nodeList` after applyDirectivesToNode has finished, all directives are resolved.

```javascript
function compileNodes(nodeList, transcludeFn, $rootElement, maxPriority, ignoreDirective,
												previousCompileContext) {
	var linkFns = [],
			attrs, directives, nodeLinkFn, childNodes, childLinkFn, linkFnFound, nodeLinkFnFound;

	// <FIX PART 1>
	var parentNodePreserved;
	if ( nodeList.length && !( nodeList.length === 1 && nodeList[ 0 ].nodeName === "BODY" ) ) {
		parentNodePreserved = nodeList[ 0 ].parentElement;
	}
	// </FIX PART 1>

	for (var i = 0; i < nodeList.length; i++) {
		...

		nodeLinkFn = (directives.length)
				? applyDirectivesToNode(directives, nodeList[i], attrs, transcludeFn, $rootElement,
																	null, [], [], previousCompileContext)
				: null;

		// <FIX PART 2>
		if ( parentNodePreserved ) {
			nodeList = parentNodePreserved.childNodes;
		}
		// </FIX PART 2>

		...
	}

	// return a linking function if we have found anything, null otherwise
	return linkFnFound ? compositeLinkFn : null;

	...
}
```

But I am not sure - should this be fixed in Angular or WebComponents.js...?

**Comment by petebacondarwin** [comment]
Given the discussion in the WebComponents project - in particular https://github.com/webcomponents/webcomponentsjs/pull/393 - I feel that it is understood that this is on a problem with Angular but with how WebComponents is polyfilling incorrectly.
