### ISSUE TITLE
1.3.x and 1.2.x tags lost in bower-angular repository

### ISSUE THREAD

**Issue by Hacklone** [angular/angular.js#11950]
Hello,

Somehow the older angular version tags disappeared from the bower-angular repository.
Could you push those back, we use bower to collect packages and it fails at every build?

Thanks

**Comment by IgorMinar** [comment]
I can't reproduce this issue. The repo [has all the tags](https://github.com/angular/bower-angular/releases/) and `bower install angular#1.3.5` does the right thing.

Can you provide steps to reproduce the issue please?

**Comment by Hacklone** [comment]
Oops a dependency package caused it.
Closing this, sorry for your time.
