### ISSUE TITLE
A problem with boolean expression evaluation in 1.4

### ISSUE THREAD

**Issue by SamuraiPrinciple** [angular/angular.js#11959]
Greetings,

After upgrading to angular 1.4 we're having a problem with expressions like:

true && aMissingObject.aMissingProperty

They evaluate to true, instead of false (incidentally, true && !!aMissingObject.aMissingProperty evaluates to false).

Here is an example on plunkr:

http://plnkr.co/edit/4wVwHOO3lsc10JaSrIXI

Could you please comment if this is expected behaviour?

Many thanks

**Comment by Narretz** [comment]
Thanks for the report. This happens since 1.4.0-rc.3, so it looks like it's caused by the parse refactor. @lgalfaso can you take a look?

**Comment by lgalfaso** [comment]
@SamuraiPrinciple thanks for reporting this! The fix landed and should be part of the next release

**Comment by SamuraiPrinciple** [comment]
Indeed - just tried it on master and it works like a charm.

Much appreciated

**Comment by christianv** [comment]
@lgalfaso any idea on when this might land?

**Comment by lgalfaso** [comment]
This already landed and should be part of 1.4.1 once released

**Comment by jziggas** [comment]
Commenting on here as I can't seem to find anything related, I just ran into an issue similar to this. I had a line of code `this.canEdit = this.item && this.item.id` where I would normally expect the value to short-circuit to `false` when `this.item` is `undefined`, however it evaluated `this.canEdit` to `undefined`!

I had to rewrite the line to `this.canEdit = this.item !== undefined && this.item.id !== undefined` for it to evaluate to a boolean value. Weird?

**Comment by codymikol** [comment]
This is actually the github for angularJS 1.x, but what you're doing is essentially evaluating 

this.canEdit = undefined && 'Not Undefined'

Which does return undefined, so it seems to be working as expected.

![image](https://user-images.githubusercontent.com/13606342/52025515-8c794280-24d2-11e9-89cf-26e33f889dfb.png)
