### ISSUE TITLE
1.4 vs 1.3 performance

### ISSUE THREAD

**Issue by chino23** [angular/angular.js#11962]
Hi,

As I understand 1.4 should bring quite a performance boost in the digest cycle.

How come this test shows it's up to 50% slower? 
http://jsperf.com/angularjs-digest-1-0-1-vs-1-2-4/48

**Comment by Narretz** [comment]
A few notes:
1) it's unclear how well the test shows what real apps do
2) Firefox currently shows perf improvements

**Comment by jhg** [comment]
I run test in Chrome in Ubuntu and is 33% slower, is 17% less that Firefox (2 note). Is possible test all with unclear or all with clear? I can run test in Chrome, Firefox in Ubuntu and Chrome, Firefox, Opera and IExplorer in Windows Xp,7 and 8.

**Comment by chino23** [comment]
That is indeed interesting.

While in Chrome 43 Angular 1.4 is about 50% slower than 1.3, testing Firefox 38 shows 1.4 about 20% faster than 1.3.

All in all, Firefox in 1.4 has twice the speed than Chrome.

**Comment by lgalfaso** [comment]
The performance improvements vary depending on your application. There are two different aspects
* The more *expression heavy* and the more complex the expressions, then the higher the benefits.
* Firefox is more aggressive in JIT-ing generated code, this implies that in micro-benchmarks numbers may look better

**Comment by jhg** [comment]
@chino23 What times run test in Firefox 38? A little times is more fast (1 for each 10, or less) but other time is more slow.
![captura de pantalla de 2015-05-29 12 08 44](https://cloud.githubusercontent.com/assets/1288711/7881533/ec2b3ffc-05fb-11e5-81d8-8e97554b1375.png)
![captura de pantalla de 2015-05-29 15 24 41](https://cloud.githubusercontent.com/assets/1288711/7884584/df554140-0616-11e5-993f-0a3de93be0ad.png)

**Comment by wa-Nadoo** [comment]
Test conditions: Revision 50, Core i5 3570K @ 4.0 GHz, 8 GB DDR3 @ 1866 MHz
![angular](https://cloud.githubusercontent.com/assets/1248501/7896174/5c1c4b7c-06b9-11e5-903d-12b29258209e.png)

**Comment by chino23** [comment]
@wa-Nadoo why do you go back to 1.3.9 when there's 1.3.15 out?

Here's my Chrome result:
![screen shot 2015-05-30 at 6 34 57 pm](https://cloud.githubusercontent.com/assets/7042593/7896880/b4b72b12-06fa-11e5-9989-3c46e8c9ec1d.png)


And this is my Firefox:

![screen shot 2015-05-30 at 6 35 27 pm](https://cloud.githubusercontent.com/assets/7042593/7896884/bcd66b0a-06fa-11e5-8d7c-0f0008b2ce02.png)


2015 13" Macbook Pro, i7, 16GB RAM

**Comment by wa-Nadoo** [comment]
![angular](https://cloud.githubusercontent.com/assets/1248501/7896949/5c635494-06d3-11e5-89ee-a4a5c327f8c5.png)

**Comment by lgalfaso** [comment]
First, I would like to stress that when running any test on jsperf, close everything else and if testing with Chrome, have only one tab in incognito mode. This is still not as good as a calibrated machine, but I think should be ok if you keep in mind that the noise to signal ratio can be substantial.

Updated the test from the original post, at version 51 there are the following changes:
* Uses ng 1.2.5, 1.2.16, 1.3.15 and 1.4.0
* The expression is slightly more complex `a["b"].c + 3`, the previous expression `a.b.c` should have close to no performance improvement as expressions of this form were already heavily optimized before 1.4
* Run `$digest` once on the scope setup, the first time you run a digest with new expressions involves some memory pressure. This makes all runs work with someone the same memory pressure. Ideally all the warm-up should run first and then all the tests, but I do not expect big changes (famous last words)
* Made all the child scopes isolated. This should not have any impact, but makes the test closer to how real apps work


Once again, stressing that micro-benchmarks do not reflect real apps performance, I see that a performance improvement of 1.4 of about 20% using Chrome 42 and about 30% using Firefox 38. In all cases on OS X 10.10.

**Comment by chino23** [comment]
@lgalfaso Thanks for the update, I've tried version 51 and the results are what is in line with the statement that 1.4 is about 30% faster.

I know those micro-benchmarks aren't really how apps work, but I was still curious how the 1.4 used to be slower than 1.3. With this version now, it seems better :)

![screen shot 2015-06-01 at 12 25 39 pm](https://cloud.githubusercontent.com/assets/7042593/7906234/ce345424-0859-11e5-9a25-424bd51a14c4.png)

**Comment by lgalfaso** [comment]
I think this can be closed now. If there is anything else that needs some tracking, then feel free to reopen it.
