### ISSUE TITLE
$window mocking not working with ngAnimate since 1.4.0

### ISSUE THREAD

**Issue by tjokimie** [angular/angular.js#11964]
I have tests for a directive that uses `$window` and `ngAnimate`. Since 1.4.0 (or 1.4.0-rc.0) I cannot mock `$window` without having `document` property set in `$window`.

This issue is due to `var bodyElement = jqLite($document[0].body);` in `ngAnimate` `animateQueue.js` https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateQueue.js#L108.

I have a JSFiddle demonstrating this problem:
- [Both tests are passing in 1.3.15](http://jsfiddle.net/tjokimie/g7wndnb5/1/)
- [Test without `document` is failing in 1.4.0](http://jsfiddle.net/tjokimie/s9jLkhhj/1/)

**Comment by arsahmad** [comment]
testing

**Comment by Narretz** [comment]
Closing with regards to https://github.com/angular/angular.js/pull/11997#issuecomment-110082566
