### ISSUE TITLE
ngAnimate provider error when trying to inject this into my controller

### ISSUE THREAD

**Issue by landed1** [angular/angular.js#11965]
1.3.15 (and below tried)
I have ---
app.js

```
var baApp = angular.module('baApp', [
  'ngResource',
  'ngSanitize',
  'ngAnimate',
  'ngRoute',
  'ngTouch',
  'LocalStorageModule',
  'videoController',
  'toursController'
])
  .config(
```

then in a controller js file Main.js ---
```
angular.module('baApp')
    .controller('MainCtrl', ['$scope','$location','localStorageService','ngAnimate',function ($scope,$location,localStorageService,ngAnimate){...
```

I am getting the error - Unknown provider: ngAnimateProvider 

Usually this is due to a different version of the animate and angular .js files (yes I checked both are loading and the correct version - I really do not know what else to try...)

thanks

**Comment by tjokimie** [comment]
This is not a bug.

`ngAnimate` is the module name not the service you are trying to inject. If you want to use animate service you should inject `$animate` instead of `ngAnimate`. See https://docs.angularjs.org/api/ng/service/$animate

**Comment by landed1** [comment]
Thank you so much - I don't know of a better place to post now that stack doesn't allow any more questions. It works and no not a bug but an issue...
