### ISSUE TITLE
Issue with ng-app from angular-2.0.0-alpha is not working

### ISSUE THREAD

**Issue by vrammohan** [angular/angular.js#11967]
![angular-2_x-alpha-is-it-a-bug-in](https://cloud.githubusercontent.com/assets/4157858/7867541/5593d4d0-0594-11e5-8a6d-522c9629e4ce.png)

Please see the highlighted areas, is it aa bug in the angular 2.x , I am confused.

**Comment by caitp** [comment]
The angular 2.x api is very different from angular 1.x. You might want to take a look at some of the examples from https://github.com/angular/angular/tree/fbd6851860a04c923efbf8f0e785929f012417a6/modules/examples/src
