### ISSUE TITLE
Angular 1.4.0 does not follow semver

### ISSUE THREAD

**Issue by fenduru** [angular/angular.js#11966]
#6484 seems to indicate that Angular 1.3+ would be following semver, however this doesn't seem to be the case as of the 1.4.0 release. My build suddenly started failing when my bower dependency on angular and angular-animate `^1.3.0'` resolved to 1.4.0.

Was this a conscious decision?

**Comment by fredyang** [comment]
This looks like it is the issue of client's interpretation.

**Comment by fenduru** [comment]
@fredyang [please see the summary of semver](http://semver.org/)

**Comment by Narretz** [comment]
Yes, angular 1.x does introduce breaking changes in MINOR versions. This is explained here: https://code.angularjs.org/snapshot/docs/misc/faq

**Comment by olsonpm** [comment]
For future readers - angular doesn't follow semver per the link Nerretz posted.
