### ISSUE TITLE
bug with directive "replace" property

### ISSUE THREAD

**Issue by TekVanDo** [angular/angular.js#11977]
When i insert the value of attribute with same name as one of the isolate scope property into directive template. Space symbol is appended to scope property.
http://jsbin.com/bohicegaka/3/edit?js,console,output

**Comment by ryanhart2** [comment]
Is this a duplicate of https://github.com/angular/angular.js/issues/8132?

**Comment by TekVanDo** [comment]
yas it's duplicate.

**Comment by Narretz** [comment]
`replace: true` is deprecated. As noted in the linked issue, this bug will not be fixed.
