### ISSUE TITLE
$location.absUrl()

### ISSUE THREAD

**Issue by SolStis86** [angular/angular.js#11978]
This is causing a full page reload rather than just the getter function as specified in the documentation: https://docs.angularjs.org/api/ng/service/$location.

im just using it as var absUrl = $location.absUrl()

**Comment by joshuakelly** [comment]
Where are you trying to run this code?

**Comment by SolStis86** [comment]
1.3.15 within the link object of a directive

**Comment by Narretz** [comment]
Well, this should not happen. Can you provide a demo of the problem?

**Comment by Narretz** [comment]
Closing because of lack of response.
