### ISSUE TITLE
Invalid boolean expression evaluation when accessing a property of an undefined value

### ISSUE THREAD

**Issue by julien-f** [angular/angular.js#11976]
Let `foo` be `undefined`.

`{{true && foo || false}}` evaluates to `false` which is perfectly normal.

But `{{true && foo.bar || false}}` evaluates to `true`!!!

**Comment by julien-f** [comment]
Tested with Angular 1.4.0.

**Comment by julien-f** [comment]
Probably duplicate of #11959.

**Comment by Narretz** [comment]
Yep, duplicate
