### ISSUE TITLE
Can't Authenticate using Basic Authentication in CORS

### ISSUE THREAD

**Issue by 4success** [angular/angular.js#11980]
Hello,

I'm using AngularJS v1.3.12 connected with a SAP Server that require basic authentication:

		$http({
			url	   : apiUrl,
			method : 'GET',
			withCredentials : true,
			header : {'Authorization'					 : 'Basic NFMuUi5PTElWRUlSOnAwazNyZjRjMw==',
					  'Access-Control-Allow-Credentials' : true,
					  'Access-Control-Allow-Origin'      : fixedConstants.basePath,
					  'Accept' : "text/plain"}
			}
		).success(function(data, status, headers, config) {
			console.log(data);
		}).error(function(data, status, headers, config) {
			console.log('Error on SAP connection');
		});

The problem is that the data send in Authorization doesn't have effect and a popup is displayed everthime, ignoring the Authentication Data.

Any sugestions? I live demo can be checked at: http://apps.4success.com.br/ourofino/dms/#/core/dms

**Comment by Narretz** [comment]
Have you tried if it works with jquery / pure javascript? Most of these CORS problems are not actually angular specific.

**Comment by 4success** [comment]
Yes, I have tried and isn't worked. The problem is related with autentication return that not have the Access-Control-Allow-Origin. So basically send a correct or invalid authentication always will be blocked by CORS.

**Comment by Narretz** [comment]
So it is not an angular problem and this issue can be closed?
