### ISSUE TITLE
ng-repeat doesn't seem to duplicate the event listeners for the DOM element.

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular.js#11988]
I have a use case where i have a directive, and i have used ng-repeat inside the template.

```
<div class="card-container">
	<md-card ng-repeat="card in reportCtrl.reports">
		<md-toolbar class="md-accent md-toolbar-sm">
			<div class="md-toolbar-tools">
				<h5 ng-bind="card.title"></h5>
			</div>
		</md-toolbar>
		<md-card-content>
		</md-card-content>
	</md-card>
</div>
```

I need to add an event listener for each individual card that is created.  I tried to do this by adding the event listener to the md-card element during the compile phase of the directive, but it appeared to be that the event listener was not carried over to each of the different cards.

I might not be going about this the best way, but if I am, then I think it might be helpful to enable ng-repeat to copy the event listeners as well.

**Comment by Guardiannw** [comment]
I think that the problem is in the copy of the transcluded element that the transclude function provides to ng-repeat.

**Comment by Guardiannw** [comment]
Perhaps this line num 7374.
```
$linkNode = JQLitePrototype.clone.call($compileNodes);
```

It lacks the copying of all event listeners and events in general

**Comment by gkalpak** [comment]
I think you should be using the linking phase (either pre or post) or use an event-listener directive.

**Comment by Guardiannw** [comment]
The linking phase won't work because the ng-repeat directive has already been compiled, but has not yet duplicated itself.  Therefore, only a comment exists.  An event listener directive would work, but seems to be an unnecessarily large amount of coding just to toggle a class on a hover event.  I know there are other ways to do it, but event listeners seem the most appropriate.

**Comment by Narretz** [comment]
It's pretty difficult to say what the problem is without more context. A naive reproduction shows that it works with adding the listeners inside the link function: http://plnkr.co/edit/BSt7LHaiPmD7lTyTCDpd

**Comment by Guardiannw** [comment]
I have updated the plunker to better reflect the usage.  Provided here: http://plnkr.co/edit/50SjuGaMKfxMIC8Ko83B

**Comment by gkalpak** [comment]
@Guardiannw, In that you should either use another directive on the repeated elements or use the built-in `ngMouseenter`/`ngMouseover` directives.

E.g. 1:

```js
directive('myDir', function myDirDirective() {
  return {
    template: '<div my-other-dir ng-repeat="card in [\'a\', \'b\', \'c\']">{{ card }}</div>'
  };
}).
directive('myOtherDir', function myOtherDirDirective() {
  return function (scope, elem) {
    elem.on('hover', function onHover(evt) {
      $scope.$apply(...);
    });
  };
})
```

E.g. 2:

```js
directive('myDir', function myDirDirective() {
  return {
    template: '<div ng-mouseenter="doSomething()" ng-repeat="card in [\'a\', \'b\', \'c\']">{{ card }}</div>'
  };
})
```

**Comment by Guardiannw** [comment]
@gkalpak Ok.  After looking at your previous examples I think that would be the best way to go about it.  I think it is probably a better solution and does a better job separating concerns.

It is strange to me though that we don't copy event listeners during the transclude copy, is there any reason for this?  If not, it might be good to implement.

**Comment by gkalpak** [comment]
I don't really know what is the actual reason for not copying event listeners, but I wouldn't be surprised if it had something to do with performance and/or code complexity.

In any case, it doesn't feel very "Angular-ish" to do that (e.g. it is not declarative etc). 
If you want to attach behaviour to an element, a directive is the right way to do it.
(Of course, you can always set up _one_ event on the parent element and use event delegation (but that's not supported in `jgLite` out of the box).)

**Comment by Guardiannw** [comment]
Ya, your probably right.  I don't have any other use cases for this so it is probably ok just to forget about it.  I will go ahead and close this issue.
