### ISSUE TITLE
Performance: angular.copy 1.2 vs 1.3

### ISSUE THREAD

**Issue by buihoanghai** [angular/angular.js#11990]
I have a issue with performance. When I upgrade my app angular 1.2 to 1.3. The app run very slow when digest a big data. $digest in 1.2 just 3s but in 1.3 it take about 10s. I checked and saw angular.copy in 1.2 is run faster than 1.3 2-3 times. You can check it in: http://jsfiddle.net/hoanghaibui2003/0npr2sqn/2/

**Comment by Narretz** [comment]
We don't really encourage using the built-in helper methods, because they are mainly for internal purposes. So it's unlikely that we will prioritize fixing these perf regressions.

**Comment by Narretz** [comment]
For what it's worth, it seems to be caused by supporting circular references since 1.3.0-beta.11: https://github.com/angular/angular.js/commit/083f496d46415c01fec6dfa012da63235d0996e4

**Comment by buihoanghai** [comment]
I see in function digest line 14308 version 1.3.15 use "copy". It's mean if I watch a big object the digest will very slow than 1.2. Currently, I use JSON.parse(JSON.stringify(source)); for angular.copy and it run faster

**Comment by Narretz** [comment]
The built-in helpers are not built for speed. copy is maybe an exception as it often used by the watch / digest mechanism. There's an issue about this here: https://github.com/angular/angular.js/issues/11099
