### ISSUE TITLE
Binding functions through nested directives with isolated scope failing in 1.4

### ISSUE THREAD

**Issue by ximenean** [angular/angular.js#11995]
The 1.4 update seems to have introduced an issue when binding functions in nested directives. I have an example plunker: http://plnkr.co/edit/fQLY0N8BTNs38VC8ikll

Example code:

    var app = angular.module('myApp', []);

    app.controller('myCtrl', function(){
       this.searchFunction = function(term) {
        console.log('you searched for ' + term);
      }
     });

     app.directive('outerDirective', function(){
       return {
        restrict: 'E',
        scope: {
          outer: '&'
        },
        template: '<inner-directive inner="cx.outer(term)"></inner-directive>',
        controller: function(){

        },
        controllerAs: 'cx',
        bindToController: true
      };
    });

    app.directive('innerDirective', function(){
      return {
        restrict: 'E',
        scope: {
          inner: '&'
        },
        template: '<a ng-click="cx.execute()">Click</a>',
        controller: function(){
          this.execute = function(){
            this.inner('fred');
          }
        },
        controllerAs: 'cx',
        bindToController: true
      };
    });

This was working in 1.3 but is there some new way I should do this in 1.4?

Clicking on the link you'll see the following error in the console:

TypeError: Cannot use 'in' operator to search for 'cx' in fred
at fn (eval at (https://code.angularjs.org/1.4.0/angular.js:13036:15), :2:54)
at destination.(anonymous function) as inner
at execute (http://run.plnkr.co/zE9xlCQNMBrOZZgi/script.js:35:14)
at fn (eval at (https://code.angularjs.org/1.4.0/angular.js:13036:15), :2:237)
at callback (https://code.angularjs.org/1.4.0/angular.js:23090:17)
at Scope.$eval (https://code.angularjs.org/1.4.0/angular.js:15719:28)
at Scope.$apply (https://code.angularjs.org/1.4.0/angular.js:15818:23)
at HTMLAnchorElement. (https://code.angularjs.org/1.4.0/angular.js:23095:23)
at HTMLAnchorElement.eventHandler (https://code.angularjs.org/1.4.0/angular.js:3247:21)

**Comment by gkalpak** [comment]
You are not passing the arguments correctly. In `&` bindings, you have to pass an object specifying values for the various arguments. E.g. 

```
<div some-func="doSomething(arg1)">...</div>

directive('someFunc', function () {
  return {
    ...
    scope: {someFunc: '&'},
    link: function (scope) {
      // You have to call is like this
      scope.someFunc({arg1: 'some value for arg1'});
    }
  };
})
```

Here is the [updated plnkr][1] that works.

--
This is **not** something new in 1.4, so your plnkr doesn't work properly on 1.3 either.
The difference is that in 1.3 it doesn't throw an error (it just calls the function with `undefined`).

I am not sure if throwing was an intentional change. While I look further into it, @lgalfaso, do you have a quick insight on whether it is related to the recent parser changes ?
If so, is this a breaking change ? Is this desirable ?

[1]: http://plnkr.co/edit/bz1fCy6TJlHMomIItDR6?p=preview

**Comment by gkalpak** [comment]
Yup, this is relatedto the new parser.

**Comment by Narretz** [comment]
The new behavior is slightly better, because it shows you that you have an error. Just the message isn't that helpful.

**Comment by gkalpak** [comment]
I agree throwing is better (I wonder if it should documented as a breaking change; I lean towards _no_)

:+1: for a better error-message.

**Comment by tolemac** [comment]
+1
plunkr here: https://jsfiddle.net/y0xnro37/

It's occurs me when the parameter to the expression is a string.

**Comment by gkalpak** [comment]
@tolemac, your example is totally unrelated to this issue. You are using `$parse` incorrectly (passing a string, instead of a `locals` object).

**Comment by gkalpak** [comment]
Closing since everything works as expected.

**Comment by ahmehri** [comment]
@gkalpak does a better error-message have been implemented?

**Comment by gkalpak** [comment]
@ahmehri, no. It's not easy because it is related to core `$parse`r functionality (it is not something specific to `&` bindings). But if anyone has a good suggestion on how to improve the situation, I'm all ears  :ear: :smiley: :ear:
