### ISSUE TITLE
Cannot access Set-Cookie header in interceptor response

### ISSUE THREAD

**Issue by ronaldjeremy** [angular/angular.js#12000]
Angular for whatever reason is stripping Set-Cookie headers out of the response object and response.headers() does not contain them.  But when you look at the raw response headers in Chrome, it shows Set-Cookie headers there, so they definitely are coming in to Angular.  

$browser.cookies() is not an acceptable solution, for a few reasons including that it will not work inside of cordova+iOS 

We absolutely must be able to access Set-Cookie headers in an angular response interceptor.  Can this bug be fixed?

**Comment by lgalfaso** [comment]
I am sorry, but this is not an angular thing, this is how `XMLHttpRequest`. You just cannot access the `Set-Cookie` header. http://www.w3.org/TR/XMLHttpRequest/#the-getresponseheader()-method

**Comment by ronaldjeremy** [comment]
In a regular browser you are correct, but inside of a native iOS app (we are using ionic) Set-Cookie headers CAN be accessed.  And you NEED to be able to access them in that context to interface with legacy web services that depend on sessions.  The following works in the context of cordova/iOS:

      var ajaxRequest = new XMLHttpRequest();
      ajaxRequest.open('GET', "http://somesite.com", true);
      ajaxRequest.setRequestHeader('Content-Type', 'text/html');
      ajaxRequest.onreadystatechange = function () {
	 if(ajaxRequest.readyState == 4) {
	    if(ajaxRequest.status == 200) {
	       try{
		  var setCookieHeader = ajaxRequest.getResponseHeader("Set-Cookie");
		  alert(JSON.stringify(setCookieHeader));
	       }
	       catch(e){
	       }
	    }
	 }
      }
      ajaxRequest.send();
