### ISSUE TITLE
Cannot access Set-Cookie header in interceptor response

### ISSUE THREAD

**Issue by ronaldjeremy** [angular/angular.js#12002]
Inside of an ionic cordova+iOS app, Set-Cookie headers CAN be accessed. And, because $browser.cookies() does not work in that context, we MUST be able to access the Set-Cookie headers to interface with legacy web services that depend on sessions.

The following low level javascript works in the context of cordova+iOS.  But Angular for whatever reason is stripping Set-Cookie headers out of the response object in http interceptors, and response.headers() does not contain them. We need to be able to do the same within Angular interceptors as we can outside of Angular:

      var ajaxRequest = new XMLHttpRequest();
      ajaxRequest.open('GET', "http://somesite.com", true);
      ajaxRequest.setRequestHeader('Content-Type', 'text/html');
      ajaxRequest.onreadystatechange = function () {
	 if(ajaxRequest.readyState == 4) {
	    if(ajaxRequest.status == 200) {
	       try{
		  var setCookieHeader = ajaxRequest.getResponseHeader("Set-Cookie");
		  alert(JSON.stringify(setCookieHeader));
	       }
	       catch(e){
	       }
	    }
	 }
      }
      ajaxRequest.send();

**Comment by ronaldjeremy** [comment]
Facepalm.  After testing this in the context of actual cordova+ios, Angular does in fact pass along set-cookie headers to the response interceptor.  Please close this issue, my apologies!

**Comment by letai1409** [comment]
Hi  @ronaldjeremy I faced the same problem like you. Could you please show me how to get "Set-Cookie" from response header. I tried low level javascript as above, but it always return null

**Comment by matthiaslexer** [comment]
@ronaldjeremy  @letai1409 I'm facing the same problem, do you have any solutions?
