### ISSUE TITLE
dynamic table row not fire click event.

### ISSUE THREAD

**Issue by dev33250240** [angular/angular.js#12006]
Hi,

I have two td in my table. Dynamically I convert td to tr for collapse expand feature. Button with in dynamically created tr not trigger but its working in another td which was not dynamically created.

**Comment by Narretz** [comment]
Please ask support questions on these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem Also make sure to provide enough information, so that others can easily understand your problem.

**Comment by dev33250240** [comment]
I am using a table structure and apply datatable.net to it. Table populating its row and column data by angularjs and there is also edit or delete button. All are working fine. as soon as i want to implement nested table i just put a hidden td and when we click on expand i dynamically convert td to tr. But dynamically created tr not support any angular event like click etc. Please guide us.
