### ISSUE TITLE
ngMessageDefault - Add support for showing values not mapped with ng-message

### ISSUE THREAD

**Issue by douglascvas** [angular/angular.js#12008]
Many times it is necessary that we show a generic error message for unexpected values.
Would be nice to have something like:

``` HTML
<div ng-messages="controller.errors">
    <div ng-message="error1">Option 1</div>
    <div ng-message="error2">Option 2</div>
    <div ng-message-default>Option 3</div>
</div>
```

This way, whenever there is an "error3" in "controller.errors", as it is not mapped, the value under the ng-message-default would be shown.

**Comment by douglascvas** [comment]
Sorry to push it, but could someone tell me what is the status? Will it not be included in the release?

**Comment by petebacondarwin** [comment]
This will go into 1.6 as soon as 1.5.0 is out; since we have locked down 1.5 features now in preparation for a release very soon.

**Comment by gilad905** [comment]
+1

**Comment by petebacondarwin** [comment]
Marked with "PRs plz" which indicates we would accept a community contribution for this issue.

**Comment by 4O4** [comment]
I'm planning to work on this. I'll probably start with the code from https://github.com/angular/angular.js/pull/12213 and make changes requested in the comments.

**Comment by Narretz** [comment]
@4O4 That's great to hear!
