### ISSUE TITLE
$resource doesn't correctly resolve dot notation in URI parameters

### ISSUE THREAD

**Issue by jardilio** [angular/angular.js#12015]
If a URI parameter contains dot notation to express a path to retrieve the value on the given object, then the $resource will correctly collect the key/value pairs via "lookupDottedPath" during "extractParameters", however it doesn't get applied correctly during "Route.setUrlParams". The issue is that spliting the url value on /\W/ results in breaking up the dot notation parameter into 2 separate parameters.

Example:

A path of "'/parent/:parent.parentId/child/:childId'" is resolved to "/parent/.parentId/child/2?parent.parentId=1" when given {parent: {parentId: 1}, childId: 2} when "/parent/1/child/2" is expected.

http://plnkr.co/edit/cV5hvlgp8i1cNoJBmgGl?p=preview

The correct value returned from "lookupDottedPath" and passed into the "params" argument of "Route.setUrlParams" is: {"childId":2,"parent.parentId":1}

**Comment by lgalfaso** [comment]
Dot notations nor any other form of reference was ever supported. This is opened as if this was a bug, while in fact, if this is requested, then if should be a feature request.

`$resource` is not the only library out there, how to other libraries behave?

**Comment by jardilio** [comment]
I classified it as a bug because the code specifically handles this situation and even names the function that does so as "lookupDottedPath", the value is correctly resolved in the parameters sent to the "setUrlParams" function, the error is simply in the way "setUrlParams" breaks up the url to inject the values.

**Comment by gkalpak** [comment]
I think, mapping dotted paths to parameters is the `params` object's responsibility (else we wouldn't need it at all).
In your example, it should be:

```js
$resource('/parent/:parentId/child/:childId', {}, {
  get: {
    method: 'GET',
    params: {
      'parentId': '@parent.parentId',
      'childId': '@childId'
    }
  }
});
```

[Updated plnkr][1]

--
It's definitely not a bug imo and as a feature I don't think it adds much (if anything).
@jardilio, is there any usecase that is not possible to support using the current implementation ?

[1]: http://plnkr.co/edit/7k686TGaMkmFamLkQuOA?p=preview

**Comment by jardilio** [comment]
You are correct, this can be closed, it just wasn't well documented. Thanks for the clarification.
