### ISSUE TITLE
ngAnimate's ng-animate-ref does not work when anchoring between 2 directive's templates

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular.js#12013]
I have two different directives that are toggled off an ng-switch, both of the directives have a template containing an image.  I am trying to anchor and animate this image so that when the switch is activated and toggles from one directive to the other, that the image will animate and go to the spot on the new directive.  It appears that it only anchors and animates correctly when navigating between views.

I find this extremely important for effective routing between directives, as well as good separation of concerns between different parts of the application.  Since angular is moving toward the component model anyway, this would be helpful.

**Comment by matsko** [comment]
Would you be able to create a demo for this? Testing with two directives was something that was left out unfortunately and I'm interested to see what's breaking it.

**Comment by Guardiannw** [comment]
Good news, I think that something was happening in my code that was outside of the affairs of ngAnimate.  When I tested under 2 different conditions, both seemed to work as expected.

The first condition is a simple ng-switch between 2 different directives portrayed here.
http://plnkr.co/edit/hh11FGNQmf1FBZqHsiRr

The second is more like the actual situation I had was using where I had an element that had the ng-animate-ref directive in one route, while I had a directive that had an element using ng-animate-ref in another route.  I am not sure why it was not working in my application, but it seems to be working in this example: 
http://plnkr.co/edit/JKifU01p5qp8pFx8fisL

Thanks for your consideration @matsko.

**Comment by petebacondarwin** [comment]
It looks like this is not actually an issue for the original poster.
