### ISSUE TITLE
ngModel generates errors when in a form element with a ngController directive

### ISSUE THREAD

**Issue by neoGeneva** [angular/angular.js#12029]
The following HTML snippet generates errors under 1.4.0, but works with 1.3.15.

ngModelDirective generates errors in ngModelPreLink because it inadvertently references myController rather than the expected FormController.

```html
<html>
<body ng-app="myApp">
	<form ng-controller="myController">
		<input ng-model="myModel" />
	</form>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0/angular.js"></script>
	<script>
		angular.module("myApp", []).controller("myController", function () { 
                  return {}; 
                })
	</script>
</body>
</html>
```

**Comment by damiengenet** [comment]
We have the same problem with 1.4.0, this worked fine with 1.4.0beta6 and 1.3.x versions.

**Comment by Narretz** [comment]
The important part is the return inside the controller. Probably caused by https://github.com/angular/angular.js/commit/9900610eea4ece87b063f2aa9d82c75c369927df
