### ISSUE TITLE
Unable to get property '$$ngAnimateParentKey' of undefined or null

### ISSUE THREAD

**Issue by havenchyk** [angular/angular.js#12026]
Hi, I catch error with angular 1.4 in IE 11. Chrome has some freezes on UI, but without exception in the console.

`Unable to get property '$$ngAnimateParentKey' of undefined or null`

I use ng-switch and ng-if only. Cannot reproduce it on jsbin, but problem exists.

**Comment by dmackerman** [comment]
Yeah, getting this all over our application as well. Downgrading to 1.3.15 fixes it.

**Comment by Narretz** [comment]
Do the actual animations work? Or is the app completely broken? Please try to isolate the buggy scenario, that would help a lot.

**Comment by havenchyk** [comment]
@Narretz animation is working and application is not completely broken. It looks like the previous animation still in progress and after invoking new one I get this error. I'll try to isolate this error.

**Comment by xavhan** [comment]
I don't think this is a browser dependent bug, I got it on Chrome 43 too. 
I have not found right now what is causing it but, it happens on page with a fullcalendar view (https://github.com/angular-ui/ui-calendar). Maybe the two are related ? 
I keep diggin'

**Comment by havenchyk** [comment]
Here is what I found so far in Chrome 43.

![Image of bug](http://i.imgur.com/hvN6yoS.png)

`$scope.selectedTab` is 'Default', so selected div element (at the bottom) should be hidden with 'ng-hide' class, IE 11 crashes after several clicks, but Chrome works fine for a while.

**Comment by dmackerman** [comment]
The bug in our case was we were trying set the `selectedIndex` (or whatever your selected bound model is) before the tabs compiled. Wrapping in a `$timeout` works, but feels kinda hacky.

**Comment by matsko** [comment]
Could this be because of how `ng-if` and `ng-include` are both on the same element? Could you @dmackerman and @havenchyk please provide me with plnkr examples so I can test this out?

**Comment by havenchyk** [comment]
> Could this be because of how ng-if and ng-include are both on the same element

It looks like using both on the same dom element is not a problem. But I still can't reproduce the issue on the jsbin. @matsko could you suggest the way how to emulate heavy $digest loop (I have 900+ watchers on the page, could it be a problem?)? :)

**Comment by havenchyk** [comment]
@matsko I still unable to reproduce this issue out of the scope of my application. Can I help with anything else here?

**Comment by matsko** [comment]
Alright. I'll spend some time creating a reproduction, but please also try to continue your investigation. Hopefully we can get to the bottom of this.

**Comment by havenchyk** [comment]
Sure, I will continue, thank you. 

As a point, could the problem be in the time of evaluation digest loop? I've already mentioned, but there are 900+ watchers on the page and the problem is only reproducible on the re-initialization of the huge controller with a lot of ng-if and ng-include directives in the template.

**Comment by matsko** [comment]
Hey @havenchyk have you had any luck getting a working demo? I've tried a few combinations of ng-if, ng-include and ng-switch, but nothing triggers the error. I'll keep looking. @dmackerman do you have any clue as to what was causing it for you?

**Comment by havenchyk** [comment]
@matsko I still have this on my project and cannot able to reproduce on plnkr with any combination of ng-if, ng-show and so on. We used our custom `ng-view` directive, maybe the reason can be there, I'm looking into it.

**Comment by matsko** [comment]
@havenchyk would you be able to pair on this sometime tomorrow or Wednesday? We could get down to the bottom of this if you're willing to screen share your project.

**Comment by havenchyk** [comment]
@matsko sure, it would be nice if you have free time. I'll let you know by email. Thanks!

**Comment by havenchyk** [comment]
As discussed with @matsko, there were a problem with tooltip that in some situation hasn't `parentNode` during the `leave` event.

**Comment by havenchyk** [comment]
I'm not sure, but is it enough to add additional check on `node.parentNode`? @matsko 

![image with change](http://i.imgur.com/5Z5b92L.png)

**Comment by havenchyk** [comment]
Probably, has been fixed with https://github.com/angular/angular.js/commit/e4aeae0c7303b94135e6df20e6c5e25f2aa0f586 and issue can be closed.
