### ISSUE TITLE
Problem in parsing valid JSON responses

### ISSUE THREAD

**Issue by mmnaseri** [angular/angular.js#12025]
I have this piece of code:
    
        $http.get('/entities/').then(function (response) {
            $scope.entities = response.data;
        });

wherein `/entities/` returns the following:

    [{
        "id": "2a7305fc-432e-4c30-9060-be54a4f473dd",
        "status": "WAITING"
    }]

and I get the following error:
  > SyntaxError: Unexpected token a

This is happening with the following call stack trace:

>  * Object.parse (native)
>  * fromJson (angular.js:1072)
>  * defaultHttpResponseTransform (angular.js:8619)
>  * (angular.js:87045)
>  * forEach (angular.js:323)
>  * transformData (angular.js:8703)
>  * transformResponse (angular.js:9429)
>  * processQueue (angular.js:13249)
>  * (angular.js:13265)
>  * Scope.$get.Scope.$eval (angular.js:14467)

I am using AngularJS 1.4.1 in conjunction with some Bootstrap and jQuery JavaScript. Nothing else is in the project, and I can't see anything illegitimate with the returned JSON object, therefore  I assume this to be a bug somewhere in the AngularJS code. My module only depends on `ngRoute`.

**Comment by JimmyLv** [comment]
@mmnaseri  Hello, have you solved this problem, I met the same one and so confused about it.

**Comment by mmnaseri** [comment]
Hi
in my case it was because the MVC framework I was using (Spring) didn't wrap String responses in quotations. So, "something to test" would not be treated as a valid String result when converting to JSON. This is a valid behavior, and I had to wrap my response in quotations to avoid this error.

**Comment by JimmyLv** [comment]
@mmnaseri Thanks, that make sense and seems I met the same case as yours, so how did you wrap response (return a object in Spring) to fix it?

**Comment by JimmyLv** [comment]
@mmnaseri have fixed, just override the default transformResponse() method.

**Comment by mmnaseri** [comment]
I just used string concatenation to add quotations to my response:

    return "\"" + result + "\"";

**Comment by JimmyLv** [comment]
@mmnaseri yeah, the same as you.
