### ISSUE TITLE
$animate.enter for a compiled directive doesn't seem to animate

### ISSUE THREAD

**Issue by dagumak** [angular/angular.js#12048]
I do realise there is a newer version of Angular, but am in a position where I can't immediately upgrade. However, I am using Angular 1.3.15 and I think this might be a bug. Correct me if I am wrong, or can someone explain to me why this not animating as expected.

http://plnkr.co/edit/iEVOxKxQKNI5f0ILhxk5

**Comment by Narretz** [comment]
Custom elements are by default not block elements - adding `blue-block: {display: block}` to the css makes the animation work.
