### ISSUE TITLE
$scope inside nested callbacks

### ISSUE THREAD

**Issue by brunocascio** [angular/angular.js#12047]
```
DB.messages().all(function(err, cursor){

    $scope.messages = [{text:'pepito!'}]; // here work

    cursor.toArray(function(err, msgs){
        $scope.messages = [{text: 'pepito'}]; // here not work
    });
  });
```

Note: I use angular 1.3.16

**Comment by Narretz** [comment]
what is DB.messages()? It might be that the callbacks are not executed inside an angular app context, so you need to call `scope.$apply()`.

**Comment by havenchyk** [comment]
@brunocascio you probably need to invoke `$scope.$apply` for async operation of reading the date from database. Look at https://github.com/angular/angular.js/wiki/When-to-use-$scope.$apply()

**Comment by brunocascio** [comment]
Yes, definitely i need execute `$scope.$apply()`

thanks @havenchyk @Narretz
