### ISSUE TITLE
Changing interpolation characters in a controller.

### ISSUE THREAD

**Issue by alexandernst** [angular/angular.js#12045]
Is it possible to change the interpolation characters in a function (inside a controller),  or is that possible only in the `.config()` method?

[SO question about this](http://stackoverflow.com/questions/30503000/using-interpolateprovider-startsymbol-outside-of-config)

This is Angular 1.3.15

**Comment by Narretz** [comment]
This is only possible in the config phase, since it is global for the whole app. What's your use case for changing this in the controller?

**Comment by alexandernst** [comment]
@Narretz I have a directive that accepts a string as a template. That string contains some variables names that don't exist in the scope which is managing the directive, but in the objects that the directive is handling*. Each variable name is delimited by `{|` and `|}`.

Real world example: A dropdown-like widget filled with items. Each item's text is a string in the format `{| var1 |} {| var2 |} ...`. The directive receives an array of objects, and each object contains `var1, var2, ...`.

When the directive renders each item in the dropdown it needs to parse the format string (`{| var1 |} {| var2 |} ...`) and interpolate it with the content of the currently rendered item.

If I could change the interpolation characters at runtime (outside of the `.config()` method) that wouldn't require doing [this](https://github.com/alexandernst/angular-multi-select/blob/9c4d66e7ff4c76569d621bf66c00705fa038eb66/src/angular-multi-select.js#L293)

**Comment by gkalpak** [comment]
@alexandernst, fwiw, what you are doing now is much more concise and clear from temporarily replacing the interpolation symbols:

```js
_fmt = _fmt.replace(/\{\|/g, "{{").replace(/\|\}/g, "}}");
```

vs 

```js
var _s = $interpolate.startSymbol();
var _e = $interpolate.endSymbol();
$interpolate.startSymbol("{|");
$interpolate.endSymbol("|}");
...
$interpolate.startSymbol(_s);
$interpolate.endSymbol(_e);
```

I don't see much merit in being able to replace the symbols at runtime (not to mention the risks of failing to properly restore them).

**Comment by alexandernst** [comment]
It makes less operations to do the trick, but it's unclear what I'm doing there. There could be more real-world examples for what I'm suggesting.

**Comment by lgalfaso** [comment]
Changing the interpolation symbols after config has side-effects that I think everybody would like to avoid. The only option I think makes sense (even when I do not really like the idea) is to add an optional parameter to `$interpolate` to specify the begin/end tokens just for this interpolation. The main issue would be that this parameter would be its 5th...

**Comment by pkozlowski-opensource** [comment]
Hmm, why not add the `locals` argument to a function generated by $interpolate (and then use-case described here could be handled using a standard interpolation delimiters - if I understand the use-case correctly....)

**Comment by alexandernst** [comment]
Javascript is single-threaded, I can't understand how would changing the interpolation symbols affect annything else (if restored correctly, after doing what one needs to do). Care to explain a little bit?

**Comment by lgalfaso** [comment]
Would it be possible to understand why not just use the standard `{{` and `}}` symbols?
The only change would be to change this [line](https://github.com/alexandernst/angular-multi-select/blob/9c4d66e7ff4c76569d621bf66c00705fa038eb66/src/angular-multi-select.js#L281) to 

```js
// Warning untested code
var _fmt = element.attr(attrs.$attr.itemLabel);
```

**Comment by alexandernst** [comment]
@lgalfaso That won't work as the `itemLabel` is set inside the directive, like this: `<div item-label="{| var1 |}"></div>`, if I do it with the normal angular brackets, angular will try to interpolate that.

**Comment by lgalfaso** [comment]
@alexandernst `var _fmt = element.attr(attrs.$attr.itemLabel);` should be able to retrieve the uninterpolated attribute, at least within `link`. I did not dig too dip into this directive implementation so I do not know when is this function called, but that aside, this mechanism is provided exactly for this.

**Comment by alexandernst** [comment]
@lgalfaso I just tried, but that is returning empty strings. Does that requires Angular 1.4?

**Comment by lgalfaso** [comment]
Angular 1.4 is not needed. Now, this is somehow off topic as this is not really an issue with Angular.. If you would like to keep this conversation, please put a plunker together and we can continue this on StackOverflow.

Trying to go back to the original issue that caused this issue, I think there are other means to achieve this so I lean towards "wont fix".

**Comment by gkalpak** [comment]
Angular provides a way to escape interpolation symbols:

```js
<div item-label="\{\{...}}">...
```

I can't test it right now, but you should be able to make it work without needing to swap the intetpolation symbols or replace them in `_fmt`.

**Comment by alexandernst** [comment]
@lgalfaso Fair enough. Please check http://stackoverflow.com/questions/30725108/passing-format-string-to-a-directive-and-interpolating-it (includes a demo showing the problem).

@gkalpak That doesn't work. Please check my SO question and the demo from plunkr.

**Comment by lgalfaso** [comment]
Answered at SO

**Comment by gkalpak** [comment]
@alexandernst, I had misunderstood the usecase. I added an alternative approach on SO (there are other ways of doing it, based on the exact requirements, but swapping interplation symbols shouldn't be one of them).

**Comment by alexandernst** [comment]
@gkalpak I saw your answer, but the question here isn't about evaluation math expressions, but about rendering items. I'll update my SO question, please check it again. /cc @lgalfaso

**Comment by lgalfaso** [comment]
I see that you already changed it with https://github.com/alexandernst/angular-multi-select/commit/dd306338b68dcf7f9f17cba5281af7bc8c15e4eb

BTW, you can reuse the result of `$interpolate(...)` as that construction is not super cheap

**Comment by alexandernst** [comment]
@lgalfaso You mean save the result of `$interpolate(...)` and just to `_savedResult(obj)` in my `_createLabel` function?

**Comment by lgalfaso** [comment]
yep

**Comment by alexandernst** [comment]
@lgalfaso Done :) Thanks for the tip!
