### ISSUE TITLE
$anchorScroll on root page

### ISSUE THREAD

**Issue by Grandiz** [angular/angular.js#12051]
Hi. I have some issue this anchors and html5mode. If i go for example to domain/foo#bar, this work properly, but if i want go to domain/#bar i get redirection to domain/bar

**Comment by gkalpak** [comment]
@Grandiz, does `domain#bar` work as expected ?
(This sounds more like a `$location` issue, rather than `$anchorScroll` (but I'm not sure yet).)

**Comment by petebacondarwin** [comment]
@Grandiz - please provide a running example of this problem. It is very hard to help you otherwise.

**Comment by divmgl** [comment]
This happens to me as well. If I route a URL which is formatted as "localhost:1337/applications/foo#bar" then my anchor will work as intended. However, "localhost:1337/applications/#bar" will scroll to my anchor and then immediately scroll all the way up. This is an extremely annoying issue that I hope I will be able to solve.

**Comment by petebacondarwin** [comment]
Please can you provide a running example?

**Comment by Narretz** [comment]
Closing because we don't have a reproduce scenario.
