### ISSUE TITLE
ng-if doesn't parse typeof right

### ISSUE THREAD

**Issue by cionescu** [angular/angular.js#12057]
ng-if doesn't parse typeof statements correctly

**error:**
Syntax Error: Token 'e' is an unexpected token at column 8 of the expression [typeof e != 'boolean'] starting at [e != 'boolean'].

**Code:**
```
<li ng-repeat="e in entry">
 <div ng-if="typeof e  == 'boolean'">
  Yes				
 </div>
 <div ng-if="typeof e != 'boolean'">
  No					
 </div>
</li>
```

where the entries array is defined as [0, 1, 2, 3, true, 5, 6, 7, 8, 9]

**Comment by gkalpak** [comment]
`ngIf` evaluates [Angular expressions][1] (not JavaScript expressions) against the current `Scope` (not the global context, e.g. `window`). Things like `typeof` are not available on the `Scope` (nor are they supported in Angular expressions), thus you get an error.

You proper way to do it, is define a function on the `Scope` and then call is from the view:

```html
<div ng-repeat="item in [1, 2, true]" ng-if="isBoolean(item)">
  {{ $index + 1 }}. {{ item }}
</div>
```
```js
// Inside the controller
$scope.isBoolean = function (value) {
  return typeof value === 'boolean';
};
```

[Demo pen][2]

--
That said, this is rather a general support question and as such should have been directed to the [appropriate channels][3]. GitHub is reserved for bug reports and feature requests.

[1]: https://docs.angularjs.org/guide/expression
[2]: http://codepen.io/ExpertSystem/pen/GJmeqB?editors=101
[3]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
