### ISSUE TITLE
ng-model does not update selected radio input value on specific Android version

### ISSUE THREAD

**Issue by nodohoung** [angular/angular.js#12055]
I am developing an angular - webview based android app. It targets on Lenovo A536 (Android 4.4.2).
I used the following template:

``` html
<form>
    <div class="radio">
        <label>
            <input type="radio" name="answer" ng-model="test.answer" value="a"/>
            <span>
                A.
            </span>
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="answer" ng-model="test.answer" value="b"/>
            <span>
                B.
            </span>
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="answer" ng-model="test.answer" value="c"/>
            <span>
                C.
            </span>
        </label>
    </div>
    <p>Answer is <strong>{{test.answer}}</strong></p>
</form>
```

Everything is working fine on my HTC One X+ (Android 4.2.2).
**But on Lenovo A536**, the model value `test.answer` is not updated (remained undefined) when I select a radio button (radio button has displayed checked) _within a few seconds_ after the page loaded. And it seems angular is then freezed a few seconds because I can't select another radio within that time range.
The model value `test.answer` is updated if I do selection after a few seconds since the page loaded or if I do selection 2 or more times (on the same radio or different radio inputs).

When I select within a few seconds (about 4 seconds) after the page loaded:
![screenshot_2015-06-09-16-22-23](https://cloud.githubusercontent.com/assets/5056656/8055071/2e9a1f38-0ec7-11e5-8362-7e2647fe60be.png)

When I do selection after a few seconds since the page loaded or when I do selection 2 or more times:
![screenshot_2015-06-09-16-22-32](https://cloud.githubusercontent.com/assets/5056656/8055111/75bd2496-0ec7-11e5-9738-bf1c4b4be526.png)

Tested on:
- angular (angular + angular-touch) version 1.3.15, 1.3.16.
- bootstrap css version 3.3.4
- android api 17

Thank you!

**Comment by Narretz** [comment]
So it seems to be a problem with the device, not with angular. What version does the embedded webview have? Is it different?

**Comment by nodohoung** [comment]
I don't know how to check version of the embedded webview. But I think it's the default android webview engine shipped with the Android OS.

My webview setup:
```java
WebView webView = (WebView)findViewById(R.id.webView);
webView.getSettings().setJavaScriptEnabled(true);
webView.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
webView.setWebChromeClient(new WebChromeClient());
webView.loadUrl("file:///android_asset/index.html");
```

I tested on several phones (Lenovo A536), all ran into the problem. I don't have any other Android 4.4.2 device to check if the problem is from Android OS version or it is device specific.
My HTC phone is running Android 4.2.2 and its built in webview is surely different from the Android 4.4.2 (Lenovo A536).

**Comment by Narretz** [comment]
The webview basically uses the Android or the Chrome browser engine. It should be possible to the get the version number of that.

**Comment by moravcik** [comment]
I am developing webapp both desktop and mobile and it seems I am experiencing the same problem, radio button selection doesn't update the model. I am testing it in mobile Chrome browser shipped with the device (LG G4).

**Comment by Narretz** [comment]
Closing this as it's difficult to assess bugs in individual devices. I assume there could be some interop issues with other frameworks such as ionic here.
