### ISSUE TITLE
Uncaught TypeError: $browser.addPollFn is not a function

### ISSUE THREAD

**Issue by agjs** [angular/angular.js#12056]
Hey there guys. 
I've tried to upgrade to ng 1.4.0 and after I did so I got: 

Uncaught TypeError: $browser.addPollFn is not a function

Currently I had to downgrade do 1.3.6 until I realise whats the issue. Tried to Google the issue but no luck with responses. 

Thanks in advance,
Alek

**Comment by agjs** [comment]
Problem is solved by updating angular-cookies and angular-resource both to 1.4.0

**Comment by pkozlowski-opensource** [comment]
> Problem is solved by updating angular-cookies and angular-resource both to 1.4.0

Yes, you need to use all the files from the same release.

**Comment by syzer** [comment]
:+1: this answer helped me.

**Comment by Steffi3rd** [comment]
Worked for me.

**Comment by liyatang** [comment]
Thanks!

**Comment by itsazzad** [comment]
:100:

**Comment by BrutalBrutus** [comment]
Perfect. This works, +1: " you need to use all the files from the same release."

**Comment by artdias90** [comment]
+1

**Comment by DinhAnhTu** [comment]
Thanks!  A+ :+1:

**Comment by ksiabani** [comment]
+1

**Comment by yuanxiaowa** [comment]
+1

**Comment by joshuaebowling** [comment]
+1

**Comment by Sachin51** [comment]
Update angular using:  bower update angular. That's enough, your project will be working fine. :)

**Comment by artdias90** [comment]
time to close this?

**Comment by Sachin51** [comment]
Yes it can b closed now

**Comment by oshingc** [comment]
+1

**Comment by knightbenax** [comment]
Still have this problem. All are in the same release. Using Angular 1.2.16

**Comment by sunfuhao** [comment]
thanks

**Comment by DnyaneshD** [comment]
Thanks that worked from me as well 👍

**Comment by benjaminug** [comment]
Perfect! Thank you

**Comment by crosas14** [comment]
It works!
