### ISSUE TITLE
ngShow - 1.4 behavior

### ISSUE THREAD

**Issue by jayoungers** [angular/angular.js#12062]
Has anyone else run into issues with ngShow in 1.4?  This problem is only occurring for me on a single page, so I'm not sure if I can reproduce it in a jsfiddle.  If no one else has been seeing this, I'll try to delve a little deeper to determine why this specific situation is triggering the problem.

My markup looks like so, with the expression pieces of my ngShow printed out in the html prior to it (added for debugging purposes):

![image](https://cloud.githubusercontent.com/assets/6578515/8059337/1c870d8e-0e85-11e5-8a67-b8e35b53085b.png)

And in this use case, ngShow should evaluate to true, and it should display.  However, this is what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/6578515/8059371/58e02f0e-0e85-11e5-9196-390ec63528a1.png)

Anyone know how this is possible?  As you can see the exact same expression evaluates to `true` in the binding prior to the ngShow binding.  If I change the angular version to 1.3.16, the problem goes away

**Comment by Narretz** [comment]
Can you please test with the latest snapshot? http://code.angularjs.org/snapshot/angular.js

**Comment by jayoungers** [comment]
It looks like the problem is still there against that version as well.

My guess is it's some sort of timing issue:  the page has a group of "customizations" it can display, so if I switch from the first "SelectedCustomization" that I select to another, and then back to the original one, it will correctly display - it's as if the first time the directive this code is contained in is loaded, this particular ngShow isn't watching for changes.

One other note is it appears to be working correctly in IE11, but not the current version of Chrome or IE10.  I'll try to do some more research to see if I can boil the problem down to something reproducible outside of our code base.

**Comment by jayoungers** [comment]
I think I'm going to close this for now.  

I narrowed the problem down to the directive referring to a saved `$http` promise that had already been run.  If I use a new `$http.get` call the issue goes away, or if I use the existing promise object and wrap the logic in a `$timeout` the issue also goes away.

For the life of me, though, I was not able to find a way to reproduce it such that the inline {{}} binding would be correct with the ngShow binding being incorrect.

This should have been a close approximation, but I can't get it to fail: http://jsfiddle.net/umuxocq1/
