### ISSUE TITLE
Having custom Object.prototype method prevents form validation

### ISSUE THREAD

**Issue by funkflute** [angular/angular.js#12066]
I'm running into this issue that if I set a custom Object.prototype method, it stops form validation from updating:

    <!DOCTYPE html>
    <html lang="en">
    	<head>
    		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    		<title>Test</title> 
    	</head>
    	<body ng-app>
    		<form name="testForm" novalidate>
    			
    			<input type="text" name="test" ng-model="test" required> Field Valid? {{testForm.test.$valid | json}}
    		</form>
    		Form valid? {{testForm.$valid | json}}
    
    		<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0/angular.min.js"></script>
    		<script>
    			// remove this line and validation works again
    			Object.prototype.someThing = function() {}
    		</script>
    	</body>
    </html>

**Comment by ryanhart2** [comment]
Here is a plunk http://plnkr.co/edit/XauBqEKawyDyk21RFc1r?p=preview demonstrating the behaviour (the prototype method is set in script.js). The issue seems to have started in version 1.3.0-rc.1 so that is what I have used in the plunk.

**Comment by lgalfaso** [comment]
The check that there are no errors in the errors object was not checking that any of the properties comes from the Object.prototype. #12075 should take care of this
