### ISSUE TITLE
Directive within ng-if won't run

### ISSUE THREAD

**Issue by alarv** [angular/angular.js#12063]
I have a custom directive ```myDirective``` that performs a task on an element.

I have this directive in an ng-if block
```
<div ng-if="condition">
    <div my-directive></div>
</div>
```
Something like this fiddle: http://jsfiddle.net/hGnvv/ only the ng-if condition turns to true after my $http requests are loaded.

The directive is probably compiled during runtime, but never linked, so the code never runs. If I replace the ng-if by ng-show the directive works fine.

I can't use ng-show because I have 130 directives within the form. 20 directives run anyway, and the other run according to my object type.

* ng-if="type == 1" then load these elements
* ng-if="type == 2" then load other elements etc.
If I change the ng-if to ng-show, the form takes 8s to load instead of 1s.

Any solutions?

**Comment by pkozlowski-opensource** [comment]
For me it works as expected, see: http://jsfiddle.net/kuj4bjz9/
In short: directives are not linked till you've got instances of those in the DOM. ngIf will remove / prevent elements from being inserted in the DOM thus no linking function.

BTW: you are using a really ancient version of AngularJS (not that it matters for this use-case).

Closing, as it works as expected.
