### ISSUE TITLE
route has problem

### ISSUE THREAD

**Issue by joebnb** [angular/angular.js#12069]
```
http://localhost/projectocean/src/web/#/open/info#tid=1315731
$rootScope.$on('$routeChangeStart',function(evt,next,current){
condition for check permission jump
}
```
the angular rout next.originalpath will match #tid=1315731 and it will crash on permisson and no jump,i think angular should be just match the path between first and second #

**Comment by gkalpak** [comment]
I am not able to reproduce it (based on the provided info).

@joebnb, could you provide a runnable demo of the issue (e.g. using CodePen, Plnkr, JSFiddle etc) ?
This might depend on a number of things (e.g. version of Angular, `$routeProvider` configuration etc).

<sub>(You could use [this pen][1] as starting point.)</sub>

[1]: http://codepen.io/ExpertSystem/pen/gpRprm?editors=101

**Comment by joebnb** [comment]
thanks for watch,i'm chinese,i‘m afraid of jsbin jsfiddle,the goverment hijacked DNS,
i could writen the detail of requirement
```
$rootScope.$on('$routeChangeStart',function(evt,next,current){
condition for check permission jump
}
//in my requirement the /open/info is public for visit
//if i enter: http://localhost/src/web/#/open/info#tid=1315731
//the next.originalpath in $routeChangeStart event is /open/info#tid=1315731
//the route $changestart event also contains param and angular determined /open/info#tid=1315731 not in public array and it was private

```

**Comment by gkalpak** [comment]
You could at least share the exact code that one can use to reproduce the issue.
What is your `$routeProvider` config ? What version of Angular are you using ?

**Comment by joebnb** [comment]
1.3.15 this problem has fix with another wayswhatever(i use preg match to filter out this url,problem still exist),i dont konw is location.path() trans # to %23 cause problem?whatever
