### ISSUE TITLE
Restart/reload Angular app

### ISSUE THREAD

**Issue by alexandernst** [angular/angular.js#12070]
I'm working on a project with Yii2 and Angular. The structure of the code is as follows:

```html
<html ng-app="myApp">

    <head.../>
    <body>
        ...
        <div class="body-content"> MAIN CONTENT GOES HERE </div>
        ...
    </body>

</html>
```

The page contains a header and a column on the left and a center area which is rendered inside the .body-content div. Now, as you can imagine, I have some buttons in there, some other angular widgets, etc..

Yii2 has a really cool feature called renderPartial that will re-render a view file without wrapping it again in the <head> and <body>. I use that to update the content of my main area, by calling that function, getting the response with jQuery and replacing the content.

Now, that causes all buttons that where binded with Angular to stop working (I'm guessing why). My question is: How can I make Angular re-run or re-bind all my (new) DOM elements to their actions?

PS: I'm using a PHP backend with Angular because I want the best from both worlds. PHP is faster than JS and it's easier to get a webpage ready for SEO (Angular on the other hand needs to go the prerender.io way). Yii2 in particular has tons of ready-to-use widgets, while Angular is just a DIY solution. Angular is very good at handling user interaction and makes it very easy to handle scenarios with lots of inputs.

**Comment by pkozlowski-opensource** [comment]
You would have to $compile and link the content returned from the server. You might check this SO answer to learn more about various services in AngularJS that are used to process template content: http://stackoverflow.com/a/17901134/1418796

Closing, as this is a general support question that should be asked using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
