### ISSUE TITLE
Linky does not work with case-insensitive schemes

### ISSUE THREAD

**Issue by BiohZn** [angular/angular.js#12073]
According to RFC 3986 (http://tools.ietf.org/html/rfc3986#section-3.1) scheme such as http or mailto are case-insensitive. So links such as http://server/ and HTTP://server/ are valid and equivalent.

However, the linky filter recognizes only links with lowercase schemes as links. While http://server/ will be recognized as a link, HTTP://server will be not.

NOTE: This is a duplicate of #3210

**Comment by petebacondarwin** [comment]
@BiohZn - would you like to make a PR from your commit with an appropriate unit test?

**Comment by BiohZn** [comment]
@petebacondarwin I'm not 100% comfortable with making unit tests, but I can add some, yes.

**Comment by petebacondarwin** [comment]
Magic. It is fun to get outside your comfort zone. I will help you as you need it. Take the tests in https://github.com/angular/angular.js/commit/7fef06fef9b6af4436f9fed10bd29d0a63707614 and https://github.com/angular/angular.js/blob/master/test/ngSanitize/filter/linkySpec.js#L27-L36 as starting points.

**Comment by BiohZn** [comment]
@petebacondarwin one misconfigured git commit later, it should now be ok
