### ISSUE TITLE
Dynamically disabling of radio buttons not working.

### ISSUE THREAD

**Issue by orsonjones** [angular/angular.js#12077]
I'm trying to work with a list of radio buttons where some of them need to be dynamically enabled/disabled. Here is an example: http://jsfiddle.net/51fce7bs/ In the example, when it first initializes the radio buttons, everything seems to be working correctly. After clicking update (trying to enable second and disable third) the text and css are updated, but the radio buttons don't change their disabled status.

Might be related to issue #8014

**Comment by pkozlowski-opensource** [comment]
`ngDisabled` takes an expression and not interpolation, so you need to write: `ng-disabled="thing.disabled"`: http://jsfiddle.net/oocx2zz4/

**Comment by orsonjones** [comment]
I can't believe I missed that! Thanks so much.
