### ISSUE TITLE
Naming conventions. Starts controller name with lowercase letter

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular.js#12071]
Why controller name starts with capital letter? Resource starts with capital letter because it is class, that returns instances. Controller is ordinary function and must begin with lowercase letter like most of services.

**Comment by pkozlowski-opensource** [comment]
Controller function is a constructor function that is used to create controller instances. It is a common practice to name constructor functions starting with upper-case.

**Comment by lgalfaso** [comment]
Hopefully that solves the issue :)

**Comment by tamtakoe** [comment]
Controller function is not a constructor function because you don't use `new`, and you don't create instances manually as Resource (`var phone = Phones.get({id: 123})`). Controller function similar to the usual function.

If the controller is similar to the usual function, is invoked as a usual function and works as a usual function, so this is a usual function (regardless of their implementation), and must be named with a lowercase letter.

**Comment by pkozlowski-opensource** [comment]
> Controller function is not a constructor function because you don't use new

Framework is actually calling `new`, so those are closer to constructor functions in the sense that those are used to create instances instead of being called directly
