### ISSUE TITLE
ngRoute exclude option

### ISSUE THREAD

**Issue by mrodrig** [angular/angular.js#12088]
Hi,

I'm on Angular 1.3, but searched for a while and couldn't find anything about how to cause ngRoute to exclude certain 'routes' from being "intercepted" and run through the router.  For example, say I want to have a directory server-side with attachments in the `/attachments` path.  Then, in my HTML, I want to link to an attachment: `<a href="/attachments/latest-copy-of-file.pdf">Latest Copy of a File</a>`.  Right now the router that I set up is intercepting this request and redirects me to my `.otherwise(...)` route which is not the desired behavior.  I'm not sure if I missed it, but it would be nice to be able to do something like: `.exclude('/attachments*')` which causes the request to go through to the server.  I don't believe it exists, but I apologize if I missed it.

Please let me know what you think.

Thanks,
Mike

**Comment by Narretz** [comment]
You can tell angular to ignore location changes by specifying a `target` attribute: https://docs.angularjs.org/guide/$location#html-link-rewriting

**Comment by mrodrig** [comment]
Thanks! That works well
