### ISSUE TITLE
ngRepeat doesn't refresh DOM on simple array update

### ISSUE THREAD

**Issue by zishanj** [angular/angular.js#12084]
I am using simple array of numbers like below with `ng-repeat`:

    n = [1,2,3,4,5,6]

The issue is, when I change this array for eg:

    n=[1,2,3]

It doesn't fully reload the DOM but instead it just remove the last 3 `div` elements related to array `4, 5, 6`. Is there any way to force the `ng-repeat` to reload DOM everytime I change the array.

**Comment by Narretz** [comment]
`ngRepeat` tries to reuse element as much as possible to avoid updating the DOM too much. When you have numbers and strings in your collection, ng-repeat can track elements by default, even though you replace the whole collection. With objects, you will not see this reuse, unless you use a track by expression.
Why exactly do you need ng-repeat to rerender every time you update the collection?

**Comment by zishanj** [comment]
@Narretz Actually I am switching between different models. For example in one model I have 114 array elements and in another I have 30 array elements. When I switch between models, it only update it's content. But I need to reload the complete DOM with animation for better user experience.

**Comment by zishanj** [comment]
I have tried to use custom function also in `track by` but that also doesn't work.

**Comment by Narretz** [comment]
You could use a track by function that returns a unique, random id. something like `Math.random() + Date.now()`. But I don't really recommend it.

**Comment by zishanj** [comment]
@Narretz I already tried it but it doesn't work, because it doesn't add `$$hashkey` to the simply array of integers. It only does it when using objects.

**Comment by Narretz** [comment]
http://plnkr.co/edit/4Cf9Xq08sagGeEOH2gXW?p=preview

You can test that the elements do not get reused by giving them a random class via the developer tools. When you set the list, the classes will be gone, which means the element has not been reused.

**Comment by lgalfaso** [comment]
I do not see this as an issue as this is the way that ngRepeat works.
If you need support on how to use Angular, then I would recommend you that you post your question on StackOverflow
