### ISSUE TITLE
ng-if Preventing Select Change

### ISSUE THREAD

**Issue by JimAdkins** [angular/angular.js#12090]
I'm not sure if this is a bug or not. I just started using Angular, so this may be intended behavior. I have a select with some options in it. I have a link to change the select to the first option. When I use ng-if to show the select and link on the page, my "Change" code will work as long as the select isn't dirty. Once you select a different option and the select element is dirty, the "Change" click doesn't work. 

If I change the ng-if="showDropdown" to ng-show="showDropdown", the code works perfectly. Is this intended behavior? 

http://codepen.io/anon/pen/rVwJvg

    <div ng-app="myapp">
      <div ng-controller="MyController">
         <form name="theForm">
          <div ng-if="showDropdown">
            <select ng-change="changeClientId(clientListModel)" ng-model="clientListModel" ng-options="client.CompanyId as client.CompanyName for client in clientList">
            </select>
            <a href="#" ng-click="changeSelectedOption()" style="padding-left: 10px;">Change</a>
          </div>
        </form>
      </div>
   </div>

        angular.module("myapp", [])
      .controller("MyController", function($scope) {
        $scope.showDropdown = true;
        $scope.clientList = [{
          CompanyId: 1,
          CompanyName: "Nissan"
        }, {
          CompanyId: 2,
          CompanyName: "Toyota"
        }, {
          CompanyId: 3,
          CompanyName: "Fiat"
        }];

        $scope.changeSelectedOption = function() {
          // set selected value to yet another value
          $scope.clientListModel = $scope.clientList[0].CompanyId
        }
      });

Thanks! -Jim

**Comment by gkalpak** [comment]
This is working as expected:

* `ngIf`: will remove the element form the DOM (if evaluated to false`), so there is no `select

--
That said, this is a general support question and should have been directed to the [appropriate channels][1]. GitHub is reserved for bug reports and feature requests.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by gkalpak** [comment]
This is working as expected:

* `ngIf`: will remove the element form the DOM (if evaluated to false`), so there is no `select` element (and thus no `ngChange` listener).

* `ngShow/Hide`: will just (visually) hide the element (using `display: none` by default), but the element is still present in the DOM and all it's binding/listeners are active.

--
That said, this is a general support question and should have been directed to the [appropriate channels][1]. GitHub is reserved for bug reports and feature requests.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
