### ISSUE TITLE
how to use overlap(&&) operator?

### ISSUE THREAD

**Issue by SanderElias** [angular/angular.js#12092]
I have this: `select * from tab;e  where ARRAY['a tag','antoher'] && tags`
in English, I have an field tags that is an array of text fields. Now I need to get all records that have any of the items in my array. 

How do I express this with sql-bricks?
I know it's an postgres extension, but I think it needs another operator.

**Comment by gkalpak** [comment]
Is this by any chance intended for another repo ?

**Comment by SanderElias** [comment]
Yes it is! sorry..
