### ISSUE TITLE
$browser.defer().cancel() to keep testability in unstable state.

### ISSUE THREAD

**Issue by alfonso-presa** [angular/angular.js#12108]
## TL;DL

This issue is two things, a request and a question:
* Is $browser.defer().cancel() the best pattern available to make the testability waitStable callbacks to wait until something is completed.
* If so... ¿shouldn't it be documented somewhere?

## Background
Let's say you have an application that's being tested with a framework relying in the $$testability service (like protractor). It has an open websocket connection and when you click a button it sends a request to the backend and expect a response. AFAIK the $$testability.whenStable notification will be triggered immediately because angular is not aware of this flow, so it's necessary for the application to "do something" in order for this to work correctly.

## Pattern
I've been able to solve this kind of situations by applying the following pattern:
```js
var promise = doMyWebSocketStuff();
var id = $browser.defer(function () {console.log('Ooops');}, VERY_BIG_TIMEOUT);
promise.finally(function () {
    $browser.defer.cancel(id);
});
```  
¿Is there any other way of handling this?

## Request
IMHO I think this is something that should be easier to do and of course it should be documented. I was planning to:
* PR with an addition to docs to document this but $browser is not public so... where?
* PR with a better API for this in something like $$testability.unstableUntil(promise), but I'm not sure if that's the correct place for such a functionality. 

What do you think?

Thanks!

**Comment by lgalfaso** [comment]
I can answer half of the issue. `$browser` and `$$testability` will not be documented, they are private and should not be relied upon. Read this as, this may break or change in any release including a patch release.

Now just based on the nature of a web socket, without some testability built in and some information from the running  test, it is not possible to know if there is a pending message from the server. This is, without this information, it is no possible to know if the test is done or not. IE, the library that you are using when calling `doMyWebSocketStuff()` and your test should cooperate with your testing library to expose when the test is done.


I am ok in keeping this open, but it might be better to track this at [protractor](https://github.com/angular/protractor) or the testing framework that you are using.

ping @juliemr

**Comment by alfonso-presa** [comment]
Thank you for the reply Lucas. I completely understand your point.

I though that as protractor is built to "waitForAngular" and AngularJS is taking track of the "pending async tasks" it would be nice to expose this tracking so that other services built on top of angular could benefit from this angular+protractor synergy. It's not only about websocket based services but also webworkers, graphics rendering libraries, web component solutions, services built on top of libraries like apache thrift. I really think there's something that can be improved in this Protractor+AngularJS ecosystem to make testing with third party angular services more transparent.

I agree in that it should not be angular's responsibility to provide this tracking, but neither it is protractor's. In fact I opened this issue (https://github.com/angular/protractor/issues/2246) recently in protractor to built a framework independent specification to keep this unstable browser state tracking for everyone needing it (other testing frameworks, other libraries, etc), and also decoupling protractor from angularjs implementation details. In the mean while I though it will be a good solution to use current angular's mechanism as it works seamlessly with protractor.

As part of my proposal I plan to build an specification and a reference implementation, and also provide a protractor plugin and an AngularJS component or a PR to integrate this with $browser current tracking. Do you see this like something interesting for the AngularJS and protractor's projects or I'm I just loosing my (and your) time? :-).

Thanks!

**Comment by lgalfaso** [comment]
I cannot answer this on behalf of the entire team, so this is just my personal opinion.

There is an interest to make web sockets and web workers play better with angular. About the other named options, I do not feel qualified to say how big the interest is, so I would just ask other contributors to express their opinions. Now, when any of this happens, the testability of such components should be built-in.

Now, how this should be done is quite hard of a challenge, if you would like to tackle this, I would encourage you to do so, but to do so first as a third party module.

**Comment by alfonso-presa** [comment]
Thank you very much again Lucas. That's all I needed to read to keep on working on this ;-). Of course I'm not aiming to address the whole websocket and webworkers problem but to ease their testability implementation.

Thanks!

**Comment by alfonso-presa** [comment]
I was thinking about this and I realized  that $timeout delegates to $browser.defer and it's public. I guess the following pattern will be better to achieve the same behaviour as mentioned before (making angular and thus protractor aware of a pending task running) and using only public angular API.

```js
var promise = doSomeAsyncNonAngularStuff();
var timeoutPromise = $timeout(function () {console.log('Ooops');}, VERY_BIG_TIMEOUT);
promise.finally(function () {
    $timeout.cancel(timeoutPromise);
});
```

**Comment by lgalfaso** [comment]
As long as you keep in mind https://github.com/angular/angular.js/blob/master/src/ngMock/angular-mocks.js#L66

BTW, I do not think there is anything else to track that should be part of angular, so I am closing this

**Comment by alfonso-presa** [comment]
Thank you for the tip. This is for e2e testing so there should be no plage for ngMock I guess :-).
