### ISSUE TITLE
ngAnimate is not smooth

### ISSUE THREAD

**Issue by zishanj** [angular/angular.js#12104]
Why ngAnimated is not smooth? It always makes the screen jumps downward even if I have used CSS classes using `$AnimateCss` in angular version 1.4. This jumping of the screen has always been the issue prior to version 1.4 also. This jumping downward of the screen is suitable only for list data but when I need to use block of elements with `FadeIn` animation, this really looks awkward.

**Comment by lgalfaso** [comment]
Would it be possible to have a plunker that shows the issue?

ping @matsko

**Comment by havenchyk** [comment]
@zishanj could you please create an example at plnkr.co or jsbin?

**Comment by Narretz** [comment]
Closing due to missing info.
