### ISSUE TITLE
Angular " OrderBy: '' " (empty string) no longer sorting by index

### ISSUE THREAD

**Issue by TheMcMurder** [angular/angular.js#12100]
In previous versions of Angular (1.2) when you passed an empty string to the OrderBy in an ng-repeat it would order by the index of each item in the array.

Now (1.3.15 & 1.4.0) it orders very differently. [This plunk](http://plnkr.co/edit/WSVdJq7unEEElo9LBzzr?p=preview) shows 1.2, 1.3.15, and 1.4.0 and how the order by functions differently in each case. 

It should order by index if OrderBy isn't specified.

**Comment by Narretz** [comment]
This is going to be fixed in 1.4.2 with https://github.com/angular/angular.js/commit/48e1f5605edd32a63318fd78f5165c7d1f1a20f9
It broke in 1.3.0-rc.5 in https://github.com/angular/angular.js/commit/607f016a0ba705ce40df0164360fb96a9d7f5912

**Comment by jawang35** [comment]
Any chance this could be fixed in 1.3.x as well?

**Comment by lgalfaso** [comment]
Fix landed as 48e1f5605edd32a63318fd78f5165c7d1f1a20f9
