### ISSUE TITLE
unable to set default selected option in selection tag using angular.js 1.4.0

### ISSUE THREAD

**Issue by joemalski** [angular/angular.js#12105]
I have encountered issue with angular.js 1.4.0.  I can't set the default in select tag if I will use a 'number' but it will work if I use a 'string'.  The select statement is hard code in the view.  I already initialize my model in the controller. 

// This will NOT WORK, value passed is a 'number'
$scope.colors = 2;

// This will WORK, value passed is a 'string'
$scope.colors='2';

Please see codepen:  http://codepen.io/joemalski/pen/YXQMKO

If I use angular.js version 1.3.15, both 'number' and 'string' will work.

Note: angular version set in codepen is 1.4.0 so you can see the error.

**Comment by ryanhart2** [comment]
This is a documented breaking change: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#140-beta0-photonic-umbrakinesis-2015-01-13

**Comment by joemalski** [comment]
Thanks for the update.
