### ISSUE TITLE
Throw exception when circular template reference

### ISSUE THREAD

**Issue by nhduc296** [angular/angular.js#12109]
```
angular.module('abcApp')
        .when('/inventory', {
//circular reference
          templateUrl: 'js/inventory/inventoryDirective.html'
        })
```

```
(function () {
  'use strict';

  function inventoryDirective() {
    return {
      restrict: 'EA',
      scope: {},
      controller: 'inventoryController',
      controllerAs: 'vm',
//circular reference
      templateUrl: 'js/inventory/inventoryDirective.html'
    };
  }
```

**Comment by pkozlowski-opensource** [comment]
Not sure how we could go about this, technically speaking, nor if it is worth the overhead. But you should be getting already an error from a browser, no?

For now I'm leaning towards "won't fix" - while I'm all for having great error messages we need to keep in mind that each error message has cost (bytes added to the framework + CPU). So we need to make sure that we are creating overhead for rare cases (and I believe this one isn't very common)

**Comment by lgalfaso** [comment]
Agree with @pkozlowski-opensource. The fact that `templateUrl` can be a function and can change the value it returns does not make it any easier.

Closing this as wont fix

**Comment by nhduc296** [comment]
@pkozlowski-opensource 
Chrome was stuck, I have to kill that tab
