### ISSUE TITLE
Dynamic DOM not trigger button click.

### ISSUE THREAD

**Issue by dev33250240** [angular/angular.js#12117]
I am using a table structure and apply datatable.net to it. Table populating its row and column data by angularjs and there is also edit or delete button. All are working fine. as soon as i want to implement nested table i just put a hidden td and when we click on expand i dynamically convert td to tr. But dynamically created tr not support any angular event like click etc.
I hope its using bind onclick how we bing "live" onclick of jquery.
Please guide us.

**Comment by Narretz** [comment]
Please ask support question on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem Thanks!
