### ISSUE TITLE
 $resource parameter object with array values cannot be passed to server

### ISSUE THREAD

**Issue by xforceco** [angular/angular.js#12115]
In angular (1.3.16), for 'Stories' as a resource defined by a factory, I run
...
Stories.query({array: [1,2,3], a: 1},callback);
...

In node (latest stable), 
...
router.get("/stories",function(req,res,next){
   console.log(req.query);
});
....

Output:
{a: 1}

'Expected' Output:
{array: [1,2,3], a: 1}

I am not sure whether it is the same with the following fixed issue, it looks similar though
https://github.com/angular/angular.js/issues/2256

**Comment by gkalpak** [comment]
This eems to [work as expected][1]. If you check out the console, you'll see that the requested URL's query part for `Stories.query({a: 1, b: [1, 2, 3]});` is: `?a=1&b=1&b=2&b=3`.
Maybe it is a Node.js issue or something in between.

In any case, it doesn't seem to be an issue with `ngResource`.

(Feel free to reopen, if you can provide more info showing that it is something in Angular/ngResource that causes a problem.)

[1]: http://codepen.io/ExpertSystem/pen/QbMEKz?editors=001

**Comment by xforceco** [comment]
You are right, I found I am actually stuck with a bug in my code instead
