### ISSUE TITLE
How can I revalidate form after appending compilled content into ng-form in Angular?

### ISSUE THREAD

**Issue by mciastek** [angular/angular.js#12119]
I have a form with nested ng-forms where on each key press user make script append a compiled form fields (like ui-select, ui-datepicker, etc.) to container with ng-form directive.

How can I trigger validation after content is replaced in ng-form?

<a href="http://jsfiddle.net/mciastek/e3bd0sme/">Simple demo on JSFiddle</a>

If you want to reproduce the bug, append field by typing into textarea word "date", then remove appended field value, remove word "date" from textarea and type new one to refresh date field.

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem); these types of questions are ill-suited for GitHub. Thanks!
