### ISSUE TITLE
exponential notation in input[type=number] validation

### ISSUE THREAD

**Issue by mprokopowicz** [angular/angular.js#12121]
If we provide some long number, like 111111111111111111111111 in the input[type=number] and then click this little up/down arrow, then input value is converted to exponential notation: 1.11111111111111111e+23

Angular consider this is invalid value, but i think it should be still valid:
```
> typeof 1.11111111111111111e+23
< "number"
```

See this plunker:
http://embed.plnkr.co/hBmk7d/preview

**Comment by caitp** [comment]
Yeah, the number regexp doesn't deal with exponential notation currently. It shouldn't be a difficult PR to submit if interested
