### ISSUE TITLE
Decorating $templateRequest breaks ngAnimate

### ISSUE THREAD

**Issue by Antariano** [angular/angular.js#12127]
**Overview**
Decorating $templateRequest will break ngAnimate. The usual ng-enter, etc. classes are no longer added, and animations/transitions don't run.

**OS:** Windows 8.1, OSX, Windows 10
**Browsers:** Chrome, Safari, Firefox
**Angular Versions:** Reproduced on 1.3.14, 1.3.16, 1.4.0
**JSBin Reproduction:** http://jsbin.com/xefora/edit?html,js,output

It's probably me decorating incorrectly, but just in case I reported it here. Don't hit me! :(

**Comment by Antariano** [comment]
As I suspected, I did it wrong. 
Adding

```
        for (var key in fn) {
            $delegate[key] = fn[key];
        }
```

To the example fixes it, so I wasn't copying all attributes correctly.
Closing.

**Comment by williamweckl** [comment]
Was with the same problem and posting at stackoverflow I came up to the same solution.

http://stackoverflow.com/a/34036752/2767026
