### ISSUE TITLE
ngAnimate - Doesn't animate when the ng-repeat scope value is transformed

### ISSUE THREAD

**Issue by clementoriol** [angular/angular.js#12128]
Hello !
After updating to angular 1.4 and trying myself with the new ngAnimate module, I'm having an issue while trying to animate ng-repeat elements, with filtered data.

It looks like a bug with the module, more than my misdoing, so I'm submitting this issue : 

If the scope element the ng-repeat is iterating over is transformed in some way (like filtered (the native Array function) from a controller, in my exemple), ngAnimate gets a little crazy. When using "addClass" / "removeClass", the event almost doesn't trigger, so nothing is animated. When using "enter" or "leave", old copies of the repeated element are not destroyed. Without registrating the animation on the module, everything is fine.

I prepared two plunkers to illustrate the various issues : 

**addClass / removeClass issues :**
http://plnkr.co/edit/cpU7mBvHDfZu7OqSWyf4?p=preview

**enter / leave issues :**
http://plnkr.co/edit/07KUZxeeOasCfhv6hiFA?p=preview

**Reproducible**: always
**Browsers**: Chrome 43, Firefox 38
**Operating system**: OSX 10.9.5

Edit 1 : The issue remains the same when using custom filters with the angular filter module
Edit 2 : The issue only seems to happen when trying to animate an element containing a ng-repeat with filtered data (either filtered from the controller or using an angular filter)

**Comment by sreeramu** [comment]
addClass / removeClass issue is caused due to ngRepeat collection is dynamically changed so both enter and removeClass animation events are fired at same time as the animation enter event is structural event when the structural event is executed the parents classBasedAnimation(ie:removeClass) so that only removeClass is not executed.

'''
animateQueue.js file

if (animationDetails.structural) {
    closeParentClassBasedAnimations(parentElement);
}
'''

**Comment by Narretz** [comment]
The plnkr doesn't work. Did you forget to save it?

**Comment by Narretz** [comment]
The first issue is fixed in the current snapshot as far as I can tell. The second one seems to be broken still.

**Comment by Narretz** [comment]
The second issue is not an issue: you have to call the done fn in your javascript animations, otherwise the animator does not know when the animations are finished: http://plnkr.co/edit/RzV1Fj5aQpSPNoAhjWk9?p=preview
