### ISSUE TITLE
ng-include-component

### ISSUE THREAD

**Issue by Abrissirba** [angular/angular.js#12126]
I would like to be able to dynamically include a directive/component based on the component name much like we can do with templates in ng-include today. 

I'm developing a dashboard app that includes multiple kinds of widgets. At the moment each widget consists of a template and a controller. I'm rendering these widgets with an ng-repeat that loops over an array of widget configuration objects. Each config has a templateUrl which is used to include the widget template. An ng-controller at the top of the widget template is then instantiating the controller that should be used for the widget. What I don't like about this is that I have to think of my widget in terms of its url. I think it would be much nicer if I only had to refer to the component name instead. My proposal would look something like the example below.

    vm.widgets = [{
        component: 'widgetA'
    },{
        component: 'widgetB'
    }]

    <div ng-repeat="widget in dashboardCtrl.widgets>
        <ng-include-component name="widget.component"></ng-include-component>
        <ng-include-component name="widget.component"></ng-include-component>
    </div>

**Comment by pkozlowski-opensource** [comment]
You could easily create such directive without any changes to the core. It would be very easy: just $parse `name` attribute value and use the $compile service to "dynamically" process a specified directive.

I'm not sure this belongs to the core, though, as there would be many open questions on how to make it generic (what about scopes, how to pass arguments to directives etc.)

For now it would be -1 from me to include this in core as this is something easy to do in the user-land and hard to get right in the way it is generic for all the possible use-cases.

**Comment by Abrissirba** [comment]
Ok, fair points Pawel and I guess you are right about scopes and passing arguments. However, I created a gist on how I implemented if anyone would be interested in how I did it. https://gist.github.com/Abrissirba/157e4c3bb87e724b35e1

**Comment by pkozlowski-opensource** [comment]
Right, your directive looks like a good approximation of what I was thinking about (it is missing DOM nodes removal when watch fires etc.). But yeh, let's keep it in the user-land for now - we can always revisit if / when there is more interest / demand.

**Comment by Abrissirba** [comment]
Will not element.html(html) handle DOM removal?

**Comment by pkozlowski-opensource** [comment]
@Abrissirba maybe, not sure. Was just hinting that some special care needs to be taken to properly cleanup
