### ISSUE TITLE
ngAnimate - Providing only keyframe/keyframeStyles to $animateCss does nothing

### ISSUE THREAD

**Issue by intellix** [angular/angular.js#12124]
After realising that `keyframe` should actually be `keyframeStyles` for $animateCss I see that passing `keyframeStyles` alone will decide that there's nothing to do and return: `closeAndReturnNoopAnimator()`.

To get around this I have to do something like:
```js
$animateCss(ele, { 
  keyframeStyles: '1s my-anim ease',
  addClass: 'meh'
});
```

**Comment by Narretz** [comment]
The comment before the return in question says:
```
      // there is no way we can trigger an animation since no styles and
      // no classes are being applied which would then trigger a transition
```
(https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateCss.js#L560)

If that is correct, the documention needs to be updated. @matsko do you know if that is the case?

**Comment by matsko** [comment]
Excellent find. This PR will fix this issue and we should have it ready for tomorrow's release (1.4.3):

https://github.com/angular/angular.js/issues/12340
