### ISSUE TITLE
Adding 'ngMock' as a dependency module removes my partial view

### ISSUE THREAD

**Issue by Shawful** [angular/angular.js#12137]
Hello,

I'm not sure if my problem has to do with versioning or documentation.

I'm using angular 1.2.28 and my team has not yet moved to 1.3.

When I include 'ngMock' among my app's dependencies, the main page content is blank.  When I remove 'ngMock', the page content is shown.  Any idea what would cause this?

I'm just trying to set up unit tests and eventually set up protractor for e2e tests, but am just having some trouble.

Any help is appreciated!

Shawn

**Comment by Narretz** [comment]
You are not really supposed to add `ngMock` as a dependency for your real site. It's used to make mocking of certain services easier in unit tests and should only be used there. For e2e tests, you would probably test against a real backend, or mock it on a different level from angular.

**Comment by Shawful** [comment]
That makes obvious sense. Thanks.  I only list my app's dependencies in my app.js file (using yeoman), so I was confused.
