### ISSUE TITLE
$resource body data not supported for DELETE method - undocumented

### ISSUE THREAD

**Issue by rcollette** [angular/angular.js#12133]
The documentation for $resource states that all non-GET action methods support postData, however, looking in the code,  the resourceFactory function sets a variable called hasBody and does not include the DELETE method.    I'm not sure why it would be excluded, in addition to the documentation not indicating this.

See https://github.com/angular/bower-angular-resource/blob/master/angular-resource.js line 518

**Comment by pkozlowski-opensource** [comment]
Duplicate of https://github.com/angular/angular.js/issues/8567, let's centralize the discussion in there.
