### ISSUE TITLE
Angular JS

### ISSUE THREAD

**Issue by odl123** [angular/angular.js#12131]
I have created a login form in angular jS for login authentication. The ng-submit value is login1()
Now I implement the login1 function on my custom dashboard.min.js file as shown below.

angular.module("RDash").config(["$stateProvider", "$urlRouterProvider", function(e, t) {
    t.otherwise("/logg"), e.state("verify", {
        url: "/verify",
        templateUrl: "php/verifyAuthentication.php"
    })
}]);

function LoginController(s, l, h) {
    s.login1 = function() {
      console.log(s.user.username);
        var data = $.param({
            json: JSON.stringify({
                name: s.user.username,
                pass: s.user.password
            })
        });
        h.post(l.path("/verify"), data).success(function(data, status) {
            console.log(data);
        })
    }
}

angular.module("RDash").controller("LoginController", ["$scope", "$location", "$http", LoginController]);

I have deployed the entire code in apache tomcat and i am facing a POST error on clicking submit. The error is : 
Note : The submit button posts the request to a verifyAuthentication.php page..(Check above)

POST http://localhost:8080/tailf/[object%20Object] 404 (Not Found)

Can somebody let me know as to why am I facing this issue.

**Comment by Narretz** [comment]
Please ask support question on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
