### ISSUE TITLE
Isolated scope property for directive is being re-digested in version 1.4.1

### ISSUE THREAD

**Issue by kikhtenko** [angular/angular.js#12144]
Hi,

the issue is not reproducible in 1.4.0 and appears only in 1.4.1 as you can see in the link below 
http://plnkr.co/edit/kbIJflj4sL5kcCcYPzw7?p=preview

The problem is when scope property is changed in directive's controller then in the next digest cycle it's being rewritten.

Regards,
Andrew
@kikhtenko

**Comment by Nickproger** [comment]
+1

**Comment by vovashevchenko** [comment]
+1

**Comment by soutlan** [comment]
+1

**Comment by pbiryukov** [comment]
+1

**Comment by gkalpak** [comment]
It's probably a6339d3.

**Comment by Narretz** [comment]
Probably. Doesn't happen with `= `..

**Comment by asadovnikov** [comment]
+1

**Comment by petebacondarwin** [comment]
This issues is reopened as the fix was reverted.

**Comment by caitp** [comment]
@petebacondarwin missing a link/reason for the revert

**Comment by Narretz** [comment]
@caitp https://github.com/angular/angular.js/issues/12259

(If material relied on buggy behavior, we should fix it there rather than in core)

**Comment by gkalpak** [comment]
+1 @Narretz
It seems quite bizarre that we reverted a fix to a (rather serious imo) bug/regression, because the fix broke an external module.

IS anyone looking into why `ngMaterial` broke with the fix ?

**Comment by caitp** [comment]
I was looking into it earlier, but I can't get any tests to fail when the angular module has the revert reverted, and i couldn't find any demos that behaved weirdly (under tabs or autocomplete)

**Comment by caitp** [comment]
I'm not actually sure where the material tests are, because the file in the test directory just has a bunch of matchers, no tests

**Comment by caitp** [comment]
nvm, found em :> there's a ddescribe() in there preventing tests from running, sending pr

**Comment by petebacondarwin** [comment]
Thanks for looking into this everyone. I agree if material relied on buggy behaviour then it should be fixed there.

**Comment by petebacondarwin** [comment]
But since angular-material is a first class citizen of the Angular team then we ought to have a process in place to run angular-material tests before we do a release.

**Comment by caitp** [comment]
The main problem I'm seeing is that they're using `=?` isolate scope bindings to represent boolean attributes, which doesn't make a lot of sense. It doesn't die in the reverted version because the reverted version ignores expressions valued at the empty string, if they're optional (which we can probably still do)

**Comment by caitp** [comment]
All of the angular-material tests pass for me (with the revert reverted) with the following change:

```diff
           case '=':
             if (!hasOwnProperty.call(attrs, attrName)) {
               if (optional) break;
               attrs[attrName] = void 0;
             }
+            if (optional && isString(attrs[attrName]) && !attrs[attrName].trim()) {
+              break;
+            }
```

I don't know if there are still other problems, but if there are, they aren't causing test failures (there are 2 disabled tests in the tree still)
