### ISSUE TITLE
Can not load 'ngMessages' in my demo app

### ISSUE THREAD

**Issue by hckhanh** [angular/angular.js#12142]
When I import `'ngMessage'` to my app. It does not work, even does not display the Material theme.
If i remove `'ngMessage'` from the module. It displays the correct theme, but `'ngMessage'` doesn't work
How can I fix it?
![but](https://cloud.githubusercontent.com/assets/6380436/8198291/92e33d96-14ce-11e5-9fca-3590b54c4b40.png)

**Comment by hckhanh** [comment]
I follow the example in Material page of Angular
https://material.angularjs.org/latest/#/demo/material.components.input

**Comment by Narretz** [comment]
You need to include the angular-messages.js file like you have with angular.js etc.

**Comment by hckhanh** [comment]
Thahnk you #Martin Staffa.

On Wed, Jun 17, 2015 at 2:58 PM, Martin Staffa <notifications@github.com>
wrote:

> Closed #12142 <https://github.com/angular/angular.js/issues/12142>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/issues/12142#event-332896658>.
>



-- 
Thân,
Hoàng Châu Khánh
