### ISSUE TITLE
$http.delete causes non-zero Content-Length header in IE10 due to passing undefined to xhr.send

### ISSUE THREAD

**Issue by zps938** [angular/angular.js#12141]
Since 1.4.0-rc1 and confirmed in 1.4.1, calling `$http.delete('url')` in IE10 causes a non-zero Content-Length header to be added to the request. I noticed this when the webserver was returning HTTP error code 415 on all `$http.delete` calls.

I tracked this down to 1.4.0-rc1 where `xhr.send(post || null)` in createHttpBackend was changed to `xhr.send(post)`. When post is undefined, this problem occurs in IE10. The code below reproduces this bug in IE10 and is essentially what `$http.delete('url')` is doing.

    var xhr= new window.XMLHttpRequest();
    var post;
    xhr.open('DELETE', 'url', true);
    xhr.send(post);
Changing `xhr.send(post)` to `xhr.send(post || null)` fixes the problem.

**Comment by pkozlowski-opensource** [comment]
This was changed in e04a887c9b506de18516600310fe6e529d9d2ca3 (which looks like a valid fix). I guess we need to find another work-around for IE (probably be explicitly passing `null` for the requests without body)

**Comment by mstock** [comment]
This issue seems to affect AngularJS 1.4.3 on IE11 as well. I was able to work around it by passing `{ data: null }` as second parameter to the `delete()` method of the `$http` service.

**Comment by zps938** [comment]
This defect also affects POSTs with no data.
