### ISSUE TITLE
Chrome considered $http request cancelled with either timeout number or promise to still be "pending" indefinitely

### ISSUE THREAD

**Issue by spemmons** [angular/angular.js#12146]
I'm pretty sure the snippet below is correct. I don't think it matters that I'm using JSONP since I basically had the same problem when trying to use a simple "get" method. If the URL in this case does not respond and my timeout kicks, the "deferral.resolve()" correctly triggers the "error" method on the $http request, but in the Chrome tab for the page I see the "spinning" request-pending animation and the Javascript Console shows the request still "pending." Is there some way programmatically to convince Chrome that the request HAS been cancelled?

```javascript
    var deferral = $q.defer();

    $http.jsonp('http://something/api?callback=JSON_CALLBACK',{timeout: deferral.promise})
      .success(function(data){
        $timeout.cancel(timeout); // not sure if this is necessary, but assume it is...
        console.log('success! ');
      })
      .error(function(data, status){
        $timeout.cancel(timeout); // not sure if this is necessary, but assume it is...
        console.log('error! ' + status);
      });

    var timeout = $timeout(function(){
      if (deferral) {
        console.log('timeout! ');
        deferral.resolve();
      }
    },250);
```

**Comment by pkozlowski-opensource** [comment]
@spemmons actually it does make a difference when you do JSONP request as JSONP is a smart hack really and it is next to impossible to cancel requests in a reliable way.

Could you please provide a minimal, live reproduce scenario for non-JSONP requests? At the end of the day AngularJS is just calling `xhr.abort()` to cancel a pending request so if a browser doesn't honor this call, there is not much we can do...

Anyway, please provide a minimal, live reproduce scenario so we can have a look.

**Comment by Narretz** [comment]
I'm gonna close this as we have not reproduce scenario, Feel free to reopen with more information.

**Comment by mjy78** [comment]
We're seeing this same behaviour on Chrome on Ubuntu 16.04 when call $http.get().
