### ISSUE TITLE
ngTouch prevents focusing inputs at or below ngClick

### ISSUE THREAD

**Issue by OlenDavis** [angular/angular.js#12153]
You can see [my comment on this commit here](https://github.com/angular/angular.js/commit/0bbd20f255b2954b5c41617fe718cf6eca36a972#commitcomment-11730613) to explain the problem with that commit further. But, I truly don't understand how in an attempt to bust the redundant, original/"ghost click" click event (because it's being done faster than the original thanks to this wonderful work) we would also want to prevent the very likely *intended* behavior of also focusing a clicked focusable element. After all, it isn't as if this focusing behavior is also redundant; ngTouch's ngClick doesn't also focus the element if focusable when it triggers the click event. But before I contribute either a removal of this blurring "feature", or the addition of a speedier focusing *feature*, do you all agree that something must be done?

Because FYI, (and I'm sure I'm not the only one) my organization is relying my own copy of Angular *just* to remove this one line of code. (...which happened to break the login for my company's site, as well as all other inputs in all other dialogs, and even gave pause to my CTO that we should even be utilizing Angular to the extent we are considering this bug was because of migrating to 1.4.0 - though technically a minor release, it's hardly a *minor* release)

**Comment by xnuter** [comment]
+1

**Comment by Narretz** [comment]
Hmm, interesting. I don't even understand what problem https://github.com/angular/angular.js/commit/0bbd20f255b2954b5c41617fe718cf6eca36a972 is trying to solve. Can someone give an example?

**Comment by Narretz** [comment]
BTW, you don't need to maintain a complete copy of angular, you can do the same ngTouch does - decorate the ngClick directive. In practice, that means you'll have to copy most of ngTouch's code, but you can do it in a more maintainable way.

**Comment by adambuczynski** [comment]
This is also causing us serious problems with checkboxes being unclickable and any input element in a modal (which has a ng-click directive on its parent) being unclickable as well.

**Comment by JudahGabriel** [comment]
This blocks me from using ngTouch as well. I have a div that has an ng-click handler on it. Then, inside that div, I have a text input. On mobile, the text input cannot be focused. Only solution I've found is to remove ngTouch.

**Comment by walliski** [comment]
We seem to have problems with this ^ also.

**Comment by ymaz** [comment]
I have the same issue with ng-touch and input with ng-click...

**Comment by jpodpro** [comment]
+1
my simple bootstrap nav doesn't work with ngTouch - isn't this a glaring problem?

**Comment by ymaz** [comment]
Any news?

**Comment by ymaz** [comment]
Replaced ngTouch with classic FastClick and it's works like a charm for me.

**Comment by russhendy** [comment]
I'm finding this a problem too. Please let us know when this is addressed!

**Comment by dlhuffmanjr** [comment]
If you do not mind me asking:  how did you replace ngTouch?  Did you
include it and then pull in another library to decorate it, or did you not
include ngTouch and go with the Fastclick proper and then attach in a run
block?  The latter is the approach that I took with
angular-stateful-fastclick which is working fine; however, I now have a
dependency on yet another library which could make migrating to later
versions of Angular more difficult.

I apologize for asking here as realize this query is better suited for
something like SO.

**Comment by dimger89** [comment]
we have the same issue, if somebody has anwer how to fix it, please share

**Comment by adambuczynski** [comment]
The blunt "solution" we took was to simply remove ngTouch. Although an
alternative could be that you make the code changes preventing this
behaviour in the module yourself, and include that copy in your application
instead of the one from your package manager.

**Comment by dimger89** [comment]
Please update that thread if smb will find way to change that behaviour. For now I'll probably remove it.

**Comment by adambuczynski** [comment]
Thanks for that!
