### ISSUE TITLE
ngMock doesn’t support `inject` from `before` hooks.

### ISSUE THREAD

**Issue by mikol** [angular/angular.js#12154]
Both Jasmine 2.1+ and Mocha support `before` hooks that run setup code once before all `beforeEach` hooks and test cases are run. `angular-mocks.js` does not use these hooks to configure `currentSpec` (the way, for example, it uses `beforeEach` to do so). When `inject` is called from a `before` hook, it returns without invoking `workFn` and therefore does not invoke the specified function block, configure the injector, etc.

We would like to use `before` hooks with ngMock to avoid repeating common, state-agnostic, possibly expensive test fixture setup work.

**Comment by lgalfaso** [comment]
Whatever you put in `before` cannot be injected as, at that time, there is
no injector nor app running

**Comment by Narretz** [comment]
I assume @lgalfaso's answer and the closed PR settle this.
