### ISSUE TITLE
minlength validator binded to ng-model not input

### ISSUE THREAD

**Issue by piernik** [angular/angular.js#12158]
I'm using custom directive to build my form.
Like `<my-input ng-model="vm.value" required="true" minlength="6">`

This example shows that in validation required is bind to ng-model and works great. But `minlength` or `ng-minlength` is different - I suppose it works only with `input` tag.

Can You bing `ng-minlength` with `ng-model`?

Should I make my own validator?

**Comment by gkalpak** [comment]
The non `ng-` prefixed attributes will work correctly on **any** element (as long as `ngModel`is present).

The _boolean_ attributes (such as `ngDisabled` or `ngRequired`) will also work correctly on **any** element (as long as `ngModel`is present).

The (so called) _aliased_ attributes (`ngMin`, `ngMax`, `ngMinLength`, `ngMaxLength`, `ngPattern`) on the other hand will only work on `<input>` or `<textarea>` elements.

[Demo][1]

---
I am not implying that it is OK (nor do I know why); I am just describing how things work atm.

So, a quick _workaround_ (until this is resolved or decided to be left as is) is to use the non `ng-` prefixed versions.

[1]: http://codepen.io/ExpertSystem/pen/Qbqbdg

**Comment by Narretz** [comment]
Since we try to support custom controls with `ng-model`, these directives should probably not be restricted by element.
