### ISSUE TITLE
Angular code snippets appear during Page Refresh

### ISSUE THREAD

**Issue by Dariatj** [angular/angular.js#12152]
I have a page with lots of Angular code in it.  However, during a postback (i.e. my users click the refresh button), Angular code snippets appear  then go away after Angular loads.
{{Message}}
[[m.FieldName]]

Is there any way to prevent these Angular codes from appearing?

Thanks

Tom
![angularjscodesshowingwhen usersclickrefesh](https://cloud.githubusercontent.com/assets/12939784/8213784/7a251eae-14f2-11e5-92b2-65ba1e8d2ed3.jpg)

**Comment by pkozlowski-opensource** [comment]
See: http://stackoverflow.com/q/12866447/1418796

**Comment by Dariatj** [comment]
Thank you very much!
