### ISSUE TITLE
Calling element.click() causes "$apply already in progress" with ng-touch

### ISSUE THREAD

**Issue by thany** [angular/angular.js#12150]
With angular-touch installed and working fine, when calling `element.click()` in the process of an $apply (where `element` is a plain vanilla DOM element, gotten from something like `$event.target`) causes an error `$apply already in progress`.

Presumably this is because ng-touch registers a click handler on each and every element, which calls $apply again, which is no good for Angular.

I see two solutions possible:
1. Fix angular-touch so that it doesn't do an $apply (for example, using $timeout is common practise)
2. Fix Angular to allow calling $apply while another $apply is already in progress. This one makes the most sense to me. If an $apply is already happening, calling it again don't need to do anything at all.

All this is on Angular 1.4.1, angular-touch 1.4.1, no jQuery, and Firefox 38.

**Comment by havenchyk** [comment]
@thany hi, could you please create a working example on jsfiddle/plnkr/jsin?

**Comment by wesleycho** [comment]
Does removing ngTouch change this? I don't think a click should ever be triggered inside an $apply unless it is to run code that is outside of the scope of angular - the desired function should be called directly. It sounds like this problem would occur regardless of ngTouch upon inspection of the [source code](https://github.com/angular/angular.js/blob/master/src/ngTouch/directive/ngClick.js).
