### ISSUE TITLE
Bug: certain usage of $location causes infinite digest loop

### ISSUE THREAD

**Issue by dzmitry-kankalovich** [angular/angular.js#12168]
Related to https://github.com/angular/angular.js/issues/9629

Actual for angular 1.3.16

Using $location to set search param to null and then invoking `$location.replace()` causing infite digest loop.

See example here: http://plnkr.co/edit/udQ8rwDM6TJ3bsD3182l?p=preview

**Comment by robmazan** [comment]
Seems like the [location.replace()](https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L154) is not happening immediately, but after a short time period, that is enough to cause infinite digest, as it is detected is a location change on each check.

**Comment by robmazan** [comment]
Or it can be solved by saving the actual URL (that should be there) and returning that instead of reading `location.href` directly. (I'm checking if this works now)

**Comment by robmazan** [comment]
Found a working solution that is similar to the [`reloadLocation` exception](https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L167), but taking a closer look revealed that when the only search param is reset in the example above (`$location.search('some_param', null);`) then the page is getting reloaded as stripping the # from the end of the URL makes the browser (Chrome in my case) thinking that the URL changed and it needs to load the "new" page. The infinite digest is happening right before the page is getting reloaded.

What do you think about making sure that once the # got in the URL making sure that it won't get stripped later?

**Comment by robmazan** [comment]
This issue seems to be present since v1.2.27. Running with v1.2.26 is not triggering infinite digest / page reload (though I'm not certain any more what URL change is causing a page reload any more :) ).

**Comment by robmazan** [comment]
Ok, so that specific change introduced the infinite digest in this setup: https://github.com/angular/angular.js/compare/v1.2.26...v1.2.27#diff-ab8fe92910b19f1815d419aead809672R171

Removing the condition solves the infinite digest issue, but the page is still reloading... That's how far I could get for now. I hope I can find some time next week to pick up investigating.

**Comment by robmazan** [comment]
One more detail:

In v1.2.26 the code hits that line: https://github.com/angular/angular.js/compare/v1.2.26...v1.2.27#diff-ab8fe92910b19f1815d419aead809672L158

While in v1.2.27 hits that one: https://github.com/angular/angular.js/compare/v1.2.26...v1.2.27#diff-ab8fe92910b19f1815d419aead809672R175

So a `history.replaceState()` call got accidentally replaced with a `location.replace()`.

**Comment by gustavokloh** [comment]
Finally, I found the reason of my problem.
I hope that solved soon.

**Comment by gustavokloh** [comment]
Returning the `history.replaceState` not solve?

Or is there some other reason to maintain `location.replace`?

**Comment by robmazan** [comment]
I suspect it has to do something with this comment: https://github.com/angular/angular.js/blob/17d8a520caeecdafd55d26326ef869c888493176/src/ng/browser.js#L159-L162

I had no time to setup this specific case locally and experiment with it, but it's on my list. :)

**Comment by gkalpak** [comment]
I [can't reproduce][1] this any more on v1.5.10/v1.6.1. It was likely fixed at some point.
If this is still an issue, pleae open a new bug report with an updated reproduction.

[1]: http://plnkr.co/edit/MwkKcOK9IzgL8Ph7Tr7P?p=preview
