### ISSUE TITLE
Angular App Not Loading in Latest Chrome & Firefox Browsers

### ISSUE THREAD

**Issue by sanjivani2208** [angular/angular.js#12160]
I have developed app in AngularJs & Spring MVC. It was working fine up to Chrome version 42. Updating Chrome to 43 & running application makes application blank. Error appears in console as "Error : No module myapp". Issue appears only inlatest chrome & FF.
Please help.

**Comment by Narretz** [comment]
That means you haven't included your app or you have an error in your app. Without a stack trace, there's nothing we can do with this. Please reopen this if you can provide more info.

**Comment by sanjivani2208** [comment]
App has already been included, issue is only with latest versions.

**Comment by Narretz** [comment]
Please provide the complete stack trace, and try to isolate the problem.
