### ISSUE TITLE
Breaking change introduced by assertValidDirectiveName in 1.3.16

### ISSUE THREAD

**Issue by dimac** [angular/angular.js#12169]
Hi, 

I've found that my application fails to initialize after angular updated from 1.3.15 to 1.3.16 due to a new assertion in 

https://github.com/angular/angular.js/blob/v1.3.16/src/ng/compile.js#L786

which requires directive name to start from a small letter.

I'm using a directive bounded to a class name and named with the first capital letter to initialize a 3d party plugin which originally requires an html like: ```<div class="Plugin"></div>```

I've already fixed this from my side but I think minor update is not a place for such change.

Thank you.

**Comment by Narretz** [comment]
According to the commit, it's not a breaking change, rather it wasn't working before anyway. So in theory, if uppercase directive initials didn't work, the directive should never have worked anyway.

**Comment by dimac** [comment]
In practice, it did work:

https://jsfiddle.net/8j6byu9p/

**Comment by gkalpak** [comment]
Ooops, seems like class-based directives behave kind of unexpectedly :)
`directive('FooBar', ...function() { return {restrict: 'C', ...}; })` will match:

* `class="FooBar"`
* `class="Foo-Bar"`
* `class="Foo-bar"`

But not:

* `class="Foobar"`
* `class="foo<anything>"`

--
It is actually not that unexpected once yu realize that classes do not have the all-lowercase restriction of node/attribute names.

In that sense, the start-with-lowercase restriction **was** a breaking change.

**Comment by lgalfaso** [comment]
Mmm... I think that the right thing to do would be to revert this change from the 1.3.x branch, and keep it at the 1.4.x branch. @petebacondarwin WDYT?

**Comment by petebacondarwin** [comment]
Yes, we should revert. Unfortunately I didn't see this issue till after running 1.3.19 release.

**Comment by petebacondarwin** [comment]
Closed by reverting see 3a6bf0d
