### ISSUE TITLE
Docs: Guide page for decorators

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#12163]
decorators are a pretty nifty part of angular that is currently only documented as part of `$provide`. We should have a guide page that shows some common use cases: decorating a (core) service and decorating a directive. Probably also a good place to mention some limitations.

**Comment by sjbarker** [comment]
@Narretz I was surprised there was no guide for decorators when I came across this. So, I am putting together a PR and I will have it opened soon, but I need to address backwards compatibility. 

I see this is in the 1.5.x milestone but there aren't any branch labels. The document I created gives examples using a couple 1.5.x exclusive features and I then realized that it should be probably be backwards compatible. The question is: **how far back should this document support?** If it is prior to v1.4.0-rc.0 then it looks like the initial version shouldn't include mentions of the decorator exposure through the module (e57138d) either. I can prepare a pre v1.4.0-rc.0 document and then a current document noting the module.decorator (a simple, but sometimes confusing aspect that I'd like to cover in the guide). Forgive me if I am making this more difficult than need be, but I am not sure how the core team handles previous version support and patches.

Please get back to me when you can, and I will get a PR opened and ping you for a code review.

Thanks!

**Comment by awerlang** [comment]
@sjbarker The guides are versioned, e.g. https://code.angularjs.org/1.5.1/docs/guide. So BC is not an issue. To cover pre-v1.5, you'll need to backport.

**Comment by sjbarker** [comment]
@awerlang Fantastic thanks!
