### ISSUE TITLE
recipeName in invokeLaterAndSetModuleName function, Angular v1.4.1

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/angular.js#12171]
The input 'recipeName' in the returned function from invokeLaterAndSetModuleName (line: 2194) isn't being used, but the variable 'name' is? So, I'm guessing that 'name' should be 'recipeName' in the returned function. It doesn't error out since 'name' is a global. Anyway, just checking.

**Comment by Narretz** [comment]
Note: this concerns the angular-loader

**Comment by lgalfaso** [comment]
The use of `name` at
https://github.com/angular/angular.js/blob/master/src/loader.js#L341
uses the `name` parameter at
https://github.com/angular/angular.js/blob/master/src/loader.js#L81

`recipeName` is not used directly but as part of `arguments` at https://github.com/angular/angular.js/blob/master/src/loader.js#L342

**Comment by OpenSiteMobile** [comment]
Thanks. Sorry I missed that. It just seemed odd for a new function not to use the first input.
