### ISSUE TITLE
Not able to access filtered ng-repeat array in controller

### ISSUE THREAD

**Issue by xavianaxw** [angular/angular.js#12179]
So i have a ng-repeat that is set up like this in my Ionic application

    <ion-slide ng-repeat="item in ( filtered = (products | filter:{ category: filters.category}))" 
        ng-style="{ 'background-image': 'url({{site_path}}{{item.feat_image}})' }">

and in my controller, I'm watching for when the `$scope.filtered` gets updated/changed with the following code, but it's as if `$scope.filtered` does not exist in my controller.

    $scope.$watch('filtered', function(newValue, oldValue) {
		console.log(newValue);
		console.log(oldValue);
	}, true);

I've also read up that there was a major change in 1.3.0 that this doesn't work but instead Angular came up with a alternative where it will look a little bit like this.

    <ion-slide ng-repeat="item in products | filter:{ category: filters.category} as filtered" 
        ng-style="{ 'background-image': 'url({{site_path}}{{item.feat_image}})' }">

but this also doesn't work. Am I missing out something or is this a bug of some sort?

**Comment by xavianaxw** [comment]
And to add, I actually am able to display `$scope.filtered` in my application when put together with the template file with `{{ filtered }}`

**Comment by Narretz** [comment]
It's possible that your controller is in one scope, and the repeat inside a new scope. In that case, `filtered` is not accessible in your controller scope. http://plnkr.co/edit/n7zrum5ub6IzW3kkEw4w?p=preview

**Comment by xavianaxw** [comment]
Hey Narretz.

How will I be able to tell if the controller is in one scope and the repeat is inside a new scope?

**Comment by Narretz** [comment]
Have a look at the plunkr. The ng-repeat is inside a directive that creates a new scope with `scope: true`. You should look for something like that.

**Comment by Narretz** [comment]
Anyway, this is more of a support question. You should ask them on one of these channels in the future: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by NoelBaron** [comment]
@xavianaxw Did you find a solution to this? I have a similar issue where I define a filtered array in ng-repeat, but $scope.watch doesn't pick up changes as they happen.

**Comment by xavianaxw** [comment]
@NoelBaron since this was a year ago i'm not too sure what my exact codes were like. If I was not mistaken, I filtered out the array in my controller instead. That way I was able to access it from my controller. So it was something like this.

```
$scope.filtered = $filter('filter')(data);
```

Hope that helps.

Cheers
