### ISSUE TITLE
Select ng-model change but html stay stills, ipad safari mobile 7.0

### ISSUE THREAD

**Issue by kinhbang89** [angular/angular.js#12173]
Hi,

I got one problem in ipad safari 7.0:

`<select ng-model="bookingFromTime" ng-change="changeBookingTime()">
    <option value="1">1</option>
    <option value="2">2</option>
</select>`

`$scope.changeBookingTime = function(){
	if( $scope.bookingFromTime == 2) {
		$scope.bookingFromTime = 3;
	}
}`

In another web browsers in PC or even ipad safari 8.+ . WHen I select 2 it will change to 3 in html but in Ipad Safari 7.0 it stays the same value 2 in html. So how could I fix  that bug in ipad safari 7.0?

**Comment by Narretz** [comment]
@kinhbang89 you could call the $render function of the selectController explictly. (Require the selectController in a custom directive)

**Comment by Narretz** [comment]
Closing, since this is a bug in Safari 7.1 and current is Safari 8. The workaround for this is also pretty straightforward. Here's how it could look: http://plnkr.co/edit/vQdEMRItOQ7mkTRBSDlS?p=preview
