### ISSUE TITLE
$locationChangeSuccess not fires with browser back and hash is empty

### ISSUE THREAD

**Issue by fspezi** [angular/angular.js#12175]
I am using **angular 1.3.16**, in Google Chrome.  
I found a wrong behavior of $locationChangeSuccess event.

To reproduce:
* open a page like "path/#"
* click to a link to go to a page like "path/#arg=123"
* click to a link to go to a page like "path/#arg=555"
* now, click to "Back" button of browser. You will go to "path/#arg=123"; $locationChangeSuccess event is fires.
* click another time to "Back" button of browser. You will go to "path/#"; sometimes, $locationChangeSuccess event is NOT fired ($locationChangeStart is fired).
* click to "foreward" button of browser. You will go to "path/#arg=123"; $locationChangeSuccess is fired.
* click to "back" button of browser. You will go to "path/#"; $locationChangeSuccess is NOT fired.

I found in "angular.js" source code that there is a comparison between $location.absUrl() and `newUrl` local variable. `$location.absUrl()` returns "path/", and `newUrl` returns "path/#".  
Row 11486: `if ($location.absUrl() !== newUrl) return;`  

This comparison is made after "$locationChangeStart" and before "$locationChangeSuccess". The comparison do exit by function.

The $succes

**Comment by juniorjpf** [comment]
fspezi, i've tried to reproduce this bug, but no success. Can you make a example into Plunker http://plnkr.co/ or post here your files ?

**Comment by fspezi** [comment]
I develop a test page. I discovered that the issue fires if the path ends with "/" like "www.acme.com/", or "www.acme.com/path/".  
You can [download code from here](http://plnkr.co/edit/hKv1Kd?p=preview), then install to local website, so you will open 'index.html' as default page of folder.  
Then, follow step, and watch fired events below.

(you can [open the code in my local server](http://angularjs.location.dev.xilium.it/#) )

**Comment by Deklin** [comment]
This issue exists in 1.4.4 as well.

**Comment by timmolendijk** [comment]
I think this demo illustrates the same issue. It uses version 1.4.6. Maybe it's helpful.

http://output.jsbin.com/zihoza/quiet/

**Comment by Deklin** [comment]
Outstanding!

**Comment by lbysun** [comment]
Hi, this bug still exists in 1.3x. Just wondering if there is any reason why the above [PR](https://github.com/angular/angular.js/pull/13251) is not merged into 1.3x. 

Thank you!

**Comment by gkalpak** [comment]
1.3.x is an okd version and not actively maintained any more. For the latest fixes and features, you need to upgrade to the current version.
