### ISSUE TITLE
unsorted keys in ng-repeat "(key, value) in myMap"

### ISSUE THREAD

**Issue by dimylik** [angular/angular.js#12186]
Hi team,

Don't know is that a feature or bug, but in all Angular versions until 1.4.0 keys were sorted alphabetically, but not in 1.4.0/1.4.1
      div ng-repeat="(key, value) in myMap">    {{ key }}

Check a plunker:
http://plnkr.co/edit/J0ctwgN2jLOH98LCNegx?p=preview

**Comment by gkalpak** [comment]
This is a ([documented][1]) breaking change in `v1.4` (which has been requested for quite zealously: #6210).

[1]: https://docs.angularjs.org/guide/migration#ngrepeat
