### ISSUE TITLE
ensureSafeObject && ensureSafeFunction test for obj.constructor === obj

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/angular.js#12184]
Both the ensureSafeObject and ensureSafeFunction functions in v1.4.1 (and some earlier) have the same test: "if (obj.constructor === obj)". That doesn't hurt anything, but is there a good reason not to combine them? Or just use the "if (obj.constructor === obj)" in ensureSafeFunction?

**Comment by lgalfaso** [comment]
The calls to the functions `ensureSafeObject` and `ensureSafeFunction` are 30-50% of the cycles used when evaluating expressions (and this is the most expensive part of a `$digest`). This is, these functions are super hot, any cycle that we can save there have a direct impact on `$digest` performance.
