### ISSUE TITLE
ng-click does not work inside a modal dialog with bootstrap

### ISSUE THREAD

**Issue by raz3r** [angular/angular.js#12191]
Basically if I call a function from a normal button it works, however if I call the same function (with a different parameter) from a button inside a modal dialog (triggered with another button) nothing happens. Literally nothing is shown on the console, not even an error. Everything worked fine till yesterday and I did not touch my code. I am using angular JS version 1.2.28 and bootstrap version 3.3.2.

**Comment by havenchyk** [comment]
@raz3r could you please provide an example of the issue on jsbin/fiddle?

**Comment by raz3r** [comment]
I guess I realized what is causing the error... It's the Google Picker... Removing it solves the issue...

**Comment by havenchyk** [comment]
@raz3r so, it looks like the problem isn't in angular itself. Could you close issue?

**Comment by pvn6396** [comment]
Same problem with my code.
normal ng-click works
but function is not called on ng-click from a bootstrap modal.
