### ISSUE TITLE
Find a control from $sce.trustAsHtml()

### ISSUE THREAD

**Issue by manishkrai** [angular/angular.js#12193]
Hello,
I have a string that contains some html data. Here I am using $sce.trustAsHtml() to produce safe data for using with ng-bind. This string may contains few hyperlinks that I have to disable before the binding.

Currently, I am using regex.Replace to achieve the same and its working fine. But I think this is not a good solution.

var regexPatternSearchHyperlinks = "<[aA]\s+(?:[^>]?\s+)?href=\"([^\"])\"";
var disableHyperlinkPattern = "<a href=\"$1\" disabled=\"disabled\" onclick=\"return false;\"";
var messageBody = self.SelectedMessage.Body;
messageBody = messageBody.replace(new RegExp(regexPatternSearchHyperlinks, "gi"), disableHyperlinkPattern);
self.SelectedMessageBody = $sce.trustAsHtml(messageBody);

Can I use some jquery/angular selector on self.SelectedMessageBody to find all available hyperlinks 
and just disable this by doing something like -

$("a").click(function() { return false });

Regards,
Manish

**Comment by IgorMinar** [comment]
trustAsHtml doesn't produce safe html, it just marks a string that you've already sanitized as a string that is safe to be used by Angular in the html context.

So you'll need to use a sanitizer to sanitize the html. You can take a look at the provided ngSanitize module, but I don't believe it handles the particular scenario you are trying to handle and adding more features to it is out of the scope of the project.

I'd definitely recommend against using regular expressions. Instead look for an existing html sanitizer that contains the features you are looking for, have it sanitize the html and then mark that string as a trusted string.

**Comment by manishkrai** [comment]
Hi IgorMinar,

Thanks for your response for this issue. Someone had advised me to do this workaround -

"The best way to handle this, is create a small attribute directive that watches your SelectedMessageBody and then do a $element.find('a) on the next digest."

Could you please help me on this, I am new to angular so not much info about the above attribute directive etc..

Regards,
Manish
