### ISSUE TITLE
Get only variables in $scope

### ISSUE THREAD

**Issue by alexandernst** [angular/angular.js#12195]
Let's say I store a few variables in a `$scope`, like this:

```javascript
$scope.a = "Test";
$scope.b =  {x: 42, y: 5};
$scope.c = 99;
```

Is there a way I could get a list of that scope containing `a, b, c`, aka, the data that doesn't belong to Angular?

**Comment by havenchyk** [comment]
@alexandernst please, ask questions like this on the stackoverflow.com. In your case just try `Object.keys($scope)` and skip the variables with `$$` at the beginning. Maybe there is a better solution, but I really don't know :)

**Comment by petebacondarwin** [comment]
Good answer @havenchyk, thanks.
