### ISSUE TITLE
ng-class object notation fails to render if class name contains a hyphen  or underscore

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular.js#12199]
Angular: 1.4.1

Suppose a variable in the scope is set to <code>v=true</code>.  In the view,  we want to add class <code>panel-error</code> when the variable is false, and <code>panel-success</code> when the variable is true.

If we use the directive  <code>ng-class="{panel-error:!v,panel-success:v}"</code>, Angular will get confused by the hyphen character ("-"), will fail to parse the class name correctly and will not add either class to the DOM element.  If we remove the hyphen,  things work as they should.

Additional note: the underscore character  ("_") also causes this failure.

http://plnkr.co/edit/JNSTCu3siuC0QVBHU9VM?p=preview

**Comment by gkalpak** [comment]
This is more like a JS thing (rather than Angular). If your object key contains a hyphen (or other _special_ characters), you need to wrap it into quotes: `ng-class="{'panel-error': !v, 'panel-success': v}"`

**Comment by RoxKilly** [comment]
Thank you
