### ISSUE TITLE
How to commit the $viewValue to view model in unit test ?

### ISSUE THREAD

**Issue by abbish** [angular/angular.js#12204]
```
var form = scope.createGoodsForm;
      form.name.$setViewValue('test');
      form.tags.$setViewValue(['tags']);
      form.$commitViewValue();                          

      console.log(vm.form.data); #empty
```
In my test case, i have a form then i have to set view value and want to commit the view value to view model which is bind with ng-model, i'm use commitViewValue, but it's didn't work.

Someone can help on this ?

**Comment by Narretz** [comment]
Please use on of these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
