### ISSUE TITLE
"setter" function in v1.4.1 (and earlier?) has ambiguous code

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/angular.js#12206]
In the "setter" function (starting at line: 13941), the obj[key] gets set to propertyObj if propertyObj is undefined. Then, just after the "if" statement, obj gets set to propertyObj which is now just {}.

So the question is, should the "obj[key] = propertyObj;" line be removed or should the "obj = propertyObj;" line be placed in an else {}?

The code:

    if (!propertyObj) {
      propertyObj = {};
      obj[key] = propertyObj;
    }
    obj = propertyObj;     // obj set to {}, so above obj[key] = propertyObj; does nothing

With a simple test example, it works either way. And since I don't know exactly know how it is suppose to work (still learning AngularJS), I can't offer a good explanation of what it should be.

**Comment by Narretz** [comment]
Two questions: 
1. Can you please point to the actual source file of this code?
2. What's the actual problem you have encountered with this code?

**Comment by OpenSiteMobile** [comment]
Yeah, unfortunately I don't know the source code file this comes from, other than as a recently downloaded version of AngularJS v1.4.1. That said, I believe it has been the same in previous versions also.

As for the problem: It doesn't seem to matter which way one changes this particular piece of code, although as written, the one line is not needed. So I was just pointing this out. Plus, it resets the inputed "scope" object, which of coarse may be what is the intended outcome. I don't know, because I don't have a good example of what was the intended function in the first place.

However, since AngularJS allows the "dot" separated module name notation, it might be best not to change the "scope" object structure derived from that module name. Just sayin...I don't know for sure, but it sure looks odd. So here is my version:

    function setter(obj, path, setValue, fullExp) {
        var temp_sr = 'ng - setter -> ',
            element = path.split('.'),
            i = 0,
            key,
            key2,
            safeObj,
            unsafeObj = obj;

        msos.console.debug(temp_sr + 'start, path: ' + path);

        ensureSafeObject(unsafeObj, fullExp);

        for (i = 0; element.length > 1; i += 1) {
            key = ensureSafeMemberName(element.shift(), fullExp);
            key2 = ensureSafeMemberName(element[0], fullExp);
            safeObj = ensureSafeObject(unsafeObj[key], fullExp);

            if (!safeObj) { // NA, so build a safe one
                obj[key] = {};
                safeObj = obj[key];
                safeObj[key2] = {};
            }
            // Set for next interation
            unsafeObj = safeObj;
        }

        // Finish last path name
        ensureSafeObject(safeObj[key2], fullExp);
        safeObj[key2] = setValue;

        msos.console.debug(temp_sr + 'done!');
        return setValue;
    }

This version allows the "scope" input object to retain the same structure as the path (module name) that was entered with it. Again, I have no idea what this piece of code is trying to do and have a feeling it is just checking for the safeMember and safeObject stuff and nothing more. But like many areas of AngularJS, it works but you aren't really ever sure why.

So, my code works too. Which actually may be the problem you should be worrying about. Any you don't have to worry about me bothering you with these questions/concerns. I can tell it isn't much appreciated.

**Comment by ryanhart2** [comment]
Hi @OpenSiteMobile 

From what I can see, that code was there from the very first commit! It is now in parse.js and is one of the parser helper functions. It sets a value on an object using the provided path. Here is a plunker that shows that it is required http://plnkr.co/edit/enmR9KvsrJLUdaScbgFq?p=preview. I removed all of the ensureSafe stuff as this is not required for the primary purpose of the function.

In the code below, only the very first call to ```obj[key] = propertyObj``` affects the obj argument. When ```obj = propertyObj``` is executed, the local obj becomes a separate object from the obj argument.

```js
if (!propertyObj) { // if the property does not exist
  propertyObj = {}; // create a new object
  obj[key] = propertyObj; // add the new object as a property
}
obj = propertyObj; // set local obj variable to the property just added
```

**Comment by Narretz** [comment]
@OpenSiteMobile Sorry if my reply made it seem like your comments are not welcome. We simply try to categorize everything that is posted here quickly - basically we want to keep github for features requests and bugs only. For example, if this code was causing bugs in your app, this were important to us than a question of understanding the code. Thanks to @ryanhart2 for explaining this. If you think there's a better way to do this, you can open a pull request. If you have more questins, group: https://groups.google.com/forum/#!forum/angular is a good starting point.

**Comment by OpenSiteMobile** [comment]
Thanks for the response. Well, it is only used in ngForm "formDirectiveFactory" now. So it isn't even used in the parser any longer.

And it was my bad. I assumed that JavaScript treats an input object as a "reference" to the origin (as Perl does), when it just make a copy of the base object with references to the originals properties. It just looked odd to set a key to an object, then set it to {} on the next line. Learn something new everyday.
