### ISSUE TITLE
Wrong currency format nl-be

### ISSUE THREAD

**Issue by tdhulster** [angular/angular.js#12210]
When filtering a value using the currency filter with angular-locale_nl-be (Dutch language in Belgium),
the position of the euro symbol is not correct according to legal standards. 

Now, the symbol is placed after the value. Instead it should be in front of the value. 

https://en.wikipedia.org/wiki/Linguistic_issues_concerning_the_euro#cite_note-dutch_valuta-5

**Comment by pkozlowski-opensource** [comment]
Please check [Localization Issue](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-found-an-issue) section.

**Comment by frfancha** [comment]
@tdhulster Your reference says: In Nederland is het gebruikelijk de muntcode voor het bedrag te zetten, in Vlaanderen erachter.
That means that NL-BE putting the symbol after the value is correct behavior.

**Comment by tdhulster** [comment]
@frfancha When using the ISO 4217 standard (EUR), then yes. But when using the € symbol it should be in front of the value.

**Comment by daviddk** [comment]
+1 on '€'-symbol being before the number and EUR being after.

Expected:
€ 1.200,00
1.200,00 EUR

nl-be returns:
1.200,00 €

**Comment by lgalfaso** [comment]
Please check https://github.com/angular/angular.js/issues/12210#issuecomment-116304351. If the generated locale files have any issues, then these should be reported there. Once these are fixed there, we can regenerate the locale files with updated data.
