### ISSUE TITLE
ng-repeat doesn't work if model is an array with same string values

### ISSUE THREAD

**Issue by k4rim-github** [angular/angular.js#12216]
Hello!
I have this in my controller :
$scope.skills = ['java', 'java', 'java'];
and this in the view : 
[span ng-repeat="s in skills"] {{s}} 
[/span]
it's doesn't work (shows nothing) because the values in the array are the same.
but when i do that:
$scope.skills= ['java', 'java2', 'java3'];
it works perfectly.
i'm using Angular 1.2.26
Is that a bug ?
the '[' and ']' represent  the '<' and '>'

**Comment by Narretz** [comment]
Duplicates are not allowed in an ng-repeat. If you need duplicates, you can provide a tracking function.
You can read the docs about this for more info: https://code.angularjs.org/1.4.1/docs/api/ng/directive/ngRepeat (it's for 1.4.1, but the part about duplicates and tracking applies to 1.2.x, too)

**Comment by k4rim-github** [comment]
Thank you!
