### ISSUE TITLE
css files ared loaded twice

### ISSUE THREAD

**Issue by westor21** [angular/angular.js#12229]
Dear angular.js team,
after upgrading to angular 1.4.1 we noticed in google chrome network console double loading of css files. The first origin is the style tag in our html file, and the second origin comes from angular.js line 3171.

The line
    element.innerHTML = value;
in the function html

seems to cause that.

Beste regards.
Westor21

**Comment by havenchyk** [comment]
@westor21 please, provide an example on jsbin or plnkr.co It would be much easy to understand the problem with working example.

**Comment by westor21** [comment]
Yes, I can try to make one, but the app is already a complex system using ui-router. (Still waiting for the new angular router to become productive ;-) )
It currently looks to me, we could have a routing problem. Initially the request goes to "/". Later in the inititialisation process, I see a call to index.html. That could cause the double loading.
I will investigate into this, and I suggest to close this issue in the meantime.

**Comment by gkalpak** [comment]
It's a shot in the dark, but I would look for a route or directive with an empty `templateUrl`.
