### ISSUE TITLE
Chrome update breaks Angular App

### ISSUE THREAD

**Issue by skidvd** [angular/angular.js#12223]
Hello,

Please bear with me for a bit, as what I am about to describe seems surprising at best; perhaps even hard to believe.  However, I have spent nearly a week trying to track things down in a completely stable app that has not changed to arrive at this point.... 

I have a stable Angular 1.3.3 base application. It have been stable and working without issue for quite some time up until a week or so ago.  Around that time, the app started to exhibit 'odd' problematic behaviors in Chrome.  The behaviors seen are hard to imagine being possible, but following extensive debugging, we have determined that some UI elements with ng-click behaviors are being triggered automatically upon application load in Chrome.  This is NOT the desired behavior (we only want these actions to be triggered in response to an actual user click on the element) are leading to further problems downstream within the app.  Again, the application is stable and has not changed.  Furthermore, the application continues to work without any issues whatsoever in Firefox.  My Chrome is up-to-date at Version 43.0.2357.130 m and it would appear the 6/23/15 update to Chrome is at the center of this as all worked fine before it.

Anyone else seeing similar issues?  Is this a known issue that is being worked?  Any ideas on how to resolve and/or workaround in the meantime?

TIA!

**Comment by caitp** [comment]
Could you please provide a reproduction of your issue

**Comment by skidvd** [comment]
Hello Caitp,

Thanks for your help!  I'm not sure exactly what you are looking for?  I can't really provide a screen shot of a ng-click being automatically triggered upon app bootstrap?  The app is stable and has not changed in quite some time.

**Comment by caitp** [comment]
I'm asking you to create a minimal, runnable example of this issue

**Comment by bl4de** [comment]
@skidvd 
Is upgrade to 1.4.* not acceptable for your app? I've got one based on 1.4.1 and on Chrome 43.0.2357.130 works fine, didn't experience such behaviors as you.

**Comment by caitp** [comment]
i'm betting it's not actually related to the ng-click or angular version code, @skidvd. Most likely there's some other operation occurring which now triggers a click when previously it did not.

**Comment by skidvd** [comment]
@bl4de, this is a stable app in production.  We would not like to expend cost and effort required to upgrade to 1.4 for this app unnecessarily.

@caitp, I'll attempt to work on a plunker.  Any hunches on what other operations may trigger a click when it previously did not?

**Comment by gkalpak** [comment]
It might be obvious (but checking anyways):
Have you been able to reproduce the issue with all Chrome Extensions disabled ?

**Comment by gkalpak** [comment]
BTW, especially [that issue][1] comes to mind (but it could be some other extension or issue as well).

[1]: https://github.com/angular/angularjs-batarang/issues/227

**Comment by pkozlowski-opensource** [comment]
As for @gkalpak, for me it sounds like a Chrome extension interfering here.

**Comment by skidvd** [comment]
@gkalpak, thank you!  You nailed it!

Batarang was indeed the culprit.  Interesting that in our case this only surfaced with Chrome 43?
