### ISSUE TITLE
$animate.enter ng-enter is not triggered

### ISSUE THREAD

**Issue by nestorneto** [angular/angular.js#12224]
http://plnkr.co/edit/nBJ33Ymv6Xv9jZUNfMyd

in this case ng-enter should not be triggered right away?

**Comment by havenchyk** [comment]
@matsko could you please take a look?

**Comment by nestorneto** [comment]
I just realised that element.on event needs scope.$apply();

http://plnkr.co/edit/nBJ33Ymv6Xv9jZUNfMyd

**Comment by havenchyk** [comment]
@nestorneto yep, you're right :smile: So can this issue be closed?

**Comment by nestorneto** [comment]
sure :smile:

**Comment by matsko** [comment]
Sorry for not making that clear in the docs. All animation methods require a call to `$apply` to be called so that a digest is running when they operate. This will be more clear when #11801 is ready (that will be done once the other major animation issues are complete).
