### ISSUE TITLE
AngularJS Commit Message Conventions examples do not follow all conventions

### ISSUE THREAD

**Issue by davidmason** [angular/angular.js#12225]
The linked google doc with detail for the commit message conventions ([AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#)) has examples at the end, but several of the examples do not follow the convention for subject and body:

> use imperative, present tense: “change” not “changed” nor “changes”

A few suggested fixes:
- change "Added new event to $browser" to "Add new event to $browser"
- change "Couple of typos fixed" to "Fix a couple of typos"
- change "Changed the isolate scope binding options to:" to "Change the isolate scope binding options to:"

There may be a few others I did not pick up on

I can put suggested changes on the doc directly if I can get suggest permissions on it.

**Comment by Narretz** [comment]
In my personal experience, the body has a lot more variety in phrasing and it's usually not a important as the subject. Since the docs is not in our hands, I will close this and suggest someone who can to take a look at it.
