### ISSUE TITLE
how do I use 'require' in angularJS? for e.g. in controllers?

### ISSUE THREAD

**Issue by fkkcloud** [angular/angular.js#12228]
what if I want to use require to import my other script and use it in angularJS 's controller?

it says that require is not available in controller.

**Comment by havenchyk** [comment]
Angular just supports syntax of CommonJS and can be retrieved from npm or bower with `require('angular')`, but you have to use other tools for building like browserify or webpack etc. Angular doesn't provide `require` word, just made the way to use angular package from npm without shims. 

There are some details in changelog http://angularjs.blogspot.com/2015/02/new-angularjs-releases-140-beta5-and.html

@fkkcloud for the future please, ask questions on the stackoverflow.com, github issues are for bugs mostly. thanks
