### ISSUE TITLE
10 $digest() iterations reached. Aborting! in 1.2.28 but not in 1.3.16 

### ISSUE THREAD

**Issue by Genffy** [angular/angular.js#12237]
Example like this: http://jsfiddle.net/sxe31ft7/1/ 
the same code,but the error happen in lower version, why ?

when i debugger the source fond something wrong in 
1.2.28 version   $watchCollection -> $watchCollectionWatch line 12471 

TKS

**Comment by lgalfaso** [comment]
The construct that puts a literal inside an `ngRepeat` is not supported in the 1.2.x branch. You have to use a reference.

Given that the 1.2.x branch is only open for security fixes and this is working on the active branches, then I am closing this
