### ISSUE TITLE
Hash not added to URL on home page

### ISSUE THREAD

**Issue by iamdriz** [angular/angular.js#12232]
Usually if you load an angular app and have the html5 mode disabled, it automatically adds the hash to the url so that it can find the home page and prevents duplicate homepage urls.

However my application isn't doing that... and I have to manually visit /#/ to load the home page.

Any ideas what would cause this?

**Comment by iamdade** [comment]
If I understood you correctly It's because of routing. This will help.

```javascript
$urlRouterProvider.when('', '/');
```

Basically that let's the router know that the page with or without ending "/" should work the same way.

**Comment by wesleycho** [comment]
@iamdade's example works if you are using [UI Router](https://github.com/angular-ui/ui-router). If using ngRoute, then doing
```
$routeProvider.otherwise('/')
```
should work.

**Comment by iamdriz** [comment]
I'm using UI Router and I have:

~~~
App.config(function($stateProvider, $urlRouterProvider, $locationProvider) {

	$urlRouterProvider.otherwise('/');
	[...]
~~~

But it doesn't redirect to `http://domain.com/#/` and only stays on `http://domain.com/`

**Comment by iamdriz** [comment]
Fixed! I had this silly route in place:
~~~
.state('404', {
    url: "*path", // will catch all URLs
~~~
