### ISSUE TITLE
"Unexpected end of expression" in ngRepeat with no reason.

### ISSUE THREAD

**Issue by limonte** [angular/angular.js#12239]
Can't figure out why I'm getting "Unexpected end of expression" in simple expression in ngRepeat.

Here's actual ngRepeat:

```html
<!-- ngRepeat: emailList in (currentList = (emailLists | orderBy:sortingParams)) -->
```
![screenshot](https://i.imgur.com/P9NUQBe.png)

As far as I know such expression is not documented, but I followed [this SO answer](http://stackoverflow.com/a/11722324/1331425) with 120 upvotes to get filtered list in scope.

PS. I'm using latest AngularJS 1.4.1

**Comment by lgalfaso** [comment]
Can you please create a plunker that shows this error?

**Comment by limonte** [comment]
@lgalfaso trying to create the plunkr I figured out the mistake which is not in AngularJS :) Thank you anyway :)
