### ISSUE TITLE
Bug or what?

### ISSUE THREAD

**Issue by vko-online** [angular/angular.js#12230]
```javascript
<textarea type="checkbox" name="note" data-ng-model="preparation.note" id="note" class="form-control" placeholder="note"></textarea>
```
Ng-model binds `"true/false"` to $scope, although element is textarea

**Comment by pkozlowski-opensource** [comment]
@vko-online please provide, complete (but reduced), live reproduce scenario: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue

We can't act on the issue like this, there is simply not enough context...

**Comment by vko-online** [comment]
I was wrong, http://plnkr.co/edit/ECNCexHLrFkKHcdNm7pc?p=preview
Having `type="checkbox"` on `textarea` doesn't even bind to model, by design i guess

**Comment by pkozlowski-opensource** [comment]
Right, `type` doesn't seem to be a permitted attribute on `textarea`: http://www.w3.org/TR/html-markup/textarea.html

**Comment by vko-online** [comment]
offtop but im glad that you @pkozlowski-opensource still with us.
