### ISSUE TITLE
Nested headers are not serialized correctly

### ISSUE THREAD

**Issue by bcherny** [angular/angular.js#12233]
```js
// ok
$http.get('/good', {
  headers: {
    foo: 'bar'
  }
})
// request headers: {
//   "foo": "bar"
//   ...
// }

// ok
$http.get('/good-ish', {
  headers: {
    foo: JSON.stringify({
      bar: 'baz'
    })
  }
})
// request headers: {
//   "foo": "{"bar":"baz"}"
//   ...
// }

// not ok
$http.get('/bad', {
  headers: {
    foo: {
      bar: 'baz'
    }
  }
})
// request headers: {
//   "foo": "[object Object]"
//   ...
// }
```

demo: http://codepen.io/anon/pen/BNJvZV

knowing how to serialize headers shouldn't be the consumer's concern i think.

**Comment by wesleycho** [comment]
This is what the documentation says:

- **headers** – `{Object}` – Map of strings or functions which return strings representing HTTP headers to send to the server. If the return value of a function is null, the header will not be sent. Functions accept a config object as an argument.

So this would be a feature request, and likely an easy one to implement.

**Comment by lgalfaso** [comment]
Agree with @wesleycho this is a feature request. Not sure if this would be so simple, mostly as once we start accepting objects, then there is a need to define what to do with some of the *special* objects like `Date`. This aside, this request sounds reasonable

**Comment by gkalpak** [comment]
FWIW, I don't think JSONified objects are a common value for headers (but there might be a common usecase that I've missed).

**Comment by bcherny** [comment]
@lgalfaso i think this is already well defined. what if we just JSON.stringify the content, like what angular already does for request bodies?

```js
JSON.stringify(1)                   // 1
JSON.stringify({ foo: 'bar' })      // "{"foo":"bar"}"
JSON.stringify(new Date())          // "2015-06-30T18:08:54.973Z"
```

**Comment by lgalfaso** [comment]
Would it be possible to know what is the use case? It is not entirely clear what it is to gain with allowing JSON as headers, it is just very very uncommon and what you are asking for can be done with a global interceptor anyhow (BTW, just like allowing objects makes sense to some, allowing `undefined` and `null` and allow for these to be JSON serialized would make sense to somebody else).

Without a clear understanding of what the use case is, then I do not think that this should be part of the core.

**Comment by bcherny** [comment]
My use case is attaching some custom metadata to every request (think `userId`, `currentPage`, etc.). I do that with a global request interceptor as you said, but I don't believe that serialization logic should be defined in that interceptor. One option would be to move header serialization into a separate interceptor, but it seems to me that since angular handles serialization/deserialization for bodies, query params, and cookies, already, it should handle it for headers as well.

**Comment by pkozlowski-opensource** [comment]
I think we are going to pass on this one. Having this custom serialization logic in an interceptor is perfectly fine, so people can customize the serialization logic if desired.
