### ISSUE TITLE
Alternative to setTimeOut or $timeout

### ISSUE THREAD

**Issue by felippetadeu** [angular/angular.js#12246]
Why the angular set the $render after of hook elements/functions ?

In my case I need to set a default value for an input but my code only work if I write the timeout function.

More details see the stackoverflow question please:

http://stackoverflow.com/questions/31147073/alternative-to-settimeout-or-timeout?noredirect=1#comment50304863_31147073

**Comment by lgalfaso** [comment]
This is the intended behavior. `postLink` is not executed inside the digest loop.
