### ISSUE TITLE
Infdig in Custom groupBy

### ISSUE THREAD

**Issue by deadmann** [angular/angular.js#12242]
Dear folks, 

i recently needed some kinda customized repeater, which group data by their key, but not simply group them all together, so i read several references and things,... and at last i come up to copy 
groupBy from this article which he seem to complete it at best, ... 
http://sobrepere.com/blog/2014/10/14/creating-groupby-filter-angularjs/
And then i customized so it become like this:

the things my group by do... is: 
 - Group Data Together Until It Reach Differences.

but the matter is that though it work, it still generate infdig, i know it's because the digest done call other one, but what i don't know is how to solve it in very easy and understandable manner, as i'm new to JavaScript...

                //angular.module("sbrpr.filters", [])
                
                app.filter('gapedGroupBy', function () {
                    var results = {};
                    return function (data, key) { //Data => My Objects Array - Key => Name Of Filtered Property
                        if (!(data && key)) return;
                        var result;
                        if (!this.$id) {
                            result = {};
                        } else {
                            var scopeId = this.$id;
                            if (!results[scopeId]) {
                                results[scopeId] = {};
                                this.$on("$destroy", function () {
                                    delete results[scopeId];
                                });
                            }
                            result = results[scopeId];
                        }

                        for (var groupKey in result)
                            result[groupKey].splice(0, result[groupKey].length);
                
                        var grpKey = -1; //GroupKey
                        var lastUserId;
                        for (var i = 0; i < data.length; i++) {
                            if (!result[grpKey] || lastUserId && lastUserId != data[i][key]) // Ex.: result[data[0]["UserId"]]{ => return UserId
                                result[++ grpKey] = [];
                
                            result[grpKey].push(data[i]);
                            lastUserId = data[i][key];
                        }
                
                        var keys = Object.keys(result);
                        for (var k = 0; k < keys.length; k++) {
                            if (result[keys[k]].length === 0)
                                delete result[keys[k]];
                        }
                        return result;
                };
        });

**Comment by josepot** [comment]
What version of Angular are you using?

**Comment by Narretz** [comment]
Please ask support questions on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by deadmann** [comment]
@josepot so you mean i should inject $scope, and no longer work with scope? so then what will be a scope id? i just copy that...

@Narretz Sry man, but i'm too much force that didn't think of that
