### ISSUE TITLE
ng-form  cannot show message & remove item from arry

### ISSUE THREAD

**Issue by kimx** [angular/angular.js#12249]
Hello 
when I upgrade version from 1.3.16 to 1.4.1 ,I occur some errors.
* ng-message cannot show， But if I downgrade to angular-messages .1.3.16 it can be work.
* When some input has validation in ng-form ,It cannot be remove from an array.I found the problem cause by when inject module of  ng-animate e.g
` angular.module("App", ["ngMessages",  "ngAnimate"])`
see [Plunker](http://plnkr.co/edit/mUi24IA2yyww0TyoDeRD)

please help me ,thanks a lot

**Comment by Narretz** [comment]
Can you please provide a plnkr or similar for these issues, especially the first? The second one sounds like a known ngAnimate bug.

**Comment by kimx** [comment]
For first Issue ng-message cannot show ,[this plunker can show] (http://plnkr.co/edit/lML0DrYXj6XkT9fASgsn) ,for this sample just clear any value of input,that will show validation message,but if I change 1.3.16 to 1.4.1 ,the message cannot show.

**Comment by gkalpak** [comment]
Regarding the 1st issue, there have been some changes in `ngMessages` on 1.4.x, so the `ng-messages` expression is not interpolated.
To make it work on both versions, change `rowForm['item.name{{$index}}'].$error` to `rowForm['item.name'+$index].$error` ([updated plnkr][1]).

[1]: http://plnkr.co/edit/gmIthPYnztmO7l6jRPxb?p=preview

**Comment by kimx** [comment]
@gkalpak thanks 1st issue can work, @Narretz  about second issue will be fix in next version? thanks a lot .

**Comment by sreeramu** [comment]
#12271 should fix this issue.

**Comment by Narretz** [comment]
@kimx Sorry, we don't have a fix for that yet. It's been tracked in issue https://github.com/angular/angular.js/issues/12161, so I'll close this one.
