### ISSUE TITLE
Ng-repeat with dynamic ng-model on input not working 

### ISSUE THREAD

**Issue by eduardoroyer** [angular/angular.js#12256]
Hello There

In controller I've a list like this:
```js
scope.data = [  { user: { address: { city: 'Boston'} } } ];
```
And a property, where I've the name to access the object:
```js
scope.propertyName = 'address.city';
```

In HTML, I've a ng-repeat where I put a dynamic input to edit that value.

```html
<div ng-repeat="item in data">
    <input ng-model="item[propertyName]">
</div>
```

My question is: How can I bind the value of the item with the ng-model?

**Comment by godofrayer** [comment]
i use scope.watch every item in data

**Comment by eduardoroyer** [comment]
@godofrayer Can it works, but I'm making a datatable, so, if I have five columns and 100 rows, I've 500 watchers

**Comment by Narretz** [comment]
Please use one of these channels to ask support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
