### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by Manmohan1118** [angular/angular.js#12257]
Hello ,

I am working on "Token Based Authentication using Asp.Net Web API 2,OWIN ,and Identity" with AngularJS from tutorial Link :- "http://bitoftech.net/2014/06/01/token-based-authentication-asp-net-web-api-2-owin-asp-net-identity/" but i getting trouble in Registration form the following ERROR 1.

When I use "CODE 1" code in webconfig.cs then registration working well but login display error "ERROR 2" .
-----------------------------------------CODE 1---------------------------------------------------
httpProtocol>
      customHeaders>
        add name="Access-Control-Allow-Origin" value="*" />
        add name="Access-Control-Allow-Headers" value="Content-Type" />
        add name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS" />
      /customHeaders>
/httpProtocol>
-----------------------------------------------------------------------------------------------------------
Please help me 
Thanks
 

-------------------------------------------------------ERROR 1----------------------------------------------------------
POST http://localhost:3030/register
	
200 OK
		1.07s	
angular.js (line 10506)
Error: response.data is null
register/$scope.SubmitReg/<@http://localhost:7480/app/register/register.js:55:28
processQueue@http://localhost:7480/scripts/angular.js:14551:28
scheduleProcessQueue/<@http://localhost:7480/scripts/angular.js:14567:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:7480/scripts/angular.js:15830:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:7480/scripts/angular.js:15641:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:7480/scripts/angular.js:15935:13
done@http://localhost:7480/scripts/angular.js:10356:36
completeRequest@http://localhost:7480/scripts/angular.js:10528:7
createHttpBackend/</requestError@http://localhost:7480/scripts/angular.js:10479:9
[undefined]
	

return logFn.apply(console, args);

angular.js (line 12314)
[app] 
["[HT Error] response.data is null", Object { exception=TypeError: response.data is null,  cause=undefined}]
	

return logFn.apply(console, args);

angular.js (line 12314)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3030/register. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
---------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------ERROR 2 ---------------------------------------------
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
	

0

POST http://localhost:3030/token
	
200 OK
		4.31s	
angular.js (line 10506)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3030/token. (Reason: CORS header 'Access-Control-Allow-Origin' does not match '*, *').

Error: err is null
login/$scope.SubmitL/<@http://localhost:7480/app/login/login.js:42:13
processQueue@http://localhost:7480/scripts/angular.js:14551:28
scheduleProcessQueue/<@http://localhost:7480/scripts/angular.js:14567:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:7480/scripts/angular.js:15830:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:7480/scripts/angular.js:15641:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:7480/scripts/angular.js:15935:13
done@http://localhost:7480/scripts/angular.js:10356:36
completeRequest@http://localhost:7480/scripts/angular.js:10528:7
createHttpBackend/</requestError@http://localhost:7480/scripts/angular.js:10479:9

undefined
angular.js (line 12314)
[app] [HT Error] err is null Object { exception=TypeError: err is null,  cause=undefined}
---------------------------------------------------------------------------------------------------------------------

**Comment by Narretz** [comment]
Please use one of these channels for asking support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
That said, you should probably read up on CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
