### ISSUE TITLE
pass by value not working in select

### ISSUE THREAD

**Issue by brendonco** [angular/angular.js#12265]
I'm trying to set the value in select element. Assuming the building values is from http get e.g. http://someurl/?id=1234

when the selectBuilding function is called, the selectedBuilding that is attached to ng-model is set but doesnt trigger the change unless I used $scope.$apply();  is there other way to do this?

```
html:
<select id="buildings" class="buildings-select" ng-change="selectBuilding();" ng-options="building as building.name for building in buildings track by building.id" ng-model="selectedBuilding">

controller:
$scope.buildings = [{id: "1234", name: "Tower 1"}, {id: "12345", name: "Tower 2"}];

$scope.selectBuilding = function(){
  $scope.selectedBuilding = $scope.buildings[0]; // assuming the id 1234 is retrieved from the url.
}
```

**Comment by pkozlowski-opensource** [comment]
http://plnkr.co/ please: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by pkozlowski-opensource** [comment]
Closing due to the lack of response / reproduce scenario.

**Comment by brendonco** [comment]
Sorry for the late response. you can close this. I manage to tweak it by using a callback from the directive.
