### ISSUE TITLE
Custom Validator Directive causes duplicate form.$error

### ISSUE THREAD

**Issue by thoughtassassin** [angular/angular.js#12270]
When I add a custom directive to prevent two textboxes from having the same value, it causes the custom validator errors to be duplicated when I iterate over form.$error.

Here is the code that I am using for the directive:

```
(function(){
    'use strict';

    angular
        .module('psp.directives')
        .directive('pspMatchField', pspMatchField);

        /* @ngInject */
        function pspMatchField() {
            var directive = {
                restrict: 'A',
                require: 'ngModel',
                link: link,
                scope: {
                    pspMatchField: '='
                }
            };
            return directive;

            function link(scope, elem, attrs, ngModel) {

                ngModel.$validators.matchField = function (modelValue) {
                    return modelValue == scope.pspMatchField;
                }

                scope.$watch("pspMatchField", function() {
                    ngModel.$validate();
                });

            }
        }
})();
```
Here is the code for the div that I try to iterate over the errors with:
``` 
<div data-ng-repeat="(key, values) in form.$error">
```
The html output when the validation is triggered shows this in firebug:

```
<div data-ng-repeat="(key, values) in form.$error">
<div data-ng-repeat="(key, values) in form.$error">
```

**Comment by Narretz** [comment]
There's not enough information to see if this is a bug or a usage error. Pease post a minimal demo in a plnkr or similar.

**Comment by thoughtassassin** [comment]
Does this help? http://plnkr.co/edit/DV6mZELTjyE1LNYJMqps?p=preview

**Comment by thoughtassassin** [comment]
Fill in the form. I don't list anything for contacts but you will notice as soon as the form is submitted and the directive starts checking if the social security field and the confirm social security field matches it shows the validation error twice in the list of validation errors.

**Comment by ryanhart2** [comment]
The documentation on $parsers says that the parse error is stored in ngModel.$error.parse. In your directive you are also adding the error to ngModel.$error.matchField. So when the user enters different information into the two fields, ngModel will have two errors: one for parse and one for matchfield. Your code iterates over both and shows the "Does Not Match" message each time.

**Comment by thoughtassassin** [comment]
@ryanhart2 Here is the plunker only displaying the ngModel.$error.matchField and not the ngModel.$error.parse: http://plnkr.co/edit/0JsvvFbd5ziVpGGpvjSM?p=info
