### ISSUE TITLE
ng-messages-include throws controller required error

### ISSUE THREAD

**Issue by mitcht** [angular/angular.js#12279]
Whenever I attempt to use the following code

```html
<div class="error-messages"  ng-messages="currentform.firstName.$error" >
   <div ng-messages-include="/error/messages.html"></div>
</div>
```

and use the file /error/messages/html with contents contained here
http://hastebin.com/emurovaret.m

i get the following error:
Controller 'ngMessages', required by directive 'ngMessage', can't be found!

App.js has the 'ngMessages' in it.  It was working.

FYI i have been using ngMessages for awhile now and have just recently run into this problem after updating all of my libraries and switching to angular 1.4.1 from 1.3.16.
I'm very sorry about the markdown. I am having trouble figuring out how to put html on here.

**Comment by petebacondarwin** [comment]
@mitcht could you create a reproduction of this in Plunker?

**Comment by petebacondarwin** [comment]
Here is a plunker that appears to be working: http://plnkr.co/edit/WPhRkoplfwcWnc4WLJhF?p=preview

**Comment by mitcht** [comment]
I tried to create a plunker but i was unable to replicate the bug accurately.  I was able to trace it down into a bit of subcode that was using $anchorScroll but I couldn't track past that.  I switched the code out to use $window.scrollTo() and the error went away.

File it under unable to reproduce.

**Comment by petebacondarwin** [comment]
Thanks @mitcht. It seems strange that $anchorScroll was causing this...

**Comment by migarc1** [comment]
<div ng-messages="model.$error" ng-messages-include="remote.html">
  <div ng-message="required">Your message is required</div>
</div>


<div ng-messages="model.$error">
  <div ng-message="required">Your message is required</div>
  <div ng-messages-include="remote.html"></div>
</div>
