### ISSUE TITLE
Safari strange error angular 1.4.1

### ISSUE THREAD

**Issue by mato75** [angular/angular.js#12275]
This happens only in safari, and I don't understand why.
```
[Error] Error: No default value
toString@[native code]
join@[native code]
g@http://127.0.0.1:8383/v2/data_explorer/?data=~(bigtable~(sc~null)~time~(tmp~'q3-2015~ctmp~'q2-2015~tmpt~null~ctmpt~null)~scale~'week~clients~(~)~metrics~(~)~dimensions~(~(~)~(~))~columns~(~)~rows~(~)):81:130
http://127.0.0.1:8383/dashboard/widgets/dimensionspopover/dimensionspopover.js:287:18
$watchCollectionAction@http://127.0.0.1:8383/js/components/angular/angular.js:15534:21
$digest@http://127.0.0.1:8383/js/components/angular/angular.js:15667:31
$apply@http://127.0.0.1:8383/js/components/angular/angular.js:15935:31
http://127.0.0.1:8383/js/components/angular/angular.js:17691:42
completeOutstandingRequest@http://127.0.0.1:8383/js/components/angular/angular.js:5387:15
http://127.0.0.1:8383/js/components/angular/angular.js:5659:33 undefined
	g (data_explorer, line 81)
	(anonymous function) (angular.js, line 12314)
	(anonymous function) (angular.js, line 9101)
	(anonymous function) (exceptionhandler.js, line 34)
	$digest (angular.js, line 15685)
	$apply (angular.js, line 15935)
	(anonymous function) (angular.js, line 17691)
	completeOutstandingRequest (angular.js, line 5387)
	(anonymous function) (angular.js, line 5659)
```

**Comment by Narretz** [comment]
I find it hard to believe that this happens with every watchCollection in Safari. What's the exact scenario where this happens? Can you try to isolate the problem and put it in a plnkr or similar?

**Comment by mato75** [comment]
It is so strange, it works in all browsers expect for safari. I am creating a directive, and in directive I create a new instanceOf DraggableList2.

         directive = {
			templateUrl: 'widgets/draggablelist2/draggablelist2.tpl.html',
            compile: compile,
			controllerAs: 'ctrl',
			bindToController: false,
            scope: {
				attrs: '=?'
			},
            restrict: 'AC',
			replace: true
        };

        scope.attrs = new DraggableList2();

And when I log console.log(typeof scope.attrs) it says object, but when I want to log console.log(scope.attrs) it throws this error:

Error: No default value
join@[native code]
g@http://127.0.0.1:8383/v2/data_explorer/?data=~(bigtable~(sc~null)~time~(tmp~'q2-2015~ctmp~'q1-2015~tmpt~null~ctmpt~null)~scale~'week~clients~(~(obj~'0~disabled~false)~(obj~'101~disabled~false)~(obj~'3~disabled~false)~(obj~'71~disabled~false)~(obj~'77~disabled~false))~metrics~(~(obj~'engagementratio~disabled~false)~(obj~'impressions~disabled~false)~(obj~'rev-clicks~disabled~false)~(obj~'visratioi~disabled~false))~dimensions~(~(~(obj~(client_name!in~(~'Italy))~separator~'!all~disabled~false))~(~(obj~(rev-impressions!gt~100)~separator~'!any~disabled~false)~(obj~(rev-clicks!gt~100)~separator~'!all~disabled~false)))~columns~(~)~rows~(~)):81:130
initWidget@http://127.0.0.1:8383/widgets/draggablelist2/draggablelist2.js:116:19
fn
$eval@http://127.0.0.1:8383/js/components/angular/angular.js:15830:28
pre@http://127.0.0.1:8383/js/components/angular/angular.js:24141:20
http://127.0.0.1:8383/js/components/angular/angular.js:8636:49
invokeLinkFn@http://127.0.0.1:8383/js/components/angular/angular.js:8642:15
nodeLinkFn@http://127.0.0.1:8383/js/components/angular/angular.js:8121:23
http://127.0.0.1:8383/js/components/angular/angular.js:8372:36
processQueue@http://127.0.0.1:8383/js/components/angular/angular.js:14551:30
http://127.0.0.1:8383/js/components/angular/angular.js:14567:39
$eval@http://127.0.0.1:8383/js/components/angular/angular.js:15830:28
$digest@http://127.0.0.1:8383/js/components/angular/angular.js:15641:36
$apply@http://127.0.0.1:8383/js/components/angular/angular.js:15935:31
done@http://127.0.0.1:8383/js/components/angular/angular.js:10356:53
completeRequest@http://127.0.0.1:8383/js/components/angular/angular.js:10528:15
requestLoaded@http://127.0.0.1:8383/js/components/angular/angular.js:10469:24 – "<div ng-init=\"initWidget()\" class=\"row ng-isolate-scope\" nt-draggable-list2=\"\" x-attrs=\"widgets.draggableListRows\">"

Error: No default value – {exception: TypeError: No default value, cause: "<div ng-init=\"initWidget()\" class=\"row ng-isolate-…ble-list2=\"\" x-attrs=\"widgets.draggableListRows\">"}

**Comment by mato75** [comment]
It has to do something with the directives, I don't understand what is the reason for this issue.

**Comment by Narretz** [comment]
Like I said, please post a demo. This might be something in your code rather in angular core.

**Comment by mato75** [comment]
Safari is a stupid ass browser. No wonder it it becoming the new IE.

http://lists.apple.com/archives/quartzcomposer-dev/2011/Feb/msg00161.html

**Comment by shawn-simon** [comment]
Seeing this as well... will try to dig in

**Comment by S-YOU** [comment]
Just fyi, In Firefox. attribute name "watch" can cause $digest throwing error, because is Object.prototype.watch is always exists and watching it cause error on angular $digest loop.
Safari might have similar case but may be not "watch".
