### ISSUE TITLE
$compile a string with <img> causes browser to load images.

### ISSUE THREAD

**Issue by joshribakoff** [angular/angular.js#12272]
```html
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.min.js"></script>
<script>
    angular.module('myApp', []).run(function($compile, $rootScope) {
        var template = '<img src="https://www.google.com/logos/doodles/2015/fourth-of-july-2015-5118459331477504.2-hp.jpg" />';
        $compile(template)($rootScope);
    });
</script>
<div ng-app="myApp"></div>
```

I would expect the browser to not download the image, because I have not added anything to the DOM at this point. When I run this example in Chrome it does download the image.

If this is expected behavior, I cannot find anything in the documentation about it. This happens if using `ng-src` or using `src`, I see no difference either way.

I supposed that the current behavior is correct, but my issue is that the documentation doesn't explain why. Does calling $compile() modify the DOM? Does it explicitly call `new Image` when compiling a string containing `<img>`? Why does this happen? Is it creating nodes? elements? DOM? It could be documented better.

**Comment by caitp** [comment]
This is normal course of business for HTML, per https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element --- when the `src` attribute is set (either during parsing or via JS), a new request is made (which may result in fetching cached image data).

If you need the DOM to be inate, you could wrap it in a `<template>` element (at a cost of greater complexity and reduced browser support)

**Comment by joshribakoff** [comment]
@caitp  Thanks, I'm clear on the spec about setting `.src` on an img element, I use that to preload images with `new Image` syntax. What clears it up for me is your last sentence. The compiler is creating document fragments (documentation for states its creating "templates" which is not so clear). I can see this now in the source code, $compile calls into jqLite, which calls `document.createElement()`. Makes sense now. This link was helpful to me - https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment
