### ISSUE TITLE
ngAnimate issue on ng-show with a nested ng-repeat

### ISSUE THREAD

**Issue by Okazari** [angular/angular.js#12276]
Hi, i was actually helping on stackoverflow for some issues and i ran into this one : 
http://stackoverflow.com/questions/31245780/parent-child-animation-unexpected-different-angular-1-3-to-1-4/

After some try i was able to figure out where was the trouble : 

On "ng-show/hide" with a nested "ng-repeat" there is no class "ng-hide-animate" added on the element during the animation.

This doesn't work on 1.4.0 - 1.4.1 - 1.4.2: http://codepen.io/anon/pen/EjEora
This works on 1.3.5 : http://codepen.io/anon/pen/VLXygP

Not having this class cause this to be applied during the animation.

.ng-hide:not(.ng-hide-animate) {
  display: none !important;
}

Which result into not hiding the element before the animation end.

I'm also a bit confused about the documentation : 

**1.4.X documentation**
> CSS Class-based Animations
> Class-based animations (animations that are triggered via ngClass, ngShow, ngHide and some other > directives) have a slightly different naming convention. Class-based animations are basic enough that a standard transition or keyframe can be referenced on the class being added and removed.

> For example if we wanted to do a CSS animation for ngHide then we place an animation on the .ng-> hide CSS class:

The 1.4.X documentation specify that we shoudn't have this "ng-hide-animate". So i guess that the ng-hide:not(.ng-hide-animate) in the CSS shoudn't exist.

What do you think about this ? Is that a bug or just a miss-use ?

**Comment by havenchyk** [comment]
@Okazari works much better with 1.4.1 instead of 1.4.0, could you have a try?

**Comment by Okazari** [comment]
@havenchyk  Just tried with 1.4.1 and 1.4.2. still got the issue.

**Comment by planetflash** [comment]
@Okazari , @havenchyk , likewise, I have the same issue and no change on 1.4.0 - 1.4.2

**Comment by matsko** [comment]
The issue is because of the repeater cancelling out the parent classes. There is a fix that takes care of this issue: https://github.com/angular/angular.js/pull/12248

I just need a few days to do some more testing.

**Comment by matsko** [comment]
I confirm that https://github.com/angular/angular.js/pull/12248 fixes the issue.

**Comment by Okazari** [comment]
@matsko Thank you, great work.
