### ISSUE TITLE
Poor email validation

### ISSUE THREAD

**Issue by zverevalexei** [angular/angular.js#12288]
Hi

I was watching a tutorial video on codeschool about form validation in Angular, when I found out emails were validated way too poorly.
For example, you needn't type the email address completely: foo@bar is enough to make form validated.
Just a simple form:
```
{{test}}
<form name="testForm" ng-submit="return false;" novalidate>
Enter your email:<br>
<input type="email" ng-model="test" required>
<div>form is {{testForm.$valid}}</div>
<input type="submit" class="btn btn-submit" value="Submit">
</form>
```
Result is that testForm.$valid is TRUE

Thanks.

**Comment by caitp** [comment]
"foo@bar" is a valid email address, per spec. You can add a custom ng-pattern validator (or otherwise extend the email validator or add another parser/formatter) to be strict about requiring a top-level domain.

**Comment by caitp** [comment]
Dupe of #11510 / #11385 / #10052 / numerous others

**Comment by caitp** [comment]
@Narretz you mentioned previously that we should allow customization of this, did you have a plan for an api to make this customization easy?

**Comment by gkalpak** [comment]
Just in case @zverevalexei is not aware of that, there is an example that shows how to overwrite e-mail validation in the [Forms section][1] of the Developer Guide.

[1]: https://docs.angularjs.org/guide/forms#modifying-built-in-validators

**Comment by zverevalexei** [comment]
@caitp I did look for other topics, but it seems like I should have done it more properly :) Thanks for your advice!
@gkalpak I'm learning the nature of Angular atm, and certainly, it's useful to me. Thank you!
