### ISSUE TITLE
ngOptions select as selects first option (due to reuse?)

### ISSUE THREAD

**Issue by asharpe** [angular/angular.js#12283]
See http://plnkr.co/edit/uQL4B6C32f65Cm4lnFNH?p=preview

Inspecting the options in the select shows that both options have been selected.

**Comment by asharpe** [comment]
Here's another plunk that indicates it's the reuse of the first option (with selected="selected") that's causing the option to remain selected - http://plnkr.co/edit/hmsvIu5OV8o2lCu1Ass1?p=preview

**Comment by asharpe** [comment]
Possibly a dupe of #11727

**Comment by Narretz** [comment]
Yes that's a dupe of #11727
