### ISSUE TITLE
$$rAF performance issue in Angular Material

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/angular.js#12280]
When scrolling *sticky* md-subheader, recent changes in $$rAF seem to create excessive CPU usages.
See https://github.com/angular/material/issues/3531 for details and CodePen demos.

**Comment by ThomasBurleson** [comment]
Thx @Narretz

**Comment by ThomasBurleson** [comment]
Another issue related to **mdMenu**: https://github.com/angular/material/issues/3527

**Comment by AdriVanHoudt** [comment]
Any movement on this? We have to resort to using 1.3.15...

**Comment by MichhDiego** [comment]
Same as @AdriVanHoudt , any movement?

**Comment by AdriVanHoudt** [comment]
The commit is there why wasn't this included in 1.4.4?

**Comment by matsko** [comment]
@AdriVanHoudt the commit wasn't guaranteed to fix it. We're testing to see if we can use setTimeout in IE to make this work better.

**Comment by AdriVanHoudt** [comment]
@matsko cool, let me know if I can help and of you know an ETA that would be helpfull

**Comment by matsko** [comment]
It's set as the main fix for 1.4 this week. So it should be done for the next release.

**Comment by AdriVanHoudt** [comment]
Cool, thanks for all the work!

**Comment by MichhDiego** [comment]
Thanks guys!

**Comment by matsko** [comment]
1.4.5 will have the fix.

**Comment by AdriVanHoudt** [comment]
:tada: :pray:
