### ISSUE TITLE
angular.js 1.4 isFunction is not defined in loader.js

### ISSUE THREAD

**Issue by jerryorta-dev** [angular/angular.js#12287]
Loading the seed-app with index-async.html, loader.js throws an error ```Uncaught ReferenceError: isFunction is not defined```.

I will have a pull request to fix loader.js.

**Comment by lgalfaso** [comment]
I think that `isFunction` should be added to *src/loader.prefix*, and that should make it.

**Comment by jerryorta-dev** [comment]
@lgalfaso thank you. Didn't see this at first. Adjusting pull request.

**Comment by jerryorta-dev** [comment]
ok... this should be ready to merge per instructions.

**Comment by jerryorta-dev** [comment]
I see the pr was declined. Any suggestions how this may be fixed?

**Comment by pkozlowski-opensource** [comment]
@jerryorta-dev sorry, I've closed your PR by accident / lack of knowledge. I've re-opened it.

**Comment by lgalfaso** [comment]
landed as 9ea52d818bcd2fb3ea8ccc85bf47f9fd5af68843
