### ISSUE TITLE
ng-show not working with ng-animate after event.preventDefault()

### ISSUE THREAD

**Issue by palortoff** [angular/angular.js#12296]
When aborting a location change with event.preventDefault() ng-show depending on the $location is not evaluated correctly.

This only happens since angular 1.4 if angular-animate is included in the module dependency.

See [Plunker](http://plnkr.co/edit/gLKGkS) for example:
- click 'go to sub-page'
- click 'go home'
- cancel the dialog
==> route stays on sub page, home link is shown for home

Workaround: Using ng-if instead of ng-show works as expected.

**Comment by sreeramu** [comment]
@matsko I had verified this issue with snapshot, this issue is fixed with #12277 merge, it should be safe to close this issue.

Updated Plunker:
http://plnkr.co/edit/LwESLTSFTtd7qoKaOHN3

**Comment by matsko** [comment]
This has been fixed in master with @sreeramu's fix: http://plnkr.co/edit/YoLRbHJEQjq2sroR9oHc?p=preview

Once 1.4.4 is out then you can use it on there. For now you can use the snapshot version: https://code.angularjs.org/snapshot.
