### ISSUE TITLE
Paradox in populating select box from directive

### ISSUE THREAD

**Issue by pulkitnandan** [angular/angular.js#12302]
I'm trying to select options of select box after clicking an d3js chart element. D3js chart is built up inside the link function of a directive and has a action listener attached on all sectors of chart where action is a function defined in the controller wrapping the directive where I'm currently assigning desired values in ng-model of selectBox but its doesn't make selectBox to display selected options.

As a corollary I'm able to select options of selectBox through a click on a div that has action as same function which d3js chart listener had and that div too lives under the same parent as d3js chart.
 
Have a look at this plunk http://goo.gl/qCwqBo

Tab1: Why it doesn't populates ng-model -- currentVendors present in filterController when selecting one of the option in selectBox.

Tab2: populates it 
But 
After Clicking aqua colored square just above pie chart performs auto selection of select box. 
While clicking any of the sectors of the pie chart supposed to perform the same action fails to do so while both of them execute same effective line of code at line 50 of filterController.js. which populates currentVendors array used as model of select-box.

**Comment by pkozlowski-opensource** [comment]
@pulkitnandan please provide a minimal reproduce scenario using http://plnkr.co/ or similar. We can't debug full application code, I'm afraid.

**Comment by pulkitnandan** [comment]
For tab1 I need to attach filterController inside the template of ng-include directive so this means I can't set an array inside a controller which is wrapping ng-include directive which includes a html template that has element which uses the array model present controller but how the function is accesible inside the html template that is attached as ng-change?

Issue in tab2 is resolved if I call $rootscope.$digest() after assigning values to model.

**Comment by pulkitnandan** [comment]
I need put this array inside a object and then use this array as element of the object. Then tab1 works..
