### ISSUE TITLE
Feature Request: Path in $watch

### ISSUE THREAD

**Issue by peter254** [angular/angular.js#12306]
**Overview**:
when the handler of the $watch event is called, it would be helpful to get the path to the attribute that changed. When using objectEquality=true this can be long and searching for differences has a high computational effort

**Motivation**:
An example for usage would be when tracking changes in an object. This is necessary if data should be synchronized with a server - if the changed objects could be tracked only those would need to be send back to the server.

**Comment by Narretz** [comment]
Afailk, the change check doesn't know the path, either, because, as you said, it's computationally expensive. It could be possible as an option, but I don't really see huge demand for it.

**Comment by gkalpak** [comment]
Deep-watch uses `equals`, which currently doesn't keep track of the property path. Adding this feature would require significant changes to critical paths (`equals`, `$watch`) for very little benefit imo.

Note that `equals` will bail out when it encounters the first change, but there is no guarantee about the total number of changes in the object. In order for such a feature to be useful, we would need to always traverse the whole object, which would have non-negligible performance implications.

Closing as implementing this would have negative impact on the core.
