### ISSUE TITLE
directive require

### ISSUE THREAD

**Issue by tuchk4** [angular/angular.js#12308]
Directive:

```js
module.directive('foo', function() {
    return {
      restrict: 'E',
      require: ['^foo'],
      transclude: true,
      scope: {},
      controller: function($scope) {
       this.bar = function() {
         console.log(1);
       }
      },
      link: function(scope, element, attr, require) {
        console.log(require);
      },
      template: '<div>1</div>'
    };
  });
```
Here is example http://plnkr.co/edit/SggOc9ZGGln4T1COB8Dv?p=preview
Why in this case **require**  variable at link function is link to current directive controller?
Markup is
```html
<foo></foo>
```

But I expect that **require** will be a controller of parent directive in this case:
```html
<foo>
  <foo></foo>
</foo>
```

And this is recursion. But angular does not throw error. Is it possible to configure directive's require as optional (require: '^?foo')?

**Comment by gkalpak** [comment]
This is a general support question and should be directed to the [appropriate channels][1].
GitHub is reserved for bug reports and feature requests.

That said, this works as expected. Check out the [relevant docs][2].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://docs.angularjs.org/api/ng/service/$compile#-require-
