### ISSUE TITLE
angularjs directive

### ISSUE THREAD

**Issue by harishr2222** [angular/angular.js#12310]
Hi Team,

I am using 1.3.8 version, i have created a directive, in directive i have created controller which can handle http get request, i have used this directive 6 times, but http get call is overriding the values of other http get call, i have used two-way-binding(=) for setting the value.

Regards,
Harish

**Comment by pkozlowski-opensource** [comment]
Please ask general support questions like this one using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
