### ISSUE TITLE
regarding issue

### ISSUE THREAD

**Issue by rameshwargurjar** [angular/angular.js#12315]
heyy there i have one issue i have angular js version angular.min.js3.16  but my one contact add programme not workigh in this version that is working on version 1.1.1 angular.min.js

**Comment by bradleyflood** [comment]
Not clear what the issue is here? It sounds like your code itself has issues, not Angular.

**Comment by pkozlowski-opensource** [comment]
@rameshwargurjar this is not a proper place nor form to ask general support questions (btw, it is really hard / impossible to understand what your problem really is). See: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
