### ISSUE TITLE
Unterminated quote when string contains some chars

### ISSUE THREAD

**Issue by pixsrv** [angular/angular.js#12311]
folowing lines cause angular to show error
```html
<div ng-click="foo('abc!')"></div>
<div ng-click="foo('abc&')"></div>
```
Error: $parse:lexerr
Lexer Error: Unterminated quote at columns ... ['abc] in expression [foo'abc].

but of course these two don't
```html
<div ng-click="foo('abc')"></div>
<div ng-click="foo('abc')"></div>
```

(escaping doesn't help)

EDIT: this works well
```html
<div onclick="foo('abc!')"></div>
<div onclick="foo('abc&')"></div>
```

**Comment by gkalpak** [comment]
Which version of Angular are you using ? (I can't reproduce it on 1.4.)
A live reproduction would also help.

<sub>BTW, make sure to disable any extensions that might fiddle with Angular expressions (e.g. Batarang).</sub>

**Comment by pixsrv** [comment]
hi gkalpak
it's v1.3.15
live preview not possible :(

digging in the issue i noticed strange thing

when i add ng-click as above using jQuery with .attr() then error occurs
but when i add it by .data() then it doesn't occur

**Comment by caitp** [comment]
(what)

**Comment by pixsrv** [comment]
that was my reaction ;)

btw: switching off batarang "fixes" the problem

**Comment by caitp** [comment]
The code for `readString()` has only changed superficially between 1.3.15 and master (https://www.diffchecker.com/lnygm32z), so any impact there likely causes the same issue in master.

> btw: switching off batarang "fixes" the problem

Then it's worth filing on batarang

**Comment by pixsrv** [comment]
will be done asap

thanx guys for your help ;)
