### ISSUE TITLE
error running npm install and bower install on windows 7

### ISSUE THREAD

**Issue by nokunver** [angular/angular.js#12313]
I am getting following error while running npm install or bower install

C:\angularJSTutorial\angular-phonecat>bower install
bower not-cached    git://github.com/angular/bower-angular.git#1.4.x
bower resolve       git://github.com/angular/bower-angular.git#1.4.x
bower not-cached    git://github.com/jquery/jquery.git#~2.1.1
bower resolve       git://github.com/jquery/jquery.git#~2.1.1
bower not-cached    git://github.com/twbs/bootstrap.git#~3.1.1
bower resolve       git://github.com/twbs/bootstrap.git#~3.1.1
bower not-cached    git://github.com/angular/bower-angular-mocks.git#1.4.x
bower resolve       git://github.com/angular/bower-angular-mocks.git#1.4.x
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular.git
", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.131]: errno=No error

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=No error

//////////////npm install

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=No error

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\np
m\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angularJSTutorial\angular-phonecat\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\np
m\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 prestart script 'npm install'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angularJSTutorial\angular-phonecat\npm-debug.log

**Comment by bradleyflood** [comment]
It looks like the issue is on your end "`unable to connect to github.com`". Not an issue with Angular. Perhaps a local networking issue?

**Comment by nokunver** [comment]
The issue is not with angular but looks like its a an issue with BOWER conf file, if i use https:// github.com/angular/bower-angular.git#1.4.x then i can connect but not with git://

May be something to do with running this tutorial on windows 7 platform


bower not-cached    git://github.com/angular/bower-angular.git#1.4.x
bower resolve       git://github.com/angular/bower-angular.git#1.4.x
bower not-cached    git://github.com/angular/bower-angular-mocks.git#1.4.x
bower resolve       git://github.com/angular/bower-angular-mocks.git#1.4.x
bower not-cached    git://github.com/jquery/jquery.git#~2.1.1
bower resolve       git://github.com/jquery/jquery.git#~2.1.1
bower not-cached    git://github.com/twbs/bootstrap.git#~3.1.1
bower resolve       git://github.com/twbs/bootstrap.git#~3.1.1
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-moc
ks.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=No error


Med vennlig hilsen

Kundan Verma
Senior IT Architect | Nordic IT

TDC AS
Sandakerveien 130
Postboks 4600. Nydalen
N-0405 Oslo

Tlf:                   +47 98158704
E-post:            kundan.verma@tdc.no<mailto:mobil@tdc.no>
Web:               tdc.no
[TDC Logo 2010]

**Comment by nokunver** [comment]
Problem got solved using git config --global url.https://github.com/.insteadOf git://github.com/

as i am behind corporate firewall :)

Med vennlig hilsen

Kundan Verma
