### ISSUE TITLE
[jqLight] Prepend method freezes browser

### ISSUE THREAD

**Issue by smashercosmo** [angular/angular.js#12327]
jqLight's prepend method freezes browser completely. Here is a [plunker](http://plnkr.co/edit/CcUDVQoWOTFo1cSvKLh1). Append method works fine.

**Comment by gkalpak** [comment]
Duplicate of #11217 (e.g. see https://github.com/angular/angular.js/issues/11217#issuecomment-76715981).

Because of how the Angular compiler works, you can't prepend elements to the element you are compiling during the compilation phase.
