### ISSUE TITLE
 Cannot read property '$$nextSibling' of null - delete directive from contenteditable

### ISSUE THREAD

**Issue by Olgagr** [angular/angular.js#12331]
I understand that my issue could be a corner case. I have contenteditable div, which contains html with directives. As this is contenteditable, directives could be removed outside angular. However, I can observe changed in the DOM thanks to MutationObserver and if the particular directive is removed, I would like to make clean up (destroy scope, unbind events from element). However, when I call scope.$destroy() I get this error:

```
 Cannot read property '$$nextSibling' of null
```

and also

```
Error: [$rootScope:inprog] $digest already in progress
```

I prepared example of this behaviour:
http://plnkr.co/edit/lE5eFde73LYAgRr0hMoR?p=preview

I wonder if this issue is so specific that this is not possible to correctly clean up with contenteditable or this is bug in my code.

**Comment by lgalfaso** [comment]
Is this browser OS specific? Try the plunker with Chrome 43/OS X and there is no error in the console.

**Comment by Olgagr** [comment]
Did you remove the directive from contenteditable ? The error is thrown when you removed directive from contenteditable and so the scope.$destroy() is called. I'm also using Chrome 43/OS X.

**Comment by lgalfaso** [comment]
I simply do not know what I am looking at. Please create a minimal scenario with the least amount of extras

**Comment by Olgagr** [comment]
Ok, the simple scenario is:

1. Load the page http://plnkr.co/edit/lE5eFde73LYAgRr0hMoR?p=preview
2. Put the cursor before "other content"
3. Hit Backspace
4. The "edit directive" is deleted, the error "Cannot read property '$$nextSibling' of null" is thrown
5. Start write something, the error "Error: [$rootScope:inprog] $digest already in progress" is thrown

**Comment by lgalfaso** [comment]
You are doing 2 things that are big no-no.
1/ Destroy a scope you did not create (in this case the scope the directive lives on
2/ Destroy a scope within a watches on the same scope

This aside, this is not a support forum and I would recommend that you use StackOverflow for help
