### ISSUE TITLE
Angular 1.4 filtered promises support

### ISSUE THREAD

**Issue by mgcrea** [angular/angular.js#12337]
Angular 1.4.0 started to throw errors when the ng.filter filter started to throw on non-array objects (#9992). This type check broke promise usage with filters, the following expression is now throwing errors before resolving the promise:

```
getAddress($viewValue) | filter:"Al" | limitTo:6
```

```js
  $scope.getAddress = function() {
    return $q(function(resolve, reject) {
      resolve(['Alabama', 'Alaska', ...]);
    });
  }
```

More specifically, this broke AngularStrap typeahead with remote source example.

Looking at the source code, it looks like filters where probably not correctly applied in previous version of Angular, anyone could confirm this? Maybe there is another way around this issue?

Anyway, promises should be first class citizen across the framework. So it would be nice to have full support for them.

**Comment by lgalfaso** [comment]
@mgcrea from what version of Angular are you upgrading from? Automatic resolution of promises in expressions was deprecated in 1.3.

**Comment by mgcrea** [comment]
@lgalfaso, this code used to "work" (not fail) for both 1.2 and 1.3 branches. Indeed it probably correctly worked in 1.2, maybe failed silently in 1.3 (but the results were fine du to the filter being handled by the promise) and currently throws in 1.4.

Too bad it's unsupported anymore, it was a nice API. Any ideas on how to achieve that in 1.4?

**Comment by gkalpak** [comment]
@mgcrea, well, it didn't actually work in 1.2/1.3 either (it just didn't throw an error).
Pre 1.4, `filterFilter` would silently return the input unchanged if it wasn't an array/array-like, but it would throw an error.

As a result, you would get back the original promise (see [parse-options.js#L35][1]) and the bind the async rsolved values to `$parseOptions.$values`. So there would be no filtering going on.
([Demo of synv vs async typeahead][2] - notice that in the sync case the items are properly filtered, while in the async the original list is displayed unfiltered.)

--
So, the current throwing behaviour is better (in that it revealed a silent bug).
I don't think this can be improved in core, without automatic promise resolution or a new async filter.

If I wanted to support filtering async loaded data in my typeahead component I would try one of 2:

1. Change my parsing to separate the actual expression from the filtering part, resolve the expression (if it's a promise) and then pass the result through the filtering pipe.

2. Provide an async filter, that returns an empty array which will be populated with data when they arrive (pretty much what `ngResource` does).

Option 2 is more clear/straightforward and maintainable imo, but it has the downside that one should use an extra filter: `bd-options="item in getItemsAsync() | async | filter:... | ..."`
(<sub>I'd still go for option 2 anyway !</sub> 

[1]: https://github.com/mgcrea/angular-strap/blob/v2.2.4/src/helpers/parse-options.js#L35
[2]: http://codepen.io/ExpertSystem/pen/jPKmOK?editors=101

**Comment by lgalfaso** [comment]
This issue talks about a use case that was never supported and was already broken. There is nothing actionable here.
