### ISSUE TITLE
There is a small problem in AngularJS Git Commit Message Conventions on google docs

### ISSUE THREAD

**Issue by stevemao** [angular/angular.js#12339]
Related PR: https://github.com/angular/angular.js/pull/12032
> The type is mandatory and the scope is optional

is wrong. It should say The **header** is mandatory and the **scope** of the header is optional.
You could also say "The type and subject is mandatory and the scope is optional in the header, and other parts are optional".

I also think a git repo would be easier for us to contribute than google docs... 
@petebacondarwin

**Comment by Narretz** [comment]
This has been changed in our contributing.md yesterday. I am not sure we can edit this google doc, or if this change should be tracked here. Wdyt @petebacondarwin ?

**Comment by petebacondarwin** [comment]
I have tweaked the Google doc further. We should probably allow public comments to make it easier to collaborate on that document.

**Comment by stevemao** [comment]
Thanks @petebacondarwin , Looks good for now. Just a few things:
1. I updated table of contents (as there is some mismatch with the new titles). Not sure if you see my suggestion.
2. When I open the doc, I'm in "Suggesting mode". I think it would be better to be in "Viewing mode" by default. Not sure if you can change this though. Or is it just my machine.

**Comment by petebacondarwin** [comment]
Thanks @stevemao. I don't think we can control what the default view you get is...
