### ISSUE TITLE
The [pass] parameter to $timeout is not transferred to the callback function

### ISSUE THREAD

**Issue by roysharon** [angular/angular.js#12333]
The [$timeout reference](https://docs.angularjs.org/api/ng/service/$timeout) says it should pass the [pass] parameter to the callback function. This does not seem to be working.

**Comment by caitp** [comment]
Which version of angular are you using?

**Comment by caitp** [comment]
This feature was added in 1.4.0, maybe it's just an issue of looking at the incorrect version of the docs. Please clarify if this is not the case

**Comment by pkozlowski-opensource** [comment]
Closing due to the lack of details.
