### ISSUE TITLE
Can you include connection timeout in Angular js using the ready state?

### ISSUE THREAD

**Issue by jsasid0** [angular/angular.js#12349]
In my application, I need to distinguish between connection timeout and read timeout.
Presently in angular the $http cal waits till the read timeout value (e.g 45sec) even though the server connection is not established, which can be identified within (1-2 sec). I need to abort the http call once connection timeout has happened.

In ajax we can do this but checking the xhr.ready state. Refer:
http://www.w3schools.com/ajax/ajax_xmlhttprequest_onreadystatechange.asp

**Comment by petebacondarwin** [comment]
I think this would be solved by #1934

**Comment by Narretz** [comment]
I believe this should be possible to handle with either https://github.com/angular/angular.js/commit/d49782226689a135b7f6a86ee35bcded59c22b33 or 106f90aafa
