### ISSUE TITLE
$q.all unexpected behavior when given multiple arguments

### ISSUE THREAD

**Issue by javinor** [angular/angular.js#12343]
I encountered two odd scenarios.

* When given primitives, an empty object is returned: 
```javascript
$q.all(7,8,9).then(console.log.bind(console)) // 'Object {}'
```
* When given multiple promises, only the first promise is resolved:

```javascript
var p1 = $q.when(7)
  , p2 = $q.when(8)
$q.all(p1, p2).then(console.log.bind(console)) // '7'
```

I'm not sure what would be the best behavior, but my gut feeling is that `$q.all` should
(1) wrap non-object non-array input, by wrapping it with `$q.when`, just like it would do with a hash/array of non-promises and (2) support the case when `arguments.length != 1` 
_**OR**_ 
warn / throw / reject / anything which is not walking silently into the night

**Comment by lgalfaso** [comment]
Please read the documentation https://docs.angularjs.org/api/ng/service/$q#all `$q.all` takes a single parameter that is an array or an object.

**Comment by javinor** [comment]
Yes, I read the documentation and know that it takes a single parameter which is an array or an object. My team encountered a bug due to a passing in multiple promises and omitting the `[]` accidentally. I'm guessing we're not the first who encountered this. Having `$q.all` either support additional inputs or return a rejected promise if `arguments.length != 1` sounds like a good idea to me. Being an intermediately experienced angular developer, I thought I'd suggest this.

Is this reasonable? If so, I'd be more than happy to do it myself. If not, could you explain why?

**Comment by pkozlowski-opensource** [comment]
@javinor are you suggesting that `$q.all` should throw when passed more than one argument? If so, the request sounds reasonable, but proper error reporting in client-side frameworks is always tricky, as each check adds bytes to the framework which increases its load / processing time. This is why we should by adding checks for most common errors and we will probably never be able to properly report all possible mistakes. So, while I would love to have super precise error messages I don't want to explose the size of the framework.

**Comment by S-YOU** [comment]
If $q.all throw error when passing more than one arguments, how about every other javascript functions that take single argument? That's one of the feature of typescript that give warnings on such things.

**Comment by gkalpak** [comment]
I definitely agree with @S-YOU. Checking every function to make sure the user didn't pass more arguments makes no sense imo.
(If nothing else, it _**is**_ perfectly valid in JS to pass as many arguments as you want.)

**Comment by lgalfaso** [comment]
I think that detecting when more parameters are sent fits better into angular-hint than as part of the core
