### ISSUE TITLE
Screen freeze 

### ISSUE THREAD

**Issue by talhaali** [angular/angular.js#12357]
Screen freezes when cross button is clicked multiple times in autocomplete

**Comment by pkozlowski-opensource** [comment]
@talhaali there is not enough detail here, this issue is not actionable. Please check https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit before submitting issues.

**Comment by havenchyk** [comment]
It's not a problem of angular itself, I guess.

**Comment by talhaali** [comment]
The issue is reproducible on my project and https://material.angularjs.org/ as well .. you can check it there

**Comment by havenchyk** [comment]
@talhaali but what exactly should be found there? please, describe the problem in details

**Comment by talhaali** [comment]
@havenchyk sorry if I am ambiguous here. Please follow below steps:
1. Go to below link
https://material.angularjs.org/latest/#/demo/material.components.autocomplete
2. Select your favorite state from drop down
3. Click multiple time on the cross button which appear after selecting the state.

Here you will observe that the screen will freeze and you will have to refresh the window.

**Comment by pkozlowski-opensource** [comment]
@talhaali I can't reproduce this on my Linux box (tried with Chrome and FFox). Maybe you've got an extension installed in your browser that messes up things?

In any case this is something that should be investigated on the material components side. Please try to re-test using an incognito mode in your browser and if you still face problems open an issue in https://github.com/angular/material (remember to provide all the details as requested: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit )
