### ISSUE TITLE
Question: How angular know when to run or not to run $scope.$apply for $http().success

### ISSUE THREAD

**Issue by askucher** [angular/angular.js#12352]
Hi. 

if I do setTImeout I have to explicitly use $scope.$apply in order to show changes in my template
```Javascript
setTimeout(function() {
$scope.$apply(function() {
$scope.i = 1
});
}, 100);
```
But when I do 

```Javascript
$http.get('').success(function() {   $scope.i = 1 });
```

My scope will be updated correctly without extra actions
How angular know when it should run $scope.$apply. and How angular access to my local $scope
Or it always run $rootScope.$apply?

**Comment by pkozlowski-opensource** [comment]
It does it depending on the `useApplyAsync` flag: https://github.com/angular/angular.js/blob/1622182737a41cf4619a514fd71529e07e82d594/src/ng/http.js#L1249-L1254

Please direct general questions like this to an appropriate support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question, we want to keep GitHub issues for bug reports and feature requests. Thnx!

**Comment by S-YOU** [comment]
This should be stackoverflow question. setTimeout is not under control by angular.
