### ISSUE TITLE
Updating directive definition

### ISSUE THREAD

**Issue by bukharin** [angular/angular.js#12355]
I try to implement live updating of angularjs application, that user can modify directive definition (controller, template, bindings...) and it has been re-rendered at the page automatically,  without reloading the page (through nodejs + websockets + chrome extention)

The purpose is update existing definition of directive that has been rendered at the page. I have done with template, but can't achieve with controller and other directive definition properties. It seems that it's impossible in current angularJs implementation.

I found that `directive` method register `name + "Directive"`factory. I tried to register the directive as factory direct but `directive` method also register it in  in `hasDirectives` private variable (https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L726) that checks on compile time. Also injector caches the factory result in the internal cache object.

It would be nice to see an api for updating existing directive defintion objects, like:

```
$compile.updateDirective(name, newDirectiveDefinitionObject);
```

I experiment and found to achieve this we need:

- register new `name + "Directive"`factory
- drop injector cache for `name + "Directive"`

**Comment by lgalfaso** [comment]
I think that this is a bad idea. What should happen to a directive that is currently active when it is redefined? What about it scope, other directives that may hold the controller, merged and transcluded html, other directives within, when there are multiple directives with the same name... the list just goes on and on.

If you want the ability to redefine a directive, then the directive itself need to collaborate, do its part, and whatever needs to be recompiled, done by the app itself.

**Comment by bukharin** [comment]
@lgalfaso live updating - it's a feature to speedup development process only. It means that user can modify application source code and it will be reflected on the page without reloading and it does not imply any support in application code.

I think it is not so impossible. Extension may know about all directive instances which currently rendered on the page, by intercepting compile and link functions. After user update directive in the source code, it can:

- update directive definition in browser
- compile directive instances with the same compilation context (transcludefn, controllers etc)
- replace old directive element with new one
- destroy old directive scope

**Comment by lgalfaso** [comment]
An automatic reload mechanism to make development faster at the expense of a larger codebase for everybody is not something very interesting. Until there is some explanation that shows how this would work, I do not think there is anything actionable here. If you would like to build a proposal, then please create a doc explaining it (please do not start with a PR, start with a doc) and send it to the devs mailing list.
