### ISSUE TITLE
hi,where can i get the offeline demo for ui-bootstrap

### ISSUE THREAD

**Issue by coojee2012** [angular/angular.js#12369]
hi,where can i get the offeline demo for ui-bootstrap.
tks

**Comment by Narretz** [comment]
I think this is a question for https://github.com/angular-ui/bootstrap

**Comment by pkozlowski-opensource** [comment]
Which was answered already: https://github.com/angular-ui/bootstrap/issues/3955 :-)

@coojee2012 please, don't cross-post.
