### ISSUE TITLE
ngAttr added attributes don't trigger directives

### ISSUE THREAD

**Issue by twhitbeck** [angular/angular.js#12363]
This may be by design, but I thought I'd bring it up.

Since `ngAttr`-prefixed attributes are interpolated with allOrNothing, an attribute may or may not be present initially. If the expression is defined on the first evaluation, it looks like the resulting attribute _will_ trigger directives. However, if the expression is initially undefined, when it later becomes defined the attribute that is added will not cause any directives to be applied to the element.

My use case is this: I'm using `ng-attr-min` and `ng-attr-max` on an `input[type=date]` with something like `ng-attr-min="{{minDate | date:'yyyy-MM-dd'}}"`. If `minDate` is undefined, I don't want there to be any min validation. When `minDate` becomes defined, the min attribute is properly set but the `min` directive is not applied retroactively, therefore I don't get my angular min validation.

The alternatives are
* Use `ngMin`, but this doesn't set the `min` attribute and on Chrome the datepicker won't be properly restricted.
* Use interpolation on `min` directly (e.g. `min="{{minDate | date:'yyyy-MM-dd'}}"`), but when `minDate` is undefined, this leaves a dangling `min` attribute with no value which incorrectly makes _any_ value invalid (this might be a bug).

**Comment by caitp** [comment]
This is one of those difficult things --- unfortunately, we don't have a good way to trigger compilation when the DOM changes in this way. Attempting to do so would massively harm performance.

To add to this, there's also no way to "trigger" one particular directive, all you can do is compile an entire chunk of DOM. You could explicitly recompile the chunk of DOM you want to, but there isn't really a good way to do this.

**Comment by caitp** [comment]
oops, didn't mean to close that, maybe someone else will have something to say about it.

**Comment by pkozlowski-opensource** [comment]
Agree with @caitp that it would be very hard to support. I would suggest that we focus on the original issue of the conditional `min` validation here instead.

**Comment by gkalpak** [comment]
This is easy to work around by means of: `min="{{(minDate || 0) | date:'yyyy-MM-dd'}}"`
(It's not ideal though...)

**Comment by twhitbeck** [comment]
All makes sense.
It seems to me like the issue could be solved if the `min` directive could handle having a blank value by not validating.

`<input type="date" min ng-model="date">` will invalidate any input.
