### ISSUE TITLE
ngIf on body stop animation

### ISSUE THREAD

**Issue by ricardobfa** [angular/angular.js#12366]
When i use a condition (in my case `ngIf`) in the `body`, all animation using `ngAnimate` dos not work anymore.

reproduced:
http://codepen.io/anon/pen/MwByOL

I tried using a old version (1.3.15) and everything back to normal.

**Comment by matsko** [comment]
It seems like Angular Material is having an issue with the latest release of 1.4. @ThomasBurleson and I are getting to the bottom of it.

**Comment by ThomasBurleson** [comment]
I also just noticed that I really do not like *Line 38*
<https://github.com/angular/material/blob/master/src/core/core.js#L38>
which should be:

*queueArgs = Array.prototype.slice.call(arguments);*

**Comment by gkalpak** [comment]
Since you are passing it to `apply()` I don't think it matters (so I prefer the more concise version :smile:).

**Comment by ThomasBurleson** [comment]
`.apply()` expects an array not an object. I have found some scenarios where not explicitly passing an Array caused problems.

**Comment by matsko** [comment]
@ricardobfa this looks like it's still not working with the latest patch we have for ngAnimate. Once https://github.com/angular/angular.js/pull/12669 is in then I'll be able to figure this one out. Sorry for the delay.

**Comment by matsko** [comment]
Alright we have a fix: http://www.angular-dev.com/pr-12366/index.html

This PR does the job: https://github.com/angular/angular.js/pull/12721

**Comment by Narretz** [comment]
This is fixed and will be part of the next 1.4 release.
