### ISSUE TITLE
Validation Messages are not getting displayed using ngMessages inside twitter bootstrap accordion.

### ISSUE THREAD

**Issue by raajamalik** [angular/angular.js#12368]
Hello,

We are using ngMessages for displaying validation messages in our angular app.

We have a bussiness requirement that the controls on the page be grouped inside an accordion panels(using twitter bootstrap accordion).

But the problem with this - ngMessages is not displaying the validation message for the controls which are placed inside the accordion panel. The same control when placed outside the accordion panel is displaying validation message. 

Any idea about this?

I debugged the code and found that to display a validation message this is the watch ngMessages code uses:

var cachedValues, watchAttr = $attrs.ngMessages || $attrs['for']; //for is a reserved keyword
          $scope.$watchCollection(watchAttr, function(values) {
             cachedValues = values;
             ctrl.renderMessages(values, multiple);
        });

I am trying to find the problem but no success till now. 

Thanks
Raja

**Comment by pkozlowski-opensource** [comment]
@raajamalik you should be using a dedicated support channel for questions like this, if you are unsure if we are talking about the AngularJS bug here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

If you believe that this is a bug, please provide all the required details so we can reproduce: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit

**Comment by raajamalik** [comment]
Ok. I was not ware about this. Neither I noticed section of questions you
pointed out.

I will raise this questions at the write channel.

Thanks
Raja

On Friday, July 17, 2015, Pawel Kozlowski <notifications@github.com> wrote:

> @raajamalik <https://github.com/raajamalik> you should be using a
> dedicated support channel for questions like this, if you are unsure if we
> are talking about the AngularJS bug here:
> https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
>
> If you believe that this is a bug, please provide all the required details
> so we can reproduce:
> https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/issues/12368#issuecomment-122211541>
> .
>


-- 
Thanks
Raja Malik
