### ISSUE TITLE
Angular 1.4.x breaks Angular Material Select menu

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/angular.js#12375]
See issue for details

* https://github.com/angular/material/issues/3780#issuecomment-122344455
* https://github.com/angular/material/issues/3704

**Comment by ThomasBurleson** [comment]
Appears to have been an issue with transitionEnd events not firing and our wait process timing out; 
Perhaps Angular 1.4.x is interfering with some dispatching of transitionEnd events... meanwhile AMv1 appears to account for this now.

> Occassionally the transitionEnd event will not fire and the '$mdUtil. waitTransitionEnd()' process will timeout; which rejects the pending promise. Using '.finally()' [consistently] allows the correct handlers to fire and will continuing to propagate the rejected promise.

**Comment by ThomasBurleson** [comment]
@matsko  - Reopening to investigate why Angular 1.4.x appears to interfere with transitionEnd events.

**Comment by petebacondarwin** [comment]
This line looks a bit "unusual":

https://github.com/angular/material/blob/d6a938e983690c229c1ee856c0416ae1832cffb4/src/core/services/interimElement/interimElement.js#L405

Am I wrong or are you assigning `true` to a promise (`showDone`) and then also rejecting the original promise. Later on you are creating a new promise that uses `$q.when(showDone)`. Depending upon when this gets called you could be getting the original promise here or `true`, right.

That seems quite convoluted.

**Comment by ThomasBurleson** [comment]
@petebacondarwin - That is some legacy code that should be cleaned...

The issue is the `show()` returns a promise... which can fail. But the `remove()` does not want to block on a **failed** show. Recently we updated the code to use a [`.finally()`](https://github.com/angular/material/blob/d6a938e983690c229c1ee856c0416ae1832cffb4/src/core/services/interimElement/interimElement.js#L415) handler, however:

```js
return removeDone = $q.when(showDone).finally(function() {
```
Which mean that we no longer have to **spoof** the show rejected promise.

**Comment by ThomasBurleson** [comment]
@petebacondarwin Per your thoughts and hints, I decided to refactor and fix our promise-chain logic: [Fixes to InterimElement and More Tests](https://github.com/angular/material/commit/eaa3324407799a600353b4f9bbc7ccf4ef2e2b37)

**Comment by Narretz** [comment]
@ThomasBurleson  Looks like this will be fixed by https://github.com/angular/material/pull/3949 right?

**Comment by Narretz** [comment]
I see your changes landed as https://github.com/angular/material/commit/d2a76c2bc1d9c077c6983adb102989c60d876be3. angular 1.4.4 is also released later today, so this will hopefully resolve this. I am tentatively going to close this issue then
