### ISSUE TITLE
Unused function $$AsyncCallbackProvider

### ISSUE THREAD

**Issue by alexlamsl** [angular/angular.js#12371]
After https://github.com/angular/angular.js/pull/12254 and https://github.com/angular/angular.js/issues/12251, `src/ng/asyncCallback.js` seems to contain only dead code

**Comment by mzgol** [comment]
D'oh, how did I miss that. Do you want to submit a PR?

**Comment by alexlamsl** [comment]
I don't have AngularJS codebase set up to do PRs properly, sorry.

Only spotted this whilst auditing the changes on `angular.js` between `1.4.2` & `1.4.3`

**Comment by lgalfaso** [comment]
@alexlamsl thanks for reporting this. A fix landed with 8ed6829

**Comment by alexlamsl** [comment]
I am not familiar enough with the build to be sure, but does [this line](https://github.com/angular/angular.js/blob/44ce9c8288fc6c12043567027271a09bd0594d74/angularFiles.js#L17) need to be removed as well?

**Comment by lgalfaso** [comment]
@alexlamsl you are right. Thanks!
