### ISSUE TITLE
Angular 1.4.x - ngMessagesInclude crashes

### ISSUE THREAD

**Issue by dmitriynosenko** [angular/angular.js#12389]
Hi, as far as I know this issue was fixed according to https://github.com/angular/angular.js/issues/11196.
Error is the same
`Error: [$compile:ctreq] Controller 'ngMessages', required by directive 'ngMessage', can't be found!`
But it still not working in ng-repeat and in form.
See example http://codepen.io/anon/pen/yNxJvL
Thanks

**Comment by lgalfaso** [comment]
I do not know if putting `ng-messages` and `ng-messages-include` at the same element is a supported configuration. Ping @matsko

**Comment by dmitriynosenko** [comment]
yes, seems like you right. I used layout from example and it works. Strange that it worked in prev versions and not now.
Anyway all works as expected.
