### ISSUE TITLE
angular.copy is not copying all properties in IE

### ISSUE THREAD

**Issue by saibotsivad** [angular/angular.js#12385]
In 1.2.x through 1.4.3 if you `angular.copy` an object containing properties that are numbers or number-like, in Internet Explorer (verified in 10 and 11 at least) these properties are not copied.

**Reproducable**: always
**Browsers**: IE 10, IE 11
**Operating system**: Windows 7

[Here is a JSFiddle](https://jsfiddle.net/6aqqgqnh/2/) that shows the problem, and I've copied the JS code here, since it's so short:

```js
var myRandomObject = { '1234': true };
var firstCopy = angular.copy(myRandomObject);
```

At this point, `firstCopy['1234']` should be true, as should `firstCopy.hasOwnProperty('1234')`, but in IE `hasOwnProperty` returns `false`.

Because of this, [since `angular.copy` uses `hasOwnProperty`](https://github.com/angular/angular.js/blob/master/src/Angular.js#L871), any following calls to `angular.copy` won't copy the object property, so that for:

```js
var secondCopy = angular.copy(firstCopy);
```

In Chrome and FF `secondCopy['1234']` is true, as expected, but in IE it is undefined.

**Comment by saibotsivad** [comment]
You can try this in IE 10/11, apart from Angular, to see that it's an IE issue:

```js
var copy = Object.create(Object.getPrototypeOf({ 5: true }));
copy[5] = true;
alert(copy.hasOwnProperty(5)); // should be true, but in IE is false
```

**Comment by saibotsivad** [comment]
I made a naive shim that overrides `Object.prototypy.hasOwnProperty` in the case where IE 

```js
(function() {
    var copy = Object.create(Object.getPrototypeOf({ 5: true }));
    copy[5] = true;
    if (!copy.hasOwnProperty(5)) {
        Object.prototype.hasOwnProperty = function hasOwnPropertyShim(propertyName) {
            return Object.getOwnPropertyNames(this).some(function(thisPropertyName) {
                return thisPropertyName == propertyName
            })
        }
    }
})();
```

Now if you run this code, it'll give you `true` as expected:

```js
var copy = Object.create(Object.getPrototypeOf({ 5: true }));
copy[5] = true;
console.log(copy.hasOwnProperty(5));
```

**Comment by lgalfaso** [comment]
Hi @saibotsivad, this is very interesting. I would recommend you to open a bug report for IE. Adding polyfill for IE broken implementation of `hasOwnProperty` feels outside of the scope.

@petebacondarwin WDYT?

**Comment by jbedard** [comment]
This might be the same as #11283 which was a temporary IE bug (which I've seen in IE10-11, not only 9 like the original bug says).

**Comment by saibotsivad** [comment]
I forgot to link to it here, but I filed a [bug with IE](https://connect.microsoft.com/IE/feedbackdetail/view/1570228/javascript-implementation-error-object-hasownproperty-returns-erroneous-results#tabs).

**Comment by saibotsivad** [comment]
@jbedard that looks like the bug, yep. :disappointed:

**Comment by jbedard** [comment]
I've run into it a few times when using VMs from http://modern.ie but found that it doesn't occur if windows is up to date. I think it was introduced in a windows update and fixed quite quickly, but some people (including the modern.ie VMs for a while) are stuck with the buggy version.

**Comment by saibotsivad** [comment]
@lgalfaso Adding polyfills like the naive one I wrote definitely sounds outside the scope of AngularJS, and after reading the link in the last comment of #11283, my naive approach was indeed very naive.

**Comment by saibotsivad** [comment]
I did indeed run this on the modern.ie VM, as I normally develop on a non-Windows machine. Our clients are running recent-ish versions of Windows/IE, so maybe that's why we've never heard anyone complain. *crosses fingers*

**Comment by petebacondarwin** [comment]
I just tried this on Win 8.1 with IE 11.0.9600.17905 (update versions 11.0.21 KB3065822) and this issue does not appear.

**Comment by lgalfaso** [comment]
With all the previous information, it looks like there is nothing else to be done. Closing.
