### ISSUE TITLE
Cannot make a regex to work

### ISSUE THREAD

**Issue by beastie1891** [angular/angular.js#12388]
Hey guys, I can't find any documentation regarding how regexes work in Angular and I'm currently struggling with the one I wrote.
I need to validate a SQL connection string (sort of) in a format instance_ip_or_dns\Instance_name:port

So I wrote this regex: 
controller:
$scope.regex = /[\\s]+\\[a-zA-Z]+[:][0-9]+{4}/ 

view:
<input type=text ng-pattern="regex" ....>

SyntaxError: nothing to repeat

$scope.regex=/[\\s]+\\[a-zA-Z]+[:]{1}[0-9]+{4}/;

What am I doing wrong?

**Comment by pkozlowski-opensource** [comment]
This has nothing to do with AngularJS, just try this in a regular JavaScript `var r =  /[\\s]+\\[a-zA-Z]+[:][0-9]+{4}/;` and you are going to see the same error.

As such this is a general support question and as such it should be asked using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by beastie1891** [comment]
Thanks.
