### ISSUE TITLE
attrs.$observe invoked callback if new and old values are undefined

### ISSUE THREAD

**Issue by katmai7** [angular/angular.js#12383]
attrs.$observe callback calls if new and old values are undefined, is it ok?

http://plnkr.co/edit/a8qD22?p=preview -- angular 1.4.1
http://plnkr.co/edit/xggx0p?p=preview -- angular 1.4.0

**Comment by petebacondarwin** [comment]
This is related to changes around the `$compile` initialization that we are trying to get to the bottom of in https://github.com/angular/angular.js/issues/12144 and https://github.com/angular/angular.js/pull/12290
