### ISSUE TITLE
$httpBackend mock should allow for testing that a particular request has not been made

### ISSUE THREAD

**Issue by mkhanal** [angular/angular.js#12399]
$httpBackend mock right now allows for 

```javascript
$httpBackend.expect***
```
as a matcher to assert that something has been called.

However, a negative matcher is missing. We need 
```javascript
$httpBackend.expectNone***
```
 or a similar method that allows us to EXPLICITLY assert that a specific request has not been made. Specially when we want a few requests to be made and exclude some.

This might mean change in $http.flush() method which currently throws error when no requests have been made at all. If this is a valid use case, an alternate behaviour might be set a flag instead of throwing an error as it does now.

**Comment by lgalfaso** [comment]
This looks like an interesting proposal. A PR would be mostly welcome

**Comment by mkhanal** [comment]
Will work on it over this weekend :)

**Comment by KostyaDanovsky** [comment]
Hey guys, I have started work on this issue, but I faced with kind a bug

```javascript
it("should not throw an exception if only one function expected", function() {
  $httpBackend.expect('GET', '/some1', null).respond(200, '', {});
  expect(function() {
    $httpBackend('GET', '/some1', null, noop, {});
    $httpBackend('GET', '/some2', null, noop, {});
  }).not.toThrow();
});
```

And this test fails. As for me this is not expected behaviour.

So for now if we want to test a function we should enumerate all called functions of *$httpBackend* mock in strict sequence. In other case this test will fail. Also *expectNone* function doesn't have a lot of sense for now, because if we just skip *expect* for not called function it will mean *expectNone*.

**Comment by mkhanal** [comment]
@KostyaDanovsky 
I'm trying to understand this. The test only expects call to '/some1' url; however, the code makes a call to '/some2' as well. 
So the second call should fail hence failing the test.

Why do you think think this test should not fail ?

**Comment by KostyaDanovsky** [comment]
@mkhanal 
I thought that $httpBackend mock works like in other test frameworks, but it doesn't.
As for now we MUST define responses for all mock calls to pass the test.

```javascript
     it("should not throw an exception if only one function expected", function() {
        $httpBackend.when('GET', '/some1', null).respond(200, '', {});
        $httpBackend.when('GET', '/some2', null).respond(200, '', {});

        $httpBackend.expect('GET', '/some1', null);

        expect(function() {
          $httpBackend('GET', '/some1', null, noop, {});
          $httpBackend('GET', '/some2', null, noop, {});
        }).not.toThrow();
      });
```

This test passes, but what the difference with the previous example? That we define responses for two calls, but we expect only one.

Anyway it's ok how it works now, but for me it was strange a little.

**Comment by mkhanal** [comment]
The difference between the two is that on the first test you did not have 
```javascript
  $httpBackend.when('GET', '/some2', null).respond(200, '', {});
```
And you still called this URL

Angular $httpBackend is meant to be used to mock out a backend during tests. Angular does not pass it through to the real http provider, it does not know what to do with it and then tell you that you have not mocked it. However, if you're using the ngMockE2E module, you can explicitly choose to forward it to the real API using passThrough().

**Comment by petebacondarwin** [comment]
@mkhanal is right here. We don't have `expectNONE` or similar because the mock `$httpBackend` will throw an error if you have not provided a response for a URL that is requested, which ensures that we are not making unexpected requests.
