### ISSUE TITLE
Angular 1.4.x - Dropdown binding issue

### ISSUE THREAD

**Issue by SuperBiscotte** [angular/angular.js#12390]
Hi ! I've nearly the same issue as the #11890, but in my case i bind directly on a string. Moreover, sometimes the value is correctly bind, sometimes it isn't - I can't reproduce it everytime ! My select's options are hard coded (don't use ng-options) and the code is as simple as this plunker http://plnkr.co/edit/k09Xh9xEgcXQBbKTkRdh?p=preview, except i retrieve my datas from a service.
I already tried $scope.$apply, $timeout, setTimeout,.. None of this solution works for me

**Comment by pkozlowski-opensource** [comment]
@SuperBiscotte 2 remarks:
* you are using quite an old version of 1.4.x line - please re-test with the latest release
* I can't reproduce with the attached plunker either.... I'm afraid you will have to narrow it down a bit more - we can't fix bugs that we can't reproduce....

**Comment by SuperBiscotte** [comment]
I use Angular v1.4.0-rc.2 and that's my problem, i can't even reproduce it...

**Comment by Narretz** [comment]
If you cannot reproduce it, we cannot do anything about it infortunately. Please reopen this issue if you have a reduction.
