### ISSUE TITLE
[ngResource] should initialise `data` when response data is array

### ISSUE THREAD

**Issue by itsmechlark** [angular/angular.js#12391]
[ngResource#L557](https://github.com/angular/angular.js/blob/v1.4.3/src/ngResource/resource.js#L557), causes error when action is array and accessing from an instance.

```coffee
product = $resource "/v1/products/:id", {},
    years:
      url: "/v1/products/:id/years"
      isArray: true

product = Product.get id: 1, ->
    product.$years()
```

Another problem also is that `:id` is not set and you still need to:
```coffee
product.$years(id: product.id)
```

Is this correct?

**Comment by pkozlowski-opensource** [comment]
@itsmechlark it is not very clear what your problems is... Could you please provide a minimal reproduce scenario using http://plnkr.co/ or similar?

**Comment by itsmechlark** [comment]
@pkozlowski-opensource, here is the scenario http://embed.plnkr.co/CHVzHB/preview.

**Comment by itsmechlark** [comment]
Error raise `TypeError: value.push is not a function` at [ngResource#L598](https://github.com/angular/angular.js/blob/v1.4.3/src/ngResource/resource.js#L598)

**Comment by pkozlowski-opensource** [comment]
@itsmechlark ngResource is there to work with RESTful endpoints, but you seem to be trying to use it as a generic backend-access method. Specifically, ngResource works with collections containing objects, so returning `[2015, 2014, 2013]` doesn't make much sense. You would be probably better off using $http here.
