### ISSUE TITLE
make $compile accept DDO without a factory

### ISSUE THREAD

**Issue by Jandalf** [angular/angular.js#12397]
could we add the possibility to define a directive without a factory. this would only be syntactic sugar and I could make a PR for this. This would make the creation of directives easier for beginners.

```
angular.module('sample', []).directive('test', {
    template: 'Hello World!'
});
```

**Comment by Narretz** [comment]
Thanks for your suggestion. In my opinion, this is not something really needed. Just another way to do something. Also, it's a golden opportunity for beginners to learn what a factory is. On a side note, we have the angular.component helper lined up for 1.5, which will help create "idiomatic components" for angular 1 (also good for migration to ng2): #12166

**Comment by petebacondarwin** [comment]
We now have the `component` helper in master for these simple cases.
