### ISSUE TITLE
Cannot change properties in mocked $window.navigator

### ISSUE THREAD

**Issue by davidlmiller21** [angular/angular.js#12394]
When I'm running tests that have to do with changes in $window.navigator, I'm trying to simulate these changes by doing something such as `$window.navigator.onLine = true;`, but that has no effect as the property is still `false`. Understandably modifying readonly `$window` properties should not be possible in production when using AngularJS, but for testing purposes it seems necessary to be able to modify the mocked `$window` object to truly verify the functionality of the code interacting with these services.

**Comment by davidlmiller21** [comment]
Also, is it possible for this change to accordingly trigger the `online` and `offline` events if this is implemented?

**Comment by davidlmiller21** [comment]
@lgalfaso @petebacondarwin @gkalpak is this something that is already possible or does it need to be added into AngularJS's mock?

**Comment by gkalpak** [comment]
I don't think there is a mocked window object in AngularMock (it doesn't need to be), but you are free to mock it out as needed.
I don't think it is useful (or at all possible), to mock everything on `window` and it would be an unnecessary overhead for the majority of tests that don't need it. The current behaviour (allowing `$window` to be mocked) is lightweight and flexible enough to cover the needs.
(That's one of the major points about DI - being able to easily mock ddependencies out (be it for testing or elsewhere).)

Here is a [simple demo][1], mocking out `$window.navigator`.

[1]: http://codepen.io/ExpertSystem/pen/yNQeBm?editors=001

**Comment by petebacondarwin** [comment]
@davidlmiller21 There is a decent mock window object used in out `$location` tests if you want to use it as a starting point for mocks in your own applications: https://github.com/angular/angular.js/blob/master/test/ng/locationSpec.js#L2533-L2570

**Comment by davidlmiller21** [comment]
Thanks for the help.  Fixed it.
