### ISSUE TITLE
Can't call controller function in controller config

### ISSUE THREAD

**Issue by mohsinrs** [angular/angular.js#12403]
I am using textAngular editor in my AngularJS project. I have added custom button in toolbar using taRegisterTool. How to call function defined in controller on click of this button:

angular.module('minovateApp').controller('MainCtrl', function ($scope, $http, $rootScope, $timeout,     $filter, $window, $location, $modal, trafficCop) {
           var modalInstance;
            $scope.openPopup = function (tempUrl, popupController, params) {

                modalInstance = $modal.open({
                    templateUrl: tempUrl,
                    controller: popupController,
                    size: 'lg',
                    resolve: {
                        items: function () {
                            return params;
                        }
                    }
                });

                modalInstance.result.then(function (selectedItem) {
                    $scope.selected = selectedItem;
                }, function () {
                    // $log.info('Modal dismissed at: ' + new Date());
                });
            };
          })
        .config(function($provide){
                // this demonstrates how to register a new tool and add it to the default toolbar
                console.log($provide);
                $provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions){ // $delegate is the taOptions we are decorating
                        taRegisterTool('mergeCode', {
                            buttontext: 'Merge Code',
                            action: function(){                                
                                $provide.openPopup('views/tmpl/user/widgets/popup_widgets.html', 'WidgetsController');
                            }
                        });
                        taOptions.toolbar[1].push('mergeCode');
                        return taOptions;
                    }]);
        });

**Comment by Narretz** [comment]
This looks like a question for textAngular, no? This repo is for angular.js core only.
