### ISSUE TITLE
ngAnimate's new reflow system forgets to run a reflow for parentless animations

### ISSUE THREAD

**Issue by matsko** [angular/angular.js#12400]
Turns out that if we don't have a parent, class-based animation waiting on some elements then a reflow isn't run directly after postDigest.

http://plnkr.co/edit/19zd2RYTRaCxAymbwxkv?p=preview

This PR fixes it: https://github.com/angular/angular.js/pull/12401

**Comment by petebacondarwin** [comment]
@matsko - sorry, I can't see what the issue is in that Plunker. What is supposed to happen?
