### ISSUE TITLE
$location.state()

### ISSUE THREAD

**Issue by unique-vv** [angular/angular.js#12404]
when I called $location.state() like this:
```CoffeeScript
$location.state
  cellPhone: $scope.cellPhone
```
the browser throwed an error:
```
Error: [$location:nostate] History API state support is available only in HTML5 mode and only in browsers supporting HTML5 History API
```
my browser is Safari (Version 8.0.7)
the Plunker address: [$location.state() error](http://plnkr.co/edit/sasxvoJJXWegxpA4nr0F?p=preview)

**Comment by rmdias** [comment]
Hey @unique-vv 

Do you already tried use `$locationProvider.html5Mode(true);` ?

I used it here and now, it's working.

Fell free to look this -> https://docs.angularjs.org/error/$location/nostate

**Comment by unique-vv** [comment]
@rmdias thanks very much for teaching me!
