### ISSUE TITLE
cg-busy not working 

### ISSUE THREAD

**Issue by LaxmiSingh** [angular/angular.js#12413]
I am using angular js's 1.4.3 version and angular-animate's 1.2.16 version.
The problem is cg-busy is not working with these files.

**Comment by pkozlowski-opensource** [comment]
@LaxmiSingh I'm not sure what `cg-busy` is, but it sounds like a 3rd party directive (https://github.com/cgross/angular-busy ?). If this is the case you should file the issue in the respective repository. We can't fix cg-busy on our side. If the author of this directive believes that there is un-documented breaking change in AngularJS 1.4.x then he should file an issue with more details.

Closing as non-actionable.

**Comment by gkalpak** [comment]
As a sidenote, using different versions for angular and angular-animate is not supported (and won't end up well...).
