### ISSUE TITLE
Angular 1.2.6: form auto-complete on IE9 does not work  

### ISSUE THREAD

**Issue by bitliner** [angular/angular.js#12420]
I am using angular 1.2.6 . 
Browser is IE9.

My login form is inside an angularJS view.

On Chrome username and password are autoamtically filled inside the form.

On IE9 there is no same behaviour.

Of course, I enabled the options for IE9 to let it store username and password.

**Comment by bitliner** [comment]
Actually I made it work but the problem is that it just auto-filles the input text, but then the fields looks still empty.

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular.js/issues/1460

**Comment by bitliner** [comment]
Ok, I used this plugin https://github.com/tbosch/autofill-event and it works.
