### ISSUE TITLE
ES2015 syntax results in TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by OlsonDev** [angular/angular.js#12424]
I put together [this plunk](http://plnkr.co/edit/09uiBvV5CUV82Tk3fH8v?p=preview) to demonstrate the issue.

The issue itself (I'm reasonably sure) is the dependency annotator doesn't understand [ES2015 syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_6) for shorthand method names even though the browser does (Chrome v43.0.2357.134 m, Windows 10).

The weird thing is it only matters for the `controller` key, best I can tell. If I use the same syntax for the `link` key, the `TypeError` doesn't happen and `$scope` is successfully injected.

Here's the full stack trace:
```
TypeError: Cannot read property '1' of null
    at Function.annotate (angular.js:3725)
    at Object.invoke (angular.js:4428)
    at $get.extend.instance (angular.js:8999)
    at nodeLinkFn (angular.js:8109)
    at compositeLinkFn (angular.js:7541)
    at compositeLinkFn (angular.js:7545)
    at compositeLinkFn (angular.js:7545)
    at publicLinkFn (angular.js:7416)
    at angular.js:1635
    at Scope.$get.Scope.$eval (angular.js:15846)
```

**Comment by lgalfaso** [comment]
#12425 should take care of this

**Comment by OlsonDev** [comment]
Awesome. Thanks!

**Comment by jmls** [comment]
I have this codepen which _sometimes_ gives this error, using 1.5.5 of angular

http://codepen.io/anon/pen/ONwMGg?editors=1011

make a change (like a space) and the console sometimes shows the "Cannot read property '1' of null" error. 

You may have to try a few times - sometimes the error happens _all_ the time, and then sometimes you have to make several changes before you see it

**Comment by gkalpak** [comment]
This is because of some Chrome v50 weirdness. It's tracked in #14487.

**Comment by jmls** [comment]
ah, thanks. I did indeed upgrade to v50 ... :(
