### ISSUE TITLE
Make $cookies.get() to take options in to account

### ISSUE THREAD

**Issue by bogdanalexe90** [angular/angular.js#12423]
It will be very useful to read cookies for a provided options to be consistent with put() and remove().

The use case for this:
* Let's say you register a cookie for .domain.com;
* Some one else create a cookie for x.domain.com
* If you try to read the registered cookie, you receive the one for x.domain.com

This come from the ```$$cookieReader```:

```js
for (i = 0; i < cookieArray.length; i++) {
        cookie = cookieArray[i];
        index = cookie.indexOf('=');
        if (index > 0) { //ignore nameless cookies
          name = safeDecodeURIComponent(cookie.substring(0, index));
          // the first value that is seen for a cookie is the most
          // specific one.  values for the same cookie name that
          // follow are for less specific paths.
          if (lastCookies[name] === undefined) {
            lastCookies[name] = safeDecodeURIComponent(cookie.substring(index + 1));
          }
        }
      }
```

**Comment by lgalfaso** [comment]
The cookie metadata like path, domain and expires are not visible in JavaScript. What this is asking is simply not possible.

**Comment by bogdanalexe90** [comment]
Right. So no option to workaround this scenario.

**Comment by lgalfaso** [comment]
@bogdanalexe90 no unless this information is exposed by the browser. BTW, this information is not sent to the server either
