### ISSUE TITLE
Transcluded directive is not rerendered on parent model update

### ISSUE THREAD

**Issue by ameteiko** [angular/angular.js#12422]
While working on an project, my colleagues and I faced an issue with transcluded directives.

A `parentDirective` contains a directive  with transclusion enabled (`transcludeDirective`). The latter has another directive, `innerDirective`, which contains reference to parent model `item.color`. When the parent model `item` is updated, `innerDirective` still has the old value of `item.color`.

We came up with two possible solutions. Either removing `transcludeDirective`, which is not a solution in our case, or manually set model with empty object on `parentDirective` initialization, which seems to be unnecessary.

Please see following jsbin:
https://jsbin.com/siwoje/2/edit?html,js,output

Thank you.

**Comment by lgalfaso** [comment]
This is just a more elaborated version of the following (warning, there might be typos):
1/ Create a parent scope and a child non-isolated scope.
2/ In the child scope execute `childScope.$eval("foo.bar = 1")`
3/ In the parent scope execute `parentScope.$eval("foo = {}")`

In this case, `parentScope.foo.bar !== 1`.
Swapping (2) and (3) will cause that `parentScope.foo.bar === 1`

This is the intended behavior.

I recommend that you read https://github.com/angular/angular.js/wiki/Understanding-Scopes it is somehow outdated but still relevant.
