### ISSUE TITLE
Array can't hold duplicates ??

### ISSUE THREAD

**Issue by kvneswar** [angular/angular.js#12432]
Why the following code is not working ?? Array can't hold duplicate values ??

http://plnkr.co/edit/ooJJPv?p=options

<html ng-app="AngularApp">
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
    <script>
      var app=angular.module('AngularApp', []);
      app.controller('myController', function($scope){
       
        $scope.names = ['John', 'John'];
      
        
      });
    </script>
  </head>
  
  <body ng-controller="myController">
    
    
    <ul>
      <li ng-repeat="name in names">
        {{ name }}
      </li>
    </ul>
    
  
    
  </body>
</html>

**Comment by caitp** [comment]
you need to use a "track by" expression to make this work (eg "track by $index" in http://plnkr.co/edit/rENcz72qVyRmKVW7wwj3?p=preview). This is covered in the documentation for ngRepeat.
