### ISSUE TITLE
Latest Chrome update 44.0.2403.107 adds a delay on buttons/links

### ISSUE THREAD

**Issue by napcat** [angular/angular.js#12435]
Does anyone have problems with the latest chrome update?

I'm with the chrome latest version 44.0.2403.107 m (64-bit).

I'm developing one app that uses angularjs and this framework http://mobileangularui.com/

My app started to have some strange issues on href and ui-sref and they are driving nuts!!

If a link is clicked the other links will be unavailable for a few seconds. I need to leave the button area with the mouse or click more than one time so the link could work again. It's like there's some kind of lag or delays.

This can be noticed with the basic demo page:
http://mobileangularui.com/demo
   . Just put the browser small enough to have the "hamburger" button and call the side menu.

   . Then click on the "hamburger" and click on a link on the open side menu.

   . Go again to the "hamburguer" button, you will notice the button has not correct mouse icon when you over it.
   . You will need to click more than one time or move the mouse a few times along the button so it can work again.

If this does not happen on the first time, just try a few more times the same steps described above.

It works good on version of Chrome 43.x.x and on latest version of Firefox and IE.
It does not work properly on Chrome 44.0.2403.107 and above (also tested on 46.0.2463.0 canary version).

Can someone point me to a possible cause?

Thank you!

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem); these types of questions are ill-suited for GitHub. Thanks!

If you are having issues with an external project, please keep questions in that project
