### ISSUE TITLE
How to place caret to end upon focus?

### ISSUE THREAD

**Issue by binarykitchen** [angular/angular.js#12438]
How can I place the caret position to the end whenever the text input gains focus?

This the most easiest way without too many hacks. Had a look around but couldn't find anything that simple.

**Comment by lgalfaso** [comment]
Please read the [contributing guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem); these types of questions are ill-suited for GitHub. Thanks!

**Comment by binarykitchen** [comment]
Ok, sorry, moved this to StackOverflow:
http://stackoverflow.com/questions/31663764/angularjs-how-to-place-caret-to-end-upon-focus
