### ISSUE TITLE
ngInit and controlerAs Syntax

### ISSUE THREAD

**Issue by victorherraiz** [angular/angular.js#12433]
Could it be posible to add the following example to the docs for a valid usage of ngInit? 

```html
<!-- assuming we are using 'controller as' -->
<div ng-repeat="contact in ctrl.contacts"
     ng-controller="contactController as contactCtrl"
     ng-init="contactCtrl.setContact(contact)">
  <!-- some bits of complex DOM here -->
</div>
```
from: http://www.technofattie.com/2015/03/02/nested-controllers-and-shared-data-in-angular.html

This solves the problem of sharing data in nested controllers with controllerAs syntax

**Comment by wesleycho** [comment]
Creating a custom directive that encapsulates that template and another one for each repeated element would be better component design, instead of using ng-controller and ng-init there.

**Comment by victorherraiz** [comment]
Using a directive is fine when it is going to be reuse elsewhere, but if the code belongs only to that view and that context a controller should be enough in my opinion.

**Comment by wesleycho** [comment]
This would encourage a bad practice IMO - I also disagree, even for a one-off component. By putting a controller on the ng-repeat, it is not necessarily obvious to a user that a controller will be instantiated for each element in the repeater.

By creating a custom directive, one would have a natural initializer with the linking function, leading to cleaner HTML with more modularity.

**Comment by Narretz** [comment]
I agree with @wesleycho , this is not something we want to encourage.
