### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by deadmann** [angular/angular.js#12442]
it's kinda good that switch should take direct value, but there are also cases that it is in fault...

Ex.
i have a Scope Variable:

    $scope.WindowType={
        'Users' : 0,
        'Chat'   : 1,
        ...
    }
    $scope.MyModel ={
                ...
                Sections       : {
                    ...
                    SwitchWindow : $scope.WindowType.Chat,
                }
    }

In here, there are three issue,...
1. Readability is low : <div data-ng-switch-when="0">
2. You can't remember the conditions for life time: 
3. Changing Model Cause System Failure...

So i'm wonder if you provide ng-switch with another bind-able directive, or attribute.

**Comment by deadmann** [comment]
I don't know which version of angular i have, but i hope see it in next nuGet package i fetch from server...

i fix it by creating this directive:

    var ngSwitchWhenBindDirective = ngDirective({
        transclude: 'element',
        priority: 1200,
        require: '^ngSwitch',
        multiElement: true,
        link: function (scope, element, attrs, ctrl, $transclude) {
            ctrl.cases['!' + scope.$eval(attrs.ngSwitchWhenBind)] = (ctrl.cases['!' + scope.$eval(attrs.ngSwitchWhenBind)] || []);
            ctrl.cases['!' + scope.$eval(attrs.ngSwitchWhenBind)].push({ transclude: $transclude, element: element });
        }
    });

So older project can continue working...

**Comment by lgalfaso** [comment]
This was discussed and this is not something for the core.
