### ISSUE TITLE
Incorrect da-DK time format

### ISSUE THREAD

**Issue by tinwaisi** [angular/angular.js#12445]
In angular-locale_da-dk.js, the time format should use ":" instead of "." Both mediumTime and shortTime are incorrect. 

Current format:
    "fullDate": "EEEE 'den' d. MMMM y",
    "longDate": "d. MMMM y",
    "medium": "dd/MM/y HH.mm.ss",
    "mediumDate": "dd/MM/y",
    **"mediumTime": "HH.mm.ss"**,
    "short": "dd/MM/yy HH.mm",
    "shortDate": "dd/MM/yy",
    **"shortTime": "HH.mm"**

**Comment by pkozlowski-opensource** [comment]
@tinwaisi please check the localisation issues section in https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#issue

**Comment by wesleycho** [comment]
This should probably be filed with Google Closure - see [here](https://github.com/google/closure-library/wiki/Internationalization-%28i18n%29-changes-in-Closure-Library).

Probably safe to close this as a Closure issue.

**Comment by Narretz** [comment]
Thanks @wesleycho , yes this must be changed here: http://cldr.unicode.org/ (from which closure generates its locale files)
