### ISSUE TITLE
Angular ng-repeat animation transition not working with `ie10`

### ISSUE THREAD

**Issue by 3gwebtrain** [angular/angular.js#12448]
Any expert to help to answering this question:

http://stackoverflow.com/questions/31659373/angular-ng-repeat-animation-transition-not-working-with-ie10

**Comment by Narretz** [comment]
Sorry, usage questions are not in the scope of the github issues, see https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
