### ISSUE TITLE
feat: create noop controller implicitly when controllerAs is used 

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular.js#12441]
Nowadays, it's a best practice to use `controllerAs` whenever possible in our Angular apps. This is true for routing, as well as directives. In addition to that, since 1.4, `bindToController` allows us to specify how properties are bound to the controller, instead of defining them on the scope.

I think this is really awesome, because it encourages developers to use controller in directives, where we'd normally use link. However, there's a tiny little usability problem:

It often happens, that we create directives, that don't really have controller logic, but they do use `controllerAs` in order to follow the best practice. Such a directive could look something like this

```js
app.directive('foo', function () {
  return {
    restrict: 'E',
    scope: {},
    bindToController: {
      prop1: '='
    },
    controller: function () {

    },
    controllerAs: 'ctrl'
  };
});
```

This totally does it's job. However, it turns out that the controller really does nothing. So i'd like to omit it. Doing that will throw an error, because `controller` is undefined, which is why we can't use it like that.

I basically want to be able to use controller as syntax, without specifying a controller in case there's no functionality in it anyways. Maybe angular can use `angular.noop` as a fallback, in case `controllerAs` is specified?

**Comment by Narretz** [comment]
You can do `controller: angular.noop`, and that has the added benefit of being explicit, yet still very succinct. Since I'm a fan of being explicit, I don't really want the compiler to handle this.

**Comment by Narretz** [comment]
We've decided that because of the new module.component helper (https://docs.angularjs.org/api/ng/type/angular.Module#component), this feature will not land, see https://github.com/angular/angular.js/issues/9774#issuecomment-152334369
