### ISSUE TITLE
$watch doesn't trigger inside directive when a radio-input changes value

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular.js#12450]
I have a set if radio-inputs defined like this:
```
<input type="radio" ng-model="range" value="date">
<input type="radio" ng-model="range" value="age">
```
If we try to set up separate watches for the values in `range` inside the view's controller:
```javascript
$scope.$watch("range=='date'", function (val) {
    // triggers always when the value changes.
});
$scope.$watch("range=='age'", function (val) {
    // triggers always when the value changes.
});
```
 -they both work exactly as expected.

However, if we try to do the same from inside a directive, the $watch is triggered only when the condition is satisfied, i.e. `true`. But when the value is `false`, $watch isn't triggered.

Angular version being used: 1.3.17.

**Comment by vitaly-t** [comment]
Found out it was somehow related to where the directive was placed in the document. Dunno know, because where it was sitting, it wasn't behind `ng-if`. But moving it out to a level up somehow fixed the issue, it now receives $watch update as expected. This is quite strange...

**Comment by Narretz** [comment]
Hi, unproducible issues are not really actionable. If you can provide a reproduction, please reopen this issue. Thanks!

**Comment by gkalpak** [comment]
It was obviously a scope/JS prototypal inheritance (no dot in ng-model) issue.
