### ISSUE TITLE
Indeterminate ngModel behavior when updateOn is blur

### ISSUE THREAD

**Issue by robmazan** [angular/angular.js#12455]
The example for the issue described here can be checked on [CodePen](http://codepen.io/robmazan/pen/MwzjEa?editors=101).

Let's assume you have the following setup:

  - An input field with `ngModel` on it, having `ng-model-options="{updateOn: 'blur'}"`
  - A button with `ngClick` on it, where the handler function using the value of the model from scope

Executing the following steps has different results on mouse and on touch devices:

  - Edit the input value
  - Click on the button directly (without clicking anywhere else first)

With mouse based input the `ngClick` handler can access the current input value on scope, and it is the same value that you can see in the input field.

On touch devices however, when the `ngClick` handler is executed the value is not updated yet (see the CodePen example with Chrome DevTools device emulation to see it happening).

**Comment by Narretz** [comment]
It looks like ngTouch is to blame, as the touchdown happens before the blur, and ngTouch will evaluate the ngClick expression before the blur happens. We are currently evaluating if we will deprecate ngTouch, so it might be a good idea for you to switch to fastclick.js / hammer.js.

In your specific example, this should also work: http://codepen.io/anon/pen/KpEMNW?editors=101

**Comment by robmazan** [comment]
> We are currently evaluating if we will deprecate ngTouch

@Narretz What are the chances? :)

We have a quite big code base here, and I would only suggest this transition to our client if it is a future proof one.
