### ISSUE TITLE
One way binding being updated inside ngSwitch/ngIf (edited)

### ISSUE THREAD

**Issue by levin81** [angular/angular.js#12456]
Hi,

I don't know if this is an issue or not - but the behavior is confusing. When using "::" inside a directive template it seems as if the binding is still being updated. Code here:

http://plnkr.co/edit/tbC3Ji6122gdqt4XbZpI?p=preview

To reproduce:
1. Enter value into top text field -> value inside directive updates for the first time.
2. Click "edit", enter new value and then click "copy".
3. Value inside [ ] is updated and will continue to update each time it is edited.

Even when adding the "::" prefix to the directive (``<my-directive obj="::t"></my-directive>``) the value inside ``{{ ::obj.value }}`` will continue to update each time.

**Comment by levin81** [comment]
Updating this issue as it seems it is more a documentation problem (or perhaps could be solved in code to be straightforward?).

http://stackoverflow.com/questions/31680779/one-time-binding-not-working-inside-custom-angular-directive/31685507

Seems that ``ngSwitch``/``ngIf`` cause one way bindings ``::`` to interpolate regardless. I've gone over the documentation on angularjs.org (https://docs.angularjs.org/guide/expression) to make sure I've understood it correctly and there is nothing that shows that these two features should not "play nicely" (at least, when only reading this part of the guide).

So please decide whether they should work together regardless of removing and adding back to the DOM, or whether the documentation needs to be revised. Thanks!

**Comment by lgalfaso** [comment]
Thanks for opening this issue. The current behavior is the expected behavior, and I think that the current behavior is the one that makes these two directives "play nice" with each other.
If you would like to create a PR with some documentation changes, please feel free to do so, but I do not think there is anything actionable here. Closing.
