### ISSUE TITLE
Long $templateCache loading time in components with many inherit views.

### ISSUE THREAD

**Issue by xmityaz** [angular/angular.js#12461]
I have a page that has a lot of inheriting views. 
For first time user redirecting to the page (views not in the cache) state is changing and user can see a loading spinner. All views are uploading from the server, even if ' ng-if="false" ' for them.
For next redirecting to the same page (views already in the cache) state is changing and there is delay about 2 seconds before user can see a spinner or any other reaction for his action.

Is there any workaround for this issue? To make $templateCache lazy loading, and load the view in case if ' ng-if="true" ' for example?

**Comment by realityking** [comment]
Good timing, in #12078 they're working on a solution for this problem.

**Comment by Narretz** [comment]
Are you loading the templates from the server via ajax? If so, you can try putting the templates inside the templateCache when you build your app, see e.g. https://github.com/karlgoldstein/grunt-html2js

**Comment by xmityaz** [comment]
@Narretz I actually do the same with https://www.npmjs.com/package/grunt-angular-templates.
I'm loading templates via Ajax just for dev version

**Comment by Narretz** [comment]
Looks like the lazy compilation of transcluded elements has fixed this.
