### ISSUE TITLE
translated text & $sanitize on utf-8 title

### ISSUE THREAD

**Issue by eidng8** [angular/angular.js#12460]
Not sure if I should ask here, but it seems more like an Angular issue, so I try it here.

I've got a translation setup as:

```javascript
$translateProvider.preferredLanguage("zh");
$translateProvider.useSanitizeValueStrategy("sanitize");
```

and a language json:

```json
{
    "something": ".....",
    "title": "旅客",
    "othermore": "....."
}
```

and then the ion-view:

```html
<ion-view view-title="{{ 'title' | translate }}">
    <!-- view content here -->
</ion-view>
```

The view got rendered and shown correctly on page:

```html
<ion-view view-title="&#26053;&#23458;" some-other-attr="some values">
    <!-- view content here -->
</ion-view>
```

However, when I view it on the Mac Chrome browser, I see the page (tab) title shows `&#26053;&#23458;`, instead of the characters `旅客`.

Then I check the `<title>` tag in `<head>`, it is:

```html
<title>&#26053;&#23458;</title>
```

I realize that $sanitize doesn't do it wrong with the `view-title` attribute. But the `<title>` tag content shouldn't be escaped, right?

Am I doing it wrong?

**Comment by Narretz** [comment]
Does it only happen in Mac Chrome? If not, it's probably a browser bug.

**Comment by eidng8** [comment]
Tried on Windows 7 x64 with Chrome, Firefox, & IE, all the same. Aside from the title, I've just noticed that `<input placeholder=""/>` also suffers from the same issue.

For the moment, as a work around, I've switched to 

```javascript
$translateProvider.useSanitizeValueStrategy("escape");
```

**Comment by lgalfaso** [comment]
Would it be possible to have a minimal plunker that shows the error?

**Comment by eidng8** [comment]
view template
```html
<!-- playlists.html -->
<ion-view view-title="{{ 'failed' | translate }}">
  <ion-content><h1>{{ 'failed' | translate }}</h1>
    <ion-list>
      <ion-item ng-repeat="playlist in posts" href=#/app/posts/{{playlist.id}}>
        {{playlist.title}}
      </ion-item>
    </ion-list>
  </ion-content>
</ion-view>
```

js fragment
```javascript
.config(["$stateProvider", "$urlRouterProvider", "$translateProvider",
($stateProvider, $urlRouterProvider, $translateProvider) =>
{
  $translateProvider.preferredLanguage(browserLanguage());
  $translateProvider.fallbackLanguage(fallbackLanguage);
  // $translateProvider.useSanitizeValueStrategy("escape");
  $translateProvider.useSanitizeValueStrategy("sanitize");
  $translateProvider.useStaticFilesLoader({prefix: "lang/", suffix: ".json"});

  // ......

  .state("app.playlists", {
    url: "/playlists",
    views: {
      menuContent: {
        templateUrl: "templates/playlists.html",
        controller: () => {}
      }
    }

  // ......
}
```

lang fragment
```json
{
  // ......
  "failed": "失败了.",
  // ......
}
```

output:
......
![6 yp7aln5 d7nrqet dykar](https://cloud.githubusercontent.com/assets/787265/9157952/15280c36-3f41-11e5-859d-939885e743d3.png)
......
![t f3 vqt2nq51qzpd zlcvm](https://cloud.githubusercontent.com/assets/787265/9157955/3a3383a2-3f41-11e5-8f2c-0c8408e27195.png)
and gets
![p0 dl0c b0 p fp40_z6](https://cloud.githubusercontent.com/assets/787265/9157965/645a6402-3f41-11e5-8ea4-86e8858dc321.png)

It's just extracted from our project code and organized a bit into the side menu starter project. I've just slightly tested the setup a bit, not guaranteed to work :smirk_cat: 

If you need anything, just let me know.

**Comment by lgalfaso** [comment]
Any chance you can create a plunker?

**Comment by eidng8** [comment]
sorry for the late, finally got it setup:

http://plnkr.co/edit/mQiWvt?p=preview

The `<title>` tag can't be checked in plunker, so I've put up a `<input placeholder/>` on top of the `playlists` list, in `playlists.html`.

P.S. I've checked before while trying to look into this issue. It seems that doesn't matter if I use `{{ 'some' | translate }}` or `translate` & `translate-attr-xxxx` attributes.

**Comment by lgalfaso** [comment]
I do not know enough about angular-translate to know if the issue is in their library or if the issue is in how you are using. Anyhow, the root of the problem is that in angular-tranlate at line 2405 they are setting the sanitize mode to `text` and then using the literal after html escaping and setting an attribute with the content at line 2706

One way or another, the issue is not in angular core
