### ISSUE TITLE
Simple ng-show not working

### ISSUE THREAD

**Issue by valentincocaud** [angular/angular.js#12467]
Hello, I'm making a very simple application:

I want to load an array via ajax call, then display it. During the loading time, I want an animated gif.

    <!DOCTYPE html>
    <html ng-app="thresholdApp">
    <head lang="fr">
        <script src="/lib/angular.min.js"></script>
        <script src="/bin/js/thresholds/angular/controller/controller.js"></script>
        <script src="/bin/js/thresholds/angular/service/webservice.js"></script>
    </head>
    <body ng-controller="thresholdCtrl as ctrl" class="text-center">
        <div class="row">
            <div class="column small-6 small-centered">
                <table>
                        <tr ng-show="loading">
                            <td colspan="3" class="text-center">
                                <img src="/res/img/greyLoadingWheel.gif" alt="loading"/>
                                {{loading}}
                            </td>
                        </tr>
                        <tr ng-repeat="t in thresholds">
                            <td>{{t.brand.name}}</td>
                            <td class="text-center">{{t.stock}}</td>
                            <td class="text-center">{{t.threshold}}</td>
                        </tr>
                </table>
            </div>
        </div>
    </body>
    </html>

With that controller :

	thresholdApp = angular.module "thresholdApp", []
	
	thresholdApp.controller "thresholdCtrl", ($scope, webService) ->
	
		$scope.loading = false
	
		webService.post "stock/threshold/check", {}, (result) ->
			$scope.thresholds = result.stockThresholds
			$scope.loading = false

It works well, the table is filled with the ajax response as expected but the tr with the ng-show directive don't work. The weird thing is that in the other hand, {{loading}} is well updated and is replace by false.

Any idea ?

**Comment by ericmdantas** [comment]
Shouldn't you set it to true somewhere? Like in:

```js
$scope.loading = true

webService
     .post("stock/threshold/check", {})
     .then(result => {
          $scope.thresholds = result.stockThresholds          
     })
     .finally(_ => $scope.loading = false)
```

**Comment by pkozlowski-opensource** [comment]
@valentincocaud please direct support questions to an appropriate support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Thnx!

**Comment by valentincocaud** [comment]
@ericmdantas Yes, it's a copy mistake. I found that the problem is that css classes (like `ng-hide`) are not set. Loading the angular-csp.css file fix the issue but I don't use ng-csp directive.
