### ISSUE TITLE
ng-if="myarray[index]" or binding like {{myarray[index]}} 

### ISSUE THREAD

**Issue by JugnuPathak** [angular/angular.js#12463]
i have directive one directive having template shown as below : 
 template: "<div class='form-horizontal'>\n  <div  ng-if=\"myarray[myindex] > somevalue\" >{{myarray[myindex]}} </div>\n  </div>",

in scope i have

scope.myarray = //any array
scope.myindex = //some integer value

its throwing syntax error anybody have any idea????

**Comment by pkozlowski-opensource** [comment]
@JugnuPathak I've [asked](https://github.com/angular/angular/issues/3354#issuecomment-125934313) to use proper support channel for those questions... 

We really can't help without enough context / reproduction scenario, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-submission-guidelines
