### ISSUE TITLE
angular/bower-angular does not specify license in bower.json file

### ISSUE THREAD

**Issue by pantocrator27** [angular/angular.js#12472]
Could angular include the license type in bower.json file for angular/bower-angular?

**Comment by Narretz** [comment]
Hi @pantocrator27 this is certainly possible. If you want to give a PR a shot, this file needs to be updated to include the license: https://github.com/angular/angular.js/blob/master/scripts/bower/publish.sh

**Comment by pantocrator27** [comment]
Will certainly do Martin.  I was not familiar enough with the project to
identify the correct file so thanks for steering me in the right direction!

**Comment by pantocrator27** [comment]
@Narretz In looking at the https://github.com/angular/angular.js/blob/master/scripts/bower/publish.sh file, it looks like the file provides a way to modify attributes in bower.json for each component being published but not necessarily a way to add attributes and their associated values.  Would the correct thing to do in this case be just to touch the bower.json file in each repo corresponding to a particular component or to modify the publish.sh script to make this change so that it can add attributes as well as modify them?  It seems like a nasty thing to do in bash but I guess it can be done :)

**Comment by 4O4** [comment]
Looks like this has been fixed in https://github.com/angular/bower-angular/commit/1f6d26acd5021b555ac10a6214c23b4c8290a2ef
