### ISSUE TITLE
downloading angular js windows 10

### ISSUE THREAD

**Issue by lupster12** [angular/angular.js#12475]
I have tried downloading angular to my new desktop windows 10 but it keeps giving me the same message. Error: 'window' is undefined. Code: 800A1391. Source: Microsoft JScript runtime error

**Comment by Narretz** [comment]
Do you mean you cannot download angular from angularjs.org or that you cannot use it with a browser in Windows 10?

**Comment by lupster12** [comment]
I can't download it from angular.org

**Comment by maumorales** [comment]
Had no issues downloading on a Windows 10 machine. I did double-click the downloaded file (angular.js) out of curiosity and got the error mentioned by this issue. I'm assuming @lupster12 browser tries to run before downloading.
![12475 download win10](https://cloud.githubusercontent.com/assets/4475355/9152486/02804f1a-3df9-11e5-9fec-a47fdf7f7657.PNG)

**Comment by Narretz** [comment]
Thx @maumorales I think your explanation is spot on. It's a bit weird how IE handles this. Firefox actually opens the file in the browser, only Chrome opens the download dialog. Maybe we need to make this consistent.

**Comment by zeph1997** [comment]
Hi, I am having the same problem as well. I downloaded angularjs using chrome but the error as @maumorales has shown keeps popping up. Can you guys help? Thanks!

**Comment by gkalpak** [comment]
@zeph1997, try downloading the file (instead of baving the browser run it (e.g. right click -> Save as..).
If you are still running into problems, try asking on one of the [general support channels][1].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by kxk302** [comment]
I am having the exact issue that maumorales was having. I download angular.min.js, but when I run it I get "Error: 'window' is undefined". I'm on a Windows 10 box. Any fix for this problem? Thx
