### ISSUE TITLE
How can i set URL parameters and make a button click to be type. like if you type the word "Peter" the URL be like http://sample.com/events.json?name=peter

### ISSUE THREAD

**Issue by rhob** [angular/angular.js#12488]
var myTable=angular.module('myTable',[]);
  myTable.controller('tableCtrl',function($scope,$http){
  $http.get("http://sample.com/events.json", {headers: {Authorization: 'qZFzMs9c3IjSw856PnGUyOAlmgTW'}})
   .success(function(response) {
      debugger
    $scope.members=response.events;
     $scope.totals = response.paging;
  });
});

**Comment by pkozlowski-opensource** [comment]
@rhob please use an appropriate support channel for those types of questions, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Thnx!
