### ISSUE TITLE
Change in angularjs 2.0 DISPLAYING DATA document, class FriendsService has to be defined before appInjector. 

### ISSUE THREAD

**Issue by deepakshrma** [angular/angular.js#12487]
According to issue: https://github.com/angular/angular/issues/1655 
FriendsService has to be defined before appInjector. It is very irritating to resolve this kind of error. If i have just started how you can expect i will resolve this kind of issue with my own.
https://angular.io/docs/js/latest/guide/displaying-data.html

**Comment by lgalfaso** [comment]
It looks like this issue was open on the wrong repo. Please create this at https://github.com/angular/angular

**Comment by deepakshrma** [comment]
Thanks, done ! https://github.com/angular/angular/issues/3452

**Comment by gdi2290** [comment]
lol is this the first time there was an ng2 issue in the ng1 repo? there are so many ng1 issues opened in the ng2 repo

**Comment by lgalfaso** [comment]
@gdi2290 this is not the first time, but this is not an issue at all

**Comment by deepakshrma** [comment]
:+1:  Thank guys ;) it was by mistake. I think you should change the repo name of angular 2.0 (https://github.com/angular/angular) from angular to angular2. It creates lots of confusion :-D
