### ISSUE TITLE
Infinite digest on location change on iOS 9 beta 4

### ISSUE THREAD

**Issue by viattik** [angular/angular.js#12485]
Me and few more people are experiencing the same issue as in #12241 .
Creating new because that one is closed and not sure anyone's going to reopen it.

**Comment by lgalfaso** [comment]
This is a duplicate of #12241. Closing

**Comment by viattik** [comment]
@lgalfaso could you please reopen #12241 then? cause issue exists.

**Comment by machroad** [comment]
+1
