### ISSUE TITLE
angularjs issue in IE9 -Object expected

### ISSUE THREAD

**Issue by devangrc95** [angular/angular.js#12486]
SCRIPT5007: Object expected 
angular.js, line 318 character 12 
SCRIPT438: Object doesn't support property or method 'module' 
refernce-module.js, line 6 character 1

**Comment by lgalfaso** [comment]
Hi, what version of Angular are you using? Can you please create a plunker that shows the error.

Without this information, there is nothing that can be done.

**Comment by devangrc95** [comment]
![ajserror](https://cloud.githubusercontent.com/assets/13620743/9033659/d723698a-39e6-11e5-9fc9-67d190741ba5.JPG)

I am using angular.min.js

**Comment by lgalfaso** [comment]
Would it be possible to know what Angular version are you using? Eg 1.4.3
Please create a plunker with the error, without this, there is nothing actionable.

**Comment by Narretz** [comment]
Closing because we don't have a reproduce scenario.
