### ISSUE TITLE
Strange behavior CORS on Safari

### ISSUE THREAD

**Issue by no-more** [angular/angular.js#12480]
Hi All,

I have a very strange issue with angular(or at least I think it's about angular) and Safari.

When I start the application, I do a call through a $resource element. As I had some errors I added trace and logs. I find out some very strange behavior:
The issue only occurs on site launch (refresh page). During this step I do, on some conditions, a few $resource calls to a server.
As those calls are on another subdomain I have set up CORS and so I have an automatic OPTION call before every request.
The OPTION call works as expected, but then the trouble come on the GET request. I have no trace of this call on the server (not even in the access log file).
In safari however I have a trace in the resources panel, but the response is not the one I expect, it is in fact exactly the same response as the OPTION response. Seems like Safari does not make the GET call and just simulate it and use the cached OPTION response. I set up a specific response for OPTION calls in order to be very lightweight on the server, so I don't have the data 'cached'.

What is even stranger is that other calls are working fine (once the application is loaded).

I have absolutely no idea of what's going on with Safari but in my current configuration it's not working at all because it's a mandatory step.

I'm using angular 1.4.3 and with angular material#0.10.1-rc5

I can send a link for testing if required.

Thanks

**Comment by pkozlowski-opensource** [comment]
@no-more I'm afraid that we can't help much here as CORS pre-flight request are browser built-in mechanism and are _not_ sent by AngularJS. So this would be something to check on Safari-related support forums.

**Comment by no-more** [comment]
Thanks, and sorry I forgot to describe the solution.

The issue was in fact in server side, the OPTION response was marked as cached. After changing the server everything is working fine.

What is still strange is why this happened only on safari, and not on every requests. The server always send the same OPTION response, so the issue might be on some type of request only but I can't find out what it was.

Thanks.
