### ISSUE TITLE
add none or noop filter

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular.js#12494]
Add `none` filter
```js
filter('none', function() {
    return function(input) {
        return input;
    };
});
```

It useful for plugins which use filter name in options
```js
somePlugin({
    listFilter: 'none' //default 'somePluginASCsort'
})
```

Of course, you can add the filter to `somePlugin`, but then it will have to be named `somePluginNone`, that it is not conflict with other filters

**Comment by Narretz** [comment]
So in the "plugin" you can define which filter it should use? Shouldn't the plugin then be clever enough to not use a filter when you pass `false` or something?
I personally don't see the big utility of / demand for a `none` filter. It's a very simple filter that can be added on a per-project basis.

**Comment by lgalfaso** [comment]
Agree with @Narretz we are going to pass on this. Closing.
