### ISSUE TITLE
ngAnimate causes ngShow to malfunction in certain circumstances

### ISSUE THREAD

**Issue by brianmcd** [angular/angular.js#12491]
Plunkr: http://plnkr.co/edit/dlBOem

#### Overview 
While upgrading an app from 1.3 to 1.4, I've found that `ng-show` can show the wrong result when `ngAnimate` is included on the page.  In the Plunkr, the `div` should be hidden, but it's shown.

**Versions**: 1.4.0+ (1.4.0-rc.2 is the last version that doesn't have this bug)
**Browser/OS**: I've tested with Chrome and Firefox on OS X and it's always reproducible in both.

Here's the commit range where I believe the bug was introduced: https://github.com/angular/angular.js/compare/0681a5400e4150a961f9c8651e55623ca23b0cc2...291d7c467fba51a9cb89cbeee62202d51fe64b09 (between 1.4.0-rc.2 and 1.4.0)

The closest issue I found is https://github.com/angular/angular.js/issues/11717, which was fixed, but seems related.

#### Observations:

If you remove `ngAnimate` from the module or switch to `ng-if`, the `div` is properly hidden.

The `ng-show` condition relies on 2 variables.  The values of the variables are printed to the console in the plunkr, and the progression goes like this:

```
...
loading: true
results.length: 0

loading: false
results.length: 0

loading: false
results.length: 1
...
```

The condition for the `ng-show` is `!loading && !results.length`.  I think that second iteration where `loading` is `false` and `results.length` is `0` is what's throwing things off.

Tagging @matsko since he seems to be the expert in this area.

**Comment by matsko** [comment]
I'm having a look.

**Comment by matsko** [comment]
There was a big commit over the last few weeks that fixed ngAnimate (https://github.com/angular/angular.js/commit/32d3cbb3aadf71492102f9318fcac570fb60bef8) and it looks like your issue may be fixed in it: http://plnkr.co/edit/DRaRsT?p=preview

**Comment by matsko** [comment]
Keep in mind that there hasn't been a release for a few weeks just yet. 1.4.4 will come out this week and that includes this fix that is present in snapshot.

**Comment by brianmcd** [comment]
Thanks for such a quick response, @matsko.  I dropped the snapshot version into my project, and I can confirm that this issue is fixed now.

**Comment by matsko** [comment]
Excellent! :)
