### ISSUE TITLE
ngOptions regression while filling the option value without using track by.

### ISSUE THREAD

**Issue by ruimarques** [angular/angular.js#12505]
Overview of the Issue:
This issue happens while using ngOptions to create options for a select element where the model is an array of objects and "track by" is not used. The issue is that ngOptions fills the options value property with an object hash instead of the array index, like it previously did.

Basically what happens is that this is generated:

```
<option value="option:3" label="black"></option>
<option value="option:4" label="red"></option>
``` 
Instead of this:

```
<option value="0" label="black"></option>
<option value="1" label="red"></option>
```

Motivation for or Use Case: 
Regression of an expected behaviour.

Angular Version(s):
1.3.16 worked OK
1.4.x not OK

Browsers and Operating System:
Linux + Chrome Version 44.0.2403.130 (64-bit) or PhantomJS

Reproduce the Error:
You can actually see this happening in AngularJS documentation examples which I link next.
If you inspect the option HTML elements within the ngOptions documentation examples you will notice than with [1.3.16](https://code.angularjs.org/1.3.16/docs/api/ng/directive/select) the values have the array indexes (0, 1, 2, ...), and [1.4.3](https://code.angularjs.org/1.4.3/docs/api/ng/directive/ngOptions) has the hash string of some object ('object:100', 'object:102', 'object: 102', ...). The same happened in my project when I upgraded from 1.3.16 to 1.4.3.

The values are correct if 'track by' is used. The problem seems to be that a hash string of a model item property is used to set the option value instead of the array index.

I suspect [this was the commit](https://github.com/angular/angular.js/commit/14638f4a60053b085565e597fc74bd31cf0d372b) which changed this behaviour.

**Comment by Narretz** [comment]
This is a documented breaking change: https://code.angularjs.org/1.4.3/docs/guide/migration#ngoptions

What is your actual use case?

**Comment by ruimarques** [comment]
I was unaware of that breaking change detailed explanation. I think I can easily modify my
application to accommodate this by using `track by` or other work around. 

In my application the value was only used in testing, to check the correct order of the options and so on, but there are several alternatives to do that.

**Comment by Narretz** [comment]
Great to hear that it doesn't affect your application severly.
