### ISSUE TITLE
ngAnimate error in 1.3.x

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#12503]
I am running into a weird error in UI Bootstrap, where it appears ngAnimate is the culprit (removing the dependency does not trigger the error in console).

[Here](http://plnkr.co/edit/S0EixpxpoNJQu4FQhZCs?p=preview) is the Plunker - it should be noted that where it is throwing the error in console, on the first execution of this block, `elementNode` and `parentNode` exist fine. On second and third execution, `elementNode` ends up being undefined, which results in the error being thrown.

This error does not seem to create any functional problem.

This component does not use ngAnimate functionality at all, which makes me suspect there is something wrong with ngAnimate itself here.

Note that this is only a problem in 1.3.x (i.e. 1.3.17) - this does not manifest in 1.4.x.

**Comment by codeorganic** [comment]
I see this issue as well

**Comment by elishaterada** [comment]
Related issue on AngularJS thread: https://github.com/angular/angular.js/issues/10205

**Comment by elishaterada** [comment]
@wesleycho the issue seems to be resolved with 1.3.18 update. We confirmed that this fixed the issue on our projects as well.

https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1318-collective-penmanship-2015-08-18

**Comment by wesleycho** [comment]
This indeed seems fixed now, as seen [here](http://plnkr.co/edit/JHl4FZgMvPMj9PD7N9ns?p=preview).

Thanks @matsko!
