### ISSUE TITLE
ng-repeat gets compiled before outer directive

### ISSUE THREAD

**Issue by maseev** [angular/angular.js#12501]
Hello there!

I've run into a problem related to the directive compile phase.
To be particular - I'm trying to create a directive which sole purpose will be 
to change a nested directive into something else, recompile nested stuff and update the DOM.

Here's a simple example of what I'm trying to achieve:

```html
<pageable>
  <table>
    <thead>
      <tr>
          <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="item in items">
          <td>{{item}}</td>
      </tr>
    </tbody>
  </table>
</pageable>
```

I thought that by the time pageable runs its compile phase, I would be able to get access to the nested directive before it gets compiled (in this example it's ng-repeat directive), because pageable directive has a higher priority than ng-repeat:

```html
<tr ng-repeat="item in items">
  <td>{{item}}</td>
</tr>
```

But, I get already compiled ng-repeat directive instead of that html template in the compile method:

```html
<tbody>
  <!-- ngRepeat: item in items -->
  <tr ng-repeat="item in items" class="ng-scope">
      <td class="ng-binding">1</td>
  </tr>
  <!-- end ngRepeat: item in items -->
  <tr ng-repeat="item in items" class="ng-scope">
      <td class="ng-binding">2</td>
  </tr><!-- end ngRepeat: item in items -->
  <tr ng-repeat="item in items" class="ng-scope">
      <td class="ng-binding">3</td>
  </tr>
  <!-- end ngRepeat: item in items -->
  <tr ng-repeat="item in items" class="ng-scope">
      <td class="ng-binding">4</td>
  </tr><!-- end ngRepeat: item in items -->
</tbody>
```

Here's a simple plnkr that demonstrates that effect: http://plnkr.co/edit/oOaEMZDgrGl1JY0iCD2Y

**Comment by lgalfaso** [comment]
When you do a console.log of an html element and the html element chances, then the console reflects this (even when if the element is changed after the console.log call). This is easy to see if you do `console.log(element[0].outerHTML)`. This is working as expected.

BTW, for support questions, please open them first at StackOverflow.
