### ISSUE TITLE
$animate with ngShow is not working properly when used with Angular Material

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/angular.js#12519]
The [Plunker Demo](http://plnkr.co/edit/PpyyYMcqiD65u1ysq3ZA?p=preview)  shows a Form used with ngShow and custom directives/transcludes.

*  If the module ['ngMaterial'] is not included, the Form displays properly
*  If the module ngMaterial **is** included, the Form **is not** displayed
  *  `.ng-hide` is never removed
*  If the module ngMaterial **is** included and a custom `ng-show` directive is used, the Form **is** displayed.
  * see script.js for the ngShowDirective override
  * $animate is not used. Instead element.remove() is used.

This issue references https://github.com/angular/material/issues/3941.

> Is this a known **$animate** bug with remove/add class ? Why would $animate work when ngMaterial is NOT a dependency?

**Comment by Narretz** [comment]
Hi @ThomasBurleson , thanks for labeling the issue. You should also set the milestone if you know in which timeframe exactly this'll be handled. If it's not clear if this is an angular issue, put it in Purgatory.

**Comment by ThomasBurleson** [comment]
@Narretz - While I think this issue hints at a serious subtle bug (either in $animate or Angular Material), I do not want to presume when this issue should be targeted.

**Comment by matsko** [comment]
There's currently a bug with ngShow in Angular 1.4 that I'm looking into. It's preventing me from releasing 1.4.4. I will reply later today when I have more info on the situation.

**Comment by matsko** [comment]
The snapshot version of Angular has fixed this: http://plnkr.co/edit/hQ2Q6y5Qi72fePI1VrUl?p=preview

There are still some animation issues with ngShow that I'm fixing, but this issue is good.

**Comment by ThomasBurleson** [comment]
@matsko - I do not understand your comment. Do you have a specific commit that fixes this?

**Comment by sreeramu** [comment]
@ThomasBurleson you are correct snapshot version is most current HEAD build on master.

**Comment by matsko** [comment]
snapshot = latest build on master: https://code.angularjs.org/snapshot/angular.js
