### ISSUE TITLE
Unterminated statement in ngAnimate breaking minification

### ISSUE THREAD

**Issue by ryanhendry** [angular/angular.js#12513]
There is an unterminated statement [here](https://github.com/angular/angular.js/blob/32d3cbb3aadf71492102f9318fcac570fb60bef8/src/ngAnimate/shared.js#L72) which is breaking minification for me.

**Comment by Delapouite** [comment]
Which tool do you use to minify this file?

**Comment by ryanhendry** [comment]
@Delapouite [This](http://joliclic.free.fr/php/javascript-packer/en/) unfortunately (legacy application).
