### ISSUE TITLE
Documentation Contradiction

### ISSUE THREAD

**Issue by zwhitchcox** [angular/angular.js#12510]
"Now that Angular knows of all the parts of the application, it needs to create them. In the previous section we saw that controllers are created using a factory function"

-https://docs.angularjs.org/guide/concepts#template

"The instructions for the injector to create these special objects (with the exception of the Controller objects) use the Factory recipe behind the scenes."

-https://docs.angularjs.org/guide/providers

Do these two pages not contradict each other? Forgive me if I'm being a total n00b here

**Comment by lgalfaso** [comment]
It might be somehow confusing as in one case it is talking about the `$controller` controller factory function and the other `module.factory` function that is syntactic sugar on top of provider
