### ISSUE TITLE
angular-resource breaks IPv6 URLs

### ISSUE THREAD

**Issue by c2franz** [angular/angular.js#12512]
There is a regular expression in angular-resource.js that is breaking IPv6 resource URLs:

    url = url.replace(new RegExp("(\/?):" + urlParam + "(\\W|$)", "g"), function(match,
        leadingSlashes, tail) {
      if (tail.charAt(0) == '/') {
        return tail;
      } else {
        return leadingSlashes + tail;
      }
    });

Example:
http://jsfiddle.net/c2franz/pszLs0kg/4/

Expected behavior: a GET request is performed to http://[2620:0:861:ed1a::1]
Observed behavior: a GET request is performed to http://[2620:0:861::1]

**Comment by lgalfaso** [comment]
This looks like a real bug. PR welcome.
