### ISSUE TITLE
ng-model bound to select with a numeric value doesn't work as expected

### ISSUE THREAD

**Issue by richardthombs** [angular/angular.js#12517]
I am accessing an api that returns numeric values for enumerations and I'm trying to bind that to a select:

```
<select ng-model="mode">
  <option value="1">Off</option>
  <option value="2">On</option>
</select>
```
When the model variable "mode" is a numeric value, the select's initial value is not set correctly, eg: `mode=2` yields an uninitialised select. However if the model value is the string representation of the number, it works, eg: `mode='2'`.

Simple jsbin that reproduces this: http://output.jsbin.com/danerajifa

**Comment by pkozlowski-opensource** [comment]
This works as intended, since comparison of model values to select takes types into account. From https://docs.angularjs.org/api/ng/directive/select:

> The value of a select directive used without ngOptions is always a string. When the model needs to be bound to a non-string value, you must either explictly convert it using a directive (see example below) or use ngOptions to specify the set of options. This is because an option element can only be bound to string values at present.

**Comment by richardthombs** [comment]
Thank you, sorry for wasting your time.
