### ISSUE TITLE
$location.replace() and state.go(name, params, { location : 'replace' }) not working properly with history back

### ISSUE THREAD

**Issue by kenilam** [angular/angular.js#12516]
I encounter a strange behavior when using $location.replace() and state.go(name, params, { location : 'replace' }).

Scenario as follow:
A static page (domain.com/experiments) with a list of link to an angular app

```
<a href="domain.com/#!?experiment=A">experiment A</a>
<a href="domain.com/#!?experiment=B">experiment B</a>
<a href="domain.com/#!?experiment=C">experiment C</a>
```

Tap on the domain.com/#!?experiment=A link and it take you to the angular App that has a config with urlRouterProvider as follow:

```
function whenRouteOtherwise ($injector, $location) {
    $location.replace();

    return '/home';
}
$urlRouterProvider.otherwise(whenRouteOtherwise);
```

And another redirection to home/shop on a directive as follow:

```
if ($state.current.name !== 'home.shop') {
    $state.go('home.shop', { shopId: 123 }, { location: 'replace' });
}
```

The end result is that you land on the domain.com/#!/home/123 as expected and the history show domain.com/experiments as the previous browser history (Nice!)

Tap on the back button and now you are back to the domain.com/experiments

Tap on the domain.com/#!?experiment=A link again and you are back to the angular app

But now if you look at the browser history, you will see:
domain.com/#!/home is the previous history and,
domain.com/#!?experiment=A is the one before that.

**Comment by Narretz** [comment]
Oh my, that's actually a uiRouter issue ...
