### ISSUE TITLE
Angular-meteor: ngMessages can't be found 

### ISSUE THREAD

**Issue by lscordilis** [angular/angular.js#12523]
I added the ```angular:angular-messages``` Meteor package to my app and included it in the main app.js:

```
angular.module('basic-orders', [
    'angular-meteor',
    'ui.router',
    'ngMaterial',
    'ngMessages',
    'ngRoute',
    'ngNumeraljs'
]);
```

And then implement it in a form, like so:
```
                <md-input-container>
                    <label>Name</label>
                    <input ng-model="thing.name"
                           required>
                    <div ng-messages="thing.name.$error">
                        <div ng-message="required">This is required.</div>
                    </div>
                </md-input-container>
```

per the example on https://material.angularjs.org/latest/#/demo/material.components.input

but I get this error: 
```
Error: [$compile:ctreq] Controller 'ngMessages', required by directive 'ngMessage', can't be found!
```

All my other included packages, like ngMaterial and ngNumeraljs work just fine, so it's likely not an angular-meteor problem, but rather a problem with the angular-messages package

Also, I've seen previous issues where ngMessages has failed when dealing with ng-included templates. My ng-message doesn't include any external templates, but the form itself is included in another template like so:

```
<md-sidenav id="side-menu" ng-show="loggedIn"
            class="md-sidenav-right md-whiteframe-z3" md-component-id="right">
    <ng-include src="sideTemplate"></ng-include>
</md-sidenav>
```

Any help would be greatly appreciated, I would love to be able to use angular messages in my app. It makes dynamic form validation so much easier :)

**Comment by lgalfaso** [comment]
Would it be possible for you to create a minimal plunker that shows this error?

**Comment by lscordilis** [comment]
![image](https://cloud.githubusercontent.com/assets/12753650/9202322/4f89d4c0-401f-11e5-9c61-94b2c4bf8338.png)

This is the simplest example I could come up with. I don't receive any error in Plunker, but I get the same fault behavior as I did in my Meteor app. Might it be a problem with your latest build? Because I've seen older examples that work just fine, like on the angular-material docs.

Here's the plunk: http://plnkr.co/edit/yTsvaB0Xe4Fo03VPLkYp?p=preview

**Comment by pkozlowski-opensource** [comment]
@lscordilis I think that you've linked a wrong plunk, since the one you've linked is almost empty...

**Comment by lscordilis** [comment]
My bad. I hadn't saved. The link points to the latest version now.

**Comment by lgalfaso** [comment]
The form is simply missing the `name` attributes to the form and to the input. The errors are not bind to the model. http://plnkr.co/edit/oAYwoWJU4MBye9HetPUV?p=preview

**Comment by lscordilis** [comment]
Thanks for the quick response! Looks like I misread the tutorial because the form name and ng-model attribute were very similar in name.

Unfortunately, while that solved the issue with the Plunker, I'm still getting the same error:
```
Error: [$compile:ctreq] Controller 'ngMessages', required by directive 'ngMessage', can't be found!
http://errors.angularjs.org/1.4.2/$compile/ctreq?p0=ngMessages&p1=ngMessage
    at REGEX_STRING_REGEXP (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:98:12)
    at getControllers (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:8039:19)
    at nodeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:8186:33)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:7573:13)
    at nodeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:8177:24)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:7573:13)
    at nodeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:8177:24)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:7573:13)
    at nodeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:8177:24)
    at compositeLinkFn (http://localhost:3000/packages/angular_angular.js?c3a778493846e58a63e652cd68b47914889a794c:7573:13) <ng-include src="sideTemplate" class="ng-scope" data-ng-animate="1">
```
in my Angular-Meteor app.

Per your advice, I changed the markup to the correct usage in my project:
```
<form name="myForm"> 
                <md-input-container>
                    <label>Date</label>
                    <input ng-model="thing.date"
                           id="datepicker"
                           required
                           name="datepicker">  
                    <div ng-messages="myForm.datepicker.$error">
                        <div ng-message="required">This is required.</div>
                    </div>
                </md-input-container>
</form>
```

But, still no luck. It doesn't seem to have made a difference.

**Comment by lscordilis** [comment]
Update: It only seems to completely crash like that with the datepicker. 

It works perfectly with normal input elements now that I'm using it properly. I don't know if this merits any investigation, but all my datepicker is is a simple pickadate defined like so:
```
    $('#datepicker').pickadate({
        format: 'mm/dd/yy'
    });
```

**Comment by lscordilis** [comment]
Thanks for your help, either way :)

**Comment by lgalfaso** [comment]
There are some issues with some jQuery plugins and Angular. I am not sure if the date picker that you are using is one of them, but I would recommend you to use an angular based date picker
