### ISSUE TITLE
We should test against minified files

### ISSUE THREAD

**Issue by matsko** [angular/angular.js#12530]
I just recently saw this commit fix: https://github.com/angular/angular.js/commit/4c92a3ccc7dacfd4bf8144b96c4cbb0c1a324b16

And it's a pretty serious issue, but none of our tests caught it. Why? Because we don't test against the minified artifacts in our code.

This is something that should happen on the travis-level prior to merge.

**Comment by Delapouite** [comment]
In this specific case, the minifying tool is guilty (http://joliclic.free.fr/php/javascript-packer/en/). So a test on an artifact compress through uglify would have succeed.

**Comment by Narretz** [comment]
Recap from Monday's meeting: our minification process is not broken and this also shouldn't happen for 99%  of files, since jshint / jscs would catch tahat; just this specific file had jshint disabled. It's nice to have, but the number of minification errors are extremely low, so it's not high priority.

**Comment by petebacondarwin** [comment]
Why is jshint disabled for the whole of this file?
https://github.com/angular/angular.js/blob/4c92a3ccc7dacfd4bf8144b96c4cbb0c1a324b16/src/ngAnimate/shared.js#L3

We should be disabling only line by line and for specific rules.

**Comment by petebacondarwin** [comment]
@matsko - why is the whole of the ngAnimate/shared.js file not being linted?

**Comment by matsko** [comment]
There were definition issues with the content defined in the file. I can take a look at it again to fix it up.

**Comment by guilhermeasg** [comment]
Can we close this? ESLint should catch this specific issue now

**Comment by Narretz** [comment]
Yeah, let's close it. We never had any more problems due to minification.
