### ISSUE TITLE
Drop non-compliant Promises/A+  progress/notify on $q

### ISSUE THREAD

**Issue by pocesar** [angular/angular.js#12533]
Makes it really hard to replace $q when using a compliant library, since angular uses progress/notify handlers on core itself.

**Comment by lgalfaso** [comment]
Would it be possible to know what library are you trying to use? The extra
parameters should be ignored, so more info is needed
>
>

**Comment by pocesar** [comment]
I managed to replace $q with bluebird, and set the scheduler to `$rootScope.$applyAsync`. I was trying to use `$interval` but uses notify. Another module included in my project also uses notify from $http. 
I implemented the `defer` method manually, along with `when`.

```typescript
        Bluebird.defer = function() {
            var dfd: any = {};

            dfd.promise = new Bluebird(function(_resolve, _reject) {
                dfd.resolve = _resolve;
                dfd.reject = _reject;
                dfd.notify = angular.noop;
            });

            return dfd;
        };

        var bb: any = Bluebird;
        bb.when = Bluebird.resolve.bind(Bluebird);

        var originalAll = Bluebird.all;

        Bluebird.all = function(promises: any|any[]) {

            if (angular.isObject(promises) && !angular.isArray(promises)) {
                return Bluebird.props(promises);
            } else {
                return originalAll.call(Bluebird, promises);
            }

        };

        Bluebird.onPossiblyUnhandledRejection(angular.noop);

        function BluebirdConstructor(cb: any): any {
            if (!(this instanceof Bluebird)) {
                return new Bluebird(cb);
            }
            return Bluebird;
        }

        angular.extend(BluebirdConstructor, Bluebird);

        $provide.decorator('$q', function() {
            return BluebirdConstructor;
        });
```

**Comment by Rush** [comment]
I was hit by this problem as well. @pocesar have you been able to fix `$interval`. It seems to me I would need to replace the whole service to make it work.

**Comment by lgalfaso** [comment]
would it be possible to have a plunker that shows the entire problem?

**Comment by Agamnentzar** [comment]
http://plnkr.co/edit/ITbUfnXOogSdO2r1w52J?p=preview

If you remove 'promise' module from dependencies you can see interval ticking as expected

The problem seems to be $interval depending on promise progress notification that is no longer part of promises

**Comment by lgalfaso** [comment]
@Agamnentzar thanks for the plunker. I think there should be an easy fix.

**Comment by Rush** [comment]
btw. a dumb/simplified workaround for `$interval` needing notify is simply swapping it with a custom one:
```js
  app.config(function($provide) {
    $provide.decorator('$interval', function($delegate, $rootScope) {
      var $newInterval = function(fn, timeout) {
        if(arguments.length !== 2 || typeof fn !== 'function' || typeof timeout !== 'number') {
          return console.error(new Error('custom $interval supports only 2 arguments, Function and timeout'));
        }
        
        var interval = setInterval(function() {
          $rootScope.$apply(fn);
        }, timeout);
        
        return interval;
      };
      
      $newInterval.cancel = function(handle) {
        clearInterval(handle);
      };
      
      return $newInterval;
    });
  });
```

**Comment by wesleycho** [comment]
Given that dropping the API is a breaking change to $q, it probably is safe to close this issue unless it is desired to remove it completely from the codebase. To fully remove notify usage from $interval would require a breaking change as well (under the assumption someone is hooking into the notifications from the interval promise).

Not sure how it is felt, but IMO it probably isn't worth removing since this is a more uncommon case.

**Comment by gkalpak** [comment]
@lgalfaso, WDYT (since this is assigned to you) ?

**Comment by lgalfaso** [comment]
Given that the issue with $interval is fixed, I would close this issue.

**Comment by gkalpak** [comment]
Thx @lgalfaso!

So, closing this (since we are not going to remove the `notify` method), but since Angular itself does not rely on `notify` for any internal fnctionality any more, you should be able to substitute `$q` for other promise libraries (e.g.  as described in https://github.com/angular/angular.js/issues/12533#issuecomment-129262925).
