### ISSUE TITLE
No error when using controllerAs in directive without an isolated scope

### ISSUE THREAD

**Issue by levin81** [angular/angular.js#12537]
Using controllerAs inside a directive without an isolated scope doesn't work - as is intended. Only problem is that there is no error in the console in the case of this scenario. It will just fail the entire application.

**Comment by Narretz** [comment]
There should probably be an error, that's right. However, what exactly do you mean with "it will fail the entire application"? This simple example works without an issue: plnkr.co/edit/FXOQCsD8HI2F3TgpUNnf?p=preview

**Comment by levin81** [comment]
I tried to reproduce it in a simple scenario and I can't seem to. My app has many other directives and they just wouldn't render once I had this issue. If I ever find out, I'll update. Thanks

**Comment by brendonco** [comment]
can you paste your HTML and JS or provide the code in jsfiddle or codepen that cause the problem?

**Comment by caitp** [comment]
There is absolutely no problem with using controllerAs without an isolate scope, why would there be? Yes it's possible to pollute scopes if you don't create a new scope for it, but it's certainly not something you can't do if you're careful

**Comment by Narretz** [comment]
@caitp Then we should probably update the docs: https://code.angularjs.org/snapshot/docs/api/ng/service/$compile#-controlleras- ;)

**Comment by caitp** [comment]
Those docs don't say anything about out being only for isolate scopes

**Comment by Narretz** [comment]
That's right. They do however say you need a new scope, but it also works without a new scope. I'll create a PR to make this clearer.

**Comment by Narretz** [comment]
@caitp can you please take a look at https://github.com/angular/angular.js/pull/12758?

**Comment by t9nf** [comment]
For extra  money  😆 

T9anef ™
