### ISSUE TITLE
form not attached to controller when using controllerAs/bindToController

### ISSUE THREAD

**Issue by levin81** [angular/angular.js#12547]
Hi,

I have a directive with `{ controllerAs: "vm", bindToController: true }` defined. When using a `<form name="thisForm">` inside the directive template, the `vm.thisForm` is undefined inside the controller. `$scope.thisForm` is working fine (if I inject $scope, obviously). Is this working as intended? Couldn't find any documentation on this.

**Comment by Narretz** [comment]
This is working as expected, see https://code.angularjs.org/snapshot/docs/api/ng/directive/form
