### ISSUE TITLE
Debugging angularjs

### ISSUE THREAD

**Issue by pulkitnandan** [angular/angular.js#12540]
Hi, Is there any way to debug angularjs app without using this line debugger;

Or any way by which we debug web apps like we do in gdb, Step and continue and exit if looping infinity which happens everytime with angularjs or in least is there a way to know where exactly error came from. Which line. Supposing I'm working on a opensource app and that uses names with unfamiliar means.

**Comment by ncapito** [comment]
This doesn't seem like an issue for the github project.   Questions like yours are probably best suited for the [google group](https://groups.google.com/forum/?fromgroups#!forum/angular).  If you have a better description of what you are trying to track down you could try [stackoverflow](http://www.stackoverflow.com) .


From the [CONTRIBUTING.md](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md) 

>  If you have questions about how to use AngularJS, please direct these to the Google Group discussion list or StackOverflow. We are also available on IRC.

**Comment by pkozlowski-opensource** [comment]
Thnx @ncapito !

**Comment by pulkitnandan** [comment]
Ok.
