### ISSUE TITLE
Properly decode $httpParamSerializer querystring?

### ISSUE THREAD

**Issue by Vayvala** [angular/angular.js#12559]
Here is my object, that I want to serialize:

    {"cars": [
       {"make":"volkswagen","model":"golf"},
       {"make":"volkswagen","model":"polo"},
       {"make":"audi","model":"a3"},
       {"make":"bmw","model":"1-series"},
       {"make":"renault","model":"espace"} 
    ]}

Before, I used jQuery `$.param()` function and `qs` library to decode it on node.js. And everything worked fine, I didn't need to parse anything myself.    
Now, I decided to try new Angular 1.4 service `$httpParamSerializer`. And after decoding, instead of `objects` in the array, I get `strings`:

     '{"make":"volkswagen","model":"golf"}'

How can I properly decode querystring that was created with the `$httpParamSerializer` service, without calling `JSON.parse` on every object in the array?

Here is `$.param` querystring:

    cars%5B0%5D%5Bmake%5D=volkswagen&cars%5B0%5D%5Bmodel%5D=golf&cars%5B1%5D%5Bmake%5D=volkswagen&cars%5B1%5D%5Bmodel%5D=polo&cars%5B2%5D%5Bmake%5D=audi&cars%5B2%5D%5Bmodel%5D=a3&cars%5B3%5D%5Bmake%5D=bmw&cars%5B3%5D%5Bmodel%5D=1-series&cars%5B4%5D%5Bmake%5D=renault&cars%5B4%5D%5Bmodel%5D=espace&demo%5Bsome%5D=bar

And here is `$httpParamSerializer` querystring:

    cars=%7B%22make%22:%22volkswagen%22,%22model%22:%22golf%22%7D&cars=%7B%22make%22:%22volkswagen%22,%22model%22:%22polo%22%7D&cars=%7B%22make%22:%22audi%22,%22model%22:%22a3%22%7D&cars=%7B%22make%22:%22bmw%22,%22model%22:%221-series%22%7D&cars=%7B%22make%22:%22renault%22,%22model%22:%22espace%22%7D&demo=%7B%22some%22:%22bar%22%7D`

**Comment by Narretz** [comment]
There's an alternative serializer in 1.4.x called `$httpParamSerializerJQLike` that serialies objects jQuery-style. You can use it either directly, or you can set the default via https://code.angularjs.org/snapshot/docs/api/ng/provider/$httpProvider or you can set it on a per call basis as part of the http config object.
For the future, please consider using one of these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by Vayvala** [comment]
Here is output of the `$httpParamSerializerJQLike` serialization: 

    { "cars": [ {
       make: [ 'volkswagen', 'volkswagen', 'audi', 'bmw', 'renault' ],
       model: [ 'golf', 'polo', 'a3', '1-series', 'espace' ] 
    } ] }

**Comment by lgalfaso** [comment]
18a2e4fbfc44216c31bbcdf7705ca87c53e6f1fa fixes an issue with `$httpParamSerializerJQLike`, this should be part of 1.4.4
