### ISSUE TITLE
cannot load different page on angular spa

### ISSUE THREAD

**Issue by spyroSlevin** [angular/angular.js#12551]
I am building an angular 1.2.28 app on an express/node server. There are two pages. I set them on app.js

```
var routes = require('./routes/index');
var users = require('./routes/users');

app.use('/', routes.list);
app.use('/users/', users.showUsers);
```

here are the routes (index and users)

```
exports.list = function(req, res){
res.render('index')
};

exports.showUsers = function(req, res){
res.render('users')
};
```

Now, users.ejs is just a dummy page like

```
<!DOCTYPE html>
<html >    
    <div id="main">
     this is where content will be injected 
    </div>
</html>
```

but the index.ejs is spa style like
```
<html ng-app="sp">
<head>
<script>
var sp = angular.module('sp', ['ngRoute']);

sp.config(function ($routeProvider,  $locationProvider) {
    // configure the routes


    $routeProvider
    .when('/', {
    // route for the home page
        templateUrl: 'http://localhost:4800/home.html',
        controller: 'homeController'
    })

    .when('/about', {
    // route for the about page
        templateUrl: 'http://localhost:4800/about.html',
        controller: 'aboutController'
    })
    .otherwise({
        templateUrl: 'http://localhost:4800/routeNotFound.html',
       controller: 'notFoundController'
    });

    $locationProvider.html5Mode(true).hashPrefix('!');

});

sp.controller('homeController', function ($scope) {
    $scope.message = 'Welcome to my home page!';
});

sp.controller('aboutController', function ($scope) {
    $scope.message = 'Find out more about us.';
});

   sp.controller('notFoundController', function ($scope) {
       $scope.message = 'There seems to be a problem finding the page you wanted';
    });
<script>
<base href="/">
</head>

<body ng-controller="homeController" >


<li><a href="/"> Home</a></li>
<li><a href="/about"> About</a></li>          
<li><a href="/users"> users</a></li>

    <div id="main">
        <div ng-view></div>
    </div>
</body>
```

Templates loading is fine. But, when I click the users link, it thinks is another template to load in index and fails.  I get "There seems to be a problem finding the page you wanted" on the page , from the "notFoundController" . No errors in the console.
If I remove the `$locationProvider.html5Mode(true).hashPrefix('!');` and change the template links prefixes from `/` to `#` everything works fine and I can see the users page. 
`<a href="/"> and <a href="/about"> becomes <a href="#"> and <a href="#about"> `

Why html5 mode breaks the link? I dont want to use `#` prefix, so I need to fix this. Is this a bug, a server issue or am I missing something?

Thank you

**Comment by Narretz** [comment]
Do I understand correctly, /users is a separate page that should not be routed by angular? You'll have to add a `target` attribute to the `a` then. Angular location / routing will ignore anchors that have target attributes. And for the future, please use one of these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by spyroSlevin** [comment]
I guess `target="_self"` in the users link will do the trick. Thanks
