### ISSUE TITLE
example in docs for $controller appears wrong

### ISSUE THREAD

**Issue by lsiden** [angular/angular.js#12550]
The [docs for ngMock.$controller](https://github.com/angular/angular.js/blob/master/src/ngMock/angular-mocks.js#L1772)
 give an example of it's invocation as 

    myMod.directive('myDirective', {
      controller: 'MyDirectiveController',
      bindToController: {
        name: '@'
      }
    });
    // Controller definition ...
    myMod.controller('MyDirectiveController', ['log', function($log) {
      $log.info(this.name);
    })];

Then,

    $controller('MyDirective', { /* no locals */ }, { name: 'Clark Kent' })

But 'MyDirective' is the registered name of the directive, not the controller.  Nowhere in the docs for $controller does it say that $controller will look up a controller by the name of a directive that binds to it.  Is this a mistake in the docs?

**Comment by caitp** [comment]
The example is showing you how to test "bind-to-controller" stuff, without having to rely on the `$compile` service. This was asked for. So, if you scroll down a bit further, the entire example shows you how you can completely set up mock bindings

**Comment by caitp** [comment]
although, you may be right, I can't recall if that was a typo or not, need to inspect the patch. If it is a typo, a fix is welcome

**Comment by caitp** [comment]
Yes, please send a patch to change it to `$controller('MyDirectiveController'`, thanks!
