### ISSUE TITLE
Adding and removing class in same digest cycle causes class to still be added

### ISSUE THREAD

**Issue by djasper99** [angular/angular.js#12564]
I have created a simplified plunker to demonstrate this issue:
http://plnkr.co/edit/sVomGmPvI2wMgaoh0MsA?p=preview

The second remove class call appears to cancel the first animation, however when the canceled animation is processed post digest, the class is still added.

The actual issue in my application arises in slightly more complicated circumstances.  A property is changing multiple times during the digest loop, causing the watch handler for ng-show to process multiple times, first adding the "ng-hide" class, and then removing it.

This appears to be a regression in the 1.4.x animate code, as changing the angular and angular-animate versions to 1.3.4 in the plunker will no longer produce this issue.

**Comment by Narretz** [comment]
It does look fixed in master: http://plnkr.co/edit/TJZC4p0jyZZgKrHhe3hr?p=preview
