### ISSUE TITLE
feat(orderBy): Support natural sort

### ISSUE THREAD

**Issue by gabrielmaldi** [angular/angular.js#12572]
This is a feature request. I searched issues and pull request and didn't find anything, sorry if this is a dupe.

I think that many of us would like to be able to ask `orderBy` to sort strings in a "natural" way (i.e. `foo 92` "is smaller than" `foo 147`, as opposed to the current lexicographical order which sorts `1` before `9`).

I'd be willing to submit a pull request but first I'd like to know if this is a feature the Angular team would like to add, discuss the possible syntax, and get some guidelines (I took a look at `orderByFilter` and noticed it's really optimized for performance).

Thanks!

**Comment by lgalfaso** [comment]
This is one of those things and always found a reasonable workaround (eg
for this case, (+somefield.substr(4))), but would be open to it if there is
enough community interest
>
>

**Comment by Ericson578** [comment]
Maybe a flag to force orderBy to convert input into integers?

**Comment by frankweb** [comment]
@Narretz I'd like to know your oppinion about this feature, I could create a new filter.

**Comment by Ericson578** [comment]
I've definitely run into this problem before, where I have a field that I want to order by in an ng-repeat, and the field is a number but for a variety of reasons is stored in js as a string. I've fixed the problem by writing a custom filter that converts to int before comparing using parseInt(num, 2), but would be nice if there was already a filter that did this.

**Comment by gkalpak** [comment]
Is it just me or does this sound like a better fit for an external module (rather than a core feature) ?

**Comment by gkalpak** [comment]
Now that #14468 has landed in master, it will be even easier to do this by providing a custom comparator function. I'm going to close this for now, since it seems like a better fit for an external module.
