### ISSUE TITLE
ngAnimate applies sequential addClass and removeClass animations out of order

### ISSUE THREAD

**Issue by harmoney-nikr** [angular/angular.js#12573]
Sample Plunkr: http://plnkr.co/edit/GNNLxdoRVuP4WkUBFz2k?p=preview

To reproduce, continue to type the same key in the email field so it never validates. Every 2-3 presses the `ng-invalid` class will be removed, however the span with ng-if remains (proving that the `$invalid` property is still true).

As far as I can tell, when a `removeClass` and an `addClass` are fired within short succession of each other (which is the case here; the class is removed on keypress and added after validation) the order is not always the same and the `removeClass` can come after the `addClass`.

I couldn't tell exactly if #12248 would fix this issue. I suspect so but I thought I'd note it just to be sure.

**Comment by Narretz** [comment]
This is fixed in master: http://plnkr.co/edit/ZrisDtnjnUW4vwRc2sx4?p=preview and will be fixed in 1.4.4

**Comment by harmoney-nikr** [comment]
Great, thanks @Narretz.
