### ISSUE TITLE
$http not catching the error function when preflight request happen

### ISSUE THREAD

**Issue by pavankumarkatakam** [angular/angular.js#12574]
I know that $http will use `application/json` so that some browsers will trigger a `preflight request` with the verb `OPTIONS`,  actual my issue is 

 when OPTIONS and POST is success -> success function will be executed. by $http

when OPTIONS is success and POST is error (error thrown by server)-> success function is executing (expected error function to be executed.).

please tell me why this is hapenning? is there anything to change?

**Comment by pkozlowski-opensource** [comment]
This doesn't sound right. I would suspect that you've got an interceptor in your app that distorts results. Could you please demonstrate the issue with a plunker so we can confirm?

**Comment by pavankumarkatakam** [comment]
Yes it's due to interceptors, problem is solved. thanks for the answer.
