### ISSUE TITLE
dynamic iframe disappeared and page doesn't go back to previous visited page, when i click Firefox browser back button in angularjs application. Its working in IE and Chrome

### ISSUE THREAD

**Issue by mpkalaiarasan** [angular/angular.js#12587]

**Comment by Narretz** [comment]
Can you provide code / a demo of this happening?

**Comment by mpkalaiarasan** [comment]
CardCtrl.js:

( function () {
	angular.module('myApply.payment').controller('CardCtrl', function ($scope, $rootScope, $attrs, $location) {
		
		var url ="profile/applications/::applicationId/payment/authtocharge";
		
		$scope.init = function () { 
			
			$scope.initForm({ action:url }, function (data) {
							
				$scope.isMobileView = false;
				$scope.data = data;
				
				$scope.actionVar = data.financialsAuthToChargeFormUrl;
				console.log(data.financialsAuthToChargeFormUrl)
				
				if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
					$scope.isMobileView = true;
				}
				if(!$scope.isMobileView){
					//we are setting all the values manually instead of setting in scope
					//because we need control to submit form after all the values are set
					//if we do angular way, we need to wait until digest cycle is done.
					//currently there is no direct way to know when digest cycle is done.
					angular.element('#a2cform').attr('action', data.financialsAuthToChargeFormUrl);
					angular.element('#A2CFName').val(data.stFirstName);
					angular.element('#A2CLName').val(data.stLastName);
					angular.element('#A2CAddress').val(data.stAddress1);
					angular.element('#A2CAdress2').val(data.stAddress2);
					angular.element('#A2CCity').val(data.stCity);
					angular.element('#A2CState').val(data.stState);
					angular.element('#A2CZipCode').val(data.stZipCode);
					angular.element('#IRN').val(data.irn);
					angular.element('#A2CApplicationID').val(data.applicationId);
					angular.element('#A2CStudentAuth').val(data.stA2CStudentAuth);
					//we are submitting form using jquery, this makes sure form is submitted only after
					//all the values are populated
					
					
						$('#a2cform').submit();					
					
						
					} else {
						angular.element('#a2cform').attr('action', data.financialsAuthToChargeFormUrl);
						angular.element('#A2CFName').val(data.stFirstName);
						angular.element('#A2CLName').val(data.stLastName);
						angular.element('#A2CAddress').val(data.stAddress1);
						angular.element('#A2CAdress2').val(data.stAddress2);
						angular.element('#A2CCity').val(data.stCity);
						angular.element('#A2CState').val(data.stState);
						angular.element('#A2CZipCode').val(data.stZipCode);
						angular.element('#IRN').val(data.irn);
						angular.element('#A2CApplicationID').val(data.applicationId);
						angular.element('#A2CStudentAuth').val(data.stA2CStudentAuth);
						
						angular.element('#A2CLast4').val('');
						angular.element('#A2CCType').val('');
						angular.element('#CPPStatus').val('');
						angular.element('#A2CSendDate').val('');
						angular.element('#A2CSendTime').val('');
						angular.element('#A2CSaveCardRadio').val('');
						
						
						$('#a2cform').submit();
						
					}
					
			});
		};

		

		$scope.init();
	

	});

}());


payment.card.html
-----------------------

<header>
	<h1>Provide card information for future charges.</h1>
	<div ng-init="excludeRequiredLegend=true"></div>
	<div class="row-fluid" ng-include="'resources/appc/modules/main/app/components/form-header.html'"></div>
</header>

<section class="row-fluid nogap" ng-controller="CardCtrl">
	<form id="a2cform" name="a2cform" class="hidden" target="auth_to_charge_frame" method="post">
		<input name="A2CFName" type="hidden" id="A2CFName" /> 
		<input name="A2CLName" type="hidden" id="A2CLName" />
		<input name="A2CAddress" type="hidden" id="A2CAddress"  /> 
		<input name="A2CAddress2" type="hidden" id="A2CAdress2"  />
		<input name="A2CCity" type="hidden" id="A2CCity" /> 
		<input name="A2CState" type="hidden" id="A2CState"/>
		<input name="A2CZipCode" type="hidden" id="A2CZipCode" />
		<input name="A2CRole" type="hidden" id="A2CRole" value="ACAUUSD" /> 
		<input name="A2CORGA" type="hidden" id="A2CORGA" value="31"/> 
		<input name="IRN" type="hidden" id="IRN"/> 
		<input name="A2CApplicationID" type="hidden" id="A2CApplicationID"/> 
		<input name="A2CStudentAuth" type="hidden" id="A2CStudentAuth"/>
		<input name="auth2charge" type="hidden" id="auth2charge"/> 
		<input name="A2CRedirect" type="hidden" id="A2CRedirect"/> 		
	</form>

	
		<iframe id="auth_to_charge_frame" name="auth_to_charge_frame" class="frameless"></iframe>
	
		
	

</section>

**Comment by mpkalaiarasan** [comment]
<section class="row-fluid nogap" ng-controller="CardCtrl">
	<form id="a2cform" name="a2cform" class="hidden" target="auth_to_charge_frame" method="post">
		<input name="A2CFName" type="hidden" id="A2CFName" /> 
		<input name="A2CLName" type="hidden" id="A2CLName" />
		<input name="A2CAddress" type="hidden" id="A2CAddress"  /> 
		<input name="A2CAddress2" type="hidden" id="A2CAdress2"  />
		<input name="A2CCity" type="hidden" id="A2CCity" /> 
		<input name="A2CState" type="hidden" id="A2CState"/>
		<input name="A2CZipCode" type="hidden" id="A2CZipCode" />
		<input name="A2CRole" type="hidden" id="A2CRole" value="ACAUUSD" /> 
		<input name="A2CORGA" type="hidden" id="A2CORGA" value="31"/> 
		<input name="IRN" type="hidden" id="IRN"/> 
		<input name="A2CApplicationID" type="hidden" id="A2CApplicationID"/> 
		<input name="A2CStudentAuth" type="hidden" id="A2CStudentAuth"/>
		<input name="auth2charge" type="hidden" id="auth2charge"/> 
		<input name="A2CRedirect" type="hidden" id="A2CRedirect"/> 		
	</form>

	
		<iframe id="auth_to_charge_frame" name="auth_to_charge_frame" class="frameless"></iframe>
	
		
	

</section>

**Comment by Narretz** [comment]
Sorry, I really don't see any iframe related code in this. Are you using 3rd party scripts that insert the iframe?

**Comment by mpkalaiarasan** [comment]
Narretz, I found the solution for this issue.

var frame = $('#auth_to_charge_frame')[0];  					
frame.contentWindow.location.replace(data.financialsAuthToChargeFormUrl);

Source:

http://stackoverflow.com/questions/2245883/browser-back-acts-on-nested-iframe-before-the-page-itself-is-there-a-way-to-av?rq=1

**Comment by Narretz** [comment]
Glad you found a solution.
