### ISSUE TITLE
In IE9, the xhr response get a Bytes Array,  instead of json string! What's wrong?

### ISSUE THREAD

**Issue by terryliulj** [angular/angular.js#12586]
src/ng/httpBackend.js, line 63:

var response = ('response' in xhr) ? xhr.response : xhr.responseText;

In IE9, xhr.response get a bytes array, but xhr.responseText is expected json string

I write the debug code:
console.log("xhr response", xhr.response);
console.log("xhr response text", xhr.responseText);
and I got:
xhr response [object Array][123, 34, 105, 100, 34, 58, 49, 44, 34, 116, 105, 116, 108, 101, 34, 58, 34, 103, 101, 101, 103, 97 ...]
xhr response text {"id":1,"title":"geega",...}

why?

**Comment by terryliulj** [comment]
Because ie9 console report an error:
-----------------------------
[object Error]{description: "[$resource:...", message: "[$resource:...", name: "Error"}
description"[$resource:badcfg] Error in resource configuration for action `get`. Expected response to contain an object but got an array 
------------------------------
so I debuged the source code.

**Comment by terryliulj** [comment]
I added these codes to fix it, but I can't confirm that it's correct completely:
        var response = ('response' in xhr) ? xhr.response : xhr.responseText;
+      if(isArray(response)){ // fix it for IE9
+          response = xhr.responseText;
+      }

**Comment by lgalfaso** [comment]
Are you using a real IE9? (This is, not another IE in IE9 mode)

**Comment by terryliulj** [comment]
IE9 mode,  and real IE9
![ie9](https://cloud.githubusercontent.com/assets/4178443/9297821/ba05c7ca-44d7-11e5-977c-3002b01d1c8d.png)

**Comment by lgalfaso** [comment]
On IE9, the property `response` is not there unless some other library adds
it. Are you using some other library or plugin?

**Comment by lgalfaso** [comment]
Here is a link to MS where they state that the property `response` was
added in IE10
https://msdn.microsoft.com/en-us/library/hh872881(v=vs.85).aspx

**Comment by terryliulj** [comment]
Only recently found to have this problem. Our tester was using real IE9 to test, and found that the browser didn't show any data. So I use IE11 to set IE9 mode for test and debug. When I added these codes, the tester's IE9 can display backend data.

**Comment by terryliulj** [comment]
I'm sorry, I found the problem. Because we used Flexpaper , and it added the response property to XMLHttpRequest!

**Comment by lgalfaso** [comment]
It is outside of Angular scope to work around third party polyfill that work in non-compatible ways.

**Comment by brafkind** [comment]
I am still seeing this issue with Angular 1.4.7 and IE9, IE10, IE11, and IE Edge, so can it please be re-opened?
