### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by bgobi1991** [angular/angular.js#12599]
Hi,
If i am using timeout for 5 sec in my application, is it performance issue ? please let me know about $timeout function

**Comment by pkozlowski-opensource** [comment]
@bgobi1991 the docs for `$timeout` are here: https://docs.angularjs.org/api/ngMock/service/$timeout (did you bump into any particular problems trying to locate this page?).

As for the "performance issue" question, it is impossible to answer based on the info provided. Morover support questions like this one should be directed to a dedicated support channel, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
