### ISSUE TITLE
ngResource: Do not update internal data when HTTP status >= 400 on $save.

### ISSUE THREAD

**Issue by vicary** [angular/angular.js#12596]
I don't see documentations on server-side implementations, especially on error handling.

The API I currently working on, upon errors, returns a JSON object `{"error": "...", "code": 13362}` with HTTP status >= 400, but `$resource` updates internal data with the error context.

If the server is meant to be implemented in a way it returns the original resource data even upon errors, users would then have no obvious way to handle error message and/or codes.

Can we skip the data update when server returns an error status code?

**Comment by gkalpak** [comment]
@vicary, `$resource` will **not** update the instance with the response data upon save error. ([Demo pen][1])
It is something else on your end that is causing the weird behaviour (in similar cases it's been usually some interceptor that does not preperly propagate the error).

If you still think there something wrong with Angular itself, please provide a live reproduction (using CodePen, Plnkr etc), so we can investigate further.

[1]: http://codepen.io/ExpertSystem/pen/mJZmrO?editors=001

**Comment by vicary** [comment]
Turns out it's one of my global error handlers missed the `$q.reject()` statement, closing this and thanks for the hint.
