### ISSUE TITLE
ng-class Directive: Unexpected behavior in Angular 1.4.4

### ISSUE THREAD

**Issue by daniel-nagy** [angular/angular.js#12601]
Hi, I am the author of the unofficial [Material Design Data Table](https://github.com/daniel-nagy/md-data-table) for Angular Material. With the release of Angular 1.4.4 row selection exhibits some unexpected behavior.

The logic for row selection seems to still be working; however, the visual state of the checkbox is not always accurate. I suspect the issue may be related to the `ng-class` directive but I can't say for sure.

```html
<!-- ngClass definition on checkbox element -->
<md-checkbox ng-class="[mdClasses, {'md-checked': allSelected()}]"></md-checkbox>
```

To reproduce this issue visit this [Pen](http://codepen.io/anon/pen/mJgzQK?editors=101) using the 1.4.4 CDN.

1. Select the checkbox in the table header to select all rows.
2. Select one row in the table body
3. Select the checkbox in the table header again to select all rows

You will notice that all rows are selected but the `md-checked` class has not been applied to the checkbox in the table header. Furthermore, if you open the developer tools, select the checkbox element in the table header and type

```javascript
angular.element($0).scope().allSelected() -> true
```

> I don't think angular is defined in the console within Codepen, you may have to run the app locally to do this.

This of course is not the only way to reproduce this issue, just the easiest way to reproduce it every time.

To see row selection working properly you can visit this [Pen](http://codepen.io/anon/pen/zGXWWp?editors=101) using Angular 1.4.3

**Comment by Narretz** [comment]
Hi, thanks for opening the issue. However, the pen doesn't work. There's an angular module error. Can you please make it work?

**Comment by daniel-nagy** [comment]
@Narretz I am not able to reproduce the error, are both pens not working for you? Can you provide a stack trace? Sometimes I get the **loading...** indicator without response but if I just refresh the page it works.

**Comment by Narretz** [comment]
@daniel-nagy Sorry, yes it works, I just had rawgit blocked. I see the error now. Can you please check if it works if you don't use this syntax: `ng-class="[mdClasses, {'md-checked': allSelected()}]"` It's just a shot in the dark, but you don't see this very often, so maybe it's related.

**Comment by daniel-nagy** [comment]
After simplifying the syntax to just `ng-class="{'md-checked': allSelected()}"` the bug is still persistent.

**Comment by gkalpak** [comment]
> I don't think angular is defined in the console within Codepen, you may have to run the app locally to do this.

Unrelated to the actual issue, but you can access the iframe where the actual code is run in CodePen (where you have access to Angular and everything), by selecting the appropriate iframe in the Developer Tools.
(It's different in every browser, but it is possible.)

**Comment by daniel-nagy** [comment]
@gkalpak thanks! that is useful information.

**Comment by Narretz** [comment]
This works in 1.4.7: http://codepen.io/anon/pen/RWeWQd?editors=101
