### ISSUE TITLE
Use function name as injectable name

### ISSUE THREAD

**Issue by remcohaszing** [angular/angular.js#12600]
The syntax for creating a factory is the following:
```js
app.factory('example', function() {
  return {};
});
```

Some style guides, such as [the one by John Papa](https://github.com/johnpapa/angular-styleguide#named-vs-anonymous-functions) mention it is better to use named functions. This makes it easier to debug.
```js
app.factory('example', function example() {
  return {};
});
```

If a named function is passed, the explicit name of the factory seems redundant. Instead the `name` property of the function could be used. This would reduce code duplication.
```js
app.factory(function example() {
  return {};
});
```

Dgeni already uses this method.

The first method should still be supported for minified code.

The similar approach could be used for

###### controllers

```js
app.controller(function ExampleController() {});
```

###### providers

Allow an optional `Provider` prefix to allow a properly named `$get` method.

```js
app.provider(function exampleProvider() {
  this.$get = function example() {};
});
```

###### services

```js
app.service(function example() {});
```

###### decorators

```js
app.config(function($provide) {
  $provide.decorator(function example($delegate) {
    return $delegate;
  });
});
```

###### filters

```js
app.filter(function example() {
  return function exampleFilter(input) {};
});
```

**Comment by bcherny** [comment]
this would be pretty cool, but note that it doesn't work on IE, or in [many other browsers](http://kangax.github.io/compat-table/es6/#function_name_property). it also would not work with coffeescript.

**Comment by pkozlowski-opensource** [comment]
Yeh, this sounds pretty cool, but given limited support in browsers that we need to support, I think we will have to pass on this one :-( 

I would love to have this, but the technology is simply not here... Closing for now.
