### ISSUE TITLE
change angularjs querystring format

### ISSUE THREAD

**Issue by msaleh22** [angular/angular.js#12608]
in angularjs $location.search() function we can get or set querystring with this format:
`http://localhost:7988/app/index.html#!/?brand=Samsung&brand=Apple&brand=LG&orderby=MostPopular`
i want querystring change to this format:

`http://localhost:7988/app/index.html#!/brand-Samsung/brand-Apple/brand-LG/orderby-MostPopular
in fact change: & to / and = to - and if may remove ?
i survey angularjs source and see that if code change to
```
function parseKeyValue(/**string*/keyValue) {
  var obj = {}, key_value, key;
  forEach((keyValue || "").split('/'), function(keyValue) {
    if (keyValue) {
        key_value = keyValue.replace(/\+/g, '%2F').split('-');
      key = tryDecodeURIComponent(key_value[0]);
      if (isDefined(key)) {
        var val = isDefined(key_value[1]) ? tryDecodeURIComponent(key_value[1]) : true;
        if (!hasOwnProperty.call(obj, key)) {
          obj[key] = val;
        } else if (isArray(obj[key])) {
          obj[key].push(val);
        } else {
          obj[key] = [obj[key],val];
        }
      }
    }
  });
  return obj;
}

function toKeyValue(obj) {
  var parts = [];
  forEach(obj, function(value, key) {
    if (isArray(value)) {
      forEach(value, function(arrayValue) {
        parts.push(encodeUriQuery(key, true) +
                   (arrayValue === true ? '' : '-' + encodeUriQuery(arrayValue, true)));
      });
    } else {
    parts.push(encodeUriQuery(key, true) +
               (value === true ? '' : '-' + encodeUriQuery(value, true)));
    }
  });
  return parts.length ? parts.join('/') : '';
}
```

if any way exist that without change source code this occur
or
any solution?

**Comment by Narretz** [comment]
Query strings (https://en.wikipedia.org/wiki/Query_string) use ?, & and =. If you don't have them, it's not a query string, but a clean url: https://en.wikipedia.org/wiki/Semantic_URL. You'll probably need some custom url extraction technique if you want to use urls like that.
In the future, please refer to one of these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-question
