### ISSUE TITLE
enter/leave events not fired in certain circumstances with ng-repeat (animated content outside app root)

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#12617]
I am not sure if this is reproducible with the other directives like ng-if or ng-show/ng-hide, but there was a bug reported in https://github.com/angular-ui/bootstrap/issues/4222 where it turns out the events are not fired, nor the animation running - [here](http://plnkr.co/edit/CjhanwZ1k2B3lVxg6zDh) is a reproduction where it works normally for a defined JavaScript animation with jQuery with ng-repeat, but inside the modal element, it does not log any output.

**Comment by Narretz** [comment]
That's because the modal is outside of the ng-app root element. In that case ngAnimate cannot detect if animations are defined. I'm not sure if this is intentional, or if it should work.

**Comment by Narretz** [comment]
There's the $animate.pin API for that. You should call that after the modal element has been added to the DOM. However, it's currently broken, I'm looking into it.

**Comment by wesleycho** [comment]
Hm, so would you say that it is highly recommended to have the app bootstrapped on `body` or a higher element? I typically just do `angular.bootstrap(document, [...])` myself.

**Comment by Narretz** [comment]
It's always the best bet. But once $animate.pin is fixed, bootstrap ui should use it inside the modal function and pin the modal to the $rootElement. Bascically, all libraries that add fragment DOM like this should do it, to be one the safe side.

**Comment by gkalpak** [comment]
Something to keep in mind wrt `$animate.pin()` is that it is not available prior to `v1.4`, so if you have a version of a library that tries to be compatible with angular `v1.3+`, it might be a problem.

**Comment by wesleycho** [comment]
Got it - we are about to drop 1.3 support in our next release, so that shouldn't be an issue.

**Comment by Narretz** [comment]
The fixes to pin() have landed in master (8f0b48259666c1496970d6ca90decb36d6fa3295) and 1.4.8 (1329e0f1ae4f3c4753cee218598aa8adf0d06650) and will be available in 1.5.0 and 1.4.10.
