### ISSUE TITLE
Disabled button with ngClick still triggers the ngClick with nested elements in MS Edge

### ISSUE THREAD

**Issue by jpzwarte** [angular/angular.js#12611]
http://jsfiddle.net/v7tmLnyp/

In Chrome, Firefox when you click on the *span* in the button, nothing happens. In MS Edge, when you click on the *span* the count increases. If you click in the button, but not on the span (padding of the button), nothing happens.

This obviously severely breaks application logic. Found with angular 1.3.17.

**Comment by jpzwarte** [comment]
This looks to be an Edge specific bug: clicking on the span triggers a click event. If you click in the padding area of the button, nothing happens.

```
<button disabled="disabled" onclick="alert('click')"><span>CLICK ME</span></button>
```

**Comment by Narretz** [comment]
Can you please open a bug with Microsoft for that and link to it here?

**Comment by RyanDawkins** [comment]
Is this a bug for the browser not angular? @Narretz

**Comment by kishoreinvits** [comment]
What version of Angular has this fix? Is there any workAround other than Angular upgrade?

**Comment by kishoreinvits** [comment]
This bug can be closed. It has been fixed on TH2 November Update on Windows(IE Edge)
**References :**
https://connect.microsoft.com/IE/feedback/details/1748050
http://stackoverflow.com/questions/32377026/disabled-button-is-clickable-on-edge-browser

**Comment by jpzwarte** [comment]
Thnx for the update!
