### ISSUE TITLE
ngModel not updating correctly on select multiple on iPhone

### ISSUE THREAD

**Issue by albertvazquezm** [angular/angular.js#12615]
Hi,

The model bound to a select multiple element doesn't update the values correctly on iPhone 6 (ios 8). The same code is working properly in other mobile devices.

AngularJS Version: 1.4.2

There is a fiddle where you can test with your iPhone: http://jsfiddle.net/maku/GV9Ek/

`<select multiple class="chosen-results" ng-model="mapCtrl.filters">
                <option value="a"></option>
                <option value="b"></option>
                <option value="c"></option>
  </select>`

**Comment by petebacondarwin** [comment]
I think this is the same as #13753
