### ISSUE TITLE
Getting error while running my ionic project on devices  

### ISSUE THREAD

**Issue by SUDHAKHAR** [angular/angular.js#12621]
hi ,

  i am getting the following error on my device when running it,where as it runs withour erron on browser and only one of my device and check all the devices but same problem

can any one help me 

 Uncaught TypeError: Object.keys called on non-object ionic.bundle.js:9110
Failed to load resource: net::ERR_CACHE_MISS https://cdn.auth0.com/client/cWQeRf3L4Ength5tIFSrPhrNPUHgO6yQ.js?t1439965186084
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.13/$rootScope/infdig?p0=10&p1=%5B%5D ionic.bundle.js:22980

**Comment by pkozlowski-opensource** [comment]
@SUDHAKHAR please ask support questions using a dedicated support channel, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Thnx!

**Comment by SUDHAKHAR** [comment]
sorry new here ..please delete my post
