### ISSUE TITLE
$Http response not available if listening for a promise twice

### ISSUE THREAD

**Issue by LeleDev** [angular/angular.js#12627]
I'm using the following code in my sample app:
```js
var samplePromise = $http({method: 'GET', url: 'http://sampleurl'})
         .then(
                  function success(response) {
                           console.log(response.data)
                  },
                  function error(response) {
         
                  }
         );

samplePromise
         .then(
                  function success(response) {
                           console.log(response.data)
                  },
                  function error(response) {

                  }
         );
```
I can print to console the response.data content only in the FIRST success function, while in the second I get only 'undefined'. Is this an intended behaviour, or every time a success callback is fired i should be able to access to the response data, and not the first time only?

Thank you in advance

**Comment by pkozlowski-opensource** [comment]
Both should work, just looking at the provided sample. Provide a plunk with a minimal reproduce scenario, otherwise it is not actionable: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submit

**Comment by LeleDev** [comment]
Here you go!
http://jsfiddle.net/HB7LU/16591/

**Comment by pkozlowski-opensource** [comment]
Oh, you are assigning to `simplePromise` a promise that resolves to undefined. I'm not sure what you want to do here, but probably this fiddle will illustrate what I mean: http://jsfiddle.net/ydckcjLf/

Closing, it all works as expected, I guess it is a case of confusion regarding promises usage. Next time try to ask questions on a dedicated support forum if you are not sure that we are talking about a bug in AngularJS: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by LeleDev** [comment]
Ok I've got it, thank you
