### ISSUE TITLE
$httpBackend not calling promise.reject for 4xx and 5xx mock response

### ISSUE THREAD

**Issue by ptlis** [angular/angular.js#12625]
Mock responses with a 2xx or 3xx status code correctly result in the promise resolving correctly, but responses with 4xx or 5xx status codes aren't rejected.

AngularJS 1.4.4
ngMock 1.4.4

[Plunkr demo](http://plnkr.co/edit/GMEQUgWiZ3aUgMCGl97Z?p=preview) using [example code from the documentation](https://docs.angularjs.org/api/ngMock/service/$httpBackend#unit-testing-with-mock-httpbackend) (provided by wafflejock in IRC) demonstrates this problem.

**Comment by pkozlowski-opensource** [comment]
It is not the pb with $http / $httpBackend, but rather the controller example, it should be:

```javascript
$http.get('/auth.py').success(function(data, status, headers) {
    authToken = headers('A-Token');
    $scope.user = data;
  }).error(function() {
    $scope.status = 'Failed...';
  });
```

http://plnkr.co/edit/lQVuGWnO9wYermdldCga?p=preview

**Comment by ptlis** [comment]
Thanks for the quick response @pkozlowski-opensource - however the documentation says that [both those methods are deprecated](https://docs.angularjs.org/api/ng/service/$http#deprecation-notice) - it seems that the .then() method is the suggested way of handling success/error states.

I may be totally wrong, but looking through the docs it seems that this isn't a documentation bug but a problem with ngMock - the same code that fails in tests works correctly in-app.

**Comment by pkozlowski-opensource** [comment]
> I may be totally wrong, but looking through the docs it seems that this isn't a documentation bug but a problem with ngMock - the same code that fails in tests works correctly in-app.

Not sure I follow your line of thought. I've just demonstrated in plunker that the test is fixed by a change in the controller. What makes you think that this is a bug in $httpBackend?

Depreciation are another story - @petebacondarwin if we are serious about depreciating .success and .error we should probably remove it from the documentation as well...

**Comment by ptlis** [comment]
I would expect the failure callback attached with then() to be called when the request errors/fails (receiving a 4xx/5xx status code) - [as the documentation says](https://docs.angularjs.org/api/ng/service/$q#the-promise-api) "regardless of when the promise was or will be resolved or rejected, then calls one of the success or error callbacks asynchronously as soon as the result is available."

In addition to the fact that they're deprecated, there is a concrete reason that I can't use .success() & .error() - in the real code I'm working with to be able to chain the promises but from what I can tell these methods don't behave the same way as .then() does.

It looks like the discussion around deprecation started in bug #12625 for the same rationale for me needing to use .then(). I could look at manually handling this throughout my application but that would be error prone and just a pain to do - particularly when I'm pretty sure that then() should already handle this.

**Comment by pkozlowski-opensource** [comment]
> I would expect the failure callback attached with then() to be called when the request errors/fails (receiving a 4xx/5xx status code) 

But in this particular test there is a failure detected before and promise handler have a chance of being invoked...

**Comment by ptlis** [comment]
I think we're talking cross-purposes, let me see if I can explain the essence of why I think it's a bug.

As described in [the documentation](https://docs.angularjs.org/api/ng/service/$q#the-promise-api):

> ```then(successCallback, errorCallback, notifyCallback)``` – regardless of when the promise was or will be resolved or rejected, ```then``` calls one of the success or error callbacks asynchronously as soon as the result is available.

With a real $httpBackend instance, HTTP responses that result in 4xx and 5xx responses result in the failure callback being executed - with a mock $httpBackend and identical (but mocked) responses don't result in the callback being called.

The bug is this deviation in behaviour - the mock isn't behaving in the same manner as the component it's substituting. I have no idea why this is the case - but whatever the cause is, the problem is that it's not replicating the behaviour of a real $httpBackend instance.

**Comment by pkozlowski-opensource** [comment]
@ptlis we are mixing issues, indeed. Could you just please share a _minimal_ plunk that shows the issue, using `.then` instead of `.success` / `.error` to illustrate what you think is a bug? It is kind of hard to have one plunk and discuss another pb....

**Comment by ptlis** [comment]
@pkozlowski-opensource I'm really sorry for wasting your time - having made a [simplified testcase](http://plnkr.co/edit/sxHwszbSrqLRvesPxsrf?p=preview) I found that it actually works perfectly. Further investigation revealed that I had a misbehaving interceptor which was preventing the request from being rejected.

Sorry about this!

**Comment by pkozlowski-opensource** [comment]
@ptlis no worries. Actually it happens quite often that the true pb becomes obvious as soon as we spend time to prepare a reduced test case. This is why we are insisting on providing minimal reproduce scenarios.

Thnx for bearing with me, glad that you've made it work on your end.
