### ISSUE TITLE
feat(ngPromise) CSS based promise awareness for elements 

### ISSUE THREAD

**Issue by mchlbrnd** [angular/angular.js#12630]
Hi all,

On a recent project my team mainly applied CSS (hiding, animatons) based on promise outcomes . Our goal was to support compound CSS behavior based on a combination of multiple promises.

We wanted to avoid adding logic to our controller/directives to process these outcomes in order to bind to ngClass, manipulate $element or call $animateCss. Therefore we ended up implementing an attribute directive. The directive and demo are available at: https://github.com/mchlbrnd/angular-promise. 

Looking forward to any ideas and suggestions to improve this! Please shoot!

Cheers,
Michael

**Comment by Narretz** [comment]
Hi @mchlbrnd thanks for showing this. Personally, I think it's good as an external module. Do you plan to make the state classed customizable? Because I'd like my classes to reflect the element's state, rather than the promise state.

**Comment by mchlbrnd** [comment]
Hi @Narretz 

I have been pondering over this , but did not work it out yet. Agreed that reflecting element state through classes is valuable.

My approach would be an ngPromiseOptions attirbute  which maps promise outcome keys (initial (?), pending, resolved, rejected and settled) to your own classes. As a fallback the proposed ng-promise- prefixed classes should be used. Object promises should work similarly. However, the ngPromised attribute is not assigned, but ngPromiseOptions is used to add the customized classes.

**Comment by mchlbrnd** [comment]
@Narretz: I'm very interested in your feedback on https://github.com/mchlbrnd/angular-promise/tree/feature/customizable-promise-classes (if you find the time ;))

**Comment by mchlbrnd** [comment]
Published on npmjs: https://www.npmjs.com/package/angular-css-promise

**Comment by Narretz** [comment]
I think that's ok as a 3rd party module.
