### ISSUE TITLE
Angular 1.2.28 - ngModel.$isEmpty always true when using ng(False|True)Value

### ISSUE THREAD

**Issue by KrekkieD** [angular/angular.js#12648]
See [plunkr](http://plnkr.co/edit/036b81zmtuzq2GDKcokF?p=preview). Source comes from docs, tweaked to show `$isEmpty` value.

First checkbox uses simple model, using `true` or `false` as value.

Second checkbox uses `ng-true-value` and `ng-false-value`, properly setting the `checked` state and `$viewValue`, but running the `$viewValue` through `ngModel.$isEmpty` always returns true.

Changing that to use `$modelValue` instead fixes the problem, as seen in [this plunkr](http://plnkr.co/edit/WtMWWqWyX7yQwlO2usHX).

However, updating that last plunkr to angular 1.4.4 (as [seen here](http://plnkr.co/edit/PKVBKO0zkjr64cXT06L8)) breaks it again, and now suddenly `$isEmpty` always gives us `false`.

Patching that back to `$viewValue` as [seen here](http://plnkr.co/edit/1IJZBZN3gXiOOPNKDmtH) will make it work again.

As `$isEmpty` is used with `$viewValue` by validators, this creates an issue when combining it with `required`, as seen in [this form](http://plnkr.co/edit/amF5L5gyYw8PxvsjO0iu), which is never valid for submission.

I believe this is because in `checkboxInputType()` the `trueValue` and `falseValue` are always of type `string` (it's not an `expression` you can put as attribute value as this was introduced later, possibly 1.3.x). Therefore the value of those vars remains identical to the string provided in the attribute (i.e. `"yes"` and `"no"`) whilst the `$viewValue` is always a `boolean`. Therefore the statement `return value !== trueValue;` can be seen as `return 'boolean' !== 'string'` which is always true.

**Comment by Narretz** [comment]
So the result of isEmpty returning false values is that the checkbox doesn't get checked when set from the model, right? Just asking because you don't mentiond it explicitly.

**Comment by KrekkieD** [comment]
It's not necessarily just that, I haven't tried that. But create a form, stuff in a checkbox with `ng-true-value` and `ng-false-value`, and add a `required` attribute. It will never pass validation, because the `isEmpty` value returned is never correct.

**Comment by KrekkieD** [comment]
See here: http://plnkr.co/edit/siPyBPlTuwFTeoQdTO4U

**Comment by Narretz** [comment]
This is essentially a bug that is fixed in 1.4, but wasn't fixed in 1.2.x. We don't usually fix bugs in 1.2, but you can use this workaround: http://plnkr.co/edit/H0peV7ExzR4m6LPSwtnX?p=preview

Essentially, passing the viewValue to isEmpty is the right thing, just the check inside the checkbox input type is wrong. The plnkr adds a custom input directive that overwrites the isEmpty fn for the modelController.

**Comment by Narretz** [comment]
1.2.x doesn't receive bug fixes anymore. Closing.
