### ISSUE TITLE
Document the options parameter of $animate functions

### ISSUE THREAD

**Issue by djdmbrwsk** [angular/angular.js#12645]
Unless I missed it, there is no documentation explaining the `options` parameter that is optional in a bunch of the `$animate` service's functions. Ex:

```js
$animate.enter(element, parent, [after], [options]);
```

I just spent a bit digging through the source to finally find you can pass in an object like this:

```js
{
  addClass: 'some-new-class',
  removeClass: ' some-old-class'
}
```

**Comment by Narretz** [comment]
@djdmbrwsk Would you like to submit a PR which adds the info to the docs?
