### ISSUE TITLE
ngdocs reference all @params as type Function where an annotation array can be used

### ISSUE THREAD

**Issue by cgatesman** [angular/angular.js#12641]
Anywhere a parameter can optionally be an annotation array as apposed to a simple Function, the JSDoc should reflect that; otherwise, it can cause warnings to be shown in some IDE when using the function.

```javascript
/**
 * ...
 * @param {Function|Array} function
 */
```

This documentation problem exists in many places, but one example is on `@name $provide#decorator`.

**Comment by petebacondarwin** [comment]
This was fixed at 6874cca1589a2a4c28f3caa036897c70e57763ef
