### ISSUE TITLE
Cannot read property 'classes' of undefined

### ISSUE THREAD

**Issue by shahidmohammed** [angular/angular.js#12647]
we have been work on Angular 1.3.2 and now we have to deploy the application at customer end, we suddenly get the errors and application stops working.
can somebody help list the compatible Angular components for version Angular 1.3.2? 

am stuck, I appreciate your help.

**Comment by caitp** [comment]
This is more of a support question, and while we'd love to help, there are a lot of details missing. You might consider asking on #angularjs on irc.freenode.net, or try the gitter.im chat room linked from the readme. It would be easier to help if a stack trace or reproduction was provided

**Comment by shahidmohammed** [comment]
Thanks for the prompt reply.

Here is the stack trace:
"Cannot read property 'classes' of undefined at W (http://localhost:28386/app/lib/angular-animate/angular-animate.min.js:8:396)'

TypeError: Cannot read property 'classes' of undefined
    at W (http://localhost:28386/app/lib/angular-animate/angular-animate.min.js:8:396)
    at http://localhost:28386/app/lib/angular-animate/angular-animate.min.js:20:307
    at http://localhost:28386/app/lib/angular-animate/angular-animate.min.js:8:48
    at h.$digest (http://localhost:28386/app/lib/angular/angular.min.js:121:393)
    at h.$apply (http://localhost:28386/app/lib/angular/angular.min.js:123:406)
    at p (http://localhost:28386/app/lib/angular/angular.min.js:80:284)
    at J (http://localhost:28386/app/lib/angular/angular.min.js:84:338)
    at XMLHttpRequest.t.onload (http://localhost:28386/app/lib/angular/angular.min.js:85:367) undefined

I appreciate your help.

**Comment by Narretz** [comment]
You should provide a stack trace using the unminified version of angular.js. Also, you should use the latest angular 1.3 version, which is 1.3.18. Also make sure all the other modules, such as angular-animate, use the exact same version.

**Comment by Narretz** [comment]
Please reopen when you can provide more info.
