### ISSUE TITLE
Wrong month translations for RU_RU locale in the localized file

### ISSUE THREAD

**Issue by SergeyKoval** [angular/angular.js#12642]
In russian language there are several grammar cases for nouns. Monthes are translated in the incorrect grammar case. Here is correct values:
"MONTH": [
      "\u044f\u043d\u0432\u0430\u0440\u044C",
      "\u0444\u0435\u0432\u0440\u0430\u043b\u044C",
      "\u043c\u0430\u0440\u0442",
      "\u0430\u043f\u0440\u0435\u043b\u044C",
      "\u043c\u0430\u0439",
      "\u0438\u044e\u043d\u044C",
      "\u0438\u044e\u043b\u044C",
      "\u0430\u0432\u0433\u0443\u0441\u0442",
      "\u0441\u0435\u043d\u0442\u044f\u0431\u0440\u044C",
      "\u043e\u043a\u0442\u044f\u0431\u0440\u044C",
      "\u043d\u043e\u044f\u0431\u0440\u044C",
      "\u0434\u0435\u043a\u0430\u0431\u0440\u044C"
    ]

**Comment by Narretz** [comment]
Please see the "Localization issue" note here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-found-an-issue

This needs to be fixed in the Google Closure i18n library first. If it's fixed there, we can import the new files.
