### ISSUE TITLE
feat(ngModelOptions): make defaults globally customizable

### ISSUE THREAD

**Issue by NicBright** [angular/angular.js#12644]
Hi there,

in the project I'm currently involved in, we basically always want to have "allowInvalid: true". For now, we've created a wrapper for our form components which takes care of that (inside its template we just add  `ng-model-options="{ allowInvalid: true }"` and we're good to go).

**Unfortunately, this often leads to the following problem:**

Some fields need other stuff from ng-model-options too (like e.g. setting `updateOn: 'blur'`). What really happens a lot now is the fact that the developer is not aware that he also has to specify `allowInvalid: true` again. Everytime a developer forgets to add this, we end up with invalid values not being written to the model, which leads to a bad user experience in our case (because a user may navigate back and forth between forms and the user should not lose any (even invalid) input while doing so).

This problem could be avoided by adding a new feature:

*As a developer,
I would like to be able to globally specify defaults for ngModelOptions,
in order not to experience the pitfalls described above.*

Thank you very much for reading and considering this.

Regards,
Nicolas

**Comment by Narretz** [comment]
There's a PR that implements global config and inheritable options: https://github.com/angular/angular.js/pull/10922 It's planned for 1.5

**Comment by NicBright** [comment]
Thank you very much for pointing this out. I didn't know about it.
