### ISSUE TITLE
Can't build Cygwin and Windows 10 without --force

### ISSUE THREAD

**Issue by jrgleason** [angular/angular.js#12649]
I am trying to build and getting....

    $ grunt package
    Running "shell:npm-install" (shell) task
    Warning: EINVAL, invalid argument Use --force to continue.

    Aborted due to warnings.

Going to try and troubleshoot

    grunt-cli v0.1.13
    grunt v0.4.5

**Comment by jrgleason** [comment]
In addition when I do use --force I get the following...

     >> build/angular-message-format.js minified into build/angular-message-format.min.js
    build\angular.js:4437: WARNING - Throw expression is not a minErr instance.
          throw err;
          ^

    build\angular.js:10656: WARNING - Throw expression is not a minErr instance.
            throw e;
            ^

    build\angular.js:12125: WARNING - Throw expression is not a minErr instance.
        throw e;
        ^

    build\angular.js:15989: WARNING - Throw expression is not a minErr instance.
            throw e;
            ^

    0 error(s), 4 warning(s)
    >> build/angular.js minified into build/angular.min.js


But it does in fact finish

**Comment by jrgleason** [comment]
Could it be related to this line in the gruntfile...

    "npm-install": {
        command: path.normalize('scripts/npm/install-dependencies.sh')
      },

And the fact that I am on windows w/ cygwin (aka paths getting hosed)?

**Comment by lgalfaso** [comment]
I do not have access to this environment, but if you can figure this out
and create a clean PR, I see no problem in merging it

**Comment by Narretz** [comment]
I think this is is only half the solution. You'll probably run into https://github.com/angular/angular.js/issues/11143 after this is fixed

**Comment by Narretz** [comment]
Actually, the path.normalize should handle different platform file paths, so it's probably a different problem. Can you run the command --verbose?

**Comment by gkalpak** [comment]
`shell:npm-install` has been re-implemented in #12792.
@jrgleason, can you test if your issues are still there with the code on master ?

**Comment by gkalpak** [comment]
Closing since the part that was causing issues has been re-implemented and there hasn't been any response for over a month. Feel free to re-open, if you are still facing this problem.
