### ISSUE TITLE
View transition animations break with single ng-animate-ref 1.4.4 and snapshot

### ISSUE THREAD

**Issue by roblouie** [angular/angular.js#12655]
When using a view transition animation and ng-animate-ref, if you have only a single ng-animate-ref it breaks the view transition animation.

Take this lightly modified version of the ng-animate-ref example from the Angular documentation. I have modified it to just show a link to a single record rather than a list.  Notice the page sliding is no longer working properly:
http://plnkr.co/edit/n5WPBEyF04WxAEb2bnFi?p=preview

By adding an empty span with a nonsense ng-animate-ref, the issue goes away:
http://plnkr.co/edit/ua4e00iUajeh0dcu7UF9?p=preview

The issue also resolves by simply reverting to 1.4.3:
http://plnkr.co/edit/Lq9AoWo6Hz3qpCbNie92?p=preview

Updating to snapshot version does not resolve the issue.

**Comment by matsko** [comment]
Here's a demo with a patch that will go into 1.4.5: http://plnkr.co/edit/1gTNNLBEPwiDlJYXxudu?p=preview

**Comment by matsko** [comment]
I'm super happy to see you're using the anchoring feature :)
