### ISSUE TITLE
Angular.merge() fails on scope merge

### ISSUE THREAD

**Issue by NickBolles** [angular/angular.js#12653]
When performing angular.merge() on an object containing a $scope it fails with 
"RangeError: Maximum call stack size exceeded" 

.Merge() is attempting to deep copy the scope. Which just doesn't work. Angular.copy() states that copying states is not supported. 

I was going to submit a PR but i'm not quite sure what the behavior should be. Should it just set a reference to the scope on the new object? (this is what I, as a user, would prefer) or skip it? Whatever it is I don't think it should throw an exception

CodePen:
http://codepen.io/anon/pen/eNwxYj

This has been handled with Dates and RegExp in the following issues:
 #12409 #11974 #11720 #10519

**Comment by Narretz** [comment]
Difficult case. I think in that case the doctrine applies that the angular.* functions are not universal and should not be adjusted for every use case. Imo We should document this clearly and not support merging scopes.

**Comment by NickBolles** [comment]
What would be the behavior of merge then? It would just skip that property? Would it be bad to just set a reference to the scope on the new object? I understand what your saying that the angular.* functions aren't meant to be universal. But it seems like a fairly trivial operation to set a reference to the scope in my opinion.
Like I said I can submit a PR for this. just not quite sure which way to go.

**Comment by gkalpak** [comment]
IMO, setting a reference to the scope is **not** the correct behaviour, since `merge()` is supposed to _"deeply extend"_. 
Silently skiping the property, also obscures things.

I would prefer throwing an error (same as `angular.copy()` when trying to copy `Window` or `Scope` objects).

**Comment by NickBolles** [comment]
@gkalpak okay. I agree. Setting a reference isn't extending it. 
I will put a PR together that documents that .merge() doesn't support scope merging and throw an error.

**Comment by lgalfaso** [comment]
Adding support for scopes and merge can cause more issues than what it solves. What should happen if the source and the target are scopes? Now, the current error is not the best and would be nice if someone wants to create a PR that would throw a better error when a scope is found
