### ISSUE TITLE
How to $apply without forcing $render on tests

### ISSUE THREAD

**Issue by mrodrigues** [angular/angular.js#12667]
I'm trying to test a `$watch(someValue, listener)` call in library which overrides the `ngModelController`'s `$render` method. Unfortunately, it seems that although the `listener` is never called, the `$render` is, either when calling `$rootScope.$apply()` or `$rootScope.$digest()`.

Is it possible not to force the `$render` function to be called? Is there a better way to test this watcher? Since I don't own this library, should I recommend them not to override the `$render` function?

**Comment by Narretz** [comment]
There isn't really enough information to see what exactly is happening. In any case, for support questions please use the mailing list, the IRC or Stackoverflow. You should also provide a demo of your code.
