### ISSUE TITLE
Please Fix It? AngularJS v1.2.28 Line 22151

### ISSUE THREAD

**Issue by c3stream** [angular/angular.js#12663]
})(window, document);

@ngdoc directive
@name select

bug?
no minfy angular.js
Line 22151

**Comment by Narretz** [comment]
This gives me no idea what should be fixed. Please provide more information: what behavior do you see, what are you trying to achieve, which browser etc.

**Comment by Narretz** [comment]
Without concrete information we cannot do anything about this.
