### ISSUE TITLE
Angular 1.4.4, $parse, assign function does not return the value set

### ISSUE THREAD

**Issue by fcaballero** [angular/angular.js#12675]
Hi guys,

I was using angular 1.3.15 and I had this code:
```javascript
function getDataRoot(data, expression){
      var getter = $parse(expression);
      
      return getter(data) || getter.assign(data, {});
}

var data = {details: {orderId: ''}};
console.log(getDataRoot(data, 'details')); // should return: {orderId: ''}
 console.log(getDataRoot(data, 'address')); // should return a new object {}
```
The function above always returned a value either an existing or a new one object, because getter.assign always returned the value set, now I have upgraded to angular 1.4.4 and getter.assign no longer return anything.

Here is an [example](http://plnkr.co/edit/OQq0FLonOhr3ZvzOVBEH?p=preview), just change the versions and you will see the issue.   

Cheers,
Fabián

**Comment by lgalfaso** [comment]
Even when the value returned by `assign` is undefined, the bug looks very
reasonable and should be a simple fix. Will aim at fixing this for 1.4.5

**Comment by fcaballero** [comment]
Thank you guys! ;)
