### ISSUE TITLE
ng-show is not working when ng-class is having array expression

### ISSUE THREAD

**Issue by vinayk406** [angular/angular.js#12674]
ng-show is not working (angularjs version 1.4.4) when ng-class is having array expression

Here is the plnkr to demonstrate the issue. 

http://plnkr.co/edit/qNTsC8sWS7b1u76zvfbO?p=preview

**Comment by frfancha** [comment]
In your plunker your controller is not defined, and this is the error message your got in the console

**Comment by vinayk406** [comment]
Sorry for the wrong plnkr. 

Here is the updated plnkr. http://plnkr.co/edit/qNTsC8sWS7b1u76zvfbO?p=preview

When we remove the ng-class expression every thing work as expected. 

In the function addRemoveClassesPostDigest at line 4876, elements are added to the postDigestElements and then the classes are validated.

When the classes to be added or removed are not valid classNames, elements are not removed from the postDigestElements. Because of which function to apply the classes is never registered (line 4903)

**Comment by frfancha** [comment]
I have tried different things in your plnkr, and I was able to reproduce only combining an empty string and a null or undefined in the array. USing only null or only empty string works. If you can avoid mixing both you will by-pass the problem.
The minimum to reproduce (without explicit controller) is:
<body ng-app>
  	<div ng-class="[null, '']"></div>
  	<div ng-show="show">on show</div>
  	<div ng-show="!show">on hide</div>
</body>
(only including angular, no css, no animate)

**Comment by vinayk406** [comment]
I can't do that because the values in my case will be dynamic in nature. 

This used to work with angular 1.4.3. Only with angular 1.4.4 we are facing this problem.

**Comment by Narretz** [comment]
Looks like it's caused by https://github.com/angular/angular.js/commit/0d6fc2dce57ac60dfebba6eefb571ef9afcd2189
Though I'm not sure why the element with ngClass affects the elements with ngShow.

**Comment by petebacondarwin** [comment]
The code is adding an element to the postDigestQueue but then never attaching the handler for removing it since it deems that no valid CSS class names were added. This blocks the subsequent `ng-show` directive etc from getting to their own postDigestQueue items.

I think we just need to make sure we only add to the queue if the CSS class names are valid.

**Comment by petebacondarwin** [comment]
I think I have a fix at #12725 
@vinayk406, @frfancha and @Narretz can you take a look?

**Comment by vinayk406** [comment]
@petebacondarwin, With the changes the example in plnkr is working fine.
But the code changes in your pull request and the angular.js file which is loaded in plnkr look different.

**Comment by petebacondarwin** [comment]
:-) yes I changed the fix but forgot to update the plunger.

**Comment by vinayk406** [comment]
@petebacondarwin, Thanks for the fix.
