### ISSUE TITLE
$animateCss can't disable animations.

### ISSUE THREAD

**Issue by wawyed** [angular/angular.js#12685]
It would appear that when I call $animate.enabled(false) the code in $animateCss doesn't seem to be affected by it, meaning that it will add the animation classes regardless of the status of animationsEnabled.

Is this intended? If so, how do I disable animations completely?

**Comment by matsko** [comment]
Yes this was something we came across with material and we plan on adding it in for 1.4.5

**Comment by wawyed** [comment]
Brilliant, I'll wait for 1.4.5 then :)
