### ISSUE TITLE
using tabs in angularjs

### ISSUE THREAD

**Issue by darkmanAmazigh** [angular/angular.js#12684]
I have big forms with lots of data, so I'd like tabs with chunks of data for each tab.
in any tab i have an html forms whish i want to send his value via angularJS service to REST service, my forms is prefilled using ng-init and apache velocity, 

My problem is when i send the data i have only the data of the active tab, can someone help me to get all value of all forms in each tab or any idea to do this

my js code for rooting

      app.config([ '$routeProvider', function($routeProvider) {
      $routeProvider
            .when('/xlsparams', {templateUrl : xlsparamsTemplate,   controller : xlsparamsController})
            .when('/alternative', {templateUrl : alternativeTemplate,   controller : alternativeController})
            .otherwise({redirectTo : '/xlsparams'}); 
      } ]);

html code

      <div  ng-controller="generationController">
             <ul class="nav nav-tabs">
                   <li id="xls" class="active"><a href="#xlsparams">xls</a></li>
                   <li id="alt"><a href="#alternative">alternative</a></li>
            </ul>
            <div ng-view></div>
            <button class="form-control input-sm btn-primary" ng-click="generate()">generate</button>
     </div>

**Comment by Narretz** [comment]
Please use one of these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by darkmanAmazigh** [comment]
I have used jQuery
