### ISSUE TITLE
Page load is very slow in IE11 and EDGE but fast enough in IE10/Chrome/Firefox

### ISSUE THREAD

**Issue by skumarone** [angular/angular.js#12688]
We have an application developed using followings:

1. AngularJS 1.2.17
2. jQuery 1.10.2
3. Freedom 2.0
4. WebAPI

We are using <b>ngGrid</b> to display data and <b>ngAnimate</b> for animations.

Our application is running in IE10/Chrome/Firefox without any performance issue. But its very slow in loading a page in IE11/EDGE in following scenario-

There is a dropdown having three options and each option loads a new view (see the images below).  In IE11 and EDGE it takes <b>20-30 seconds</b> to load the new view. But in IE10/Chrome/Firefox it takes 1-2 seconds.

Screenshot: Dropdown
![dropdown](https://cloud.githubusercontent.com/assets/13990601/9510881/188ecd42-4c8e-11e5-8d4c-7dba799245c3.JPG)

Screenshot: The new view loaded when an item is selected from the dropdown
![view](https://cloud.githubusercontent.com/assets/13990601/9510882/1d604512-4c8e-11e5-9444-9a64a02fc26c.JPG)

The view has date controls and a simple text box. For date controls we are using <b>"ui-select2"</b> directive https://github.com/angular-ui/ui-select2 . Which is using <b>ng-repeat</b> to populate the Months/Days/Years. 

<span style="">
&lt;select ui-select2=&quot;{minimumResultsForSearch: -1}&quot; class=&quot;adcSelect adcSelectDayWidth&quot; ng-model=&quot;day&quot; data-placeholder=&quot;DD&quot; ng-change=&quot;monthYearChanged()&quot;&gt;
         &lt;option value=&quot;&quot;&gt;&lt;/option&gt;
         &lt;option ng-repeat=&quot;d in days&quot; ng-value=&quot;d&quot;&gt;{{d}}&lt;/option&gt;--&gt;
&lt;/select&gt;
</span>

There is a ng-grid on the page which is initially hidden (using ng-show) as there is no data to display. The data is fecthed from server only when user clicks search. 

<b>IE 11 Profile:</b>

![ie11_slowness_profile](https://cloud.githubusercontent.com/assets/13990601/9511569/ba02e116-4c95-11e5-8abd-8e61644c4d15.png)

What I tried to improve the performance <b>(still have performance issue) - </b>

1. I have followed the solution proposed in https://github.com/angular/angular.js/issues/12076 to populate the date dropdowns instead of using <b>ng-repeat</b>. 

2. Also I removed the "closeAnimation" call from <b>"performAnimation"</b> method of angular-animate.js because during my investigation I found it taking more time and I saw a comment in the "performAnimation" mention which says that "closeAnimation" call is required for IE8 + IE9 only, our application doesn't support IE8 and IE9. We are still analizing the impact of removing <b>"closeAnimation".</b>

After these 2 changes the new view is taking <b>10 seconds</b> to load. Which is not acceptable.

**Comment by skumarone** [comment]
<b>IE 11 Profile:</b>

![ie11_slowness_profile](https://cloud.githubusercontent.com/assets/13990601/9511569/ba02e116-4c95-11e5-8abd-8e61644c4d15.png)

**Comment by matsko** [comment]
1.2 is quite old. Is there anyway you can upgrade to 1.4?

**Comment by vitaly-t** [comment]
Perhaps even upgrading to 1.2.28 would be a good start, to see if that makes any difference ;)

**Comment by skumarone** [comment]
@matsko - We can't upgrade to 1.4.

@vitaly-t  - I will try upgrading to 1.2.28 and will update you.

**Comment by skumarone** [comment]
@vitaly-t Upgraded to AngularJS 1.2.28 but no improvement in the performance.

**Comment by Narretz** [comment]
How big are the select lists? In issue #12076 it's said the IE handles huge select list not very well. If that is the case in your application, you have the option to either reduce the number of options or to patch angular to use documentFragments with option elements. Since 1.2.x is unsupported / legacy, there won't be any patches from our side.
