### ISSUE TITLE
Angular.copy() does not work properly for generic ArrayBuffer type.

### ISSUE THREAD

**Issue by noKid** [angular/angular.js#12680]
When trying to copy an existing ArrayBuffer without using any specific view, angular.copy returns an empty / unusable object.

    var genericArray = new ArrayBuffer(512);  // ArrayBuffer {byteLength:512}

    var copyArray = angular.copy(genericArray);  // Wrong - Object{}
    var subArray = genericArray.slice(0);  // Correct - ArrayBuffer{byteLength:512}

( [JSFiddle to test](http://jsfiddle.net/HB7LU/16833/) )

I think either angular.copy should use [ArrayBuffer.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/slice) (Polyfills are available for old browsers) or, at least, throw a warning to the user indicating that an ArrayBufferView must be used. 

It can leads to misunderstanding of some "simple" pieces of code.

    // Following HTTP mock will return incorrect value because of angular.copy.

    $httpBackend.whenGET(/.*/).respond(
        function() {
            var zip = new JSZip();
            zip.file("nested/hello.txt", "Hello World\n");
            var archive = zip.generate({type:"arraybuffer"});
                    
            return [200, archive, {
                'Content-Type': 'application/zip',
                'content-transfer-encoding': 'binary'
            }];
        }
    );

**Comment by Narretz** [comment]
Since the built-in angular.x functions are specifically made with the core's need in mind, I have marked this as a feature rather than a bug.

**Comment by gkalpak** [comment]
Support for `ArrayBuffer` has been added with #13640.
It should work as expected on the `v1.5.x` branch.
