### ISSUE TITLE
ng-show doesn't work properly when radio button input is used within ng-repeat 

### ISSUE THREAD

**Issue by ssameer07** [angular/angular.js#12681]
I am using a radio input within ng-repeat which works....but i  want to show a div under the selected image...it doesn't show up...
 here's the code...
<code>

	<div class="col-sm-12">
		<input type="radio" ng-model="data.selectedOption" value="{{index}}" name="default" />
		<div ng-show="data.selectedOption =='{{index}}'">Hello</div>
	</div>
</code>

i tried ng-if too...but it also doesn't work...

**Comment by frfancha** [comment]
This is only an extract of your code, to help you we need the full (but minimal) code necessary to reproduce the problem. Ideally in a plnkr.

**Comment by Narretz** [comment]
This looks like a support questions. Please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
If you think you've found a bug, you can open a new issue. Thanks!
