### ISSUE TITLE
Date filter returns wrong week (calculated with wrong year)

### ISSUE THREAD

**Issue by marcelboelen** [angular/angular.js#12698]
Angular 1.4.4

Function with error: weekGetter(size) line 18727

    function weekGetter(size) {
       return function(date) {
          var firstThurs = getFirstThursdayOfYear(date.getFullYear()),
             thisThurs = getThursdayThisWeek(date);

          var diff = +thisThurs - +firstThurs,
             result = 1 + Math.round(diff / 6.048e8); // 6.048e8 ms per week

          return padNumber(result, size);
       };
    }

Instead:
Use the year of the ThursdayThisWeek date to calculate the week instead of the year of the date (day) that is chosen. Fix is testable with week 1 of 2015 (previously week 53 of 2014 was generated when monday 29 Dec tuesday 30 Dec or wednesday 31 Dec were chosen).

    function weekGetter(size) {
       return function(date) {
          var thisThurs = getThursdayThisWeek(date),
             firstThurs = getFirstThursdayOfYear(thisThurs.getFullYear());
     
          var diff = +thisThurs - +firstThurs,
             result = 1 + Math.round(diff / 6.048e8); // 6.048e8 ms per week

          return padNumber(result, size);
       };
    }

However, this does not fix the issue when displaying year and week together with the ww/yyyy format.
Results:
- week 52 of 2014 = 52/2014
- week 1 of 2015 = 01/2014 (when selecting monday 29 Dec tuesday 30 Dec or wednesday 31 Dec)
- week 1 of 2015 = 01/2015 (when selecting thursday 1 Jan or Friday 2 jan etc..)
- week 2 of 2015 = 02/2015

Possible solution (requires discussion)
add weekyear date format i.e. wyyyy, wyy, wy next to the yyyy, yy, y date formats that represent the year of the week selected instead of the year of the date selected.

**Comment by lgalfaso** [comment]
This was discussed several times, and would be best to align to http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table

That said, the current behavior does align with the table above, and any PR that would implement this, is welcome.

Closing in favor of #10977

**Comment by marcelboelen** [comment]
I'm missing the 'year week' symbol in the [Date Field Symbol Table](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table). I don't know if a year week symbol even exists.

[#10977](https://github.com/angular/angular.js/issues/10977) disusses how a week must be calculated by using or not using ISO-8601.

The problem that i'm describing is about the calculation of the first week of the year depending on which day of the week is selected. Example using the week of dec 2014/jan 2015.

- monday 29 (Returns week 53)
- tuesday 30 (Returns week 53)
- wednesday 31 (Returns week 53)
- thursday 1 (Returns week 1)
- friday 2 (Returns week 1)

These dates should return week 1 as week 1 is the first week of the year with a Thur, according to [https://code.angularjs.org/1.4.4/docs/api/ng/filter/date](https://code.angularjs.org/1.4.4/docs/api/ng/filter/date)
The above behavior is not the behavior described, nor is it behavior you want. It must be either week 53 or week 1 for all the days in this week.

If I understand correctly, you don't want half weeks assigned to a weeknumber!
28 dec (sunday) 2014 till 31 dec (wednesday) 2014 as week 53. (4 days)
1 jan (thursday) 2015 till 3 jan (saturday) 2015 as week 1 (3 days)

**Comment by lgalfaso** [comment]
@marcelboelen I do not understand your assertion
> I'm missing the 'year week' symbol

The symbol **w** is week of the year.

The other assertion is clear, all days in a week must belong to the same week number (this being on the year that the Thursday is at). If this is not the case, feel to write this same case at #10977 or better, create a PR :)

**Comment by marcelboelen** [comment]
@lgalfaso I'll explain the missing year week symbol.

Example by using the date format ww/yyyy. Where <b>ww</b> is the symbol for week with 2 digits and <b>yyyy</b> is the symbol for the year with 4 digits.

When selecting a day in the week that belongs to the previous year, like wednesday 31 december 2014, the year will be, as expected, <b>2014</b>. The week will be <b>01</b>, assuming that the issue about the week number in the post above is fixed.

Both week and year are calculated using the day by using the <b>ww</b> and <b>yyyy</b> symbols. This means that the year is a <b>year day</b> (calulated with the day).

I'm missing a <b>year week</b> symbol and calculation. as the <b>year week</b> of the example will be 2015 (the week of wednesday 31 december is the first week of 2015. ie: 01/2015).

so:
- year calcuation with the day (symbol: <b>yyyy</b>):
   - wednesday 31 december 2014 will be : 01/2014
- year calcuation with the week (symbol: <b>unavailable</b>):
   - wednesday 31 december 2014 will be : 01/2015

**Comment by lgalfaso** [comment]
@marcelboelen ok, but I think you are talking about the **YYYY** symbol in the table (that is not implemented and would be a nice addition).

**Comment by marcelboelen** [comment]
@lgalfaso ahh. i totally missed that symbol in the table:

> Year (in "Week of Year" based calendars). Normally the length specifies the padding, but for two letters it also specifies the maximum length. This year designation is used in ISO year-week calendar as defined by ISO 8601, but can be used in non-Gregorian based calendar systems where week date processing is desired. May not always be the same value as calendar year.

In that case, the symbol does exists and the implementation would be a nice addition
