### ISSUE TITLE
Define templates without <script> or an external file

### ISSUE THREAD

**Issue by juschu** [angular/angular.js#12690]
Definig templates with `<script type="text/ng-template" id="tmplName"></script>` already works (more or less).
But why are you forcing us to put HTML inside of a script tag? HTML just doesn't belong there. The problem is folowing:
```
<script type="text/ng-template" id="tmplName">
    <h1>I'm not syntax higlighted</h1>
</script>
```
In many code editors other HTML features probably won't work too, since they don't expect HTML there.

Why don't do it like this instead?
```
<div ng-template id="tmplName">
    <h1>I am syntax higlighted</h1>
</div>
```

In addition (not only -> downward compatibility) this should be possible.
```
<template ng-template id="tmplName">
    <h1>I am syntax higlighted</h1>
</template>
```
Or just allow ng-template on any tag. Of course Angular should do *[ng-template]{display:none;} at initialization.

**Comment by lgalfaso** [comment]
This same issue was discussed several times. The main reasons are:
* `<script>` is inhert, this is a must
* using `<div>` or any other tag other than `<template>` would make the html not inhert
* `<template>` is not supported by all the browsers that the current release supports
