### ISSUE TITLE
How do you test the run block?

### ISSUE THREAD

**Issue by adamzerner** [angular/angular.js#12706]
http://stackoverflow.com/questions/32169240/how-should-the-run-block-be-dealt-with-in-angular-unit-tests

Would be useful to include a section on it in the [Unit Testing Guide](https://docs.angularjs.org/guide/unit-testing).

**Comment by petebacondarwin** [comment]
If you load a module and then inject something from it. It's run block will then be executed.

It is best not to put things that need to be tested directly in a run block. Instead put them in a service and test them there. Then you simply call the service from the rub block.

Regarding, "not" running things in a run block during unit test; my preferred approach is to have lots of modules, but only put things in the run block of the "app" module (i.e. the root module). And that this module should contain very little that needs unit testing (if anything).

This means that you can load the other modules, for testing without running unwanted run block code.

If someone wanted to update the guide to reflect this, we would merge it.

**Comment by mkalish** [comment]
This might not be the cleanest way, but if you absolutely have code in the run block that needs testing you can access it through the module.

```javascript
it('should call something in a run block', function() {
    var moduleToTest = angular.module('moduleToTest');
    var runMethod = moduleToTest._runBlocks[0];
    runMethod();
   expect(...
});
```
