### ISSUE TITLE
scrollLeft setter is not working

### ISSUE THREAD

**Issue by carlitux** [angular/angular.js#12702]
Hi,

I have this code

      var divWrapper = input.parent('.tags')[0];
      divWrapper.scrollLeft = divWrapper.scrollWidth;
      console.log(divWrapper.scrollWidth);
      console.log(divWrapper.scrollLeft);

but scrollLeft is never updated it keeps old value.

**Comment by pkozlowski-opensource** [comment]
@carlitux it doesn't look like AngularJS is used anywhere in your code. On top of this this is sounds like a general support question that should be asked using a dedicated support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by carlitux** [comment]
@pkozlowski-opensource if you need more code

    /**
     * The search input.
     */
    var input = element.find('input').eq(0);

    /**
     * Focus the input element.
     */
    scope.focus = function() {
      if (!input.length) return;
      input[0].focus();
      input[0].select();
      var divWrapper = input.parent('.tags')[0];
      divWrapper.scrollLeft = divWrapper.scrollWidth;
      console.log(divWrapper.scrollWidth);
      console.log(divWrapper.scrollLeft);
    };

This is inside a directive fnLink and focus is called when ui is changed this because use overflow: hidden and input disapear when many items on left... so I need to scroll to far right and keep input visible.
The 
    divWrapper.scrollLeft = divWrapper.scrollWidth;
works fine on chrome dev tools but when focus is called don't update the scrollLeft attribute.

**Comment by pkozlowski-opensource** [comment]
@carlitux this really sounds like a question for a support channel, please let's move the discussion there.

**Comment by carlitux** [comment]
@pkozlowski-opensource ok, thanks
