### ISSUE TITLE
How to make style-guide for my application

### ISSUE THREAD

**Issue by vladanPro** [angular/angular.js#12718]
Can you direct me how to make my own style-guide in angular, i try with grunt-ngdocs and no luck, i have problem to put divs and css for simple elements (icons, etc) Also problem was   to make in menu list for HTML elements and sub-menu witch belongs like Buttons and inside Secondary Button or Custom Button. In ng-docs is only for code ctrl,module and directives. Thank you.

**Comment by Narretz** [comment]
This sounds like a support question. Please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

(ngdocs is as far as I know only for documenting JS code. Internally, we now use dgeni which is a more powerful doc generator. Neither of these have special style guide capabilities)

**Comment by Narretz** [comment]
Basically, you are not looking at an angular specific problem, but a doc generation problem.

**Comment by vladanPro** [comment]
Ok, thank you.
