### ISSUE TITLE
ngModelController.$setViewValue() on invalid field keeps validation error

### ISSUE THREAD

**Issue by edzius** [angular/angular.js#12713]
The problem is with input[number] field. When i change value to invalid and uncheck checkbox field should reset value to last valid one and thus there should be no validation error. View value is changed back but validation value is still present.

See the demo: http://plnkr.co/edit/qIFxmVEXowSNGaBifV4T?p=preview

By digging some into angular, whole problem seems to be automatically added "badInputChecker" $parser. It checks element ValidityState without respect to new value and in consequence returns undefined to model.

Workaround could be before $setViewValue() to set new value for input and perform checkValidity():
```
  // Set new input value and do checkValidity() that updates input ValidityState
  var tmp = input.val();
  input.val(valid);
  input[0].checkValidity()
  input.val(tmp);
  // Do standard angular $setViewValue()
  inputCtrl.$setViewValue(valid);
  inputCtrl.$render();
```
Any ideas or plans how can this be solved in angularjs?

Cheers,
Edvinas

**Comment by gkalpak** [comment]
I don't get what the issue is. What are you observing in your plnkr and what how is it different from the expected behaviour ?
AFAICT, it works as expected.

**Comment by edzius** [comment]
The precodintion to reproduce issue is the field must be filled with non-numeric value. After that when you set valid value using $setViewValue(), $viewValue changes, but $modelValue stays undefined.

According to API docs it does not work as expected:
> ...
> When this method is called, the new value will be staged for committing through the $parsers and $validators pipelines. If there are no special ngModelOptions specified then the staged value sent directly for processing, finally to be applied to $modelValue and then the expression specified in the ng-model attribute.
> ...

**Comment by gkalpak** [comment]
@edzius, sorry, but I still can't reproduce it. Could you please add the following details:

1. What browsers/OS are you using.
2. Exact steps to reproduce.
3. Observed output
4. Expected output

**Comment by gkalpak** [comment]
Ah, wait ! I can see what you mean using Firefox and Edge (on Win 10).
I was previously trying it on Chrome, where it's not reproducible.

Looking into it...

**Comment by edzius** [comment]
I reproduced it on Unbuntu 14.04 with "Chromium v43" and "Firefox v38".

Sequence to reproduce:
1. Set input value to non numeric one (e.g. "1x")
2. Uncheck the checkbox
3. Input has valid value, however validation error still present
4. Expected input not to have any validation error.

It seems to me that this is not browser related issue. When i $setViewValue(), input field still hodling *old value*, and when running $parsers pipeline "badInputChecker" parser checks input's *internal* ValidityState (which is still invalid, because input's value is not changed) and when found it forces to *return 'undefined'* to model instead real value. So in conclusion validators says input is not valid, because in model it is undefined.

See: https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1303

This looks like design buggy.

**Comment by Narretz** [comment]
It looks like you are using the API not how it is designed (it is confusing though).
If you are using $setViewValue, you have to make sure the value you are passing is the same as the current value in the input.
Can you explain what you are trying to achieve? I think in the viewChangeListener you should actually set the scope model, so the value propagates back to the view.

**Comment by edzius** [comment]
My goal is to create generic input field with checkbox attached to it. Checkbox controls enabled state of input field. When checkbox changes to disable i need input field to revert it's value to last valid one.

@Narretz Yes this is actually my case -- current input value is not the same as i passing to $setViewValue(). However what is the purpose of $setViewValue() if passing value must be the same as input's value?
Also was trying to avoid interaction with scope's model value since all things i do is data-binding and validation related, it seemed to me that using ngModelController API is the "proper" way to do it.

**Comment by Narretz** [comment]
The purpose of $setViewValue is to propagate the value of the input / control into the ngModel pipeline:
change in control / inoput -> setViewValue -> parsers -> validators -> set on scope (simplified). Basically, you cannot separate the scope value from the value inside the ngModelController. The goal is to always have the value in the input control reflected by the scope value. In our example, the input value would be disconnected from the value inside the ngModelController. So the right way is to set the scope value to the last valid value, and it will propagate down to the input value.

**Comment by gkalpak** [comment]
Although people often think that `$setViewValue()`'s purpose is to update the view (i.e. the DOM), it isn't.

As @Narretz explained, it's purpose is to _propagate_ the value set **in the view** (e.g. by the user's interacting with an input) **through the `ngModel`** pipeline (parsers, validators) **to the model** (JS object).

Thus, it is mostly useful to people creating input directives (i.e. directives the bind interactive elements to the model, using `ngModel`).
Angular does that for the built-in input elements (`<input>`, `<textarea>`, `<select>`), but anyone could overwrite these directives or create their own (bound to non-standard input elements).

--
As @Narretz said, in Angular, the model is the source of truth. If you need to set a value, you should not try to interact with the input element - you should set the value in the model instead (and let Angular propagate the change to the view).

[Here][1] is a simplified version of what you are trying to achieve.

---
I initially (incorrectly) thought this was a bug in `$setViewValue()`. 
Thx @Narretx for clarifying (and bring us back on the _Angular way_ :smiley:). 

[1]: http://codepen.io/ExpertSystem/pen/rONYrX?editors=101

**Comment by edzius** [comment]
Okey, thank you guys for explanation :)
