### ISSUE TITLE
Difference in $location.path() between $locationChangeStart and $routeChangeStart

### ISSUE THREAD

**Issue by ravishivt** [angular/angular.js#12723]
If I click on a route with path, "/test?dog=cat#boat" and have both the $locationChangeStart and $routeChangeStart handlers defined, I get different results of $location.path().  For locationChangeStart, I get the full path of "/test?dog=cat#boat" but with routeChangeStart, I only get "/test".  I could reconstitute the query params using the nextRoute argument that gets passed with $routeChangeStart but the "#boat" search history isn't available in the nextRoute.

This is on Angular 1.4.4.

**Comment by petebacondarwin** [comment]
I cannot reproduce this in 1.4.4: See http://plnkr.co/edit/1WvuFIS9rDjDt9JhK7CU?p=preview

**Comment by gkalpak** [comment]
Closing due to lack of reproduction.
