### ISSUE TITLE
Overriding controllers - add file path as $CONTROLLER_PATH

### ISSUE THREAD

**Issue by Machiaweliczny** [angular/angular.js#12726]
Hello there. I would like to add functionality to custom fork of batarang 
* open controller in editor
* open view in editor

I want to add `$CONTROLLER_PATH` to each controller and directive and `$TEMPLATES.push($FILE_PATH)` to each template. 

I can do this with script or assets preprocessor, but it would be the best to add this by default to every controller and directive. 

Could you point me out how could I modify default angular controller to achieve this very wanted by me functionality?

**Comment by Narretz** [comment]
Hi, there is an extra repo for batarang, please post your issue there: https://github.com/angular/batarang/issues Thanks!
