### ISSUE TITLE
Bad content-length for $resource remove in IE 11, angularjs 1.4.5

### ISSUE THREAD

**Issue by rpsde** [angular/angular.js#12739]
See plunk at http://plnkr.co/edit/1Pf5wTbjdMqmVQCkJ8il?p=preview.

The angular version is initially 1.4.3 (same problem exists in 1.4.5).  In IE 11, when you click the "Test Delete" button and examine the request, notice that the Content-Length is 9 (which corresponds to the text 'undefined').

If you change the version to angular 1.3.18 and repeat, Content-Length is 0, which is correct.

The content-length of 9 with the value of 'undefined' causes the DELETE request to fail at the REST server.

This issue only exists in IE, I'm using version 11.

**Comment by gkalpak** [comment]
It is e04a887 that causes the different behaviour from earlier versions.
Maybe we should change `xhr.send(post)` to `xhr.send(isUndefined(post) ? null : post)`.
