### ISSUE TITLE
Unable to set secure flag for cookies using $cookies.putObject in Angularjs version 1.4.4

### ISSUE THREAD

**Issue by anupkawtia** [angular/angular.js#12735]
We are unable to set the secure flag for cookies using the $cookies service in Angularjs 1.4.4.
We are using the putObject() method mentioned in https://code.angularjs.org/1.4.4/docs/api/ngCookies/service/$cookies for the same.

Below is the same code snippet we are using for the same:
```
var config = {
    secure: true
 };
$cookies.putObject('foo', 'bar', config);
```

We cannot see the secure flag being set when we inspect the cookie that's being created. 
Also, if we try to do a $cookies.getObject('foo') we get an undefined object in response. We already have all the necessary modules like "ngCookies" injected in our application.

**Comment by petebacondarwin** [comment]
@shahata can you take a look at this?

**Comment by shahata** [comment]
@anupkawtia can you create some form of reproduction for this issue? How are you checking the secure flag on the cookie? Are you sure you are trying to create the cookie on a secure web page? I've tried this out and it seems to work fine: https://jsbin.com/qijodawofe/edit?html,js,output

After clicking the "Write cookie" button you will see the value you entered in the text box appear near the "Cookie value" label. Also, in `devtools -> resources tab -> cookies -> null.jsbin.com` you can see that the secure flag is marked as expected.

**Comment by anupkawtia** [comment]
@shahata We were getting an undefined value because we were trying to test with https disabled. When we tested with https enabled it worked fine and the cookie was getting set as secured correctly. Sorry for the inconvenience caused. You can close the issue.
