### ISSUE TITLE
Add commitizen script to package.json

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#12730]
One barrier to contributing is getting [the commit message conventions](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format) right the first time. I don't expect I need to justify that this is a challenge and would be nice to make easier.

Enter [commitizen](https://github.com/commitizen/cz-cli) by @jimthedev. Long story short:

1. Add `commitizen` and `cz-conventional-changelog` to `devDependencies`

```json
"devDependencies": {
   "commitizen": "^1.0.4",
    "cz-conventional-changelog": "1.1.0"
}
```

2. Add `czConfig` to `package.json` to tell `commitizen` to use the `cz-conventional-changelog`:

```json
"czConfig": {
  "path": "node_modules/cz-conventional-changelog"
}
```

3. Add `commit` npm script that utilizes the `git-cz` binary installed from `commitizen`:

```json
{
  "scripts": {
    "commit": "git-cz"
  }
}
```

Then, just update documentation to tell people to run `npm run commit` after they've staged the changes they want to commit. They will be greeted by the beautiful step-by-step wizard to fill in to create their perfectly formatted commit message:

![git-cz](https://cloud.githubusercontent.com/assets/1500684/9622525/44d31176-50f1-11e5-96f9-92c37432c4ba.png)

---

A few comments to address some possible concerns:

Q: What if I don't want to use some weird wizard? I want to have total control over my commit message!
A: You don't have to use it. Everything will work just fine using the regular git commit flow you're used to.

Q: I use a GUI like SourceTree. What if I don't want to do this?
A: See answer above.

---

I've been using commitizen for a while at work (though I use the [cz-jira-smart-commit](https://github.com/commitizen/cz-jira-smart-commit) plugin) and it's be really great. I added it to [angular-formly](https://github.com/formly-js/angular-formly/blob/master/package.json) and so far it's been quite helpful. I think that people would find the barrier to contributing lowered even a little bit with something like this.

---

As a side-note, you could take this a step further and integrate something like [ghooks](https://github.com/gtramontina/ghooks) by @gtramontina to ensure that people don't attempt to commit with a message that doesn't follow the conventions. I added this to angular-formly too: [config](https://github.com/formly-js/angular-formly/blob/master/package.json#L76), [script](https://github.com/formly-js/angular-formly/blob/master/scripts/pre-commit-git-check.js). But that's probably another story...

Anyway, I was just thinking of ways to lower the barrier to contributing. Hope this sparks ideas at least :-)

**Comment by jimthedev** [comment]
Quick update, now you use config.commitizen.path in package.json.

**Comment by ocombe** [comment]
This only work for people who commit via command line, what happens if you use SourceTree for example?

**Comment by kentcdodds** [comment]
You have to do the same thing you have to do now... Code it manually. This is only useful for people who will run the command. But I don't see that as a drawback...........

**Comment by jimthedev** [comment]
Yes, commitizen is completely opt in. There will still need to be server side validation hooks to verify that people are following the convention. This simply makes it easier for people to commit to the angular project without needing to worry if they followed the commit message convention.

**Comment by Narretz** [comment]
Closed by https://github.com/angular/angular.js/commit/a179757fad90285cd3ce0934ccfffd571518cbc1
