### ISSUE TITLE
Angular adds static code to my HTML.

### ISSUE THREAD

**Issue by alucardu** [angular/angular.js#12749]
I'm trying to test my app on a production Rails server and I'm having problems with Angular.

I've commented out `config.assets.js_compressor = :uglifier` in production.rb so I can see the code better.

The problem is that Angular adds a lot of static code to my HTML.

I use router-ui to insert a template in a div called `.search` on my application.html.haml through a State.

In the `.search` div Angular adds this span element.

    <span class="ng-scope">// Angular Rails Template
    // source: app/assets/javascripts/angular-app/templates/_search.html.haml

    angular.module("templates").run(["$templateCache", function($templateCache) {
      $templateCache.put("angular-app/templates/_search.html", "</span>

It also adds a `\n` in the beginning and end of a element.

Like this,

    <ul id="showresults">\n    \n  </ul>

Angular does work but I have no idea why this extra code is being inserted.

**Comment by Narretz** [comment]
It's difficult to say what adds these elements. Is this the same in all browsers? The line breaks in the second example might be because the ngRepeat comment is added, or it might be the browser. In any case, without a demo we can't really say.

**Comment by Narretz** [comment]
Hi, without more info we cannot do anything about this issue. Feel free to reopen if you have more info.

**Comment by alucardu** [comment]
After a lot of trial and error I found out that the problem was comming from a old sprockets gem. When I have sprockets 3.2.0 in my gemlock file there´s no problem. But when I do bundle update it `updates` the sprockets to 2.2.14 and the static code error apears. I then manually override the sprockets gemlock file back to 3.2.0 and everything is fine.
