### ISSUE TITLE
clearing picker inputs makes form invalid => can't submit form

### ISSUE THREAD

**Issue by jimmywarting** [angular/angular.js#12744]
when ppl how has a date picker (eg: chrome) decides to clear the field on a input that is not required results in a invalid form

if datetime-input starts empty, its valid
if you pick a date it's valid
but if you clear it, it will be invalid

**Comment by Narretz** [comment]
This sounds similar to https://github.com/angular/angular.js/issues/12207 and https://github.com/angular/angular.js/issues/11622. Seems to be a bigger problem.

**Comment by gkalpak** [comment]
This seems indeed to be the same issue as #12207.

**Comment by jimmywarting** [comment]
Yupp, can close this.
