### ISSUE TITLE
Don't $watch hidden elements

### ISSUE THREAD

**Issue by mato75** [angular/angular.js#12748]
Is there a possibility to pause $watches on hidden elements?

**Comment by Narretz** [comment]
Are you watching DOM elements? You are not supposed to do that. As such, there is no way to "pause" a watch when the element is hidden.

**Comment by mato75** [comment]
I would like to pause ng-if, ng-show,... inside of a specific element.

I used a solution from (toggleChildrenWatchers):
http://stackoverflow.com/questions/29801907/angularjs-pause-digest-watchers-on-hidden-dom-elements

What do you think about it?

**Comment by Narretz** [comment]
There is currently no way to stop watches in a subtree. I think it's because it's very difficult to do it right, exactly because of the reasons you mentioned. Can you post an example that shows shwy exactly ngIf + popup gets slow?

**Comment by mato75** [comment]
It is a very complex example. But simple code would look like this.

show (true/false)

        <div class="Popup">
             <div ng-if="show">
                 <div ng-transclude></div>
             </div>
        <div>

**Comment by Narretz** [comment]
This doesn't really give me an idea, why this is becoming slower. Do you mean it's becoming slower because you simply have lots of elements that need to be compiled?

**Comment by mato75** [comment]
No, I use angular-vs-repeat for lists, so only the initiation is slow, but other then that it works great. One of the examples of slowness shows at drag and drop. When dragging over elements, drop events get triggered slower then at first. And this happens only when I open/close popup multiple times.

**Comment by Narretz** [comment]
If you are using a separate directive, this might also contribute to the performance problems. If you can provide an example of this happening with a core directive, please open a new issue. Meanwhile, I am going to close this issue, as it is pretty broad, and pausing digests / watches has been considered, but it's pretty difficult to do.
