### ISSUE TITLE
$locationChangeStart event fires if we are using ng-include directive and there is no location change.

### ISSUE THREAD

**Issue by palmanis** [angular/angular.js#12757]
In angular 1.4.3, if we are using ng-include directive, and if another piece of code is listening for $locationChangeStart event, it gets fired, even if there was no location change.

Reasons: ng-include depends upon $anchorScroll, which in turn depends upon $location service. So it gets initialized and adds a watch on the $rootScope which executes in every digest cycle.
Internally it has a variable initializing which is originally set to true, and gets reset only when location really changes. But the problem is, if there is no location change, the variable is still true and the $watch in $LocationProvider fires this event.

a plunkr showing this issue.
http://plnkr.co/edit/qDQqlV8uwRGOdKyyTCkB

**Comment by gkalpak** [comment]
I am not sure if this is really undesirable.

Is it causing you problems ?
It is fairly easy to ignore the event if `newUrl === oldUrl`, but in most cases it wouldn't even be necessary.

**Comment by palmanis** [comment]
Yes it did cause issues for us and the solution you are suggesting is exactly what we did to work around this.
The reason i reported this was because:
1. when this happened, it took some time and effort to find the root cause.
2. it does not sound right to dispatch events for a condition that did not happen. does it ?

cheers..

**Comment by gkalpak** [comment]
> it does not sound right to dispatch events for a condition that did not happen. does it ?

It's not exactly that it didn't happen. It happened at an earlier point in time (before the service was instantiated). I can think of more usecases where the consistency of getting an event for every change (including the initial load) is desirable, compared to usecases that the delayed firing of the event would cause problems.

I'm not feeling too strongly about either way, but I think I have a slight preference for the way things are right now.
I would like to hear what other people think.

**Comment by gkalpak** [comment]
Summing it up, there are two independent "issues"/behaviors here:

1. `$location` will fire a pair of `$locationChangeStart/Success` events upon first load.
2. `$location` will not be initialized until the user instantiates some service that (transiently) depends on it - i.e. Angular core will not instantiate `$location` by default.

I can imagine that both of these behaviors can be thought of as a feature or a bug, depending on your poiint of view/usecase. Considering that changing the current behavior would be a significant breaking change (for no objective benefit) and that it is trivial to work-around it, I don't think we should make any change.

Based on the above, I'm going to close this issue, but feel free to continue the discussion below.
