### ISSUE TITLE
docs(tutorial): Code samples use deprecated $http promise methods

### ISSUE THREAD

**Issue by rabdill** [angular/angular.js#12755]
The tutorial ([website](https://docs.angularjs.org/tutorial), [repo](https://github.com/angular/angular.js/blob/master/docs/content/tutorial/)) looks like it might be due for at least a few minor changes. In particular, starting in [step 5](https://docs.angularjs.org/tutorial/step_05#controller), it sets up a call using the $http service like this:
```
phonecatApp.controller('PhoneListCtrl', function ($scope, $http) {
  $http.get('phones/phones.json').success(function(data) {
    $scope.phones = data;
  });

  $scope.orderProp = 'age';
});
```
When, according to the most recent docs, [we aren't supposed to do that anymore](https://docs.angularjs.org/api/ng/service/$http#deprecation-notice). I'd be happy to move everything into using the `.then()` method, but this would also require fixing the [angular-phonecat](https://github.com/angular/angular-phonecat) repo that's used in the tutorial, and I'm not sure if there's a particular process in place for coordinating changes so they line up properly. (Also, to be honest, I have no idea how you've been dealing with pushing changes through all the phonecat "releases" retroactively without someone dying in a rebasing accident.)

**Comment by gkalpak** [comment]
Closed with c2033d7.
