### ISSUE TITLE
Creating Angular debugging bar Feature which is rendered only in case of development environment

### ISSUE THREAD

**Issue by m-amr** [angular/angular.js#12760]
This is inspired from (Symfony 2 php framework ) debugging bar, it will be at the button of the page
full width and about 80px height so angular debugging bar can contain information about 

1 - Controllers and their scopes
2 - Rendered Directives and their scopes 
2 - Rendered time to measure performance
3 - List of https requests
4 - Forms and their data
5 - Track events and their data

This feature will help the developer to debug their modules faster without log variables. this debugging bar is like a map for all the rendered directive and controllers and their scopes so developer can see every thing happened and can improve the application performance.

**Comment by Narretz** [comment]
Hi, thanks for your post.
Is this something you entertain to create or do you think it should be in core / "official". There is already the Angular Batarang (https://github.com/angular/batarang), which provides a few of these functions. Maybe this is already a start for you. Others seem more suited for server-side code, such as list of http requests (the browser already tracks these), and forms and their data (SPAs often don't have form handling like Symfony does).

**Comment by m-amr** [comment]
@Narretz 
I tried Angular Batarang and it is a great tool but sometimes it doesn't work.
but it is chrome extensions it won't work in other browsers or mobile devices.I am very interested to create something like that. 

i think if angular core have an official debugging bar which will work across all the browsers and all the devices or be as a separated module like ng-animate will be more stable.
I think it can be a directive called "ng-debug" 
1- developer set it to true ng-debug='true' to enable it
2- developer set it to true ng-debug='false' to disable it

as a developer it will be a useful tool for me.

Thanks

**Comment by Narretz** [comment]
We don't have time for this unfortunately - we maintain batarang, but this is as far as it gets
