### ISSUE TITLE
bug in directives

### ISSUE THREAD

**Issue by kumar4384** [angular/angular.js#12770]
Hi,

I noticed a bug while creating the below custom directive

Code which gives error
=========================
var myapp = angular.module('app',[]);
myapp.controller('mainCtrl',function($scope)
{
	
});
myapp.directive('acctSummary',function()
{
	return
	{
		template:'helo'
	}
});

Error 
=========================================
TypeError: Cannot read property 'compile' of undefined
    at angular.js:7040
    at n (angular.js:336)
    at Object.<anonymous> (angular.js:7035)
    at Object.e [as invoke] (angular.js:4473)
    at Object.$get (angular.js:4325)
    at Object.e [as invoke] (angular.js:4473)
    at angular.js:4290
    at Object.d [as get] (angular.js:4432)
    at G (angular.js:8333)
    at ha (angular.js:7708)

The above error disappears when we move the curly brace just next to the return statement instead of placing down. The below code works fine.
myapp.directive('acctSummary',function()
{
	return{
		template:'helo'
	}
});

Thanks.

**Comment by bathos** [comment]
That's not related to Angular, it's just how return statements in JS work. An expression must begin on the same line as the `return` keyword to be part of the return expression, or else an implicit semicolon after `return` is added when the code is parsed.

**Comment by Narretz** [comment]
bathos is right! Thanks for explaining.
