### ISSUE TITLE
Bug in limitTo filter when using negative begin parameter

### ISSUE THREAD

**Issue by scroach** [angular/angular.js#12775]
There is an error in the limitTo filter begin/end position calculations.
I want to show a maximum 5 characters from a string no matter which length it is.

Therefore I am using this snippet: ```{{string | limitTo : 5 : -5  }}```
I expect the filter to show max. 5 chars beginning from the -5 index. This works as long as the string is at least 5 characters long. If it is shorter the filter won't display anything!

Example here:
http://plnkr.co/edit/tSdeeQ1Ue8rxyapC11vV?p=preview

Bug seems to be in any 1.4.x version of angular.

**Comment by gkalpak** [comment]
Why don't we make `limitTo` behave like the native `slice` ?

**Comment by scroach** [comment]
What do you mean with 'behave like'? Changing the parameters from length/begin to start/end as in slice?

I just looked into the implementation and as the filter internally uses ```slice``` anyway there seems to be a bug in the calculation of the ```end``` param. When using a negative ```start``` parameter for slice ```end``` needs to be negative too or omitted. In my example above 5 and -5 result in ```end``` to equal 0 and ```slice``` returns an empty string.

```
console.log("123".slice(-3))
> "123"
console.log("123".slice(-3, 0))
> ""
```

**Comment by gkalpak** [comment]
@scroach, sorry, it wasn't clear - I meant wrt the begin index.
I.e. right now we have: `begin = (begin < 0 && begin >= -input.length) ? input.length + begin : begin;`, whereas `slice()` works more like: ` begin = (begin < 0) ? Math.max(0, input.length + begin) : begin;`

**Comment by gkalpak** [comment]
BTW, @scroach, while this is fixed and since `limitTo` works a little different than `slice()` (and offers more power in some cases), you can easily return the last X items of an array/string by using a negative limit:

```
{{ string | limitTo: -5 }}
```

**Comment by scroach** [comment]
Ah thx, didn't know that I could also provide a negative limit parameter but thanks for pointing that out and fixing the strange behaviour.
