### ISSUE TITLE
BUG: element on a directive with ngIf on root HTML element it's a comment

### ISSUE THREAD

**Issue by marcalj** [angular/angular.js#12776]
```js
angular.module('app')
    .directive('directiveNgIfRoot', function () {}
        return {template: '<section ng-if="enabled">hello</section>', ... , link: function (s, element, a) { console.log(element[0]); }};
    );
```

The element on ```link``` function refers to the comment added by ngIf directive, not the ```<section>``` element.

I'm using v1.4.4.

**Comment by Narretz** [comment]
Your example doesn't show the problem, this happens only if the directive has `replace` set. Given that replace is deprecated, I wouldn't hold out for a fix.

**Comment by marcalj** [comment]
Thanks! Maybe it's time to force people don't use ```replace``` option?

**Comment by wesleycho** [comment]
This should probably be closed, given that `replace: true` is deprecated and this type of bug has been declared as a won't fix essentially.

**Comment by wesleycho** [comment]
Also a workaround is to wrap the template with a dummy element like a `div`.

**Comment by marcalj** [comment]
@wesleycho Sure, also I'm migrating to NG2 right now :)
Feel free to close it.

**Comment by gkalpak** [comment]
Closing then :smiley:
