### ISSUE TITLE
Serving global data to the views

### ISSUE THREAD

**Issue by 45kb** [angular/angular.js#12798]
Could be great to setup an object like that angular will directly port to the view, usually you would need ```$rootScope``` to achieve this, or controller/directive scopes, i was wondering if is there any plan or possibility to generate view objects ad hoc.

For example:
```javascript
run(function ($rootScope, $routeParams) {
  $rootScope.viewData = {
    'appName': 'MyAwesomeApp',
    'appRouteParams': $routeParams,
    'etc': etc..   
  };

...then watch the rootScope for changes.. etc ...

});
```
```html
<span>The app name is {{viewData.appName}}</span>
```

to something like (just an example):

```javascript
viewData(function ($routeParams) {
 return {
     'appName': 'MyAwesomeApp',
     'appRouteParams': $routeParams,
     'etc': etc..  
  };
});

or even better a provider!? , just asking / thinking/ trying ...
```
```html
<span>The app name is {{viewData.appName}}</span>
```

I am just asking not going to conclusions, thank you for ng.

**Comment by gkalpak** [comment]
How is this different/better than using the `$rootScope` ?

If you want a function, it is super easy to create one as well.

**Comment by 45kb** [comment]
@gkalpak  hi, afaik using rootScope for this is not so clever, but i would like to understand more about this.

**Comment by gkalpak** [comment]
Could you elaborate on the "not so clever" part ?
How is another solution _more clever_ ?

Maybe you could share snippets of the two approaches and explain what works differently and why it is better. TBH, right now I don't quite get what this feature request is about.

**Comment by 45kb** [comment]
Yes my mistake the question is not complete at all.

What i'm trying to explain is that usually, there is a portion of "core" data that is not visible in views that could be great to have directly available, for example, $location, $routeParams and more.

Many times you have for example to change links, menus, classes based on route or location or hashbangs and their changes.

So, normally, you  have to pass data through the controller or through the directive or in the rootScope.

What i am wondering is if this could never exists for example:

```html
<a ng-if="$location.hashbang.indexOf('hello')"> Hello </a>
```

while this exists of course.

```html
<a ng-if="scopeLocation.hashbang.indexOf('hello')">Hello</a>
```

**Comment by gkalpak** [comment]
But the `$rootScope` is available everywhere (except for isolate scopes of course, but I don't think self-contained components need to have access to app-wide state).
Why not put `$location` on `$rootScope` (pretend it is called `$viewData` if you fancy :smiley:) and use it everywhere ?

**Comment by 45kb** [comment]
@gkalpak sure... just you already have $location why not expose it to the view directly .... :)

**Comment by gkalpak** [comment]
So, do you mean that some stuff (e.g. `$location`, `$routeParams` etc) should be exposed to the view _by default_ (i.e. done by Angular itself, not the user) ?

**Comment by 45kb** [comment]
Yes, maybe using an alias like indeed $viewData don't know... that is automatically updated/watched and available everywhere

**Comment by gkalpak** [comment]
It is already possible to put `$viewData` on the `$rootScope` if you want.

Also, I don't understand what you mean by _"automatically updated/watched"_.
There is no need to automatically update and object (since assignment is done by reference) and if you put something on the view using Angular's 2-way binding it is already watched automatically.

I still don't get it :worried: I think it would be best to post a detailed usecase (with some code of how you would like it to be and a description of how you expect it to work).

**Comment by 45kb** [comment]
@gkalpak  Ok sorry better to close the issue then i will try to explain this later, with some code :)
