### ISSUE TITLE
Encapsulate ngMessage inside another directive does not work with ngMessagesInclude

### ISSUE THREAD

**Issue by korbav** [angular/angular.js#12791]
Hi all,

Playing with angular-messages I'm facing an issue. I am not sure of the origin of this.

As soon as I put ngMessage elements inside a custom directive, then they don't seem to be working anymore. They not appear/disappear as they should, they become static, as if they were not managed.

Because code is more explicit than words I built a simple plunkr to illustrate the situation, you will find it here : [Plunkr Link](http://plnkr.co/sqsJipdh2bUUWvBZhXDS)

Thanks for any idea on this

**Comment by Narretz** [comment]
Hi, what you are doing does not work and is not supported. When you add attributes / directives inside the directive compile / link fn, they will not be compiled. They act as normal attributes. You can re-compile these elements yourself (then the directives will be added - but this can lead to problems too). The best way is to simply use a directive template that includes these directives from the start.

**Comment by korbav** [comment]
Thanks Narretz you put me on the right way, the pre-compile function is definitely a mysterious one on Angular
