### ISSUE TITLE
jqLite handles on/off asymmetrically for mouseenter/mouseleave

### ISSUE THREAD

**Issue by VWoeltjen** [angular/angular.js#12795]
After an alternating series of `on`/`off` calls for `mouseenter` or `mouseleave`, the event listener starts being invoked more often than expected.

Say you have a reference to a jqLite-wrapped element, `$element`, and you want to invoke some function when the mouse enters that element:

```javascript
$element.on('mouseenter', someFn);
```

Now, `someFn` is invoked once every time the mouse enters the DOM element wrapped by `$element`, as expected.

Now detach that listener:

```javascript
$element.off('mouseenter', someFn);
```

No, `someFn` is no longer invoked when the mouse enters that DOM element, again as expected.

Now, reattach the listener:

```javascript
$element.on('mouseenter', someFn);
```

Observe: Now `someFn` is invoked twice whenever the mouse enters the specified DOM element, which is _not_ expected.

More generally, after _n_ calls to `on` and _n - 1_ calls to `off`, the event listener starts getting invoked _n_ times per mouse entry, instead of once as expected.

This is true for `mouseenter` and `mouseleave` but does not appear to be the case for other events.

See [this gist](https://gist.github.com/VWoeltjen/c0d9b9bb182e96725891) illustrating the issue.

**Comment by VWoeltjen** [comment]
Guessing that this has to do with some special handling for `mouseleave` and `mouseenter` which appears [in `jqLiteOn`](https://github.com/angular/angular.js/blob/43769fb676ae904852582a2c88a5523f0b9f58fc/src/jqLite.js#L820) but does not appaar in `jqLiteOff`.

**Comment by VWoeltjen** [comment]
@gkalpak I'm impressed and humbled by the fast turnaround on this issue! Thanks!

**Comment by gkalpak** [comment]
Anything to help NASA - LOL

Seriously, @VWoeltjen, your detailed report and accurate description of the problem played a major role.
You basically handed me the fix on a plate :smile:

**Comment by gkalpak** [comment]
Now let's see how fast it gets merged (I am not sure my approach is the best - it's definitely not an ideal situation) :)
