### ISSUE TITLE
problem md-backdrop can't remove after close bottom sheet

### ISSUE THREAD

**Issue by tronghuynhhb** [angular/angular.js#12796]
I write event ng-mouseover open bottom sheet, but when I mouseover multiple, bottom sheet show right data after I cancel bottom sheet, md-backdrop only remove last backdrop so screen freezes. How can i remove all backdrop after bottom sheet cancel. Thanks!

**Comment by gkalpak** [comment]
Since the question is ngMaterial-specific, it should be posted to the [ngMaterial repo][1].
This repo is for core AngularJS.

[1]: https://github.com/angular/material
