### ISSUE TITLE
Add placeholder capabilities to ng-include

### ISSUE THREAD

**Issue by ProLoser** [angular/angular.js#12807]
Right now if I place some (placeholder) html inside of an `ng-include` element, it never gets rendered. It would be really nice if it did as I could create a loading spinner or something that would not require messing with scope variables and creating watchers through `onload`.

**Comment by Narretz** [comment]
I think that's basically the same as https://github.com/angular/angular.js/issues/1769. The router should be able to do this, imo. Not sure if it makes sense to put this into 1.x at this point
