### ISSUE TITLE
i18n and l10n Plnkr example not working?

### ISSUE THREAD

**Issue by vinkaga** [angular/angular.js#12801]
On developer guide https://docs.angularjs.org/guide/i18n, the Plnkr example at http://plnkr.co/edit/QBVRQ70dvKZDWmHW9RyR?p=preview gives message output as follows

Message
{{recipients.length, plural, offset:1 =0 {You ({{sender.name}}) gave no gifts} =1 { {{ recipients[0].gender, select, male {You ({{sender.name}}) gave him ({{recipients[0].name}}) a gift.} female {You ({{sender.name}}) gave her ({{recipients[0].name}}) a gift.} other {You ({{sender.name}}) gave them ({{recipients[0].name}}) a gift.} }} } one { {{ recipients[0].gender, select, male {You ({{sender.name}}) gave him ({{recipients[0].name}}) and one other person a gift.} female {You ({{sender.name}}) gave her ({{recipients[0].name}}) and one other person a gift.} other {You ({{sender.name}}) gave them ({{recipients[0].name}}) and one other person a gift.} }} } other {You ({{sender.name}}) gave {{recipients.length}} people gifts. } }} 

How do I make it work properly?

**Comment by Narretz** [comment]
The links to angular are out of date. Try this: http://plnkr.co/edit/mzei8wcaGxVUfXkPkBEG?p=preview

**Comment by vinkaga** [comment]
Thanks a lot. It works.

**Comment by Narretz** [comment]
I'll leave this open until we have fixed it in the repo
