### ISSUE TITLE
ng-include issue

### ISSUE THREAD

**Issue by linkin2015** [angular/angular.js#12806]
I used ng-include:
<div ng-include="'notification/notification.html'"></div>
 to inject a partical html below into my main html file

<div ng-controller="notificationController">
    <div id="jqxNotification_success" class="Notification">
    </div>
</div>

Then, I defind JS behavior in "notificationController“ controller as shown:
myAppModule.controller("notificationController", function ($scope, $http, $exceptionHandler, $filter) {
    $("#jqxNotification_success").text("Add text here");  
     console.log("This is executed.")
 });

The partial html is successfully injected, but the JS behaviour is missing.
FireBug's console prints "This is executed.", but the text "Add text here" is not showing up.

Can anybody help me figure this out? Why does the line 
"$("#jqxNotification_success").text("Add text here"); " executed but not being in effect?

Thanks.

**Comment by JordanMajd** [comment]
It would seem that
```javascript
$("#jqxNotification_success".text("Add text here");
```
is getting executed before `ng-include` injects the partial HTML. This means JQuery will not find element any element with id `jqxNotification_success`. If the element doesn't exist you cannot change its text. You could test this hypothesis by setting a timeout on the JQuery so it has a delayed execution. Note: this is not a fix, it is just a test to see if execution order is the issue.

```javascript
//inject angular $timeout dependency
myAppModule.controller("notificationController", function ($scope, $http, $timeout, $exceptionHandler, $filter) {

   //execute jquery after a 1000ms delay
   $timeout(function(){
       $("#jqxNotification_success").text("Add text here");
       console.log("This is executed.")
   }, 1000);
});
```

A long term fix would be to not use JQuery, but instead just use Angular to set the components text. I don't know what your partial HTML looks like, but this should provide you with a solid example:

```html
<div id="qxNotification_success"> {{addText}}></div>
```

```javascript
myAppModule.controller("notificationController", function ($scope, $http, $exceptionHandler, $filter) {
   $scope.addText ="Add text here";
});
```

**Comment by Narretz** [comment]
I think @JordanMajd is right: whenever you are using jquery this way in an angular app, you are setting yourself up for disappointment. Interpolation is the way to go.

**Comment by linkin2015** [comment]
Thank you @JordanMajd and @Narretz. 

I have a further question. What if I replace "$("#jqxNotification_success").text("Add text here");"
with $("#jqxNotification_success").jqxNotification({position: "top-left" });
where jqxNotification() is from a 3rd party JQuery UI library.

So the question comes to people apply a useful 3rd party JQuery Library while using AngularJS ?
Basically, I really like to use AngualJS as my sole JS library, in order not to cause unexpected conflicts. 
However, I don't have time to develop some basic functionalities like Notification Window, enhanced input, or datepicker, etc. I can only find these kind of mature resource in JQuery community.

**Comment by gkalpak** [comment]
@linkin2015, the point is, that you should use Angular as if it were jQuery (e.g. looking up an element in the DOM through a selector and modifying it).
If you want to use an existing jQuery plugin, you should _wrap_ it in a directive (i.e. "bind" it to a class or attribute), so any DOM manipulation (such as content text modification) can be applied at an appropriate time (i.e. as soon as the element gets inserted into the DOM).

**Comment by JordanMajd** [comment]
@linkin2015 For future reference, this really isn't the place for questions like this. Instead I would recommend using something like [StackOverflow](www.stackoverflow.com) to ask these kinds of questions. This is a place to report actual issues with the framework. 

As @gkalpak pointed out, the proper design pattern would be to wrap it in a directive. Thankfully, someone has already done this for you [jQWidgets Directives for AngularJS](http://www.jqwidgets.com/jquery-widgets-demo/demos/jqxangular/).  Here is an [example of jqxNotification as an Angular directive being used](http://www.jqwidgets.com/jquery-widgets-demo/demos/jqxangular/notification.htm).

I'd recommend searching for <plugin desired> angular directive, and there is a good chance you will find what you need. One great collection of UI tools like date pickers and the such is (AngularUI)[https://angular-ui.github.io/]
