### ISSUE TITLE
Incorrect documentation for ngMock/function/angular.mock.inject

### ISSUE THREAD

**Issue by trevorade** [angular/angular.js#12812]
The documentation says that `angular.mock.inject` takes `(...Function)`.
In reality, it takes `(...(Function|!Array<string|Function>))`.

In addition, the documentation should be updated to include an example like this:

```js
beforeEach( inject( ['@q', function($q) {
  ...
}]));
```

This is needed when tests are minified and is supported correctly when specifying the params in string form before the function.

**Comment by trevorade** [comment]
I think `angular.mock.module` may also be missing a parameter.

**Comment by Narretz** [comment]
This is a common problem with functions that are injectable, see https://github.com/angular/angular.js/issues/11399. Why do you minify your tests?

**Comment by trevorade** [comment]
I don't minify my tests.  I work for Google and was working on improving the externs for angular.mock.inject and angular.mock.module and while building dependencies of this externs file, I came across build breaks resulting because they passed an array into inject.  This particular case ran their tests as is and compiled (which obfuscates function params).

**Comment by Narretz** [comment]
So this breaks because the code was minified, not when the tests are minified.
