### ISSUE TITLE
ngAnimate: minification

### ISSUE THREAD

**Issue by bsitruk** [angular/angular.js#12816]
Hi.
I'm using ui-router, and I've set a CSS animation to my views with ngAnimate.
On dev sources, an animation is trigerred at start, but not on my production build.
Any idea ?

**Comment by matsko** [comment]
What version of Angular are you using?

**Comment by bsitruk** [comment]
I'm using the version 1.4.5

**Comment by matsko** [comment]
OK could you put together a demo of this using plnkr http://plnkr.co/ ?

**Comment by bsitruk** [comment]
I think the issue is coming from the minification of angular animate.

**Comment by matsko** [comment]
Yes, but if you put up the demo with the working version then I can test it out on both the dev and minified versions to see if some of the reflow code got stripped out.

**Comment by bsitruk** [comment]
I'll try to put a demo tomorrow (11PM here).

**Comment by matsko** [comment]
Awesome. Thank you.

**Comment by bsitruk** [comment]
I don't really know where the issue come from anymore.
My build packages are a bit old, so it might come from there.
When I use the minified version of angular-animate in my dev sources, I got the same behavior. 
It must be something else.
