### ISSUE TITLE
Bug? $scope.$watch triggered with same old and new value when ng-if used

### ISSUE THREAD

**Issue by Episodex** [angular/angular.js#12823]
I've found strange behavior in AngularJS. Looks to me like a bug but maybe it's reasonable.

I have some value that I pass to my directive as attribute. Inside this directive I watch the parameter with `$scope.$watch`. Turns out that if I put `ng-if` on this directive with same parameter in condition the `$watch` will be triggered with wrong old value (old value == new value).

I need to know when the value really changed (to distinguish from initial run when `$watch` is triggered without change). 

From the docs: 
> The listener is called only when the value from the current watchExpression and the previous call to watchExpression are not equal (with the exception of the initial run, see below). 

Here the listener is called with same values and it's not initial run. Is this a bug or second exeption to the rule?

 [Here is the fiddle to show the problem][1]

HTML Code:

    <div ng-controller="myCtrl">
        <select ng-model='myValue'>
            <option>1</option>
            <option>2</option>
            <option>3</option>
        </select>
        <check-change value="myValue"></check-change>
        <check-change value="myValue" ng-if="myValue==3"></check-change>
    </div>

JS Backend:

    var myApp = angular.module('myApp', []);

    myApp.controller('myCtrl', function ($scope) {
        $scope.myValue = 1;
    });

    myApp.directive('checkChange', function () {
        return {
            restrict: 'E',
            template: '<div>{{result}}</div>',
            scope: {
                value: '='
            },
            controller: directiveController
        };
    });

    var directiveController = function ($scope) {
        $scope.$watch('value', function (newVal, oldVal) {
            $scope.result = 'Watch triggered. Values equal? ' + (newVal == oldVal);
        });
    };

  [1]: http://jsfiddle.net/pz1kmtyj/3/

**Comment by Narretz** [comment]
When the element gets destroyed via ng-if, it's scope and therefore the watcher on it is also destroyed. When the element is rendered again, the watcher is initialized again - which means it's called with the same values, because it triggers the exception.

**Comment by adamlg** [comment]
As far as what to do about tracking actual changes, the docs provide guidance a little further down: add something like "if(newVal === oldVal) return" to your watch expression, and you should be fine.

**Comment by Episodex** [comment]
Thanks for clarifying this. Does this mean that is impossible to track the change of `myValue` in my second directive? As it seems it will always only be initialized and never launched again. Am I right?

**Comment by adamlg** [comment]
Depending on what specifically you're trying to accomplish, you have a couple of options.  You can stick with ng-if and track the old and new values inside the controller, then pass them into the directive controller, but that's kind of funky.  The simplest thing for you to do is just use "ng-show='myValue===3'" (or something similar with ng-hide) instead of ng-if.  ng-show does not destroy and re-create the element, so the oldValue is always tracked.  There are some performance trade-offs, though.
