### ISSUE TITLE
Select tag with Options does not have a tooltip

### ISSUE THREAD

**Issue by AnandMuley** [angular/angular.js#12822]
I wanted to implement a angular js select with ng-options directive but it generates options without any title element or tooltip. Wanted to show tooltip if the label value is more than 'x' characters since I have the options rendered with fixed width. Checked the ngOptions.js but its not creating any title attribute for the option tag. Is there a way to achieve that ?

**Comment by Narretz** [comment]
This sounds more like a support question. Please ask on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question If you think xou've found a bug, please open a new issue with a minimal, runnable example of the problem (e.g. on plnkr.co)

**Comment by AnandMuley** [comment]
Sorry for communicating with wrong channel. Would add the same in the mentioned channel. Thank You
