### ISSUE TITLE
$window.open() throw $parse:isecwindow error

### ISSUE THREAD

**Issue by lhj7218** [angular/angular.js#12821]
the $window had injected. why still throw error?
[$parse:isecwindow] Referencing the Window in Angular expressions is disallowed! Expression: openWindow()

**Comment by Narretz** [comment]
This is a security mechanism, as described in http://localhost:8000/build/docs/error/$parse/isecwindow
Instead of `<button ng-click="$window.open()">Click</button>` you should do `<button ng-click="openWindow()">Click</button>` where openWindow is a function that calls $window.open() inside a controller.

**Comment by Narretz** [comment]
If this explanation doesn't apply to your problem, please post a demo via plnkr.co or similar.

**Comment by lhj7218** [comment]
this is my example:
"use strict";
angular.module("print", []).controller("printCtrl", [
  "$scope", "$window", function($scope, $window) {
    return $scope.openWindow = function() {
      return $window.open("printpage2.html", "newwindow", "height=800, width=1000");
    };
  }
]);

<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" ng-app="print">
<head>
    <title>Print Page</title>
    <script src="js/angular-1.4.5/angular.js"></script>
    <script src="/CoffeeScript/print.js"></script>
</head>
<body ng-controller="printCtrl">
    <button type="button" ng-click="openWindow()">open window</button>
</body>
</html>

**Comment by lhj7218** [comment]
![22](https://cloud.githubusercontent.com/assets/14228648/9812360/6b9029d2-58af-11e5-9629-01f35affeacb.png)

**Comment by gkalpak** [comment]
Probably because you return the return value of `window.open()`, which happens to be a `Window` object.

**Comment by lhj7218** [comment]
Yes, you are right.

**Comment by sachinthaHarshana** [comment]
**dont return return $window.open();**

$scope.download = function(){
            var tab_text = $("#dataTable").html();

            var ua = window.navigator.userAgent;
            var msie = ua.indexOf("MSIE ");

            if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
            {
                txtArea1.document.open("txt/html","replace");
                txtArea1.document.write(tab_text);
                txtArea1.document.close();
                txtArea1.focus();
                var excel = txtArea1.document.execCommand("SaveAs",true,"Say Thanks to Sumit.xls");
            }
            else{
                
                var excel = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));
            }

           // return (excel);
        }
