### ISSUE TITLE
ngAnimateRef: can it be used with ui-router ui-view?

### ISSUE THREAD

**Issue by dmackerman** [angular/angular.js#12820]
Is this compatible? I'm trying to copy the examples from the documentation, and it just doesn't work. Get some very strange behavior that I'm not even sure how to describe.

**Comment by GabiGrin** [comment]
+1

**Comment by GabiGrin** [comment]
Actually I just tested it and it looks like it works.
See my reply in this issue - https://github.com/angular-ui/ui-router/issues/2024

**Comment by Narretz** [comment]
Looks like this is resolved.
