### ISSUE TITLE
Angularjs Encoding Issue

### ISSUE THREAD

**Issue by kraw** [angular/angular.js#12845]
Hi, 
How to solve this issue?? 
https://drive.google.com/file/d/0B71VOCCR4Ub0TXotb0RxdzdiTVU/view?usp=sharing

I have already try with cdn but nothing. the charset is utf-8

**Comment by Narretz** [comment]
Please ask support questions on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question Thanks!
