### ISSUE TITLE
why setting $$destroyed to true in  $rootScope while we can't destroy the root scope

### ISSUE THREAD

**Issue by guday** [angular/angular.js#12855]
in ionic.bundle.js about 23199 line:      
$destroy: function() {
        // we can't destroy the root scope or a scope that has been already destroyed
        if (this.$$destroyed) return;
        var parent = this.$parent;
        this.$broadcast('$destroy');
        this.$$destroyed = true;   //the next line ,we return while $rootScope .but why setting this.$$destroyed to true.
        if (this === $rootScope) return;

**Comment by guday** [comment]
In my App,where exceptions occur ,we use $location to jump a errorMsg page.

in errorMsgPage,one can click a button to jump to a  home page.

but after that,every directives not work any more.

**Comment by guday** [comment]
debug and findout that ,while exception occurs, the rootScope will fire a $destroy(). thought failed,but $rootScope.$$destroyed =  true.

then,init directives will fail : postLink function won't fire.

**Comment by guday** [comment]
I know a little about how this issues happens:  ionic.bundle.js in 48606:

  self.appendViewElement = function(viewEle, viewLocals) {
    // compile the entering element and get the link function
    var linkFn = $compile(viewEle);

    $element.append(viewEle);

    var viewScope = $scope.$new();

    if (viewLocals && viewLocals.$$controller) {
      viewLocals.$scope = viewScope;
//here invoke user controller function.
      var controller = $controller(viewLocals.$$controller, viewLocals);
      $element.children().data('$ngControllerController', controller);
    }
//when exception occurs in user controller,this linkFn won't invoke. so viewEle.data('$scope') will be undefined
    linkFn(viewScope);

    return viewScope;
  };

As a result .when ionic destroy a ion-view's scope, viewEle.data('$scope') will be undefined . so ionic lookup every parentNodes to find a scope until $rootScope. and invoke $destroy()

**Comment by guday** [comment]
So,it come up with three solutions：
1、we make viewEle.data('$scope') = viewScope before invoking user controller.
2、Not setting this.$$destroyed while destroying $rootScope.
3、Invoke user controller in $timeout,so linkFn will be definite invoke.

In my app,I use solution 1.

    if (viewLocals && viewLocals.$$controller) {
      viewLocals.$scope = viewScope;
      //预先对ele的$scope数据赋值，避免controller出异常时，destroy错scope
      viewEle.data('$scope',viewScope)
      var controller = $controller(viewLocals.$$controller, viewLocals);
      $element.children().data('$ngControllerController', controller);
    }

**Comment by guday** [comment]
Back to the question: Why setting $$destroyed to true in $rootScope while  we can't destroy the root scope

**Comment by lgalfaso** [comment]
While it is true that the `$rootScope` cannot be fully destroyed, calling `$destroy` on the `$rootScope` is the mechanism to torn down an angular app.

Note: Not everything is torn down, and there are several PRs that try to handle the missing parts, but this does not change the overall intention of the behavior.

**Comment by guday** [comment]
we would not like to torn down our app when an unknown exception catched.

so if we change angularjs code from  
        this.$$destroyed = true;
        if (this === $rootScope) return;
to
        if (this === $rootScope) return;
        this.$$destroyed = true;

this will solve problems.  But I want to know it won't trigger exceptions.

**Comment by lgalfaso** [comment]
I do not know the specifics of your app, but calling $rootScope.$destroy()
is the signal to torn down your app. Regarding how safe this change is;
this might be safe in the specific version that you have (the code for 1.4
does not look like what you posed), but I am not going to assess that, and
this will severely limit your capabilities to upgrade to newer versions.
