### ISSUE TITLE
jqLite - removeClass cannot accept a function

### ISSUE THREAD

**Issue by JordanMajd** [angular/angular.js#12851]
Angular documentation redirects to [jQuery 1.4](http://api.jquery.com/removeClass/), which states that `removeClass` should be able to take a function as a parameter. Also they state that if no parameter is provided `removeClass` should remove all classes.

This is currently not the case. 

I am submitting a pull request to fix this issue.

**Comment by gkalpak** [comment]
It's not `jQuery 1.4`, it's the latest 1.x jQuery (currntly 1.9).

That said, there seems to be indeed a difference between the `add/removeClass()` signatures/behaviour.
I'm not sure it we should just document it, or if it's worth implementing.
(If we do implement it, we have to be consistent with the jQuery implementation though.)

**Comment by JordanMajd** [comment]
You are correct, I misspoke: the ability to pass in functions or no parameters was introduced in `jQuery 1.4` but we need it to be compliant with the the latest version.

#12852 should fix this in a manner that is consistent with the jQuery implementation.
