### ISSUE TITLE
bower-angular-cookies not updating to recent versions

### ISSUE THREAD

**Issue by crearc** [angular/angular.js#12863]
The automated repo for [angular-cookies](https://github.com/angular/bower-angular-cookies) is not being updated correctly. It is updating and adding tags/releases, but the files have not actually moved up in version to the 1.4 release of angular-cookies with the new API

**Comment by Narretz** [comment]
What do you mean exactly? This looks like the new API to me: https://github.com/angular/bower-angular-cookies/blob/v1.4.5/angular-cookies.js

**Comment by Narretz** [comment]
Closing because it appears to work and there hasn't been an update.
