### ISSUE TITLE
custom directive wrong with table header

### ISSUE THREAD

**Issue by trong291990** [angular/angular.js#12861]
I have a directive : 
```
angular.module('app').directive('sortheader', function() {
   var directive = {};
   directive.templateUrl = 'app/directives/sortHeader/sortHeader.html'
   directive.replace = true;
   directive.transclude = true;
   directive.controller = ['$scope', function($scope) {
   }];
   return directive;
});
```
sortHeader.html  : 
```
    <th ng-class="ok">{{col.label}}</th>
```
And in html page : 
```
<table class="table table-striped table-hover" id="users-list-table">
    	<thead>
        	<tr>
                       <th sortHeader ng-repeat="col in header"><th>
                 </tr>
        </thead>
....
```
But it's always render superfluous th tag, and it's empty , like this : 
```
...
<tr>
   <th>The th in repeat</th>
  <th>The th in repeat</th>
  <th>The th in repeat</th>
  <th></th>
</tr>
```

**Comment by gkalpak** [comment]
It's not obvious what you mean by _"superfluous th tag"_, nor is the provided info sufficient to understand or reproduce the problem.

That said, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
