### ISSUE TITLE
Angular JS is not found on his own site

### ISSUE THREAD

**Issue by riteshetymon** [angular/angular.js#12879]
HTTP 404 for angular js files and libs.
![angular](https://cloud.githubusercontent.com/assets/14331728/9934860/585afa24-5d71-11e5-921f-8a8ae47e17d9.png)

**Comment by robinj** [comment]
See 12877

**Comment by czmj** [comment]
They're looking into it :) #12877

**Comment by pkozlowski-opensource** [comment]
Tracked in #12877
