### ISSUE TITLE
AngularJS Docs Website is down

### ISSUE THREAD

**Issue by p4l-aman** [angular/angular.js#12877]
It's trying to load from Google's library with a null version id

https://ajax.googleapis.com/ajax/libs/angularjs/null/angular-resource.min.js

**Comment by pkozlowski-opensource** [comment]
Right, we are aware, working on the fix. Thnx for reporting.

**Comment by petebacondarwin** [comment]
Sorry about that. Opening up 1.5.x branch for development messed up the latest docs site. It should be back up now.

**Comment by p4l-aman** [comment]
Cool! Thanks

**Comment by allisondeluca** [comment]
https://docs.angularjs.org/guide/directive
Docs site down again?

**Comment by petebacondarwin** [comment]
@allisondeluca - It doesn't look down to me. What are you seeing?
