### ISSUE TITLE
docs.angularjs.org not functioning

### ISSUE THREAD

**Issue by czmj** [angular/angular.js#12878]
The https://docs.angularjs.org/ site is currently not functioning.
Looks like exactly the same issue as #9652

![screen shot 2015-09-17 at 14 46 37](https://cloud.githubusercontent.com/assets/3911835/9934723/f36f37c2-5d4a-11e5-99ee-111229058274.png)

**Comment by pkozlowski-opensource** [comment]
Yes, this is duplicate. We are looking into it right now.

**Comment by czmj** [comment]
Ah sorry, I thought this had been sorted back in Jan.

**Comment by pkozlowski-opensource** [comment]
What I've meant is that is a duplicate of #12877

**Comment by czmj** [comment]
I think we posted at the same time. Sorry to bother you!
