### ISSUE TITLE
Feature request: Have templates uniformly ignore top level comments

### ISSUE THREAD

**Issue by azaslavsky** [angular/angular.js#12880]
Suppose I have following HTML template: 

```html
/* MyLittleApp Development Build: v1.2.3-alpha, Thu Sep 17 2015 15:34:02 GMT-0700 (PDT) */

<div class="sample">
  <span>The rest of my template goes here</span>
</div>
```

I realize that [these docs](https://docs.angularjs.org/error/$compile/tplrt) specify not to put HTML comments in the root of the template, and always have a single root DOM Node, no matter what.  But...why?  As shown above, HTML comments can be useful for noting file versions, build configs, etc.  I prepend a comment like the one above onto basically every file I put through my build process.

The weird thing is that putting comments in the template root is fine when I use those templates in controllers...but as soon as I try and use them for a directive, errors get thrown.  It would be great to enable comments in the template root.

**Comment by Moncef12** [comment]
Why not using a task runner to handle this ? I tkink these comments will not be available in production.

**Comment by azaslavsky** [comment]
Yeah in production one might remove these headers (I personally leave them
in as a quick version and metadata reference for recording bugs, etc).
Still, it seems like Angular should work in developmemt as well.  The
specific purpose of DOM comments is to be ignored by DOM interpreters, but
still visible in the source - since Angular templates are a sort of DOM
interpreter, shouldn't they respect that?

**Comment by frfancha** [comment]
@azaslavsky A comment is potentially a directive "call" itself in angular, so it is normal that it is seen as element. Therefore that makes really 2 elements

**Comment by Narretz** [comment]
Directive templates behave differently than controller templates. I think "only one root element" is important for elements that replace, so we cannot really change this either. And @frfancha is right, since we support comment directives we cannot simply ignore comments.

**Comment by azaslavsky** [comment]
Ok, the point about comment directives makes sense.  Thanks!
