### ISSUE TITLE
ngAnimate regression in 1.4.5

### ISSUE THREAD

**Issue by pkaminski** [angular/angular.js#12900]
I have a JavaScript animate triggered by `ng-show` that works fine in 1.4.4 and below.  However, in 1.4.5 and 1.4.6 I can observe a strange behavior: maybe about half the time, when the `ng-show` condition changes via an `ng-click` handler, I see the `ng-animate` and `ng-hide-animate` classes being added onto the element, as well as the `data-ng-animate="2"` attribute, but the JavaScript animation is not called until something happens to trigger another digest.

Another oddity is that when I'm listening for a raw `mousedown` event (not through a directive), and invoke the condition-changing code through an `$applyAsync`, the animation always works correctly.

Any idea what might be going on?  I know that's not much information to go on, but I figured I'd try that first before attempting to make a clean repro since I expect that'll be pretty hard.  Thanks.

**Comment by Narretz** [comment]
First thing first: Have you tried with 1.4.6?

**Comment by gkalpak** [comment]
From "However, in 1.4.5 and 1.4.6 [...]" I guess he did :)

**Comment by matsko** [comment]
Any chance you could put together a plunkr for me?

**Comment by pkaminski** [comment]
@matsko, I can try tomorrow, but since this looks like a race condition it might be tricky to get it to repro cleanly.  I was hoping that the details I gave and knowing which version it broke in might give you an idea...  If you have things you'd like me to try, I'm happy to poke around the Angular source to gather more data.

Another option could be to set up a broken instance of my app, with the Angular libs unminified, so you could reproduce it in situ.  Would that be helpful at all?

**Comment by pkaminski** [comment]
My apologies, the problem was most likely my fault.  My animation code uses `$rootScope.$$postDigest` to schedule the actual animation, and apparently in Angular 1.4.5 the animation isn't necessarily called from within a digest any more.  So unless the Angular docs happen to specify that JS animation calls happen within a digest it's a case of me depending on an implementation artifact.  I've worked around the issue.
