### ISSUE TITLE
docs.angularjs.org is very sporadic in connection 

### ISSUE THREAD

**Issue by pavithrancr** [angular/angular.js#12908]
![image](https://cloud.githubusercontent.com/assets/8965550/10006339/8a99204e-6071-11e5-94a7-ed324ea32938.png)

**Comment by pavithrancr** [comment]
![image](https://cloud.githubusercontent.com/assets/8965550/10006381/dadb1724-6071-11e5-9a73-46635608b677.png)

**Comment by Narretz** [comment]
I don't have any problems with it. Maybe it was your service provider?

**Comment by Narretz** [comment]
It doesn't seem to be a problem at the server-end, so I'm closing this.
