### ISSUE TITLE
rebind expressions by filter

### ISSUE THREAD

**Issue by leibale** [angular/angular.js#12904]
my filter has config that my change at any time,
i need listen to `config.change` and rebind all the expressions using this filter (and only them, i don't want to set the `$stateful` on the filter to `true` and run `$rootScope.$apply();` when i need to rebind).

**Comment by pkozlowski-opensource** [comment]
@leibale please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Thank you!

**Comment by leibale** [comment]
it's not a question, i know there is no option to rebind by expression, i need you (or any body) to add this option
