### ISSUE TITLE
Docs app will fail when we go to 1.6

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#12906]
The docs app needs improving to ensure that changes to the "minor" version do not cause a catastrophic failure of the production docs app.

**Comment by petebacondarwin** [comment]
The trick is not to update the 

```
"branchVersion": "^1.5.0-beta.2",
```

until the CDN is ready

**Comment by gkalpak** [comment]
Don't we need a similat issue for `1.7`?

**Comment by petebacondarwin** [comment]
Well strictly the information is in the Asana task. But even better we should fix the build process so that this can't happen... i.e. when searching for a viable release to use in the docs we shouldn't bail out if we can't find a version that matches the version being built.

**Comment by petebacondarwin** [comment]
Created a new issue.
