### ISSUE TITLE
ng-change inside directive not work 

### ISSUE THREAD

**Issue by ckrad** [angular/angular.js#12910]
```javascript
angular.module('app').directive('categoryselect', function() {
...
scope: {},
template: '<select ng-change="change()">...</select>',
link: function($scope, element, attrs) {
    $scope.change = function() {
        console.log('work');
    }
}
})
```

it will not work.

**Comment by gkalpak** [comment]
As the error you are getting in the console says, `ngChange` depends (requires) `ngModel` which is not present on your template.
Changing your template to `<select ng-model="val" ng-change="change()">...</select>` [fixes the issue][1].

---
That said, this is a general support question. Please, use one of the [appropriate support channels][2] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: http://codepen.io/ExpertSystem/pen/qONMNy?editors=101
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by ckrad** [comment]
@gkalpak  i have bind ngModel. but it still not work.

**Comment by gkalpak** [comment]
@ckrad, I don't think this is an issue with Angular, but some problem in your code (which is impossible to diagnose with the info provided).

Since this is a general support question, I recommend you use one of the [appropriate support channels][1]. Make sure to provide all necessary context to reproduce the problem (ideally a live reproduction using CodePen, Plnkr etc).

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by ckrad** [comment]
@gkalpak  i found the reason why ng-change not work. because i setted replace to true. there was no dom to bind the scope. am i right? i set replace to false. now it work.

**Comment by gkalpak** [comment]
@ckrad, `replace` alone shouldn't cause any issues (e.g. try adding `replace: true` in my [previous example][1] andit still works). Nonetheless, `replace` has been deprecated as it causes a lot more issues than it solves and its use is discouraged.

It is obviously some combination of `replace` with some other feature(s) that is causing the issue, but once again, it is impossible to say without a proper reproduction.

[1]: http://codepen.io/ExpertSystem/pen/qONMNy?editors=101
