### ISSUE TITLE
gantt-tooltip to display date in tooltip in gantt table

### ISSUE THREAD

**Issue by amitchandavale** [angular/angular.js#12912]
I want to display the date in the tooltip in the format "MMM DD(Dec 01)" on over over image. I tried out different options mentioned on angular js moment. The code is like this <gantt-tooltips enabled="true" date-format="moment.format("MMM DD");"><gantt-tooltips/> but this is not working but if i dont use date-format option it is dispalying date in default format i.e. MMM DD, HH:mm. and for moment().format(); also it is displaying date and time in default format. how should i resolve this.

**Comment by gkalpak** [comment]
This sounds an issue for another repo. If you are using a 3rg-party module, please open the issue in the corresponding repo.

**Comment by amitchandavale** [comment]
i am using this <gantt-tooltips enabled= "true" date-format="MMM DD"><gantt-tooltips/> in the HTML bu it is not working also i have tried with <gantt-tooltips enabled= "true" date-format="moment().format("MMM DD");"><gantt-tooltips/> but this one also displays only default date

**Comment by amitchandavale** [comment]
i am using this <gantt-tooltips enabled= "true" date-format="MMM DD"><gantt-tooltips/> in the HTML bu it is not working also i have tried with <gantt-tooltips enabled= "true" date-format="moment().format("MMM DD");"><gantt-tooltips/> but this one also displays only default date

**Comment by amitchandavale** [comment]
i am using date-format attribute in the gantt-tooltips div with MMM DD option but it is not working i have also tried the date-format option with moment().format() with different formats but it is still not working correctly

**Comment by gkalpak** [comment]
You are referring to APIs of 3rd-party modules (gannt-tooltip?, momentjs?).
Please, ask the question to one of the support channels for these projects.
