### ISSUE TITLE
checkbox and model inside A tag

### ISSUE THREAD

**Issue by coolbombom** [angular/angular.js#12917]
Hi

I don't know if angular is supposed to work like this, but I found an "issue" when a checkbox is inside an A tag with ng-model attribute.

the model is set once, but the display/checkbox is not updated or checked ... and nothing happens when you try to click the checkbox again.

hope it makes sence!

cheers
c_bb

**Comment by pkozlowski-opensource** [comment]
> hope it makes sence!

Sorry, it is not clear what you are saying... Please share a live reproduce scenario using plunker or similar if you believe that there is a bug in the framework. We need much more context to be able to help here, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue

**Comment by coolbombom** [comment]
Hi pkozlowski-opensource

I have created a quick example here:
http://plnkr.co/edit/p9bplnFvadHGNyJ3l6EP?p=preview

cheers
c_bb

**Comment by pkozlowski-opensource** [comment]
[HTML5 spec](http://www.w3.org/TR/html5/text-level-semantics.html#the-a-element) prohibits [interactive elements](http://www.w3.org/TR/html5/dom.html#interactive-content-0) in the `<a>` tag. `<input>` is an interactive element so putting it inside `<a>` is a bad idea :-(

Closing as this is not valid HTML and the issue at hand has nothing to do with AngularJS but rather with how browser interpret and handle HTML / DOM.

**Comment by coolbombom** [comment]
thank you
