### ISSUE TITLE
Angular Dynamic Routing causes Canvas "Failed to execute 'toDataURL' error

### ISSUE THREAD

**Issue by krusk** [angular/angular.js#12927]
I am using AngularJS built on top of Node/Express for a Web application. One of my routes has an HTML5 canvas that I convert to an image. If I traverse to that route with this, I have no issues with converting my canvas to an image:

    when('/myroute/, { templateUrl: 'views/mytemplate.html', controller: 'myCtrl as vm' })

However, when I use dynamic routing (since I need to pass a unique ID to the 'myroute' page), the Canvas to image conversion throws the following error:

>Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Here is the dynamic route syntax from my App.js:

    when('/myroute/:ID, { templateUrl: 'views/mytemplate.html', controller: 'myCtrl as vm' })

Why would a dynamic route cause this... what appears to be a CORS issue, and how do I resolve it? Could it be related to "living" on top of Node.js/Express?

Here is an example of how I convert the Canvas to an Image:

    var canvasImage = document.getElementById("c");
    var img = canvasImage.toDataURL("image/png");

**Update 1:** I just tried the following, but received the same error:

    var canvasImage = document.getElementById("c");
    var img = new Image();
    img.crossOrigin = "anonymous";
    img.src = canvasImage;
    img = canvasImage.toDataURL("image/png");

**Comment by gkalpak** [comment]
Please provide a live reproduction (e.g. using CodePen, Plnkr etc). It's next to impossible to tell what is causing the problem without a way to reproduce it.
Also, are you using `html5Mode` or "hashbang" mode ?

**Comment by krusk** [comment]
I am using html5 mode and for reasons beyond my control, I am not allowed to post the code.

**Comment by Narretz** [comment]
If we don't have a demo, it's next to impossible to see where the error is. Basically, we cannot even see if the bug is in angular or in your app. 
> generalizing it may not give us what we need.
True, but before you haven't tried to create a minimal demo, you cannot be sure of that.

**Comment by krusk** [comment]
Fair enough, let me see what I can put together from a minimal standpoint. It will take some time, but appreciate all of yours!

**Comment by krusk** [comment]
Alright, I put together a plunk and found that the dynamic routing with a plain canvas worked. It is when I used a image from a server for an overlay that the CORS popped up. It shouldn't be, but it is. Closing this out.

**Comment by gkalpak** [comment]
Again, this is next to impossible to debug without  a reproduction.
But it sounds more likely like a CORS issue. Are you sure the server is configured properly ?

**Comment by krusk** [comment]
Yes, I am using Azure Blob Storage and it is loading the overlay on screen properly.

**Comment by gkalpak** [comment]
Yet, it seems to "taint" the canvas (it's not just a question of being displayed properly).

**Comment by krusk** [comment]
Correct, and there must be some sort of odd conflict somewhere since a static route works, but only when getting to the page via a dynamic route are there issues.

**Comment by gkalpak** [comment]
BTW, I wonder if using "hashbang" mode would make any difference.

**Comment by krusk** [comment]
Solved it. The issue was with Fabric.JS. Once I set the flag for crossOrigin anonymous on the overlay I was loading, it worked. Not sure why it worked with a standard route beforehand.

**Comment by Narretz** [comment]
Good to hear that you solved it!
