### ISSUE TITLE
ngOptions not observing changes in model in chromium browser

### ISSUE THREAD

**Issue by marcin-chwedczuk** [angular/angular.js#12928]
Plunk for a problem is [here](http://plnkr.co/edit/eGkKpXUBp51Eox7BGiGa).

After timeout no option is selected in `<select>` control. This issue only occurs in Chromium, I have no problems with Firefox (and since I am on linux box I cannot test on IE).

I tested it on Angular 1.2, 1.3 and 1.4 with Chromium Version 44.0.2403.89

**Comment by Narretz** [comment]
Are you sure it doesn't work in 1.4? I've tested with latest Chrome + angular 1.4.6, and it works. I'm asking because that looks a lot like a bug that was fixed in 1.4.

**Comment by marcin-chwedczuk** [comment]
OK, my mistake when I created Plunk I used 1.3 instead of 1.4. Checked again and it works in 1.4. Sorry for troubles.
