### ISSUE TITLE
$q.race() method to match ES6

### ISSUE THREAD

**Issue by mhayes14** [angular/angular.js#12929]
Hi,

Any chance of a `$q.race()` method being implemented? $q is compatible with the ES6 promise spec apart from the race method.

Thanks

**Comment by jrencz** [comment]
:+1: 

@bluehayes you can implement it yourself easily if you need it by using `$provide.delegate()`. Here's a quick (and probably having some issues so be warned!) attempt https://gist.github.com/jrencz/0bf3917d0a28c2b87dff
