### ISSUE TITLE
Possible Performance Improvement (concerning Watchers in $digest loop)

### ISSUE THREAD

**Issue by NicBright** [angular/angular.js#12932]
Hi there,

today I've stumbled upon a "thing" inside the $digest function of $rootScope. 

This is the thing:
if you deep watch a considerably large object, then even the slightest change in it will make angular copy **the whole object** for the next comparison: [click here to compare](https://github.com/angular/angular.js/blob/681affef591273615e4505811eec663d0c0d1bb4/src/ng/rootScope.js#L777)

I think this could be improved by fine tuning which part is copied for the next comparison.

What do you think? Is it worth the effort to improve this? Or do you think that copying large objects is only a small part of time spent during $digest loop?

My use-case is deep watching our local "model" which holds various business objects of considerable size. This "model" can be considered to be a session thing which is why we need to watch it in the first place (to be able to persist it in web storage when it changes).

Regards,
Nicolas

**Comment by Narretz** [comment]
The question is, how would you fine-tune which part is copied? That's the thing, if the object is on the scope, it needs to be checked on each digest.

**Comment by NicBright** [comment]
I think what would practically work is to improve angular.equals(). One could make it accept a 3rd parameter which allows to hand over a tracking array, like this:

```javascript
function equals(o1, o2, paths) {
  if (!isArray(paths)) paths = null; // accept only arrays
  if (o1 === o2) return true;
  if (o1 === null || o2 === null) {
    if (paths) paths.push(''); // empty '' path means the object itself is different
    return false;
  }
  if (o1 !== o1 && o2 !== o2) return true; // NaN === NaN
  ...
```

This way, angular.equals() can still return a boolean, but it can also hand back information to the caller about the exact location where the given objects `o1` and `o2` actually differed. This information could then be handed back to angular.copy() to make it faster: the faster the bigger the object and the less change in it (maybe there's only a single change let's say somehwere 5 levels nested deep inside).

What do you think?

Regards,
Nicolas

**Comment by lgalfaso** [comment]
> This way, angular.equals() can still return a boolean, but it can also
> hand back information to the caller about the exact location where the
> given objects o1 and o2 actually differed.
>

This would imply that `equals` will need to keep on traversing the objects
even after it found a difference. With this in mind, I think it will not
make a difference, but would love to be proven wrong :) Now, without a
prototype implementation and a benchmark, this cannot be decided.

@NicBright do you want to give it a try?

**Comment by gkalpak** [comment]
Closing due to lack of response.

As @lgalfaso said, the proposed fix requires a non-negligible amount of extra work (e.g. traversing the whole object even if a change is found early on, keeping track of the paths to changed properties, additional logic to only copy the changed paths). There is no proof that the overall performance will be improved (and in what cases) - my feeling is that it won't.
<sub>(Same as @lgalfaso, I'll be happy to be proven wrong :smiley:)</sub>
