### ISSUE TITLE
ng-messages-include raises "Error: [jqLite:nosel]" when including empty file

### ISSUE THREAD

**Issue by 0xDCA** [angular/angular.js#12941]
As shown in http://plnkr.co/edit/VFrt4rXZaK194zwJg0P2?p=preview, the ng-messages-include directive attempts to call `angular.element()` with the content of the file (empty or spaces) and, because jqLite interprets every string that does not start with "<" as a selector, it will raise an error. 

The error will be raised if the included file is not empty but starts with a text. I am not sure if angular-messages should handle the case where the included file contains text outside a `<div ng-message="..."></div>`, but I believe it should handle empty files gracefully.

**Comment by Narretz** [comment]
Do you mean it should throw a more descriptive error or ...?

**Comment by 0xDCA** [comment]
Sorry for being unclear.

I believe it shouldn't throw an error for this case. 
I faced this issue when testing a custom directive. As I am adding messages from multiple files (i.e multiple `<div ng-messages-include="..."></div>`, I would like to test that they're added, and that they're added in the correct order. For the first case (just testing that messages are added from some custom sources), I just fill one of the sources with messages and leave the other ones empty.

It's easy to workaround (I can just add `<div></div>` to the 'empty' sources), but I wonder if it should fail at all.

**Comment by Narretz** [comment]
If you want to open a PR with this change, I'd be happy to look at it.

**Comment by gkalpak** [comment]
There you go #14726 :smiley:
