### ISSUE TITLE
Docs for $http interceptor - what is the config object?

### ISSUE THREAD

**Issue by adamzerner** [angular/angular.js#12949]
The docs say that you have access to the config object, but don't say what the object looks like. It'd be helpful to know what the object looks like.

**Comment by pkozlowski-opensource** [comment]
It is the same config object as documented in the "Usage" section of https://docs.angularjs.org/api/ng/service/$http

In other words - the same config that is used to trigger the original $http call that is being intercepted.

**Comment by adamzerner** [comment]
I don't understand. It says:

> The $http service is a function which takes a single argument — a configuration object — that is used to generate an HTTP request and returns a promise

But it doesn't document what this object looks like. Below, it gives examples using the shortcut methods `$http.get` and `$http.post`.

**Comment by gkalpak** [comment]
It's actually mentioned in the _General Usage_ section (which might not be the best name), but document in the [_Usage_][1] section.
It might be a good idea to add a link to the _Usage_ section on the phrase "configuration object" in:
_"The $http service is a function which takes a single argument — a configuration object — that..."_ 

[1]: https://docs.angularjs.org/api/ng/service/$http#usage

**Comment by Narretz** [comment]
The General Usage section itself doesn't show the config object very well, though, because it shows two examples with shortcuts.

**Comment by Narretz** [comment]
I have a PR here: https://github.com/angular/angular.js/issues/12950

Technically, it's almost impossible to miss the Usage section when reading the docs, it's simply that there's so much in there, and a beginner doesn't really know that the usage section comes at the end ..
