### ISSUE TITLE
Add an `$assign` method to Scope

### ISSUE THREAD

**Issue by xieranmaya** [angular/angular.js#12942]
It's known that Scope has a method `$eval` which returns expression value based on that scope;
But when we want to assign a value on Scope by string when using something like "life.meanning",
we should write this:
`$parse('life.meanning').assign(scope,42)`
it's a little bit boring
It would it be very convenient if there is a method called $assign:
`$scope.$assign('life.meanning',42)`

**Comment by gkalpak** [comment]
`$eval()` can also be used to evaluate "assign" expressions: `$scope.$eval('life.meaning = 42')`
But if you are going to assign values repeatedly, it is more performant to `$parse` the expression once and re-use the parsed expression (something you can't do with `$eval()`).

**Comment by xieranmaya** [comment]
What if I want to assign a variable on scope property like `scope.life.meanning = play`

**Comment by petebacondarwin** [comment]
`$scope.$eval('life.meaning = play')` is effectively the same thing as `$scope.life.meaning = $scope.play`.

I think `$eval` and in some cases `$parse(...).assign` has got this covered.

**Comment by xieranmaya** [comment]
what if I want to assign a variable to a scope property like
`scope.life.meanning = play`
2015年9月25日 下午5:58，"Georgios Kalpakas" <notifications@github.com>写道：

**Comment by gkalpak** [comment]
Why not simply do `scope.life.meanning = play` ?

**Comment by xieranmaya** [comment]
Because `play` may not a `$scope` variable, for example if I want a directive to write something to scope like:
```html
<div file-selected="user.selected.file" />
```
this directive `fileSelected` will write user selected file to scope provided by `event.target.files[0]`
the directive definition will look something like this(assume `$assign` is implemented):
```js
.directive('fileSelect', function() {
  return {
    link: function(scope, el, attr, ctrl) {
      scope.$assign(attr.fileSelected, event.target.files[0])
    }
  }
})
```
This way I can not use `$scope.life.meanning` because the `life` object may not be on scope at the time.

**Comment by petebacondarwin** [comment]
This is doable with $parse, as you say in the original post, and I think it is not such a big deal:
```
.directive('fileSelect', function($parse) {
  return {
    link: function(scope, el, attr, ctrl) {
      var fileSelectedExpr = $parse(attr.fileSelected);
      fileSelectedExpr.assign(event.target.files[0]);
    }
  }
})
```

You could even do this in the compile function if you knew that it would be a static string and not contain any interpolation.

**Comment by lgalfaso** [comment]
@petebacondarwin is spot on. This functionality is already present, and this issue can be safely closed

**Comment by pankajkachhwaye** [comment]
@petebacondarwin i have assign scope property for selected file using this 
`.directive('fileSelect', function() {
  return {
    link: function(scope, el, attr, ctrl) {
      scope.$assign(attr.fileSelected, event.target.files[0])
    }
  }
})`

scope file object is assigned successfully but problem is that i have set a $watcher for particular scope and $watcher function is not trigger, any idea.

**Comment by petebacondarwin** [comment]
@pankajkachhwaye  - `$assign` is not actually a thing. Did you implement it yourself?

**Comment by pankajkachhwaye** [comment]
not $assign its only assign
