### ISSUE TITLE
$DocumentProvider function

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/angular.js#12953]
I hate to even ask, but why is this:
```
function $DocumentProvider() {
  this.$get = ['$window', function(window) {
    return jqLite(window.document);
  }];
}
```
...not this instead?
```
function $DocumentProvider() {
  this.$get = ['$window', function($window) {
    return jqLite($window.document);
  }];
}
```
It is the first time I've seen it done without the $ version as input. Is there a specific reason why this is different?

**Comment by gkalpak** [comment]
If the question is about the name of the argument (`window` vs `$window`), it's just a name (it could be `win` or `foo` and I don't think there is any particular reason - could just as well be `$window`).
<sub>
In case it's not clear, the name of the argument does not play a role when using "[inline array annotation][1]" for DI.
`['someDep', function (someVar) {...}]` means: "Get me the dependency `someDep` and pass it as a first argument to my function." 
What you name the argument is local to your function and completely arbitrary.
</sub>

--
Closing as this is not actionable.
<sub>
BTW, it is recommended to use one of the [appropriate support channels][2] for these types of questions.
</sub>

[1]: https://docs.angularjs.org/guide/di#inline-array-annotation
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by OpenSiteMobile** [comment]
Yeah, I figured I shouldn't have asked. The problem is, when you are new to Angular, you don't know where normal JavaScript ends and Angular specific conventions begin, unless you ask. Yes it all seems so apparent when you know. Thanks anyway for the response.

**Comment by gkalpak** [comment]
> Yeah, I figured I shouldn't have asked.

I hope I didn't give the wrong impression: By all means, please, _do_ ask !
I just pointed out that there are other channels more appropriate for these types of questions :smiley:
