### ISSUE TITLE
IE9 Expected identifier exception

### ISSUE THREAD

**Issue by lookfirst** [angular/angular.js#12954]
I'm seeing it on an IE9 modern.ie win7 VM with angular 1.4.6.

Screenshot: http://take.ms/JswSg

I found this potentially related issue: http://stackoverflow.com/questions/32233586/angularjs-v1-4-4-expected-identifier-error-on-ie10

According to the developer guide https://docs.angularjs.org/guide/ie, IE9 is supposed to be supported.

**Comment by gkalpak** [comment]
Any chance of providing a live demo of the error (e.g. using CodePen, Plnkr etc) ?

**Comment by lookfirst** [comment]
Sadly not easily... =( That said, I'm not doing anything special. This error is clearly just the act of loading angular up and there being an error doing so.

**Comment by gkalpak** [comment]
How are you loading it ?

Is the error thrown on IE9 only ? Have you tried on other IEs ? How about IE11 in IE9 mode ?

**Comment by lookfirst** [comment]
Going to close this... seems to have been something else i guess... =(
