### ISSUE TITLE
error loading docs.angularjs.org

### ISSUE THREAD

**Issue by ittayd** [angular/angular.js#12960]
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.0-beta.0/$injector/modulerr?p0=docsApp&p1=E…s.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.0%2Fangular.min.js%3A19%3A463)

**Comment by Narretz** [comment]
I wonder how that happened.
You can still get it here: https://code.angularjs.org/1.4.6/docs/api

**Comment by Narretz** [comment]
Can you try CTRL+F5? That worked for me.

**Comment by Aleksey-Danchin** [comment]
I have this one trouble too
![2015-09-27-180923_1280x1024_scrot](https://cloud.githubusercontent.com/assets/4380886/10123479/2d9873b4-6543-11e5-8483-b0f8ef4da02e.png)

**Comment by rcbytes** [comment]
https://docs.angularjs.org/api/ng/directive/ngRepeat

broken also

**Comment by toddhgardner** [comment]
[TrackJS](https://trackjs.com/) would love to provide free monitoring and alerting for when JavaScript errors happen. If you're interested, let me know todd -at- trackjs dotcom

**Comment by petebacondarwin** [comment]
We are looking into this. It should be fixed in the next few hours.

**Comment by petebacondarwin** [comment]
See #12963

**Comment by lastlink** [comment]
docs.angularjs.org is broken again...
