### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by mohislm** [angular/angular.js#12961]
https://docs.angularjs.org/

<img width="769" alt="screen shot 2015-09-27 at 11 32 00 am" src="https://cloud.githubusercontent.com/assets/508043/10123593/7cdc1da0-650b-11e5-9476-204ebc3bb674.png">

**Comment by Narretz** [comment]
https://github.com/angular/angular.js/issues/12960#issuecomment-143565005
