### ISSUE TITLE
Input type number rounding large numbers

### ISSUE THREAD

**Issue by endamaco** [angular/angular.js#12973]
Hi, if you try to enter a big number (for example 211111111111111111) in the input field at https://docs.angularjs.org/api/ng/filter/number you'll see it gets rounded to 211,111,111,111,111,100 .

Why this happens?

**Comment by pkozlowski-opensource** [comment]
It is because JS can't handle such big numbers so it rounds them:
* http://stackoverflow.com/questions/1379934/large-numbers-erroneously-rounded-in-javascript
* http://www.ecma-international.org/ecma-262/5.1/#sec-8.5

**Comment by Narretz** [comment]
@pkozlowski-opensource Should we document this?

**Comment by pkozlowski-opensource** [comment]
@Narretz we could but this is JS-thing really so I rather would not.

**Comment by Narretz** [comment]
If people keep hitting this, a note in the docs will save us from closing these issues
