### ISSUE TITLE
Directive used in partial view gets wronge scope

### ISSUE THREAD

**Issue by renevaessen** [angular/angular.js#12978]
Hi.

I have a view that is loaded on my main page, 

 <div id="content" data-ng-view class="ng-cloak"></div>

..using the routing features.

In this - by routing parameters - loaded (orderEdit) view I have:

    <div data-ng-include="'views/order.html'" data-ng-controller="orderController"></div>

Inside 'views/order.html' I use a custom directive:

      <select class="quickAddressLeft" tabindex="200" data-text-model="quickAddressLeft" title="{{'views.order.hints.pickupHistory' | translated }}">
                            <option value="-1"></option>
                            <option value="-2">[{{ 'views.order.lastAddress' | translated }}]</option>
                            <option value="-3">[{{ 'views.order.ownAddress' | translated }}]</option>
                            <option value="-4">[{{ 'views.order.clearAddress' | translated }}]</option>
                            <option data-ng-repeat="lastAddress in lastAddressesLeft track by $index" value="{{ $index }}">
                                {{ lastAddress.Name }}
                            </option>
                        </select>

 but when I debug, I can clearly see that this directive does not inherit the scope of 'orderController', but from it's parent orderEdit.html/orderEditController which was loaded via routing.
 
Am I doing something wronge?

**Comment by Narretz** [comment]
Can you post a plnkr.co or similar? And what is the actual problem? Inheritance can look a bit confusing,

**Comment by renevaessen** [comment]
Thanks for your quick response.
I will create a simple reproduction upcoming weekend. 
cheers.

**Comment by renevaessen** [comment]
Hi..

I made a simple reproduction. I hosted it myself.

http://platformtest.for-our.info/repro/#/readme

**Comment by gkalpak** [comment]
@renevaessen, as @Narretz mentioned, a reproduction on plnkr.co, codepen.io etc is preferable, since we can more easily see (and modify) the source code.
BTW, you should try with the latest patch version to make sure the issue isn't fixed already.

**Comment by frfancha** [comment]
@renevaessen Look at your console: you have $digest already in progress error message because you are calling $apply in your angular event handler (line 66 of your script.js).
Also your code seems quite complex for what it does, if your problem is not solved by solving the $digest in progress problem, then it would be helpful for angular people that you first eliminate the lines not necessary to reproduce your issue.

**Comment by renevaessen** [comment]
I am not calling $apply in a angular eventhandler. Maybe in a jquery eventhandler.

The code seems complex, because I ripped everything else, that is irrelevant.

**Comment by renevaessen** [comment]
I have solved this problem, by using sessionStorage and custom url rewriting.
 
Still think it is an issue with the Angular version I used, if it is resolved in later versions, idk.
 
You should embrace this tip, and investigate though ;)

**Comment by Narretz** [comment]
One fundamental problem I see is that in your example, the $watch is initalized in the "orderController" which belongs to the order/new route. When you are changing to order/edit, the "orderEditController" is initalized, which doesn't have the watch, so you never get the alert.

**Comment by renevaessen** [comment]
@Narretz  All true what your writing, but your still mistakenly seeing this through. see: orderedit.html

**Comment by renevaessen** [comment]
http://platformtest.for-our.info/repro/views/orderedit.html

**Comment by Narretz** [comment]
If you can put your example in a form where I can see the code side-by-side with the result (e.g. https://plnkr.co), and with a clear explanation of the expected and actual behavior, then I'll be happy to look at it again.

**Comment by renevaessen** [comment]
Alright then :)

http://plnkr.co/edit/ncOvsZl0xr593OSBdrgf?p=preview
