### ISSUE TITLE
Feature: let ngClick directive catch "captured" events.

### ISSUE THREAD

**Issue by DOrlov77** [angular/angular.js#12971]
Currently ngClick proceed bubbled events only. It would be very useful to have an option to catch the  events in "capture" phase as well.

**Comment by gkalpak** [comment]
IMO, it is not such common a feature to add in core (even more so, considering that jqLite/jQuery do not support _capturing_ event listeners).

It's pretty trivial to make your own directive though.
([Example][1]) 

[1]: http://codepen.io/ExpertSystem/pen/meRdXM?editors=101

**Comment by DOrlov77** [comment]
Hi, that is exactly what I do (your example). But, IMHO, it is better to be consistent and use full event cycle implemented in the core (one core) (see http://www.w3.org/TR/uievents/#event-phase). I see already low-level usage of "captured" events inside angular-material lib and it's look dirty and messy.

**Comment by gkalpak** [comment]
I agree it would be a nice-to-have feature, but I don't think it would be easy to get right. And even if we did, there is still the problem that `jQuery` doesn't support them, so we couldn't use `jqLite`, but native event listeners (with any implications that come with that: inconsistency, more difficult to test etc).

TBH, I don't think it's a common enough usecase to justify the complexity and implementation/maintainance overhead (but would be happilly proven wrong - either by a convincingly strong usecase or by an unexpectedly simple (yet robust) implementation :smiley:).

Let's see what other people think...

**Comment by Narretz** [comment]
I agree with @gkalpak, the complexity stands in no relation to the use with this feature.
