### ISSUE TITLE
Can't build Angular.js on Windows using instructions from https://docs.angularjs.org/misc/contribute

### ISSUE THREAD

**Issue by Kyle-Reis** [angular/angular.js#12970]
The instructions for building and testing Angular.js call out git as a required dependency, and contains a link to http://www.git-scm.com/. However, at least on Windows, it seems that the GitHub desktop client (https://desktop.github.com/) is actually required. Moreover, if you have git installed from git-scm.com and added to your PATH, you can't build Angular.js even when building from the "Git Shell" that is made available on the desktop when installing Github Desktop. Here is what works for me on WIndows:

1.)    Install NodeJS
2.)    Install Java
                If you’re on a 64-bit machine, install the 64-bit version.
3.)    Install the GitHub desktop client
               You must install this client to build Angular.js. If you have installed git from git-scm.com, 
                it CAN NOT be added to your PATH.
               After installation, a prompt will appear, click “Run” to launch the GUI client. Click “Skip setup”  
               or go ahead and configure the client with your GitHub credentials, etc.
4.) From the GitShell (you should have a shortcut for this on your desktop after step 3) clone the Angular.js repo locally: 
               git clone https://github.com/angular/angular.js.git
5.)  Verify that java has been added to the PATH (run command “java” and see if you get a list of options or if it is unrecognized). 
                If not, log out, then back in to refresh your PATH. 
6.)    Cd to the root of the angular.js repository.
7.)    Run the following commands to install dependencies and build the repo:
                npm install –g grunt-cli
                npm install –g bower
                npm install
                bower install
                grunt package

**Comment by gkalpak** [comment]
Not sure why you think you need GitHub Desktop client to build Angular, but you definitely don't.
I don't have it installed and can still build it (_like a boss_ :stuck_out_tongue:).

It's probably some other issue (not related to Angular).

--
BTW, I've also downloaded `git` from http://www.git-scm.com/ and it sits nicely on my **Path** (`C:\Program Files (x86)\Git\bin;`).

**Comment by Kyle-Reis** [comment]
Just tried on a new Win10 VM and things do seem to work. I know a couple people who were hitting this issue in addition to myself across several different machines and Windows versions. However, this was over a month ago. Seems that whatever the issue was it doesn't repro anymore. Closing out this issue.
