### ISSUE TITLE
input type=email breake input $modelValue

### ISSUE THREAD

**Issue by lukaszwado** [angular/angular.js#12977]
If you use input type=email it is breaks input model value.
For example I would like to enter aaa@aaa.pl as email what will happen is:
entering aaa@ - not showing any value (input $modelValue is empty or undefined)
entering aaa@a.- removing value from input $modelValue

example:
http://jsfiddle.net/qbge5qse/45/

**Comment by Narretz** [comment]
The value will not be set on the scope if it is invalid. If you want invalid values to show up, you have to use ngModelOptions.allowInvalid, see https://docs.angularjs.org/api/ng/directive/ngModelOptions
