### ISSUE TITLE
Strange values in ng-options

### ISSUE THREAD

**Issue by brunocascio** [angular/angular.js#12980]
Hi everybody,

I created a select directive, and when inspect the options i see that the values has prepend with the type.

for example:

`<option value="string:person">Person</option>``

My directive:

```
.directive('dropdownDict', function () {
      return {
        restrict: 'E',
        scope: {
          ngModel: '=',
          ngData: '=',
          ngChange: '&',
          placeholder: '=placeholder'
        },
        require: 'ngModel',
        replace: true,
        template: '<div class="ui dropdown selection dropdown-light">' +
    				'<i class="dropdown icon"></i>' +
    				'<div class="text">{{ngData[ngModel]}}</div>' +
    				'<select ' +
    					'ng-options="k as v for (k,v) in ngData" ' +
    					'ng-model="ngModel" ' +
    					'ng-change="ngChange" ' +
    					'ng-selected="ngModel">' +
    						'<option value="">{{(placeholder) ? placeholder : "Select"}}</option>' +
    				 '</select>' +
    			'</div>',
        link: function (scope, elem, attr, ngModel) {
          scope.updateModel = function(value) {
            ngModel.$setViewValue(value);
          }

          ngModel.$viewChangeListeners.push(function() {
            scope.$eval(attr.ngChange);
          });

          elem.dropdown({
            onChange: function (value, text, $choice) {
                scope.updateModel(value);
            }
          });
        },
      };
    })
```

Calling in template:

```
<dropdown-dict
    ng-model="customer.type"
	ng-data="customerTypes"
	ng-change="changeCustomerType()"
	placeholder="'Select Customer Type'">
</dropdown-dict>
```

```
$scope.customerTypes = {'person': 'Person', 'organization': 'Organization'};
```

Thanks!

**Comment by Narretz** [comment]
Yes, this is how it works. Does this cause you any trouble?

**Comment by brunocascio** [comment]
Yes, because i need that the value be "person" instead of "string:person". How to fix this?

**Comment by Narretz** [comment]
You can use select + repeat instead of ngOptions. With ngOptions, it is not possible. Why exactly do you need the option value to be just "person"? Inside an angular context, I can't think of a scenario where this is necessary.

**Comment by brunocascio** [comment]
Ok i'll try.

In context angular, maybe it's necessary, but i need populate a json object, for example:

```
{"type": "person"}
```

But this, will be wrong:
```
{"type": "string:person"}
```

**Comment by Narretz** [comment]
Well, in angular you wouldn't go to the DOM to get the data, you would get it from the model. Which you already have, otherwise you couldn't populate the options. So it looks like you are approaching your problem from a non-angular way. But with more info, I can't say if it's reasonable or nor.

**Comment by brunocascio** [comment]
Well, i changed the directive code for this:


```
.directive('dropdownDict', function () {
      return {
        restrict: 'E',
        scope: {
          ngModel: '=',
          ngData: '=',
          ngChange: '&',
          placeholder: '=placeholder'
        },
        require: 'ngModel',
        replace: true,
        template: '<div class="ui dropdown selection dropdown-light">' +
    			'<i class="dropdown icon"></i>' +
    			'<div class="text">{{ngData["string:"+ngModel]}}</div>' +
    			'<select ng-model="ngModel" ng-change="ngChange"> ' +
    			  '<option value="">{{placeholder}}</option>' +
                          '<option ng-repeat="(k,v) in ngData" value="{{k}}" selected="{{ngModel==k}}"> ' +
                             '{{v}}' +
                          '</option>' +
    			'</select>' +
    		'</div>',
        link: function (scope, elem, attr, ngModel) {
          scope.updateModel = function(value) {
            ngModel.$setViewValue(value);
          }

          elem.dropdown({
            onChange: function (value, text, $choice) {
                scope.updateModel(value);
            }
          });
        },
      };
    })
```

```
<dropdown-dict
	ng-model="customer.type"
	ng-data="customerTypes"
	ng-change="changeCustomerType()"
	placeholder="Select">
</dropdown-dict>
```

but the problem now is how to bind `ng-change` to select?

**Comment by S-YOU** [comment]
may be `changeCustomerType($event.target.value)`?

**Comment by brunocascio** [comment]
@S-YOU the problem is that the event is not fired.

**Comment by Narretz** [comment]
Please post a demo on plnkr.co or similar.

**Comment by S-YOU** [comment]
@brunocascio may be because you are updating ngmodel manually.
ng-change do works with normal ng-model - http://jsbin.com/payuzoqesa/1/edit?html,js,console,output

**Comment by brunocascio** [comment]
@Narretz Plunker:

http://embed.plnkr.co/0s62CMbRSAtumn4PuolM/preview

<iframe style="width: 100%; height: 600px" src="http://embed.plnkr.co/0s62CMbRSAtumn4PuolM/preview" frameborder="0" allowfullscren="allowfullscren"></iframe>

**Comment by brunocascio** [comment]
I understand @S-YOU, then how to fire the function ngChange associated to directive?

**Comment by S-YOU** [comment]
hmm, `elem.dropdown({onChange` seems to be triggered here.

**Comment by brunocascio** [comment]
Well, works. I call the ngChange function in directive when updated

my code:

```
scope.updateModel = function(value) {
    ngModel.$setViewValue(value);
    scope.ngChange()
}
```

Thanks @S-YOU and @Narretz ! :)
