### ISSUE TITLE
Defining value '$sniffer' silently breaks ngAnimate 1.4.7

### ISSUE THREAD

**Issue by samhax** [angular/angular.js#12982]
When following the guides for Angular here https://docs.angularjs.org/guide/$location#browser-in-html5-mode and here https://docs.angularjs.org/api/ngRoute/directive/ngView#animations I found that when you do this on version 1.4.7 (just like the tutorial does) 

angular.module('ngViewExample').value('$sniffer', { history: true });

The application will simply stop adding the animation classes. No error whatsoever and no way to know what is going on.

You can see it happening here:
http://plnkr.co/edit/zLQ8OfdXaSzjNacpX98i?p=preview

**Comment by mzdunek93** [comment]
How about: 

```
angular.module('ngViewExample').value('$sniffer', { history: true, animations: true })
```

Seems to work for me.

You could also put `transitions: true` instead, or both.

**Comment by samhax** [comment]
It wasn't a conscious choice. I was just following the tutorial.

But if it's intended behavior, I think I will just send a fix to the team maintaining the documents.

**Comment by mzdunek93** [comment]
`$sniffer` is a service which checks the browser's capabilities. I guess they were trying to ensure that the code runs as if in the html5 environment regardless of the browser.

**Comment by Narretz** [comment]
I don't really understand why you would recreate these examples in your own project. It says numerous times that these are examples that show how location works in different browsers based on a fake browser. Also, this isn't a tutorial. But, yeah we can probably make it even more explicit.
