### ISSUE TITLE
Form submit event not triggered

### ISSUE THREAD

**Issue by seemas-grazitti** [angular/angular.js#13008]
Hi ,

I want to submit form when ng-change function called on select. but form doesn't submit.

$scope.resultCountFilter = function(e){
					var size_val = $( "#Resultcount" ).find( "option:selected" ).text(); 
					console.log('Check size-'+ size_val);
					$('#display_size').val(size_val);					
					angular.element('#searchFrm').triggerHandler('submit');
					
				}

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Comment by seemas-grazitti** [comment]
I didn't get the solution of my issue.
