### ISSUE TITLE
ng-submit doesn't work when called ng-change funtion

### ISSUE THREAD

**Issue by seemas-grazitti** [angular/angular.js#13011]
Hi ,

I want to submit form when ng-change function called on select. but form doesn't submit.

$scope.resultCountFilter = function(e){
var size_val = $( "#Resultcount" ).find( "option:selected" ).text(); 
$('#display_size').val(size_val);
angular.element('#searchFrm').triggerHandler('submit'); }

Please provide me solution to submit form from other function without reloading page.for ng-submit not working when i use above code.

**Comment by gkalpak** [comment]
Please, don't keep re-submitting issues that have already been closed (see #13008).

What @pkozlowski-opensource meant (https://github.com/angular/angular.js/issues/13008#issuecomment-145456981) is that this is not the appropriate place to post your question.
It is a general support question and as such should be directed to one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
