### ISSUE TITLE
Add support for "for of" loops in templates to iterate on Set and Map es6 datatypes

### ISSUE THREAD

**Issue by uriva** [angular/angular.js#13027]

**Comment by Narretz** [comment]
Can you elaborate on this? Do you mean in `ng-repeat`?

**Comment by uriva** [comment]
yes I mean ng-repeat

**Comment by mgol** [comment]
Related: #14123.

**Comment by Narretz** [comment]
Let's continue discussion here, as there's clearer info: https://github.com/angular/angular.js/issues/14600
