### ISSUE TITLE
ng-options doesn't work well when using objects

### ISSUE THREAD

**Issue by coli** [angular/angular.js#1302]
http://jsfiddle.net/ADukg/658/

The example uses ng-options to provide 3 different objects which can be selected. All works until you switch to the next section then comes back. As the implementation uses object comparison, Angular can no longer match the current selected with the datasource.

Conceptually, ng-options should store the 3 selection objects (somewhere) and their lifespan is tied to the "data" object's scope, and not to the ng-options's proxyOptions lifespan.

Also, the comparison should be on a key, and not on the object, in this example, the key is proxyType, there currently is no way to provide the key field to ng-option while still using the object as the value.

**Comment by Narretz** [comment]
`track by` is indeed the way to solve this: http://plnkr.co/edit/FIQ1eORODFibHon12rYz?p=preview

**Comment by dailytabs** [comment]
Track by does NOT solve it. Track by can only be used by arrays. The OP is reporting issues with objects.

Converting objects to arrays to "solve" the problem with objects is NOT a solution.

**Comment by senterright** [comment]
@dailytabs, similarly, converting arrays to objects just so your form data works smoother with id's from the backend is a pretty crappy solution too.

**Comment by Nanle21** [comment]
Found the answer using resources http://embed.plnkr.co/ZXo8n0jE8r3LsgdhR0QP/preview

**Comment by fionagithub** [comment]
Why does AngularJS include an empty option in select? and my default value is empty ?
blow is my code:
.directive('gettheme',function( ){
    return {
        restrict:"AE", 
         template:"<select ng-init='themedata=theme[0]' ng-model='themedata' ng-options='item for item in theme'  class='form-control'></select>",
        link:function(scope, element, attrs){ 
            scope.theme=['macarons', 'infographic'];
        }
    }
})

**Comment by MydlarzMateusz** [comment]
You dont have to write a whole directive for it.
 If you use ng-options angular usually make empty first option, but if
you dont want it, you have to define ng-model in your js file like
that:
$scope.option = ['banana','apple'];$scope.selectedOption = 'banana';
<select ng-model="selectedOption" ng-options="x in option"></select>

Best Regards.


2017-05-05 6:56 GMT+02:00 fionagithub <notifications@github.com>:

**Comment by tcjcodes** [comment]
For anyone still experiencing this, the `track by` was breaking the `ngOptions`. Removing it caused the `ngModel` binding to work as expected.

Below is my component's code:

```html
<select class="form-control"
        id="{{::$ctrl.elementId}}"
        data-ng-model="$ctrl.selectedKey"
        data-ng-options="item.key as item.label for (key, item) in $ctrl.items">
    <option value="" ng-if="::$ctrl.placeholder">{{::$ctrl.placeholder}}</option>
</select>
```
