### ISSUE TITLE
$cookies in IE

### ISSUE THREAD

**Issue by jacobharasimo** [angular/angular.js#13032]
I am using cookies to store my login token. So a user enters a username and password and submits it to the server. On good response from the server i set a cookie with this token.
```
var domain = $location.host();
$cookies.put('token', response.data.sessionToken,{domain: domain});
```

Then this token is, by use of an interceptor, appended to the authorization header on each request.

```
angular.module('SOMEAPP').
    factory('authInterceptor', function ($q, $log, $cookies) {
        return {
            request: function (config) {
                config.headers = config.headers || {};
                if ($cookies.get('token')) {
                    config.headers.Authorization = $cookies.get('token');
                }
                return config;
            },
            response: function resolve(response) {
                if (response) {
                    if (response.status === 401) {
                        $cookies.remove('token');
                        $log.debug('401 response user not authenticated');
                    }
                }
                return response || $q.when(response);
            }
        };
    });

```
This all works fine but I have noticed that since upgrading to angular 1.4 no IE wont connect. The problem is the on login it sets the cookie fine. When i go to my next view and $log the cookie its also fine. then i place a click event, that fires a api. In this call, in the interceptor above, the value for ```$cookies.get('token')``` is undefined.
In IE (10+) sometimes $cookies.get('token') returns fine as expected but it seams to expire itself fast.

**Comment by mfc-julius** [comment]
Why not using localStorage? I'd bet you would get rid of all of these issues.

**Comment by jacobharasimo** [comment]
Because cookies should work. I know I could use it but then there would be
no fallback for older browsers

**Comment by mfc-julius** [comment]
Even from version 1.3 Angular has dropped IE8 support (see https://docs.angularjs.org/guide/ie).

So have a look what browsers support localStorage:
http://caniuse.com/#search=localstorage

There's no point of using cookies, especially if your server code does not need to reed them.

**Comment by jacobharasimo** [comment]
in this case the server does need to use them as the the specific problem i
had was with an authentication token which i do want passed.

Look, point is cookies should work. They work in all browsers I tested
except IE. I also realize IE is, and always has been, a giant pile of crap
and should never be used by anyone (same is starting to be true with
Safari) BUT people do use it. Sure you can use other methods BUT if you
include a service/library/function as Angular has with $coookies it should
work as expected in all listed supported browsers. In this case it does
not. Therefore this IS A BUG.

Bugs should be fixed. This was issue was created to report a bug so it can
get fixed. It was not posted to ask for other developers opinions as to
what alternative methods or technologies can be used. I'm well aware of the
options and choices that exists.

**Comment by gkalpak** [comment]
@jacobharasimo, it's really hard to tell what is going on (and whether or not this is related to a problem in Angular or your code or IE or whatever). Could you provide a live demo (e.g. using CodePen, Plnkr etc) with details to reproduce the issue (e.g. browser/version, steps etc) ?

**Comment by Narretz** [comment]
Closing becasue we don't have a reproduce scenario.
