### ISSUE TITLE
ng-options don't check value type when is multiple

### ISSUE THREAD

**Issue by epplestun** [angular/angular.js#13046]
If selec tag has multiple attribute, the ng-options directive don't  checks the type of value, assuming that is an array, and then use .forEach method directly.

https://github.com/angular/angular.js/blob/master/src/ng/directive/ngOptions.js#L506

In my opinion it should be checked the type to avoid errors

**Comment by epplestun** [comment]
A simple solution:

```js
if(value && Array.isArray(value)) {}
```

**Comment by gkalpak** [comment]
Is there any (valid) usecase where `value` is not an array ?
If not, I think it's better to throw, than silently fail.

**Comment by epplestun** [comment]
Imagine, a directive that inserts other directives dinamically, and one of this directives has a "<select>" with "ng-options" directive, when you remove a directive with ng-options from the DOM the method $render is fired and value can be other thing and not an array, this is my reason to check the value type.

**Comment by gkalpak** [comment]
Could you share some code (or a live demo using CodePen, Plnkr etc) ?
It's not clear to me.

**Comment by epplestun** [comment]
I can't share because is private product .... I will try to make a codepen demo to demostrate.
