### ISSUE TITLE
Add documentation for structural option in animateCss service

### ISSUE THREAD

**Issue by sevdog** [angular/angular.js#13049]
The `structural` option for `$animateCss` service is undocumented on the service page (https://docs.angularjs.org/api/ngAnimate/service/$animateCss), but is used in the animation examples (https://docs.angularjs.org/api/ngAnimate).

To find out what this option do you must go to the source code of the service.
This feature should be documented for better knowledge.

**Comment by Narretz** [comment]
Would you like to open a PR with the changes?

**Comment by sevdog** [comment]
I will as soon as I have time.
