### ISSUE TITLE
.then callback alternatives

### ISSUE THREAD

**Issue by negherbon** [angular/angular.js#13053]
Hey,

I'm working in a project with use .success deprecated callback and the problem is: all the response of backend is prefixed with a .data object and the first parameter of .success callback  is only the data of response, but now callback .then return only one parameter with one object and for access the response now i need to use: response.data.data has another approach to use or other way to take only data in .then parameter?

Thanks.

**Comment by randalmaia** [comment]
.success deprecated notice
https://docs.angularjs.org/api/ng/service/$http

**Comment by Narretz** [comment]
If I understand you correctly, you should be able to use transformResponse to extract the data https://docs.angularjs.org/api/ng/service/$http#transforming-requests-and-responses

**Comment by negherbon** [comment]
@Narretz it works.

![t hanks](https://cloud.githubusercontent.com/assets/5859119/10466329/2fb6dbe8-71ca-11e5-8ccf-0ccd8647a646.jpg)
