### ISSUE TITLE
$$rAF callback not fired in iOS9, WKWebView

### ISSUE THREAD

**Issue by sapieneptus** [angular/angular.js#13052]
Specifically, the `requestAnimationFrame(cb)` doesn't seem to be firing it's callback. Works on other browsers, but iOS9 WKWebView seems not to work. 

I've read some [hack solutions](http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/) but curious if there isn't an Angular solution.

**Comment by sapieneptus** [comment]
To provide a bit more context, where the issue is manifesting is in this code:

```
$animate.on('enter', $(document.body), function(el, phase) {
        console.log("something was added");
      });
```

The log is never called in the WKWebView. I've tracked it down to `angular:notifyProgress()`:
```
function notifyProgress(runner, event, phase, data) {
        runInNextPostDigestOrNow(function() {
          var callbacks = findCallbacks(element, event);
          console.log({callbacks:callbacks});
          if (callbacks.length) {
            // do not optimize this call here to RAF because
            // we don't know how heavy the callback code here will
            // be and if this code is buffered then this can
            // lead to a performance regression.
            $$rAF(function() {
              console.log("Callback");  //Never called
              forEach(callbacks, function(callback) {
                callback(element, phase, data);
              });
            });
          }
        });
        runner.progress(event, phase, data);
      }
```

Let me know if I can provide any more info!

**Comment by Narretz** [comment]
I have looked through the page, but I can't find the "hack solution", not one specific to webkit that is. Can you point me to it?

**Comment by sapieneptus** [comment]
Hi @Narretz ,

After much exploration, I think the problem may have been related to the webview not being visible at the time of testing. Apparently, if `webview.hidden=YES`, iOS imposes some fairly restrictive limitations on what the webview can do, including refresh rates (to conserve energy, I suppose). 

Interestingly, if `webview.hidden=NO` but `webview.alpha=0`, the webview behaves as expected. Go figure.

**Comment by Narretz** [comment]
@sapieneptus Thanks for the update! Do you consider this issue to be solved, then?

**Comment by Narretz** [comment]
I think we can close this. Afaik, some browsers disable / slow down animation frames when the tab / window is not visible. It's possible that this was the issue - a similar issue is being tracked here: https://github.com/angular/angular.js/issues/12842
