### ISSUE TITLE
composer support?

### ISSUE THREAD

**Issue by burzum** [angular/angular.js#13056]
Bootstrap, CK Editor, Fontawesome, Jquery... They all have a composer.json file. It would be awesome if we could manage Angular in php apps through composer as well. Even our task runner (Robo) is a php tool and does all the asset building.

I don't mind creating a PR with a composer.json file, just let me know if it's desired or not.

**Comment by Narretz** [comment]
Your task runner is in PHP, you poor soul.
Just kidding. I've used PHP too, it's not that bad.
I don't know about composer support. What's needed for that? Maybe this could also be a community project?

**Comment by wesleycho** [comment]
Composer support probably would require a build task modification modifying a composer.json file in all of the distribution repositories - [here](https://github.com/symfony/symfony/blob/master/composer.json) is an example composer.json file. Most of that can probably be chucked, and specifying the version is [straightforward](https://getcomposer.org/doc/02-libraries.md#specifying-the-version).

**Comment by Narretz** [comment]
This never really got traction, and at this point in the AngularJS lifecycle it's probably not worth the effort to include this in the build.
