### ISSUE TITLE
`$animate leave` event is not bubbling when fired by `ngIf`

### ISSUE THREAD

**Issue by trescenzi** [angular/angular.js#13054]
I am looking to implement behavior in a parent whenever a child element is removed from the dom by `ngIf`. I have done this by placing an event handler on the parent listening for `leave` however the event doesn't seem to be bubbling.

[This plunker](http://plnkr.co/edit/FuQWTm02O91s8PK2slEU) demonstrates my problem. As I understand it, and according to the docs, `enter` and `leave` should both bubble although only `enter` is correctly doing so.

Thank you.

**Comment by frankweb** [comment]
Hi @trescenzi I'd like to know if your issue could be resolved with this pull request:

https://github.com/angular/angular.js/pull/12278

**Comment by trescenzi** [comment]
Hi @frankweb thanks for the quick response. It does fix the problem. Everything looks good if I build angular locally with those changes merged.

Is there any sort of timeline on when that change will be merged into master?

**Comment by frankweb** [comment]
I commented about merge the pull request, let's wait for a response :)

**Comment by frankweb** [comment]
@trescenzi  I'm not sure, but I asked about to merge the pull request. Let's wait for a response.
