### ISSUE TITLE
injecting ngMock crash the app

### ISSUE THREAD

**Issue by FrancescoMussi** [angular/angular.js#13063]
I have installed angular-mocks through bower.
But after injecting ngMock the app crashed with no errors in the console.
(angular-mocks.js is properly linked in the index.html)

It was happening in an Ionic app. I have tried in a simple angular app for test purpose and i am having the same behavior.

Am i doing something wrong or there currently some issues with angular-mocks?

Thank you!

**Comment by Narretz** [comment]
Can you provide a demo of the problem on plnkr.co or similar? Also, are you injecting ngMock in your real app? You shouldn't do that.

**Comment by FrancescoMussi** [comment]
Thanks for reply.

I have created this plunker: http://plnkr.co/edit/Un9xBtrm1yqG4HubEdza?p=preview

Currently the app is crashed. By removing 'ngMock' the app come back working as expected.

What do you mean I shouldn't inject ngMock in my real app?

**Comment by Narretz** [comment]
Look at your console, you are not actually including any version of angular mocks. You have `//code.angularjs.org/X.Y.Z/angular-mocks.js` X.Y.Z should be a version, like 1.4.7. You are also including a super old version of angular (1.0.8). Please use the latest, 1.4.7

ngMock is a module that "mocks" several core services of angular to make testing easier. You should never need it in your actual app.

**Comment by FrancescoMussi** [comment]
Ok that was actually a mistake of the plunker, sorry. (In the apps i have latest version)
I have updated the plunker but there is the same problem.

**Comment by Narretz** [comment]
Oh, I see. I don't actually know why it breaks. Why do you exactly need ngMock in your app, though?

**Comment by FrancescoMussi** [comment]
I was trying to set up the environment for unit testing

**Comment by Narretz** [comment]
You wouldn't do it like this. Here's a good guide: https://www.airpair.com/angularjs/posts/testing-angular-with-karma
