### ISSUE TITLE
getting issue  with angulat , TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by chaitrahn** [angular/angular.js#13062]
Hi friends,
   am working angular peoject, am getting above issue, till before 10 min everytghing was working fine , but now am getting below issue, 
http://i.imgur.com/kRdagcQ.png

pls help me

**Comment by Narretz** [comment]
There's not enough information to do anything about this issue. You'll have to isolate the problem and the create a demo on plnkr.co or similar.

**Comment by mfc-julius** [comment]
Undo everything you did in those 10 minutes - the issue is probably in your code.

FYI, personally I would suggest to drop jQuery when using Angular.

**Comment by Narretz** [comment]
Closing due to lack of response.
