### ISSUE TITLE
Angular v. 1.4.0 CORS problem 

### ISSUE THREAD

**Issue by codekraft-studio** [angular/angular.js#13060]
I read in previous issues that was fixed and I looked into $httpProvider to check that fix and actually there isn't $httpProvider.defaults.headers.common['X-Requested-With']
but is still not working for me any $http method.

I tried jsonp and it work perfectly, I tried jQuery and it works so I looked into the jQuery docs and I found this:
> __Note__: For cross-domain requests, setting the content type to anything other than application/x-www-form-urlencoded, multipart/form-data, or text/plain will trigger the browser to send a preflight OPTIONS request to the server.

I checked and angular is using by default: application/json for common, patch, post, put
So I tried to add this header to the get request:
```javascript
$http.get('myurl/feed', { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } })
```
as jQuery does for $.ajax by default but is still not working..always the same error:
```html
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Can someone say me what make jQuery work and above all why $http jsonp method is working and bypassing this "issue" of Access-Control-Allow-Origin ? 

thanks in advance

**Comment by Narretz** [comment]
In 99% of the cases, the problem with CORS is the server and not the client. Are you sending custom headers with your request and is your server configured to accept them?

Mozilla Developer Network has a quite good article on CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by codekraft-studio** [comment]
mmh I told you I set Content-Type request header and nothing more
but I'm sure is not server side because with get method $.ajax of jQuery is working.
And also with $http.jsonp is working too.. I tried to run once with jQuery and I noticed there are no different or particular request headers..

**Comment by Narretz** [comment]
It's possible that angular sets another header by default, which would influence the browser behavior. You should check if the actual request has different headers between jquery and angular.
I'm gonna close this issue, because I think this is more of a support questions than a bug / feature report.

**Comment by codekraft-studio** [comment]
ok.. I will check.. but I explored the headers and the one it set is just Content-Type application/json

I still can't find a solution..
