### ISSUE TITLE
Issue: MouseEnter & MouseLeave Event is working in Mobile Devices with Touch event I

### ISSUE THREAD

**Issue by shmdhussain** [angular/angular.js#13073]
Mouse Enter and Mouse Leave event is working in iPhone6 OS: iOS 8 and samsung android 4.4.2 chrome 45

Please see this code in codepen http://codepen.io/shmdhussain/pen/bVroGK , When i tap over using my finger in touch devices the mouse events are working. Ideally it should not have worked with touch.

Is this the default behaviour or issue. Please help me in this . Thanks in advance for any help.

**Comment by petebacondarwin** [comment]
It seems to me that this is just the behaviour on iOS etc.
See http://stackoverflow.com/questions/15600511/dealing-with-mouseenter-and-mouseleave-on-the-ipad

**Comment by Narretz** [comment]
Mouse events are usually translated to touch events on touch devices. The angular event handlers are very minimal and you'll have to roll your own if you want advanced functionality.
