### ISSUE TITLE
scope in filter is no longer watched in angular 1.4

### ISSUE THREAD

**Issue by badoet** [angular/angular.js#13071]
changing the value of the scope used in angular filter
no longer trigger an update to the filter
http://plnkr.co/edit/iVABuG5ApiwgyV6RRwQA?p=preview

if u change the angular version loaded in html to 1.2.8 it will work fine.

is this change intended? or regression?

**Comment by Narretz** [comment]
This is a breaking change that was introduced in 1.3, see https://github.com/angular/angular.js/blob/master/CHANGELOG.md#130-rc2-tactile-perception-2014-09-16

What that means is that the filter is only applied if any inputs to the filter change. You can use the stateful flag to make it run on every digest. However, I'd recommend you pass the conversion rate to the filter instead.
