### ISSUE TITLE
 [ngAria] aria-required is not allowed for input type="checkbox"

### ISSUE THREAD

**Issue by k7sleeper** [angular/angular.js#13078]
We've the problem that ngAria adds attribute aria-required to our checkboxes and W3C Validator rightly complains about that.

What am I doing wrong? Or is it an issue in ngAria?

**Comment by gkalpak** [comment]
Could you provide a demo of the issue (preferrbly a live reproduction using CodePen, Plnkr etc) ?

**Comment by Narretz** [comment]
I think this is going to be fixed by https://github.com/angular/angular.js/pull/13095

**Comment by gkalpak** [comment]
@Narretz, I thought #13095 is about `tabindex` (this one is about `aria-required`). No ?

**Comment by marcysutton** [comment]
We need another PR to cover extraneous `aria-*` attributes....it piggybacks on the `tabindex` work, but should remain separate.

**Comment by Narretz** [comment]
Yeah, it's a different issue, sorry for the noise. Thanks @marcysutton for all the work!
