### ISSUE TITLE
angular js

### ISSUE THREAD

**Issue by sherksiva** [angular/angular.js#13088]
i need space inside the experssion {{}}.how to add space inside the {{}}

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !
<sub>
That said, you can add space as you would in plain-old JS: by concatenating a string containing a space. E.g.: `{{ someProp + ' ' + someOtherVal }}`
</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
