### ISSUE TITLE
$http service: if a CORS request fails, the response (status code) returned is always 0

### ISSUE THREAD

**Issue by adrianbader** [angular/angular.js#13085]
Suppose an http POST to a different origin. This implies CORS, including a CORS preflight exchange. Now suppose the OPTIONS request returns a 503 service unavailable error due to a server problem. In this case the error handler gives ""for data and 0 for status instead of giving me the status code 503 and the text:service not available.

Please see http://stackoverflow.com/questions/31312703/whenever-a-cors-http-request-fails-the-response-returned-is-always-0 for full description.

Thanks in advance for fixing this.
 - badera

**Comment by gkalpak** [comment]
Are you sure this is an Angular issue. Angular has nothing to do with the OPTIONS request; the browser handles that. I don't think this is Angular-related at all (nor that we can do anything about it).

In any case, I would try to use "raw" `XMLHttpRequest` and see what I get.
If you get empty data and a status code <= 0, then this can't be fixed on the Angular side.

**Comment by adrianbader** [comment]
Dear gkalpak. Thanks for your answer. You are absolutly right. I tried it with `XMLHttpRequest` directly and the status code is also 0. So it seems really to be the browser returning absolutly no info in the given case... Sorry to raise an issue for this.

**Comment by NagarajuGaddam1** [comment]
Hi gkalpak ,

I am facing similar kind of issue in my application i use rest services json communication in my application but some my Angular ajax is not even hitting the Rest API servr and it is giving -1 as status how can i handle such situation in my Angular application and can you give some context why will this happen?

**Comment by gkalpak** [comment]
@NagarajuGaddam1, it is likely a CORS issues (in which case you would need to configure your server properly). I can't really say though. I would try asking for help on one of the [general support channels][1].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by NagarajuGaddam1** [comment]
@gkalpak 

Thanks for the reply. please put here if you found anything around it.
