### ISSUE TITLE
Link debounce and keypress

### ISSUE THREAD

**Issue by smebberson** [angular/angular.js#13097]
I've created a fiddle to demonstrate the problem, https://jsfiddle.net/smebberson/n91rj4uu/

1. Open the fiddle, and show your console
1. Type something really quickly, and then hit Enter (in a swift sequence)

You'll notice that 'Enter' hits the console, before the complete version of the text you entered. The problem with this is, it's hard to evaluate the completed text when a specific key is pressed (Enter) when using debounce.

Here is a workaround, https://jsfiddle.net/smebberson/s4w65mbx/

Do the same steps as before. You'll notice 'Enter' evaluation comes after the last debounce. Is there a better way to do this? Can we link debounce and keypress for certain keys?

**Comment by Narretz** [comment]
keypress and ngModel aren't really designed to work together, that's unfortunate, but it is what it is. You can make this a better though if myAppDirective is directly on the input, because then you can require the ngModelController and react directly on the values / options: http://plnkr.co/edit/Jb9iahrMwcIipH0fur1L?p=preview

**Comment by frfancha** [comment]
You don't have the "problem" without debounce, but should you have it, I wouldn't find that a bug:
ngModel is, at least conceptually, linked to the event generated by the browser regarding the full text.
keyPress is linked to each key.
So it is quite normal that the keypress event is triggred before the "full text changed" event.
That happens in this order in GUI framework in C++, Smalltalk, ... I don't find abnormal that angular behaves the same way.
If you need the current text in the keypress handler you could read input.text (that would be a raw text however)

**Comment by smebberson** [comment]
@Narretz, I simplified the use case for demonstration purposes, my component is a little more complex.
Thanks for the reply!
