### ISSUE TITLE
PageSpeed Insights ( Google speed test tool) is warning about Render-blocking javascript for my angularvendor.js

### ISSUE THREAD

**Issue by ifventures** [angular/angular.js#13090]
Hello,

I minified all vendor package into vendor.version_number.js and also my angular code into scripts.version_number.js.

They are working well.  But Google speed test tool (PageSpeed Insights)  is warning me for Render-blocking javascript (For my minified package).

After that i checked chrome console's network tab. And the web site is waiting for almost 3 sec to build angular package before getting datta.

Conclusion if we use angular.js, we must wait more then 3 seconds to see web site?

Sorry for my english.

Thank you for your help.

**Comment by Narretz** [comment]
What do you mean by
> the web site is waiting for almost 3 sec to build angular package before getting datta

Does that mean you have a blank page for 3 seconds before your code is executed? This can have many reasons, especially if you package all your vendor script code into one file. Are you sure it's angular's fault? You should try with all your scripts on their own, and see which blocks.

That said, this question is better suited to one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question Github is for feature and bug reports only.
