### ISSUE TITLE
ngPattern invalid error clobbers ngMaxlength validity

### ISSUE THREAD

**Issue by joshforester** [angular/angular.js#13092]
Steps To Reproduce (use plnkr's below):
1. type in 11 alpha characters to trigger maxlength error
2. type in a '$' character to trigger pattern error 

Expected Behavior:
Both maxlength and pattern $error's will be set to true

Actual Behavior:
The pattern $error being set to true toggles the maxlength $error to false.    

Broken in 1.2.29 (latest 1.2 at this time)
http://plnkr.co/edit/pELZZaS24RBaKv23yQQ1?p=preview

Working in 1.3.0
http://plnkr.co/edit/J22On1Tafvh1VcGK5es7?p=preview

**Comment by Narretz** [comment]
In 1.2.x, an input can only have one error at any time. This was changed in 1.3, and will not be backported to 1.2, sorry.
