### ISSUE TITLE
In $http, Fail When CORS Fails

### ISSUE THREAD

**Issue by trisys3** [angular/angular.js#13104]
Would it be possible to fail an `$http.get`, `$http.post`, etc. when CORS fails? We have the host, so we know when it is CORS; we have the headers, including `Origin`, `Access-Control-Allow-Origin`, etc.; we know whether we needed credentials. Is there anything else we need? Most or all major browsers can tell whether CORS fails and color the response red or some other UI change, so can we do the same thing?

To be clear, I am asking to reject the promise returned by an `$http` request, when CORS fails.

**Comment by gkalpak** [comment]
I **does** get rejected ([demo][1]).

Closing, as things seem to already work as expected.
<sub>Feel free to re-open with more details in case I misunderstood your point.</sub>

[1]: http://codepen.io/ExpertSystem/pen/vNWBzJ?editors=101

**Comment by trisys3** [comment]
You are right, I do get rejected. I believe I was getting lost in the promise chain, my mistake.
