### ISSUE TITLE
jqLite does not allow to select a button

### ISSUE THREAD

**Issue by KamBha** [angular/angular.js#13107]
For some reason, in jqLite this fails:-

angular.element('button').css('display', 'none');

Now, I can't see anything in the documentation that would indicate why angular.element('button') doesn't work.

but angular.element('div') would work.

Here is an example:-

http://plnkr.co/edit/kSAcIbmhiigCL157WQpl?p=preview

Can we either clarify why angular.element doesn't work here in the documentation or update jqLite to allow for selecting the button tag.

**Comment by gkalpak** [comment]
There is nothing special about `button`s or `div`s. In fact `angular.element('div')` will fail as well.
If you want to select all elements by tag-name, you can use something like `$document.find('button')` ([updated plnkr][1]) - but you should be doing this in a controller <sub>(just saying...)</sub>.

As explained in the docs, the `element` argument (in `angular.element(element)`) is an _"HTML string or DOMElement to be wrapped into jQuery"_.
I agree that is not super-clear, so if you would like to submit a PR to improve the docs, we would gladly consider it :smiley:

[1]: http://plnkr.co/edit/lRnetnTq3nwA10C4eVR7?p=preview
