### ISSUE TITLE
Why is the call to $apply needed in $http?

### ISSUE THREAD

**Issue by thorn0** [angular/angular.js#13108]
I started to think about it looking at #12557. At first glance the answer is obvious: we need to update the views after we got a response, so we trigger a digest. But hey, it'll be triggered anyway because `$http` uses `$q` internally. And when a `$q` deferred is resolved, it schedules a digest. So can't we just remove that call to `$rootScope.$apply` (with all the `$applyAsync` thing altogether)? Am I missing something? If it's needed only for the tests, the `$apply` call should be moved to `$httpBackend.flush`.

**Comment by gkalpak** [comment]
Hey, this sounds about right. I would try replacing `$q` with `$$q` inside `$http`and keep `$http`'s apply (sync or async) - probably disable-able with an extra argument.

(This has been discussed before (more or less). See #2049 and https://github.com/angular/angular.js/issues/2049#issuecomment-59020072.)

--
@thorn0, would fancy giving it a shot ?

**Comment by thorn0** [comment]
> I would try replacing $q with $$q inside $http and keep $http's apply (sync or async)

It won't work this way. The `$apply` call in `$http` is useless (or seems so if I do miss something) because it happens just after the response comes, but before any callbacks are called, which means before any scopes are modified. After `git blame`'ing, it seems to me that this `$apply` call is merely a historical rudiment.

**Comment by gkalpak** [comment]
True. Yet, by merely removing `$http`'s apply, we can't have the `applyAsync` perf improvement (which we don't have now either I think).

--
So, I would still try replacing `$$q` with `$q` and add another callback at the end of the promise chain to make the digest (sync or async). That way we can easily have normal apply (using `$rootScope.$degest()`), async apply (using `$rootScope.$applyAsync()`) or add an extra option to skip apply altogether (in which case we should not add anything at the end of the chain).

<sub>Again, this is off the top of my head, so take it with a grain of salt :smiley:</sub>

**Comment by gkalpak** [comment]
Or do you mean removing the [`$rootScope.$apply()`][1], but keep the [`$rootScope.$applyAsync(...)`][2] ?
That would work as well, I guess, but we would still get an extra $digest in the async case (I think).

Plus, replacing `$q` with `$$q` would also enable skipping apply altogether (as an option).

[1]: https://github.com/angular/angular.js/blob/v1.5.0-beta.1/src/ng/http.js#L1275
[2]: https://github.com/angular/angular.js/blob/v1.5.0-beta.1/src/ng/http.js#L1272

**Comment by thorn0** [comment]
> try replacing $$q with $q and add another callback at the end of the promise chain to make the digest

We can break someone's response interceptors this way.

> Or do you mean removing the $rootScope.$apply(), but keep the $rootScope.$applyAsync(...) ?

No, I mean we can safely remove all these lines:

```
        if (useApplyAsync) {
          $rootScope.$applyAsync(resolveHttpPromise);
        } else {
          resolveHttpPromise();
          if (!$rootScope.$$phase) $rootScope.$apply();
        }
```
and leave only 
```
        resolveHttpPromise();
```

**Comment by gkalpak** [comment]
>> try replacing $$q with $q and add another callback at the end of the promise chain to make the digest

> We can break someone's response interceptors this way.

How exactly ?

--
>> Or do you mean removing the $rootScope.$apply(), but keep the $rootScope.$applyAsync(...) ?

> No, I mean we can [...] leave only `resolveHttpPromise();`.

That would essentially remove the `useApplySync` optimization.
We don't want to remove that one (I suppose it was added for a reason).

**Comment by thorn0** [comment]
>>> try replacing $$q with $q and add another callback at the end of the promise chain to make the digest
>> We can break someone's response interceptors this way.
> How exactly ?

Those interceptors can modify the scopes and expect a digest to happen earlier than in the end of the interceptor chain.

>> No, I mean we can [...] leave only `resolveHttpPromise();`
> That would essentially remove the useApplySync optimization.
> We don't want to remove that one (I suppose it was added for a reason).

No, we'll just get the same effect for free.

**Comment by gkalpak** [comment]
OK, I'll believe you when I see it :stuck_out_tongue:

**Comment by thorn0** [comment]
Did anyone see the effect of this useApplyAsync optimization? :)

**Comment by thorn0** [comment]
OK, please see this PR #13111.

**Comment by thorn0** [comment]
I think this issue is important in the first place because `$http` should be a model for building async services. It should be a canonical example of how async operations and the digest cycle should be married so that libraries like [bramski/angular-indexedDB](https://github.com/bramski/angular-indexedDB) could learn from it. But unfortunately, this example is misleading now. It leaves people wonder why it's written the way it is, why this `$apply` call can be needed.

**Comment by rcollette** [comment]
Is there a consideration that needs to be made for JavaScript to Native calls with regards to digest cycles?
http://stackoverflow.com/questions/42305044/angularjs-digest-already-in-progress-when-calling-javascript-native-bridge-func?noredirect=1#comment71765277_42305044

**Comment by jbedard** [comment]
Closing, see: https://github.com/angular/angular.js/pull/13128#issuecomment-387832395
