### ISSUE TITLE
unable to do grunt package? how to resolve this?

### ISSUE THREAD

**Issue by shaunstanislaus** [angular/angular.js#13115]
```bash
shaunstanislaus@Master ~/workspace/MEAN/fullstack_practice/app/angular.js (master) $ grunt package
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'cheerio'
Warning: Task "package" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by Narretz** [comment]
It looks like your npm dependencies are not correctly installed (Error: Cannot find module 'cheerio'). Try `npm install`. That said, this is more of a usage question, please try these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by shaunstanislaus** [comment]
@Narretz i did npm install, obviously `npm install` would be the first thing i do before i even do grunt. 

are you sure you know how to resolve this issue ?
