### ISSUE TITLE
Directive transclusion with script tags in IE8

### ISSUE THREAD

**Issue by niclassahlin** [angular/angular.js#13121]
When having an attribute directive that transcludes its content and apply it to a `<script>` tag, the content seems to be lost in legacy browsers (IE8) while it works as expected in IE>=9. 

[Here is a reproducable example](http://plnkr.co/edit/5uqDEZ8eMmRteQ50Eytu?p=preview)

**Version:** 1.2.28
**Browsers:** IE8

**The issue:**
The issue seems to be in jqLite's clone method, where the cloning is done by simply calling `element.cloneNode(true);`. For `<script>` tags in IE8, this clones the tag itself but ignores the content. 

jQuery solves it specifically for IE<=8 by using a document fragment: https://github.com/jquery/jquery/blob/1.11-stable/src/manipulation.js#L239

**Comment by lgalfaso** [comment]
Angular 1.2 that is the only supported version that has IE8 support, is only open for security issues. Given, that this never worked in IE8 and it works as expected in newer versions, then closing this issue.
