### ISSUE TITLE
Unit testing: Error thrown during promise resolution causes "$digest already in progress" message for the *next* call to $scope.$apply()

### ISSUE THREAD

**Issue by gregjacobs** [angular/angular.js#13127]
Angular 1.4.7

```javascript
it( 'thrown errors and $digest', inject( function( $rootScope, $q ) {
    $q.when().then( function() { 
        throw new Error( 'Test Error' ); 
    } );

    expect( function() {
        $rootScope.$apply();  // to finalize the promise
    } ).toThrowError( 'Test Error' );

    $rootScope.$apply();  // **digest already in progress** 
} ) );
```

Our codebase throws many errors to alert developers of problems, but we're having trouble testing them. This minimal test case showcases the problem.

**Comment by Narretz** [comment]
Why are you adding the second $rootSCope.$apply()? Is something coming afterwards in this test? To me, it doesn't make sense to have essentially two $rootScope.$apply() after another.

**Comment by gregjacobs** [comment]
It's just a minimalist example of the problem. 

An error thrown during a digest doesn't allow Angular to know that it's no longer in a digest.

**Comment by Narretz** [comment]
Okay. I don't know maybe there's a way to manually clear the digest loop.
However, to keep the test focused shouldn't you simply test that the error
is thrown and nothing more?
Am 27.10.2015 21:18 schrieb "Gregory Jacobs" <notifications@github.com>:

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
