### ISSUE TITLE
ngOptions documentation and example directly contradict each other

### ISSUE THREAD

**Issue by weshardee** [angular/angular.js#13134]
From the [docs](https://docs.angularjs.org/api/ng/directive/ngOptions):

> Do not use `select` **`as`** and **`track by`** in the same expression. They are not designed to work together.

Then immediately following that, there is an example where they are used together in the same expression:

```
item.subItem as item.label for item in values track by item.id
```

Either the code example directly contradicts the previous statement, or I'm misinterpreting this and the documentation is very confusing. I ran this by a couple of other devs to validate that others are interpreting it the same way I am.

**Comment by ryanhart2** [comment]
This is a duplicate of #11768, and there is a PR in progress #13007.

**Comment by weshardee** [comment]
Oops. My bad. I tried looking but didn't see that other issue. Thanks for taking a look.
