### ISSUE TITLE
ng-animate stops working correctly when there is an ng-if element looking at the same property

### ISSUE THREAD

**Issue by xelhark** [angular/angular.js#13132]
Look at this plunkr:

http://plnkr.co/edit/iv4qFtSShUWR7glbAhWA

You can see the behavior I'm talking about if you use chrome dev tools and break on attribute modification on the div with the ng-class property.

Basically, ng-animate stops using the classes 'red-add' or 'red-remove' if there is an ng-if element inside looking at the same property. The data-ng-animate-status attribute is stuck to 1 and doesn't advance to 2, I believe this is an unintended bug, but it took me a LOT of time to find out the reason why it wasn't working. Even if it's not immediately fixable, a footnote or a warning in the docs would at least give people something to look out for.

**Comment by Narretz** [comment]
In the example, the classes are never added, because there are no transitions / animations on the element. If you add transitions, the classes are added and animations start to work: http://plnkr.co/edit/2XiyN5HaIlkSCWfMmIc4?p=preview
