### ISSUE TITLE
Help please, how to set the default paramSerializer to $httpParamSerializerJQLike?

### ISSUE THREAD

**Issue by KingMario** [angular/angular.js#13130]
I try the following config to setup $httpProvider defaults, but the $httpParamSerializerJQLike is not invoked when I post a request using `$http.post(myUrl, {phone: '18812222'}).then(func1, func2);`. The form data in the post request is a JSON string `{"phone":"18812222"}`, which is not serialized JQLikely.

    myApp.config(['$httpProvider', function ($httpProvider) {
        $httpProvider.defaults.headers.post["Content-Type"] = "application/x-www-form-urlencoded";
        $httpProvider.defaults.paramSerializer = '$httpParamSerializerJQLike';
    }]);

Thanks

**Comment by armanforghani** [comment]
I have the same problem using Angular 1.4.6.

**Comment by gkalpak** [comment]
The paramSerializers are for serializing...params (not the payload/data of the request).
I.e. `$http.get('/url', {params: {foo: 'bar'}})`.

Currently, automatically serializing the data is not supported (but you could use the provided paramSerializers to serialize it manually).

--
Closing as this works as expected atm and the feature request for adding support for serializing data is tracked in #6039.
<sub>
BTW, you can use a paramSerializer to serialize payload/data, but you need a little setup and it is not guarranteed to work in all edge-cases, as it hasn't been designed/tested for that purpose.
See https://github.com/angular/angular.js/issues/6039#issuecomment-113502695.
</sub>
