### ISSUE TITLE
Angular doesn't find module - why?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular.js#13133]
I have set up a simple and small text application for using ui-grid/RequireJS.

My problem with the setup below is that Angular starts searching for the ng-app directive before the HTML has finished loading. So randomly I get an Angular error stating that module "gridtest" could not be found:

```
 [$injector:modulerr] Failed to instantiate module gridtest due to:

Error: [$injector:nomod] Module 'gridtest' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

http://errors.angularjs.org/1.4.7/$injector/nomod?p0=gridtest
   at Anonymous function (http://localhost:2920/_Mocks/uiGuid/js/angular.js:1986:11)
   at ensure (http://localhost:2920/_Mocks/uiGuid/js/angular.js:1910:5)
   at module (http://localhost:2920/_Mocks/uiGuid/js/angular.js:1984:7)
...
```

What am I doing wrong? Why is AngularJS searching for the module before the DOM has completely been loaded?

Here's my source:
```javascript
require(["uiGrid"], function ()
{
    angular.module("gridtest", ["ui.grid"])
    .factory("loaddata", ["$http", function ($http)
    {
        return function ()
        {
            return [
                { name: "John", Address: "Texas" },
                { name: "Doe", Address: "Florida" }
            ];
        };
    }])
    .controller("gridCtrl", ["$scope", "loaddata", function ($scope, loaddata)
    {
        $scope.data = loaddata();
    }]);
});
```

```html
<!DOCTYPE html>
<html>
<head>
    <title>jqGrid Test Page</title>
    <link type="text/css" rel="stylesheet" href="css/ui-grid.min.css" />
</head>
<body ng-app="gridtest">
    <div ng-controller="gridCtrl" style="padding: 2em; background-image: linear-gradient(rgb(56,77,112), white)">
        <div ui-grid="{ data: data }"></div>
    </div>

    <script type="text/javascript">
        var require =
            {
                paths:
                    {
                        jquery: "../../../Content/js/jquery-2.1.4/jquery-2.1.4.min",
                        angular: "angular",
                        uiGrid: "ui-grid.min"
                    },
                shim:
                    {
                        "angular": { deps: ["jquery"] },
                        "uiGrid": { deps: ["angular"] }
                    }

            };
    </script>
    <script type="text/javascript" src="js/require.js" defer="defer" data-main="js/GridTest.js"></script>
</body>
</html>
```

**Comment by tomtom87** [comment]
You must set the `ng-app` directive inside of the `<html>` tag e.g

```html
<!DOCTYPE html>
<html ng-app="gridtest">
<head>
    <title>jqGrid Test Page</title>
    <link type="text/css" rel="stylesheet" href="css/ui-grid.min.css" />
</head>
```

**Comment by SetTrend** [comment]
Just tried. It doesn't make a difference.

... and many StackOverflow answers confirm that it doesn't make a difference.

**Comment by tomtom87** [comment]
Wait sorry that was full retard of me. It's because you don't have the module gridtest loaded into your page mate, you need to set a `<script>` for it - unless that `js/require.js` is doing it. You want double check it and see there in the console if you can access the gridtest module first.. safe

**Comment by SetTrend** [comment]
No problem. I happen to regularly boob myself, too ;)

But your new reply isn't helpful, either, I'm afraid. As you can see from the code snippets, module `gridtest` actually exists. And it's getting loaded - occasionally. But occasionally it isn't.

I assume, AngularJS doesn't well co-operate with RequireJS. Is this assumption true? Or did I do something wrong here?

**Comment by JustinBeaudry** [comment]
It looks like your using a deferred script loader. That could be a problem for the use of the `ng-app` directive. If `DOMContentLoaded` has fired then `ng-app` will automagically call `angular.bootstrap`. So you may need to manually bootstrap your angular application once you're certain that all scripts have been loaded. https://docs.angularjs.org/guide/bootstrap#manual-initialization

**Comment by SetTrend** [comment]
I understand. Yet the problem is not that I need to manually initialize AngularJS, but instead that AngularJS is throwing an exception, and I'm not able to suppress this exception.

**Comment by robwormald** [comment]
this is an either / or decision: you *either* use `ng-app="yourapp"` in your HTML, *or* you use `angular.bootstrap(document, ['yourapp']);` - using both doesn't work.

**Comment by robwormald** [comment]
other note: you'll find that with async loading, its possible you'll see a flash of `{{binding}}` tags before angular bootstraps - the `ng-cloak` directive is useful for handling this scenario.

**Comment by robwormald** [comment]
all of that said, one pretty hard and fast requirement of angular is that all modules be loaded before bootstrapping - that is, you can't lazy-load a module at some point after the application has bootstrapped.

**Comment by Narretz** [comment]
thanks @robwormald for solving this!

**Comment by lafiza** [comment]
this is still a issue for me

<html ng-app="workflow">
.
.
.
 <script>
var app = angular.module('workflow', ['ui.bootstrap']);

</script>
.
.
</html>

**Comment by khullah** [comment]
You normally can't lazy load, but with [oclazyload](https://oclazyload.readme.io/) you can. In case it helps someone..
