### ISSUE TITLE
(ngShow) cannot evaluate expression containing void 0

### ISSUE THREAD

**Issue by burner-account** [angular/angular.js#13149]
version: 1.4.7

I usually like to use "void 0" in expressions to test for undefined values, so i tried that on ngShow
```
<div data-ng-show="someVar !== void 0">
</div>
```
This majestically goes boom with the following output:

Error: [$parse:syntax] Syntax Error: Token '0' is an unexpected token at column 17 of the expression [someVar !== void 0] starting at [0].  
at <mycdn>/bower/angular/angular.js:68:12
at Object.AST.throwError (<mycdn>/bower/angular/angular.js:13057:11)
at Object.AST.ast (<mycdn>/bower/angular/angular.js:12827:12)
at Object.ASTCompiler.compile (<mycdn>/bower/angular/angular.js:13276:31)
at Parser.parse (<mycdn>/bower/angular/angular.js:14146:29)
at $parse (<mycdn>/bower/angular/angular.js:14248:39)
at Scope.$watch (<mycdn>/bower/angular/angular.js:15412:19)
    
I have not tested this against other expression evaluating directives, but since this comes from the AST i suspect other failure candidates as well.

Is this something that is expected or defined behaviour?

Have a nice day!

**Comment by frfancha** [comment]
As void 0 is undefined, you can write someVar !== undefined to get the desired behaviour

**Comment by lgalfaso** [comment]
The `void` operator is not supported in angular expressions. This is explained here https://docs.angularjs.org/guide/expression

**Comment by burner-account** [comment]
> As void 0 is undefined, you can write someVar !== undefined to get the desired behaviour
> -frfancha

Yeah, sure. Until some funny guy assigns something like $scope.undefined = 'bla' or even worse assigns to $rootScope. This is why i use void 0, which evaluates to undefined but is not undefined.

> The void operator is not supported in angular expressions. This is explained here https://docs.angularjs.org/guide/expression
> -lgalfalso

Thank you very much, that explains it.

**Comment by lgalfaso** [comment]
Inside an expression, undefined will always evaluate to undefined. If you
want to access a property on $scope under the name "undefined" then the
expression must be this.undefined

**Comment by burner-account** [comment]
@lgalfaso  Thanks a lot for your relentless effort to answer my questions and further my understanding of angular. I appreciate your patience.
