### ISSUE TITLE
how to using <script for="activeid" event="AppLaunched()" ></script> in angularjs

### ISSUE THREAD

**Issue by vominhtam** [angular/angular.js#13157]
Hi all

I have issue when using activex with angular js. I don't known how to load <script for="activexid" event="AppLaunched()"></script> because if load it on html file event auto call although activex object not yet load.

please help me

Thank all so much

**Comment by mcpDESIGNS** [comment]
This is more of a question for [stackoverflow](http://www.stackoverflow.com), as it's not an issue with Angular code.

**Comment by Narretz** [comment]
I agree with @mcpDESIGNS . Please use of the support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
