### ISSUE TITLE
Checkbox form models not in scope until changed (or model pre-defined in the Controller)

### ISSUE THREAD

**Issue by mcpDESIGNS** [angular/angular.js#13155]
#### [jsFiddle demo (using latest v1.4.7)](http://jsfiddle.net/mcpDESIGNS/2jdzw9z4/)

The issue is, when submitting a form with a checkbox in it. This key/value pair doesn't even populate the scope until :
a) The checkbox has been touched / changed
b) Or if you pre-populated the ngModel of the checkbox to true/false in the Controller beforehand.

For example:

    <div ng-controller="DemoController as vmDemo">
        <form>
            <label>Is active:
                <input type="checkbox" ng-model="vmDemo.myForm.isActive" />
            </label>

            <button type="submit" ng-click="vmDemo.submit(vmDemo.myForm)">Submit</button>
        </form>
    </div>

    angular.module('app', []).controller('DemoController', function () {
   	   var vm = this
    
       vm.submit = function (formResults) {
           console.log(formResults);
       };
    });

When the Controller is first loaded and `submit` is pushed, the object simply outputs `undefined` as opposed to at at least populating the object in scope w/ `{ isActive : false }`.

If the checkbox is checked, and submit is pushed: 
`(index):33 Object {isActive: true}`

If unchecked after that, and submit is pushed it is *populated as it should be*:
`(index):33 Object {isActive: false}`

#### The obvious quick fix
Of course adding `vm.isActive = false;` in the controller, but is this intentional?? It seems to me everything else is treated as a boolean and even undefined things turn to `false` when it comes to `ngShow / ngIf / etc`, shouldn't this be the same?

**Comment by m-amr** [comment]
@mcpDESIGNS 
You should five the model a default value in the controller.
     this.myForm = {};
     this.myForm.isActive = false;
add these two lines to the controller and it will work.

**Comment by mcpDESIGNS** [comment]
I know that, but this just doesn't seem like "default" intentional behavior does it?
You don't need to "set" any other type of input to default behavior ("" empty string, or something else), why would checkboxes be any different?

I know it's not neccessarily a "bug", this seems like more of a simple possible *enhancement*

Example form:

    <input ng-model="vmDemo.user.name">
    <input ng-model="vmDemo.user.age">
    <input ng-model="vmDemo.user.isActive" type="checkbox" /> IsActive?

    <button ng-click="vmDemo.submit( vmDemo.user )">Submit</button>
    // ^ this will output this:
    {
        name : '',
        age    : ''
    }

**Comment by frfancha** [comment]
The current behavior (model not set if gui not touched) is perfect for us, please do not change anything!

**Comment by nick13jaremek** [comment]
Checkboxes in Angular are special in the way that they only allow true or false values, and how its underlying logic works. If you do not set an initial *true* value in the controller's $scope, then the checkbox will be false by default.

It is right after you click on the checkbox when the $scope variable switches between *true* and *false* boolean values.

This behaviour is the most consistent one, in order to avoid mismatches between the view and the controller checkbox values.

**Comment by mcpDESIGNS** [comment]
@nick13jaremek if you see the demo the value is neither true nor false when it starts, that's the problem. You have to manually set it to false when the controller loads. This seems very inconsistent. No other value requires that.

**Comment by nick13jaremek** [comment]
@mcpDESIGNS You can use the ng-init directive inside your checkbox element to initialize the checkbox value in the view itself, rather than on the controller.

**Comment by frfancha** [comment]
@mcpDESIGNS <<This seems very inconsistent>>
I don't think so: it is the same for a simple ng-model. The property on the scope is unchanged until you touch the input (It stays what it is, null, or undefined, or '' e.g.). If the property myProp doesn't exist, it is not even created if the input is linked to myObj.myProp.

**Comment by mcpDESIGNS** [comment]
I suppose I'm the only one! Never mind then, I'll stick to defaulting them like usual then :)
