### ISSUE TITLE
SOLVED: $httpBackend does not respond to request when asynchronous beforeEach is used

### ISSUE THREAD

**Issue by vrka** [angular/angular.js#13153]
If asynchronous beforeEach in jasmine is used (via the parameter done) requests are not responded to. This test timeouts:

```javascript
      describe('Fails', function() {
        beforeEach(function(done) {
          $timeout(done, 10);
        });
        it('should work', function(done) {
          $httpBackend.expectGET('url').respond();
          $http.get('url').then(done);
          $httpBackend.flush();
        });
      });
```
If whole the `beforeEach` part is ommited the request is responded to.

Here is a plunker http://plnkr.co/edit/dwe57Y21wBXcXiXU1Cqq

with jasmine 2.3.4 and angular 1.5.0-beta.1

**Comment by brandonroberts** [comment]
Trying using the done in your describe instead of your beforeEach. Once that done is finished the tests are ready to be run, so it should run correctly.

```javascript
      describe('Fails', function(done) {
        beforeEach(function() {
          $timeout(done, 10);
        });
        it('should work', function(done) {
          $httpBackend.expectGET('url').respond();
          $http.get('url').then(done);
          $httpBackend.flush();
        });
      });
```

**Comment by vrka** [comment]
describe does not pass done. When changed as described in plunker both the test pass but it is only because they become same - synchronous.

**Comment by brandonroberts** [comment]
I see. I'm not sure what the Jasmine support for $timeout is, but setTimeout works fine with your updated plunk in the first post.

**Comment by vrka** [comment]
I found the problem. The second test was actually never run because the $timeout in the beforeEach section was not flushed.

This is the proper way.
```
      describe('Fails', function() {
        beforeEach(function(done) {
          $timeout(done, 10);
          $timeout.flush();
        });
        it('should work', function(done) {
          $httpBackend.expectGET('url').respond();
          $http.get('url').then(done);
          $httpBackend.flush();
        });
      });

```

And it works ok

Please mark as Solved

**Comment by brandonroberts** [comment]
:+1:

**Comment by Narretz** [comment]
Glad you got is solved. You can also close your own issues!
