### ISSUE TITLE
Tabs change controller many times

### ISSUE THREAD

**Issue by lecoleco** [angular/angular.js#13154]
Hi,

My application open the pages inside the tab!

I have too a page to make a lock screen! If i try to open two pages with diferentes controllers and try to open a lock screen, all controllers come start again!

If i change something before call lock, everything is lost. A page within the tab is restarted.

Thank you

**Comment by frankweb** [comment]
Hi @lecoleco could you provide an example in http://plnkr.co/?

**Comment by lecoleco** [comment]
Hi,

Yes http://plnkr.co/edit/zhSB4599cRMxj80rQ2CV?p=preview

When start, show on console

start controller ctrltab2
start controller ctrltab1

When click on button New Page, show on console

newPage

When return to the tabs, show on console

start controller ctrltab2
start controller ctrltab1
newPage
<h5>start controller ctrltab1</h5>
<h5>start controller ctrltab2</h5>

That is the problem, the controllers restarts again.

Thank you

**Comment by lecoleco** [comment]
Hi, 

What am I doing wrong?

Thank you

**Comment by Narretz** [comment]
The controllers are part of the elements, that's why they are initialized whenever the element is created, and destroyed whenenver the element is destroyed. If you need to persist data between view changes, you should use a service (or localstorage etc.).
