### ISSUE TITLE
$http service synchronous option 

### ISSUE THREAD

**Issue by mehmetotkun** [angular/angular.js#13164]
Why **$http** service don't have synchronous option? It is important when calling it on window 'beforeunload' event.

**Comment by mcpDESIGNS** [comment]
It seems that the `$http` service has been hard-coded to be `asynchronous`.

It looks like you'll have to create your own service (either using the vanilla `xhr.open(method, url, false /* synchronous */)` or use jQuery if you have that in your project.

**Comment by gkalpak** [comment]
You can decorate (or replace) [`$xhrFactory`][1] (if you are on a version of Angular that supports it), but I would definitely recommend **against** using synchronous requests (e.g. see [MDN][2]).

[1]: https://docs.angularjs.org/api/ng/service/$xhrFactory
[2]: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#open()

**Comment by Narretz** [comment]
I agree with @gkalpak. Also, this feature has been discussed previously and the result was that we don't want it, e.g. see here: https://github.com/angular/angular.js/issues/7025

**Comment by mehmetotkun** [comment]
@gkalpak and @Narretz it seems that you are right. Also, using ajax inside  on window 'beforeunload' is not a good idea. Because the form data have been lost. :) thanks.
