### ISSUE TITLE
Locale for input[month] is not applied

### ISSUE THREAD

**Issue by suguiura** [angular/angular.js#13162]
Hi guys,

I expected input[month] directive to apply my locale, but it doesn't. For instance, the month names are always in English.

**Reproducable**: always
**Browsers**: Chromium 45.0
**Operating system**: Linux debian 3.16.0-4-amd64

**Steps to reproduce**:

- Create a new HTML file with the following content:

```html
<!doctype html>
<html ng-app="main">

<head>
    <script src="https://code.angularjs.org/1.4.7/angular.min.js"></script>
    <script src="https://code.angularjs.org/1.4.7/i18n/angular-locale_pt-br.js"></script>
    <script type="application/javascript">
        angular.module('main', [])
        .controller('c', ['$scope', function ($scope) {
            $scope.month = new Date(2015, 10, 1);
        }]);
    </script>
</head>

<body ng-controller="c">
    <input type="month" ng-model="month"/>
    <div>{{ month | date:'MMMM yyyy' }}</div>
</body>

</html>
```

- Open it in Chromium and you'll notice the month name within the input and widget is in English, while the formatted date is printed in Portuguese.

**Comment by lgalfaso** [comment]
The `<input type="month">` is native to Chrome and out of the scope of angular
