### ISSUE TITLE
jQuery data missing in $destroy event

### ISSUE THREAD

**Issue by kdietrich** [angular/angular.js#13168]
I'd like to follow up on https://github.com/angular/angular.js/pull/3089. jQuery's `$destroy` is not a perfect solution: I'm using `ng-repeat` to display widgets that have `data` bind to it. When I remove/update a widget, Angular sometimes rebuilds some DOM elements. This leads to calling of jQuery `$destroy` even though they were not removed (because they were just rebuilt). `$destroy` of `$scope` gets only called for really removed widgets, but here `data` is not available anymore.

**Comment by Narretz** [comment]
Could you please set up a minimal demo of what you are doing? ngRepeat will re-use elements if you use a track by expression, otherwise the elements will be destroyed when items are removed from the collection.

**Comment by Narretz** [comment]
Closing because we don't have a reproduce scenario. :(
