### ISSUE TITLE
Documentation of property of property of service doesn't render

### ISSUE THREAD

**Issue by csaftoiu** [angular/angular.js#13178]
Given this code:

    var zomg = angular.module('zomg', []);

    /**
     * @ngdoc object
     * @name zomg.Foo
     * @description
     * # Foo
     */
    zomg.factory('Foo', [function () {
      return {
        /**
         * @ngdoc object
         * @name zomg.Foo.bar
         * @propertyOf zomg.Foo
         * @description
         * A property of Foo
         */
        bar: {
          /**
           * @ngdoc object
           * @name zomg.Foo.bar.baz
           * @propertyOf zomg.Foo.bar
           * @description
           * A property of Foo.bar
           */
          baz: 100
        }
      };
    }]);

I get this documentation:

![image](https://cloud.githubusercontent.com/assets/43113/10763680/499edd6c-7ca1-11e5-96c5-77b6cf49e774.png)

That is, the `Foo.bar.baz` property doesn't show up in the documentation. It is parsed properly - since if I change `@propertyOf` from `zomg.Foo.bar` to something like `zomg.Foo.doesnotexist`, I get an error when compiling the documentation. But the results don't show up in the resulting HTML.

How should I document nested objects? The actual use case is that I have a service which contains `$resource`s, and I want to document the special methods on the `$resource`. I'd rather do it in a standard jsdoc way (`@ngdoc function` with `@methodOf` of the special function itself) rather than including it in the `@description` of the `$resource` in a non-standard way.

**Comment by Narretz** [comment]
Hi, this is a question for https://github.com/angular/dgeni-packages, please open an issue there. Thanks!
