### ISSUE TITLE
ngAnimate regression in 1.4 & 1.5

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#13177]
We have an interesting regression from 1.3 to 1.4 & 1.5 with ngAnimate in UI Bootstrap - [here is a Plunker](http://plnkr.co/edit/ny1Mb75ebJDexvoFeX1N?p=preview), and the issue is https://github.com/angular-ui/bootstrap/issues/4667 .

It should be noted that it works perfectly fine in 1.3, but both branches of the relevant code in the Plunker copy of the carousel code (lines 50-61 in ui-bootstrap.js) never seem to run the event handler callbacks.

**Comment by matsko** [comment]
Could you provide more info as to what's going on? It seems broken all together.

**Comment by wesleycho** [comment]
I'm not sure what is happening in the internals of ngAnimate here, but this is the problem block we are coming across in UI Bootstrap
```js
      if (NEW_ANIMATE) {
        $animate.on('addClass', slide.$element, function(element, phase) {
          if (phase === 'close') {
            $scope.$currentTransition = null;
            $animate.off('addClass', element);
          }
        });
      } else {
        slide.$element.one('$animate:close', function closeFn() {
          $scope.$currentTransition = null;
        });
      }
```

The event handlers are never getting called in either when tweaking the block.

**Comment by Narretz** [comment]
That's still broken on master.
What I would like is a smaller demo with clear repro steps. It's a bit problematic since the slider seems erratic.

**Comment by wesleycho** [comment]
Sorry, looks like this was a false alarm - I made an incorrect change it looks like, fixing it makes this work properly again as seen [here](http://plnkr.co/edit/SlgtN9H3CDrulTnuAzIW?p=preview).

**Comment by Narretz** [comment]
@wesleycho Great to hear!
