### ISSUE TITLE
ngAnimate: Cannot re-enable animations with `$animate.enabled`

### ISSUE THREAD

**Issue by dcherman** [angular/angular.js#13179]
If you are a descendant of an element that potentially called `$animate.enabled(elem, false)`, you cannot re-enable animations on yourself by calling `$animate.enabled(elem, true)`

It looks like when you do the latter, the element is simply removed from the internal HashMap rather than having a value toggled.  As a result, the while loop that checks whether or not animations are enabled for a given element only considers whether or not a parent is disabled, not whether or not it's explicitly enabled.

http://jsfiddle.net/rogqp47y/8/

**Comment by Narretz** [comment]
Looks like a bug to me, but let's ask @matsko if this is intended behavior.
