### ISSUE TITLE
Upgrading from 1.3 to 1.4 broke my link directive

### ISSUE THREAD

**Issue by moneytree-doug** [angular/angular.js#13187]
I read over the migration docs for the upgrade, and I didn't expect this to be an issue. I went from 1.3.15 to 1.4.7. 

I can't seem to understand why this is breaking. I would expect the parent controller to be passed to the transcluded child, but it's giving me a function instead. Perhaps it's my outdated methodology of not using the controllerAs syntax, but that syntax seemed more like an option than anything else. It especially seemed unnecessary since all I needed was the communicate between a parent and child.

Here's my code: 

```
angular.module('utility-belt').directive 'ubView', ()->
  {
    require: '^utilityBelt'
    restrict: 'E'
    transclude: true
    scope: {
      viewId: '@'
    }
    template: '<div ng-show="selected" ng-transclude></div>'
    link: (scope, element, attrs, ubController) ->
      ubController.api.addView scope
      return
  }


angular.module('utility-belt').directive("utilityBelt", ($window, $rootScope)->
  return {
    restrict: 'E'
    templateUrl: 'views/utility-belt.html'
    scope: {}
    transclude: true
    controller: () ->
      this.vm = {}
      this.vm.isOpen = false
      this.vm.views = []

      hideAllExcept = (viewId) ->
        _.each(this.vm.views, (view) ->
          if view.viewId == viewId
            view.selected = true
          else
            view.selected = false
          return
        )
        return

      toggleUtilityBelt = (viewId)->
        this.$evalAsync(() ->
          this.vm.isOpen = !this.vm.isOpen
          if this.vm.views.length == 1
            this.vm.views[0].selected = true
          else
            hideAllExcept(viewId)

        )

      this.api = {}
      this.api.addView = (view) ->
        this.vm.views.push view
        return

  }
)

```

**Comment by lgalfaso** [comment]
Hi, can you create a plunker that shows this error?

**Comment by moneytree-doug** [comment]
@lgalfaso If you look at the JS console, you would see an error related to ``addView`` and a dump of the arguments: http://plnkr.co/edit/AVrjF1H5gmGhJPCkAmz3

**Comment by Narretz** [comment]
That's because coffeescript always returns the last statement in a fn, and since angular 1.4, the controller fn return value is used as the actual controller. So you have to either remove the return or explicitly return the controller: http://plnkr.co/edit/15D9JqmvQhPfWoMjcAET?p=preview There was also an error in your addView fn, btw.

**Comment by moneytree-doug** [comment]
@Narretz Ahh, I see! I appreciate the help and the quick reply, thank you! I definitely should move over to ES6 sooner rather than later.
