### ISSUE TITLE
Error lexer in resouceUrlWhitelist

### ISSUE THREAD

**Issue by Geoide** [angular/angular.js#13189]
In my .config I have a white list like this:

    $sceDelegateProvider.resourceUrlWhitelist([
            'self',
            'https://s3-eu-west-1.amazonaws.com/something/**'
        ]);

But this fire a lexerr error:
```
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 2-2...
````
Only if I remove "**" (two asteriks) works (but the url is blocked for $sce). My url is somthing like this:
```
https://s3-eu-west-1.amazonaws.com/something/img$002.jpg
```

My white list is very close to the angular docs example. I not sure if this is a error. Any idea?

**Comment by Narretz** [comment]
Can you post where the error points to? Without the context it's hard to say what's wrong

**Comment by Geoide** [comment]
Yes, sorry. This image is the complete message error.
![err1](https://cloud.githubusercontent.com/assets/2845462/10792724/3c836d62-7d8e-11e5-9c74-a7266a2119fa.jpg)

**Comment by Narretz** [comment]
The image is unfortunately hardly readable. 
However, it looks like the image / its base64 representation is being parsed by angular. It's possible that `/**` is catching too much ...

However, since you are using Angular Foundation I would advice you to open an issue there, because I don't know what happens in their directives (interchange).

**Comment by Geoide** [comment]
It's very odd (no image is served in base64) I have some other images with Foundation-interchange and all works fine except this one. 

I'll try to ask Foundation forum.

Thanks anyway. (I attach the imagen again. Just in case...)

![err](https://cloud.githubusercontent.com/assets/2845462/10795395/e31e6586-7d99-11e5-9fdb-b330731bfb44.jpg)

**Comment by gkalpak** [comment]
It is hard to investigate further without a reproduction. If you are still seeing this, please open a new issue providing a way to reproduct the error. Thx!
