### ISSUE TITLE
angularjs select ng-options doesn't bind to model when selected ios9

### ISSUE THREAD

**Issue by boyfunky** [angular/angular.js#13197]
Is there a bug with ng-options and ios9, 

`<label class="item item-input item-border-bottom item-select">
            <span class="input-label state-input-label">State</span>
              <select name="state"  class="form-control state-options-style" ng-options="state.name for state in states track by state.id" style=" border-top: solid 1px #ccc;" ng-model="user.state">
              </select>
          </label>`
In my android app, this code works fine and when user clicks on the drop down and select the option they want, it auto binds to the model but on ios9, it shows the dropdown list but when an option is selected, it doesn't bind to the model. it only binds to the model after going to another model. 

Does anyone know why might be causing this?

**Comment by Narretz** [comment]
Do you mean it only sets the model after you close the dropdown list?

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
