### ISSUE TITLE
angular.copy([], obj) will make obj un-clear-able

### ISSUE THREAD

**Issue by fanglijun** [angular/angular.js#13193]
```
var arr = []; // got from php like: json_encode(array())
var obj = {};
angular.copy(arr, obj);
```

after that, both `angular.copy([], obj)` and `angular.copy({}, obj)` will not clear the properties of `obj`. I know that the doc says the destination object should be same type as the source object, but there is no check on that.
It'll be good for debugging if an error would be thrown when the types dose not match.

**Comment by jbedard** [comment]
This probably changed a bit after 33c67ce785cf8be7f0c294b3942ca4a337c5759d (will be in next 1.5 release). Now the destination object will be cleared correctly, but copying to it will fail in some cases (same cases as before the change).

This could be enhanced a bit to either a) throw an error when `isArray(source) != isArray(destination)` or b) allow copying from an array into object (just like object into array works today - which is kind of weird)...
