### ISSUE TITLE
Situation when $scope only applies values when they are properties on an object

### ISSUE THREAD

**Issue by dmaison** [angular/angular.js#13191]
I feel this issue is easier and less confusing to explain in step form:
* Invoked a Semantic UI's `.modal( 'show' )` (appears that its just an extension of jQuery `.fadeIn()` )
* Modal contains a form
* Form inputs' are bound to models
* The model's value remains undefined in the controller's scope, but are defined in the view
  * Writing `{{myModel}}` to the view displays the value of the input
  * In the controller, `$scope.myModel` is undefined
  * `$scope.$apply()` does not correct the issue

**Circumstance where the issue above works**
The model's value becomes available in the controller's scope if it is the property of an object.

**Example:**
This is *not* available in the controller's scope:
`<input type="text" ng-model="myModel">`

This *is* available in the controller's scope:
`<input type="text" ng-model="myModel.property">`

**Versions**
angular 1.4.1
semantic-ui 2.1.3
jQuery 2.1.4

**Comment by frfancha** [comment]
This is a classic one.
When angular creates a property it does it on the most local $scope (and lot of directives/angular instructions creates local $scope ng-if, ...).
If however it creates myProp on existing $scope.myObj, then the $scope.myObj.myProp exists as you noticed.
Note that all this is pure normal javascript behavior and from a certain point of view has nothing to do with angular.

**Comment by dmaison** [comment]
I'm not sure I understand.

So you're saying `$scope.myObj` is only available in the local scope when in a directive, until you assign a property to it, `$scope.myObj.myProp`, and then it becomes available to the parent scope?

**Comment by Narretz** [comment]
It's because of prototypical inheritance. Here's an explanation: https://github.com/angular/angular.js/wiki/Understanding-Scopes
