### ISSUE TITLE
form.FormController.$valid is undefined in Angular 1.4.7

### ISSUE THREAD

**Issue by NSLS** [angular/angular.js#13195]
I have met a bug while developing a site using angularjs,
when I am trying to test the validity of my form from controller by calling $valid property, it is undefined.
I have logged entire form controller and $valid is actually undefined, what could be the solution?

![proof](https://cloud.githubusercontent.com/assets/8458382/10803131/6291732e-7dc9-11e5-86c9-b93841e7664c.jpg)

**Comment by jbedard** [comment]
I assume this is caused by async validators? See #11167

**Comment by NSLS** [comment]
Yes, it seems to be, but what would be the solution in this case? How can I call the validation of the entire form in my controller?

**Comment by KeyKrusher** [comment]
Can you paste in all of the code? I'm not really sure...

**Comment by KeyKrusher** [comment]
@NSLS

**Comment by NSLS** [comment]
@KeyKrusher Makes no point, because I have the code devided into many different pieces, but i can try to explain what is happening.

Because I have custom directives like ng-dropdown, I needed to connect angular form validation to the selected values. 
I only managed to make it working by adding hidden input with it's model and then calling $validate of this input field directly from dropdown on-update callback

**Comment by KeyKrusher** [comment]
@NSLS True. I wasn't looking it all the way through.

**Comment by KeyKrusher** [comment]
@NSLS You have both valid and invalid listed as undefined... But I don't think that would do anything.

**Comment by NSLS** [comment]
@KeyKrusher Yeah, in the examples with the async validation, form "decides" it's validity after few seconds, but in my case it just stays undefined

**Comment by KeyKrusher** [comment]
Could there be a error in any of the function? Such as it being redefined?

**Comment by NSLS** [comment]
@KeyKrusher Yes, thanks, mate! The problem was in my custom validation directive, which was not returning true in case, if there is no error!

**Comment by NSLS** [comment]
Issue solved
