### ISSUE TITLE
Trouble with AngularJS lifecycle.

### ISSUE THREAD

**Issue by opsigor** [angular/angular.js#13190]
I'm trying to expose some of my directive's methods to $scope, so those functions could be called from the controller. This directive is being used as a wrapper for my form directives, and it has a controller so that other directives can communicate with it. Also, this directive is the "official event emitter" for my form. The directive looks like this:

```js
function MyForm() {
    return {
        restrict: 'A',
        scope: false,
        require: 'form',
        transclude: false,
        controller: ['$scope','$element','$attrs','$timeout', function($scope, $element, $attrs, $timeout) {
            let ctrl = this;

            $scope.obj = {}
            $scope.obj.fun1 = fun1;
            $scope.obj.fun2 = fun2;
            $scope.obj.fun3 = fun3;
            $scope.obj.fun4 =fun4;


            function fun1 (par1, par2){
                // code
            }

            function fun2(){
                // code
            }

            function fun3 (par1, par2, par3, par4){
                // code
            }

            function fun4(){
                // code
            }

        }]
    }
}

``` 

And on the controller, i'm trying to acess this  `obj` and its functions like this:

```js
function MainController($scope,$timeout){
    $scope.obj.fun1('name', 'foo');
   //Cannot read property 'fun1' of undefined
}
```

i'm trying to figure it out the problem, and when i use $timeout around the function on $scope, i can call the function. How do i solve it?

**Comment by ozsay** [comment]
If you use the ngController directive on the element, It runs before your directive runs due to the priority (ngController priority is 500 and yours 0).

To make your directive run before the ng-controller directive simply add a greater priority to it than 500.

Check the $compile api for reference https://docs.angularjs.org/api/ng/service/$compile.

**Comment by opsigor** [comment]
Hello @ozsay, and thanks!

Even if i add a greater priority value at the directive, it still doesn't work because i'm not using ng-controller, i'm using ui.state. :disappointed:

**Comment by ozsay** [comment]
do you mean ui.router ? is MainController what you attach to the state ? see if https://github.com/angular-ui/ui-router/wiki#resolve can help you

**Comment by opsigor** [comment]
Yeah, sorry. I was looking for a way to just make this value available from the directive itself.

**Comment by Narretz** [comment]
This looks like a usage question. Please use one of these channels (especially important if you use third-party modules): https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question Thanks!
