### ISSUE TITLE
Worst tutorial ever?

### ISSUE THREAD

**Issue by chimerablack** [angular/angular.js#13203]
Install Node.js
If you want to run the preconfigured local web-server and the test tools then you will also need Node.js v0.10.27+.

You can download a Node.js installer for your operating system from http://nodejs.org/download/.

Check the version of Node.js that you have installed by running the following command:

node --version

WTF am I supposed to be running this command in?  You haven't mentioned it.  Run it in Node.exe? Run it in Git? run it on windows command prompt?  Run it on a treadmill? WHAT!? I've tried all four and it just gives me random errors no matter what I try.  TERRIBLE tutorial.  Can't get past the fucking install page after 8 hours of pulling my hair out.

**Comment by chimerablack** [comment]
https://docs.angularjs.org/tutorial

**Comment by lgalfaso** [comment]
I am sorry, but this language is not acceptable. On top, it looks like you are looking for support. Please do so in StackOverflow.

**Comment by chimerablack** [comment]
focused on my swear word like a 3rd grade teacher?  who THE FUCK cares what language I use.  Get off your high horse bud.

**Comment by alexandr2110pro** [comment]
Funny. That guy should try to learn at least something before start to programming. )) 
Maybe after that he will not look so stupid)

**Comment by shreyas-a** [comment]
@chimerablack you look pissed. Relax! You are complaining like you've paid for this tutorial.
