### ISSUE TITLE
Encapsulation of angular in shadow dom

### ISSUE THREAD

**Issue by yousfiSaad** [angular/angular.js#13212]
Hello,
I try to create a controller inside shadow dom, but it does not work
https://gist.github.com/yousfiSaad/0c48bca5f25c22acdb78

can someone explain the reason of that behaviour ?

**Comment by Narretz** [comment]
I'm sorry, I can't really figure out how the code works. If you don't think this is a bug, please try one of the support channels first: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
If you find this is a bug, please reopen this issue.

**Comment by yousfiSaad** [comment]
Thank you, here is the link for interested users http://stackoverflow.com/questions/33451063/encapsulation-of-angular-in-shadow-dom
the problem is that the controller is not instantiated
