### ISSUE TITLE
Failed to instantiate module when multiple apps in page (e.g., via Chrome Extension).

### ISSUE THREAD

**Issue by richburdon** [angular/angular.js#13219]
I have an angular chrome extension (content script) that gets injected into a page that already contains a different angular app (e.g., calendar.sunrise.am).

I'm using angular.bootstrap to manually run my app. But this causes the following familiar error -- I'm guessing because Angular is trying to automatically instantiate the existing ng-app directive:

    Uncaught Error: [$injector:modulerr] Failed to instantiate module App due to:
    Error: [$injector:nomod] Module 'App' is not available! You either misspelled the module name or forgot to load it. 
    If registering a module ensure that you specify the dependencies as the second argument.

My extension loads and runs fine, but I'd like to remove this error.

Is there a mechanism to suppress angular from inspecting the DOM and looking for "ng-app"?

**Comment by gkalpak** [comment]
I onced answered a similar (actually I think it's the same) question on SO: [answer][1]
It's been almost 2 years, so things might have changed a bit (but the general concept should still apply).

Wondering if @kentcdodds has some insights on this (since he's been there, done that :smiley:).

[1]: http://stackoverflow.com/questions/21048891/using-angular-in-extension-on-a-page-that-already-uses-angular/30664238#21049890

**Comment by gkalpak** [comment]
In any case, this is a general support question and as such would have been a btter fit for one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

--
Closing as this isn't actionable, but feel free to continue discussion below.
If you think you ran into a bug or want to request a feature, please open a new issue with a detailed description.



[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by kentcdodds** [comment]
[Here's the extension](https://github.com/kentcdodds/genies-lamp) if you want a working example. I think that @gkalpak's answer to my question two years ago outlines it quite nicely (thanks again @gkalpak!). Good luck!
