### ISSUE TITLE
Circular dependency injection error only on firefox

### ISSUE THREAD

**Issue by no-more** [angular/angular.js#13214]
Hello,

I've a new bug on a existing program and I'm not sure where it comes from but the error is : 
```
Circular dependency found: edTranslator <- edLogger <- edAuthenticationService <- edTranslator
```
I checked my source and I have not such dependencies (edTranslator does not require edAuthenticationService nor edLogger, edLogger does require only edTranslator and edAuthenticationService  does require both of them)

What is even stranger is that I have this issue only on firefox (41.0.2) (no error on chrome, edge or safari).

I can provide a link to a test website.

---
Angular 1.4.7

**Comment by Narretz** [comment]
Hi, yes a link to a test website or a demo in a plnkr would be very welcome.
That said, it looks like the error comes from third party modules so the error might not be in angular core at all.

**Comment by no-more** [comment]
Thanks for your fast response.

Here is the incriminated website : http://test.dufacile.appiesonline.com (it's quite long to load because it's the uncompressed version).

The error occurs on my own modules, but as it only concern Firefox I think that maybe there's something wrong elsewhere.
I don't think I would be able to reproduce it on purpose (on plnkr or not). It might be tightly related to the whole application.

Thanks.

**Comment by Narretz** [comment]
I'm seeing a different error in Firefox when the page loads ($rootScope.applicationData is undefined), none in Chrome. I suggest you look for support on one of the support channels (https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question). At the moment, it's not clear that this is a bug with angular. Please reopen this issue if you can show that it is. Thanks!

**Comment by no-more** [comment]
Thanks I will ask on the group, it's strange we don't have the same error.

**Comment by no-more** [comment]
Thanks I will ask on the group, it's strange we don't have the same error.
