### ISSUE TITLE
$http multidimensional params

### ISSUE THREAD

**Issue by vineck** [angular/angular.js#13217]
I need to send a multidimensional object as params from a get request, but when I do that, the second level of my object is encoded to json, not url pattern

Code:
```
$http({
  method: 'get',
  url: 'http://localhost/',
  params: { filters: { filterOne: 'filterValue' } }
})
```

Requested URL:
```
http://localhost/?filters=%7B%22filterOne%22:%22filterValue%22%7D
```

URL that I need to request:
```
http://localhost/?filters[filterOne]=filterValue
```

it should work like this? What I can do to get the expected result?

Tks

**Comment by gkalpak** [comment]
Angular's default paramSerializer stringifies objects as JSON. If you want to overwrite that behaviour, you can use the `paramSerializer` property of the [`$http` config object][1], e.g. specifying your own serialization function (or dependency-injected factory).

If you want to serialize the parameters in the way jQuery does (which seems likely based on your example), you can use the built-in [`httpParamSerializerJQLike`][2]:

```js
$http({
  method: 'GET',
  url: 'http://localhost/',
  params: {filters: {filterOne: 'filterValue'}},
  paramSerializer: '$httpParamSerializerJQLike'   // ...or any custom serializer
});
```

If you want to overwrite the serialization for all requests made by `$http` (and not have to do it on a per-request basis), you can specify the default serializer in [`$httpProvider.defaults.paramSerializer`][3].

--
BTW, for general support questions (such as this one), please use one of the [appropriate support channels][4].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://docs.angularjs.org/api/ng/service/$http#usage
[2]: https://docs.angularjs.org/api/ng/service/$httpParamSerializerJQLike
[3]: https://docs.angularjs.org/api/ng/provider/$httpProvider#defaults
[4]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
