### ISSUE TITLE
Q: is there a way to selectively avoid DOM processing?

### ISSUE THREAD

**Issue by mr-moon** [angular/angular.js#13229]
Say I wanna have the popup directive with ability to declare it's content within a same HTML view:
```
<a popup>
    <span>Click me</span>

    <popup-content>
        <div with-some-other-directives></div>
    </popup-content>
</a>
```
Then I'd like to use HTML code taken from within `<popup-content>`, compile that raw HTML against the scope of popup directive (decorating with some more HTML) and finally append it to BODY. That  part `popup-directive` would get removed without being compiled and processed by angular.

The goal is to prevent `with-some-other-directives` directive from execution.

Thanks.

P.S we're at 1.2.28

**Comment by Narretz** [comment]
As this is a usage question, please ask on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
