### ISSUE TITLE
Problem Angular With JQuery

### ISSUE THREAD

**Issue by thierrylaz** [angular/angular.js#13220]
Hello everyone.
Here is my problem and I do not know if it is a conflict between angular and jQuery.

if I use the script $ ("select"). selecter () to my style, all values in my "optionSelect" are empty set, and if I comment the script, I get the values.
Are you a solution to this conflict?

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
