### ISSUE TITLE
docs($compile): usage of bindToController as object is undocumented

### ISSUE THREAD

**Issue by gjungb** [angular/angular.js#13228]
Since version 1.4 it's possible to use ```bindToController``` as an object like so:

```
bindToController: {
  text: '@text',
  obj: '=obj',
  expr: '&expr'
},
scope: {}
```

This fact is not reflected in the documentation.

**Comment by Narretz** [comment]
Yeah, that's right! Would you like to submit a PR that adds the info?

**Comment by Nazanin1369** [comment]
@Narretz Putting up a PR today for this
