### ISSUE TITLE
What is about digest cycle after $timeout in angular?

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular.js#13225]
Let we have the code in the control's method executed when, for example, we push a button
````
$timeout(function() {
    $scope.names = ['A', 'B', 'C'];
}, 0, false).then(function() {
    $scope.names.push('D');
})
````
in this case we will not see any changes at the screen because the digest cycle will not be running

But if we wrote this
````
$timeout(function() {
    $scope.names = ['A', 'B', 'C'];
}, 0, false).then(function() {
    $scope.names.push('D');

    return $q.when();
})
````
we will see changes because when we return promise the $Q provider decides to run the digest cycle. http://plnkr.co/edit/DqAzPBe37Qd9CU1ug8Pp?p=preview

 This logic is not consistent. How to prevent this? How to regulate the $q provider not to run the digest cycle?

**Comment by gkalpak** [comment]
I don't think it's possible (without resorting to private APIs :wink:).
Why do you need to use `$q.when()` ? And why do you need a `$timeout` ?

**Comment by olegdunkan** [comment]
````
function getImage() {
...
    return promise;
}
function processImage() {
...
    return promise; 
}
$timeout(function() {
    return getImage();
}, 0, false).then(function(image) {
    var promise;

    if (image.inCache) {
         promise = $q.when(image); 
    } else {
        promise = processImage();
    }
    return promise;
}); 
````
p.s. 
I don't need any digest cycle in the case because it's all background stuff!

**Comment by gkalpak** [comment]
You don't need to wrap the value in a promise inside of the `thenCallback`.

Basically, `.then(callback)` will return a promise that will be resolved with either the return value of `callback` (if it's not a promise) or with the value with which the promise returned by `callback` will be resolved.
In case it doesn't make sense, here is some code:

```js
// Both promises will eventually resolve to `123`
var promise1 = somePromise.then(function () { return 123; });
var promise2 = somePromise.then(function () { $q.when(123); });
```

**Comment by olegdunkan** [comment]
@gkalpak yes, you are right, but the reason is next:
what if I have the function like this
````
function processImage(image) {
    var promise;

    if (image.inCache) {
         promise = $q.when(image); 
    } else {
        promise = processImage();
    }
    
    return promise;
}
````
and i don't know when and in what context I will use it.
For example, I can use it simply in some event handler

```` 
processImage(image).then(function() {
    console.log("Processed");
}); 
````
The same function I can use in the resolver function of promise, like in my first case.
My goal is to keep promise logic for all context of execution.

**Comment by gkalpak** [comment]
That is a different problem than the one described initially imo. Basically, it has nothing to do with `$timeout`. You rather want a promise library/helper (like `$q`) that does not hook into the `$digest` cycle.

While it doesn't sound like an unreasonable feature request, I can only imagine in what bug-inflicting ways people could abuse this.

In fact, Angular has an internal service (`$$q`), an alternative to `$q`, that does exactly that (skips the `$digest`). I guess it's been internal/private for a reason, but I could be convenced that it's a good idea to make it public.

ATM, it is definitely **not** recommended to use a private/undocumented service.
As an (ugly) workaround, you could (ab)use `$timeout`, which can utilize `$$q` internally. E.g.:

```js
function processImage(image) {
    var promise;

    if (image.inCache) {
         promise = $timeout(0, false).then(function () { return image; }); 
    } else {
        promise = rotate(image);
    }

    return promise;
}
```

**Comment by olegdunkan** [comment]
@gkalpak Thanks. I like your previous message.)

**Comment by gkalpak** [comment]
@olegdunkan, glad you liked it.

BTW, I just realized, you can save a `.then()` (not that it would make any difference): `promise = $timeout(function () { return image; }, 0, false);`

**Comment by gkalpak** [comment]
Of course, if you find yourself using it often, you could also wrap it into a factory :stuck_out_tongue: :

```js
.factory('myQWhen', function myQWhenFactory($timeout) {
  return function myQWhen(value) {
    return $timeout(function () { return value; }, 0, false);
  }
})
