### ISSUE TITLE
Multiple select boxes (size > 1) freezes under asynchronous conditions in IE11

### ISSUE THREAD

**Issue by jonlarsson** [angular/angular.js#13239]
We're having issues with select boxes, where selection in one box leads to an asynchronus load of options for the next select box. In IE11 the select boxes will freeze until somthing as simple as setting visibility to hidden and back again.

I have reproduced this in this plunker: http://plnkr.co/edit/NGwG1LUVk3ctGOsX15KI?p=preview
If you fiddle around with the topmost select, the second and third select will often freeze. One interesting thing is that if you open the plunker in its own window, the freezing will not happen. I have tested this with 1.4.7 and 1.5.0-beta-1.

This seems like similar problem to  #11314 and #11795 one thing being different is the async behaviour.

**Comment by Narretz** [comment]
Oh, it's this bug again. This is seriously one of the most ridiculous bugs I've ever seen. I assume I can count myself lucky that I never had to support IE6-7.

**Comment by rockyrfernandes** [comment]
http://plnkr.co/edit/UZGWX9?p=preview
I have similar code & the issue is also reproducible in chrome & IE10

**Comment by jonlarsson** [comment]
@rockyrfernandes are there any specific steps to produce the bug i your plunker? I'm just clicking around and can't seem to get the selectbox freeze, neither in chrome nor in IE11.

**Comment by bkirtika** [comment]
same issue. n in angular v1.3 17.
