### ISSUE TITLE
Ordering string which are case sensitive

### ISSUE THREAD

**Issue by Nihn** [angular/angular.js#13238]
Hi,

when I want to sort some strings with respected lower and upper case I'm forced to use my own function. Is there any way to use `orderBy` in this case?

https://github.com/angular/angular.js/blob/v1.5.0-beta.1/src/ng/filter/orderBy.js#L275

**Comment by Narretz** [comment]
No, there's currently no way to do this. Here's a PR which was met with some reservations: #8112.
