### ISSUE TITLE
Add information about time separator in $locale

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#13232]
We have a feature request in UI Bootstrap for custom time separators for hours and minutes depending on the locale - the best solution I can find is for us to use the locale as defined in $locale, but this particular information is not separated.

This is a feature request to add a key under the `DATETIME_FORMATS` object maybe with key `TIMESEPARATOR` or something similar with value as the time separator character. For English this would be `:`, and for Finnish this would be `.` for example.

**Comment by lgalfaso** [comment]
Hi, the CLRD has a key called `timeSeparator` that represents exactly what you are looking for. The main issues are:
* Google closure library does not propagate this property into their files
* Going strait to the CLRD would involve a substantial amount of work

**Comment by wesleycho** [comment]
Understood - could close this issue then, and I can reject the request we have gotten in UI Bootstrap then given this situation.
