### ISSUE TITLE
[bug] ng-repeat + ng-model + input[type=email] 

### ISSUE THREAD

**Issue by leitasat** [angular/angular.js#13237]
Hello!

Have just found a very weird bug: if I use input of `type="email"` instead of `type="text"` inside `ng-repeat`, binding becomes broken. Check out the fiddle http://jsfiddle.net/3L143sn6/ (slightly modified version of this http://jsfiddle.net/jaimem/rnw3u/5/ by jaime from here http://stackoverflow.com/a/13715352/1151950 )

Tried on both 1.2.1 at jsFiddle and 1.4.7 in my project.

Thanks.

**Comment by Narretz** [comment]
type="email" will not update the model if the input is not an email. If you enter an email, it will update. Since 1.3, you can also use ngModelOptions.allowInvalid to set invalid values on the model.
