### ISSUE TITLE
Controller aliases conflict with inherited scopes

### ISSUE THREAD

**Issue by SamGraber** [angular/angular.js#13240]
I recently ran into an issue when using inherited scopes with controllerAs and bindToController. The situation is as follows:
The parent and child directives use the same controller alias (controllerAs: 'controller')
The child directive binds an action from the parent using an event binding. (bindToController: { action: '&' })
The child directive uses an inherited scope. (scope: true) This is important because the binding appears to work correctly with an isolate scope.
The parent directive binds a method from its controller to the child action. (action="controller.parentAction()")
When the child triggers a call to the action, the angular compiler incorrectly picks up the controller of the child directive instead of the parent, thus leading to a noop or an incorrect function call.

Plunkr: http://plnkr.co/edit/JRCoRIsDV3UpS6D2ELKa?p=preview

**Angular Version**: 1.4.5

I don't know exactly where the issue originates, but I do know the following line is hit with the child scope when the child tries to trigger the action: https://github.com/angular/angular.js/blob/96288d02d316ff1508b2e0673f34291f9abd1c7f/src/ng/compile.js#L2765

**Comment by gkalpak** [comment]
I believe this is a duplicate of #13021 (and will (hopefully) be addressed with #13025).

**Comment by SamGraber** [comment]
Yes, looks like the same issue. Thanks!
