### ISSUE TITLE
Native autocomplete doesn't work inside of ngRepeat in IE9 and IE10

### ISSUE THREAD

**Issue by ikhmilevskiy** [angular/angular.js#13249]
Native browser autocomplete in IE9/10 work perfectly for input[name="test"] but for some reason it doesn't work for inputs generated with ngRepeat directive. Is there any solution for this issue?
```
<form>
   <input name="test">
   <input name="test-{{i}}" ng-repeat="i in [1,2]">
</form>
```

Demo: http://plnkr.co/edit/9GDPmo
This issue is not reproducible in IE11 and other browsers.

P.S. I'm using angular v1.2.27.

**Comment by Narretz** [comment]
Hi, can you please test two things for me:
1. Does it happen with angular 1.4.7? (1.2.28 doesn't receive patches anymore).
2. Does it happen if you only have `<input name="test-{{'1'}}">`, so without ngRepeat.

I suspect it's a problem with the interpolation, but I don't have an IE9/10 to test

**Comment by pkozlowski-opensource** [comment]
From what I remember IE9 can't change input names, so yes `name="test-{{i}}"` won't do much good. `attr-name` would probably work, though.

**Comment by ikhmilevskiy** [comment]
1. Doesn't work with 1.4.x
2. Works with static name
3. !!! Works with dynamic name but without ng-repeat 

other ideas?

**Comment by tarasok** [comment]
guys, do you have any updates? I have the same issue.

**Comment by Narretz** [comment]
Have you tried with `ng-attr-name="test-{{i}}"`?

I find it weird that ng-repeat makes a difference here.

**Comment by gkalpak** [comment]
I couldn't reproduce this on IE9 / Windows 10 (using [this plnkr][1]). Autocomplete worked on every field.
I tried with `v1.5.6`, `v1.4.0` and `v1.2.27`. (Note that in your plnkr, there is no `ngApp`, so Angular never takes over.)

I'm closing this, since there is no reproduction. 

[1]: http://plnkr.co/edit/#!/6AckBPIE0O9HdFOpRtFn?p=preview
