### ISSUE TITLE
ng-selected in ng 1.4.7 doesn't respond

### ISSUE THREAD

**Issue by csthsl** [angular/angular.js#13242]
I'm using ng-selected like this:

```
<select class="form-control" ng-model="vm.newChannel" ng-change="vm.changeLanguage(vm.satelliteData.serialNumber, vm.newChannel)">
     <option value="{{a}}" ng-selected="a.channelId == vm.channelId" ng-repeat="a in vm.languages">{{a.languagePair}}</option>
</select>
```

This code worked in 1.4.5. I updated my NG lib to 1.4.7 and it stopped working. I tried to look up the docs to see if the implementation changed but it doesn't appear it did.

**Comment by Narretz** [comment]
We fixed a bug in the `option` directive; it's possible that your code broke because of that fix. That said, you shouldn't use ngSelected together with option when the select has an ngModel, as the selectController will then select the correct option for you.

Can you put a demo in a plnkr.co or similar? I see you are assigning an object to the value attribute. This is also not recommended.

**Comment by csthsl** [comment]
Thank you for replying so quickly. I'm not using the option directive. I am using ng-change directive though. Perhaps that may be conflicting?
Also, I have found a need for placing the object in the value which in all our testing appears to work like like a champ. I'll revisit it though.

**Comment by Narretz** [comment]
You are implicitly using the option directive via the option element. It registers the option on the select element.

**Comment by csthsl** [comment]
If the option directive is implicitly used by virtue of using the option element and it doesn't play nice with ng-selected, under what scenario is ng-selected appropriate?

**Comment by Narretz** [comment]
The way I see it, ng-selected is only appropriate if you use a select element without ngModel. Only the combination of the latter two will bring the option directive into play.

**Comment by csthsl** [comment]
Yes indeed. You are correct. No ng-model on the select element. So that begs the question, how would you bind to the selected value without using ng-model?

**Comment by csthsl** [comment]
It looks like if I want to bind, I need to use ng-options.

**Comment by csthsl** [comment]
Thank you Narretz! I appreciate you taking the time to help me understand it. I changed my code all around to use ng-options as you suggested.

**Comment by Narretz** [comment]
Glad you got it working!
