### ISSUE TITLE
ng-animate skips animation "under pressure" 2

### ISSUE THREAD

**Issue by bmmpt** [angular/angular.js#13241]
I have a similar issue to the one reported here https://github.com/angular/angular.js/issues/12359. Before I decided to post my problem I tried the plunker pointed out as a fix to 12359: http://plnkr.co/edit/P7E5CXnuMQDpH1SiJ0pj?p=preview

It appears to me that the issue is still there when you repeatedly press the buttons randomly.

I believe my scenario is simpler and illustrates a similar problem:

http://plnkr.co/edit/YzxCThylPk4AfX0cvcfG

If you click the button to hide the label and wait for the animation to finish and then click it to show the label and wait until it finishes, all goes well. But when the animation is half way down and you click the button I would expect the label to go back up, and apparently it's happening but if you continue clicking the button, you will notice it "jumps" rather than "sliding".

Thanks in advance.

**Comment by Narretz** [comment]
Interesting. I can only see this happen in Chrome, not in Firefox. Which browsers have you tested?

**Comment by Narretz** [comment]
I have tested again with the latest snapshot, and I cannot reproduce the problem anymore (animate was on 1.4.3 in your plnkr).

**Comment by bmmpt** [comment]
I tested in Chrome and IE.

**Comment by Narretz** [comment]
Can you please test again with the latest version: https://code.angularjs.org/snapshot/angular.js

**Comment by bmmpt** [comment]
This is the angular.js API, not angular-animate.js, right?

**Comment by Narretz** [comment]
True, but I meant angular-animate. :) You can get the latest snapshot 
for angular-animate the same way, simply replace angular.js with 
angular-animate.js

Am 03.11.2015 um 19:47 schrieb Bruno Mendonca:

**Comment by bmmpt** [comment]
btw, IE seems to be working though. I will replace angular-animate.js and give it a try.

**Comment by bmmpt** [comment]
Thanks, Chrome is working like a charm! Any ideas when this will be released?

**Comment by Narretz** [comment]
Okay, so is this issue resolved then?

**Comment by bmmpt** [comment]
Yes, thank you for your help.
