### ISSUE TITLE
ng-options and track by id (selected option always empty)

### ISSUE THREAD

**Issue by Luddinus** [angular/angular.js#13259]
http://jsfiddle.net/Lgevdx1m/

**Comment by Narretz** [comment]
You have to be careful when using select as ... and track by, please read the docs: https://docs.angularjs.org/api/ng/directive/ngOptions#-select-as-

**Comment by Luddinus** [comment]
Read, but doesn't make sense to me.

**Comment by Narretz** [comment]
ngOptions doesn't convert types. I think you should be able to use a parser on ngModelController for that.

**Comment by Luddinus** [comment]
parser in ngModelController? I don't understand that.

**Comment by Narretz** [comment]
Sorry, this is not a support forum. Please ask again on Stackoverflow, the
Google groups or the IRC
