### ISSUE TITLE
ng-Model update based on time and not on value change,

### ISSUE THREAD

**Issue by ryager01** [angular/angular.js#13258]
The ng-Model updates the values of the elements on a tick.
The tick should check to see if the value has changed and if so THEN update the element to the new value. I know this is a little anal, but when you have a recursive directive based on an ng-model element , not having this can create a lot of overhead.

**Comment by Narretz** [comment]
Can you please show an example? I don't even know if you're saying there's a problem with ngModel itself or with functionality you have build upon it.

**Comment by Narretz** [comment]
Closing due to lack of feedback.
