### ISSUE TITLE
Does any version of Angular Js supports Firefox 1.7.13?

### ISSUE THREAD

**Issue by jimuliautsav** [angular/angular.js#13255]
I have developed application in Angular Js 1.3.16 and it is working fine with latest version of chrome and Firefox.

But now i need to run this application in Firefox 1.7.35 in some old system and it does not work.

Is this a known issue or is there any workaround?

**Comment by pkozlowski-opensource** [comment]
Sorry, there is no Angular version that would support such an old version of FFox. Currently we are using Firefox 39.0.0 in our unit tests.

I'm afraid that there is no work-around here.

**Comment by jimuliautsav** [comment]
Thanks powel,

Do you know which is the lowest version of Firefox, angular js supports ?
