### ISSUE TITLE
ngModel not updating with input type="search" clear button in IE

### ISSUE THREAD

**Issue by aderowbotham** [angular/angular.js#13256]
When using an `input type="search"` field with AngularJS 1.4.7 in IE 9, 10 or 11: When you click the search clear / cancel button rendered inside the field (after entering text) in Internet Explorer the model value does not reset to `''` or `undefined`.

Example HTML:

    <input ng-model="searchVal" type="search">
    <p>searchVal = {{ searchVal }}</p>

http://plnkr.co/edit/zE2qMMfaJK11KYfUWZzr?p=preview

Model updates as expected in Chrome and Safari.

**Comment by Narretz** [comment]
This is the same issue as https://github.com/angular/angular.js/issues/11193
