### ISSUE TITLE
Accesing the ng-model value in a template was called in templateUrl was inside template of element directive

### ISSUE THREAD

**Issue by praveen1228** [angular/angular.js#13268]
>" Here i have a directive inside having a template, in the template i was using a templateUrl for rendering the another template into directive, Whats My issue is
--> i Want access the form data inside the template which is called by templateUrl",

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
