### ISSUE TITLE
Google logo in the homepage is old

### ISSUE THREAD

**Issue by vpanjganj** [angular/angular.js#13260]

**Comment by gkalpak** [comment]
What page are you referring to ? https://angularjs.org/
Where is the logo ?

**Comment by vpanjganj** [comment]
Hi,
https://angularjs.org/img/AngularJS-large.png

**Comment by gkalpak** [comment]
I don't think it's a Google logo (afaik the logo never looked like that).
(But even if it were, this issue would belong to https://github.com/angular/angularjs.org :wink:)

**Comment by Narretz** [comment]
@gkalpak The colors look off, but I think that's definitely a Google logo - I opened an issue in the org repo: https://github.com/angular/angularjs.org/issues/186
