### ISSUE TITLE
HTML entities are been decoded during parsing when text is bound to directive's scope

### ISSUE THREAD

**Issue by olostan** [angular/angular.js#13269]
Having HTML like
```
<test 
    	   a="{field:'There shoould not be apostropth &apos; here'}">
</test>
```
When in directive `test` I declare scope's field to be bound to attribute `a`, html entities that are in initial value are been decoded, making two-way binding not possible.

Directive code:
```
app.directive('test', function() {
  return {
    scope:{a:'='},
    link: function(scope)  {
      console.log(s.a);
    }
  }
})
```

Plunker for testing: http://plnkr.co/edit/qPnzO0pYQIQmKNj37sj6?p=preview

**Comment by lgalfaso** [comment]
This is a dup of #13270
