### ISSUE TITLE
build 1.5.0-build.4376+sha.aff74ec and batarang

### ISSUE THREAD

**Issue by SanderElias** [angular/angular.js#13275]
If you use the .component helper form this build, and you have batarang active, the following error will be thrown.

`script.js:8 Uncaught TypeError: angular.module(...).component is not a function`

Took me some time to figure out what was happening... 
Disable batarang, and your component(s) start working!

**Comment by Narretz** [comment]
Interesting. I think you should cross-post this to angular/batarang

**Comment by SanderElias** [comment]
@Narretz, good idea. Done!

**Comment by petebacondarwin** [comment]
Fixed by https://github.com/angular/batarang/pull/284

**Comment by gkalpak** [comment]
Fixed in https://github.com/angular/batarang/commit/21f3e6cad5a939fed252f259213c26c799a17f04.
