### ISSUE TITLE
Multiple ngMessagesInclude elements only the first works

### ISSUE THREAD

**Issue by gligoran** [angular/angular.js#13276]
I'd like to use multiple ```ngMessagesInclude``` directives in a single ```ngMessages``` directive, but it doesn't work. I'm not sure if this is a bug, but I'll assume it's by design.

This feature would allow me to separate my messages into multiple files and then include the ones that apply to a certain field. An example like this would be a template for ```required``` message, which would go on every field that must be filled in. For password fields there would be a set of messages that only apply those fields.

Template examples:
```html
<script type="text/ng-template" id="requiredMessage">
    <ng-message when="required">This field is required.</ng-message>
</script>

<script type="text/ng-template" id="passwordMessages">
    <ng-message when="compareTo">Passwords do not mach.</ng-message>
    <ng-message when="minlength, maxlength">Password must be between 8 and 100 characters long.</ng-message>
</script>
```

Usage:
```html
<ng-messages for="myForm.myField.$error" multiple role="alert">
    <ng-messages-include src="requiredMessage" />
    <ng-messages-include src="passwordMessages" />
</ng-messages>
```

The key value of this would be that the actual string would not be repeated through the code, leading to better maintainability and easier changes to the messages.

**Comment by Narretz** [comment]
I think you are missing the `ng-messages-multiple` attribute on the `ng-messages  element.

**Comment by gligoran** [comment]
@Narretz I'm not, although I did forget to add it here. (Fixed it now.) I've got it in my actual code.

The problem isn't that ```ngMessages``` is displaying just one message, but that the ones that are not from the first ```ngMessagesInclude``` directive are not displayed at all. In my example message for ```minlength``` or ```maxlength``` are not displayed, even though other things that are triggered by ```myForm.myField.$error.minlength``` or ```myForm.myField.$error.maxlength``` work as they should. If I flip the order of includes, so that ```passwordMessages``` are first and ```requiredMessage``` is second, then ```minlength``` and ```maxlength``` work, but ```required``` doesn't.

**Comment by Narretz** [comment]
Can you please post a demo in a plnkr.co or similar?

**Comment by gligoran** [comment]
[Here you go.](http://plnkr.co/edit/MggQFQzkRxjQwkMRvkGz?p=preview)

**Comment by Narretz** [comment]
Oh, I see. If you use the element form of `ng-messages-include`, you need to close the tag. They are not self-closing: `<ng-messages-include src="emailMessages"></ng-messages-include>`

**Comment by gligoran** [comment]
Oh, now that works. Thanks.

BTW: Is this an Angular thing? I was under the impression that from HTML perspective these are equivalent.

**Comment by Narretz** [comment]
There are only very few HTML elements that are self-closing. And afaik you cannot add your own self-closing elements, so Angular only supports custom elements with end-tag. What happened in your case is that the browser parsed the second include as a child of the first, and when it saw the ng-messages closing tag, it added an implicit closing tag for the first include. Because angular replaces the ngMessagesInclude element, the second include was lost.
So no, they are not equivalent, but in some cases it might work anyway.

**Comment by gligoran** [comment]
I did a bit of searching and it turns out I thought HTML5 was more like XHTML, where every element could be self-closing. It turns out that's wrong. There's actually no self-closing in HTML5 (except for [foreign elements](http://www.w3.org/html/wg/drafts/html/master/single-page.html#foreign-elements): MathML, SVG, ...). The slash in ```/>``` is just synthetic sugar for [void elements](http://www.w3.org/html/wg/drafts/html/master/single-page.html#void-elements) and is not needed for HTML to be valid.

Anyway, thanks for the in-depth explanation. I also see now why it worked when there was only one ```include```.
