### ISSUE TITLE
1.5.0-build.4376 components??

### ISSUE THREAD

**Issue by SanderElias** [angular/angular.js#13274]
Am I missing something obvious? The component just will not render?

```javascript
   function myTest() {
       return {
           controller: function () {this.name = 'my test component'},
           template: "<div>Hello Component {{myTest.name}}</div>",
           //transclude:false
       };
   }
   
   angular.module('myPlunk',[])
      .component('myTest', myTest)
```

see it [in action(plunk)](http://plnkr.co/edit/Utlz7X7UnYbKUwlDeWtH?p=preview)

**Comment by SanderElias** [comment]
Ok, that was a stupid oversight :-D
This would have worked:

```javascript
.component('myTest', myTest())
```

The component expects an object, not a function. Its a bit different from a directive there!

**Comment by Narretz** [comment]
directive has the same signature. :)

**Comment by SanderElias** [comment]
According to the docs:

`directive(name, directiveFactory);`

a directive accepts a factory, a component accepts a object. Allomst the same ;)

**Comment by Narretz** [comment]
Oh yes, now I see it. You are right .
