### ISSUE TITLE
PhonecatApp tutorial doesn't work

### ISSUE THREAD

**Issue by R1sus** [angular/angular.js#13278]
I did everything step by step, but angular doesnt work. I think something wrong with bower. Maybe someone can help me, please? In browser i see Nothing here {{'yet' + '!'}}

**Comment by Pablo-Ivan** [comment]
Perhaps you didn't include the 'ng-app' directive or maybe you didn't write the:
"script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js></script>"

**Comment by Narretz** [comment]
There's not enough information to say what's wrong. But the result indicates that angular hasn't loaded properly, so either the files aren't included or an angular module wasn't loaded.

That said, please use one of these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
