### ISSUE TITLE
ng-disabled not working with controller as synthax

### ISSUE THREAD

**Issue by boriscy** [angular/angular.js#13288]
Please check
http://plnkr.co/edit/4f6sOudHNMQ8mMKaKHWt?p=preview
No stack trace
Angular 1.4.7

**Comment by pkozlowski-opensource** [comment]
You've got typos in your plunker: `main.form.edit` vs. `main.form.endis`

**Comment by boriscy** [comment]
Sorry for that one, but I have the same problem in a project, thanks for your help.
