### ISSUE TITLE
Document Display Data Page bug

### ISSUE THREAD

**Issue by gupei515** [angular/angular.js#13285]
At document https://angular.io/docs/ts/latest/guide/displaying-data.html:
After import hero.ts files into the app.ts, we should update the template myHero to myHero.name
template: `
  <h1>{{title}}</h1>
  <h2>My favorite hero is: {{myHero}}</h2>
  <p>Heroes:</p>
  <ul>
    <li *ng-for="#hero of heroes">
      {{ hero.name }}
    </li>
  </ul>
`,
because the definition of myHero is myHero = this.heroes[0]; instead of this.heroes[0].name

**Comment by wesleycho** [comment]
This should be posted in https://github.com/angular/angular/issues, not here.

**Comment by Narretz** [comment]
@wesleycho is right, please open a new issue in the repo.
