### ISSUE TITLE
Extending select directive

### ISSUE THREAD

**Issue by rand0m86** [angular/angular.js#13283]
I want to write directive that will check for available options in the scope and preselect some option if only one item present inside ngOptions.

For now I wrote something like this:

```html
<select id="provider" name="provider" class="form-control"
        ng-model="foo.provider"
        ng-options="provider.name for provider in providers track by provider.id"
        select-first-if-only-one="providers"
        required>
    <option value="">- Select -</option>
</select>
```

and my directive:

```javascript
'use strict';

angular.module('app')
    .directive('selectFirstIfOnlyOne', function() {
        return {
            restrict: 'A',
            require: 'select',
            link: function(scope, elem, attrs, ctrl) {
                scope.$watchCollection(attrs.selectFirstIfOnlyOne, function(values) {
                    if (angular.isDefined(values) && values.length === 1) {
                        scope.$evalAsync(function() {
                            ctrl.ngModelCtrl.$setViewValue(values[0]);
                        });
                    }
                });
            }
        };
    });
```

And it works. But I want not to pass array values to directive directly but to take them from ngModel or ngOptions.

I found that [`SelectController`][1] doesn't provide methods to get all values from `<select>`, same for [`NgModelController`][2].

Same question on [StackOverflow][3].

[1]: https://github.com/angular/angular.js/blob/aff74ec87bd31933565b76cd0ab0b988cd9bae21/src/ng/directive/select.js#L22
[2]: https://docs.angularjs.org/api/ng/type/ngModel.NgModelController
[3]: http://stackoverflow.com/questions/33614435/angular-directive-to-preselect-select-value-if-only-one-option-exists-in-ngopt

**Comment by Narretz** [comment]
You should set the scope, not the select. Programatic change should always be driven from the scope. I'd say http://stackoverflow.com/a/33618387/787333 is the way to go.

**Comment by rand0m86** [comment]
It's not the way for me. I need use this logic in lots of places so I'd rather have one directive than lots of controllers with duplicates.

**Comment by Narretz** [comment]
I don't see why you'd have lots of controllers and duplicates. The logic of setting on the scope from a directive would be the same in all places.

**Comment by rand0m86** [comment]
If I'll do your way then for every `<select>` where I need this behavior (majority of selects in my app) I will write in controllers smth like:

```js
promise.then(function(items) {
  $scope.items = items;
  $scope.selectedItem = (items.length === 1 ? items[0] : null);
}
```

This is ugly

**Comment by Narretz** [comment]
I still don't see why you can't just assign the scope value in our directive, similar to the example directive you posted.

**Comment by rand0m86** [comment]
Are you are talking about something like this?

```js
ngModel.$setViewValue(items[0]);
```

because I can't hardcode scope variable names inside directive.

If so then I still have my question - how can I get array of items inside custom directive *extending angular's `select` directive* without passing reference to it explicitly? I think it's already duplication of code - why should one try to get values from **outside** of custom directive if it is already bound to `<select>` that knows which values contained **inside** of it.

Also I've written a hack inside of `scope.$watchCollection`:

```js
scope.$evalAsync(function() { ... })
```

to be sure that all items were already rendered on the DOM. This is because I can't extend ngOptions which is terminal so I need to write my own bicycle.


In a perfect world I would rather write directive like this:

```js
angular.module('app')
    .directive('selectFirstIfOnlyOne', function() {
        return {
            require: ['ngModel', 'ngOptions'],
            link: function(scope, elem, attrs, ctrls) {
                scope.$watch(ctrls[1].options, function(values)) {
                    if (angular.isDefined(values) && values.length === 1) {
                        ctrls[0].$setViewValue(values[0]);
                    }
                });
            }
        };
    });
```

**Comment by Narretz** [comment]
Oh, I was focusing on a different aspect of your directive (that you shouldn't use setViewValue). I see how exposing the options could be useful in that case. There's another issue where that has been proposed.https://github.com/angular/angular.js/issues/7417 If you want to open a PR which implements this change, I'll be happy to look at it,
