### ISSUE TITLE
link selection doesn't work on IOS safari

### ISSUE THREAD

**Issue by xavierva** [angular/angular.js#13287]
let me explain, when a long click on a link i expect this to happen :
![screenshot_11_10_15__11_17_am](https://cloud.githubusercontent.com/assets/3062366/11059945/4344f7d8-879d-11e5-9b4d-99253934e3a8.png)

I'm doing `<a  ng-href="{{url}}">{{url}}</a>` on Firefox+Chrome android and it work perfectly. But on iOS safari the link is not recognize.

Is it an issue, or am I doing it wrong ?

**Comment by Narretz** [comment]
What does your link html look like?

**Comment by xavierva** [comment]
Hi, sorry my code was missformated I updated my post.

And here is a sample of html link : http://mydomain.com/5cMx5sw6TdeNwsQfr/organizer
or http://sub.mydomain.com/5cMx5sw6TdeNwsQfr/organizer

**Comment by Narretz** [comment]
Can you try with adding an empty `src=""` attribute? And do you have ngTouch enabled by any chance?

**Comment by xavierva** [comment]
I just tried adding `src=""`but with now result. Yes I have ngTouch enabled.

**Comment by Narretz** [comment]
Can you try without ngTouch? It's unfortunately very buggy.

**Comment by xavierva** [comment]
Done, unfortunately same result.

may be i should specify that I am using angular with Meteor 1.2.1

**Comment by Narretz** [comment]
Can you try and see if the problem appears in an angular-only app, too? Basically, the most simple demo possible. And which angular version do you use?

**Comment by xavierva** [comment]
I just tried it in a Plunker : http://plnkr.co/edit/NHVcoDGdyGdmro96rV6V?p=preview

And it works.

**Comment by Narretz** [comment]
Interesting. So the long touch / click works in the simple example? Then you'll have to find out which part of your app modifies the click behavior. I'd say it doesn't look like a bug in angular core.

**Comment by Narretz** [comment]
Closing due to lack of feedback.
