### ISSUE TITLE
custom resource action returns a promise from a promise

### ISSUE THREAD

**Issue by Nosthertus** [angular/angular.js#13296]
i am trying to get the response from the server which returns something like` true, false`, or something else, depending on the request i do, the application i am developing is using a `Restful` server i created, and just for testing purposes i made it return true or false, later i will make it return proper `json` data.

here i am trying to get the response from this code (i am not sure how to use promises yet)
```javascript
app.service('UserService', ['$resource', function($resource){
    var self = this;

    self.login = function(credentials){
        var handler = $resource('server/web/user/access', null, {
            access: {
                method: 'POST'
            }
        });

        handler.access(credentials).$promise.then(function(data){
            console.log(data);
        });
    }
}]);
```
for now i am just logging what it seems to return from the server, but the log shows another `promise`. for now i just need to get the data so i can make the conditions, parse objects, or show data it returns from the `Restful` server

**Comment by gkalpak** [comment]
`$resource` won't help you much with non-restful datasources (and atm your datasource i not restful).
You might be better off using `$http` or make your datasource actually restful.

in any case, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
