### ISSUE TITLE
ng-pristine remains on form after interaction

### ISSUE THREAD

**Issue by danwellman** [angular/angular.js#13294]
Using Angular 1.4.7, when a page with a form on it loads, both the form and input fields within the form have the `ng-pristine` class on them.

After tabbing into and away from the first input, this input loses the `ng-pristine` class and gains the `ng-touched` class, but the form element retains the `ng-pristine` class and does not gain `ng-touched`.

Surely the class names on the form and its inputs should remain in sync?

**Comment by Narretz** [comment]
I can't reproduce this: http://plnkr.co/edit/1HjZ8YeiBU9Uxgp48zLu?p=preview

The input get `$touched = true`, which the form doesn't have.

**Comment by danwellman** [comment]
Sorry, I'm talking about the CSS class names that get applied to the form fields. In your Plunk, if you open up the DOM explorer in your browser and inspect the form, you will see that the input gets the class `ng-touched` after tabbing into and out of the field, but the outer `<form>` element does not

**Comment by Narretz** [comment]
That's right, $touched is not propagated to the parent form, and that's why ng-touched isn't set on the form. It has nothing to do with ng-pristine, though.
This issue is already tracked here: https://github.com/angular/angular.js/issues/10813

**Comment by danwellman** [comment]
I checked the linked issue and I didn't see any reference to the class names that appear on either the form or the form fields.

I'm sorry, but regardless of the technical implementation, I don't see how the form can be pristine if any of the fields have been touched. It's making styling things, like a label, based on the state of form impossible using pure CSS.

I really feel that this is a genuine issue that the form retains the `ng-pristine` class when it is clearly no longer pristine. It's unintuitive and feels like a bug.

**Comment by Narretz** [comment]
Like I said, I cannot reproduce what you wrote in your first post. In the plnkr I linked, `ng-pristine` is not removed in either the input or the form when simply tabbing through the input. Pristine is changed to dirty when something is entered in the input (tabbing doesn't count), and this also changed the classes. This is intended behavior.
Untouched is changed to touched when you tab out of an input. This is currently not propagated to the parent form, and this is tracked in the other issue.

**Comment by danwellman** [comment]
Many apologies, you're right, the `ng-pristine` class does not change on the form *or* the input after only tabbing.
