### ISSUE TITLE
Strange behaviour with ng-model binding to checkbox

### ISSUE THREAD

**Issue by jamesla** [angular/angular.js#13305]
I'm trying to intercept a checkbox change so I can put a confirmation stage in the middle and I am experiencing strange behaviour. When I intercept the event the model is getting out of sync with the element. However this only happens once and then it works as expected.

I've made a simple example here which illustrates what I mean - https://jsfiddle.net/tcVhN/197/

Would anybody be able to explain to me why this is happening and potentially advise me on how I could get around it?

**Comment by frfancha** [comment]
I don't know if you have any doc saying that ng-click will "run" before ng-model, therefore, to do what you want, I would use a watcher on x.checked to ask for confirmation (resetting x.checked if the user doesn't confirm) instead of ng-click with prevent default.
Then you won't have any problem.

**Comment by Narretz** [comment]
This works as expected, but isn't quite transparent.
The `input` directive registers its own click handler for checkboxes. It's registered in the preLink fn, which means it runs before ngClick.
Another problem with your code is that you don't stop the event propagation, which means even if your click handler ran before input's, the model would still be updated. You can use this directive as a starting point:

        priority: 2,
        link: {
          pre: function($scope, el) {
            el.on('click', function($event) {
              $event.preventDefault();
              $event.stopImmediatePropagation();
            });
          }
