### ISSUE TITLE
ngRoute failing to load template very quick , wait 10 seconds , retries and succeeds?

### ISSUE THREAD

**Issue by bechampion** [angular/angular.js#13301]
Hi Guys ,I'm noticing something stramge

I'm using ngroute to do something like:
```
                              }).when('/domSearch/:domRegex', {
                                    templateUrl: 'templates/domSearch.html',
                                   controller: 'domController',
```

But when i do a GET to get the template it fails extremely quick ,  and waits for 10 seconds and then succeeds... any ideas?

1st attempt:
![image](https://cloud.githubusercontent.com/assets/4983875/11149862/cc260516-8a1c-11e5-90ab-2273ca3698e5.png)
             
2nd attempt:
![image](https://cloud.githubusercontent.com/assets/4983875/11149882/df4814b8-8a1c-11e5-9b53-c722ebcec2f0.png)

more logging:
![image](https://cloud.githubusercontent.com/assets/4983875/11150074/e1e7e5f8-8a1d-11e5-8388-1b230522e31b.png)

**Comment by Narretz** [comment]
Hard to say where the problem is without a demo. I'd say it's more likely that the network is responsible and not angular.

**Comment by Narretz** [comment]
If you can create a demo that reproduces the error on more than one machine, we can see if it is a bug, otherwise you should ask on one of the support channels. https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by bechampion** [comment]
we can close this ,  i found "window.location.reload();"  after a window.location ...my god...Thanks!
