### ISSUE TITLE
Wrong plurals in Spanish

### ISSUE THREAD

**Issue by gtrabanco** [angular/angular.js#13303]
The plurals are not translated and they should be:

var PLURAL_CATEGORY = {ZERO: "cero", ONE: "uno", TWO: "dos", FEW: "pocos/as", MANY: "muchos/as", OTHER: "otro/a"};

**Comment by lgalfaso** [comment]
Plural categories is a CLDR mechanism to classify nouns morphisms according to their number, and not words translations. http://cldr.unicode.org/index/cldr-spec/plural-rules

**Comment by gtrabanco** [comment]
So the translations of the plurals must be a self-done stuff, right?
