### ISSUE TITLE
elements in ng-repeat doesn't apply css style of classes

### ISSUE THREAD

**Issue by feniixx** [angular/angular.js#13304]
When i have my elements in ng-repeat like:

```javascript
<div class="dashboard-options row panel">

        <a ui-sref="{{ option.route }}" ng-repeat="option in vm.dashboard_options">
            <div class="col-md-4 text-center dashboard-option button-effect">

                <img src="{{ option.icon }}">

                <p>{{ option.option_text }}</p>

            </div>
        </a>

    </div>
```

There's a `text-center` class that is not centering the elements, but if i create the html by hand it works, is there something that ng-repeat does?

**Comment by gkalpak** [comment]
`ngRepeat` doesn't do anything that would affect styling (afaik). It sounds more like a browser quirk (or a bug in your code).

Is this reproducible on several browsers ?
Could you create a minimal reproduction (e.g. using CodePen, Plnkr etc) ?

**Comment by feniixx** [comment]
I have to say that it problem with error with bootstrap and flexbox.
