### ISSUE TITLE
input [type=number] does not update ng-model when valid numbers (1e10) or letters are input.

### ISSUE THREAD

**Issue by DeanMW** [angular/angular.js#13300]
I have managed to find a reproducible bug where inputs with type=number do not update the model when a valid number such as 1e10 is input. Similarly in firefox, where input type=number are not restricted to just the character 'e' and numbers, when a user enters any characters the model does not update. 

See this plunkr to view the reproducible bug: http://plnkr.co/edit/qiNXYPUj7w1VQDOKH5oR?p=preview

**Comment by gkalpak** [comment]
It has been fixed and works as expected in the latest version. See [plnkr with `v1.4.7`][1].

[1]: http://plnkr.co/edit/hagUqXGwwggNuEjC2psR?p=preview

**Comment by DeanMW** [comment]
@gkalpak, Still will not insert into the object with invalid numbers like e123123, I'm assuming we will call this a "feature"? 

Also no need to fork my example when I was already using 1.4.7 :/

**Comment by DeanMW** [comment]
Another test case which doesnt work. Typeing e123 and then correcting this to a valid number and adding 1 to the front 1e123 does not add this now valid number to the model.

**Comment by gkalpak** [comment]
> Still will not insert into the object with invalid numbers like e123123, I'm assuming we will call this a "feature"?

@DeanMW, there is nothing Angular can do in this case, since an invalid value (such as `e123`), changes the input's `value` property to an empty string (the browser does that), so there is no way for Angular to know what value is displayed in the field.

--
> Also no need to fork my example when I was already using 1.4.7 :/

When I tried your example it was using `v1.4.0` (that's why I had to fork it).

**Comment by DeanMW** [comment]
Awesome, thanks for the quick feedback! :+1:  I guessed there was a certain point where it became a browser issue and no longer an Angular fixable thing. Thanks. 


>>Also no need to fork my example when I was already using 1.4.7 :/

>When I tried your example it was using v1.4.0 (that's why I had to fork it).

Also sorry about that, I noticed after I typed thats why I edited it away :)
