### ISSUE TITLE
Phonecat tutorial does not follow style guide

### ISSUE THREAD

**Issue by teropa** [angular/angular.js#13312]
The [Phonecat tutorial](https://docs.angularjs.org/tutorial) does not really follow the conventions laid out by the [Angular Styleguide](https://github.com/johnpapa/angular-styleguide).

In particular, I think the following rules should be applied:

* [Rule of 1](https://github.com/johnpapa/angular-styleguide#style-y001)
* [Folders-by-feature structure](https://github.com/johnpapa/angular-styleguide#style-y152)
* [controllerAs View Syntax](https://github.com/johnpapa/angular-styleguide#style-y030)

It also might not hurt to explicitly refer to the style guide in the tutorial.

**Comment by teropa** [comment]
I'm working on the Angular 2 upgrade guide, and thinking of using Phonecat as the example app to upgrade. It would be less awkward if this issue was resolved.

I'm happy to work on this, but would first like to know whether you'd accept such changes.

**Comment by petebacondarwin** [comment]
I agree. PRs are welcome - but phonecat is a right pain to refactor due to the nature of it using commits as the tutorial steps

**Comment by teropa** [comment]
@petebacondarwin Thanks! I'll dig into it.

**Comment by teropa** [comment]
@petebacondarwin Looks like I'll need to make changes to some of the diagram images in the tutorial. Do you know where I might find the sources for them?

**Comment by petebacondarwin** [comment]
Hmm. Not sure.  I'll see if I can find out

**Comment by gkalpak** [comment]
Closed with c2033d7.
