### ISSUE TITLE
How do I document an attribute should either be present or absent?

### ISSUE THREAD

**Issue by csaftoiu** [angular/angular.js#13316]
I want to create a directive which takes a parameter based on whether an attribute is present. That is:

    <foo some-attr></foo>

Should do one thing, while:

    <foo></foo>

Should do another thing. I know how to accomplish this [in code](http://stackoverflow.com/questions/25811734/check-existence-of-attribute-in-angular-directive). 

The question is, how do I document this with [ngdoc](https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation)? Currently I have:

    /**
     * @ngdoc directive
     * @name someModule.directive:foo
     * @restrict E
     * @param {boolean=} someAttr If present, will do something.
     */

However, when the documentation is generated with [ngdocs](https://www.npmjs.com/package/grunt-ngdocs), it looks like this:

> # Usage

> as element:

>     <foo
>          [some-attr="{boolean}"]>
>     </foo>

This doesn't really convey what I want, which would be something like:

> # Usage

> as element:

>     <foo
>          [some-attr]>
>     </foo>
    
Is there any way to make the generated documentation look like that?

**Comment by Narretz** [comment]
Looks like this is an issue for https://github.com/angular/dgeni-packages. Please open an issue there.

**Comment by csaftoiu** [comment]
Thanks - I always forget that dgeni-packages is where ngdoc lives.
