### ISSUE TITLE
Unable to watch the changes of the property '$' of an object which is used by filterFilter.

### ISSUE THREAD

**Issue by javeme** [angular/angular.js#13313]
Unable to watch the changes of the property '$' of an object which is used by filterFilter.

```
//object to search 
$scope.search = {'$': 'something...'}

//watch the object
$scope.$watch('search',
  function (newValue, oldValue) {
    //do action 
    results = filter(list, search);
    ...
  }, true);
```
The "$" in the function filterFilter represents any property, however it represents built-in variable in the function equals(watch). 
How to resolve the conflict between them?

filterFilter: https://github.com/angular/angular.js/blob/master/src/ng/filter/filter.js#L235
equals(watch): https://github.com/angular/angular.js/blob/master/src/Angular.js#L992
Smart-Table: https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L122

**Comment by petebacondarwin** [comment]
@javeme You could supplement your watch with value of this property directly...

```js
//object to search 
$scope.search = {
  '$': 'something...',
  // ... other filtering properties
};

function filterResults() {
  results = filter(list, search);
} 
// watch the search object (except the `$` property)
$scope.$watch('search', filterResults, true);
// watch the `$` property
$scope.$watch('search.$', filterResults);
```

This would not work for situations where `$` appears further down in the search object.

Perhaps this is another use case for https://github.com/angular/angular.js/pull/10096

**Comment by LiZhangmei** [comment]
@petebacondarwin Thanks for your solution, if we already know the bug we could bypass it. but it would be better If we can completely solve it.

**Comment by petebacondarwin** [comment]
Perhaps the easiest solution here would be to allow the "match any property" identifier symbol (currently `$`) to be configured on a filter by filter basis?

The `filterFilter` could have an extra parameter:

```js
//object to search 
$scope.search = {
  '%': 'something...',
  // ... other filtering properties
};

function filterResults() {
  results = filter(list, search, undefined, '%');
} 
// watch the search object (including the `%` property)
$scope.$watch('search', filterResults, true);
```

Now the watch would pick up changes to the `%` properties. Would that be acceptable?

@gkalpak do you have any thoughts on this?

**Comment by gkalpak** [comment]
@petebacondarwin, your suggestion sounds reasonable. It should be easy to implement and not introducing any BC, so why not ?

#10096 would offer an equally good solution (but both can co-exist).

I am fine with both.

--
Admittedly, it wasn't a great choice to have use `$` (which is considered Angular-proprietary) for something that we expect the user to specify.

If we considered this a bug and wanted to fix it, maybe we could add an extra check, wherever we check (and ignore) properties starting with `$`, to also check that the property isn't just `$` (in which case it shouldn't be ignored).
(I'd be a little BC though.)

--
So, all things considered, I think @petebacondarwin's suggestion gives the best "value-for-money" :smiley:

**Comment by petebacondarwin** [comment]
> Admittedly, it wasn't a great choice to have use $ (which is considered Angular-proprietary) for something that we expect the user to specify.
<sub>
  I did think of saying this but thought it would not be fair on the person who wrote the code - especially as I reviewed it :->
</sub>

PRs welcome!

**Comment by gkalpak** [comment]
> I did think of saying this but thought it would not be fair on the person who wrote the code

Nah...Angular has (almost) always taken pride in having a large community and a great team. There's no person in Angular, it's always a team. I didn't mean to be judgemental in any case :smiley:

--
> - especially as I reviewed it :->

Are you sure ? It seems that the special `$` filter property has been there since [the very very first commit][1] to this repo.
I obviously spoke too soon. It's the other way around: `$` as a special filter property was there before standardizing the convention of prefixing Angular-specific properties with `$`/`$$`.
<sub>(Useless info of the day: `ng` was `nglr` back then. Go figure !)</sub>

[1]: https://github.com/angular/angular.js/commit/c9c176a53b1632ca2b1c6ed27382ab72ac21d45d#diff-130f2c355f842efd96e966d06090c4c7R81
