### ISSUE TITLE
jquery lite "after" parent node is null

### ISSUE THREAD

**Issue by tborychowski** [angular/angular.js#13315]
There is an odd case, where in IE11, this line throws an error:
https://github.com/angular/angular.js/blob/master/src/jqLite.js#L962

I have an `ng-repeat` inside `ng-if` clause (not sure if that's relevant to the problem) and I get an error on that `ng-repeat` (in IE11 only!) and the error states, that the `parent` is null.
When I `console.log` the `element` from that `after` function - it points to the `ng-repeat` comment that angular adds before the real `ng-repeat`.

**Comment by Narretz** [comment]
Can you please post a demo (plnkr.co) of that problem?

**Comment by tborychowski** [comment]
From further investigation It seems to be happening when the `ng-repeat` is inside a `ui-view` (I'm using `ui-router` plugin).
So this would not be an angular issue after all :-)
Sorry for rising the issue here prematurely, and thanks for your response.
