### ISSUE TITLE
$q.all doesn't properly reject promises

### ISSUE THREAD

**Issue by drcapulet** [angular/angular.js#13325]
Examples: http://plnkr.co/edit/XAIP4elGDXjvwSKjewjJ?p=preview

The second then should also be rejected, but instead it succeeds.

Affects: 1.3.13+ (tested a handful of newer versions).

**Comment by drcapulet** [comment]
Nevermind me, looks like I misread the spec on promises. Still odd that the result of a `.then` is the new promise and you can go from rejected to succeeded.

**Comment by pkozlowski-opensource** [comment]
> Still odd that the result of a .then is the new promise and you can go from rejected to succeeded.

It is an equivalent of a `try / catch` block in a synchronous programming where you don't re-throw from catch but recover there. I don't see nothing odd with it.
