### ISSUE TITLE
$swipe doc references component `ngCarousel`

### ISSUE THREAD

**Issue by Mutmatt** [angular/angular.js#13322]
Kind of confused by the documentation on the docs.  They seem to reference a component that i have not been able to locate "ngCarousel."

[$swipe](https://docs.angularjs.org/api/ngTouch/service/$swipe)

[swipe.js](https://github.com/angular/angular.js/blob/master/src/ngTouch/swipe.js)

Line 16: 
* `ngCarousel` in a separate component.

**Comment by Narretz** [comment]
ngCarousel doesn't exist. Mabye it did at one point. Do you want to open a PR that removes this?
