### ISSUE TITLE
google api support

### ISSUE THREAD

**Issue by MadMub** [angular/angular.js#13329]
Currently implementing an angular app with google sign in. I find the documentation, browser practices, and general api usage wonky and difficult to understand (that's more of a general critique aimed at google apis).

Current sign in development flow found here:
https://developers.google.com/identity/sign-in/web/

This design does not support modern module loaded/bundled client side development. In general I think there should be a better client side api library (currently source code is posted nowhere, there is a stale repo, with no source code, again a general google api issue).

Relating to angular, I think developer support for angular could increase with an official "angular-google-api" to easily allow for google user authentication. Obviously this wouldn't be part of angular core, but as suggested be an extension.

**Comment by Narretz** [comment]
Do you mean something like this? http://jeradbitner.com/angular-directive.g-signin/
Or more high level, i.e. services that can be used by components?
Also can you elaborate what do you mean by this:
> This design does not support modern module loaded/bundled client side development

In general, I think this is more of a community project. These APIs tend to change quite often. Also, if we start with one API, people will request others to follow. We should instead focus on the core framework.

**Comment by MadMub** [comment]
The directive you mention uses a deprecated sign in (Google+). I guess my goal, is to consider if Google should go the route of Android, since they run the project, they could, tightly integrate some of their services into the product.

Of course this would spark debate on whether that is appropriate, but if ultimately the goal is to get wide adoption, offering more services out of the box puts less stress on developers to find "one off directives".

In this particular case, i see it like this: most angular users have goals of developing a web app, and most of those webapps need login, why not have an out of the box integration with their Identity Platform.

To address the "this design does not support..." comment, I am referring to the fact that their client side api has no source code available. The usage requires us to bring in the platform the old way
```
<script src="/path/to/platform.js"></script>
```
I think across the board developers want full control over the source code going into their application, with a modernly written library, a module loader could pick and choose what methods/functions to bring in. This of course is a critique of the google-javascript-api and not angular.

I also see a future of integrating the Identity Platform for angular 2.0, as the goal their will be to have hybrid apps (to my knowledge at least that is a project goal), where an angular app is running on iOS and Android, where again a tight integration with sign in could offer a lot to potential developers.

**Comment by MadMub** [comment]
@Narretz not sure if my latest comment added more useful context

**Comment by petebacondarwin** [comment]
@MadMub - As I understand it, Google Signin is just using OAuth 2.0 (see https://developers.google.com/identity/sign-in/web/sign-in). So perhaps you could use [oauth-ng](http://andreareginato.github.io/oauth-ng/) to achieve what you want?

In any case, this is definitely something that should be dealt with by a 3rd party Angular module and not in the core Angular library. Right now we don't have the resources to put together such a library but if oauth-ng doesn't do it, we would be happy for someone else to provide such a module.
