### ISSUE TITLE
<textarea ng-model="test" ng-init="test = '{{ () }}'></textarea> gives hard error

### ISSUE THREAD

**Issue by rbaarsma** [angular/angular.js#13335]
it seems everything that through ng-model is put inside the <textarea>content</textarea> is also executed. So this breaks the page:
```html
<textarea ng-model="test" ng-init="test = '{{ () }}'></textarea>
```

Now this may or may not be intended, but my common usecase is to load the ng-model from ng-init from a server-side rendering (to prevent additional ajax calls). If however the user inputs {{ () }} into the textarea and saves, then reloads the page, there's a hard JS error. This could also be used by users to show other angular vars in their posts.

In my opinion the default behavior (just as with ng-bind-html) should be to escape user input and therefore the above should be impossible. Just like with the ng-bind-html sanatize methods there should probably be some workaround in case the above behavior is intended.

See also jsbin for the simplest example: https://jsbin.com/xirumalepa/edit?html,output

**Comment by Narretz** [comment]
You can easily work around this by not using ng-init and instead setting it on the scope. 
The problem has also nothing to do with ngModel, it's simply that the parser cannot handle `"ng-init="test = '{{ () }}'"'. It looks like it tries to interpolate `()` and that fails.
I'm also not quite sure why you are having interpolation brackets in your ng-init - ng-init takes an expression, not an iterpolation.

**Comment by Narretz** [comment]
@lgalfaso can you check if the parser is doing the right thing in this case?

**Comment by Narretz** [comment]
Yes, on further evaluation, `()` is not a valid expression, and throws a parse error (also in real Javascript). And attribute can contain interpolations, which are evaluated independently of any directive that access the attribute value.
So you should either set the variable on the scope, or if you have to set it on in ng-init, escape the curly braces: `'\{\{ () \}\}'`
