### ISSUE TITLE
ngCookies reading domain cookie from subdomain, but can't delete?

### ISSUE THREAD

**Issue by moneytree-doug** [angular/angular.js#13332]
I have a cookie written from the top level, and then redirecting to my Angular app in a sub-domain. I want my angular app to read the cookie from the sub-domain (which is working fine) and then delete it, but I am unable to delete it. Is this the intended design?

For example, the cookie would have the domain ``.hello.com`` and my Angular app is hosted on ``app.hello.com`` and is trying to delete the cookie with the domain  ``.hello.com``

I tried setting the domain in options when removing, but that did nothing.

**Comment by moneytree-doug** [comment]
I just found out that everything has to be the same. I was able to get this to work after setting the path to the same.

**Comment by prashanthparsi** [comment]
Hey I need this. How did you do this?
