### ISSUE TITLE
when i use $location's service make error in console 

### ISSUE THREAD

**Issue by Jason-mor** [angular/angular.js#13337]
##### second step: click the delete button ,many error in console
![image](https://cloud.githubusercontent.com/assets/13294110/11242721/77dfc8b8-8e3e-11e5-97ff-abf1ec178c34.png)

### because my page need to support ie8, so i can only use 1.2.x 
``` html
<!DOCTYPE html>
<html ng-app="myApp">
	<head>
		<meta charset="utf-8">
		<script src="//cdn.bootcss.com/jquery/1.11.1/jquery.js"></script>
		<script src="//cdn.bootcss.com/angular.js/1.2.28/angular.js"></script>
	</head>
<body>

<div ng-controller="myCtrl">
	<button ng-click="add()">add
	</button>
	<button ng-click="delete()">delete
	</button>
</div>

<script>
var app = angular.module('myApp', []);
app.controller('myCtrl', function($location, $scope) {
    $scope.add = function(){
    	$location.search("name", "Jason");
    }
    $scope.delete = function(){
    	$location.search("name", null);
    }
});
</script>
</body>
</html>
```

**Comment by frfancha** [comment]
It doesn't happen with 1.4, and it doesn't happen when the removed attribute isn't the last one.
But it also happen if if just call $location.search({}) in the delete.
Strange.
As a by-pass, you could set at least a "dummy" attribute in your search, as the problem occurs only when you remove the last attribute of search.

**Comment by Narretz** [comment]
Development on 1.2.x is effectively halted. I suggest you look on of the support channels and see if someone finds a workaround: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
