### ISSUE TITLE
Add `ng-empty-value` attribute to `ngOptions` directive

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#13334]
See https://github.com/angular/angular.js/issues/1780#issuecomment-157344476

**Comment by Narretz** [comment]
I think that this is not needed in core, as it can be simply and robustly implemented as a 3rd party module - see https://github.com/angular/angular.js/issues/1780#issuecomment-294939793 for more info. @gkalpak also agrees that this is not 100% necessary: https://github.com/angular/angular.js/pull/13471#issuecomment-287732365
