### ISSUE TITLE
ngAnimate doesn't remove class which is animating

### ISSUE THREAD

**Issue by maxaon** [angular/angular.js#13339]
Removing class which is currently animating doesn't work. 

**Angular Version:** since 1.4.5 till 1.5.0-build.4389
**Browser:** Any
**Reproducable:** almost always (sometimes doesn't reproduce under debugging)
**Operating system:** Any

**Detail**
For the example of bug see [plunker](http://plnkr.co/edit/BsWymZhJ35Ljs9EYSu1Z?p=preview)
By normal it should not have class `pending` at the end.

What happens:
1. Adding class `pending`
2. NgModel adds class `ng-valid-required` (it's joining animation and applies preparation class)
3. Timeout is fullfilled
4. Trying to remove class. 
Inside ngAnimations it checks that element has animations, it cannot be cancelled and skipped, so it's try to join animation. Because element is in running state it tries to normalize options.  Function normalize options cannot find class  `pending` and remove it from options. Remove animation exits as invalid.
5. Class `pending` added to dom node

**Comment by Narretz** [comment]
Very interesting. Is the use of `attrs.$addClass` necessary? You could otherwise simply use `element.addClass` and the bug does not appear: http://plnkr.co/edit/k8KBsZ3hlXgC0QsL2eAB?p=preview

**Comment by maxaon** [comment]
Yes, as a temporary solution, we do not use animations, but nevertheless adding animation in this situation is problematic.

**Comment by Narretz** [comment]
This will be fixed by #13414, see http://plnkr.co/edit/ldW3OBDahDbiK5C2bnzP?p=preview
