### ISSUE TITLE
ngAnimate transitions on android webview 4.

### ISSUE THREAD

**Issue by herbzi** [angular/angular.js#13342]
I am using ng-include animations in my project and I have noticed that on android webview 4 for certain transitions (transform translate and anything that uses transition delay etc) ng-enter is not applied. The old template leaves correctly but the new one shows instantaneously. Other transitions including opacity and left work correctly so long as they don't include a transition delay. 

I quickly forked someone elses plunker, this works on chrome etc but will not work correctly on android webview 4. http://plnkr.co/edit/Kz7I98OLzuGQStf7We2w?p=preview

This also works fine on versions 1.3.x of ngAnimate but does not work on 1.4.x or 1.5.0-beta-2.
I am testing this using android 4.4.2.

This has been bothering me for some time. I would appreciate a workaround if anyone knows one. 

Edit: it actually works on the android simulator 4.4.2 (api level 19)  because this actually runs android 4.4.4 with webview version 33 but it doesn't work on versions below 4.4.3.

**Comment by Narretz** [comment]
Since this is a rather old version of Android now, and no further reports have come about this, I'm going to close this issue.
