### ISSUE TITLE
Using <md-select> with <md-option> of '<' fails

### ISSUE THREAD

**Issue by djmarcus1** [angular/angular.js#13348]
I use `<md-option>` to display math boolean operators for the user to select.

    <md-select ng-model="operator" style="width: 75px" aria-label="Select comparison operator">
      <md-option ng-value="lessThan">&lt;</md-option>
      <md-option ng-value="lessThanEqual">&lt;=</md-option> 
      <md-option ng-value="equal">=</md-option>
      <md-option ng-value="true">true</md-option>
    </md-select>

See codepen: http://codepen.io/djmarcus/pen/avMeod

When I select the `<` option, the selected value becomes `=`.

When I do the same thing using a regular `<select>`, it works:

    <select>
      <option value="lessThan">&lt;</option> 
      <option value="lessThanEqual" selected>&lt;=</option>
      <option value="equal">=</option>
      <option value="true">true</option>
    </select>

**Comment by djmarcus1** [comment]
A personal guess on what is going on:

I see, using chrome DOM element inspection, that the DOM generated is something like:

    <md-select-value class="md-select-value" id="select_value_label_137">
      <span>=</span>
      <span class="md-select-icon" aria-hidden="true"></span>
    </md-select-value>

Note the `<span>=</span>`

I assume one of these is generated for each `<md-option>`.

So, my first option is `&lt;` which would generate a `<`

So if it tries to generate `<span><</span>` there would be a problem.

Just a guess. I tried single-stepping the code with a debugger but could not follow all the transformations that take place :-(

**Comment by Narretz** [comment]
You should open this issue in https://github.com/angular/material/

**Comment by djmarcus1** [comment]
Agreed.. I actually thought I was in 'Material'.. brain freeze.. my apologies .. late in day :-(
