### ISSUE TITLE
ngShow/ngHide in ngInclude within ngRepeat does not work

### ISSUE THREAD

**Issue by lukas-schulze** [angular/angular.js#13345]
Tested with AngularJS 1.4.7.
If I use ngInclude inside of a ngRepeat, the ngShow and ngHide is not executed as expected.

Example: http://lukas-schulze.github.io/angular-showhide-bug/

**Comment by pkozlowski-opensource** [comment]
Where is your `tpl.connected.html` variable defined?

**Comment by pkozlowski-opensource** [comment]
I've got an impression that you are expecting ng-include to take a string, while it takes an expression that evaluates to a template name. If you still believe that this is a bug please share live reproduce scenario using plunker, jsfiddle or similar - it is hard to debug your code without any ability to modify it / seeing the entire example.
