### ISSUE TITLE
Question for Two-way bind with JSON string

### ISSUE THREAD

**Issue by RopoMen** [angular/angular.js#13351]
Hi,

I didn't find any issue that could have given me the answer for this so I post this.

I was doing some performance testing with AngularJS Batarang Chrome extension and it crashed Angualar environment, my [JSFiddle](https://jsfiddle.net/RopoMen/4f2Latb1/) 

as you can see, I discovered that in two-way binding you can handleJSON string in to the variable and becomes an parsed object.

Why I use this? because I can initialize that same directive through single interface from the server side and from view template, without defining two different kind of initialization paths.

My questions are:
Is this a hidden feature? 
 * if this is a hidden feature I think this should be documented
 * If this is a hidden feature, but intended for internal use, then this still should be documented, but also strong mention that **do not use, internal only stuff**

Is this a bug in two-way binding?
 * it should be fixed ofc. :)

https://github.com/angular/batarang/issues/282

**Comment by frfancha** [comment]
<<as you can see, I discovered that in two-way binding you can handleJSON string in to the variable and becomes an parsed object.>>

In your JSFiddle, you don't provide a JSON string but a simple javascript expression giving an object, and ... it gives this object.
Exactly as in pure javascript you write:
o = {p: 2};
There is no hidden feature at all.

**Comment by frfancha** [comment]
Looking further, indeed what you should provide is an assignable expression, which a "pure" object expression such as {p: 2} is not.
Therefore you fiddle should crash (angualr should report an error) and it doesn't.
This is because it will reports an error only if try to really use two way:
add
scope.stuff = 3;
in your directive then you will get the normal message that {...} is not assignable

**Comment by RopoMen** [comment]
Good point :) I updated that string now to HTML encoded JSON string (Chrome hides HTML entities unless you select "edit as HTML")

```html
<my-directive stuff="{&quot;cat&quot;: &quot;cat&quot;, &quot;some&quot;: &quot;some&quot;}"></my-directive>
```

But yes, this would break that, but in my case I don't need to alter the original value, because the directive is only showing values and doesn't provide any editing capabilities.
```js
scope.stuff = 3;
```
Ok, well... I will fix my implementation to support pure Two-way binding + some attribute from which I can pass JSON string in to directive. But it is still attempting to abuse that Two-way binding "because it works"

**Comment by petebacondarwin** [comment]
@RopoMen this is exactly what you would expect Angular to do. Your HTML encoded string is still passed to the Angular compiler as the following "Angular expression": `{'cat': 'cat', 'some': 'some'}`. Angular will evaluate this expression in the context of the scope where the attribute is found and the inner `$scope.stuff` will indeed contain a JavaScript object with `cat` and `some` properties.

It is also completely valid to pass a non-assignable expression through to a directive using `=` binding, as long as you don't intend to assign to it inside the directive.

Marking as works as expected.

**Comment by frfancha** [comment]
@petebacondarwin You say: ''It is also completely valid to pass a non-assignable expression through to a directive using = binding, as long as you don't intend to assign to it inside the directive.''
Good to know, thanks, but then the error message you receive when you don't pass expression at all is not really correct, see documentation of $compile:
''If the parent scope property doesn't exist, it will throw a NON_ASSIGNABLE_MODEL_EXPRESSION exception.''

**Comment by petebacondarwin** [comment]
You are right, it should say, "If the parent scope property does not exist, **and you try to assign a value to the property on the isolate scope**, it will throw a NON_ASSIGNABLE_MODEL_EXPRESSION."

PRs welcome.
