### ISSUE TITLE
ngAnimate: Jumps in transition when 'delay' is set with $animateCss, but not set in CSS

### ISSUE THREAD

**Issue by ben-reilly** [angular/angular.js#13355]
Plnkr: http://plnkr.co/edit/DGI0fUHtzQkyIw6CKuJ6?p=preview

When I run a transition using $animateCss with a delay set in the params, the transition will jump suddenly sometimes, especially when `delay` = `duration`.

I don't think this is supposed to be happening.

This issue is easily fixed by setting `transition-delay` in the object's CSS to **any value at all** (which gets ignored). I am not sure why no-value behaves differently from `transition-delay: [any value]`.

A general workaround for anyone having trouble is to put the following at the top of your CSS:
````
* {
  transition-delay: 0s;
}
````
since this is the default value for `transition-delay` anyway.

**Comment by Narretz** [comment]
For the record, it doesn't happen in Firefox for me.

**Comment by Narretz** [comment]
This seems to happen because we ignore the delay value unless it's also set in style, in which case the delay values are recalculated.

**Comment by Narretz** [comment]
I took the liberty of fixing this - see #13363
