### ISSUE TITLE
ng-repeat does not work

### ISSUE THREAD

**Issue by ollorens** [angular/angular.js#13357]
I have a JSON file in a PHP.

My controller prints the console.log properly but my view does not print data from a ng-repeat. 

Could you please help me on this? 

see below my controller and the html view:

/* My php - json file */

<?php

header("Content-type: application/json");
 
$data = array();

include 'conexion.php';
  
$result = mysql_query("SELECT * FROM equipos");
 
while($row = mysql_fetch_array($result)){
    $data['equipos'][] = array(
        'Equipo' => $row['nombre_equipo'],
        'Nombre del Jugador' => $row['nombre_jugador'],
        'Apellidos del jugador' => $row['apellidos_jugador'],
        'Primer Entrenador' => $row['primer_entrenador'],
    );
}
 
echo json_encode($data);

?>
/*PHP - result:*/
{"equipos":[{"Equipo":"Cadete Preferente A2","Nombre del Jugador":"xxxx","Apellidos del jugador":"yyyyy","Primer Entrenador":"LLLLLLLL"},{"Equipo":"Cadete Preferente A2","Nombre del Jugador":"oooooo","Apellidos del jugador":"ooooooo","Primer Entrenador":"ttttttttt"},{"Equipo":"preinfantil A","Nombre del Jugador":"happy","Apellidos del jugador":"basket","Primer Entrenador":"Santiago"},{"Equipo":"preinfantil A","Nombre del Jugador":"Alejandro","Apellidos del jugador":"uuuuuuuuu","Primer Entrenador":"Santiago"},{"Equipo":"","Nombre del Jugador":"superman","Apellidos del jugador":"kriptonita","Primer Entrenador":"batman"},{"Equipo":"Cadete A","Nombre del Jugador":"superwoman ","Apellidos del jugador":"wonderwoman","Primer Entrenador":" spiderman"}]}

/* My Model */
var myApp = angular.module('myApp', []);
myApp.controller('customersCtrl', function($scope, $http) {

	$scope.equipos = [];

    $http.get("api/consulta.php")
    .success(function(data) {
    	$scope.equipos = eval.data;
    	console.log(data);
    });

});

/* My HTML */
/*Use my html tags as comments in order you will be able to see it.*/

/*<div ng-controller="customersCtrl">

   <ul>
      <li ng-repeat="x in equipos">
        
        {{ x.primer_entrenador }}

      </li>
    </ul>

</div> */

Thank you very much in advance,
Kind Regards,
Oscar.

**Comment by balbuenac** [comment]
You should change  $scope.equipos = eval.data; to  $scope.equipos = eval.data.equipos;

**Comment by ollorens** [comment]
Thank you for your help but it does not work.

**Comment by gkalpak** [comment]
Shouldn't it be `$scope.equipos = data.equipos` ?
In any case, this is a general support question and should be directed to the [appropriate support channels][1].
<sub>GitHub is reserved for bug reports/feature requests.</sub>

--
<sub>Unrelated to your question, but the PHP code needs some love as well (e.g. you [shouldn't use the MySQL extension][2]).</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
[2]: https://stackoverflow.com/questions/12859942/why-shouldnt-i-use-mysql-functions-in-php
