### ISSUE TITLE
ngOptions is setting select $dirty when options change and selected option is removed

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#13362]
When the options change, and the currently selected option is removed because of that, we update the model and set it to the unknown / empty option. We do this by calling $setViewValue, which calls $setDirty. That means if the options change before the user has interacted with the form, the select is set to $dirty even though there was no user interaction.
We could do the following things:
1. Remember the $pristine state and restore it if was true
2. Don't use $setViewValue, as it's not really made for that purpose.

Bug was introduced here: https://github.com/angular/angular.js/commit/933591d69cee2c5580da1d8522ba90a7d924da0e

**Comment by petebacondarwin** [comment]
OK, so we can do the following:

```js
        // Check to see if the value has changed due to the update to the options
        if (!ngModelCtrl.$isEmpty(previousValue)) {
          var nextValue = selectCtrl.readValue();
          if (ngOptions.trackBy ? !equals(previousValue, nextValue) : previousValue !== nextValue) {
            ngModelCtrl.$iewValue = nextValue;
            ngModelCtrl.$$parseAndValidate();
            ngModelCtrl.$render();
          }
        }
```

@Narretz do you think this will be acceptable?

**Comment by Narretz** [comment]
That looks good, but I think we also need to do `ngModelCtrl.$$lastCommittedViewValue = nextValue`, because that's what the parse pipeline and the validators use.

**Comment by Narretz** [comment]
We would still be losing the update to the empty status. Basically, we are just working around the problem. Imo we should be setting the model directly. Or enhance setViewValue so that we can skip the pristine setting in a logical way. Maybe by passing the trigger argument all the way to commitViewValue

**Comment by petebacondarwin** [comment]
Hmm, setting the model to `null` eh? That could work.

**Comment by Narretz** [comment]
I'm not sure if we have the right API for that. We'd need to access the model setter, but ngModel does not expose that. Since no-one else has found the bug, I'm also okay with pushing it back to post-1.4.8

**Comment by Narretz** [comment]
Not going to get fixed.
