### ISSUE TITLE
$q makes controller instance lose context of `this` (thisArg) object in its methods

### ISSUE THREAD

**Issue by frapontillo** [angular/angular.js#13369]
I have just started writing controllers and directives in TypeScript, using controller methods that get compiled as controller function prototype methods.
When I use `$q` in a method and then rely on `this` to refer to the controller instance in other (chained) methods, I lose the context of the `this` object. A live demo of the issue is available [in this plunker](http://plnkr.co/edit/JJraqaGbWup1Y68v2o0a), but the main issue can be easily described here:

```javascript
MyDirectiveController.prototype.doSomething = function() {
  // makeSomePromise returns a promise 
  // (and is able to access to controller properties via this.someVariable)
  return this.makeSomePromise(1)
    // makeSomeCalculation takes a value and tries to set a property 
    // on the controller instance (e.g. `this.anotherVariable`): THIS ERRORS
    .then(this.makeSomeCalculation);
};
```

The only obvious solution I found (which I don't like a lot) is to use `.then(this.makeSomeCalculation.bind(this))` to forcefully bind the `thisArg` object of the function to the controller instance.
Is this a bug or is there any other way to achieve the same result in a "cleaner" way?

The live demo is running AngularJS 1.4.8 and the behaviour was tested on Chrome.
Related topics:
- http://stackoverflow.com/questions/28638600/angularjs-http-interceptor-class-es6-loses-binding-to-this (I am getting `window` as well, instead of the constructor, when referencing `this`)
- http://stackoverflow.com/questions/30185369/angularjs-promise-this-references-window

**Comment by pkozlowski-opensource** [comment]
This is expected behavior as defined in the Promises A+ spec: https://promisesaplus.com/#point-35

**Comment by frapontillo** [comment]
TIL, thanks for the accurate reference @pkozlowski-opensource! :sparkles:

**Comment by ryanhart2** [comment]
Using the typescript arrow function will result in
```js
this.makeSomePromise(1)
  .then((response) => this.makeSomeCalculation(response));
```
compiling to
```js
var _this = this;
this.makeSomePromise(1)
  .then(function (response) { return _this.makeSomeCalculation(response); });
```
```this``` in the makeSomeCalculation function will then reference ```_this```, which I believe is what you want

**Comment by frapontillo** [comment]
Arrow fns really eliminate a lot of boilerplate (repeating the parameter would still be unavoidable), I may end up using this form, thanks!
