### ISSUE TITLE
angular.equals question

### ISSUE THREAD

**Issue by furyscript** [angular/angular.js#13366]
I need to compare two object like this
```javascript
var a = { a: "1" };
var b = { b: 1 };
angular.equals(a,b); // false
```
I want to use `==` for `===`, can I or can be added this feature?

**Comment by Narretz** [comment]
I think that's too specific a requirement. The angular.x functions are tailored for what the core needs. So I suggest you use something like lodash's isEqual (which let's you customize the comparator): https://lodash.com/docs#isEqual
