### ISSUE TITLE
Displaying JSON

### ISSUE THREAD

**Issue by manoj1991** [angular/angular.js#13375]
Not able to display authenticated JSON from a remote server in a angular js table??

```
var app = angular.module("MyApp", []);

app.controller("PostsCtrl", function($scope, $http) {
    $http.get('http://fabfresh-dev.elasticbeanstalk.com')
    $http.defaults.headers.common.Authorization = 'Bearer jkegrdnjnk54wkje';
    $http.defaults.headers.post["Content-Type"] = "application/json";
    $http.defaults.headers.patch["Content-Type"] = "application/json";
    success(function(data, status, headers, config) {
      $scope.posts = data;

    }).
    error(function(data, status, headers, config) {
      // log error
    });
});

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
