### ISSUE TITLE
input[url] validation regex is not valid

### ISSUE THREAD

**Issue by Noamyoungerm** [angular/angular.js#13379]
In v1.4.8 the validation scheme for `url` inputs was changed, causing valid URLs with semicolons, which previously passed the filter, to become invalid

Our application handles the generation of long urls with messy query strings to be used in advertising, so it's important to us that esoteric characters remain supported. [Semicolons are valid URL characters](http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid)

You can reproduce the error at the angular code example for a [url input](https://docs.angularjs.org/api/ng/input/input%5Burl%5D), try entering
```
http://www.test.com/asdf;df
http://www.test.com/asdf?asd=f;df=df
```

The fix is simply to add a semicolon to the last chunk of the validation regex [here](https://github.com/angular/angular.js/commit/cb51116dbd225ccfdbc9a565a66a170e65d26331)

**Comment by gkalpak** [comment]
Sounds like a real bug. Apart from `;` there seem to be a few more characters that should be allowed in the `URL_REGEXP`: `[`, `]`, `$`, `'`, `(`, `)`, `*`, `,`, `;`, `~`

I will take a closer.

--
In the meantime, a little context: The `;` character wouldn't have been allowed by our `URL_REGEXP` in previous versions, but another bug in the regexp shadowed this issue. That other bug was fixed as part of cb51116 in `v1.4.8`, revealing the `;` issue (bug?).

**Comment by andypatterson** [comment]
@gkalpak @Narretz I've opened a PR against `angular:v1.4.x` - please let me know if it should be against a different branch and I'll create a separate PR.

**Comment by gkalpak** [comment]
Thx @andypatterson !

For future reference:
Usually, you should submit the PR against the master branch, which is where development is mainly taking place, and we will cherry-pick it into specific older version branches if necessary/appropriate.
You should still submit against a concrete version branch, if it's a bug/feature specific to that version (e.g. it is already solved or not applicable on master).

<sub>(You don't need to submit a new PR for this, we'll take care of cherry-picking it into master.)</sub>
