### ISSUE TITLE
feat: method to check whether a certain module exists

### ISSUE THREAD

**Issue by robstoll** [angular/angular.js#13371]
Hi,

I would like to request a new feature. I am currently using the following hack to know whether a certain module was already created or not

```javascript
var module;
try { 
  module = angular.module(moduleName);
} catch(err) {
  module = angular.module(moduleName, []);
}
```
Which is of course not ideal and could be simplified if angular does somehow expose `modules`, the registered modules respectively. 

Following the use case where I am using this hack:

```javascript
function tutteliRegisterController(moduleName, dependencies, controllerName, constructor){
    var module;
    try { 
        module = angular.module(moduleName);
        module.requires.push.apply(module.requires, dependencies);
    } catch(err) {
        module = angular.module(moduleName, dependencies);
    }
    module.controller(controllerName, constructor);
}    
```

I am using this function in order that I can separate controllers into different files without the need to bother whether a module (which I am kind of using like a namespace) was already created or not.
This way I can nicely separate the angular registration from the actual functionality like so:

```javascript
tutteliRegisterController(
  'tutteli.controllers',
  ['tutteli.auth'],
  'tutteli.LoginController',
  LoginController
);

LoginController.$inject = ['tutteli.auth.AuthService'];
function LoginController(AuthService){
  //..
}
```

This is surely just a nice to have feature and it works as well without it. But maybe there are more people who would like it. Just as an idea.

**Comment by petebacondarwin** [comment]
Why not just put each controller into its own module, which is guaranteed not to exist already, then do the registration of the controller modules when declaring the app module?

**Comment by robstoll** [comment]
Sure, I could to that, but I think that is not the purpose of modules. In the end I do not want to have a very long list with dependencies. I could create another module which depends on all controller-modules which then can be used from the outside, but that's a so much work for such little gain. 
Anyway, the feature request is not really about my function but about the missing functionality to query whether a certain module exists or not. Another use case I can think of is to implement some sort of fallback. If a certain module is not present then I use a fallback implementation

I created a pull request which shows the feature I have in mind. Nothing special really just some sugar if you like.

**Comment by petebacondarwin** [comment]
While I appreciate that it would be nice not to have to list off all the modules that your app depends upon, I would argue that this is exactly the purpose of modules. Remember that module dependency is hierarchical and so you could group similar components together in a single module and then group similar modules together in higher level module. Then you only need to depend upon these few higher modules.

My concern with encouraging re-opening of modules is that it makes it more difficult to track what is actually going to be loaded from looking at the source code.

Also, you should consider that the only time when you should be checking the existence of a module (from a fallback perspective) is just before bootstrap. Consider the following scenario:

```html
<html>
  <head>
    <script src="angular.js"></script>
    <script src="a.js"></script>
    <script src="b.js"></script>
    <script src="c.js"></script>
  </head>
  ...
</html>
```

where `a.js`, `b.js` and `c.js` all define modules `a`, `b` and `c` respectively. Notice that we can load these script files in any order, even if these modules depend upon each other.

What happens if, in the `b.js`, you are checking to see if `c` module has been loaded, and if not then falling back and adding some other module `c2`. Then later the `c` module gets loaded from `c.js`. You would be in a strange situation where `c2` and `c` would be competing with each other...

If you want to do what you are doing but without resorting to hacks then you could try something like the following:

```js
function ControllerRegistry() {
  this.controllers = {};
  this.depencencies = [];

  this.register = function(controllerName, moduleDependencies, constructor) {
    this.controllers[controllerName] = constructor;
    this.dependencies = this.depencencies.concat(moduleDependencies);
  }

  this.createModule = function(moduleName) {
    return angular.module(moduleName, dependencies).controller(controllers);
  }
}

  ////////


var registry = new ControllerRegistry();
registry.register('Controller1', ['dep1', 'dep2'], function($scope) { ... });
registry.register('Controller2', ['dep4'], function($scope) { ... });
registry.register('Controller3', ['dep3', 'dep2'], function($scope) { ... });

var myModule = ControllerRegistry.createModule('myModule');
```

**Comment by robstoll** [comment]
> Remember that module dependency is hierarchical and so you could group similar components together in a single module and then group similar modules together in higher level module. Then you only need to depend upon these few higher modules.

I agree and also make use of the hierarchical behaviour, but it does not make sense to put every single controller, service, factory etc. into a separate module. That's unnecessary overhead IMO and I suppose you agree with me on this one. 

Thanks for the example, but it leaves me with a similar problem. As soon as I take the idiom one file = one responsibility = one controller/service etc., then I do not know when to call `createModule` and the `ControllerRegistery` object needs to be created before the controllers. Using `angular` is handy since it needs to be loaded beforehand anyway and I do not need to deal with other loading order issues.

> My concern with encouraging re-opening of modules is that it makes it more difficult to track what is actually going to be loaded from looking at the source code.

I guess you mean by "re-opening of modules" the way I add additional dependencies to the module, right? I think it is clearer to have the dependencies where I require them, ergo next to my controller/service etc. instead of defining a module like so:
```javascript`
angular.module('tutteli.controllers', ['a', 'b', 'c']);
```
where it is not obvious why I have the dependencies if the corresponding code which depends on those modules is in another file.

I do not know, maybe the idiom one file = one responsiblity does not make sense with angular. That might be the problem in the end. What do you think?

**Comment by gkalpak** [comment]
A small observasion: 

Not having all dependencies of a module mentioned/registered in one place === looking for trouble (imo).

If I am to depend on module A, I want to see `angular.module('A', ['dep1', 'dep2'])` and know what module A depends on. It would be a very unpleasant surprise, if any controller/service inside module A brings in more deps at runtime behind the scenes.

Just my 2 cents...

**Comment by robstoll** [comment]
Maybe you guys are right, might be confusing as well. It just happened to me that I had a module with lot of dependencies without knowing any more which component requires it, if they are really all required etc. I need to re-think this and the one file = one responsiblity. Maybe it is not really suited for angular

**Comment by petebacondarwin** [comment]
I always go with one file - one module in my apps. If things are similar enough to be in the same module then they go in the same file. The overhead is only at bootstrap time (once the injector is created then modules have no relevance) and I suspect that the actual impact would be trivial if measurable.

**Comment by petebacondarwin** [comment]
Alternatively I know that some people use their own packaging system, such as require.js, letting that do all the collecting up of the code and then have a single module per output file.

**Comment by robstoll** [comment]
Alright, I will try the one file = one module approach. I'll close this issue and the corresponding pull request. Thanks for your time

**Comment by gkalpak** [comment]
> It just happened to me that I had a module with lot of dependencies without knowing any more which component requires it

If you have a lot of components in your module (with lots of dependencies), maybe it is an indication you need to break it down to smaller modules.

FWIW, I use 1 file per _thing_ (controller or service or directive or template or module definition etc) and it has worked nicely for me so far. (This is also what @johnpapa's [style guide recommends][1].)

But sure that requires some more "coordination" when loading/concatenating the files (i.e. _order matters_).

--
Of cource other approaches are viable as well - it also depends on the size of the app, the team working on it etc.

[1]: https://github.com/johnpapa/angular-styleguide#style-y150
