### ISSUE TITLE
Bower install can't find 1.4.7 version for angular-sanitize

### ISSUE THREAD

**Issue by thiniulian** [angular/angular.js#13370]
We have a dependency for angular-sanitize 1.4.7 in our project and bower can't find it. 
In the bower-angular-sanitize repo are tags only for 1.5.0 builds.

**Comment by OscarBarrett** [comment]
The tag is still there.
https://github.com/angular/bower-angular-sanitize/releases/tag/v1.4.7

`bower install https://github.com/angular/bower-angular-sanitize.git#1.4.7` worked for me.

**Comment by thiniulian** [comment]
I think there was a problem with bower. Now it seems to work. 
Thank you!
