### ISSUE TITLE
input[type=datetime-local] does not support changing the timezone dynamically

### ISSUE THREAD

**Issue by Dretch** [angular/angular.js#13382]
The timezone can be set on `type="datetime-local"` inputs (e.g. `ng-model-options="{timezone: '+0400'}"`), but once the datetime picker has been created, changes to the timezone are not reflected in the edited value.

This plunk demonstrates the issue: http://plnkr.co/edit/R1cFGi23y0Eq2Fe7iN5h?p=preview - when you click the button then the timezone is put forward an hour, but this is not reflected in the time shown.

This happens in at least Chrome and Firefox on OS X, via angular `1.4.7`.

**Comment by gkalpak** [comment]
One problem with tracking the timezone is that it is not clear what should happen when it changes:

1. `modelValue` + `newTimezone` ==> `newViewValue` ?
2. `viewValue` + `newTimezone` ==> `newModelValue` ?

@Narretz, any thoughts on this ?

**Comment by Dretch** [comment]
@gkalpak 

The behaviour I personally would like is for the *displayed* value to change - the unix timestamp should remain the same.

I was able to work around this issue by forcing a re-render using the directive here http://stackoverflow.com/questions/22080351/how-to-re-render-a-template-in-an-angular-directive

**Comment by Narretz** [comment]
ngModelOptions doesn't watch option changes - this is currently by design. We could change that, but so far I haven't seen many requests for it.
