### ISSUE TITLE
debuginfoenabled(false) not working after update version 1.4.3  to 1.4.8

### ISSUE THREAD

**Issue by sargsyangugo** [angular/angular.js#13396]
when I set debuginfoenabled to false state then in browser I see debug info like 

<@-- ngSwitchWhen: 1 -->
<@-- ngIf: gameModel.PeriodNumber==6 -->
.......
etc.

**Comment by gkalpak** [comment]
It's hard to know what you are seeing in the browser and whether it is indeed debug info or not. Providing a live reproduction (e.g. using CodePen, Plnkr etc) would help provide a definitive answer.

From the looks of it though, it seems you are seeing the placeholder comment nodes that inserted from Angular into the DOM as placeholders/markers for certain transcluding directives (including `ngIf` and `ngSwitch`). This is not debug info, it is necessary data for those directives to perform their task.

--
Closing as everything seem to work as expected. Feel free to re-open if you can provide evidence that these are actual debug info.
