### ISSUE TITLE
ng-route not working in phonegap

### ISSUE THREAD

**Issue by CalvinPangch** [angular/angular.js#13406]
I had create the angular js Application. it working fine in my IIS server , 
but i build it in phonegap and it does not work. 
P/S: i also got the error when i direct open as html 

the error msg i get 
![Image of error](http://i.stack.imgur.com/Nj6sR.png)

i had added $compileProvider.urlSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|tel):/); but still didnot work.

any solution ? or its a bug ???

**Comment by Narretz** [comment]
I don't know much about phonegap, so I can't say with certainty where the problem is. But it doesn't look like a angular problem at first sight. Have you tried to use the current version of angular (1.4.8)?

**Comment by CalvinPangch** [comment]
yes i use the latest angular js version 1.4.8

**Comment by Narretz** [comment]
The screenshot said something different. :) It looks like you shouldn't directly access the filesystem, but run it inside a server. Basically, it's trying to make a XHR request to a file in the filesystem, I don't think that works.

**Comment by CalvinPangch** [comment]
angular js cannot make XHR request to file system directly ? must use server ?

**Comment by Narretz** [comment]
what does your route definition look like anyway?

**Comment by Narretz** [comment]
Closing due to lack of feedback
