### ISSUE TITLE
In IE11 $http with method 'GET' taking longtime to load ,but in chrome it works fine,,,,,appx time in IE11 >6sec,in chrome <3 seconds

### ISSUE THREAD

**Issue by reddysainathn** [angular/angular.js#13407]

**Comment by Narretz** [comment]
This could have a huge number of reasons. First, you should test if the behavior is the same with a pure XHR,

**Comment by reddysainathn** [comment]
I see the same issue with pure XHR, 

only IE11 takes >6 seconds and Other all browsers including IE10 < 3 seconds

**Comment by Narretz** [comment]
Then I'd say it's not an issue with angular. You should open a ticket with Microsoft or ask on Stackoverflow etc. If you do, can you post a link here? The bug sounds interesting.
