### ISSUE TITLE
How do you tell if an optional multi transclude property has been set?

### ISSUE THREAD

**Issue by waeljammal** [angular/angular.js#13426]
Basically I can not find a way to check if an optional transclude was supplied, I want to show hide the parent based on the transclude being set or not.

If there is no way is it possible to get this added? It is a useful feature to along side optional transclude.

Thanks

**Comment by petebacondarwin** [comment]
This is something that @PascalPrecht was asking for too, I think...

**Comment by petebacondarwin** [comment]
A benefit of this would be that we could provide default content in `ngTransclude` for optional transclusion slots.

**Comment by petebacondarwin** [comment]
Here is a PR: https://github.com/angular/angular.js/pull/13431
