### ISSUE TITLE
What dose this line do ? 

### ISSUE THREAD

**Issue by dubiao** [angular/angular.js#13434]
I was searching a bug of my app and found a magic line in [`/src/ngRoute/route.js`](https://github.com/angular/angular.js/blob/master/src/ngRoute/route.js#L159) line 159

>159____var redirectPath = (path[path.length - 1] == '/')
>160___________? path.substr(0, path.length - 1)
>161___________: path + '/';

It seems that if the path's last char is '/' then remove it. And if it's not, then add one.
Is this a bug?

**Comment by lgalfaso** [comment]
This works as expected. This is the paths `foo/bar/` and `foo/bar` will be mapped to the same route regardless of which is the one you define
