### ISSUE TITLE
Binding to objects works much more consistently than binding to primitives

### ISSUE THREAD

**Issue by cicuz** [angular/angular.js#13437]
Basically, I keep randomly bumping in the issue described [on this StackOverflow conversation](http://stackoverflow.com/questions/18642371/checkbox-not-binding-to-scope-in-angularjs/23943930#answer-23943930), where an ng-model binding doesn't really work unless it's put inside an object.
The unexpected behaviour is also inconsistent: sometimes the binding does not work at all; sometimes it works for a couple of variables but not for other, identical, ones; sometimes it works on one button but not on another one modifying the same variable.
I feel like I need to know how I can avoid this.
Thank you.

**Comment by B1aZer** [comment]
If you haven't read already - [from angular wiki](https://github.com/angular/angular.js/wiki/Understanding-Scopes). 

This is rather old problem and as a best practice just use dot in ng-models. Something like 'models.name' instead of simply 'name'.

**Comment by frfancha** [comment]
It is not a problem at all, just the normal way prototype inheritance works.

**Comment by petebacondarwin** [comment]
I think that @B1aZer and @frfancha have covered this.
