### ISSUE TITLE
ng-strict-di directive not working with ngRoute

### ISSUE THREAD

**Issue by vonmoltke** [angular/angular.js#13432]
I am working on an application that uses ngRoute and ran into a module initialization error.  I traced the error down to the ngRoute module.  I am using `ng-strict-di`, and simply including the ngRoute js module and defining the `$routeProvider` config function as per the ngRoute documentation causes initialization of my application to fail.  Either removing `ng-strict-di` or the config function allows my application to start normally.

I have replicated this same behavior using the example provided in the `$route` documentation.  I modified the controller definitions in that example to comply with strict DI guidelines; [this file is here](https://github.com/angular/angular.js/files/49927/script.js.txt).  When I add `ng-strict-di` to the `<body>` tag per the directive instructions application initialization fails with <a href="http://errors.angularjs.org/1.5.0-beta.2/$injector/modulerr?p0=ngRouteExample&p1=Error%3A%20%5B%24injector%3Astrictdi%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.0-beta.2%2F%24injector%2Fstrictdi%3Fp0%3Dfunction(%2524routeProvider%252C%2520%2524locationProvider)%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A6%3A423%0A%20%20%20%20at%20Function.eb.%24%24annotate%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A189%3A52)%0A%20%20%20%20at%20Object.e%20%5Bas%20invoke%5D%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A40%3A309)%0A%20%20%20%20at%20d%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A39%3A148)%0A%20%20%20%20at%20http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A39%3A272%0A%20%20%20%20at%20n%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A7%3A344)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A39%3A49)%0A%20%20%20%20at%20eb%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A42%3A361)%0A%20%20%20%20at%20c%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0-beta.2%2Fangular.min.js%3A19%3A463">this highly generic error</a>.  It isn't clear from the Angular documentation that I am doing anything wrong or that ngRoute is fundamentally incompatible with strict DI.

**Comment by lgalfaso** [comment]
You have to make this line strict-di compatible

.config(function($routeProvider, $locationProvider) {

**Comment by vonmoltke** [comment]
Thanks.

I did find the relevant part of the Dependency Injection section of the documents after your suggestion.  The code works fine now with strict DI on.
