### ISSUE TITLE
$templateRequestProvider httpOptions are not used when downloading templates

### ISSUE THREAD

**Issue by bananer** [angular/angular.js#13441]
With angular 1.5.0 beta2 have the following config block:
```
app.config(function($templateRequestProvider) {
    $templateRequestProvider.httpOptions({
        params: {
            '_': 'some-build-id'
        }
    });
});
```

I expect this to add a parameter to the request when downloading any template.

This is not the case, no parameter is added. I checked with a debugger a bit and it seems like $templateRequest is never used to download templates, apparently it goes directly to $http.

Maybe I'm misunderstanding what this provider is used for, but I was under the impression i can modify the behaviour when angular needs to request a template file.

**Comment by Narretz** [comment]
What kind of templates are we talking about? Directive templates? ng-includes? route templates?

**Comment by bananer** [comment]
The templates I tried loading were for routes with angular-ui/ui-router, I just realized this is not an issue with angular directly and angular-ui already has pull requests for using $templateRequest. Works fine for directive templates.
