### ISSUE TITLE
ng-options dropdowns (angular 1.2) broken with new version of chrome (47)

### ISSUE THREAD

**Issue by phillcunliffe** [angular/angular.js#13446]
The select appears functional until you try and select anything.

Code:
```
<select name="test" class="Sitedropdown"
        data-ng-model="model"
        data-ng-change="changeHandler()"
        data-ng-options="model.number as model.number for model in modelList">
        <option value="">Select Model Number</option>
</select>
```

This code worked before the latest chrome update

**Comment by willsr** [comment]
replicated on windows + linux

**Comment by Narretz** [comment]
Is this a correct demo: http://plnkr.co/edit/BdlXmtyNW5VC1qwNqm9x ? (Please always include a runnable demo, that makes things much easier).

I have tested with  49.0.2581.0 canary (64-bit) and 47.0.2526.73 m and it works in both browsers (1.2.29)

Please also not that 1.2.29 is a legacy version which only receives security and critical bug fixes.

**Comment by matijagrcic** [comment]
It's related to the chromium issue [Modal window drop-down menus are not working in AngularJS 1.2.6](https://code.google.com/p/chromium/issues/detail?id=565132)

**Comment by Narretz** [comment]
Thanks. Will monitor if that gets resolved in Chromium. Maybe it's also possible and easy to patch it in angular.

**Comment by Narretz** [comment]
I've just seen that the problem does not appear with the latest version - 1.2.29, so I'm inclined to say this is basically already fixed.

**Comment by ncoevoet** [comment]
is there a work around we could use with some changes in angular's directives ?

**Comment by Narretz** [comment]
Like I mentioned, you can upgrade to 1.2.29.

**Comment by Narretz** [comment]
If for some reason, you cannot update to 1.2.29, this here is the commit that makes it work: https://github.com/angular/angular.js/commit/dc149de9364c66b988f169f67cad39577ba43434

**Comment by jasonkvickers** [comment]
For umbraco users, they have posted a download with the patch from Angular team: 
http://issues.umbraco.org/issue/U4-7496

**Comment by Narretz** [comment]
Fixed in the stable version of Chrome: https://code.google.com/p/chromium/issues/detail?id=565132#c57
