### ISSUE TITLE
jsFiddle linked from the main page doesn't work

### ISSUE THREAD

**Issue by dmitriz** [angular/angular.js#13457]
Anyone noticed the major Component example on the main page 
https://angularjs.org/#create-components 
links to jsFiddle 
https://jsfiddle.net/api/post/library/pure/ 
that is broken?

It puts the comment with the non-existent link inside the CSS
```
 <!-- Ugly Hack due to jsFiddle issue: http://goo.gl/BUfGZ -->
```
whereas jsFiddle wants you to use external resources instead.

Maybe Plunkr can be used instead, consistently with the rest of the site?

Also `replace` probably shouldn't be used as it is deprecated?

**Comment by petebacondarwin** [comment]
We need to do a reworking of the home page examples...
@beardyco - fancy converting the examples to link to Plunker?

**Comment by Narretz** [comment]
That's fixed now
