### ISSUE TITLE
Dependancy injection into decorating functions

### ISSUE THREAD

**Issue by epeleg** [angular/angular.js#13470]
I am not sure if this is the right place to ask but here goes anyway,
please let me know if there is a better place to ask Q's like this one.

I have also asked this in http://stackoverflow.com/questions/34130070/dependency-injection-into-decorator-functions-in-angularjs but got no response there.

When using angularJS you can register a decorating function for a service by using the $provide.decorator('thatService',decoratorFn).

Upon creating the service instance the $injector will pass it (the service instance) to the registered decorating function and will use the function's result as the decorated service.

Now suppose that thatService uses thatOtherService which it has injected into it.

1) How I can I get a reference to thatOtherService so that I will be able to use it in .myNewMethodForThatService() that my decoratorFN wants to add to thatService?

my current solution to the problem was to:
var inj=angular.element(document.body).injector()
var $thatOtherService = inj.get('$thatOtherService');

it works but it smells...

2) The situation becomes even more complex if you consider that other functions of 'thatService' might (and often do) use variables that are defined in the body of the service constructor function and are available to the service methods via closure... - is there any way to tap into those some how?

**Comment by gkalpak** [comment]
This indeed not the best place to ask these types of questions. The (more appropriate) support channels are listed [here][1].
<sub>(We try to reserve GitHub for bug reports and feature requests.)</sub>

Regarding your 2nd question:
No, it's not possible to access variables that are only available to the service via closure from another function. If you need access to them, your service has to expose them. 

--
> I have also asked this in http://stackoverflow.com/... but got no response there.

You might get one soon ;)

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
