### ISSUE TITLE
$scope modelValue variable does not properly update when Chrome autofills field

### ISSUE THREAD

**Issue by reZach** [angular/angular.js#13478]
I've outlined [a post over on StackOverflow][1], but my question outlines the use of the "chain of command" AngularJS runs through when updating $modelValue and $viewValue. In short:

When Chrome autofills my phone number field, the $parsers for this field are executed, giving my phone number field the correct **$viewValue**, but the **$modelValue** is not updated with the formatted value. 

I do not know if the better approach is to fiddle in the $parsers array to update the $modelValue or if there is another way I should be going about this (or if this is a bug)

  [1]: http://stackoverflow.com/questions/34141516/chrome-autofill-angularjs-field-bug

**Comment by Narretz** [comment]
I've added a comment to your question. I'm gonna close this one here, as it's a support question.

**Comment by reZach** [comment]
Okay, I will update the link with an example
