### ISSUE TITLE
Documentation is broken due to broken references for core library files

### ISSUE THREAD

**Issue by antoniomercado** [angular/angular.js#13475]
*Broken Page*: https://docs.angularjs.org/guide/directive
*Reason*: Core library file references are broken. Looking at my developer console several links look like this ...
`https://ajax.googleapis.com/ajax/libs/angularjs/null/angular.min.js`
Notice the "null" in the URI where the version number is supposed to go. 

Changing to `https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js` gets me the content.

**Comment by guilbep** [comment]
+1

**Comment by cebor** [comment]
:+1:

**Comment by pkozlowski-opensource** [comment]
Aware and @petebacondarwin is working on a fix

**Comment by antoniomercado** [comment]
Great to hear you guys are on top of it. Do you have an estimated ETA on fix?

**Comment by Narretz** [comment]
In the meantime, you can use the devdocs: http://devdocs.io/angular/ or use the docs here: https://code.angularjs.org/1.4.8/docs/api/ng/function/angular.extend

**Comment by antoniomercado** [comment]
Thanks for the links just what I needed

**Comment by Narretz** [comment]
Docs are baaaaack: https://docs.angularjs.org/api

**Comment by mescalito** [comment]
what was the problem? if I may ask...
