### ISSUE TITLE
Write migration notes for 1.4->1.5 

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#13474]
Here https://docs.angularjs.org/guide/migration and for a blog post

**Comment by guilbep** [comment]
The dev part is not working: https://docs.angularjs.org/#
Are you aware of that?

**Comment by Narretz** [comment]
@guilbep We are aware, thanks!

**Comment by petebacondarwin** [comment]
The docs are back up. It was a glitch in the release of 1.5.0-rc.0
