### ISSUE TITLE
Select ng-options with "group by" does not clear list on update (IE11)

### ISSUE THREAD

**Issue by simon04** [angular/angular.js#13487]
Having  a `<select>` and `ng-options` with a `group by` clause, after an update of the `list` (e.g. using a `filter`) the rendered list (of `<optgroup>`/`<option>`) isn't cleared but gets longer and longer after each update (IE11).

```html
<select size="20" ng-model="selected" 
  ng-options="i as i.name group by i.cls for i in list | filter:filter">
</select>
```

**Steps to reproduce**:
1. Open https://jsfiddle.net/gk8xeupm/ with IE11
2. Type "foo" into the filter text field
3. Clear text field
4. Type "bar" into the filter text field
5. Clear text field
6. Watch the list becoming longer and longer

**AngularJS**: 1.4.8
**Reproducable**: always
**Operating System**: Windows 10
**Browsers**: IE version 11.11.10586.0

**Comment by Narretz** [comment]
Wow, that looks completely broken. In my IE, the groups are already duplicated on load.

**Comment by simon04** [comment]
Thank you a lot for the super-quick fix! :sunny:

**Comment by Narretz** [comment]
No problem! It was so broken I had to fix it immediately. The changes will land in 1.5.0 / 1.4.10.
