### ISSUE TITLE
Add groups to form validation

### ISSUE THREAD

**Issue by m-amr** [angular/angular.js#13484]
Add this feature to angular forms
if we have form with a lot of controls and we want to validate only some of these controls
by adding validation group name to ng-validation-group directive

    <form nam="user">
        <input type='"text" name=''name" ng-validation-group="personalData" ng-required="true"/>
        <input type='"text" name=''age"  ng-validation-group="personalData"  ng-required="true"/>
       // Other inputs
       //Other inputs
     </form

so we can check if these controls that belong to group "personalData" is valid or not by just using
    
    user.personalData.$valid
 
other than using 
   
     user.name.$valid && user.age.$valid 

Thanks

**Comment by Narretz** [comment]
You can group controls with subforms:

    <form name="user">
        <div ng-form name="personalData">
          <input type='"text" name=''name"  ng-required="true"/>
          <input type='"text" name=''age"    ng-required="true"/>
       </div>
       // Other inputs
       //Other inputs
     </form>

and `user.personalData.$valid`

**Comment by Narretz** [comment]
Closing due to lack of feedback (and available options)
