### ISSUE TITLE
Mock $httpBackend.respond() should support conditional passThrough()

### ISSUE THREAD

**Issue by coli** [angular/angular.js#13482]
I'd like to be able to in the respond() function, programmatically passThrough() the request under certain conditions.

**Comment by petebacondarwin** [comment]
I guess you are talking about `ngMockE2E`, not `ngMock` here?
By definition we do not want to make server requests in unit tests.

**Comment by Narretz** [comment]
Closing due to lack of feedback. I know that people use ngMockE2E as a faux-backend for development (instead of tests), so maybe that's where OP is coming from.
