### ISSUE TITLE
AngularJS Library Production support

### ISSUE THREAD

**Issue by medevelop** [angular/angular.js#13499]
hi,
This is a concern normally companies raises before accepting this open source library for developing the enterprise application...
Is there any professional support available from Google or *AngularJS  development/support team* for AngularJS library  ?

thanks
Akash

**Comment by petebacondarwin** [comment]
The Angular team do not provide paid for support for angular.js.
The project is being used internally at Google for hundreds of production applications, if that is helpful in determining its reliability.
As an open source project, we are happy to accept high quality bug fixes into the codebase.
If you wish to discuss a closer relationship between your company and the Angular team, then you can contact @juleskremer.
