### ISSUE TITLE
ng-blur don't fire event on firefox with input number

### ISSUE THREAD

**Issue by carlosvicient** [angular/angular.js#13508]
I have post a question on [stackoverflow](http://stackoverflow.com/questions/34176344/ng-blur-dont-fire-event-on-firefox-with-input-number).

Apparently, the blur event on an html input number type on firefox is not fired when using the up and down arrows. I can't find if the problem is because of Angular or due to the browsers.

**Comment by Narretz** [comment]
Doesn't look like an angular problem: http://plnkr.co/edit/9KiAuCIqJ5orhg5cTOLd?p=preview

And the way Firefox displays the input, the event behavior looks correct. When you are outside the input, and click the arrows, the input is not focused. Likewise, when you are inside the input and click the arrows, the input is not defocused / blurred. 

In Chrome, when you are outside the input and click the arrows, the input us focused (event fired). When you are inside, and click the arrows, the input is not defocused (same as FF) and the blur event is not fired.

This looks all correct to me.

**Comment by carlosvicient** [comment]
I see what you mean. Thanks for the answer and for the example. 

It is totally clear now. However, I do not understand the firefox's event behaviour. Since the arrows are inside the input, when clicking on them they should be focussed and, being focused, they should be blurred when clicking outside the input (like chrome does). 

But as you said, doesn't look like an angular problem.

Thanks again for your answer and apologize for any inconveniences this may have caused.

**Comment by Narretz** [comment]
The arrows aren't elements in their own right, so they these can't be focused. They belong to the input field. I think what Firefox should do is to focus the input when the arrows are clicked. Maybe you can open an issue at Mozilla about this?

**Comment by carlosvicient** [comment]
I have created an issue in [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1232233). Thanks again.

**Comment by GildedHonour** [comment]
@carlosvicient why did you not say thanks?
