### ISSUE TITLE
$httpBackend.verifyNoOutstandingRequest fails to throw when digest is not triggered

### ISSUE THREAD

**Issue by katemihalikova** [angular/angular.js#13506]
**Overview of the Issue**
In unit test, I use `$httpBackend.verifyNoOutstandingRequest();` to make sure that no request was done. The test also passes when the request is done, because `verifyNoOutstandingRequest` does not trigger digest (in contrary to `flush` and `verifyNoOutstandingExpectation`) which leads to unpropagated [_Unexpected request_](https://github.com/angular/angular.js/blob/75e876424da5f569481488d03cf3a61441341513/src/ngMock/angular-mocks.js#L1237) error.
There is a [comment](https://github.com/angular/angular.js/commit/ea6fc6e69c2a2aa213c71ed4e917a0d54d064e4c#commitcomment-11571705) asking whether calling digest should be added to `verifyNoOutstandingRequest` as well, but with no response.

**Use Case** - testing that `$http` request is _not_ being done
**Angular Version** - 1.4.8
**Reproduce the Error**
```js
    it('should not allow submitting invalid form', function() {
        var ctrl = createCtrl();
        ctrl.submit();
        $httpBackend.verifyNoOutstandingRequest();
    });
```

**Comment by gkalpak** [comment]
Sounds like a reasonable change (if nothing else, restores consistency with `verfiyNoOustandingExpectations() and `flush()`). It will be a BC, though - might be a good candidate for `v1.6.x`.

@katemihalikova, would you like to take a stub at it (and see how much it breaks our testsuite :smiley:) ?

**Comment by katemihalikova** [comment]
Will look into it soon :+1:
