### ISSUE TITLE
need to set ngCookies path to root or to base path

### ISSUE THREAD

**Issue by SnehalSatardekar** [angular/angular.js#13509]
Hello,

I am facing one issue with ngCookies.

I have one js script where i can set my routes and the home page is index.php.

I have used ngCookies for storing logged in user data like name, email etc.

When i try to login with URL as <my_domain>/index.php, cookies works perfectly.
But when I do the same thing with URL as <my_domain>/, cookies doesnt work.

Please help me with this.

**Comment by gkalpak** [comment]
This sounds like a general support question. @SnehalSatardekar, please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
