### ISSUE TITLE
Upgrade build setup to node 5 + update all npm dependencies (especially karma)

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.js#13505]
also can someone please prepare PRs to make master, 1.4.x, 1.3.x compatible with node 5? do not merge them, just prepare the PRs please. Ideally these three branches should have the same build setup and be always updated in sync so that it’s easy to jump between branches and cherry-pick commits
- [ ] master
- [ ] 1.4.x
- [ ] 1.3.x

**Comment by IgorMinar** [comment]
this is not time-critical but we should do it soonish. on or before Dec 21 is good.

**Comment by gkalpak** [comment]
Node 5 comes with npm 3, which breaks our "purge node_modules in preinstall" workflow. This is tracked in https://github.com/angular/angular.js/issues/13123.

The same issue should also affect ng2 (see https://github.com/angular/angular/issues/5172). @IgorMinar, any ideas on how to tackle it on ng2 ?

**Comment by IgorMinar** [comment]
I'll work on nmp3 upgrade of ng2 in late december.

If this is blocking then let's upgrade to node 4 first now and once ng2 is
npm3 compatible we'll reuse the same approach here.

**Comment by Narretz** [comment]
Why do we need it for 1.3? I'd say more people are using 1.2 than 1.3.

**Comment by petebacondarwin** [comment]
I think it is reasonable to ensure that our main branches are all building on the same environment.
1.3 is a low priority for us but I think that there are still quite a few Google apps using that version. @IgorMinar could probably provide more detail.

**Comment by petebacondarwin** [comment]
Here is a PR for using node 4 on Travis: https://github.com/angular/angular.js/pull/13552

**Comment by Narretz** [comment]
We are on node 6 right now :D
