### ISSUE TITLE
angular.merge loses type information

### ISSUE THREAD

**Issue by djonesdev** [angular/angular.js#13500]
Assuming I have the following code:

```javascript
  function Cat(name) {
    this._name = name;
  }
  
  var myFatCat = new Cat("Garfield");
  var myKitten = new Cat("Nermal");
  
  if(myFatCat instanceof Cat){
    console.log("I'm a cat!");
  } else {
    console.log("I'm not a cat :(");
  }
  
  var myCats = {
    cat1: myFatCat,
    cat2: myKitten
  };
  
  var myPets = angular.merge({}, myCats);
  
  if(myPets.cat1 instanceof Cat){
    console.log("I'm a cat!");
  } else {
    console.log("I'm not a cat :(");
  }
```

The type information of the 'deep' object is lost.

**Comment by petebacondarwin** [comment]
This is expected. The `merge` function just copies enumerable properties across from the source object to the destination object. It is outside the scope of this function to be able to make deep clones that have the same type information.

**Comment by lgalfaso** [comment]
Agree with @petebacondarwin it is outside the scope of `angular.merge` to copy type information
