### ISSUE TITLE
Binding Select list with value from database

### ISSUE THREAD

**Issue by DevQueen** [angular/angular.js#13501]
The problem - I need to fill a select list from one table (in this case U.S. States) but I need to set the default value equal to a field brought back from a call to web api that brings back user info and the State of the user's office.  The database designer did not name the fields the same and, I quote, he "doesn't believe in foreign keys".  The field in the State table that holds the State abbreviation is callled vchStateID  (and it is the key field), and the field with the value I need to show in the select list which comes from the user info is called vchOfficeStateID.  Is it possible to get this to work?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
