### ISSUE TITLE
MessageFormat gender not working

### ISSUE THREAD

**Issue by danielsmink** [angular/angular.js#13516]
```{{genderExpression, gender,
    male { Send him a message. }
    female { Send her a message. }
    other { Send them a message. }
}}```

According to the specs this should work, but I can't find any references to it in the code. And obviously it doesn't work when you try to use it either.

**Comment by danielsmink** [comment]
@chirayuk could you please let us know if this should be supported?

**Comment by Narretz** [comment]
According to the specs? You mean the messageFormat spec, right? I'm not sure it's completely supported. Also, chirayuk isn't working on this anymore iirc.

**Comment by danielsmink** [comment]
@Narretz ye the spec described in the Google doc https://docs.google.com/document/d/1pbtW2yvtmFBikfRrJd8VAsabiFkKezmYZ_PbgdjQOVU/edit and @PascalPrecht uses the Gender selection as an example in a blog post: http://blog.thoughtram.io/angular/2015/12/10/ng-message-format-the-unheard-feature-in-angular.html

**Comment by Narretz** [comment]
Strange, didnt' they test it? I suggest you open an issue in their blog's github if it doesn't work. Have you checked the guide page? https://code.angularjs.org/1.5.0-rc.0/docs/guide/i18n#MessageFormat-extensions
A Cursory glance reveals that it has gender-related code.

**Comment by danielsmink** [comment]
Thanks for that link @Narretz switching out `gender` with `select` fixed the issue. I've let @PascalPrecht know as well and they fixed their blog post.
