### ISSUE TITLE
URL_REGEXP is not accurate

### ISSUE THREAD

**Issue by IlanFrumer** [angular/angular.js#13528]
@andrewaustin @petebacondarwin

This commit broke the URL validation: https://github.com/angular/angular.js/commit/ffb6b2fb56d9ffcb051284965dd538629ea9687a

For example this URL (which uses a curly brackets macro syntax and should be a perfectly valid URL):
```
http://ads.xxxxx.com/xxxxxx/?pid=1234&pos=c&r={TIMESTAMP}
```

![console](https://cloud.githubusercontent.com/assets/3116399/11768383/013d4c22-a1d4-11e5-985b-192e9d1bf6b0.png)

Also check this
http://stackoverflow.com/questions/5984116/regular-expression-for-w3c-compliant-urls

**Comment by andrewaustin** [comment]
Sorry, but ```{``` and ```}``` are not allowed in URIs. You can read RFC 3896 for the full rules about URI characters: https://tools.ietf.org/html/rfc3986#section-2

Furthermore, RFC 3897 is even more explicit: 
> Systems accepting IRIs MAY also deal with the printable characters in US-ASCII that are not allowed in URIs, namely "<", ">", '"', space,  "{", "}", "|", "\", "^", and "`", in step 2 above.

**Comment by andrewaustin** [comment]
Sorry, but ```{``` and ```}``` are not allowed in URIs unless they are URL encoded. You can read RFC 3986 for the full rules about URI characters: https://tools.ietf.org/html/rfc3986#section-2

Furthermore, RFC 3987 is even more explicit:

> Systems accepting IRIs MAY also deal with the printable characters in US-ASCII that are not allowed in URIs, namely "<", ">", '"', space, "{", "}", "|", "\", "^", and "`", in step 2 above.

And later:

> On the other hand, in the HTTP protocol [RFC2616], the Request URI is defined
       as a URI, which means that direct use of IRIs is not allowed in
       HTTP requests.

**Comment by IlanFrumer** [comment]
@andrewaustin thanks for the clarification
- Since we are validating a user input I think it is more clear to use IRI
- Also (as i said) this syntax was valid before this commit, so if we choose URI we must add it to the breaking changes list.

Thanks.

**Comment by petebacondarwin** [comment]
We will make a decision about this before RC.1

**Comment by Narretz** [comment]
We've been following Chrome in the past in terms of what urls are allowed (not implementation). Both Chrome and Firefox allow curly brackets, so I think we should too.

**Comment by gkalpak** [comment]
AFAIK, we've ever actually followed Chrome in terms of URL validity.
Before ffb6b2f, there was a bug in `URL_REGEXP` that allowed all non-whitespace characters in hostname (i.e. it never matched port, path, query, hash - it considered it all to be one, big, valid, hostname).

After ffb6b2f and e4bb838 (which built on top of the former), we try to more closely match the URI spec. Browsers seems to be much more forgiving - maybe we should be too (i.e. be more concerned with validating the structure, than the actual characters).

**Comment by IlanFrumer** [comment]
@gkalpak this should also be fixed inside 1.4.x

**Comment by gkalpak** [comment]
@IlanFrumer, it has - I just forgot to link to the commit (6610ae8). Thx for pointing it out :smiley:
