### ISSUE TITLE
Combine factory with routeParams/stateParams in controller

### ISSUE THREAD

**Issue by mankinchi** [angular/angular.js#13529]
I am trying to inject the services and routeParams/stateParams in my controller but they doesn't work well together

My simple code:

Factory code: 

myApp.factory('sharedInfo', function () {
  var data = {
    age: 13
  }
  return data;
});

Controller code:

myApp.controller("venueCtrl", ["$scope", "sharedInfo", function($scope, $routeParams, sharedInfo) {
  console.log(sharedInfo.age);
}])

If I inject routeParams, the log would be an error since sharedInfo is undefined.
If I don't, the log will be 13.

**Comment by Narretz** [comment]
The injection strings must be in the same order as the function arguments. You are missing $routeParams in your injection strings.
