### ISSUE TITLE
Erroneous FIRSTDAYOFWEEK in most of european locales

### ISSUE THREAD

**Issue by toni-moreno** [angular/angular.js#13523]
https://github.com/angular/angular.js/blob/master/src/ngLocale/angular-locale_es-es.js 

FIRSTDAYOFWEEK should be (monday) = 1 but now it has 0 as first day of week.

There is any plans to fix this error?

**Comment by Narretz** [comment]
The data comes from https://github.com/google/closure-library/tree/master/closure/goog/i18n, so it needs to be fixed there.  Odd that it should be wrong for such a basic property.

**Comment by lgalfaso** [comment]
The property for first day of the week follows ISO 8601 that has the unfortunate property that 0 is Monday. This same issue showed up multiple times, but changing this to match JavaScript would be a breaking change.

**Comment by toni-moreno** [comment]
Thank you very much for your explanation @Igalfaso.
