### ISSUE TITLE
Missing var declaration in function nodeLinkFn

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/angular.js#13521]
Minor fix possibly needed for the nodeLinkFn function of Angular v1.4.8. It appears that the "i" variable is not declared in this function, and thus is actually the same as declared in the applyDirectivesToNode function closure (ref. the "for" statement at line 7961). In other words, the "i" variable at line 8312 of the "Prelinking" code, and line 8333 of the "Postlinking code in nodeLinkFn, is the same variable as line 7961.
It doesn't seem to be a problem, as they are reset to new values in nodeLinkFn, but with so much going on in the applyDirectivesToNode function, it does raise the possibility that someday it might come back to haunt.

**Comment by lgalfaso** [comment]
Thanks for reporting this!
