### ISSUE TITLE
[$parse:lexerr] Lexer Error: Unexpected next character  at columns ... 

### ISSUE THREAD

**Issue by 4554** [angular/angular.js#13539]
angular suprisingly add , `&shy;` , keyword next to my angular expression like in photo. And the lexer exception thrown by the angular core, that like shown other photo
![screenshot_1](https://cloud.githubusercontent.com/assets/8876095/11790391/2df5225a-a2a4-11e5-8a4a-dede8178a6f9.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/8876095/11790393/2fdf7764-a2a4-11e5-9c76-6bda3e63fa19.png)

**Comment by lgalfaso** [comment]
A `&shy;` is a zero-length character used to tell word processors where it is legal to break a work and put an hyphen. Are you sure that the template you have does not contain this character?

**Comment by 4554** [comment]
sure. &shy; had generated automaticly.

**Comment by gkalpak** [comment]
@4554, I don't think this is Angular. Have you tried without Angular ? Could you create a live reproduction (e.g. using CodePen, Plnkr etc) or posting the raw template/html content ?

**Comment by 4554** [comment]
when ı pasted my code to plnker the point(red-in image) become placed uncertainly. how this can be, my html code does not exist this.  http://plnkr.co/edit/jkAi3RLnirMTATo4TpI6?p=preview
![screenshot_3](https://cloud.githubusercontent.com/assets/8876095/11810682/7e85dc0c-a338-11e5-9821-57fd77f251d8.png)

**Comment by gkalpak** [comment]
As @lgalfaso explained, this is probably some zero-length character that is not displayed by your editor (so you think it is not there in your HTML, but it is).

<sub>If you inspect the element in Developer Tools, you will notice that the ACE editor has recognized it as an invisible character (and marked it as `ace_invisible ace_invisible_space ace_invalid`).</sub>

Closing as this not related to Angular.
