### ISSUE TITLE
ngOptions duplicates when used with group by

### ISSUE THREAD

**Issue by cforycki** [angular/angular.js#13537]
Hi,

When using ngOptions with expression using group by, every option appears twice in select.
Bug was found in IE9/10/11, with angular 1.4.8. Was working with previous versions and doesn't seem to be fixed in 1.5.0.

Here's a plunker : http://plnkr.co/edit/#!/cItCfLj6UvwDumzqxZnk?p=preview

Best regards.

**Comment by Narretz** [comment]
Thanks for the report. This is already fixed and will be available in 1.4.9 and 1.5.0-rc.1
