### ISSUE TITLE
ngMock contains unannotated functions

### ISSUE THREAD

**Issue by bisubus** [angular/angular.js#13542]
ngMock contains unannotated functions, i.e.

https://github.com/angular/angular.js/blob/d67e999dfbdf47b79fdb3830a04f4f4010a98b98/src/ngMock/angular-mocks.js#L2527

https://github.com/angular/angular.js/blob/d67e999dfbdf47b79fdb3830a04f4f4010a98b98/src/ngMock/angular-mocks.js#L2652

This prevents `angular-mocks.js` from being minified.

The problem was conditional (`angular.mock.module({ mockedService: ... })` syntax was incompatible with minification before [this commit](https://github.com/angular/angular.js/commit/d67e999dfbdf47b79fdb3830a04f4f4010a98b98)), now it throws

> [$injector:modulerr] Failed to instantiate module function (e){l.$providerInjector=e} due to:
> Error: [$injector:unpr] Unknown provider: e
> http://errors.angularjs.org/1.5.0-beta.2/$injector/unpr?p0=e

unconditionally.

**Comment by Narretz** [comment]
Probably happens because ngMock isn't usually minified, because it should only run in tests, where minification isn't really needed. But we should probably fix it anyway.

**Comment by gkalpak** [comment]
Indeed I don't think it is intended to be minified. (In fact we are not producing a `angular-mocks.min.js` as part of our build.)
Why minify it ?

**Comment by szimek** [comment]
@gkalpak I just modified our Gulp file to prevent minification of `angular-mocks.js` as a workaround for this issue. Previously, we just added `angular-mocks.js` to a list of all external JS files (but only if `ENV === "test"`) that later all ended up as a single `vendor.js` file, which is loaded in `index.html`. It was just much easier to load it like this, especially for e2e tests.

**Comment by gkalpak** [comment]
OK, from a quick search, this has been brought up #3534 and #4448 before.

The last comment from @IgorMinar sums it up nicely, I think:

> [...] We have no way to test it right now, so if we break it in the future, we'll fix it when someone complains.

So, @szimek, did you just complain ? :smile:

**Comment by szimek** [comment]
@gkalpak I just wanted to explain why people minify it :smile:  I found a [workaround](http://reasoncodeexample.com/2015/10/03/loading-angular-mocks-js-as-a-mock-module-angular-integration-tests/) for it, so it's fine for me as it is, but I suspect there are a lot more people who just add `angular-mocks.js` to their standard pipeline that minifies everything and will complain later on :smile:

**Comment by bisubus** [comment]
@gkalpak It is rare scenario but it exists, I've experienced problems after 1.5.0-beta.2. I test [here](
https://github.com/ex-machine/ng-classified/blob/master/test/specs/minified.spec.es6.js#L11) that class detection will fail in transpiled and minified code on some condition, while it will pass on another condition. Without mgMock being fixed, I have to revise the way the specs are being bundled.

**Comment by gkalpak** [comment]
@bisubus, @szimek, could you try out this [angular-mocks.js][1] and see if it works for you ?

[1]: https://ci.angularjs.org/view/AngularJS%20Dev/job/angular.js-gkalpak/115/artifact/build/angular-mocks.js

**Comment by messo** [comment]
@gkalpak, we had the same issue as OP, and I have just tried your build and it is working for us :+1: Thanks! It would be nice to see this in 1.5.1

**Comment by gkalpak** [comment]
Thx, @messo, for the feedback. If it doesn't make it into `v1.5.1` it will sure make it into `v1.5.2` (but let's think positive :stuck_out_tongue: )
