### ISSUE TITLE
instanceof doesn't work for $q promises

### ISSUE THREAD

**Issue by thorn0** [angular/angular.js#13545]
```js
angular.module('app', []).run($q => {
  var promise = new $q(resolve => resolve());
  console.log(promise instanceof $q); // false
});
```

http://plnkr.co/edit/a6VE6z

So basically there is no way to check if an object is a $q promise.

**Comment by lgalfaso** [comment]
A promise can never be an instance of `$q` as that would imply that
* a promise has a method named `defer`, `reject`...
* `$q` has a method named `then`

When not sure if something is a promise or not, then the best option is to use `$q.when`

**Comment by thorn0** [comment]
No, in JS, "is instance of" doesn't mean what you have described. Angular introduced `$q.resolve` instead of `$q.when` for consistency with ES6, so it'd be logical to make `instanceof` work too since it works in ES6.

**Comment by lgalfaso** [comment]
`$q` follows Promises/A+ and this was based on Kris Kowal's Q. The first implementation of `$q` was well before ES6 Promise was a draft. It uses `when` and not `resolve` because that is what Kris Kowal's Q uses.


`$q` has some methods, these are specified at https://docs.angularjs.org/api/ng/service/$q and include `defer`, `reject` and others that currently are part of the `$q` prototype.

The object returned by `$q.defer` (that in the docs is referred as `Deferred` or `Promise`) has, in its prototype, the methods `then`, `finally` and `catch`.

Keeping things in the prototype reduces the memory pressure on something as critical as Promises.

With this information, can you please elaborate
> No, in JS, "is instance of" doesn't mean what you have described.

**Comment by thorn0** [comment]
It seems like you're confusing something here. `defer` and `reject` are not part of the `$q` prototype. They're methods of `$q` itself, static methods. Deferreds and Promises aren't the same. They're two different types. In particular, Deferreds don't have the methods `then`, `finally` and `catch`.

As for `instanceof`, here is how it usually works:

```js
var a = new Array();
console.log(a instanceof Array); // true
```

If we're creating something calling a constructor with the `new` keyword, we usually expect the created object to pass the check: `createdObject instanceof usedConstructor`. In particular, it works for ES6 Promises. From the fact `$q.resolve` and the ability to use `$q` as a constructor were implemented, I deduce that `$q` is supposed to be compatible with ES6 promises. And making `instanceof` work is an additional step towards this compatibility.

**Comment by fa137** [comment]
Am I missing something?
I am assigning y with a new constructor, but it still isn't an instanceof of x. 

http://plnkr.co/edit/wcRinNm59LUmYwRCZmr8?p=preview

**Comment by jbedard** [comment]
I think this makes sense. Currently `$Q` is not a proper constructor, even though it [attempts](https://github.com/angular/angular.js/blob/e57cf13d5da204a3324e8b083718c0dcfbb58207/src/ng/q.js#L569-L572) to be...

**Comment by thorn0** [comment]
@fa137 By using `return` in the constructor, you broke `instanceof` exactly the same way Angular did it with `$q`.

> The instanceof operator tests presence of constructor.prototype in object's prototype chain.

(from MDN)

**Comment by fa137** [comment]
@thorn0 Thanks for clearing it up! :+1: 

You are absolutely right then, we need a way to identify whether an object is a promise.

**Comment by thorn0** [comment]
@fa137 Your check doesn't really check if an object is a $q promise. It will as well pass for any promise implementation: jQuery, native ES2015, etc. Even when it comes just to Angular, we have two different kinds of promises here: `$q` and `$$q`. And what if we want to find out whether a promise in question is constructed with $q or with $$q?

**Comment by lgalfaso** [comment]
@thorn0 you are right, and this seams like a reasonable request
