### ISSUE TITLE
Tab is misspelled in `Advanced Component Communication` section

### ISSUE THREAD

**Issue by drewtunney** [angular/angular.js#13554]
In the Advanced Component Communication section in `index.jade` change 

### From:
"This allows tobs component to work with ngFor without any special knowledge of it." 

### To:
"This allows tab components to work with ngFor without any special knowledge of it."

**Comment by gkalpak** [comment]
Couldn't find that section, but since `ngFor` is involved, I assume this refers to either Angular 2 or http://angular.io.

This repository is for Angular 1. Please, reopen in either https://github.com/angular/angular or https://github.com/angular/angular.io.
