### ISSUE TITLE
html5 mode with mismatching base href causes "TypeError: Cannot read property 'replace' of undefined" error in location.js

### ISSUE THREAD

**Issue by jamlee1** [angular/angular.js#13565]
Looking at the latest version of location.js (https://github.com/angular/angular.js/blob/4412fe238f37f79a2017ee7b20ba089c0acd73e9/src/ng/location.js)

If the <base href="xxx"> tag does not match the actual href, $$parseLinkUrl will miss all the conditions and rewrittenUrl will not be defined, which means this.$$parse will not be called and $$absUrl will not be set.

Later on line 902 (https://github.com/angular/angular.js/blob/4412fe238f37f79a2017ee7b20ba089c0acd73e9/src/ng/location.js#L902), trimEmptyHash($location.absUrl()) will be called in a condition, which will end up having trimEmptyHash call .replace on undefined, so we end up halting with:

TypeError: Cannot read property 'replace' of undefined

**Comment by Narretz** [comment]
I'm not sure I understand the problem. In what case would the base tag not match the actual href?

**Comment by jamlee1** [comment]
In my case, the html was being served on multiple domains. Granted, we can correct that base url, but it still shouldn't cause a javascript error in angular.

**Comment by OverZealous** [comment]
I agree, this shouldn't cause an unknown error. This is happening to us, and we couldn't see it until production, and it simply killed the page.  Having such a low-level JS error seems like something that should have feedback.

(It was a weird case in our situation, a production-only url rewrite that triggered an error.)

**Comment by gkalpak** [comment]
Should be fixed by #14488.
