### ISSUE TITLE
hidden routeChangeError

### ISSUE THREAD

**Issue by charlierudolph** [angular/angular.js#13563]
I am lazy loading some css/js. I ran into a case where the page wasn't loading and I saw no error in my console.

``` js
$routeProvider.when("/my/route", {
  templateUrl: "/my/template.html",
  resolve:  {
    load: function () {
      return "<a promise>"
    }
  }
});
```

If the promise returned by my load function rejects, it triggers a routeChangeError. However, if I don't have anything listening on routeChangeError, then the error just stops my page flow and I see no error to let me know why.

If there is a routeChangeError and there are no listeners, I would appreciate it if angular just logged the error to the console.

**Comment by Narretz** [comment]
Sounds reasonable. I would say we can log a debug message. PRs welcome!

**Comment by gkalpak** [comment]
A thought:

While it may sound reasonable, it is inconsistent with how we handle other errors (e.g. `$locationChangeError`), which will also be confusing.

**Comment by Narretz** [comment]
As @gkalpak has noted (see also https://github.com/angular/angular.js/pull/13575#issuecomment-266859928), logging an error here is inconsistent with our error logging, so I'm going to close this
