### ISSUE TITLE
jqLite.element.off removes all events on falsy event name

### ISSUE THREAD

**Issue by matsko** [angular/angular.js#13571]
When the `elemento.off` method is invoked in jqLite with a null or empty string value as the first param it removes all the events off of the element.

``` js
var elm = angular.element(...);
elm.on('click', fn);
elm.on('input', fn2);

// these guys remove everything
elm.off('', fn);
elm.off(null, fn);
```

The functionality of jqLite should match that of jQuery. Either jqLite doesn't do anything if `arguments.length >= 1` or it only removes events that contain a handler that matches the provided function.

**Comment by Narretz** [comment]
jQuery isn't consistent with this either:
http://plnkr.co/edit/DaZKbPrmZzJSCtiSh89y?p=preview

`''` removes everything, `null` doesn't

**Comment by gkalpak** [comment]
I believe @matsko is talking about the case where `off()` has a second argument (`fn`).
In that case, jQuery will remove all listeners having `fn` as the callback.
jqLite will [remove all listeners][1] (essentially ignoring `fn`).

We should definitely be compatible with jQuery.

[1]: http://plnkr.co/edit/DaZKbPrmZzJSCtiSh89y?p=preview

**Comment by Narretz** [comment]
Yes, you are right. I read it wrong.
Am 18.12.2015 13:58 schrieb "Georgios Kalpakas" <notifications@github.com>:

**Comment by mgol** [comment]
Neither `.off(null, fn)` nor `.off('', fn)` is documented at https://api.jquery.com/off/ which means those usages are unsupported.

That said, it looks useful so I'll try to fix the jQuery docs first and then add it to jqLite.

**Comment by mgol** [comment]
Now that I look at it it doesn't look so good & intuitive. A `null` or an empty string parameter looks like a hack. It is useful to be able to remove all event handlers from an element and jQuery [supports that](https://api.jquery.com/off/) via a parameterless `.off()` but I don't see lots of use cases for removing all event handlers for all events matching a particular listener.

I don't think it's something we'll standardize in jQuery so I'm closing this ticket.
