### ISSUE TITLE
Issue on Microsoft Edge when changing items in a bound list in a Form.

### ISSUE THREAD

**Issue by aseemflowingly** [angular/angular.js#13573]
I have a list of users bound to div tag as below:

Angular controller:

    groupctrlr.model = {
            formState: {}
        };

The cshtml markup as:

    <form class="card" name="addCtrl.currentForm" ng-app="app.group" ng-  controller="AddGroupController as addCtrl" ng-init="addCtrl.activate()" method="POST" novalidate ng-cloak>
    <div class="row title">
    <div class="col s12">
    <h4>Create Group</h4>
    </div>
    </div>
    <div class="content" >
    <div class="row">
     
    <div class="col m5 s12 offset-s0">
    <div class="row" ng-show="addCtrl.model.formState.Users.length>0">
    
    <div class="col m10 s12 table-responsive">
    <table class="table table-bordered">
    <thead>
    <tr>
    <th>Name</th>
    <th>Department name</th>
    <th>Email</th>
    <th></th>
    </tr>
    </thead>
    <tbody>
    <tr ng-repeat="selectedUser in addCtrl.model.formState.Users">
    <td>{{selectedUser.FullName}}</td>
    <td>{{selectedUser.DepartmentName}}</td>
    <td>{{selectedUser.Email}}</td>
    <td>
    <button type="button" ng- click="addCtrl.removeUser($index)"></button></td>
    </tr>
    </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    <div class="row">
    <div class="input-field col s6 offset-s0" >
    <a class="" ng-click="addCtrl.cancelAddGroup()">Cancel</a>
    <button type="submit"  ng-click="addCtrl.addGroup()" ng-disabled="addCtrl.currentForm.$invalid">
    <i class="mdi-content-save"></i>
    &nbsp;Save
    </button>
    </div>
    </div>
    </div>
    </form>

The error scenario is:
1. Open this page.
2. Add a user to this list, which gets displayed.
3. Remove the user from this list.
4. Click on the save button.
5. The ng-click event does not fire the method right away.
6. Wait for a second or so, and click the "Save" button, the click event works fine.

All of this works fine on Chrome, Firefox and Safari.

Is this specific to Edge? Any ideas how I can get around this problem?

**Comment by Narretz** [comment]
Can you please put a demo in a plnkr.co or similar?

**Comment by Narretz** [comment]
Closing because we don't have a demo.
