### ISSUE TITLE
Anchor tag helper not working when angular binding

### ISSUE THREAD

**Issue by jaganjan** [angular/angular.js#13582]
look at this thread http://stackoverflow.com/questions/34353425/anchor-tag-helper-not-working-in-mvc-6-and-angular-js

**Comment by Narretz** [comment]
This looks like a problem with MVC6. I don't think angular is doing something wrong here. As a support question, the right place for it is Stackoverflow, so I'm closing this,

**Comment by MaximRouiller** [comment]
Not a problem with MVC 6. Or with AngularJS for that matter. 

Client-side code is being used in Server side code that generates URL. It's a problem in usage.
