### ISSUE TITLE
Angularjs ng change is not triggering in Firefox

### ISSUE THREAD

**Issue by Jeevanandanj** [angular/angular.js#13585]
I am using the ng-change for select.

This is working fine in my application. But when I test in firefox, the ng change is not triggering. Is this the bug from angular? Do I do anything wrong?

For the simple program it's working in the plnkr. But in my large application, this is not trigger.

Do I need to do any modification specially for this?

**Comment by Narretz** [comment]
It's impossible to say what the problem is without a running demo. Please try to reproduce the problem and then re-open this issue. Thanks!

**Comment by Jeevanandanj** [comment]
That is browser issue not from angular.

In firefox, if select is inside the anchor then the issue will come. Sorry for the wrong post.
