### ISSUE TITLE
$q.all seems to be modifying values in key value pair

### ISSUE THREAD

**Issue by zyzzyx88** [angular/angular.js#13586]
```
var promises = queryIds.map(function(queryId) {
      return Results.get(queryId, payer, practice, time,insurance).then(function(data) {
        ctrl.scoreData[queryId] = data;
      }); 
    });
    $q.all(promises).then(function() {
      ctrl.isWaiting = false;
    });
```

in the above code the data object has a set of key value pairs. When printing to the console we can see  that all values are correct for each item in ctrl.scoreData. When showing ctrl.scoreData in the $q.all, any -1 values are changed to null. Not sure why.

**Comment by Narretz** [comment]
can you please put an example in a plnkr.co etc.?

**Comment by Narretz** [comment]
Closing due to lack of feedback.
