### ISSUE TITLE
Error: [$parse:syntax] Syntax Error: Token ':' not a primary expression for filter option

### ISSUE THREAD

**Issue by poshest** [angular/angular.js#13595]
I want to use a one time binding on a filter option, eg 

```
{{ vm.unixDateNumber | date : ::vm.customDateFormat }}
```

but I get `Error: [$parse:syntax] Syntax Error: Token ':' not a primary expression for filter option...`.

The `vm.unixDateNumber` can change (so I don't want it to be bound once), but the `vm.customDateFormat` will not.

**Comment by lgalfaso** [comment]
you cannot pick and choose, within one expression, what is one-time and what is not. In this case, an interpolation is one expression and only one expression

**Comment by poshest** [comment]
Well, yes, that is the way it is now.  I forgot to mention this was a feature request, not a bug report! :)

**Comment by lgalfaso** [comment]
@poshest allowing for any part of an expression to be one-time binding would be a large effort and would imply the definition of a prefix operator `::`. This would imply that this operator would need a priority. Eg the expression `::foo.bar()` can have any of the following possible, all valid, valuations `(::foo).bar()`, `(::(foo.bar))()` or `::(foo.bar())` with all its consequences. Keeping an internal state and possible performance implications.


This is, without a clear use case that such feature would enable or that working with the existing mechanism involves a substantial amount of work, then it is not clear what benefits this syntax provides or justifies the amount of work

**Comment by poshest** [comment]
Well, I wasn't suggesting you would be able to put :: anywhere the way you suggest.  Just at the start of major segments of common expressions like the date filter `{{ date_expression | date : format : timezone}}`, the way ng-repeat can understand the :: placed before the array `ng-repeat="item in ::items"`.  

But look, if it's lots of work or causes degradation in performance I'm in full agreement about closing this issue.
