### ISSUE TITLE
ng-options should support datalist

### ISSUE THREAD

**Issue by twwwt** [angular/angular.js#13596]
Seems that the ng-options directive does not support \<option\> elements inside a \<datalist\> element. It would be great if ng-options could be extended.

Since an option inside a datalist (i) may not contain a label text (only a value attribute), (ii) may not contain \<optgroup\> elements, nor (iii) (multiple) selected options, the comprehension expression would consequently be simpler; something like
    `value in array` for array data sources, and
    `(k, v) in object` for object data sources.

Using this syntax for object data sources, it is not clear whether to render `k` or `v` into an option´s value attribute. Therefore, I propose the following syntax to make that clear:

    `(k, _) in object` // render `k` as the value attribute value
    `(_, v) in object` // render `v`  as the value attribute value

where `_` is a kind of a anon variable indicating the part that is not used.

**Comment by Narretz** [comment]
ngOptions isn't supposed to work with options that are already inside the select. When using ngOptions, the options always come from the scope. Can you show an example of what you are trying to achieve?

**Comment by twwwt** [comment]
```html
<input type="text" list="colors">
<datalist id="colors" ng-options="color in myColorsArray">
   <!-- render each color name a an option element here -->
</datalist>
```

**Comment by Narretz** [comment]
Ah now I see. Yes, that sounds like a worthwhile addition. Is this
something you'd like to work on?
Am 21.12.2015 14:13 schrieb "Thorsten Möller" <notifications@github.com>:

**Comment by twwwt** [comment]
Well, before raising this feature request, I was actually checking the code of the ng-options directive whether I could do that. I would have done it, if it would have been within the amount of time I can currently spend for this extension. What was actually surprising is that the directive is rather large, and I did not easily understand all that stuff within 15min or so, sigh.

**Comment by Narretz** [comment]
Yes the ngOptions directive is pretty complex. Actually it might be a
better idea to create a new datalist directive that behaves similar to
ngOptions. Then, we could still decide to integrate it.
Am 21.12.2015 15:19 schrieb "Thorsten Möller" <notifications@github.com>:

**Comment by Narretz** [comment]
Marking this as "not core"
