### ISSUE TITLE
Directive's controller setter called before class instantiation (view attributes assigned before initialization)

### ISSUE THREAD

**Issue by CodySchaaf** [angular/angular.js#13590]
This seems to be intentional in order to allow access to bound variables during a directive's controller instantiation, but it is really unintuitive.

As you can see in this [codepen](http://codepen.io/codyschaaf/pen/jWWPEq) this can cause issues with variables that should have been instantiated in the constructor not being available when a method is called. 

Basically in my situation we have a controller that needs to notify its link function when a bound variable is changed (widget.title), to do this I set up a setter for the variable that calls notify when it is called. 

So the parent directive can change the title, then the setter is called which notifies the widget's link function. Although since the parentDir changes the title in it's constructor we get a console error where notify is called before the array of subscribers is set up. You can uncomment the code to see the order of the console logs. This code would allow my version to work, although it would end up masking other issues. 

The code responsible for this is [here](https://github.com/angular/angular.js/blob/d077966ff1ac18262f4615ff1a533db24d4432a7/src/ng/controller.js#L117)

Following this pattern:

``` ts
var instance = Object.create(directiveDefinition.controller.prototype);

instance.widgetTitle = "New Title"

directiveDefinition.controller.apply(instance);
```

Is there an existing pattern for getting around this issue? Seems sort of like a bug, although it would probably require a pretty big breaking change that would make a lot of people angry.

**Comment by gkalpak** [comment]
Indeed this seems to be an unwanted side-effect of our way of instantiating controllers with bindings.
Unfortunately, "fixing" this would break other (much more common) usecases, as you already mentioned.

So, I'm afraid we'll have to stick with the current implementation and people using setters with side-effects should handle this "manually" (unless someone can come up with a clever work-around).

**Comment by Narretz** [comment]
Since 1.6, the bindings are after the controller's constructor is called, which should resolve this issue.
