### ISSUE TITLE
input[type="email"] does not properly fire ng-change handler

### ISSUE THREAD

**Issue by krassx** [angular/angular.js#13600]
Not sure why, but it just does nothing. Here is plunker to reproduce it: http://plnkr.co/WCBTW3JKJcPlLRM32wD2

I am trying it in Chrome 47.0.2526.106. When I use [type="text"] everything works just fine, unlike with "email".

**Comment by Narretz** [comment]
ng-change only fires when the model of the input changes. And the model is only set if the input is valid, unless you set ngModelOptions.allowInvalid (https://code.angularjs.org/1.5.0-rc.0/docs/api/ng/directive/ngModelOptions)
