### ISSUE TITLE
bug in scope.$last

### ISSUE THREAD

**Issue by uxitten** [angular/angular.js#13601]
hi
i use this code for run function after finish angularjs process in view

```javascript
myApp.directive('ngFinishRender', function ($timeout) {
    return {
        restrict: 'A',
        link: function (scope, element, attr) {
            if (scope.$last === true) {
                $timeout(function () {
                    scope.$eval(attr.ngFinishRender);
                }, 0);
            }
        }
    }
});
```

but sometimes scope.$last value is false, but angularjs process is finished

**Comment by Narretz** [comment]
There is no guarantee that ngRepeat is finished when your directive's link function is executed. I assume that's the problem. It could also be an issue with directive priorities. Can you please post a demo that shows the problem?  Otherwise it's very hard to say.

**Comment by uxitten** [comment]
hi Martin Staffa
thank's  for quick response
this picture demo of bug
1 click undo button for a action
2 element add in view
3 scope.$last = false

![bug](https://cloud.githubusercontent.com/assets/1549069/11949198/6bcf0a20-a874-11e5-873d-6d33dbc5c455.jpg)

but sometimes work!!!

**Comment by gkalpak** [comment]
@uxitten, it is still not possible to say what is going on without seeing some actual code.
If I had to guess, I'd say the item added is not always the last element in the repeated list.

**Comment by uxitten** [comment]
ok how understand finish render? when add or remove in middle list?

**Comment by Gennady77** [comment]
I can't find $last property in documentation

**Comment by gkalpak** [comment]
@uxitten, it is not supported "out-of-the-box". There are ways to do it, but it varies on the usecase and implementation details. (E.g. if you don't need to make requests for templates, wrapping something in a `$timeout` may be sufficient.) It really depends on the elements you are creating (what directives they have on them, and what nested directives may exist on those directives' templates etc).

I suggest you create a concrete demo of your usecase (providing actual code - preferrably a live demo using CodePen, Plnkr etc) and post it on one of the [support channels][1].

Closing this, as it works as expected.
<sub>Feel free to re-open if you find an actual bug in Angular or want to request a new feature (that's not already requested).</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by gkalpak** [comment]
@Gennady77, `$last` is a property added for cenvenience by the `ngRepeat` directive.
You can read more about it in [the `ngRepeat` docs][1].

[1]: https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by uxitten** [comment]
this demo in codepen

http://codepen.io/itten/pen/yeJKGK  - automatic!
[GitHub](http://codepen.io/itten/pen/yeJKGK )

**Comment by lgalfaso** [comment]
`scope.$last` is true when this is the last element of the list, not when it is looping over the last element it needs. When elements are added in the middle of the list, then when adding the DOM nodes, the last element added will have `scope.$last === false` even when this is the last element added (it was added last, but it was added in the middle of the list)

**Comment by gkalpak** [comment]
@uxitten, for the simple example in your demo (i.e. no template requests, no nested directives etc), it is sufficient to simply debounce the call to your callback until after the current rendering phase (as shown in this [demo][1]).
But, let me stress again, that this naive implementation might not be sufficient in a more complex scenario.

[1]: https://codepen.io/ExpertSystem/pen/XXKqqr?editors=101

**Comment by uxitten** [comment]
ok i a idea for this problem and tested work :)

```javascript
myApp.directive('ngFinishRender', function ($timeout) {
    var timeoutID = [];
    return {
        restrict: 'A',
        link: function (scope, element, attr) {
            $timeout.cancel(timeoutID[attr.ngFinishRenderIndex]);
            timeoutID[attr.ngFinishRenderIndex] = $timeout(function () {
                scope.$eval(attr.ngFinishRender);
            }, attr.ngFinishRenderLength * 1.5);    // remainig time
        }
    }
});
```

thank's all AngularJS team

**Comment by NicolasEckell** [comment]
@behnammodi  I was looking for this solution. The fact that i need this is because i cannot $watch after filter is applied con ng-repeat, cuz it collapses in large tables size. I use scope.$emit(attr.ngFinishRender) instead of $eval to fire a broadcast message to the controller. Thank you!

**Comment by behnammodi** [comment]
@NicolasEckell You're welcome, It's about 5 years ago and I don't remember anything about this, however thanks 🙏🏻
