### ISSUE TITLE
module.component should restrict to 'AE' by default

### ISSUE THREAD

**Issue by davidreher** [angular/angular.js#13603]
Hey,

I tried using the new 1.5 component router and component api. While doing this I created my components without an explicit restrict attribute. [The loader restricts them to 'E' by default](https://github.com/angular/angular.js/blob/master/src/loader.js#L426). 

The component router (for angular1?) creates new components [via attributes syntax](https://github.com/angular/angular/blob/master/modules/angular1_router/src/ng_outlet.ts#L158).

Please change the default restriction to 'AE' or change the component router ;)

**Comment by fesor** [comment]
I think that this is issue of angular/router rather that angular. Components should be only elements (by default).

**Comment by davidreher** [comment]
I just saw, that [pull request 5278](https://github.com/angular/angular/pull/5278) fixes this issue ... Hope it gets merged soon ;)

**Comment by Narretz** [comment]
Please don't close the issue, this is usually where most of the discussion happens.

**Comment by davidreher** [comment]
Hmm, I thought it would be best to not have this discussion in multiple threads (here, in the angular2 repo bug and the pull request) ...

**Comment by petebacondarwin** [comment]
Components should be E only - we need to fix the router.
