### ISSUE TITLE
Favicon is not appearing on firefox browser for Angular js templates

### ISSUE THREAD

**Issue by bsurendrakumar** [angular/angular.js#13610]
Here is my code snippet how I am including the favicon in my personal website which was built with Angular JS.

```html
<link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico"/>
```

With this code, the favicon is appearing on Chrome and IE browsers. But the favicon is not appearing for Angular JS templates on Firefox browser.

Thanks.

**Comment by bsurendrakumar** [comment]
I looked at the similar websites made with Angular JS, the same issue is repeated.

https://www.madewithangular.com/#/

**Comment by martinoppitz** [comment]
I think this is no angular specific problem. Because there are just one favicon on the side and it makes no sense to build it into the app.

**Comment by gkalpak** [comment]
I agree with @martinoppitz. This shouldn't be Angular specific. @bsurendrakumar, can you get the same icon work on FF without Angular ?

**Comment by Narretz** [comment]
Closing due to lack of feedback.

**Comment by synotna** [comment]
We are encountering exactly the same bug as https://www.madewithangular.com/ due to the same technique

Go to http://play.eslgaming.com/intern/test/hearthstone/open/1on1/therogue-swiss-15/rankings/ , Angular changes to http://play.eslgaming.com/intern/test/hearthstone/open/1on1/therogue-swiss-15/rankings/#!?page=1 : favicon broken

Go directly to http://play.eslgaming.com/intern/test/hearthstone/open/1on1/therogue-swiss-15/rankings/#!?page=1 (or simply f5 from before): favicon is fine

Does not occur in Chrome/IE, so is something between Angular/Firefox

**Comment by synotna** [comment]
Trying to research further, I suspect it's really a Firefox bug, not sure if Angular can workaround it, or pressure Firefox to fix it

http://stackoverflow.com/questions/24185506/using-history-pushstate-in-firefox-make-my-favicon-disappear

https://bugzilla.mozilla.org/show_bug.cgi?id=408415

**Comment by gkalpak** [comment]
@Narretz, should this be closed (since it seems to be a browser issue) ?

**Comment by Narretz** [comment]
Not sure. It seems to affect Angular apps in higher numbers due to hashbang routing.
Btw, does this workaround work: http://stackoverflow.com/a/25873321/787333?

Feel free to close. I think what we all can do is vote on this bug and maybe leave a comment.

**Comment by synotna** [comment]
Our initial tests show yes, we'll probably do that if it's not otherwise solved :)

**Comment by gkalpak** [comment]
Closing as it is a browser bug (meaning we can't really do anything) and there is a workaround.

**Comment by Narretz** [comment]
Nice, this was fixed in FF: https://bugzilla.mozilla.org/show_bug.cgi?id=408415

**Comment by synotna** [comment]
Hurrah, thanks for informing!

**Comment by m-key** [comment]
@synotna
Which version of FF you're testing on? Doesn't work for me, on FF 41.0.2, latest to date.

**Comment by synotna** [comment]
It's fixed in FF 47 (aurora at the moment iirc)

Current FF is 44 :)
