### ISSUE TITLE
AngularJs locale (i18n)

### ISSUE THREAD

**Issue by mrlarssen** [angular/angular.js#13612]
In i18n, the short date format for en-us is:

    "short": "M/d/yy h:mm a"

while the short date format for e.g nb-no (norwegian) is:

    "short": "dd.MM.y HH.mm"

Why is there a difference in the way year (y) is represented. Shouldnt both be yy ?

**Comment by kukac7** [comment]
@mrlarssen https://docs.angularjs.org/api/ng/filter/date

**Comment by lgalfaso** [comment]
https://github.com/angular/angular.js/issues/13612#issuecomment-166651658 is spot on
