### ISSUE TITLE
$q Promise API chaining behavior

### ISSUE THREAD

**Issue by phsstory** [angular/angular.js#13613]
I may or may not be reading the spec https://promisesaplus.com/#point-64 2.3.4 correctly, but I my interpretation suggests these is a bug in the chaining logic.

2.3.4 suggests that in a chain, if the resolved or rejected callback do not return a value, the next in the chain should be resolved or rejected with the original value in turn.

Please see http://plnkr.co/edit/9Di1pjjcPdTZI7FsXID3?p=preview as an example

The only other option i see is the undefined behavior state in the spec involving 2.2.7.1 where neither onFilfilled nor onRejected returns a value, but in such a situation, I feel the specificity of 2.3.4 supersedes the undefined behavior.

If this ticket is deemed not a bug, I would suggest updating the docs to mention that all onFulfilled or onRejected callbacks should, at the least, return the original result

**Comment by lgalfaso** [comment]
A function that has no `return` statements and ends its execution normally (this is without throwing an exception) returns an implicit `undefined`. The behavior of the result of
```js
somePromise.then(functionA, functionB)
```

https://promisesaplus.com/#point-40

The current behavior is the correct.

There are many things that can be added to the docs, in this specific case we can include the entire spec, but I still think it is best to have a reference to it.

**Comment by phsstory** [comment]
@lgalfaso would you also say the rejected resolved chain

```
var deferred = $q.defer();
deferred.promise.then(
  resolved = function() { console.log('resolved'); },
  rejected = function() { console.log('rejected'); }
).then( resolved, rejected);
deferred.reject(); // first then: rejected, second then: resolved NOT rejected
```

is behaving properly?

**Comment by lgalfaso** [comment]
Yep, check

https://promisesaplus.com/#point-41

And

https://promisesaplus.com/#point-44

This second link is only important if in the first `then` you put
`undefined` as a parameter.

$q passes the Promise/A+ compliance test (that is very strict and
everything is the spec is checked)
