### ISSUE TITLE
Cannot get $event from ng-click or ng-change in Firefox

### ISSUE THREAD

**Issue by kevin031612** [angular/angular.js#13628]
When I used ng-change or ng-click to listen a checkbox, the function can not get the event( whether I pass $event or not). The code is : 
HTML
```
<input type="checkbox" ng-change="SendList.oListen.fnCheckHead($event)" ng-model="SendList.oListen.checkHead[career.career_id]" />
```
JS
```javascript
   $scope.SendList.oListen.fnCheckHead:function(ev){
                var oEvent = ev||window.event;             //ev=>undefined, oEvent=>undefined
                var self = oEvent.target||oEvent.srcElement;
            }
```
And when i use onclick and onchange without angularJS, I can easily get the event by passing the parameter "event".
So please tell me how to get the event of ng-* in Firefox. 
Thank you.

**Comment by wesleycho** [comment]
ng-change is not an evented directive - one cannot get the event from there. It is an expression that is executed when the model changes from a view value change.

**Comment by Narretz** [comment]
@wesleycho is right. Thanks for answering!
