### ISSUE TITLE
Declare routes inside controller

### ISSUE THREAD

**Issue by danielemontesi** [angular/angular.js#13622]
Is possible to declare routes inside controller? How can i do? Thanks

**Comment by martinoppitz** [comment]
I think, that is not a good idea.

In which case the controller will be running?

The route should be defined only one time!

**Comment by danielemontesi** [comment]
i need to create conditional routes

**Comment by martinoppitz** [comment]
Do you have a finite number of routes? then define all routes in the config section and control the routing via the $routeChangeStart-Event.

**Comment by Narretz** [comment]
This is currently not possible. The new angular/router has the option to register routes at runtime, however. Docs are not yet available, though.
