### ISSUE TITLE
phonecat setup instructions seems to be out of date

### ISSUE THREAD

**Issue by JoeKahl** [angular/angular.js#13623]
First of all, I am a Visual Studio / .NET MVC / jQuery / Chrome developer and I am new to node and npm and git.  
I want and need to learn to develop with angularjs and I have the patience to dig in and succeed but the phonecat application set up instructions are not working for me.

Initially, I am having problems setting up phonecat.  I cannot run git due to certificate problem:

C:\WebProjects>git clone --depth=14 https://github.com/angular/angular-phonecat.git

Cloning into 'angular-phonecat'...
fatal: unable to access 'https://github.com/angular/angular-phonecat.git/': SSL certificate problem: self signed certificate in certificate chain

My workaround, in which I have little confidence, except that it did download a lot of files including the package.json:
C:\WebProjects>git -c http.sslVerify=false clone --depth=14 https://github.com/angular/angular-phonecat.git

Then npm failed, looking for python which I do not have and is not mentioned as a prerequisite in the instructions.

I got a lot of messages about the wrong versions.  The warnings are unnecessary because I have much newer versions than these very old instructions.

C:\WebProjects\angular-phonecat>npm installnpm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.2.3","npm":"2.14.7"})

Why is this code so old that it is looking for version 0.x and I have version 4.x?
Had the same warnings with node looking for version 0.x and I have 4.x.

> angular-phonecat@0.0.0 postinstall C:\WebProjects\angular-phonecat
> bower install
bower SELF_SIGNED_CERT_IN_CHAIN      Request to https://bower.herokuapp.com/packages/jquery failed: self signed certificate in certificate chain

I received a bunch of errors like this and I feel discouraged and I am not going to continue with the phonecat tutorial.

Not being experienced with node and npm and python this is surprising, confusing and disappointing.  
It makes me think that the phonecat sample app is too old to bother with.  Please either update phonecat or replace it.

I am not having a good user experience setting up phonecat with these challenges.  
I wish someone would test these instructions and update them.

Sincerely, Joe Kahl

**Comment by JoeKahl** [comment]
C:\WebProjects\angular-phonecat>npm install

> angular-phonecat@0.0.0 postinstall C:\WebProjects\angular-phonecat
> bower install

bower SELF_SIGNED_CERT_IN_CHAIN      Request to https://bower.herokuapp.com/packages/angular-mocks failed: self signed certificate in certificate chain

npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\WebProjects\angular-phonecat\npm-debug.log

C:\WebProjects\angular-phonecat>bower -c install 'bower' is not recognized as an internal or external command, operable program or batch file.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose readDependencies loading dependencies from C:\WebProjects\angular-phonecat\package.json
5 verbose install where, deps [ 'C:\\WebProjects\\angular-phonecat',
5 verbose install   [ 'karma',
5 verbose install     'karma-chrome-launcher',
5 verbose install     'karma-firefox-launcher',
5 verbose install     'karma-jasmine',
5 verbose install     'protractor',
5 verbose install     'http-server',
5 verbose install     'tmp',
5 verbose install     'bower',
5 verbose install     'shelljs' ] ]
6 verbose install where, peers [ 'C:\\WebProjects\\angular-phonecat', [] ]
7 verbose installManyTop reading for lifecycle C:\WebProjects\angular-phonecat\package.json
8 info preinstall angular-phonecat@0.0.0
9 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\bower\package.json
10 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\http-server\package.json
11 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\karma\package.json
12 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\karma-chrome-launcher\package.json
13 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\karma-firefox-launcher\package.json
14 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\karma-jasmine\package.json
15 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\protractor\package.json
16 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\shelljs\package.json
17 verbose installManyTop reading scoped package data from C:\WebProjects\angular-phonecat\node_modules\tmp\package.json
18 info package.json http-server@0.6.1 No license field.
19 info package.json shelljs@0.2.6 No license field.
20 info package.json tmp@0.0.23 No license field.
21 verbose readDependencies loading dependencies from C:\WebProjects\angular-phonecat\package.json
22 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\bower\package.json
23 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\http-server\package.json
24 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\karma\package.json
25 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\karma-chrome-launcher\package.json
26 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\karma-firefox-launcher\package.json
27 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\karma-jasmine\package.json
28 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\protractor\package.json
29 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\shelljs\package.json
30 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\tmp\package.json
31 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\bower\package.json
32 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\bower.cmd\package.json
33 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\http-server\package.json
34 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\http-server.cmd\package.json
35 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\karma\package.json
36 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\karma.cmd\package.json
37 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\protractor\package.json
38 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\protractor.cmd\package.json
39 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\shjs\package.json
40 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\shjs.cmd\package.json
41 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\webdriver-manager\package.json
42 verbose targetResolver reading package data from C:\WebProjects\angular-phonecat\node_modules\.bin\webdriver-manager.cmd\package.json
43 verbose already installed skipping protractor@^2.1.0 C:\WebProjects\angular-phonecat
44 verbose already installed skipping http-server@^0.6.1 C:\WebProjects\angular-phonecat
45 verbose already installed skipping tmp@0.0.23 C:\WebProjects\angular-phonecat
46 verbose already installed skipping bower@^1.3.1 C:\WebProjects\angular-phonecat
47 verbose already installed skipping shelljs@^0.2.6 C:\WebProjects\angular-phonecat
48 verbose already installed skipping karma@^0.12.16 C:\WebProjects\angular-phonecat
49 verbose already installed skipping karma-chrome-launcher@^0.1.4 C:\WebProjects\angular-phonecat
50 verbose already installed skipping karma-firefox-launcher@^0.1.3 C:\WebProjects\angular-phonecat
51 verbose already installed skipping karma-jasmine@~0.1.0 C:\WebProjects\angular-phonecat
52 silly install resolved []
53 info build C:\WebProjects\angular-phonecat
54 info linkStuff angular-phonecat@0.0.0
55 silly linkStuff angular-phonecat@0.0.0 has C:\WebProjects as its parent node_modules
56 verbose linkBins angular-phonecat@0.0.0
57 verbose linkMans angular-phonecat@0.0.0
58 verbose rebuildBundles angular-phonecat@0.0.0
59 verbose rebuildBundles [ '.bin',
59 verbose rebuildBundles   'bower',
59 verbose rebuildBundles   'http-server',
59 verbose rebuildBundles   'karma',
59 verbose rebuildBundles   'karma-chrome-launcher',
59 verbose rebuildBundles   'karma-firefox-launcher',
59 verbose rebuildBundles   'karma-jasmine',
59 verbose rebuildBundles   'protractor',
59 verbose rebuildBundles   'shelljs',
59 verbose rebuildBundles   'tmp' ]
60 info install angular-phonecat@0.0.0
61 info postinstall angular-phonecat@0.0.0
62 verbose unsafe-perm in lifecycle true
63 info angular-phonecat@0.0.0 Failed to exec postinstall script
64 verbose stack Error: angular-phonecat@0.0.0 postinstall: `bower install`
64 verbose stack Exit status 1
64 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
64 verbose stack     at emitTwo (events.js:87:13)
64 verbose stack     at EventEmitter.emit (events.js:172:7)
64 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
64 verbose stack     at emitTwo (events.js:87:13)
64 verbose stack     at ChildProcess.emit (events.js:172:7)
64 verbose stack     at maybeClose (internal/child_process.js:818:16)
64 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
65 verbose pkgid angular-phonecat@0.0.0
66 verbose cwd C:\WebProjects\angular-phonecat
67 error Windows_NT 6.1.7601
68 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
69 error node v4.2.3
70 error npm  v2.14.7
71 error code ELIFECYCLE
72 error angular-phonecat@0.0.0 postinstall: `bower install`
72 error Exit status 1
73 error Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
73 error This is most likely a problem with the angular-phonecat package,
73 error not with npm itself.
73 error Tell the author that this fails on your system:
73 error     bower install
73 error You can get their info via:
73 error     npm owner ls angular-phonecat
73 error There is likely additional logging output above.
74 verbose exit [ 1, true ]

**Comment by JoeKahl** [comment]
$ cd C:/WebProjects/angular-phonecat

$ bower install
bower angular#1.4.x         not-cached git://github.com/angular/bower-angular.git#1.4.x
bower angular#1.4.x            resolve git://github.com/angular/bower-angular.git#1.4.x
bower angular-route#1.4.x   not-cached git://github.com/angular/bower-angular-route.git#1.4.x
bower angular-route#1.4.x      resolve git://github.com/angular/bower-angular-route.git#1.4.x
bower jquery#~2.1.1         not-cached git://github.com/jquery/jquery.git#~2.1.1
bower jquery#~2.1.1            resolve git://github.com/jquery/jquery.git#~2.1.1
bower bootstrap#~3.1.1      not-cached git://github.com/twbs/bootstrap.git#~3.1.1
bower bootstrap#~3.1.1         resolve git://github.com/twbs/bootstrap.git#~3.1.1
bower angular-mocks#1.4.x   not-cached git://github.com/angular/bower-angular-mocks.git#1.4.x
bower angular-mocks#1.4.x      resolve git://github.com/angular/bower-angular-mocks.git#1.4.x
bower angular-animate#1.4.x not-cached git://github.com/angular/bower-angular-animate.git#1.4.x
bower angular-animate#1.4.x    resolve git://github.com/angular/bower-angular-animate.git#1.4.x
bower angular-resource#1.4.x       not-cached git://github.com/angular/bower-angular-resource.git#1.4.x
bower angular-resource#1.4.x          resolve git://github.com/angular/bower-angular-resource.git#1.4.x
bower angular-mocks#1.4.x             ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-mocks.git", exit code of #128 fatal: read error: Invalid argument

Additional error details:
fatal: read error: Invalid argument

**Comment by Narretz** [comment]
Node and npm only very recently moved to versions beyond 0.12. So yes, it's possible that your problems come from these new versions. We need to investigate this.

**Comment by wangxiank** [comment]
bower angular-mocks#1.4.x   not-cached git://github.com/angular/bower-angular-mo                  cks.git#1.4.x
bower angular-mocks#1.4.x      resolve git://github.com/angular/bower-angular-mo                  cks.git#1.4.x
bower angular-resource#1.4.x       not-cached git://github.com/angular/bower-ang                  ular-resource.git#1.4.x
bower angular-resource#1.4.x          resolve git://github.com/angular/bower-ang                  ular-resource.git#1.4.x
bower jquery#~2.1.1                    cached git://github.com/jquery/jquery.git                  #2.1.4
bower jquery#~2.1.1                  validate 2.1.4 against git://github.com/jqu                  ery/jquery.git#~2.1.1
bower angular#1.4.x                    cached git://github.com/angular/bower-ang                  ular.git#1.4.8
bower angular#1.4.x                  validate 1.4.8 against git://github.com/ang                  ular/bower-angular.git#1.4.x
bower bootstrap#~3.1.1                 cached git://github.com/twbs/bootstrap.gi                  t#3.1.1
bower bootstrap#~3.1.1               validate 3.1.1 against git://github.com/twb                  s/bootstrap.git#~3.1.1
bower angular-route#1.4.x              cached git://github.com/angular/bower-ang                  ular-route.git#1.4.8
bower angular-route#1.4.x            validate 1.4.8 against git://github.com/ang                  ular/bower-angular-route.git#1.4.x
bower angular-animate#1.4.x            cached git://github.com/angular/bower-ang                  ular-animate.git#1.4.8
bower angular-animate#1.4.x          validate 1.4.8 against git://github.com/ang                  ular/bower-angular-animate.git#1.4.x
bower angular-mocks#1.4.x             ECMDERR Failed to execute "git ls-remote -                  -tags --heads git://github.com/angular/bower-angular-mocks.git", exit code of #1                  28 fatal: read error: Invalid argument

Additional error details:
fatal: read error: Invalid argument

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                  node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'                  .
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\testgit\angular-phonecat\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                  node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 prestart script 'npm install'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\testgit\angular-phonecat\npm-debug.log

**Comment by gkalpak** [comment]
Closed with c2033d7.
