### ISSUE TITLE
Environment Configuration ,Grunt Error 

### ISSUE THREAD

**Issue by vittal288** [angular/angular.js#13636]
I had set up with environment and I am getting following error while executing following command 
grunt package
or grunt 
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: undefined is not a function
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

Please provide me a solution....

**Comment by Narretz** [comment]
Please provide more info:
- what version of grunt, npm, node are you using?
- Have you installed the dependencies? https://code.angularjs.org/snapshot/docs/misc/contribute#installing-dependencies

**Comment by petebacondarwin** [comment]
Closing due to lack of response.
