### ISSUE TITLE
Doc page about providers falls short of defining precisely its most important component

### ISSUE THREAD

**Issue by marco-faustinelli** [angular/angular.js#13644]
In the docs there is a very interesting and informative page talking about providers.

https://docs.angularjs.org/guide/providers

One of its most important points is the definition of a `function UnicornLauncher(apiToken)` right at the beginning of the "Service Recipe" paragraph. That named function is used to build most of the examples in the page.

However, it is not shown _how_ and _where_ that named function itself has to be defined:
- is it a `value` on its own? I don't think so...
- is it a `constant` on its own? possibly
- is it defined in the global namespace, polluting it? I certainly hope **it's not**
- could it be defined inside an IIFE along with some app main module? how? please be specific

**Comment by dmitriz** [comment]
Usually you would enclose it into anonymous function to avoid polluting global namespace.
I personally use Gulp to wrap every file into anon. func. automatically.

Style guides might be of help, e.g. see
https://github.com/toddmotto/angular-styleguide#services-and-factory

It is true that few words can be said in the DOC, but that is what the "Improve Doc" button is for :)

**Comment by Narretz** [comment]
@marco-faustinelli Thanks for bringing this up. Most people are probably familiar with wrapping in anonymous functions or follow boilerplate projects that do this, but if you want to open a PR which clarifies this, I'll merge it in.

**Comment by 4O4** [comment]
This was reported a long time ago and since then nobody expressed the desire to improve this part of docs. I think it's time to just close it :)

**Comment by Narretz** [comment]
I agree. This is not something that must be mentioned in the provider guide.
