### ISSUE TITLE
.component template function not accepting annotations

### ISSUE THREAD

**Issue by cameronjroe** [angular/angular.js#13645]
Given a component:
```
import angular from 'angular';

export default {
  bindings: {},
  template: [
    '$element',
    '$attrs', 
    function ($element, $attrs) {
      return [
         '<div class="search-input">',
        '</div>'
      ].join('');
    }
  ],
  controller: [
    'Search', 
    function (Search) {}
  ]
};

```

The controller works, however the template doesn't accept the annotations and returns a string.

**Comment by Narretz** [comment]
This is coming in 1.5.0

**Comment by karlhorky** [comment]
Is there a workaround that we can use until then? Manual injection or something?

**Comment by gkalpak** [comment]
@karlhorky, it sounds more like an issue for https://github.com/toddmotto/angular-component.
Beware that `.component()` is still a feature under development (although pretty clode to final), so make sure your polyfills keep up with the breaking changes or you might run into surprizes when trying to upgrade to 1.5.

**Comment by karlhorky** [comment]
Okay thanks @gkalpak, I've opened toddmotto/angular-component#11

**Comment by toddmotto** [comment]
Anyone using the component() polyfill, I've added support for Array dependency annotation under release `0.0.4`, code here: https://github.com/toddmotto/angular-component/commit/24264c0154121980ffe811be516377b27970b762

Demo for annotated code: https://jsfiddle.net/toddmotto/67vmx7p5

**Comment by toddmotto** [comment]
@petebacondarwin Note on minification against this:

In the `link` function of Directives, you can use any name such as `scope` instead of `$scope`:

```js
// works
link($scope) {}
// also works
link(scope) {}
```

I've added this same behaviour to the component() polyfill [here](https://github.com/toddmotto/angular-component/blob/master/dist/angular-component.js#L31-L35) to automatically annotate, would this be worth aligning in the Angular core as well? ... Assuming you need to declare `template($element) {...}` and `template(element) {...}` breaks.

Small comments below:
```js
function makeInjectable(fn) {
  var isArray = angular.isArray(fn);
  if (angular.isFunction(fn) || isArray) {
    return function (tElement, tAttrs) {
      // isArray check, annotates the function if it's a function, or leaves as DI Array syntax
      return $injector.invoke((isArray ? fn : [
        '$element',
        '$attrs',
        fn
      ]), this, {
        $element: tElement,
        $attrs: tAttrs
      });
    };
  } else {
    return fn;
  }
}
```

**Comment by petebacondarwin** [comment]
@toddmotto thanks for the idea but I am concerned that mixing injected and non-injected APIs is too dangerous.
