### ISSUE TITLE
multiple-when ng-switch needed

### ISSUE THREAD

**Issue by calidion** [angular/angular.js#13648]
currently ng-switch only support single value,
but in most case, we need to control more value for one piece of html.
so a mulitple or/and for an ng-switch-when if needed.

```html
<ANY ng-switch="expression">
  <ANY ng-switch-when="matchValue1 || matchValue2">...</ANY>
  <ANY ng-switch-or="matchValue1 || matchValue2">...</ANY>
  <ANY ng-switch-and="matchValue1 && matchValue2">...</ANY>
  <ANY ng-switch-when="matchValue2">...</ANY>
  <ANY ng-switch-default>...</ANY>
</ANY>

**Comment by lgalfaso** [comment]
this came up several times and #10798 is the proposed PR to handle this. The PR does not handle what the example shows as `ng-switch-and` as the expression cannot take two values. Closing this as there are other issues and a PR to handle this
