### ISSUE TITLE
Decommenting Angular

### ISSUE THREAD

**Issue by vitaly-t** [angular/angular.js#13643]
This is not an issue, rather trying to contribute, and if this isn't the right place, my apologies then.

I am an active user of AngularJS, which I love a lot. And I appreciate how much code documentation is going into this library for automatic API generation. It is the same path with many other large libraries today.

Sometimes code documentation becomes so large, it becomes larger than the code itself, and instead of helping with debugging an application, it may get in the way.

On that sentiment, if you ever consider either distributing or otherwise publishing Angular JS without all the inline documentation, I just wrote a library - [decomment](https://github.com/vitaly-t/decomment), and used [Angular JS 1.5 Core](https://code.angularjs.org/1.5.0-rc.0/angular.js) as the ultimate test to see that everything looks and works right.

For that particular file, the [29,859 lines](https://code.angularjs.org/1.5.0-rc.0/angular.js) are reduced to [13,851 (less than half)](https://gist.github.com/vitaly-t/24bc56b19065d14c0e16), after passing it through `decomment(text, {trim: true})`, which is still the same-formatted code, but easier to navigate through.

Keep up good work, guys!

**Comment by Delapouite** [comment]
An alternative can be to turn on automatic comment-folding in your text editor.

**Comment by Narretz** [comment]
Cool library! I agree that inline docs can be a bit overwhelming.
Personally, if I wanted to see a file without comments, I would either use editor comment folding, or run uglifyJS so that it only removes comments, and otherwise doesn't touch the code.

**Comment by vitaly-t** [comment]
I mostly meant it for easier and faster debugging within browsers. Plus you end up with less than half the file size, which is good when you don't care about inline documentation.
