### ISSUE TITLE
bindToController with object hash allows binding properties with new instead of isolate scope

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#13658]
In https://github.com/angular/angular.js/commit/35498d7045ba9138016464a344e2c145ce5264c1, bindToController was changed to allow setting an object hash instead of true. 

The object hash works the same as with the scope property, and sets up the bindings to the controller. What it not does is create an isolate scope for the directive. You have to manually set the scope property to `{}`, but you can also set it to `true` or if you don't specify it, now scope is created at all. The commit says this is intentional, but I can't see how this is something that should be possible. Using `scope` with a has always creates an isolate scope, and I can't see why you'd want bindings with a new / no scope. It also defeats the purpose of defining your bindings with bindToController, because you still have to set the scope prop.

The whole behavior is actually undocumented, so it's possible not many people are using it. But imo, we should change it so that bindToController with hash creates an isolate scope in all cases.

**Comment by drpicox** [comment]
-1 
Not agreee.

It should not use scope:{} in all cases. For example:

```html
<my-component-foo data-foo="foo" my-decorator-bar data-bar="bar">
   ...
```

Which in both cases you can have bindToController and if decorators have scope:true can coexists with components with scope:{}.
By thumbrule I usually give scope:{} to entity directives and scope:true to attribute directives.

If you force to have always scope:true you are actually forbidding to use bindToController in attribute directives.

**Comment by fesor** [comment]
I completely agree with @drpicox.

**Comment by Narretz** [comment]
I see what you mean. Well, we need better docs for this, then.

**Comment by gkalpak** [comment]
I too think that `bindToController` with `scope: true` is a valid usecase (albeit not a common one).
In that sense, the implementation is correct, but the docs can always be improved.

**Comment by Narretz** [comment]
@gkalpak There were no docs for bindToController with object hash, that's how I stumbled upon this. Docs are here now: #13681 Can you please review? The thing is that this makes the API even more more complex, but maybe that's how it should be.
