### ISSUE TITLE
For angular 1.x please put email regex into a constant

### ISSUE THREAD

**Issue by fimius23** [angular/angular.js#13669]
We have some logic that, when the page loads, determines if email addresses should be read only or an input box. We want it to be an input box if the email is not valid, and for this it would be nice if the chromium email regex was a constant available to all.

**Comment by Narretz** [comment]
So you want to check the email against the regex and based on that render either text or an input? Why don't you use `ng-readonly` and make the input readonly if the email is valid?

**Comment by fimius23** [comment]
The group in charge of usability here believes that user's find grayed out information confusing. They believe that users ultimately spend time trying to figure out why the field is grayed out, and how to make the data accessible (even if they don't need to), instead of moving on in the form.

Therefore, we're currently using one time binding to decide whether or not to show a span or the input based on the validity of the data being retrieved.

**Comment by Narretz** [comment]
I see. I feel however that this is overcomplicating things. You could just style the input to look like a text-field, no? http://plnkr.co/edit/TOc1IhNlIb39ale9zbeu?p=preview

Granted, it doesn't look nice for long inputs and you still get the cursor in other browsers than Chrome. I just don't feel comfortable exposing the regex. But maybe that's just me. I'd like to hear from other contributors on this.

**Comment by gkalpak** [comment]
I too think it is not a good idea to make the RegExp a public API. If the RegExp works for you and you want to use it, it is super easy to copy it and declare it as a constant in your app.

**Comment by fimius23** [comment]
I don't understand the trepidation with making the constant a part of the public API. Seems like, because Angular is used by so many systems, the other regex that is grouped in that same area of code would also be good candidates for constants in the public API. This makes it so that use-cases you aren't thinking of can also be supported. You could just use the 'NG' namespace. 

I have currently copied the regex into a constant, but need to make sure (every time I upgrade to the latest release) that the regex hasn't changed. Styling the input if it's readonly is also, unfortunately, not a viable solution because I have to use our company's common javascript API and it wraps all inputs with styling that changes for a variety of issues. I would have to overwrite all of that styling, and also make sure that with each new release my styling 'fixes' are still working. Corporate America...

**Comment by ftheomunhoz** [comment]
I also disagree Have you considered extending/override the input directive for type 'email'?

**Comment by IgorMinar** [comment]
I don't think that we should expose the regexp. It's an internal implementation detail that we need to be able to tweak and improve. Making it a public api ties our hands and forces us to make breaking changes even for small bug fixes.

If you want the regexp you can grab it from our code base.
