### ISSUE TITLE
Feature request: ng-messages $warning

### ISSUE THREAD

**Issue by thorgilsv** [angular/angular.js#13666]
I'm creating a form with 30+ input fields and each input field has multiple error checks. There are are many variables that can have unlikely inputs but should still be submittable if the user chooses so.
I really like ng-messages because it makes error handling neat. What I think is missing is $warning that unlike $error would show warnings the same way as errors but not make the ngmodel invalid. NgModel and the form should then need an extra option beside $valid and $invalid, perhaps $unclear?

**Comment by Narretz** [comment]
I see what you mean, but this has nothing to do with ng-messages. ngMessages takes any object hash and renders the properties if they are truthy. But for ngModel, we might need something like $warnings, or $info. Let's talk about this here: https://github.com/angular/angular.js/issues/13465
