### ISSUE TITLE
Inner Component to Outer Component

### ISSUE THREAD

**Issue by guygit** [angular/angular.js#13667]
Hi,

using "Multi-slot" transclusion and the new "component()" function (Ng version 1.5.0-rc.0)

there seems to be no way for the inner component to use the API of the outer component:

```
<outer>
   <inner on-close="outerclose()"></inner>
</outer>
```
... where "outer" component (NG 1.5 component) exposes an API "outerclose()" to it's nested directive.

The only way I could coax it into work was something like that:
```
<outer vm="vm">
   <inner on-close="vm.outer.outerclose"></inner>
</outer>
```
```
function OuterCtrl () {
   var outer = this;
   // exposing the API
   outer.outerclose = function () { blah };
   // Trick, extending the surrounding scope (vm) of <outer> with outer's API
   outer.vm.outer = outer;
}
```
But is not the right approach I guess - however how is supposed to access API then?
Thank you!
guygit

**Comment by Narretz** [comment]
Can you please put a complete example into a plnkr.co? Specifically, I don't see any multi transclusion here (except the one that happens from the component itself).

**Comment by Narretz** [comment]
cc @petebacondarwin

**Comment by petebacondarwin** [comment]
@guygit - the trouble you have is that the context of the HTML being transcluded is the scope in which the component lives and not the isolated scope that the component creates (and on which the `outerclose` method is defined.

I am guessing from your example that you have no template for the `outer` directive, in which case it should not be defined as a component. What you want to do is to create a directive that does not create isolate scope, nor uses transclusion.

**Comment by guygit** [comment]
Hi Pete, hi Narretz,

both "outer" and "inner" have a template (or templateUrl) but "<inner on-close="outer.outclose()>" doesn't work, because "outer" and "inner" components both can only access the scope of the surrounding controller.

That means, I would have to re-define the API of the "outer" component inside the surrounding Controller to be accessible by the "inner" component.

I guess, this behavior is standard in all current versions of Ng 1.x, but with Multi-Transclusion and Component() function, there's no way to change it, as it was possible with the transclude-fn, where you could provide the scope of the "outer" (parent) component.

At the moment it's not clear to me whether or not, this is indented behavior - so do I always have to go via the Controller's scope when the "inner" wants to use the "outer's" API?

Thx

guygit

**Comment by guygit** [comment]
Hi Pete, hi Narretz,

both "outer" and "inner" have a template (or templateUrl) but "<inner on-close="outer.outclose()>" doesn't work, because "outer" and "inner" components both can only access the scope of the surrounding controller.

That means, I would have to re-define the API of the "outer" component inside the surrounding Controller to be accessible by the "inner" component.

I guess, this behavior is standard in all current versions of Ng 1.x, but with Multi-Transclusion and Component() function, there's no way to change it, as it was possible with the transclude-fn, where you could provide the scope of the "outer" (parent) component.

At the moment it's not clear to me whether or not, this is indented behavior - so do I always have to go via the Controller's scope when the "inner" wants to use the "outer's" API?

Thx

guygit

**Comment by Narretz** [comment]
We talked about allowign ng-transclude to specify which scope it should get. Maybe we should do that.

**Comment by guygit** [comment]
I know it's a complicated  issue with potential of introducing memory leaks etc.
It just came to my mind, because on the road to Angular 2, we would like our Ng-Controllers in Angular 1 to be as small as possible - though, perhaps it's not worth the effort.

But thx anyway!

**Comment by petebacondarwin** [comment]
@guygit - I think for your purposes you will need to get down to the metal and do a `terminal: true` in your directives, then take responsibility for grabbing the contents of the current element, loading the template and then injecting the grabbed HTML into the template.

**Comment by guygit** [comment]
Thx Pete, really appreciate the great job you did with Ng 1.5!
