### ISSUE TITLE
force ng-include to load same source again

### ISSUE THREAD

**Issue by ajinkya12** [angular/angular.js#13676]
Hi,
I am using ng-include to render a template.

`<ng-include src="current[0].htmlTemplate"></ng-include>`

current[0].htmlTemplate is always same as "search.html". But the controller associated with "search.html" must be run again. But ng-include prevents from doing that. For the first time ng-include works fine.

**Comment by Narretz** [comment]
If the template is the same, you should either move the data update logic into the controller, or you can append a parameter with a timestamp or similar to the url so it gets reloaded. In any case, please ask support questions on the support channel: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
