### ISSUE TITLE
The new component method is not working?

### ISSUE THREAD

**Issue by dmitriz** [angular/angular.js#13671]
It doesn't seem to use the binding:
http://jsbin.com/coloqa/edit?html,js,output

**Comment by bogdanalexe90** [comment]
you need to change you code into this
```
Testing: <my-comp name="'John'"></my-comp>
```

**Comment by Narretz** [comment]
@bogdanalexe90 is right, thanks for explaining that. Without quotation marks, the parser assumes John is a property on the scope. With quotation marks, it's a string literal.

**Comment by dmitriz** [comment]
Oops, thanks, you are right of course :)
