### ISSUE TITLE
ngResource data object is undefined in transformRequest funcion

### ISSUE THREAD

**Issue by daverdalas** [angular/angular.js#13674]
Hey, I'm using angular in version v1.4.8. I'm trying to do a very simple thing described in many places, however I can't make it work. Maybe this is a bug. Simple I want to change the data before sending it with ngResource. Here is my code:

Controller:
```javascript
var vm = this;
vm.application = new Application();
vm.application.title = 'Test title';
Application.save({}, vm.application, function(){

 });
```
Service:
```javascript
function application(ApiBaseUrl, $resource) {
    var actions = {
        'save': {
            metod: 'POST',
            url: ApiBaseUrl + "/applications",
            headers: { 'Content-Type': false },
            transformRequest: function (data) {
                console.log(data); //Returns 'undefined'
                return data;
            }
        }
    };
    return $resource(ApiBaseUrl + "applications/:id", {}, actions);
}
```
In the function transformRequest data object is always marked as 'undefined'. If I add `data` parametr  to service ex. `data: {test: 1}` then the object appears in `transformRequest`. However, in this way, I can't pass it from the controller. Maybe I'm doing something wrong?

**Comment by Narretz** [comment]
You should be saving the instance, not the Resource:

```
vm.application = new Application();
vm.application.title = 'Test title';
application.save().$promise.then(function() {

    });
```

untested, but should work

**Comment by daverdalas** [comment]
According to this (https://docs.angularjs.org/api/ngResource/service/$resource) i should call it this way: `vm.application.$save();` which returns also data as undefined. Your way returns `vm.application.save is not a function`.

**Comment by Narretz** [comment]
Yes, this is wrong, I meant $save

**Comment by daverdalas** [comment]
Unfortunately still returns undefined :(

**Comment by Narretz** [comment]
typo: `            metod: 'POST'`


;)
