### ISSUE TITLE
improve error message when making syntax mistakes with ngFor directive

### ISSUE THREAD

**Issue by sreeni** [angular/angular.js#13685]
In the stack trace below, the iteration variable "hero" is used without the # prefix in the ngFor directive. The resulting error message doesn't clearly state that cause. Any chance of improving this error message ?
`
EXCEPTION: Template parse errors:
Can't bind to 'ngFor' since it isn't a known native property ("
      <h2>My Heroes</h2>
        <ul class="heroes">
            <li [ERROR ->]*ngFor="hero of heroes" [class.selected]="hero === selectedHero"  (click)="onSelect(hero)">
         "): AppComponent@3:16
Property binding ngFor not used by any directive on an embedded template ("
      <h2>My Heroes</h2>
        <ul class="heroes">
            [ERROR ->]<li *ngFor="hero of heroes" [class.selected]="hero === selectedHero"  (click)="onSelect(hero)">
     "): AppComponent@3:12BrowserDomAdapter.logError @ angular2.dev.js:23514
angular2.dev.js:23514 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23514
`

**Comment by Narretz** [comment]
Please open an issue in https://github.com/angular/angular. Thanks!

**Comment by mashaly100200** [comment]
you forgot to put hash #  

try this
<li *ngFor="#hero of heroes"
