### ISSUE TITLE
Run travis tests on Microsoft Edge

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#13687]
- [x] update to karma 0.13.x (Edge poses as webkit browser, confusing karma)
- [ ] ~~install a launcher for Edge? See issue: https://github.com/karma-runner/karma-ie-launcher~~/issues/35
- [ ] update karma conf
- [ ] update travis build.sh

**Comment by petebacondarwin** [comment]
Possibly use https://github.com/nicolasmccurdy/karma-edge-launcher ?

**Comment by mgol** [comment]
A separate Edge launcher would only be needed to run tests locally, similarly to how `karma-chrome-launcher` & `karma-firefox-launcher` are needed only for that. For Travis purposes `karma-sauce-launcher` for Sauce Labs & `karma-browserstack-launcher` for BrowserStack are enough. Therefore, I think the second point is invalid.

**Comment by Narretz** [comment]
PR here https://github.com/angular/angular.js/pull/14401, but needs some work

**Comment by petebacondarwin** [comment]
Hurray! Good work @Narretz
