### ISSUE TITLE
Looking for a Lead Front-end Engineer to work in Warsaw

### ISSUE THREAD

**Issue by ewalobohr** [angular/angular.js#13689]
Hi,

We are looking for a Leader Front-end Engineer to work in Warsaw.

Job Description

Front End Developer Head of Technology Technology Warsaw, Poland

Looking for a skilled web and Front End developer to implement and maintain our in-houseand client-facing applications and website using HTML5, CSS3 and JavaScript. Working as part of an Agile development team, you will need to implement pixel-perfect designs while maintaining high user experience throughout.

Experience
2 + years of proven production web UI

Responsibilities
Interpreting graphic visuals (Photoshop, Sketch) into HTML, CSS(LESS)
Strong JavaScript knowledge – including packages like Query
Understanding of AngularJS or similar MV* frameworking
Collaborate with other developers using GIT for code reviews and an up-to-date development environment using Bower and Grunt
Working with Product Owners, UX Designer and Development teams to implement industry-leading responsive UI’s
Testing across bowers, devices and platforms for any inconsistencies
Keeping up to date with the latest industry technologies and releases

Essential skills
Strong hands on knowledge of latest UI languages – HTML5 / CSS3 (LESS) /jQuery
Good understanding of JavaScript and experience developing applications in AngularJS or similar
High attention to detail
Understanding of website / web applications usability and techniques to improve user experience
Experience using source code control (preferably Git)
Photoshop / Sketch and Illustrator

Desirable skills

Experience testing your front-end applications using Karma, Jasmine and Protractor or similar tools
Package management software such as Bower
Experience working in an Agile environment
Website analytics (e.g. GoogleAnalytics)

And you will be someone whois

Excited by the opportunity to keep up-to-date with the latest technologies / trends and implement them wherepossible
Salary 190 000 - 240 000 thousand gross per year polish zloty
Location Poland, Warsaw
Medical and social package

Send your resume on ewa.milkowska@ligohr.pl

**Comment by petebacondarwin** [comment]
This is not an issue with Angular. Please do not use GH as a recruitment tool
