### ISSUE TITLE
Remove $sniffer.vendorPrefix (was: Rethink the CSS prefixing strategy)

### ISSUE THREAD

**Issue by mgol** [angular/angular.js#13690]
Currently, Angular tries to detect the CSS prefix the browser supports and then uses the saved one. This strategy is not ideal as currently some browsers are supporting more than one vendor prefix. The best example is Microsoft Edge that added `-webkit-` prefixes to be more Web-compatible; Firefox is doing a similar thing (but AFAIK only on mobile so far). Some of the `-webkit-`-prefixed things are now even getting into specs to sanction that they're now required for Web compatibility.

In some cases Edge even supports only the `-webkit-`-prefixed property; one example is `-webkit-appearance`.

That's why I think we shouldn't try to detect the vendor prefix & save it; we should just do the detection for each CSS property we're interested in using. That's similar to what jQuery does and it works fine but here, in Angular, it's even easier to cache it as we only need a few CSS properties.

Such a strategy change will make Angular more future-proof.

**Comment by petebacondarwin** [comment]
I agree. Let's get this in after 1.5.0

**Comment by mgol** [comment]
ngAnimate no longer uses this API and since it's bad & undocumented anyway we'll be removing it in 1.6.0.

**Comment by mgol** [comment]
PR: #15287
