### ISSUE TITLE
Track by in combiantion with | orderBy messes up string value

### ISSUE THREAD

**Issue by stijnhaus** [angular/angular.js#13703]
When you use a track by, in combination with an '| orderBy', the calcualted value is a comma seperated string.

Eg.

ng-options="domain as domain.name for domain in domains track by domain.id  | orderBy:'name'"

the corresponding option value is a comma seperated list of all cahracters in domain.id

**Comment by lgalfaso** [comment]
Hi, this is the wrong place to get support. Please use StackOverflow for this. BTW, the right syntax is
`ng-options="domain as domain.name for domain in domains | orderBy:'name' track by domain.id"`
