### ISSUE TITLE
302 Redirect

### ISSUE THREAD

**Issue by harishr2222** [angular/angular.js#13705]
Hi Team,

I am facing difficulties in handling 302 redirect, after session timeout its trying to redirect but in angular interceptor i am not getting 302 code and in firefox firebug i can see head location value in header but  not able to get angularjs interceptor.
Using angularjs v1.3.8.

Thanks,
Harish

**Comment by Narretz** [comment]
Please ask support questions on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
