### ISSUE TITLE
Controller will sometimes run before all the directives compiled

### ISSUE THREAD

**Issue by luozt** [angular/angular.js#13700]
Generally, controller runs after direcitves including custom-directives.

However, I recently found the issue that "Controller will sometimes run before all the directives compiled".

The following code will show you the problem: 

```html
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>test directive</title>
</head>
<body ng-controller="bodyController">

  <hello alert="outAlert"></hello>

  <script type="text/javascript" src="http://cdn.bootcss.com/angular.js/1.4.8/angular.js"></script>
  <script type="text/javascript">
  angular.module("myApp", [])

  .directive("hello", function(){
    return {
      scope: {
        alert: "="
      },
      link: function(scope, elem, attrs){
        scope.alert = function(msg){
          window.alert(msg)
        }
      }
    }
  })

  .controller("bodyController", function($scope, $timeout){
    $scope.outAlert("this occurs an error: undefined is not a function")

    $timeout(function(){
      $scope.outAlert("this works great!")
    }, 100)
  })
  </script>
</body>
</html>
```

I hope that issue can be fixed as soon as possible!

**Comment by Narretz** [comment]
What makes you think that ngController will run after all other diectives?
It's actually just a "normal" directive that takes its controller from the ng-controller attribute.
And the order of execution is based on the scope tree, so parent directive controllers run first, then children.

**Comment by luozt** [comment]
The example code I showed above is just a simple instance. In some complicate cases, angular controllers will really run before custom directives compiled. But it seems to be a unstable probability which may depend on the network speed. It happens about once in 20 times. The problem really exists which can't be ignored.

**Comment by Narretz** [comment]
If it's a real problem, we need a repro. The demo you posted is expected behavior.

**Comment by Narretz** [comment]
If you have demo that shows the problem, feel free to reopen this issue.

**Comment by luozt** [comment]
Oh, the demo I posted above had already shown the problem. 
In `bodyController`, the function of  `$scope.outAlert` runs immediately, which will turns out to be an error "TypeError: $scope.outAlert is not a function". But to call `$scope.outAlert` in 100ms will work greatly! 
So I just want to ask why `$scope.outAlert` is undefined in controller runtime and becomes a function after 100ms??

**Comment by Narretz** [comment]
Because ngController is instantiated first, and the post link function of the directive is run after that. All that takes a few miliseconds, maybe even less.

**Comment by luozt** [comment]
So here comes the problem -- `All that takes a few miliseconds, maybe even less.`. The time is not a certain time. To delay 100ms to run `$scope.outAlert` works mostly, but still occurs an error sometimes. 
**Is there a better way then "$timeout(func, 100)"? **
Thanks! This is a really puzzle to me. -_-#||

**Comment by Narretz** [comment]
You simply shouldn't assume that the function you call in your parent 
controller will be defined by any of its children. This is imo bad 
architecture.

Am 07.01.2016 um 14:28 schrieb luozt:

**Comment by luozt** [comment]
Oh! Before, I just assumed that directives exports API to parent controller so parent controller can call API to control the directive. 
But now I figure out it is just a bad and wired way and I will modify code using the way.
Thanks for your kind guide and answer.

**Comment by luozt** [comment]
> You simply shouldn't assume that the function you call in your parent controller will be defined by any of its children. This is imo bad architecture.

But sometimes I want to make custom directives export API in order to let parent controller control the directive ui. To accomplish this, should I use custom scope events with `$on` and `$emit`, `$broadcast`? Is it a good practice?

**Comment by gkalpak** [comment]
@luozt, there are several ways to implement this. Using events is one.
Other ways include using a shared service or using directive communication (i.e. requiring a parent controller and calling functions on it).

What to choose strongly depends on the exact usecase.

**Comment by luozt** [comment]
@gkalpak , thanks for your kind answer. I choose using events as a shared service is hard to manage.
.-_-.
