### ISSUE TITLE
Typo in Documentation Image

### ISSUE THREAD

**Issue by petkostas** [angular/angular.js#13704]
There is a typo in the Scope diagram:
https://docs.angularjs.org/guide/scope

More specific, the scope name in the image:
![Image on Documentation]
(https://docs.angularjs.org/img/guide/concepts-scope.png)

Should be **'World'** not **'Wold'**

**Comment by Narretz** [comment]
If someone wants to replicate this picture, PRs welcome! Very minor though.

**Comment by SibuStephen** [comment]
@Narretz  the image has been replaced in PR - `#13724` plus the source of the image has been updated in PR - `13734` which is referenced in PR - `#13724`
