### ISSUE TITLE
Remove Default from ngList

### ISSUE THREAD

**Issue by Binvention** [angular/angular.js#13714]
The default on ngList of ", " prevents the ability of the attribute to use an empty string as a delimiter which can be useful if you want a list of every character in the text (including line breaks, spaces, tabs, etc). if the current default is removed then an empty string will be possible (in fact it will be the default)

**Comment by gkalpak** [comment]
It doesn't seem reasonable to have the empty string be the default delimiter, but we should allow the user to specify it (via `ng-list=""`).

**Comment by m-amr** [comment]
@gkalpak 

I think there is noway to distinguish between ng-list and ng-list = ""
because they both will return an empty string as a value

     element.attr(attr.$attr.ngList)
     // it will always return empty sting in case of
     // <input ng-list> or <input ng-list="">

I think we have this two options 
1 - add another attr ng-list-no-separator
2 - add a value like ng-list="no-separator"

i think we can't make no separator a default instead of ", " because it will break the
already written application that depends on that behaviour,

**Comment by Binvention** [comment]
I know that the default of ", " over writes if you try and out the delimiter as "". Removing the current delimiter would make the default "" since an attribute that isn't assigned a value returns "". I already tried it in my own code and it does work just by removing the default. And any other delimiter could still be assigned using ng-list="delimiter"

**Comment by m-amr** [comment]
@Binvention ,
 but what if someone depends that the default value is ", " it will breaks his application
your solution looks logically right but will not have a backward compatibility
changing a default value will break application that depends on this default behaviour.

**Comment by Binvention** [comment]
Yes it will lose backwards compatibility but any way of solving it while keeping the default will require more code. And it isn't very clear how much that default is even used. I tried looking up the origins for the default but was unable to find it. I don't think it would be a huge change for anyone, just allowing for one more option, but there isn't any way to tell. So it's a balance between excess code that might not be necessary, increased capability, and backwards compatibility that we don't know we need.

**Comment by gkalpak** [comment]
I imagine that `', '` is a very reasonable default. I expect it to be used most of the time. We shouldn't be making a change that (a) breaks existing apps (i.e. raises the barrier to upgrade) and (b) require more code for the most common case.
Besides, I consider `''` a very rare usecase. 

One option is to introduce an extra (optional) `ng-list-separator` attribute and use it's value (if the attribute is present). Then `ng-list ng-list-separator=" | "` would be equivalent with `ng-list=" | "`. The difference is that (if the `ng-list-separator` attribute is present), it's value will be used even if empty. `ng-list` or `ng-list=""` would still fallback to the default (`', '`), but `ng-list ng-list-separator=""` would use the empty string as a separator.

This avoids the BC, does not require extra code for the most common usecase and is easy to implement.

**Comment by lgalfaso** [comment]
1/ Putting a BC in place for an obscure case is a big no-no

2/ Creating a directive that does this would be very very simple

```js
// Warning, untested code.
{
  restrict: 'A',
  priority: 100,
  require: 'ngModel',
  link: function(scope, element, attr, ctrl) {

    ctrl.$parsers.push(function(viewValue) {
      if (viewValue == null) return;
      return viewValue.split('');
    });
    ctrl.$formatters.push(function(value) {
      if (Array.isArray(value)) {
        return value.join('');
      }
      return undefined;
    });

    ctrl.$isEmpty = function(value) {
      return !value || !value.length;
    };
  }
}
```

Should this case be handled at the core?

**Comment by Binvention** [comment]
Um wouldn't it be easier just to check for the ngListNoSeparator in the ngList directive after all I know that the only thing that prevents an empty string from working is the default so you could check if the new attribute is there maybe even have the attribute options be Boolean. If the attribute is set to true then set the delimiter to an empty string. That way a whole new directive is not required. The parsers for the normal ngList will parse it just fine it's just trying to set the delimiter to an empty string

**Comment by m-amr** [comment]
I think that ng-list separator should act as javascript split function
which will split a string with any separator including empty string
But for our case we should introduce a solution that take it's consideration the backward
compatibility with the already written application that depends that "," is a default separator
i would add a new attribute called ng-list-no-separator="true"
based on this attribute if it is true then we use "" (empty string) as a separator

        var ngListNoSeparator = attr.$attr.ngListNoSeparator ? element.attr(attr.$attr.ngListNoSeparator) : false;
      var ngList = '';

      // if attr.$attr.ngListNoSeparator attr is added to the element
      // and it's value is true this means that list has not separator
      // so string "abcd" will be changed to ["a", "b", "c", "d"]
      // or if it is not true
      // it will read the separator from attr.$attr.ngList
      // and split the string based on it
      if (!ngListNoSeparator) {
        ngList = element.attr(attr.$attr.ngList) || ', ';
      }

I just added this lines to fix the problem and add a test case for it.
This will enable developers to split list with empty string and will no break any application
Thanks.

**Comment by Narretz** [comment]
I would prefer if we could "fix" this by respecting spaces in attributes: https://github.com/angular/angular.js/pull/5597

Would be a breaking change in itself, though.

**Comment by m-amr** [comment]
@Narretz  
So you want solve it byusing
 ng-list=" " (space ) to split input value  on empty string and since that the value will be trimmed
 and use ng-list="" with ng-trim='false' to split based on space ?

**Comment by lgalfaso** [comment]
Agree with https://github.com/angular/angular.js/issues/13714#issuecomment-171980714

Anyhow, I think this is too late for 1.5

**Comment by gkalpak** [comment]
I don't  see how this can be solved by _"respecting spaces in attributes"_.
The problem here is that we can't distinguish between an attribute with an empty string as value and an attribute with "no value".

But, yeah, too late for 1.5.

**Comment by Narretz** [comment]
But we can distinguish betwen ngList="" and ngList=" ". Personally, I don't think ngList should be used to split strings.

**Comment by gkalpak** [comment]
It is a rare usecase indeed. I'm OK closing this as a won't fix too.
BTW, the same thing can be achieved using appropriate getter/setter (with `ngModelOptions`), but with more code :smiley: .

**Comment by Narretz** [comment]
You can actually split on empty string already: `<textarea type="text" ng-model="list" ng-trim="true" ng-list=" "></textarea>`
The whitespace " " in the ngList attr will be trimmed to "" and hence the separator will be "", too. I agree that this is not 100% obvious, but since this is such a rare use case, we don't have to implement a specific solution for this.
