### ISSUE TITLE
@sce.trustAsHtml and 'TM' symbol lock up mobile browser

### ISSUE THREAD

**Issue by legendarytoe** [angular/angular.js#13713]
I have found that when I try pulling html via ajax and "injecting" it into an angular view with code such as:

                        $scope.loadedViaAjax = $sce.trustAsHtml(data);
                        $scope.$apply();

or...

                        var injector = $('#ngCourseDrilldown').injector();
                        var $compile = injector.get('$compile');

                        // Compile the HTML into a linking function...
                        var linkFn = $compile(data);

                        // HEre's another way to get the scope for the controller
                        var theScope = $('#mainController').scope();

                        var elem = linkFn($scope);  

                        $('#ajaxTarget').append(elem);

                        // Now that the content has been compiled, linked,
                        // and added to the DOM, we must trigger a digest cycle
                        // on the scope we used in order to update bindings.
                        $scope.$digest();

A "TM" symbol (ascii 8482) in the html being injected will cause mobile browsers to lock up completely.  Very strange.  Doesn't happen on any of the desktop browsers I've tried (chrome, IE, Firefox), but it does happen on mobile Chrome, Dolphin and Safari.

Took me about 6 hours to track this down, and I still don't believe it.  But took the TM symbol out of the html and now it works.

**Comment by legendarytoe** [comment]
I should add that the first code example only works because there is a directive involved that I failed to mention...looks like this...

.directive('myNgCompile', function ($compile, $parse) {
    return {
        restrict: 'A',
        link: function (scope, element, attr) {
            var parsed = $parse(attr.ngBindHtml);

            //Recompile if the template changes
            scope.$watch(
              function () {
                  //alert('a');
                  return (parsed(scope) || '').toString();
              },
              function () {
                  // alert('b');
                  $compile(element, null, -9999)(scope);  //The -9999 makes it skip directives so that we do not recompile ourselves
              }
            );
        }
    };

**Comment by gkalpak** [comment]
@legendarytoe, could you create a live demo of the issue (e.g. using CodePen, Plnkr etc) ?
Something that we can ran in a mobile browser and see it crashing ?

That would help identify and solve the problem more quickly.

**Comment by legendarytoe** [comment]
I spend some time trying to reproduce this issue independent of our
application and I couldn't do it.  Very puzzling. I now have the sense this
is more of a browser issue that is independent of angular completely.
Please close this issue.  False alarm, sorry!

**Comment by gkalpak** [comment]
Thx for looking into this. Closing...
