### ISSUE TITLE
Http requests to content-negotiated API endpoints fail on Firefox

### ISSUE THREAD

**Issue by johnrbaur** [angular/angular.js#13712]
http://plnkr.co/edit/FamsVu1O3MxShrQIyMCy?p=preview

We investigated this and found that the default "Accept" header is different between Firefox and Chrome. 

Chrome defaults to: ```"*/*"```
Firefox defaults to: ```"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"```

Angular 1 handled this for us. With Angular 2, we're required to modify the headers to request JSON or accept the server default.

**Comment by gkalpak** [comment]
This repo is for ng1 only. Please, reopen on https://github.com/angular/angular.
