### ISSUE TITLE
$http 'GET' memory leak--number of listeners (AngularJS v.1.4.7/8)

### ISSUE THREAD

**Issue by megabyzus** [angular/angular.js#13716]

**Comment by deeg** [comment]
Just curious why you closed this, was there a resolution?

**Comment by megabyzus** [comment]
@deeg , we believe so.  It seems this is a 'feeture' of Chrome dev tools.  While recording the timeline, the listeners increase unboundedly (no garbage collection).  However between recordings, garbage is collected and listeners drop to 'zero'.  NOTE, while recording, if you manually garbage collect then the listeners indeed drop. It seems in recording mode Chrome dev tools required manual garbage collection.  We still have a question from the Chrome team about the heap saw tooth which implies SOME garbage collection.  Regardless, this has nothing to do w/AJS at this point. I hope this helps.

**Comment by deeg** [comment]
@megabyzus, thanks for the info.

**Comment by megabyzus** [comment]
@deeg Here is the Chromium link if you'd like more details:  https://code.google.com/p/chromium/issues/detail?id=576302
