### ISSUE TITLE
Missing ">" in textarea closing tag in ngListSpec

### ISSUE THREAD

**Issue by m-amr** [angular/angular.js#13728]
I was debugging something in ngListSpec test and i found that 

    helper.compileInput('<textarea type="text" ng-model="list" ng-trim="false" ng-list="&#10;"></textarea');

Missing '>' and the textarea closing tag

**Comment by m-amr** [comment]
I fixed it in  this pull request https://github.com/angular/angular.js/pull/13727

**Comment by gkalpak** [comment]
@m-amr, (for future PRs) if you submit a PR that fixes a reported issue (even one reported by yourself), you should add `Fixes #<issue-number>` in the footer of the commit message.
Then the issue will be closed automatically once the PR is merged.
