### ISSUE TITLE
Messages disappear

### ISSUE THREAD

**Issue by gisek** [angular/angular.js#13723]
Please take look at the Angular Material demo site at the `Postal Code` input:
https://material.angularjs.org/1.0.1/demo/input

Scenario 1 (works ok)
1) We start with
![a_1](https://cloud.githubusercontent.com/assets/1664094/12216965/f9b165b8-b6f2-11e5-8540-ef0c5c6b6184.PNG)
2) Mark whole text in the input and click `backspace`
3) Result
![a_2](https://cloud.githubusercontent.com/assets/1664094/12216968/0f34a8be-b6f3-11e5-9596-324cc610e99c.PNG)
4) Everything is ok

Scenatio 2 (bug)
1) We start with
![1](https://cloud.githubusercontent.com/assets/1664094/12216973/29cb15dc-b6f3-11e5-979d-2cd99713063b.PNG)
2) Delete last digit and you and up with (still ok)
![2](https://cloud.githubusercontent.com/assets/1664094/12216980/486e8b4a-b6f3-11e5-95e2-82c259cc5f1e.PNG)
3) Delete the rest of the input one by one:
![3](https://cloud.githubusercontent.com/assets/1664094/12216986/59a3751a-b6f3-11e5-94e5-5a6181a8fefa.PNG)
4) BUG, the should be 'You must supply a postal code' message, but there is nothing
5) Type a digit:
![4](https://cloud.githubusercontent.com/assets/1664094/12216993/86dfe66c-b6f3-11e5-81b4-2ef7dc067d09.PNG)
6) BUG again, there should be a message: 'That doesn't look like a valid postal code', but there is nothing
7) Type the rest of the digits
![5](https://cloud.githubusercontent.com/assets/1664094/12216996/b0969fa0-b6f3-11e5-8cef-c56b7ccf308c.PNG)
8) Now it's ok
9) Delete the last digit
![6](https://cloud.githubusercontent.com/assets/1664094/12217002/c285a800-b6f3-11e5-8178-994ae06b631d.PNG)
10) It's ok again

The messages are present in DOM, but the message container size seems to be calculated in a wrong way. 

This is how it looks when the message is visible
![image](https://cloud.githubusercontent.com/assets/1664094/12217051/808eb40e-b6f4-11e5-86bc-047e4a0d094e.png)

This is how it looks when the message is invisible
![image](https://cloud.githubusercontent.com/assets/1664094/12217040/5d4ab038-b6f4-11e5-9830-c7a6464760e0.png)

**Comment by Narretz** [comment]
This looks like an issue for https://github.com/angular/material
