### ISSUE TITLE
Query params after factory call

### ISSUE THREAD

**Issue by shash8787** [angular/angular.js#13737]
Is it possible to show the factory call in the browser's address bar? 

For example, when I say, 

$scope.bearFails = BearSettlement.getBearFails({filters: $scope.filters, checkbox_status: $scope.checkboxStatus}, function(response) {  .... }); 

I want to show this url in the address bar so that it can be saved and also helps in the back button functionality. Please help. 

Thanks

**Comment by gkalpak** [comment]
@shash8787, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
