### ISSUE TITLE
fix(input[date]): support years with more than 4 digits

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#13735]
Currently, (mainly because of the REGEXPs used for parsing dates, e.g. [here][L13] and [there][L29-L32]), date-family inputs do not support years with more than 4 digits (they consider the value invalid and the parser returns `undefined`).

According to the [W3 spec][1], the value of a date-family input should be a "valid _full-date_ as defined in [[RFC 3339]][2], with the additional qualification that **the year component is four or more digits** representing a number greater than 0" <sub>(emphasis mine)</sub>.

Additionally, [ISO 8601][3] allows (upon agreement of the involved parties) to have _expanded representation_ of years (with more than 4 digits); see for example sections 2.3.8 and 4.1.2.4.

--
Current browser support:

* **Chrome**, **Opera**: Support date inputs and years greater than 9999.

* **Firefox**, **IE**: Do not support date inputs, but the user can still enter the dates in ISO format and `ngModel` parses them correctly

* **Edge**: Supports date inputs, but **not** years greater than 9999.

* **Safari**: ???

There's nothing we can do for MS Edge on the Angular side, but the users of other browsers will still benefit from adding support for years greater than 9999.

[1]: http://www.w3.org/TR/html-markup/input.date.html
[2]: http://www.w3.org/TR/html-markup/references.html#refsRFC3339
[3]: http://dotat.at/tmp/ISO_8601-2004_E.pdf

[L13]: https://github.com/angular/angular.js/blob/8ccc0547a8838454300e2dc75bab7fafdf22d21f/src/ng/directive/input.js#L13
[L29-L32]: https://github.com/angular/angular.js/blob/8ccc0547a8838454300e2dc75bab7fafdf22d21f/src/ng/directive/input.js#L29-L33

**Comment by Narretz** [comment]
Safari 9 has no special date input handling. ios9 has a datepicker input, and you can't actually enter the date by hand (at least not in Saucelabs).
