### ISSUE TITLE
Not reusing existing object problem 

### ISSUE THREAD

**Issue by armanx64** [angular/angular.js#13745]
In Angular 1.4.x when I'm trying to call smth like `angular.module("myApp")` twice, on second call I'm getting error of double initialization, but the right way is just to return previously created object. 

Currently because of this behavior we needed to create variable in global context and reuse it; that's not helping to write clean code. If Angular know that module already initialized, so it must return reference to that object. And then instead of 

    var mainApp = angular.module("mainApp");
    ....
    mainApp.controller(...)

we'll can use 

    //init
    angular.module("mainApp");
    ....
    angular.module("mainApp").controller(...)

And do it in as more places as we want. No more global variables and less code in bootstrappers. Some way can be done with controllers and other points of Angular.  

Try to find something wrong in that approach.

**Comment by gkalpak** [comment]
Calling `angular.module('...')` should **not** throw any error (nor try to initialize the module/app), no matter how many times you call it. It is just a module getter (and indeed you don't need any global variables).

The variation that does initialize the module, is `angular.module('...', [...])` (**with** the second argument) and that one should now me called twice.

--
It seems like something else is wrong in your code. Posting a live demo (e.g. using CodePen, Plnkr etc) would help identify the problem.

**Comment by Narretz** [comment]
Closing due to lack of feedback
