### ISSUE TITLE
RegExp Literal in template expression parse error  

### ISSUE THREAD

**Issue by wfalkwallace** [angular/angular.js#13743]
```
<div *ng-if="myStringVar.match(/regexp/)">myStringVar had 'regexp' in it! </div>` 
```
produces 
```
EXCEPTION: Template parse errors:
Parser Error: Unexpected token / at column 25 in [ng-if myStringVar.match(/regexp/)] in function () {
 > div:nth-child(0)[*ng-if=myStringVar.match(/regexp/)]
```

[Plunkr](http://plnkr.co/edit/kOK8CRqv78eLhyPUHpqH?p=preview)

**Comment by gkalpak** [comment]
This repo is for ng1. You are looking for https://github.com/angular/angular (or rather the ng2 [support channels][1]).

[1]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
