### ISSUE TITLE
Typescript version of angular_1_router.js and the d.ts

### ISSUE THREAD

**Issue by varghesep** [angular/angular.js#13748]
I'm using **Angular 1.4.6** and **Angular 2 beta** in the same project and all my files are typescript files.

I had a **angular_1_router.js** before and want to port it's **ts** file to this new project.
1. Should I be not using **angular_1_router** but the router from angular2 which is a **ts** version already?
2. If I can't use angular2 router, Is there a typescript version of **angular_1_router.js** and it's types as **d.ts** file available?

**Comment by petebacondarwin** [comment]
@btford what is the recommendation here?

**Comment by sarod** [comment]
The npm '@angular/router' 0.2.0 still does not contain the d.ts files.

Is there any progress on this?

**Comment by petebacondarwin** [comment]
You need to use Angular 1.5.2 or higher with the new component router.
We have not yet created a .d.ts file for angular_1_router.js. The Angular 1 version of the router has a slightly different public API to the Angular 2 version so such a file would probably need to be hand crafted.

**Comment by Narretz** [comment]
Since the component router for AngularJS is deprecated, I don't think d.ts files will be added.
