### ISSUE TITLE
Input Directive not Posting

### ISSUE THREAD

**Issue by rochapablo** [angular/angular.js#13749]
I'm trying create a directive to reuse in a form. But when I submit, the input (directive) is not there.

This is my tag:

```
<core-input type="text" icon="person" name="name" placeholder="Name" ng-model="mymodel.name"></core-input>
```

This is my directive js code:

```
angular.module('StarterApp').directive('coreInput', function($compile) {
        return {
            restrict: 'AE',
            require: '?ngModel',
            scope: true,
            link: function(scope, element, attrs, ngModel) {
                if (!ngModel) return;
                scope.onChange = function() {
                    ngModel.$setViewValue(scope.value);
                };
                ngModel.$render = function() {
                    scope.opts = attrs;
                    scope.value = ngModel.$modelValue;
                    $compile(element.contents())(scope);
                };
            },
            templateUrl: function(elem, attr) {
                return './app/views/directives/form/' + attr.type + '.html';
            }
        };
    });
```

And this is what I want reuse:

```
<md-input-container class="md-icon-float md-block" flex-gt-sm md-no-float>
    	<md-icon class="material-icons">
    		<i class="material-icons">{{ opts.icon }}</i>
    	</md-icon>
    	<input type="text" name="{{ opts.name }}" placeholder="{{ opts.placeholder }}" ng-model="$parent.ngModel">
    </md-input-container>
```

I have opened a [Question](http://stackoverflow.com/questions/34741450/why-my-angular-directive-input-is-not-been-posted), but until now, not working.

What am I missing here?

**Comment by Narretz** [comment]
Hi,
first of all you should ask support questions on one the support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Second, you are doing some very strange things. 
- there is no connection between the ngModel on the coreInput directive and the actual input inside it `$parent.ngModel` is not defined anywhere.
- calling $render with a compile everytime your model changes is very wasteful
- I can't find a reference to onChange anywhere
- you should better not put ngModel on anything else but an input if you do not know what you are doing.

Keep it simple. I think this is a good starting point: http://plnkr.co/edit/4ylLqoMuWP3OyjwAOcmh?p=preview
