### ISSUE TITLE
invoke function inside html gets invoked too many times… not good practice

### ISSUE THREAD

**Issue by jamesbondo** [angular/angular.js#13755]
invoke function inside html
     (gets invoked too many times… not good practice)
<span>{{todoList.check()}}</span>
  todoList.check = function(){
    console.log("here")
  }

this is a snippets from https://angularjs.org/
in the console, the "here" will be printed at least twice each time this function is invoked. is this a bug?

**Comment by Narretz** [comment]
This is how the digest cycle works. It checks the result of each expression up to 10 times per digest to make sure it is stable. 2 times is the minimum.

**Comment by jamesbondo** [comment]
So it's not a good idea to have a long expression in the html.. Right?

**Comment by gkalpak** [comment]
@jamesbondo, if by "long" you mean "computationally expensive" then indeed it's not a good practice :)
Ideally, only simple getters should appear in templates.

**Comment by jamesbondo** [comment]
I see. Thanks!
