### ISSUE TITLE
When replace=true in the directive, the style of the outmost element will be duplicate

### ISSUE THREAD

**Issue by kinglcc** [angular/angular.js#13757]
### The javascript code：
```
buildTools.directive('buildStatus', function () {   
            return {   
                restrict: 'E',    
                replace: true,   
                scope: { },   
                transclude: true,   
                template: '<a style="color:#fefefe;">test</a>'  
            }    
   });
 ```   

### The html code:
`<build-status></build-status>`

### The render html code:
`<a style="color:#fefefe;;color:#fefefe;">test</a>`

**Comment by Narretz** [comment]
This is a known issue (https://github.com/angular/angular.js/issues/6239), which is unlikely to get fixed. Remember that replace: true is deprecated, and its use is discouraged.
