### ISSUE TITLE
Problem with angular.equals

### ISSUE THREAD

**Issue by tuankiet1708** [angular/angular.js#13765]
angular.equals runs not exactly when comparing between empty object **{}** and other object with key starting with character **$**.

Example: 
```
angular.equals (
 { },
 { "$or" : [1, 2] }
) 
```
=> Expected Value is false, but true.

But when using jQuery.isEmptyObject, it's ok.

**Comment by frfancha** [comment]
That's because $properties are supposed to be angular properties to be ignored by comparaison. Angular.equals is designed for angular needs and therefore works as designed.

**Comment by tuankiet1708** [comment]
I got it. Thank @frfancha very much :+1:
