### ISSUE TITLE
Duplicate values in IE9 when adding a grouping to ngOptions

### ISSUE THREAD

**Issue by KwintenP** [angular/angular.js#13768]
If you open a select dropdown on IE9 which has a group clause in the ngOptions, the groups are duplicated.
The documentation has an example where the issue can be reproduced.
https://code.angularjs.org/1.4.8/docs/api/ng/directive/ngOptions
(at the bottom, the third dropdown)

**Comment by Narretz** [comment]
A fix for this was already committed, and will be part of 1.4.9

**Comment by KwintenP** [comment]
Perfect, does v1.4.9 already have a release date?
