### ISSUE TITLE
ngOptions with “group by” show double results in IE 11

### ISSUE THREAD

**Issue by joecoolish** [angular/angular.js#13778]
I'm noticing something weird in Angular 1.4.8 and 1.5.0 RC0 but only for IE 11.  This doesn't happen in Chrome or Firefox

I have a select box that has the following ngOptions value:

     test.value as test.label group by test.group for test in model

Because I have the `group by` clause, all of the options are doubled. There are some other weirdnesses with adding and removing values from model and having them not disappear from the select box as well.

I built a quick example to show what I mean

Angular 1.4.8: http://codepen.io/anon/pen/LGzRmy
Angular 1.4.7: http://codepen.io/anon/pen/LGzRJL

Html:  

	<div ng-app="test">
	  <div ng-controller="testCtrl">
		<select style="height: 200px; width: 100px;" multiple ng-options="test.value as test.label group by test.group for test in model" ng-model='selected'></select>
		<select style="height: 200px; width: 100px;" multiple ng-options="test.value as test.label for test in model" ng-model='selected'></select>
	  </div>
	</div>

JavaScript:

```JavaScripts
angular
  .module('test',[])
  .controller('testCtrl', function($scope){
  
  $scope.selected=[]
  $scope.model = [
    {
      value: 'test1',
      label: 'Test 1',
      group: 'test'
    },
    {
      value: 'test2',
      label: 'Test 2',
      group: 'test'
    },
    {
      value: 'test3',
      label: 'Test 3',
      group: 'test'
    },
    {
      value: 'foo',
      label: 'Foo',
      group: 'bar'
    }]  
})
```

Here is a picture of what I'm seeing in IE 11
![angular doubling up](https://cloud.githubusercontent.com/assets/1739416/12364123/d591e71e-bb9a-11e5-9926-165ec94c5027.PNG)

Angular 1.4.7 and newer do not have this issue.

**Comment by Narretz** [comment]
This will be fixed in 1.5.0-rc.1 and 1.4.9. Releases are next Tuesday.
