### ISSUE TITLE
Newbee question ng-route, cannot invoke function 

### ISSUE THREAD

**Issue by GerhardKreuzer** [angular/angular.js#13774]
Hi,
have a small web site and use ng-route to jump between views, all happy.
On one of this partial views I need to execute a script function. And no, I cant run this in the controller.
I placed a button and tried to call that function from the click, but I get the error 'undefined function'
???? I still can see the function.
I include my Website. Follow 'Route-1' and than click 'Energy' button ...
I also include a snap shot.
I know, this makes not that sense, but I am newbee and just try out things, with a Website in mind.

Thanks for helping

With best regards

Gerhard
[Website.zip](https://github.com/angular/angular.js/files/91506/Website.zip)

**Comment by Narretz** [comment]
Please ask support questions on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question Thanks!

**Comment by Narretz** [comment]
You can also put your (minimal) code into websites such as plnkr.co - that makes it easier for others to test.
