### ISSUE TITLE
default controllerAs broken in rc1

### ISSUE THREAD

**Issue by Janpot** [angular/angular.js#13781]
in rc0 components, when no `controllerAs` was specified, the name of the component was chosen to publish the controller in the scope.
this doesn't work anymore in rc1:

rc0: https://jsfiddle.net/a7s2oj2x/

rc1: https://jsfiddle.net/tbw358t4/

rc1 with `controllerAs`: https://jsfiddle.net/jqk2wr11/

**Comment by Janpot** [comment]
My bad, just found this: https://github.com/angular/angular.js/commit/d91cf167960d47ce38fec0d33cab6119268623f0

**Comment by Janpot** [comment]
Maybe this can be added as a breaking change?

**Comment by Narretz** [comment]
I'll add a BC note, good catch

**Comment by Narretz** [comment]
CL is updated.

**Comment by Narretz** [comment]
Oops, not yet
