### ISSUE TITLE
Form reset for field with minlength not working

### ISSUE THREAD

**Issue by LorandLorincz** [angular/angular.js#13790]
Hi,

I think I found a bung. When using a ng-minlength on a form field and not passing validation, the field cannot be reseted. Thats cause the model is not updated until the validation passes. Please see fiddle bellow. I also tried using .$rollbackViewValue() but it still doesen't work. I hope I'm using it right.

https://jsfiddle.net/lorisl/dfyaddc6/7/

Thanks.

**Comment by Narretz** [comment]
Known issue. ngModel won't reset the view because the model hasn't changed yet. For real reset functionality, you'll want to use a button with type="reset". This is also the only way to reset input type="number" with a non-number entered.
