### ISSUE TITLE
$compile: `$document` is unused

### ISSUE THREAD

**Issue by dcherman** [angular/angular.js#13791]
Currently, `$document` is injected into compile, however it is entirely unused; the global `document` is always referenced instead.  Should the `$document` variable be used in all of these locations, or should we consider removing the `$document` dependency?

I'm happy to make a PR for whichever way you feel this should go.

**Comment by Narretz** [comment]
I think it can be removed. It was added by https://github.com/angular/angular.js/commit/9532234bf1c408af9a6fd2c4743fdb585b920531 and it's only use finally removed by https://github.com/angular/angular.js/commit/9f4d99f4eaa53ea4b186a2954b23ce4c86643947
