### ISSUE TITLE
ng animate not working first time loading 

### ISSUE THREAD

**Issue by sibascodeking** [angular/angular.js#13806]
i try to animate the <div> elements one by one. It is working one by one using ng-enter-stagger and ng-leave-stagger but at the  time of loading the animation is not coming.

Thank You 

This is my code
&lt;div ng-repeat='obj in objs' class='flipInAni'&gt;&lt;/div&gt;"

.flipInAni.ng-enter-stagger, .flipInAni.ng-leave-stagger, .flipInAni.ng-move-stagger {
    -webkit-animation-delay: 0.3s;
    animation-delay: 0.3s;
    -webkit-animation-duration: 0;
    animation-duration: 0;
}
.flipInAni.ng-enter {
    -webkit-animation:2s ease-in-out all;
    animation:2s ease-in-out all;

    animation-name:flipInX;
    -webkit-animation-name:flipInX;
}
.flipInAni.ng-enter.ng-enter-active {

    animation-name:flipInX;
    -webkit-animation-name:flipInX;
}
.flipInAni.ng-leave {
    -webkit-animation:1s ease-in-out all;
    animation:1s ease-in-out all;
    animation-name:flipOutX;
    -webkit-animation-name:flipInX;
}
.flipInAni.ng-leave.ng-leave-active {
    animation-name:flipOutX;
    -webkit-animation-name:flipOutX;
}

**Comment by Narretz** [comment]
What do you mean by loading? Page load?

**Comment by sibascodeking** [comment]
when page load this ngAnimate was not working

**Comment by Narretz** [comment]
ngAnimate is disabled when the app bootrstraps / the page loads. You can add this to your app, and it should work
```
yourAppModule.run(function($animate) {
  $animate.enabled(true)
});
```

**Comment by sibascodeking** [comment]
no it is not working.My main problem was i want to check the ng-Event-stagger when this stagger was working then animation at the time of loading not came if stagger not working then the animation came 

http://plnkr.co/edit/cilmUfsa5wjhWnJtOmoA?p=preview

**Comment by Narretz** [comment]
Sorry, I'm not sure I understand. You mean the stagger animation is not working? That's all I can see in the plnkr. There is no stagger animation for add, and no stagger animation for remove.

**Comment by Narretz** [comment]
Also, you are using an old version of  Angular. You should use the latest version, 1.4.8. 1.2 is not developed actively anymore.

**Comment by Narretz** [comment]
I still don't know what the exact problem is.
Please: post what I should do in the plnkr so that the bug happens, and what you would expect to see otherwise. Closing for now.
