### ISSUE TITLE
ngRoute Not Working UCBrowser

### ISSUE THREAD

**Issue by nemesis9999** [angular/angular.js#13811]
i build app with angularjs, use ngRoute, try it access on browser with UCBrowser, click that link not support my App not show for part my template, but i try it make ngRoute just file html that working if not get data from database,,,

**Comment by Narretz** [comment]
Does it work in any other browser? Can you please post a minimal demo? On plnkr.co would be good.

**Comment by nemesis9999** [comment]
i try myApp in localhost, i try access via mobile, my App have a data and get that data from database, but i try make file ngRoute just html that working, but if that get data myApp not show my template, can you try make a just file angular and your access via mobile with UCBrowser that work and you try access your app wit get data after that access via mobile UCBrowser, i cant make a demo, for myApp cause myApp still in localhost :)

**Comment by nemesis9999** [comment]
any other browser not work if not get data and just html file that work any browser,

**Comment by gabrielclima** [comment]
Do you have correct connected the templates with controllers and services through the App.js?
Can you show the output JavaScript console during the 'getData' process?

Guy! @Narretz asked if can you post your code on http://plnkr.co/ to wee see, haha =)

**Comment by nemesis9999** [comment]
i dont know to see console from mobile, do you know it for see console, android mobile?

**Comment by gabrielclima** [comment]
How are you emulating on mobile? Using terminal, prompt, VisualStudio?
You can emulate on your browser and press F12 to see console log =)

**Comment by nemesis9999** [comment]
mobile, i try it on codeigniter.. why i can show demo, cause myApp still localhost..

**Comment by nemesis9999** [comment]
mobile, i try it on codeigniter.. why i can show demo, cause myApp still localhost..

**Comment by nemesis9999** [comment]
mobile, i try it on codeigniter.. why i can show demo, cause myApp still localhost..

**Comment by nemesis9999** [comment]
mobile, i try it on codeigniter.. why i can show demo, cause myApp still localhost..

**Comment by gabrielclima** [comment]
Can you paste ur code on GitHub?

**Comment by Narretz** [comment]
Sorry, without a reproduction there is nothing we can do.
