### ISSUE TITLE
angular.module(...).component is not a function

### ISSUE THREAD

**Issue by krasevych** [angular/angular.js#13813]
I updated my angular to 1.5.0-rc.1
And I try to use .component()  but it doesn't work.
I got a error: 
Uncaught TypeError: angular.module(...).component is not a function

**Comment by Narretz** [comment]
Are you using batarang by any chance?

**Comment by krasevych** [comment]
Yes batarang is active. is it a problem?

**Comment by Narretz** [comment]
Yes, batarang is currently not compatible with 1.5. :( We are planning a new batarang release in the very near future.

**Comment by krasevych** [comment]
Yes it was problem with batarang
