### ISSUE TITLE
View is different in ngOpen docs.

### ISSUE THREAD

**Issue by shyamji1983** [angular/angular.js#13818]
In example section, view is different in https://docs.angularjs.org/api/ng/directive/ngOpen page.

**Comment by gkalpak** [comment]
@shyamji1983, what do you mean ? What is different ? What did you expect it to be instead ?

**Comment by shyamji1983** [comment]
**Below code is not related to ngOpen :**
userType: guest 
userType = guest
myForm.input.$valid = true
myForm.input.$error = {}
myForm.$valid = true
myForm.$error.required = false

**Against this code : **
<label>Check me check multiple: <input type="checkbox" ng-model="open"></label><br/>
<details id="details" ng-open="open">
   <summary>Show/Hide me</summary>
</details>

**Comment by gkalpak** [comment]
@shyamji1983, I still don't know what you mean. Could you describe what you are seeing vs what you would expect ? Maybe post a screenshot.

**Comment by Narretz** [comment]
Sorry, we cannot do anything without more info. Closing. Feel free to reopen when you have more info,
