### ISSUE TITLE
HTML5 tags with ng-repeat are rendered incorrectly in IE8

### ISSUE THREAD

**Issue by natebridi** [angular/angular.js#1381]
Simple example: http://jsfiddle.net/59Db4/1/

Look at the generated code using the Developer Tools in IE8.

HTML5 tags (`<article>`, in my example) with an ng-repeat are rendered with a colon at the beginning of the tag in native IE8. `<article ng-repeat="item in items">`  generates `<:article>`. This does not happen in IE9 running in IE8 mode, only in IE8 itself.

It doesn't seem to make any difference if I employ the HTML5 shiv or not, result is the same.

In my project where I discovered this problem, all functionality (bindings, etc.) still continue to work, but it causes the CSS styling to be broken.

**Comment by Narretz** [comment]
IE8 / 1.2.28 are not actively supported anymore. Good to know there's an easy fix for this, though.
