### ISSUE TITLE
input validation problem with ngAnimate

### ISSUE THREAD

**Issue by r20** [angular/angular.js#13825]
In Angular 1.4.5 and later, validation for required inputs has a bug.
In Angular 1.4.0 - 1.4.4 it works.

If the value in the input is cleared and then later quickly asynchronously updated (such as with a $http call or a $timeout) the classes ng-invalid and ng-invalid-required are some times set on the input element even though it has a valid value.

This can be reproduced in http://plnkr.co/edit/tONUcHgu3CTKYov2YOUz?p=preview
Hit the submit button a few times to see the input remain invalid (marked with red) even though it has a value.
Change the version from 1.4.5 to 1.4.4 and the problem goes away.

**Comment by Narretz** [comment]
I can't reproduce the bug with 1.4.9.

**Comment by r20** [comment]
Yes, it looks like 1.4.9 (released yesterday) fixed it.  I found this yesterday so hadn't tried that one. Thanks.
