### ISSUE TITLE
Cloudant Database Script is not able to Running

### ISSUE THREAD

**Issue by karthiki2s** [angular/angular.js#13829]
Hi All,
I try to create Bluemix cludant database for ready apps but i can not able to load the sample script file. Bcos i was trying to load readyapps banking apps script file is not load our database. Kindly anyone suggest me.

i got issues for that script file when run the command it opening file only.

cloudant_update.pl -d CLOUDANT_DB -p PASSWORD [-o FILENAME] [-u FILENAME]

Thanks

**Comment by karthiki2s** [comment]
hi all,
i have small doubt the ready app for banking only runing at ios device? or android?. and how can i configure the below that proerties. is it related to bluemix credential ?

<dict>
  <key>demoPassword</key>
  <string>password1</string>
  <key>demoUsername</key>
  <string>user1</string>
  <key>hatchRealm</key>
  <string>ReadyAppHatchAuthRealm</string>
  <key>isDevelopment</key>
  <false/>
  <key>mqaApplicationKey</key>
  <string>your-mqa-application-key</string>
</dict>

what is your-mqa-application-key? 
what is demoPassword ?
etc...

thanks

**Comment by gkalpak** [comment]
Wrong repo (I presume). This repo is about AngularJS.
