### ISSUE TITLE
Consider exposing $log by default in $scope

### ISSUE THREAD

**Issue by mprobst** [angular/angular.js#13839]
This is a bit odd - naturally we want to keep `$scope` as clean as possible. However it's very common that users would want some quick way to log something for debugging event handlers, or possibly even expression evaluation. Exposing `$log` on `$rootScope` would easily solve that, and shouldn't have negative impact.

**Comment by mprobst** [comment]
@lgalfaso wdyt about this?

**Comment by petebacondarwin** [comment]
```js
myMod.run(function($rootScope, $log) { $rootScope.log = $log; });
```

This one liner is very simple to add to any app. I would rather not expose debugging devices as part of the core setup.

**Comment by mprobst** [comment]
Yeah, but you have to remember that, and in particular users who pull Angular from a CDN or look at an app where they're not that familiar with the setup might struggle with this. I don't feel very strongly about this, but I think it'd be a nice usability feature with very little impact on code size and very low risk on breaking anything.

There is a security risk though for exposing that...

**Comment by Narretz** [comment]
We've decided that we are not gonna do this. Security risks are always bad, and we'd rather keep the scope clean. $log is an utility, and you'd still have to inject it into services, directives etc. We can add a line about adding it to the scope (in debug mode preferrably) to the docs though.
