### ISSUE TITLE
add a callback for the not handled events

### ISSUE THREAD

**Issue by m-amr** [angular/angular.js#13836]
$scope.$broadcast or $scope.$emit are used to fire custom events. 
but sometimes the $scope of the (controller or the directive) is not rendered yet,
so it will be better have a failure callback

      $scope.$broadcast('custom:event', data).hasNoListener(function(){
           // developer can choose to 
          // 1- broadcast it again or wait for some time .
          // 2- or log an error.
      });

provide a callback like hasNoListener() which is called if the events has no listener or
callback which is called when the event is handled by listeners
       
        var numberOfListenersThatHandleEvent = 0;
        $scope.$broadcast('custom:event', data).eventHandled(function(){
             numberOfListenersThatHandleEvent++;
        });

so developers can keep track of that is happening.
Thanks

**Comment by petebacondarwin** [comment]
I think you are really looking for something more general than the `$scope` event system. Have you considered trying out one of the observable libraries such as RxJS or Bacon.js?  I think you would get more value from them.
