### ISSUE TITLE
Feature Request: Directive which automatically applies once promise is resolved.

### ISSUE THREAD

**Issue by ApacheTyler** [angular/angular.js#13841]
One common pattern when trying to update a view once a promise is resolved is to assign a value of the successful promise's callback parameter to a $scope variable. eg.

In the controller:
```javascript
promise.then(function(response) {
  $scope.val = response.val;
});
```
In the view:
```html
<div>{{val}}</div>
```

Would there be a reason why introducing a directive that automatically applied values once a promise is resolved be a bad idea?

For example:
```html
<div ng-resolve="makeAsyncCall()" ng-response-as="resp">{{resp.val}}</div>
```

**Comment by petebacondarwin** [comment]
Once upon a time we had a thing called automatic promise unwrapping. It generally caused more confusion than help and led to bugs where one tried to write to an object in the scope that had not yet arrived. We decided that this was not a good pattern and deprecated then removed the feature.

I fear that this directive would have similar problems. It is fairly simple to code up for your own uses but I don't think we will put such a directive into the core.

**Comment by ApacheTyler** [comment]
I see. Thanks for the article! I figured it was because "it could potentially introduce a lot of WTFs to your daily work".
