### ISSUE TITLE
$http : config.url checked too early

### ISSUE THREAD

**Issue by ngavard** [angular/angular.js#13847]
Hi angular team,
Since 1.4.9 and the following fix https://github.com/angular/angular.js/commit/c5bf9daef6dfdb3e4a2942c21155a9f67d92e237
We cannot call $http any more.
Indeed, we have an interceptor that create the config.url parameter but the fix above check config.url too early, before the call to the interceptor.
Is there a way to postpone this test after the interceptor is called ?

Thanks for any comment on this.

**Comment by Narretz** [comment]
I see. But that just means you have to call $http with an empty string if you set the url later.

**Comment by petebacondarwin** [comment]
The workaround is very straightforward for this unusual case, so this is a won't fix.
