### ISSUE TITLE
ngRoute: Resolve properties not immediately available on the $scope object

### ISSUE THREAD

**Issue by jamesfer** [angular/angular.js#13844]
Resolved properties of a route are added to the `$scope` object under the name `$resolve` (unless otherwise changed by the `resolveAs` setting), however, the `$resolve` object is not present when the controller function is first executed (it is added a few milliseconds after).

[Here is a plunker](http://plnkr.co/edit/VQuUUACMSjOCypzx8fNt?p=preview) of the problem (an edited version of the route example in the docs).
When `BookController` loads, it immediately tries to access properties from `$scope.$resolve` but it is undefined. 

One of my routes is used for both creating a new resource and editing an existing one as they both use the exact same form. The only difference is that when you are editing an existing object, it is fetched from the server in the `resolve` section of the route definition. In the route controller, I cannot inject it like a normal resolve property because it is not present all the time. So I wanted to access it via the `$scope`, so I can fill the form with existing data.

**Comment by petebacondarwin** [comment]
The aim of the `$resolve` property is to help with simple scenarios where a controller is not needed.
It is added as part of the `ngView` directive: https://github.com/angular/angular.js/blob/master/src/ngRoute/directive/ngView.js#L278

If you want to have access to these values in your controller then you can either:

* have them injected directly into your controller
* access them via `$route.current.locals (which is the same object as `$resolve`

That being said, it might be possible to move the attachment to before the controller is instantiated. What do you think @shahata?

**Comment by shahata** [comment]
I agree `$resolve` is not the right way to go in this use case, I would just inject the values in controller constructor.

**Comment by jamesfer** [comment]
I can't inject them in the controller because the values are given as locals to the injector when the controller function is run.
I think `$route.current.locals` might work for my situation, but I still think the attachment of `$resolve` to the scope should be moved to before the controller is instantiated because its not really possible to use it as it stands now. Although I understand how low priority this fix is.

**Comment by jamesfer** [comment]
After having a look at the source it looks like `$resolve` is set at the same time as the controller is added to the scope using the `$controllerAs` property. This makes sense to me and seems like the intended behaviour. Maybe just close this issue then.
