### ISSUE TITLE
location.reload() redirects to default route in Chrome etc.

### ISSUE THREAD

**Issue by gflohr** [angular/angular.js#13851]
With angular/angular-route 1.4.9 location.reload() behaves differently in Firefox and Chrome.  In our HTML we have:

    <a href="#abcd" ng-click="comeBackHere()"><span>Reload</span></a>

The controller has this code:

    $scope.comeBackHere = function() {
            document.location.reload(false);
    };

In Firefox 43.0.4 a reload is performed, and I stay where I are (in the angular-phonecat app for example at http://localhost:8000/app/#/phones/motorola-xoom).  In Chrome I am redirected to http://localhost:8000/app/#abcd, and then angular-route redirects to the default route http://localhost:8000/app/#phones.

**Comment by gkalpak** [comment]
This seems to have to do with how Firefox (vs Chrome) handles click-handlers on links that also have an `href`. Firefox seems to make a request for the current URL (before applying the `href`), whereas Chrome seems to apply the `href` and then make a request for the new URL.

In your example, Chrome will apply the href (i.e. `#abcd`) and then try to reload the resulting URL (e.g. `http://localhost:8000/app/#abcd`). (Angular's routing will eventually kick in and redirect to the default route.) Firefox, on the other hand, will request the current URL, that is **before** applying the `#abcd` hash (e.g. `http://localhost:8000/app/#/phones/motorola-xoom`), so you will effectively "stay where you are".

Closing as this seems to be a browser-specific thing (not Angular-related).

---
BTW, it doesn't seem like a good idea to have both and `href` **and** a callback that directly manpulates `document.location`. If you need to have a callback that conditionally does a reload (while you still have the `href` for the _default_ case, then you should call `$event.preventDefault()` to stop the browser from applying the `href`. ([Demo pen][1])

[1]: https://codepen.io/ExpertSystem/pen/MKGWKg?editors=1000
