### ISSUE TITLE
Setting ng-animate-children="false" doesn't work within ng-if

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular.js#13865]
See this plunkr:
https://plnkr.co/edit/7qDiemoxZhXMHnf8JpdH?p=preview

There is an ```ng-animate-children="true"``` directive applied to the ```<body>``` element, and a second ```ng-animate-children="false"``` directive applied to a descendant ```<ul>``` element. Despite the presence of this second, overriding directive, the list items continue to animate when their containing panel's visibility is toggled.

**Comment by Narretz** [comment]
Looks like a valid bug. When ng-animate-children is on or inside an ng-if, the value only gets set after the animateQueue checks if the animations are allowed.
