### ISSUE TITLE
ngComponentRouter not calling $routerOnActivate in angular 1.5 when using a template URL

### ISSUE THREAD

**Issue by ericj79** [angular/angular.js#13860]
I know it is not released yet, but I am testing out the new router  with Angular 1.5 RC1. The router file I am using is pulled from Here: https://github.com/brandonroberts/angularjs-component-router/blob/master/lib/angular_1_router.js

The $routerONActivate hook is never called if my router directive uses a templateUrl. When I switch it to just be a template (using an ng-include pointing to the url) it gets called as expected.

**Comment by Narretz** [comment]
@petebacondarwin could you take a look at this?

**Comment by petebacondarwin** [comment]
I will add it to my list of router related tasks for this week and next

**Comment by petebacondarwin** [comment]
We should cross post this to angular/angular since that is where the code is and also where other issues with ng1 component router are being managed

**Comment by vguede** [comment]
@petebacondarwin Yes, duplicate of angular/angular#4633
