### ISSUE TITLE
Date filter returns invalid minute field

### ISSUE THREAD

**Issue by steven10172** [angular/angular.js#13872]
When using the ```date``` filter in ```1.4.2``` the minute field is always off. It seems to want to display ```01``` no matter what the actual value is.

http://plnkr.co/edit/YkMYGtwZDFrYwMQSIKfQ?p=preview

**Comment by gkalpak** [comment]
You were using `HH:MM:ss` instead of `HH:mm:ss` (`MM`: month, `mm`: minutes).
So it was showing `01` for the month, not the minutes.
[Updated demo][1]

[1]: http://plnkr.co/edit/BqVb8myLODMHTQtLm0nV?p=preview
