### ISSUE TITLE
DynamicComponentLoader  and Lifecycle Hooks

### ISSUE THREAD

**Issue by BaruchFisherman** [angular/angular.js#13873]
Hi,
I want to implement  DynamicComponentLoader approach in my Angular2 application.
I'm using  loadIntoLocation function for this behavior.

1. My Application (root) component loads Header component Dynamically, and it's working good,
but when my Header component created, the lifecycle of Header is not called.

**All of them not called:**
OnInit
OnDestroy
DoCheck
OnChanges
AfterContentInit
AfterContentChecked
AfterViewInit
AfterViewChecked

**The only one - is the constructor called.**

Because of this, in my child (Header) component i cannot dynamically creates elements with loadIntoLocation function.

Can you please explain regarding this limitation/bug?

**Comment by gkalpak** [comment]
This is the AngularJS (Angular 1) repo.
You are looking for https://github.com/angular/angular.
