### ISSUE TITLE
Dynamically added item to ng-repeat hold duplicate model

### ISSUE THREAD

**Issue by hemantvikram** [angular/angular.js#13885]
I 'm creating a web page where I 'm providing option to the user to dynamically add line items. I have used angularjs framework (v 1.4.7). I was able to achieve the effect of dynamically adding item to the ng-repeat but the modal seems to be not unique amongst the dynamically added items.

Here is demo code showing the problem:
```
<div>
<form novalidate class="form-vertical" ng-show="!loading" name="detailsForm" ng-controller="DetailsCtrl">

  <div ng-repeat="social in socials track by $index">
      <ng-form name="urlForm">
            <input type="email" name="socialUrl" ng-model="social.email">
            <span class="alert error" ng-show="urlForm.socialUrl.$error.email">Email error</span>
      </ng-form>
  </div>  
  <a title="Add" class="btn btn-success" href="javascript:void(null)" ng-click="addSocial()"><i class="fa fa-plus fa-lg"></i> Add</a>
</form>
</div>
```
```javascript
var myApp = angular.module('myApp', []);

myApp.controller('DetailsCtrl', ['$scope', function($scope) {
    $scope.loading = false;
    var social = {"email":""};

    $scope.socials = [
            { email: 'test@test.com'},
        { email: 'invalid email'}];


  $scope.addSocial = function(){
    $scope.socials.push(social);
  };

    }]
    );
```

I have created the [fiddle ](http://jsfiddle.net/c9vr7ohn/6/)showing the problem. In the fiddle, please add a new item "12345@email.com". Add another item "54321@email.com". You will notice that the item added at first is also changed when typing in the second one.

**Comment by frfancha** [comment]
Your code doing the 'add' push always the same object to the array, then of course changing "this" object displays the change in all views sharing the same object.
addSocial must do: $scope.socials.push({email:""}), creating a new email at each call

You should close this issue, nothing to do with angular.

**Comment by arashkbanan** [comment]
@arashkbanan #miami #kashan #tehran

**Comment by Narretz** [comment]
I agree with @frfancha
