### ISSUE TITLE
Datepicker + modal = doesn't work

### ISSUE THREAD

**Issue by taugustyniak** [angular/angular.js#13889]
check this out:
http://plnkr.co/edit/8IlV0KPwQ3jgxjiWNgZx?p=preview

**Comment by Narretz** [comment]
It looks like this is an issue for https://github.com/angular-ui/bootstrap

**Comment by taugustyniak** [comment]
looks like I got this
http://plnkr.co/edit/FNmbRgEo4tNn17m6jegp?p=preview

**Comment by Narretz** [comment]
Like I said, modal and date picker are part of https://github.com/angular-ui/bootstrap, not angular core. If you don't think this is a bug with angular core, then the issue does not belong here.

**Comment by pkozlowski-opensource** [comment]
Agree with @Narretz that this belongs to https://github.com/angular-ui/bootstrap not here.
