### ISSUE TITLE
Angular filter was not working

### ISSUE THREAD

**Issue by sibascodeking** [angular/angular.js#13881]
**obj.desc | filtername** was working but
 
**obj[f.name] | filtername** was not working where **f.name** is **desc** both are same

**Comment by Narretz** [comment]
This is not enough information. If you think you've found a bug, please post a demo of the problem on plnkr.co or simiar. Otherwise, use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
