### ISSUE TITLE
[1.4/1.5] Cannot delegate `load` events

### ISSUE THREAD

**Issue by marcalj** [angular/angular.js#13892]
http://plnkr.co/edit/rHApia?p=preview

I can only bind to ```load``` event if I create a directive and associate event on it. But within a directive or controller I can't delegate event binding :(

**Comment by gkalpak** [comment]
You can't use event delegation for the `load` event, because it [does not bubble][1].
This is [according to the spec][2].

Closing as this is not related to Angular.

[1]: https://developer.mozilla.org/en-US/docs/Web/Events/load
[2]: https://www.w3.org/TR/DOM-Level-3-Events/#h-event-types-list

**Comment by marcalj** [comment]
Thanks for the references. I didn't know that! Thank you :)
