### ISSUE TITLE
Directive isn't updated when new data comes in if called from another directive

### ISSUE THREAD

**Issue by Vayvala** [angular/angular.js#13897]
I have started to use directives with ui-router:

    $stateProvider
      .state('book', {
        abstract: true,
        url: '/:book',
        template: '<book-tabs />'
      })
      .state('book.about', {
        url: '',
        template: '<book-about />'
      })
      .state('book.stats', {
        url: '/statistics',
        template: '<book-stats />'
      });

Here is one of the directives:

      export default function(app) {
        app.directive('bookStats', function() {
          return {
            restrict: 'E',
            controllerAs: 'statsTab',
            templateUrl: 'book-stats.tpl.html',
            controller: 'BookStatsCtrl'
          };
        });
      };

Inside of `book-stats` directive I want to call `stats-list` directive and pass `book` object, that is empty at first, but has data after HTTP request is fulfilled:

    var vm = this;
    vm.book = {};
    Book.get.single({bookId: id}).then(function(res) {
        vm.book= res; // there is data
        return res;
    });

In template:

    <stats-list book="statsTab.book"></stats-list>

And here is `stats-list` directive:

    export default function(app) {
      app.directive('statsList', function() {
        return {
          restrict: 'E',
          scope: {
            book: '='
          },
          templateUrl: 'stats-list.tpl.html',
          controller: 'CircleRankListCtrl'
        };
      });
    };

**When initialized, `stats-list` directive is called with a empty `book` object as a parameter, and when HTTP request is fulfilled and `book` object gets some data, `stats-list` directive doesn't update.**

**When I tried to call `$scope.$apply` inside of a callback I got `$digest already in progress` error.**

I used Angular 1.4.7 but I also tried to changed it all to Angular 1.5 components.

**Comment by gkalpak** [comment]
@Vayvala, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

--
<sub>If you think you have found a bug with Angular itself, it would be very helpful if you could create a minimal live reproduction (e.g. using CodePen, Plnkr etc).</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
