### ISSUE TITLE
Dynamic html compile does NOT work with module controllers ONLY global controllers

### ISSUE THREAD

**Issue by MackeyK24** [angular/angular.js#13916]
As per the docs for creating dynamic HTML:

```
var $div = $('<div ng-controller="pageController">Message: {{ message }}</div>');
				$(document.body).append($div);

				angular.element(document).injector().invoke(function($compile) {
				  var scope = angular.element($div).scope();
				  $compile($div)(scope);
				  scope.$digest();
				});
```
ONLY works if you define your controller on the window, otherwise you get Error: [ng:areq] Argument 'pageController' is not a function, got undefined

So if pageController defined like this:

```
var app = angular.module('myApp', []);
			app.controller('pageController', function($scope) {
				$scope.message = "Hello World - Part II";
			});
```

DOES NO WORK GIVES ERROR

BUT if you define controller on window like this:
```
			angular.module('ng').config(function ($controllerProvider) { $controllerProvider.allowGlobals(); });

			var pageController = function($scope) {
				$scope.message = "Hello World";
			}
```
IT WORKS FINE.

I would like to be able to use the current "GOOD PRACTICE" of place controllers on the module instead of global window controllers.

WHY does my dynamic HTML NOT see controllers defined on the app module/

**Comment by Narretz** [comment]
Interesting. The example is very old, there's probably been a change there somewhere.
Usually, you also wouldn't get the $compile service like this. You would instead require it in a service or a directive. Or are you compiling DOM elements outside of an Angular app?

**Comment by Narretz** [comment]
Ah, and on which DOC page did you find this?

**Comment by Narretz** [comment]
Can you post the complete failing example in a plnkr.co or similar, please?

**Comment by MackeyK24** [comment]
I finally got dynamic compile OUTSIDE the angular service using the root element injector.

ALSO this stuff would be done AFTER the initial boot strap.

First... I config the app module for dynamic provider support so i can call ANY of the module commands AFTER bootstrap

<pre>
            appModule.config( function($controllerProvider, $compileProvider, $animateProvider, $filterProvider, $provide) {
                    // Provider-based controller.
                    appModule._controller = appModule.controller;
                    appModule.controller = function( name, constructor ) {
                        $controllerProvider.register( name, constructor );
                        return( this );
                    };
                    // Provider-based directive.
                    appModule._directive = appModule.directive;
                    appModule.directive = function( name, factory ) {
                        $compileProvider.directive( name, factory );
                        return( this );
                    };
                    // Provider-based component.
                    appModule._component = appModule.component;
                    appModule.component = function( name, options ) {
                        $compileProvider.component( name, options );
                        return( this );
                    };
                    // Provider-based animation.
                    appModule._animation = appModule.animation;
                    appModule.animation = function( name, factory ) {
                        $animateProvider.register( name, factory );
                        return( this );
                    };
                    // Provider-based filter.
                    appModule._filter = appModule.filter;
                    appModule.filter = function( name, factory ) {
                        $filterProvider.register( name, factory );
                        return( this );
                    };
                    // Provider-based service.
                    appModule._service = appModule.service;
                    appModule.service = function( name, constructor ) {
                        $provide.service( name, constructor );
                        return( this );
                    };
                    // Provider-based factory.
                    appModule._factory = appModule.factory;
                    appModule.factory = function( name, factory ) {
                        $provide.factory( name, factory );
                        return( this );
                    };
                    // Provider-based value.
                    appModule._value = appModule.value;
                    appModule.value = function( name, value ) {
                        $provide.value( name, value );
                        return( this );
                    };
                    // Provider-based constant.
                    appModule._constant = appModule.constant;
                    appModule.constant = function( name, value ) {
                        $provide.constant( name, value );
                        return( this );
                    };
                    // Provider-based decorator.
                    appModule._decorator = appModule.decorator;
                    appModule.decorator = function( name, func ) {
                        $provide.decorator( name, func );
                        return( this );
                    };
                    // Provider-based provider.
                    appModule._provider = appModule.provider;
                    appModule.provider = function( name, providerType ) {
                        $provide.provider( name, providerType );
                        return( this );
                    };
                    // Allow gobal window controllers
                    if (allowGlobals) {
                        $controllerProvider.allowGlobals();
                    }
                }
            );
</pre>

Then to dynamic compile:

Note: controller is a param that comes from parent function to support assign controller to new scope if specified

<pre>
            injectorElement.injector().invoke (function($rootScope, $controller, $compile) {
                    var containerElement = angular.element(container);
                    if (markup != null) {
                        containerElement.html(markup);
                    }
                      var markupScope = containerElement.scope();
                    if (controller != null) {
                        markupScope = $rootScope.$new();
                        var templateCtrl = $controller(controller, { $scope: markupScope } );
                        if (templateCtrl != null) {
                            containerElement.data('$ngControllerController', templateCtrl);
                            containerElement.children().data('$ngControllerController', templateCtrl);
                        }
                    }
                    $compile(containerElement)(markupScope);
                    markupScope.$digest();
                }
            );
</pre>

This is working beautifully now.

**Comment by MackeyK24** [comment]
I finally got dynamic compile OUTSIDE the angular service using the root
element injector.

ALSO this stuff would be done AFTER the initial boot strap.

First... I config the app module for dynamic provider support so i can call
ANY of the module commands AFTER bootstrap

<pre>
            appModule.config( function($controllerProvider,
$compileProvider, $animateProvider, $filterProvider, $provide) {
                    // Provider-based controller.
                    appModule._controller = appModule.controller;
                    appModule.controller = function( name, constructor ) {
                        $controllerProvider.register( name, constructor );
                        return( this );
                    };
                    // Provider-based directive.
                    appModule._directive = appModule.directive;
                    appModule.directive = function( name, factory ) {
                        $compileProvider.directive( name, factory );
                        return( this );
                    };
                    // Provider-based component.
                    appModule._component = appModule.component;
                    appModule.component = function( name, options ) {
                        $compileProvider.component( name, options );
                        return( this );
                    };
                    // Provider-based animation.
                    appModule._animation = appModule.animation;
                    appModule.animation = function( name, factory ) {
                        $animateProvider.register( name, factory );
                        return( this );
                    };
                    // Provider-based filter.
                    appModule._filter = appModule.filter;
                    appModule.filter = function( name, factory ) {
                        $filterProvider.register( name, factory );
                        return( this );
                    };
                    // Provider-based service.
                    appModule._service = appModule.service;
                    appModule.service = function( name, constructor ) {
                        $provide.service( name, constructor );
                        return( this );
                    };
                    // Provider-based factory.
                    appModule._factory = appModule.factory;
                    appModule.factory = function( name, factory ) {
                        $provide.factory( name, factory );
                        return( this );
                    };
                    // Provider-based value.
                    appModule._value = appModule.value;
                    appModule.value = function( name, value ) {
                        $provide.value( name, value );
                        return( this );
                    };
                    // Provider-based constant.
                    appModule._constant = appModule.constant;
                    appModule.constant = function( name, value ) {
                        $provide.constant( name, value );
                        return( this );
                    };
                    // Provider-based decorator.
                    appModule._decorator = appModule.decorator;
                    appModule.decorator = function( name, func ) {
                        $provide.decorator( name, func );
                        return( this );
                    };
                    // Provider-based provider.
                    appModule._provider = appModule.provider;
                    appModule.provider = function( name, providerType ) {
                        $provide.provider( name, providerType );
                        return( this );
                    };
                    // Allow gobal window controllers
                    if (allowGlobals) {
                        $controllerProvider.allowGlobals();
                    }
                }
            );
</pre>

Then to dynamic compile:

Note: controller is a param that comes from parent function to support
assign controller to new scope if specified

<pre>
            injectorElement.injector().invoke (function($rootScope,
$controller, $compile) {
                    var containerElement = angular.element(container);
                    if (markup != null) {
                        containerElement.html(markup);
                    }
                      var markupScope = containerElement.scope();
                    if (controller != null) {
                        markupScope = $rootScope.$new();
                        var templateCtrl = $controller(controller, {
$scope: markupScope } );
                        if (templateCtrl != null) {

containerElement.data('$ngControllerController', templateCtrl);

containerElement.children().data('$ngControllerController', templateCtrl);
                        }
                    }
                    $compile(containerElement)(markupScope);
                    markupScope.$digest();
                }
            );
</pre>


This is working beautifully now.

**Comment by lgalfaso** [comment]
Pasting the relevant parts of the docs present from where the example was taken. Bold added to the important parts.

> Sometimes you want to get access to the injector of **a currently running Angular app from outside Angular**. Perhaps, you want to inject and compile some markup after the application has been bootstrapped. You can do this using the extra injector() added to JQuery/jqLite elements. See angular.element.
> 
> ***This is fairly rare but could be the case if a third party library is injecting the markup.***


With this said, this is not a support forum, so if you need any help please use StackOverflow.
