### ISSUE TITLE
Accessing Control object using ngFormControl on a custom directive.

### ISSUE THREAD

**Issue by amanjain** [angular/angular.js#13929]
I have created a custom directive `<autocomplete></autocomplete>` and I am trying to access a `Control` object as `<autocomplete ngFormControl='controlObjectVar'></autocomplete>`. It raises the following exception: `EXCEPTION: No value accessor for '' in [controlObjectVar in ManagerComponent@38:63]`. Is there a document I can refer to, cause I could not find one..

**Comment by gkalpak** [comment]
This repo is for AngularJS (ng1). You should reopen on https://github.com/angular/angular.
