### ISSUE TITLE
grunt package an error occurred

### ISSUE THREAD

**Issue by hnbzlb** [angular/angular.js#13932]
build\angular.js:4555: WARNING - Throw expression is not a minErr instance.
          throw err;
          ^

build\angular.js:11393: WARNING - Throw expression is not a minErr instance.
            throw e;
            ^

build\angular.js:12901: WARNING - Throw expression is not a minErr instance.
        throw e;
        ^

build\angular.js:16887: WARNING - Throw expression is not a minErr instance.
            throw e;
            ^

build\angular.js:19533: WARNING - If this if/for/while really shouldnt have a bo
dy, use {}
  for (i = 0; numStr.charAt(i) == ZERO_CHAR; i++);
                                                 ^

0 error(s), 5 warning(s)

**Comment by Narretz** [comment]
These are warnings, you can ignore them. The last one should be fixable though.

**Comment by hnbzlb** [comment]
right, thank you!
