### ISSUE TITLE
createInternalInjector.instantiate fails at args.unshift(null) in PhantomJS 1.9.8 (Angular 1.5.0-rc2)

### ISSUE THREAD

**Issue by jsdw** [angular/angular.js#13939]
Our test suite started failing with:

```
[$injector:pget] Provider '$$sanitizeUri' must define $get factory method.
```

When I upgraded to angular 1.5.0-rc2. I tracked the error down to the line

```
args.unshift(null);
```

In angular.js, in the function `instantiate`, which is returned from `createInternalInjector`. With `null`, the object returned from `providerInjector.instantiate(provider_)` (where `provider_` was the function `$$SanitizeUriProvider`) is empty. I imagine PhantomJS, being based on quite an old engine, handles new/bind a little differently.

The fix for me was simply changing the `null` to an `{}`.

Not sure if the version of phantom this fails on is supported but thought I'd bring it up just in case! :)

**Comment by Narretz** [comment]
This sounds similar to https://github.com/angular/angular.js/issues/13794 We don't officially support PhantomJS as a browser, but the good news is that you can simply upgrade to PhantomJS 2 or use a polyfil for whatever is missing. I think it's the same as in the other issue.

**Comment by ivanvpan** [comment]
@jsdw Have you figured out how to fix this? We are getting the same exact error in our test suite after upgrading to 1.5, except we are already on PhantomJS 2 and the error occurs even when we run the tests against Chrome.
