### ISSUE TITLE
HTML output

### ISSUE THREAD

**Issue by ShavidzeT** [angular/angular.js#13933]
How can I display html on output.
For example when I'm trying to show up 
```HTML
<b>text</b>
``` 
it doesn't make a sense, it shows me like a plain text, I'm looking for sulition...

**Comment by 17cupsofcoffee** [comment]
[ngBindHtml](https://docs.angularjs.org/api/ng/directive/ngBindHtml) is what you're looking for - you will need to include [ngSanitize](https://docs.angularjs.org/api/ngSanitize) in your module's dependencies.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

--
<sub>(What @17cupsofcoffee said, sounds about right btw...)</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by ShavidzeT** [comment]
Problem has been solved.. @17cupsofcoffee  Thank's! ;)
