### ISSUE TITLE
IE issue when replacing element contents with directive.

### ISSUE THREAD

**Issue by atrophic** [angular/angular.js#13947]
I'm getting errors with my directive in IE only (v11). It seems to be the "element[0].outerHTML = replacement" that's causing the problem. Here's a plunker: http://plnkr.co/edit/lLHmC4QHzhl24SGxTq5g?p=preview

The code actually still works, even in IE, but it's throwing "Invalid Argument." errors at interpolateFnWatchAction after it renders.

**Comment by gkalpak** [comment]
Replacing the element's `outerHTML` can lead to all sorts of unexpected behavior (potentially including some memory leaks), I'm afraid.
In this case, IE does not like setting `.nodeValue` on a text-node that has been overwritten (e.g. using `innerHTML`/`outerHTML` on its parent). The very fact that angular is trying to set `nodeValue` on a removed text-node is an indication of stale references been unreleased.

I would use a more straightforward implementation, that replaces the elements altogether: [demo plnkr][1].

--
Closing as there's not really much we can do.

[1]: http://plnkr.co/edit/YHFxt1O00T815PexNWNj?p=preview

**Comment by atrophic** [comment]
Your demo plnkr works perfectly. Thanks!
