### ISSUE TITLE
Is angularjs Logo is a trademark?

### ISSUE THREAD

**Issue by TheNightFall** [angular/angular.js#13946]
I don't know where should I ask this, so if this is off-topic I would appreciate if you guide me to the correct place to obtain a response for my question.
We are developing a new product in the company I work for and we want to make T-Shirts with the technologies we used for developing it which is Angularjs, HTML 5 and CSS 3.
I can't find anywhere in the MIT license specification about logo, all I can find is about documentation and code.
Before spending time and money to make the T-Shirt, I would like to know if this is legal.

In any case, hopefully this will help others that could have the same doubts.

P.S: I don't live in USA, my company's country is Brazil.

**Comment by dineshv16425** [comment]
Yes! You can find design files in our github repository, under "angular.js/images/logo" The logo design is licensed under a "Creative Commons Attribution-ShareAlike 3.0 Unported License". Check this link for more information. https://docs.angularjs.org/misc/faq

**Comment by gkalpak** [comment]
Thx @dineshv16425 :smiley:

**Comment by TheNightFall** [comment]
Thank you
