### ISSUE TITLE
🔑 (key) symbol basically destroys Angular $parse. I put it into one of my todo items and it destroyed that list.

### ISSUE THREAD

**Issue by aligajani** [angular/angular.js#13953]

**Comment by Narretz** [comment]
There is no unicode support for $parse. If you put it into a string, then that's different. Can you show how you used $parse with 🔑?

**Comment by Narretz** [comment]
@lgalfaso This might interest you.

**Comment by aligajani** [comment]
Well, folks, to be honest. I just tried to put this in one of my list items (todos as they call it). 

"Major 🔑 (key) alert". And then suddenly, everything was blank. I opened up console.

There were parse errors. I was in shock. I didn't read or see what was happening.

I refreshed the page. To my dismay, the list was blank and there were 539 blank todo items.

But it was completely blank.

This 🔑 (key) got everything messed up.

**Comment by Narretz** [comment]
A simple example shows that a string in interpolated markup is okay: http://plnkr.co/edit/wdLzcCk9Occ3iqemgcw6?p=preview

You'll have to create a demo to show the problem. You can start by modifying the plnkr.

**Comment by lgalfaso** [comment]
I am not able to reproduce the error. Without more information I think there is nothing that can be done.

**Comment by aligajani** [comment]
Alright, I'll try to publish more information on this later.

**Comment by aligajani** [comment]
Okay guys, here's an update. @Narretz @lgalfaso . MySQL's implementation of UTF8 is a lie. It only supports some 5 % of the entire 1.1 million unicode characters. Since I was using Laravel, and it uses UTF8 as default, it falls into that trap. So [here](https://twitter.com/aligajani/status/698982082454880257) I have proposed "utf8mb4" to be the default setting in `database.php` in Laravel's configuration file. `utf8mb4` does the magic. It wasn't an angular issue!
