### ISSUE TITLE
Loading angular-mocks@1.5.0 into PhantomJS causes TypeError

### ISSUE THREAD

**Issue by onlywei** [angular/angular.js#13956]
Hello, I just tried updating to angular@1.5.0 and angular-mocks@1.5.0 and my tests are broken with this error:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: 'Unhandled promise rejection', 'TypeError: Attempted to assign to readonly property.
	Evaluating http://localhost:9876/static/base/public/jspm_packages/npm/angular-mocks@1.5.0/angular-mocks.js
	Evaluating http://localhost:9876/static/base/public/jspm_packages/npm/angular-mocks@1.5.0.js
```

I am using `karma-jspm` to run my unit tests, as described in this repo: https://github.com/gunnarlium/babel-jspm-karma-jasmine-istanbul

Used to work fine with `angular-mocks@1.4.7`.

**Comment by gkalpak** [comment]
It's impossible to tell what might be wrong without a way to reproduce it. Could you create a minimal reproduction of the issue ?

**Comment by Narretz** [comment]
Closing due to lack of feedback.

**Comment by onlywei** [comment]
Hey sorry I got really busy and wasn't able to provide any feedback about this issue for the last two weeks. I'm just picking this back up now, and it looks like even in Chrome, when the file `angular-mocks.js` tries to execute this code:

`angular.mock = {};`

I get the TypeError explained above.

**Comment by onlywei** [comment]
OK I figured it out. It's because my unit test must first load `angular` itself before trying to load `angular-mocks`. This is because I've switched to installing `angular-mocks` and `angular` from NPM instead of bower. For some reason, the `package.json` file of the `angular-mocks` package does not list any dependencies (not even Angular).

**Comment by abobwhite** [comment]
@onlywei Thanks! I had the same import 'angular' issue that was giving me the same error!

**Comment by prasikumbhare** [comment]
i am facing the same problem.. how did you fix it. Thanks in adavance

**Comment by onlywei** [comment]
@prasikumbhare I fixed it with the `1.5.6` release of Angular using this pull request: https://github.com/angular/bower-angular-mocks/pull/22

**Comment by prasikumbhare** [comment]
@onlywei  Thanks so much.. in my case the problem was: i was using **'angularMocks'** in 'paths' section of  requireJS config But in 'shim' section i was referring it incorrectly as **'angular-mocks'**:


   paths: {
        'angular': 'war/lib/angularjs-1.5.5/angular.min',
         '**angularMocks**': 'war/lib/angular-mocks/angular-mocks',
    }
 shim: {
        'angular': {
            exports: 'angular'
        },
        **'angular-mocks'**: {
            deps: ['angular'],
            exports: "angular.mock"
        },
}


Changing in the 'shim' to use **'angularMocks'** fixed the problem..

**Comment by mohitjee15** [comment]
@onlywei was stucks with this for hours, thanks for providing the solution.

**Comment by anthonyettinger** [comment]
@prasikumbhare What file did you put that json in?

**Comment by suryatejahanumandla** [comment]
@onlywei, I'm also facing the same issue, here could see the weird behaviour irrespective of the angular version, it's throwing error. Please check the following error log and let me know, if I'm missing anything.
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: Attempted to assign to readonly property.
at app/bower_components/angular-mocks/angular-mocks.js:17
```
The following code is located at 17th line of the angular-mock 
**angular.mock = {};**

Note:
I'm using angular version **_1.4.8_**

**Comment by Keegan-lee** [comment]
Same error as above, any word on a concrete solution for this?

**Comment by s-uds** [comment]
Using angularJS **1.4.8,** load angular.js before angular-mocks.js in the karma configuration file did the trick for me.

```
        files: [
            //Closure library
            {pattern: 'node_modules/closure-library/closure/goog/base.js', watched: false, included: true, served: true},
            {pattern: './node_modules/closure-library/closure/goog/deps.js', watched: false, included: false, served: false},

            //Angular
            'node_modules/angular/angular.js',
            'node_modules/angular-mocks/angular-mocks.js',
```
