### ISSUE TITLE
Version 1.5.0:restrict 'A' on component() fails silently which might cause a lot of confusion 

### ISSUE THREAD

**Issue by radek-anuszewski** [angular/angular.js#13966]
In early versions of AngularJS 1.5, it was possible to use `restrict: 'A'` for `component()` method, and I used it widely in my code. Breaking change came with [1.5.0-rc.1 quantum-fermentation (2016-01-15)](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-3), where only `restrict: 'E'` became permitted, but I missed it (I think not only me) because I stayed with one of the previous 1.5.0 versions. Today I updated Angular's files to 1.5.0 final release and `components` with `restrict: 'A'` weren't visible and it took me a while to figure out that I have to replace attribute usages to element usages. Maybe, to avoid confusion, it should throw an Error when `component()` method meets `restrict` other than `'E'`?
Thank you in advance for looking on this post.

Best regards,
Radek.

**Comment by petebacondarwin** [comment]
Yes we talked about this recently... I think there might even be a PR somewhere.

**Comment by gkalpak** [comment]
The only relevant PR that I can think of is #13802 (which does not exactly cover this issue, but unsupported CDO properties in general). 

@petebacondarwin, was #13802 what you had in mind ?

**Comment by petebacondarwin** [comment]
Oh yes, @gkalpak that was it. Looks like I wasn't keen. :-/

**Comment by albatrosary** [comment]
Hello, everyone

I tried to implement the Component and Component Router of Angular1.5.It is an error in the difference of the value of the restrict for the Component and Component Router.

ComponentRouter is so as not to accept only 'A'.

(angular_1_router.js)
```javascript
this.controller.$$routeParams = instruction.params;
this.controller.$$template = '<div ' + dashCase(componentName) + '></div>';
this.controller.$$router = this.router.childRouter(instruction.componentType);
```

But Angular1 Component is 'E'.

(angular/angular1.js)
```javascript
      return {
        controller: controller,
        controllerAs: identifierForController(options.controller) || options.controllerAs || '$ctrl',
        template: makeInjectable(template),
        templateUrl: makeInjectable(options.templateUrl),
        transclude: options.transclude,
        scope: {},
        bindToController: options.bindings || {},
        restrict: 'E',
        require: options.require
      };
```
When I say that either, I think that is good to the 'E'.

**Comment by gkalpak** [comment]
@albatrosary, this has been fixed with https://github.com/angular/angular/pull/6796 (the router will create elements, instead of divs). The fix will be included in the next release of the router.

**Comment by albatrosary** [comment]
@gkalpak, Great! ,Thank you.

**Comment by Narretz** [comment]
Since not many people will be affected by the BC from beta to 1.5.0, we'll not gonna log / throw etc. here. Maybe we can do the validation inside the ngHint project, but that's also very low priority: https://github.com/angular/angular-hint/issues/118
