### ISSUE TITLE
this.component is not a function

### ISSUE THREAD

**Issue by huineng** [angular/angular.js#13972]
I'm trying to register a new component using angular 1.5
All works fine except for this last line 

this.component = function registerComponent(name, options) {.........
........
factory.$inject = ['$injector'];
return this.directive(name, factory);  ->   TypeError: this.directive is not a function

**Comment by lgalfaso** [comment]
This is not a support forum, please post your questions in StackOverflow. Thanks!

**Comment by huineng** [comment]
Hi, i nevertheless think this is a bug in your code.
 "return this.directive" changes scope within "this.component".
I solved it be adding var self=this on top and then "return self.directive(name, factory);"
thanks

**Comment by gkalpak** [comment]
@huineng, the problem probably arises from how you are calling the function, so it's not a bug in Angular. E.g.

```js
var componentFn = $compileProvider.component;

$compileProvider.component(...)   // Works (the context is `$compileProvider`)
componentFn.call($compileProvider, ...)   // Works (the context is `$compileProvider`)
componentFn(...)   // Doesn't work (the context is `undefined`)
```
