### ISSUE TITLE
Parent scopes and function arguments

### ISSUE THREAD

**Issue by joeghodsi** [angular/angular.js#13986]
In the plunker below I expect the function `foo` to be called and print "foo foo" but it doesn't get called at all. If you change the names of the functions to be consistent between the three directives, it works. Another oddity is that when it prints the scope and parent scope for each controller, you'll notice that directives `inside` and `outside` have the same parent while in the template, `inside` is a child element of `outside`. Thanks for your time.

http://plnkr.co/edit/Mxb4GYp5jIiLlfSSx1o7?p=info

**Comment by gkalpak** [comment]
This is a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

--
Brief explanation:

Your second observation explains the first. I.e. `inside`'s scope inherits from `myctrl`'s scope, so it's bindings are evaluated against that scope (basically, you are calling `bar(arg)` on `myctrl`'s scope).

Regarding the unexpected scope inheritance: When a directive (e.g. `outside`) has an isolate scope, only the elements in it's template "see" that. `div[inside]` is not in `outside`'s template, so it can't "see" its isolate scope and inherts from its parent instead.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
