### ISSUE TITLE
Bug: Angular moves an element down the tree involuntarily 

### ISSUE THREAD

**Issue by ness-EE** [angular/angular.js#13987]
Bug with moving an element down the tree.

Please review this code and screen shot of the DOM in Chrome.

```
<div id="fp-articles-container">
    <div id="fp-articles">
        <div class="fp-article" data-ng-repeat="value in articles | limitTo: 8">
            <div>
                <div class="fp-image-crop"><img data-ng-src="{{urls.s3}}styles/large/s3/{{value.image.uri}}" /></div>
                <div class="fp-article-padding">
                    <h3 class="fp-centre">{{value.label}}</h3>
                    <p>{{articlesCtrl.getDate(value.timestamp)}}</div>
                </div>
            </div>
        </div>
    </div>
    <div id="fp-pagination" class="fp-centre">
        <div class="fp-page fp-inline-block" data-ng-repeat="page in pages">{{page}}</div>
    </div>
</div>
```

The "fp-pagination" class should sit inside "fp-articles-container", but is pushed below.

![screen shot 2016-02-09 at 18 04 59](https://cloud.githubusercontent.com/assets/9382424/12925761/cdb0b7de-cf57-11e5-9de0-6d3383921076.png)

I've seen this on many other pages that use ngRepeat in Angular 1.4.8

**Comment by Narretz** [comment]
In your code example (not screenshot) fp-pagination is already outside the fp-articles-container. Is this a typo?

**Comment by ness-EE** [comment]
Yes, typo

`<p>{{articlesCtrl.getDate(value.timestamp)}}</div>`

I'll close it thanks!
