### ISSUE TITLE
Date filter (still) shows incorrect month names for Slavic languages 

### ISSUE THREAD

**Issue by Janneman84** [angular/angular.js#13999]
As a follow up of this issue:
https://github.com/angular/angular.js/issues/10247

Languages like Polish and Croatian have different versions of months names depending on the context.

The Angular's localization files now have both versions present ("MONTH" and "STANDALONEMONTH"). But the date filter doesn't seems to be always using the right ones, actually it still only seems to use the "MONTH" version at all times

For example if you use "MMMM" to just get the month's name it should show the version from "STANDALONEMONTH".

Would it be possible to at least make the plain "MMMM" one behave correctly? Because if it does then AngularUI's datepicker will work correctly too. Thanks.

Or introduce a new code, like five M's ('MMMMM') or something for the standalone version so people can choose themselves what version should be used.

I'm on 1.4.9 by the way.

**Comment by Narretz** [comment]
@Janneman84 do you want to give a PR for this a try?

**Comment by gkalpak** [comment]
I couldn't find it properly documented anywhere, but the Closure Library (which we get our locale data from), seem to be using `LLLL` for STANDALONEMONTH (e.g. see [here][1] and in other places in the source code).

I think it's reasonable to use `LLLL` as well. There seems also to be the `LLL` pattern for STANDALONESHORTMONTH, but we are not extracting that information (so I don't think we need `LLL` until someone asks for it - then we can consider it :smiley:).

[1]: https://google.github.io/closure-library/api/source/closure/goog/i18n/datetimeparse.js.src.html#l653

**Comment by Janneman84** [comment]
Using 'LLLL' sounds good, I'm looking forward for a PR or update.

'LLL' for short standalone month doesn't seem really necessary because it's the last part of the month's names that is different so the short versions are the same anyway. Maybe there is an exception somewhere, but at least not in Polish or Croatian.

**Comment by gkalpak** [comment]
> I'm looking forward for a PR or update.

@Janneman84, `LLLL` has been already implemented in #14013 has been merged into `master` and `v1.5.x` :smiley:
It will be available since `1.5.1`. You can try the latest code from master using https://code.angularjs.org/snapshot/angular.js.
