### ISSUE TITLE
Undesirable scroll to the top by $anchorSroll

### ISSUE THREAD

**Issue by DominikKrulak** [angular/angular.js#13995]
I have [this situation](http://codepen.io/DominikK/pen/dGwXxb) - by following anchors in demonstration, it should explain itself.

**Comment by Narretz** [comment]
I don't think that's an effect of anchorScroll. If you are doing `<a href="#">bla</a> then you are telling the browser to scroll to the top of the page. You shouldn't use a link for your open function, you should use a button with ngClick instead. You are not linking anywhere, so an anchor is semantically wrong. You will also confuse screenreaders.

**Comment by DominikKrulak** [comment]
Yes Narretz, you are correct. I did an anchor way because `<button></button>` is not allowed in heading tags. So I had no choice just to use a link. At least it has solved my problem :+1: 
Thanks!

**Comment by Narretz** [comment]
Good that it's solved. You could use a span element with role=button in that case.

**Comment by DominikKrulak** [comment]
What about using `ng-click` straight on heading tag?
