### ISSUE TITLE
AngularJS 1.4.8 & IE10: SCRIPT5009: 'angular' is undefined

### ISSUE THREAD

**Issue by basickarl** [angular/angular.js#13994]
https://code.angularjs.org/1.4.8/docs/guide/ie doesn't really give any good information. 

IE10 doesn't work with the following fiddle: https://jsfiddle.net/basickarl/4behds2y/3/

I'm also running a localhost server (nodejs) and I'm running a `IE10 on Win8` VM from https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/ to test.

I get the following error: `SCRIPT5009: 'angular' is undefined`. I tried setting <meta http-equiv="X-UA-Compatible" content="IE=9,chrome=1"> but still doesn't work. My includes in the body are set:

```
        <!-- angular versions must be the same! -->
        <!--[if gte IE 9]> -->
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-cookies.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js"></script>
        <script src="https://cdn.socket.io/socket.io-1.3.6.js"></script>
        <script src="/js/main.js"></script>
        <!-- <![endif]-->
```
My code and the fiddle linked work both in IE9 and IE11 and all the other major browsers.

**Comment by basickarl** [comment]
I let my Windows 8 software update (on the VM) and now it's working.

**Comment by gkalpak** [comment]
Closing as it seems there's no issue. Sounds more like a temporary network or jsFiddle issue.
Feel free to reopen if there is any indication there might be a permanent error with Angular.

**Comment by basickarl** [comment]
I think it was more connected to Windows 8 and the version of IE10 on Windows 8. In any case if anyone stumbles upon this, update your VM Windows to fix this.
