### ISSUE TITLE
ng-class : HTML keeping old value of a var in ng-class

### ISSUE THREAD

**Issue by ashleymoogle** [angular/angular.js#13997]
Hello :)
I'm using angular.js in an app with lots of websockets events.
I have a HTML element with a variable in the ng-class which is changed if some sockets events are emitted.
When the events are emitted too fast, the scope var is correctly updated BUT the html sometimes keep the old value of the scope var in its class attribute.
Can you help me on that ? thanks :)

**Comment by Narretz** [comment]
What version of angular are you using? Also, a demo app would be good although that might be difficult in that case.

**Comment by ashleymoogle** [comment]
I'm using angular 1.4.4

**Comment by Narretz** [comment]
Please try 1.4.9 and see if this fixes it
Am 10.02.2016 19:43 schrieb "ashleymoogle" <notifications@github.com>:

**Comment by m-amr** [comment]
@ashleymoogle 
 if you are using websockets are setting the new value inside an apply function

     socket.on(''event:name", function(data){
           $scope.$apply(function(){
                   $scope.data = data;
           });
     })

?

**Comment by Narretz** [comment]
Closing due to lack of feedback.
