### ISSUE TITLE
Require angular-mocks

### ISSUE THREAD

**Issue by aciccarello** [angular/angular.js#14000]
I recognize that this change is in the bower repo, but there is a pull request sitting out that that isn't getting much love. Just thought I'd bring it to the maintainer's attention.

This makes angular-mocks require-able like the other angular repos.
angular/bower-angular-mocks#17

**Comment by Narretz** [comment]
The bower repos are generated, so I think the change must be made in this repo somewhere.

**Comment by aciccarello** [comment]
Right, I think the package.json is generated. The other PRs in that repo are on non-generated files though.

I think the file is not named index.js because there are actually 3 separate modules listed (ngAnimateMock, ngMock, and ngMockE2E).

**Comment by aciccarello** [comment]
Upon further investigation, it seems the package.json needs to be updated in the bower repo. My understanding of [publish.js](https://github.com/angular/angular.js/blob/master/scripts/bower/publish.sh#L70) is that the file's version property is updated, leaving everything else.

**Comment by gkalpak** [comment]
I too think that these files are not generated. But the problem remains, that `angular-mocks` exposes 3 modules, not just `ngMock`. (Actually, only `ngMock` and `ngMockE2E` are important).

**Comment by gkalpak** [comment]
BTW, this was decided extensively in #10732.

**Comment by aciccarello** [comment]
Thanks @gkalpak. @petebacondarwin's [comment](https://github.com/angular/angular.js/pull/10732#issuecomment-75225380) goes over how the package.json file is managed in the bower repo.

The remaining question is what should be the default commonJS export. As I think about it, it may not make sense to go with angular/bower-angular-mocks#17 because of the multiple modules. The only alternative would be an index.js file with properties of the module names similar to how @bclinkinbeard [mentioned](https://github.com/angular/angular.js/pull/10732#issuecomment-69760751) in that same thread. I like that style more but it would probably be a breaking change for people using a CommonJS build.

Even if that isn't changed. Someone should look at the other PRs in the bower repo.

**Comment by aciccarello** [comment]
I'm closing this as I think the existing entry file setup is fine because there are multiple files.

The PRs on the repo should still be looked at :wink:
