### ISSUE TITLE
instanceInjector = protoInstanceInjector in $injection module

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/angular.js#14012]
In the createInjector function of  angular.js/src/auto/injector.js (commit 43f7206),

The instanceInjector variable on this line:
Line 663 -> instanceInjector = protoInstanceInjector;  ...variable is overwritten several lines down, by this one.

line 667 -> instanceInjector = protoInstanceInjector.get('$injector');

So is the second line necessary in some use case? I commented it out (line 667) and everything I use AngularJS for seems to work just fine. On the face of it, it looks to be a ref. to the same object, but maybe I'm not seeing something important. And commenting the first one out (line 663) doesn't work of coarse, since the  instanceInjector.invoke() call in  protoInstanceInjector isn't available yet.

It just looks a little odd, so I was curious about what is going on here.

**Comment by gkalpak** [comment]
You linked to the wrong commit. The relevant commit it 29a0598 and the purpose is to enable decorating the `$injector`. It's a quite uncommon usecase, so you're not likely to need it, but that's what the re-assignment is for. See also the test added with that commit, to see what usecase wasn't possible before.
