### ISSUE TITLE
Add ng-alias directive to angular core

### ISSUE THREAD

**Issue by lugovsky** [angular/angular.js#14017]
I'm almost sure, that you have some obvious reason for this question, but unfortunately I wasn't able to find some similar issue on github. Anyway I'm just curious, why Angular core doesn't have directive that works just like ng-init, but executes its expression on every $digest cycle? This would allow to reduce copy-paste in bindings for deep object structures:
```html
<div>
  <div ng-bind="obj.array1[0].anotherProp.anotherProp.array2[5].destinationProp1"></div>
  <div ng-bind="obj.array1[0].anotherProp.anotherProp.array2[5].destinationProp2"></div>
</div>
```
versus
```html
<div ng-alias="deepObjectProp = obj.array1[0].anotherProp.anotherProp.array2[5]">
  <div ng-bind="deepObjectProp.destinationProp1"></div>
  <div ng-bind="deepObjectProp.destinationProp2"></div>
</div>
```

I know, that this is probably not the most elegant way in terms of performance. But when it would come to changes and readability my thoughts that it would be much better. I think this directive would be very helpful for people which know tradeoffs.

Thanks for your time looking into this!

**Comment by SashaSkywalker** [comment]
+1

**Comment by gkalpak** [comment]
It would allow/encourage to put more logic into the template than there should be imo (plus it is super-easy to add as a 3rd-party module).

<sub>TBH, I've used my fair share of similar tricks myself, but I'm proud of it :stuck_out_tongue:</sub>

**Comment by lugovsky** [comment]
@gkalpak In my opinion it would be almost the same as `ngInit` :) 

As for 3rd-party module, I agree here. But in my ipinion this use case is pretty common, that's why it could be moved to core

**Comment by gkalpak** [comment]
`ngInit` has a very specific usecase (and there's no other way to achieve aliasing local `ngRepeat` variables) and even then, it's not one of Angular's proudest moments.

That's not the case with `ngAlias`.

**Comment by lugovsky** [comment]
Okay, never mind then :)
