### ISSUE TITLE
ngMock - injector not attached to $rootElement

### ISSUE THREAD

**Issue by jsuchenia** [angular/angular.js#14022]
Under ngMock when injector was already created it's not connected to a $rootElement, so:
      $rootElement.injector()`
returns an undefined value.

I wish to use $rootElement to create sub-elements for test purposes, then tested piece of code can use:
     `angular.element(localElement).injector()`
to retrieve already initialised injector.

**Comment by jsuchenia** [comment]
As a workaround I can add it to the rootNode by myself, but then I know internals of Angular:
`$rootElement.data('$injector', $injector)`

**Comment by gkalpak** [comment]
Hm...I submitted #14034, but tbh I am not sure why you need to call `.injector()` on elements.
Why can't you just inject the `$injector` (which is so meta and cool :stuck_out_tongue: ) ?

**Comment by jsuchenia** [comment]
@gkalpak My use case is similar to this one from a [angular.injector documentation](https://docs.angularjs.org/api/ng/function/angular.injector), so I have an angular app which is using separate framework for drawing (configured externally from JSON file, so I can't inject injector)
In some elements I wish to use data from other angular services, so I need instance of already initialised angular app, and it's working fine (except under ngMock tests)

**Comment by gkalpak** [comment]
Yeah, 3rd-party libs sound like a valid usecase.

**Comment by matsko** [comment]
@jsuchenia @gkalpak sorry guys to be the bearer of bad news but this fix causes a memory leak in Karma + JQuery (a particular internal Google projects was having an issue with this). Therefore we need to revert this for now until we can have a solution that doesn't use `data()` (or cause a leak). @gkalpak let's chat on Wednesday and figure out something better.

**Comment by gkalpak** [comment]
#14098 fixes the leak. But if you need to revert this go ahead and we'll figure it out later :smiley:

**Comment by gkalpak** [comment]
#14098 has neen merged. It includes the reverted fix Relanded the fix along with appropriate meassures to prevent the leak.

Let's see if something breaks :smiley:
