### ISSUE TITLE
ngChange directive not triggering in Microsoft Edge

### ISSUE THREAD

**Issue by digitalclover** [angular/angular.js#14025]
**Version:** AngularJS v1.4.9

I have a simple character counter function that is triggered by the ngChange directive.  Here's the HTML snippet.  I already have the app and controller defined earlier in the document.

`<textarea ng-model="message" ng-change="charLimit()" maxlength="140"></textarea>`

And the accompanied JS file inside the controller object.
`$scope.charCount = 140;`
`$scope.charLimit = function(){`
`$scope.charCount = 140-$scope.message.length;`
`};`

This code works across all browsers I've tested on so far (Chrome, Firefox, Safari, IE11) but the latest Microsoft Edge (Version: 25.10586.0.0 on Windows 10) shows inconsistent performance. The DOM only reflects the updated value when you highlight the number with the cursor.  The rest of the time, it stays frozen on the same number.

Is there any additional methods I can use to troubleshoot this problem?

**Comment by gkalpak** [comment]
@digitalclover, I couldn't reproduce it. Could you post a live demo (e.g. using CodePen, Plnkr etc) ?

**Comment by digitalclover** [comment]
Looks like the same case on my end.  http://codepen.io/digitalclover/pen/mVvKPw

I suppose there must be something else interfering with the text counter in the actual code I'm referencing.  Its just strange that its only occurring in the Edge browser.

Anyway, thanks for your help.
