### ISSUE TITLE
1.5 Feature: Backport ngOnDestroy (as $onDestroy for example) exactly as ngOnInit ($onInit)

### ISSUE THREAD

**Issue by radek-anuszewski** [angular/angular.js#14020]
In new 1.5.0 release is possible to use [$onInit](https://toddmotto.com/on-init-require-object-syntax-angular-component) hook which is similar to `ngOnInit ` from [Angular 2 lifecycle hooks](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html). It will help with keeping controller's  constructors clean, with initialization logic moved to the `$onInit` method.
I think worth consideration is backport also `ngOnDestroy`, as `$onDestroy` for example.
### Use Case:
In recent project in my company on of the business rules is to send request to device every second (which we have done with timeouts). We [try to stay away as possible from injecting `$scope` to controllers](https://github.com/johnpapa/angular-styleguide#style-y031), but timeouts needs to be cleared when user opens new view or hits back button on mobile device etc... So we solved this with `$scope.$on`:

```javascript
$scope.$on('$destroy', function () {
      viewModel.removeIntervals();
});
```
And it's only one direct usage of `$scope` at this moment. If we have `$onDestroy` hook, code would be like:

```javascript
viewModel.$onDestroy =  function () {
      viewModel.removeIntervals();
});
```

And we can get rid off `$scope` injection completely. Also, it let us keep code closer to Angular 2 syntax.

Thank you in advance for looking on this post.

Best regards,
Radek.

**Comment by dcherman** [comment]
+1, would love to have something like this.

**Comment by shlomiassaf** [comment]
We have a workaround for this, i'll share it.
We use it until it will be supported and it works quite well.

We register our first __run__ block and request the `$injector` service.
We monkey patch the `$injector.instantiate` method and inside register the $onDestory event, if needed.

```
angular.module('app').run(['$injector', function($injector) {
    var $instantiate = $injector.instantiate;
    $injector.instantiate = function (Type, locals, serviceName) {
        var instance = $instantiate.call(this, Type, locals, serviceName);
        if (instance.$onDestroy && typeof instance.$onDestroy === 'function') && locals && locals.$scope) {
            locals.$scope.$on('$destroy', function() {instance.$onDestroy()});
        }
        return instance;
    }
}]);
```

This is a very simple example of the idea, I converted it real time from TypeScript and removed internal utils so I hope its correct.

Its important to note that it will not work on "child" injectors, i.e injectors created using `angular.injector` factory, to support it `angular.injector` should be monkey patched as well, returning a monkey patched version of the injector (using the code above).

This is a very simple hack to support this feature until it lands.

**Comment by poshest** [comment]
Am I correct in saying that the `this.$onDestroy` only gets "converted" into a `scope.$on('$destroy', ...` at the time a component is linked? So if, in a component's code you did 

    $timeout(this.$onDestroy = function ...)

$onDestroy wouldn't actually fire upon component destruction, whereas this

    $timeout(scope.$on('$destroy', function ...))

would get mean the `$destroy` function was called upon component destruction (assuming the destruction happened after the $timeout was processed).

**Comment by gkalpak** [comment]
@poshest that is correct (assuming you meant `$timeout(function() { this.$onDestroy = ... })`).
Basically, right after the controller is instantiated and the `$onChanges()`/`$onInit()`/`$doCheck()` hooks are triggered (if present), the controller instance is checked for `$onDestroy()` and sets up the `scope.$on('$destroy', ...)` listener if necessary.

**Comment by poshest** [comment]
Yes, that's what I meant! OK cool. Thanks again @gkalpak :)

**Comment by dazelpro** [comment]
.
