### ISSUE TITLE
Docs is using old version of angular-bootstrap with click issues in Firefox

### ISSUE THREAD

**Issue by nlwillia** [angular/angular.js#14024]
The [version of angular-bootstrap](https://github.com/angular/angular.js/tree/master/docs/app/assets/js/angular-bootstrap) used by angularjs.org and the documentation site is unspecified, but clearly older than the current 1.1.2 release since nothing has been committed for two years now.

Why does it matter?  Well, anyone using Firefox will have a bad time when trying to open header links in a new tab due to a [click dispatch bug](https://github.com/angular-ui/bootstrap/issues/5051) that wasn't fixed until angular-bootstrap 1.0.0.  Who is really to blame here?  Firefox is clearly doing something different than other browsers, but it creates a real usability issue which angular-bootstrap has finally moved to solve.  However, Angular needs to update its ui-bootstrap version to pick up the change.

It's very frustrating to middle-click or right-click a link and not be able to open it in a new tab, and this has been a problem for Firefox users of the Angular site for years.  Tracking the current ui-bootstrap could break other things, but it shouldn't be allowed to stagnate.

**Comment by Narretz** [comment]
Thanks for reporting.
It's indeed odd that we use a custom version of bootstrap-ui for the docs app / angularjs.org. But the bug in question was only filed and fixed in December 2015, and we never got any reports about this until now, so I'm not really sure why you are so upset. Bugs happen.

**Comment by nlwillia** [comment]
I'm not upset, but I understand that updating dependencies isn't always trivial, and now that there's an upstream solution I want to make it clear that there's a use case for it.  If it helps, one of my first experiences with angular was thinking "why don't the links on their site work right?" which was a source of friction until I understood that it didn't really have anything to do with angular itself.

**Comment by nlwillia** [comment]
Terrific, thanks!
