### ISSUE TITLE
Input blur CSS transition is broken since Angular 1.4.0

### ISSUE THREAD

**Issue by slavinskas** [angular/angular.js#14029]
Usually, when the border transition is set on the input element, border-color smoothly transitions into the set value when element is focused and smoothly transitions out, when blurred.

Since Angular 1.4, the input element with ng-model directive brakes this normal behavior. When element is focused, CSS transition proceeds as usual, but when it’s blurred it jumps to the default value without any smooth transitions. It happens only one time, before ng-touched class is added. Afterwards, all transitions happen as normal.

I’ve created a plunker, where you can find input with ng-model and input without ng-model. Try to select input and blur it. The first time blur on input with ng-model happens without CSS transition.

https://plnkr.co/edit/JitVgK2G3EscNtlS0GPh?p=preview

**Comment by gkalpak** [comment]
Interesting. This seems to be related with the `ng-touched` class being animated in and `ng-untouched` being animated out. During all subsequent `blur` events, there is no class-based animation, so the border animation works as expected.

Maybe @Narretz has some insight (since he has dealt with both `$animate` and `ngModel` extensively :stuck_out_tongue:).

**Comment by slavinskas** [comment]
I updated plunker. It seems that when !important is added next to CSS transition value, blurred transition executes normally.

**Comment by Narretz** [comment]
Interesting. I can only reproduce this in Chrome.

**Comment by gkalpak** [comment]
> I can only reproduce this in Chrome.

Indeed. This seems to be some bug with how Chrome applies style-rules (I'm just guessing of course).

**Comment by Narretz** [comment]
Looks like it might be a problem with animation blocking. The status quo is that the class based animation will see the transition and think it's an animation meant for itself. It will then block any animations / transitions that are added by a possible `ng-touched-add` class by applying a negative transition delay. And it looks like this also blocks the border transition in Chrome, while it doesn't do that in FF.

**Comment by gkalpak** [comment]
So, doesn't the blocking "work" in Firefox ?

**Comment by Narretz** [comment]
I'm not completely sure. It's also possible that it is blocked correctly, and then the unblocking triggers the transition, and then that would be the thing that doesn't work in Chrome.

**Comment by Narretz** [comment]
I just tested in Chrome 61 and this works now! 😮
