### ISSUE TITLE
Stateless component shorthand

### ISSUE THREAD

**Issue by martiansnoop** [angular/angular.js#14038]
I want to start out by saying I love the new `component`, it takes care of so much boilerplate and I've been using it and loving it since I upgraded to 1.5 last week.

I was wondering, are there any plans to support a stateless component shorthand (like [React's stateless function components](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions)) in Angular?

For context, I recently demonstrated a stateless component to my team using the new one-way binding:

```typescript
app.component("greeter", {
  bindings: {
    name: "<"
  },
  template: `<div> Hello, {{ $ctrl.name }}! </div>`
});
```

And I was thinking it would be really cool to be able to do something like 

```typescript
app.statelessComponent("greeter", ($ctrl) => `<div> Hello, {{ $ctrl.name }}! </div>`);
```

I'm not super familiar with how the provider method works, so it's not clear to me what level of difficulty this is. I was considering making a custom helper function to do this, but I figured I'd ask first to see if there are any plans or interest in official support.

**Comment by Narretz** [comment]
I personally don't think even more sugar is needed. Or is there a semantic difference between the stateless helper and the normal helper? Or differently asked, what's stateless about this new syntax?

**Comment by martiansnoop** [comment]
> what's stateless about this new syntax?

Upon reflection, I think stateless might be a less-optimal word in this context. The functionality is not different, it's sugar for a very specific configuration of component: 

* all bindings are one-way (hence dropping the bindings config object)
* the controller only contains bindings; no other functionality is added to it
* returns an inline template
* probably doesn't use transclude or any other config options

The specific example I was attempting to translate was [this one](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#stateless-function-components-in-react) from the React support in Typescript:

```typescript
const Greeter = ({name = 'world'}) => <div>Hello, {name}!</div>;

let example = <Greeter name='TypeScript 1.8' />;
```

That example seems to demo well (people in my office were very excited about it being a one-liner, and then were a little disappointed that we couldn't golf the angular component into a one-liner too), but I accept that it may have limited use outside of a demo.

**Comment by gkalpak** [comment]
```js
const Greeter = ({name = 'world'}) => <div>Hello, {name}!</div>;
```
I was able to golf this to one line :P:

```js
.component('greeter', {bindings: {name: '<'}, template: '<div> Hello, {{ $ctrl.name }}! </div>'});
```

--
Fun aside, I agree with @Narretz that we don't want to start adding syntactic sugar for every concept around. This is getting too specific and what works for your team will not work for another.

Until certain concepts have been established as widely adopted best practices, I think the `.component()` helper provides an appropriate abstraction and in flexible enough to build any custom helpers on top of.

E.g.:

```js
function statelessComponent(moduleName, componentName, bindings, template) {
  bindings = bindings.reduce((aggr, prop) => { aggr[prop] = '<'; return aggr; }); 
  angular.module(moduleName).component(componentName, {bindings, template});
}

statelessComponent('myApp', 'greeter', ['name'], '<div>Hello, {name}!</div>');

// OR
function slc(bindings, template) {
  bindings: bindings.reduce((aggr, prop) => { aggr[prop] = '<'; return aggr; }),
  return {bindings, template};
}

.component('greeter', slc(['name'], '<div> Hello, {{ $ctrl.name }}! </div>'));
```

**Comment by martiansnoop** [comment]
>I was able to golf this to one line :P

OK, fair, golf was a poor choice of words on my part :p

Thanks for the suggestions, I really like the second one. 

It appears that I have the permissions to close this, so I am going to go ahead and do so. Thanks for the prompt response!

**Comment by winnemucca** [comment]
Todd Motto covers this on his blog.  Not sure by the comments if you have checked it out but here is the link https://toddmotto.com/stateless-angular-components/  .
