### ISSUE TITLE
form with ng-submit doesn't work with enter

### ISSUE THREAD

**Issue by DutchProgrammer** [angular/angular.js#14036]
Im building an webshop with angularjs

I found the next bug when you have an simple form with ng-submit, input fields, button with type="submit" and your focus in an input field and press enter.
It's not submitting the form to the ng-submit function but it's doing an GET request and puts all form elements in the URL, what causes that angular doesn't know the URL and redirect the user to the 404 page.

I've created an directive to fix this issue with the following code:

```js
	.directive('form', function () {
    return function (scope, element, attrs) {

    	if (attrs.ngSubmit !== undefined) {
	      element.bind("keydown keypress", function (event) {
	        if(event.which === 13) {
	          scope.$apply(function (){
	          	scope.$eval(attrs.ngSubmit);
	          });

	          event.preventDefault();
	        }
	      });
	    }
    };
	})
```

But it has the side effect that the ng-model where you have pressed enter not to get updated.

So i gues it's better to fix this bug in angularjs ?

I've tested this with older version and with AngularJS v1.4.9

**Comment by gkalpak** [comment]
@DutchProgrammer, could you post the exact code for reproducing the issue (preferrably as a live demo, e.g. using CodePen, Plnkr etc) ?
The unexpected behavior can be caused by a bunch of things (both Angular and non-Angular related).

**Comment by Narretz** [comment]
Closing due to lack of feedback.
