### ISSUE TITLE
Implement lifecycle hooks for directive/component controllers (ng2-style)

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#14030]
I open this issue in order to track/discuss the implementation of lifecucle hooks to directive/component controllers.

--
### Context

In our attempt to improve the upgrade path to Angular 2, it makes sense to allow developers structure their directive/component controllers is a way that is as easy as possible to migrate them to Angular 2 (ideally, there should be no modification of the controllers code necessary).
As part of this attempt, it will be useful to implement some of the [lifecycle hooks available in Angular 2][1]. (Obviously, it isn't necessary (or possible) to implement all of them, due to differences between ng1/ng2 internals.)

--

### Lifecycle Hooks

- [x] `OnInit`: Implemented in `v1.5.0` as `$onInit`.
- [ ] `OnDestroy`: Useful (and probably straightforward to implement). Discussed in #14020.
- [ ] ~~`DoCheck`~~: Not applicable.
- [ ] `OnChanges`: ~~Not applicable.~~ Applicable.
- [ ] `AfterContentInit`: Not sure how much more useful than `AfterViewInit` (in the context of ng1).
- [ ] ~~`AfterContentChecked`~~: Not applicable.
- [ ] `AfterViewInit`: Useful. Discussed in #13991.
- [ ] ~~`AfterViewChecked`~~: Not applicable.

[1]: https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html

**Comment by thorn0** [comment]
Why is `OnChanges` not applicable?

**Comment by gkalpak** [comment]
I'm not sure what I was thinking at the time. Maybe because it's tied to Inputs/Outputs and ng1 doesn't have the same semantics. It would probably be reasonably feasible to implement for '@' and '<' as inputs and '&' as outputs (with a small overhead), but with two-way binding it gets really muddy.

But I definitely be convinced otherwise. One of the main purposes of opening the issue was to get the discussion going.

**Comment by thorn0** [comment]
I'm not sure if 'OnChanges` works with outputs at all. Even though [the docs](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) state otherwise:
> `ngOnChanges` - called when an input or output binding value changes

**Comment by mikeerickson** [comment]
I am unable to get $onChanges to fire regardless what I try.  To further complicate matters, the documentation is VERY vague and there are basically NO examples, etc. online (I am trying to get it working with ES6 modules).

If *anybody* has a working example (with ES6) which you wish to share, I would be greatly appreciative.

Thanks in advance...

**Comment by petebacondarwin** [comment]
I don't have ES6 examples to hand - but here is a project that uses `$onChanges` effectively: github.com/petebacondarwin/ng1-component-demo

**Comment by adrianolsk** [comment]
@mikeerickson 

Looks like $onChanges only watch for changes on simple variables, so in objects it doesn´t do a deep check of the properties it only check if the object reference change.

so if you change the object using angular.copy  it will trigger the $onChanges
or you can inject the $scope and use the $watch function so you could pass the parameter to deep check.

**Comment by petebacondarwin** [comment]
@adrianolsk - absolutely. We made a conscious decision not to watch objects deeply for `$onChanges`. It would add an unwanted performance penalty if your app didn't actually mutate objects, especially if they are large.
Also, what it means for an object to change is sometimes subtle and not that easy to put into a single general algorithm.
Finally, it is worth noting that this is how Angular 2 works as well.

As you suggest, if you really care about tracking deep property changes on your inputs then rather than using `$onChanges` you should use `$scope.$watch(..., true)` where the true indicates that you want to check every property deeply, or use `$scope.$watchCollection(...)`, which will watch for changes only to the first layer of the object/array.

**Comment by samal84** [comment]
Yeah like @adrianolsk mentions, it's probably easiest to just do a angular.copy to create a new object. 

Won't trigger $onChange if you're binding on complicatedObject:
complicatedObject.someProperty = 'new value';

But this will:
complicatedObject.someProperty = 'new value';
complicatedObject = angular.copy(complicatedObject);

**Comment by mazzur** [comment]
@gkalpak @adrianolsk Can you please explain why was doCheck considered not applicable? I think $doCheck hook could be used for cases like deep watching object properties supplementing $onChanges hook. We encountered the need for it in a quite huge project when migrating to 1.5. Still using $scope seems counterproductive if one is planning to eventually migrate to angular 2, and the workaround proposed by @samal84  seems to be a bit of an overhead.

**Comment by petebacondarwin** [comment]
There is actually a PR discussing this feature - #14656 - let's move the discussion there.

**Comment by kirinmurphy** [comment]
Was struggling with this one too.  Came up with an even simpler approach that avoids the overhead of angular.copy() and the step backwards to using $scope.   Just don't deep watch the object.  Add a one way binding directly to the nested property you want to observe in addition to it's parent  $onChanges then works exactly as intended.

**Comment by gkalpak** [comment]
BTW, we now support `$doCheck()` if anyone's intrested :smiley:

**Comment by khullah** [comment]
@kirinmurphy this seems to be the best approach indeed. However, complex objects with nested objects won't work either. You would basically have to break the object in every possible piece that you want to update with. This seems counter productive.

PS: I think from a logical point of view avoiding the extremes is the better option - not just 1 object holding all properties of the controller, nor break it all apart, but 'chunks' of 'main' properties, that associate with general actions/updates from the app (a button click, UX events, etc).

**Comment by samal84** [comment]
@khullah you can deep watch objects if you really want to: http://stackoverflow.com/questions/14712089/how-to-deep-watch-an-array-in-angularjs

Just be mindful of the performance hit.
