### ISSUE TITLE
select postLink overwriting ngModel.$render handler

### ISSUE THREAD

**Issue by iamwill** [angular/angular.js#14048]
@Narretz we just upgraded from 1.5rc0 to 1.5.0 and ran into this issue.

We have a directive that implements ngModel on the select directive. Our directive overrides ngModel.$render to refresh a select box replacement, select2.

This change f7eab8d8fe8cadecaee425f0db0c74e48619310c means that anyone wanting to implement the ngModel controller on a select field can't use $render because the selectpostlink would blow away their handler.

Here is a jsfiddle showing what I mean. Compare between 1.5.0 and 1.5-rc0

1.5.0: https://jsfiddle.net/hejxa6wu/

1.5-rc0: https://jsfiddle.net/6rhvfp3o/

**Comment by Narretz** [comment]
That's what `priority` is for: give your directive `priority: 1` and it will run after the selectDirective has overwritten the $render fn.

**Comment by iamwill** [comment]
Ah yes of course, I tried everything but that. Thank you.
