### ISSUE TITLE
ngPluralize / ngView Documentation bug

### ISSUE THREAD

**Issue by litera** [angular/angular.js#14045]
On the website if you look at **[ngPluralize](https://docs.angularjs.org/api/ng/directive/ngPluralize)** and check usage, you can see that when you use this directive as an attribute it's actually **missing the n-pluralize attribute**.

This is what is written now

``` html
<ANY
  count=""
  when="string"
  [offset="number"]>
...
</ANY>
```

This is what it should be

``` html
<ANY
  ng-pluralize
  count=""
  when="string"
  [offset="number"]>
...
</ANY>
```

> **Note**: I wanted to improve this doc, but this text is not part of ngdoc and I'm not really sure how to contribute this change hence this issue.

**Comment by Narretz** [comment]
This is a bug in angular/dgeni-packages. the usage section uses the params, but it can't handle directives whose attribute selector doesn't take a value (ng-pluralize is a void attribute, and it's not listed in the params). I think this should be handled as a special case in /dgeni-packages/ngdoc/templates/api/directive.template.html

**Comment by litera** [comment]
@Narretz Where is this *Usage* part even documented as it's not part of the ngDoc?

**Comment by Narretz** [comment]
The usage template part is defined in this template: https://github.com/angular/dgeni-packages/blob/master/ngdoc/templates/api/directive.template.html

**Comment by Narretz** [comment]
I've opened https://github.com/angular/dgeni-packages/issues/158 to track this on the dgeni-packages site. It's kind of low priority. Do you want to give this a shot?

**Comment by litera** [comment]
@Narretz I don't think I'd be up for it as I don't know anything about how dgeni works nor do I have the time at the moment to learn about it. If you may provide some sort of info how this template is being processed I may see where to look and maybe come up with a solution.

**Comment by Narretz** [comment]
In the template, there is this block, which renders the usage section.
```
  {% block usage %}
  <h2 id="usage">Usage</h2>
  <div class="usage">
  {% if doc.usage %}
    {$ doc.usage | marked $}
  {% else %}
    <ul>
    {% if doc.restrict.element %}
      <li>as element:
      {% if doc.name.indexOf('ng') == 0 -%}
      (This directive can be used as custom element, but be aware of <a href="guide/ie">IE restrictions</a>).
      {%- endif %}
      {% code %}
      <{$ doc.name | dashCase $}
        {%- for param in doc.params %}
        {$ directiveParam(param.alias or param.name, param.type, '="', '"') $}
        {%- endfor %}>
      ...
      </{$ doc.name | dashCase $}>
      {% endcode %}
      </li>
    {% endif -%}

    {%- if doc.restrict.attribute -%}
      <li>as attribute:
        {% code %}
        <{$ doc.element $}
          {%- for param in doc.params %}
          {$ directiveParam(param.name, param.type, '="', '"') $}
          {%- endfor %}>
        ...
        </{$ doc.element $}>
        {% endcode %}
      </li>
    {% endif -%}

    {%- if doc.restrict.cssClass -%}
      <li>as CSS class:
        {% code %}
        {% set sep = joiner(' ') %}
        <{$ doc.element $} class="
        {%- for param in doc.params -%}
          {$ sep() $}{$ directiveParam(param.name, param.type, ': ', ';') $}
        {%- endfor %}"> ... </{$ doc.element $}>
        {% endcode %}
      </li>
    {% endif -%}

  {%- endif %}
  </div>
  {% endblock -%}
```
For elements that can be used as attributes, it renders an element with the directive name and all of its params as attributes. What we should do: when the directive name is not in the params, add it as an attribute
