### ISSUE TITLE
angular directive on unknown 3rd party website enviroments

### ISSUE THREAD

**Issue by rarutu** [angular/angular.js#14053]
Hi

i have a more complex questions that would most probably not "survive" on stack-overflow so i decided to ask it here :)

I need to create a plugin (piece of embeddable code) ... that will get inserted into client websites ... the code is supposed to build up a google map with custom functionalities on top. I wanted to use angular for this for both subjective and objective reasons :) but i do not have an answer for some of the cases i may encounter.

so i thought i will build up a directive that will transform the code into the map that i need.

my first and biggest pb is that this map is supposed to be responsive so i wanted to use bootstrap for this ...now imagine that i do not know if either bootstrap, jquery or bootstrap are included into the page ... so i need basically a requirements step i need to validate before running the directive ... so if any requirements are missing i need to load them into the current scope ... meaning that if i load bootstrap for example ... it should note destroy the current css of the website the directive is loaded into.

there is one more thing ... theoretically the map can be loaded into a modal ... or a tab inside of a modal ... so there might be functions needs to force and update or to tell the directive to do something specific ... can angular help me achieve this?

thanks,
rarutu

**Comment by Narretz** [comment]
I don't think all of this is very angular specific. Embedding stuff is always difficult, and your best is probably an iframe that gets all the dependencies it needs itself. But I really don't think this is a question that needs to be discussed here. The google group is probably good for discussions like this.

**Comment by rarutu** [comment]
got it thanks :)
