### ISSUE TITLE
input stays invalid when "required" attribute is dynamically unset

### ISSUE THREAD

**Issue by slintes** [angular/angular.js#14055]
Hi,

I have an issue which might be a bug: I have a form with a checkbox and an input field. The input's `readonly` and `required` attributes are set dynamically by the value of the checkbox. Problem is: when the input is readonly and not required, it is invalid (when empty).

Angular version is 2.0.0-beta.6

Example: http://plnkr.co/edit/XM8QTwkr3B4nzc40gEpx?p=preview

Greetings, Marc

**Comment by Narretz** [comment]
Question for https://github.com/angular/angular

**Comment by slintes** [comment]
oh sorry!
