### ISSUE TITLE
angular2.0, how to stop writing "this" anywhere, I prefer write 'scope'

### ISSUE THREAD

**Issue by Awakening-j** [angular/angular.js#14052]
how to stop writing "this" anywhere, I would like it become a global variable, and can be called in internal function, so write directly "heroes, myHero, lastone"

![2016-02-16 14 37 14](https://cloud.githubusercontent.com/assets/8085088/13068910/d513a744-d4ba-11e5-9aef-a9959c1c7a19.png)

**Comment by Narretz** [comment]
This probably belongs in the https://github.com/angular/angular2 repo

**Comment by Awakening-j** [comment]
@Narretz this url not working, https://github.com/angular/angular2

**Comment by Narretz** [comment]
The right one is https://github.com/angular/angular
