### ISSUE TITLE
Binding ignores object keys that begin with '$'

### ISSUE THREAD

**Issue by uriva** [angular/angular.js#14057]
Codepen:
http://codepen.io/uriva/pen/mVoQZg

**Comment by Narretz** [comment]
1. leading $ and $$ are public / private API indicators and you should not use them in your objects for that reason
2. The codepen doesn't show the problem
3. The pen is using a very old version of angular - it shouldn't matter in this case, but please always test with the latest stable.

**Comment by uriva** [comment]
Fixed codepen.

**Comment by uriva** [comment]
Related to #1463

**Comment by Narretz** [comment]
Duplicate of https://github.com/angular/angular.js/issues/6266 Atm, we don't have plans to fix this and I've recently updated the repeat docs to reflect this.
