### ISSUE TITLE
NgSwipe does not support pointer events

### ISSUE THREAD

**Issue by strokyl** [angular/angular.js#14061]
Hello, 

NgSwipe does not work on microsoft surface IE11 when used with ng-swipe-disable-mouse.
This is due to the fact that IE11 does not use [touch events](https://www.w3.org/TR/touch-events/) but [pointer events](https://www.w3.org/TR/pointerevents/).
I took a look at the pointer events API and at ngTouch code, I have a feeling it will not be complicated to add support to the pointer events API.

Is it something already planned ?

**Comment by Narretz** [comment]
This is not planned, but if you like you can open a PR. ngSwipe isn't very high priority, though.
