### ISSUE TITLE
Replace:true support for components() ?

### ISSUE THREAD

**Issue by geroyche** [angular/angular.js#14078]
Components don't support replace: true.
I realize they are eventually meant to facilitate migration to 2.0, but I still wonder whether they shouldn't support replace, seeing how they are 1.x feature.

why am i asking?
i am trying to style my app with a bootstrap template (not angular-ui, just a generic bootstrap css theme) and this:
[https://github.com/angular/angular.js/issues/13805](https://github.com/angular/angular.js/issues/13805)
is a huge issue (also going forward with 2.0 i guess).

**Comment by Narretz** [comment]
-1
Replace is deprecated in 1.x and we encourage people to remove it from their directives. It's buggy and custom elements are actuallt the replacement for replace so to speak. Bootstrap should really fix their css imo.

**Comment by Narretz** [comment]
Yeah, I don't think this is gonna happen.

**Comment by tomer78** [comment]
Angular material and flex css also has major problems with the fact that component/directives are wrapped inside a container tag.
Anyone has an idea how to handle that issue?

**Comment by ASVBPREAUBV** [comment]
@tomer78 I just ran into the same problem.
Did you find a suitable solution ?

**Comment by angelxmoreno** [comment]
Is there at least a work-around ?

**Comment by gkalpak** [comment]
@angelxmoreno, you can use `directive` instead, but keep in mind that `replace: true` is deprecated and not recommended.

**Comment by beazergood** [comment]
I too am experiencing this issue when trying to leverage Angular Material layout structures. My component tags are an intermediary tag which break the layout-fill chain I need in order to achieve the layouts I'm after.  Surely i'm not the only one?! Does anyone have any suggestions?

**Comment by jasonwatt** [comment]
or at a minimum remove the need to a template to have a wrapping html tag. 

this html wrapper in html wrapper BS sucks for flex box design and makes it nearly impossible.

**Comment by aijazkhan81** [comment]
@jasonwatt How do you do that?

**Comment by rajatvijay** [comment]
Yeah @jasonwatt 
How did you do that?

**Comment by jbedard** [comment]
Oops. Wrong button. Dang phone...
