### ISSUE TITLE
$http status code 0

### ISSUE THREAD

**Issue by furyscript** [angular/angular.js#14082]
Hi,

I try to intercept status on error callback of `$http` but i get status 0 instead status 502.
Obviously request break in `OPTIONS`.

CORS is set correctly.

How can I reach to status like `502`?

**Comment by Narretz** [comment]
Please ask support questions on one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by Gillespie59** [comment]
Are you sure that your main request (not the OPTIONS one) is sent ?
Can you share the response of the OPTIONS request ? and your AngularJS
interceptor ?
Thanks

2016-02-19 11:19 GMT+01:00 Daviz <notifications@github.com>:

> Hi,
>
> I try to intercept status on error callback of $http but i get status 0
> instead status 502.
> Obviously request break in OPTIONS.
>
> CORS is set correctly.
>
> How can I reach to status like 502?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/issues/14082>.
>



-- 
Emmanuel DEMEY
Consultant
Zenika
+33 (0)6 47 47 42 02
demey.emmanuel@gmail.com

   - fr.linkedin.com/in/emmanueldemey/


Twitter : @EmmanuelDemey

**Comment by nikinfinity2** [comment]
same issue i am getting.. is there any solution for this
please comment on this. thanks in advance
