### ISSUE TITLE
angular-mocks package.json file does not depend on angular

### ISSUE THREAD

**Issue by onlywei** [angular/angular.js#14087]
This is kind of an issue with JSPM workflow. I seem to be forced to use the bower version of the installation rather than the npm version. Meaning:

`jspm install npm:angular-mocks`

This will install a package that has no idea that `angular` should be loaded before loading `angular-mocks` into the page. Installing from the `bower.json` works because it has the dependency listed correctly.

I prefer installing via npm rather than via bower because we have set up a local NPM cache.

**Comment by petebacondarwin** [comment]
I think that this can be solved using jspm peerDependencies: http://jspm.io/0.17-beta-guide/peer-dependencies.html or possibly a jspm shim dependency.
@onlywei can you take a look and suggest a solution that doesn't involve changing npm dependencies??

**Comment by onlywei** [comment]
@petebacondarwin JSPM's `peerDependencies` feature seems like a way to resolve version conflicts when multiple packages depend on different versions of another package. It doesn't seem to apply here because the `npm` version of `angular-mocks` has no idea that there's a dependency on Angular at all.

**Comment by onlywei** [comment]
@guybedford maybe you have some insight on this?

**Comment by petebacondarwin** [comment]
A JSPM  shim dependency then?

**Comment by guybedford** [comment]
See https://github.com/jspm/registry/commit/94ebcfda771f8cbd1d0d2cb435152dab160829a1 for an example of an Angular override in the registry to shim the package dependency and module dependency (two separate things, the first for install, the second for module loading).

**Comment by petebacondarwin** [comment]
@guybedford - thanks for that. Are you saying that if a similar commit is made for each of the core angular modules then that would solve the problem for @onlywei ?

**Comment by guybedford** [comment]
All that would be needed is the ability for jspm to know that it should load angular first. This can be as simple as the following in the package.json of angular mocks:

```json
{
  "shim": {
    "angular-mocks": {
      "deps": ["angular"]
    }
  }
}
```

Alternatively this can be added with an override into the registry, but putting it in the original repo is preferred.

Note that the above shim config only works for global files - modules that aren't CommonJS or AMD or use a global UMD pattern.

**Comment by petebacondarwin** [comment]
We can add that. @onlywei fancy creating a PR for each of the `bower-angular...` repositories?

**Comment by guybedford** [comment]
There are already some overrides for these repos in https://github.com/jspm/registry/tree/master/package-overrides/github/angular. Checking in those proven configurations into the original repos is definitely worthwhile. It is worth first testing the overrides locally and carefully considering any breaking changes where jspm users are already using these repos.

Just let me know if I can help further at all here.

**Comment by onlywei** [comment]
Thanks @guybedford. @petebacondarwin I will try my hand at this soon, hopefully sometime next week.

**Comment by onlywei** [comment]
@guybedford the `package.json` property is just called `"shim"`? It's not called `"jspm-shim"` or anything namespaced like that?

**Comment by guybedford** [comment]
Yes exactly, more info here - https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#shim-configuration.

**Comment by onlywei** [comment]
@petebacondarwin @guybedford yep, test with that command works. I see the string: `"deps angular";` on line 3 of `angular-mocks.js` with the override.

**Comment by gkalpak** [comment]
Closed via https://github.com/angular/bower-angular-mocks/commit/3f3116c4c74f7397bce13c14e4436ae8ecacc783.
