### ISSUE TITLE
feat(ngAnimate): Animation anchoring: use an element different from the root element

### ISSUE THREAD

**Issue by maximethebault** [angular/angular.js#14084]
Currently, for animation anchoring, ngAnimate uses the root element of the application (where ng-app was defined), aka the body element most of the times.

In many web applications, the scrolling part is not the body element (for instance, using ngMaterial with a md-toolbar, the scrolling part of the page is a md-content element). The problem being, ngAnimate uses the root element's scrollTop to calculate the absolute positioning of the anchor, which messes things up if the scrolling element is not the root element (wrong position). It would be nice to have the possibility to use a custom element for the anchoring animation.

**Comment by petebacondarwin** [comment]
@Narretz - fancy taking a look at this one?

**Comment by petebacondarwin** [comment]
It might be a simple case of changing https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateCssDriver.js#L132 so that it looks up its scroll container rather than assuming it is the body node?

**Comment by Narretz** [comment]
I'll have a look.

**Comment by maximethebault** [comment]
Okay nevermind, ngAnimate uses getBoundingClientRect which computes the absolute positioning correctly regardless of my md-content scrolling. The bug is probably on my side and not on ngAnimate's side, sorry for bothering :/

**Comment by petebacondarwin** [comment]
Thanks for the update @maximethebault - please open another issue if you find it is a fault in ngAnimate.
