### ISSUE TITLE
Server Engine abstraction support

### ISSUE THREAD

**Issue by a-lucas** [angular/angular.js#14081]
Hello, I am trying to get a personal project[ angular-on-server](https://github.com/a-lucas/angular-on-server) working well (on a server side perspective with jsdom). 

On https://github.com/a-lucas/angular.js I'm trying to make a branch engine - 

I had to modify the following services: qFactory, HttpBackendProvider, LogProvider and create a new EngineQueue in order to trigger two $window CustomEvent.

I will update the tests as soon as I get this npm publish sorted  - 

I need angular-on-server to load this modified version of Angular on both client & server ( Universal Angular ) and I am planning to add better support with Angular1@ES6/7

I am not very sure how to handle all this branch names - this can't be a pull request to the orginal Angular. What should I do ?

**Comment by Narretz** [comment]
Sorry, but what exactly is the question? Do you want to integrate your changes into core or ... ?

**Comment by a-lucas** [comment]
I don't think the core need this functionalities, 

I'd rather see it as a core's branch, something like angular.js-engine or angular.js-server.

**Comment by Narretz** [comment]
Okay, but in this repo we only have versioned branches, not feature branches. So we can't keep it in a core branch. We've also no plans for server side angular 1 support, although we appreciate if the community works on this. I think it's best to keep it as a project like you have it now, made available to others via github. There's also another project which reminds me of this: https://github.com/saymedia/angularjs-server

**Comment by Narretz** [comment]
Oh, and since angularjs is MIT licensed, you can simply start with the angularjs code and then make your modifications - you don't need to keep any of our branches or anything.
