### ISSUE TITLE
getting TypeError: Cannot read property 'friends' of undefined when using custom directive in ng-repeat

### ISSUE THREAD

**Issue by glazerjoni** [angular/angular.js#14095]
I can really use some help here. I have 2 custom directives (second one nested in 1st). All the code is running fine except the second directive. When I try to click on Remove button, I get the following error in Dev tools:

TypeError: Cannot read property 'friends' of undefined
    at vm.removeFriend 

I have tried everything and at my wits end but can't figure this out. Can someone assist please? Here is the Plunker:

https://plnkr.co/edit/jmIifQPPO7Xmiw6rVTnM

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by Narretz** [comment]
I agree with @gkalpak, but I had a look at this and you are making some wrong assumptions about the scope hierarchy here. In your removeFriends direcitve, you are assigning the controller to the vm property on the scope, and that means when you try to access vm.user.friends, it accesses your removeFriends controller instead. If you are using controllerAs, you need to be careful that you don't overwrite properties that are already on the scope - the best way to do this is to use an isolate scope.

**Comment by glazerjoni** [comment]
thank you Narretz! I was thinking on the same lines, but I get the same eror on using isolate scope. I guess I am not as conversant with using the controllerAs and bindToController properties. I was trying to avoid using $scope. Anyhoo, this topic is closed :(

**Comment by glazerjoni** [comment]
Aha. The second one makes complete sense and I got it working using & function. However, I am still wondering as to why I cannot use the inherited scope (scope: false). I understand I am muddying the scope but can't seem to fix the code the way it is. Anyhoo, your soln worked. Thanks much!!!
