### ISSUE TITLE
issue with unit-testing directive using karma

### ISSUE THREAD

**Issue by nehaverma8** [angular/angular.js#14102]
I am unit testing my reusable directive in which I am setting some values in my scope and accessing those values in my directive. However, in the directive, the value comes to be empty. Below is the link method of my directive (full code in plunkr)

Link to Plunkr : http://plnkr.co/edit/Y4tQ7UPmTRJnz2hrKDTt

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

--
<sub>From a quick look, you seem to expect `ngModel` to be initialized with the value set via the `value` attribute. This is not how things work, with `ngModel` (and Angular in general). Your data/model is the source of truth not the DOM. If you want to initialize your control to a specific value, you should set the property bound to `ngModel` to that value.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
