### ISSUE TITLE
Connection timed out during cloning or fetching

### ISSUE THREAD

**Issue by Vadorequest** [angular/angular.js#14108]
```
$ git fetch
fatal: unable to access 'https://github.com/angular/angular.js.git/': Connection timed out after 300021 milliseconds
```

This isn't related to angular.js, it's not an angular issue. it's because the repository is so huge I can't download it within the required amount of time. Any workaround? I can't even fetch after downloading the master branch manually and setting the git repo afterwards.
Thanks.

**Comment by Narretz** [comment]
You can use `--depth=<depth>`
https://git-scm.com/docs/git-fetch

**Comment by Vadorequest** [comment]
Thanks; It didn't work while cloning. But it worked when fetching.
