### ISSUE TITLE
`ngMock` breaks during clean-up with mocked `$rootScope`

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#14106]
#13433 introduced `$rootScope` clean-up after each test. The implementation assumes that `$rootScope` will always have a `$destroy()` method, which might not be true for a mocked/decorated `$rootScope`, resulting in an error.

Also discussed in https://github.com/angular/angular.js/issues/13985#issuecomment-186409320.

**Comment by Narretz** [comment]
I think if you are mocking essential services then you need to provide their API surface. I would go as far as recommending against mocking things such as $injector, $rootScope etc.

**Comment by Narretz** [comment]
Ok, I see how this can be confusing if you inject this in a service but you don't actually use any of the functions of the rootScope. So I'm okay with fixing this.
