### ISSUE TITLE
jqlite returns incorrect value for boolean attributes in some cases

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#14126]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
jqlite.attr(attrName) returns the lowercase version of attrName if the element has attrName set as a property. See the discussion in https://github.com/angular/angular.js/issues/14115

* **What is the expected behavior?**
jqlite should always return the actual attribute value like jquery does.

* **What is the motivation / use case for changing the behavior?**
mainly consistency with jquery, because this behavior doesn't seem to cause issues outside of tests.

* **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
versions of Angular? Please also test with the latest stable and snapshot versions.
all versions up to 1.5.0

**Comment by mgol** [comment]
I'll do it as part of the other jQuery changes for 1.6.0.
