### ISSUE TITLE
`Error in resource configuration for action `{0}` when 1 array response received from APIs

### ISSUE THREAD

**Issue by nagen1** [angular/angular.js#14128]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I am not sure if this been asked but didn't find any info in stackoverflow or by searching it. 

Scenario:
I have 2 REST APIs (built on ASP.NET) 
1 - when I search for all list of products using standard query feature, I am getting few records with [ {0}, {1},{2},{3} ] and with ng-repeat UI renders well. 
2 - when I search for a specific record using unique ID passing parameters, I am getting 1 record in {0} without [ ] which shows up as not an array but not, now UI is not showing record and I see response data, an error kept populating in developer tools and when I click on it, navigated to **"Error: $resource:badcfg Response does not match configured parameter"**

Request and Response for both are identical, don't see what's stopping to render. I used both GET and QUERY results on UI was able to see response in developer tools.

Error
Error: [$resource:badcfg] http://errors.angularjs.org/1.4.9/$resource/badcfg?p0=Error%20in%20resource…=array&p3=object&p4=GET&p5=http%3A%2F%2Flocalhost%3A51540%2Fapi%2Ftodoitem
    at Error (native)

**Comment by BobChao87** [comment]
Typically, this response when an instance of `$resource` expects an array and get an object, or _vice versa._

When a `$resource` is made, the `.query()` method expects arrays, and the `.get()` method expects objects. You likely need to switch which method you are using for this request. Based on what you said, you are likely using `.query()` and should be switching to `.get()` for this particular request.

**Comment by gkalpak** [comment]
As @BobChao87 mentioned the error means that your API returns a different type than `$resource` expects (based on the configuration of the used `$resource` action). E.g. your action expects an array and the API returns an object or vice versa.

This sounds like a general support question, though, so please use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
