### ISSUE TITLE
$resolve is not added to the $scope until after the controller is instantiated

### ISSUE THREAD

**Issue by jdforsythe** [angular/angular.js#14134]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
BUG

* **What is the current behavior?**
See my question and the accepted answer at http://stackoverflow.com/questions/35637853/access-angular-route-scope-property-resolve-within-controller-instead-of-view/35647226#35647226

The new $resolve property on the scope added in #134400 works fine when referenced from within the view template. However, the property is not available on `$scope` within a controller unless a `$timeout` is used. Additionally, even using `$timeout` (maybe as a result of using `controllerAs` syntax?) the value can be printed to the console but still does not propagate to the view.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://jsfiddle.net/96dwgjea/1/

* **What is the expected behavior?**
The `$resolve` property should be put on the scope prior to the controller being instantiated.

It would be even better if `$resolve` was available to inject directly into the controller, so using the `controllerAs` syntax I could just do:

    app.config(function($routeProvider) {
      $routeProvider.when('/test'. {
        templateUrl: 'test.html',
        controller: 'TestController',
        controllerAs: 'vm',
        resolve: {
          'stuff': function() { return 'stuff'; },
          'otherstuff': function() { return 'other stuff'; }
        }
      });
    });

    app.controller(function($resolve) {
      this.stuff = $resolve.stuff;
      this.otherstuff = $resolve.otherstuff;
    });

Instead of injecting the whole `$scope`:

    app.controller(function($scope) {
      this.stuff = $scope.$resolve.stuff;
      this.otherstuff = $scope.$resolve.otherstuff;
    });

* **What is the motivation / use case for changing the behavior?**
Many times I need/want to make mutated copies of the resolved properties for use in the view while still retaining the full data set in the controller. I can easily do this the old way, by injecting each individual resolve property, but I have controllers that have a lot of parameters due to having a bunch of resolve properties (think a view with a form containing a bunch of `<select>`s populated with arrays obtained from factories). It would be much cleaner if all of these properties were injectable in one parameter rather than n parameters.

* **Which version of Angular, and which browser and OS does this issue affect?**
1.5.0 - tested on Chrome 48.0.2564.116 m

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)
I will submit a PR to fix the issue of needing the `$timeout`. The issue of having `$resolve` as an injectable would obviously need further discussion.

**Comment by lgalfaso** [comment]
This looks reasonable, PR welcome :)

**Comment by jdforsythe** [comment]
@lgalfaso I have code ready for a PR that would allow using `$resolve` or the `resolveAs` string as an injectable into the controller. Would it be preferable to create a separate issue and PR or just push the code to the same branch?

**Comment by Narretz** [comment]
Isn't this the same as https://github.com/angular/angular.js/issues/14134 which @petebacondarwin and @shahata were against changing this?

**Comment by jdforsythe** [comment]
@Narretz did you mean to reference a different issue? This is #14134

**Comment by Narretz** [comment]
Yes I meanthttps://github.com/angular/angular.js/issues/13844

**Comment by lgalfaso** [comment]
Mm... Yep, this is the same, and there is a very reasonable workaround.
Let's put this on hold until there is some agreement on what is best

**Comment by jdforsythe** [comment]
The Angular Guide states: "Scope is the glue between application controller and the view". I guess it just feels like a bug to have a scope property available to the view that isn't available to its controller.

**Comment by Narretz** [comment]
@petebacondarwin Wdyt?

**Comment by petebacondarwin** [comment]
This information is available in the controller already. See https://github.com/angular/angular.js/pull/14136#issuecomment-190225880

```js
controller: function($route) {
  this.$resolve = $route.current.locals;
}
```
