### ISSUE TITLE
Typescript service class and $rootScope inject

### ISSUE THREAD

**Issue by artaommahe** [angular/angular.js#14152]
Using typescript class for service that injects $rootScope like this
```ts
class Settings() {
  static $inject = [
    '$rootScope'
  ];
  constructor(private $rootScope: ng.IRootScopeService) {}
}
```
will falls with this errors
```
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
Error: [ng:cpws] Can't copy! Making copies of Window or Scope instances is not supported.
```
it happens becasue $rootScope saves as accesible function variable after transpiling
```js
function Settings($rootScope) {
  var _this = this;
  this.rootScope = rootScope;
}
```
and angular trying to [hang watch](https://github.com/angular/angular.js/blob/1c6edd416b4baad0c8b01148f429eb78e0ad7eaa/src/ng/rootScope.js#L801)
```js
watch.last = watch.eq ? copy(value, null) : value;
```
and [falls with copy](https://github.com/angular/angular.js/blob/68f528aa04290609422c0d73eeef2c27c8f9a8f6/src/Angular.js#L863)
```js
if (isWindow(source) || isScope(source)) {
  throw ngMinErr('cpws',
    "Can't copy! Making copies of Window or Scope instances is not supported.");
}
```
based on this staskoverflow question
http://stackoverflow.com/questions/33814040/how-do-i-inject-rootscope-using-typescript-static-injector-pattern/35710099#35710099

**Comment by gkalpak** [comment]
I'm not able to reproduce it ([exaple attempt][1]). Could you post a live reproduction (e.g. using CodePen, Plnkr etc) ?

[1]: https://codepen.io/ExpertSystem/pen/mPyWOr?editors=0011

**Comment by dpogue** [comment]
One nice solution to the general problem of injecting things and TypeScript that we've come up with is to only inject the $injector (if possible).

```typescript
class MyService {
  private $injector : ng.auto.IInjectorService;

  static $inject = ['$injector'];
  constructor($injector : ng.auto.IInjectorService) {
    this.$injector = $injector;
  }

  someMethod() {
    let $rootScope = this.$injector.get<ng.IRootScopeService>('$rootScope');
    // ...
  }
}
```

This avoids needing to have all the injectables you want to use as instance variables on your service.

**Comment by gkalpak** [comment]
On the downside, using the `$injector` might cover up cyclic dependencies.
This is not specific to TypeScript; it's also true with JavaScript.

**Comment by thorn0** [comment]
@artaommahe See [my answer on SO](http://stackoverflow.com/questions/33814040/how-do-i-inject-rootscope-using-typescript-static-injector-pattern/35857489#35857489).

**Comment by Narretz** [comment]
I think this is expected behavior. This could also happen with non-Typescript code. You simply should not watch the whole instance as @thorn0 has written in his SO answer.
