### ISSUE TITLE
ng-options object data sources keys with number type interpret as strings

### ISSUE THREAD

**Issue by HighAley** [angular/angular.js#14150]
Here is a sample controller

```
$scope.estCount = {0: 'N/A', 
                   1: '0', 
                   2: '1-9', 
                   3: '10-99', 
                   4: '100-999', 
                   5: '1000-9999', 
                   6: '10000-99999', 
                   7: '> 100000'};
$scope.count = 2;
```

The select in the looks so

`<select ng-model="count" ng-options="key as value for (key, value) in estCount"></select>`

As you see the property names are numbers. count is a number too. But I get an additional line

`<option value="?" selected="selected"></option>`

If I set the count as string, the right option is selected.
`$scope.count = "2";`

Should the property names stay numbers or not?

**Comment by petebacondarwin** [comment]
Property names are never numbers in JavaScript. They are stored as strings.
`ngOptions` compares using strict equals (`===`), and so `"2" === 2` is false.

**Comment by HighAley** [comment]
petebacondarwin, But this is from [Mozill JavaScript Guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types).

> Additionally, you can use a **numeric** or string literal for the name of a property or nest an object inside another. The following example uses these options.

In my case, it was the best solution, but I had to add much additional code to solve my task because angular doesn't accept the numbers as a property name.

**Comment by petebacondarwin** [comment]
@HighAley - sure you can provide an integer as a key - but internally it will be stored as a string. Try this:

```
var obj = { 0: 'a', 1: 'b', 2: 'c' };
Object.keys(obj).forEach(function(key) {
  console.log(key, typeof(key));
});

for(var key in obj) {
  console.log(key, typeof(key));
}
```

See http://plnkr.co/edit/9UlFuMO0mGyN27QQEuUn?p=preview
