### ISSUE TITLE
input type used in component, ng show noassign error.

### ISSUE THREAD

**Issue by Nipol** [angular/angular.js#14153]
* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

input type and ng-model used on Component on 1.5.0. ng is crash and **noassign event.**
you typed email, and password. every browser error noassign.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

https://jsfiddle.net/Nipol/b3osod2x/3/

* **What is the expected behavior?**

model have to input value.

* **Which version of Angular, and which browser and OS does this issue affect?** 

ng is 1.5.0
safari 9.0.3
chrome 48.0.2564.116
firefox 44.0.2

**Comment by gkalpak** [comment]
This is because you haven't provided the bindings for `lnEmail` and `lnPword`.
Replace: `<usetype></usetype>`
with something like: `<usetype ln-email="myEmail" ln-pword="myPword"></usetype>`
