### ISSUE TITLE
timezone not work in 'ui.calendar

### ISSUE THREAD

**Issue by nithi** [angular/angular.js#14154]
**How to change timezone to local:**
 http://plnkr.co/edit/LM39yL?p=preview. 

 myApp.controller('CalendarCtrl', ['$scope', function($scope){
   var events = [
        { title: "event1", start: new Date(2015, 6, 21) },
        { title: "event2", start: new Date(2015, 7, 31), end: new Date(2015, 8, 02) },
        { title: "event3", start: new Date(2015, 8, 01) },
    ];

    $scope.eventSources = [events];
    $scope.calOptions = {

        editable: true,
        header: {
            left: 'prev',
            center: 'title',
            right: 'next'
        }};
}]);

* when giving start: new Date(2015, 7, 31), end: new Date(2015, 8, 02) it will show 07-Jul-2015 to 01-Aug-2015

**Comment by gkalpak** [comment]
This doesn't seem to be related to Angular core. You should probably ask on `uiCalendar`'s repo.
Or you could ask for help on one [support channels][1] (since this is basically a general support question).

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
