### ISSUE TITLE
when i load one html in other using jquery its not working properly

### ISSUE THREAD

**Issue by binodthakur** [angular/angular.js#14161]
function loadpage(text){
		if (text === 'environments') {
				$('#contentdisplay').load('../html/environments.html');
			}
			;

		};

<div id="contentdisplay">
</div>

I am trying to load html page like this its not working properly. In single when i run only separate html its working fine.

**Comment by gkalpak** [comment]
It's not clear what you are trying to achieve. If you are trying to bootstrap an Angular app asynchronously, you should manually bootstrap it using [angular.bootstrap()][1].

In any case, this sounds like a general support question. Please, use one of the [appropriate support channels][2] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://docs.angularjs.org/api/ng/function/angular.bootstrap
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by binodthakur** [comment]
Thank you for information.
