### ISSUE TITLE
Injecting a constant into another gets undefined

### ISSUE THREAD

**Issue by kikar** [angular/angular.js#14168]
I'm reporting a bug.
When trying to inject a constant into another constant function, it just gets undefined. It should instead inject the other constant

Here is the fiddle demo of the issue. https://jsfiddle.net/kikar/fy39qq1m/

The reason for this behavior is to be able to define a constant based on the value of another one, like API  base url, based on type of enviroment.

Not working in angular 1.5.0 and 1.4.8

**Comment by Narretz** [comment]
This looks like it works as expected. A `constant` is basically a special version of a `value` - they have in common that both are not injectable, they are really just used for the simplest of use cases. I guess the docs should make that clearer.

**Comment by Narretz** [comment]
You should simply use a factory: `  .factory('SECOND', secondConst)`

**Comment by kikar** [comment]
Thanks for the reply. But why can I inject them into a controller if they're _not_ injectable?

**Comment by Narretz** [comment]
I meant you can't inject into them, but you can inject them into other
things. So your example doesn't work because Second can't be injected with
First.
Am 03.03.2016 16:30 schrieb "Gady" <notifications@github.com>:
