### ISSUE TITLE
ng-repeat on a <tr> throws away anything that's not a <td> or <th>

### ISSUE THREAD

**Issue by dandart** [angular/angular.js#14160]
* **What is the current behavior?**
`<tr ng-repeat="...">`

repeats every td and th but plonks anything else before the first repeater contrary to documentation.

e.g. `<tr ng-repeat="names in ['bob','jim']"><td>{{name}}</td><div></div></tr>`

would generate:
`<div></div>
<tr ng-repeat="names in ['bob','jim']">
<td>bob</td>
<td>jim</td>
</tr>`

* **What is the expected behavior?**
I expect the divs to be copied as well despite it being dissuaded HTML - it's not Angular's job to ignore dissuaded HTML (is it?)

* **What is the motivation / use case for changing the behavior?**
Specifically I'm trying to create an expanding table and using the next tr would ruin colouring and screw with the design.

* **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
versions of Angular? Please also test with the latest stable and snapshot versions.

Affects latest stable

**Comment by gkalpak** [comment]
This is not done by `ngRepeat` nor Angular.
It's the browser (enforcing the spec).
