### ISSUE TITLE
multi slot transclusion as attribute

### ISSUE THREAD

**Issue by david2tm** [angular/angular.js#14167]
Hello,

in 1.4.7 I was able to use multi slot transclusion like:
```
<!-- parent.html -->
<div data-my-directive>
  <div data-my-slot>
    <span>Lorem Ipsum</span>
  </div>
</div>

<!-- template.html -->
<div>
  <div data-ng-transclude="mySlot" />
</div>
```

But after upgrading to 1.5.0 it fails, works only like this:
```
<!-- parent.html -->
<div data-my-directive>
  <my-slot>
    <span>Lorem Ipsum</span>
  </my-slot>
</div>
```

I consider it to be a bug.

**Comment by Narretz** [comment]
Multi slot transclusion has only been available in 1.5.x, starting with beta.2. I'm not sure where your issue comes from. The API that landed in 1.5.0 is stable. We did some changes during the beta / rc releases, but what landed in 1.5.0 is final.

**Comment by david2tm** [comment]
You are correct, about it not being there for 1.4.8. Probably assumed it to work as we had ng-multi-transclude attached before.

Can this be changed to feature request, to support attributes as slot names?

**Comment by Narretz** [comment]
Can you please open a new issue for that? We considered this briefly, but it was considered unneeded for most use cases. So make sure to add your use case / why you need slots with attribute lookup.
