### ISSUE TITLE
In AMP Plugin, The attribute image.width has an invalid value

### ISSUE THREAD

**Issue by websiteslabs** [angular/angular.js#14162]
in structured data testing tool i have error validation : "The attribute image.width has an invalid value."

Anyone know whats wrong ?

https://wordpress.org/plugins/amp/

In: "https://developers.google.com/structured-data/carousels/top-stories?" image.width (required) /	Number /	The width of the image, in pixels. / Images should be at least 696 pixels wide.

Thank you

**Comment by Narretz** [comment]
Please use one of these channels for support questions: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question Thanks!
