### ISSUE TITLE
$controller failing in angular 1.5

### ISSUE THREAD

**Issue by rhinoceraptor** [angular/angular.js#14164]
In my unit tests, calling ```$controller``` from ngMocks is now throwing a ```TypeError```.

Here is a stack trace:
```
     TypeError: ($scope,CommentsService,$stateParams,$mdDialog)=>{__cov_hHb9$o2LSNTszpge0wZGsQ.s['3']++;$scope.minimizeComments...<omitted>...;} is not a constructor
      at Object.instantiate (node_modules/angular/angular.js:4619:14)
      at node_modules/angular/angular.js:9870:28
      at node_modules/angular-mocks/angular-mocks.js:2170:12
      at injectController (test/controllers/details/comments-history-details-controller.js:42:3)
      at Context.<anonymous> (test/controllers/details/comments-history-details-controller.js:57:3)


```

Some other context, pretty standard:
```
function injectController() {
  $controller('CommentsHistoryDetailsController', {
    $scope: $scope,
    CommentsService: CommentsService,
    $stateParams: $stateParams,
    $mdDialog: $mdDialog
  });
}
```

My tests were working in 1.4.8, upgrading to 1.5.0 seems to be the cause of this.

**Comment by rhinoceraptor** [comment]
Accidental creation - oops!

**Comment by Narretz** [comment]
Thanks for reporting. There must be something else going on here, because otherwise we would have gotten lots of reports. Can you please try to reproduce the problem, starting with this plnkr: http://plnkr.co/edit/mhxA3CoPe9QcWOvInotG?p=preview

**Comment by Narretz** [comment]
Closing due to lack of feedback,

**Comment by rhinoceraptor** [comment]
Sorry for the delay in responding. I found the issue, I'm putting it here in case anyone else hits it.

I understand this is not a bug due to the way Angular is implemented (```controller as``` syntax).

The problem was using ES6 arrow functions as controller functions, they do not have a ```prototype```.
