### ISSUE TITLE
img ng-src doesn't work as expected with 404 server errors

### ISSUE THREAD

**Issue by danidev** [angular/angular.js#14174]
Hello,

the ng-src binding for error doesn't work as expected if the server responds with an image but the response status is 404.

in a link function on a directive to manage the ng-src events I have this code:

    element.bind('load', function() {
        console.log('image is loaded');
    });
    element.bind('error', function() {
        console.log('image could not be loaded');
    });

From some tests I did, if I have a broken link in the url, the ng-src triggers the error function (even if the status of a broken url is 200) but if I send a status code of 4xx with an image in the response, the error function is not triggered.

Can you check if this behavior is correct (maybe it is a feature of the img element and there are no options to check the header status) and eventually suggest a workaround?

Many thanks in advance,
Daniele

**Comment by Narretz** [comment]
IIrc correctly, this is a problem with the img element and not with angular. The error handler will be called if the response is not an image, the success fn will be called even if there is error status code. Have you done your tests without ng-src? I think they will show the same behavior. As far as I know, there's no workaround for this problem except loading the image via XHR, which will correctly read the status.

**Comment by danidev** [comment]
Hello Narretz, thanks for answering. 
Yes, you're right, the behavior is the same with ng-src or src. 
Probably, for maintaining consistency between these two way to load an image, it is better to leave ng-src working like now and maybe create a custom directive for an image element that load image data with an XHR call.
Thanks again for the answer.
I'm leaving this issue open for now just to see if that topic could be relevant for some other people.

Daniele

**Comment by Narretz** [comment]
Yes, I think a custom directive could be interesting - but not in the core. ;) Feel free to link to such a directive here if you find / create one.
I'm going to close this issue. I think people will still find it when they search for it.
