### ISSUE TITLE
ngModel.$setViewValue not accepting "-$xxx" instead of parenthesis "($xxx)" 

### ISSUE THREAD

**Issue by aarongan** [angular/angular.js#14171]
Thanks, but there is bug if $filter('currency') is returning negative-sign , it is not supported in ngModel.$setViewValue function.

ngModel.$setViewValue("-$50") results below
=> ngModel.$viewValue = ""
=> ngModel.$modelValue = ""

But it works when using parenthesis "()" instead of negative-sign "-".

Please refer to previous issue. Which this is inconsistent accross both ngModel and $filter services. 
https://github.com/angular/angular.js/issues/14163

**Comment by Narretz** [comment]
Can you please provide a fully runnable example, in a plnkr.co or similar?

**Comment by Narretz** [comment]
There's not enough information here to act. Please reopen when you can provide a demo.
