### ISSUE TITLE
Question: why is scope.$destroy not automatically called on directives with isolate scope?

### ISSUE THREAD

**Issue by plong0** [angular/angular.js#14176]
When I have a `restrict: 'E'` directive with an isolate scope, I am wondering why the $scope.$destroy() would not be called automatically when the element is destroyed?

I have seen a [couple](http://www.bennadel.com/blog/2706-always-trigger-the-destroy-event-before-removing-elements-in-angularjs-directives.htm) [articles](http://www.mattzeunert.com/2014/11/03/manually-removing-angular-directives.html) about this.  I just wonder if there is a case that an isolate scope should stay after its element is destroyed?

Assuming it is an isolate scope, would it be a bad idea to include in my directive something like:

    element.on('$destroy', function(){
        scope.$destroy();
    });

**Comment by dcherman** [comment]
Consider a `transclude: element` directive where `element` becomes a comment.  Events aren't triggered on comment nodes, so your scope would never have been destroyed.  I don't think this is something we could generalize, but of course you're free to do this in your own code if necessary.

Explicit scope destruction usually isn't needed except in the case of manual `ngIf` like behavior, or if you're drawing outside the lines of the normal scope hierarchy.

**Comment by gkalpak** [comment]
I would also like to note, that the built-in structural directives do already clean up scopes as needed (e.g. `ngIf`, `ngSwitch`, `ngInclude`, `ngView` etc).
If you are manually removing component from the DOM (e.g. as part of your custom structural directive), you are responsible for cleaning up the scopes (as @dcherman alreayd mentioned).

@plong0, how are the components removed from the DOM in your situation ?

**Comment by plong0** [comment]
Ah that makes sense why it couldn't be generalized.  Thank you for the replies.

I was using configuration options passed to my directive to generate its children dynamically and then $compile + append() them.  So when the base directive is destroyed or the configuration options changed, I would do `generatedElement.remove();`

I've refactored the directive to use ng-ifs in its template.  It's ok for now, but it seems like if the configuration options have many more combinations of attributes I need to apply to the children, the template will end up with a big list of very similar directives with different ng-if condiitions and combinations of attributes.

**Comment by gkalpak** [comment]
You don't have to use `ngIf`s. But if you are compiling and inserting stuff, then you are responsible for cleaning up after you remove that. 

You can simply call `generatedScope.$destroy()` after you remove the element. E.g.:

```js
function parentPostLink(scope, elem) {
  var generatedScope = scope.$new();
  var generatedElement = $compile('...')(generatedScope);

  elem.append(generatedElement);
  ...
  // Some time later
  generatedElement.remove();
  generatedScope.$destroy();
  ...
```

**Comment by gkalpak** [comment]
Closing as it's working as expected.
