### ISSUE TITLE
Cannot use transclude service within a directive's controller when it is required by another directive

### ISSUE THREAD

**Issue by jjenzz** [angular/angular.js#14189]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
The following error is thrown when calling the transcludeFn within a required controller's constructor, $onInit or post linking methods: https://docs.angularjs.org/error/$compile/ctreq

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Simplified example of the code....

HTML:

    <div ng-app="app">
      <m-carousel>
        <m-carousel-slide>foo</m-carousel-slide>
        <m-carousel-slide>bar</m-carousel-slide>
      </m-carousel>
    </div>

JavaScript:

    class CarouselDirectiveController {
      constructor($transclude) {
        $transclude(clone => {
          // do something
        }, null, 'slide');
      }
    }

    class CarouselSlideDirectiveController {
      $onInit() {
        console.log(this.carousel);
      }
    }

    function carouselDirective() {
      return {
        restrict: 'E',
        replace: true,
        controller: CarouselDirectiveController,
        controllerAs: 'carousel',
        template: '<div class="m-carousel" ng-transclude="slide"></div>',
        transclude: {
          slide: 'mCarouselSlide'
        },
        scope: {},
        bindToController: true
      };
    }

    function carouselSlideDirective() {
      return {
        restrict: 'E',
        replace: true,
        transclude: true,
        controller: CarouselSlideDirectiveController,
        controllerAs: 'carouselSlide',
        template: '<div class="m-carousel-slide" ng-transclude></div>',
        scope: {},
        bindToController: true,
        require: {
          carousel: '^^mCarousel'
        }
      };
    }

    angular.module('app.carousel', [])
      .directive('mCarousel', carouselDirective)
      .directive('mCarouselSlide', carouselSlideDirective);
      
    angular.module('app', ['app.carousel']);

This throws the following error: 

https://docs.angularjs.org/error/$compile/ctreq?p0=mCarousel&p1=mCarouselSlide

However, if I comment out the `$transclude(clone => {}, null, 'slide');` then all is good in the world...

CodePen: http://codepen.io/anon/pen/KzdNRE?editors=1011

If I make the transclude optional, you will see that the `console.log(this.carousel)` in the child controller outputs:

```
null
null
Object {} // CarouselDirectiveController
Object {} // CarouselDirectiveController
```

If I remove the transclude the console logs:

```
Object {} // CarouselDirectiveController
Object {} // CarouselDirectiveController
```

* **What is the expected behavior?**

I would expect the child directive to check for it's required controllers after all it's controllers have been constructed (e.g. `$onInit`) so I can use the transcludeFn within a parent controller without causing it's child controller to throw this error.

* **What is the motivation / use case for changing the behavior?**

I have a directive that should only be able to contain a maximum number of a particular child directive. I'm trying to use the transcludeFn to verfiy that there are no more than this maximum and throw an error if there are.

* **Which version of Angular, and which browser and OS does this issue affect?**

Only tested with 1.4.0 (http://codepen.io/anon/pen/NNxpwR?editors=1011) and 1.5.0. All browsers, Mac OS X Yosemite 10.10.5.

**Comment by dcherman** [comment]
For better or for worse, the require/controller hierarchy is determined by the DOM itself, so by calling `$transclude` and not appending the cloned element to yourself, it's failing to find that parent controller since it is not part of the expected DOM structure.

If you inject `$element` and append your clone to that, you should see the error go away.

**Comment by jjenzz** [comment]
@dcherman Ah... thank you. Although, I just want everything to stay where it is. Is there an easy way to get the slot element and re-append it to that? Re-querying the DOM seems a bit dirty:

```
$transclude(clone => {
  angular.element($element[0].querySelector('[ng-transclude="slide"]')).append(clone);
}, null, 'slide');
```

:disappointed:

**Comment by Narretz** [comment]
I assume the slot is not availabel in the cloneAttachFn, since it's expected that you are doing the appending yourself if you use the $transclude fn. In most cases, you wouldn't have an ng-transclude="slot" if you are using $transclude.

**Comment by gkalpak** [comment]
Closing since everything works as expected.
