### ISSUE TITLE
Dynamically Compiling Nested Directives with Templates and Compile Service Does not work

### ISSUE THREAD

**Issue by bbehling** [angular/angular.js#14182]
* **Do you want to request a *feature* or report a *bug*?**
Bug Report

* **What is the current behavior?**
When a parent directive <dirA> compiles children directives <dirB><dirC></dirC></dirB> from an event (button click or on change event of a drop down list), and only when directive B contains a template via  templateUrl, directive C does not compile.

https://plnkr.co/edit/theggRtJlbFj1H4zVUKU?p=info

* **What is the expected behavior?**
Any nested directive that is compiled using the compile service and contains a template via the templateURL property should compile.

* **What is the motivation / use case for changing the behavior?**
I need a configurable web site where nested directives will be defined in a configuration file and compiled completely dynamically. So, I will not know ahead of time what directives the parent directive will compile.

* **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
versions of Angular? Please also test with the latest stable and snapshot versions.
AngularJS v1.4.7
Whatever latest 1.4.x version plnkr is using
Latest versions of Chrome and Firefox

**Comment by dcherman** [comment]
This is working as expected with any directive that uses templates whether they're a templateUrl or not.  In order to do what you're attempting here, you need to use transclusion.  Please read through the developer guide, especially this section:

https://docs.angularjs.org/guide/directive#creating-a-directive-that-wraps-other-elements

creating-a-directive-that-wraps-other-elements

**Comment by lgalfaso** [comment]
@dcherman is spot on, and this is working as expected.

**Comment by bbehling** [comment]
Well hang on before you close this.....

Now If I use the same nested directives, and I DONT use the $compilie service, this works fine.

Example: dirA still compiles dirB, but instead of using an HTML formatted string, '<dirB><dirC></dirC></dirB>', place dirC inside of dirB's template, dirC will compile.

So why do I need transclusion when using the $compile service and don't need it when not using the $compile service?

From what I understand about transclusion, its used to replace the contents of a directive. I'm not replacing the contents of a directive, this is appending one directive into another.

Some hokey this is working by design.

**Comment by lgalfaso** [comment]
when there is a directive that has a template and does not specify `transclude`, implies that the directive will not use the content of the element where the directive is. This is, there is no need to compile it as it will be discarded and replaced with the directive template.

**Comment by bbehling** [comment]
I updated the plnkr to use transclusion, but the dircC template is not added to the dirB template.

dirC controller is never called nor is the link function.
