### ISSUE TITLE
ngOpen can be out of sync

### ISSUE THREAD

**Issue by lgalfaso** [angular/angular.js#14180]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
ngOpen can get out of sync when applied on an element of type `detail`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:yBpEi4).

Check http://plnkr.co/edit/B0axCHYd08I3RXSXz9c0?p=preview

* **What is the expected behavior?**

Here http://plnkr.co/edit/vhkizCkFSWD3PQSTNCb8?p=preview is the same example but with an extra directive that adds some extra boilerplate to fix the issues

* **What is the motivation / use case for changing the behavior?**

Without a fix, `ngOpen` is mostly useless

* **Which version of Angular, and which browser and OS does this issue affect?** Did this work in previous
versions of Angular? Please also test with the latest stable and snapshot versions.

1.5.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by Narretz** [comment]
Dupe of https://github.com/angular/angular.js/issues/3867?

**Comment by lgalfaso** [comment]
#3867 has a workaround that is no longer working in 1.5.x

**Comment by Narretz** [comment]
Still the same issue.
