### ISSUE TITLE
Provide a public API for accessing transclude slots through the transclude function

### ISSUE THREAD

**Issue by SamGraber** [angular/angular.js#14193]
* **Do you want to request a *feature* or report a *bug*?**
Feature

The new multi-transclusion model in angular 1.5 is a big improvement over the original method. However, there are still some cases where using ngTransclude doesn't satisfy the use case. An example would be a tab control that wants to transclude in its header, body, and footer, and provide only the header to the tabset control for display. In these cases it would be ideal if there was a way to call the transclude function to get a single transclude slot.

I noticed that the following is possible:
```
transcludeFn(cloneAttachFn, null, 'slotName');
transcludeFn(scope, cloneAttachFn, null, 'slotName');
```
but I don't know if this was meant to be a public API or whether this functionality will be supported to later version of Angular 1.

**Comment by SamGraber** [comment]
Example usage: https://github.com/SamGraber/TypeScript-Angular-Components/blob/1bac3d8d23073e66ece7d82fca0f46ec094192e5/source/components/tabs/tab.ts

**Comment by jjenzz** [comment]
It seems it is meant to be public as it is documented in the Angular docs:

https://code.angularjs.org/1.5.0/docs/api/ng/service/$compile#-controller-

**Comment by gkalpak** [comment]
@jjenzz pointed out, since it's documented, it's public API.
Closing. Thx @jjenzz

**Comment by SamGraber** [comment]
That's exactly what I was looking for. Thanks!
