### ISSUE TITLE
ng-include src="chrome://..." does not work in Firefox extension

### ISSUE THREAD

**Issue by godmar** [angular/angular.js#1419]
That's because it returns a status code 0, even though the response is there, just like file:// URLs

See https://github.com/angular/angular.js/blob/master/src/ng/httpBackend.js#l96-97

Could you add <code>|| protocol == 'chrome'</code>?

**Comment by gkalpak** [comment]
It is not exactly clear what problem you were facing. In any case, the issue is pretty old and the code has evolved since then, so it is likely not a problem any more.

<sub>If you are still facng problems, please open a new issue (with more details).</sub>
