### ISSUE TITLE
ng-minlength when completes then counter updates ....it doesn't updates initially.  what should be the issue .

### ISSUE THREAD

**Issue by atul121001** [angular/angular.js#14197]
<div class="col-xs-12">
        <div class="form-group">
        <label class="_500">Title of the {{ ::CreatePostVm.postTypeTitle }}</label>
        <input name="postTitle" type="text" autofocus ng-model="CreatePostVm.post.title" placeholder="Write the title of your {{ ::CreatePostVm.postTypeTitle }} here..." ng-minlength="10" ng-maxlength="100" minlength="10" maxlength="100" required class="form-control" />
       <div class="row">
           <div class="col-xs-12 col-xs-8">
               <div ng-messages="createPost.postTitle.$error" role="alert" class="ng-validation-messages m-t-xs">
                   <div ng-message="required">Title is needed to summarize your {{ ::CreatePostVm.postTypeTitle }}</div>
                   <div ng-message="minlength">Title should be minimum 10 characters long</div>
                   <div ng-message="maxlength">Title should be maximum 100 characters long</div>
               </div>
           </div>
           <div class="col-xs-12 col-xs-4">
               <div class="helper-text text-right">
                   <span class="small text-muted">
                       <span>{{ CreatePostVm.post.title.length || 0 }}</span>/100
                   </span>
              </div>
           </div>
      </div>
  </div>
</div>
angularjs

**Comment by Narretz** [comment]
Sorry, this is not a good issue description. Please provide a good description of the problem and a minimal example. If this is a support question, please use Stackoverflow or the google groups.
