### ISSUE TITLE
bug Chrome 48/49 under Windows 10 ignores one time binding

### ISSUE THREAD

**Issue by lukaszTrackback** [angular/angular.js#14203]
If I run simple code under Windows 10 Chrome (tested on angular 1.4.9 and 1.5.0):

`<li ng-repeat="artist in ::main.beatles">
         <a href="" ng-click="main.removeArtist('beatles', $index);">
             {{ artist.name }}
          </a>
    </li>`

and controller:

     ' function MainController() {
        this.beatles = [{
          name: 'John Lennon'
        }, {
          name: 'Paul McCartney'
        }, {
          name: 'Ringo Starr'
        }, {
          name: 'George Harrison'
        }, {
          name: 'Pete Best'
        }, {
          name: 'Stuart Sutcliffe'
        }];

        this.removeArtist = function (band, index) {
          this[band].splice(index, 1);
        };
      }

      angular
        .module('app')
        .controller('MainController', MainController);`

I expect that html won't be updated even though `main.beatles` will change and it work like that in most of the browser but not Windows 10 Chrome.

**Comment by Narretz** [comment]
I can't reproduce this in this plnkr: http://plnkr.co/edit/kJldlhnZF9hnUfkRbqSx?p=preview Can you please try and create a demo that shows this problem?

**Comment by lukaszTrackback** [comment]
My bad I didn't tested it well enough. The problem is caused by AngularJS Batarang Chrome addon.

**Comment by Narretz** [comment]
Hm, okay that's different. I still can't reproduce it with Chrome 49 on Win7. I doubt it's a Win10 specific problem Can your reproduce with the plnkr I linked? Do I need to follow specific steps? I just enabled the Batarang and then clicked an item, but it wasn't removed.

**Comment by lukaszTrackback** [comment]
It seems that batarang doesn't work for plnkr (doesn't show any information for provided demo) so this is why it doesn't break it. This is how it looks with batarang on and off on my localhost (incognito = batarang off):
![angularonetimechrome](https://cloud.githubusercontent.com/assets/16818253/13670158/184180e2-e6c0-11e5-83a8-d88d76625478.gif)

**Comment by Narretz** [comment]
Ok, now I see it. Can you please open an issue in batarang repo? https://github.com/angular/batarang/issues
