### ISSUE TITLE
Request: angular.isPromise helper since $q.prototype !== Promise

### ISSUE THREAD

**Issue by nlwillia** [angular/angular.js#14209]
In angular 1.5.0, if I want to test a value to see if it is a promise, I can't just say `x instanceof Promise` because the promises created by $q do not inherit from the native Promise implementation.  I don't know if it would be practical for $q to extend Promise.  If not, it would be useful if angular provided an `angular.isPromise(p:any): boolean` utility function that would return true for both $q and native promises.

**Comment by Narretz** [comment]
It can't inherit from promise, because not all supported browsers feature Promise. As for a helper, we don't really want to expose more public helper functions - only if we have internal use for them. So I would say the best idea is to write your own helper fn.

**Comment by gkalpak** [comment]
BTW, in the latest versions (I don't remeber exaclty since when), the promises created with `$q` are instances of `$q`.
So, your helper would be as simple as:

```js
.factory('isPromise', function isPromiseFactory($q, $window) {
  return function isPromise(val) {
    return (val instanceof $q) || ($window.Promise && (val instanceof $window.Promise));
  };
}) 
```

**Comment by nlwillia** [comment]
#13545 looks like it landed in 1.5.

Promise detection is an issue for external code trying to interop with angular.  Just getting access to $q externally is difficult and hackish.  `angular.injector(['ng']).get('$q')` is not going to return the same $q instance as may have been injected in the module that returned the result in question which means that instanceof still won't work and `then` while also ugly remains the most reliable approach.

The scenario where this is biting me is a jquery widget with an event callback that I'm wiring in angular and returning a router navigation promise.  I'm trying to minimize the extent to which the widget knows it's talking to angular, but the lack of a standard promise means `then` checking.  A top-level angular method isn't ideal either, but it would encapsulate the detection logic until someday when hopefully instanceof becomes a viable option.  (I guess checking for the presence of a global Promise--which could be native or a polyfill--and adding it to the prototype chain of $q isn't workable?)

**Comment by gkalpak** [comment]
No, we can't arbitrarily add things to the prototype chain. This might break any time.
`.then()` seems the way to go then, indeed :)

FWIW, our internal `isPromiseLike()` helpers looks like this:

```js
function isPromiseLike(obj) {
  return obj && isFunction(obj.then);
}
```

which in native JS translates to:

```js
function isPromiseLike(obj) {
  return obj && (typeof obj.then === 'function');
}
```

**Comment by wesleycho** [comment]
This sounds like this isn't likely to be added given comments here - would it be worthwhile to close this issue?
