### ISSUE TITLE
$setTouched() in directive issue

### ISSUE THREAD

**Issue by rvarbanov** [angular/angular.js#14205]
* **What is the current behavior?**
When you use a directive to apply $setTouched() on an element it does not work

* **If the current behavior is a bug, please provide the steps to reproduce and, if possible, a minimal demo of the problem** 
[Demo of the issue](http://codepen.io/radi/pen/NNNNxj)
To reproduce the issue, please go to the codepen and:

1. With your mouse select a "Favorite Make".
2. Skip the "Favorite Model" and don't touch it!
3. With your mouse select the "Name" input and enter some text.
4. Hit tab to go to the "Email" input and do not enter anything.
5. Hit tab on your keyboard to go to the "Submit" button.
6. Hit space on your keyboard to submit the form.

You will only be able to reproduce it if you follow the steps!

You should observe that the Favorite Model select is focused, but is not touched ($touched = false) and the ng-message not displayed.

* **What is the expected behavior?**
After submitting the form, the Favorite Model should be focused, "touched" and the ng-message displayed.

* **What is the motivation / use case for changing the behavior?**
Make $setTouched() work in a directive as expected.

* **Which version of Angular, and which browser and OS does this issue affect?** 
Tested on 1.4.8 and 1.5.0 and you should be able to reproduce in all Chrome, FF, and IE.

**Comment by Narretz** [comment]
Since your are listening to the `submit` element, anything that happens in the listener callback happens outside of the digest cycle and angular doesn't know the $touched status of the form fields have changed (and it won't update the classes). You have to wrap the setTouched code into a scope.$apply:

        scope.$apply(function() {
          angular.forEach(form.$error, (field) => angular.forEach(field, (errorField) => {
            
              errorField.$setTouched()  
           }));
         });

**Comment by rvarbanov** [comment]
Thank you very much, @Narretz !
