### ISSUE TITLE
$location or component templateUrl bug

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular.js#14201]
If I set $location as application.run dependency or if I set templateUrl (async template) router doesn't work.
http://plnkr.co/edit/kXcik8znN5HMp6ohRuMA?p=preview

If you remove problem dependency or change templateUrl to template everythink works correct.

**Comment by Narretz** [comment]
I've answered on the linked issue and I think it's a ui-router bug. At least the debugging should be done by someone who knows the ui-router.

**Comment by gkalpak** [comment]
Closing as this is indeed a `uiRouter` issue and has been fixed in `v1.0.0alpha0` of `uiRouter` (see https://github.com/angular-ui/ui-router/issues/2574).
The easy work-around for those who can't upgrade, is to instantiate `$state` early (e.g. inside a `.run()` block).
