### ISSUE TITLE
browser refresh triggers xhr onabort causing template load failure

### ISSUE THREAD

**Issue by banderberg** [angular/angular.js#14219]
I think this is a bug.  I can reproduce it in Chrome and Firefox but not IE.

When refreshing the browser while angular is in the middle of loading templates, xhr object raises abort event, resulting in the following error:

`Error: [$compile:tpload] Failed to load template: view2/view2.html (HTTP status: -1 )
http://errors.angularjs.org/1.4.9/$compile/tpload?p0=view2%2Fview2.html&p1=-1&p2=
    at angular.js:68
    at handleError (angular.js:17959)
    at processQueue (angular.js:14997)
    at angular.js:15013
    at Scope.$eval (angular.js:16257)
    at Scope.$digest (angular.js:16075)
    at Scope.$apply (angular.js:16365)
    at done (angular.js:10791)
    at completeRequest (angular.js:10995)
    at XMLHttpRequest.requestError (angular.js:10944)`

Reproducing this is pretty easy.

1) Install the angular-seed from github
2) Host the angular-seed website - I've used IIS and Nodejs and reproduced this with both
3) Browse the website in Chrome (49.0.2623.87 m)
4) Open Chrome dev tools and view console tab
5) Refresh the website and while it's loading hit refresh again - this may take several tries, it is very much related to timing.  Too early or too late won't work - you have to refresh at the right time during the template loading - I've gotten it down to where I can get it to happen just about every time I try.
6) Watch for the error above.

Expected behavior is that no matter how often I refresh or when, the website should load properly with no tpload errors.

Please try to reproduce this and give me your thoughts, it's driving me crazy.  I thought about recording a little screen capture video showing me reproducing it.. if that would be helpful let me know.

-Barry

**Comment by Narretz** [comment]
So far it sounds like expected behavior. Why is this a problem? When you reload the page, everything gets reloaded, so any errors shouldn't have any consequences.

**Comment by banderberg** [comment]
Well, actually if you don't hit refresh again after the refresh that triggered the tpload error, then you get empty content on the screen where the view should have been rendered, so it's a pretty huge issue.

We have a production AngularJS application that is exhibiting this behavior and it's impacting our customers.

I boiled the issue down to reproduce it just using the angular-seed website.

**Comment by Narretz** [comment]
I still don't understand why the error breaks the site loading. Refreshing the site should cause aborting requests of the currently running template requests, but since you are reloading the whole site, the requests of the next page load should not be affected. 
I'll try to reproduce the behavior.

**Comment by gkalpak** [comment]
This sounds more like a browser issue. Not something Angular-related.
@banderberg, are you able to reproduce it on the latest versions ?

**Comment by massimocode** [comment]
@banderberg we are facing this issue as well. Do you have any more information or maybe a workaround?

**Comment by gkalpak** [comment]
Closing since we haven't heard from the OP and it doesn't sound like something related to Angular anyway. Happy to reopen/investigate if we have more info.

**Comment by massimocode** [comment]
I have replicated this by doing the following:
1) Clone the angular-seed from github
2) Host the angular-seed website by running `npm start`
3) Open the website in Firefox (v49.0.1, latest)
4) Open the dev tools and view console tab
5) Refresh the website and while it's loading hit refresh again - this may take several tries, it is very much related to timing. Too early or too late won't work - you have to refresh at the right time during the template loading - I've gotten it down to where I can get it to happen just about every time I try.
6) Watch for the error in the OP

I have not yet been able to replicate in latest Chrome or Edge but will keep trying.

Interestingly, I also saw this error in Firefox doing the whole random refresh thing:
```
Error: [$injector:modulerr] Failed to instantiate module myApp due to:
[$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=myApp
minErr/<@http://localhost:8000/bower_components/angular/angular.js:69:20
module/<@http://localhost:8000/bower_components/angular/angular.js:2006:31
ensure@http://localhost:8000/bower_components/angular/angular.js:1930:46
module@http://localhost:8000/bower_components/angular/angular.js:2004:24
loadModules/<@http://localhost:8000/bower_components/angular/angular.js:4436:36
forEach@http://localhost:8000/bower_components/angular/angular.js:341:25
loadModules@http://localhost:8000/bower_components/angular/angular.js:4420:13
createInjector@http://localhost:8000/bower_components/angular/angular.js:4345:17
bootstrap/doBootstrap@http://localhost:8000/bower_components/angular/angular.js:1677:28
bootstrap@http://localhost:8000/bower_components/angular/angular.js:1698:20
angularInit@http://localhost:8000/bower_components/angular/angular.js:1592:13
@http://localhost:8000/bower_components/angular/angular.js:29017:9
trigger@http://localhost:8000/bower_components/angular/angular.js:3058:17
defaultHandlerWrapper@http://localhost:8000/bower_components/angular/angular.js:3347:9
createEventHandler/eventHandler@http://localhost:8000/bower_components/angular/angular.js:3335:21

http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=myApp&p1=%5B%24injector%3Anomod%5D%20Module%20'myApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.8%2F%24injector%2Fnomod%3Fp0%3DmyApp%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A69%3A20%0Amodule%2F%3C%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A2006%3A31%0Aensure%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1930%3A46%0Amodule%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A2004%3A24%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A4436%3A36%0AforEach%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A341%3A25%0AloadModules%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A4420%3A13%0AcreateInjector%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A4345%3A17%0Abootstrap%2FdoBootstrap%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1677%3A28%0Abootstrap%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1698%3A20%0AangularInit%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1592%3A13%0A%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A29017%3A9%0Atrigger%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A3058%3A17%0AdefaultHandlerWrapper%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A3347%3A9%0AcreateEventHandler%2FeventHandler%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A3335%3A21%0A
angular.js:69:20

```

**Comment by gkalpak** [comment]
angular-seed uses Angular v1.5.x for some time now. These error messages indicate the problem happens with older version. Were you able to replicate with the latest version?

**Comment by massimocode** [comment]
Yep I've replicated both errors using 1.5.8. Here are the errors:
```
Error: [$injector:modulerr] Failed to instantiate module myApp due to:
[$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=myApp
minErr/<@http://localhost:8000/bower_components/angular/angular.js:68:12
module/<@http://localhost:8000/bower_components/angular/angular.js:2082:17
ensure@http://localhost:8000/bower_components/angular/angular.js:2006:38
module@http://localhost:8000/bower_components/angular/angular.js:2080:14
loadModules/<@http://localhost:8000/bower_components/angular/angular.js:4617:22
forEach@http://localhost:8000/bower_components/angular/angular.js:321:11
loadModules@http://localhost:8000/bower_components/angular/angular.js:4601:5
createInjector@http://localhost:8000/bower_components/angular/angular.js:4523:19
bootstrap/doBootstrap@http://localhost:8000/bower_components/angular/angular.js:1758:20
bootstrap@http://localhost:8000/bower_components/angular/angular.js:1779:12
angularInit@http://localhost:8000/bower_components/angular/angular.js:1664:5
@http://localhost:8000/bower_components/angular/angular.js:31763:5
trigger@http://localhost:8000/bower_components/angular/angular.js:3207:7
defaultHandlerWrapper@http://localhost:8000/bower_components/angular/angular.js:3497:3
createEventHandler/eventHandler@http://localhost:8000/bower_components/angular/angular.js:3485:9

http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=myApp&p1=%5B%24injector%3Anomod%5D%20Module%20'myApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3DmyApp%0AminErr%2F%3C%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0Amodule%2F%3C%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A2082%3A17%0Aensure%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A2006%3A38%0Amodule%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A2080%3A14%0AloadModules%2F%3C%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A4617%3A22%0AforEach%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A321%3A11%0AloadModules%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A4601%3A5%0AcreateInjector%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A4523%3A19%0Abootstrap%2FdoBootstrap%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1758%3A20%0Abootstrap%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1779%3A12%0AangularInit%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A1664%3A5%0A%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A31763%3A5%0Atrigger%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A3207%3A7%0AdefaultHandlerWrapper%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A3497%3A3%0AcreateEventHandler%2FeventHandler%40http%3A%2F%2Flocalhost%3A8000%2Fbower_components%2Fangular%2Fangular.js%3A3485%3A9%0A
angular.js:68:12
```

And the original error:
```
"Error: [$compile:tpload] Failed to load template: view1/view1.html (HTTP status: -1 )
http://errors.angularjs.org/1.5.8/$compile/tpload?p0=view1%2Fview1.html&p1=-1&p2=
minErr/<@http://localhost:8000/bower_components/angular/angular.js:68:12
handleError@http://localhost:8000/bower_components/angular/angular.js:19433:17
processQueue@http://localhost:8000/bower_components/angular/angular.js:16383:28
scheduleProcessQueue/<@http://localhost:8000/bower_components/angular/angular.js:16399:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8000/bower_components/angular/angular.js:17682:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8000/bower_components/angular/angular.js:17495:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8000/bower_components/angular/angular.js:17790:13
done@http://localhost:8000/bower_components/angular/angular.js:11831:36
completeRequest@http://localhost:8000/bower_components/angular/angular.js:12033:7
createHttpBackend/</requestError@http://localhost:8000/bower_components/angular/angular.js:11976:9
"angular.js:13920:18
```

**Comment by massimocode** [comment]
I can replicate it extremely reliably, achieving one of those errors in the console at least 9/10 times I try.

However, the application *seems* to render correctly. Although I am not sure if all functionality would work.

**Comment by gkalpak** [comment]
This seems to be a Firefox issue. More specifically, Firefox seem to trigger the `onerror` callback of any pending XHR when moving away of the current page (e.g. reloading).

I was able to reproduce this with the following HTML:

```html
<!doctype html>
<html>
  <body>
    <script type="text/javascript">
      var xhr = new XMLHttpRequest();
      xhr.onabort = function onAbort() { console.log('abort'); };
      xhr.onerror = function onError() { console.log('error'); };
      xhr.open('GET', '/some/slow/to/respond/server');
      xhr.send();
    </script>
  </body>
</html>
```

This [old Firefox bug][1] seems related.

--
This should not affect the functionality in the fresh instance of the page, but is indeed annoying. In any case, this is something that i not specific to Angular and should be fixed on the Firefox side.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=486511

**Comment by massimocode** [comment]
It seems as though Firefox is following the HTML standard. There is some discussion around it here:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27347

**Comment by massimocode** [comment]
I have implemented a fix for this as it seems that browsers are apparently supposed to abort outstanding XMLHttpRequests on document unload and Firefox's behaviour does not seem to be non-standard. I'll create a PR.

**Comment by massimocode** [comment]
@gkalpak If you think this issue is worth fixing and the spirit of the PR is correct then I'll finish making it compliant with tests etc so it can be merged https://github.com/angular/angular.js/pull/15209

**Comment by gkalpak** [comment]
According to my understanding of the spec, when [navigating across documents][1] he browser should abort the active document. [Abortign a document][2] includes the following:

> Cancel any instances of the `fetch` algorithm in the context of this `Document`, **discarding any tasks queued for them**, and discarding any further data received from the network for them.

<sub>(emphasis mine)</sub>

And (again) as far as I understand, error handler fall under the category of queued tasks, thus should be discarded.

[1]: https://html.spec.whatwg.org/multipage/browsers.html#navigating-across-documents
[2]: https://html.spec.whatwg.org/multipage/browsers.html#abort-a-document

**Comment by massimocode** [comment]
Fair point. I will chase it up with Mozilla.

**Comment by massimocode** [comment]
@gkalpak I'm afraid this issue affects Google Chrome as well Version 53.0.2785.143 m (64-bit) (latest version)

I've simply amended the replication steps by changing the URL called by $TemplateRequestProvider to `https://fake-response.appspot.com/api/?sleep=5`

Edge handles the situation properly by cancelling everything. IE11 handles the situation fine as well. But latest Chrome and Firefox trigger errors. That's quite a large amount of users that will be affected by this. I could try in Opera if you like? (not that anyone uses Opera!)

**Comment by gkalpak** [comment]
Just to be clear on what "affects" means:

In all browsers, when you navigate away from a page, the pending requests (including XHR) are cancelled. Contrary to my understanding of the spec (which dictates that queued tasks should be discarded), in Chrome and Firefox (maybe Safari as well?) some events are triggered on the requests: Chrome triggers `abort` and Firefox triggers `error`.

As a result, the attached `onabort`/`onerror` listeners are executed. This is neither specific to Angular nor to `$templateRequest`; it even affects "raw" XHRs.

What this means for Angular specifically, is that the promise returned by `$http` will be rejected and the associated rejection handlers will be executed. In case of `$templateRequest`, it involves passing an error to the `$exceptionHandler` (which by default logs it to the console).

The only observable side effect of this is that people which have their DevTools open (and in Chrome also have the "Preserve log" flag set) will see an error logged in their console.

<sub>Preventing (or working around) the default browser behavior for all requests is not a good idea and out of question (I assume we agree on that).</sub>

--
I am still not convinced this is worth "fixing".

1. It seems harmeless to me (the vast majority of endusers will never even notice it - I mean how many users browse websites with their DevTools open and the "Preserve log" flag set?).
2. Even in the worst case, it will just log an error in the console. I assume most people will have many more XHRs logging  upon error.
3. It still seems a browser issue/spec deviation (to me at least) - and the fact that Chrome and Firefox have different behaviors supports this.

--
Note that (even if not ideal) it is possible to decorate the `$exceptionHandler` or `$templateRequest` and ignore errors while unloading.

<sub>Since we now have more info, I am going to reopen this and see what other people think.</sub>

**Comment by massimocode** [comment]
That summaries everything really well and I think you're right, it's probably not worth fixing.

We had the same discussion here as our protractor tests were set to fail when console errors were logged. This was causing intermittent failures in CI because of this error. We have chosen to ignore this specific error as opposed to patching Angular.

**Comment by gkalpak** [comment]
It seems we are all on the same page :+1:

We also discussed this internally and we agree this is not something that should be "fixed" in Angular.
<sub>(If the current behavior is deemed undesirable, it is something to be addressed on the browser-level.)</sub>

**Comment by freddi301** [comment]
Hi,
At work we have a particular customer that experiences this very problem,
aside from cluttering our error log, it does not load all the content properly (some random templates missing)
So you think i should tell my boss "i found the problem, the solution is that all browsers used by our customers should address this very specific problem and then all of the must use the right version of browser with this bug fixed"

**Comment by gkalpak** [comment]
> aside from cluttering our error log, it does not load all the content properly (some random templates missing)

There is nothing in this thread that indicates there should be any connection between such errors with partially or incorrectly loaded templates. I doubt it is the same issue, but I would be happy to investigate if you can provide the steps/code to reliably reproduce it (ideally in a live demo using Plnkr etc).

**Comment by freddi301** [comment]
> Well, actually if you don't hit refresh again after the refresh that triggered the tpload error, then you get empty content on the screen where the view should have been rendered, so it's a pretty huge issue.
>We have a production AngularJS application that is exhibiting this behavior and it's impacting our customers.
>I boiled the issue down to reproduce it just using the angular-seed website.

I couldn't reproduce it myself, even on our customer machines.
The app uses very basic routing with templateUrl.
It would a lot of work to extract something interesting for you, aside from creating an account in our test deployment. (there are some security bugs, so i prefer doing this as last-resort solution if that could help)

**Comment by gkalpak** [comment]
> Well, actually if you don't hit refresh again after the refresh that triggered the tpload error, then you get empty content on the screen where the view should have been rendered, so it's a pretty huge issue.
We have a production AngularJS application that is exhibiting this behavior and it's impacting our customers.

We were not able to reproduce the content on the reloaded page being broken - e.g. see https://github.com/angular/angular.js/issues/14219#issuecomment-251078712.
(And even if we could, I doubt we would be able to do anything in Angular to fix it - it would be a browser issue).

##
The art of the issue that was confirmed and reproduced is the error logged to the console. And as explained [here][1] and [there][2] it is:

1. a browser issue/deviation.
2. harmless.
3. easily worked around if you need to.

(Again, the above bullets refer to the logged error, not the broken content, which we haven't been able to reproduce.)

##
We can't fix an error that we are not able to reproduce or identify the cause of 😞 

[1]: https://github.com/angular/angular.js/issues/14219#issuecomment-251314143
[2]: https://github.com/angular/angular.js/issues/14219#issuecomment-251364645

**Comment by freddi301** [comment]
Thank you,
I did read those but, i didn't get
>(Again, the above bullets refer to the logged error, not the broken content, which we haven't been able to reproduce.)
Very nice from you to reply on a closed issue this fast. Have a nice day :)

**Comment by gkalpak** [comment]
> (Again, the above bullets refer to the logged error, not the broken content, which we haven't been able to reproduce.)

I am not sure if it wasn't clear before or if it still isn't, so just to be sure:

This issue involved two problems:

1. An unwanted error being logged for the unloading page.
2. The content being broken on the new page.

The first one is a browser issue/deviation, harmless and easily worked around.
The second one we weren't able to reproduce and investigate (and is possibly an old Firefox bug).

**Comment by trivett** [comment]
I just want to chime in here since I have been experiencing this fairly frequently in Chrome with Angular 1.5. It's devilishly hard to reproduce, happens on colleagues laptops but very infrequently on mine. I'm really at a loss as to how to work around this.  

I am on Chrome 56 on Linux and I am not experiencing this lately (at least I don't remember) but a co-worker on Mac with Chrome 58 is having it happen *in production* quite a lot.

My users are seeing partial content just flash in such a way that we might give someone seizures for a few seconds until it just stops and everything loads. has anyone figured out a way to consistently reproduce it and/or fix? 

Some issues and SO posts point to CORS but I don't think that's the case with me as I have my angular app served through the rails asset pipeline, and it does eventually just relent.

**Comment by EyalRonel** [comment]
I'm also experiencing some strange behavior in a somewhat similar scenario:
I have a chrome extension injecting a simple Angular 1.5.x app to an existing page (no routing used).
The extension triggers an XHR request when the use navigated to different urls within the site it's injected into, which is a single-page application without and page reloads.

I notices that sometimes, an **XHR POST** request triggered from the extension is **canceled** and the page refreshes unexpectedly. 

Catching the error right before the page refreshes contains these details:
`{
  "data": null,
  "status": -1,
  "config": {
    "method": "POST",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "url": "\/\/SOME.CORS.URL",
    "headers": {
      "token": "ARealTokenStringWouldBeHere",
      "Accept": "application\/json, text\/plain, *\/*"
    },
    "params": {}
  },
  "statusText": ""
}`

Any ideas?
