### ISSUE TITLE
Directive to get all of the attributes

### ISSUE THREAD

**Issue by DiasLife** [angular/angular.js#14239]
Tell me whether it is possible in the directive to get all of the attributes of all the descendants ?

**Comment by DiasLife** [comment]
`<div init-test>
<span test-attr-one="one">
     <span test-attr-two="two"></span>
</span>
</div>`

**Comment by DiasLife** [comment]
get all of the attributes of all the descendants

**Comment by Narretz** [comment]
Yes, that should be possible. But this repo is the wrong place to ask this question. Please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
