### ISSUE TITLE
IE8 <script> tags in ng-include template disappears

### ISSUE THREAD

**Issue by aaani** [angular/angular.js#14238]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In IE8 when I put a script tags in the templateCache like this:
```
    $templateCache.put('app/popups3.html',
        '<div> <script type="text/template" id="infopopupTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</script> <script type="text/template" id="infopopupTitleTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</script> <script type="text/template" id="infopopupMobileTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</script> <script type="text/template" id="infopopupTitleMobileTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</script> </div>'
    );
```
and then do
```
 <div ng-include src="'app/popups3.html'"></div>
```
the rendered html is
in IE8,
```
<div class=ng-scope src="'app/popups3.html'" ng-include ng339="73">
  <div class=ng-scope ng339="74"></div>
</div>
```
in latest Chrome,
```
<div ng-include="" src="'app/popups3.html'" class="ng-scope"><div class="ng-scope"> <script type="text/template" id="infopopupTemplateMapbox">
    <div></div>
</script> <script type="text/template" id="infopopupTitleTemplateMapbox">
    <div></div>
</script> <script type="text/template" id="infopopupMobileTemplateMapbox">
    <div></div>
</script> <script type="text/template" id="infopopupTitleMobileTemplateMapbox">
    <div></div>
</script> </div></div>
```

Why is the final html different between chrome and IE8? Why did the script tags not render for IE8?

But when I use the following (`use <div> instead of <script>`)
```
    $templateCache.put('app/popups3.html',
        '<div> <div id="infopopupTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</div > < div type="text/template" id="infopopupTitleTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</div > < div type="text/template" id="infopopupMobileTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</div > < div type="text/template" id="infopopupTitleMobileTemplateMapbox">\n' +
        '    <div></div>\n' +
        '</div> </div>'
    );
```
the final html is same for both IE8 and chrome. 

**What is the expected behavior?**
Scripts tags must also be in the final html for IE8, like it is for Chrome.

**What is the motivation / use case for changing the behavior?**
We store some legacy templates in the script tags, which are later rendered. Those template are added to the dom via ng-include.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

 1.2.19, IE 8

**Comment by Narretz** [comment]
I assume that's a limitation in IE8. We also do not work on 1.2.x anymore, so I'm afraid you have to find a different solution. You can always test with 1.2.29 (in case 1.2.19 isn't just a typo).

I also wonder why you put a template made of templates in the templateCache.

**Comment by Narretz** [comment]
Closing due to lack of feedback
