### ISSUE TITLE
Bug: ngAnimation classes skipped on enter when using ng-if on form that contains required email input

### ISSUE THREAD

**Issue by poacher2k** [angular/angular.js#14249]
Hey!

**What is the current behavior?**
When you have a form that is shown using `ngIf` and contain an `<input type="email" ng-model="someModel" required>`, ngAnimate classes are not added when the `ngIf` statement becomes truthy.

**Steps to reproduce**
[Link to demo](http://codepen.io/poacher2k/pen/zqNOxo)
1. Create a form that is shown with `ngIf` and contains an `<input type="email" ng-model="someModel" required>`
2. Make `ngIf` statement truthy

**What is the expected behavior?**
ngAnimate classes should be added when `ngIf` statement becomes truthy.

**What is the motivation / use case for changing the behavior?**
Consistent behavior 

**Affected:**
This occured when I tested with Chrome and Firefox on Linux, Safari on OSX, and Chrome / IE on Win7, both angular 1.5.x stable and snapshot.

**Other information**
It works as expected if:
1. `type="email"` is changed to something else
2. `required` is removed
3. `ngShow / ngHide` is used instead of `ngIf`

**Comment by Narretz** [comment]
Looks like it was caused by https://github.com/angular/angular.js/commit/776972ed9c49a62f5ad7c6f207209bf0f0c900bb

**Comment by michi88** [comment]
This could very well also be related to lazy compilation with the ng-if transclude as discussed here: https://github.com/angular/angular.js/issues/14074

just my two cents

**Comment by Narretz** [comment]
I don't think so, because you need very specific prerequisites. I've explained the cause in the linked OR
