### ISSUE TITLE
ngMock running in angular1 app

### ISSUE THREAD

**Issue by char0n** [angular/angular.js#14248]
Hello,

I having problem setting up ngMock in angular1 app. I have created the plunker to demonstrate the problem. http://plnkr.co/edit/UQI34twF0tLDOtoXTXGw?p=preview

**What is the current behavior?**

Interpolation of `<p>Hello {{name}}!</p>` will not happen.

**What is the expected behavior?**

Result of interpolation is `Hello World!`

**What is the motivation / use case for changing the behavior?**

I am trying to use ngMock in hybrid angular1/angular2 application. ngMock is causing application not to start, so I decided to create minimal angular1  application and try to load ngMock. After loading ngMock and adding it as an app dependency event angular1 application stops working.

**Which versions of Angular, and which browser / OS are affected by this issue? **

angular: angular 1.5.0
OS: windows 8.1
Browser: Chrome 49.0.2623.87 m

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

When I modify app.js from

```javascript
var app = angular.module('plunker', ['ngRoute', 'ngAnimate', 'ngSanitize', 'ngMock'])
```

to 

```javascript
var app = angular.module('plunker', ['ngRoute', 'ngAnimate', 'ngSanitize']);
```
...everything works as expected.

Can you please advice ? Thank you

**Comment by Narretz** [comment]
You are not supposed to include ngMock outside of tests. Why do you need ngMock in your app?

**Comment by char0n** [comment]
I don't need it in my app. I was just following the docs: https://docs.angularjs.org/api/ngMock

I understand now that I load the library only during running tests, e.g. via karma-runner, right ?

**Comment by Narretz** [comment]
I'll add a note to this page. I wonder how you ended up on that page / with the impression you'd have to require ngMock in your app?

**Comment by char0n** [comment]
Like I said, I wanted to unit tests my components written in angular1. So I went to ngMock documentation and followed the instructions. Instructions were clear to include angular-mocks.js and add ngMock dependancy into app. So it was like that... ;]

**Comment by Narretz** [comment]
I'm just asking to see if we can or should make the docs clearer about that, and I guess we need to. :)

**Comment by char0n** [comment]
Thanks, I guess it will be helpful for other people too.
