### ISSUE TITLE
Feature: hide element if ng-transclude-slot not filled

### ISSUE THREAD

**Issue by yasinkocak** [angular/angular.js#14241]
Its seems logical when use ng-transclude-slot="string" and it's not filled to hide element. This will save me build a controller to do this.

**Comment by Narretz** [comment]
I don't know. If the element doesn't have content, it's generally "hidden" for most purposes (since it won't have a height, except when explicitly set). So I don't think that's a common requirement. Can you explain your use case a bit more?

**Comment by yasinkocak** [comment]
If i have PanelController and panel-footer is not filled. The styling and html of panel-footer is still exists.
`
export class PanelController {
    static $inject = ['$transclude'];
    constructor(protected $transclude: ng.ITranscludeFunction) { }
}

export default <any>{
    transclude: {
        heading: '?panelHeading',
        body: 'panelBody',
        footer: '?panelFooter'
    },
    controller: PanelController,
    template: `
        <div class="panel panel-primary">
            <div class="panel-heading" ng-if="$ctrl.$transclude.isSlotFilled('heading')" ng-transclude="heading"></div>
            <div class="panel-body" ng-transclude="body"></div>
            <div class="panel-footer" ng-if="$ctrl.$transclude.isSlotFilled('footer')" ng-transclude="footer"></div>
        </div>
        `
};

`

**Comment by Narretz** [comment]
You can do this with css:   

```css
.footer:not(:empty) {
    height: 20px;
  }
```

**Comment by Narretz** [comment]
Or 
```
.footer:empty {
  display: none;
}
```

This is available in all our supported browsers, so I'll say that this is an acceptable solution.

**Comment by itxds** [comment]
(2 years later)
Or you know... we could have had:
```css
[ng-transclude]:empty {
  display: none;
}
```
:/
