### ISSUE TITLE
$animatecss Preventing Structural ng-show classes.

### ISSUE THREAD

**Issue by ChrisSargent** [angular/angular.js#14254]
Report a 'bug' maybe - or is this expected behaviour?

In Angular, using  $animatecss, triggered by an addClass or removeClass event, it seems to prevent ng-show / hide on the same element from adding the structural animation classes, and therefore prevents transitions from happening based on them too.

Codepen: http://codepen.io/ChrisSargent/pen/yOgOOY/

Expected Behaviour
I would expect the Angular native structural animation classes to be added - like ng-hide-remove, ng-hide-remove-active etc.

This is in Angular 1.4.7 and 1.5.0, happening on Safari, FF and Chrome on MAc OSX El Capitan. I assume others too.

**Comment by ChrisSargent** [comment]
So, if I manually add back in the event with `event: "hide-remove"` and `structural: true`, then it starts to work again, BUT it I don't think it reads the transition value for the `animated-element.ng-hide-active` class, only if there's a transition on the base `animated-element` class.

http://codepen.io/ChrisSargent/pen/grgrdN

**Comment by Narretz** [comment]
Hi @ChrisSargent I tried to investigate, but the codepen you linked doesn'T work. Angular can't be loaded from the CDN and after I changed the url, there's a module missing. Please let me know when you have fixed this, I'll take another look then.

**Comment by ChrisSargent** [comment]
Hi @Narretz,

That's strange, was working for me. Anyway, I updated the CDN to point to Google's hosting. Both pens should be good now.

Chris

**Comment by Narretz** [comment]
You can't use javascript animations and animations defined in css at the same time. This is mentioned in the docs: https://code.angularjs.org/snapshot/docs/api/ngAnimate#css-js-animations-together
I'm not sure if this is intentional, but it's specific to the actual event - in your example, addClass works because it's not defined in the javascript animation.

**Comment by Narretz** [comment]
Closing due to lack of feedback.
