### ISSUE TITLE
i want to use a custom header

### ISSUE THREAD

**Issue by luodonger** [angular/angular.js#14256]
![image](https://cloud.githubusercontent.com/assets/6228242/13838448/121c7926-ec4f-11e5-9dc1-81fdd6cce844.png)

![image](https://cloud.githubusercontent.com/assets/6228242/13838467/48eeeb00-ec4f-11e5-9044-f7a8c50999b2.png)

i i remove the gustom header, it will work fine, so what's wrong with it ,and how can i use it?

thanks  a lot

**Comment by pkozlowski-opensource** [comment]
This is CORS at work, see: http://www.html5rocks.com/en/tutorials/cors/?redirect_from_locale=fr
Closing, as this is browser's behavior and has nothing to do with AngularJS.
