### ISSUE TITLE
filter comparator should pass filter object key

### ISSUE THREAD

**Issue by ilovett** [angular/angular.js#14260]
**_Note_: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

Filter comparator function takes `function(actual, expected) {}`

**What is the motivation / use case for changing the behavior?**

If I provide a filter object and have a special case for comparing just one of those objects, I would want to look for it in my comparator function:

```
$scope.filterObj = {
  '$': 'all',
  'specialFilterValue': [1,2,3]
}

$scope.comparatorFunction(actual, expected, key) {
  if (key === 'specialFilterValue') {
    return ... // 1 OR 2 OR 3
  }
  else {
    return ...
  }
}
```

```
<div ng-repeat="row in allData | filter:filterObj:comparatorFunction">
  ...
</div>
```

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.0

**Comment by gkalpak** [comment]
This might be a little bit problematic. E.g. there are situations where there is no key, or the item's key does not correspond to the filter object's keys (e.g. when matching "deeply"), or there are keys with the same name on different nesting levels etc. There are all corner cases though.

I assume you are you referring to the item's key.

TBH, I believe this will be complicate the implementation for little gain. If you have a very specific usecase, you can always use acustom filtering function: `... | filter:myPredicateFn`

--
If you feel strongly about it, feel free to take a stab at a PR, so we can have a more concrete basis for discussion :smiley:

**Comment by Narretz** [comment]
Closing because of concerns and little demand.
