### ISSUE TITLE
Text not justified on iOS Safari when using "ng-bind-html"

### ISSUE THREAD

**Issue by morphet81** [angular/angular.js#14265]
*bug*

When injecting html content using `ng-bind-html`, the CSS property `text-align: justify` does not work on Safari (iOS and Mac OSX). The text is align on the left.

To reproduce it, inject a string containing html text embeded in a `<p>` block, set the text-align CSS attribute to justify, inject this string into the HTML page using `ng-bind-html` then run the page on safari.

The text should be justified (it is on android and desktop chrome).

This bug occured with Angular 1.4.0 on iOS and Mac OSX Safari explorers.

**Comment by Narretz** [comment]
Can't reproduce in this plnkr: http://plnkr.co/edit/LLPPNngfgfTfvUL51MUQ on ios 9.2 on iPad 2 simulator. Please provide a demo that shows the problem.

**Comment by Narretz** [comment]
Closing due to lack of feedback.
