### ISSUE TITLE
Request for feedback: $componentController change signature to enforce presence of $scope

### ISSUE THREAD

**Issue by FreakenK** [angular/angular.js#14261]
This is a request for feedback for a PR I'd like to make.

Currently, the signature of $componentController is this:
$componentController(componentName, locals, [bindings], [ident]);

Since a note has been at the top of the documentation page stating that locals requires $scope to be defined (https://docs.angularjs.org/api/ngMock/service/$componentController), I'd like to enforce this by changing the signature of the service to:

$componentController(componentName, $scope, [locals], [bindings], [ident]);

I tried writing the TS typings for the service this afternoon, and finally gave up when I couldn't enforce the presence of a $scope.

**Comment by Narretz** [comment]
We could consider it, if we can do it without a breaking change. Do you want to open a PR?

**Comment by thorn0** [comment]
@FreakenK What is the problem with the TS typings?
```ts
$componentController<T>(
  componentName: string,
  locals: { $scope: ng.IScope },
  bindings?: { [propName: string]: string },
  ident?: string
): T;`
```
Am I missing something?

**Comment by FreakenK** [comment]
@thorn0 The typings I have locally looks pretty much like the one you just provided, but I find it to be a bit confusing since the 'locals' parameter takes an object, but with only one available property.

I checked a bit more how $controllerComponent works this weekend and understand that it has been written this way to map the type of $controller's service 'locals' parameter. My understanding was that 'locals' parameter had other properties available (since it's an object), with $scope being required, but that doesn't seem to be the case.

**Comment by gkalpak** [comment]
> My understanding was that 'locals' parameter had other properties available (since it's an object), with $scope being required, but that doesn't seem to be the case.

@FreakenK, that is exactly the case :smiley: `locals` can have any parameters and they are used to overwrite the ones returned by the injector while Dependency-Injecting the controller. `$scope` is necessary, because it is not something the injector knows about; it is "normally" provided by Angular's `$compile`, but since you are instantiating the controller yourself (i.e. not as part of a directive and thus outside of the context of `$compile`), you need to provide it yourself, thus it is the only _required_ property.

Other properties may or may not be required depending on the implementation of a specific controller.

**Comment by FreakenK** [comment]
@gkalpak Ok, thanks for clearing that up, it all makes much more sense now.

I've got working typings, without requiring any modification to the service.

```
    ///////////////////////////////////////////////////////////////////////////
    // ComponentControllerService
    // see https://docs.angularjs.org/api/ngMock/service/$componentController
    ///////////////////////////////////////////////////////////////////////////
    interface IComponentControllerService {
        // TBinding is an interface exposed by a component as per John Papa's style guide
        // https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#accessible-members-up-top
        <T, TBinding>(
          componentName: string, 
          locals: { $scope: IScope, [name: string]: any }, 
          bindings?: TBinding, 
          ident?: string): T
    }
```

Your comments are welcome.

**Comment by gkalpak** [comment]
Not sure what `TBinding` looks like (`bindings` is basically a `{[key: string]: string}` object).
Also, what is the `name` property inside `locals` ? Is it specific to your app ?

**Comment by FreakenK** [comment]
TBinding is just an interface representing a component bindings. We export one at the top of all our components, since it is recommended practice in John Papa's styleguide. [Here is the article which brought us to use this convention.](http://almerosteyn.com/2016/02/angular15-component-typescript). It allows to quickly spot all exported bindings on a component as well as enforce types in tests.

The name property is arbitrary and could be renamed to 'key'. Using an hasmap is the way I found to enforce $scope presence in the 'locals' object as well as allow anything else.

**Comment by gkalpak** [comment]
Right :smiley: Looks reassonable.
<sub>(BTW, I was wrong about `bindings` in the previous comment. I hope I didn't cause much confusion :grin:)</sub>

**Comment by gkalpak** [comment]
So, closing this as we seem to have reached a consencus that no changes are necessary.
<sub>(Feel free to re-open, if I'm wrong.)</sub>

**Comment by FreakenK** [comment]
Alright, I'll submit it as is.

Thanks for helping out !

### No harms done about the bindings, I read over it and did the exact mistake a couple days ago ;)
