### ISSUE TITLE
Safari URL Parameters being ignored when redirected from a server-side API

### ISSUE THREAD

**Issue by jeff-mk** [angular/angular.js#14270]
My application is using a server-side API that redirects users to an Angular URL in this form:

`https://www.myapp.com/#/app?someKey=value1&someKey2=value2`

When I test on Chrome, Firefox, and IE, everything works well. When I test on Safari, the browser ignores everything after the `#` and redirects to this instead:

`https://www.myapp.com/`

... as if it was ignoring the hashbang. I played around with encoding the hashtag to %23, but Safari then complains 404 (as expected, since myapp.com/%23/app isn't really a directory on my web server).

I've googled around and the closest issue I've found was this: http://stackoverflow.com/questions/25156291/url-parameters-work-on-chrome-firefox-but-not-on-safari

And no other reports. Due to the lack of actual reports, I'm going to assume this is either an unknown Safari bug, or I'm doing something wrong.

Could anyone advise?

Thanks

**Comment by jeff-mk** [comment]
Non-issue. The issue was the server was redirected to http://, and the web server was automatically redirecting it to https://, thus losing all of the URL parameters. The weird thing is this only happens on Safari, but that's a separate issue altogether.

**Comment by anilp1201** [comment]
What is solution for this issue.
