### ISSUE TITLE
chore(*): enable jshint eqeqeq

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#14287]
Add jshint eqeqeq and eqnull rules, and fix all resulting errors.

**Comment by Narretz** [comment]
@lgalfaso So, in parse there's actually a comparison that seems to be == / != on purpose: https://github.com/angular/angular.js/blob/aa077e81129c740041438688dff2e8d20c3d7b52/src/ng/parse.js#L1532-L1543 Changing == to === for binary== makes this expectation fail: https://github.com/angular/angular.js/blob/aa077e81129c740041438688dff2e8d20c3d7b52/test/ng/parseSpec.js#L1741  , changing != to !==  for binary!= does not. Can you take a look at this?

**Comment by gkalpak** [comment]
Seems like we are missing a test, e.g. `expect(scope.$eval('1!="1"')).toBeFalsy()`.
Obviously we need to retain the `==`/`!=` for `binary==` and `binary!=`.

**Comment by Narretz** [comment]
That's right, thanks @gkalpak
