### ISSUE TITLE
angular : Safari hangs after button click on Docs page in-line demo

### ISSUE THREAD

**Issue by YvesLeBorg** [angular/angular.js#14281]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Demo on docs page beach-balls safari, must terminate Safari process and restart

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

-  Navigate to the [docs page, scopes](https://code.angularjs.org/1.5.2/docs/guide/scope), with Safari
- Scroll down to the 'inpage example' for *Scopes as Data Model*
- Modify the content (in this case, just add a letter at the end)
- click on the 'greet' button, and voila ! beach ball
- this is repeatable with 1.5.2 version and current version

**What is the expected behavior?**
no beach ball

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

my setup : macbook pro, el Capitan 10.11.2, completely up-t-date
Browser : Safari (with some extensions , AdBlock and Ghostery)
can produce this with snapshot and 1.5.2 release (i assume most others)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
I've tested with  OS X El Capitan Safari 9 (Saucelabs) on this url https://code.angularjs.org/snapshot/docs/guide/scope and I cannot repro this. Can you please test without any extensions? This is a very simple example, I doubt this is a general issue.

**Comment by YvesLeBorg** [comment]
I will try to nuke (lose .... sighhhh) my settings especially for AdBlock (the perfect garbage filter for LinkedIn) 

btw : exact behavior for me to get this : at the url you posted, add a 'e' after 'World', then type space (or any other, or click 'greet'). The hang occurs at the next UI event.

related : Similar, with materials. 

https://github.com/angular/material/issues/7652

**Comment by YvesLeBorg** [comment]
@Narretz : well, the plot thickens for me. Although i cant be certain, i think this is related to a condition that occurs far too often on my puter (too many files open). I rebooted and the behaviour is gone. Closing this issue, but ... there is something there.
