### ISSUE TITLE
Browser refresh in beta.11

### ISSUE THREAD

**Issue by chundemer** [angular/angular.js#14288]
Browsersync not launching in beta.11

**package.json:**
...
"scripts": {
    "postinstall": "npm run typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" ",
    "typings": "typings"
  },
 
  "dependencies": {
    "angular2": "^2.0.0-beta.11",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.2",
    "systemjs": "^0.19.23",
    "zone.js": "^0.6.2"
  },
.....

Environment:
**MAC/Chrome**

"Issue":
When executing npm start, browsersyc does not appear to be starting. Changes are detected but not refreshed in browser.

"Resolution:
Changing entry in package.json from  "angular2": "^2.0.0-beta.11" to ("angular2": "^2.0.0-beta.9" or "angular2": "^2.0.0-beta.8")  browsersyc works as expected.

**Comment by Narretz** [comment]
PLease open an issue here: https://github.com/angular/angular
