### ISSUE TITLE
Drop down value not set after upgrading from 1.3.6 to 1.4.8

### ISSUE THREAD

**Issue by RobertVogt** [angular/angular.js#14298]
**What is the current behavior?**
An object is populated...
Controller.policyKeys = {
            insuranceType: Controller.FormValues.insuranceType,
            cropYear: cropYear,
            stateAbbreviation: Controller.FormValues.stateAbbreviation,
            policyNumber: Controller.FormValues.policyNumber

        }
Drop Down value is set to Controller.policyKeys.cropYear

AFTER upgrading to 1.4.8...
Drop Down value DOES NOT get set instead it's set to blank.

**What is the expected behavior?**

Drop Down value is set to Controller.policyKeys.cropYear

**Comment by Narretz** [comment]
First, please read the [Migration guide](https://code.angularjs.org/snapshot/docs/guide/migration) to see if this is due to a documented BC. If not, please provide a demo in a plnkr.co or similar.

**Comment by Narretz** [comment]
Closing due to lack of feedback
