### ISSUE TITLE
Breacking change in the selectDirective 

### ISSUE THREAD

**Issue by AshDevFr** [angular/angular.js#14296]
Hello,

I would like to report a breaking change when using the selectDirective

with this commit: https://github.com/angular/angular.js/commit/ac35b416fb818faba73ee4cbdf5837b4d9f31f38 , the selectDirective controller does not have the same amount of arguments.

When using a decorator to change the controller behavior I have an issue.

Example with the version 1.5.1 which do work : http://codepen.io/AshDevFr/pen/BKWgvK
```
  ...
  $provide.decorator('selectDirective', function($delegate) {
    var directive = $delegate[0];
    var OriginalController = directive.controller[3];
    ...
```

If I change the version to 1.5.2 it does not work anymore : http://codepen.io/AshDevFr/pen/zqZVeL
```
TypeError: OriginalController is not a constructor
```

Change I had to do with the version 1.5.2 : http://codepen.io/AshDevFr/pen/PNprLZ
```
  ...
  $provide.decorator('selectDirective', function($delegate) {
    var directive = $delegate[0];
    var OriginalController = directive.controller[2];
    ...
```

The position of the function has changed so I had to edit my decorator. It's not a big deal but I think it should be noted as a breaking change.

Regards,

**Comment by Narretz** [comment]
Thanks for the example. I think we should revert this specific change, as an injection argument is a bit different from an internally unused variable.

**Comment by Narretz** [comment]
@gkalpak Wdyt?

**Comment by gkalpak** [comment]
TBH, I don't consider this a breaking change. It was never documented that the controller is defined as an array or what arguments it needs. It's a very "internal" implementation detail, imo.

I mean one could of course take the risk on relying on something like this (we all have done it :smiley:), but they should accept the fact that underlying implementation details could change.

If we go down this path, even re-ordering some arguments would be a breaking change :stuck_out_tongue: 

--
That said, and while I don't know what "features" are added to the original controller, I feel like this is not the Angular way&trade;. In most cases thare are much better alternatives to augment an existing directive, e.g. requiring its controller from another one.

Even in this particular case, if one is willing to accept the (admittedly low) risk that we will keep defining the `SelectController` using inline array notation, it is very fragile to grab the constructor function by index. You should be accessing it as the last element of the array and you would be unaffected by ac35b41. E.g.:

```js
var directive = $delegate[0]
var controllerArr = directive.controller;
var OriginalController = controllerArr[controllerArr.length - 1];
```

For a more robust solution, I would also use `controllerArr` to inject the correct arguments into the new controller and pass them to `OriginalController`. You might even want to use `$controller()` service to instantiate `OriginalController`.

--
Just m2c...

**Comment by AshDevFr** [comment]
@gkalpak

your example is exactly what I did to correct my code.
As I said, it is not a big deal to change my decorator. 

The thing is, the issue has appeared when upgrading from 1.5.1 to 1.5.2 which is just a patch. 
So I was a little confused about this change

**Comment by Narretz** [comment]
Oh I misunderstood what the decorator does. So yeah it's an implementation detail that we use the array notation here.
@AshDevFr not all changes that break something are breaking changes. If an undocumented feature or implementation changes this is not a BC. It's tricky with decorators since they access the internals in an unpredictable way.

**Comment by Narretz** [comment]
Given @gkalpak explanation and the fact that the selectController is undocumented, I'm gonna close this.
