### ISSUE TITLE
ngMessages with bound message doesn't remove watch when message is removed

### ISSUE THREAD

**Issue by jwalker-scottlogic** [angular/angular.js#14307]
We have ngMessage texts which can change, and so are bound to model values rather than being hardcoded into the view.

eg.

```
<div ng-messages="form.input.$error">
    <div ng-message="myError">{{errorMsg}}</div>
</div>
```

Every time the message is shown, it adds a new watch which is not removed when the message is removed, but stays added until the parent ng-messages element is destroyed.

JSFiddle showing the problem is available here https://jsfiddle.net/jwalkersl/Lumjd9tm/

**Comment by Narretz** [comment]
That's quite a leak there ... not sure if there's an easy way to fix it. Does your message text change while it is displayed? If not, as a workround you could use one-time bindings, so no watcher is added at all.

**Comment by jwalker-scottlogic** [comment]
Yes, we have some messages which need to update while they're displayed - others already use one-time bindings where we can.
