### ISSUE TITLE
Dynamic controls or css issue

### ISSUE THREAD

**Issue by rameshbas** [angular/angular.js#14301]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**  bug

**What is the current behavior?**
the UI behaves differently with the ngif added and removed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Piece of code:
 <div *ngIf = (user) >
        <h4>{{editUser.FirstName | uppercase }} details</h4>

     <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <label class="mdl-textfield__label" for="nametext">First Name</label>
      <input type="text" id="nametext" class="mdl-textfield__input" [(ngModel)]="editUser.FirstName" />
    </div>

the text field loses the added touch of the class style and produces normal input style. The user is not empty. If I remove *ngIf = (user)  it works correctly. Looks like angular is overwriting the presetaion part incorrectly for dynamically created controls (like buttons and for fields))

**What is the expected behavior?**
should have the style attribute worked as designed whether ng filters are used or not..
ANgular paints the screen firts and then applies ngIf. while doing it overwrites the styles
the genrated .js files are identical with ngif filter is there are not 

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This repo is for the 1.x version of Angular (AngularJS).
Please reopen in https://github.com/angular/angular.
