### ISSUE TITLE
$httpBackend: Better reporting of failed expectations

### ISSUE THREAD

**Issue by dcherman** [angular/angular.js#14300]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Failed expectations that include data expectations are reported as `Error: Unsatisfied requests: POST /myUrl`

**What is the expected behavior?**

The expectation should include what the expected data was and what the actual data was, similar to as if you had done

`expect(data).toEqual(expectedData)`;

**What is the motivation / use case for changing the behavior?**

Ease of use.

**Comment by harbieism** [comment]
I'm working on a PR for this issue but I can't seem to figure out when an unsatisfied request will have 'actual' data.

For instance,

```
hb.expect('POST', '/u1', 'ddd').respond(201, '', {});
hb('POST', '/u1', 'dad', noop, {});
```
Already throws an error:
```
Error: Expected POST /u1 with different data
EXPECTED: ddd
GOT:      dad
```

As it stands the PR I have going has the following behavior.
```
hb.expect('POST', '/u1', 'ddd').respond(201, '', {});
hb.expect('POST', '/u3', 'aaa').respond(201, '', {});
hb('POST', '/u1', 'ddd', noop, {});
expect(function() {hb.verifyNoOutstandingExpectation();}).
  toThrowError('Unsatisfied requests: GET /u2, POST /u3 (Expected: aaa)');
```
Does this make sense? Let me know if I'm missing something obvious.

**Comment by gkalpak** [comment]
@harbieism, I believe @dcherman is talking about failing expectation because of different data. E.g. something like:

```js
$httpBackend.expectPOST('/foo', 'bar');
$http.post('foo', 'baz');
```

@dcherman, I do see the expected vs actual data in the error message though:

```
Error: Expected POST /foo with different data
EXPECTED: bar
GOT:      baz
```

Maybe you mean something else. Could you post an example with the exact test code ?

**Comment by dcherman** [comment]
Been meaning to circle back to this, but my recent unit tests using the `$httpBackend` mock all display failed expectations perfectly.  I don't recall what version I was using when I filed this, but it looks like somewhere along the way the message got improved.
