### ISSUE TITLE
Can we do real http call in integration test using karma framework?

### ISSUE THREAD

**Issue by s-sridevi15** [angular/angular.js#14305]
I am trying to write an integration test using karma. I need to do real http call and get the actual response. I tried all solutions mentioned in https://github.com/angular/angular.js/issues/1434 like using passthrough() and commenting "$httpBackend: angular.mock.$HttpBackendProvider," in angular-mocks.js and none of them worked.

Here is my test code :

use strict';

describe('module: main, service: AuthService', function () {
  beforeEach(module('ngMockE2E'));
  // load the service's module
  beforeEach(module('main'));
  // load all the templates to prevent unexpected $http requests from ui-router
  beforeEach(module('ngHtml2Js'));
  
  // instantiate service
  var AuthService;
  var $q;
  var deferred;
  var $rootScope;   
  var response;  
  var scope, http, flush, httpBackend;    
  beforeEach(inject(function ($httpBackend,_AuthService_,_$q_, _$rootScope_) {
    httpBackend = $httpBackend;  
    AuthService = _AuthService_;
    $q = _$q_;
    $rootScope = _$rootScope_;
    deferred = _$q_.defer();  
    scope = $rootScope.$new();
  }));
    
  it('should do something', function () {
    expect(!!AuthService).toBe(true);
    expect(AuthService).not.toBeNull();      
  });
    
  
   
it('verify authenticating user', function () {
      AuthService.authUser('abc@abc.com','abc123').then(function (result) {
        console.log("Result of successful auth user is ");
        console.log(result);
        expect(result).toEqual(true);
        done();
      }, function (error) {
          console.log("error of failure auth user is ",error);
         expect(false).toBe(true);
         done();
      });
    httpBackend.whenPOST('/oauth/token').passThrough();
    $rootScope.$digest();
    //httpBackend.flush();
  });   

});

It will be great if somebody have any solution for this to do real http call in karma test

**Comment by gkalpak** [comment]
If you are just trsting the `AuthService`, why do you need to reach out to the server ?

**Comment by s-sridevi15** [comment]
but  authUser method does http call to backend server

**Comment by gkalpak** [comment]
It sounds more like you are trying to unit test `AuthService` (in which case you shouldn't make actual requests to the server, but "train" the mocked `$hhtpBackend` with the appropriate responses).
If you want to write an end-to-end (e2e) test, you should be using Protractor instead.

I'm going to close this as it sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
