### ISSUE TITLE
Demo of Animation Anchoring (via ng-animate-ref) broken on latest docs

### ISSUE THREAD

**Issue by vidhill** [angular/angular.js#14312]
Sorry if this is known or I shouldn't report bugs on the snapshot (I'm not sure on the protocol)

**Steps to reproduce and a minimal demo of the problem**
Visit https://docs.angularjs.org/api/ngAnimate#anchoring-demo 
v1.5.3-build.4692 (snapshot)

**Current behavior**
Pin animation demo not working as pin should work
**Expected/desired behavior**
Should work as in current stable release: https://code.angularjs.org/1.5.2/docs/api/ngAnimate#anchoring-demo

**Comment by Narretz** [comment]
Thanks for reporting! You should report issues with the snapshot, as we try not to commit broken stuff there :) The issue should be fixed in about half an hour, once Travis finishes
