### ISSUE TITLE
[Docs] Why is lowercase/uppercase deprecation not in changelog?

### ISSUE THREAD

**Issue by adgoncal** [angular/angular.js#14316]
Doc entries for angular.lowercase and angular.uppercase were removed in angular 1.5.0-rc.2 (See #11387, https://github.com/angular/angular.js/commit/6a92e9111f8eddc9cebaa1ee01c8453c891f23bd).

Why is this not in the changelog?

**Comment by gkalpak** [comment]
Docs changes are usually not included in the changelog. On the other hand, this was the first time we removed something from the docs, but not from the code (afaik). It makes sense to add a deprecation warning in the changelog.

@adgoncal, would like to submit a PR for that ?
