### ISSUE TITLE
Can we increase the timeout for post call in karma test

### ISSUE THREAD

**Issue by s-sridevi15** [angular/angular.js#14310]
In one of my karma tests, I am calling a service which does post call. It seems like post call is getting timeout . Is there any way I can I can increase the timeout for post call from my integration test? 

Btw, this post call is real http call which calls backend server. As it is integration test I need to do real post call.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
