### ISSUE TITLE
ng-options track by with property in 2nd level of depth

### ISSUE THREAD

**Issue by brentahiti** [angular/angular.js#14317]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Might be a bug or intended behavior

**What is the current behavior?**

The ng-options sets the model with the appropriate object but can't be programmatically set

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

https://plnkr.co/edit/Xfsmo5zjp1Pm9z1y1S2l?p=preview

**What is the expected behavior?**

I would expect to be able to set the select programmatically since it correctly updates the model when I select through clicks and generated option values are correct

**What is the motivation / use case for changing the behavior?**

I want to be able to save only data that isn't tied to the UI, e.g display text

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

I see it with angular 1.5.x and tried on Firefox, Safari and Chrome. Never tried this use case in previous versions so I can't tell

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This is a known (and [documented][1]) limitation of `select as` + `track by`.
The docs have examples of what works and what doesn't when combining `select as` with `track by`.

[1]: https://docs.angularjs.org/api/ng/directive/ngOptions#-select-as-and-track-by-
