### ISSUE TITLE
$onChanges isn't called on the initialization of the component

### ISSUE THREAD

**Issue by thorn0** [angular/angular.js#14318]
**Do you want to request a *feature* or report a *bug*?**

Feature (I guess)

**What is the current behavior?**

`$onChanges` isn't called on the initialization of the component.

**What is the motivation / use case for changing the behavior?**

The motivation is to match the behavior of Angular 2. In A2, `ngOnChanges` is called on the initialization of the component too. And the change object includes the `isFirstChange` method, which in this case returns `true`.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

A plunk that shows how `ngOnChanges` works in Angular 2: http://plnkr.co/edit/kIf8QgrFxtENzvr6V5TZ?p=preview

**Comment by petebacondarwin** [comment]
I guess we could just hard code a call to `recordChanges` during the original configuration of the bindings?

**Comment by petebacondarwin** [comment]
I have a fix at #14323
