### ISSUE TITLE
Callback $animate.on() leave-close isn't called after an ng-leave animation finishes

### ISSUE THREAD

**Issue by ahagelstein** [angular/angular.js#14321]
**Do you want to request a feature or report a bug?**

Report a bug.

**What is the current behavior?**

Based on #6049 I have modified the sample code to use the current angular version 1.5.3.

http://plnkr.co/edit/KffprsYkzg6ZoTfzsC7y?p=preview

With 1.5.2/1.5.3 the leave-close callback is not called.

If I remove the following lines from angular-animate.js the callback is working:

jqLite(container).on('$destroy', function() {
  $animate.off(event, container, callback);
});

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.2/1.5.3 --> bug
1.4.9/1.5.0/1.5.1 --> ok

**Comment by Narretz** [comment]
Thanks for the report. This was introduced by https://github.com/angular/angular.js/commit/ce7f400011e1e2e1b9316f18ce87b87b79d878b4, (the lines you commented out).
We have to make sure that the listeners are removed after the callbacks for "leave" have been fired.
