### ISSUE TITLE
Arabic Numeric Shaping Support

### ISSUE THREAD

**Issue by ragabo** [angular/angular.js#14327]
### Introduction to Arabic Numeric Shaping

Arabic and many other languages (Thai and Bengali) have classical shapes for digits “National Digits” that are different from the conventional Western Digits (European).

National digits have the same semantic meaning as the European digits, and the numbers they form are read from left to right (most significant digit on the left). The difference is only a difference in glyphs.

| European Digits | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
| --------------- |----|---|---|---|---|---|---|---|---|---|
| **Arabic-Indic Digits** | ٠ |	١ |	٢ |	٣ |	٤ |	٥ |	٦ |	٧ |	٨ |	٩ |

From the Arabic user's point of view, Arabic-Indic numerals are the basic numerals used in almost all forms of documents such as most of government documents (IDs, birth certificates, driver's licenses, passports and household bills), bank statements, newspapers, calendars, road signs and menus.

<br>

### Options for Arabic Numeric Shaping

There are 3 options which should be taken into consideration when implementing national numeric shaping support in any framework/technology. These options are:

- **None**: No shaping is performed, and the value appears as it is in the data source.
- **National**: Digit shapes are determined from the user’s language.
- **Contextual**: Digit shapes are determined from the preceding characters in the buffer. European digits follow strong Latin character and Arabic-Indic digits follow strong Arabic character.
When there is no preceding strong characters, the base text direction attribute determines the digit shaping.(Arabic-Indic digits in RTL context and European digits in LTR context).

|**Pseudo Sample** | 123 abc 456 *ARABIC* 789 |
| -----------------|:-------------------------|
|**Arabic Sample** | 123 abc 456 أبجد 789|
|**Sample Buffer** |![sample buffer](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/buff.png)|

| Option | LTR Context | RTL Context |
| ------------ |----------|----------|
| None | ![](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/01.png) | Same as LTR. |
| Contextual | ![](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/02.png) | ![](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/03.png) |
| National | ![](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/04.png) | Same as LTR |
<br>

### Problem Statement

Most of the available frameworks/technologies lack the contextual shaping option of national digits. Contextual digit shaping is a very important feature as the Arabic users don’t expect to see Arabic-Indic numerals or European numerals only when they have mixed English and Arabic data. 

For example if a document has many paragraphs some in Arabic and others in English, in the Arabic paragraphs the Arabic users expect to see national or Arabic-Indic numerals, and in the English paragraphs the Arabic users expect to see European numerals.

Since the mixed English and Arabic data cases are very common in Arabic region, the same case with numerals is very common too.

| ![Figure 1](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/fig1.png) |
|:--------------------------------:|
|Figure 1: Sample communication thread using IBM Lotus Notes|

|![Figure 2](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/fig2.png)|
|:----------------------------:|
|Figure 2: Sample Arabic and English list of references.|

Arabic paragraphs that list references’ names(which include numerals) are very common for Arabic users as well. In that case the Arabic users expect to see the numerals as European not Arabic-Indic.

|![Figure 3](https://raw.githubusercontent.com/ACGC/national_numeric_shaping_draft/master/images/fig3.png)|
|:----------------------------:|
|Figure 3: Sample Arabic paragraph where users expect to see European numerals.|
<br>

**_So direct conversion of digits from latin to national will not fulfil Arabic users’ needs.
Contextual behavior is the core numeric shaping option that is needed from the Arabic users’ point of view._**
<br>

**Comment by gkalpak** [comment]
:+1: for the comprehensive and well-structured write-up !

But good you be more specific on how it relates to Angular ?
Are you requesting a new feature ? What exactly ? What part of the framework is it related to (filters, directives, etc) ?

**Comment by gkalpak** [comment]
So, if I understand correctly, a filter could be passed some string including letters and numbers and decide how to display the number (based on the preceding letters). I'm not 100% sure of the rules that govern the decision about european vs arabic-indic digits, but it shouldn't be too hard (at least for the majority of cases).

That said, this doesn't sound like a good fit for the core. We try not to make all users pay the cost (e.g. increased size) for a feature only few of them will use, especially if it's something that can easily be implemented as a 3rd party module (such as this one, afaict).

**Comment by ragabo** [comment]
@gkalpak , Can you please advice how can I include that in 3rd party module (non-core).

**Comment by gkalpak** [comment]
@ragabo, since you mentioned it would be a filter, it should be registered using the `.filter` method of a module. E.g.:

```js
angular.
  module('arabicNumericShapingSupport', []).
  filter('contextuallyShapeDigits', function contextuallyShapeDigitsFilter(/* Inject whatever you need here */) {
    return function contextuallyShapeDigits(text) {
      // Process the `text` as necessary and return a new text with escaped digits...
    };
  });
```

Then you can include it in any app like this:

```js
angular.
  module('myApp', ['arabicNumericShapingSupport']);
```

And finally you can use it either in views or from JS (e.g. controllers, services etc):

```html
<div>{{ someText | contextuallyShapeDigits }}</div>
```
or
```js
.controller('MyCtrl', function MyCtrl(contextuallyShapeDigitsFilter) {
  this.text = contextuallyShapeDigits('some text');
})
```

**Comment by ragabo** [comment]
@gkalpak, thanks for code clarification, but I was asking about how to include my support in Angular as a new feature (even if it's not included to core). But I want my support to be included in Angular package.

**Comment by gkalpak** [comment]
@ragabo, angular packages/external modules, such as `ngAnimate`, `ngRoute` etc, are no different than regular external modules. The only difference is that the Angular team is in charge of maintaining and enhancing them.

These modules provide functionality that we believe will be useful to most people, but is not strictly necessary for running an Angular app, nor does it need to be coupled with the core.

--
At this point, I don't think it makes sense to add another module with the functionality we are discussing here. The best thing about Angular's extensibility is that _anyone_ can create and publish an external module which can very easily be used in any app and benefit the whole community.

You are in a much better position than most of the team members to implement and maintain the necessary functionality anyway :smiley:

--
I'm going to close this as _not core_, but feel free to continue the discussion below.

**Comment by ragabo** [comment]
I have my support for Arabic numeric shaping. Please let me know how to include this file as plugin or external module. Thanks in advance

**Comment by ragabo** [comment]
@gkalpak Now I am done with the Arabic Numeric Shaping support and I need to publish it under angular to be angular-hosted project. Is it possible to make a repository under angular like angular/angular.js/arabicNumericShaping instead of publish it under my_username/arabicNumericShaping? Or if there is any other way to make it angular-hosted project, please advice. if yes, how to do so? thanks in advance

**Comment by gkalpak** [comment]
@ragabo, like I said before, it is not a good idea t make this an "angular-hosted" project. You need to publish (and maintain) it (github and npm are popular places), but maybe you can list it under "complementary libraries" in our Developer Guide, so people that need it can find.

[1]: https://github.com/angular/angular.js/blob/master/docs/content/guide/external-resources.ngdoc
