### ISSUE TITLE
docs(ngComponentRouter): incorrect installation instructions on the module's API page

### ISSUE THREAD

**Issue by thorn0** [angular/angular.js#14329]
The 'Installation' part here is totally misleading:
https://docs.angularjs.org/api/ngComponentRouter

**Comment by Narretz** [comment]
Yeah, that's auto generated ...

**Comment by OlenDavis** [comment]
Is `ngComponentRouter` as documented there though (aside from the installation instructions), actually accurate? I've been using https://github.com/rvl/bower-angular-component-router for the time-being, but should I expect to be able to use ngComponentRouter as documented [here](https://docs.angularjs.org/guide/component-router) anytime soon? And if at all possible, do you anticipate it to be available at any particular milestone, such as 1.5.4 or 1.5.5?

**Comment by gkalpak** [comment]
> should I expect to be able to use ngComponentRouter as documented [here][1] anytime soon

@OlenDavis, you should be able to use it like this already. If you have found any issues/inconsistencies, please do report them.

That said, the router is still far from final (so changes are to be expected in the near future) and we are still figuring out the best way to distribute it for ng1. Right now it is a separate package on npm (`@angular/router`).

[1]: https://docs.angularjs.org/guide/component-router

**Comment by rekna1** [comment]
Installation instructions for component router are confusing and incomplete... on IE11 component router does not work at all, something about missing shims ?
I know it's been developped as part of angular2 but it should be part of the distribution of angular 1.5.x
(e.g. https://code.angularjs.org/1.5.3/)

**Comment by Josh68** [comment]
@rekna1 - All respect to the Angular team, I second your comment. Anything we can do to help at least put some extra content in documentation, I'd like to know. I'm not sure where the code belongs, but I understand both components and the router are tracking development in ng2. That said, it seems like the inclusion of components in ng1 would have been better left until the router was ready for release. The fact that they're both fully documented in 1.5.x docs (guide and API) suggests they're both in release, not "still far from final."

BTW, without cloning master, building ng2 completely, and then running `gulp buildRouter.dev`, [https://www.npmjs.com/package/ngcomponentrouter](https://www.npmjs.com/package/ngcomponentrouter) may give you a more recent version than `npm install @angular/router`. Not sure which of those three approaches is best at the moment.

**Comment by rekna1** [comment]
So could anyone from the angular team please comment on this? Since the docs of angular 1.5 describe component router, as if it is complete and functional:
- is the component router officially released?
- how do we install a stable version?
- what about the missing shims (I think it is es6-shim that is needed)

**Comment by Josh68** [comment]
Just to be clear, pop open the source and you'll see it's far from complete. I wish there could be some more meta-documentation about timeline, and you're right that it's really difficult to know the actual released version, because the source code is tied in with ng2 but the documentation is in ng1. You'd expect the router to be at version 1.5.3, but it's actually at 0.2.0 or something, at the moment.

**Comment by gkalpak** [comment]
We are still figuring out the best strategy to version and distribute the `ngComponentRouter` for ng1.
In the meanwhile, the installation instructions have been updated with fad6c7c.

**Comment by zilkey** [comment]
Now that the version 2 rcs are out, I had to use this to install:

```
npm install @angular/router@0.1.0
```

I couldn't find any packages in the new rcs that looked like `angular_1_router.js`

**Comment by gkalpak** [comment]
@zilkey, you should probably be using v0.2.0 (the guide has been updated and I just updated the API docs (but it will take some time to propagate)).
