### ISSUE TITLE
Disabling Debug Data - debugInfoEnabled(false)

### ISSUE THREAD

**Issue by projectmanagementsystem15** [angular/angular.js#14331]
When i try this function it is not working.

App.js
var app = angular.module('test', ['ngMaterial', 'ngMessages','ngRoute', 'ngResource', 'ngAnimate',  'md.data.table']);

Example 
app.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(true);
}]);

Please, Can you give suggestion to me,

**Comment by gkalpak** [comment]
@projectmanagementsystem15, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
