### ISSUE TITLE
iOS 5 Safari - Application with html5Mode(false) when linking to external website breaks the app

### ISSUE THREAD

**Issue by dudevon** [angular/angular.js#1433]
I've tested this on iPad and iPhone iOS 5 and both fail. This can be reproduced using the "angular-phonecat" tutorial application.

I've forked it with one small change, link to google before the phones list.

https://github.com/dudevon/angular-phonecat

Once you click the external link and go back to the application using the back button, the application fails to load and consequent hits come across the following errors:

Error: 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations : ....

Has anyone encountered this bug before since it's very frustrating since the web application works in all browsers apart from iOS Safari?

**Comment by Narretz** [comment]
The issue seems to have been fixed according to the webkit report: https://bugs.webkit.org/show_bug.cgi?id=34679
