### ISSUE TITLE
How to get all the same ngModels dynamically and put them into an array

### ISSUE THREAD

**Issue by Erichain** [angular/angular.js#14335]
> Version of Angular: 1.3.0

> Platform: Mac OS X 10.11

I have mutiple ngModels in my page that are the same. And I would add one by one dynamically.

So, how can I get all the same ngModels and put them into an array ?

Here is a pen to show my question:

http://codepen.io/Erichain/pen/QNgJgL?editors=1010

**Comment by Narretz** [comment]
Please ask questions on of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
