### ISSUE TITLE
.finally() promise for $http throwing error on android 2.3

### ISSUE THREAD

**Issue by madebycambiamentico** [angular/angular.js#14334]
*bug - angular 1.2.29 - 1.4.9* on android 2.3.6

using `$http`, the promise `then()` works as expected, but promise `finally()` throw error and stop angular from parsing the html.

*bug - angular 1.5.3* on android 2.3.6

angular not working at all.

**Comment by Narretz** [comment]
You mean if you are doing something like this:
```
myPromise.then(function() {}).finally(function() {})
```

That's because finally is a reserved keyword on Android 2.3. Try the bracket notation instead: `['finally']`.
