### ISSUE TITLE
JqLite html() return invalid html;

### ISSUE THREAD

**Issue by jack-fdrv** [angular/angular.js#14349]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I am very new in Angular world, but.
I have directive which set to `$scope.element` = some DOM element which look like this 
`<div pdfdummy>
        <img  src="img/logo.svg" alt="Logo" />
    </div>`
in controller I call it like that
`angular.element($scope.element).html() `
and it returns 
`<img  src="img/logo.svg" alt="Logo">`
- without back slash, so the html start be invalid for some services like Doc Raptor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
No problem http://plnkr.co/edit/9wYDdufWrU82NGGiYnr8?p=preview

**What is the expected behavior?**
Return valid html.

**What is the motivation / use case for changing the behavior?**
Users cant create pdf with invalid html.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Mac Book. 10.13.3
Last Chrome.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Dont know yet.

**Comment by Narretz** [comment]
jQuery html() produces the same result. I do think the pdf creator should be able to handle the tag without a /. Actually, it's even possible that the / is redundant for void elements.

**Comment by Narretz** [comment]
Here's an explanation about jquery html: http://stackoverflow.com/questions/17586653/prevent-jquery-html-from-removing-self-closing-tag-slash So it's browser behavior and your pdf generator should be able to handle it.
