### ISSUE TITLE
Component controllers have constructors fired with a different `this` than `$onChanges` later on

### ISSUE THREAD

**Issue by mgol** [angular/angular.js#14359]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

Component controllers have constructors fired with a different `this` than `$onChanges` later on.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

1. Open http://plnkr.co/edit/oeulkVsfau0HfkHTdyeI
2. Open the console.

**What is the expected behavior?**

There should be no error.

**What is the motivation / use case for changing the behavior?**

The error is caused by the fact that the constructor is fired with a different `this` than the `$onInit` method later on. This is a bug, there should be only one instance of the controller.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

The current 1.x snapshot as well as the `v1.5.x` branch tip are buggy. It seems to work fine with Angular 1.5.3.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by mgol** [comment]
I'm setting a milestone to 1.5.4 as this seems to be a regression from 1.5.3.

**Comment by petebacondarwin** [comment]
I believe that this is fixed by #14355
