### ISSUE TITLE
Directives applied according the condition

### ISSUE THREAD

**Issue by knezik** [angular/angular.js#14356]
Steps to reproduce and a minimal demo of the problem
https://jsfiddle.net/c8fh7k8p/1/

Current behavior
It inserts/uses directive no matter the condition is true or false.

Expected/desired behavior
It should respect the condition.

**Comment by Narretz** [comment]
It's not possible to apply directives conditionally. You'll have to put the condition inside the directive (e.g. based on an attribute value)
