### ISSUE TITLE
[mis-orgnized] different menus on same website: https://angularjs.org/

### ISSUE THREAD

**Issue by Eddy1028** [angular/angular.js#14351]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
I currently start to learn angualrjs on https://angularjs.org/, but the menu bar did make me misunderstand, and I feel mess about what I am going to learn. Could you make them uniform?

![home1](https://cloud.githubusercontent.com/assets/6291736/14165147/4b5fa32c-f738-11e5-8e81-68359fadcdb4.png)
![home2](https://cloud.githubusercontent.com/assets/6291736/14165150/517ce4cc-f738-11e5-8760-16b5f7a778b3.png)

**What is the expected behavior?**
All pages with a same menu bar.

**Comment by orifzunnunov** [comment]
@Eddy1028 Hey Eddie this is a cosmetic issue, the "arrow" is not showing up. But I think this shouldn't stop you from learning AngularJS.

Below classes might be missing from guide page.

navbar .dropdown-menu:after and .navbar .dropdown-menu:before classes might be missing.

 **{
    content: '';
    display: inline-block;
    border-left: 6px solid transparent;
    border-right: 6px solid transparent;
    border-bottom: 6px solid #ffffff;
    position: absolute;
    top: -6px;
    left: 10px;
}**

**Comment by Narretz** [comment]
The issue is that the links in the menu are different on the main page and when you are in the docs: For the main page, this issue is tracked here: https://github.com/angular/angularjs.org/issues/80

**Comment by linuxjackto7** [comment]
Deadpool (2016) 720P Download ：https://movied.org/deadpool-2016_801438.html
