### ISSUE TITLE
Angular v1.5, Directive with class="{{className}}", addClass('extraClass') in link function doesn't work

### ISSUE THREAD

**Issue by aarongan** [angular/angular.js#14354]
Hi, 
I tried to inject extra className in link function using addClass method, i found a problem is when my directive has expression in class, the injection just ignore and no error message. 
eg
directive with class="class-{{ id }}"

and in directive link function, i tried manually addClass('extraClassNam'), this extraClassName doesn't get injected into Dom element after link.  

I noticed that, in link function time, expression didn't get eval compare to previous version.

thanks,
Aaron

**Comment by aarongan** [comment]
Continue my investigating... 
This is happening in all attributes which i would believe is mechanism change. 

Tried any attributes with expression in your template, and add attr('my-attribute', 'xxxx'), it wouldn't work unless i remove expression {{}} in the templates. =(

**Comment by Narretz** [comment]
It's a known issue: https://github.com/angular/angular.js/issues/12813
There are currently no plans to fix this, as it is a complex problem. But PRs are welcome.
