### ISSUE TITLE
Select control doesn't render correctly when inside of ng-repeat in IE10

### ISSUE THREAD

**Issue by codan84** [angular/angular.js#14358]
This is a bug in IE10 (I didn't check other versions of IE), checked with Angular 1.2.1 and latest 1.5.1.

If a `select` control with options generated by ng-repeat is nested within another ng-repeat, on initial navigation to the page we can see angulars `{{variable_name}}` as a selected text of the select box. Only after clicking on the select box the `{{variable_name}}` is being correctly replaced by a value.  
Investigating the DOM, the values are correctly populated, it seems like IE refuses to render them correctly.  
The problem only exists if the `select` is inside ng-repeat, everything works fine if it is not.
Here is a [jsfiddle](http://jsfiddle.net/fsqvstmp/7/) replicating the problem.

**Comment by thorn0** [comment]
Can't reproduce in IE11.

**Comment by thorn0** [comment]
In IE10, how stable is it? Does it happen always or from time to time?

**Comment by Narretz** [comment]
Can reproduce in IE10. What a strange problem. I guess we could try to trigger a re-render somehow, as it looks like a similar problem to https://github.com/angular/angular.js/issues/6211

**Comment by Narretz** [comment]
This works in >= 1.6.0
