### ISSUE TITLE
Cannot bind to all ngComponentRouter events

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular.js#14350]
version `1.5`

I have multiple components using the `routeOnActive` in their component controllers and I am trying to bind to any event for `routeOnActive`, however I can't seem to pick it up on `rootScope`.  I tried specifying both `routerOnActivate` and `$routerOnActivate` as the name of the event and neither worked.
```
if (typeof angular.module('ngComponentRouter') !== 'undefined') {
                            this.$rootScope.$on('routerOnActivate', function (next, prev) {
                                //Do stuff
                            });
                        }
```

**Comment by linuxjackto7** [comment]
Deadpool (2016) 720P Download ：https://movied.org/deadpool-2016_801438.html

**Comment by Narretz** [comment]
We are currently tracking comp router issues here: https://github.com/angular/angular/issues (even for ng1). Can you please open an issue there? Thanks!
