### ISSUE TITLE
Angular Error: compile is not defined

### ISSUE THREAD

**Issue by klmuralimohan** [angular/angular.js#14388]
Hi,

I have been an issue since long time. Can you please help me out.

Actually, I want to use table directive in many places. so I have created a directiv and binds with angular UI grid. But I'm getting compile error like,

What I did wrong here?

**HTML**
<div ng-controller="ctrl1 as two">
	<ltcg-table><ltcg-table>	
</div>
<div ng-controller="ctrl2 as two">
	<ltcg-table><ltcg-table>	
</div>

**JS**
function one($scope) {
	                   this.song="Murali";
	                  // alert("gg");
	                    $scope.gridOptions = {
				        enableSorting: true,
				        columnDefs: [
				          { name:'firstName', field: 'first-name' },
				          { name:'1stFriend', field: 'friends[0]' },
				          { name:'city', field: 'address.city'},
				          { name:'getZip', field: 'getZip()', enableCellEdit:false}
				        ],
				        data : [      {
				                           "first-name": "Murali",
				                           "friends": ["friend0"],
				                           "address": {street:"301 Dove Ave", city:"Laurel", zip:"39565"},
				                           "getZip" : function() {return this.address.zip;}
				                       },
				                        {
				                           "first-name": "Mohan",
				                           "friends": ["friend0"],
				                           "address": {street:"301 Dove Ave", city:"Laurel", zip:"39565"},
				                           "getZip" : function() {return this.address.zip;}
				                       }
				                   ]
				      };
				      //alert($scope.gridOptions.columnDefs[1].name);
				       //alert($scope.gridOptions);
	         }

        
         function two ($scope) {
                   this.song="Mohan";

                   $scope.gridOptions = {
				        enableSorting: true,
				        columnDefs: [
				          { name:'firstName', field: 'first-name' },
				          { name:'1stFriend', field: 'friends[0]' },
				          { name:'city', field: 'address.city'},
				          { name:'getZip', field: 'getZip()', enableCellEdit:false}
				        ],
				        data : [      {
				                           "first-name": "Cox",
				                           "friends": ["friend0"],
				                           "address": {street:"301 Dove Ave", city:"Laurel", zip:"39565"},
				                           "getZip" : function() {return this.address.zip;}
				                       },
				                        {
				                           "first-name": "Cox",
				                           "friends": ["friend0"],
				                           "address": {street:"301 Dove Ave", city:"Laurel", zip:"39565"},
				                           "getZip" : function() {return this.address.zip;}
				                       }
				                   ]
				      };
				      //alert($scope.gridOptions.columnDefs[1].name);
				       //alert($scope.gridOptions);
         }
myApp.directive('ltTable', function($compile) {
            return {
                restrict: 'E',
                transclude: true,       
                replace: false,                            
                scope: {  },
                controller: Controller,
		      	controllerAs: 'Controller',
		       	bindToController: true,		       
		       	compile: compile   
            }
                
        });
Error: angular.min.js:102 ReferenceError: compile is not defined **But  I could load the content**

**Comment by 17cupsofcoffee** [comment]
`compile: compile` - Where is the `compile` function defined? There doesn't seem to be one in the code you posted, so it makes sense that you'd get a ReferenceError when you try to use it.

Also, did you just ignore the big message that appears in the 'new issue' box by default?

***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
