### ISSUE TITLE
$compile does not work as expected when compiling a valid html document

### ISSUE THREAD

**Issue by Mestika** [angular/angular.js#14392]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When compiling (using $compile) a fully html document which contains the tags `html` `head` and `body` the behaviour differs for the behaviour on a html string without these.
It doesn't bind and render the same way. The ng-model does not seem to render when the html tags are present. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Please see [this plnkr demo](http://plnkr.co/edit/TiVoObX3TaSVF8GIMhjQ?p=preview)

**What is the expected behavior?**
To compile the full html content and render it as expected with data-bindings and scope. 

**What is the motivation / use case for changing the behavior?**
I wanna create a HTML Email template service where I can build my HTML email templates with data fetched from a backend system. Get the template via $http, compile the response (the html template) and add the scope data to the $compile function. Returning everything in the end back to the backend which handle the send email part.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular 1.5.0 with Chrome 49.0.2623.110 (64-bit)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This isn't related to `$compile` per se, but to how `jqLite/jQuery` parse the passed in HTML-string to create and jqLite/jQuery element. `<html>`, `<head>` and `<body>` are special elements and you can't put them inside another element or a document fragment.

You could work around this, by creating an `<html>` element manually and passing that to `$compile()`, but that might not work on older browsers (e.g. <IE9) (see below). There is also the issue that you arent't allowed to have a "raw" binding (i.e. `{{ ... }}`) inside the `head`, so if you don't put it inside a tag, it can get automatically moved to the body by the browser.

```js
var htmlContent = res.data.substring(
    res.data.indexOf('<head>'),
    res.data.lastIndexOf('</body>'));
var doc = $document[0].implementation.createHTMLDocument('inert');
var html = doc.documentElement;
html.innerHTML = htmlContent;

$compile(html)(scope);
```

[Updated plnkr][1]

--
This is just a workaround though (and probably a not very robust one).

Closing as this is more related to how browsers treat specific elements.
Also note, that we should keep in line with how jQuery handles this.

[1]: http://plnkr.co/edit/V7QTQL10KXu1vzfaRspL?p=preview
