### ISSUE TITLE
"this" in controllerAs function sometimes null for small set of users

### ISSUE THREAD

**Issue by neb636** [angular/angular.js#14393]
**What is the current behavior?**
In Angular 1.5 with controllerAs sometimes "this" is null inside controller function. A small fraction of our user base seem to be affected after we deployed 1.5 and is being reported from our error tracking. Here are a couple of error reports. I have not been able to replicated this issue myself.
https://sentry.modelo.io/share/issue/322e323934/
https://sentry.modelo.io/share/issue/322e333531/

**What is the expected behavior?**

"this" will always refer to the function passed into .controller()

**Which versions of Angular, and which browser / OS are affected by this issue?**

This error was never reported before Angular 1.5. Seems to be effecting 15 of our 3000 users. All on Windows 7 and various versions of Chrome.

**Other information**
Possibly related to https://github.com/angular/angular.js/commit/8955cfb6462f79a32caa641ffc002f1522f08220. 

Maybe has to do with change from args.unshift({}); to args.unshift(null);

**Comment by gkalpak** [comment]
It sounds more like a browser bug (maybe one with an early implementation of Class in Chrome).
I saw you are using several ES6 features. Are you using classes as well ?

I don't think we can do much, unless we figure out where it happens so we can reproduce it (e.g. what versions of Chrome are affected, what does the code that triggers this look like etc).

**Comment by thorn0** [comment]
@neb636 Do you use any polyfills for `Function.prototype.bind`? This part of the stack trace looks suspicious:
![image](https://cloud.githubusercontent.com/assets/94334/14411693/48b49c0e-ff58-11e5-9ee2-38a7f93a46ac.png)

**Comment by neb636** [comment]
So we actually are not using classes at all. Here is a Gist of the transpiled code for one controller that has this issue. https://gist.github.com/neb636/917ce177cf56c025c7888289a444a550

**Comment by thorn0** [comment]
Your users may have some sloppy 3rd party code on the page (e.g. ads), which adds the polyfill. Or it may be a browser extension.

**Comment by neb636** [comment]
Closing as is an issue with end users browsers.

Ended up finding out all users being effected are actually in China but using a VPN so they appeared to be in all different countries. Most likely some bad Chinese chrome extension.

Thank you @thorn0 for pointing us in the correct direction with the anonymous function returning from apply. Also thank you to @gkalpak for initial suggestions and triaging the issue.
