### ISSUE TITLE
Input of type number has incorrect min and max validation when the value being checked is zero

### ISSUE THREAD

**Issue by cmbrownfield** [angular/angular.js#14398]
Tested in Angular 1.5.3:

The numberInputType function definition in Angular source code always declares zero to be valid with respect to min and max validation.  The ctrl.$isEmpty function returns true for zero (which is the issue).

To reproduce:
set min to any number greater than 0 (say 100) and then type 0 into the input and check validation.
set max to any number less than 0 (say -100) and then type 0 into the input and check validation.

The definitions for ctrl.$isEmpty may be incorrect for other usages, but I noticed it is redefined within Angular source code.  The best fix might be to redefine it within the numberInputType function to account for zero, but I haven't looked at all the usages to know for sure.

**Comment by gkalpak** [comment]
I can't reproduce the problem. AFAICT, `0` is treated correctly with `input[type="number"]` (tested [here][1]).
If you see something different, please provide a runnable demo.

[1]: https://codepen.io/ExpertSystem/pen/XdZrpe?editors=1000
