### ISSUE TITLE
why html tags hiding 

### ISSUE THREAD

**Issue by flik** [angular/angular.js#14395]
https://plnkr.co/edit/gWFKX34woucJRgDrJCdd?p=preview

It is hiding html paragraph tags in text box.

How can I show them.

**Comment by gkalpak** [comment]
This is not how things work in Angular. The model is your source of truth. Any data initialization should be done there. E.g. you should set `name` to the value you want and the input field would be updated accordingly (not the other way around). [Updated plnkr]

--
That said, this repository is reserved for bug reports and feature requests.
Please, use one of the [appropriate channels][1] for general support questions (such as this).

Thx !

[1]: https://plnkr.co/edit/gWFKX34woucJRgDrJCdd?p=preview
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
