### ISSUE TITLE
Angular http post json content-length : 0

### ISSUE THREAD

**Issue by robinkedia** [angular/angular.js#14409]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When doing http post json data content length randomly is set to zero. The json is still present in request body.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Random behavior. On subsequent request it works

**What is the expected behavior?**
Content length should be greater than 0 if post body has data.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
Angular doesn't set content length. It's probably some browser or server-config issue.
We can't do much without a reproduction, though.

Closing as this is not actionable. Feel free to reopen if you can provide a reproduction (even a random one) and also more details on the platforms/browsers/versions this issue affects.
