### ISSUE TITLE
ngif ? directive and audio

### ISSUE THREAD

**Issue by unlangchan** [angular/angular.js#14415]
#Request Type: bug

#Current Behavior:
  when loaded DOM:
     Chrome 49:  ng-if==false ? the audio  object is deleted :
                                when  ng-if(first) == true ? a directive translate to element  create DOM Object                   twice :a directive translate to element  create DOM Object once;
 Firefox 42: ng-if==false ? the audio  object is not deleted : 
                                           a directive translate to element  create DOM Object once;

#Reproduce?
   <Audio> or directive created based <Audio> use  ng-if  control;
  http://plnkr.co/edit/vVC7KYMKUhjLTAdCWzbw
#Expected behavior?
  when loaded DOM:
         ng-if==false ? the audio  object is deleted : a directive translate to element only create DOM Object once;  
#Versions
This was tested in Angular 1.5.0 in Chrome 49 and Firefox 42

Finally ,bug Will not happen when using ng-src ,but I am confused;

**Comment by Narretz** [comment]
Hi, can you please add a description of the problem / steps to reproduce either here or in the plunkr? We don't have time to decipher the problem from code only.

**Comment by unlangchan** [comment]
@Narretz; Hi, i need help;

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
