### ISSUE TITLE
Linebreaks in output break the ng-bind-html functionality

### ISSUE THREAD

**Issue by a2liang** [angular/angular.js#14412]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
For ngSanitize, the html that I want to display via ng-bind-html cannot have newlines.  All the html must be on one line, with no breaks

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

The following line works as a JSON for ng-bind-html

```html
<table><tr><td>Name</td></tr></table>
```
 

but the equivalent line with readable line breaks does not

```html
<table>
     <tr>
          <td>Name</td>
     </tr>
</table>
```

**What is the expected behavior?**
returning a JSON string of HTML code, with no line breaks, makes code difficult to read.  I would expect that newlines are ignored so I can format the resulting

**What is the motivation / use case for changing the behavior?**

readability in code, or some documentation of this issue somewhere

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Can you please provide a minimal demo of the problem via https://plnkr.co or similar? (template: http://plnkr.co/edit/tpl:yBpEi4).

**Comment by a2liang** [comment]
http://plnkr.co/edit/RPZghKYVeh8jb2Lasz5V

I may be an idiot.  PLunker shows that my newline breaks in app2.js break the file.

Comparing app.js and app2.js, app2.js is just readable HTML.

I'm missing something, right?
