### ISSUE TITLE
Decimal separator for Korean language

### ISSUE THREAD

**Issue by krish-ram** [angular/angular.js#14417]
**Do you want to request a *feature* or report a *bug*?**
Currently, the decimal separator for currency in korean language is .(dot). But this should be ,(comma). Please change this and update the angular_locale_ko_kr.js files. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Please set the locale to korean and use a currency filter. This will show you a currency with dot instead of comma. 

**What is the expected behavior?**
For korean language, the decimal separator should be comma and not dot.

**Comment by gkalpak** [comment]
Angular.js uses the [Google Closure I18N library][1], to generate its own I18N files. This means that any changes to these files would be lost the next time that we import the library. The recommended approach is to open an issue (or submit a patch) to the I18N project directly.
Then the changes will propagate to Angular the next time we pull the date for there.

Closing as this is not actionable (As far as Angular is concerned).

[1]: https://github.com/google/closure-library/tree/master/closure/goog/i18n

**Comment by clichedmoog** [comment]
Even this is a closed issue but I should inform that decimal separator in ko is a dot.
As I know South and North Korea both GROUP_SEP: "," and DECIMAL_SEP: "." with gSize: 3
If I follow the notation, 900000.9₩ would be 900,000.9₩
