### ISSUE TITLE
Not possible to install 1.5.4 by bower

### ISSUE THREAD

**Issue by morgoth** [angular/angular.js#14434]
I'm getting error `bower angular-messages#1.5.4  ENORESTARGET No tag found that was able to satisfy 1.5.4` when trying to install angualr 1.5.4 by bower.

I can see that repos like https://github.com/angular/bower-angular-messages are missing 1.5.4 tag.
Is it automated process or when new versions are available to install?

**Comment by Narretz** [comment]
1.5.4 hasn't been released officially. It's on code angularjs but not on bower npm or cdn.

**Comment by Narretz** [comment]
More precisely, there was an issue with the release and not all modules have benn published.

**Comment by bloveridge** [comment]
@Narretz I just encountered this as well, 1.5.4 has been out over a day now, is documented in the changelog, etc. Is it possible to get a notification here when the modules have been successfully published to bower et al?

**Comment by Narretz** [comment]
Well we usually don't botch the releases, but that said:  when the changelog appears on github, the release hasn't run yet. When the files are on code.angularjs they are also on bower and npm unless the release failed (unusal). If you want 100% assurance wait for the announcement on the angularjs twitter channel.

**Comment by Narretz** [comment]
We are going straight to 1.5.5 (at the beginning of next week), so please wait for that release.
