### ISSUE TITLE
Bug: insert dom before page loaded made form submit be stopped.

### ISSUE THREAD

**Issue by masquevil** [angular/angular.js#14431]
when i run such code with jquery and angular:
```
 $input = $('<input type="text">');
 $div.prepend($input);
```

the input's closest form (not ng-form and there is no controller outside) will be automatic add an eventListener by angular:
```
var t = function(c) {
    a.$apply(function() {
         m.$commitViewValue();
         m.$setSubmitted()
     });
    c.preventDefault()
  } ;
d[0].addEventListener("submit", t, !1);
```

so I can't use form submit anymore.
if I change my code into this, it will be ok:
```
 $input = $('<input type="text">');
 $(function(){
    $div.prepend($input);
 });
```

**Comment by Narretz** [comment]
Hi, thanks for the report. Can you please put a demo of the problem in a https://plnkr.co or similar? That makes it much easier to assess the problem.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
