### ISSUE TITLE
ngChange is not working when ngChange in ngRepeat 

### ISSUE THREAD

**Issue by re661b** [angular/angular.js#14453]
I'm trying to use ngChange in ngRepeat [jsfiddle](http://jsfiddle.net/ax78djjL/1/) 

1.click [Item one] trigger ng-change event
2.click [Check All] can't trigger ng-change event
AngularJS v1.1.1
Thanks for any advice

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

<sub>Also, note that v1.x is very old and not supported any more. You should upgrade to a newer version.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
