### ISSUE TITLE
Angular one way data binding not working,

### ISSUE THREAD

**Issue by shyjymathew** [angular/angular.js#14456]
[anglr.txt](https://github.com/angular/angular.js/files/223612/anglr.txt)

I have two ng-repeats for customer and number arrays. I am passing the first array object to the second ng-repeat and trying to change the first array object element in a particular condition. i.e, the name should change to 'Mary' only in the 4th iteration of the second array.
 Excepted output : Jill - DL 
                            Jill - DL 
                            Jill - DL 
                            Mary - DL 
                            Jill - DL. 
But when I run the code all the 'Jill' is replacing with 'Mary'.
(output : Mary - DL 
              Mary - DL 
              Mary - DL 
              Mary - DL 
              Mary - DL.)
Could you please help me to find a solution to change name only in the 4th iteration?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
