### ISSUE TITLE
IE Edge Compatible issue with angular Js

### ISSUE THREAD

**Issue by amshekar** [angular/angular.js#14454]
My angular js Web application is working fine in dev environ ment as expected once its deployed to higher environment . While running/browsing the application in IE Edge the application by default selecting the 8 and my application is not working since ie 8 wont support angular js.

So tried changing the  meta tag to override the compatable view  setting in my code as follows

Trial `1)
**<!DOCTYPE html> 
<html> 
  <head> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> `**

Here in place of conent i tried with all possible options like 
IE=edge","IE=11","IE=EmulateIE11","IE=10","IE=EmulateIE10","IE=9","IE=EmulateIE9

Trial 2)

```
<system.webServer>
     <httpProtocol>
        <customHeaders>
           <add name="X-UA-Compatible" value="IE=edge" />
        </customHeaders>
     </httpProtocol>
  </system.webServer>
```

I tried in all possible ways but while browsing the application by default it is selecting the ie mode 8 and application not working.

Note: 
Before upgrading to i.e from 10 to  IeEdge the application was up and running correctly with out any override compatability code
My hosted environment has compatiable view settings by default so am trying to override default setting by above trials but no luck.
In Fiddler Http response header i can see the  X-UA-Compatible edge and in view source i can see the
<html> 
  <head> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

Any suggestions or any issue with Edge or my code ?

FYI
**Issue** But my application opening in ie8 by default in higher environment  ?
![edge compatiable issue _int env](https://cloud.githubusercontent.com/assets/16417812/14584653/4e39bb76-046e-11e6-8ac8-6d87838c4a28.jpg)

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

That said, maybe the problem is that Edge doesn't supprt compatibility modes anymore? http://superuser.com/questions/952607/is-there-a-compatibility-view-settings-in-windows-10-edge
