### ISSUE TITLE
Angular CDN 404

### ISSUE THREAD

**Issue by amilajack** [angular/angular.js#14461]
The CDN's for Angular 1.5.4 and 1.5.5 return 404's:

https://ajax.googleapis.com/ajax/libs/angularjs/1.5.4/angular.min.js https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js

**Comment by gkalpak** [comment]
1.5.5 is up now.
There were some errors with 1.5.4, so we skipped it.

**Comment by lpsBetty** [comment]
When is https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js available?

**Comment by gkalpak** [comment]
Soon (hopefully today)...
