### ISSUE TITLE
ES6 controller class with angular 1.5.5 has $onInit called before constructor

### ISSUE THREAD

**Issue by opadillaintegrify** [angular/angular.js#14469]
Bug

I'm using ES6 with angular 1.5.5 and using babel to convert to ES5.

```javascript
export class ReportConfigColumnDialogController {
    constructor($mdDialog, column) {
        'ngInject';

        // fired after $onInit
        this.column = column;

        console.log(this.column.Alias);  // has expected value
    }

    $onInit() {
        // fired first
        console.log(this.column.Alias); // this.column undefined at this point
    }
}
```

According to the docs at https://code.angularjs.org/1.5.5/docs/guide/component:
$onInit() - Called on each controller **after** all the controllers on an element have been constructed

That's not what I'm seeing in my code.  $onInit got called before the constructor.

BTW, the ES5 code generated by babel looks like this:

```javascript
var ReportConfigColumnDialogController = exports.ReportConfigColumnDialogController = function () {
	    ReportConfigColumnDialogController.$inject = ["$mdDialog", "column"];
	    function ReportConfigColumnDialogController($mdDialog, column) {
	        'ngInject';
	
	        _classCallCheck(this, ReportConfigColumnDialogController);
	
	        this.column = column;
	
	        console.log(column);
	
	        this.$mdDialog = $mdDialog;
	    }
	
	    _createClass(ReportConfigColumnDialogController, [{
	        key: '$onInit',
	        value: function $onInit() {
	            this.aliasQuestion.Answer = this.column.Alias;
	        }
	    }, {
	        key: 'save',
	        value: function save() {}
	    }, {
	        key: 'close',
	        value: function close() {
	            this.$mdDialog.cancel();
	        }
	    }]);
	
	    return ReportConfigColumnDialogController;
	}();
```

**Comment by gkalpak** [comment]
@opadillaintegrify, I wasn't able to reproduce it ([here][1]).
Could you create a live demo of the problem (you can form my CodePen or use anything else that works for you, e.g. plnkr, etc).

[1]: https://codepen.io/ExpertSystem/pen/oxydOb?editors=0011

**Comment by opadillaintegrify** [comment]
Here is a CodePen in which $onInit() doesn't get fired at all: https://codepen.io/anon/pen/YqvjLB.  Click on Launch Dialog and see console logs.

That CodePen is a fork of https://codepen.io/marcysutton/pen/PwJrrG but with babel turned on and the DialogController converted to an ES6 class.

```javascript
class DialogController {
  constructor($scope, $mdDialog){
    console.log('DialogController constructor');
  }
  
  $onInit() {
    console.log('DialogController $onInit');  // nothing in CodePen console
  }
}
```

Maybe my problem is specific to angular material design's dialog?  I only see the problem when using ES6 classes as controllers to the dialog as shown in the code pen above.  Typical controllers and components work correctly as demonstrated in your CodePen.

**Comment by dcherman** [comment]
Yep, looks like angular-material doesn't support the new lifecycle hooks for a variety of things right now.

https://github.com/angular/material/blob/master/src/core/services/compiler/compiler.js#L117

**Comment by gkalpak** [comment]
@dcherman is right. This is an issue with `ngMaterial` not supporting lifecycle hooks (yet).
Please, open an issue [over there][1]. 

<sub>(BTW, classes or Babel don't seem to have anything to do with this afaict.)</sub>

[1]: https://github.com/angular/material

**Comment by marcusjwhelan** [comment]
@opadillaintegrify  Have you tried this. 

```javascript
class DialogController {
  constructor($scope, $mdDialog){
    console.log('DialogController constructor');

    this.$onInit() {
        console.log('DialogController $onInit'); 
    }
  }
}
```

This works for me.

**Comment by kefimo** [comment]
I have the same problem, i think that the problem is comming from version of angular-material.
I don't need to use this proposition: 

> constructor($scope, $mdDialog){ console.log('DialogController constructor'); this.$onInit() { console.log('DialogController $onInit'); } }

> 
because the $onInit here it will be called on constructor phase and not after that.

**Comment by kefimo** [comment]
Also, if the controller instanciated by the router and not by the directive, the $onInit can not be fired.
