### ISSUE TITLE
documentation for input[checkbox] does not mention ng-checked

### ISSUE THREAD

**Issue by rosyatrandom** [angular/angular.js#14465]
https://docs.angularjs.org/api/ng/directive/ngChecked

ng-checked is surely relevent to input[checkbox]; it merits a mention!

**Comment by Narretz** [comment]
Do you want to open a PR which changes this? I think ng Checked isn't used much because ngModel can also be used to bind to checkbox. Im fact you can't use only one or the other.

**Comment by vgvenkat** [comment]
Can I take this one? I am guessing adding ngChecked to the Usage, Arguments and Example is enough, any suggestions?

**Comment by Narretz** [comment]
@vgvenkat Yes, please open a PR. I think a link to ngChecked with a short description should be sufficient.
