### ISSUE TITLE
@Input no longer resolves on subclassed components

### ISSUE THREAD

**Issue by asgerjensen** [angular/angular.js#14472]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug. 
Maybe its a design change. I've checked "breaking changes", but don't see anything specific to this.

**What is the current behavior?**
If you create two components A and B, and B extends A, then any @Input annotations on A are not bound in the template

This used to work, at least in beta.4

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

export abstract class A  {
	@Input('name') public name: string = '';
}

@Component({
	selector: 'somecomp',
	directives: [APP_DIRECTIVES],
	template:`<h1>{{name}}</h1>`,
})
export  class B extends A   {
}

Usage
<somecomp name="hello world"></somecomp>

**What is the expected behavior?**
That it would scan the inheritance tree, to pick up annotations from baseclasses, to avoid having to replicate annotations and add forwarding code in every subclass.

**What is the motivation / use case for changing the behavior?**
To allow base classes to implement shared behavior, while making subclasses that have different visual and user interactions, on the same basic data.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Worked in beta.4 

Tested in beta.15

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Might be a design change introduced between the two versions.

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular2. Please open an issue here: https://github.com/angular/angular/issues
