### ISSUE TITLE
empty template are treated as not exist in templateCache

### ISSUE THREAD

**Issue by oojerryoo** [angular/angular.js#14479]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
empty template are treated as not exist in templateCache

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
create a empty template, use template cache. and it is treated as not cached

**What is the expected behavior?**
should be treated as cached

**What is the motivation / use case for changing the behavior?**
i think this is a bug.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
multiple version include the latest

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
in $TemplateRequestProvider

this condition
if (!isString(tpl) || !$templateCache.get(tpl))

should be if (!isString(tpl) || !isUndefiend($templateCache.get(tpl)))

**Comment by Narretz** [comment]
What is the use case for adding an empty template to the  cache?

**Comment by rjamet** [comment]
I've seen that pattern a few times when people have a ng-include in a template used in test, but want to disable it and don't request over the network while testing other stuff. If you have an empty TrustedResourceUrl whitelist, then the $sce call will throw. I advised them to refactor to $templateCache.put('key', 'placeholder') or so.

I'm not sure about the proposed fix though. The point of that check is to bypass security checks for templates in cache, but the proposed fix does the opposite. Adding a .has(key) in the caches, and keeping track of what has been set might be a better option.

**Comment by rjamet** [comment]
Turns out that cacheFactory.js returns early with no warning when given an undefined value: https://github.com/angular/angular.js/blob/master/src/ng/cacheFactory.js#L161 

The commit (https://github.com/angular/angular.js/commit/0e2ac3cd705c02312e3a91786fc338fa0ab585dc) doesn't mention a particular reason, but this might be deliberate? @lgalfaso, maybe you remember?

**Comment by gkalpak** [comment]
The commit you mention did not introduce the behavior you describe. IT just fixed a "bug" where the value wasn't updated, but the entry was marked as "recently used". You need to look deeper :stuck_out_tongue: 

But, why would you want to store an undefined value. That's what you get anyway, when calling `get()` with a key that is not stored in the cache.

**Comment by rjamet** [comment]
Oops... Deeper leads to the initial commit of cachefactory (https://github.com/angular/angular.js/commit/497839f583ca3dd75583fb996bb764cbd6d7c4ac), so it's been that way forever, and those valueless cache adds never did anything.
