### ISSUE TITLE
$interpolate allOrNothing not working with multiple expressions

### ISSUE THREAD

**Issue by ClickerMonkey** [angular/angular.js#14476]
There's a bug in the $interpolate service that occurs when using the `allOrNothing` flag with a `text` that has multiple expressions. Even the [current documentation](https://code.angularjs.org/1.5.1/docs/api/ng/service/$interpolate) has an example that's incorrect.

[Here's a jsFiddle showing the bug](https://jsfiddle.net/Lkwnzu7v/1/)

The code found in the jsFiddle for convenience:

*HTML*
```
<div ng-app>
  <h2>Interpolating Testing</h2>
  <div ng-controller="InterpolateCtrl">
    <div>
      {{ interpolated1 }}
    </div>
    <div>
      {{ interpolated2 }}
    </div>
  </div>
</div>
```

*JS*
```
function InterpolateCtrl($scope, $interpolate) {
  // all or nothing (doesn't work because multiple expressions)
  var	exp1 = $interpolate('{{greeting}} {{name}}!', false, null, true);
  var context1 = {greeting: 'Hello'}; // , name: undefined
  $scope.interpolated1 = exp1(context1);
  
  // all or nothing (works because single expression)
  var exp2 = $interpolate('{{name}}', false, null, true);
  var context2 = {notname: 'World'};
  $scope.interpolated2 = exp2(context2);
}
```

*OUTPUT*
```
<div ng-app="" class="ng-scope">
  <h2>Interpolating Testing</h2>
  <div ng-controller="InterpolateCtrl" class="ng-scope">
    <div class="ng-binding">
      Hello !
    </div>
    <div class="ng-binding">
      
    </div>
  </div>
</div>
```

I've tested it in the most recent versions of Angular and they all have the problem.

**Comment by gkalpak** [comment]
You are using a very very old version of Angular (that probably doeesn't even support `allOrNothing`).
It is working as expected in the latest versions (e.g. [Updated fiddle][1]).

[1]: https://jsfiddle.net/j0ptfeqk/

**Comment by ClickerMonkey** [comment]
Sorry for wasting your time, I didn't even check that. I was seeing the issue in 1.5.1 and created a fiddle to replicate it not even realizing the angular version is very old (and I can't even select the proper angular version). If I can replicate it in 1.5.1 and its not due to my own error - I'll submit a new issue.

Thanks!
