### ISSUE TITLE
$routeProvider deep-copies its route objects before using them, which is probably not necessary

### ISSUE THREAD

**Issue by rjamet** [angular/angular.js#14478]
**Do you want to request a *feature* or report a *bug*?**
Bug, I guess ?

**What is the current behavior?**
$routeProvider deep-copies its route object in the beginning of the when('...', route) call, which is a heavy way of solving #8181 and #9731.

**What is the expected behavior?**
Handle routes without needing a deep-copy. 

**What is the motivation / use case for changing the behavior?**
I'm trying to plumb the Closure goog.html types in Angular as an alternative to the $sce types. These rely on a private marker that is passed to each instance by builders to ensure other classes can't fake them, and the deep copy breaks that link when passing an instance of that type in templateUrl.  

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Recent ones ? That was initially fixed in https://github.com/angular/angular.js/commit/b4770582f84f26c8ff7f2320a36a6b0ceff6e6cc . 

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I think this issue can be worked around by replacing templateUrl : safeTypeInstance with templateUrl : function(){return safeTypeInstance;}, but that's ugly. Martin Probst asked us to write an issue, saying "deep copying the entire object seems overkill if all you wanted was to (shallow) copy the fields in the angular.extend call.".

**Comment by mprobst** [comment]
I guess a repro would be 

```js
var obj = {};
$routeProvider.when('foo/bar', {
  someProp: obj
});
// route change somehow, then:
expect($route.current.someProp_.toBe(obj);
```

**Comment by Narretz** [comment]
Thanks for the report. The issue seems pretty minor, but if there's an easy solution that fixes it, we can merge it in. Do you want to open a PR for this?

**Comment by rjamet** [comment]
Cool, thanks :) I was a little out of my depth on this one.
