### ISSUE TITLE
Need to make accordion headers customizable in UI Bootstrap

### ISSUE THREAD

**Issue by AtulJain09** [angular/angular.js#14486]
I am creating accordion using library ui-botstrap-tpls-0.14.3.min.js.

But as far as I have experimented with ui-bootstrap accordion, it only lets the developer specify the content inside .panel-title, everything goes inside <h4><a>{{heading}}</a></h4>

In our UI we only have <h1> tag, so to maintain the hierarchy, we need <h2> tag instead of <h4> tag.

Please suggest how we can customize it in code to get <h2> tag without customizing the .library file.

Thanks

**Comment by Narretz** [comment]
This reads like an issue for https://github.com/angular-ui/bootstrap
