### ISSUE TITLE
XOR operation is absent in angular js.

### ISSUE THREAD

**Issue by debojyoti0391** [angular/angular.js#14485]
XOR operator is present in javascript.But it is not present in angular js

**Comment by Narretz** [comment]
Do you mean bitwise XOR (^)? Bitwise operators are not supported by Angular expressions. https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
If you need them, you should put them into controller functions.

**Comment by debojyoti0391** [comment]
Well angular can have its way of including or not including xor functionality.But it is not mentioned in the docs.I thought javascript has xor functionality so angular will have it too.I can implement the functionality with other operators.But the problem here is no documentation of its unavailability
