### ISSUE TITLE
Spacing in ng-repeat using key, value pair

### ISSUE THREAD

**Issue by LeftPinkie** [angular/angular.js#14481]
I'm using AngularJS v1.2.15, Firefox 45.

I am experiencing a bug with ng-repeat using key/value pair.

The error message returned is `ngRepeat:iidexp`

These will generate the error (space next to either of the parenthesis):
```
<div ng-repeat='( group, products) in FeaturedProducts'>
...
</div>

<div ng-repeat='(group, products ) in FeaturedProducts'>
...
</div>

<div ng-repeat='( group, products ) in FeaturedProducts'>
...
</div>
```

These will work (no space next to either of the parenthesis):
```
<div ng-repeat='(group, products) in FeaturedProducts'>
...
</div>

<div ng-repeat='(group , products) in FeaturedProducts'>
...
</div>
```

My object is:
```
FeaturedProducts => {
  "Test 1": [
    {
      "id": "1A",
      "title": "blah 1A"
    },
    {
      "id": "1B",
      "title": "blah 1B"
    }
  ],
  "Test 2": [
    {
      "id": "2A",
      "title": "blah 2A"
    }
  ]
}
```

It's not really a show-stopper, just an annoyance.  Any idea why having a space next the parenthesis would cause the error?

**Comment by Narretz** [comment]
1.2.15 is a very old version of Angular and 1.2.x only receives criticial bug fixes. You should at least use 1.2.29 or upgrade to 1.5.x. The bug sounds vaguely familiar and I think it has been fixed in newer releases.

**Comment by LeftPinkie** [comment]
Thanks for the follow-up. It's annoying more than a bug. I am new to Angular & just took over a biz critical site with no dev/test environment so I am a little hesitant to upgrade anything at this time.

**Comment by Narretz** [comment]
Ok I see. The reason is that the content of ngRepeat is  parsed separately from other expressions. So the regex is simply a bit too strict in this case.

**Comment by Narretz** [comment]
This works at least since 1.3.19: http://plnkr.co/edit/k5IE189fWGt2h0j0Zsn2?p=preview
So if you don't have to support IE8, you should consider upgrading from 1.2.x.
