### ISSUE TITLE
UI issue in chrome 50.0.2661.75 m, in which only showing header, rest page is blank.here is my theame link http://flatfull.com/themes/materil/angular/#/app/dashboard

### ISSUE THREAD

**Issue by ils-ankushh** [angular/angular.js#14484]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
It's difficult to say what your issue is. It reads like you have a problem with angular material which has a separate repo: https://github.com/angular/material. You should also provide more info for your problem, such as version of material & angular used.
