### ISSUE TITLE
$resource (Response for preflight is invalid (redirect))

### ISSUE THREAD

**Issue by ChrisFuck** [angular/angular.js#14491]
I use angular version 1.4.7

when I used $resource to get a REST API which design by myself,and it said Response for preflight is invalid (redirect) error code 302.
I made some change in the app.js config function:
$httpProvider.defaults.headers.post = {};
and try to use sed $resource to get a API and it is success.

But when I set the headers in $resource,it said  Response for preflight is invalid (redirect) error code 302  again.

I want to ask how to solve this CORS problem

**Comment by Narretz** [comment]
CORS problems are almost always caused by the server. Please see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS for info on that. Especially in your case, as the browser reports your server response is invalid.
