### ISSUE TITLE
data rendered datatable ,but still occur "No data available in table"

### ISSUE THREAD

**Issue by heitaoq** [angular/angular.js#14492]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?*

**What is the current behavior?**
After data render the datatable ,but "NO data available in table " still appear in the last line of the datatable. If I directly put the data on the js code ,not get the data from the background,then the datatable display right.
It looks like the data render slower than the datatable from 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
There is not datatable directive in angular core. You should open an issue with the appropriate project. What's the name of the directive you are using?

**Comment by heitaoq** [comment]
@Narretz I don't use directive in the table,  is it need ?

**Comment by Narretz** [comment]
Like I said, you are using a directive that comes from a 3rd party module, so I can't help you with this.
