### ISSUE TITLE
animation on wrong element in ng-repeat  removed item

### ISSUE THREAD

**Issue by arbixy** [angular/angular.js#14501]
When items in `ng-repeat` are tracked by index and animation is used on `ng-leave` the item is removed and then a wrong item is duplicated and the animation is applied on that duplication.

Here's a fresh [example](https://jsfiddle.net/8bhyv1b4/)
This issue seems to be relatively old: [stackoverflow](http://stackoverflow.com/questions/18432584/ng-animate-animate-wrong-item-when-using-track-by-index-in-ng-repeat)

If one is using images and wants images with same sources to be included in the ng-repeat directive then `track by $index` is necessary.
Here's another thought on the matter as consequence to the behavior. 
Imagine there is watcher in directive that keeps track of the ng-repeated items and actualities a css `width` removing item and animation may cause wrong behavior in that case.

**Comment by Narretz** [comment]
This is unfortunate, but this seems like an expected side effect of track by $index and I'm not sure if it is fixable.

If you have duplicate items, you could add a unique identifier to them before you repeat over them (or use a track by function that does this).

**Comment by Narretz** [comment]
This is an expected side effect of track by index.
