### ISSUE TITLE
ng-animate addClass, classNameFilter and svg element does not work together

### ISSUE THREAD

**Issue by artaommahe** [angular/angular.js#14508]
Plunk - http://plnkr.co/edit/Wk0yHL
Element rotates on button click via adding 'fsp-refresh-icon--rotated' and on animation end this class must be removed. If you uncomment
```js
$animateProvider.classNameFilter(/use-animate/);
```
then animation will not work - $animate.addClass() promises resolves instantly after start.
With `div` element everything works well(`.styled` commented out div in template near svg, uncomment it and comment out svg)

**Comment by Narretz** [comment]
I don't see the problem. The classNameFilter defines a regex that is matched against an element's class. If there's a match, the element is animated, if not, it's not animated. So in your example you have to give your element the class `use-animate` and it'll work.

**Comment by artaommahe** [comment]
@Narretz in my example there *is* class for svg element and animation does not work.
```html
<svg id="fsp_refresh_icon" class="use-animate" ...
```

**Comment by Narretz** [comment]
You must have posted the wrong plnkr. There's no svg element in the one you posted.

**Comment by artaommahe** [comment]
@Narretz my bad, here is right one http://plnkr.co/edit/Wk0yHL

**Comment by artaommahe** [comment]
@Narretz do u review fixed link and this bug? (previous issue with another bug was lost after being closed despite my comments after this...)

**Comment by Narretz** [comment]
I'll check it tomorrow

**Comment by artaommahe** [comment]
thx
