### ISSUE TITLE
Form object properties are not deleted

### ISSUE THREAD

**Issue by Tobbe** [angular/angular.js#14510]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Angular leaves `undefined` object properties that should have been deleted

Demo: http://jsfiddle.net/Tobbe/8eohL2nq/2/

First press one of the "RemoveChild" buttons, then press "Trigger Error". Watch the output in your browser's console.

**What is the expected behavior?**

Seeing as Angular automatically adds the entire object property (i.e. `vm.forms.formId0` and `vm.forms.formId1` in the demo above) when the corresponding form is dynamically created, it should be completely removed (`delete`ed) when the form is dynamically removed.

**What is the motivation / use case for changing the behavior?**

Looping over the object with the generated forms should not cause JS errors. ("TypeError: Cannot read property '$valid' of undefined" in this case)

**Which versions of Angular, and which browser / OS are affected by this issue?**

Angular 1.4.6
Chrome Version 49.0.2623.112 m
Windows 7 Pro SP1

Also confirmed on latest snapshot (AngularJS v1.5.6-build.4771+sha.c95a3d8)

Have not tried with earlier version of Angular

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

No

**Comment by gkalpak** [comment]
The `name` attribute of a form dirrective is evaluated as an Angular expression.
Deleting a property should be done through the parser and it is not supported atm (and don't think it will be).

(Of course, you can always check before accessing a value or manually delete the keys when removing a form.)

**Comment by Tobbe** [comment]
Thanks for the reply.

Checking before accessing is what I do right now :) Not sure how I would go about manually deleting the keys though since in my real implementation the array I loop over to generate the forms and the object I use to store the form references in are two totally separate parts of my application (one is part of the model, and the other is part of the view/controller). Since it's angular itself that removes the form because of the data-binding to the model object I'm not sure where to hook in my code that would `delete` the property.

**Comment by gkalpak** [comment]
Not able to make any concrete suggestion without the actual code, but `$index` seems to be the "greatest common divisor". You should be able to use that.

**Comment by Tobbe** [comment]
Alright :+1: Don't worry about it :) Checking with `angular.isDefined` before accessing is good enough then!
