### ISSUE TITLE
Cannot use regular expression literal with $parse

### ISSUE THREAD

**Issue by pabloes** [angular/angular.js#14515]
**Do you want to request a *feature* or report a *bug*?**
Not sure

**What is the current behavior?**
When I use $parse like the following:
`$parse('name.replace(/o/,\'ou\')')({name:'Pablo'});`

I receive an error:
Syntax Error: Token '/' not a primary expression at column 14 of the expression [name.replace(/o/g,'ou')] starting at [/o/g,'ou].

**What is the expected behavior?**
the result would be: 'Pablou'

**What is the motivation / use case for changing the behavior?**
I want to pass a literal regular expression to String prototype functions which accepts RegExp as parameter. As well as is supported other javascript literals.
For example, with a literal string, it works:
`$parse('name.replace('o',\'ou\')')({name:'Pablo'});`

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot.***
Tested in 1.4.9 and 1.5.5

**Comment by gkalpak** [comment]
This is indeed a feature request. Currently, `$parse` does not support literal RegExps.
/cc @lgalfaso (on insights why we might want or not want to add this)

**Comment by pabloes** [comment]
Thanks for the answer.

I see that in the documentation:

> No RegExp Creation With Literal Notation: You cannot create regular expressions in an Angular expression.

We work with a "dynamic form engine" based on AngularJS where users can save "form JSON definitions", it would provide more flexibility on the expressions the users can write.

**Comment by lgalfaso** [comment]
Hi, I really do not like the idea of adding support for regular
expressions. That said, if there is a great use case behind it, then that
can change my mind. Note: allowing users to write their own expressions is
not one of these cases, and in fact is a security issue as $parse is not a
security sandbox.

**Comment by Narretz** [comment]
Closing due to lack of response / the probability that this would be used to let users write their own expressions.
