### ISSUE TITLE
Support ng-minlength and ng-maxlength validations on load for multiple select directives

### ISSUE THREAD

**Issue by dambrosiomike** [angular/angular.js#14521]
Validations for ng-minlength on a multiple select directive aren't run until an item is selected. 

https://plnkr.co/edit/53B1No519yZ1Zhyeo8FM?p=preview

In the above example, there is a multiple select directive with a minimum number of options set to 2. However, if you inspect the element classes, it contains "ng-valid-minlength". Only after selecting one item does it change to "ng-invalid-minlength". 

The select element in the above plunk should have the "ng-invalid-minlength" class when running the plunk. 

This was tested against angular 1.5.5 and the 1.4.x branch. 

The root cause of this bug is because the validation for ng-minlength and ng-maxlength first checks for $isEmpty and if it returns true, assumes that minlength and maxlength are valid. I'm guessing this is to get around cases where the model value may be null or undefined and avoid calling "value.length" on something that does not have a length property. 

I'm happy to submit a PR, but I'd first like to confirm why "empty" values are assumed to be valid. Thanks!

**Comment by Narretz** [comment]
The validators assume that there's actually input in the control, so empty controls are usually always valid. If they are required, they are invalid while empty.
I also don't think it makes a lot of sense that select can have minlength / maxlength validation, because the options are not controlled by the user, but by the developer. Angular validations follow the HTML5 validation, and there's not min/maxlength for select elements.
I'd say min/maxlength for select is not supported.

**Comment by dambrosiomike** [comment]
Thank you for your reply. 

> The validators assume that there's actually input in the control, so empty controls are usually always valid. 

I tried updating my example to use a text input with a minlength of 5 and it exhibited the same behavior as the select. Meaning, the input was initially set to have the "valid-minlength" class but only updated to have the correct state after the user types something in the field. Is this expected? 

> Angular validations follow the HTML5 validation, and there's not min/maxlength for select elements.

This is true, but there is min and maxlength validations for input elements and they seem to share the same behavior as selects. Maybe this issue can be re-worded to scope it to just inputs? 

Obviously there are several workarounds for our specific issue, but I wanted to gain some understanding as to why empty values are valid for all validations except for "required". If this is just part of the spec for validations, then I can close the issue. Thanks!

**Comment by Narretz** [comment]
Oh, I see. I think in this point Angular is following HTML5 validation pretty strictly: http://plnkr.co/edit/sYbiY6mUHyfVOebZjDPm?p=preview (only Chrome supports a message for minlength). When the input is rendered (empty), the validityState for tooShort is false (= valid). Only when you enter and submit something, it becomes invalid.
I think this can be expected, as the application should not set errors before the user has made a change to the input.
