### ISSUE TITLE
How do we use tabs in angular 1.5 using ngRouter and component model? Seems it is not working.

### ISSUE THREAD

**Issue by pradeep-mehta** [angular/angular.js#14523]
I have a tab page on which I created tabs like this-
  $scope.tabs = [
        {
            name: 'Details',
            url: 'app/tenant/detail/details.html',
            active: true
        }, {
            name: 'Application',          
            url: 'app/tenant/detail/application.html',                     
            active: false
        }

This is how I am using ngRouting here
 $routeProvider
            .when('/login', {
                template: "<login title='Shield Portal :: Login'></login>"
            })
              .when('/tenants', {
                  template: "<shell mode='tenant' title='Shield Portal :: Tenant'></shell>"
              })
             .when('/tenants/details', {
                 template: "<shell mode='details' title='Shield Portal :: Tenant'></shell>"
             })
How can I give url in tabs? This way is not working altogether and when I specify a url like '#/tenat/application' then it loads whole page including header inside the tab with only first tab selected, I can not go to second one. The concern in above approach that how a html page will know that which JS it need to load for instance if i am loading application.html.

**Comment by pkozlowski-opensource** [comment]
Please use a right channel for support questions, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
