### ISSUE TITLE
Add Angular2 github/website links to ReadMe

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular.js#14524]
Maybe it'd be a good idea to add a link to Angular2 Github/website just incase someone is new to Angular entirely, and gets here by mistake, but they're looking for the newer version?

Just throwing the idea out there...

**Comment by gkalpak** [comment]
@MarkPieszak, doesn't sound like a bad idea. Could you submit a PR ?

**Comment by MarkPieszak** [comment]
Will do!
