### ISSUE TITLE
Ng-switch commentary has unnecessary white space

### ISSUE THREAD

**Issue by d0g** [angular/angular.js#14549]
When creating ng-switch-when end commentary, because no comment is passed an unnecessary white space is generated.

Before: 
```html
<!-- end ngSwitchWhen: -->
```

Now:
```html
<!-- end ngSwitchWhen:  -->
```

To prevent that we could do something like this:
```javascript
compile.$$createComment = function(directiveName, comment) {
      var content = '';

      if (debugInfoEnabled) {
        content = ' ';
        content += (directiveName || '');
        content += ':';
        content += comment ? ' ' + comment : '';
        content += ' ';
      }

      return window.document.createComment(content);
    };
```

**Comment by arashkbanan** [comment]
ایول

**Comment by Narretz** [comment]
Thanks for the report. This looks pretty inconsequential, but we might incorporate this change if your open a PR with this.

**Comment by Narretz** [comment]
Anyway, does this cause you any problems in your app?

**Comment by d0g** [comment]
Yep, this broke some unit tests because we've tested the html output. I will open a PR then, thanks.

**Comment by d0g** [comment]
But as you said, this is inconsequential with no big impact.

**Comment by Narretz** [comment]
I'm curious, why would you test the output of ngSwitch in a unit test? Shouldn't you test for presence / absence of non-comment nodes?

**Comment by d0g** [comment]
Summing this up:
- Very old tests where we define our directive scope, compile it and checked the html output
- This is on our backlog team to refactor but, unfortunately, It's not a priority.

**Comment by d0g** [comment]
Also, this HTML validation shouldn't be done in unit test IMO, automated tests exists for something.
