### ISSUE TITLE
ngResource does not replace parameters in the host

### ISSUE THREAD

**Issue by bluesliverx** [angular/angular.js#14542]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
When you use a parameter (i.e. :domain) in the hostname, it is not replaced correctly.  Instead, it is kept as the parameter name with the colon intact.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Here is the broken plunkr using 1.4.5: http://plnkr.co/edit/9m0b2er2P6Gb3Jx9Bppo?p=preview
Here is the working version using 1.4.3: http://plnkr.co/edit/RsI3TgKwcjGEXcTMKoQR?p=preview

**What is the expected behavior?**
It should replace any parameters in the domain, ignoring IPv6 hosts and ports correctly.

**What is the motivation / use case for changing the behavior?**
This behavior was standard in ngResource 1.4.3.  As of 1.4.5, it changed in order to support IPv6 URLs (see #12512).  The fix implemented in that issue was too aggressive and effectively ignores hostnames/domains from parameter replacement.

I make use of this behavior heavily in order to support a multi-tenanted application where the the sub-domain decides the tenant.  I am not the only one either: http://stackoverflow.com/questions/32463584/passing-domain-name-as-parameter-with-resource-in-angularjs#

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.4.5 is where the issue first appeared (I didn't see a 1.4.4 of ngResource), and 1.4.3 worked correctly as described above.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I think if we can simply add a regex to catch IPv6 addresses and for all other cases keep the previous behavior, including the same handling of port numbers (if the param contains only numbers, ignore it). I'm not sure of IPv6 syntax, but in the examples given in the linked issue, something as simple as looking for square brackets around the hostname may catch it.

**Comment by Narretz** [comment]
I'm not sure replacing the host was ever officially supported. At least there are no mentions for this in the docs. Of course you are welcome to open a PR with the proposed changes and we can see if it makes sense.

I also can't see a difference between the plnkrs you posted. Both throw an exception for me. As a general guideline, you should also reduce your demos so that only the relevant parts remain (I see ui-view and factory abstractions which seem unrelated).

**Comment by petebacondarwin** [comment]
Looks like a regression. Let's fix this. Do you want to take a look @Narretz if @lgalfaso doesn't see to it first?
