### ISSUE TITLE
Set expiration date for JS files

### ISSUE THREAD

**Issue by s1mone** [angular/angular.js#14554]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by s1mone** [comment]
This is not a support question. The Google Page Speed Insights is warning
about the expiration date on files hosted in code.angularjs.org

   - https://code.angularjs.org/1.2.29/angular-route.min.js (expiration not
   specified)
   - https://code.angularjs.org/1.2.29/angular-sanitize.min.js (expiration
   not specified)


. .. . .. . .. . .. . .. . .. .
simone villas boas


2016-05-04 5:37 GMT-03:00 Martin Staffa <notifications@github.com>:

**Comment by Narretz** [comment]
Hi,
in that case please open a new issue in the angularjs.org repo with a real issue description. Your initial post was completely devoid of information
