### ISSUE TITLE
Component Router NPM Package Does Not Include Angular1 Folder 

### ISSUE THREAD

**Issue by mickeyvip** [angular/angular.js#14564]
The documentation on Component Router for Angular 1.5.x has the following installation instructions:

```
npm init
npm install angular@1.5.x --save
npm install @angular/router --save
```

The version of the Router that is installed with the last command is `2.0.0-rc.1` and does not include `Angular1` folder.

So one cannot use this NPM package with `Angular 1.5.x`.

**Comment by petebacondarwin** [comment]
We need to specify the version explicitly for now

**Comment by Narretz** [comment]
Like this? https://github.com/angular/angular.js/pull/14560

**Comment by mc-suchecki** [comment]
Will the Angular 1 version of the Component Router be included in later releases? Or is support for Angular 1.5 dropped?
