### ISSUE TITLE
not working on opera mini

### ISSUE THREAD

**Issue by pradeeptrends** [angular/angular.js#14563]
I create a simple page with list bind with API call
its working with all mobile browsers but not in opera mini

$http({  method: 'GET',  url: APIRequest.getListData(), timeout:6000})
              .success(function(response) { 
                //code
}).error(function(){    
                //code            
              });

**Comment by Narretz** [comment]
We don't officially support Opera Mini, so this is expected behavior.
Since I'm curious, what's the error message for the app? ( stacktrace)
