### ISSUE TITLE
Anjular js application performance issues 

### ISSUE THREAD

**Issue by arjuncfe** [angular/angular.js#14561]
Hi ,, All

I am new in angularjs . I have more js ( 50 custom Controller , 25 custom services,  70 custom filter,directive , 1 app and some design js like bootstrap and more js ) these all js import on index.html js 
So my app take lot of time in first  page load how i can make my app fast please inform me

**Comment by CihanAksoy** [comment]
Gulp + Uglify ?

**Comment by Narretz** [comment]
- concatenate and minify your js and css files (application code)
- use a CDN for library files
- put remote angular templates (directives with templateUrl) into the templateCache when you build your application

Anyway, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
