### ISSUE TITLE
Handler for unhandled rejections

### ISSUE THREAD

**Issue by marlun78** [angular/angular.js#14569]
It would be great to have something like `$unhandledRejection`. Much like the [$exceptionHandler](https://docs.angularjs.org/api/ng/service/$exceptionHandler) for unhanded rejections. There is already the `window.onunhandledrejection` event for native Promises.

For more info on the `unhandledrejection` see [promise-rejection-events](https://googlechrome.github.io/samples/promise-rejection-events/) or 
[onunhandledrejection on MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection).

What do you think?

**Comment by lgalfaso** [comment]
Have you seen #13662 ?

**Comment by marlun78** [comment]
No I hadn’t, so this will be out with 1.6, right?

**Comment by lgalfaso** [comment]
yep

**Comment by marlun78** [comment]
Great! Thanks @lgalfaso!
