### ISSUE TITLE
Unable to get component $onChanges method to fire...

### ISSUE THREAD

**Issue by mikeerickson** [angular/angular.js#14572]
I am unable to get $onChanges to fire regardless what I try. To further complicate matters, the documentation is VERY vague and there are basically NO examples, etc. online (I am trying to get it working with ES6 modules).

If anybody has a working example (with ES6) which you wish to share, I would be greatly appreciative.

Thanks in advance...

**Comment by Narretz** [comment]
Your issue is unfortunately also very vague. On thing to keep in mind is that $onChanges only fires if the bound object is replaced (its identity changes). So array item changes or property changes will not fire it.

**Comment by Narretz** [comment]
Tools like https://plnkr.co support ES6 syntax, so you can create minimal example that shows what you are trying to do.

**Comment by Alber70g** [comment]
I've got this problem also, but as you say, only property changes aren't fired. Why is this? What would be the right way to solve this?

**Comment by Narretz** [comment]
I can't say how to solve this if I can't look at a non working demo. Can
you put something on plnkr.co? May crystal ball is in repair currently.
Am 09.05.2016 17:10 schrieb "Albert Groothedde" <notifications@github.com>:

**Comment by Alber70g** [comment]
I'm sorry. My solution is to use `angular.copy()` to deep clone the object and set it so the trigger get's fired. I'll put up a plnkr tomorrow morning.

Thank you!

**Comment by Narretz** [comment]
I assume this basically works as expected. We probably should make this clearer in the docs, though.

**Comment by mikeerickson** [comment]
@Narretz OK, I have come back to this (time to figure it out) and have created a fiddle as per your request.   

In short, when clicking `Update Name` you will see the change from Erickson to Smith.  However, this click action does NOT fire the `$onChanges` lifecycle hook (which I feel it should).  Further, entering a value in the input field, I feel this too should trigger the same hook

https://jsfiddle.net/codedungeon/n1fsgnu7/1/

**Comment by gkalpak** [comment]
@mikeerickson, this is working as expected. The `$onChanges` hook is fired when the external value/input (bound to a component controller property) changes, not when the property value changes from inside the controller.

**Comment by thayumaanavan** [comment]
@Narretz  Did you find how to handle this scenario? I'm also looking for similar functionality.
