### ISSUE TITLE
Angular $response GET request removes content type

### ISSUE THREAD

**Issue by madhairsilence** [angular/angular.js#14578]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Angular $response GET request removes content type

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
- Create a resource and perform a GET operation. The **Content-Type**  attribute from the headers vanishes 
- Add an interceptor to force insert the **Content-Type** in to the GET request. Still the Content-Type does not get passed.

**What is the expected behavior?**
GET request should support adding custom behavior. Surprising **$http** works , but **$resource** duly removes the **Content-Type**

**What is the motivation / use case for changing the behavior?**
Its would be impossible to use **$resource** if you are calling a API which demands a set of Headers

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
**1.5.5**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Do you mean it removes it from the request or from the response?

**Comment by gkalpak** [comment]
I don't think it removes any header values. Are you sure this is not CORS-related or something ?

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
