### ISSUE TITLE
Feature: Make asterisk syntax sugar more logical for structural directives

### ISSUE THREAD

**Issue by mavericken** [angular/angular.js#14573]
Basically, I feel that the asterisk syntax sugar implementation is the logical inverse of ideal syntax.

I was reading about it here: https://angular.io/docs/ts/latest/guide/structural-directives.html
I stumbled upon this bit right here:

```
<!-- Examples (A) and (B) are the same -->

<!-- (A) *ngFor div -->
<div *ngFor="let hero of heroes">{{ hero }}</div>

<!-- (B) ngFor with template -->
<template ngFor let-hero [ngForOf]="heroes">
  <div>{{ hero }}</div>
</template>
```

Example (A) is supposed to be more convenient than Example (B)...  and it is.
However, why not make the more convenient version even more convenient, and reverse the asterisk usage?

My reverso world example:
```
<!-- Examples (A) and (B) are the same -->

<!-- (A) ngFor div -->
<div ngFor="let hero of heroes">{{ hero }}</div>

<!-- (B) *ngFor with template -->
<template *ngFor let-hero [ngForOf]="heroes">
  <div>{{ hero }}</div>
</template>
```
You kinda have to look carefully to notice the difference.  I took the asterisk from (A) and put it on (B).

Let fancy things be fancy, and let simple things be simple.

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular2. Please open an issue here: https://github.com/angular/angular/issues

**Comment by mavericken** [comment]
Ah, I see.  Thank you.  I have reentered there:
https://github.com/angular/angular/issues/8540
