### ISSUE TITLE
RC1 too many javascript files to load!

### ISSUE THREAD

**Issue by adamwuyu** [angular/angular.js#14584]
Hi, we've prepared ourselves for angular2 a while, and decided to use the RC1 version for our new projects. But RC1 is loading hundreds of javascript files. Is this a feature mean to be? Or it will be solved soon? About when? 

Thank you for your attention.

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular2. Please open an issue here: https://github.com/angular/angular/issues
