### ISSUE TITLE
feature: promise unwrapping filter

### ISSUE THREAD

**Issue by bughit** [angular/angular.js#14591]
since automatic promise unwrapping was removed, why not add a filter

something like:
```js
    .filter('promise', ['$q', function($q) {
        
      return function(promiseOrValue) {
        if (promiseOrValue instanceof $q)
          if (promiseOrValue.$$state.status === 1)
            return promiseOrValue.$$state.value;
          else
            return undefined;
        else
          return promiseOrValue;
      };
      
    }]);
```

```html
<div>{{data | promise}}</div>
```

**Comment by lgalfaso** [comment]
The property `$$state` is private and no code should rely on it

**Comment by bughit** [comment]
> The property $$state is private and no code should rely on it

1. this is proposed as an angular feature, is angular code not allowed to use $$state?
2. you only objected to a possible implementation, what about the feature itself?

**Comment by lgalfaso** [comment]
> this is proposed as an angular feature, is angular code not allowed to use $$state?

If possible, then it should not.

> you only objected to a possible implementation, what about the feature itself?

I object for this to be part of the core. It is possible to implement this as part of a third party module as follows

```js
// Warning, untested code.

[...].filter('promise', ['$q', function($q) {
  var wm = new WeakMap();
  return function(promiseOrValue) {
    if (promiseOrValue instanceof $q) {
      if (wm.has(promiseOrValue)) {
        return wm.get(promiseOrValue);
      } else {
        wm.set(promiseOrValue);
        promiseOrValue.then(function(value) { wm.set(value); });
      }
    } else {
      return promiseOrValue;
    }
  };
}]);
```

It should be also possible to implement this without a `WeakMap` by using the current scope to keep the promises.

**Comment by bughit** [comment]
> I object for this to be part of the core

I am curious as to why?  It seems like manually unwrapping promises is something that everyone is frequently doing.  Why not extract that into a simple reusable core feature?
