### ISSUE TITLE
bug or docs issue: filters are always invoked for object inputs (regardless of identity or value equality)

### ISSUE THREAD

**Issue by bughit** [angular/angular.js#14590]
https://plnkr.co/edit/d0J4zqlTZvrsSJvywM0y?p=preview

for primitive inputs, the filter is invoked only if the value changes

docs:
> The filter function should be a pure function, which means that it should be stateless and idempotent. Angular relies on these properties and executes the filter only when the inputs to the function change.

so is the behavior for objects a feature or a bug?

**Comment by Narretz** [comment]
This is expected behavior, as it's too expensive to keep a copy of an object around to determine if the object changed, see https://github.com/angular/angular.js/blob/eebbca0a8bdc47e0d4f4d59d6981b912d6605ccc/src/ng/parse.js#L1991-L2004

Do you want to submit a PR that updates the docs about this?
