### ISSUE TITLE
Directive with Controller an ControllerAs vs Directive with ng-controller vs Component

### ISSUE THREAD

**Issue by SamanthaAdrichem** [angular/angular.js#14609]
**What is the current behavior?**
Currently when i use a directive inside a component with ng-controller="Controller as $ctrl", the $ctrl is aliased safely and all $ctrl vars are unique.
Currently when i use a component inside a component, the $ctrl is aliased safely and all $ctrl vars are unique
However if i use a directive in a component using "controller:" and "controllerAs". the components $ctrl variable is overwritten by the directive's $ctrl variable

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

https://embed.plnkr.co/jmskhdNLXIN8xfdq5S2h/

**What is the expected behavior?**
The controller and controllerAs alias should behave the same as the ng-controller="name as alias"

**What is the motivation / use case for changing the behavior?**
It's a bug, and if you ask me the controller and controllerAs notation is better than the ng-controller notation in a template

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.5

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
no, sorry

**Comment by gkalpak** [comment]
This "overwriting" happens because your directives have no scope of their own, so they are "poluting" the parent scope.
If you use isolate scopes, the issue goes away.

Closing as it works as expected.

[Updated plnkr][1]

[1]: https://plnkr.co/edit/sCYYwW3tHNFfijAZ8W1W?p=preview

**Comment by gkalpak** [comment]
BTW, in case it isn't clear: `ngController` creates a new scope, that's why it isn't poluting the parent scope with it's alias. Your directives would work with `scope: true` (instead of isolate scope) as well, but most of the time isolate scopes are more appropriate.

**Comment by SamanthaAdrichem** [comment]
I completely understand. Due to using the controller as syntax, i completely stopped using scope when i didn't share variables. Silly me!
