### ISSUE TITLE
Allow for ngAria to ignore specific elements

### ISSUE THREAD

**Issue by psaniko** [angular/angular.js#14602]
It would be great if there was a flag/directive to apply to elements to exclude them from being altered by ngAria. 

**What is the current behavior?**
We include a non-native element with ng-model (angular-ui/ui-select) which gets a tabindex="0" automatically added by ngAria. Since the actual input is encapsulated within the ng-model div, you'd have to tab twice to get to the element.

**Comment by Narretz** [comment]
Can't you set the tabindex on the element yourself?

**Comment by gkalpak** [comment]
Indeed, if it's only about the `tabindex`, you can manually set it. `ngAria` can do a lot more stuff (such as adding `aria-invalid`, `aria-required`, `role` etc), so if there is a strong usecase, we mght consider having a flag attribute to disable `ngAria` on a specific element.

You could of cource do it yourself :) [Demo pen][1]

[1]: http://codepen.io/ExpertSystem/pen/GZLMVL?editors=0010

**Comment by psaniko** [comment]
As it is an external plugin we would have to fork it or force a negative tabindex via DOM manipulation. Thanks for your codepen @gkalpak! We'll try that out once the ticket is due for completion :)

**Comment by gkalpak** [comment]
Loosely related to #14672.

**Comment by stowball** [comment]
I 100% agree with needing the ability to able to exclude specific elements from being enhanced by ngAria.

I have recently built a complex, bar chart type layout, which has a `<button>` for the axis label for accessibility, but the whole "row" of the bar chart needs to be mouse clickable. So currently, I have a fake `[role="button"]` wrapping a real `<button>`, which is bad for accessibility as raised by @marcysutton  in https://github.com/angular/angular.js/issues/14672.
