### ISSUE TITLE
[BUG] ng-repeat filter true

### ISSUE THREAD

**Issue by exejutable** [angular/angular.js#14601]
**What is the current behavior?**

On ng-repeat  filter: model : true (strict) If i do a filter in the array and then cleaned the input, it does not return to normal state (not filtered)

**Angular version**
1.4.9

**Link to reproduce the bug**

http://plnkr.co/edit/my0ilXPu7aTUIiKxOI4n?p=preview

**Steps**

- Filter in the input (the array filter correctly)
- Clean the input (the array does not return to the previus state (not filtered)

**What is the expected behavior?**

I suppose the expected behavior is return the ng-repeat array complete (not filtered).

**Comment by gkalpak** [comment]
This is expected behavior. It happens because initially the expression is undefined, but when you clear the field it is an empty string (and `undefined !== ''`).
See #12060 for more context and possible work-arounds.
