### ISSUE TITLE
ngLocale with wrong FIRSTDAYOFWEEK in german (DE)

### ISSUE THREAD

**Issue by devimplode** [angular/angular.js#14615]
Currently the locale file for german (de-*) set ``"FIRSTDAYOFWEEK": 0``.
The correct value should be ``1`` for Monday.
It seems it is correct in CLDR.

**Comment by lgalfaso** [comment]
`ngLocale` follows ISO-8601 that the week days are specified Monday-Sunday. This is, Monday is 0 and Sunday is 6. It is unfortunate that this does not match `Date::getDay()`, but changing this would be too big of a breaking change.
