### ISSUE TITLE
What is the message format for a feature being removed?

### ISSUE THREAD

**Issue by gajus** [angular/angular.js#14619]
Regarding https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

I understand that the commit message footer must have the `BREAKING CHANGE` message. But what type ought to be used to indicate that a feature is being removed?, feat?

**Comment by gkalpak** [comment]
Generally, we don't remove features, unless

1. It is necessary to fix something else (e.g. a regression or a long-standing bug).  
    Type: **fix**, **perf**
2. It replaced/superceded by another feature.
    Type: **feat**
3. It has been deprecated for a while and we decided to remove it.
    Type: Not sure - we hardly ever do this

<sub>I'm going to close the issue, as it not really actionable.</sub>
