### ISSUE TITLE
component method called with undefined for name argument should throw error

### ISSUE THREAD

**Issue by rekna1** [angular/angular.js#14614]
When you register a component with an angular module, and the component name argument happens to be undefined, no error is thrown... 

It would be better if angular checks the argument to be a valid name

**Comment by gkalpak** [comment]
We are typically not doing such validations. I've seen some workflows, where people put the directive/component/service name as a static property on a class or constructor function and use that when registering.

Still, if we do it for one thing (e.g. components), then we should do it for everything (e.g. directives, services, filters, decorators, controllers etc), but I don't think it is worth the overhead tbh.
