### ISSUE TITLE
How to write $canActivate component hook in typescript

### ISSUE THREAD

**Issue by csfanse** [angular/angular.js#14616]
I am using Angular 1.5.5 with typescript.How Can I write canActivate hook for my component?
I can write other hooks but don't know about canActivate hook.

Below is my code.

     class workspaceOptions implements ng.IComponentOptions {
        public controller: any;
        public templateUrl: string;
        public bindings: any;
        public $routeConfig: any;
              
        $canActivate() {
            console.log('check can active');
        }
        constructor() {
            this.bindings = {
                $router: '<'
            };
            this.templateUrl ='app/workspace/workspace.html' ;
            this.controller = workspaceCtrl;
            this.$routeConfig = [
                { path: '/calmenu/...', name: 'Calmenu', component: 'calmenu', useAsDefault: true }
            ];
        }
    }

**Current Behavior**
$canActivate() is not getting called.

**Expected Behavior**
Call $canActivate(), inject service and set routing dynamically based on service data.

**Comment by gkalpak** [comment]
It depends on how you are registering your directive/component.
`$canActivate` should be a property of the DDO/CDO.

Here is an [example][1] using plain JS.

--
That said, this sounds more like a general support question, so please use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://plnkr.co/edit/l00ZibquTd1U7hxmB0VA?p=preview
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
