### ISSUE TITLE
Extract translations from ngMessageFormat

### ISSUE THREAD

**Issue by peeter-tomberg** [angular/angular.js#14623]
I couldn't find any documentation or any scripts in this repository that enable me to extract translations from my code. 

Is there a script in the works?

**Comment by Narretz** [comment]
There's nothing in the works, unfortunately. There's currently no one working on ngMessageFormat atm from the core team. Your use case definitely sounds useful, but also like something that would be a good candidate for a 3rd party module.

**Comment by Narretz** [comment]
I'll close this as "not core". Our focus is on other parts of the core atm.
