### ISSUE TITLE
assigning an array to variable is not working in angularjs-1.5.5

### ISSUE THREAD

**Issue by sanathjs** [angular/angular.js#14636]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

if you run the plunkr given below u can see we have assigned array to a function and looping using ng-repeat which is currectly working since we have added angular version 1.0.3 but if you replace it with angular version 1.5.5 its not working as earlier

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

http://plnkr.co/edit/j5kNLY4Xr43CzcjM1gkj?p=preview

**What is the expected behavior?**

it should work same when we use angular-1.0.3 and 1.5.5

**What is the motivation / use case for changing the behavior?**

behavior should be same for all versions

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

angular-1.0.3 and 1.5.5

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
You can see that this logs the ngRepeat:dupes error in the console. You can read more about this here https://docs.angularjs.org/error/ngRepeat/dupes and here https://docs.angularjs.org/api/ng/directive/ngRepeat#tracking-and-duplicates
This is expected behavior.

**Comment by gkalpak** [comment]
BTW, this has been like this since `v1.1.5` (although I couldn't find a Breaking Change notice in the docs :stuck_out_tongue: ).
You can restore the previous behavior by tracking by `$index` ([updated plnkr][1]). 

[1]: http://plnkr.co/edit/8v4KCnOCXb1DXD4XM0BQ?p=preview

**Comment by Narretz** [comment]
It's actually in the 1.1.4 release notes. ;)

**Comment by sanathjs** [comment]
Can you just say how do I loop that text in plunkr for 1000 times

**Comment by sanathjs** [comment]
In angular 1.5.5

**Comment by gkalpak** [comment]
@sanathjs, either create an array with 1000 (different) items - e.g. numbers 0 - 999 - or tack by `$index`.
(See https://github.com/angular/angular.js/issues/14636#issuecomment-220323143.)

**Comment by sanathjs** [comment]
@gkalpak I looked into the tracking by  $index  (updated plnkr). thanks a ton :)

**Comment by sanathjs** [comment]
i want to load a million images on a page but when trying do that using
ng-repeat its taking huge time to load,is there any best practice to load a
million inages at a time.

**Comment by Narretz** [comment]
@sanathjs 
this github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

That said, Angular isn't made to render a million images at the same time. I think that you'll find this is very hard to do with any framework or even without one,
