### ISSUE TITLE
Unable to focus text input when validation error present and using ng-messages as an element

### ISSUE THREAD

**Issue by RKumsher** [angular/angular.js#14639]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Description**
Using ng-messages as an element (instead of an attribute of a DIV), you cannot focus on a text input if there's a ng-message displayed

**Steps to reproduce**
1. Navigate to http://codepen.io/anon/pen/XdLMeP
2. Clear the contents in the 2nd description text input
3. Click in the 1st description text input
4. "This is required." should appear in red as a validation error on the 2nd description text input
5. Click in the 2nd description text input

**Expected Behavior**: Text input focuses
**Actual Behavior**: Cannot focus on text input

**Which versions of Angular, and which browser / OS are affected by this issue**
**Angular Version**: 1.4.8
**Chrome Version**: 52.0.2741.0
**OS**: OSX 10.11.4

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular Material, since it only happens with Material included. Please open an issue here: https://github.com/angular/material/issues

**Comment by RKumsher** [comment]
Thanks, I created https://github.com/angular/material/issues/8508
