### ISSUE TITLE
ngRoute does not respect the new controller lifecycle hooks ($onInit, etc...)

### ISSUE THREAD

**Issue by AGiorgetti** [angular/angular.js#14630]
I'm not sure if this is supposed to work; but if we define a controller for a route template and we let the ngRoute module loads the template and wire up the controller to it, it does not fire the new lifecycle hooks that can be defined in the controller.

Here's a plunker that shows the problem:
https://plnkr.co/S14Zcalb7W6oHZ16nko3

This scenario is not mentioned in the documentation, so I'm not sure it's supposed to be supported.

A workaround can be: create a custom directive/component for the whole route, let the route template directly use the new component.

**Comment by Narretz** [comment]
The new lifecycle hooks only work in components (and plain directives, as components are directives). So they don't work on ngController or route controllers. Until we have a new router that is special for components, your workaround of using a component in the route template is the way to go.
