### ISSUE TITLE
$scope.$on function is not running

### ISSUE THREAD

**Issue by marie15** [angular/angular.js#14642]
Hi everybody, I'm trying to use $scope.$on and $rootScope.$broadcast in order to use a variable of a controller function in another controller function. I have already use this for other purpose, so my issue is the $scope.$on function isn't executing, I tried to make alert inside it but I didn't get any alert, I don't know what is the problem. Here is a snippet of my code to illustrate the issue. Thankx for advance :)

`app1.controller('autoCompleteCTRL',function($scope,$rootScope,$http) {
$scope.$on("myEvent3", function (event, args) {
      
        alert(1);
        $scope.SearchNearPoint= args.value;
        
        $http({
        method: "get",
        url: "path/to/file.php",
        dataType: 'json',
        params: { 'userText': $scope.searchText},
        async: false
            
        }).success(function(data, status, headers, config) {
        $rootScope.suggestions = data;

        }).error(function(data, status, headers, config) {
                            
        });
      
     }); 
app1.controller('BasicCenterController', function($scope, leafletData,$http) {
     $scope.$root.$broadcast("myEvent3", {
            
            value: startLatLng

        });
});`

**Comment by marie15** [comment]
Is it the problem because I use $scope.$on function before $scope.$root.$broadcast?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by marie15** [comment]
Oki I understood. Thankx
