### ISSUE TITLE
"npm start" is stuck - angularJS getting start tutorial

### ISSUE THREAD

**Issue by Av1shay** [angular/angular.js#14647]
I start the "[PhoneCat Tutorial App](https://docs.angularjs.org/tutorial)" and I have a problem in the step where I need to "Running Development Web Server", After running `npm start`, it stuck on "Starting up http-server, serving ./ on port: 8000", and below there is a line "Hit CTRL-C to stop the server".
I've wait an hour and nothing happen, should I keep waiting? Thanks

**Comment by Narretz** [comment]
That means the server is running and you can open localhost:8000 in your browser to see the tutorial app :)

**Comment by Av1shay** [comment]
Lol, should have open a new command window, what a newbies mistake, thank you!
