### ISSUE TITLE
ngAnimate anchoring is acting weirdly on Safari

### ISSUE THREAD

**Issue by sebastiendan** [angular/angular.js#14650]
Hi,

I tested my first ngAnimate anchoring animation on Safari and saw it behaved differently (weird positioning at the start of the transition).
Then I realised this problem also happens in the demo you provide in the documentation at https://docs.angularjs.org/api/ngAnimate. I'm on Safari 9.1. I couldn't find any compatibility issues in the documentation, should there be any?

**Comment by sebastiendan** [comment]
Sorry, most likely a duplicate of #14643

**Comment by Narretz** [comment]
Ok, let's continue discussion there. Please add any info you have to that issue.
