### ISSUE TITLE
angular-mock: $animate.flush is not a function

### ISSUE THREAD

**Issue by htulipe** [angular/angular.js#14668]
In my Mocha tests run with Karma, I have to flush some animation before making some assertions:
  
    beforeEach(inject(function ($animate, $httpBackend) {
      $httpBackend.flush();
      $animate.flush();
      scope.$digest();
    }));

I get the following error: `$animate.flush is not a function`.  Other mocks work well ($httpBackend for instance).

I searched a bit and saw that the part of the code of angular-mock that defines the $animate service is never executed. I also saw that mocked $animate is the only mock that is [declared as an actual module](https://github.com/angular/angular.js/blob/v1.5.5/src/ngMock/angular-mocks.js#L763) and this module is never required.

I can get my tests working by adding following line [here](https://github.com/angular/angular.js/blob/v1.5.5/src/ngMock/angular-mocks.js#L2935): `modules.unshift('ngAnimateMock');`

Environment info:
Angular: 1.5.5
Mocha: 2.2.1
Karma: 0.13.10

Is this a bug or am I missing something? Thanks in advance

**Comment by htulipe** [comment]
Blaming the source file I found in the [original commit](https://github.com/angular/angular.js/commit/4224cd5182bc93e4a210f75e0a4e4de7f3c544e8) that we can do the following to get it to work:

` beforeEach(module('ngAnimateMock'));`

I still think there a bug there (or at least some doc to be improved). I will happily make a PR for that, let me know.

**Comment by gkalpak** [comment]
Indeed, we should probably document it somewhere, that if you want the mocked version of `$animate` (et al) you need to include the `ngAnimateMock` module (e.g. `beforeEach(module('ngAnimateMock'))`).

PRs welcome :smiley:

**Comment by htulipe** [comment]
Ok will do
