### ISSUE TITLE
the git clone depth should be 15 instead of 14

### ISSUE THREAD

**Issue by mathewthekkekara** [angular/angular.js#14666]
In the toutorial
https://docs.angularjs.org/tutorial/

step "Download install Phonecat"
in my opinion you need to git clone with the depth 15 instead of 14

Because you need the Step-0 in the next Tutorial-step

**Comment by gkalpak** [comment]
The tutorial has been updated yesterday. There are two new steps now, so the instructions have been updated to mention `--depth=16`. Make sure to refresh your page to get the new content (you might need to disable your browser's cache).
