### ISSUE TITLE
scope have a limit !!

### ISSUE THREAD

**Issue by darkmanAmazigh** [angular/angular.js#14689]
hi,

i have 64 input text, with 64 checkbox near evry input, in html page, i have declared and creted a controller, when i print the value of input in console, i get fine the data, but with checkbox it say me that undefined,
My inputs is in an object vehicle ( vehicle.identification.kind, vehicle.speed.size, etc ), but checkbox ng-model name is a simple string.
i can't get the value of my checkboxsin JavaScript side, but in HTML i get correctly the value of my checkboxs
Any idea !!

Than'x

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
