### ISSUE TITLE
Angular $http.jsonp(url) didn't parse all special character at the URL

### ISSUE THREAD

**Issue by anasbenis** [angular/angular.js#14688]
Exemple : 

url = http://exemple/Objects?callback=JSON_CALLBACK&params={"Report Name":"Test*"}

$http.jsonp(url) should parse this url to:
http://exemple/Objects=JSON_CALLBACK&params=%7B"Report Name":"Test*"%7D

But it didn't convert character "{" and "}"
http://exemple/Objects=JSON_CALLBACK&params={"Report Name":"Test*"}

**Comment by gkalpak** [comment]
@anasbenis, could you create a live demo (e.g. using CodePen, Plnkr etc) ?
Have you tried if this happens with "vanilla" XHR as well ?

**Comment by wesleycho** [comment]
This seems like a usage problem to me - this doesn't look like Angular's responsibility.

One should probably be doing
```js
$http.jsonp('http://example/Objects?callback=JSON_CALLBACK', {
  params: {
    params: {
      'Report Name': 'Test*'
    }
  }
})
```

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
@wesleycho 's post looks like a good starting point.
