### ISSUE TITLE
xComponent not working as name

### ISSUE THREAD

**Issue by dietergoetelen** [angular/angular.js#14693]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
_Bug_

**What is the current behavior?**
When you name a component prefixed with `x` it's not working. For instance:

```
module.component('xApp', {
   template: "<h1>x app</h1>"
})

```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://jsbin.com/qunofexoja/edit?html,js,output

**What is the expected behavior?**
The possibility to register components prefixed with `x`

**What is the motivation / use case for changing the behavior?**
Many people giving demos do not always have the inspiration to use decent prefixes. I usually fallback on `x`. If this is intended not to work, please throw atleast an error, it took me a few hours before I understood the `x` was the problem.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

>= 1.5

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
As explained in the [Directives section][1] of the Developer Guide, `x` and `data` prefixes are stripped of.
So, when you use `<x-app />` in your HMTL, Angular will look for an `app` directive. Therefore, it is not recommeneded to use `x` or `data` as a prefix for your directives, but if you must, you should add an extra prefix in the HTML:

```html
<x-x-app />

<!-- OR -->

<data-x-app />
```

--
Closing as it works as expcted.

[1]: https://code.angularjs.org/1.4.10/docs/guide/directive#normalization
