### ISSUE TITLE
Populate $scope.$$isolateBindings for Angular 1.5 components, the same way as it currently behaves for isolate scopes in directives

### ISSUE THREAD

**Issue by azaslavsky** [angular/angular.js#14708]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

On `.component()`s created in Angular 1.5.x, the $$isolateBindings defintion is an empty object, and not reflective of the data supplied to the "bindings" property.

**What is the expected behavior?**

The bindings property should behave as it does for isolate scopes in `.directive()`, and provide the correct set of definitions

**What is the motivation / use case for changing the behavior?**

We bind some handler methods automatically - this would help tremendously in that process.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.5+

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

For example, this works: 
```
.directive('test', ['$scope', function($scope) {
  templateUrl: 'test.html',
  bindings: {
    onStart: '&?',
    onStop: '&?'
  },
  controller: function() {
    console.log($scope.$$isolateBindings); //Returns {onStart: {..}, onStop: {...}}
  }]
]});
```

This fails:
```
.component('test', {
  templateUrl: 'test.html',
  bindings: {
    onStart: '&?',
    onStop: '&?'
  },
  controller: ['$scope', function($scope) {
    console.log($scope.$$isolateBindings); //DOES NOT return {onStart: {..}, onStop: {...}}
  }]
});
```

**Comment by gkalpak** [comment]
This has nothing to do with `.directive` vs `.component` (`.component` uses `.directive` under the hood anyway). The difference is with `bindToController` (it is `true` by default in `.component`) - you will get the same results with `.directive` if using `bindToController: true`.

In any case, `$$isolateBindings` is a private Angular property (being `$$` prefixed) and you shouldn't use t in your code.
