### ISSUE TITLE
Location of cli.js in Protractor 3

### ISSUE THREAD

**Issue by gziebold** [angular/angular.js#14703]
I use Webstorm to run my E2E protractor tests.  For previous versions of Protractor I have a setup similar to what is mentioned here:

http://ng-learn.org/2014/02/Debugging_Protractor_from_WebStorm_Intellij/

I'm on a new project that is using Protractor 3.3 I'm not seeing ../node_modules/protractor/lib/cli.js which I believe I need to populate in 'Path To Node JS App file'.  Is this not included in Protractor 3?  Is there an alternative that I could use?

**Comment by gkalpak** [comment]
This is a Protractor specific question. The Protractor repo is at https://github.com/angular/protractor.
