### ISSUE TITLE
attributes function parameter for linky only works for first link

### ISSUE THREAD

**Issue by cdmckay** [angular/angular.js#14707]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

The attributes function is only called back for the first link.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

As you can see in this plunk, the setAttributes function is only called back once, even though there are two links in the text.

http://plnkr.co/edit/d5zWDOcF46wZEQjdLUYf?p=preview

**What is the expected behavior?**

There should be 2 callbacks, one for each link.

**What is the motivation / use case for changing the behavior?**

So that each link can have different attributes depending on whether or not it's an external or internal link.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

All browsers and the latest version of Angular (1.5.5 I believe).

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

It appears that the attributes function is overwritten by its return value in the first call of addLink which causes it not to be called back in further calls (since it's now an object).

**Comment by Narretz** [comment]
Oh wow, that's a bad one.
