### ISSUE TITLE
ng-if not working with controllerAs syntax

### ISSUE THREAD

**Issue by alcfeoh** [angular/angular.js#14706]
``
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Can't get ng-if or ng-show to work using the controller As syntax

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

The following H4 never shows up even if vm.foundAddress is defined:
`<h4 ng-show="vm.foundAddress">{{ vm.window.model.distance | number:2}} mi from your address</h4>`

**What is the expected behavior?**

I would expect ng-if to work with the controllerAs syntax as it's the recommended syntax

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.5

**Comment by Narretz** [comment]
Can you please put an runnable example in a plnkr.co or similar?

**Comment by alcfeoh** [comment]
My bad, it was a scope issue with angular-google-maps. Found a solution here: https://github.com/angular-ui/angular-google-maps/issues/823
