### ISSUE TITLE
Make it easier with `$cacheFactory` to recycle a cacheFactory if already exists

### ISSUE THREAD

**Issue by adambuczynski** [angular/angular.js#14716]
Currently, there's a lot of boilerplate that needs to be written when you want to either create, or re-use a specific cache if it already exists:

```js
let someCache = $cacheFactory.get('someCache');
if (!someCache) {
  someCache = $cacheFactory('someCache');
}
```

Simply calling the `$cacheFactory` constructor will throw an error saying the cache ID already exists.

Can we make the above into a one-liner, using one of the following approaches?

```js
let someCache = $cacheFactory('someCache'); //create or re-use by default
let someCache = $cacheFactory('someCache', {getIfExists: true}); //via an option
let someCache = $cacheFactory.getOrCreate('someCache'); //via a new method
```

The first option has my preference, but I realise it might cause issues where someone doesn't expect to be re-using an existing cache. Second option is less pretty, but probably the easiest to implement with the current API. 

Open to alternative suggestions as well.

**Comment by wesleycho** [comment]
One could write a helper wrapper around $cacheFactory doing that, i.e.
```js
function getCache($cacheFactory, cacheKey) {
  let cache = $cacheFactory.get(cacheKey);
  return cache ? cache : $cacheFactory(cacheKey);
}
```
And just use the helper everywhere.

**Comment by adambuczynski** [comment]
Possible, but then you have to expose that helper as a service in Angular, which feels like unnecessary overhead.

**Comment by pkozlowski-opensource** [comment]
How about a decorator of $templateCache? Such decorator could override the get method as you preffer (option 1 from your list)

**Comment by Narretz** [comment]
I also don't think we really need that in core. Decorator sounds like a good idea to me.

**Comment by gkalpak** [comment]
FWIW, you can still do it in one line :smiley:

```js
let someCache = $cacheFactory.get('someCache') || $cacheFactory('someCache');
```

You can also decorate `$cacheFactory` (I assume that is what @pkozlowski-opensource meant above (instead of `$templateCache`)):

```js
.decorator('$cacheFactory', function decorateCacheFactory($delegate) {
  $delegate.getOrCreate = function getOrCreate(cacheName) {
    return $delegate.get(cacheName) || $delegate(cacheName);
  };

  return $delegate;
})
```

I don't think this is such a common usecase, that makes it worth complicating the API.

**Comment by pkozlowski-opensource** [comment]
> I assume that is what @pkozlowski-opensource meant

Precisely that @gkalpak :-) 

I think we've got enough votes / work-arrounds to close this one for now.

**Comment by adambuczynski** [comment]
Alright, it was just a thought. Seemed to me like it would be more elegant having it in core rather than having to use decorators/workarounds, but it's not a big deal. I'll use @gkalpak's one liner instead ;)

**Comment by gkalpak** [comment]
<sub>It's not too long unless you choose long cache names :stuck_out_tongue: </sub>

**Comment by adambuczynski** [comment]
Hehe, unfortunately in this particular case the cache name is dynamic and it requires some string concatenation. That and my max line length being set to 80 doesn't help ;)
