### ISSUE TITLE
Angular 1.4 ng-options with track by

### ISSUE THREAD

**Issue by ra00l** [angular/angular.js#14729]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Using selects' ng-options directive without track by on a collection of key-value object works ok. If setting a default value, that value is taken into account. (demo: http://plnkr.co/edit/c6EK2chHDMF1HqujcuXp?p=preview)
But if in the same demo I use "track by", I am forced to select the initial value as an existing object in the collection + at first select change, that value is reset in the interface (demo: http://plnkr.co/edit/oORBDOlvvICYRIi5zQqN?p=preview)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This is expected behavior. As [documented][1], there are some limitations when using `select as` + `track by`.

[1]: https://docs.angularjs.org/api/ng/directive/ngOptions#-select-as-and-track-by-

**Comment by ra00l** [comment]
Georgios, thanks for the reply. You're right, it's documented. Still a bit weird to use; especially since the change function will receive the value as argument, not the object itself, as required by the initial select.

However, there's another issue in which when you change the selection from the interface, the select resets the value. Have a look at the "track by" plunker to see it. I doubt that this will actually be the expected behaviour. (http://plnkr.co/edit/oORBDOlvvICYRIi5zQqN?p=preview)

**Comment by gkalpak** [comment]
This is part of the above limitation - that is why you shouldn't use `select as` with `track by` unless you select the whole object. Using `opt as opt.name` restores the expected behavior: http://plnkr.co/edit/gjdi5O1Mq1zFyhqi9hLb?p=preview
