### ISSUE TITLE
Layout performance issue with nested flexbox with flexitem percentage height & width

### ISSUE THREAD

**Issue by lost78** [angular/angular.js#14724]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Chrome 50 and below produces a very short "Layout" to render tabular data that uses nested flexbox and flexitem with percentage width and height.

See attached timelines [http://imgur.com/a/LdwFO](http://imgur.com/a/LdwFO)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Working on a smaller demo, but haven't captured that lightning in a bottle. Only happening in Chrome 51+ as reported here: [https://bugs.chromium.org/p/chromium/issues/detail?id=617792](https://bugs.chromium.org/p/chromium/issues/detail?id=617792)

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Seems to occur on Mac/Win/Linux but tested across these browsers on multiple OS's where possible.

Chrome (49.0.2623.87): OK
Chrome (50.0.2661.75): OK
Chrome (51.0.2704.84): Fail
Chrome (53.0.2760.0): Fail
     Safari (9.1.1): OK 
    Firefox (39-46): OK
      IE (11, Edge): OK

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
Closing as I don't see anything Angular-related.
Feel free to reopen in case I missed something.
