### ISSUE TITLE
IE Hangs when large json data assigned from $http.

### ISSUE THREAD

**Issue by synechron-ror** [angular/angular.js#14748]
**Report a *bug***

**What is the current behavior?**
I have an application where I assign JSON response to $scope object which in turn renders all my template from the data assigned.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

I dont think I will be able to generate the plnker for this type of test. 

**What is the expected behavior?**
An application should load properly and does not stop responding the IE browser. It's happening from IE 9 to 11. 

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular 1.5.6
Browser : IE 9 to 11

**Comment by bhushangahire** [comment]
I meant to create with @bhushangahire user.

**Comment by Narretz** [comment]
Without a demo, there's nothing we can do about this issue. Does this also happen if the data is written in JavaScript directly? Then it might be a rendering problem and nothing about $http.
In general, if you have huge amount of data, that has less to do with Angular than with the browser. How many items do you render? And what do the items look like?

**Comment by bhushangahire** [comment]
Yes I tried with direct JSON and happening with that too. I am rendering like 15 to 20 templates with ng-repeat when data is assigned. Templates are Radiobutton / Checkbox list. Not anything complex. Other than IE its works great. I will see if I can generate demo.

**Comment by bhushangahire** [comment]
I think I am using $compile and when there are many templates to compile it takes time nad also uses almost 100% CPU. Is there any other way to use $compile or any alternative.

**Comment by Narretz** [comment]
You think you are using $compile? Sorry, this is too much guessing. I can take a look at a demo, but without it I can't do anything.

**Comment by bhushangahire** [comment]
You can close this. It was $compile causing the issue. I fixed it. Thanks.

**Comment by Narretz** [comment]
Good to hear that you could solve it.
