### ISSUE TITLE
Developer Guide / HTML Compiler "draggable" directive doesn't account for zoom

### ISSUE THREAD

**Issue by GeoffChurch** [angular/angular.js#14747]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
On IE (at least), if the user isn't at exactly 100% zoom, the dragged item doesn't stay aligned with the mouse.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
1. Visit https://docs.angularjs.org/guide/compiler
2. Set zoom to 150%
3. Scroll down to the draggable directive demo
4. Drag the "Drag Me" span
5. Shudder

**What is the expected behavior?**
The span should stay under the mouse at all zoom levels.

**What is the motivation / use case for changing the behavior?**
I was surprised by the behavior, and disappointed that it wasn't a robust solution.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
I'm not aware of the Angular version used, but I'm using IE 11.0.9600.18282 on Windows 7 Enterprise w/ Service Pack 1.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Just adjust offsets wrt current zoom

**Comment by Narretz** [comment]
The docs are not meant to include all-purpose directives that work under all circumstances. they are simply examples used to illustrate common concepts. Did the docs really give you the impression that this is a robust solution?

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
