### ISSUE TITLE
Input with ng-model as default transclude keeps validators alive

### ISSUE THREAD

**Issue by eyalhakim** [angular/angular.js#14765]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When using multi slot transclusion, if an input element with ng-model is being used as the default\fallback, when replace with trascluded content, validators from the default input are still present and are preventing the form from being valid.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
I think it is explained well above.

**What is the expected behavior?**
The validators should be destroyed in the $destroy function of the NgModelController

**What is the motivation / use case for changing the behavior?**
Explained aboe

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
angular 1.5.6
chrome 51.0.2704.84
Mac osx El Capitan
I just started using the multi slot transclusion and since it is new, i don't believe this ever worked before.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
for now i used ng-if on the default input as a workaround and checked for transcluded slot existance.

**Comment by Narretz** [comment]
Can you please post a demo in a plnkr or similar?

**Comment by eyalhakim** [comment]
Can you please send me an angular-ready environment in plnkr or similar?
I will complete the rest.

**Comment by Narretz** [comment]
http://plnkr.co/edit/pxbd3dTVtBpPnnqF6wEF

**Comment by eyalhakim** [comment]
There you go:
http://plnkr.co/edit/RlFUZDrEMwde2Zv4PFrw?p=preview

Thanks!
