### ISSUE TITLE
Two dimensional array with unique ng model

### ISSUE THREAD

**Issue by donjosecr7** [angular/angular.js#14767]
i am having ng repeat in <tr> and <td> i am trying to achieve a time table like structure thus require unique ng model for each cell in table

**Comment by Delapouite** [comment]
I guess this kind of question is better suited for stackoverflow.com

**Comment by donjosecr7** [comment]
http://stackoverflow.com/questions/37717733/angular-two-dimensional-ng-model?noredirect=1#comment63044446_37717733

Can you go through this and check its an issue or problem??

**Comment by Narretz** [comment]
As @Delapouite has pointed out, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
