### ISSUE TITLE
shorthand method syntax not compatible with instantiating a controller

### ISSUE THREAD

**Issue by jgrund** [angular/angular.js#14766]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Consider: 

```
x = {
  controller() {}
};

$controller(x.controller)
```

This throws:

`angular.js:4723 Uncaught TypeError: Function.prototype.bind.apply(...) is not a constructor`

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.5.6 /  51.0.2704.84

**Comment by wesleycho** [comment]
This probably fails because this uses the ES6 style of function declarations inside objects and Angular 1 uses a regex to parse the function as a string.

This probably would be fixed if one adds `x.controller.$inject = []` after the object declaration.

**Comment by gkalpak** [comment]
I don't think it has anything to do with injection. It is the same when you try to instantiate `x.controller` using `new x.controller()`.

This seems to be according to [the spec][1]: Object methods have their `functionKind` set to `'non-constructor'`, which means they don't get an internal `[[Construct]]` property, which means they can't be called as constructors.
You can still use `x = {controller: function () {}}`, though.

Closing as this is not Angular-related (and working as expected).

[1]: http://www.ecma-international.org/ecma-262/6.0/#sec-functioncreate

**Comment by jgrund** [comment]
This should probably have a note in the docs. The case that got me is creating a component:

```
{
  controller () {

  }
}
```

As people stop using babel to transpile ES6 features, more will likely hit this.

**Comment by gkalpak** [comment]
@jgrund, would you like to submit a PR for the docs?
