### ISSUE TITLE
Does ngMessageFormat support the standard ICU message syntax?

### ISSUE THREAD

**Issue by mreiche** [angular/angular.js#14762]
I just want to know if ngMessageFormat supports the syntax proposal 2 as described in this document: https://docs.google.com/document/d/1pbtW2yvtmFBikfRrJd8VAsabiFkKezmYZ_PbgdjQOVU
?
Or is it planned to support this? Because I already got ICU messages and want to reuse them in my Angular app.

**Comment by Narretz** [comment]
The document you linked is for angular 1.x, so yes ngMessageFormat supports ICU message. Is your quesiton if angular 2 will support the same messages? I believe so, but you should ask here for clarification: https://github.com/angular/angular/issues

**Comment by mreiche** [comment]
The format supported by ngMessageFormat is not the ICU message format, it has an own syntax. Also the documentation doesn't describe how to use multiple languages and how to use standard ICU messages like other frameworks.

**Comment by Narretz** [comment]
Angular uses double curly braces for interpolation, so no, the standard syntax for interpolation is not supported.
ngMessageFormat doesn't make any specific assumptions about the language. I can see that atm this is difficult as the localized messages themselves would need to be interpolated.

**Comment by Narretz** [comment]
Regarding support for different languages - since it's not possible to put the whole ngMessageFormat expression in a string, the best way I found is to create an interpolation function that is called with the context, see https://plnkr.co/edit/DxGHZo8HREkSyK6WBHWK?p=preview
