### ISSUE TITLE
Input File native support

### ISSUE THREAD

**Issue by apiweb** [angular/angular.js#14777]
**Do you want to request a *feature* or report a *bug*?**
Please add native support to Input type File.

I believe it would be interesting to add Angular (in version 2 for example), native support for Input type File.
With that we could extend to user functions/actions when the file has been selected, when it started and finished uploading, file name and content, among others.

**Comment by Narretz** [comment]
For Angular 2, we've decided not to support input[file]. For Angular2, please check if an issue is open or open an issue here: https://github.com/angular/angular/issues
