### ISSUE TITLE
$timeout and $interval do not support function which binds to a 'this' value

### ISSUE THREAD

**Issue by deplay** [angular/angular.js#14771]
Assume that we have a class named Test
```
 function Test(val) {
        this.v = val;
        this.get = function(v2) {
            return (this.v++) + v2;
        }
    }
```
We get a new instance of class Test and execute its method 'get',we get values from the 'this' reference.
```
var ins = new Test(5);
    console.log(ins.get(2));//7
    console.log(ins.get(2));//8
    console.log(ins.get(2));//9
```

But , if I use the $timeout service to execute the method asynchronously.
The 'this' value is deprecated,null is passed to function as 'this'.See a part of $timeout service source code  below.
```
timeoutId = $browser.defer(function() {
                    try {
                        deferred.resolve(fn.apply(null, args));//null is passed to function as this
                    } catch (e) {
                        deferred.reject(e);
                        $exceptionHandler(e);
                    } finally {
                        delete deferreds[promise.$$timeoutId];
                    }
                    if (!skipApply) $rootScope.$apply();
                }, delay); 
```
I am a newbie for angularjs.
I think supporting function which binds to a certain 'this' value is useful in some scenario.
If this idea is rejected by the core dev team ,I want to know the reasons,thank you .

If this idea is accepted,I will creat a branch to accomplish this idea for $timeout and $interval.

My mentality of codeing is as below.
```
// Usage
// if you want to specify a 'this' value for function
// wrap function and 'this' in a array

$timeout([ins.get, ins], 3000, true, 2).then(function(result) {
    console.log(result);
});
// Service
```
```
function timeout(fn, delay, invokeApply) {
	// if you pass a array as fn
	// consider the fn[0] as function ,fn[1] as 'this'
	// if fn is not a array,this branch will not be executed
	// even if the users don't know the change of this service
	// It dosen't cause compatibility problem
        // They can only pass a function as the first parameter as usual after the code has changed.
    if (angular.isArray(fn)) {
        var thisArg = fn[1];
        fn = fn[0];
    }
    // other codes
    deferred.resolve(fn.apply(thisArg||null, args));//if thisArg is defined ,use it.otherwise use null
    // other codes	
}
```

**Comment by dcherman** [comment]
What you want is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind which is a built in part of the language

**Comment by wesleycho** [comment]
Or if using ES6, the fat arrow `=>` syntax suffices too
```js
$timeout(() => foo());
```

**Comment by deplay** [comment]
@dcherman

function Test(val) {
    this.v = val;
    this.get = function(v2) {
        return (this.v++) + v2;
    }
}
var ins = new Test(5);
console.log(ins.get(2)); //7
console.log(ins.get(2)); //8
console.log(ins.get(2)); //9
console.log(ins.get.apply(null, [2]));//NaN
console.log(ins.get.bind(ins).apply(null, [2]));//10

in the source code ,the fn passed in is executed like this 'fn.apply(null,args)'
if I pass the ins.get ,it cause aproblem NaN
if I manually bind ins.get to ins itself,then it works.

So you mean pass ins.get.bind(ins) is more elegante than pass [ins.get,ins]?

**Comment by deplay** [comment]
@wesleycho 
good suggestion!But we are still waiting the modern browser'usage to increase.
[http://caniuse.com/#feat=arrow-functions](http://caniuse.com/#feat=arrow-functions)

**Comment by gkalpak** [comment]
Adding this feature would complicate the API for very little benefit imo.

It will deviate further away (than necessary) from the native `setTimeout` API, which is not desirable and will affect all users, while it will (marginally) benefit a small minority of usecases only.

Furthermore, it will introduce just another way to do the same thing (binding a context to a function). As @dcherman mentioned, using `.bind()` is the "industry standard" (:smiley:) for accomplishing this and providing an alternative just for `$timeout` doesn't seem to give us much (there are dozen of other places where you need the same thing - basically, everything that accepts a callback could use context-binding).

There are other ways to bind the execution context for a function call as well, such as using arrow functions (as pointed out by @wesleycho) of using a wrapper function (`function () { return ins.get(); }`).

Based on the above, I'm going to close this as _won't fix_.

**Comment by deplay** [comment]
@gkalpak 
thanks dude , I learned many coding skills form your comment.
