### ISSUE TITLE
debounce doesn't trigger $apply for $viewValue

### ISSUE THREAD

**Issue by phazei** [angular/angular.js#14776]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using debounce, the ng-modal $viewValue is actually updated right away as it should be as it's being viewed.  When that value changes, because of the offset on the debounce, it doesn't reflect until the debounce period is over when it updated the $modelValue.

**If the current behavior is a bug, please provide the steps to reproduce**
http://plnkr.co/edit/Ap8zqCfq8t3rBQszhKSV?p=preview
If you click the button after typing something in the input, you'll see the values update to what they are, but hadn't updated to before

**What is the expected behavior?**
Anything that's watching the $viewValue should be updated right away because the $viewValue has changed.  The debounce should only effect the $modelValue.

**What is the motivation / use case for changing the behavior?**
As the user is typing in the box, I'm taking the $viewValue and determining the width of the box based on the text inside it, and expanding/contracting it.  If the $viewValue doesn't update for 1000, then the box is too small and you can't see what's being typed.  

**Which versions of Angular, and which browser / OS are affected by this issue?.**
This affects 1.5.x in Chrome

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I tried using the $viewChangeListeners events since the view is actually changing, but those don't trigger until after the debounce either.  Does fix if I add a `ng-keyup=""`

**Comment by gkalpak** [comment]
TBH, I think this works as expected. One of the purposes of `ngModel` debouncing is to avoid too may digests (at least that was my first usecase for it :smiley:). So, Angular is basically ignoring the input (whatever that includes) until the debounce delay has passed.

Triggering a digest on every keystroke would be a waste for many usecases. If you need it, you can still have it via a work-around (such as adding `ng-keyup`) or properly hook into the element using a custom directive (and for example grab its actual value when the user types something).

**Comment by Narretz** [comment]
The biggest reason for debounce was to reduce the number of digests for ngModel directives. Changing this would be not sensible in this light.
