### ISSUE TITLE
AJS 1.4.X slow $http response time.  Goes away after upgrade to 1.5.6

### ISSUE THREAD

**Issue by megabyzus** [angular/angular.js#14773]
#The performance of our AJS app has gradually degraded under version 1.4.11 (for most versions of 1.4.X and 1.3.X too). Adding simple timing instrumentation has narrowed it down to $http calls (prior to DOM interpolations/setting scope variables). For *this* app, we are seeing:

- Pre/post $http times of ~1200ms-2000ms (the actual network call is ~100ms). 
- The number of $$watchers are between ~300 and ~500. 

Note 1: The sluggishness pervades promise callbacks too.  The promise callback from the $http.then promise back to the controller.then is ~20ms-30ms (this might be due to high CPU usage).
Note 2: We are not using one time binding at the moment. 

As a test, we upgraded to 1.5.6 and the performance is an order of magnitude faster:

- Pre/post $http times of ~120ms to ~130ms which is very close to the actual network call) 
- The number of $$watchers is the same @ ~300 and ~500.  

In fact, 1.5.0 is as performant as well.

Can you please point where exactly in the changelog (or blog) this 'fix' has occurred.  I see implicit references to performance improvement there and on the web ($parse and $compile) but nothing as to what exactly.  Also note, in Chrome tasks, the CPU cycles drop by about 25% and the memory footprint drops by about 40% as well.  This information will be helpful for us to permanently migrate to 1.5.7 and start the one time binding optimizations. 

Many thanks and apologies for the interruption.

**Comment by Narretz** [comment]
We haven't changed much in $http. You can try the rc and beta releases to see where it was introduced. We had beta.1, beta.2 and  rc.0, rc.1, rc,2 . My first guess is [Lazy Transclude](https://github.com/angular/angular.js/commit/652b83eb226131d131a44453520a569202aa4aac). This means that ngIf, ngSwitch aren't compiled until they actually are added to the page for the first time. This can make a difference. However, I am not sure what exactly happened in 1.4.x that would make an app signicantly slower.

**Comment by megabyzus** [comment]
@Narretz Thank you for your response.  I did a few quick tests and the issue still exists (for us) as of 1.5.0-beta.0.  Goes away at 1.5.0-beta.1.  The devolution is repeatable below 1.5.0-beta.1. 

To be clear, we $log.debug() the time of the day ('todStart' in seconds) right before an $http call and after its success callback ('todEnd'). Needless to say, deltaT = todStart - todEnd.  

I also didn't mention at application (re)load deltaT is ~300ms.-- still high compared to ~100ms network call but still not 'noticeable. deltaT jumps immediately after first state transition to the sluggish ~1200ms-2000ms deltaTs (for our app).

Thanks.

**Comment by Narretz** [comment]
Since there is no 1.5.0-beta.0, it must be 1.5.0-beta.1, and that is the one that includes lazy transclusion. It's possible that you are simply seeing fewer $http requests because templates from transcluded content aren't loaded on startup.

**Comment by megabyzus** [comment]
@Narretz, thanks.  I'm retrieving 1.5.0-beta.0 @: https://cdnjs.com/libraries/angular.js/1.5.0-beta.0.

Thanks.

**Comment by Narretz** [comment]
You are right, 1.5.0-beta.0 exists, but it's 99% the same as 1.4.6. And since you said the improvement comes in beta.1
So I wonder what you would like to know? I can't tell you exactly what the change is without knowing your application. I believe you are seeing less $http requests because some transcluded content isn't compiled at start-up.

**Comment by megabyzus** [comment]
Correct, the 'fix' happened at 1.5.0-beta.1.

By the way, if by 'transcluded content' you mean we're using 'transclude:true' in our directives (~150), we aren't. 

I wanted to know if we were doing something wrong making 1.4.8 super sluggish and it all going away by an upgrade to 1.5.X because I don't see anything on it specifically on the web. On the other hand, if we're not doing anything egregious, then perhaps there is a fix to 1.4.X for those that don't have the flexibility to move to 1.5.X.  Regardless, thank for your help and time!

**Comment by Narretz** [comment]
The performance improvement applies to many built-in directives, too: ngIf, ngSwitch, ngInclude, ngView.

Unfortunately, I can't say what makes your app sluggish pre 1.5 without looking at it.

**Comment by Narretz** [comment]
I assume this explains the performance gains? Feel free to reopen if there's still something to discuss.

**Comment by megabyzus** [comment]
@Narretz I was hoping there was a very specific fix applied since the issue is very distinct.  However, we've moved to 1.5.6 and see 10x improvement for *our* app.  Looks good!
