### ISSUE TITLE
Allow for leading '@' character in $resource paramDefaults

### ISSUE THREAD

**Issue by Blackbaud-StacyCarlos** [angular/angular.js#14788]
Not sure if this has been resolved after doing some searching of the issues so I decided to post it here.

This would be a feature to allow for a leading '@' character in a string when using the paramDefaults of the $resource factory. Currently, any string with a leading '@' character is interpreted as being an attribute of the data object and not as a string. This causes problems when trying to use it as part of GET (and presumably HEAD) requests.

**Comment by gkalpak** [comment]
I don't see how this can be a problem for GET/HEAD requests. Can you post an example?

**Comment by Blackbaud-StacyCarlos** [comment]
Sure, here's quick example.

    $resource('api/users', { filter : '@nts' })['get'];

In the example above, I want use a GET request to search for users whose names have '*@*nts' in it. However, AngularJS seems to interpret that as the property 'nts' of the data I pass and not as filter variable whose value is '*@*nts'.

**Comment by gkalpak** [comment]
I see. You are right, you can't (unless you pass the parameter on each call.

The only semi-decent way I can think of for solving this, is saying that we are going to strip a specific character if founf at the beginning of the param value (e.g. `\`). So, people will be able to send a literal `@id`, by doing `{foo: '\\@id'}`. The caveat is that if anyone wants to actually send a value starting with `\`, they need to prepend an extra `\`.
This would be a breaking change, but I don't expect it to affect many users.

Other ideas ?

(PRs are also welcome, btw :wink:)

**Comment by Blackbaud-StacyCarlos** [comment]
I would simply suggest adding a property to the required **options** parameter of the $resource factory, called **ignorePrefix** maybe, which would allow you to bypass the @ prefix while also not causing any breaking changes.

I'm not very familiar with the AngularJS code base outside of documentation, but I could look into creating a PR for this.

**Comment by gkalpak** [comment]
That's an optiion too. But it is less flexible, since you can't have some params that use `@` normally and some that use it as a literal value.

**Comment by gkalpak** [comment]
@Blackbaud-StacyCarlos, would you like to give it a shot and submit a PR.
Even the `ignorePrefix` approach is better than what we have now :smiley:

**Comment by Blackbaud-StacyCarlos** [comment]
Sure, I will attempt it. I will also consider a more flexible design.

**Comment by gkalpak** [comment]
I am going to close this since it didn't gain any traction (and there is already a work-around available).
