### ISSUE TITLE
angular.element($0).scope() can't be accessed in Firefox

### ISSUE THREAD

**Issue by pocesar** [angular/angular.js#14807]
**Do you want to request a *feature* or report a *bug*?**

Featured-bug maybe?

**What is the current behavior?**

When selecting an element with the inspect tool in Firefox, and doing `angular.element($0).scope()` returns `undefined`. Used to work fine in all browsers (Edge, Firefox and Chrome)

It does work for `angular.element('body').scope()` so there must be a catch

**What is the expected behavior?**

Should return the scope object (it works on Chrome). 

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Any version of angular. Firefox 47, windows 10 x64

**Comment by Narretz** [comment]
Are you sure you haven't set $compileProvider.enableDebugInfo = false?

**Comment by gkalpak** [comment]
It works fine for me FWIW.

**Comment by pocesar** [comment]
@Narretz the debug info is enabled, since it works in Chrome. plus when inspecting the element in Firefox, they have the ng-scope class, so it's definitely enabled. 

@gkalpak 

Chrome
![Chrome](http://i.imgur.com/sFA8OTq.png)

Firefox
![Firefox](http://i.imgur.com/gOnxqFo.png)

**Comment by gkalpak** [comment]
@pocesar, I believe you now :stuck_out_tongue:
There are probably other moving parts (e.g. I assume you use jQuery). You should create a runnable demo that reproduces the problem on Firefox while it works on Chrome and post it here along with the OS/browser versions you are using.

**Comment by pocesar** [comment]
oh well, I have near 30 libraries, will be really hard to pinpoint and make a repro, but I'm flabbergasted that only happens in Firefox and only on inner body elements.

**Comment by Narretz** [comment]
It's been a while with no response, so I'm going to close this issue because we have no reproduction of the issue. Feel free to reopen this issue if you can provide a reproduction.
