### ISSUE TITLE
Should be possible to add css class to host element of a component

### ISSUE THREAD

**Issue by rekna1** [angular/angular.js#14800]
Components do not have the replace option like directive so you can not style host element

**Comment by Narretz** [comment]
You still have access to the component's element in the controller or postLink fn. This should be enough for styling.

**Comment by rekna1** [comment]
So It s not against  best practises to add css classes to element inside components?  Thought it was moe for pure directives. Adding a class using an option declared in icomponent options would be convenient though

**Comment by Narretz** [comment]
I don't think we another option to add attributes / classes. The provided APIs should definitely be enough. Yes, usually components don't need extra classes but there's nothing specifically against adding them in the component. For everything else, there's the usual directive api.
