### ISSUE TITLE
$onChanges hook is not called when the changes happen onkeyup/onkeydown event

### ISSUE THREAD

**Issue by angun33** [angular/angular.js#14809]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
`$onChanges` doesn't get called when the change is in the keyup/keydown event

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
`$onChanges` get called where ever change happened

**What is the motivation / use case for changing the behavior?**
Not as expected

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular version 1.5.7. Tested on Chrome 50

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Can you please post a plnkr.co etc that shows this issue? There isn't enough info to act on this.

**Comment by angun33** [comment]
After looking at it again, I found out that I forgot to call $scope.apply on keydown/up event.
Sorry my mistake, you can close this issue.
