### ISSUE TITLE
$transclude.isSlotFilled returns true when the only DOM element returned is a comment

### ISSUE THREAD

**Issue by mboudreau** [angular/angular.js#14801]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
While using multi-slot transclusion, I'm calling the `isSlotFilled` function to see if it's being used.  Within one of those transclusion, I have an `ng-if` on the transclusion element itself and it returns false, hence removing the DOM element, the `isSlotFilled` still returns true even though no real DOM element is currently filling it except the `ng-if` comment.

**Expected/desired behavior**
If the only DOM element within multi-slot transclusion are comments, `isSlotFilled` function should return false, not true.

**Reproduction of the problem**
http://plnkr.co/edit/NCBtZk5eahNjpU2Vkq00

**What is the expected behavior?**
To quote the angular docs: 
> The $transclude function also has a method on it, $transclude.isSlotFilled(slotName), which returns true if the specified slot contains content (i.e. one or more DOM nodes). 

The issue is that, in my opinion, comments shouldn't be considered DOM nodes, especially the ones injected by Angular

**What is the motivation / use case for changing the behavior?**
I want to remove the transclusion from showing up if it's not needed.

**Please tell us about your environment:**

* **Angular version:** 1.5.6
 
* **Browser:** [all ] 
 
* **Language:** [ ES5 ]

**Comment by gkalpak** [comment]
This is working as intended imo. The purpose of `isSlotFilled` is to answer whether or not the user provided something to fill the slot. If the fragment you provided has a directive with specific behavior that might (or might not) remove the element from the DOM, that should not be `isSlotFilled`'s concern.

Also note that `ngIf` will always replace the element with a comment and later insert a compiled/linked instance of the "template" element, but this is really an implementation detail of a directive that is present on the content you provided for filling a slot and should not affect the behavior of `isSlotFilled` imo.

Maybe @petebacondarwin has some insights on this.

**Comment by petebacondarwin** [comment]
The reason that this happens is that the transclusion slot check is done at compile time, not linking time, which means that the `ngIf` has not yet been compiled or linked itself, which is why the slot is seen as filled. So you get this:

* `multiSlotTransclusion` directive : compile 
  * sees `<some-template ng-if="window.opener">` : slot is filled
* transclusion content compiled
  * `ngIf` is compiled
  * leaving `<!-- ngIf ... -->`
* `multiSlotTransclusion` directive : link
  * `ngTransclude` directive receives the transclusion function

So what we are saying is that slots are a "static" thing, that cannot be modified at run time.

**Comment by petebacondarwin** [comment]
An effective way to achieve what you want is to pass a parameter to the directive via an attribute.
See http://plnkr.co/edit/AndS6gErujphjmps0LmY?p=preview

**Comment by mboudreau** [comment]
@gkalpak Yeah, figured it wouldn't get fixed, just wanted to put it out there to be certain cause it doesn't work very well in my use case.   @petebacondarwin that wouldn't work in my use case since I'm trying to create a very generic directive that removes DOM elements depending if the slot is filled or not.  Don't worry about it though, I found a workaround using CSS that makes it still look good.

Cheers.
