### ISSUE TITLE
Function.prototype.bind.apply(...) is not a constructor

### ISSUE THREAD

**Issue by kiro112** [angular/angular.js#14814]
Im trying to learn angular-tdd
this is my [repo](https://github.com/kiro112/AngularJs-BDD-101)

with this versions my tests is working fine
**depencies version**
angular: 1.4.8
angular-mocks: 1.4.8
node: v4.4.5
karma-cli: 0.13.22

but when i use
**versions**
"angular": "^1.5.7"
"angular-mocks": "^1.5.7"

it throws an error
```
karma start karma.conf.js

22 06 2016 16:53:04.002:WARN [karma]: No captured browser, open http://localhost:9876/
22 06 2016 16:53:04.012:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
22 06 2016 16:53:04.018:INFO [launcher]: Starting browser Chrome
22 06 2016 16:53:05.959:INFO [Chrome 51.0.2704 (Linux 0.0.0)]: Connected on socket /#Vfy_Fpt6BZ2INRyEAAAA with id 36097936
Chrome 51.0.2704 (Linux 0.0.0) calculator sum 1 + 1 should equal 2 FAILED
	TypeError: Function.prototype.bind.apply(...) is not a constructor
	    at Object.instantiate (/home/malanay/workspace/AngularJs-BDD-101/node_modules/angular/angular.min.js:41:477)
	    at /home/kiro112/workspace/AngularJs-BDD-101/node_modules/angular/angular.min.js:90:3
	    at /home/kiro112/workspace/AngularJs-BDD-101/node_modules/angular-mocks/angular-mocks.js:2214:12
	    at Object.it (/home/kiro112/workspace/AngularJs-BDD-101/tests/calculator.controller.test.js:17:21)
Chrome 51.0.2704 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) (0 secs / 0.027 Chrome 51.0.2704 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.037 secs / 0.027 secs)
```

**Comment by wesleycho** [comment]
The problem is using the fat arrow syntax to define the function constructor for the controller class. Assuming your function passed as the second argument to module.controller is `Foo`, Angular will call `new Foo(...)` on it, which is illegal with the fat arrow syntax in ES6.

**Comment by gkalpak** [comment]
@wesleycho, is right. Controllers should be instantiable (i.e. called with `new`), so things like arrow functions (`() => {...}`) and shorthand object methods (`{someMethod() {...}}`) aren't suitable for controllers.

See https://github.com/angular/angular.js/issues/14766#issuecomment-226005516 for more details.

**Comment by nikhildev** [comment]
Hey,

I found this as some of the very few places where there is some help.
I have a component defined as 
```
import angular from 'angular';

import {IacManagerController} from './iac-manager.controller';

const IacManager = angular.module('app.automation.iac-manager', [])
.controller('IacManagerController', IacManagerController)
.component('automationIacManager', {
  controller: 'IacManagerController as iacManager',
  template: require('./iac-manager.html'),
  bindings: {
   <All my bindings here...>
  }
});

export default IacManager;
```

when I'm trying to use this in another module like below
```
import angular from 'angular';
import * as uiRouter from 'angular-ui-router';

import automationRoutes from './automation.routes';
import AutomationController from './automation.controller';
import IacManager from './iac-manager';

const Automation = angular.module('app.automation', [
  uiRouter,

  IacManager.name,
])
.controller('AutomationController', AutomationController)
.config(automationRoutes);

export default Automation;
```
I get the error *TypeError: Function.prototype.bind.apply(...) is not a constructor* in my console.
I recently converted all my code to ES6 and my controller is defined like below

```
export default class IacManagerController {
  constructor($scope, $interval) {}
}
```

This error has been haunting me now. Can't seem to get a hang of it. Any advice?
