### ISSUE TITLE
svg <use> xlink combined with ngIf cache issue

### ISSUE THREAD

**Issue by felixruponen** [angular/angular.js#14815]
**What is the current behavior?**
When using an svg use tag like `<svg><use xlink="someSvgSprite.svg#someId"></svg>` inside a ngIf block a new network request for 'someSvgSprite.svg' is issued every time the ngIf is toggled 
to true and the svg is re-rendered.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

1. Create container tag with ngIf="someToggleFlag" that contains two svg use:xlink elements
2. Record network activity in Chrome
3. Toggle the someToggleFlag to false and true again
4. The network activity should now show one more fetch for the svg sprite

I have created this plnkr to show the behaviour:

http://plnkr.co/edit/2Jy6nXQsf2XC0bfQi4qW?p=preview

Just open network tab in chrome inspector and press the toggle button to hide/show two of the icons and watch the icons.svg file be loaded every time the icons get shown again.

**What is the expected behavior?**
The expected behaviour is that the 'someSvgSprite.svg' is only fetched once.

**What is the motivation / use case for changing the behavior?**
Svg use:xlink should work with ngIf.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Tested this in Chrome v. 51.0.2704.103 with Angular 1.5.5, not sure if this is an Angular bug
or a bug in Chrome since it works as expected in Firefox ie. the 'someSvgSprite.svg' is
only fetched once.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
I'm pretty sure this is due to different browser cache implemenations - note that the same happens when you put the icons.svg in an img tag. The .svg doesn't have any caching set (Cache-Control:no-cache in response header), so it actually sounds correct that the browser gets the same image again. Note that Firefox doesn'T actually make a request - so the behavior must be in some layer that is deeper than http caching.

Afaict, the same happens without Angular: http://plnkr.co/edit/mJG33dAXI7BRavUwqoDq?p=preview

**Comment by felixruponen** [comment]
Thanks! Then I just have to load the spritesheet in a different way or inline it I guess. 
Just strange that the browsers behave differently in this way.

**Comment by Narretz** [comment]
If you set your cache headers correctly, then Chrome shouldn't request the file every time the containing svg is rendered.

**Comment by felixruponen** [comment]
Of course! Thanks a lot for the help. Now it shows up in the network tab but with the added '(from cache)' and if I go to offline mode it still shows the icons.
