### ISSUE TITLE
We can not move cursor to edit inputted value in text boxes in mobile website in FireFox mobile Browser

### ISSUE THREAD

**Issue by jatinbphp** [angular/angular.js#14817]
Hello,

We are not able to move cursor by holding mobile key board cursor from one place to another for edit text.
It Only not works in Mobile Fire fox version. Please let me know if any solution is there for this.
You can check that issue by visiting below website in Mobile FireFox browser.
https://material.angularjs.org/1.0.5/demo/input

***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular Material. Please open an issue here: https://github.com/angular/material/issues

**Comment by jatinbphp** [comment]
Okay, i submitted issue there. Thanks for Quick reply.
