### ISSUE TITLE
Incorrect date/time format i18n da-dk

### ISSUE THREAD

**Issue by jeppech** [angular/angular.js#14823]
When importing the locale for `da-dk`, the format of date and time is incorrect. The current formatting is as follows:

`24/06/2016 12.35`

The expected output would be:

`24-06-2016 12:35`

Ie. dashes should be used for seperating the date, and colon for time.

http://plnkr.co/edit/3oeU3v6Rxjiqtkzw9GVm?p=preview

Can I submit a pull request, for the source files in this repository? Or are they generated by some other source?

**Comment by wesleycho** [comment]
This issue needs to be filed against http://cldr.unicode.org/ - see https://github.com/angular/angular.js/issues/12445#issuecomment-225821998 for details

**Comment by czesiu** [comment]
@jeppech Did you manage to fix this in CLDR?

**Comment by jeppech** [comment]
Oh sorry, I forgot to give any feedback. But no, I actually never got to, submit an issue against CLDR.
