### ISSUE TITLE
Custom Directive does not data bind for select control

### ISSUE THREAD

**Issue by HimanshuK18** [angular/angular.js#14835]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In coding for a custom directive, which create drop down list, checkbox or textbox as per the condition, Angular is able to data bind the data for textbox and chcekbox, and not for drop down list.
I have created all the 3 controls through HTML first and then through angular directive next.

The drop down list created through directive does not databind, the problem I see here is that if we data bind the drop downlist through the directive and also supply it with data thorough ng-options, it creates each option as a object and not as a value. Therefore it returns each selected value as a object also.

https://plnkr.co/edit/iTyP7JircSjSu1q6PvLm?p=info

**What is the expected behavior?**
The drop down list created through the directive should data bind and the options created in the list through ng-options should be a value each and not a object.

**Comment by Narretz** [comment]
Your model does not match what the ngOptions directive expects as the model value. You can specify what model ngOptions sets with the first part of the ngOptions expression `s as s.Name` 

You can either set `s.id as s.name` and set the model to `'5'`, and the model will bind. Or if the model object is not the same as the option object, you need to set track by at the end of the option expression: `track by s.id`.
Also make sure your model has the same type (integer vs string) as the option.

That said, for support questions please try one of these channels instead next time: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
