### ISSUE TITLE
jQuery UI datepicker inside ng-if not working

### ISSUE THREAD

**Issue by phanivaranasi** [angular/angular.js#14849]
Hi Team,
I'm developing a custom datepicker using Angular Directive,
I'm developing an angularjs directive for datepicker using some options, while developing I found a strange issue.,
Below is HTML Code
```
<div>
<input type="text" id="dtpicker" name="dtpicker" />
</div>
```
Inside directive link 
```
$("#dtpicker).datepicker();
```
In the above code is **working,** 
when angularjs _ng-if_ is used datepicker is not working
```
<div ng-if="admin"> 
<input type="text" id="dtpicker" name="dtpicker" />
</div>
```
I have did some investigation and found ng-if causing blocker in binding datepicker(), Can any one help me in fixing this blocker.

Thanks
Phaneendra

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of these channels instead: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
