### ISSUE TITLE
[HELP!] Problem occurred when I used an array or object for ngModel

### ISSUE THREAD

**Issue by cesiya23** [angular/angular.js#14841]
```javascript 
// js
var app = angular.module('app', []);
app.controller('ctrl', function($scope) {
  $scope.data = [1, 2, 3];
  $scope.push = function () {
    $scope.data.push(4);
  };
  $scope.cover = function () {
    $scope.data = [7, 8, 9];
  };
});
```

```html
<input ng-model="data" type="text" /> {{data}}
<p>
  <button ng-click="push()">push</button>
  <button ng-click="cover()">cover</button>
</p>
```

I wonder why when I click the update button, data in the input does not change, but the cover function will work.

[view in plunker](http://plnkr.co/edit/cpyGZN?p=preview)

**Comment by gkalpak** [comment]
By default, test inputs are bound to string values. So, `$scope.data` will be set to a string (which doesn't have a `push` method). If you want to bind to an array, you can use `ngList` ([updated plnkr][1]), but it can only be an array of strings, of course.

--
That said, this is a general support question and is better suited for one of the [general support channels][2].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: http://plnkr.co/edit/Q0qKk4VJxerGyuGfOD6a?p=preview
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by cesiya23** [comment]
@gkalpak Thanks.

Here is a link about [ngModelWatch](https://github.com/angular/angular.js/blob/master/src/ng/directive/ngModel.js#L860)
