### ISSUE TITLE
ngSrc shouldn't load src when ngIf is false

### ISSUE THREAD

**Issue by SeanHayes** [angular/angular.js#14846]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

<img> src gets loaded when it shouldn't (when hasAutoplay is true). I can see the src get loaded in Developer Tools. As expected, the <img> element isn't rendered, so I know the logic is correct.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

In my template:

    <img ng-if="gif && (hasAutoplay === false)" ng-src="{{gif.media.gif.url}}"/>

In my controller:

    $scope.hasAutoplay = null;
    Modernizr.on('videoautoplay', function(hasAutoplay) {
        $scope.hasAutoplay = hasAutoplay;
    });

**What is the expected behavior?**

The src shouldn't get loaded.

src is not loaded when I do this:

    $scope.hasAutoplay = true;
    Modernizr.on('videoautoplay', function(hasAutoplay) {
        //$scope.hasAutoplay = hasAutoplay;
    });

**What is the motivation / use case for changing the behavior?**

I'm trying to only display a GIF if HTML5 video autoplaying isn't supported.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.5.7

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Hard to say what the problem is without a demo. Normally, this doesn't happen. Is it possible that you set hasAutoplay to false somewhere else before it is set to null?

**Comment by wesleycho** [comment]
Sounds like you need to do $scope.$apply() after setting $scope.autoplay = false;

**Comment by SeanHayes** [comment]
Closing, I think this might actually be a problem with Modernizr: https://github.com/Modernizr/Modernizr/issues/1095
