### ISSUE TITLE
 window.inject annoy me with tons of exceptions

### ISSUE THREAD

**Issue by ArtemAvramenko** [angular/angular.js#14854]
After upgrading to v1.5.7, window.inject annoy me with tons of exceptions when I run tests in IE 11.

Please move code to catch section:

![mocks](https://cloud.githubusercontent.com/assets/11413326/16525489/4e1bc300-3fb5-11e6-9268-34b83cbc07f0.png)

**Comment by gkalpak** [comment]
The whole point of this error, i to capture the stack trace at the point of declaration - not when the actual error is thrown. Why is IE11 giving you exceptions? Can you create a runnable demo (e.g. using CodePen, Plnkr etc)?

**Comment by gkalpak** [comment]
Do you have turned on the option to break at every exception (even the handled ones)?

**Comment by ArtemAvramenko** [comment]
> Do you have turned on the option to break at every exception
Yes, I want to know where the code fails and not just to see the result.

**Comment by gkalpak** [comment]
I am not sure we can do much about it. We do you need to break even on handled exceptions? A handled exception doesn't mean a failure.

Have you tried turning on the setting that will only break on your own code? Would it work for you?

**Comment by ArtemAvramenko** [comment]
> you need to break even on handled exceptions?
Yes, because Jasmine handles all exceptions in tests.

> break on your own code
Unfortunately, Visual Studio has no such option.

**Comment by gkalpak** [comment]
I don't think we can do much here - we can support one of the two:

1. Properly show the declaration location when errors are thrown in IE10+ and PhantomJS.
2. Allow people to debug in Visual Studio with the "break on all exceptions" feature enabled.

I am not sure which usecase is more common, but if I had to pick one I would say it is the first.
Also, the problems associated with the second usecase can be worked-around (e.g. do not break on every error or debug outside of VS etc).

--
I will put this in the Ice Box, but leave it open for others to chime in.

**Comment by ArtemAvramenko** [comment]
At the moment I use quick & dirty workaround:
```` javascript
(function () {
    if (window.navigator.userAgent.indexOf('Trident') < 0) {
        return;
    }
    var oldError = Error;
    Error = function (desc) {
        var e = new oldError(desc);
        if (desc != 'Declaration Location') {
            return e;
        }
        var stack = '';
        for (var caller = arguments.callee.caller; caller; caller = caller.caller) {
            var name = 'Anonymous function';
            var match = /function\s*([\w$]+)/.exec(caller);
            if (match) {
                name = match[1];
            }
            stack = stack + '\nat ' + name;
        }
        e.stack = stack.trim();
        return e;
    }
})();

**Comment by gkalpak** [comment]
I am going to close this as _won't fix_ (for the reasons mentioned in https://github.com/angular/angular.js/issues/14854#issuecomment-230353557 and because nobody else has complained about it).
