### ISSUE TITLE
Angular 1.5.5+ One-way and 2-way binding no longer copies primitives to child scope

### ISSUE THREAD

**Issue by dswamy** [angular/angular.js#14851]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Possibly a bug after angular 1.5.5 versions. Works fine prior to angular 1.5.3

**What is the current behavior?**

When using angular.component() in angular 1.5.5+, One-way and 2-way bindings no longer copies primitives from parent scope to child scope (component). We have to explicitly copy from parent using $onChanges() method. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Create 2 directives parent and child directive and bind Primitives from parent to child (also, using controllerAs:vm) using one way binding. Make change to value in parent scope. No longer refreshes child directive with value

**What is the expected behavior?**

When using angular.component() in angular 1.5.5+, One-way and 2-way bindings no longer copies primitives from parent scope to child scope (component). We have to explicitly copy from parent using $onChanges() method. 
 
This works correctly in angular 1.5.3 and prior versions

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
It is difficult to identify the problem without a reproduction. The description is quite vague. Can you please post a runnable demo of the issue (e.g. using CodePen, Plnkr etc) or a code sample that we can use to reproduce the problem?

**Comment by Narretz** [comment]
Closing due to lack of response
