### ISSUE TITLE
Minor change in the AngularJS tutorial (Step 12)

### ISSUE THREAD

**Issue by schandrasekhar** [angular/angular.js#14858]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Error in documentation, line 73 
PFA 
https://github.com/angular/angular.js/blob/master/docs/content/tutorial/step_12.ngdoc#L73

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
in this image (img/tutorial/tutorial_12.png) in step 12 (Line 73) of the tutorial, shouldn't the arrow pointing from the <phone-detail> tag say phoneDetail component ? Just wanted to confirm

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
PFA Documentation Link
https://docs.angularjs.org/tutorial/step_12

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
The fix might be that the arrow should point to phoneDetail component

**Comment by wesleycho** [comment]
I don't think this is a bug. That is under the models section, and one should consider the Angular $scope objects as the model. From that perspective, it is referring to `phoneDetail`'s data model.

**Comment by schandrasekhar** [comment]
Yes but doesnt it say phoneList component in the image ? Isnt it similiar to this step ( https://docs.angularjs.org/tutorial/step_03 ) where it says <phone-list> pointing to phoneList component.
Can u please confirm

**Comment by wesleycho** [comment]
The arrow says phoneList component on both.

**Comment by wesleycho** [comment]
Ah, I see what you're saying now - linking directly to the image here: https://docs.angularjs.org/img/tutorial/tutorial_12.png

You're correct, this is a typo.

**Comment by gkalpak** [comment]
Good catch! Actually, we have the same typo in step 10.
