### ISSUE TITLE
The future of this project (Angular 1.X )

### ISSUE THREAD

**Issue by MahdiZareie** [angular/angular.js#14862]
we are starting a large project and currently thinking about using Angular 1.X but there are concerns about the future of this project
Angular 2.0  development is quickly going forward and will release an stable version soon , but what will happen to Angular 1.X ?
how long do you intend to keep maintaining Angular 1.X ? Do you have any estimation of angular 1.x lifetime ? 2 years ? 4 years ?

**Comment by petebacondarwin** [comment]
@MahdiZareie - can I ask why you would not start this new large project with Angular 2 instead? What is the timescale for completing the new project and putting it into production? If you expect more than 6 months of development then I would definitely consider Angular 2.
Angular 1 will continue to be developed for the next few years but as the interest moves over to Angular 2, the resources put into maintaining it will be reduced.

**Comment by lgalfaso** [comment]
Hope that @petebacondarwin answered your question. One way or another, I think this is not the right place to discuss this and one of the existing forums should be used.
