### ISSUE TITLE
$http post method always having Error 500 when the content response is bigger in size

### ISSUE THREAD

**Issue by Ajishapj** [angular/angular.js#14869]
Hi 

I am using $http post method and it works perfectly as expected when the response data is small 
but when i return a bigger data it fails and goes to error function with status 500.Below is the code which i am using, please suggest any solution or advice me if i am doing something wrong.
 $http({
            method: 'POST',
            url: 'my.aspx/GetFiles',
            data: {},            
            headers: {
                'Content-Type': 'application/json'
            }
        }).then(function (response) {
            $scope.filedetails = $.parseJSON(response.data.d);           
        }, function(response){
            alert("error");
        });

**Comment by gkalpak** [comment]
If you are getting a 500 error, then this is not related to Angular (i.e. the same would happen without Angular). It could be a server configuration issue. You should look at your server's error log to find more info about the error.
