### ISSUE TITLE
$resource v1.5.6 on Firefox-only: does not pass "watch" query string parameter for GET URLs

### ISSUE THREAD

**Issue by matthewkrom** [angular/angular.js#14866]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

$resource should pass parameters for GET on query string. On Firefox only, it appears to skip parameter named "watch" (specific to only that parameter name).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Plnkr at:  http://plnkr.co/edit/E7KwZfBaYQPqDFZzTTsC?p=preview

Note I did not stub $http; check the Network console to see the missing parameter "watch" in FireFox only. Parameters "day" and "slot" work fine. Specific URL examples below.

**What is the expected behavior?**

Expected behavior: Firefox impl of $resource should include "watch=..." on query string, like it does for other names in the query string data.

**What is the motivation / use case for changing the behavior?**

The fact that it's missing seems like a bug; it's only present in Firefox.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

v1.5.6 (Plnkr above)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

! I didn't stub $http in the Plnkr above; check the Console Network log to see that, e.g., 

  Good/Chrome:  
      http://run.plnkr.co/r/get-data?day=2016-07-04&slot=1&watch=1

  Bad/FireFox (missing watch=1)  
      http://run.plnkr.co/r/get-data?day=2016-07-04&slot=1  
      !!Missing watch=1

**Comment by Narretz** [comment]
Looks like a similar issue to https://github.com/angular/angular.js/issues/11813

**Comment by gkalpak** [comment]
Yeah, it's a similar issue. Actually, it is more general than that. We are skipping any properties that are on `Object.prototype` (including `watch` on Firefox), but there doesn't seem to be a reason for that.
