### ISSUE TITLE
Make ng-show/hide work with HTML5 <dialog> elements

### ISSUE THREAD

**Issue by ph-hs** [angular/angular.js#14877]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

ng-show and ng-hide are ignored for html5 &lt;dialog&gt; elements.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo 

Refer http://stackoverflow.com/questions/38244562/getting-ng-show-to-work-with-html5-dialog-elements for code snippet.

**What is the expected behavior?**

Shouldn't have to manually call .open() or .close() on the dialog widget. ng-show and ng-hide should transparently understand dialog and interop as appropriate.

**What is the motivation / use case for changing the behavior?**

Less lines of code, is always better. Plus Angular apps should stick to Angular idioms.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.7 still has this bug/non-feature.

**Comment by Narretz** [comment]
ngShow / ngHide to something very specifc - remove / add the ng-hide class. They should not try to be clever about special elements. If we can improve dialog element handling in Angular, I'm open to it, but ngShow/Hide are not the way to go.

**Comment by Narretz** [comment]
- [ ] 

- [ ] 
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Comment by paul-hammant** [comment]
OP here by my other id. Here's a blog entry showing the mild tricks you have to do because Angular doesn't support <dialog> --> http://paulhammant.com/2016/08/06/wishing-angular-would-support-html5-dialogs-better/

**Comment by gkalpak** [comment]
Actually it is much simpler than that in Angular-land. You can create your own directive for everything you want, it doesn't need to be built-in. (Remember Angular let's you teach HTML new tricks :smiley:)

Here is one of many possible implementations: [demo][1]

[1]: https://codepen.io/ExpertSystem/pen/XKxGBV?editors=1010
