### ISSUE TITLE
Invalid Argument in IE 11

### ISSUE THREAD

**Issue by js12690** [angular/angular.js#14873]
Hello,

I am using angular js with version  v1.4.8. I am facing Invalid Argument issue in IE 11.
You can see my code as below.
---------------------------------------------------
var ele = $(".planner-container");
$compile(ele)($scope);
$scope.$apply();
--------------------------------------------------

Please help. 
Thanks in advance

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

There also not enough information about your issue -  it's impossible to say what is wrong if it's unclear what is inside the element that is compiled.
