### ISSUE TITLE
Can't load angular when Object.prototype.toJson is already defined

### ISSUE THREAD

**Issue by denisvlr** [angular/angular.js#14879]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When Object.prototype.toJson is already defined, Angular fails to load and triggers the following error:
`Uncaught TypeError: Cannot assign to read only property 'toJson' of object '#<Object>'`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

```
Object.defineProperty(Object.prototype, 'toJson',{
     value: function(){return JSON.stringify(this)},
});
var tag = document.getElementsByTagName("script")[0];
var script = document.createElement('script');
script.src = 'https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js';
tag.parentNode.insertBefore(script, tag);
```

**What is the expected behavior?**

It should catch and handle this, and load Angular anyway.

**What is the motivation / use case for changing the behavior?**
When angular is loaded along with other technologies and/or the developer doen't control the entire code, it would be great to catch and handle this error.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
fails on angular 1.2 to 1.5.7
all recent browsers

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

Can you suggest any workaround? Thanks!

**Comment by OpenSiteMobile** [comment]
Not sure, but maybe this is related to the problem:
http://stackoverflow.com/questions/27519836/uncaught-typeerror-cannot-assign-to-read-only-property

So maybe you can set it "writeable" before you load AngularJS?

Also as ref:
https://msdn.microsoft.com/en-us/library/br230269%28v=vs.94%29.aspx

Using "strict mode" as AngularJS does, the error may be indicating a less secure environment anyway.

**Comment by dcherman** [comment]
In addition to what @OpenSiteMobile mentioned a moment ago, you should likely not be modifying `Object.prototype` anyway unless to polyfill new features in older browsers.

If you're using a library that's doing this, you should file an issue against them asking them to stop.

**Comment by gkalpak** [comment]
If nothing else, you should at least make it writable.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
