### ISSUE TITLE
return promise in pending state if request was canceled

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular.js#14887]
If we cancel a request and return new unresolved/unrejected promise in catch-callback our callbacks will never done. It it good behavior for canceled requests. Otherwise we must to check canceled status in the catch-callback

**Comment by gkalpak** [comment]
It is not clear what you mean. Please provide a code sample to demonstrate the issue.
(Bonus points for providing a runnable demo (e.g. using CodePen, Plnkr etc).)

**Comment by tamtakoe** [comment]
Angular resource code
```js
//... code of $http/$resource which need to return promise.

//We add catch callback for abort status
promise.catch(function(err) {
    if (err.status === 'aborted') {
        return $q.defer.promise
    }
})

return promise;
```

Our code
```js

var News = $resource('/news', {}, {cancellable: true});

function searchNews(str) {
    return News.get({query: str});
}

var result = search('a');

//If Angular resolves or rejects canceled promise we must to check it in every callback
result.$promise.catch(function(err) {
    if (err.status === 'abort') {
        //no wrong
    } else {
        console.error('ERROR')
    }
})

//If Angular returns pending promise, then our catch callbacks will never call for aborted requests and we can handle errors without abort status checking
result.$promise.catch(function(err) {
    console.error('ERROR')
})

result.$cancelRequest();

result = search('ab');

```

**Comment by gkalpak** [comment]
I still don't get the issue. Your code has typos which do not help in that direction either.
Could you create a runnable demo. You can for example use [this pen][1] as a starting point if it helps.

[1]: https://codepen.io/ExpertSystem/pen/JKoyob?editors=1011

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Comment by tamtakoe** [comment]
I have no idea how to make clear example in plnker etc. about this topic. This is simple thing (sorry for my english).

**Now**
If you abort request you get error (in promise.catch)

**My offer**
If you abort request you get nothing because your promise will be in the endless pending state
