### ISSUE TITLE
Select ng-options expression changes on runtime

### ISSUE THREAD

**Issue by povilass** [angular/angular.js#14882]
Feature:
Possible feature for ng-options could be that you can update it on a runtime.

Current behavior:
ng-options can be set only once. Example of current behavior [plnkr](https://plnkr.co/edit/6xB9XK?p=info)

Motivation:
For example I got a list of values which should be displayed differently. Example [plnkr](https://plnkr.co/edit/dFfBsM)

**Comment by Narretz** [comment]
I am rather strongly against complicating the ngOptions logic even more. Embedding interpolation in expressions is also very un-angularlike and should be avoided when possible.

 In your case, which would be rather rare, you could simply create two selects with different ngOptions that you switch out when you need to. https://plnkr.co/edit/wG6cln?p=preview

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
