### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module ng due to:

### ISSUE THREAD

**Issue by li-ml** [angular/angular.js#14899]
I have a suite of tests that all ran fine with Karma + PhantomJS when I was at version 1.2.x of Angular, however once I upgraded all of my tests are failing.
I updated AngularJS to 1.5.0,and angular-mocks is also updated to 1.5.0.

In Angular 1.5.x, how can I properly inject a model into my unit tests?

karma.conf.js :
>     // list of files / patterns to load in the browser
    files: [
        './node_modules/angular/angular.js',
        '../../src/webapp/scripts/app-test.js',
        '../../src/webapp/apps/demo/examples/forms/validate.js',
        './node_modules/angular-mocks/angular-mocks.js',
        '../../src/test/spec/**/*.js'
    ],

app-test.js:
> var app = angular.module('abc', [    ]);

DEPRECATED: use your own version of lodash, this will go away in karma@2.0
12 07 2016 11:09:54.250:INFO [karma]: Karma v1.1.1 server started at http://localhost:9876/
12 07 2016 11:09:54.253:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
12 07 2016 11:09:54.262:INFO [launcher]: Starting browser PhantomJS
12 07 2016 11:09:55.827:INFO [PhantomJS 1.9.8 (Windows 7 0.0.0)]: Connected on socket /#gv2F7FrSQfyP3CbTAAAA with id 2835289
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
PhantomJS 1.9.8 (Windows 7 0.0.0) FormsValidateCtrl test Here adds two numbers together FAILED
	Error: [$injector:modulerr] Failed to instantiate module ng due to:
	TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')
	    at instantiate (node_modules/angular/angular.js:4619)
	    at provider (node_modules/angular/angular.js:4433)
	    at node_modules/angular/angular.js:365
	    at forEach (node_modules/angular/angular.js:335)
	    at node_modules/angular/angular.js:4423
	    at ngModule (node_modules/angular/angular.js:2475)
	    at invoke (node_modules/angular/angular.js:4604)
	    at runInvokeQueue (node_modules/angular/angular.js:4497)
	    at node_modules/angular/angular.js:4506
	    at forEach (node_modules/angular/angular.js:321)
	    at loadModules (node_modules/angular/angular.js:4529)
	    at createInjector (node_modules/angular/angular.js:4409)
	    at workFn (node_modules/angular-mocks/angular-mocks.js:2799)
	    at http://localhost:9876/context.js:151
	http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=ng&p1=TypeError%3A%20'undefined'%20is%20not%20an%20object%20(evaluating%20'Function.prototype.bind.apply')%0A%20%20%20%20at%20instantiate%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4619)%0A%20%20%20%20at%20provider%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4433)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A365%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A335)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4423%0A%20%20%20%20at%20ngModule%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A2475)%0A%20%20%20%20at%20invoke%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4604)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4497)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4506%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A321)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4529)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.js%3F7fe9d9cca8a32dbd859d791af18c3659bf2d2ee1%3A4409)%0A%20%20%20%20at%20workFn%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fangular-mocks%2Fangular-mocks.js%3F9dbebaf59ea2da974e8b7071a720a24cf08ec76e%3A2799)%0A%20%20%20%20at%20attemptSync%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1886)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1874%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1859%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A697%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A363%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A2479%0A%20%20%20%20at%20attemptAsync%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1916)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1871%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1859%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A697%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A2473%0A%20%20%20%20at%20attemptAsync%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1916)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1871%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1859%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A697%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A2473%0A%20%20%20%20at%20attemptAsync%20(http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1916)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1871%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A1859%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A697%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A2332%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F391e45351df9ee35392d2e5cb623221a969fc009%3A761%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fbase%2Fnode_modules%2Fkarma-jasmine%2Flib%2Fadapter.js%3F7975a273517f1eb29d7bd018790fd4c7b9a485d5%3A320%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fcontext.js%3A151%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9876%2Fcontext.html%3A48
	    at forEach (node_modules/angular/angular.js:321)
	    at loadModules (node_modules/angular/angular.js:4529)
	    at createInjector (node_modules/angular/angular.js:4409)
	    at workFn (node_modules/angular-mocks/angular-mocks.js:2799)
	    at http://localhost:9876/context.js:151
	    at node_modules/angular/angular.js:4527
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 1 of 2 (1 FAILED) (0 secs / 0.004 secs)
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 2 of 2 (1 FAILED) (0 secs / 0.004 secs)
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 2 of 2 (1 FAILED) (0.018 secs / 0.004 secs)

**Comment by gscoppino** [comment]
Newer versions of Angular expect `Function.prototype.bind` to be available, as support for IE8, which does not support `Function.prototype.bind`, was dropped after 1.2.x. But some older versions of PhantomJS do not have `Function.prototype.bind` available either. You can update to PhantomJS 2.x which supports `Function.prototype.bind`, or you can load a polyfill for the function before you load angular.

**Comment by gkalpak** [comment]
@gscoppino is correct. Either load a `Function.prototype.BIND` polyfill or use PhantomJS 2.

**Comment by li-ml** [comment]
@gscoppino  thank you very much,  update to PhantomJS  2.1.1 ,use  PhantomJS  "have not captured"  ,but change browsers to Chrome  the tests was executed  successfully :

PhantomJS  
> D:\SVN\pass\vmanager\client\tools\build>karma.bat
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
20 07 2016 11:01:05.961:INFO [karma]: Karma v1.1.1 server started at http://localhost:9876/
20 07 2016 11:01:06.044:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
20 07 2016 11:01:06.357:INFO [launcher]: Starting browser PhantomJS
20 07 2016 11:01:56.496:WARN [launcher]: PhantomJS have not captured in 50000 ms, killing.
20 07 2016 11:01:58.499:WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
20 07 2016 11:02:00.502:WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.

Chrome:
> D:\SVN\pass\vmanager\client\tools\build>karma.bat
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
20 07 2016 11:05:14.425:INFO [karma]: Karma v1.1.1 server started at http://localhost:9876/
20 07 2016 11:05:14.427:INFO [launcher]: Launching browser Chrome with unlimited concurrency
20 07 2016 11:05:14.439:INFO [launcher]: Starting browser Chrome
20 07 2016 11:05:40.445:INFO [Chrome 45.0.2454 (Windows 7 0.0.0)]: Connected on socket /#uOJmiXjh1Y_pVXFyAAAA with id 87513140
Chrome 45.0.2454 (Windows 7 0.0.0): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
Chrome 45.0.2454 (Windows 7 0.0.0): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
Chrome 45.0.2454 (Windows 7 0.0.0): Executed 1 of 2 SUCCESS (0 secs / 0.072 secs)
Chrome 45.0.2454 (Windows 7 0.0.0): Executed 2 of 2 SUCCESS (0 secs / 0.072 secs)
Chrome 45.0.2454 (Windows 7 0.0.0): Executed 2 of 2 SUCCESS (0.094 secs / 0.072 secs)

**Comment by andorremus** [comment]
adding this to a js file and importing it sorted it out for me 

```
if (!Function.prototype.bind) {
  Function.prototype.bind = function(oThis) {
    if (typeof this !== 'function') {
      // closest thing possible to the ECMAScript 5
      // internal IsCallable function
      throw new TypeError('Function.prototype.bind - what is trying to be bound is not callable');
    }
    var aArgs   = Array.prototype.slice.call(arguments, 1),
        fToBind = this,
        fNOP    = function() {},
        fBound  = function() {
          return fToBind.apply(this instanceof fNOP
                 ? this
                 : oThis,
                 aArgs.concat(Array.prototype.slice.call(arguments)));
        };

    if (this.prototype) {
      // Function.prototype doesn't have a prototype property
      fNOP.prototype = this.prototype; 
    }
    fBound.prototype = new fNOP();

    return fBound;
  };
}

```


Source for the code is [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind)
