### ISSUE TITLE
$cookies.get("JSESSIONID") return undefined

### ISSUE THREAD

**Issue by pienikrz** [angular/angular.js#14935]
$cookie.get("JSESSIONID") always return undefined even if JSESSIONID cookie is set by the browser.
Angular version: 1.4.9. Checked on Chrome 51.0.2704.103 and Firefox 44.0.2

**Comment by gkalpak** [comment]
Please, provide a runnable demo (e.g. using CodePen, Plnkr etc) or the exact steps and code to reproduce this. Without a concrete reproduction, there is no way we can investigate this.

**Comment by arungeorge101** [comment]
@pienikrz I tried this in plnkr and I am able to get the value from the cookie. Check this plunker:

http://embed.plnkr.co/hl5s8UqFROwNiimfYYId/

**Comment by gkalpak** [comment]
Closing since there was no response from the OP and we don't have a reproduction.
<sub>Happy to reopen when/if you can provide more info and/or a reproduction.</sub>

**Comment by bfx** [comment]
Still happening to me, angular 1.6.2 and angular-cookie 1.6.2. 
I'm on a gulp development environment with browser-sync, angular-ui-router.

These are the "steps" (sorry no time now to update the plunker already provided), I payed attention to not cause any page reload from browser-sync.
- login state/page: In a "SessionService" I put $cookies.put('JSESSIONID', response.data.portofinoSessionId);
- the cookie is visible in chrome developer tools for domanin "localhost:3000"
- change state after login
- home page: again in the previous "SessionService" try $cookies.get('JSESSIONID') but return undefined 
- the cookie is still visible in chrome developer tools for domanin "localhost:3000"

**Comment by csdenboer** [comment]
I'm having the same issue
