### ISSUE TITLE
$location.path - issue rendering full page

### ISSUE THREAD

**Issue by tbone849** [angular/angular.js#14940]
Using $location.path to change the URL causes an issue where the browser doesn't add the vertical scrollbar the browser window. I am using $location.path to after logging in a user. The behavior can be viewed in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/11409836/17031641/2b5e2ef0-4f43-11e6-8d81-722b2e3292cb.png)

When I refresh the page, the vertical scrollbar is loaded correctly. See below.

![image](https://cloud.githubusercontent.com/assets/11409836/17031692/6de2a9b8-4f43-11e6-901e-c584721f8151.png)

Using:
Chrome -  Version 52.0.2743.82 m
Angular - v1.5.6

**Comment by gkalpak** [comment]
@tbone849, this sounds more like a browser issue. Have you tried on other browsers or other Chrome versions? Have you tried on different OSs and/or with different Angular versions?

<sub>Btw, while screenshots are great for visualizing the problem, they don't help much in reproducing/investigating it. It would be very helpful, if you posted a runnable reproduction (ideally a live demo, e.g. using CodePen, Plnkr etc).</sub>

**Comment by tbone849** [comment]
Tried also on Edge and Opera. Same result. I know what you mean about screenshots. I'll see if I can get a CodePen up today.

**Comment by tbone849** [comment]
@gkalpak Ok. Solved the problem on my own. Turns out it wasn't an Angular issue, it was a Bootstrap modal issue. The modal wasn't closing properly and wasn't allowing for scrolling.
