### ISSUE TITLE
angular.merge fails with MediaStream objects

### ISSUE THREAD

**Issue by matthieusieben** [angular/angular.js#14941]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
`angular.merge` transforms MediaStream objects in `src` into plain JavaScript Objects.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

With the template: https://plnkr.co/edit/4cBUxjdB4kya0s5Wtbxd?p=preview 
Simpler: https://plnkr.co/edit/LGUAcCTbYyf4UTxSbvBC?p=preview

``` js
navigator.mediaDevices.getUserMedia({ audio: true }).then(function (stream) {
  var dst = angular.merge({}, { stream: stream });
  console.error('Is valid ?', stream === dst.stream); // false
})
```

**What is the expected behavior?**
`angular.merge` (and derived) should not alter MediaStream objects.

**What is the motivation / use case for changing the behavior?**
Allow writing simpler/cleaner code. The workaround is simply to manually set the stream objects.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Google Chrome - Version 51.0.2704.106 (64-bit)
Other browsers probably also affected.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
MediaStream objects should be cloned properly (MDN: `MediaStream.clone()`) in the case of `angular.clone`, or copied as is in `angular.merge` and `angular.extend`.

**Comment by Narretz** [comment]
The angular.* helpers are mainly designed for the uses of Angular core, so we don't usually prioritize fixing bugs in them. Pull requests are welcome nevertheless.

**Comment by matthieusieben** [comment]
The issue still exists with `angular.clone`

**Comment by gkalpak** [comment]
What is `angular.clone`?

**Comment by matthieusieben** [comment]
Il meant, `angular.copy`, sorry you were not able to figure that out...

**Comment by Narretz** [comment]
Sorry you were not able to make yourself clear ... :D

So for copy this should probably be fixed as copy is used by scope.$watch
For extend ... maybe, because that's used in route where it extends the params object.

**Comment by Narretz** [comment]
Actually, I can't see that extend is broken: https://plnkr.co/edit/B3LebuAQPoj6kRgS2eCG?p=preview 

I created an issue for copy:
https://github.com/angular/angular.js/issues/16055
