### ISSUE TITLE
Angular 2 website doesn't load

### ISSUE THREAD

**Issue by bharath6693** [angular/angular.js#14949]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

unable to access the Angular 2 website. (https://Angular.io) Chrome says: ERR_SSL_PROTOCOL_ERROR

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

n/a

**What is the expected behavior?**

Loading of webpage successfully.

**What is the motivation / use case for changing the behavior?**

n/a

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

n/a

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
n/a

**Comment by gkalpak** [comment]
The repository for the angular.io website is [here][1]. (I can access angular.io without a problem fwiw.)

[1]: https://github.com/angular/angular.io

**Comment by madmikede** [comment]
Same issue here.
unable to access the Angular 2 website. (https://Angular.io) Chrome, FF and IE says: ERR_SSL_PROTOCOL_ERROR

Deleting Cookies, Cache, etc. doesn't help. I'm not able to get website open in any of my browsers.

Opening the website from my tablet (same network) works fine. So it doesn't seem to be a Firewall issue.

**Comment by gkalpak** [comment]
Same response [here][1] :smile:

[1]: https://github.com/angular/angular.js/issues/14949#issuecomment-235172176

**Comment by madmikede** [comment]
So your answer is basically: "hm, works for me, so I'm fine. But you can get a copy here".

Please don't get me wrong, I'm fine with this answer and will grab a copy from github. But if I would give this answer to my customer he would rip my head off. ;-)
There seems to be a problem with the website and I think someone should have a look at this and investigate what the problem is. But that is non of my business.

**Comment by gkalpak** [comment]
Not really. My answer is more like: "This is the wrong place to report such an issue, because this repository is not related to angular.io" (plus pointing you to the correct repository).
