### ISSUE TITLE
ngInclude not working in google chrome extension

### ISSUE THREAD

**Issue by mgodoyr** [angular/angular.js#14955]
the ngInclude directive does not work within an extension for google chrome , I replied the following functionality within the extension

**template.js**

```javascript
angular
  .module("myApp")
  .run(["$templateCache", function($templateCache) {
         $templateCache.put("test.html","<div>working</div>")
  }]);
```

**view.html**

```html
<div>
  <ng-include src = " 'test.html' ">
</div>
```

when I check the rendering code in the part where this declared ngInclude shows :

```html
<!-- ngInclude : undefined -->
```

_the extension creates an iframe , insert it into the DOM and injected into the entire application in angular_

**Comment by gkalpak** [comment]
We need more info in order to investigate that. Can you share a minimal reproduction?

**Comment by mgodoyr** [comment]
replicate a test environment in a public repository , as the policies of the project where I have the incidence does not allow me to publish the source code .

**Comment by gkalpak** [comment]
We can't investigate what we can't see :smiley: If you can somehow help us reproduce the problem (not necessarily using the code from your project), we can investigate. There is not much we can do without a reproduction.

**Comment by emegodoyr** [comment]
the error was solved , the problem through the interceptor that does not validate the priority of the request , the priority is evaluated and if templateCache who makes the request does not fall into any mistake, I close the issue
