### ISSUE TITLE
Dropdown issue in IE when working with RWD

### ISSUE THREAD

**Issue by bootlearn** [angular/angular.js#14954]
Dropdown menu is going out of the view when working with RWD, width is not getting adjusted. We have tried adjusting the width,padding and other various component. Width is working fine for Firefox but In IE is not getting reflected.

Any suggestions?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

Note that Angular Core doesn't provide a dropdown, it only provides data binding to select elements. I assume you are having problems with a 3rd party library.
