### ISSUE TITLE
incorrect minification in angular-message-format.min.js

### ISSUE THREAD

**Issue by metamatt** [angular/angular.js#14966]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If I use the unminified angular-message-format.js (version 1.5.5 or 1.5.8), and feed an invalid ng-expression (unterminated string constant) into it, I get a proper "untermstr" error.

If I feed the same invalid ng-expression into angular-message-format.min.js, then $ngMinError blows up while trying to construct the "untermstr" error with

```
VM1079 angular.js:13920 TypeError: template.replace is not a function
    at VM1079 angular.js:49
    at c.ua (VM1081 angular-message-format.min.js:16)
    at c.Ba (VM1081 angular-message-format.min.js:14)
    at interpolate (VM1081 angular-message-format.min.js:25)
    at addAttrInterpolateDirective (VM1079 angular.js:9783)
    at collectDirectives (VM1079 angular.js:8714)
    at compileNodes (VM1079 angular.js:8539)
    at compileNodes (VM1079 angular.js:8555)
    at compile (VM1079 angular.js:8442)
    at VM1079 angular.js:1763
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

https://jsfiddle.net/qwo7mnxn/1/

**What is the expected behavior?**

untermstr error

**What is the motivation / use case for changing the behavior?**

It's impossible to diagnose errors in template strings.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Angular 1.5.5 and 1.5.8 are both broken this way, tested on Chrome 51 under Mac OS X 10.11 but I have no reason to think it's browser/OS dependent.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

I don't know what's wrong with the minified code but it works fine with the unminified code, so I suspect something wrong in the minifier or build pipeline

**Comment by metamatt** [comment]
I'm installing Angular and related libraries (-message-format, etc) via jspm, and bower-angular-message-format defaults to the .min.js (unlike all the other bower-angular-* projects), due to https://github.com/angular/bower-angular-message-format/blob/master/index.js. I removed the ".min" from that index.js in my source tree and this problem went away. I think the project on install should probably default to unminified code and people can set up their own build pipeline if they want minification. But if you're going to provide minified code, it should work the same way as the unminified code, right?

**Comment by metamatt** [comment]
Also filed as https://github.com/angular/angular/issues/10384 (I don't know where it's better categorized)

**Comment by gkalpak** [comment]
This is expected behavior, because you are using the minified `angular-message-format` with the unminified `angular` core file. Since minified files are intended for use in production, they `minErr` implementation (which is responsible for constructing and logging the errors) is slightly different, not showing the error description in the console.

Using minified files, the error is logged correctly (includes the error code and the URL to the error page, which contains all the info).

**Comment by metamatt** [comment]
OK, thanks for explaining _why_ it doesn't work - that `minErr` doesn't work if you cross minified/non-minified versions of angular core/additional modules.

However, I think there's still a real problem here, which is that "out of the box", angular-message-format defaults to using the .min.js. (At least this is true if I install with jspm, and from the look of https://github.com/angular/bower-angular-message-format/blob/master/index.js, this would be true for installing via npm or bower as well.) For all the other angular-* libraries I've tried, installing via jspm, I get unminified code active until I make changes to use the minified version, but for angular-message-format, it's always using the minified version (and thus, produces this problem by default).

Note that https://github.com/angular/bower-angular-message-format doesn't accept issue reports, and says to file issues and pull requests against *this* repo.

**Comment by gkalpak** [comment]
You are right. I opened angular/bower-angular-message-format#4 (before I realized there were already 2 (almost) identical PRs :grin:).
