### ISSUE TITLE
The app does not work on iPad and iPhone

### ISSUE THREAD

**Issue by felixfx777** [angular/angular.js#14974]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Everything works on computer and Android. On iPad and iPhone not working.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Just open my project on iPad.  https://felixfx777.github.io

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
all browsers on iPad and iPhone.
https://code.angularjs.org/1.5.8/angular.min.js and older.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I'm new

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

Note that we cannot debug a complete app. If you think you've found a specific bug, please create a minimal demo that reproduces it and open a new issue.
