### ISSUE TITLE
IE 11 Out of memory issue

### ISSUE THREAD

**Issue by deepjyotiTechjini** [angular/angular.js#14975]
Hi,

When my application is used for 10-15 mins in IE, I am getting Out of memory issue and browser freezes.
error message we got in console

```
SCRIPT2344: Out of memory at line: 1
SCRIPT7: Out of memory
SCRIPT5022: [$injector:modulerr] http://errors.angularjs.org/1.5.7/$injector/modulerr?p0=ng&p1=Out%20of%20memory
File: angular.min.js, Line: 1, Column: 47
```

angular version we are using 1.5.6

Thanks

**Comment by Narretz** [comment]
Impossible to say what the problem is. There's probably a memory leak in your application, but we cannot say whether it comes from your code or from Angular core. You must first see if it comes from your code.
