### ISSUE TITLE
$locationChange events fire after destination controller has been initialized

### ISSUE THREAD

**Issue by briananderson1222** [angular/angular.js#14981]
**I want to report a *bug*?**

**What is the current behavior?**

$locationChange events fire after destination controller has been initialized (haven't tested with ngRoute)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

http://plnkr.co/edit/mO7OPoPzEg1u2QCGJQ9N?p=preview

**What is the expected behavior?**

I would expect the $locationChange events (or at least the $locationChangeStart event) to fire before the destination controller has been initialized

**What is the motivation / use case for changing the behavior?**
Specific to our use case is subscribing to location changes in a router agnostic way to clear modals that may have not been dismissed on a previous location (I know this is quite specific to our use case)

Hoping at the very least to get a little more clarity as to why these events fire after the state has been initialized. Problem does not seem to exist with $stateChangeSuccess or $routeChangeSuccess events..

**Comment by Narretz** [comment]
> haven't tested with ngRoute

Then you'll have to ask in the ui-router repo, or re-create the example with ngRoute.
uiRouter is quite similar to ngRoute, but I can't say that ngRoute behaves the same. So it might just be uiRouter issue.

**Comment by gkalpak** [comment]
This is indeed not happening with `ngRoute` ([demo][1]).
Closing as this is specific to `ui.router`. You should open an issue in their repo (as suggested by @Narretz).

[1]: http://plnkr.co/edit/P59Cp5813yLD8z6kG3fY?p=preview
