### ISSUE TITLE
Resolved ngRoute route dependencies are not injected into components

### ISSUE THREAD

**Issue by Lingomat** [angular/angular.js#15012]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

This looks like a bug.

**What is the current behavior?**

Based on the documentation of components, using a component as a router with ngRoute does not appear to bind resolve dependencies as claimed. Undefined variables appear on the scope.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

https://plnkr.co/edit/AvOSYrLJDGB27MKQnMxe?p=preview

This plunker shows the effect. Resolve works okay, you can uncommon reject() to see a route change failure, but if resolve() is used then either the resolve property or resolveAs, both result in undefined variables.

**What is the expected behavior?**

I would expect to see the same behavior as when injecting resolves, using a directive as a router. Behavior as documented at https://docs.angularjs.org/guide/component

**What is the motivation / use case for changing the behavior?**

So it works as the docs said. Well, it doesn't seem possible to use components as routes.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.8. This was the only version tested. The documentations states that this works as of 1.5.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

No clue sorry. There are no errors, just undefined variables.

**Comment by Narretz** [comment]
The resolves aren't automatically injected into the component, you have to do this yourself. Since 1.5, Angular makes this easier by putting the resolves on the $scope as $resolve (or as the property you specify in resolveAs), so

```
    $routeProvider.when('/', {
        template: '<whatevs bind="$resolve.thing"></whatevs>',
        resolve: {
            thing: promisethinggy
        }
    });
```

If the docs gave you the impression that injection is automatic, then maybe we can improve them.
