### ISSUE TITLE
Problem loading content using promises (only with Google Chrome)

### ISSUE THREAD

**Issue by rafaelcastillolopez** [angular/angular.js#15013]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
A possible bug (it only happens on Chrome v52.0.2743.116 and newer versions)

**What is the current behavior?**
App seems to freeze while loading content using promises

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
- For example, go to [http://212.227.143.28:8081](url)
- Try to filter using box "Find issue" (for example, try to filter by user john.doe)
- It "freezes" on "Please wait"

**What is the expected behavior?**
In other browsers (or previous versions of Chrome) it works as expected: the page ends loading and the app shows rows which contains words used in filter

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
angular 1.3.20, google chrome 52.0.2743.116 and newer

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I don't know if it's a bug of angularjs (or some other related components) or if it's a Chrome problem (just in case I've opened an issue on chromium page [https://bugs.chromium.org/p/chromium/issues/detail?id=636699](url) ). I've uploaded source code of this example project to github: [https://github.com/rafaelcastillolopez/issues](url)

**Comment by Narretz** [comment]
I can reproduce the behavior, but it's very difficult to say what exactly the problem is, as I can't see the source code and it's a full app. So any number of things might cause this problem.

Can you please try and create a minimal demo that shows this problem and put it on plnkr.co or similar?

**Comment by rafaelcastillolopez** [comment]
You can see code of this simple app on
https://github.com/rafaelcastillolopez/issues . In fact I've tried to
simplify my example: first with a simple promise (with $timeout), a promise
with $http, adding angular-loading-bar, adding angular-busy, searching
larger JSON in order to make it fail,... but in fact it works ok. On the
other hand, my simple app is not so big: involved controller is
CasoListCtrl.js and basically uses loading-bar, angular-busy and angular
resource (which goes against a mongodb instance with a simple collection).
I'll keep trying to find some simpler example but I'll be very pleased if
you could take a look on my repo (just in case you could see some possible
cause of this problem).

Thank you in advance

2016-08-11 11:12 GMT+02:00 Martin Staffa <notifications@github.com>:

**Comment by gkalpak** [comment]
I took a look but didn't spot anything. This also using a pretty old version. Could you try with the latest (e.g. 1.5.8 or snapshot)?

<sub>(I wouldn't be too surprised if this was some of Chrome's "optimization" that have been breaking things lately, but (like @Narretz said) it is very difficult to investigte properly without a more stripped down reproduction.)</sub>

**Comment by rafaelcastillolopez** [comment]
Sure, I've tried with 1.5.8 and it fails the same way... I've opened the
following issue on chromium
https://bugs.chromium.org/p/chromium/issues/detail?id=636699 just in case.
Meanwhile I'll continue making tests (if I find something I'll update info).

Thank you anyway

2016-08-12 15:11 GMT+02:00 Georgios Kalpakas <notifications@github.com>:

**Comment by francisace** [comment]
Hi @rafaelcastillolopez, thanking for posting the example. Having a similar issue here as well, have you had any workaround for this?

**Comment by rafaelcastillolopez** [comment]
Yes, disabling ETags on express with

app.set('etag', false);

it works perfectly. Here you can find more information:

https://bugs.chromium.org/p/chromium/issues/detail?id=633696
https://bugs.chromium.org/p/chromium/issues/detail?id=636699

In fact it's a Chrome issue, so I propose to close this one because it's
not angularjs related.

Cheers

2016-08-17 17:11 GMT+02:00 francisace <notifications@github.com>:

**Comment by flaurian** [comment]
Thanks this solved my problem.
