### ISSUE TITLE
ngCookies not always updating

### ISSUE THREAD

**Issue by messerbill** [angular/angular.js#15020]
Hi all,
i try to update some cookie data in my Angular Application. This works more or less, but sometimes it behaves very strange:

For example i want to update the "Tabs" which are saved in the cookies when a user sent a search request (i want to save the search parameters into the tabs, so you can leave a tab and once you return back to it, you can reload your search results). In my angular Controller there is a function which handles the search, and once it finished its job, the following method is called to update cookie data:

    `updateSearch: function (id, search) {

            var count = 0;

            var index = false;

            angular.forEach($rootScope.tabs, function (tab_) {

                if (id === tab_.id)

                    index = count;

                count++;

            });

            var tab = $rootScope.tabs[index];

            tab.search = search;

            $rootScope.tabs[index] = tab;

            console.log(tab);

            $cookies.putObject("wawiTabs", {

                tabs: $rootScope.tabs

            });
        },`

But this does not update the tabs. When i inspect the cookies, the new value is not yet added. the $rootScope.tabs are updated correctly, and the way i try to update those cookies with this logic, it works in other application parts. 
The bug i am describing here also appears when i try to save a pagination number. When i click on a page number inside of the tab, everything works fine. But when i leave the active tab and return to it again, it still saves the old value. It seems like there is a kind of cache which prevents updating cookie data sometimes...can you help me here?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).
