### ISSUE TITLE
I use $location.search()['url'] to get a url param, but can't get it correct. 

### ISSUE THREAD

**Issue by huaidan5859** [angular/angular.js#15029]
I use $location.search()['url'] to get a url param, but can't get it correct. The format of this parameter is http://example.com/#/some/path?foo=bar&baz=xoxo&url=http:%2F%2Fexample.com%2F#%2Fpage1%2Fpage. result is http://example.com/. how can I get the correct url?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
