### ISSUE TITLE
docs(guide/security) add more info about template generation

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#15033]
We should enumerate the ways the Angular template can be generated. 

Reflecting it from the server response is the most popular way, but there are XSS bugs using other compilation sinks in e.g. directives that are not obvious (e.g. $compile(userControlled) and $eval(userControlled).

**Comment by gkalpak** [comment]
Is this covered by #15094 or did you have something different in mind?

**Comment by petebacondarwin** [comment]
Covered. Thanks
