### ISSUE TITLE
Error: TypeError: router_1.Routes is not a function(…) 

### ISSUE THREAD

**Issue by sajiddesigner** [angular/angular.js#15031]
Hello,

I am having following error in console 
(index):18 Error: TypeError: router_1.Routes is not a function(…) 

If i remove <router-outlet></router-outlet> from code then error vanish away.

my App.component.ts code is

`import { Component } from '@angular/core';

import {ROUTER_DIRECTIVES, Router, Routes, RouterModule } from '@angular/router';

import { NavbarComponent } from './components/navbar/navbar.component';
import { JumbotronComponent } from './components/jumbotron/jumbotron.component';
import { HomeComponent } from './components/pages/home.component';
import { AboutComponent } from './components/pages/about.component';

@Component({
  selector: 'my-app',
  template: `
  			<navbar> </navbar>
  			<jumbotron> </jumbotron> 			
			​<div class="container">
​   <router-outlet> </router-outlet>
​        </div>
  			`,
  directives: [ROUTER_DIRECTIVES, NavbarComponent, JumbotronComponent, HomeComponent, AboutComponent]
})

@Routes([
	{path: "", component: HomeComponent},
	{path: "about", component:AboutComponent}
	])

export class AppComponent {
	constructor(private router: Router){

	}
 }
`

main.ts

`import { bootstrap }    from '@angular/platform-browser-dynamic';
import { AppComponent } from './app.component';
import {ROUTER_PROVIDERS} from '@angular/router';

bootstrap(AppComponent, ROUTER_PROVIDERS);
`

Plz confirm where i am doing wrong

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular2. Please open an issue here: https://github.com/angular/angular/issues
