### ISSUE TITLE
angular $cookie problem

### ISSUE THREAD

**Issue by FaridBeiranvand** [angular/angular.js#15035]
hi.im using angularjs v1.5.8 and i want to use $cookies for set cookie in browser.i use this method for set cookie :
$cookies.put("username", "peter");
but when browser closed the cookie is cleared!
i want to have cookie for unlimited time without exipre.
please help me.thanks a lot.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
