### ISSUE TITLE
docs(guide/component) correct usage recommendations

### ISSUE THREAD

**Issue by zuzusik** [angular/angular.js#15042]
Currently in section `When not to use Components` it is said:

> - for directives that rely on DOM manipulation, adding event listeners etc, because the compile
and link functions are unavailable

But there is a `$postLink` hook which is described in the same document as follows:

>* `$postLink()` - Called after this controller's element and its children have been linked. Similar to the post-link
    function this hook can be used to set up DOM event handlers and do direct DOM manipulation.

I assume text from the first quote should be changed to something like

>  - for directives that need to perform actions in compile and pre-link functions, because they aren't available

Thoughts?

**Comment by gkalpak** [comment]
Sounds reasonable. The initial guide was written before lifecycle hooks (such as `$postLink`) were implemented.
