### ISSUE TITLE
$postLink lifecycle functions are not executed in the correct order

### ISSUE THREAD

**Issue by onlywei** [angular/angular.js#15045]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When there is a parent component and a child component, the parent component's `$postLink()` is executed before the child component's `$postLink()`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar **
http://plnkr.co/edit/uGLPHfJO1EDE9f1VlNk6

**What is the expected behavior?**
The child component's `$postLink()` should execute before the parent component's `$postLink()`

**What is the motivation / use case for changing the behavior?**
I believe this is incorrect.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5.9

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by dcherman** [comment]
This is expected behavior when using `templateUrl` and async compilation.  See the description of `$postLink` available on https://docs.angularjs.org/api/ng/service/$compile#life-cycle-hooks

**Comment by onlywei** [comment]
@dcherman if I switch from using `templateUrl` to just use `template` and pass strings, I get an error saying that my `require` config is invalid.

**Comment by onlywei** [comment]
Ah, OK I got it. The trick is to just not use transclusion by not having a template for the parent component at all: http://plnkr.co/edit/uGLPHfJO1EDE9f1VlNk6
