### ISSUE TITLE
When a component is wrapped in 'p' tags, the transclude does not function as expected

### ISSUE THREAD

**Issue by stuartdonald-ibboost** [angular/angular.js#15054]
Tested on Angular 1.5.8

I have a component, that has multiple transclusion slots. When this component is inside a p tag, the transclusion has an error. If the component is not wrapped in a p tag, then it functions as expected.

Here is an example which can reproduce the issue:

```
var app = angular.module('miniapp', []);
app
  .component('modal', {
    template: '<div style="border:solid;">' +
      '  <div' +
      '  ng-transclude="title">' +
      '</div>' +
      '<div' +
      '  ng-transclude="body">' +
      '</div>' +
      '</div>',
    transclude: {
      title: 'modalTitle',
      body: 'modalBody'
    },
    controller: function() {
      // Stuff to make this component render as a modal
    }
  });
```

```
<div ng-app="miniapp">
  <p>
    <modal>
      <modal-title>
        <div>This is busted because its wrapped in p tags. It should have a border</div>
      </modal-title>
      <modal-body>
        <div>
          Take the p tags away and it works
        </div>
      </modal-body>
    </modal>
  </p>
</div>
```

When running you get the following error:

> angular.js:13920 Error: [$compile:reqslot] Required transclusion slot `body` was not filled.

I have an example here which reproduces the issue [https://jsfiddle.net/7ytp0zdm/](https://jsfiddle.net/7ytp0zdm/)

If you remove the wrapping p tag, then the error goes away.

This is not a blocking issue, as you can work around it, unless you must have your component directly inside a p tag. However it is an unintuitive failure, and can cost you a lot of time trying to figure out why your seemingly correct component is not working.

**Comment by arafath-mk** [comment]
@name: Ashfaq

**Comment by gkalpak** [comment]
This is because of the permitted contents of `<p>` elements, according to [the spec][1]. The browser will move non-permitted contents (e.g. `<div>` elements) outside of the `<p>` element. (There is nothing Angular can do about it.)

The resulting HTML looks like this:

```html
<p>
  <modal>
    <modal-title></modal-title>
  </modal>
</p>
<div>This is busted because its wrapped in p tags. It should have a border</div>
<modal-body>
  <div>
    Take the p tags away and it works
  </div>
</modal-body>
<p></p>
```

[1]: https://www.w3.org/TR/html-markup/p.html
