### ISSUE TITLE
Syntax error in directive does not throw exception

### ISSUE THREAD

**Issue by derfsubterfuge** [angular/angular.js#15056]
**Do you want to request a *feature* or report a *bug*?**
I am reporting a bug.

**What is the current behavior?**
If a directive is missing a comma in a particular position, no exception is thrown into the console and the directive does not work.  Here is an example, where the missing comma is at the end of line 8 of the JavaScript section:
Working directive: https://jsfiddle.net/derfsubterfuge/y9xd3mdb/
Broken directive: https://jsfiddle.net/derfsubterfuge/2nfy6b4c/1/

The example is using Angular 1.5.8.  I have attempted this on Fedora 24 for both Chrome 52.0.2743.116 (64-bit) and Firefox 48.0 (64-bit).

**What is the expected behavior?**
I would expect a syntax error to be thrown in the console and not swallowed.

**Comment by Narretz** [comment]
This is not an Angular specific problem and also not a syntax error. When you do `console.log('string' [function(){}]);` you will get `undefined`. It must be some strange Javascript parsing thing. We could throw an error though if the .directive fn is called with undefined.

**Comment by gkalpak** [comment]
As @Narretz said, this is valid JS syntax and results into calling `.directive(undefined)`. Fwiw, it is equivalent to:

```js
var obj = '...';
var propName = (function () {}).toString();
myModule.directive(obj[propName]);
```

**Comment by derfsubterfuge** [comment]
Ah, that makes sense.  JavaScript has so many weird things that you can do.
