### ISSUE TITLE
Problem with an Input=Range and their placeholder attribute in Microsoft Edge

### ISSUE THREAD

**Issue by dec** [angular/angular.js#15063]
Hello to all,

I am not sure if this is a problem with AngularJS 1.5.8 or with the Microsoft Edge browser, but, if you try this sample:

http://jsfiddle.net/2Pk3M/696/

... you can view it running in all browsers that I try (Firefox, Chrome, Internet Explorer 11) except in Microsoft Edge...

I know maybe a "placeholder" attribute for the Input Range is not really good, but, apparently other browsers simply ignored it, while Microsoft Edge simply can't load the application, resulting in an ugly and not very debugger friendly error.

Anybody have an idea about what happend here?

Many thanks to all!

**Comment by Narretz** [comment]
It's quite obviously a huge bug in Edge. Looks like Microsoft still can't handle placeholder attributes correctly. Black magic, that stuff. Please report this bug with Microsoft. You can even do it with a tweet now: https://blogs.windows.com/msedgedev/2016/08/11/edgebug-twitter/

**Comment by dec** [comment]
I alrady report it to the Edge team. Thanks for your reply @Narretz!

**Comment by dec** [comment]
Hello!

On the other hand, I am not convinced this error is "obviously a huge bug in Edge" @Narretz. Note that the browser doesn't crash if we use a Range input in a simple HTML document, even if we use the "placeholder" attribute.

What I say is the problem occur (at least) in an AngularJS application...

**Comment by Narretz** [comment]
@dec Angular doesn't do something magical when interpolating inside an attribute. It's actually pretty-straightforward. It sets the attribute to the value: http://plnkr.co/edit/eEDEPw3Gp1P8m8Qmy3IG?p=preview No browser should crash the site / tab when something simple like this happens. This is simply a huge bug.

**Comment by dec** [comment]
@Narretz Yes, you have reason, but the point is the Range fail occur in an AngularJS app and not in a plain HTML document... therefore, probably the bug is in Edge, I don't doubt that, but at least you must to recognize they are related with AngularJS, since the bug occur in an AngularJS app and not in a simple HTML document.

Anyway is not my job to defend here to the Edge developers and their "huge bugs"...

**Comment by Narretz** [comment]
@dec The point is the following. Angular doesn't do anything "wrong" here, it's not an error in the internal logic of the framework or anything. In the linked plnkr you can see that the bug can be caused very easily by just setting the placeholder attribute via Javascript. I know that we could try to work around this in Angular by special casing placeholder + Edge + input range, but this is something that should really be fixed by the browser vendor because it can theoretically affect any JS code that sets attributes programatically.

And it's a "huge" bug, because the simple setting of an attribute crashes the whole page / tab.

**Comment by dec** [comment]
@Narretz Sorry, I missunderstand you before. Now I can understand perfectly: you say the problem appear in any kind of Javascript app, so there is not something related with AngularJS at all. I simply ignore this important point @Narretz.

Thanks very much for your explaination and sorry for waste your time!
