### ISSUE TITLE
angular-sanitize does not expose the encodeEntities function

### ISSUE THREAD

**Issue by mirabilos** [angular/angular.js#15061]
When including angular-sanitize via the bower webjar (webjars.org), the encodeEntities function is not available to the application AFAICT. Please export it, so we don’t have to duplicate it in our code. (The code we duplicate actually has a one-line patch —

    @@ …
      function encodeEntities(value) {
    - return value.
    + return ("" + value).
      replace(/&/g, '&amp;').

— against the original repository, so it can be used with almost any values passed.)

**Comment by Narretz** [comment]
The encodeEntities function is not public, that's right. We are usually very conservative when making helper functions public, as this often results in feature requests for these functions etc. which we don't need for core. So I would suggest you either copy it or use a dedidcated library: https://github.com/mathiasbynens/he

**Comment by mirabilos** [comment]
OK, the dedicated library *seems* to be usable with https://github.com/mathiasbynens/he/pull/49 being taken into consideration. It’s a bit annoying to have this kind of code duplication, but, oh well…
