### ISSUE TITLE
Unexpected token N in JSON at position 0 at Object.parse (native)

### ISSUE THREAD

**Issue by Gowrisankar23** [angular/angular.js#15062]
- In $http response, i got plain text while content-type="application\json". It throw error message in console  that 

> Unexpected token N in JSON at position 0 at Object.parse (native)

in angular.js file.

 How can i rectify this problem without touching the server code?

**Comment by Narretz** [comment]
If the error is Unexpected token N in JSON at position 0 at Object.parse (native), that doesn't sound like the response is empty. That said:

Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

**Comment by gkalpak** [comment]
You could probably work around this by using an interceptor. But ckaiming to have sent different type of content than what you have actually sent, **is** a server problem. It is much better to address this on the server-side.

In any case, this is a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
