### ISSUE TITLE
Angular 2.0.0-rc5: Changing a chained pipe's parameters doesn't invoke pipes down-chain

### ISSUE THREAD

**Issue by haemaenpaa** [angular/angular.js#15066]
**Do you want to request a *feature* or report a *bug*?**: Bug

**What is the current behavior?**

I am attempting to sort the array `users` and split it into pages of 20.

I have the following template

   ```
<table class="table50">
  <thead class="table_header">
    <tr>     ...
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let theUser of users | sort: [ sortField, sortAscending ] | paginate: [ pageNumber-1, pageSize ] ">
      <td>{{theUser.id}}</td>
      ...
    </tr>
  </tbody>
</table>
<form *ngIf ="users && users.length>pageSize">
  <input type="number" min="1" max="{{numPages()}}" [(ngModel)]="pageNumber" name="pg">/{{numPages()}}
</form>
```

I use `(click)` to bind clicks on the table header to change `sortField` and/or `sortAscending`, and call `detectChanges()` on an injected `ChangeDetectorRef`. I added a few calls to `console.log` into the two pipes' `transform`  functions, and I noticed that when I click on the header, only the `sort` pipe gets called, and when I change the `pageNumber`, only the `paginate` pipe gets called.

`sort` is a quicksort, `paginate` outputs the `pageNumber`-th block of `pageSize` objects in the input array.

**What is the expected behavior?**

Changing the parameters of `sort` should also cause `paginate` to be run.

**What is the motivation / use case for changing the behavior?**

Currently, changing the parameters of a pipe in the middle of a chain does not change the output seen by the user. I find this counterintuitive, and it is currently forcing me to either write a separate pipe class for any chain of pipes with user-changeable parameters in the middle of the chain.

**Which versions of Angular, and which browser / OS are affected by this issue?**

Angular version 2.0.0-rc5
OS: Windows 7 Enterprise Service Pack 1
Browser: Firefox 45.3.0

**Comment by haemaenpaa** [comment]
I attempted to work around this by setting `pageNumber` to 1, but even that failed if already on page 1. I ended up having to increment the value, call `detectChanges` and then set it to 1 and call `detectChanges` again to make it work.

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular2. Please open an issue here: https://github.com/angular/angular/issues
