### ISSUE TITLE
angular-parse-ext is not distributed on bower

### ISSUE THREAD

**Issue by miles-billsman** [angular/angular.js#15067]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Running `bower install angular-parse-ext` as described [here](https://github.com/angular/bower-angular-parse-ext) exits with "bower ENOTFOUND Package angular-parse-ext not found".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

1. Search for "angular-parse-ext" [here](https://bower.io/search/)
2. Or run `bower install angular-parse-ext`

**What is the expected behavior?**

Bower would install "angular-parse-ext" and update bower.json.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.9

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Thanks for reporting. It should work now.
