### ISSUE TITLE
Width of HTML body changes when ng-view includes multiple rows in Bootstrap container

### ISSUE THREAD

**Issue by TaungTechnologies** [angular/angular.js#15069]
I used the Yeoman angular-generator to create an AngularJS app with Bootstrap.

When I use more than a certain number of Bootstrap rows in a partial view, the HTML body width suddenly gets smaller and throws out the alignment. It shrinks by 15px, from 1224px to 1029px.

I have been able to recreate the problem by generating an app from scratch as follows:

mkdir mytodo && cd $_
yo angular
? Would you like to use Gulp (experimental) instead of Grunt? No
? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-resource.js, angular-route.js

If I replace the HTML in 'about.html' with 26 Bootstrap rows, the HTML body width is 1224px, as expected. Here are my 26 rows:

![selection_020](https://cloud.githubusercontent.com/assets/14817464/18101796/5ec9afd6-6ef0-11e6-8ea0-e2cd7f30781c.png)

And here is the body width of 1224px:

![selection_019](https://cloud.githubusercontent.com/assets/14817464/18101770/4e058da0-6ef0-11e6-8eae-e535cc0cbf68.png)

But if I add just ONE more row, the body width decreases to 1209px. Here are my 27 rows:

![selection_022](https://cloud.githubusercontent.com/assets/14817464/18101913/de6dd618-6ef0-11e6-9450-94a8797f38d0.png)

And here is the body, less 15px: 

![selection_021](https://cloud.githubusercontent.com/assets/14817464/18101935/fa9b0a18-6ef0-11e6-97c5-3ab70f93375e.png)

The problem also happens with fewer rows if the rows contain more detail. Here I stripped the problem down to the bare bones in the hope that someone can reproduce it as well and guide me to a solution.

Note that 'main.css' and all other code is exactly as generated by Yeoman, except for 'about.html'.

The various relevant versions are: node v6.4.0; npm 3.10.6; yo 1.8.4; bower 1.7.9; grunt-cli v1.2.0; grunt v0.4.5; Bootstrap v3.3.7; AngularJS v1.5.8

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).
