### ISSUE TITLE
Promises across scope don't maintain expected ordering

### ISSUE THREAD

**Issue by jgraham** [angular/angular.js#15078]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Code like

    $q.resolve()
       .then(someOtherFactory.functionReturningPromise())
       .then(somethingElse)

runs `somethingElse` before any actually asynchronous parts of `functionReturningPromise()`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

https://jsfiddle.net/g4218b7m/3/

**What is the expected behavior?**

The promises are resolved in order.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Fails in at least 1.5.8.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by jbedard** [comment]
I think you're passing a promise instead of function to `.then`  with `.then(promiseFactory.get())`. Updating it to `.then(() => promiseFactory.get())` seems to fix it... https://jsfiddle.net/g4218b7m/5/

**Comment by lgalfaso** [comment]
@jbedard is spot on.
