### ISSUE TITLE
Tutorial docs on website are broken since May

### ISSUE THREAD

**Issue by antgel** [angular/angular.js#15076]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Since c2033d7ff04ed5507ee5911a98eb2b2adf7f2092, the [tutorial on the website](https://code.angularjs.org/1.5.1/docs/tutorial) isn't in sync with the tutorial ngdoc code in `docs/content/tutorial`.

Even as early as the [second step](https://code.angularjs.org/1.5.1/docs/tutorial/step_02), there are noticeable differences e.g.:
```
<script src="js/controllers.js"></script>
```
```
<script src="app.js"></script>
```
```
<body ng-controller="PhoneListCtrl">
```
```
<body ng-controller="PhoneListController">
```

Etc...

**What is the expected behavior?**
That the website tutorial will be synchronized with the documentation in git.

**What is the motivation / use case for changing the behavior?**
Users trying to follow the tutorial become frustrated because code and filenames are different. (I also didn't succeed in generating the docs locally, but that's another matter, I'm also new to npm and friends...)

**Comment by Narretz** [comment]
I just checked with 1.5.8 and both files are semantically in sync. For a few versions that wasn't the case, but it should be now.

**Comment by antgel** [comment]
Sorry, I don't know how I explictly got to the 1.5.1 docs (from there I obviously couldn't see newer versions in the dropdown). When I go to the main site, then click Learn -> Tutorial, it's all good.
