### ISSUE TITLE
Let resolveAs accept empty string in order to map properties directly

### ISSUE THREAD

**Issue by fmunafokion** [angular/angular.js#15097]
Why not allow such a thing?

``` html
    .when('/home', {
        templateUrl : 'views/home.html',
        resolveAs : '',
        resolve: {
            data: ['myService', function (myService) {
                return myService.getHomeData();
            }]
        }
    })
```

``` html
<p>Hi, here we are with the home data: {{data}}</p>
```

Thanks,
Filippo

**Comment by Narretz** [comment]
Possible, but then we would pollute the scope quite a lot. And I don't know if such a feature is really that useful for many people.

**Comment by fmunafokion** [comment]
Hi,
I've implemented the feature changing ngView.js (taken from master branch), method ngViewFillContentFactory.

Simply change:

`
scope[current.resolveAs || '$resolve'] = locals;
`

with:

```
if (angular.isDefined(current.resolveAs) && !current.resolveAs) {
  angular.forEach(locals, function(value, key) {
    scope[key] = value;
  });
} else {
  scope[current.resolveAs || '$resolve'] = locals;
}
```

**Comment by fmunafokion** [comment]
Even simpler:

```
if (angular.isDefined(current.resolveAs) && !current.resolveAs) {
  angular.extend(scope, locals);
} else {
  scope[current.resolveAs || '$resolve'] = locals;
}
```

**Comment by gkalpak** [comment]
I too don't see any tangible benefit (other than saving a few keystrokes).

**Comment by fmunafokion** [comment]
Right, it's just about that: saving keystrokes, nothing more nothing less.
But let me say: few or many depends on project dimension.
Anyway, we are talking about adding only three line of code.

**Comment by gkalpak** [comment]
If you are so concerned about the keystrokes, you can use a one-letter alias. Then the total amount of extra keystrokes will be negligible compared to the total amount of keystrokes need for constructing the whole template.

It is not about the extra lines of code; it is more about complicating things for no benefit. Keeping things more "linear" keeps the mental overhead low and allows developers to allocate their "processing power" to more useful and creative tasks.

Even more so, if you embrace components and define each route template as a component, the overhead is really minimal, while the benefits (e.g. in terms of improved testability, reusability etc) are not.

**Comment by Narretz** [comment]
Closing since there's no tangible demand.
