### ISSUE TITLE
Angular Interceptor return status -1

### ISSUE THREAD

**Issue by PVAngular** [angular/angular.js#15090]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

status = -1 is unclear - can there be  statusText to know the root cause

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

I was able to reproduce this bug by redirecting a server call to a invalid proxy. 

**What is the expected behavior?**
More info in the statusText 

**What is the motivation / use case for changing the behavior?**

  Better  troubleshooting of errors reported by Angular Error Interceptor

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

All

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Does a regular http call return something different? The interceptor only returns what the server returns, so if there's only -1 to report then Angular can't do anything.

**Comment by gkalpak** [comment]
Interceptors get passed the whole `response` object (which includes `statusText`). If there is anything returned from the server, it should already be available there.

I am going to close since we didn't get any response from the OP. Feel free to respond below, if you have more info to add.
