### ISSUE TITLE
scope.apply not picking up updated value

### ISSUE THREAD

**Issue by waterplea** [angular/angular.js#15107]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
When we change input values outside angular scope, i.e. using vanilla js we need to run digest cycle, for example using $scope.$apply().

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
The value change does not get picked up in case of changing event.target.value of vanilla 'wheel' event handler as illustrated in this codepen:
http://codepen.io/waterplea/pen/GjJBgO

**What is the expected behavior?**
Change should get picked up after digest cycle

**What is the motivation / use case for changing the behavior?**
Tried to implement input type="number" changing using mouse wheel (native behavior in Chrome if input is focused, but not in Firefox and also it's handy not to have to focus input for that).

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
At least latest Chrome and Firefox, presumably all browsers. Angular version 1.5.8.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

--
Hint:
Things in Angular are model-driven. I.e. you change the model and the change propagates to the view - not the other way around. Look up [`NgModelController`][2] for useful pointers.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://docs.angularjs.org/api/ng/type/ngModel.NgModelController
