### ISSUE TITLE
ngOptions documentation change

### ISSUE THREAD

**Issue by austinoneil** [angular/angular.js#15116]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

documentation change

**What is the current behavior?**

On [ngOptions documentation](https://docs.angularjs.org/api/ng/directive/ngOptions), there is a link to ngOptions.  To me, it makes sense to remove that link and possibly link to the `ngRepeat` directive in the appropriate location.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

documentation change

**What is the expected behavior?**

documentation change

**What is the motivation / use case for changing the behavior?**

more sensible documentation

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

all browsers

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

Make appropriate changes around [here.](https://github.com/angular/angular.js/blob/c75698df55f5a026bcd7fcecbb9d4ff0bc3ebc3e/src/ng/directive/ngOptions.js#L20)

**Comment by gkalpak** [comment]
Sounds reasonable. (It is probably a leftover from when these docs used to live somewhere else - in the `select` docs maybe.)

In any case, feel free to go ahead and make a PR.

**Comment by Narretz** [comment]
Landed as 51c516e7d4f2d10b0aaa4487bd0b52772022207a
