### ISSUE TITLE
[feature request] ng-selected attribute for a <select> tag without using an embedded <option> tag

### ISSUE THREAD

**Issue by austinoneil** [angular/angular.js#15125]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

there is no `ng-selected`-type attribute for a `select` element using `ng-options`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

There will be an `ng-select`-like attribute for a `select` tag without the need to do an `<option ng-repeat="item in items">`-like construct within the `select` element.

**What is the motivation / use case for changing the behavior?**

This should reduce the size of users' code bases, in addition to increased performance as noted [here](https://docs.angularjs.org/api/ng/directive/select) under "Choosing between `ngRepeat` and `ngOptions`".

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

all versions, all browsers

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
I don't understand what you want, tbh. You are you saying you want ng-selected for ng-options. But with ng-options, you are using ng-model to set the selected value. Same with select + repeated options. You use ng-model to set the value.

**Comment by austinoneil** [comment]
I want to be able to do lines 17-19 [here](https://plnkr.co/edit/12tcSTgU2LdU698U9Ix0) in one select tag, as opposed to having to do an `<option>` tag within a `<select>` tag or having to set the selected item in the controller.

**Comment by gkalpak** [comment]
If we were to implement something like this, it had to go into the `ngOptions` DSL. And I think complicating the `ngOptions` DSL further is one step too far. The "Angular way" is to set the value in the model (not the view) anyway, so working around that will only bring confusion.

Note that if you insist on having that kind of logic in your HTML (something that I would strongly recommend against), you can use `ngInit`:

```html
<select
    ng-model="data.model"
    ng-options="o.id as o.name for o in data.availableOptions"
    ng-init="data.model = data.availableOptions[2].id"
</select>
```

Closing as `won't fix`.
