### ISSUE TITLE
# (hashtag) in templateUrl if ng-app is not in index.html

### ISSUE THREAD

**Issue by iamelru** [angular/angular.js#15124]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Its a bug, i guess. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
If we have 2 files in a root folder :
1) index.html (any html no scripts, or whatever)
2) index.php (or any other name/extension) [index.php.txt](https://github.com/angular/angular.js/files/467977/index.php.txt) is an angular app
and use hastag `#` in a directive's templateUrl.

**What is the current behavior?**

So. Directive's templateUrl:
if it starts with `'/#/...'`, index.php will load index.html as a template for this directive.
if it starts with `'#/...'`, index.php (or whatever.ext) will load itself as a template, and fall into recursion.
if there is no index.html at all (just index.php, in my case), it will also fall into recursion in both cases.

**What is the expected behavior?**
I would expect # to be a "shorthand" for the file itself, but not for index.html.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
It has nothing to do with browers/OS, but:
win10, 
chrome 53.0.2785.101 m (64-bit),
canary 55.0.2858.0 canary (64-bit), 
firefox 48.0.2

snapshot version acts the same way

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Just dont use `#` in there, it really helps :)

It has nothing to do with non-angular libs, or file extensions, or app.js, etc.

Sorry if you know about that already, but i could not find anything over the net. Also, its not that easy to catch since there is no errors in a browser console. 
Plus, maybe someone else will find this post helpful.

**Comment by Narretz** [comment]
You are correct that this is not an Angular specific issue. # denotes a specific part of an HTML document, but is often also used for client side routing. Your templates will always be in  full server paths, not as part of the page (and when loading templates via templateUrl, the angular client side routing obviously does not apply).
