### ISSUE TITLE
Dynamic headers in ngResource

### ISSUE THREAD

**Issue by rohdef** [angular/angular.js#15122]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When using $resource to define actions I can perfectly fine do something like:

    $resource.(..., {
        myAction: {
            headers: {"my-header": "foo"}
        }
    }

to set the header

**What is the expected behavior?**
However, headers are far from always static, that assumption is IMO plain wrong. What I would expect is to be able to do something along the lines of:

    var myHeaders = function() {...};
    $resource.(..., {
        myAction: {
            headers: {"my-header": myHeaders}
        }
    }

which would allow me to dynamically calculate my headers.  Noteworthy suggestion is furthermore this: https://github.com/angular/angular.js/issues/7324 which would be immensely useful too. But does not fully cover the usecases.

**What is the motivation / use case for changing the behavior?**
 Even basic headers such as the "Accept" header can be dynamic in nature, for instance an image service could convert images under certain conditions giving a list of possible formats as part of the API or more commonly as part of authentication setups.  

For instance in my setup I'd like to pass on a user name and authentication token as part of the headers when a user is logged on. The setup I have I'd like to be agnostic of the storage such that it could be cookie, local variable, web storage etc., thus I'd like something along the lines of:

    var myHeaders = function() {
        return $cookies.get("myuser") + ":" + $cookies.get("token");
    };
    $resource.(..., {
        myAction: {
            headers: {"Authentication": myHeaders}
        }
    }

(Ps. as a side note, there's a no documentation for headers on https://docs.angularjs.org/api/ngResource/service/$resource )

**Comment by gkalpak** [comment]
What you request is already implemented.

As mentioned on the `$resource` docs, the ADO (Action Definition Object - I just made up another `*DO` acronym :fireworks:) can contain any property that the `$http` request config accepts That is why `headers` is not documented on `$resource` - it is already documented on `$http`.

You can find more details on the `$http` request config object (and `headers`) [here][1].

[1]: https://docs.angularjs.org/api/ng/service/$http#usage
