### ISSUE TITLE
<p> tag  will not work with <ul>

### ISSUE THREAD

**Issue by tmleeek** [angular/angular.js#15139]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

this template will not work 

`
<p>
  {{ mytitle }}
</p>

<p>
the unordered list is inside html template
  <ul><li>item 1</li></ul>
</p>

`
while this will work

`
<p>
  {{ mytitle }}
</p>

<p>pargraph out</p>

  <ul><li>item 1</li></ul>

`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

only try the template with <ul> inside <p>

**What is the expected behavior?**
loading 

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

chrome / osx

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Not an Angular issue, please see http://stackoverflow.com/questions/10601345/ul-element-can-never-be-a-child-of-p-element

**Comment by tmleeek** [comment]
you should at least fire an error with that so the person know what the problem exactly

**Comment by Narretz** [comment]
We don't parse the html, so we cannot throw an error here. This is core HTML behavior, the browser / HTML engine parses the DOM, and decides what it allows / changes.

**Comment by tmleeek** [comment]
and how the developer figure it out? the hard way  ? this isnt right , you should do something about that , this effect the language itself , i haven't thought a simple bug like this will drive me crazy and will make my app not working , what if was very deep in code !! THIS IS TOTALLY WRONG .

and congratulation for releasing final version today , but really funny bug like this will make it really regretful for developers to spend time in this in the future

**Comment by Narretz** [comment]
> and how the developer figure it out? the hard way ? 

Yes, the hard way, like you did. Do you realize that behavior affects lots of frameworks, e.g. jQuery and also vanilla Javascript? This is something every front end developer will learn some day: certain eelements cannot be children of text only elements.

You are right that an error message would be nice, but as I explained, Angular doesn't parse or statically analyze your templates, so it cannot throw an error. Maybe Angular2 can, afaik it has an HTML parser.

Also, don't call it a bug. It's not a bug in Angular. You should direct your anger at the DOM spec.

**Comment by tmleeek** [comment]
that's crucial , trust me , all this work on moving to typescript , should at least make it lot easier for developers to figure out that from angular itself , otherwise it will get dropped from developer interest with time for more safe and clear languages .

**Comment by gkalpak** [comment]
> that's crucial , trust me , all this work on moving to typescript , should at least make it lot easier for developers to figure out that from angular itself , otherwise it will get dropped from developer interest with time for more safe and clear languages .

As explained by @Narretz (several times :smiley:) the browser parses the HTML **before** Angular1's `$compile`r has a chance to parse it. All Angular1 sees is the tranformed HTML (with the `<p>` tag moved out of `<ul>`). So there is no way for Angular1 to know that the developer wanted to put the `<p>` inside the `<ul>`.

Angular2 has already addressed this. Ithas a built-in HTML parser and appropriate schemas, so it will warn you with very informative errors (including the exact position in the template) about issues like this.

**Comment by tmleeek** [comment]
i have this problem in angularjs 2 app , the problem that the angularjs 2
app will simply not work and will keep to be at loading screen , and only
for just html error , you know what i mean ?

you compile the html app without errors , you should tell the developer he
have problem in his html syntax like forbidden html or so , but keeping it
like this UKNOWN after hard work of development just because we break html
LAW ?

you should tell the developer that he have problem in his html syntax

On Fri, Sep 16, 2016 at 6:21 PM, Georgios Kalpakas <notifications@github.com

**Comment by gkalpak** [comment]
This repository is for Angular 1. The Angular 2 repo is [here][1].

[1]: https://github.com/angular/angular
