### ISSUE TITLE
Angular app problem in  when click browser back button ( browser history)

### ISSUE THREAD

**Issue by sandeepksrana** [angular/angular.js#15134]
Hi 
Can anyone tell me that how to solve the browser back button issue.

problem is that  im using **html5mode** and when i go from one page to another page its working but when going back through browser back button there is no data in scope and its print that angular code on page.

**Example**  going from home ( **/** ) to location  (**/location**), there are list of location in the location page and on clicking on a single location it open (**/location/1/usa**) all this is working fine, but when click back button on the browser it goes to **/location** url but problem is no data in that particular page but that having angular code.

there are 3 controller  **homeController** , **locationController** , **singleLocationController/:id/:locationname**  these above 3 urls

anyone can help, how to solve it and why it happen..

Thanks in Advance

**Comment by Narretz** [comment]
Hi, thanks for the report. Can you please put a demo of the problem in a https://plnkr.co or similar? That makes it much easier to assess the problem.

**Comment by Narretz** [comment]
Hi, thanks for the report. Can you please put a demo of the problem in a https://plnkr.co or similar? That makes it much easier to assess the problem.
