### ISSUE TITLE
$interpolate 'allOrNothing' ignores empty case

### ISSUE THREAD

**Issue by amitport** [angular/angular.js#15133]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`$interpolate` service when running with `allOrNothing`, does not pass the value if there's nothing to interpolate (this affects ngAtrr*, which does not write the corresponding attribute when it has a simple value)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://plnkr.co/edit/1QhnA9xb5BgyzWHpeL7O?p=preview

**What is the expected behavior?**
should see the poster image on video... 

**What is the motivation / use case for changing the behavior?**
Although there is no real need for using ngAttr/ngSrc/ngHref without interpolation, it's sometimes useful to do so when exploring initial html template or learning angular. Having to use `ng-attr-*="{{'value'}}"` instead of `ng-attr-*="value"` is not intuitive.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
angular 1.5.8
win 7
chrome 53, IE 11, firefox 47

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
following https://github.com/angular/angular.js/issues/15130#issuecomment-246769914

**Comment by Narretz** [comment]
I think this is a valid problem, and it would be good to align this with normal attribute handling (which allows static values for obvious reasons).

**Comment by gkalpak** [comment]
I don't think this has anything to do with `allOrNothing`. It is because whae there is no interpolation symbol, then `$interpolate` returns `undefined`, which cause the internal interpolate directive to bail out early (without setting the attribute value). It makes sense in most cases, because the attribute is already set, but in the case of `ngAttr` we need to explicitly set the corresponding attribute.

**Comment by gkalpak** [comment]
I submitted a possible fix in #15149.
