### ISSUE TITLE
Adding a new locale

### ISSUE THREAD

**Issue by thauk-copperleaf** [angular/angular.js#15147]
Let's say I was wanting to use an (existing) English (ISO) locale for testing problematic strings. Let's say I decided that I wanted to use EN-GS (representing South Georgia and the South Sandwich Islands) for this purpose. EN-GS is not yet in the [locale list](https://github.com/angular/angular.js/tree/master/src/ngLocale) for Angular. Would it be sufficient to make a copy of `angular-locale_en-gb.js` as `angular-locale_en-gs.js` (and change line 140 to `"localeID": "en_GS",`)?

Would that be then acceptable to put into a PR?

**Comment by Narretz** [comment]
Our locales come from the Google Closure library which uses the CLDR data. Any new locale must be added / exported from there

**Comment by thauk-copperleaf** [comment]
Thanks for the response! I opened a ticket with CLDR.
