### ISSUE TITLE
Dynamic routes registration

### ISSUE THREAD

**Issue by stej** [angular/angular.js#1515]
Hi, this feature request is based on my question on StackOverflow (http://stackoverflow.com/questions/13153121 ). 

It would be great to add routes not only in config phase, but also later, e.g. after login. The use case: user logs in, after that it is clear (based on his account or his ordered services) what routes should be registered, not earlier. 
The same also holds for registering controllers, because controllers are used during routes registration. Anyway, it is possible in angular right now (via e.g. requirejs).

Thanks for angular a lot :)

**Comment by ignaciohita** [comment]
+1
No solution for this almost one year after last comment?

**Comment by selvaa89** [comment]
+1

**Comment by csbenjamin** [comment]
+1

**Comment by kavi87** [comment]
+1

**Comment by konstardiy** [comment]
Actually i see only this approach as a solution:
define an "login-only" app that will estabilish the security context (ask user how (s)he would like to sign-in, than after answer is availalble, remove or hidemarkup of this "preloader" app and then bootstrap one in another element that will be loaded and shown as main app.
like so:
     <body class="guest-mode">
          <div ng-app="app.loginUI" id="login_ui" class="login-ui>
                 login app shown here
          </div>
          <div  id="main_ui" class="main-ui">
                Main app shown here after explicit angualar.bootstrap(mainUI, 'app.main')
          </div>
     </body>

But what if user signed out? How you will unload all controllers and services?
So better approach is to use 2 different SPAs - one for sign-in, sign-up, forgot-password, and reset-password forms, among with other public content, and other SPA that is strictly protected with classic cookie auth where all real App content will live in secured environment.

**Comment by Narretz** [comment]
This feature is too complex to be included into AngularJS.

But it is possible in the de-facto module for complex routing, AngularJS UI Router: https://ui-router.github.io/ng1/docs/latest/index.html

One note, from a security viewpoint, it's not a big difference if you register the routes right away or only after the user has been logged in. The code for registering the routes is still on the client, so by inspecting the code, you could find it, and route access should be checked anyway based on the users authorization status.
