### ISSUE TITLE
how to config $routerConfig via $http response in angular 1.5 new conponent router?

### ISSUE THREAD

**Issue by shengxinjing** [angular/angular.js#15167]
how to config $routerConfig via $http response in angular 1.5 new conponent router?
I want to dynamic set router

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
