### ISSUE TITLE
Possible bug in Google Chrome: invisible content that is actually in the dom.

### ISSUE THREAD

**Issue by mcblum** [angular/angular.js#15177]
**Overview of the Issue**
We have an app built with Angular 1.5 components and when the page loads in Chrome, half of the page (in this example everything below Bill Clinton) is invisible. 

**What is the current behavior?**
The content is actually there, but not showing up. 

**Link to an example page**
http://stage.nationalmachine.co/case-study/severs-fall-festival

**What is the expected behavior?**
The content would show up on first load. 

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
If I turn on the cache killer plugin, it never happens again, nor does it happen in Safari or Firefox.  You may have to load it a couple times so the content can be cached before you start to see the behavior. If you can get it to happen where the text and images disappear, you can scroll to the bottom completely or resize the browser in order to get them to come back.

Also, if it ends up that it was just something stupid that I did, I'm really sorry. I would only post here if I felt that there was really a decent chance it was an actual bug.

**Comment by Narretz** [comment]
I cannot reproduce this issue in Chrome Version 53.0.2785.116 m. There recently was a bug regarding to cached http responses that has been fixed https://bugs.chromium.org/p/chromium/issues/detail?id=633696. Can you test with a version mentioned in the issue? Or verify that you already use one of these?

**Comment by mcblum** [comment]
Hey @Narretz! Thanks for responding. We have three different machines all running 53.0.2785.116 that are seeing the error. I downloaded the most recent version of Chrome Canary and experienced the issue as well. It was actually more prevalent in Chrome Canary -- it seemed to happen every single time.

Here's a screen of what the page looks like with missing content. Are you saying that with no type of cache killing on you're able to see all of the content below Bill Clinton?

![screen shot 2016-09-23 at 8 58 57 am](https://cloud.githubusercontent.com/assets/1761867/18788438/76abe4e6-816c-11e6-8e6b-66d4e25b4d37.png)

**Comment by mcblum** [comment]
Shoot. Please close this issue. It's not Chrome, it's something unrelated. My fault people!

**Comment by Narretz** [comment]
NP. (You can also close your own issues, if I'm not mistaken.)

**Comment by mcblum** [comment]
@Narretz I looked and couldn't see how! Will get it right next time.
=
