### ISSUE TITLE
ng-show/ng-hide is not updating DOM. It updates on next digest cycle.

### ISSUE THREAD

**Issue by anubhavjain04** [angular/angular.js#15179]
Please go through below link which explains use case. Due to this, my application got a big regression.

http://www.bennadel.com/blog/2853-ngshow-nghide-classes-get-applied-in-the-postdigest-phase-in-angularjs-1-3.htm

Can you please give a workaround to fix this?
Waiting for your reply...

**Comment by Narretz** [comment]
Without knowing what your use case is, we cannot begin to think of a workaround.

**Comment by gkalpak** [comment]
Also, please make sure this is not covered in the [1.2 -> 1.3 migration guide][1].
<sub>(For example the note about 1bebe36 might be relevant - just guessing.)</sub>

[1]: https://docs.angularjs.org/guide/migration#migrating-from-1-2-to-1-3

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
