### ISSUE TITLE
Angular's ngKeyup is giving KeyCode as 0 for all keys on iPad

### ISSUE THREAD

**Issue by jkb016** [angular/angular.js#15188]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Angular's ngKeyup is giving KeyCode as 0 for all keys on iPad

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
On ipad if you use ngKeyup , it always gives $event.keyCode = 0 .

You can test angular's demo code https://docs.angularjs.org/api/ng/directive/ngKeyup and it shows keycode as 0.

I can reproduce issue on ipad mini 2 on browserstack.com .

ngKeydown gives proper keyCode value. Is ngKeyup supported on ipad ? Is there any way to use ngKeyup with keyCode on ipad ?

Stackoverflow issue : http://stackoverflow.com/questions/38837816/angulars-ngkeyup-is-giving-keycode-as-0-for-all-keys-on-ipad

**Comment by gkalpak** [comment]
This doesn't sound as an Angular issue. `ngKeyup` should just listen to and forward the native `keyup` event. How does a native `keyup` listener behave?

**Comment by jkb016** [comment]
@gkalpak 
Yes, you are correct. Seems to be a problem with some older versions of ipad only.  I will close bug.
Thankyou.
