### ISSUE TITLE
Dear All 

### ISSUE THREAD

**Issue by brijesh1ec** [angular/angular.js#15191]
Hi,

How to give horizontal bar for wider dropdown option,

tried overflow-x:auto, but it doesn't works.

**Comment by kibertoad** [comment]
You do realize what is the difference between issue tracker and forum, right :)?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

**Comment by brijesh1ec** [comment]
I have tried with blur admin, but it didn't work, i understand the support issue vs Portal(application) bugs. here i raised this point  because i tried same for blur admin.
