### ISSUE TITLE
Issue in multi select dropdown when switching from AngularJS v1.2.26 to AngularJS v1.4.5 in IE 11

### ISSUE THREAD

**Issue by sanchigirotra10** [angular/angular.js#15190]
![image](https://cloud.githubusercontent.com/assets/3404429/18872668/40f8e9e6-84d9-11e6-898c-a84b8046826f.png)
I am using HTML **select** element with **multiple** attribute and angular **ng-model** binding with options using **ng-options**. Refer below code :
```
<input type="text" ng-model="selectedValue" />
    <select ng-model="selectedList"
						ng-options="obj.value for obj in myObj|filter:selectedValue|orderBy:'id' track by obj.id"
					multiple>
```
This is working perfectly in AngularJS v1.2.26(angular.min.js) in IE 11 but selects all in AngularJS v1.4.5 (angular.min.js) in IE 11. Please suggest how to fix this issue in upgraded version.

In our page, we are using 2 multi select list but this issue is with only one.

**Comment by Narretz** [comment]
You should test with the latest patch release, 1.4.12.

**Comment by sanchigirotra10** [comment]
After updating angular.min.js to v1.4.12, i am able to do first time selection but when it becomes **ng-touched** it get freezes with select all selection.  Please suggest.

**Comment by Narretz** [comment]
It looks like an issue that was fixed in 1.5.5. Please update to this version and test.

**Comment by sanchigirotra10** [comment]
Yes it worked perfectly after updgrading angular.min.js to v1.5.5.

Thanks You :+1:

**Comment by Narretz** [comment]
Great!
