### ISSUE TITLE
UI Mask is always $dirty=true(since initialization)

### ISSUE THREAD

**Issue by brijesh1ec** [angular/angular.js#15195]
Hi,

Don't if it is right portal to raise the question or not.

1) i am using ui-mask for phone number but $dirty is always true, if i click mouse inside textbox it triggers the validation message. but in other case if i type input into textbox and select it and clear(delete) it then only it triggers validation.

using ng-model-options{updateOn:'blur'} ,

i wrote directive i always get $dirty true when i click mouse inside textbox.
2) i am trying to achieve two validation one is phone number should not start from 0(first digit should't be zero). another it should be required.

**Comment by gkalpak** [comment]
This repo is for the core Angular 1 framework (which `uiMask` is not a part of). If this is a problem with `uiMask`, you should report it at [their repo][1].

[1]: https://github.com/angular-ui/bootstrap
