### ISSUE TITLE
Should not ng-repeat terminate when its parent is removed from DOM?

### ISSUE THREAD

**Issue by djfd** [angular/angular.js#15193]
**Actual Behavior**: 
 -  `What is the issue? *` When an outer element containing ng-repeat is removed from DOM ng-repeat still continues
 -  `What is the expected behavior?` It expected that it will terminate as it is not needed there anymore, while its backing array still can be in use by other application parts/components

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [here](http://codepen.io/djFD/pen/EgXoAE)
 -  `Details:` There is an array of two elements containing a sequence of two sequential numbers, it is updated every second, older element is removed and next ordinal one is inserted. These numbers are wrapped into dummy directive, used to just count its invocations. Also there is a button to remove container element. And  a counter of directive invocations. After removing container from DOM we still can see that directive is invoked every a second.

Need to say however that if we will equip a container element with ```ng-if``` then all works as expected. So what is the difference between ```ng-if``` and straight element removal? (I mean behavioral difference, not how the gears do work internally)

**Angular Versions**: *
 -  `Angular Version:`1.5.7 (also 1.5.8)

**Additional Information**:
 -  `Browser Type: *` Chromium, Firefox
 -  `Browser Version: *` 52.0.2743.116, 49.0
 -  `OS: *` Ubuntu 16.04 (64-bit)
 -  `Stack Traces:` --

**Comment by gkalpak** [comment]
The reason why this happens, is that `ngRepeat` will set up a watcher on its containing scope (the scope that contains the `ngRepeat`). When you "manually" remove parts of the DOM you are responsible for destroying any unnecessary scopes/watchers.

`ngIf` (and all built-in structural directives, such as `ngSwitch`, `ngView`, `ngInclude` etc) take care of that automatically.

--
So, unless you have very specific requirements (in which case you have to take care of cleaning up yourself), you should use one of the built-in structural directives.

**Comment by djfd** [comment]
@gkalpak , like as I said before, I understand how the gears do work internally.

IMHO, independently of removal method a directive have to stop.

now lets suppose that I have very specific requirements, and ready take care of its removal. How do I stop ng-repeat directive then? for me it is a kind of black box and I have not control of it at all...

**Comment by gkalpak** [comment]
Since `ngRepeat` (like other directives) creates its own scope bindings internally, there is no way to unbind from the outside. Therefore, the recommended way is to provide it a new scope to bind to, and then destroy that scope when you want to remove the directive. (That is also the reason why `ngIf` and similar directives create child scopes.)
