### ISSUE TITLE
How do I access Multidimensional Objects in Angular2 Reactive forms

### ISSUE THREAD

**Issue by deepikabhandari2592** [angular/angular.js#15192]
I had raised this question on stackoverflow.com but got no quick response.Hoping for quick  @ChrisRose @henrik 
file : cloud.ts
        
        export class Host {
            username: string;
            password: string;
            url: string;
        }
        
        export class PrimaryStorage {
            url: string;
            name: string;
        }
        
        
        export class Cluster {
            name: string;
            clusterType: ClusterType;
            hypervisor: Hypervisor;
            hosts: Host[];
            primaryStorages: PrimaryStorage[];
        
            }
        
file: form-model-driven.ts
        
        import {Component} from  '@angular/core'
        import {FormGroup, FormControl, Validators, FormBuilder} from '@angular/forms';
        import {Cluster,Host,PrimaryStorage} from './cloudspec';
        
        @Component({
            selector: 'formmodeldriven' ,
             templateUrl: `app/form-model-driven.html` 
              
        })
        export class FormModelComponent{
               
            model=new Cluster();   
            myForm : FormGroup ;
            
        constructor(){
            this.myForm=new FormGroup({
                clustername : new FormControl(' '),
                clusterType : new FormControl(' '),
                hypervisor : new FormControl(' '),
                hostname : new FormControl(' '),
                hostpwd : new FormControl(' '),
                hosturl : new FormControl(' '),
                psurl : new FormControl(' '),
                psname : new FormControl(' '),
                    
            });
            
        }
        
        }
        
        
file : form-model-driven.html
    
    <div class="container">      
        <h1>Cluster Form</h1>
        <form  [formGroup]="myForm" autocomplete="off"  novalidate >            
        <div class="form-field">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="clustername" required [(ngModel)]="model.clustername" formControlName="clustername">
        </div>
       <div class="form-field">
       <label for="type">Cluster Type</label>
       <input type="text"  class="form-control" id="clusterType" required [(ngModel)]="model.clusterType" formControlName="clusterType">
       </div>
       <div class="form-field">
       <label for="type">Hypervisor</label>
       <input type="text"  class="form-control" id="hypervisor" required [(ngModel)]="model.hypervisor" formControlName="hypervisor">
       </div>
       <div class="form-field">
       <label for="type">Host name</label>
       <input type="text"  class="form-control" id="hostname" required
             [(ngModel)]="model.hosts.hostname" formControlName="hostname">
       </div>
       <div class="form-field">
       <label for="type">Host password</label>
       <input type="text" class="form-control" id="hostpwd" required [(ngModel)]="model.hosts.hostpwd" formControlName="hostpwd">    
       </div>
       <div class="form-field">
       <label for="type">url</label>
       <input type="text" class="form-control"id="hosturl" required [(ngModel)]="model.hosts.hosturl" formControlName="hosturl">
       </div>          
       <div class="form-field">
       <label for="type">Primary Storage url</label>
       <input type="text" class="form-control"id="psurl" required [(ngModel)]="model.primaryStorages.psurl" formControlName="psurl">
       </div>          
       <div class="form-field">
       <label for="type">Primary Storage name</label>
       <input type="text" class="form-control"id="psname" required [(ngModel)]="model.primaryStorages.psname" formControlName="psname">
       </div>   
       <div class="debug">
       <h3> Name :{{model.clustername}}</h3>
       </div>
       <button type="submit" class="btn btn-default" >Submit</button>
       <button type="button" class="btn btn-default" (click)="newCluster()">New Cluster</button>
       </form>     
       </div>
    
I want to access username of host array in Angular Form    [(ngModel)]="model.hosts.hostname" ,but this seems to be an incorrect way of doing it. Do I need to create seperate forms for nested objects or Is there any other way of accessing it for two-way binding

**Comment by deepikabhandari2592** [comment]
@dmitriz :Can you please help me with this ? Its really urgent .

**Comment by gkalpak** [comment]
This repo is for Angular 1.x. The Angular 2.x repo is [there][1].

[1]: https://github.com/angular/angular

**Comment by deepikabhandari2592** [comment]
@gkalpak  : Can you share the link of repo again ? I missed it

**Comment by deepikabhandari2592** [comment]
@gkalpak :This repo is for angular2 .I'm using Angular2 reactive forms ..Your link does not answer my question !

**Comment by deepikabhandari2592** [comment]
@gkalpak : This repo is for angular2 .I'm using Angular2 reactive forms ..Your link does not answer my question !
