### ISSUE TITLE
How can I append key value pair to the url which already existed key value pair in AngularJS?

### ISSUE THREAD

**Issue by SIMHACHALAM1001** [angular/angular.js#15207]
I have a click functions.In 1st click function i add the key value pair for existing url like this 

   

 $scope.OnItemClick=function (bedroom) {

    $location.path("/builders/"+r.id).search({bedrooms:bedroom});

}

  

so in remaining functions.I want to add extra key value pair based on existing url 

  
  

      $scope.range=function (range) {
            $location.path("/builders/"+r.id).search({budget:range});
        }
        
        $scope.status=function (status) {
           $location.path("/builders/"+r.id).search({status:status});
       }

i tried to adding key value pair  but its over riding each other like this.

    1st click : ../#/builders/1?bedrooms=1
    2nd click :../#/builders/1?budget:5(overriding)
    3rd click :../#/builders/1?status:9(overriding)

so i want to do like this based on clicking functions:

    ../#/builders/1?budget=5&bedrooms=1&status=9
    ../#/builders/1?bedrooms=1&status=9&budget=5
    ../#/builders/1?bedrooms=1&budget=5&status=9

**Comment by gkalpak** [comment]
Passing an object to `.search()` will overwrite the existing query params. If you want to set the value for a specific param use the `.search(<key>, <value>)` form, e.g. `$location.search('budget', range)`.

--
That said, this is a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
