### ISSUE TITLE
canDeactivate executes while routing to routes guarded with canActivateChild 

### ISSUE THREAD

**Issue by niyazhussain** [angular/angular.js#15212]
Hi all the below is my route 

`export const ROUTES: Routes = [
  { path: '',  redirectTo:'signin' ,pathMatch: 'full' },
  { path: 'signin', component: SigninComponent ,canDeactivate: [AuthGuard] },
  { path: 'dashboard', 
    canActivateChild: [AuthGuard],
    component: DashboardComponent,
    children: [
      { path: 'category/:id', component: CategoryViewComponent },
      { path: 'category', component: CategoryListComponent },
      { path: '',redirectTo:'category', component: CategoryListComponent }
    ]
   }
];`

whenever i navigate to /dashboard the canDeactivate executes executes , it should not execute right ? because i am navigating to different route unrelated to signin

**Comment by gkalpak** [comment]
This repository is for Angular 1.x. The Angular 2 repo is [over there][1].

[1]: https://github.com/angular/angular
