### ISSUE TITLE
Angular.min.js file when referenced locally its not working, only CDN reference seems to be working.

### ISSUE THREAD

**Issue by ganumallya** [angular/angular.js#15211]
Below is my code.
and the min.js file that i have stored locally is nothing but copy paste of CDN link
and i see that if i refer to cdn directly it works, but when i save it in my local system and then reference to the local copy it doesnt work.
Please help

`<html ng-app>
  <head>
    <script src="/angular.min.js"></script>
  </head>
  <body>
    <div>
      <label>Name:</label>
      <input type="text" ng-model="yourName" placeholder="Enter a name here">
      <hr>
      <h1>Hello {{yourName}}!</h1>
    </div>
  </body>
</html>`

**Comment by gkalpak** [comment]
There is nothing special about the CDN. The file should work locally exaclty the same. This is probably some other configuration issue (e.g. wrong path, incorrect server configuration etc).

In any case, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
