### ISSUE TITLE
Feature Request: Ability to disable destruction of scopes between test specs

### ISSUE THREAD

**Issue by JustinTullgren** [angular/angular.js#15219]
**Do you want to request a *feature* or report a *bug*?**
Feature - Ability to disable destroying scope between tests. 

**What is the current behavior?**
Angular mocks invokes rootScope.$destroy after each test spec.

**What is the expected behavior?**
This is the correct behavior because it helps keep test specs clean by not allowing a previous scope to pollute the test spec context.

**What is the motivation / use case for changing the behavior?**
This behavior did not exist pre 1.5.  Since it did not exist, we have manually been calling destroy on our scopes, testing the destroy handler.  Since we were testing the destroy event manually and a full compile->destroy cycle was not occurring during each test spec and the scope was not being destroyed it was not necessary to always hydrate our mock dependencies with what was required for the destroy handler in the test suites.  Inevitably we didn't always reach 100% code coverage and we didn't always test the destroy handlers; and we also hydrated the mocks correctly in a child 'destroy' suite context vs the root suite context since we tested the destroy event manually. 

Now have a lot of undefined or not a constructor function errors because the destroy handler is called in a spec context that does not have the hydrated mock, either due to the mock being incomplete or the mock being set up for a destroy event in a child suite.

Therefore it would be nice to be able to disable the destruction of scopes between tests at a suite level. Eg in the root describe block in a spec file.  This will allow us to manageably fix the tests as we upgrade vs having to do them all in one go which takes a good portion of tech debt time.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular 1.5 
Angular Mocks 1.5
Phantom JS / Mac

This worked in the previous minor release of angular mocks: 1.4.7

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
[Related Issue](https://github.com/angular/angular.js/issues/14158)

**Comment by gkalpak** [comment]
TBH, I don't like the idea of making this configurable. I can't think of a good usecase :/

Wouldn't it be possible for you to either hydrate your mocks higher in the test suite hierarchy or mock `$rootScope`/`$rootScope.$destroy` in the suites that you don't want it called? Wouldn't that enable you to migrate your tests gradually?

**Comment by JustinTullgren** [comment]
@gkalpak We can mock `$rootScope.$destroy` as a noop. I understand the hesitation to add the feature for normal dev.  I was thinking of this as a way to help the upgrade process for large applications with lots of tests that may be impacted by this change.  

Thanks for the thought on mocking $destroy we'll do that.
