### ISSUE TITLE
The proper approach to generate components based on data

### ISSUE THREAD

**Issue by archasek** [angular/angular.js#15222]
Hi.

I have a structure in my project that is something like this :
![image](https://cloud.githubusercontent.com/assets/2247211/19081162/9737e1c4-8a59-11e6-92c9-8e97119382e8.png)

Footer and header are nested views.

`index.html`:
```
            <div data-ui-view="header"></div>
             <div data-ui-view="main"></div>
            <div data-ui-view="footer"></div>
```
routing:
```    $stateProvider
        .state('index', {
            abstract: true,
            views: {
                'header': {
                    component: 'headerComponent'
                },
                'footer': {
                    component: 'footerComponent'
                }
            }
        })

        .state('index.home', {
            url: '/',
            views: {
                'main@': {
                    templateUrl: 'boxesTemplate.html'
                }
            }
        });
```
The main section should include boxes (that are probably components?), as you can see at the screenshot. But the number of boxes and their content (like box heading) should be generated by data that is pulled from the backend using $http. I want to use component to communicate with API.
Can I achieve this somehow?

Thanks

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
