### ISSUE TITLE
invalid media range in documentation for accept header field

### ISSUE THREAD

**Issue by reschke** [angular/angular.js#15227]
See <https://github.com/angular/angular.js/blob/master/src/ng/http.js#L484>:

  *   - `Accept: application/json, text/plain, * / *`

Note that `* / *` is invalid, whitespace is not allowed here.

(Hopefully this only affects the documentation)

**Comment by gkalpak** [comment]
This does indeed only a docs issue. It is intentionally written like this, because writing `*/` is interpreted as ending the comment block (which makes the JS file unparsable). I couldn't find a way to fix it while still keeping it inside backticks (for formatting as code) 😞

**Comment by gkalpak** [comment]
OK, fixed with b3a3ed3 (ugly but seems to work).
