### ISSUE TITLE
ng-transclude adds span element with ng-scope class

### ISSUE THREAD

**Issue by stefanFruuu** [angular/angular.js#15223]
**_Note_: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a _feature_ or report a _bug_?**
report a bug

**What is the current behavior?**
ng-transclude adds empty span for "basic" transclusion (https://github.com/angular/angular.js/issues/1293 regression) and for multi-slot transclusion in case of using fallback content (introduced in 1.5.8 by https://github.com/angular/angular.js/commit/159a68ec7ba77e9128b0d0516b813ed3d223b6e3)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Basic transclusion:
https://plnkr.co/edit/YRqaDYsdRJUotYwgntqV 
![image](https://cloud.githubusercontent.com/assets/10087254/19153800/43d90208-8bd8-11e6-9802-96d676477346.png)

Multi-slot with fallback content in 1.5.8:
https://plnkr.co/edit/NiJOif6IEbZhWAhhNHZt 
![image](https://cloud.githubusercontent.com/assets/10087254/19155292/237958f4-8bde-11e6-915e-1c01dfe8a47a.png)

For comparison - same case as above in 1.5.7:
https://plnkr.co/edit/kQhXKe0qA4Kg5aZ4zLVQ, 
![image](https://cloud.githubusercontent.com/assets/10087254/19155401/a1cccdda-8bde-11e6-8c0e-2ae8a181d743.png)

**What is the expected behavior?**
In my opinion ng-transclude should not add additional span elements (no matter which mode is being used - "basic" or "multi-slot")

**What is the motivation / use case for changing the behavior?**
Additional span introduced in 1.5.8 by https://github.com/angular/angular.js/commit/159a68ec7ba77e9128b0d0516b813ed3d223b6e3 is breaking layout in our application.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular 1.5.7, 1.5.8 - "Basic" transclusion. I'm pretty sure it worked properly in 1.4.X (?)
Angular 1.5.8 - Multi-slot transclusion

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
https://github.com/angular/angular.js/issues/1293 - related issue

**Comment by petebacondarwin** [comment]
I don't think that we can fix this in 1.5.x since it would require a breaking change in the compiler. This is already solved in 1.6.x, which is nearing release. So I suggest that if you need this functionality you look to migrate to the newer version.
