### ISSUE TITLE
incorrect media type parameter for application/json

### ISSUE THREAD

**Issue by reschke** [angular/angular.js#15226]
<https://github.com/angular/angular.js/blob/master/src/ng/http.js#L4> - note that there is no charset parameter defined for "application/json" - see last sentence in <https://greenbytes.de/tech/webdav/rfc7159.html#ianacons>.

**Comment by gkalpak** [comment]
This was added intentionally in 10f80d7 to circumvent some issues with MongoLab. As per [this discussion][1] popular frameworks are not affected. Also, according to the linked spec:

> No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients.

So, "incorrect" is a strong word :smiley: It should not affect compliant recipients (which most popular frameworks seem to be) and fixes some issues on MongoLab. Sounds like a win-win :smiley:

So, we are going to keep the `charset` suffix (even if redundant in most cases).

Thx for taking the time to look into it and bring it up, though 👍 

[1]: https://groups.google.com/forum/#!topic/angular/1T6h7bfZ7Rs/discussion

**Comment by reschke** [comment]
Well -- is there a related bug open for MongoLab? It's bad to send pointless stuff just to make one broken server happy...

**Comment by gkalpak** [comment]
No idea. This is 4 year old code now.

**Comment by reschke** [comment]
Maybe it's not even needed anymore...
