### ISSUE TITLE
JQLite .attr('foo', null) sets foo to 'null' on IE9, FF, Chrome 

### ISSUE THREAD

**Issue by rjamet** [angular/angular.js#15242]
Bug: jqlite's .attr function with null value should remove the attribute (jquery does), but sets it at value 'null' on some browsers.

Repro: `angular.element('<div xyz="foo"></div>').attr('xyz', null)` should return `<div></div>`, but returns `<div class="null"></div>`.

Affected: IE 9, Firefox 49, latest Chrome
Not affected: IE 10 and 11

**Comment by gkalpak** [comment]
This has been fixed on master (with 4e36245), but I am afraid it would be a breaking change to backport to 1.5.x. (One can always use `.removeAttr()` for removing.)

Does anyone feel it should be fixed in 1.5.x as well?

**Comment by rjamet** [comment]
It doesn't inconvenience me, so I don't mind either way. Documenting the issue and fixing it in the next release seems fine.

**Comment by petebacondarwin** [comment]
We are close to releasing 1.6 now so I vote for not fixing this in 1.5

**Comment by mgol** [comment]
It's a breaking change so IMO it should wait for 1.6.

**Comment by mgol** [comment]
We've decided to wait for 1.6.0.

**Comment by mgol** [comment]
@rjamet there are other issues that I've recently fixed, see e.g. 3faf4505732758165083c9d21de71fa9b6983f4a & 7ceb5f6fcc43d35d1b66c3151ce6a71c60309304. They are described as breaking changes so people reading the migration guide will get that, do you think it should be also documented on the [angular.element](https://docs.angularjs.org/api/ng/function/angular.element) page? Currently we only have one-line descriptions there, basically saying what a particular jqLite's method doesn't support compared to jQuery or how it differs.

**Comment by rjamet** [comment]
I don't think this is worth updating the docs, since these differences are fairly obviously bugs and not intended behavior? Maybe a pointer to https://github.com/angular/angular.js/labels/component%3A%20jqLite would be enough instead. The simplicity of the jqlite doc is a good thing IMO :)

I'm working with Jqlite/Jquery ATM, hence why I rediscovered these independently, and I just didn't think of checking whether they were already fixed at head.
