### ISSUE TITLE
npm `latest` dist-tag is pointing to 1.2.32, not 1.5.8

### ISSUE THREAD

**Issue by christopherthielen** [angular/angular.js#15247]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`npm install angular` installs angular version 1.2.32

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

```
 npm install --save angular 
~/
└── angular@1.2.32
```

**What is the expected behavior?**

version 1.5.8 should be installed

**What is the motivation / use case for changing the behavior?**

N/A

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

N/A

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

An authorized owner of the `angular` npm package should run this command: 
```
 npm dist-tag add angular@1.5.8 latest
```

**Comment by gkalpak** [comment]
Thx for reporting! It should have been fixed a few minutes ago.
<sub>(It is kind of a "known (temporary) issue".)</sub>
