### ISSUE TITLE
Bower Angular Appears to only have v1.5.9?????

### ISSUE THREAD

**Issue by Mmatiasn** [angular/angular.js#15253]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Unable to download any angular version not being 1.5.9

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Go to the Bower Angular git
![image](https://cloud.githubusercontent.com/assets/12785825/19321605/b91d80e8-9083-11e6-9ab8-f3bdf87f38d7.png)

**What is the expected behavior?**
All versions should be available?

**What is the motivation / use case for changing the behavior?**
My project stopped working when it updated to the v1.5.9-build.5059+sha.4f44e01

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
My application works with the 1.5.8 version as I still have the development server hosting that file.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Mmatiasn** [comment]
https://github.com/angular/bower-angular-route#1.5.8

None of this appear to be available ??? I'm I missing something?

**Comment by gkalpak** [comment]
The tags are there, but apparently GitHub is only showing a limited number of tags. BTW, those `v1.5.9-build.XYZ` are not actually v1.5.9 - they are (sort of) nightly builds, built automatically from our CI (and will eventually become 1.6).

Anyway, if you want to access an older tag that is not shown in GitHub's dropdown, you can either checkout the repo (and tags) locally or use a URL in this format: `https://github.com/angular/bower-angular-route/tree/v1.5.8`

**Comment by Mmatiasn** [comment]
Why is bower getting the nightly builds?

**Comment by gkalpak** [comment]
Bower is getting angular from that repository. We add appropriate tags, so when doing `bower install angular` you will get the latest stable version. The nightlies are also available, but you won't get the nightlies unless you explicitly specify the tag name.

**Comment by Mmatiasn** [comment]
gkalpak, thank you for your response.

I know this isn't related to angular but I tried the following bower.json names to get the 1.5.8 angular version.

- "angular": "=1.5.8"
- "angular": "~1.5.8"
- "angular": "^1.5.8" 

![image](https://cloud.githubusercontent.com/assets/12785825/19349347/8ec040cc-9120-11e6-8e95-fbfb86142303.png)

I still get the nightly build version no matter which version I try to get.

**Comment by Mmatiasn** [comment]
I'm sorry I just looked in my ng-route dependencies and noticed it's set to 

```
  "dependencies": {
    "angular": "1.5.9-build.5059+sha.4f44e01"
  }
```

Should I report this as a bug in the ng-route git?

**Comment by gkalpak** [comment]
This is the `ngRoute` repo :smiley: But everything seems fine on the 1.5.8 version of `ngRoute`: [bower.json][1]
It must be something on your build/process. Try removing `bower_components/` and re-installing.

[1]: https://github.com/angular/bower-angular-route/blob/v1.5.8/bower.json
