### ISSUE TITLE
[1.5.9] NgModel set value undefined in input number with decimal

### ISSUE THREAD

**Issue by YokiToki** [angular/angular.js#15257]
No set undifined only for 0.1, 0.2, 0.4, 0.8, 0.16, 0.32....

In 4999 - 5060 bower-angular builds

https://plnkr.co/edit/CMvhwlRFNSMGVKN0RAVH?p=preview

![image](https://cloud.githubusercontent.com/assets/1845813/19338188/78b258e0-9145-11e6-932e-4066b9cac2df.png)

**Comment by gkalpak** [comment]
This is a valid bug. Thx @YokiToki 👍 

**Explanation:**

One of the validations rules we use for `[step]` is `<value> % <step> === 0`. But there are cases, where `(x * y) % x !== y` (e.g. `0.5 % 0.1 === 0.09999999999999998 !== 0`). In such cases, `ngModelController` considers the input value invalid (and sets the model value to undefined).

**Affected versions/controls:**

1. `v1.5.9` (to-be-released): It will affect `input[type="range"][ng-input-range]` elements on browsers that don't natively support range inputs.

2. `v1.6.0-rc.0` (to-be-released): It will affect `input[type="number"]` elements on all browsers and `input[type="range"]` elements on browsers that don't natively support range inputs.
