### ISSUE TITLE
Dropdown options not updating when I use "group by"

### ISSUE THREAD

**Issue by venkatrjv** [angular/angular.js#15250]
My code divide the number in even/odd groups in dropdownList.
but when I add new entry in data section , the dropdownList is not adjusting according to it.

**angular code:**

         angular.module("myModule", [])
            .controller("myController", function ($scope) {
                $scope.data =
                           [{ ID: '1', groupID: 'odd', disableID: true },
                            { ID: '2', groupID: 'even' },
                            { ID: '3', groupID: 'odd' },
                            { ID: '4', groupID: 'even', disableID: true },
                            { ID: '5', groupID: 'odd' }];
                $scope.change = function (d) {
                    if (Number(d.ID) % 2 == 0)
                        d.groupID = "even";
                    else
                        d.groupID = "odd";
                }
            });
**html:**

  ```
 <ul>
        <li ng-repeat="d in data">
            <input type="text" ng-model="d.ID" ng-keyup="change(d)" />
            <input type="text" ng-model="d.groupID" readonly="true" disabled="disabled" />
            <input type="checkbox" ng-model="d.disableID" />
            <input type="button" ng-click="data.splice($index,1)" value="X" />
        </li>
        <li>
            <input type="button" ng-click="data.push({ disableID : false})" value="add" />
        </li>
    </ul>
   <select ng-model="drop" ng-options="d.ID group by d.groupID disable when d.disableID for d in data track by d.ID">
       <option value="">select value</option>
   </select>

```
**What my result end up with..**
![screenshot 2016-10-12 16 00 14](https://cloud.githubusercontent.com/assets/22792695/19309992/98b44716-90a5-11e6-9ed0-dcf7f2b1b640.png)

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).
