### ISSUE TITLE
Is this possible to remove controller from memory dynamically.

### ISSUE THREAD

**Issue by rahulgupta20nov** [angular/angular.js#15262]
Hi,
In my project, I am using requirejs and angular-ui-router. If user change state then this state load respective css then controller then html. So I register controller dynamically. After going to other state, I need to remove this controller from memory. Is this possible for controller and module both?

**Comment by gkalpak** [comment]
No, there is currently no way to "unload" a module or a controller once loaded. (You should be able to overwrite the controller with an empty function, but it is undocumented and not guaranteed to work in the future.)

BTw, for general support question such as this one, it is preferrable to use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
