### ISSUE TITLE
Problem in linked plunker in ngSwitch Doc

### ISSUE THREAD

**Issue by sajan45** [angular/angular.js#15266]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The plunker is not working as expected, It is showing default div when select 'settings'. Refer this 
[StackOverflow Question](http://stackoverflow.com/questions/40043549/ng-switch-when-separator-not-working-in-angularjs#40043549)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
It's the plunker of ngSwitch documentation .

**What is the expected behavior?**
It should show settings div when settings is selected

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
I have checked in Chrome and Angular version is 1.5.8

**Comment by Narretz** [comment]
I've answered on SO: http://stackoverflow.com/a/40044632/787333. In a nutshell, there's a mismatch between the version of Angular that is running in the embedded doc example and the one that runs in the plnkr. I'll open a new issue for that.
