### ISSUE TITLE
[Documentation] Missing 'replace' property in directive and component comparison

### ISSUE THREAD

**Issue by aartek** [angular/angular.js#15261]
In [component guide](https://docs.angularjs.org/guide/component), in section "Comparison between Directive definition and Component definition", there is missing comparison for directive's `replace` property. I suggest to add it.

**Comment by gkalpak** [comment]
It was intentional, I think. The `replace` property has been deprecated for a while now and we recommend against using it. Putting it in the comparison table would seem like promoting its use with directives.
