### ISSUE TITLE
ngAnimate leave animation takes too long

### ISSUE THREAD

**Issue by kamilkp** [angular/angular.js#15273]
This is a bug report.

When removing elements from `ng-repeat` using ngAnimate the elements are not removed immediately after the animation is finished.

The expected behavior would be to remove them as soon as the transition ends.

In the example you can see that the filtered out elements reach target opacity but are removed after a couple of seconds.

Example: http://plnkr.co/edit/sKRc2Gm1uuOPDSxnoH5N?p=preview

**Comment by gkalpak** [comment]
I can't reproduce that. Could you make the example more clear maybe. AFAICT, the elements are removd after the animation finishes.

**Comment by kamilkp** [comment]
It is very very weird indeed. I tried different browser - worked fine. I also tried the same browser but a fresh instance (Chrome) and it also works fine. There might be a bug but it is inreproducable so I'm just gonna close this issue.
