### ISSUE TITLE
Search with Querystring params for composite keys

### ISSUE THREAD

**Issue by capesean** [angular/angular.js#15279]
I've posted this on [StackOverflow](http://stackoverflow.com/questions/39405452/ngresource-query-with-composite-key-parameter).

I have an entity with a composite key, say three fields `a`, `b` & `c`. Now say I want to query the API for all records with a value `x` for one of the fields, `a`. The url called is:
`www.mysite.com/api/entity/x`

If I query for all records with a value `y` for the `b` field, the url is:
`www.mysite.com/api/entity/y`

This is indistinguishable on the server from the previous url. It should call:
`www.mysite.com/api/entity?a=x`

If this has backward compatibility issues, then could we have a property on the resource, say `useQueryString`, which gets checked when constructing the url, and if it's set to true, then it uses querystring parameters and not the url when the `.query` method is called.

**Comment by gkalpak** [comment]
`$resource` is supposed to help you when interacting with RESTful data sources. The way you try to use it is outside the scope of REST, so I don't think `$resource` should support this.

As mentioned on StackOverflow, you can work around this by defining a different method (with a different URL) or overwriting the `query` method(if you don't need the params in its URL anyway).
