### ISSUE TITLE
Document that jqLite deprecations follow jQuery deprecation timeline

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#15282]
Normally, once a feature is deprecated it will stay in the codebase for one minor release and will be removed in the next minor release (in Angular 1, minor releases are breaking release).

As discussed in #15221, we have decided to treat deprecations in jqLite which are directly related to corresponding deprecations in jQuery differently. Namely, the deprecated feature should **not** be removed, until jQuery removes it too (deprecated features tend to stay longer in jQuery than in Angular).

This decision should be documented in our FAQ.

**Comment by mgol** [comment]
PR: #15819
