### ISSUE TITLE
docs: Things that need manual fixing in Changelog/Migration guide

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#15286]
A list of things that might need manual fixing in the 1.6.0-rc.0 changelog and the related migraton guide section:

* [x] 04cad41: It says `BREAKING CHANGE` (without trailing `:`). It will not be detected as a BC.
* [x] e8c2e11: It says `POSSIBLE BREAKING CHANGE`. Make sure it is detected as a BC.
* [x] 2456ab6: Forgot to add a BC notice (see https://github.com/angular/angular.js/pull/14309#issuecomment-228782948).
* [x] https://github.com/angular/angular.js/commit/1547c751aa48efe7dbefef701c3df5983b04aa2e#commitcomment-19034659: Is a BC, but as `refactor` won't show up.
* [x] input[range]: Add BC notice?
* [x] fc0c11d: Last line of examples is wrong. It should be `elem.data('foo-bar')`.
* [x] d882fde: Raw HTML (must be wrapped in ```` ```...``` ````).

**Comment by petebacondarwin** [comment]
See https://github.com/angular/angular.js/pull/15311
