### ISSUE TITLE
Confusing Type Coercion with ng-value

### ISSUE THREAD

**Issue by jongunter** [angular/angular.js#15283]
**What is the current behavior?**
When a model value is `null` or `undefined`, a radio button `<input>` with `ng-value="false"` won't be shown as checked.

When the model value is `""` or `0`, a radio button `<input>` with `ng-value="false"` **will** be shown as checked.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
http://plnkr.co/edit/oY0YipxdTJtjjZDDCDDu?p=preview

**What is the expected behavior?**
I understand the intent here (need for a "blank" value), but if type coercion is going to happen, shouldn't we either go all in, or not do it at all? This "halfway" type coercion is confusing. **There should be some sort of option for `ng-value` that lets you turn on/off strict type coercion**.

**Comment by Narretz** [comment]
To determine the checkedness, the $viewValue and the ngValue are compared. In 1.5.8 this comparison is not strict. This has been fixed in master and the upcoming 1.5.9. 
This makes more sense than the non-strict comparison, because ngValue is an Angular expression.

In 1.5.9, this might actually be a breaking change, but going forward this is the right thing to do,

> I understand the intent here (need for a "blank" value)

What do you mean by that?

**Comment by jongunter** [comment]
Gotcha! thanks.

As far as a "blank" value goes, say you have two radio buttons, one with `ng-value="true"` and the other with `ng-value="false"`. When you load the form, you may want both radio buttons to be initially unchecked (thus forcing the user to consider the options and choose a value). `ng-value="false"` not being checked when the `$viewValue` is `undefined` or `null`solves that problem.

**Comment by Narretz** [comment]
That's right.
I have to correct myself. Unfortunately, this is not gonna be part of 1.6, as this is frozen for breaking changes.

**Comment by gkalpak** [comment]
This did make it into 1.6.0-rc.1 after all. Yay!
