### ISSUE TITLE
Feature Request: Make Angular safe to use in Firefox Addon

### ISSUE THREAD

**Issue by SebastianMetzger** [angular/angular.js#15295]
We are developing a quite large Browser Extension/Addon for Chrome, Firefox and Outlook based on AngularJS.

For our last release we got this feedback from the Firefox Addon Reviewers:

> As stated in previous reviews, Angular 1.x is no longer approved. I will not reject this version as it will disable your entire listing. Please retract this submission on your own, this will avoid disabling the entire listing, and your old version will work.
> 
> Please use another library (like ReactJS) for your next submission.

Does anybody have information on this? I was not able to get more infofmation about what exactally the problem is.
https://docs.angularjs.org/api/ng/directive/ngCsp seems not to be enough.

We love Angular and moving to another framework would not make sense as we already put in 2 - 3 years developer man years into our application

**Comment by mrcktz** [comment]
Same problem here. We were not yet rejected, but I found [this forum post](https://discourse.mozilla-community.org/t/webextension-support-for-angularjs-will-end-in-september/10268) that suggests that we will also be rejected. The post does not add any valuable information on reasons, but they seem to consider Angular 1.x highly insecure, at least in the privileged context that an extension runs in.

**Comment by Noitidart** [comment]
The lead developer from Angular 1 reached out to amo-admins. So discussions are under way! Hopefully they can pin point what it was that got Angular 1 blocked, and if it's no longer an issue, we can restore it.

**Comment by Noitidart** [comment]
Lots of activity going on in this topic - https://github.com/mozilla/addons-linter/issues/1000

**Comment by Splaktar** [comment]
Update from the Angular team here: https://github.com/mozilla/addons-linter/issues/1000#issuecomment-255269186

**Comment by mprobst** [comment]
Sorry, hadn't seen this issue. Yes, I'm working on this. It's not entirely clear whether there's a problem really worth fixing in Angular at this point, but we're working with Mozilla to figure out what's going on.

**Comment by mrcktz** [comment]
No worries. We are following the updates in the issue linked by @Noitidart and @Splaktar . Thank you all for taking charge of this issue!

**Comment by Narretz** [comment]
We have released Angular 1.5.9 which fulfills Mozilla's requirements. The linter ban will be lifted on Dec 1st: https://github.com/mozilla/addons-linter/issues/1000#issuecomment-263645094
