### ISSUE TITLE
Form submit preventing

### ISSUE THREAD

**Issue by Miqueliu** [angular/angular.js#15319]
What is the mechanism in AngularJS to avoid the submit state in forms? In others words, I want that a form prevents its default behaviour/state when submit button is clicked.

`preventDefault` and `stopPropagation` event methods are not useful.

[Here](http://codepen.io/anon/pen/EgJrrw) is a CodePen example for fixing.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by Miqueliu** [comment]
The mentioned bug is [here](http://codepen.io/anon/pen/rrbgaA). Why submit is propagated to parents and not prevented?

**Comment by gkalpak** [comment]
There is a different listener on `form`/`[ng-form]` elements that calls `formController.$setSubmitted()`. The `ngSubmit` listener only gets executed after the listener that calls `$setSubmitted()`, so you can't stop that from `ngSubmit`. `e.stopPropagation()` does indeed prevent the `submit` event from propagating upwards, but `$setSubmitted()` also propagates upwards (and you haven't prevented that) - see #11023 for some discussion.

If you want to be able to cancel both listeners, you need to set up your listener in the pre-linking function of a custom directive with a priority higher than `ngSubmit`/`form`/`[ng-form]`.

**Comment by Miqueliu** [comment]
@gkalpak, I don't want to "set `$submitted` to true on child forms when parent is submitted". What I want is to prevent absolutely any submit state in parent form (in my case, when event is crossing the child form), without class (`ng-submitted`) nor native property of form scope (`$submitted`).
