### ISSUE TITLE
optional `comparator` parameter in `$filter('filter')(array, expression, comparator, anyPropertyKey)`

### ISSUE THREAD

**Issue by ranjan-ranjan** [angular/angular.js#15312]
In this website: https://docs.angularjs.org/api/ng/filter/filter, `comparator` parameter is optional in `$filter('filter')(array, expression, comparator, anyPropertyKey)`
![1](https://cloud.githubusercontent.com/assets/16834561/19681306/8868d55e-9ac6-11e6-8b14-43ba4d6fb386.png)

**Comment by gkalpak** [comment]
Listing `undefined` as one of the possible values is an unorthodox way of saying it is optional, I guess.
If someone wants to submit a PR to properly mark it as optional (and mention that it defaults to `false`), I would be happy to merge 😄

**Comment by ranjan-ranjan** [comment]
Also, default value is `false`.

**Comment by gkalpak** [comment]
That's what I said :smiley:

**Comment by kylewuolle** [comment]
I submitted a PR [15371] (https://github.com/angular/angular.js/pull/15371) for this!

**Comment by ranjan-ranjan** [comment]
this isn't showing in docs?
