### ISSUE TITLE
`item-metastat` css class missing in autocomplete demo

### ISSUE THREAD

**Issue by ranjan-ranjan** [angular/angular.js#15315]
I am following https://material.angularjs.org/latest/demo/autocomplete for implementing autocomplete. I think `item-metastat` css class is missing. kindly confirm.
![1](https://cloud.githubusercontent.com/assets/16834561/19716725/ea7d00da-9b7a-11e6-9073-8be27e901cfc.png)

**Comment by gkalpak** [comment]
This repo is about core Angular.js (not AngularMaterial). Please, reopen at https://github.com/angular/material.
