### ISSUE TITLE
Two svg compile tests fail in Chrome 54

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#15333]
These two tests fail in Chrome 54 and Win 10.

https://github.com/angular/angular.js/blob/5cce6e233e332d24383123f185351a28e2c65d56/test/ng/compileSpec.js#L442-L467

**Comment by gkalpak** [comment]
👍 I think they started failing on Chrome v53 btw.

**Comment by gkalpak** [comment]
The reason why they fail is that `<foreignObject>` elements and their descendants seem to be reported as being 25% larger in each dimension 😕 
For example, `<foreignObject style="width: 100px; height: 100px;">...</foreignObject>`, will be reported as being `125px` x `125px` by `getBoundingClientRect()`, although it will have the correct size actually.

**Comment by gkalpak** [comment]
Actually, it doesn't seem to be Windows-specific. I can make it fail on Ubuntu too.
See https://github.com/angular/angular.js/pull/15452#issuecomment-263874025.
