### ISSUE TITLE
`parent` is null in JQLite code

### ISSUE THREAD

**Issue by adamreisnz** [angular/angular.js#15331]
Sentry is reporting an error in our app in Angular's source code for JQLite:

![image](https://cloud.githubusercontent.com/assets/490562/19826098/b42cc3b4-9ddf-11e6-98de-23daff524a4b.png)

The line in question is https://github.com/angular/angular.js/blob/master/src/jqLite.js#L986

It appears under some circumstances `parent` can be `null`, in which case this error pops up. It's probably a good idea to guard against unexpected values of `parent` so this error doesn't occur.

This was seen happening on Angular 1.5.8, on Firefox v26 on Windows XP.

**Comment by gkalpak** [comment]
There are many circumstances under which `parent` can be `null`. The question is who/what is calling `after()` on an element without a parent.

That said, jQuery seems to silently ignore a missing parent, so it might be a good idea to have the same behavior in jqLite. Thoughts, @mgol?

**Comment by lgalfaso** [comment]
I am somehow torn on this issue. On one side, not checking for the parent in `after` is bad. On the other side, silently ignoring might cause some difficult to debug issues.

**Comment by mgol** [comment]
This is the jQuery implementation: https://github.com/jquery/jquery/blob/3.1.1/src/manipulation.js#L365-L371:
```js
	after: function() {
		return domManip( this, arguments, function( elem ) {
			if ( this.parentNode ) {
				this.parentNode.insertBefore( elem, this.nextSibling );
			}
		} );
	},
```

It's specifically guarded and documented:

> Prior to jQuery 1.9, <code>.after()</code> would attempt to add or change nodes in the current jQuery set if the first node in the set was not connected to a document, and in those cases return a new jQuery set rather than the original set. The method might or might not have returned a new result depending on the number or connectedness of its arguments! As of jQuery 1.9, <code>.after()</code>, <code>.before()</code>, and <code>.replaceWith()</code> always return the original unmodified set. Attempting to use these methods on a node without a parent has no effect—that is, neither the set nor the nodes it contains are changed.

jqLite should primarily align with jQuery where it doesn't introduce a lot of code so it seems a good idea to fix it.

Generally, I think a good rule if you think some behavior is undesired in jqLite and that behavior is shared with jQuery is to report an issue to the jQuery bug tracker and make the change there first.

**Comment by lgalfaso** [comment]
Agree with @mgol that we should align with jQuery. That said, when the node
has no parent, should this be logged?

**Comment by gkalpak** [comment]
If we decide to silently not-do-anything (as jQuery does), then we shouldn't log imo.

**Comment by mgol** [comment]
I agree with @gkalpak. This seems a non-breaking feature to me so we can land it whenever we want. @adambuczynski would you like to try to create a patch?

**Comment by adambuczynski** [comment]
@mgol yes sure, will do
