### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by peterWilson34** [angular/angular.js#15334]
I am working on Angular Js web app using Laravel 5.2 as API and I have a big issue in the performance specially in the load time of the home page.

I have a request that get 5 sections from database, each section has one or tow items and each item has many comments. I loop through sections then items then comments to render it via nested  ng-repeat directive.

I also have a list of filters and another of friends each has its own request and `ng-repeat` to render it as well.

Is this considerable as huge data to use over Angular JS, How I can enhance the performance of it?

I also have about 20 modules in the dependencies of the main module, Is there a better way to load this module only when I need them?

**Notes:**

1. Angular Js version 1.5.1
2. Angular Js and jQuery loaded via CDN
3. all other js files are concatenated by GULP.js in one file and it about 66000 lines of code
4. there is 25 module in the dependencies array of the main module
5. the time of load is about 25-35 seconds

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

That said, there are a few things to try:
- make sure it's a render problem and not a problem with the server / database
- for ngRepeat, use track by (see docs)
- consider using one time bindings for data that will not change after initial load (see docs)
