### ISSUE TITLE
Make commit guidelines an independent resource

### ISSUE THREAD

**Issue by butla** [angular/angular.js#15341]
**Do you want to request a *feature* or report a *bug*?**
This can be regarded as a feature.

**What is the current behavior?**
I think that the commit conventions are useful for the whole industry, not only Angular or JS community.
Right now they are specified in (at least) three places and can go out of sync. 
Those places are:
* https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines
* https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines
* https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit?pli=1#heading=h.uyo6cb12dt6w 

That's why I created PR #15340

**What is the expected behavior?**
I think that the description of the commit convention should be available as a subpage of https://angular.io/. A good example of the style I want is http://semver.org/. 
The Google Doc can be used for discussion about how the convention should change (it should be linked to from the page).
CONTRIBUTING.md files should point to the page on angular.io.

**What is the motivation / use case for changing the behavior?**
I want the AngularJS commit conventions to become an industry standard of sorts.

**Comment by gkalpak** [comment]
I would love for the guidelines to become a common pattern, but just to be clear I don't consider the list of types or scopes to be part of it. Different types/scopes make sense for different projects.

**Comment by butla** [comment]
Scopes, of course should depend on the project, but I specifically find the types valuable.
The collection of feat / fix / docs / style / refactor / perf / test / chore would be useful in every serious Python, C#, Java, C++ or Go project that I've worked on. Not only for automated release notes, but also for continuous delivery purposes (do we need to release new docs? release a new version of the project? do we even need to run tests after the commit?).

As for the types themselves, I think that "chore" is enough to encompass CI changes and build-related stuff. It would also be good to either create a type for updating external dependencies (or explicitly mention it in one of the existing ones).

But if you don't share that vision, and I see why you wouldn't, we can close this issue an I can take my lonely quest somewhere else :)

**Comment by gkalpak** [comment]
_Disclaimer: I can only speak for myself - other team members might think differently._

While `feat / fix / docs / style / refactor / perf / test / chore` is a solid set of types, it is definitely not suitable for all projects or types of projects. For example, application projects have very different needs than a framework. I have often used typs such as `ui` (for UI/UX-related improvements/changes that only affect visual/usability aspect) or `i18n` (which is a bigger deal in a public-facing app than a framework) or `cfg` for configuration. Or I have "scoped" my types depending on whether some change is about the frontend of the backend (e.g. `f-fix` vs `b-fix`).

So while it makes sense to suggest a basic set of types that are generic enough and probably useful for most projects, this should not be a hard set rule; people should be able to adapt it to their per-project needs.

Just to be clear, I am only opposed to "standardizing" types. Making the rest of the commit-message guidelines a common practice (i.e. the `<type>(<scope>): <subject>\n\n<body>\n\n<closes/fixes/>\n\nBREAKING CHANGE:...`) would be pretty cool!

**Comment by butla** [comment]
Maybe there can be a few standardized type sets for different domains, or an extendable set... But this pushes me further towards the conclusion that I should leave Angular's conventions alone and maybe try to make something myself (based on them, of course) and see how many people would want to adopt it.

**Comment by gkalpak** [comment]
I am not sure `CONTRIBUTING.md` is suitable for putting on angular.io, but this is something to be discussed on the `angular/angular.io` or `angular/angular` repos. Other than that, I am not sure what next steps there are to take as far as Angular is concerned. If this is to become a widely adopted practice it obviously needs to be unrelated to Angular (and its specific needs).

I am going to close this, since there is nothing actionable (for ng1 repo), but feel free to continue the discussion below.
