### ISSUE TITLE
Dynamic module loading

### ISSUE THREAD

**Issue by firelizzard18** [angular/angular.js#15343]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I have to manually include the source for everything.

**What is the expected behavior?**
I can manually include the source for one module (or something) and dynamically include the source for everything else.

**What is the motivation / use case for changing the behavior?**
It would be clearer to me if I had a custom module name to URL mapping file. I'm running angular on multiple internal web applications and I reuse code. This change would make it easier to put my code on a CDN. I would find it much clearer to update something like angularModuleUrls.json than to remember to go mess with wherever I ended up putting the references.

**Angular version:** 1.5.8

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I'm thinking something like providing a hook into the module loading process. Say, I can add something like `moduleLoaderProvider`. As modules are loaded, if they define a `moduleLoaderProvider` or `*ModuleLoaderProvider` or `*LoaderProvider` (one of those or something similar), then angular gets the provided factory and asks the loader if it knows where the module is. At this time, I would look up my mapping and add a `<script>` to the page with the appropriate URL.

**Comment by gkalpak** [comment]
This does pretty much what module-loaders are about. Isn't it outside the scope of Angular? (E.g. see [here][1]).

[1]: https://docs.angularjs.org/guide/module#asynchronous-loading

**Comment by firelizzard18** [comment]
I wanted something that would work on-demand within angular. So, only loading modules when another angular module asks for them.

**Comment by gkalpak** [comment]
I think that loading modules (i.e. resolving names to URLs, creating script tags, handling their lifecycle etc) is outside the scope of Angular. Also, currently, modules are loaded upfront (i.e. there is no built-in support for lazy loading modules/providers) - this is a different subject and tracked in separate issues.

**Comment by gkalpak** [comment]
I think that loading modules (i.e. resolving names to URLs, creating script tags, handling their lifecycle etc) is outside the scope of Angular. Also, currently, modules are loaded upfront (i.e. there is no built-in support for lazy loading modules/providers) - this is a different subject and tracked in separate issues.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any further feedback. Feel free to reopen this issue if you can provide new feedback.
