### ISSUE TITLE
Ambiguous $http -1 status return on 404/500 OPTIONS

### ISSUE THREAD

**Issue by warent** [angular/angular.js#15342]
This is for Angular 1.5.5

When you're using $http to connect to a nonlocal server and run through the `OPTIONS` process of for CORS, if the server resource happens to be either 404 or there's a 500 error, the server will return that status on the OPTIONS. However, $http interprets any OPTIONS error as -1.

If the resource doesn't exist on the server, the options don't exist either, so the OPTIONS should return 404.
If the resource has a bug in it and the options are part of the server bootstrap, then the OPTIONS should return 500.

If you try to intercept these errors:
```
$httpProvider.interceptors.push(($log) => ({
        responseError(error) { $log.log(error.status) }
}));
```
You will get -1 every time from an OPTIONS 404 or 500

We need to know if there's a server error or a missing resource, because a server error should log our clients out, whereas a 404 can be ignored.

**Comment by Narretz** [comment]
As far as I know, the xhr spec defines this behavior. Failed options requests always return -1, there's nothing we can do in Angular about this. You can try the same with a plain XMLHttpRequest() and you should get the same behavior.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
