### ISSUE TITLE
docs: Some of code examples in CHANGELOG.md are missing language 

### ISSUE THREAD

**Issue by NoHomey** [angular/angular.js#15356]
There are code examples in the CHANEGLOG.md that are not highlighted due to missing language in the code blocks.

**Comment by gkalpak** [comment]
Good point! Interested in submitting a PR? :smiley:

**Comment by NoHomey** [comment]
Yes I'm about to do it.

**Comment by NoHomey** [comment]
#15357 fixes this. But I have problem with CLA check I have already sign it with PR for  `angular/in-memory-api` ...
