### ISSUE TITLE
MockBackend - Passtrough equivalent?

### ISSUE THREAD

**Issue by ganesansays** [angular/angular.js#15368]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
MockBackend does not provide an option to passthrough. This limits from mocking specific backend, still preserving original non mocked behavior for the rest.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Application development using stubs require such functionality and it was part of Angular 1.5 mocking framework as passthrough.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular version: 2.0.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This repository is for Angular 1.x only. The Angular 2+ repo is https://github.com/angular/angular.
