### ISSUE TITLE
Changelog fixes for 1.6.0-rc.1

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#15364]
* bcd0d4d896d0dfdd988ff4f849c1d40366125858

"If you don't have time to migrate the code at the moment, you can flip the
setting back to true"

`$compileProvider.preAssignBindingsEnabled(true);`

**Comment by mgol** [comment]
* 7bc71a
"Now, all traditionally false JavaScript values are treated as failing the validator, as one would naturally expect."

There is only one `false` value, the expression "traditionally false" doesn't make sense. It should say "falsy" or "falsey" (not sure what's the best spelling).

**Comment by mgol** [comment]
* fc0c11db845d53061430b7f05e773dcb3fb5b860

It says "fc0c11): camelCase keys in jqLite#data"; the weird paren needs to be removed

**Comment by mgol** [comment]
* acb545ec3ebf099db68561033645941c900973b5

In the "After" code snippet the ampersand is incorrectly encoded:
```js
// URL: /foo/42?bar=baz&amp;toString=hmm
```

**Comment by Narretz** [comment]
Am I missing something, or can we introduce these changes right away? The title makes it sound like we have to wait for 1.6.0-rc.1

**Comment by mgol** [comment]
I think you're right that we can do it at this very moment. I think the title just meant that it's sth we plan to do before releasing rc.1 but that doesn't seem to be a blocker.

**Comment by petebacondarwin** [comment]
For commits that have not been released yet we can't yet update the changelog for them. This issue is supposed to track those things
