### ISSUE TITLE
Docs app: version data for 1.6.0-rc.0 is incorrect

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#15369]
The NG_VERSION constant for 1.6.0-rc.0 looks like this:
```
{
  "raw": "v1.5.8",
  "major": 1,
  "minor": 5,
  "patch": 9,
  "prerelease": [
    "build",
    "195"
  ],
  "build": "sha.1cf01d6",
  "version": "1.5.9-build.195",
  "codeName": "snapshot",
  "isSnapshot": true,
  "full": "1.5.9-build.195+sha.1cf01d6",
  "branch": "master",
  "commitSHA": "1cf01d6fa7fcfb45bef46e4a800845ae8ab90b06"
}
```

which means rc.0 is incorrectly identified as master / snapshot on the docs site (specifically in the version picker). Do we know why the version isn't marked as 1.6.0-rc.0? The `version.json` file has the correct info:
```
{
  "raw": "v1.6.0-rc.0",
  "major": 1,
  "minor": 6,
  "patch": 0,
  "prerelease": [
    "rc",
    0
  ],
  "build": [],
  "version": "1.6.0-rc.0",
  "codeName": "bracing-vortex",
  "full": "1.6.0-rc.0",
  "branch": "v1.6.x",
  "cdn": {
    "raw": "v1.5.8",
    "major": 1,
    "minor": 5,
    "patch": 8,
    "prerelease": [],
    "build": [],
    "version": "1.5.8",
    "docsUrl": "http://code.angularjs.org/1.5.8/docs"
  }
}
```

**Comment by petebacondarwin** [comment]
OK, I don't know why but I suspect it has something to do with rc.0 being the first tag with 1.6 in it.

**Comment by petebacondarwin** [comment]
Perhaps it is because we did not update the `branchVersion` in package.json to a version containing 1.6 yet because that would break the docs app, since 1.6.0-rc.0 is not yet on CDN?

**Comment by petebacondarwin** [comment]
I think we should refactor this whole version number stuff in a fairly significant way, separating out:

* the version that the docs app runs on
* the version that is applied to the built library (e.g. `angular.version`)
* the versions that are available in the download modal on angularjs.org homepage

Any I have missed?

**Comment by Narretz** [comment]
I like the idea. We could add 

- the versions that are available in the version picker in the docs
- the version that is documented in a specific docs build

The latter *should* be the same as *the version that is applied to the built library*, but as you can see in the rc.0 folder, the version.json is correct, while the docs/versions-data.js is incorrect.

**Comment by Narretz** [comment]
Btw, we should probably update the versions-data.js manually for rc.0 in the code.angularjs.org repo

**Comment by Narretz** [comment]
See https://github.com/angular/code.angularjs.org/pull/38 for the version-data.js update for code.angularjs.org

**Comment by petebacondarwin** [comment]
I have merged https://github.com/angular/code.angularjs.org/pull/38
