### ISSUE TITLE
Add support for dataUrls as templateUrls in routes definition

### ISSUE THREAD

**Issue by hendrul** [angular/angular.js#15374]
I'm using webpack to bundle my project and it have this url-loader which allows me to set a size threshold for files (html in this particular case) where the files lower to it are inline as a [dataUrl](http://dataurl.net/) , and higher to that will be copied to the "publicPath" location into the generated bundle. It would be great to be able to do this:
```javascript
$routeProvider.when('/some/path', {
  title: 'rest',
  templateUrl: require('./some.html'),
  controller: 'someCtrl'
})
```
And let the loader make some html files be inlined as dataUrls while heavier ones loaded on demand

**Comment by Narretz** [comment]
Unless I'm missing something, this already works, *but* you have to mark the data url trusted via $sce, see https://codepen.io/anon/pen/YpXWmP?editors=1010

**Comment by hendrul** [comment]
thanks dude!

**Comment by Narretz** [comment]
You're welcome!
