### ISSUE TITLE
Maximum call stack size exceeded when using object with circular references in ngClass

### ISSUE THREAD

**Issue by Malczewski** [angular/angular.js#15373]
Using objects with circular references in ng-class causes "stack size exceeded" errors in console.
Reproduced in 1.5.0 - http://plnkr.co/edit/TwZphKvat6tzWrzwOrv6?p=preview
Related to #11372.

**Comment by gkalpak** [comment]
This will taken care of by #15246.

In the meantime, since you are only interested in the presence of the property and don't need a deep copy of it, you can convert it to boolean when using it inside `ngClass` (see below). This will also improve the performance.

```html
// Replace that:
<div ng-class="{foo: $ctrl.someLargeObject}"></div>

// With this:
<div ng-class="{foo: !!$ctrl.someLargeObject}"></div>
```
