### ISSUE TITLE
scope: false still creates a child scope.

### ISSUE THREAD

**Issue by dallingel** [angular/angular.js#15386]
Hello,

In the documentation it says that "scope: false" in a directive, force the new directive to use the scope of its parent. 

I have this:

`<parent>
<child></child>
</parent>`

When I print the scope inside my parent link directive, It says the scope has $id 200.
When I print the scope in the child link function, it says "ChildScope, $id 231", with a parent having $id 200.
But the child is like this:

```.directive('child', function () {

        return {
            restrict: 'E',
            scope: false,
            templateUrl: 'directive/view/child.html',
            link : function(scope) {
                console.log("child scope", scope);
                 scope.methodToOverride = function() { console.log("child method")}
            }
        };
    })`
```
Shouldn't it be using the full parent scope instead of inheriting from the parent scope as said in the documentation? I was hoping I could override a method from _parent_ inside _child_. But it is not working, as both scopes are different.

When I inject <child></child> inside <parent></parent> using $compile, it indeed keep the parent scope fully and I can override the method with no problem.

Am I doing something wrong or is this a bug? Actually this is a simplified version of my code. I am using multiple nested directives (Without transclude or replace).

Thank you in advance.

**Comment by Narretz** [comment]
Impossible to say why it's happening without knowing what `parent` looks like: http://plnkr.co/edit/vpu9aRxCshV8qGqi2wGE?p=preview

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.

**Comment by dallingel** [comment]
Hello,

Thank you for providing a plunker. The issue was caused by a ng-if creating a childscope. There's no problem with "scope:false". Thank you and sorry for the inconvenience.

updated plunker:
http://plnkr.co/edit/xMj1oNWK1dMMOwLSjvTG?p=preview
