### ISSUE TITLE
Values not assigning to a object in safari browser and ipad;working in chrome.

### ISSUE THREAD

**Issue by prasadyallapu** [angular/angular.js#15382]
Hi Team,

Currently there is a issue in the change of input value.In below code what I am trying to achieve is "trying to modify the price" once after changing price I am binding the value inside a object item.Here is object is (material).The modified value is working chrome perfectly, but when it come to safari browser(5.1.2) & in ipad (V10.1.1) values are assigning to the object .

```html
`<div class="row">
<input  value="{{material.Price}}" ng-model="item.material.Price" ng-click="showEditPricePopup($index)" />
</div>
```

**JS Code**
```js
**material is a objetc**
  $scope.showEditPricePopup = function(index) {   
    $scope.priceChange = {};
    var material = $scope.orderguideitems[index].material;
    $scope.initialPrice = material.Price;
    $scope.priceChange.modifiedPrice = material.Price;

    modifiedPrice = function(price){
      material.Price = parseFloat(price);
      modifyCart(material);
    }
    modifiedPrice(25);
}
```

**Comment by Narretz** [comment]
You should not bind to value and ng-model at the same time.
It also look like you are not defining modifiedPrice before assigning a function to it.
All in all, you should provide a running example for your problem.

**Comment by gkalpak** [comment]
This sounds like a general support question (and probably an issue with improper usage of `ngModel`/`value`). You should not use `value` and `ngModel` at the same time.

In any case, please use one of the [appropriate support channels][1] for these types of questions, unless there is a clear indication that this is a bug with Angular itself.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
