### ISSUE TITLE
docs($httpProvider): broken layout

### ISSUE THREAD

**Issue by OleksandrLazorenko** [angular/angular.js#15393]
Try to scroll content horizontally.

![screen shot 2016-11-15 at 17 01 21](https://cloud.githubusercontent.com/assets/9006651/20310805/fd2986be-ab55-11e6-9f69-197561a4a1fb.png)

**Comment by sagargulati** [comment]
+1 Everything broken, SSL issue, the content/scripts is  being loaded over non SSL while the docs moved to full SSL.

**Comment by gkalpak** [comment]
@sagargulati, this is totally unrelated to SSL. The docs are on SSL for a long time (if not forever).
(We have updated the app though and you might need to clear the cache and refresh.)

**Comment by Narretz** [comment]
Just an unclosed `, will fix in a minute

**Comment by sagargulati** [comment]
@gkalpak : What i meant was it wasn't forced ssl before, we could use it on both ssl and non ssl before, but since today, it's on force ssl mode.

**Comment by petebacondarwin** [comment]
I am sure we have been on HTTPS with redirects from HTTP for a long time. I'll ask @jeffbcross

**Comment by Narretz** [comment]
@sagargulati The problem with raising this problem in an existing thread is that it only causes confusion and doesn't usually get the expected response. Please open a new issue for separate prolems.

**Comment by gkalpak** [comment]
@sagargulati, it is also possible you run into a Chrome intervention: https://developers.google.com/web/updates/2016/08/removing-document-write#how_do_i_fix_this

**Comment by jeffbcross** [comment]
All angularjs.org sites have enabled hsts for over a year, and all http requests are redirected to HTTPS.
