### ISSUE TITLE
fix(docs-app): get rid of `document.write` for inserting scripts

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#15396]
Since Chrome 54, scripts inserted via `document.write` generate a warning and might be blocked on slow networks (see [this article][1] for more info).

Since we are using `document.write` for scipts in our [docs app][2], it might break on slow networks.

The warning message is:

> A Parser-blocking, cross-origin script, https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-min.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

[1]: https://developers.google.com/web/updates/2016/08/removing-document-write#how_do_i_fix_this
[2]: https://github.com/angular/angular.js/blob/ce49edc08b3d642f3768f4282d391062d2f83037/docs/config/templates/indexPage.template.html#L43

**Comment by Splaktar** [comment]
Should this issue's milestone be updated to 1.8.x?

**Comment by petebacondarwin** [comment]
Good spot @Splaktar !
