### ISSUE TITLE
BEFORE WE FORK 1.6.x FROM master

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#15417]
We want https://docs.angularjs.org to reflect the latest full release of Angular.  At the moment the docs shown are the current snapshot of master. This requires two things:

* changes to the hosting server to redirect `docs.angularjs.org` to `code.angularjs.org/latest` rather than `code.angularjs.org/snapshot`.
* changes to the release process to additionally copy released files into `code.angularjs.org/latest`.

**Comment by Narretz** [comment]
Resolved by #16093
