### ISSUE TITLE
Angular - moving on from shadow-Piercing descendant combinator - /deep/

### ISSUE THREAD

**Issue by Ne-Ne** [angular/angular.js#15416]
Hi All,

Just seen the following notice, first I have heard seen until today:

> /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

This is best practise at the moment (https://angular.io/docs/ts/latest/guide/component-styles.html#!#-deep-) ?

Does the Angular Team have a better reccomendation going foward or is this going to be removed going forward?

Current Version: `2.2.0`

Many thanks.

**Comment by gkalpak** [comment]
This repo is for AngularJS (aka 1.x). You should post this on the [Angular 2+][1] repo.

[1]: https://github.com/angular/angular
