### ISSUE TITLE
ng-santize Linebreaks in output break the ng-bind-html functionality 

### ISSUE THREAD

**Issue by shubh93** [angular/angular.js#15410]
whenever i tried to bind the not able to make on same line 
<span>{{ "hello" }} -
                    <span ng-html-bind = "page.title" </span>
                  <span>

my output is Like : 
hello 
page.title

why page.title is next line i want to be on same line how to fix it ?

**Comment by gkalpak** [comment]
It is probably related to the content of `page.title`. `ngSanitize` shouldn't add any newlines and I have [proof][1] :smiley:

--
So, this sounds like a usage/support question, in which case you can try asking on one of the [appropriate support channels][2].

If you still believe there is an issue in Angular, please provide a runnable demo of the problem (e.g. using CodePen, Plnkr etc). I would be happy to reopen and investigate.

[1]: https://codepen.io/ExpertSystem/pen/jVVoRw?editors=1000
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
