### ISSUE TITLE
How to find which view is used from ng-view or ui-view?

### ISSUE THREAD

**Issue by jay2413** [angular/angular.js#15423]
I'm creating one plugins which will used in angularjs application.

But i have 2 queries :

1.How can i check that which one is used `'ng-view' ($routeProvider)` or `'ui-view' ($stateProvider)` by user in his/her application ??

2.I want to get `module name` which he/she has defined in main `app.js` so by using that default(already defined) module name i can apply my custom angular functionality on that module.

Thanks

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

--
Hints:
For (1) you could use [`$injector.has()`][2] to check for specific services or directives.
If I understand your requirement correctly, it is not possible. And it doesn't sound like a good idea either. Just specify your module and if the user wants to, they will add it as a dependency to theirs. 

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://docs.angularjs.org/api/auto/service/$injector#has
