### ISSUE TITLE
All the sample plunker from API Reference page examples aren't working

### ISSUE THREAD

**Issue by pankajparkar** [angular/angular.js#15437]
**Bug**

All the plunker which are provided on [API Reference](https://docs.angularjs.org/api) page aren't working. Suppose take an example of [ngRepeat](https://docs.angularjs.org/api/ng/directive/ngRepeat) API, when click on **Edit Plunkr link** (provided on top of example code window)  it opens a plunker but that code isn't working because of wrong angular.js version reference.

**Below is the link taken from plunkr**

<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.10-build.5166/angular.min.js"></script>

If you look at script tag inside a plunker it has version like this `1.5.10-build.5166`, which should be ideally something like `1.5.8`(stable version).

**Comment by pankajparkar** [comment]
**Note** @gkalpak It was broken since 1.5.9-build.xxxx since week back, so I thought I should log a bug.

**Comment by gkalpak** [comment]
It was possibly broken by ce49edc. I'll take a look. It should be using `https://code.angularjs.org/snapshot/angular.min.js`.
