### ISSUE TITLE
Editing directive isolate scope edits the outer parent controller scope

### ISSUE THREAD

**Issue by moneytree-doug** [angular/angular.js#15430]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Editing the isolate scope in the directive alters the outer scope even if the directive is one-way binding

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
https://plnkr.co/edit/mgdulNjeQ5UTYHHxIUKy

**What is the expected behavior?**
Outside of the directive's scope shouldn't be altered

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Tested Angular 1.5.7

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This is working as expected. Quoting [the docs][1]:

> One-way binding does not copy the value from the parent to the isolate scope, it simply sets the same value. That means if your bound value is an object, changes to its properties in the isolated scope will be reflected in the parent scope (because both reference the same object).


[1]: https://docs.angularjs.org/api/ng/service/$compile

**Comment by moneytree-doug** [comment]
@gkalpak Could you explain to me what's the suggested solution here? I understand how that works on a JS level, but I don't think I should have to. Using ``<`` for one-way binding is a very strong intention that I don't want my changes cascading back to the parent. Since it is doing so, that's just the same as two-way binding which makes it really redundant to even use ``<`` at this point.

**Comment by gkalpak** [comment]
As mentioned in the aforementioned docs, one-way binding is useful if you do not plan to propagate changes to your isolated scope bindings back to the parent, but does not make it impossible. Also from the docs:

> `$onChanges`: [...] Use this hook to trigger updates within a component such as cloning the bound value to prevent accidental mutation of the outer value.

--
FWIW, the difference between one-way and two-way bindings is that re-assigning the inner property does not propagate to the outer scope.

--
Possible solutions if you want a one-way data flow (what is best depends on your exact usecase):

1. Do not mutate the passed in object directly. Emit mutations requests as events for the parent directive to perform.
2. Clone the passed in object in `$onChanges`.
3. Pass primitive values to the "leaf"-components that are responsible for editing values. E.g. if you want to edit `greeting.message`, do pass `greeting.message`, not `greeting`.
4. Use immutable data structures.
