### ISSUE TITLE
Ng-repeat, Internet explorer 11 (windows 10) and output in style attribute

### ISSUE THREAD

**Issue by igorcrevar** [angular/angular.js#15449]
I want to report the bug with ng-repeat and output in style attribute of repeated element. This bug only occurs in Internet explorer 11 (and probably other versions as well), it does not occur on edge, firefox and chrome, windows phone explorer, etc.... I am not sure if problem occurs in ie on other versions of windows os.

I have created minimal example which shows what bug is:
http://plnkr.co/edit/teo6MQ2hxeLtCjCOcVZz

On internet explorer 11, left and top in style of a div will not be updated to correct values. In all other browsers "labels" will have their correct positions. It seams that in expression
<div ng-repeat="label in items track by $index" class="seats-label"
             style="position:absolute;left:{{label.x}}px;top:{{ label.y}}px">

{{label.x}} and {{label.y}} are not parsed (and executed) for problematic browser

I have updated to the latest version of angularjs 1 branch and problem still occurs

**Comment by gkalpak** [comment]
This is a [documented known issue][1] for IEs (and there are straightforward workarounds available).

[1]: https://docs.angularjs.org/guide/ie
