### ISSUE TITLE
filter date error in format EEE  for saturday in spanish 

### ISSUE THREAD

**Issue by MrCalamitus** [angular/angular.js#15447]
Using de filter date whit format EEE for dates contain saturday the string is **Aáb.** but correct is Sáb. 
## Controller
````javascript 
$scope.date = new Date('2016-11-27');
````
## View 
````html
{{date|date:'EEE'}}
````

**Comment by Ivanepp2** [comment]
I have the same error

**Comment by gkalpak** [comment]
[It works][1] for me on Chrome. Closing, but happy to reopen if you can provide an actual reproduction (preferrably a live demo using CodePen, Plnkr etc).

[1]: https://codepen.io/ExpertSystem/pen/xRPKOe?editors=1011
