### ISSUE TITLE
Ошибка обработки разметки в IE9

### ISSUE THREAD

**Issue by Ruzancev** [angular/angular.js#15446]
При добавлении контроллера на страницу представления в SP2013. Обработка падает при обработке разметки таблицы. Представление содержит группировку.

**Comment by Narretz** [comment]
Sorry, I don't speak Russian and the google translate isn't very helpful.

"When a controller is added to the presentation in the SP2013. Treatment falls when marking processing table. The view contains grouping."

Please provide an English description and an example (plnkr.co etc) of your problem.
