### ISSUE TITLE
form validation dynamically using the json

### ISSUE THREAD

**Issue by dhamodharanbaskar** [angular/angular.js#15450]
hi guys i need to validate the form dynamically by using the given json format
validation must be done dynamically in angular js can anyone suggest me the steps to be followed
contact number 9952005644

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
