### ISSUE TITLE
radio button preselect from ng-model from 1.5.9

### ISSUE THREAD

**Issue by zerdos** [angular/angular.js#15453]
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behaviour**
Issue got introduced in version 1.5.9
Given a radio button, and the "pre-selected" state doesn't happen, if the model value is integer.

**Expected behaviour**
It should be preselected.

**Minimal reproduction of the problem with instructions**
<input type="radio" value="42" name="checkBox" ng-model="checkBoxValue">

in the controller:
$scope.checkBoxValue=42;

The radio won't get be selected 
($scope type is integer, and not string "42")

https://plnkr.co/edit/UTKoxnsXKPwcUbgd145g?p=preview

**What is the motivation / use case for changing the behaviour?**
Old applications which didn't cast the values will be broken now.

**Please tell us about your environment:**
Mac

* **Angular version:** 
From angular 1.5.9

* **Browser:** Chrome

**Comment by Narretz** [comment]
I think that was by accident changed with the switch to ESLint and fixed later, but the commit didn't make it into 1.5.9.

**Comment by Narretz** [comment]
@zerdos Did you further modify the plnkr? I don't see any radios in there anymore

**Comment by Narretz** [comment]
This was fixed by https://github.com/angular/angular.js/commit/593a5034841b3b7661d3bcbdd06b7a9d0876fd34 and we should get this into 1.5.10

**Comment by zerdos** [comment]
@Narretz, sorry accidentally I did. I created a cleaner test page for it.

**Comment by e-cloud** [comment]
@Narretz when will 1.5.10 be released? This is really broken behavior. Or is there any workaround?

**Comment by Narretz** [comment]
@e-cloud There's no fixed date. The usual workarounds apply - use an ngModel formatter that converts the number to a string, see https://code.angularjs.org/1.5.9/docs/api/ng/directive/select#binding-select-to-a-non-string-value-via-ngmodel-parsing-formatting for an example. It's the select directive, but the principle is the same.

**Comment by e-cloud** [comment]
@Narretz Thx angway.
I figure out another way.

use `ng-value` to host the initial value.

@zerdos see here https://plnkr.co/edit/m9EWtqhC5qBMe4bOEgci?p=preview
if the model is integer and use `ng-value` for initial, it fixes my problem.

**Comment by gkalpak** [comment]
Closing since this is already fixed by 593a503 (as mentioned by @Narretz).

**Comment by zerdos** [comment]
@gkalpak:
using ng-value is fine. But using the normal ```value```  attribute works in angular 1.5.8 and before as well, but not in angular 1.5.9 and above.

**Comment by gkalpak** [comment]
@zerdos, the 1.5.8 behavior was restored in 1.5.10 afaict. Are you still seeing something different?
