### ISSUE TITLE
Child scope in angular

### ISSUE THREAD

**Issue by danbeo95** [angular/angular.js#15457]
*
i try understand scope angular.I see the docs write 
childScope.aString = 'child string' The prototype chain is not consulted, and a new aString property is added to the childScope. This new property hides/shadows the parentScope property with the same name. This will become very important when we discuss ng-repeat and ng-include below.

i have question that:why aString is not consulted whereas Object is dose!??

**Comment by gkalpak** [comment]
This is how JavaScript prototypal inheritance works. This [wiki article][1] might help.
If you need further support, please, use one of the [general support channels][2].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/wiki/Understanding-Scopes
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
