### ISSUE TITLE
Angular 1.5.8 - flickering related to ng-show/hide

### ISSUE THREAD

**Issue by psmyrdek** [angular/angular.js#15461]
I've updated my app written in Angular 1.4.1 to Angular 1.5.8 and in some places some weird things started to happen.

Mostly it is about flickering of directives with ng-show / ng-hide used on them. I read here #13974 about similiar issue but I can't fix it with any solution posted there.

You can see the demo here - it's about that red indicators below each input:

![out](https://cloud.githubusercontent.com/assets/6187417/20795968/376dfbea-b7d4-11e6-838f-91540c40b64a.gif)

More info - in these inputs I'm using typeahead directive from AngularUI Bootstrap. Typeahead popup template is being fetched from external file (not inlined).

**Comment by Narretz** [comment]
Looks similar to https://github.com/angular/angular.js/issues/14015 for which I wrote a pach, but never opened a PR :/

**Comment by psmyrdek** [comment]
Unfortunately I tried to use patch from this issue you've attached and no difference :/

And all of this looks similar to @garycuthbert comment:

> another issue we were seeing with our directives, we use a lot of nested directives that use templateUrl and, with the latest angular release, we started to see some fairly ugly transient rendering on initial page loads & view transitions.

Same here :/

**Comment by gkalpak** [comment]
I wonder if this is also related to https://github.com/angular/angular.js/issues/15426#issuecomment-263688327. @psmyrdek, does it happen on a specific browser or not? Could you create a live reporduction (e.g. using CodePen, Plnkr etc)?

**Comment by psmyrdek** [comment]
It has been tested on Chrome, Safari and Firefox - the same problems on every mentioned browser.

@gkalpak your reply from #15426 looks promising (when speaking about solving this issue). I do have some places with ng-show initialized with falsy values (don't ask me why) and before migration to 1.5.8 it was working ok (at least from the user's perspective). Now there's a blink when ng-show="falsy value" turns into ng-hide.

**Comment by gkalpak** [comment]
@psmyrdek, your demo shows something different: The flickering is caused by the element being shown before angular takes over and hides it. Issues such as this can be solved with `ngClock` (and the appropriate styles - if necessary).

Can you try the following directive and see if the flickering goes away in your route changes:

```js
.directive('ngShow', function() {
  return function(scope, elem, attrs) {
    var doShow = scope.$eval(attrs.ngShow);
    elem[doShow ? 'removClass' : 'addClass']('ng-hide');
  };
})
```

**Comment by psmyrdek** [comment]
> @psmyrdek, your demo shows something different: The flickering is caused by the element being shown before angular takes over and hides it

My question is why places like that worked well in 1.4.1 but now I see flickering. 

Of course I agree that places with `ng-show="falsy value"` are vulnerable to this kind of issues, and I agree that there should be used ng-cloak with "css styles fallback" to prevent these problems, but as I said - in my case it wasn't possible to reproduce this issues in 1.4.1. Is newer Angular slower a bit in terms of initialization, or what?

This is just one of two - the second problem is still related to places with heavier route changes. My friend @jerry23 is also involved in this project and he say something more about it..

**Comment by Narretz** [comment]
@psmyrdek I can reproduce the initial flickering in your codepen even in 1.4.1 in Chrome.

**Comment by gkalpak** [comment]
@psmyrdek, this has nothing to do with being heavier. A bad network for example can have a dramatic impact on how long it takes for the script to load. This can definitely be an issue with older versions. But just to be clear, flickering on elements that are included in your `index.html` (as in your demo) are totally different than flickering on elements that are included inside templates (such as those related to your routes).

So, it is this second category (flickering inside templates) that we need to investigate and if necessary address. Can you try [my directive][1] and report back if route flickering keeps appearing and if it has any unwanted side effects (e.g. in terms of initial animations etc)?

It would also be tremendously useful, if you could put together a minimal reproductionof the flickering (e.g. using CodePen, Plnkr etc).

[1]: https://github.com/angular/angular.js/issues/15461#issuecomment-264424476

**Comment by jerry23** [comment]
I tried to use this directive but in some cases, it doesn't work correctly. 
Now in some places, I'm seeing elements which should be hidden e.g dropdowns list,  content messages, error messages in forms. 
Adding ngCloak in all places where the problem exists will be painful and it can be impossible in some cases (external directive).

**Comment by gkalpak** [comment]
> I tried to use this directive but in some cases, it doesn't work correctly.

Any pattern regarding the "some cases" that it does or doesn't work? We can't really do much without a reproduction or more insight on the exact usecase that is affected by the issue 😞 

--
> Now in some places, I'm seeing elements which should be hidden e.g dropdowns list, content messages, error messages in forms.

Now, that is weird. If you could share a repro of that, it would be very helpful too. But I understand it is usually difficult to reproduce a corner case in a minimal demo.

--
> Adding ngCloak in all places where the problem exists will be painful and it can be impossible in some cases (external directive).

Once again, I only suggest `ngClock` for elements that appear in the original (static) HTML in your `index.html`.

**Comment by psmyrdek** [comment]
Unfortunately, it's so far impossible to reproduce this issue in apps of that scale:
http://plnkr.co/edit/DZdAYxk836dDtoGRQgI7?p=preview

That's kind of 1:1 reproduction of situation from GIF from 1st post. We're using typeahead, which contains typeahead-popup directive inside. Template of this directive is being fetched from external file. It also contains that problematic warning element, with ng-show set to falsy value at the beginning. And that's the place where flickering/blinking occurs.

But on plnkr works good so far...

**Comment by Narretz** [comment]
Maybe there's some css / styles that's causing problems? For example, a css transition on an element with show / hide could cause issues.

**Comment by psmyrdek** [comment]
As we've just noticed, entirely removed ngAnimate restored our app back to normal. 

Tries with Angular 1.5.8 + angular-animate 1.4.1 failed, tries with angular 1.5.9 with latest animate failed, the same with 1.6.0-rc2.

Of course that's not end for us, we have to handle missing angular-animate now.

**Comment by gkalpak** [comment]
Unfortunately, it is really hard to tell without a repro. I am also still surprized that the directive abov does not work (but it might depend on the implementation of the involved directives). Can you check what happens if you add the `ng-hide` class (in the HTML) to the problematic elements?

(BTW, is this app publicly available by any chance?)

**Comment by gkalpak** [comment]
Since we haven't heard back from the OP and most importantly we don't have a reproduction, I am going to close this for now. Similar flickering problems are already tracked in other open issues anyway.
<sub>(Happy to reopen as soon as there is some reproduction or verification that this is a different/new issue.)</sub>

**Comment by ShankzPatil** [comment]
Working for me.

.directive('ngShow', function() {
  return function(scope, elem, attrs) {
    var doShow = scope.$eval(attrs.ngShow);
    elem[doShow ? 'removeClass' : 'addClass']('ng-hide');
  };
})
