### ISSUE TITLE
multiple select always jumps back to lowest marked element

### ISSUE THREAD

**Issue by Sogmog** [angular/angular.js#15477]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
- multiple select: In successively selecting one of the last and one of the first elements, the selector jumps back to the lowest selected element.
I think angular background magic bred this bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
- example: https://plnkr.co/edit/8Cw3duixywJui0TYELKF?p=preview
It's only a minimal example, i build this in different cases but i can't post the original source code.
**special look at the ```  $interval(function() {}, 100); ```**

**What is the expected behavior?**
* the select works normally without jumping.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
 - angularjs 1.5.6
- Firefox / IE

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
sorry for my bad english, I'm from Germany.

with best regards
Sogmog

**Comment by gkalpak** [comment]
This also happens on Chrome btw.

**Comment by Narretz** [comment]
Maybe it's because we re-set some attributes. I hope it's not because the options get re-rendered ... which shouldn't happen.

**Comment by gkalpak** [comment]
In Chrome, it only happens if you have one element selected (e.g. select 10, then scroll back to 1, then digest). I suspect it is because of [this method][1].

[1]: https://github.com/angular/angular.js/blob/e922c38612f52611a47419172e8173a1c024ef6c/src/ng/directive/ngOptions.js#L508-L519

**Comment by gkalpak** [comment]
Here is a [demo][1] with the fix from #15478.

[1]: https://plnkr.co/edit/Z9lAXfCcNcspNJxhhVQC?p=preview
