### ISSUE TITLE
json validation in angular js

### ISSUE THREAD

**Issue by dhamodharanbaskar** [angular/angular.js#15488]
hi 
i need to validate and the json file in angular js dynamically
i had used http request method to display the json file in html page 
now i need to validate the json schema according the input given by the user matched the error cases and if so print the error described in json 

methods tried
* used error handler function to display and validate the error
*described the error i controller and passed it through ng onsubmit option

challenges facing 

since error message and condition both declared inside the schema i dont know to compare both print the error message

**Comment by dhamodharanbaskar** [comment]
<head>
    <title>Angular</title>
</head>
<body ng-app="myApp">
<form ng-controller="appController" name="form" action="#" method="post" enctype="multipart/form-data" class="form-validation"
      ng-submit=submitForm(data) novalidate>
    <div ng-repeat="(key, val) in data.fields">
        <h2>{{val}}</h2>
        <p>Title</p>
        <input type="text" ng-model=data.form[val].title required><br>
        <p>Placeholder</p>
        <input type="text" ng-model=data.form[val].placeholder required><br>
        <p>Description</p>
        <input type="text" ng-model=data.form[val].description required><br>
        <p ng-if="data.length='0'">no records found</p>

    </div>

 <p></p>
    <button ng-click="submit()">submit</button>
</form>
<script src = "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js"></script>
    <script>
        var myApp = angular.module('myApp',[]);

        myApp.controller('appController', ['$scope','$http', function($scope, $http) {
            var NUMBER_REGEXP = /^[0-9]+$/;

            $http({ method: 'GET', url: 'JsonSchema.json' })
                .then(function successCallback(response) {
                    $scope.data = angular.fromJson(response);
                    $scope.data = $scope.data.data;
                    console.log($scope.data);
                }
                );
            

        }]);

**Comment by dhamodharanbaskar** [comment]
now what method should be used to validate the json in above html file
i had gone through the schemaform and github i cant get the method since its demo project given for my understanding and knowledge capability

**Comment by petebacondarwin** [comment]
@dhamodharanbaskar I think, but I might be wrong, that this is not bug report but a question about how to use Angular. If so, then please read https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question to see where you can find help.

If you are reporting a bug then can you please open a new issue with a more clear description of what is broken.
