### ISSUE TITLE
If a service is implmented using an es6 class that extends an imported module, injecting the service will throw an unknown provider error on IE11.

### ISSUE THREAD

**Issue by charlesdeuter** [angular/angular.js#15487]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a service is created using an es6 class that extends **an imported module** the service will throw an unknown provider error on IE11.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
I don't believe plnkr supports `import` functionality so I'll just write out the steps.

1. Setup a small angular app using babel to transpile
2. Create a class, named 'TestService' a file. export it as default.
3. open a new file name it 'ExtendsTestService', import the 'TestService' module. export it.
4. Register the ExtendsTestService as a service and inject it into any module.
5. Run the app on IE11.

**What is the expected behavior?**

App should run regularly.

**What is the motivation / use case for changing the behavior?**

It completely blocks the usage of using ES6 classes for writing services if IE11 needs to be supported.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
IE 11,
angular 1.6.0
babel 6.20.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
This behavior appears to be limited to instantiating services. Controllers written with the class - extends syntax all work as expected. This is a nasty little bug. **I've verified that if both classes are instantiated in the same file the bug disappears.**

**Comment by petebacondarwin** [comment]
Hi @charlesdeuter - could you create a minimal demonstration of the problem in a github repository that you can share?

**Comment by charlesdeuter** [comment]
Resolved this issue by using plain strings in the app.service call. We were previously using function.name to get the class name. It was changed in an unrelated fix for minification issues, but it resolved this issue also.
