### ISSUE TITLE
[Bug] An activated modal from first entry in ng-repeat elements does not use updated $scope variables

### ISSUE THREAD

**Issue by zinroc** [angular/angular.js#15495]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When the **first** ng-repeat element is clicked and 1) a $scope variable is change and 2) a modal appears, the modal that appears will not display the updated value for the $scope variable. 

(all elements after the first ng-repeated element call a modal with the correctly updated variable). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

When I run the template http://plnkr.co/edit/tpl:yBpEi4 I get Hello {{name}}! so the template is broken...

**What is the expected behavior?**
The modal called by the first ng-repeated element should have the updated $scope variable (just like a modal called from all subsequent elements after the first one).

**What is the motivation / use case for changing the behavior?**
N/A

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

This never worked. All Browsers (I think). angular 1.4.9

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

I use a hack to get around this by making a blank zeroth object in the array I am using in ng-repeat. That object has a boolean property that is checked by ng-if and ng-if prevents the first entry from being made. That way the first visible element is really the second entry in the ng-repeated array (which is not bugged)

**Comment by gkalpak** [comment]
We can't investigate this without a reproduction. The template (http://plnkr.co/edit/tpl:yBpEi4) is not broken btw. It works fine for me.

**Comment by zinroc** [comment]
![plunker](https://cloud.githubusercontent.com/assets/4406414/21108484/40a2426a-c063-11e6-9581-0f9790b5148c.png)


O.o

**Comment by zinroc** [comment]
got plnkr to work on  chrome (ff wasn't working) i'll make an example now.

**Comment by zinroc** [comment]
I tried making plunker launch a modal and it doesn't... 

http://plnkr.co/edit/kHi4kyqIo1JjtJlEEUDr

(I just copy pasted the example HTML code from http://getbootstrap.com/javascript/#modals "Live Demo" section)

**Comment by Narretz** [comment]
@zinroc Well you have some errors in the console you should fix. Angular is not defined and you need to include jquery.

**Comment by zinroc** [comment]
Just forget it -_- I'm not going to debug why the plunker angular template doesn't have angular defined...
