### ISSUE TITLE
Angular 1.6 breaking change to ngModelOptions

### ISSUE THREAD

**Issue by wesleycho** [angular/angular.js#15497]
I apologize in advance, as this is not normally the place for this sort of issue, but I actually am in need of a bit of guidance here as to how to patch a breaking change made to Angular 1.6 in UI Bootstrap while maintaining compatibility with Angular 1.5.

Currently in UI Bootstrap, we are allowing override of ngModelOptions with defaults specified by the user - for example, like https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L164-L166 . If someone is wrapping any of our components with a directive using ngModel & ngModelOptions, this will automatically wipe out the old behavior of it being not present, so it will not fallback by default but use the ngModelOptions from the parent directive.

Any suggestions?

**Comment by petebacondarwin** [comment]
Moving the discussion to https://github.com/angular-ui/bootstrap/issues/6360
