### ISSUE TITLE
multiple select rendering issue (IE 11 & Edge)

### ISSUE THREAD

**Issue by zachsteffens** [angular/angular.js#15498]
version 1.5.0
browsers affected: IE11 and Edge (might affect other versions, haven't tested)

I have two selects. One single, the other multiple.
After the binding model is changed for the multi select, the html options are no longer selectable.  
Simple example plnkr.
http://embed.plnkr.co/odNhSyVcpJNf148uw3tK/

this seems to be loosely related to 
#13239 and 
#11314

**Comment by Narretz** [comment]
Please test with latest 1.5.9. We fixed these issues you linked.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
