### ISSUE TITLE
Since version 1.6.0 - Angular Material Datepicker is blank until scrolled

### ISSUE THREAD

**Issue by steveharan** [angular/angular.js#15499]
Angular Material Datepicker is blank until you scroll

https://puu.sh/sNbCk/616eae9a00.png

**Comment by Narretz** [comment]
You should report this to https://github.com/angular/material as the fix must probably go into their library. Don't forget to include a demo, too.

**Comment by steveharan** [comment]
Will do.  I created this:

https://plnkr.co/edit/phZR6W?p=preview <https://plnkr.co/edit/phZR6W?p=preview>


I’ll post it on the material page.

Thanks

Steve
