### ISSUE TITLE
Cookie with CORS not working on Safari even if allowed in safari settings

### ISSUE THREAD

**Issue by vberthet** [angular/angular.js#15509]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**

On safari : Cookies aren't saved when using $cookies or $cookieStore when script is within an iframe from an other domain (CORS). 

CORS cookies are allowed in safari configuration.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

 * http://jsfiddle.net/nomzs9jp/
Doesn't works on safari 10, even with cross domain cookies allowed.

* https://jsfiddle.net/ARTsinn/Xbasz/
Which is similar, works perfectly on safari with same configuration.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Doesn't works on Safari 10 with angular 1.5 and 1.6
Older version not tested

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
The Angular demo uses a very very old version of Angular (that is no longer supported). Are you saying that the very same example does not work with the latest 1.5.x or 1.6.x version?

**Comment by vberthet** [comment]
It apparently works with with 1.5. 
So it's a mistake from me.

I've understand what's append, safari must be restarted when changing "tier cookies parameters" (reload / close tab doesn't works)

Sorry for that

**Comment by gkalpak** [comment]
No worries :smiley:
Thx for getting back!
