### ISSUE TITLE
ngBind and Model Functions

### ISSUE THREAD

**Issue by deadmann** [angular/angular.js#15500]
How long this gonna last? 

I mean come on, function play big part in program life, and they are vital inside the page...
and make a mess inside or controller is not nice always, make little things that we need to pass our model to, and then it implement that functionality from scratch make it a bigger mess, or call to somewhere that it's implemented already...

I do not know how you do stuff, but i first implement my entities, i care about their types, and i add functionality to them, other that just filling them with data, i use them for intellisense too... i use these models almost for anything any where. and sometime you define a getter/setter or a function within it... and as far as i test, i got disappointed. not that functions don't work, also getters won't work either.

would someone provide functionality that read from function not just scope variables :|

sample model in .ts:

```
class PersonVm {
    public id: number;
    private _firstname: string;
    public lastname: string;
    public position: PositionVm;
    public works: Array<WorkVm>;


    constructor(id: number, firstname: string, lastname: string, position: PositionVm, works: Array<WorkVm>) {
        this.setup();
        if (id != undefined)this.id = id;
        if (firstname != undefined)this._firstname = firstname;
        if (lastname != undefined)this.lastname = lastname;
        if (position != undefined)this.position = position;
        if (works != undefined)this.works = works;
    }

    public getFullName() {
        return this._firstname
        + Util.Utility.isNullOrUndefinedOrEmpty(this.lastname)
            ? ""
            : " " + this.lastname;
    }

    get fullName():string{
        return this.getFullName();
    }

    private setup() {
        this.id = 0;
        this._firstname = null;
        this.lastname = null;
        this.position = null;
        this.works = [];
    }
}
```

**Comment by gkalpak** [comment]
It is not clear what this issue is about. Is it requesting a new feature or is it pointing out a bug?
AFAICT, this is more likely a usage question (for example if used correctly, getters/setters work in most(/all?) places). 

For this type of general support questions, please use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

##
I am closing this as non-actionable. In case I have misinterpreted this and this indeed a bug report or feature request, feel free to provide some clarification below and will be happy to re-open and look into it :smiley:

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by deadmann** [comment]
it represent new feature... angular should check if the item is a function, then check for function returned value over time, otherwise check for itself (if it's a variable)...
or provide an other way to bind function inside view.

**Comment by gkalpak** [comment]
What is wrng with using getter/setter function? They should work.

**Comment by deadmann** [comment]
it returned empty using both brackets {{}} and ng-bind

**Comment by gkalpak** [comment]
Getters [work fine][1] for me. It is probably some other issue. Can you provide a runnable demo (e..g using CodePen, Plnkr etc)? 

[1]: https://codepen.io/ExpertSystem/pen/eBLbLj?editors=1010

**Comment by deadmann** [comment]
http://codepen.io/deadmann2/pen/gLBbGp/

**Comment by gkalpak** [comment]
The pen is broken (look out for errors in the console).

**Comment by deadmann** [comment]
ok recheck: http://codepen.io/deadmann2/pen/woYoep

**Comment by deadmann** [comment]
it was my issue somehow: 

i change this:
```
function () {
        return this.firstname
            + Util.Utility.isNullOrUndefinedOrEmpty(this.lastname)
            ? ""
            : " " + this.lastname;
    };
```
 to this:
```
function () {
        return this.firstname
            + (Util.Utility.isNullOrUndefinedOrEmpty(this.lastname)
            ? ""
            : " " + this.lastname);
    };
```

you were right... though the code pen version of angular is equal to mine, there shouldn't be any more problem. thank you for giving your time over my silly issue.

also since i'm here may i ask... is version 6 of angular animate unusable beside 1.5.8? i added through npm, and it fetch version 6, it generated errors... i switch to 1.5.8 and it got fixed.

**Comment by gkalpak** [comment]
Glad you got it working. Regarding the `ngAnimate` question, as with every external module (`ngAnimate`, `ngRoute`, `ngResource`, `ngSanitize` etc), you must always use the same version as the core Angular file. E.g. for Angular v1.5.8 use `ngAnimate` v1.5.8, for Angular v1.5.9 use `ngAnimate` v1.5.9 etc.

**Comment by deadmann** [comment]
i have custom made version of ng-resource from around 1.4.x and i have no issue with it :D as if you remind i asked you to add transformResult function, but still nothings there... (Angular change type of Models after transformResult function, and this rune whole the effort if i cast object to any specific type, so i made my custom version, that support such function, which get called after transformResponse...

i had no issue with angular 1.5.8
[angular-resource.zip](https://github.com/angular/angular.js/files/656079/angular-resource.zip)
