### ISSUE TITLE
$timeout.cancel still reporting unhandled promise

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [angular/angular.js#15505]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Current timeout.cancel (as of 1.6)
```
timeout.cancel = function(promise) {
      if (promise && promise.$$timeoutId in deferreds) {
        // Timeout cancels should not report an unhandled promise.
        deferreds[promise.$$timeoutId].promise.catch(noop);
        deferreds[promise.$$timeoutId].reject('canceled');
        delete deferreds[promise.$$timeoutId];
        return $browser.defer.cancel(promise.$$timeoutId);
      }
      return false;
    };
```

When combined with angular-ui-grid (4.0.0)

```
Grid.prototype.queueRefresh = function queueRefresh() {
                    var self = this;

                    if (self.refreshCanceller) {
                        $timeout.cancel(self.refreshCanceller);
                    }

                    self.refreshCanceller = $timeout(function () {
                        self.refreshCanvas(true);
                    });

                    self.refreshCanceller.then(function () {
                        self.refreshCanceller = null;
                    });

                    return self.refreshCanceller;
                };
```

It reports "Possibly unhandled rejection: canceled" in console. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Use Angular 1.6 and standard Angular UI grid with
```<div ui-grid="$ctrl.gridOptions" ui-grid-selection></div>```

which seems to trigger Grid.prototype.queueRefresh

**What is the expected behavior?**
It would look to me like angular-ui-grid implementation is still correct - it just applies "then" on a promise. Now, the angular handling, uses .catch(noop), and this, as the comment notes, should prevent from reporting of unhandled rejection (rejection is triggered right after). It seems to work just fine, if there is no .then() on the timeout, but as soon as then() is .specified, the .catch(noop) doesn't seem to work properly, that is : it does not prevent the error from appearing in console. 

**What is the motivation / use case for changing the behavior?**
The error suppression doesn't work properly.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.6 / Mac OS 10.12.1 Sierra / Firefox 50

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This is working as expected as far as Angular is concerned. By using `.then()` a new promise is created. Angular's `$timeout` has no control over that promise and thus can't prevent (and nor should it) a possibly unhandled rejection error. It is `uiGrid`'s responsibility to handle (or silence) the rejection if desirable. 

I understand this might seem inconvenient, but it is a documented breaking change and the benefits are important. BTW, (although not recommended) you can choose to disable the "Possibly Unhandled Rejection" errors, via [`$qProvider.errorOnUnhandledRejections(false)`][1].

[1]: https://docs.angularjs.org/api/ng/provider/$qProvider#errorOnUnhandledRejections

**Comment by sebastian-zarzycki-es** [comment]
Understood. That's what I suspected. Thanks.
