### ISSUE TITLE
Angular 1.2.0-rc3 and later break ng-repeat with jQuery sortable

### ISSUE THREAD

**Issue by sm-Fifteen** [angular/angular.js#15534]
**What is the current behavior?**

When using a jquery-sortable property in combination with an ng-repeat directive, the ng-repeat view may become desynchronized while doing certain manipulations. This does not occur with versions of angular older than 1.2.0-rc3.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See [this plunkr for a working example](https://plnkr.co/edit/zXIdVC). Minimal working example taken from [here](
http://www.smartjava.org/content/drag-and-drop-angularjs-using-jquery-ui).

**What is the expected behavior?**

The ng-repeat directive should mirror the model properly once $scope.$apply is fired, regardless of its state before updating.

**What is the motivation / use case for changing the behavior?**

Regression on expected behavior.

**Which versions of Angular, and which browser / OS are affected by this issue?**

Version 1.2.0-rc3 onwards.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

This does not seem to happen with ui-sortable, only with vanilla jQuery-ui.

**Comment by gkalpak** [comment]
Unfortunately, jQuery/jQuery-ui plugins are not guaranteed to work out of the box (not even if there is a blogpost that says they do). And if they (seem to) work on one version, there is no guarantee they will working in future ones.

In this particular case, you are not supposed to move `ngRepeat` DOM nodes around as that can break things (and that is what happens here).

You should use Angular-specific components/plugins (eg. [ui-sortable][1]).

(Also, note that 1.2.x is a pretty old version and not maintained any more with the exception of important security fixes.)

[1]: http://angular-ui.github.io/ui-sortable/

**Comment by sm-Fifteen** [comment]
Ah, so changing the DOM is the cause of the problem, I see. I can understand how regressions regarding mixing Angular with external DOM modifications are expected to happen and why they wouldn't be considered worth fixing.

Thanks for replying.
