### ISSUE TITLE
Error when using SVG in the component template

### ISSUE THREAD

**Issue by raciasolvo** [angular/angular.js#15539]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
*bug* (I am not sure)

**What is the current behavior?**
The error appears in the console: Error: <path> attribute d: Expected number, "M 100,{{$ctrl.test}} L…".   angular.js:3505 when using SVG in the component template. The SVG is displayed correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
[demo of the problem](http://stackoverflow.com/questions/41272150/error-when-using-svg-in-the-component-templatel)

**What is the expected behavior?**
No errors.

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Angular 1.6.0,
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
This is expected behavior, because certain attributes have restriction on the values they accept. You can use [`ngAttr`][1] to circumvent that. I have also answered on [StackOverflow][2].

[1]: https://docs.angularjs.org/guide/interpolation#-ngattr-for-binding-to-arbitrary-attributes
[2]: http://stackoverflow.com/questions/41272150/error-when-using-svg-in-the-component-templatel
