### ISSUE TITLE
Routing broken when upgrading from 1.5.8 to 1.6.0

### ISSUE THREAD

**Issue by gimmi** [angular/angular.js#15540]
Hi,

Seems that `ngRoute` is broken with angular 1.6. I've created a repro here:

http://gianmarco.gherardi.me/html-sandbox/angularjs-16-bug/index.html

angular 1.5 build the following correct links:

* `index15.html#/home`
* `index15.html#/roles`

but with angular 1.6 the links are broken:

* `index16.html#!/home` (note the extra `!`)
* `index16.html#!/home#%2Froles` (completely broken)

**Comment by gkalpak** [comment]
This is expected behavior (caused by [this breaking change][1]).

[1]: https://docs.angularjs.org/guide/migration#commit-aa077e8
