### ISSUE TITLE
Routing problem in 1.6.x

### ISSUE THREAD

**Issue by SquaredCircleHunter** [angular/angular.js#15549]
Routing problem in 1.6.x

Please check http://www.w3schools.com/angular/tryit.asp?filename=try_ng_routing_view1

If you replace 1.4.8 by 1.5.9 it still works

Broken as from 1.6.0

**Comment by edenferreira** [comment]
Because of [aa077e](https://github.com/angular/angular.js/commit/aa077e81129c740041438688dff2e8d20c3d7b52) the default has prefix is now '!'.
If you change:
```html
<p><a href="#/">Main</a></p>

<a href="#red">Red</a>
<a href="#green">Green</a>
<a href="#blue">Blue</a>
```
to:
```html
<p><a href="#/">Main</a></p>

<a href="#!/red">Red</a>
<a href="#!/green">Green</a>
<a href="#!/blue">Blue</a>
```
or add:
```
app.config(['$locationProvider', function($locationProvider) {
  $locationProvider.hashPrefix("");
}]);
```
It will work.

**Comment by SquaredCircleHunter** [comment]
Thanks a lot!!!
