### ISSUE TITLE
Internet Explorer infinite digest with location change

### ISSUE THREAD

**Issue by thetrevdev** [angular/angular.js#15556]
Bug

**Current behavior**

http://plnkr.co/edit/7SldRRsrYFO32hiG9abV?p=preview
Infinite digest error in Internet Explorer console after button click
**[$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []**

**Expected behavior**

Location changes without error

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/7SldRRsrYFO32hiG9abV?p=preview with Internet Explorer
Check error console after button click.
Note: this happens when the location change occurs during an $evalAsync 

**What is the motivation / use case for changing the behavior?**
We have a large app with different redirect scenarios that may or may not be local to our app.  We wish to set location.href.  

* **Angular version:**  1.5/1.6

* **Browser:** [ IE 11 ] 

In internet explorer the hashchange event fires asynchronously.  this causes the $locationWatch to think that the $location url was updated as it doesn't match $browser url.   It seems like the location logic should know whether a url change occured via $location setters

**Relevant Code:
https://github.com/angular/angular.js/blob/master/src/ng/location.js#L970

**Comment by gkalpak** [comment]
> In internet explorer the hashchange event fires asynchronously.

Actually, this has nothing to do with the `hashchange` event being fired asynchronously (the same happens in Chrome as well). The problem is that in IE11 there is no `popstate` event fired when only the hash changes, which is fired (synchronously) in other browsers. This is a [known bug][1] in IE11 and there is no intention to fix it 😞

[1]: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/

**Comment by Narretz** [comment]
@thetrevdev Do you have a workaround for this? It looks like it's difficult to fix at this point.

**Comment by gkalpak** [comment]
> It seems like the location logic should know whether a url change occured via `$location` setters

This sounds reasonable. Based on that, I have a potential fix [here][1]. (I still need to add tests, but it didn't break any of the existing tests, which is a good sign :smiley:)
Here is the [updated plnkr][2] with the fix.

[1]: https://github.com/gkalpak/angular.js/commit/99a3634ff380449633bb2634716d1bae8fd5f1cd?w=1
[2]: http://plnkr.co/edit/Nhx5GoCcc2z7jcbjYexB?p=preview

**Comment by gkalpak** [comment]
There you go: #15561

**Comment by thetrevdev** [comment]
Tested it in our app.  Looks good in our tests.

Thanks!
