### ISSUE TITLE
Can not get header in response headers when upgrade to Angular final

### ISSUE THREAD

**Issue by Sophia-nguyen** [angular/angular.js#15551]
Hi, I have a problem when get response headers in my app.

In API:
```
res.header("Access-Control-Allow-Origin", "*");
res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
res.header("Access-Control-Allow-Methods", "*");
res.header("Access-Control-Expose-Headers", "WWW-Authenticate");
```

Send request and open debug mode in Chrome, I see:
![image](https://cloud.githubusercontent.com/assets/11731312/21517635/29916332-cd13-11e6-87ed-255041d1a36b.png)

And in Front_end code:

```
this.http.get(url, options)
               .map(
                    res => res
                )
                .subscribe(
                    (res) => {},
                    (err) => {
                         let authenticateErr = res.headers.get("WWW-Authenticate");
                        //authenticateErr = null;
                     });
```
And err.heades that I see:
![image](https://cloud.githubusercontent.com/assets/11731312/21517695/c62a4aec-cd13-11e6-9b9a-796ddeed1f87.png)

My code is work corectly when I use Angular beta6. When I upgrade to angular rc4, and final it don't work.
How can I fix this issue, anyone can help me.
Thanks

**Comment by gkalpak** [comment]
Wrong repository (this is for Angular 1.x). The Angular (2+) repository is: https://github.com/angular/angular
