### ISSUE TITLE
Calendar not rendering Dates

### ISSUE THREAD

**Issue by edsiteproctor** [angular/angular.js#15557]
Calendar note rendering dates -- Angular 1.6.1, Angular Material 1.1.1

http://plnkr.co/edit/ZTZoYOtGOmNkq415Asia?p=preview

**Comment by gkalpak** [comment]
This doesn't work with 1.6.0 either, which means that ngMaterial v1.1.1 is affected by some breaking change in Angular v1.6.x. Can you please reopen this in the [ngMaterial repo][1]?

[1]: https://github.com/angular/material

**Comment by mgol** [comment]
It works properly on Material `master`: http://plnkr.co/edit/tQI0RBUSNwK2OEh59aha?p=preview. You need to wait for Material 1.1.2, version 1.1.1 is not compatible with Angular 1.6 (or with Angular 1.5.10+ with the [`preAssignBindingsEnabled`](https://docs.angularjs.org/api/ng/provider/$compileProvider#preAssignBindingsEnabled) flag enabled).
