### ISSUE TITLE
server side rendering ng1-server

### ISSUE THREAD

**Issue by a-lucas** [angular/angular.js#15566]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Feature

I have been working on a server-side rendering engine for ng1 apps, and the projects gets very stable now. If you guys want to check it out, and give me insights / test / experiment it, that would be very appreciated ! https://github.com/ng-consult/ng1-server

**What is the current behavior?**

No server side rendering

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

no bugs

**What is the expected behavior?**

server-side rendering

**What is the motivation / use case for changing the behavior?**

web-apps + SEO === websites

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Hi,
it's always great to see 3rd party libraries for Angular, especially for a "hot topic" like server side rendering. There's an open discussion about this, with a few similar libraries: https://github.com/angular/angular.js/issues/2104 You may want to post there.
Once your project takes of a bit, you can also open a PR which adds it to the list of 3rd party libs (https://code.angularjs.org/snapshot/docs/guide/external-resources)

I'm gonna close this now, as this repo is for bug fixes and feature requests only. Thanks for your understanding.

**Comment by a-lucas** [comment]
Thanks @Narretz ! Just did that.
