### ISSUE TITLE
Change value from other javascript library doesnt update $scope variable

### ISSUE THREAD

**Issue by rafgugi** [angular/angular.js#15565]
I have `"angular": "^1.5.9",` in my `bower.json` and I work as a team. everything works fine until my program and my friend program do different behavior, and it occur when my friend use the newest angular.js (1.6.1). I use `ng-model` to a `<select>` tag which I use selectize plugin too.

```php
<select ng-model="inventory" id="inventory">
  <option value="1">Rice</option>
  <option value="2">Pepper</option>
</select>

<button type="button" class="btn btn-primary" ng-click="add_item()">
  Add
</button>
...
<script>
  app.controller("pembelian", function($scope) {
    $scope.add_item = function() {
      console.log($scope.inventory);
    }
    $scope.inventorySelectize = $("#inventory").selectize({})[0].selectize;
  })
</script>
```
when I use angular.js 1.5.9, console.log show inventory id. but when I use 1.6.1, console.log show `null`

Operating System: Windows 10, Ubuntu 16.04

**Comment by grimly** [comment]
Hello, this is why you never ever use jquery and their plugins in an angular project.
You must wrap your select field into a directive that would trigger your jquery plugin on the controller initialisation (or on the link function) and make sure you update the ngModel view value whenever the plugin changes its value.

If you're lazy, you might want to look at different implementations that may fit your needs :
* https://github.com/machineboy2045/angular-selectize
* https://github.com/evgenyrodionov/ng-selectize

**Comment by rafgugi** [comment]
Cool, thanks. Maybe the bug is not important to be noticed because angular normally fails when used alongside jquery and their plugins. And yes I do update ngModel after selectize changes the value

**Comment by Narretz** [comment]
> this is why you never ever use jquery and their plugins in an angular project. 

This is hyperbole. Many plugins can be used if they are wrapped with a directive that does a scope.$apply when angular data needs to be updated.

**Comment by rafgugi** [comment]
I tried `$scope.apply()` but doesnt work at that time. so I get the value from jquery only for that case
