### ISSUE TITLE
Bottom Sheet example not going away with down swipe

### ISSUE THREAD

**Issue by Jodes81** [angular/angular.js#15563]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

List demo does not go away with down swipe. Grid demo does not go away at all - with down swipe or touch elsewhere.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

1. Go to https://material.angularjs.org/latest/demo/bottomSheet
2. Tap "show as list" button or "show as grid"
3. Swipe down on menu that appears, or outside, but still in "basic usage" box, or outside that.

**What is the expected behavior?**

Slides back down like when clicked outside of menu but in "basic usage" body

**What is the motivation / use case for changing the behavior?**

Essential behaviour

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Tested on above URL as at 7:27am GMT 30the Dec 2016 
Tested on Samsung Tab 4, Chrome browser 55.0.2883.91

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

Edit: Likely cause: only left swipe works on swipe demos:
https://material.angularjs.org/latest/demo/swipe

**Comment by gkalpak** [comment]
This is not related to core Angular. Please reopen in the `ngMaterial` repository: https://github.com/angular/material
