### ISSUE TITLE
Angular 1.x support timeline announcement is direly needed.

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [angular/angular.js#15569]
We have many clients that asks us about the expected support dates and there's no single reliable resource we can point them to. There are various inconclusive information scattered around the internet. 

This increases the reluctance to use Angular (whether 1 or 2+) in new projects. 

Obviously, there's a hidden wish that business would migrate early to 2+, but it cannot be achieved by lack of information.

**Comment by Narretz** [comment]
Can you elaborate what exactly you need to know? Do you mean security updates?

**Comment by Narretz** [comment]
Even if the project was abandoned this would not mean that the projects
stop working.
Wrt browser support. There will be no changes to the bottom end support.
For current browser we will evaluate changes for modern APIs but since
there are no BC for new Javascript versions there is nothing to worry
about.
I will bring this topic up in the next meeting

**Comment by sebastian-zarzycki-es** [comment]
As a developer I understand that and I don't expect Angular 1.x to "break" anytime soon, even if no new versions are released. But for business, they really tend to rely on these "official statements" and I think Angular community would benefit from one, this way or another. 

Simply, the statements made until now (about the traffic majority and whatnot), are not precise enough for business to rely on. 

So, that said, I would be grateful for bringing this up and if that could result in some kind of statement, it would mean a lot.

**Comment by tommck** [comment]
Yeah, I'm on a large angular 1.X project that's not production yet, but this will be in existence for a LONG time (large Enterprise).  It would be interesting to have any extra information in this vein

**Comment by Narretz** [comment]
While there's nothing substantial yet, the Angular team is aware of this and there will definitely be more concrete info about this. I'm closing this issue in the meantime.

**Comment by jrvidal** [comment]
@Narretz Thanks for the response. It would be nice to leave a notice here of said info when it's available, for whoever is already tracking this issue.

**Comment by sellmeadog** [comment]
Not sure if this is the appropriate place for this comment, but I also work for a large enterprise with a significant investment into Angular 1.x and we are now starting a large system integration project that will deliver numerous enhanced UI projects.  I am trying to encourage the adoption of Angular 2.x for these efforts but without a published support roadmap, there is no desire from the team to upgrade and retrain the development staff on the new framework.  Any type of official service life roadmap for 1.x would go a long way in pushing for the adoption of 2.x and beyond.

**Comment by robwormald** [comment]
@sellmeadog we're not ready to make any official announcements as of yet, but that specific feedback is definitely useful for our planning, thanks!

**Comment by slagod** [comment]
Guys, why you close the issue without providing information. You cannot announce anything now - that's fine, but I think you should leave the issue open until announcement is made.

**Comment by RubyRabelle** [comment]
I am also confused about this.  I have been researching for several months, with the impression that development was essentially over (stable) for AngularJS in favor of Angular2 (or 4?), and now 1.6.5 has been released and I'm seeing discussions about 1.7.    What direction is this project going?

**Comment by tommck** [comment]
@RubyRabelle, it's my understanding that the 1.X code is continually being updated to bring more and more 2+ concepts to the 1.X code base so that it will be easier to migrate to 2+ in the future.

**Comment by stuartellis** [comment]
This is still a live issue, at least for me. I am currently looking at a non-trivial corporate system on Angular 1, and have to make specific recommendations. In the absence of any clear messages, I have no basis to either push for a migration to Angular 4, or support a decision to continue developing the current AngularJS codebase for the next few years.

**Comment by tommck** [comment]
Yeah, I'm in a LARGE implementation of 1.x and getting questions from management now about the long-term support situation

**Comment by StephenFluin** [comment]
@tommck @stuartellis @sebastian-zarzycki-es 

We have solved a number of the fundamental problems with AngularJS in Angular (such as change detection speed at scale), and there are a lot of great new capabilities that are driving the majority of new projects to adopt Angular. We are currently continuing to support and maintain and develop AngularJS, but we would definitely love to hear from you what would you like to see. 

The fundamental issue is that "support" means something different to everyone. Is it validation or invalidation of a technical decision (and how does the idea of "support" play into this)? Does it mean security patches? The attack surface of AngularJS is relatively small, although Angular's is even smaller, so it is unlikely there will be much here. Does it mean that we should introduce breaking changes to take advantage of new browser features? 

If there are a set of promises or a timeline that you would like to see, please email me at devrel@angular.io.

**Comment by sebastian-zarzycki** [comment]
I think everyone understands that there's a upper boundary of new features/enhancements you can put into AngularJS - it's obvious that most of the power is / should be redirected to new angular. There's also only so much you can improve, given the current architecture, digest model, and so on.

As for me, by support, I mean quick reaction when one of below happens:
- security issue / flaw that needs to be adressed
- new browser / engine released and angularjs doesn't play (for whatever reason) nicely with it
- new browser / engine released offering some major improvements on an engine level, and the effort to support it from angularjs code would be relatively small.

When talking about support, our client's are mostly concerned that it will simply "stop working" at some near point in future. I understand, that from technical point of view, it's rather unlikely. But it's one developer's / project manager's opinion vs an official statement you could produce on your website, even if its "support" part would be exaggerated a bit.

**Comment by tommck** [comment]
I'd like to make sure that bug fixes will still be made (yes, I know that pull requests are welcome, but not always possible).

I'd also like to see a statement we can point to that tells us what the end goal is.
I know at one point the idea was to keep adding features to AngularJS easier to migrate to Angular.  Adding components, for instance was part of this.  Is the goal still to make AngularJS more and more like Angular until it makes no more sense?

Are we going to expect to see any new features, or are we just at maintenance mode at this point?

I know this is an open source project, but it obviously has a lot of backing from the Angular team. So, when will those resources go away?  That's kind of the "support" I think of.

I can always fork the project, but most companies would not be very excited about that.

**Comment by stuartellis** [comment]
@StephenFluin - Thank you for responding. I have now emailed you a longer message.

I think that the TLDR for us is that the basic expectation of non-technical managers is that a deployed system will continue to work in the same way until it hits an expiry date, and they are usually orientated to hard schedules, costs and specific (ultimately contractual) guarantees. If we can say "Angular will be maintained without planned breakage until the date X, and we can't guarantee after that", then it is possible to feed this into the corporate decision-making machine of proposals, projects and budgets.

**Comment by andygup** [comment]
FYI, here's the latest update on v1.7 and AngularJS long term support https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c
