### ISSUE TITLE
Memory Leaks in angular js application

### ISSUE THREAD

**Issue by steel119** [angular/angular.js#15576]
Hi,

We tried 'Recording allocation timeline' for our angular 1.5 application and found wired behavior for almost all our controllers .  I can see several instances of each of the controller.
Does it mean that the  application has memory leaks?
If Yes, what can be the reason for controllers are not dying ? 
How can i go around solving this problem ?

Please find the 'Record Allocation Timeline' snapshot attached.

![recordallocationheap](https://cloud.githubusercontent.com/assets/16788416/21646791/97b179f4-d265-11e6-995b-8b63df152329.jpg)

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
