### ISSUE TITLE
Errors throw from $onChanges result in an array passed to $exceptionHandler

### ISSUE THREAD

**Issue by jbedard** [angular/angular.js#15578]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
an error thrown in an `$onChanges` method results in [an array being thrown](https://github.com/angular/angular.js/blob/b77defde81fc265c13fa504dc78b41a43997abf4/src/ng/compile.js#L1528) which will result in `$exceptionHandler(arrayOfErrors)` 

**What is the expected behavior?**
`Error` objects are passed to `$exceptionHandler`

**What is the motivation / use case for changing the behavior?**
make `$exceptionHandler` more predictable / consistent / follow documentation

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
1.5+

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Maybe each error in the array is passed to `$exceptionHandler` separately?
Maybe the array of errors is wrapped in an `Error` before being thrown?
Or document that `$exceptionHandler` might be passed an array?

**Comment by IgorAufricht** [comment]
The behaviour also seems to be different based on when the error is thrown.

Consider this example:
```
<!DOCTYPE html>
<html>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
<body>

<div ng-app="testModule">
  <div ng-controller="TestController">
    <test-component binding="binding"></test-component>
  </div>
</div>
<script>
angular.module('testModule', [])
  .controller('TestController', function ($scope) {
    setTimeout(function() {
      console.log('updating binding');
      $scope.binding = 'value';
      $scope.$digest();
    }, 500);
  })
  .component('testComponent', {
    bindings: {
      binding: '<'
    },
    controller: function () {
      this.$onChanges = function (changesObj) {
        throw new Error('Error message');
      };
    }
  });

</script>
</body>
</html>
```

If you [run the example above](https://www.w3schools.com/code/tryit.asp?filename=FJSLGXQCNE4T), you will get two errors in console. One is thrown on the initialization of the component, while the second one is thrown when the binding gest updated. The first error is an actual `Error` (which is correct), while the second one is an array (which is not correct).

**Comment by gkalpak** [comment]
Yeah, tbh it seems reasonable to pass each error to the `$exceptionHandler` immediately (i.e. the same we do for each watcher in `$digest`). Not sure why we did it this way 😕
