### ISSUE TITLE
ngResource timeout property has no effect on version 1.4.14

### ISSUE THREAD

**Issue by teoiliev** [angular/angular.js#15580]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Timeout value for angular resource has no effect on ngResource 1.4.14.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
Set any valid number value for timeout of angular resource.
Simulate a resource load time delay.
The resource will still resolve.

**What is the expected behavior?**
The resource promise should fail in the same manner as within the http service after the timeout previously defined.  

**What is the motivation / use case for changing the behavior?**
Currently the timeout property of an angular resource cannot be used.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Version affected 1.4.14
On version 1.4.1 this works fine.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
The obvious difference is here https://github.com/angular/angular.js/blob/v1.4.14/src/ngResource/resource.js#L582 on line 582 where a check for input validity is performed but the timeout value is never pushed to the httpConfig which is to be given to the $http service. I believe a simple else containing                   `httpConfig[key] = copy(value);` would suffice to fix the issue.

**Comment by gkalpak** [comment]
v1.4.x is not maintained any more (i.e. doesn't receive updates except for critical security vulnerabilities). The timeout story for `$resource` has been improved and things should work as expected on the latest 1.5.x/1.6.x versions.
