### ISSUE TITLE
waitForAngular does not wait for $httpBackend pass through requests 

### ISSUE THREAD

**Issue by mike-bresnahan** [angular/angular.js#15593]
This change https://github.com/angular/angular.js/pull/13124 related to this issue https://github.com/angular/angular.js/issues/1434 caused this protractor issue https://github.com/angular/protractor/issues/3948.

Node v6.9.2
Protractor 4.0.14
Angular 1.5.8
Chrome 55.0.2883.87
Windows 7

**Comment by petebacondarwin** [comment]
I think we need to come up with a better way to get hold of the "original" `httpBackend` service for this.

**Comment by petebacondarwin** [comment]
I think the easiest option is to change the `ngMock` implementation to be a decorator that caches the original `$httpBackend` service somewhere that `ngMockE2E` can use.

**Comment by mike-bresnahan** [comment]
Couldn't ngMock's decorator then also support a passThrough() API similar to ngMockE2E's? Then there might be no need to load ngMockE2E into a unit/integration test. 

BTW, I personally have no need to use passThrough() in unit/integration tests and the whole idea smells bad to me, but there seems to be some momentum for it.

**Comment by petebacondarwin** [comment]
One could add the `passThrough` to `ngMock` but as you say it is not a good idea for unit tests, so I would rather not add it to the public API. Instead, we accepted that people are using the `ngMockE2E` in this way and letting them fudge it.

**Comment by petebacondarwin** [comment]
@mike-bresnahan - you can see I have put together a PR for this. Can you take a look?

**Comment by mike-bresnahan** [comment]
Interestingly, this issue was fixed in 1.6 by https://github.com/angular/angular.js/commit/4f6f2bce4ac93b85320e42e5023c09d099779b7d

**Comment by gkalpak** [comment]
Since #15601, there should be one `$browser` instance.

**Comment by mike-bresnahan** [comment]
Yes I understand that. I was just trying to be clear that 4f6f2bc did not fix the "2 $browser instance" issue, but it did fix the outstandingRequestCount issue.

**Comment by petebacondarwin** [comment]
@mike-bresnahan glad that we were able to help.
