### ISSUE TITLE
Directive ngValue sometimes do not update value attribute

### ISSUE THREAD

**Issue by DmitryKrekota** [angular/angular.js#15603]
- It is a bug.

- Current behavior: directive ngValue sometimes do not update value attribute. In my examples below, I clear $rootScope.someText value with delete operator (or set $rootScope.someText to undefined) and ngValue directive do not update view value.

- Demo:
Example in CodePen: https://codepen.io/dmitry_krekota/pen/NdNYjr
Screen record with bug reproduce steps (12 seconds): https://drive.google.com/file/d/0Bxtv10NlSOEbeXJWWnhZc1A0anM/view
Also, you can download the html file with demo: https://cl.ly/1h0F3l2P032K/download/demo.html

- Expected behavior: ngValue must set attribute value to '', when when there is no value in $rootScope.someText variable.

- Environment: Windows 7, Chrome 56

- Angular version: 1.6.1

**Comment by gkalpak** [comment]
jQuery handles it in th same way (`.prop('value', undefined)` is the same as `.prop('value')`). It seems we need special logic inside `ngValue` to convert undefined values to `null` (or something).
