### ISSUE TITLE
$scope attribute change dom not reflected

### ISSUE THREAD

**Issue by dashng** [angular/angular.js#15623]
**Do you want to request a *feature* or report a *bug*?**
*bug**

**What is the current behavior?**
$scope $$watchers is null and when I change the $scope attribute directive not reflected.

```
$form_el_row.on('click', function(event){
                var $el =$(this);
                $('div[name="form_el_row"]').removeClass('active');
                $el.addClass('active');
                //edit_attrs($el);
                $timeout(function () {
                    
                    $scope.element = $el;
                    $scope.data = $el.data('data');
                    //$scope.$apply();
                }, 0);
                event.stopPropagation();
            });
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
Hi,
If you think this is a bug in Angular, please create a minimal example in a plnkr.co or similar that shows the problem. If you have a question on how to build something, please try one of the listed Support Channels. Thanks!
