### ISSUE TITLE
missing required controllers doesn't result in an exception in tests

### ISSUE THREAD

**Issue by tommck** [angular/angular.js#15629]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
neither the $compile() or subsequent $digest() calls will throw an exception when using a directive with an unsatisfied "require" requirement.  NOTE: This is a change from 1.5.10 to 1.6.x

Plunkr: http://plnkr.co/edit/YaJbS1?p=preview

**What is the expected behavior?**
I expect it to throw when something that's required is not present

**What is the motivation / use case for changing the behavior?**
It used to work that way and the directive documentation says that $compile with throw (though it takes an extra digest to throw when you use a templateUrl - also doesn't throw if you don't have a 'link' method)

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
All Versions 1.6.x

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
In my plunker, you can copy the context of "index-161.html" to "index.html" to test 1.6.1, and "index-1510.html" to test 1.5.10

**Comment by frederikprijck** [comment]
@tommck I dont think if it's related to the unsatisfied `require` , as I removed the require and still have the same result:

http://plnkr.co/edit/ls4n6G?p=preview

Afaik it's failing due to missing backend request for the template. Have a look at:
http://plnkr.co/edit/KxTt5A?p=preview

In this case, both versions are not throwing.

**Comment by gkalpak** [comment]
There are a couple of things to mention:

1. WRT to `require: ...`, it is enforced (which means it will throw an error if not satisfied) **only** when the required controllers can be accessed from the directive. This means only when there is a pre- or post-linking function (which needs to be passed the required controllers) or when we need to bind the controllers to this directive's controller (i.e. there is a controller, `bindToController` is truthy and `require` is an object).

From that point of view everything works as intended in both versions (1.5.10, 1.6.1). It is debatable whether it is a better idea to always enforce `require`, but this is a discussion for another issue (feel free to open one btw).

2. The reason you see no error thrown in 1.6.1 is that (as a result of e13eeab) we are overzealously silencing errors thrown while fetching and compiling a remote template (see https://github.com/angular/angular.js/commit/e13eeabd7e34a78becec06cfbe72c23f2dcb85f9#diff-a732922b631efed1b9f33a24082ae0dbR3138).

This needs to be fixed 😟

**Comment by tommck** [comment]
1) Thanks for the incredibly fast work.
2) as far as it not being related to "require", I was trying to reproduce the exact situation I have with code on my job. The only problem is the require not being satisfied there.
