### ISSUE TITLE
Function is not passing values

### ISSUE THREAD

**Issue by kribalaji** [angular/angular.js#15653]
Hi Team,
I am new to Angular JS and i am in learning phase.  I have written simple code to pass values to my page but values are not passing from function. Please do let me know where is  the issue in my code?

`<!DOCTYPE html>
<html>
    <head>
    <title>
        Welcome to input form
        </title>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js">
        </script>
    </head>
    <body>
    <div ng-app="myapp" ng-controller="mycontol2">
       <table border="10">
        <tr>
            <td>
            Enter the First name:
            </td>
            <td>
            <input type="text" ng-model="firstname">
            </td>
        </tr>
        <tr>
           <td>
                Enter the last name:
           </td>
           <td>
                <input type="text" ng-model="lastname">
           </td>
                
        </tr>
        <tr>  
          <td>
                Enter the Address:
           </td>
            <td>
               <input type ="text" ng-model="address2">
            </td>
        </tr>
      </table>        
        </div>
        <script>
		angular.model("myapp",[])
		.controller("mycontol2",function($scope){
		     
            $scope.firstname = "balaji";
     		$scope.lastname =  "krishnamoorthy";
			$scope.address2 = "Address new ";
			return;
            
        }
        </script>
    </body>
</html>`

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
