### ISSUE TITLE
using function with ng-repeat causing infinite digest cycle

### ISSUE THREAD

**Issue by haseebshahid** [angular/angular.js#15659]
I have the following plunkr. 

https://plnkr.co/edit/Tt7sWW06GG08tdJu72Fg?p=preview

Just wanted to have a simple navar showing categories and sub-categories but the **digest cycle** and **dirty checking** is making it go to an infinite loop.

I am using a function with ng-repeat that in turn resolves a promise and returns an array object.

If one opens console, the errors of infinite digest cycle can be seen. The method attached to ng-repeat is stuck inside an infinite kind of loop and this distorts the display of data.

The sub-categories shown in the navbar are repeating and actually belong to the last category but somehow are being shown for each one of the  category.

The API for fetching sub-category and categories are two different ones and I dont have any flexibility to change them.

Any help will be appreciated! I am not returning a new object in every iteration, I am returning a reference of an object. How to possibly overcome such kind of situation? Is there something wrong with how  I am using ng-repeat. Should we not use ng-repeat with a function when it is nested?

The inner ng-repeat depends upon the outer ng-repeat data.

Note: Please expand the plunkr into a fuller window to see the menu on the left.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
