### ISSUE TITLE
ng-click issue in mac safari browser

### ISSUE THREAD

**Issue by anilpallikonda4** [angular/angular.js#15657]
Hi All,

Angular click event not working with mac safari browser.
Please find below link and help someone on this.

http://plnkr.co/edit/QNKZDT9N5k2tQaRrFlwY?p=preview

**Comment by gkalpak** [comment]
It works for me (make sure `alert()` is not somehow supressed on your browser).
`ngClick` binds to the native `click` event, so if a native event handler works, so should `ngClick`.

(I think there were some issues were the `click` event was not fired on `<li>` (under certain circumstances) in very old MobileSafari versions, but that is probably not related to your issue.)
