### ISSUE TITLE
[Feature Request] Save Angular template url file with ".ng" extension

### ISSUE THREAD

**Issue by GNSubrahmanyam** [angular/angular.js#15650]
Hi,

Feature: "Save Angular template url file with "`.ng`" extension"

If we get this feature that will be better. Instead of saving Angular Template URL with `.html` or` .htm` if we can save with "`.ng`" that would be very easy to differentiate between HTML Pages and Angular Template.

Thanks in Advance.

**Comment by gkalpak** [comment]
There is no restriction in the file type. AngularJS templates are just plain test files (that happen to contain HTML code). If you can get your server to correctly serve '.ng' files, AngularJS won't mind.

Note that using a different extension might affect code highlighting and autocomplete in your editor/IDE. In the past, I have used a `.tmpl.html` suffix for templates, which preserves the `.html` extension. Using `.tpl.html` is also common. But just `.html` is the preferred way these days, I think.

Anyway, AngularJS doesn't put any restrictions on the file extension used.
