### ISSUE TITLE
angular.js/docs/content/tutorial/step_04.ngdoc reference another a1 styleguide like this one for a1 https://angular.io/styleguide

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular.js#15666]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
https://docs.angularjs.org/tutorial/step_04
We will keep it short, not going into great detail on every good practice and convention. These principles are explained in great detail in the AngularJS Style Guide, which also contains many more techniques for effectively organizing AngularJS codebases.
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
link to that styleguide is wrong, personal promotion, tool promotion, vendor promotion and site promotion. this goes against the principles of open source. this is called piggy-backing. an analogy is when steve ballmer named linux a cancer.

**What is the expected behavior?**
i expect a link to an angular 1 created styleguide like this one https://angular.io/styleguide

**What is the motivation / use case for changing the behavior?**
fairness and kindness

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
a1

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
delete the reference in the a1 documentation and link to an official a1 styleguide on the angularjs site.

**Comment by petebacondarwin** [comment]
In the interests of community contribution, on which Angular has a long track record, we decided a long time back that we would promote this style guide rather than spending our resources on duplicating it.

The Angular team has worked with John on his AngularJS styleguide and he has consulted with us and a number of other Angular experts on the best practices. Moreover he is happy to take contributions from the community, so it is really just a place where everyone in the Angular world can collaborate on an agreed set of styles.

It is interesting to note that the Angular styleguide (on angular.io) was actually mostly written by John anyway - see https://github.com/angular/angular.io/blame/master/public/docs/ts/latest/guide/style-guide.jade.

**Comment by frederikprijck** [comment]
Just my 2 cents: I gotta admit I'm a big fan of Todd's (https://github.com/toddmotto/angular-styleguide) styleguide. I think it has some great additions to John's but I do think it's not one to have in the docs as it's ES2015 only.

**Comment by petebacondarwin** [comment]
I also like Todd's work. He and I often discuss these things. I don't have a problem with including a link to his styleguide too. Feel free to submit a PR.

The point I wanted to make here was that referencing a community built styleguide is not anti-OSS.

@NilsHolger - do you have a view on this?

**Comment by NilsHolger** [comment]
@petebacondarwin whatever is best for angular's growth and reputation is my view. the styleguide belongs in the official angular documentation.i personally appreciate minko, honest, honorable, knowledgeable https://mgechev.github.io/angularjs-style-guide/. maybe we can take the best components from all 3 styleguides and create a new one for the official angular 1 documentation or link to all 3?

**Comment by petebacondarwin** [comment]
Unless you want to take this on and then maintain it @NilsHolger I don't really see how feasible that would be. Instead, I am happy to link to any well maintained style guides from the docs.

**Comment by NilsHolger** [comment]
can we temporarily link to all three style guides in the angularjs
documentation, alphabetically sorted? i am interested in compiling the best
components from all three style guides in one and have them referenced
directly in our documentation. maybe there are others who are interested in
participating? it's all a question of time, surely an excellent exercise,
working through all three. actually i enjoy the code written by the angular
team, couldn't that be taken as a best practice for writing angular code?
it is concise, expressive and beautiful code. google standards is perfect
code. also it might be a good idea to update the android devices to
versions os 6 && 7 marshmallow and nougat, pixel phone and pixel-c tablet
as well as introduce material design as the new css framework, either
angular material, material design lite or materialize. what do you think?
it's all about progress and innovation.

On Sat, Feb 4, 2017 at 10:23 PM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment]
@NilsHolger - please do send in a PR with links to all three style guides. If you want to start a community driven style-guide then please begin by reaching out to the current owners of these guides and find out why they might not already be collaborating.

**Comment by frederikprijck** [comment]
+1 for referencing all 3 links (in case all 3 are still up to date)

I do think, talking about a community styleguide, there isn't something wrong with the current styleguides as I think both John and Todd are real Angular/AngularJS community leaders whereas mgechev is part of the Angular/AngularJS team.

Despite the fact we may have some points to improve those styleguides, I don't think it's a good idea to duplicate it's content, and it would be a little bit unthankful for the amount of effort which has been done.

Just as with AngularJS, the styleguides are opensourced. If anything feels incorrect, they are more then happy to review a PR.

**Comment by NilsHolger** [comment]
has anybody checked where the stars for the styleguide are from, https://github.com/johnpapa/angular-styleguide/stargazers? i remember hearing scott hanselmann on hansleminutes podcast, some time age, accusing google of skewing the search results by having everybody click on a link. My thoughts: you have to be sick or very greedy to even consider these kind of manipulations. well that's microsoft in action.
@petebacondarwin the 3 links aren't in the documentation yet? A PR, @frederikprijck can you do it please?
