### ISSUE TITLE
$anchorScroll.yOffset stops working in a modal

### ISSUE THREAD

**Issue by lorraul** [angular/angular.js#15661]
I have problems using _$anchorScroll_ with _$anchorScroll.yOffset_ in a modal. 

Basically $anchorScroll.yOffset stops working in a modal:
http://codepen.io/anon/pen/dNdaRG

Everything is fine when using it on a simple page:
http://codepen.io/anon/pen/OWQdqv

Tested with Angular 1.5.8, 1.6.1, FF, Chrome.

**Comment by gkalpak** [comment]
This is (unfortunately) a known limitation. Supporting all possible scenarions would be an overkill.
Quoting [the docs][1]:

> In order for `yOffset` to work properly, scrolling should take place on the document's root and not some child element.

[1]: https://code.angularjs.org/snapshot/docs/api/ng/service/$anchorScroll#yOffset
