### ISSUE TITLE
ngRoute not working on WP 10

### ISSUE THREAD

**Issue by rochapablo** [angular/angular.js#15679]
I think that this is a bug.

I wrote a simple app, but when I run on the mobile Windows Phone 10, nothing happen.

Here's the $routeProvider

```
  // Setting the route
  app.config(['$routeProvider', function($routeProvider) {
    $routeProvider
    .when('/', index())
    .when('/login', login())
    .when('/tasklist/:id/tasks', tasklist());
  }]);
```

and I'm using html5Mode

```
app.config(['$locationProvider', function ($locationProvider) {
      $locationProvider.html5Mode(true);
  }]);
```

Anyway, changing to true/false nothing seems changed.

Well, I have no Idea what could be, but here's my app

https://github.com/rochapablo/google-tasks-api

... here you can see working

https://google-tasks-api.herokuapp.com/

**Comment by rochapablo** [comment]
Sorry, this is working!

The problem is *gapi* (Google APIs).

**Comment by HLJMT** [comment]
nice to meet you
