### ISSUE TITLE
how to set html in model view value?

### ISSUE THREAD

**Issue by zohaibniaz** [angular/angular.js#15681]
I am doing in a directive
var value = element.html(); // html content of editable div
ngModel.$setViewValue(value);

but it display the tags as a string ... but i want to use tags as html not string
I want to append the editable html to the view 
how i can do this?? @henrik @expilo @evmar @plentz

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
