### ISSUE TITLE
JSON parse failure in defaultHttpResponseTransform

### ISSUE THREAD

**Issue by anupbelambe** [angular/angular.js#15695]
```
function defaultHttpResponseTransform(data, headers) {
  if (isString(data)) {
    // Strip json vulnerability protection prefix and trim whitespace
    var tempData = data.replace(JSON_PROTECTION_PREFIX, '').trim();

    if (tempData) {
      var contentType = headers('Content-Type');
      **if ((contentType && (contentType.indexOf(APPLICATION_JSON) === 0)) || isJsonLike(tempData))** {
        data = fromJson(tempData);
      }
    }
  }

  return data;
}
```

In defaultHttpResponseTransform() above, the response data is parsed as json, if either content type is application/json or is JSON like. In this case the data is unable to parsed as JSON in fromJson(), the exception is thrown at JSON.parse, which causes request to be rejected with empty object.
This makes it hard to debug response issues in production especially if response is dynamically generated, as no response data can be captured in this case.
My suggestion would be to reject with original response data in such cases and let client handle the failure.

**Comment by gkalpak** [comment]
I assume that by "debug [...] in production" you mean logging client errors  to the server and analysing them to find issues. For that usecase, this makes sense.

Of cource, you can create your own transform that captures that, but if someone wants to create a PR, I we can consider making this change in core.

**Comment by Narretz** [comment]
That's interesting, because prior to 1.6.0, a parse error wouldn't even be forwarded to the rejection handler / application code. Are people now finding new bugs in their apps because we let $q reject errors?

**Comment by gkalpak** [comment]
I think it would (but in a slightly different way).

**Before 1.6:**

1. Error
2. Promise rejection + `$exceptionHandler`

**After 1.6:**

1. Error
2. Promise rejection
3. If rejection not handled: `$exceptionHandler`

**Comment by anupbelambe** [comment]
I assume that by "debug [...] in production" you mean logging client errors to the server and analysing them to find issues. For that usecase, this makes sense.

Yes @gkalpak

**Comment by chirag64** [comment]
I'm interested in creating a PR. Is there any suggested approach you want me to follow to fix this?

**Comment by anupbelambe** [comment]
Can we catch the exception in defaultHttpResponseTransform and reject with original data in cases where JSON data cannot be parsed?

**Comment by gkalpak** [comment]
Off the top of my head, a reasonable approach would be to wrap the relevant code in a `try-catch` block, catch the error and throw a more informative error (containing the original).

This should be a `minErr` error though, so it needs an error page etc. Take a look [here][1] for an example of how this may look like.

[1]: https://github.com/angular/angular.js/commit/e9b9421cdb6086a35faa99fc5377171eb66d1fa4

**Comment by gkalpak** [comment]
@chirag64: Thx for stepping up btw 👍

**Comment by chirag64** [comment]
@gkalpak Thanks for the help, I've made some changes on my forked repository - 529cf2f854998e502bc66c655af0868e3b57eace. I'm not sure how I can test my changes or how I can call this function in a unit test (if a unit test is needed). Would appreciate your help on this. Thanks.

**Comment by Narretz** [comment]
@chirag64 Yes, we definitely need a test for this. The tests are in httpSpec.js, this should be in the describe block for json parsing. Once you have cloned the repo you can run grunt autotest to start the karma server, which will then run all the tests. You can isolate a single test by changing the `it` to `fit`.

HOWEVER. I am actually not sold on throwing a hard error here. Shouldn't we reject the promise with the original data instead?

**Comment by chirag64** [comment]
@Narretz So inside the `httpSpec.js` file, I created a new describe block for json parsing, and inside an `it` function, I'm trying to run `defaultHttpResponseTransform` but the tests keep erroring out saying `defaultHttpResponseTransform is not defined  no-undef`. I checked the httpSpec file to see how we're getting the other functions to work but couldn't find a pattern. Any hints on this?

**Comment by anupbelambe** [comment]
@chirag64 in your forked repository 529cf2f, can you throw tempdata instead of data

**Comment by Narretz** [comment]
@chirag64 

There's actually a section about the json already in the httpSpec.js: https://github.com/angular/angular.js/blob/71f437c15a606b542536e70c392808e84d982078/test/ng/httpSpec.js#L1186

There's a test about JSON deserialize errors: https://github.com/angular/angular.js/blob/71f437c15a606b542536e70c392808e84d982078/test/ng/httpSpec.js#L1372

Instead of a SyntaxError, we have to match for a minErr now: https://github.com/angular/angular.js/blob/71f437c15a606b542536e70c392808e84d982078/test/helpers/matchers.js#L308

It's also better to open a PR, so we can see the difference right away.

@anupbelambe I don't really understand what you mean.

**Comment by Narretz** [comment]
A problem I see is that with this behavior, you won't have access to the raw response string. Can we achieve this together with a minErr? Wdyt @gkalpak?

**Comment by gkalpak** [comment]
Sounds reasonable. We could embed the response (as string) into the minErr (and hope it is not huge 😛).

**Comment by chirag64** [comment]
Still unsure how to call `defaultHttpResponseTransform` in httpSpec.js for unit testing. Would appreciate some help with that and comments on the checked in code and documentation.

**Comment by anupbelambe** [comment]
Thanks @gkalpak and @chirag64.

I see this has been added to backlog milestone but in which Angular release would this fix be available.

**Comment by gkalpak** [comment]
v1.6.4
