### ISSUE TITLE
angular.copy loses own non-enumerable properties

### ISSUE THREAD

**Issue by zuzusik** [angular/angular.js#15692]
**Do you want to request a *feature* or report a *bug*?**

Report a **bug**.

**What is the current behavior?**

angular.copy [uses as destination object created from prototype](https://github.com/angular/angular.js/blob/a0641ea/src/Angular.js#L984), which it then [populates with own object properties](https://github.com/angular/angular.js/blob/a0641ea/src/Angular.js#L947). 
This way it loses own not enumerable properties which can cause bugs.

**Demo** : https://jsfiddle.net/zuzusik/7ye3m006/

**What is the expected behavior?**

Angular doesn't lose non-enumerable properties. I assume this can be achieved by iterating through `Object.getOwnPropertyNames` instead of using `for (key in source)` loop and checking for `hasOwnProperty`.

**What is the motivation / use case for changing the behavior?**

This causes bug with JSData v3: https://jsfiddle.net/zuzusik/6evanz3g/
Details: https://github.com/js-data/js-data/issues/442

**Which versions of AngularJS**

Angular 1.6.2, any browser.

**Comment by Narretz** [comment]
This has been documented as a "known issue": https://github.com/angular/angular.js/commit/14519f84f54b0100fcadb334220c711cfa8242b1 and changing this would impact existing apps. See https://github.com/angular/angular.js/issues/14853 for more discussion.
