### ISSUE TITLE
ng-change callback not being called.

### ISSUE THREAD

**Issue by boris-marinov** [angular/angular.js#15706]
The ng-change callback on a select menu is not being called. The bug is visible even in the live example of the ng-change directive documentation:

https://docs.angularjs.org/api/ng/directive/ngChange

When I click the "Confirmed" checkbox, the "counter" variable isn't being incremented:

**Comment by Narretz** [comment]
ngChange only fires when the input is changed. In the example, only the first input has ng-change, the second on doesn't. So the counter only increments when you click the first checkbox. So I think everything works as expected.

**Comment by Narretz** [comment]
If you are having a specific problem with select + ngChange, please provide a demo of the problem - maybe it's somethign different

**Comment by boris-marinov** [comment]
Yeah, I had `ng-change="console.log('foo')"` which does not work, but when I called a scope function it did. The other problem was that I didn't know that `ng-model` had to be defined in order for the callback to work.
