### ISSUE TITLE
Error In Processing Float Values .1/.4/.9

### ISSUE THREAD

**Issue by mfhassan22** [angular/angular.js#15701]
I spend a lot of time to find out the problem in my code but at the end it came out as that version 1.6.1 if i put 1 or 4 or 9 after decimal the value become undefined or NaN This version [http://code.angularjs.org/snapshot/angular.min.js --1.6.2](http://code.angularjs.org/snapshot/angular.min.js) http://code.angularjs.org/snapshot/angular.min.js saved me after 48 hours of try the test is on plunker [https://plnkr.co/edit/JpWtVgoooJnatjeQZVRq?p=preview](https://plnkr.co/edit/JpWtVgoooJnatjeQZVRq?p=preview)

**Comment by Narretz** [comment]
Sorry, which version was incorrect for you? The current snapshot or 1.6.2?

**Comment by mfhassan22** [comment]
The version 1.6.1 which is for download on website and try to enter 311.41 when it can accept any number instead of 4 except 1 4 9 the version can be also retrived as i have added the cdn link in the code example

**Comment by gkalpak** [comment]
This should be fixed in v1.6.2, which is not on Google CDN yet, but is available through npm/unpkg.com and code.angularjs.org. @mfhassan22, can you verify that it works with v1.6.2?

**Comment by mfhassan22** [comment]
@gkalpak Yes the version 1.6.2 is correct but i wanted to **mention** it, as it have taken my 2 days i get frustrated that what i am doing wrong. so to keep any one else safe from getting such a serious problem and confirm the issue

**Comment by gkalpak** [comment]
OK, I see. (There have been already a couple of issues about this btw.)
