### ISSUE TITLE
$http post data to execute PL/SQL  fail 

### ISSUE THREAD

**Issue by c011v** [angular/angular.js#15703]
In this case , the procedure works quickly about 1-2 mins , I got successful message .
but the procedure works over than 4~5 mins , i got My Command Line messages ,
message like "POST /service/GoProcedure 200 120003ms" ,then it returns null
,i don't know the null means successful or not .

I execute the procedures successful at SQL*PLUS ,but it run over than 4 mins.
I try to setting timeout but it doesn't work .So I have no idea to adjust this question.  

May U guys help me ?

> web1.html

`  <button class="btn btn-sm btn-primary" ng-click="GO('100')" >transfer</button>`

> web1.controller.js

```
angular.module('SystemApp')
.controller('GoCtrl', function ($scope, $http, $window, $location, $log) { 
   $scope.GO= function (obj) {
        var RECORD_ID = { RECORD_ID: obj };
        $http({
            method: 'POST',
            url: '/service/GoProcedure  ',
            data: angular.toJson(RECORD_ID),
            headers: { 'Content-Type': 'application/JSON' },
        })
        .success(function (data) {          
            if (!data.OUT_HANDLE_MESSAGE) {
                     console.log('success! next step!!!')
            } else {
                    console.log('Proc transfer fail',data.OUT_HANDLE_MESSAGE)
	            alert('transfer fail');
            }
        })
        .error(function (err) {
            console.log('err' + err);
        });
    };
})
```

**Comment by Narretz** [comment]
Hi, your issue reads like a support question, and has probably more to do with Go than with AngularJS. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
