### ISSUE TITLE
How to change required/optional in angular directive.

### ISSUE THREAD

**Issue by srivi1225** [angular/angular.js#15705]
Hi,

I have an address directive. i am using it for current and previous address. i am loading this directive in a form in the form i have time at current address. i have to make the previous address fields as optional if the timespent at current address is greater than 1.

1. initially the form will be loaded with current address and previous address as required.
2. when i enter the value for time at address based on the input the previous address fields should be mandatory/optional.

Can some one pleas help on this.

Thanks,
Sri

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
