### ISSUE TITLE
Angular directives don't work inside comments

### ISSUE THREAD

**Issue by pavelhoral** [angular/angular.js#15710]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Angular's own directives (ngRepeat, ngIf, ...) don't work in comments, but the documentation suggests they should.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.**

http://plnkr.co/edit/gENQxhZ9aZZULmpk1tN4

**What is the expected behavior?**

Either Angular directives should work in comments or the [documentation needs to be updated](https://docs.angularjs.org/guide/directive).

> All of the AngularJS-provided directives match attribute name, tag name, comments, or class name.

**What is the motivation / use case for changing the behavior?**

Being able to use ngIf and ngRepeat on multiple rows inside table.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

1.5.x and 1.6.x

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

none

**Comment by Narretz** [comment]
The docs are incorrect in this case. I'll update it.

**Comment by pavelhoral** [comment]
Maybe state specifically that ng* directives are by default EA instead of just deleting the problematic sentence (and possibly rephrasing the "Best practice" section bellow it).

**Comment by Narretz** [comment]
most ng* directives aren't EA (most are just A). I've added this to the docs. I didn't change the best practice section, but if you have any changes, a PR is welcome :)
