### ISSUE TITLE
Can I prevent Angular from swallowing my exceptions?

### ISSUE THREAD

**Issue by boris-marinov** [angular/angular.js#15716]
Hello, 

Is there a way I can tell angular to stop swallowing exceptions from my code, so I can trace them properly?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Please also include relevant code, demo, AngularJS Version etc.

Thanks!
