### ISSUE TITLE
The breaking change as by #14202 should be reverted as the reference specification was already officially deprecated

### ISSUE THREAD

**Issue by evilaliv3** [angular/angular.js#15715]
I think that the breaking change introduced in pull request https://github.com/angular/angular.js/pull/14202 should be reverted as it makes not any particular sense.

The specification by Google has been officially deprecated since October 2015.

"This recommendation is officially deprecated as of October 2015."
Reference: https://developers.google.com/webmasters/ajax-crawling/docs/getting-started

The deprecation in addition happened long time before the patch was written and committed.

**Comment by Narretz** [comment]
It's a pretty bad idea to revert something that has just been implemented.
I personally think a bigger reason für using a default hashPrefix is that without it, you are messing up your hash anchors, and this was confusing many people.
Also, deprecated doesn't mean obsolete.
Further, reacting to this change is a 3 line code change (as see in your repo).

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
