### ISSUE TITLE
Angular Js 1.6.1 htmllibmanager.gzip minification issue

### ISSUE THREAD

**Issue by Tewari1005** [angular/angular.js#15725]
Hi Team,
I am working with AEM 6.1 in which we are using angular js 1.6.1 version . AEM provide minification functionality which use htmllibmanager.gzip so when we are minifying the angular js 1.6.1 it is showing 34 syntax error. Can anyone help in resolving this or any one having htmllibmanager.gzip minified angular js version 1.6.1, Please share with me here or over mail(tewari.b34991@gmail.com) . Need help on urgent basis.

**Comment by gkalpak** [comment]
This sounds like a general support question. You can use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

##
That said, I recommend using the pre-miinified version whenever possible. It is minified using the Closure Compiler and there is also an custom transformation that removes error messages (and uses URLs that point to erro pages in the docs), so the size should be smaller than most other solutions.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
