### ISSUE TITLE
ngRoute not working on UC Browser Mobile using $locationProvider.html5Mode.

### ISSUE THREAD

**Issue by renjiza** [angular/angular.js#15721]
when i trying ngRoute inside codeigniter on desktop browser specially Mozilla and Chrome it good working but when open on UC Browser Mobile its not working. Everybody help me please... This is my code 

```
angular.module('App',['ngRoute']).config(['$routeProvider', '$httpProvider','$locationProvider', ($routeProvider, $httpProvider, $locationProvider) => {
$locationProvider.html5Mode(true);

$routeProvider
,when('/home',{ 
       templateUrl : 'home.html'
})
}])

```
in index.html 

```
<html ng-app="App">
<head>
<base href="/">
</head>
<a href="home">home</a>
<div ng-view></div>

</html>
```

Please everybody help me... :(

**Comment by gkalpak** [comment]
According to [this][1] UC Browser for Android partially supports the history API since version 11. The partial support could be the cause of the problem. Try using the default hashbang mode (i.e. remove `$locationProvider.html4Mode(true)`).

[1]: http://caniuse.com/#feat=history
