### ISSUE TITLE
angualrjs1.3 not sppport IE8 how to solve it 

### ISSUE THREAD

**Issue by hanniba214** [angular/angular.js#15720]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by gkalpak** [comment]
Versions 1.3+ only support IE9+. If you need to support IE8, you can use 1.2.x, which is the last version that supports IE8.

**Comment by hanniba214** [comment]
thank you very much


发自网易邮箱大师
On 02/17/2017 17:20, George Kalpakas wrote:

Versions 1.3+ only support IE9+. If you need to support IE8, you can use 1.2.x, which is the last version that supports IE8.
