### ISSUE TITLE
bower package for 1.2.x hold wrong version in min.js.gzip

### ISSUE THREAD

**Issue by SanderElias** [angular/angular.js#15746]
*bug*

**What is the current behavior?**
`bower install angular#1.2.32` 
if you check the gzip file, it's from the wrong (1.5.x) angular version

**What is the expected behavior?**
Make sure the right version is in there.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
All 1.2.x versions I tried (the last 2 1.2.x versions

**Comment by mgol** [comment]
IMO we shouldn't include gzipped files at all in the bundles; we don't do it for other packages and they aren't really useful - web servers are gzipping the files by themselves.

**Comment by SanderElias** [comment]
@mgol I tend to agree with you, but this is there for a long time, and users may depend on it being available. (although the wrong version might be available forever, and almost nobody noticed)

**Comment by SanderElias** [comment]
This proved to be a not a real problem in practice. the bower package is broken for a long time now, and we only received 1 report about this. Turns out it was not reported because most servers do their own gzipping, or people use a [CDN](https://ajax.googleapis.com/ajax/libs/angularjs/1.2.32/angular.min.js).

Given the effort it would take to retro fix all old bower packages, I would recommend leaving this unfixed.
I leave this here as a note to anyone that might run into this and close the issue.
