### ISSUE TITLE
Extend BC example for feat($compile) in > Angular 1.6.0 docs

### ISSUE THREAD

**Issue by lbayerl** [angular/angular.js#15740]
**Do you want to request a *feature* or report a *bug*?**
issue in doc - wanted to create PR but couldn't.

**What is the current behavior?**

in CHANGELOG.md there is this BC description for feat($compile): https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-1 regarding the 'binding' in 'components'

**What is the expected behavior?**

The same behaviour exists when you use the controllerAs pattern like e.g.

```js
  angular
    .module('myApp')
    .directive('myDirective', myDirective);

  function myDirective() {
    return {
      restrict: 'E',
      scope: {
        value: '='
      },
      controller: 'myController',
      controllerAs: 'vm',
      bindToController: true,
      templateUrl: 'myTemplate.html'
    };
  }
```
You want have access to vm.value in your Controller.

**What is the motivation / use case for changing the behavior?**
Extend the example for the BC.

**Which versions of AngularJSare affected by this issue?
All version > 1.6.0

**Comment by gkalpak** [comment]
I don't think we need to extend the example (as it would get really verbose), but the current description can indeed be confusing, because it only mentions "component constructors".

👍 for changing the description to something like: _component constructors_ --> _component/directive controller constructors_

**Comment by lbayerl** [comment]
Find with that as well - it took as a while to find out what's going on here - therefore I thought providing an additional example could help. But again as said, your approach seems good enough to me.
