### ISSUE TITLE
can not read property '$pending' of undefined.

### ISSUE THREAD

**Issue by lili21** [angular/angular.js#15742]
**Do you want to request a *feature* or report a *bug*?**

I won't say it's a *bug*.  

**What is the current behavior?**

![2017-02-23 11 48 31](https://cloud.githubusercontent.com/assets/4456380/23244345/776a85ba-f9bf-11e6-8fc7-0bbccffdb078.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Migrating from 1.5 to 1.6, don't know what does the error mean.

**What is the expected behavior?**

no error.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

angular@1.6.x

works in angular@1.5.x

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

my application works well beside the error, It just make me annoying.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

##
BTW, also make sure you go through the [1.5-to-1.6 migration guide][2], which discusses all breaking changes and suggests ways to fix your code.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6
