### ISSUE TITLE
ngroute -data binding issue 

### ISSUE THREAD

**Issue by hiharsh** [angular/angular.js#15745]
Hi, I am working on my first AngularJs SPA.
I am trying to implement routing for my first AngularJs application.
My stand alone code without any routing works as expected. Here is the plnkr link for the working code.
[http://plnkr.co/edit/zhmgNI?p=info](url)
http://plnkr.co/edit/zhmgNI?p=info

However the code with routing enabled doesn't work. i.e the traffic.html doesn't accept the text box input + websocket button doesn't work.
Here is the plnkr link.
[http://plnkr.co/edit/ozBej8?p=info](url)
http://plnkr.co/edit/ozBej8?p=info
I am missing something very simple but important.
Could someone please help?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

That said, your code is strange. Your traffic.html is a complete html document. This is wrong - route templates should only be html fragments. They are inserted automatically as children into the ng-view directive element.

And btw, the format for you plnkr links is also wrong.
