### ISSUE TITLE
HTTP 204 causes XML Parsing Error

### ISSUE THREAD

**Issue by thany** [angular/angular.js#15759]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
A HTTP 204 response from a REST API will produce an error in the console:
```
13:33:42.508 XML Parsing Error: no element found
Location: http://some.server/api/endpoint/filename Line Number 1, Column 1: 1 filename:1:1
```
The response contains no content (as it's a HTTP 204) and no `Content-Type` header (because there's no content to describe in the first place).

**What is the expected behavior?**
It should silently ignore the content that isn't there, and not try to parse it as XML, or as anything really.

**What is the motivation / use case for changing the behavior?**
We've got a REST API (not publicly available, unfortunately) that returns a HTTP 204 when requesting certain data that does exist, but is empty. This is great to distinguish from data that doesn't exist (and cannot contain data) which returns a 404. So we feel a 204 is the correct behaviour, at least from server's perspective it is.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
I've tested this with AngularJS 1.6.1 on Firefox 51, Chrome 56, and Edge on Windows 10. The error above is from Firefox though. The angularjs snapshot release has the same problem.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I've tried adding an interceptor that fakes some data to parse, but it didn't work. Like, at all. As if it does absolutely nothing.

Like so:
```
module.config(function($httpProvider) {
  $httpProvider.interceptors.push(function() {
    return {
      response: function(response) {
        if (response.status === 204) {
          response.data = "<yolo></yolo>";
        }
        return response;
      };
    });
  });
```
⚠ So that doesn't work

Like I said, I think it's best, when a HTTP 204 is encountered, to simply ignore the content alltogether and not try to parse it as anything. As far as I understand HTTP, this should be the correct behaviour for a response that naturally doesn't/shouldn't contain a body.

**Comment by Narretz** [comment]
that error doesn't look like it comes from AngularJS. Can you show the whole stack trace from the unminified file?

**Comment by thany** [comment]
The error doesn't come with a stack trace. I probably would have posted it 🙂

**Comment by Narretz** [comment]
But what kind of file is that? There's not enough information in your description. If you think this is a bug, then the best thing is to create a PR with a failing test case and ideally with the fix already included.

**Comment by Narretz** [comment]
I meant the file from which the error comes - in your post, you have called
it "filename". I wanted to know if this a Javascript file. Because if it's
not, then this is not a JS error.

We mock backend responses in our tests - please have a look at
https://github.com/angular/angular.js/blob/19bc52127f8393ffccac563b21267adb75c19275/test/ng/httpSpec.js#L413
for an example

2017-02-28 15:39 GMT+01:00 thany <notifications@github.com>:

**Comment by thany** [comment]
Like I said, it's not a file. It's an API endpoint. The last bit of the url just so happens to be called `filename` in my post. But it's not a file really. Especially not since it returns a **204 No Content**

If it *did* return content, it *would* return a JSON response, but in a 204 there's no content, so no JSON either. And no XML.

**Comment by frederikprijck** [comment]
Totally unrelated: Using 204 isn't really a great idea when you're designing REST services. Even tho this isn't my decision, I really felt like sharing this with you: http://blog.ploeh.dk/2013/04/30/rest-lesson-learned-avoid-204-responses/ 
I also don't think 204 is designed for this use-case.

Other than that, I tried reproducing it but I didn't manage to do so:
http://plnkr.co/edit/vs8vDWMDzG7x7U5x4jSV?p=preview

@thany could you have a look at the plunkr?

**Comment by gkalpak** [comment]
Froma a quick search, it seems like a Firefox issue (nothing Angular-specific): [example][1], [other example][2].

[1]: https://forums.asp.net/t/1004395.aspx?What+causes+this+XML+Parsing+Error+no+element+found
[2]: http://stackoverflow.com/questions/975929/firefox-error-no-element-found

**Comment by frederikprijck** [comment]
@gkalpak fwiw: the plunkr I mentioned above does work in firefox 51.0.1.

**Comment by Narretz** [comment]
Here's a plunkr with an XML answer:
http://plnkr.co/edit/kcoUgLA4PGV5u5xL9Igj?p=preview

As @thany said, you get a Firefox error when the response is 204 and Content-Type is XML.
However, you don't get the error when the response is 204 and the Content-Type is text/plain or empty (empty will be set the text/html).
So I assume the server will set the response content-type to XML automatically which triggers the error. And in any case, this is not an AngularJS issue.

**Comment by Narretz** [comment]
I believe this is resolved.
