### ISSUE TITLE
Binding method stored as property value to ngClick

### ISSUE THREAD

**Issue by Jorrex** [angular/angular.js#15753]
_possible feature or perhaps a bug, didn't find anything in the docs or online about this_

**Current behavior**
Binding a method, stored as a property value, to ngClick doesn't execute.

**Example**
Easy to reproduce: create an object with a property that contains the name of a method. Bind that property to a ngClick and execute the click-event.
[jsFiddle](https://jsfiddle.net/Jorrex/1txjsthk/)

**What is the expected behavior?**
Executing the bound method when clicking on the element.

**Motivation**
In my opinion, it's easier to write and it's shows clean coding. It doesn't require a wrapper function to be executed.
 
**Versions**
So far, I have only noticed this in 1.4.8 and 1.5.8

**Comment by Narretz** [comment]
Yes, if the expressions starts with the bracketNotation, then the parser does not read it correctly. Is this intended or a bug @lgalfaso ?

**Comment by gkalpak** [comment]
I don't think we can support "implicit" bracket notation to the current context. For example it would be impossible for the parser to distinguish it from array literals. This what the `this` literal is for.
E.g. instead of `[some.prop]()` (which does not work), you can use `this[some.prop]()`.

**Comment by Jorrex** [comment]
Yes, with this `this` literal, it works as expected. I did not know that was a thing, thanks for the response!
