### ISSUE TITLE
Angular 1.5.8 $http errors occasionally with status -1

### ISSUE THREAD

**Issue by yamabikoJp** [angular/angular.js#15751]
When using the $http service, occasionally the status returns -1.
Timeout of parameter information of $http service is not set.

There is no error and the request looks fine.
In fact, when I retry the transaction after one of these errors, it goes through just fine.

The usage environment is as follows.

· Angular 1.5.8
· Windows 7
· IE 11

What is the cause?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
