### ISSUE TITLE
 *bug* Angular ngAnimate add -active -remove to classes.

### ISSUE THREAD

**Issue by ben-codefresh** [angular/angular.js#15756]
I notice 2 problems that started once I turned on the ngAnimate module (I need it for some new behavior).

First, in some cases when I have ng-class, those classes also get the `-active` and `-remove` suffixes. 
For example this is from my code:
```
<i class="fa status-icon fa-exclamation-remove fa-spin-add icon-codefresh-running-add fa-exclamation-remove-active fa-spin-add-active icon-codefresh-running-add-active fa-check-remove verified-icon-remove fa-check-remove-active verified-icon-remove-active fa-exclamation"
 ng-class="{
                               'fa-exclamation': vm.signUpForm.AccountName.$invalid && !vm.signUpForm.AccountName.$pending,
                               'fa-spin': vm.signUpForm.AccountName.$pending && !vm.signUpForm.AccountName.$invalid,
                               'icon-codefresh-running': vm.signUpForm.AccountName.$pending && !vm.signUpForm.AccountName.$invalid,
                               'fa-check verified-icon': vm.signUpForm.AccountName.$valid
                           }" ></i>
``` 

Notice that I have all these classes at the same time. I didn't add any of the `-active`, `-remove` classes. Those were added by the framework (which I don't need and break my design). 

I have all these classes at the same time: `fa status-icon fa-exclamation-remove fa-spin-add icon-codefresh-running-add fa-exclamation-remove-active fa-spin-add-active icon-codefresh-running-add-active fa-check-remove verified-icon-remove fa-check-remove-active verified-icon-remove-active fa-exclamation`
![image](https://cloud.githubusercontent.com/assets/15571953/23379749/f3354402-fcec-11e6-83a1-ef4b4ab0d954.png)

The second problem is that even if the framework adds those, it doesn't always remove them. 

This happened to any Angular and ngAnimate version from 1.5.5. I tried to upgrade to 1.6.2 and it still happens.

**Comment by gkalpak** [comment]
@ben-codefresh, can you add a minimal runnable demo of the issue (without external dependencies). It is really difficult to investigate otherwise.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
