### ISSUE TITLE
Default expiration date cookie

### ISSUE THREAD

**Issue by max21** [angular/angular.js#15769]
Hi,

What is the default expiration date when create a cookie with $cookies.put('name', someData) ?

I know how to set expiration date with options https://docs.angularjs.org/api/ngCookies/provider/$cookiesProvider#defaults but I don't know when my cookie expires when I don't specify expiration date.

Thanks

**Comment by gkalpak** [comment]
If you don't specify a cookie expiration date, then none will be set (i.e. there will be no `;expires=...` in the cokkie string). This will make the cookie to expire at the end of the session.

BTW, this is a general support question. You can use one of the more appropriate [support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
