### ISSUE TITLE
require option in the directive is not working in angular 1.6.2

### ISSUE THREAD

**Issue by rajathms** [angular/angular.js#15766]
I was trying to build a custom directive(in angular-version-1.6.2), where I was trying to append other directive's controller function using **require** option, which was not working at all. After wasting some hours digging on that, I just roll back to angular-version 1.4.8 , without changing a single line of code and it is working awesome.

My major question is did you guys removed the directive concept in angular-version 1.6.x and above as you guys are bringing in **Components** in to the platform. If not why that **require** option is not working for a directive in angular-version 1.6.x.

**Comment by Narretz** [comment]
The require option is still there, and you can find information about breaking changes in the migration guide or the changelog.
Without a demo, it's impossible to say why your code didn't work. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) with a link to a demo of your problem.

**Comment by rajathms** [comment]
@Narretz  
Sorry, I didn't used  [$onInit](https://docs.angularjs.org/api/ng/service/$compile#-bindtocontroller-) in my controller, after updating to angular 1.6.x  that was the issue

The solution is
Using $onInit in your controller function for binding scope

```
controller: function () {
    this.$onInit = function () {

     // your business logic 

    };
};
```
