### ISSUE TITLE
how to fireevent of input element created by angular?

### ISSUE THREAD

**Issue by amiiPower** [angular/angular.js#15774]
Do you want to request a feature or report a bug?
feature

i create a simple html like:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="angular.min.js"></script>
  </head>
  <body>
    <div ng-app="">
      <p>name : <input type="text" ng-model="name" id="abc"></p>
      <h1>Hello {{name}}</h1>
    </div>
  </body>
</html>
```

when i input some chars into the input control,and these chars also output where {{name}} located.

now, i want to use javascript to simulate those steps,and write some script like:

document.getElementById('abc').value='123';
document.getElementById('abc').fireEvent("onblur");

chars '123' is put into the input element and view on screen,but {{name}} is not changed,
what event can i use?
document.getElementById('abc').fireEvent("on" + ?);

**Comment by gkalpak** [comment]
`change` will work on all browsers afaict. `input` will work in most (but probably not IE).
So something like `document.getElementById('abc').dispatchEvent(new Event('change'))` should do the trick.

BTW, this is a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
