### ISSUE TITLE
browser fetches the resources for ng-repeat placeholder.

### ISSUE THREAD

**Issue by jayendra13** [angular/angular.js#15777]
While using the `ng-repeat` with the html tags which, requires to fetch the resources from the server, it also try to fetch the value for placeholder used in `ng-repeat`.
IMHO it is a bug in angualr framework.

Consider the following application.
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.2/angular.min.js"></script>
</head>
<body ng-app="myApp" ng-controller="myController">

  <div class="" ng-repeat="item in items">
    <img src="{{item.image}}" alt="{{item.alt}}" />
    <h2>{{item.name}}</h2>
  </div>

  <script type="text/javascript">
    angular
      .module('myApp', [])
      .controller('myController', function($scope){
          $scope.items = [{'image': '','name':'item0', 'alt': 'item0_logo'},
              {'image': '','name':'item1','alt': 'item1_logo'},
              {'image': '','name':'item2','alt': 'item2_logo'},
              {'image': '','name':'item3','alt': 'item3_logo'}];
      });
  </script>
</body>
</html>

```

**The current behaviour**
Currently it tries to fetch the `item.image` in the `<img>`, tag. Running above code locally in chrome gives the following error.
```
GET file:///home/eddie7/Grace/%7B%7Bitem.image%7D%7D net::ERR_FILE_NOT_FOUND   test.html:11
``` 

Ideally browser should never make such requests, or may be I am using the `ng-repeat` in the wrong way.

**Comment by Narretz** [comment]
You should use [ngSrc](https://code.angularjs.org/snapshot/docs/api/ng/directive/ngSrc) instead of src
