### ISSUE TITLE
$http.head does not return all headers

### ISSUE THREAD

**Issue by ajsb85** [angular/angular.js#15779]
`$http.head` does not return all headers

![image](https://cloud.githubusercontent.com/assets/663460/23618890/2b9845ce-0292-11e7-8fa0-ec72267c3adf.png)

![image](https://cloud.githubusercontent.com/assets/663460/23618905/3049dfc4-0292-11e7-8419-e95f5d631cb4.png)

**Comment by Narretz** [comment]
This is probably a CORS problem. AngularJS doesn't modify or filter the headers that come out of the XHR call : http://stackoverflow.com/questions/8945587/xmlhttprequest-getallresponseheaders-not-returning-all-the-headers

For the future, please take note: 
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
