### ISSUE TITLE
Enable IE 11 compability of Angular + pdf.js

### ISSUE THREAD

**Issue by nemoinho** [angular/angular.js#15772]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently pdf.js defines ```document.currentScript``` but not ```link.origin``` nor ```link.protocol```. If angular starts it checks if it is allowed to [bootstrap automatically](https://github.com/angular/angular.js/blob/master/src/Angular.js#L1533) it checks for currentScript and asume that this will be enough to [filter IE](https://github.com/angular/angular.js/blob/master/src/Angular.js#L1537). This check will not work in combination with pdf.js

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
To demonstrate this behaviour there is a plnkr with a minimal environment, that shows the problem: http://plnkr.co/edit/YFCQM2Px0QU0KnGzsAlM?p=preview

**What is the expected behavior?**
Angular should check also for [link.origin](https://github.com/angular/angular.js/blob/master/src/Angular.js#L1560) and [link.protocol](https://github.com/angular/angular.js/blob/master/src/Angular.js#L1567) if they are implemented, to make sure that it works correctly with e.g. pdf.js

**What is the motivation / use case for changing the behavior?**
pdf.js is widely used to render pdfs and angular is spreaded for web-apps. They will occur on the same page more often than probably expected, because they work in similiar domains, so they shouldn't interfier each other.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
The whole angular 1.6.x tree is affected. The problem only occurs on IE 11 on each Windows.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Probably there can be a additional check for link.origin like:

    if (link.origin !== undefined && document.location.origin === link.origin) { …

And there can be a case for the undefined protocol:

    switch (link.protocol) {
      case 'http:':
      case 'https:':
      case 'ftp:':
      case 'blob:':
      case 'file:':
      case 'data:':
      case undefined:
        return true;
      default:
        return false;
    }

**Comment by Narretz** [comment]
Can you post a demo where the actual pdf.js and AngularJS files are used? I cannot reproduce the issue. To clarify, what you mean is that AngularJS autoboostrap is not working in IE11 when pdf.js is included?

**Comment by petebacondarwin** [comment]
The workaround for this is simple. If you are using `PDF.js` on IE then you just manually bootstrap AngularJS. So instead of relying upon `<body ng-app="app">` you use:

```
angular.bootstrap(document.body, ['app']);
```

It is unlikely that we will fix this on our side. It is `PDF.js` that is polyfilling `document` without accounting for what other libraries might be expecting.

**Comment by mgol** [comment]
I'd add that libraries shouldn't modify properties of objects they don't own as it causes issues like that (& many others). If they need a particular API that is missing in some supported environments they may wrap its usage in a function that will use the shimmed version if the native one is not available.

**Comment by nemoinho** [comment]
Thanks for the discussion the argument are valid and good. So I'll close this issue.

**Comment by petebacondarwin** [comment]
Thanks for closing.

**Comment by icevic1** [comment]
Faced with this issue on Firefox and angular 1.6.x
anybody solve it? how?
