### ISSUE TITLE
Semver adherence

### ISSUE THREAD

**Issue by lukebarton** [angular/angular.js#15789]
Deprecated or not, this commit & subsequent release broke Semver convention by releasing breaking changes on a patch version bump!
https://github.com/angular/angular.js/commit/1daa4f2231a89ee88345689f001805ffffa9e7de

Please refer to the npm versioning page: https://docs.npmjs.com/getting-started/semantic-versioning

A minor version would have been enough - a patch version number is a bit mean.

**Comment by Narretz** [comment]
Two things:
1. AngularJS has always included breaking changes in the *minor* version. Never in the patch version. Yes, that means we do not adher to semver.
2. The commit you mentioned has not been released in *any* version. It's only part of the master branch

**Comment by lukebarton** [comment]
Apologies, I assumed it had gone out in the release yesterday. Something in 1.6.3 has broken our builds which we've failed to lock to specific versions.
