### ISSUE TITLE
ng-transclude combined with link function

### ISSUE THREAD

**Issue by pascDa** [angular/angular.js#15787]
This has been probably asked before, but I did not find a proper solution:

When using ng-transclude, linking functions don't effect the DOM anymore, for example when an attribute is set.

I have created a Plunk where this behavior is reproduced, by setting an input field disabled. I know there are different solutions for disableing an input field (ng-disabled). It is only an example:
http://plnkr.co/edit/gyRr0tdeT9VXgCbsC39A?p=preview 

I expect the behavior of line 19 of the index.html to be just as if there was no transclude (line 20).

I'm using Angular 1.6.1

**Comment by Narretz** [comment]
in the link functions, you are not using the element that is passed to them - you are using the element passed to the compile function. This is not the same element, as transclude creates a clone. It's also noted in the docs that it is not safe to do DOM manipulation on the children elements of the compile element.
