### ISSUE TITLE
jQuery/Ready event parameter injection issue

### ISSUE THREAD

**Issue by evanron** [angular/angular.js#15781]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

_When jQuery is loaded before Angular_ then the ready event handler function can receive an unexpected parameter, which will be set to jQuery itself. 

In the case below, MyMethod() supports an optional parameter, and the parameter being passed in was jQuery:

`angular.element(document).ready(MyHelper.MyMethod);`

In my own example, I accidentally booted angular and passed in jQuery as the app element, which resulted in multiple instances of jQuery being instantiated until memory was exhausted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

[http://plnkr.co/edit/BVxsUaluLp6A7C8YTBHS](http://plnkr.co/edit/BVxsUaluLp6A7C8YTBHS)

**What is the expected behavior?**

I would have expected that no parameters are passed into MyMethod().

**What is the motivation / use case for changing the behavior?**

jQuery consistency. Consistency in general.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Not browser related.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Narretz** [comment]
@mgol is this something you could take a look at?

**Comment by mgol** [comment]
Thanks for the report. However, current behavior is consistent with jQuery which does pass the jQuery instance into the invoked callback as the first parameter. In jQuery passing jQuery itself to itself is not supported and it does trigger an infinite loop so there's no difference here.

Where exactly do you see the inconsistency?

**Comment by evanron** [comment]
I'll agree on that. I think there was confusion on my part when using angular's ready() event handler _without_ jquery loaded and no parameters are passed.
