### ISSUE TITLE
angular.module(...).info is not a function in angular-aria

### ISSUE THREAD

**Issue by kdutkowski** [angular/angular.js#15786]
I encountered the following bug - after upgrading angular-aria to recently released v1.6.3 I'm getting the following error:
```
Uncaught TypeError: angular.module(...).info is not a function
    at angular-aria.js:62
    at angular-aria.js:403
```
When I downgrade to v1.6.2, the app works normally.

**Comment by Narretz** [comment]
You need to update angular to 1.6.3, too. The .info fn is defined in angular.js itself. It's always been the case that the core file and the module files have to have the same version.

**Comment by kdutkowski** [comment]
Found out it's a problem with angular-material dependency, not angular itself. Leaving this here should anyone have the same problem https://github.com/angular/material/issues/10475. 

Thanks for help!

**Comment by Pax125** [comment]
Thank U so much Narretz :) 
I spent ONE day debugging my codes.

**Comment by jcubic** [comment]
I have the same problem with npm and webpack, the problem was that angular-messages was after angular-material so it get installed by angular-material before proper version was taken from package.json. Moving angular-messages before angular-material fixed the issue.

**Comment by leongaban** [comment]
Hi I'm running into this problem as well. Not using Aria, just angular-cookies. I upgraded to angular 1.6.4 and noticed that there is no `info` function in angular.js

http://stackoverflow.com/questions/43188708/installed-angular-cookies-getting-angular-module-error-on-info-function

**Comment by gkalpak** [comment]
@leongaban, you should update all AngularJS modules to be on the same version.

**Comment by leongaban** [comment]
@gkalpak yes, it was my mistake, I had all the angular dependencies manage by bower, not npm. Npm was only for Gulp deps, but I had angularjs in there as well. Removed from npm, installed via bower and ran my build scripts and it all works now!

**Comment by mtrogers** [comment]
Hmm, I'm still getting it:
bower list
meanjs /data/mean
├── angular#1.6.4 (1.6.5-build.5353+sha.136a42a available)
├─┬ angular-animate#1.6.4 (1.6.5-build.5353+sha.136a42a available)
│ └── angular#1.6.4 (latest is 1.6.5-build.5353+sha.136a42a)
├─┬ angular-bootstrap#1.2.5 (latest is 2.5.0)
│ └── angular#1.6.4 (1.6.5-build.5353+sha.136a42a available)
├─┬ angular-material#1.1.4
│ ├── angular#1.6.4 (1.6.5-build.5353+sha.136a42a available)
│ ├── angular-animate#1.6.4 (1.6.5-build.5353+sha.136a42a available)
│ ├─┬ angular-aria#1.6.4 (1.6.5-build.5353+sha.136a42a available)
│ │ └── angular#1.6.4
│ └── angular-messages#1.6.4 (1.6.5-build.5353+sha.136a42a available)
├─┬ angular-messages#1.6.4 (1.6.5-build.5353+sha.136a42a available)
│ └── angular#1.6.4
├─┬ angular-mocks#1.6.4 (1.6.5-build.5353+sha.136a42a available)
│ └── angular#1.6.4
├─┬ angular-resource#1.6.4 (1.6.5-build.5353+sha.136a42a available)
│ └── angular#1.6.4
├── angular-ui-notification#0.2.0 (latest is 0.3.6)
├─┬ angular-ui-router#0.2.18 (latest is 1.0.0)
│ └── angular#1.6.4 (1.6.5-build.5353+sha.136a42a available)
├─┬ bootstrap#3.3.7 (latest is 4.0.0-alpha.6)
│ └── jquery#3.2.1
├─┬ ng-file-upload#12.1.0 (latest is 12.2.13)
│ └── angular#1.6.4 (1.6.5-build.5353+sha.136a42a available)
└── owasp-password-strength-test#1.3.0

**Comment by ileathan** [comment]
Hi I get the same error with 

```
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-route.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
```

**Comment by gkalpak** [comment]
@ileathan, maybe try loading `angular.min.js` first.

**Comment by yogi07** [comment]
just replace ^ sign of the before version to ~ sign and apply following command
bower install --force

it worked for me..  :)

**Comment by sajidsidhu** [comment]
just use same version of angular.min.js and angular-sanitize.min.js.
it will fixed 100% ;)

**Comment by khoramshahy** [comment]
I had this problem too and solved that by using lower version of angular-aria
