### ISSUE TITLE
Date filter can't format date/time with newlines

### ISSUE THREAD

**Issue by ashsearle** [angular/angular.js#15794]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using a date format containing a newline is treated as though the format ended at the newline.
i.e. `| date: 'dd MMM\nyyyy'` is treated as though it were `| date: 'dd MMM'`

Plunkers: [Angular 1.5.10](https://plnkr.co/edit/dlN2hEv5XXcCPcooflcH?p=preview), [Angular 1.6.3](https://plnkr.co/edit/4ypDtgx1Y9Ao7DCp2HZh?p=preview), [Angular 2.unknown](https://plnkr.co/edit/HW9iGwyDSJza72fKYZzU?p=preview)

**What is the expected behavior?**
The format string should be processed in its entirety.

**What is the motivation / use case for changing the behavior?**
A UI design required a timestamp to be formatted with date and time separated by a newline.  This should be as simple as `| date: 'yyyy-MM-dd\nHH:mm'` (assuming an appropriate CSS `white-space` value.)

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Appears to affect all versions of since at least [March 2012](https://github.com/angular/angular.js/blob/2430f52bb97fa9d682e5f028c977c5bf94c5ec38/src/ng/filter/filters.js#L237), including [angular 2](https://github.com/angular/angular/blob/d036165a191d81955e68620eeed5be74a551d4ba/modules/%40angular/common/src/pipes/intl.ts#L44) 

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Fix in pull request #15792

**Comment by Narretz** [comment]
I see this more as a feature to be honest. And the workaround you posted is not that bad. But since the change is simple ... let's see what others say.

**Comment by ashsearle** [comment]
I'd argue it's a bug as you can't even embed newlines using escapes.  Documentation [doesn't mention this limitation](https://docs.angularjs.org/api/ng/filter/date):

> format string can contain literal values. These need to be escaped by surrounding with single quotes (e.g. `"h 'in the morning'"`).

I don't see why `"h 'in the\nmorning'"` shouldn't be expected to work.

(Incidentally, while trying alternative escape sequences like `\u000a`, I found modern unicode escape syntax like `\u{0a}` breaks horribly...  Angular does not like that at all...)

**Comment by frederikprijck** [comment]
I'd say it's a feature and not a bug, as docs clearly state: 

> format string can be composed of the following elements:

followed by a list which does not include what you're talking about.

Leaving this aside, I wouldn't say it hurts adding this even though I'd think the use-cases for this are limited.

**Comment by ashsearle** [comment]
A little further investigation: newlines are handled in the first 'token' of the format string.

These work: `| date: '\'Line 1\n\'yyyy'` or even `| date: '🤡\nyyyy'`.
These don't: `| date: 'yyyy\'\nLine 2\''` or even `| date: 'yyyy\n🤡'`.

Is that a feature?

The docs are probably missing a description of how 'other characters' are handled (including characters actually used in the US-default date format strings: e.g. colons, commas, slashes, spaces etc.)

Perhaps the docs need to include this, as used in other libraries - for example:

[PHP](http://php.net/manual/en/function.date.php):
> Unrecognized characters in the format string will be printed as-is

Or [Java](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html):
> All other characters are not interpreted; they're simply copied into the output string during formatting...

**Comment by gkalpak** [comment]
I would say this is obviously a bug in the `DATE_FORMATS_SPLIT` RegExp (and #15792 looks like the correct fix).

Also, 👍 on updating the docs to mention that unrecognized characters are printed as-is (or something similar).

**Comment by Narretz** [comment]
Ok, then let's go with the PR
