### ISSUE TITLE
Not able to pass data to angular component for angular 1.6.2

### ISSUE THREAD

**Issue by snrweb** [angular/angular.js#15793]
Whenever we are passing data using 'bindings' to angular component it is getting undefined.

This issue is reproducible for angular version 1.6.2 whereas it is working as expected for version 1.5.10. In my project I am also using angular-route and angular material (1.1.1).

Steps to reproduce:
1. Create a component
2. Inject the module
3. Pass any variable to the component
4. Do the bindings using '<'
5. The variable is getting undefined from the component.

**Comment by frederikprijck** [comment]
@snrweb This appears to be working for me: https://plnkr.co/edit/ngvCHCkw2yuSn9I46xUf?p=preview

For support, please contact us through any of the ways mentioned at:
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by healqq** [comment]
@snrweb I guess, you stumbled upon this change: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes

**Comment by frederikprijck** [comment]
@snrweb Are you accessing the input binding in the constructor ? If so, you need to move this to the `$onInit` hook as mentioned in @healqq 's link.

**Comment by Narretz** [comment]
I'm pretty sure @frederikprijck and @healqq are right - please read the BC notes and change your code if necessary. If the problem still persists, please reopen issue with a demo.
