### ISSUE TITLE
Error Page for transclude: noSlot

### ISSUE THREAD

**Issue by PatrickWatzlawik** [angular/angular.js#15790]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Angular threw an error due to misuse of transclude and transclude-slots. The generated error url linked to a not existing page. [https://docs.angularjs.org/error/$compile/noslot?p0=foo&p1=bar](https://docs.angularjs.org/error/$compile/noslot?p0=foo&p1=bar)
Note: This is not the originial generated url. I replaced the content of the query parameters `p0` and `p1`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
http://plnkr.co/edit/Sj4LpgEdzeNmKh3LThXR

**What is the expected behavior?**
A functional error page.

**What is the motivation / use case for changing the behavior?**
Helping developer.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
Happened on 1.5.11, I guess on every browser/OS. When you change the angular version on the plunkr to 1.6.2, it also appears.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I think its a regression bug, but I'm really not sure.

**Comment by JoshuaJWilborn** [comment]
@Narretz I'd like to take a stab at updating this. I found https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation for information on how angular handles docs, but no specific information on how error pages are generated. Do you have any additional documentation you suggest I read?

**Comment by Narretz** [comment]
Hi @JoshuaJWilborn, thanks for your interest. The wiki info is incomplete (and we don't maintain it ...)
Fortunately, creating an error page is very simple: just ceate a file with the error name in this folder: https://github.com/angular/angular.js/tree/c80fa1cfe13b3b08b934e7e8ee073661f2b1ab8b/docs/content/error/%24compile
You can use one of the existing errors as a guideline, e.g. reqslot which is also transclusion-related.
