### ISSUE TITLE
A date filter bug.

### ISSUE THREAD

**Issue by yy7054wyq5** [angular/angular.js#15802]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
use date filter in html.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

1483200060 *1000 | date: 'yyyy-mm-dd HH:mm:ss' // 2017-01-01 00:01:00
1483203600 *1000 | date: 'yyyy-mm-dd HH:mm:ss' // 2017-00-01 01:00:00
1483200001 *1000 | date: 'yyyy-mm-dd HH:mm:ss' // 2017-00-01 00:00:01

**What is the expected behavior?**

1483200060 *1000 | date: 'yyyy-mm-dd HH:mm:ss' // 2017-01-01 00:01:00
1483203600 *1000 | date: 'yyyy-mm-dd HH:mm:ss' // 2017-01-01 01:00:00
1483200001 *1000 | date: 'yyyy-mm-dd HH:mm:ss' // 2017-01-01 00:00:01

**What is the motivation / use case for changing the behavior?**
When ‘Minute’ is zero. The 'month' is zero.

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
angular 1.5.8 

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by frederikprijck** [comment]
This looks like a general support question, please contact anyone over at any of the official support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

> When ‘Minute’ is zero. The 'month' is zero.

You need to you uppercase for months, lowercase for minutes.

Could you try changing `yyyy-mm-dd HH:mm:ss` to `yyyy-MM-dd HH:mm:ss` ?

**Comment by gkalpak** [comment]
@frederikprijck, is right. This i an issues with incorrect usage (`m` vs `M` for month), not a bug.

**Comment by yy7054wyq5** [comment]
Thank u.
