### ISSUE TITLE
ng-aria 1.4.7 breaking in angular 1.5.x

### ISSUE THREAD

**Issue by matheuslc** [angular/angular.js#15820]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
ng-aria are breaking with angular.js 1.5.9. Looking into the code, at this commit: https://github.com/angular/angular.js/commit/60e294cbd8f0c34ed03046778a0be3befc6b6982 ng-aria is now using .info module function (only available in angular 1.6). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**
* Use ng-aria 1.4.7 with angular 1.5.9

**What is the expected behavior?**
ng-aria working with angular 1.5.9. 

**What is the motivation / use case for changing the behavior?**
This error breaks the whole application. In this case, ng-aria should have it's version bumped, no?

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Chrome 56 macOS
Angular 1.5.9
ng-aria 1.4.7

**Comment by Narretz** [comment]
You cannot use angular-aria 1.4.7 with Angular 1.5.9, or any other version for that matter. I assume in your package defintion file you haven't set the correct dependencies. You have to lock down your dependencies so that there's never a version mismatch.

**Comment by matheuslc** [comment]
I did it @Narretz! Thank you!
