### ISSUE TITLE
Update from 1.6.2 to 1.6.3

### ISSUE THREAD

**Issue by Zelle97** [angular/angular.js#15821]
Hello, 
we updated our YaaS-Store from version 1.6.2 to 1.6.3 and got the following Error in our Karma PhantomJS Tests on Debian GNU/Linux 7.11 (wheezy):

`TypeError: undefined is not a function (evaluating 'b.module("ngResource", ["ng"]).info({angularVersion:"1.6.3"})')`

The Error only occurs on Linux, not on Windows and was resolved by rolling back to version 1.6.2.

**Comment by frederikprijck** [comment]
Did you update all your `angular.js` libraries to `1.6.3` ?

**Comment by Narretz** [comment]
@frederikprijck is right, you must update all angular-* modules to 1.6.3. You probably haven't explicitly updated angular to 1.6.3

**Comment by Zelle97** [comment]
Thanks for the Quick response! Awesome Help.

**Comment by pradeep008** [comment]
Ll
