### ISSUE TITLE
MEAN.JS AngularJS - ng-repeat displaying blank rows

### ISSUE THREAD

**Issue by denGitHub** [angular/angular.js#15830]
![mean](https://cloud.githubusercontent.com/assets/2093832/24051571/23615740-0b3b-11e7-930f-36cf4bd1ed6f.png)
![php](https://cloud.githubusercontent.com/assets/2093832/24051570/235d29c2-0b3b-11e7-8897-0a77e9d95a2f.png)

I take any example with working ng-repeat.

For example this:

https://plnkr.co/edit/6IeQBH49Z3SoU817IbVk?p=preview

On PHP based site it is working. But on the latest MEAN.js it is displaying blank rows though it renders correct number of rows.

For details http://stackoverflow.com/questions/42855698/mean-js-angularjs-ng-repeat-displaying-blank-rows

**Comment by frederikprijck** [comment]
Github issue's are reserved for bugs and feature request, general support is provided through any of the official channels mentioned [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

I've commented on your SO link, so we can continue over there.

**Comment by Narretz** [comment]
@frederikprijck is absolutely right

**Comment by denGitHub** [comment]
Thank you guys. I am sure  you can help to figure out the issue.
