### ISSUE TITLE
$routeProvider's resolveRedirectTo option could use a bit clearer error documentation

### ISSUE THREAD

**Issue by tsclaus** [angular/angular.js#15834]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
resolveRedirectTo lacks specific documentation regarding how the dependencies are injected, but as far as I can tell they are supposed to be specified as arguments to the function, however I'm not sure if there is alternate injection syntax, but if the function argument names are the only way to inject them it might cause problems with minification, though minifiers as new as the resolveRedirectTo option should be able to handle it.

**Expected behavior**
resolveRedirectTo's documentation for when it fires the $routeChangeError event should include the condition if any of the dependencies fail to inject (for instance you pass as an argument name a factory name that doesn't exist)

**Minimal reproduction of the problem with instructions**
From the master docs: `If the function throws an error or the returned promise gets rejected, no further processing will take place and the $routeChangeError event will be fired.` This does not reference the dependency injection option and merely referring to `resolve`'s documentation does not fully confer understanding of the possible error.

**What is the motivation / use case for changing the behavior?**
The resolveRedirectTo option is one of the most powerful parts of $routeProvider but lacks the necessary documentation for people to use it effectively.

**Comment by gkalpak** [comment]
Thank you for taking the time to submit this issue. I am a little confused though.

The docs say that dependencies can be injected into the provided function. As in many places in the docs, we do not explicitly mention all the ways that DI works in AngularJS (and that you can use either the `$inject` property or inline array annotation or implicit annotation). If you think it would be useful to add a link to [$injector.invoke][1] (as we do in `resolve`), that's fine by me.

As far as the error is concerned, it is the typical DI error that you get in similar cases throughout AngularJS, which mentions the chain of dependencies that lead to the unknown provider and point to the [$injector:unpr][2] error.

##
That said, I would be more than happy to review a pull request improving the docs :smiley: 

[1]: https://docs.angularjs.org/api/auto/service/$injector#invoke
[2]: https://docs.angularjs.org/error/$injector/unpr

**Comment by tsclaus** [comment]
This is not specifically related to the documentation, but if the $routeChangeError event isn't handled, it might be useful to log it's occurrence in the console. I did run into the minification issue and the result was navigating to that route was a blank page that lacked any error messages (it did not have the DI error with the minified provider name).

**Comment by gkalpak** [comment]
Happy to look into a reproduction :smiley:
