### ISSUE TITLE
'$resource:badcfg' error will cause angular throw infinite '$rootScope:inprog' error.

### ISSUE THREAD

**Issue by OneOfTheWorld** [angular/angular.js#15831]
***Note*: for support questions, please use one of these channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
when '$resource:badcfg' error happened, angular will throws infinite '$rootScope:inprog' error util the browser crashed, and also prevent other operations on the same page.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

**What is the expected behavior?**
when '$resource:badcfg' error happened', just throws error logs here, and do not impact other operations.

**What is the motivation / use case for changing the behavior?**

**Which versions of AngularJS, and which browser / OS are affected by this issue? Did this work in previous versions of AngularJS? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**
v1.6.x

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
v1.3.x do not have this kind of issue.

**Comment by OneOfTheWorld** [comment]
Supplement the error logs example:
Uncaught Error: [$resource:badcfg] Error in resource configuration for action `get`. Expected response to contain an object but got an array (Request: GET /api/carrier/query)
http://errors.angularjs.org/1.6.3/$resource/badcfg?p0=get&p1=object&p2=array&p3=GET&p4=%2Fapi%2Fcarrier%2Fquery
    at angular.js:66
    at angular-resource.js:750
    at processQueue (angular.js:16843)
    at angular.js:16887
    at Scope.$digest (angular.js:17982)
    at Scope.$apply (angular.js:18280)
    at done (angular.js:12378)
    at completeRequest (angular.js:12604)
    at XMLHttpRequest.requestLoaded (angular.js:12532)
(anonymous) @ angular.js:66
(anonymous) @ angular-resource.js:750
processQueue @ angular.js:16843
(anonymous) @ angular.js:16887
$digest @ angular.js:17982
$apply @ angular.js:18280
done @ angular.js:12378
completeRequest @ angular.js:12604
requestLoaded @ angular.js:12532
angular.js:66 Uncaught Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.6.3/$rootScope/inprog?p0=%24digest
    at angular.js:66
    at beginPhase (angular.js:18535)
    at Scope.$digest (angular.js:17958)
    at angular.js:18211
    at completeOutstandingRequest (angular.js:6274)
    at angular.js:6554
(anonymous) @ angular.js:66
beginPhase @ angular.js:18535
$digest @ angular.js:17958
(anonymous) @ angular.js:18211
completeOutstandingRequest @ angular.js:6274
(anonymous) @ angular.js:6554
angular.js:66 Uncaught Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.6.3/$rootScope/inprog?p0=%24digest
    at angular.js:66
    at beginPhase (angular.js:18535)
    at Scope.$digest (angular.js:17958)
    at angular.js:18211
    at completeOutstandingRequest (angular.js:6274)
    at angular.js:6554
......

**Comment by frederikprijck** [comment]
@OneOfTheWorld Do you have a sample (plunkr, fiddle, ...) to reproduce the issue ?

**Comment by OneOfTheWorld** [comment]
Sorry, I cannot reproduce this issues in Plunker, but I will try to figure out what's going on, and update here.

**Comment by OneOfTheWorld** [comment]
Sorry for my mistake, found the reason, when I try to rewrite the '$exceptionHandler' service, I simply use 'throw exception', this will cause the infinite '$rootScope:inprog' error.
`.factory('$exceptionHandler', function ($log) {
            return function (exception, cause) {
                 throw exception;    // wrong
            };
        })`

`.factory('$exceptionHandler', function ($log) {
            return function (exception, cause) {
                $log.error(exception, cause);   // right
            };
        })`
