### ISSUE TITLE
Add missing / fix incorrect error docs 

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#15852]
- [ ] $parse:esc is an error that's apparently impossible to hit https://github.com/angular/angular.js/blob/c35786ae2634fc82a79dc42f58e138a9d33cf67e/src/ng/parse.js#L457 @lgalfaso can we remove this error?
- [ ] $parse:lval needs docs https://github.com/angular/angular.js/blob/c35786ae2634fc82a79dc42f58e138a9d33cf67e/src/ng/parse.js#L342
- [ ] $route:norout needs docs: https://github.com/angular/angular.js/blob/c35786ae2634fc82a79dc42f58e138a9d33cf67e/src/ngRoute/route.js#L612
- [ ] find out why tpload error has mixed up namespaces: https://github.com/angular/angular.js/pull/15844#issuecomment-288457572

**Comment by JoshuaJWilborn** [comment]
Hello again @Narretz  Are these 2 more error files similar to the one I just made or a regular doc page?

**Comment by Narretz** [comment]
Hi @JoshuaJWilborn, for these error you'll need to look into the code and go from there to write a description. I think $route:norout is pretty simple to document, $parse:lval maybe a bit more involved.

**Comment by petebacondarwin** [comment]
Why the breaking change @Narretz ? This is a docs only change, right?

**Comment by Narretz** [comment]
@petebacondarwin the BC is only for https://github.com/angular/angular.js/pull/15844#issuecomment-288457572, because changing the error identifier is technically a BC for apps that check for a specific error code. Very small, but still. Documentation is the description, or the error document - this applies to the other errors listed

**Comment by petebacondarwin** [comment]
Regarding `this.throwError('IMPOSSIBLE')`: we should leave that in place. It is there to catch a programming error slipping into the code in the future.

**Comment by petebacondarwin** [comment]
Regarding the `tpload` error, the change was introduced by @jbedard here: https://github.com/angular/angular.js/pull/13701#discussion_r49553155

I think to keep things simple we should just remove the `$templateMinErr` variable and reuse the `$compileMinErr` variable.

**Comment by Narretz** [comment]
@petebacondarwin do you mean the tpload error should have its own namespace, i.e. $templateRequest?

**Comment by petebacondarwin** [comment]
1 2 and 3 are fixed on master
4 is partially fixed on master and will be completely fixed via https://github.com/angular/angular.js/pull/16461
