### ISSUE TITLE
provide isError and use it in place of instanceof Error

### ISSUE THREAD

**Issue by graingert** [angular/angular.js#15868]
**I'm submitting a ...**

- [x] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

angular sometimes stringifies unhandled rejections, even if they're errors.

**Expected / new behavior:**

Angular should pass them on to the correct excetion handler

**Minimal reproduction of the problem with instructions:**
Difficult to reproduce

**Angular version:** 1.x.y
1.6.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Anything else:**
Provide angular.isError:
```js
function isError(V) {
  var tagName = Object.prototype.toString.call(V);
  return (
    tagName === '[object Error]' ||
    tagName === '[object Exception]' ||
    V instanceof Error
  );
}
```
MIT from https://github.com/yefremov/iserror/blob/master/index.js

and use it wherever instanceof Error was used.

**Comment by gkalpak** [comment]
I don't think it makes sense to complicate things unless there is a reproducible, valid usecase, which makes it worth it.

**Comment by graingert** [comment]
this is an error passed from another context, eg another frame.

**Comment by gkalpak** [comment]
OK, sounds reasonable. Any idea where `object Exception` comes from? (Also, what about `DOMException`s?)

**Comment by graingert** [comment]
@gkalpak what would be a good way to construct a test that boots up an iframe?

```js
var iframe = document.createElement('iframe');
document.body.appendChild(iframe);
try {
    var error = new iframe.contentWindow.Error();
    expect(isError(error)).to.be.true();
} finally {
    iframe.parentElement.removeChild(iframe);
}
```

**Comment by gkalpak** [comment]
Let's move the discussion to #15872.
