### ISSUE TITLE
ng-controller (not working) vs ngController (working)

### ISSUE THREAD

**Issue by marius-cristian** [angular/angular.js#15861]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

in the html file: `<div class="app management" ngController= "AppsController2">` works
if i use instead: `<div class="app management" ng-controller= "AppsController2">` the following error:
Error: [$controller:ctrlreg] The controller with the name 'AppsController2' is not registered.
http://errors.angularjs.org/1.6.2/$controller/ctrlreg?p0=AppsController2

using mean.io stack;

also when using ngController; buttons onClick or any other function does not  work. only for this case;\\

controller.js

```js
(function() {
    'use strict';
    
    function AppsController2($scope, $http, Global, Profile,  $stateParams) {
        $scope.global = Global;
        $scope.package = {
            name: 'profile'
        };
 }
        
    angular
        .module('mean.profile')
        .controller('AppsController2', AppsController2);

    AppsController2.$inject = ['$scope','$http', 'Global', 'Profile', '$stateParams'];
    
    
})();
```

** other example **
The exact same thing for a different controller

controller2.js

```
(function() {
    'use strict';
    /* jshint -W098 */
    function PaymentController($scope,$http, Global, Profile,  $stateParams) {
        $scope.global = Global;
        $scope.package = {
            name: 'profile'
        };
        }

    angular
        .module('mean.profile',[require('angular-credit-cards')])
        .controller('PaymentController', PaymentController);

    PaymentController.$inject = ['$scope', '$http','Global', 'Profile', '$stateParams'];

})();
```
and example2.html 
`<div class="profile-example" ng-controller="PaymentController">` works perfectly

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
I guess you're missing some parts of your code, However Github issues are reserved for bugs and feature requests. This looks more like a general support question.

For general support questions, feel free to ask for help in any of the channels mentioned [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

**Comment by gkalpak** [comment]
@frederikprijck, is right. [Othr channels][1] are more appropriate for these types of questions.

##
That said, `ngController` is ignored by AngularJS, so it doesn't complain about a missing controller, nor does it instantiate it. If `ng-controller="AppsController2"` complains, you either haven't loaded the appropriate JS files, or haven't added the appropriate modules as dependencies to your app's module.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by marius-cristian** [comment]
my bad. there is a space included after the equal. that was my error. not a bug.
