### ISSUE TITLE
$q.all() behaviour by rejections

### ISSUE THREAD

**Issue by cosenmarco** [angular/angular.js#15866]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
When one of the promises used to build a compound promise with $q.all() experiences a rejection, then the compound promise issues a rejection immediately without waiting for the other promises in the aggregate to complete thus IMHO breaking the contract of promise composition.

**Expected / new behavior:**
I expect that all promises would complete (either successfully or by a rejection) before a rejection on the aggregated promise is triggered.
Also I would expect this to be documented properly and with examples.

**Minimal reproduction of the problem with instructions:**
http://plnkr.co/edit/M8MS1LCzXoe3wDGTp0qv

Make sure you look at the browser console and you'll see the following sequence:
PROMISE 1
PROMISE 2
PROMISE AGGREGATE CATCH
PROMISE 3

while I would expect something like:
PROMISE 1
PROMISE 2
PROMISE 3
PROMISE AGGREGATE CATCH

**Angular version:** 1.5.9

**Browser:** all

**Anything else:**
I know fixing this would be a big breaking change.
I also know that there are several different ways of doing this.

One simple way would be:
- register the first rejection which happens
- wait for all other promises to complete
- finally reject the aggregate with the first registered rejection's value

Another way would be:
- register all rejections which are happening into an array pretty much the same way it happens for clean resolutions
- once all promises are resolved or rejected issue a rejection with the array of registered rejection values (which might be sparse) as rejection value for the aggregate

**Comment by Narretz** [comment]
Hi,
this behavior is consistent with th ECMA script proposal, and changing it would make it at odds with most/all other promise implementations: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

This is a common issue and you can find ways to handle this all over the web. For angularjs, this lib seems useful: https://github.com/ohjames/angular-promise-extras

**Comment by cosenmarco** [comment]
Ok, thanks for taking the time to answer. I'll check promise-extras out.
