### ISSUE TITLE
Building and Testing AngularJS - grunt package failing

### ISSUE THREAD

**Issue by atul-shimpi** [angular/angular.js#15873]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
I am building and testing AngularJs by referring to https://docs.angularjs.org/misc/contribute.
The step to build package - grunt package is failing with below message on terminal

--------------------------------------------------------------------------
Loading "Gruntfile.js" tasks...ERROR
Error: Unable to read CDN version, are you offline or has the CDN not been pr
operly pushed?
Perhaps you want to set the NG1_BUILD_NO_REMOTE_VERSION_REQUESTS environment
variable?
Warning: Task "package" not found. Use --force to continue.
Aborted due to warnings.
--------------------------------------------------------------------------

**Expected / new behavior:**
Message should not come. Package should be build in build directory.

**Minimal reproduction of the problem with instructions:**
Follow steps given on https://docs.angularjs.org/misc/contribute.
Section : Building AngularJS.
Line : Build AngularJS (which will install `bower` dependencies automatically):
grunt package - (fails here)

**Anything else:**
Few suggested to comment the error in Gruntfile.js, works after that but not sure if that is correct.
Tried setting NG1_BUILD_NO_REMOTE_VERSION_REQUESTS to 1, but did not worked.

System Configuration
Windows 7, 64 bit

**Comment by gkalpak** [comment]
This error should not be thrown if you have access to the internet.

But in any case, setting a `NG1_BUILD_NO_REMOTE_VERSION_REQUESTS` environment variable should prevent the error :confused:
How did you set it?

**Comment by atul-shimpi** [comment]
I set the environment variable from "My computer", environment variables. Internet connection is there. It's through proxy.
I tried this building from windows command prompt.

Sent from my Sony Xperia™ smartphone


---- George Kalpakas wrote ----


This error should not be thrown if you have access to the internet.

But in any case, setting a NG1_BUILD_NO_REMOTE_VERSION_REQUESTS environment variable should prevent the error 😕
How did you set it?

**Comment by atul-shimpi** [comment]
I set value to 1.

Sent from my Sony Xperia™ smartphone


---- George Kalpakas wrote ----


This error should not be thrown if you have access to the internet.

But in any case, setting a NG1_BUILD_NO_REMOTE_VERSION_REQUESTS environment variable should prevent the error 😕
How did you set it?

**Comment by atul-shimpi** [comment]
I have set NG1_BUILD_NO_REMOTE_VERSION_REQUESTS  to 1. Is that correct value?

**Comment by Narretz** [comment]
I found out a while ago that since we switched to yarn, the variable doesn't actually catch all internet access cases. So at the moment, internet access is required. Maybe you need to configure your proxy or the node proxy?

**Comment by atul-shimpi** [comment]
Ok. But if I comments the error in gruntfile, it works. Do I need to set npm proxy? That's what u are saying?

Sent from my Sony Xperia™ smartphone


---- Martin Staffa wrote ----


I found out a while ago that since we switched to yarn, the variable doesn't actually catch all internet access cases. So at the moment, internet access is required. Maybe you need to configure your proxy or the node proxy?

**Comment by Narretz** [comment]
I don't know what you meany by "commenting the error", sorry. You mean the line that presumably throws the error?

**Comment by atul-shimpi** [comment]
Yes.

Sent from my Sony Xperia™ smartphone


---- Martin Staffa wrote ----


I don't know what you meany by "commenting the error", sorry. You mean the line that presumably throws the error?

**Comment by Narretz** [comment]
Well, if the line you removed removes the remote request, then the internet access is not problem anymore. For developing and testing, it should work without the remote request.
Wrt the proxy, I can't really debug this for you. in general you have to tell node / npm that you are using a proxy.

**Comment by atul-shimpi** [comment]
Ok.Let me try this. Will share the results

Sent from my Sony Xperia™ smartphone


---- Martin Staffa wrote ----


Well, if the line you removed removes the remote request, then the internet access is not problem anymore. For developing and testing, it should work without the remote request.
Wrt the proxy, I can't really debug this for you. in general you have to tell node / npm that you are using a proxy.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
