### ISSUE TITLE
Routing by base path

### ISSUE THREAD

**Issue by lightapp24** [angular/angular.js#15878]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Routing occurs only within one basic path. If the site has several applications, then for them it is necessary to define the paths separately.

**Expected / new behavior:**
Define the path along with the base path if necessary.

**What is the motivation / use case for changing the behavior?**
I do not want to configure paths in different places and load the necessary settings, when I could configure it in one place.

**Other information**
I have a solution (see https://github.com/lightapp24/angular.js/tree/routing-by-basePath_Href). If this feature is approved, I will prepare PR.

**Comment by lightapp24** [comment]
Sorry. Saying "several applications", I mean different pages that contain one and the same ng-app directive.

**Comment by gkalpak** [comment]
Sorry, I am still not sure what this is about. Can you give an example or describe the usecase in a little more detail?

**Comment by lightapp24** [comment]
OK, suppose we have two pages, let's name their profile and community.

**Profile is located in http://example.com/profile and contain:**
```
<html>
<head>
<!-- definition of the head -->
<script src="js/app.js"></script>
<script src="js/profile_route.js"></script>
</head>
<body ng-app="myApp">
<!-- part of profile content generated on the server side -->
<ng-view>
<!-- part of profile content that uses ng-view -->
</ng-view>
</body>
</html>
```

**Community is located in http://example.com/community and contain:**
```
<html>
<head>
<!-- definition of the head -->
<script src="js/app.js"></script>
<script src="js/community_route.js"></script>
</head>
<body ng-app="myApp">
<!-- part of community content generated on the server side -->
<ng-view>
<!-- part of community content that uses ng-view -->
</ng-view>
</body>
</html>
```

**We have app.js:**
```
var app = angular.module("myApp", ["ngRoute"]);

// some controllers, directives and etc.
```

**profile_route.js**
```
app.config(function($routeProvider) {
    $routeProvider
    .when("/", {
        templateUrl : "tmpl/profile/main.htm"
    })
    .when("/contacts", {
        templateUrl : "tmpl/profile/contacts.htm"
    })
    .when("/security", {
        templateUrl : "tmpl/profile/security.htm"
    });
});
```

**community_route.js**
```
community_route.js
app.config(function($routeProvider) {
    $routeProvider
    .when("/", {
        templateUrl : "tmpl/community/main.htm"
    })
    .when("/settings", {
        templateUrl : "tmpl/community/settings.htm"
    })
    .when("/security", {
        templateUrl : "tmpl/community/security.htm"
    });
});
```
This example of an incomplete SPA, it is something hybrid.

We have to load the router separately so that they do not conflict. The only way out of this situation is to use the base path (in an example this is /profile and /community) in routing. My solution uses the format "[/basePath1,/basePath2,...]/somePath", where "[/basePath1,/basePath2,...]" is an optional part. For this example, this will look like:
```
app.config(function($routeProvider) {
    $routeProvider
    .when("[/community]/", {
        templateUrl : "tmpl/community/main.htm"
    })
    .when("[/community]/settings", {
        templateUrl : "tmpl/community/settings.htm"
    })
    .when("[/community]/security", {
        templateUrl : "tmpl/community/security.htm"
    }).when("[/profile]/", {
        templateUrl : "tmpl/profile/main.htm"
    })
    .when("[/profile]/contacts", {
        templateUrl : "tmpl/profile/contacts.htm"
    })
    .when("[/profile]/security", {
        templateUrl : "tmpl/profile/security.htm"
    });
});
```

Sorry for my English.

**Comment by gkalpak** [comment]
I see what you mean now. I am not too keen on this change. If nothing else, if you have two distinct pages (different apps) it makes most sense to keep the routes separate (most people even separate their routes per view).

Complicating things (e.g. in terms of API surface, maintainance cost, LOC) just in order to allow (very few) people do what doesn't seem like a good idea (putting routes from different apps in the same file) is something I don't like.

Putting this in the Ice Box, but leaving it open to see what others think.

**Comment by Narretz** [comment]
I agree that this is a feature that would only benefit very few developer and the added code / complexity is not worth implementing it.
