### ISSUE TITLE
Documentation for input[week] doesn't mention what will be the underlying Date object

### ISSUE THREAD

**Issue by Vicente69** [angular/angular.js#15883]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [X] other (Please do not submit support requests here (see above))

**Current behavior:**

The documentation for angular input[week] says the input text 'yyyy-Www' is transformed into a Date object. But it can hardly be used as the documentation doesn't say exactly which day of the week, and what time is put in the Date object.

**Expected / new behavior:**

The documentation shall mention what will be the underlying Date object.

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.2

**Browser:** [all]

**Anything else:**

**Comment by frederikprijck** [comment]
I wouldn't say the `input[week]` is not usable due to this as it's pretty easy to check for yourself:
https://plnkr.co/edit/bn6TieIDiyS5HgaQQgXF?p=preview

I'm abit confused as it looks like it defaults to wednesdays for me. I guess it would be good to update the docs.

**Comment by Vicente69** [comment]
It seems to be locale-dependent also. In France, it seems to be thursday, as the first day of week is monday.

**Comment by frederikprijck** [comment]
It seems to be using thursday as the day by adding a certain factor of 7 days to the firstThursday of that year:

https://github.com/angular/angular.js/blob/03043839d5a540b02208001fe12e812dfde00a8e/src/ng/directive/input.js#L1359

Any idea what the reason for this is @gkalpak ?

**Comment by gkalpak** [comment]
From [WikiPedia] on ISO 8601:

> There are several mutually equivalent and compatible descriptions of week 01:
> - the week with the year's first Thursday in it (the formal ISO definition),
> [...]
> The week number can be described by counting the Thursdays: week 12 contains the 12th Thursday of the year.
> [...]
> The Thursday of each ISO week is always in the Gregorian calendar year denoted by the ISO week-numbering year.

So, we find the first Thursday and then count Thursdays to find the week number.
I am not 100% sure why we pick Thursday as the day for the Date object, but I suspect it is because it is the only day of the week that is guaranteed to be in the Gragorian calendar year denoted by `yyyy`.

##
Docs improvements are always welcome :smiley:

[1]: https://en.wikipedia.org/wiki/ISO_8601#Week_dates

**Comment by frederikprijck** [comment]
Yep @gkalpak I guess Thursday is used to guarantee the correct month and year. If Thursday would be the 1st of January 2017, it would resolve to Monday (if taking Monday that is) which would be december 2016 (both incorrect year and month) . Which still is the same week but may be odd...

**Comment by frederikprijck** [comment]
> I am not 100% sure why we pick Thursday as the day for the Date object, but I suspect it is because it is the only day of the week that is guaranteed to be in the Gragorian calendar year denoted by yyyy.

By looking at the ISO spec, it makes perfect sense to pick thursday. As it's possible that any other day of that week (when using thursday to calculate week number) could be in a different month/year (so different Gregorian calendar year as you said).

**Comment by gkalpak** [comment]
@Vicente69 or @frederikprijck, if you feel like submitting PR adding a note to the docs, please do :grin:
