### ISSUE TITLE
ng-value does not work with ng-change on radio buttons

### ISSUE THREAD

**Issue by DrVishalKumarSahu** [angular/angular.js#15882]
`<input type="radio" class='options' name='option-{{que.qn}}' value='{{option.aid}}'  data-ng-change='markOption(que.qn,option.aid)' data-ng-model='que.markedAnswerID' data-ng-value='que.markedAnswerID' />`

Everything works fine if I omit the `data-ng-value='que.markedAnswerID' ` from above code. Is there any limitation of using these two?

**Comment by frederikprijck** [comment]
I'm not sure what you're trying to do here, but I'm not sure if using the same value for `data-ng-model` and `data-ng-value` is what you're supposed to be doing. I'm also not sure why you are making use of both `value` and `data-ng-value`.

I've created a plunkr without `value` and with a different value for `data-ng-value`: https://plnkr.co/edit/96yat32aYoGEesSfwl1h?p=preview

Please keep in mind that Github issues are reserved for bugs and feature requests.
For general support questions, feel free to ask for help in any of the channels mentioned [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

**Comment by gkalpak** [comment]
Using any two of `value`, `ngValue` and `ngModel` on the same element is not a supported usecase. They all modify the `value` property of the element, so they are likely to overwrite or conflict with each other. Whatever you are trying to achieve, there must be a better way.

That said, @frederikprijck is right. There are more appropriate places for discussing usage problems, such as this one.

**Comment by frederikprijck** [comment]
@gkalpak Isn't it okay to use `value` or `ngValue` on a radio button or option element that's also using `ngModel`?

> It is mainly used on input[radio] and option elements, so that when the element is selected, the ngModel of that element (or its select parent element) is set to the bound value. It is especially useful for dynamically generated lists using ngRepeat, as shown below.

**Comment by gkalpak** [comment]
@frederikprijck, you are right. Let me re-phrase: You should not use `value` _and_ `ngValue` with `ngModel`. In most cases, you should only use one of them (although you might get away with using `ngModel` and one of the other two). Radio buttons are strange beasts, so for them using `value` _or_ `ngValue` together with `ngModel` is fine.

(Note that for `option` elements, you don't have `value`/`ngValue` and `ngModel` on the same element, so this is something different.)

**Comment by DrVishalKumarSahu** [comment]
**ng-model** sets '**value**' attribute to have value of 'que.markedAnswerID'. Using **value**, **ng-value** and **ng-model** together should not affect it.

**Comment by frederikprijck** [comment]
@DrVishalKumarSahu You should not be using `value` and `ngValue` together, and it's normal that leaving one of those two out results in a working solution.

Regarding ngValue, the docs clearly state:

> AngularJS expression, whose value will be bound to the value attribute and value property of the element.

So using ngValue, angularjs will bind to `value` for you. So you should not be manually assigning `value` as `ngValue` will do it for you.
