### ISSUE TITLE
Feature request: angularjs- get the dynamic index for particular object in ng-if

### ISSUE THREAD

**Issue by imzubair10** [angular/angular.js#15895]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

i am trying to show divs based on the existence of object in json and if certain object is not present then i need to show the other div , the only change i need to make here is to show the values based on the index of the object in the json. Rightnow i've hard coded index but this json is returned from the database and indexes will be different, i've written function to properly make if and else conditions work but i am unsure on how i can get the index of that particular object instead of hard coded indexes.
**Expected / new behavior:**

I need to get the index of that particular object instead of hard coded indexes so i can show corresponding object data based on index

**Minimal reproduction of the problem with instructions:**

html
=====
```

<div ng-repeat="p in profileData">
          
    		  <div>{{p.company}}</div> 
    		  <div>{{p.department}}</div>
    		
    			<div ng-if="objectSearch('Devo100',p.metricList)" ng-model="p.metricList.Value">
    			    {{p.metricStatList[2].Value*100}}
    			</div>
    			
    			<div ng-if="!objectSearch('Devo100',p.metricList)">
    			  
    			  should only run if condition fails for Devo100
    			  
    			</div>
    			
    			<div ng-if="objectSearch('Devo101',p.metricList)">
    			  {{p.metricStatList[1].Value*100}}
    			</div>
    			
    			<div ng-if="!objectSearch('Devo101',p.metricList)">
    			  
    			 shoud only run if condition fails for Devo101
    			  
    			</div>
    			
    			<div ng-if="objectSearch('Devo102',p.metricList)">
    			 {{p.metricStatList[2].Value*100}}
    			</div>
    			
    			<div ng-if="!objectSearch('Devo102',p.metricList)">
    			  shoud only run if condition fails for Devo102
    			</div>
    		  <hr>      
    </div>
```

angularjs controller
==============
```

var app = angular.module('plunker', []);
    
    app.controller('MainCtrl', function($scope) {
        $scope.displayToggle = true;
        $scope.profileData = [
    			      {
                   ID: "1",
                   metricList: [{"Value":0.003,"Stat":{"parameter":0,"Name":"test0","Tag":"Devo100"}},
                                 {"Value":0.004,"Stat":{"parameter":0,"Name":"test1","Tag":"Devo101"}},
                                 {"Value":0.005,"Stat":{"parameter":0,"Name":"test2","Tag":"Devo102"}}],                  
                   company: "MSDFT",
                   department: "Sales"
                  },
                  {
                   ID: "2",
                   metricList: null,                  
                   company: "MSDFT",
                   department: "HR"
                  },
      	         {
                   ID: "3",
                   metricList: [{"Value":0.0333333,"Stat":{"parameter":0,"Name":"test2","Tag":"Devo102"}},
                                 {"Value":0.98879874,"Stat":{"parameter":0,"Name":"test0","Tag":"Devo100"}}],                  
                   company: "MSDFT",
                   department: "Development"
                  },
      	          {
                   ID: "4",
                   metricList: [{"Value":0.1,"Stat":{"parameter":0,"Name":"test1","Tag":"Devo101"}},
                                 {"Value":0.25,"Stat":{"parameter":0,"Name":"test0","Tag":"Devo100"}}],                  
                   company: "MSDFT",
                   department: "Finance"
                  },
      	          {
                   ID: "5",
                   metricList: [{"Value":0.233,"Stat":{"parameter":0,"Name":"test0","Tag":"Devo100"}}],                  
                   company: "MSDFT",
                   department: "Accounts"
                  }
    				
    			];
    			
    			$scope.objectSearch = function(type,object) {
          for(var key in object) {
    
            if(object[key].metricList.Tag === type) {
            return true;
            }
          }
          return false;
      };
    });
```

**Angular version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
@imzubair10 I don't see anything related to a feature request. It looks like you're having troubles understanding / using AngularJS. Please know that there's alot of people over at Gitter/StackOverflow who are willing to help you. But as mentioned before Github issues are reserved for bugs and feature requests.
For general support questions, feel free to ask for help in any of the channels mentioned [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

---
I've tried running your code but there's some issues. 
```
$scope.objectSearch = function(type,object) {
     for(var key in object) {
    
       if(object[key].metricList.Tag === type) {
            return true;
       }
     }
     return false;
};
```

This is totally incorrect and throws exceptions, exceptions can be viewed by opening your developer tools in browsers such as Chrome.
Ensure to change the above code to:

```
$scope.objectSearch = function(type,object) {
    
    for(var key in object) {
        if(object[key].Stat.Tag === type) {
            return true;
        }
    }
    return false;
}
```

If you want to elaborate on this, feel free to ping me over at gitter.

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
