### ISSUE TITLE
Component settings doesn't do spell checker in value controller

### ISSUE THREAD

**Issue by renecardozo** [angular/angular.js#15898]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

I have the next example 

```
(function(){
  'use strict';
  var app = angular.module('my.app.components');
  app.component('setTabs',{
    templateUrl: 'tabs.html',
    controlller: 'tabsController'
  })
})();
```
The angularjs doesn't  throw a exception when the field  "controller" has triple "l" also when it is loaded in page the browser doesn't display any message of exception

**Expected / new behavior:**

Angularjs should control the names of setting when is been created a component

**Minimal reproduction of the problem with instructions:**

1: Create a app using a angular
2: Create a component as shown above

**Angular version:** 1.6.3

**Browser:** Chrome XX 

**Anything else:**

**Comment by frederikprijck** [comment]
I don't think alot can be done about this. JavaScript has no types, and the `controller` option is optional. You're not specifying controller, which is fine. The `controlller` you've specified is ignored by angularjs. In JavaScript, you're free to pass an object with as many properties/methods as you want, as long as those you need exist as well.

You could make use of TypeScript if you want to have more control over what's to be passed as an argument and what isn't.

**Comment by Narretz** [comment]
@frederikprijck is right. There's a limit to validation we can or should make in AngularJS, especially since it'll always be at runtime. Typescript is a good idea.

**Comment by renecardozo** [comment]
Thanks for your feedback guys, I'll consider move to typescript and just in case, I field this bug because it given me problems when my app is running I couldn't debug and never it caught the breakpoint.
