### ISSUE TITLE
register dynamic angular module with application.

### ISSUE THREAD

**Issue by rahulgupta20nov** [angular/angular.js#15896]
Hi,
In my application, I am using **requirejs** for dynamically loading the controllers, filters, directives, services, etc. But I can't load dynamically any module. Like, I want to load **angular-google-map** after some screen and need to register with the application then how can I do.

**Comment by rahulgupta20nov** [comment]
I am using 1.5.x angular version.

**Comment by frederikprijck** [comment]
If I recall correctly, AngularJS does not provide any built in way to dynamically register modules.
You could have a look at https://github.com/ocombe/ocLazyLoad which might help you.

That said, Github issues are reserved for bugs and feature requests.
For general support questions, feel free to ask for help in any of the channels mentioned [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

**Comment by Narretz** [comment]
This has been discussed a lot, but is unlikely to make it into AngularJS, as it would necessitate many core and maybe API changes.
Angular has this functionality.
See more discussion in #11015
