### ISSUE TITLE
IE8 errors on promise.catch(noop)

### ISSUE THREAD

**Issue by binarykitchen** [angular/angular.js#15894]
Discussion started in https://github.com/zloirock/core-js/issues/294

Wondering if you would consider replacing all occurrences of `promise.catch(noop)` to `promise['catch'](noop);`?

because I am hesitant to use Babel and that would make AngularJS even more robust I think. Thoughts?

**Comment by frederikprijck** [comment]
@binarykitchen What version of AngularJS are you talking about?

AngularJS has dropped IE8 support as of version 1.3. IIRC, Microsoft has even dropped support for IE8 themselves.

**Comment by binarykitchen** [comment]
using v1.6.4 here ... regardless whether it is still supported or not by others, i still can see a small percentage of users coming with IE8 ...

**Comment by frederikprijck** [comment]
Well I can't realy say whether or not it's a fix they are willing to do. @Narretz / @gkalpak might know.

But as the [docs](https://docs.angularjs.org/guide/ie) explicitly state not supporting IE8 (which is great, as the browser is not supported anymore itself) I wouldn't say patching for IE8 is the way to go. 

Also, the babel solution mentioned looks okay.

**Comment by Narretz** [comment]
Hi, IE8 is unsupported and for full support many more modifications to the code would have to be made (mostly DOM API) to support all edge cases. So changing to `['catch']` only gives you a false sense of security, because it's not full IE8 support.

**Comment by binarykitchen** [comment]
good point guys - will consider babel or something else then.
