### ISSUE TITLE
Angularjs and ldapjs

### ISSUE THREAD

**Issue by zeinebu** [angular/angular.js#15909]
Hi
Please help me, I am new on developing nodejs.
I use ldapjs in an electron angularjs application, I have to get the users of the AD to view, edit and delete it.

`var users =[];
angular.module("app").factory("clientsFactory", function ()
{

var getUsers = function() 
{
	client.search(base_dn, optsUsers, function (err, result) { 
        assert.ifError(err);
		
        result.on('searchEntry', function(entry) {
			users.push({
				'sAMAccountName': entry.object.sAMAccountName,
				'dn': entry.object.dn
			});
			// rslt=JSON.stringify(entry.object);
	        // users=rslt;
			// console.log(rslt);
		
        });
       
 }  );
 
    console.log(users);
    return users;
};

return {
    getUsers: getUsers
    
};
});

My problem is that if I retrieve the result in a list to retrieve it, it does not give me a normal list but an object contains the objects
Then user.dn is empty
Below a screenshot of the users object display in the console:
capture
`
![capture](https://cloud.githubusercontent.com/assets/27298578/24952202/bbd460ac-1f6e-11e7-9d29-e60f69e9228b.PNG)

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
