### ISSUE TITLE
docs Tour of Heroes 5 - Routing Tutorial - Correct tag "my-hero-detail" not "hero-detail"

### ISSUE THREAD

**Issue by biblelogosthegame** [angular/angular.js#15915]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [X ] other (Please do not submit support requests here (see above))
Doc fix recommendation for: https://angular.io/docs/ts/latest/tutorial/toh-pt5.html

**Current behavior:**

"In the Routing tutorial, the docs state that:
Currently, the parent HeroesComponent sets the component's hero property to a hero object with a binding like this:

COPY CODE
<hero-detail [hero]="selectedHero"></hero-detail>"

If you change your code to "hero-detail", the app doesn't work.

**Expected / new behavior:**

I saw that and compared my running working code and noticed that the tag in my code stated "my-hero-detail" and not "hero-detail" and I changed it to "hero-detail" because I thought that I may have made a mistake but the change caused my app to stop running, so I changed it back and it worked.
"In the Routing tutorial, the docs state that:
Currently, the parent HeroesComponent sets the component's hero property to a hero object with a binding like this:

COPY CODE
<my-hero-detail [hero]="selectedHero"></my-hero-detail>"

If you keep your code the way that it is, with respect to the "my-hero-detail" and not "hero-detail," then the code works.

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

I hope I'm making this doc fix properly.  I'm a relative beginner to contributing.

**Comment by gkalpak** [comment]
This repo is for AngularJS (aka 1.x). The documentation you are referring to is for Angular (aka 2+).
Please reopen on https://github.com/angular/angular.
