### ISSUE TITLE
Snippet error in Documentation (`Appendix: Take it slow` section)

### ISSUE THREAD

**Issue by hrskrs** [angular/angular.js#15920]
**I'm submitting a ...**
- [x ] other (Please do not submit support requests here (see above))

**Current behavior:**
On the Documentation page, on Services section there exist a  buggy snippet on `[Appendix: Take it slow](https://angular.io/docs/ts/latest/tutorial/toh-pt4.html)` where `this.getHeroes()` is called instead of `HEROES` constant in `mock-heroes.ts`:

```
getHeroesSlowly(): Promise<Hero[]> {
  return new Promise(resolve => {
    // Simulate server latency with 2 second delay
    setTimeout(() => resolve(this.getHeroes()), 2000); //instead of this.getHeroes, call HEROES
  });
}
```

**Expected / new behavior:**
Instead of returning `this.getHeroes()`, you have to return `HEROES` constant from `mock-heroes.ts`

**Anything else:**
The link for buggy snipper is here:
https://angular.io/docs/ts/latest/tutorial/toh-pt4.html under `Appendix: Take it slow`

**Comment by frederikprijck** [comment]
This repo is for AngularJS (1.x). The documentation you are referring to is for Angular (2+).
Please open an issue at the Angular repository: https://github.com/angular/angular.

**Comment by hrskrs** [comment]
Moved it
