### ISSUE TITLE
angularjs don't work in webpack Hot Module Reloading (HMR).

### ISSUE THREAD

**Issue by yodfz** [angular/angular.js#15938]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**

Run AngularJS on webpack-dev-server,but don't work HMR,HMR is reload page.

**Expected / new behavior:**

Don't reload page.

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
HMR isn't something that is currently supported by AngularJS nativly. IIRC There are some possibilities to use HMR with AngularJS and Webpack by including thirth party libs, but it's not going to be as simple as supporting HMR the way Angular does.

**Comment by Narretz** [comment]
Yep, it's not supported and at this point, it would be too much effort to support it. :(
