### ISSUE TITLE
Radio Buttons Issue when hyphen in ng-value

### ISSUE THREAD

**Issue by FloPrey** [angular/angular.js#15937]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

Behavior in a fiddle:
[http://jsfiddle.net/vs1e39sy/4/](http://jsfiddle.net/vs1e39sy/4/)

**Minimal reproduction of the problem with instructions:**

When a hyphen is put into ng-value, the model doesn't represent the value, also the radio button aren't selectable as they should.

**Angular version:** 1.6.4

**Browser:** Firefox 53, Ubuntu

**Comment by frederikprijck** [comment]
This doesn't look like a bug to me, I've updated your fiddle. Could you check if this is what you're looking for ?

http://jsfiddle.net/vs1e39sy/5/

This looks like a general support question, please contact anyone over at any of the official support channels: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question for questions like this.

**Comment by Narretz** [comment]
@frederikprijck is right - to expand on that, ngValue interprets its content as an expression. If you only want a simple string value, then you can use just value.
