### ISSUE TITLE
Wish to develop a small feature -- multiple pattern validator directive 

### ISSUE THREAD

**Issue by rahulmukherjee85** [angular/angular.js#15943]
Hi There,
While developing, I found a good to have directive for Angular. A multiple pattern validator with error message for each pattern. We need this feature for most of the input control.
I wish to develop this small feature. Can I proceed with a pull request?
 
Thanks and Regards,
Rahul

**I'm submitting a ...**

- [ ] bug report
- [X] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by Narretz** [comment]
Hi, I'm not sure what exactly you have in mind, but I think it sounds like this is something that could be a 3rd party directive / module, not something that needs to go into AngularJS Core.

**Comment by frederikprijck** [comment]
It might be a great starting point to develop it as a 3th party directive/module and reference it here allowing us to have a better sight on what it actually is ?

But it doesn't sound like something that has alot of use-cases to go into the core.

**Comment by rahulmukherjee85** [comment]
hello @Narretz  and @frederikprijck ,
Thanks for the reply. will try to implement the same as a third party plugin.

**Comment by Narretz** [comment]
Ok, then I will close this issue.
