### ISSUE TITLE
ng-click does not trigger rerender of outer elements in the same template

### ISSUE THREAD

**Issue by Somebi** [angular/angular.js#15959]
Inner expressions are rerendered, sibling elements too, but outer elements (siblings to current parent) are not updated.
Only when ng-click is provided with a handler function and $scope is changed inside it, only then it's rerendering all expressions in a view...

Looks like a bug.

Using latest version 1.6.4

**Comment by frederikprijck** [comment]
@Somebi I guess you'll need to provide more information, a reproduction sample using plunkr would be a good idea so we can have a look at the, vaguely, described behavior.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
