### ISSUE TITLE
angularjs.org is down

### ISSUE THREAD

**Issue by hkoske** [angular/angular.js#15955]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

angularjs.org is down

**Expected / new behavior:**

it should be working

**Minimal reproduction of the problem with instructions:**

[See report here](http://www.isitdownrightnow.com/angularjs.org.html)

**Angular version:** 1.x.y

**Browser:** 

all

**Anything else:**

nothing

**Comment by petebacondarwin** [comment]
It should be back up now. We had some problems with firewall rules.

**Comment by Ivru** [comment]
It's down again

**Comment by petebacondarwin** [comment]
And back :-/
We are fighting a security bot inside Google that keeps turning off our firewall rules.

**Comment by monkpit** [comment]
http://isup.me/angularjs.org

It's still down...

**Comment by gkalpak** [comment]
It's up and this time it should be for good :smiley:

**Comment by Ivru** [comment]
Hey guys! It's been a long time. angularjs.or is down again.

**Comment by Narretz** [comment]
@Ivru please don't post in closed issues. There's an open issue about this.
