### ISSUE TITLE
angular#1.5.8 - alert not working

### ISSUE THREAD

**Issue by faisalkhan1987** [angular/angular.js#15950]
**I'm submitting a bug report

**Current behavior:**
TypeError: object is not a function - when using alert in angularjs script

**Expected / new behavior:**
alert should work as it was before

**Minimal reproduction of the problem with instructions:**
var solutionsModule = angular.module('com.lexec.Reports', []); 
solutionsModule.controller('ReportsController', function ($scope, $http){ // , $mdDialog) {

	$scope.report = new Object();
	
	$scope.saveReport = function(){
		$http.post("../rest/reports/post", $scope.report).
            then(function (response) {
            	alert('Report has been saved succesfully');
				$scope.report = '';
            }, function (response) {
            	alert('Unexpected failure occurred');
				console.log(response);
            });
	}
	
});

For above code, alert('Report has been saved succesfully') creates and error - "TypeError: object is not a function" in the console.
**Angular version:** 1.5.8

**Browser:** [Chrome 39.0.2171.99]

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
