### ISSUE TITLE
Angular $compile causes Datepicker popup box to misbehave slightly

### ISSUE THREAD

**Issue by tarekahf** [angular/angular.js#15956]
**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

I implemented Angular UI datepicker in my project, and after a while, I noticed that when I open the popup box, and click on the month to change to another month, another popup window is displayed on top of the existing popup. See snapshot below to get more details:

![image](https://cloud.githubusercontent.com/assets/20842027/25628131/20ddc94c-2f33-11e7-9474-ea851683ebd0.png)

Originally, when I click on the month, the current popup should disappear, and another popup should show to select the new month.

However, when I click twice on the month (highlighted in yellow below), the popup will disappear, and it will work fine. But, after I select a date, then the problem will come back.

I am using the same sample code from angular ui datepicker official demo website. Find below the related website and plunker code:

http://angular-ui.github.io/bootstrap/versioned-docs/1.3.3/#/datepickerPopup http://plnkr.co/edit/lEgJ9eC9SzBWsgVhhQkq?p=preview

My code is exactly same as the code in the plunker sample above. The only difference is that I am using $compile in the directive to add required validation dynamically.

After extensive troubleshooting, and found out that `$compile()` service causes this behaviour. I did some research, and found out that the `$compile` service also causes duplicate items in drop-down list or the `select` element. I used the proposed workaround and it worked. See code below:

	$compile(child)(elmScope, function (clone) {
		angular.element(child).after(clone);     
		angular.element(child).remove();
	});

The reason why I am using `$compile` is to add dynamic validation rules from DB to the elements using this approach [here](https://stackoverflow.com/questions/40052902/angular-dynamic-required-validation-of-group-of-fields-with-field-highlight-if-i).

**Expected / new behavior:**

When you click on the calendar to open the popup box, then click on the month picker, then the calendar popup must disappear, and the month picker box should be visible. When using $compile, both the month picker box and the calendar picker box are stacked on top of each other.

**Minimal reproduction of the problem with instructions:**

Use the demo from the plunker sample above, and use $compile to add required validation during run-time.

**Angular version:** 1.6.4

**Browser:** [all ]

**Anything else:**

**Comment by tarekahf** [comment]
Check the code in the plunker sample above which will reproduce the problem.

**Comment by gkalpak** [comment]
This happens because you are compiling the same piece of code twice (which is not supported).
This is explained in detail in [the docs][1], along with instructions on [how to avoid it][2].

##
BTW, this is a general support question. You can use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question


[1]: https://docs.angularjs.org/guide/compiler#double-compilation-and-how-to-avoid-it
[2]: http://plnkr.co/edit/EnKJtW3jfSXs8jIfkXFH?p=preview

**Comment by tarekahf** [comment]
Thank you for the explanation. I think my case is slightly different. The directive I am using `check-if-required` is applied to a parent element. The directive link function will loop over all child elements, and adds the `ng-required` attribute accordingly for each child element if required. After adding the validation attribute, it will compile.

Now, I used 'terminal=true' and it broke my application. This stopped all code under `ng-init' in the inner elements from executing.

In my original code, there is no double compilation. Please check the code I am referring to here under `checkIfRequired` directive:

http://stackoverflow.com/a/41246317/4180447

The loop will compile each child element after adding the needed validation attribute. The compile is not compiling the element which has the directive.

I hope this clarifies this issue, I still believe there is some issue with `$compile`.

Appreciate your help.

BTW, I already reported this on stackoverflow [here](http://stackoverflow.com/questions/40052902/angular-dynamic-required-validation-of-group-of-fields-with-field-highlight-if-i).

Tarek

**Comment by gkalpak** [comment]
I have looked at the code in your plnkr, where you are compiling the element twice (it is compiled once by AngularJS automatically and then you re-compile it -> double compilation).

If you want a parent directive to apply attributes on the children, this can only happen before they are compiled by AngularJS (e.g. in the parent's `compile` function).

##
Of course, each usecase is different and we can't provide a one-size-fits-all solution. If you still think there is an issue with `$compile`, please create a **minimal** reproduction of the issue along with the steps to reproduce the problem.

**Comment by tarekahf** [comment]
I think I understand what you mean now. I will modify the plunker sample to show case the problem. Please bear with me.

I think the solution is to add the attributes (such as "ng-required") before automatic compiling, and then let only the automatic compilation run. In the meantime if you can point me to an example, it would be great!

**Comment by gkalpak** [comment]
There are several cases depending one whether your directives use `template` or `templateUrl`, or what info you need in order to decide if the attribute should be added or not. Just create a minimal example of what you are trying to do (even if the example throws an error).

**Comment by tarekahf** [comment]
Finally, I was able to prepare the minimum plunker sample to reproduce the issue up to 95%.

Here is the updated plunker:

http://plnkr.co/edit/lEgJ9eC9SzBWsgVhhQkq?p=preview

See my feedback below:

- If "terminal: true" is enabled in the directive `check-if-required`, then the code will break. Same will happen in my project.

- In my project, if I enable this code part, things work fine:
```
$compile(child)(elmScope, function (clone) {
  angular.element(child).after(clone);
  angular.element(child).remove();
});
```
However, in the plunker sample above, I will get funny stacking effect with datepicker popup box. Check it out.

- I will get different results if I use (or don't use) `$timeout()`, with `scope` or `elmScope`. For example, the initialized value of 'dt2' will be lost if I use `scope` with `$timeout()` and if I use `elmScope` it works fine, but I get the stacking effect of the datepicker popup box.

- After several tests, I realized that the stacking effect will happen if I use `elmScope`. If I use the scope of the directive `scope` then things work fine. I remember I had to use `elmScope` to solve a problem happened where the scope variable if an inner directive directive with an isolated scope. I am concerned that this problem will come back if I use `scope` instead of `elmScope`.

- It seems to me that `elmScope` is safer to use, since I can see that all required scope variables under `elmScope` are defined. However, the initialized scope variables under `scope` are not present during debug which I cannot understand exactly why is that. To me, both should be the same.

Appreciate your help.

Tarek

**Comment by gkalpak** [comment]
This is an [updated version][1] using `terminal: true` and manualy compilation of children. I don't see any stacking effect. I am not sure what you mean by _"the initialized value is lost after compile"_. Does this work for you? If not, what exactly is the expected and what the actual behavior?

[1]: http://plnkr.co/edit/vGlaJNqKHp3kC548ETqg?p=preview

**Comment by tarekahf** [comment]
Thank you.

I think we are getting there. Following is my feedback:

1. I update the plunker sample you provided to fix few bugs and to follow the recommended implementation to avoid the double compilation issue: [check the update plunker here](http://plnkr.co/edit/Jg7ZROBDntbqhCPJ2Gx8?p=preview),

2. When using `terminal: true`, the stacking effect is gone, but all interpolations are not working. See the highlighted parts in the snapshot below.

![image](https://cloud.githubusercontent.com/assets/20842027/25959384/74506ef8-3641-11e7-961e-fa1eceac5b6b.png)

3. The initialized value I am referring to is that value assigned to the `dt2` scope variable in the `$scope.today()` function. But in the recent plunker sample, it seems that this is not happening; looks good.

4. If you comment out `terminal: true` then the stacking effect is back, and all interpolations are working fine. See the highlighted parts in the snapshot below:

![image](https://cloud.githubusercontent.com/assets/20842027/25959654/572f5cac-3642-11e7-8b29-e656938c70d0.png)

The expected behaviour is that in item 2 above but of course, the interpolations should work. I think the problem now due to using `terminal: true` which seems it will disable parts of Angular features since it used at the level of a parent element.

Tarek

**Comment by gkalpak** [comment]
You are right. I messed up in my previous plnkr. How about [this one][1]?

[1]: http://plnkr.co/edit/C5ATu71fg59sykU5PT0v?p=preview

**Comment by tarekahf** [comment]
Thank you so much! It worked.

I applied to changes to my project, and I used the linking function, as it was much easier to implement.

I face a very small problem. There is initialization logic that loads data from the Database using Ajax call, and then initializes the fields using a loop based on element ID. I have used promises extensively to ensure the following sequence is applied:

1. Load options for SELECT elements
2. Load validation rules from Database 
3. Load values from Database and initialize the elements using jQuery.

I know we should have done it using AngularJS method, but for know, this is the situation.

The problem is that, as it appears to me, the compile logic is the directive `check-if-required` is delaying the availability of some fields in the `document` and hence the initialization logic does not find them, and they are skipped.

So, I used `$timeout()` to delay the execution of the initialization logic for some time, and it worked like a charm.

Question: To be 100% sure that the initialization is run after all `$compile()` statements are run, I have to delay using better method than using `$timeout()` since that latter depends on luck. How I can do that?

How I can wait until all `$compile()` statements under all `check-if-required` directive are executed, then execute the initialization logic?

Appreciate your feedback at least to give me some pointers.

Tarek

**Comment by gkalpak** [comment]
There is no way to know when AngularJS directives in your childnodes are done compiling/linking. It depends on whether the directives use `template` or `templateUrl` (which makes them asynchronous).

I don't think there is a good way to achieve what you want using this non-AngularJS-way approach.

**Comment by tarekahf** [comment]
I think I know how to solve this problem. After compile is done, use a loop to initialize the `ng-model` based on the element ID. At this time, we have access to the JSON which has the element values, and also we have the compiled parent element with the related scope variables. Using the element ID we can get the  `ng-model`, and also we can get the scope.

Thank you so much for your help.

Tarek

**Comment by tarekahf** [comment]
I have one more question please if you can help me. How I can re-execute the directive `check-if-required` at some point after page loading is completed, and without reloading the page. This might be required because the list of required fields have changed, so we want to re-apply the directive logic again.

I have already added this question to stackoverflow [here](https://stackoverflow.com/questions/44462623/how-to-execute-angularjs-directive-again-after-page-loading-is-done).

Thank you.
Tarek
