### ISSUE TITLE
Taking more time to load 3.5 Lakh data

### ISSUE THREAD

**Issue by atul407** [angular/angular.js#15965]
I am new to Angular Js and my issue is showing data (which is in count of 3.5 Lakh to 4 Lakh).

I am using MySql and SQL Server database and I have more that 3.5 Lakh data in it and I want that data to be shown in the tabular format using pagination. Everything is fine but its taking much much time to load.

Can you suggest any way so that I can bring data only I click the pagination, something like LIMIT and OFFSET.

Please help me regarding this. I really want to crack this asap.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
