### ISSUE TITLE
Null array items should be omit by $httpParamSerializer

### ISSUE THREAD

**Issue by ArtemAvramenko** [angular/angular.js#15969]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Default `$HttpParamSerializerProvider` serialize null array items as strings.
The object
```
{
  items: ['foo', 'bar', null]
}
```
is serialized to
```
?items=foo&items=bar&items=null
```

**Expected / new behavior:**
null values should be omit, because any back-end can not differentiate `'null'` from `null`:
```
?items=foo&items=bar&items=
```

**Minimal reproduction of the problem with instructions:**
Demo - https://plnkr.co/edit/EqsZM2dmKZBcVVgWyx0A?p=preview

**Angular version:** 1.6.4

**Browser:** all

**Comment by lgalfaso** [comment]
Putting a side the fact that this is a breaking change and that the param serializer is configurable. If the example you posted is serialized as `items=foo&items=bar&items=`, how would you differentiate if the value is `null` from an empty string?

**Comment by ArtemAvramenko** [comment]
> how would you differentiate if the value is null from an empty string?

Empty string often is the same as `null` semantically, but `null` never the same as `'null'`.

**Comment by lgalfaso** [comment]
The fact that `$httpParamSerializerJQLike` works differently than `$.param` is a real bug and should be addressed. Changing the behavior of `$httpParamSerializer` is a breaking change that I think it is best to avoid.

**Comment by gkalpak** [comment]
I agree that given the breaking change, the ambiguity of `items=` (null or empty string) and the configurability of `paramSerializer` it is not worth "fixing" this for the default serializer.
👍 for fixing `$httpParamSerializerJQLike`.
