### ISSUE TITLE
change location when state change with id?

### ISSUE THREAD

**Issue by rahi-rajeev** [angular/angular.js#15972]
hello team,
i  want to implement like
```
$stateProvider.state('main', {
		url: '',
		sticky: true,
		views: { main: { 
		  templateUrl: listingPrd 
		} }
	});
```
this is my maim page link 'http://192.168.1.200/en/user/home'
after 
```
$stateProvider.state('item', {
		url: '/product/:id',
		sticky: true,
		resolve: {
			resolvedData: ($stateParams)=> {
				return $stateParams.id
			},
		},
		proxy: {  // Custom config processed in $stateChangeStart
			external: 'item.full',
			internal: 'item.uibModal'
		}
	});
```
ulr become http://192.168.1.200/en/user/home#/product/727
but i want to replace like http://192.168.1.200/en/product/727
so please help me 
thanks in advance

**Comment by frederikprijck** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the [listed Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by Narretz** [comment]
$stateProvider also is part of uiRouter, not part of AngularJS core ;)
