### ISSUE TITLE
BaseURL & image href on the same root

### ISSUE THREAD

**Issue by flavioreis13** [angular/angular.js#15996]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**

I'm having troubles on setting a baseURL in order to exclude the '#' from the top link.

My website is, lets say: http://test.com/public
On the index.html i have `<base href="/public/">` and it works perfectly, thumbs up for that 👍.

The problem is when i have this `<a>` that points to a image in the same root:

`<a href="http://test.com/public/media/image.png">Go To Image</a>`

Somehow the Angular redirects me to my:
```
$routeProvider.otherwise({
        redirectTo: '/404'
});
```

**Expected / new behavior:**

The expected behaviour would be to open the image and not the 404 route.

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.5.8

**Browser:** [all]

**Anything else:**

Angular Route-Segment 1.5.1

**Comment by gkalpak** [comment]
There is agood chance it is actually the server rewriting to `index.html` and then you end up with an unknown path (`media/image.png`), hence the `redirectoTo: 404`. Make sure you have set up the server-side rules correctly.

That said, this is a general support question, so please use one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by flavior121** [comment]
The problem has on the `.htaccess` file.

Solution:
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteCond %{REQUEST_URI}  !(media) [NC]
RewriteRule ^ index.html [L]
```
