### ISSUE TITLE
component controller not binding to ng-transclude template scope 

### ISSUE THREAD

**Issue by omkadiri** [angular/angular.js#15998]
Am trying to transclude a template into component for customization purpose but the binding to the template is not working

simple 
**component controller and transclude template**

```
let simpleComponent = {
    template: './simple.html',
    bindings: {
        title: '<'
    },
    transclude: true,
    controller: simpleController
};

class simpleController {
   constructor()

   getNext(){
     return true;
   }
}

angular.module('commonModule.pdfViewer', [])
    .controller('simpleController', simpleController)
    .component('simpleComponent', simpleComponent);

   <simple-component>
        <div ng-click="$ctrl.getNext()">{{$ctrl.title}}</div>
   </simple-component>
```

**Am i missing something here? the above will work for a directive if the function is $scope.getNext()**

simple.html
```

<div>
   <div ng-transclude></div>
</div>
```

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
