### ISSUE TITLE
Using ng-pattern in directive to validate form

### ISSUE THREAD

**Issue by Tommy9021** [angular/angular.js#15993]
I'm using angularjs to build a directive to validate input with `ng-messages`.

I have a plunker to test directive.

https://plnkr.co/edit/ZZ6yldgycDbQjXPBszjk?p=preview

It works fine with `required` and `type = "email"`, but not working well for `ng-pattern`.

When submit, form is invalid but all element is valid.

Anyone can resolve this problem. Thanks very much.

**Comment by frederikprijck** [comment]
Hi @Tommy9021 ,

I'm not sure what you mean with:
> It works fine with required and type = "email", but not working well for ng-pattern.

I've added an invalid character to the first input (based on the pattern regex) and it's showing as invalid:
![image](https://cloud.githubusercontent.com/assets/2146903/26191082/b584e726-3bac-11e7-9f59-bee75fa763c4.png)

I added a seperate plunkr which doesn't wrap the `ng-pattern` in a custom directive. If you realy think there's an issue with the `ng-pattern` directive I think it's better to continue reproducing it in this plunkr:

https://plnkr.co/edit/ofyZQ9POlPt29rCUBN6T?p=preview

Also, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the [listed Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by Tommy9021** [comment]
![image](https://cloud.githubusercontent.com/assets/26786349/26191881/d6a91828-3bd9-11e7-892f-8d67819362d3.png)

 I want use ng-pattern in directive
You can see form valid= false althought all input are valid=true. I want to know why?

**Comment by frederikprijck** [comment]
As far as I can tell, the reason why your form is invalid is because your `div` is invalid, hence making the parent form invalid aswell.

![image](https://cloud.githubusercontent.com/assets/2146903/26192188/fb989f60-3bb0-11e7-831d-fb578c52250d.png)

Why the div is being invalid (or why it's even being part of validation) is probably related to your custom directive. Any change you could reproduce this without your custom directive ?

**Comment by Tommy9021** [comment]
Thanks @frederikprijck , I'll check my directive.

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

(In general it's not advised to put ngModel on an element that doesn't work like an input)
