### ISSUE TITLE
Form model doesn't update on autocomplete

### ISSUE THREAD

**Issue by yaroslavert** [angular/angular.js#15994]

**Comment by frederikprijck** [comment]
@yaroslavert This is a bit of a vague (or no) description. Any chance you caould provide a plunkr demonstrating the potential bug ?

**Comment by yaroslavert** [comment]
![image](https://cloud.githubusercontent.com/assets/19486652/26193196/29cd0932-3bbd-11e7-9c19-37e955c724e9.png)

**Comment by yaroslavert** [comment]
(autofill) when page loads

**Comment by frederikprijck** [comment]
Yep, that's already being logged/tracked/discussed here: https://github.com/angular/angular.js/issues/1460

**Comment by yaroslavert** [comment]
why do not you fix a bug
