### ISSUE TITLE
Query string params for php?

### ISSUE THREAD

**Issue by rahi-rajeev** [angular/angular.js#16007]

**Comment by frederikprijck** [comment]
UI-Router is not part of the AngularJS core. I guess you'll be willing to ask the angular-ui team:
https://github.com/angular-ui/ui-router

That being said, I don't see why AngularJS' route configuration has anything to do with whether or not PHP can parse the url's parameters.

Also, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the [listed Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by rahi-rajeev** [comment]
sorry by mistake i wrote comment in angular js repo

**Comment by frederikprijck** [comment]
Instead of removing your comment, could you please close the issue if there's no problem anymore ?

**Comment by Narretz** [comment]
I'm doing the honors
