### ISSUE TITLE
Snapshot angular.min.js doesn't contain $animateProvider.customFilter

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#16002]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

ngRepeat example on snapshot docs does not work: https://code.angularjs.org/snapshot/docs/api/ng/directive/ngRepeat

It throws  `TypeError: $animateProvider.customFilter is not a function`

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

https://code.angularjs.org/snapshot/docs/api/ng/directive/ngRepeat

**Angular version:** snapshot

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

Not sure how this can happen. The customFilter is defined in the ng module animateProvider, and the angular-animate service tries to access it. It's present in the angular.js file, but not in the min file. Maybe it's not marked as exported and gets discarded by the closure compilation?

**Comment by gkalpak** [comment]
Everything semems to work fine for me 😕 Could it be a temporary issue?

**Comment by Narretz** [comment]
Yep, looks like angular.min.js was cached by my browser on an old version :/

**Comment by skortchmark9** [comment]
I'm having this issue as well now that 1.6.5 has been released. Downgrading to 1.6.4 fixes it for me.

**Comment by gkalpak** [comment]
@skortchmark9, this sounds like a different issue (e.g. `customFilter` is not even available in 1.6.4).
Please open a new issue with all the necessary details.

**Comment by skortchmark9** [comment]
I'm pretty sure that it was just because our internal package mirror had picked up the new angular animate but not the new angular. This issue came up when I had angular-animate@1.6.5 but angular@1.6.4.

**Comment by mattiLeBlanc** [comment]
@skortchmark9  Thanks mate. I had an inconsistency in my angular version (forgot the ^ :)
