### ISSUE TITLE
Old values in $watchGroup's callback is not correct.

### ISSUE THREAD

**Issue by Tobyee** [angular/angular.js#16004]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Old values in $watchGroup's parameters is not correct.

**Expected / new behavior:**

Correct values.

**Minimal reproduction of the problem with instructions:**

````html
<input id="input1" ng-model="t1" ng-change="t2=t1">
<input id="input2" ng-model="t2">
<script>
var app = angular.module('plunker', []);
app.controller('MainCtrl', function($scope) {
  $scope.$watchGroup(['t1', 't2'], function(nvals, ovals) {
    console.log('nvals:' + angular.toJson(nvals) + ', ovals:' + angular.toJson(ovals))
  });
});
</script>
````
Steps:
1. initial state
    log: _[null,null], ovals:[null,null]_
2. type "a" in input1
    log: _nvals:["a","a"], ovals:[null,null]_
3. type "b" in input2
    log: _nvals:["a","b"], ovals:[**null**,"a"]_ (??? ovals expect to be ["**a**","a"] but not.)

plunker:
https://plnkr.co/edit/slDfDzwvGT6jrZtn42C9?p=preview

**Angular version:** 1.6.4

**Browser:** all

**Anything else:**

**Comment by Narretz** [comment]
I think this works as egpected. Watch group old / new values are tracked individually, not as a collection.  The first value didn't change when you changed the second value, it only changed from null to a, so it's correct that when the second value changed to b, the old value of the first is still null.

**Comment by Tobyee** [comment]
I found some similar issues：
#8671
#12452

So it's by design behavior...
Even if the design is reasonable technically, it is weird result that confuse with the behavior of $watch.

I also found a PR #12643 that try to clarify the behavior, should it be merge?

**Comment by Narretz** [comment]
@Tobyee thanks for unearthing the issues and PR. I will create a new PR, as I think the one you linked doesn't improve the explanation sufficiently.

**Comment by gkalpak** [comment]
Closing since this has been changed in master (1.7+) with 15854 and there is a PR for documenting it for 1.6.x (#16005).

**Comment by gkalpak** [comment]
See also #16024 for a discussion on the different behaviors.
