### ISSUE TITLE
how i can upload image and video to server i try header multipart/form-data  any help please 

### ISSUE THREAD

**Issue by MohamedShawky** [angular/angular.js#16000]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by MohamedShawky** [comment]
@henrik @expilo 
any one help me please 
?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
