### ISSUE TITLE
Load a controlle after main controller loaded completly

### ISSUE THREAD

**Issue by Thinkdiff** [angular/angular.js#16012]
I have an angular application. In all of my HTML pages, I have 2 controller: "mainCtrl" and "thatPageCtrl"

I need to define queue for controllers. Actually, I want to mainCtrl lunch at the first and when mainCtrl launched and done completely, Then thatPageCtrl start to lunch.
I`m authenticating users in all the route in mainCtrl, and I want to lunch thatPageCtrl if authentication is true. And I`m binding some data to all pages in mainCtrl and I need to lunch thatPageCtrl after these data bind completely from mainCtrl.

<div ng-controller="mainCtrl">
       <div ng-controller="thatPageCtrl">
       </div>
</div>

How can I do that?

**Comment by gkalpak** [comment]
You are misusing controllers. The logic you describe should be in a service (which could potentially be used by the route to resolve some value or redirecting before instantiating the controller).

In any case, this is a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
