### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by notsonotso** [angular/angular.js#16019]
I understand angular4 is the new thing and that angular.js is the old thing. But I like the old thing better than the new thing.

So will angular.js be maintained and improved in the future, or am I forced to downgrade to angular4?

**Comment by Narretz** [comment]
AngularJS is still maintained but is considered stable and will not receive substantial feature improvements. More small improvements and bug fixes and helpful tweaks for upgrading to Angular. For new projects you should definitely use Angular.

**Comment by frederikprijck** [comment]
> or am I forced to downgrade to angular4

I understand shifting to Angular might be a bit scary in the start, but eventually I guess you'll start to apreaciate the things that make Angular differ from (and superior to) AngularJS.

**Comment by rognoni** [comment]
@notsonotso Or I am thinking to switch to [Vue.js](https://github.com/vuejs/vue)

**Comment by rockieroshan** [comment]
Hello ma'am,
I'm new to GitHub.
I just joined.

Please tell me how do I learn to code from GitHub?

Thanks

**Comment by Narretz** [comment]
In other words, yes AngularJS is still maintained.

**Comment by JonathanDn** [comment]
@Narretz Just for general knowledge, since when did AngularJS core team stopped delivering new features / core changes? (Like what is the official date)

**Comment by frederikprijck** [comment]
There is a blog post about the final release and LTS : “Stable AngularJS and Long Term Support” by Pete Bacon Darwin https://link.medium.com/3B8RvxT2MW
