### ISSUE TITLE
REGEX ng-pattern directive template

### ISSUE THREAD

**Issue by JennyWalters** [angular/angular.js#16028]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

I think I found a bug with ng-pattern that is passed with a parameter to a directive for use in a template.

**Minimal reproduction of the problem with instructions:**
[Plunker example](http://plnkr.co/edit/DWsRYxFV4b7JiWFxNa18?p=preview)

I am creating textboxes in a template that is called from html to a directive.
HTML <text-Box ... </text-Box> which calls  
--->Directive app.directive('textBox',  which calls
------>Template

**Current behavior:**
I have multiple textboxes in a form (the example only has two example textboxes).

A parameter is passed in index.html (myregxpattern='[a-z A-Z0-9]*$' ) 
to a directive apps.js (myregxpattern: '@myregxpattern',) 
that is used in the template textboxTemplate.html (ng-pattern="/^[a-z\d\-_\s]+$/i").

In the template, ng-pattern="/^[a-z\d\-_\s]+$/i" has to be **HARDCODED because myregxpattern does NOT work with a directive parameter**.

Out of desperation I tried:
    ng-pattern="/^[a-z\d\-_\s]+$/i" HARDCODE works perfectly
    ng-pattern="{{myregxpattern}}"  doesn't work
    ng-pattern="myregxpattern"      doesn't work
    ng-pattern=myregxpattern        doesn't work

I have tried a many other ways that also do not work (i.e. ng-int, new RegExp(/[a-z]+/i) ) out of desperation.

Althouh I a fairly new to AngularJS, perhaps this appears to me to be a bug.

**Expected / new behavior:**
I would expect that a parameter of REGEX passed to a directive and used in a template would work in the template (instead of having to hardcode the REGEX in the template).

**Angular version:** 1.5.11
I tried a previous version (1.4.12) and it had the same affect.

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 58.0.3029.110 (64-bit) most recent
Firefox 53.0.3 (32-bit) most recent 
IE 11.0.9600.18665 most recent

**Anything else:**

No

**Comment by Narretz** [comment]
Works for me:
http://plnkr.co/edit/pHuIoNhBrNB14zAynQd3?p=preview
I put in Jen/ and the pattern error is set.

**Comment by JennyWalters** [comment]
I accidentally hit the thumb-down.  Is there anyway I can delete the thumb-down?  Surprisingly it then allowed me to thumb-up.  SORRY

I looked at the difference in Regex.  It seems my Regex was wrong in how AngularJS accepts it.  I used /^[a-z\d\-_\s]+$/i  as a parameter and it never worked correctly.

So a note of caution.  What works hardcoded for ng-pattern does not necessarily work when passed as a parameter to a directive.

THANKS Narretz.

**Comment by Narretz** [comment]
@JennyWalters you must be looking at the wrong plnkr. I just opened my link, and there's clearly no hard-coding going. Here's the plnkr again, now I've put the initial regex in to the controller, too: http://plnkr.co/edit/pHuIoNhBrNB14zAynQd3?p=preview

I've also added an example for using a regex object instead of a string - this must be bound via = or < (because @ converts to string). You can see this by changing "myregxpattern" in the template to "regexObj"

Two  notes about github:
1. You can revert your thumbs down by clicking on it
2. When you edit your message, I won't be notified - so it's only by chance that I saw that you are not happy with my answer.

**Comment by JennyWalters** [comment]
Literally, see this screenshot  http://imgur.com/RpqKWsA  .  I must have looked at your plunker after you forked but before you saved your edits.  I happened to have never closed the screen.  I have to pickup a neighbor's child so will look at this tonight or tomorrow.  

Sorry about the confusion on the plunker.

**Comment by JennyWalters** [comment]
Narretz, Just to let you know. It is going to take me the weekend to play with your solution and come-up with a plan of action.  What you do in an hour takes me hours to do.

**Comment by JennyWalters** [comment]
I just finished but do not have the strength to message.  Tomorrow.  But thanks and I perhaps know what my problem was.  I can't really do the AngularJS code, I can't even do my own code yet.  But perhaps I can help out in documentation.
