### ISSUE TITLE
Error of Installing AngularJS on NPM

### ISSUE THREAD

**Issue by yyxyyxyyx** [angular/angular.js#16033]
Can somebody help me?
When I want to install "npm install -g @angular/cli", return:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@^4.3.0 (node_modules\@angular\cli\node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of input at 1:18763
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ss","version":"0.9.5","dependencies":{"chalk":"~0.5.1","mkdirp":"~0.5
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:                                                                      ^

npm ERR! Unexpected end of input at 1:19119
npm ERR! bf4ead75a","tarball":"https://registry.npmjs.org/stylus/-/stylus-0.13
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\harry\AppData\Roaming\npm-cache\_logs\2017-06-05T13_11_25_126Z-debug.log

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

It also looks like the error is with stylus. not angular.js. Probably a temporary npm problem.
