### ISSUE TITLE
`isAutoBootstrapAllowed` fails in Edge extensions due to lack of anchor element `origin` support

### ISSUE THREAD

**Issue by kspearrin** [angular/angular.js#16030]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Bootstrapping AngularJS in an Edge extension fails with:

> Angular: disabling automatic bootstrap. <script> protocol indicates an extension, document.location.href does not match.

**Expected / new behavior:**

Allow AngularJS to bootstrap in Edge extensions.

**Minimal reproduction of the problem with instructions:**

This is because the checks on [these lines](https://github.com/angular/angular.js/blob/837acd14e005c79d8e79f59a0075075f125da50c/src/Angular.js#L1517-L1520):

```
var link = document.createElement('a');
link.href = src.value;

if (document.location.origin === link.origin) {
```

In Edge, the `origin` property on anchor elements is `undefined`. This can be seen with the following fiddle in Edge: https://jsfiddle.net/37y8bhky/3/

```
origin is:
undefined
```

Same fiddle in Firefox and Chrome:

```
origin is:
"https://google.com"
```

**Angular version:** 1.6.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Edge 38.14393.1066.0

**Anything else:**

Suggested fix would be to use the other properties of the anchor element that are supported on all platforms to form [what `origin` is suppose to give you](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/origin).

Example:
```
var link = document.createElement('a');
link.href = src.value;

if (document.location.protocol === link.protocol &&
  document.location.host === link.host &&
  document.location.port === link.port) {
```

**Comment by kspearrin** [comment]
Issue also opened with the Edge team here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12236493/

**Comment by Narretz** [comment]
This works for me in Edge 17
