### ISSUE TITLE
i am going to start new project and i want to use angularJS not angular but. i wonder will it develop in future?

### ISSUE THREAD

**Issue by mahmut-gundogdu** [angular/angular.js#16047]
hi sorry for my english. i am working on it too. so i am going to start new project and i want to use angularJS not angular but i wonder will it develop in future? what is the roadmap
i don't want to use ES6, Babel, Webpack, or another seramonic stuff. i am .net developer. i use mvc 5 (not core). The project is multipage except just a few pages. it needs complex ui elements.
i tryed vue. same problem. es6,webpack .vue etc.
The project will maintain a least four or five year. i don't want to depraceted framework in project. i know to world of frontend  progress every day. a new frameork born every day. So i confusued a little. i learned angularjs 1.4 from Dan Wahlin on pluralSight. So Sould i use angular js on my project? i worry about my question i don't want to be root.

**Comment by frederikprijck** [comment]
This looks more like a general support question, this github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

Sidenote: I'm a .NET developer aswell, feel free to ping me at Gitter.
I don't see any problem with using ES6 and Webpack etc for new projects. Even tho I understand it all looks abit scary at first, starting a new project  with either AngularJS or Angular will both benefit from using ES6 + Webpack (or comparable).

**Comment by mahmut-gundogdu** [comment]
Thank you. and sorry for that. i am going to write on gitter.
