### ISSUE TITLE
AngularJs CLI fails with current version of NPM

### ISSUE THREAD

**Issue by ricardo-1937** [angular/angular.js#16044]
After globally installing the Angular CLI with the latest version of npm, the ng command does not work.
My machine is a Dell PC running Windows 10 with VS 2017 installed. I used the 64 bit Windows Installer for npm.
I did get errors and warnings when installing the global CLI.
When I run ng, this is what I get:
C:\>ng
C:\Users\Caribbean1\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng:7
const CliConfig = require('../models/config').CliConfig;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

C:\>
My email :
ricardo_1937@hotmail.com   

**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by Narretz** [comment]
The cli is part of Angular starting with version 2. Please report issues here https://github.com/angular/cli

**Comment by ricardo-1937** [comment]
Hi Martin,


Going to this link I get a "Page Not Found".


Ricardo Sanchez
(561) 372-9299


________________________________

**Comment by Narretz** [comment]
Sorry, tge correct link is https://github.com/angular/angular-cli

ricardo-1937 <notifications@github.com> schrieb am Sa., 10. Juni 2017 12:49:
