### ISSUE TITLE
ng-class prevent assignment operator

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular.js#16049]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
when `ng-class` has an assignment operator. it assigns the value to the variable.
Is it mandatory for `ng-class` to have this behaviour?

as mentioned [here](https://docs.angularjs.org/api/ng/directive/ngClass).  `The ngClass directive allows you to dynamically set CSS classes on an HTML element by databinding an expression that represents all classes to be added.`

It should set css class not assign variables or something.
**Expected / new behavior:**
when `ng-class` has an assignment operator. it can throw some error.

**Minimal reproduction of the problem with instructions:**
plunker => https://plnkr.co/edit/xhVw7XyIRVSIBhBJ42di?p=preview

**Angular version:** 1.6.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by frederikprijck** [comment]
@s-light Using `{active: data='var'}` wouldn't realy work as you expect in plain JavaScript either.
I don't think ng-class is to be used like that. 

Personally I think it's okay (or atleast not problematic) for the `data` value to be updated when using `{active: data='var'}`, but you just should not be using this.

**Comment by Sibiraj-S** [comment]
@frederikprijck. Thanks for the plunker. I have already been using `ng-class` for a long time. what I was trying to say is. 

Since `ng-class` directive is meant for `dynamically assigning class`. why is it performing things that it is not meant for?

**Comment by Narretz** [comment]
Because the property values are regular AngularJS expressions. You can basically do whatever you want in these expressions. But the overall use of ngClass is to dynamically assign classes. I really don't see any need for action here.
