### ISSUE TITLE
Supported Status for Versions

### ISSUE THREAD

**Issue by cjsfj** [angular/angular.js#16058]
From: https://github.com/angular/angularjs.org/issues/220

Greetings -

It would be great if angularjs.org could maintain a simple page that indicates AngularJS versions and their EOL/Security Patch/LTS status.

For example, PHP has a similar page here: http://php.net/supported-versions.php

It clearly outlines the bug fix / security patch strategy for each supported version of PHP.

For angular, there are blog entries that elude to support (security fixes for 1.2.x in the 1.6.0 announcement post, for example). But even if there was just a list, not necessarily with timelines, of the most recent version of each significant release of Angular, and the current status of support for that release, it would make it simple for a developer to choose a supported version...

Or in our case, justify staying on a 1.2.x version because security patches are still maintained.

Thanks!

C

**Comment by ozsay** [comment]
any word on this issue / what is the current versions status?

**Comment by petebacondarwin** [comment]
I will work on this during January.

**Comment by Narretz** [comment]
Here's another issue where this is requested in readme.md and angularjs.org, which sounds reasonable: https://github.com/angular/angular.js/issues/16458
