### ISSUE TITLE
1.1.28  video  loop  not work

### ISSUE THREAD

**Issue by yangyili** [angular/angular.js#16054]
I  use html5  video and set loop attribute, but it doesn't work ,the video  plays once and stops .
Have somebody encounter this issue?
thie video duration is about two minutes
video code as follow: 
\<video autoplay loop src="http://127.0.0.1:8080/ad/video1.mp4" type="video/mp4"\>\<\/video\>

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

There is also no AngularJS in your example at all, this sounds really like a general HTML question.

**Comment by yangyili** [comment]
thanks so much.
But I tried  in pure  html5  it dosen't exist this problem.  Just when I use in  angular   the issue occured
