### ISSUE TITLE
angular method '$http.then' always return status with '-1'

### ISSUE THREAD

**Issue by TheHtmler** [angular/angular.js#16051]
As it said in title, the status codes always returned by the request fail are -1, when I tried in API backend, it returned 404,405,500 and so on, it confused me a few days. I tried interceptor,but doesn't work, it still return '-1'.

**Comment by frederikprijck** [comment]
Sorry, but this sounds like a general support question. StackOverflow (or one of the [general support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question)) are better suited for these types of questions.

If you do think this is an issue with AngularJS, please provide a plunkr reproducing the problem.

**Comment by Narretz** [comment]
-1 is returned by http when the xhr event handlers for onerror, onabort or ontimeout are triggered. This is not ideal, as the app cannot distinguish between these cases. However, if the server returns a clean 4xx, the app should definitely be able to read it. If you never get a real status, you usually have a CORS problem, i.e. the server returns before it can set the correct status, and this results in a -1. The browser console will show more.
However, it's very difficult to say what exactly is going on without a repro, and this repo is not the place to debug this stuff :<
