### ISSUE TITLE
input type="time" is not working for firefox and IE

### ISSUE THREAD

**Issue by coded9** [angular/angular.js#16052]
**Current behavior:**
input type="time" is not working for firefox and IE

Any workarounds ?

**Comment by frederikprijck** [comment]
`input type="time"` isn't supported by IE and firefox (http://caniuse.com/#search=time), there's not much that can be done about that from AngularJS' side.</sub>

<sub>You probably want to have a polyfill for browsers that don't support any feature that you're using (not only the time input).

This looks more like a general support question, please keep in mind that this github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) in the future. Thanks!

**Comment by Narretz** [comment]
The docs note that not all browsers support input time, and what kind of input you can use instead. Personally, I think it's better to not use input time as long as not all browsers support it.
