### ISSUE TITLE
How to Refresh the Angular Js Template

### ISSUE THREAD

**Issue by staffsri** [angular/angular.js#16069]
hai Sir,
please Rectify this problem , i am explained in below link
https://youtu.be/SHMkrC7GBeo
example code : 
 $scope.templates =
         [ { name: 'testquestionsGet.php?id='+$scope.qno+'&exid='+exam+'&pprid='+paper, url: 'testquestionsGet.php?id='+$scope.qno+'&exid='+exam+'&pprid='+paper}
         ];
this code will written because  **testquestionsGet.php** page is included in another page how to reload this  **testquestionsGet.php**  page or if any solution please explain it.
**Thank You**,

**Comment by frederikprijck** [comment]
Hi @staffsri, 

this looks like a general support question, please keep in mind that this github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) in the future. Thanks!

**Comment by Narretz** [comment]
@frederikprijck is right, this sounds like a support question
