### ISSUE TITLE
How Do I call the function with ng-model in AngularJS?

### ISSUE THREAD

**Issue by kapilSoni101** [angular/angular.js#16074]
_I have try this code_:-
<div class="checkbox">
     <input type="checkbox" ng-model="_computeAllowUser(album.productKey, productList.keyId)"   
       ng-change=addProductInAlbum($event, product.keId)">
</div> 

Controller Code:-
$scope._computeAllowUser = function(albumKey, productKeyId) {
      return(albumKey == productKeyId) ? true: false;
}

Here,_computeAllowUser  function is called after loading but i got error non-assignabel error in the ng-model ,so how to resolve this error and how to call function with ng-model.
With the help of this function if the keyId will be return true, i have to select all the checkbox willl be checked.how to implement this?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
