### ISSUE TITLE
When a ControlValueAccessor binds to another ControlValueAccessor the initial value gets wiped

### ISSUE THREAD

**Issue by willseitz** [angular/angular.js#16077]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

When I have  two components implementing ControlValueAccessor and one of them binds it's value to the other the inner one gets undefined instead of the right value in the writeValue method. This value is then chained back up clearing the original data you were binding to. Hopefully this plunkr will be useful: 
https://plnkr.co/edit/ynlJ7fBykSGDiGdMxnd0?p=preview in demostrating the problem. In the plunkr, the problem is that the original 'green' value of thingie is wiped. After the original start up, the bindings work correctly and all the buttons function as expected.

The motivation for this pattern was that we created a custom dropdown that you could bind data to. We also had the notion of a "job dropdown" that had specific behavior. We wanted to use the job-dropdown in multiple places and bind it to data. So the job dropdown bound its value to the dropdown, revealing this bug.

**Expected / new behavior:**

I expect that my data would not be wiped out by this form of binding.

**Minimal reproduction of the problem with instructions:**

https://plnkr.co/edit/ynlJ7fBykSGDiGdMxnd0?p=preview

**Angular version:**  Checked on 4.1.1 and 4.2.5

**Browser:** Checked on Firefox and Chrome

**Anything else:**

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular 2. Please open in the Angular 2 [repository](https://github.com/angular/angular/issues). This repo is only for AngularJS.
