### ISSUE TITLE
Improve jqLiteRemoveClass performance

### ISSUE THREAD

**Issue by aresn** [angular/angular.js#16078]
I would like to propose a slight modification to jqLiteRemoveClass function to increase it's performance. 

Current implementation constantly reads the "class" value from DOM and writes it back to the DOM inside a for loop.  

Here is what I have created for our local branch of angular:

    function jqLiteRemoveClass(element, cssClasses) {
      if (cssClasses && element.setAttribute) {
        var currentClass = element.getAttribute('class');

        if (currentClass) {
          var cssClass;
          var curValue;
          curValue = currentClass = trim(currentClass);
          var classNames = cssClasses.split(' ');

          for (var i = 0, len = classNames.length; i < len; i++) {
            cssClass = trim(classNames[i]);
            currentClass = trim((' ' + currentClass + ' ')
              .replace(/[\n\t]/g, ' ')
              .replace(' ' + cssClass + ' ', ' '));
          }
          if (currentClass !== curValue) {
            element.setAttribute('class',currentClass);
          }
        }
      }
    }

Here is a link to a jsPerf that I have created that compares the two functions : 
https://jsperf.com/compare-angular-remove-class-with-improved-version/1

**Comment by Narretz** [comment]
Hi, perf improvements are definitely welcome, although I wonder if you specifically experienced perf  problems related to removeClass in your apps?
And it does make sense to open this as a PR, so it's easier to see the change in the code.
