### ISSUE TITLE
publish 1.6.5 version to google cdn 

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular.js#16083]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Angular version:** 1.6.5

publish angular v1.6.5 to google-cdn 

https://ajax.googleapis.com/ajax/libs/angularjs/1.6.5/angular.min.js isn't available yet

**Comment by gkalpak** [comment]
It is now available.
