### ISSUE TITLE
ngMessages needs viewValue but it's naming convention is complicated to connect/reach to view.

### ISSUE THREAD

**Issue by prashant-saxena** [angular/angular.js#16085]
**I'm submitting a ...**
- [ ] bug report
- [x ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
ngMessages needs viewValue but it's naming convention is complicated to connect/reach to view.

**Expected / new behavior:**
Let ngMessages reach to view value by ng-model or by id attribute

**Minimal reproduction of the problem with instructions:**
http://plnkr.co/edit/pzBPlhQu360T8GOmc8yG?p=preview

**Angular version:** 1.6.4

**Browser:** [all]

**Anything else:**
ngMessages is great feature but it could serve much better if it could handle the complex situations
as explained in plunk. As far as my understanding it works on $viewValue of model and one must
provide a clear name of the view model to connect. In plunk there are two situations where one is 
of array type and other one is follows a bit complex name on input.
The reason behind is to follow the data format. When posting the form in plunk data goes in same
format as it was fed in.
If ngMessages could reach to view value by assigning model:
`<div ng-messages-model="ip[$index].$error">`
or may be if user add an id attribute to input/select/textarea and:
`<div ng-messages-id="textInput_{{$index}}.$error">`
then it would be much better.
The whole idea is to leave the name attribute behind and let ngMesages reach to view value either by ng-model or by id attribute.

**Comment by frederikprijck** [comment]
Hi @prashant-saxena 

I'm not entirely sure what you're trying to do with the plunkr, but I changed some things in order to make it work as I expect you want:

http://plnkr.co/edit/Va16CILqfzpXB2YhInk5?p=preview

> ngMessages is great feature but it could serve much better if it could handle the complex situations
as explained in plunk.

As far as I know, the situation in the plunkr is something ngMessages can handle already.

**Comment by Narretz** [comment]
ngMessages doesn't have anything to do with the viewValue of the model. It just accepts an object where the keys are the identifiers and the values are the "switch" to show or hide. It's most commonly used for the $error prop of an ngModelController, but that's just one use case. 

The issue you have rather has something to do with the fact that ngModel is added by name to the form, but how simple or complex that name is, is fully under your control.
