### ISSUE TITLE
Not able to inject $attrs module in controller

### ISSUE THREAD

**Issue by prashant-saxena** [angular/angular.js#16092]
**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
$attrs is giving me injection error

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.4

**Browser:** [all]

**Anything else:**
I'm new to ng. Trying to get my hands on a custom project where I'm also using angular material library also. I have a controller which is working fine:
```
myApp.controller(myApp.baseController', ['$scope',
                                            //'$attrs',
                                            '$mdDialog',
                                            'getData',
                                            'postData',
                                            function(
                                            $scope,
                                            //$attrs,
                                            $mdDialog,
                                            getData,
                                            postData)
```
As soon as I add $attrs I'm getting this error in console:
Error: [$injector:unpr] http://errors.angularjs.org/1.6.4/$injector/unpr?p0=%24attrsProvider%20%3C-%20%24attrs%20%3C-%20myApp.baseController.
I tried googling but so far out of luck.
Let me explain you why I need $attrs module. Actually I'm trying to get rid of specifying formName when using ng-messages directive. I did using a hack which you can see here:
[https://stackoverflow.com/questions/45015174/ng-messages-without-form-name](url)
Although it's working as expected but is it the right way to do it ? or a custom directive would be the correct solution?  I don't know if there are any disadvantages of using the hack I implemented. You can see $attrs is working there but when I'm using it I'm getting injection error posted above. The reason to get the current scope's name which is a form. Is there any other way to get the scope's name in controller then I won't be needing $attrs module.

Cheers

**Comment by Narretz** [comment]
Works for me: http://plnkr.co/edit/coleI77TUDDKLCAmsFea
$attrs etc are services / providers btw, not modules.
