### ISSUE TITLE
Loading "Gruntfile.js" tasks...ERROR

### ISSUE THREAD

**Issue by hellofadude** [angular/angular.js#16107]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Trying to build angular using grunt get the following error

Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read CDN version, are you offline or has the CDN not been properly pushed?
>> Perhaps you want to set the NG1_BUILD_NO_REMOTE_VERSION_REQUESTS environment variable?
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

**Expected / new behavior:**

Should build successfully

**Minimal reproduction of the problem with instructions:**

git clone https://github.com/<github username>/angular.js.git

cd angular.js

git remote add upstream "https://github.com/angular/angular.js.git"

yarn install

grunt package

**Angular version:** 1.6.6

**Anything else:** fix - pull request sent

**Comment by Narretz** [comment]
Closing. See https://github.com/angular/angular.js/pull/16108
