### ISSUE TITLE
Custom string to integer directive, no value in post

### ISSUE THREAD

**Issue by prashant-saxena** [angular/angular.js#16113]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Directive is working fine but post is empty is the input field is empty.

**Expected / new behavior:**
If input is empty, an empty string should go in post.

**Minimal reproduction of the problem with instructions:**
Here is the link
[https://groups.google.com/forum/#!topic/angular/OWw5Wg00QUM](url)

**Angular version:** 1.6.4

**Browser:** [all ]

**Anything else:**

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

That said, the if / else block in your directive looks wrong (syntax error).
