### ISSUE TITLE
Set idle and timeout time dynamically in angularjs

### ISSUE THREAD

**Issue by chetanganguly** [angular/angular.js#16118]
Hi guys I want to set these value time in seconds(5) dynamically...

   IdleProvider.idle(5);
   IdleProvider.timeout(5);
   KeepaliveProvider.interval(10);

   How I can perform this inside app.config...?
   Or any other alternative way?
   I have web API which will return these times

  Thanks

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by chetanganguly** [comment]
Thanks narretz
