### ISSUE TITLE
TypeError: 'undefined' is not a function (near '....info({ angularVersion: '...') at bower_components/angular-messages/angular-messages.js

### ISSUE THREAD

**Issue by nareshg2017** [angular/angular.js#16111]
My project is based on AngularJs,Spring & Mongodb.
I was trying to deploy the Application on the server,but build failed.

Relevant parts of my bower file:
"angular": "1.4.9",
    "angular-aria": "1.4.9",
    "angular-bootstrap": "0.14.3",
    "angular-cache-buster": "0.4.3",
    "angular-cookies": "1.4.9",
    "angular-material": "1.0.3",
    "angular-local-storage": "0.2.3",
    "angular-loading-bar": "0.8.0",
    "angular-resource": "1.4.9",
    "angular-sanitize": "1.4.9",
    "angular-animate": "1.4.9",
    "angular-ui-router": "0.2.15",
    "bootstrap": "3.3.5",
    "jquery": "2.1.4",
    "json3": "3.3.2",
    "modernizr": "3.2.0",
    "ng-file-upload": "10.0.2",
    "ngInfiniteScroll": "1.2.1",
    "swagger-ui": "2.1.3",
    "moment": "^2.11.2",
    "angular-moment": "^0.10.3",
    "double-scroll-bars": "przno/double-scroll-bars#^0.1.5",
    "ngclipboard": "^1.1.1"

grunt test: 
![111111](https://user-images.githubusercontent.com/30171504/28203728-8cd1c326-6898-11e7-9d91-009dfcd62ffd.png)

now angular-messages installed by default 1.6.5
If i try to install angular-messages 1.4.9, all 44 phantomjs test fails.
what will be the cause of this issue??
Please help me,I'm new to this field

**Comment by gkalpak** [comment]
This indicates a version mismatch between angular.js and one or more optional modules (most probably `angular-messages`). Regardless of what you `bower.json` says, ensure that the versions you are using are actually the same.
