### ISSUE TITLE
Strange behaviour $compile service for literal expression at bi-directional binding

### ISSUE THREAD

**Issue by boyarincev** [angular/angular.js#16136]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

I look bi-directional binding for direcrives at [$compile service](https://github.com/angular/angular.js/blob/v1.6.5/src/ng/compile.js#L3485-L3527) and see strange behaviour for literal expressions, which in theory cause decline perfomance when working with them. Maybe I'm wrong.

1. [Using](https://github.com/angular/angular.js/blob/v1.6.5/src/ng/compile.js#L3524) objectEquality = true at $watch for literal expression
`scope.$watch($parse(attrs[attrName], parentValueWatch), null, parentGet.literal);`

For my point of view this is makes no sense, because watcher dosen't have listener and deep comparison lead to nothing, howewer will be slower than refference equality.

2. When the literal property changes within a directive's scope, rollback of values on previous [occur](https://github.com/angular/angular.js/blob/v1.6.5/src/ng/compile.js#L3498-L3504):

```
            lastValue = destination[scopeName] = parentGet(scope);
```
Howewer, at the end parentValueWatch method lastValue variable [again assigned](https://github.com/angular/angular.js/blob/v1.6.5/src/ng/compile.js#L3512-L3518) value from directive's scope and it returned as watch function value: 

```
                } else {
                  // if the parent can be assigned then do so
                  parentSet(scope, parentValue = destination[scopeName]);
                }
              }
              lastValue = parentValue;
              return lastValue;
```

As result new value will be differ from previous value and values deep comparison occur.

3. Why [need deep comparison](https://github.com/angular/angular.js/blob/v1.6.5/src/ng/compile.js#L3493-L3497) for literal expression ?

 ```
           if (parentGet.literal) {
              compare = equals;
            } else {
              compare = simpleCompare;
            }
```

Only primitives [can be literals for $parseProvider](https://docs.angularjs.org/api/ng/provider/$parseProvider), what can happen with primitive that not enough simple comparison ?

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.5

**Browser:** [all]

**Anything else:**

**Comment by jbedard** [comment]
> Only primitives can be literals for $parseProvider, what can happen with primitive that not enough simple comparison ?

Object and array literals are also literal. Those are the cases that need the deep equal since shallow equal will be false every time.

It's probably best to always use `<` bindings to avoid this stuff and the confusion with the `noassign` error.

However... we could drop the `noassign` error and treat non-assignable `=` bindings like `<` bindings. Then we'd never need deep equals, and could avoid using the `$stateful` `parentValueWatch` for those non-assignable expressions (like literals). Then when a directive/component assigns to a `=` binding that is not assignable it will be more like an optional binding and have no effect outside the directive/component. Hmm...

**Comment by gkalpak** [comment]
> 1. Using objectEquality = true at $watch for literal expression
> For my point of view this is makes no sense, because watcher dosen't have listener and deep comparison lead to nothing, howewer will be slower than refference equality.

@boyarincev, deep watching has side effects that are important for the two-way binding functionality, even when there is no watch listener. For example, it is important for [setting the `dirty` flag][1] (which determines whether there should be another digest loop) and determines how to [store the last value][2].

##
> 2. When the literal property changes within a directive's scope, rollback of values on previous occur:
>     lastValue = destination[scopeName] = parentGet(scope);
> Howewer, at the end parentValueWatch method lastValue variable again assigned value from directive's scope and it returned as watch function value:
>    ...

Not sure what you mean. In the case where `parentSet` is called (while the expression is not assignable) an error is thrown so the `parentValueWatch()` is interrupted. (And even if it weren't interrupted, it doesn't set the value to the one on the directive's scope, but to `parentValue`, which comes from the parent scope.)

##
> 3. Why need deep comparison for literal expression ?

As already explained by @jbedard, object and array literals need the deep-watching.

##
> However... we could drop the `noassign` error and treat non-assignable `=` bindings like `<` bindings. > Then we'd never need deep equals, and could avoid using the `$stateful` `parentValueWatch` for those non-assignable expressions (like literals).

@jbedard, not sure I like the idea :grin: Using non-assignable expressions (like literals) on `=` bindings is (potentially) an error. Especially now that we support `<` bindings. 

[1]: https://github.com/angular/angular.js/blob/f1d01bbc748e033035107dbb4259fe40d3443dfb/src/ng/rootScope.js#L824
[2]: https://github.com/angular/angular.js/blob/f1d01bbc748e033035107dbb4259fe40d3443dfb/src/ng/rootScope.js#L826

**Comment by gkalpak** [comment]
Closing since this isn't actionable and everything works as expected, but feel free to continue the discussion below.

**Comment by jbedard** [comment]
The weird thing is that `=*` bypasses the `noassign` already. But the best answer is to use `<` bindings...

**Comment by boyarincev** [comment]
> Object and array literals are also literal. Those are the cases that need the deep equal since shallow equal will be false every time.

@jbedard  But in the documentation for $parseProvider told than only primitive may be added as literal: https://docs.angularjs.org/api/ng/provider/$parseProvider

> literalValue Value for this literal. All literal values must be primitives or undefined.

Object and array literals considered as primitives?

When I try use $parse with object or array literals I get runtime error: https://plnkr.co/edit/erjMa8xTBnyY5Fc2qeec?p=preview

**Comment by boyarincev** [comment]
> Not sure what you mean. In the case where parentSet is called (while the expression is not assignable) an error is thrown so the parentValueWatch() is interrupted. 

@gkalpak  My mistake, i have not seen throw and think execution continued

>(And even if it weren't interrupted, it doesn't set the value to the one on the directive's scope, but to parentValue, which comes from the parent scope.)

But before calling parentSet method, parentValue variable [get new value](https://github.com/angular/angular.js/blob/v1.6.5/src/ng/compile.js#L3514):

`parentSet(scope, parentValue = destination[scopeName]);`

which as far as I understand value in directive's scope.

**Comment by jbedard** [comment]
> @jbedard But in the documentation for $parseProvider told that only primitive may be added as literal: https://docs.angularjs.org/api/ng/provider/$parseProvider

The literal flag within the code is unrelated to the public `$parseProvider.addLiteral`.
