### ISSUE TITLE
Cannot read property '$$animLeave' of undefined

### ISSUE THREAD

**Issue by abbymrs** [angular/angular.js#16134]
Hi, 
I got the error `Cannot read property '$$animLeave' of undefined` after i upgraded my application from angular version 1.5.0 to 1.6.5 with ui-router version 1.0.5.
It only happens with the sub-router with params, like "/demo/lists/:id", could you pls kindly give me some help?
Thanks a lot!

**Comment by gkalpak** [comment]
`$$animLeave` is not something used by AngularJS itself. It is probably coming from a 3rd-party library (possibly `ui.router`). You need to find out where it comes from and use their support channels.

You could also try to ask for help on one of our [general support channels][1].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
