### ISSUE TITLE
fix($httpParamSerializerJQLike): call functions as jQuery does

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#16138]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Function properties are ignored by `$httpParamSerializerJQLike()`.

**Expected / new behavior:**

Functions should be called and the return value used, the same way [jQuery does][1].

[1]: https://github.com/jquery/jquery/blob/a6b0705294d336ae2f63f7276de0da1195495363/src/serialize.js#L63-L65

**Comment by gkalpak** [comment]
(Although not necessarily a breaking change (in the sense that this serializer's purpose is to follow jQuery as close as possible), it may break some apps relying on the old, buggy behavior.)

**Comment by frederikprijck** [comment]
@gkalpak  Looking at this we could easily patch https://github.com/angular/angular.js/blob/394dbcc2773e218b1eaa7b1f2b14a943ef78c8e0/src/ng/http.js#L17 , but this would affect all other serializers. Is that something u want ?

**Comment by gkalpak** [comment]
No, we only want to affect `$httpParamSerializerJQLike`.
