### ISSUE TITLE
outdated example with Yahoo Finance API

### ISSUE THREAD

**Issue by elenaparaschiv** [angular/angular.js#16130]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

In the Conceptual Overview Section > Accessing the backend> in finance3.js the example with Yahoo Finance API is outdated. Currently the Yahoo Finance API is broken.

**Expected / new behavior:**

In the section Conceptual Overview> Accessing the backend > finance3.js:
I suggest adding a new example that is not outdated or soon to be outdated. This will keep the documentation up to date and increase its readability.

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

One example that could replace the Yahoo Finance  API is the API made by https://docs.openexchangerates.org/ 

Other suggestions:
https://1forge.com/forex-data-api
http://www.financialcontent.com/support/documentation/json_quote_api.php

**Comment by gkalpak** [comment]
I don't see the example being broken as you suggested. But if there is a solid alternative, we could consider moving the example to another API. (PRs welcome :smiley:)

**Comment by jeserkin** [comment]
Not sure how Yahoo is related to AngularJS.

**Comment by gkalpak** [comment]
Not sure what you mean. Yahoo is not related to AngularJS (except that we use the Yahoo Finance API in one of our examples).

**Comment by elenaparaschiv** [comment]
@gkalpak Yes.I am suggesting the Yahoo Finance API is not currently available. When I was reading the documentation for angular : section on Conceptual Overview Section > Accessing the backend, the example there is using the Yahoo API.
I wanted to check for the Yahoo Finance API to see the docs of how this  API  is added. And I could not find it. I was thinking it would be better to add another API as an example in this section that has documentation at the current moment. I suggested https://docs.openexchangerates.org/ as well as a few others in my initial post

**Comment by frederikprijck** [comment]
I don't think the docs for the Yahoo API are necessary in order to understand what's happening in the AngularJS docs, but I guess it wouldn't hurt updating the samples to an API which does have some docs.

**Comment by gkalpak** [comment]
OK, so in fact we are not using the Yahoo Finance API. We are using [YQL][1] (which is just a query language) to query data form [datatables.org][2]. You can find docs in these links.

And, as already mentioned, we could consider moving to an alternative API if it made the example simpler or better in some way (PRs welcome).

[1]: https://developer.yahoo.com/yql/guide/overview.html
[2]: https://www.datatables.org/

**Comment by andypotts** [comment]
I'd like to update the example if no one else is already doing it?

**Comment by elenaparaschiv** [comment]
That would be great @andypotts

**Comment by andypotts** [comment]
@elenaparaschiv @gkalpak In that PR I used the http://fixer.io/ API and was able to create a simpler solution. Let me know if you want me to change it to use a different API.

**Comment by elenaparaschiv** [comment]
Nice work @andypotts
