### ISSUE TITLE
Angularjs Interpolation using double curly braces not working under ng-if

### ISSUE THREAD

**Issue by tarekahf** [angular/angular.js#16140]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

If I use directive `check-if-required` as per the fix recommended in:

https://github.com/angular/angular.js/issues/15956#issuecomment-300873148

... then, if there is inner directive that uses a `templateUrl`, and again the directive `check-if-required` is used in the template, and there is `ng-if` used in the inner elements, then the double curly braces `{{}}` interpolation will not work. Only `ng-bind` will work in this case.

**Expected / new behavior:**

The double curly braces should work in all cases.

**Minimal reproduction of the problem with instructions:**

Check this plunker sample:

http://plnkr.co/edit/JJbq54?p=preview

In the above sample, see the section "With ng-if" and "Without ng-if", enter something in the input text, and see how the double curly braces not working under `ng-if`, but ng-bind works fine.

If you remove `ng-if` or you remove `check-if-required` from the template `sites-and-improvements.html` then the problem will be solved.

Tarek

**Comment by gkalpak** [comment]
This has to do with directive priorities. As mentioned in my previous comments, doing everything in the linking phase os only suitable for very simple usecases. The "proper" way is to use the compile phase too ([updated plnkr][1]).

##
Again, it is better to use the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: http://plnkr.co/edit/nxz7tX?p=preview
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by tarekahf** [comment]
Thank you. I understand what you mentioned, however, I used the variable `scope` (which is passed to the link function) I used it extensively in the link function. It appears to me that it is going to be very challenging to restructure the code so that such usage is done in the `compile` phase.

I appreciate your feedback.

Tarek

**Comment by gkalpak** [comment]
As you can see in the updated plnkr, you can still use the link function (where you get access to the scope), but some things might need to happen in the compile function.
(In fact you might get by with doing everything in the link function, but the `$timeout` makes things more messy.)
