### ISSUE TITLE
Event parameters not passed on from child components

### ISSUE THREAD

**Issue by adamreisnz** [angular/angular.js#16148]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Given nested components of at least 3 layers deep, event arguments are lost along the way unless explicitly creating intermediate controller helpers.

**Expected / new behavior:**
Parameters are correctly propagated when passing an output binding to a nested component without intermediate controller helpers.

**Minimal reproduction of the problem with instructions:**

https://plnkr.co/edit/XBQiohMYqc5CUDfBMVNN?p=preview

In the example plunkr this is demonstrated by three levels of nested components, `parent`, `child` and `grand-parent`. The click action link sits in the `grand-parent` component, and upon clicking it, it fires an event up the component chain. Since the `child` component is only forwarding the event, no explicit handler is defined on its controller, and the bound `onAction` handler is passed on to create a link between `parent` and `grand-child`.

However, along the way the `$event` parameter is lost and it doesn't reach the parent component.

The only way I could see to "fix" this, was by introducing a redundant intermediate controller helper in the `child` component, as demonstrated here:

https://plnkr.co/edit/xmfT9M4QeY4Vt91Ie5Ri?p=preview

In this case, the event is propagated as expected, but at the expense of introducing seemingly redundant helper methods.

One would expect the first example to work properly, avoiding the need for helper methods, which can get tedious and needlessly verbose when component nesting is more than 2 or 3 layers deep.

**Angular version:** 1.6.x

**Browser:** All

**Comment by frederikprijck** [comment]
If I use the following template in the child component, it works fine:
`<grand-child on-action="$ctrl.onAction({$event})"></grand-child>`
Here's a fork of your plunkr: https://plnkr.co/edit/u2VVg8FiALvn9RJVQrin?p=preview

This is basicly the same you're doing in your second plunkr, but there's no need for a controller just for that.

**Comment by adamreisnz** [comment]
Hi @frederikprijck , thanks, you're right, I missed that and assumed the template would take care of it and just pass the event on!
