### ISSUE TITLE
Text editor

### ISSUE THREAD

**Issue by mahitaande** [angular/angular.js#16143]
Hi,
I am looking for a text editor which offers MS word like features. Currently we are using Telerik RichTextBox, however since silverlight is not actively supported I am thinking of switching to another editor. Below link works only in IE.

http://demos.telerik.com/silverlight/#RichTextBox/TelerikEditor

The text editor should offer features like Rtf support ability, formatting options, customization.
Could you please suggest if there is another angular text editor control that offers word like features.

**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Angular version:** 1.3

**Browser:** [all | Chrome (latest) | Firefox XX | Edge XX | IE 11 | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
Hey, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by Narretz** [comment]
@frederikprijck is right.

There are many RTE out there, and my advice is not to look speficfically at AngularJS editors, because text editors are usually so "close to the metal" that a specific AngularJS implementation is not useful.
