### ISSUE TITLE
Missing scroll bar when embedding md-list into md-tab-body

### ISSUE THREAD

**Issue by Andi1990** [angular/angular.js#16144]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

When embedding a horizontal md-list into a md-tab-body, there is no horizontal scroll bar for scrolling to the end of the list.
**Expected / new behavior:**

There should be a horizontal scrollbar in order to scroll the list. Just like it is in the case of a vertical list (vertical scroll bar appears).
**Minimal reproduction of the problem with instructions:**

1. Create <md-tab> with <md-tab-body>
2.  Embed <md-list> with some items (<md-list-item> e.g. items  as <md-card>) and layout="row"
3. Result should be a horizontal list of for example cards. However, there is no horizontal scrollbar available.
**Angular version:** 1.5.8

**Browser:** [all]

**Comment by gkalpak** [comment]
Wrong repo. You are probably looking for https://github.com/angular/material.
