### ISSUE TITLE
Missing Syntax

### ISSUE THREAD

**Issue by abhishek0058** [angular/angular.js#16147]
Page have a missig '{' at -- https://angular.io/guide/reactive-forms#the-data-model-and-the-form-model
under topic 
<h1>reset the form flags</h1>
<h2>src/app/hero-detail.component.ts (ngOnchanges - revised)</h2>

**Comment by gkalpak** [comment]
I don't see any missing `{` there, but if you still do, please open an issue on https://github.com/angular/angular.
<sub>This repo here is for AngularJS (aka 1.x) only.</sub>
