### ISSUE TITLE
ScreenReader should differentiate between the name of the combo box, and the selected option

### ISSUE THREAD

**Issue by RajivPrab-Google** [angular/angular.js#16146]
**I'm submitting a ...**

- [X ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

When selecting a value from an auto-complete, the screenreader reads it out as "{Combo box name} {Value} collapsed combo box". It's unclear to the user which part of the text read is the combo-box-name, and which is the value.

**Expected / new behavior:**

When selecting a value from an auto-complete, the screenreader should read it out as "{Combo box name} combo box collapsed {Value} selected"

**Minimal reproduction of the problem with instructions:**

Download and enable the ChromeVox extension, on a Chrome browser. Go to https://material.angularjs.org/latest/demo/autocomplete. Enter an input, and select a value from the autocomplete.

**Angular version:** 1.6.4-local+sha.617b36117

**Browser:** 59.0.3071.115

**Anything else:**

I'm a SWE at Google, and we're hitting this bug while trying to improve accessibility for an internal app we're building. My ldap is rajivprab@, if you'd like to chat further.

**Comment by gkalpak** [comment]
Wrong repo. Please reopen on https://github.com/angular/material.
