### ISSUE TITLE
When selecting an entry for auto-complete, ChromeVox Screenreader does not notify user of the selection made

### ISSUE THREAD

**Issue by RajivPrab-Google** [angular/angular.js#16145]
**I'm submitting a ...**

- [X ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

When selecting an entry in an auto-complete, the screen reader reads out the entry name. Once the user hits enter, the reader simply says "entry deleted", and does not tell the user that a chip was successfully selected and added.

**Expected / new behavior:**

When the user hits enter, the screenreader should notify the user in some way that the chip was successfully selected and added. It would be great if the screenreader also notified the user which chip exactly was added.

**Minimal reproduction of the problem with instructions:**

Download and enable the Chromevox extension on a chrome browser. Go to https://material.angularjs.org/latest/demo/chips#custom-inputs, enter something into the auto-complete field, and select an auto-complete entry. This behavior was reproduced on chromevox-extension, on a chrome browser.

**Angular version:** 1.6.4-local+sha.617b36117

**Browser:** Chrome 59.0.3071.115

**Anything else:**

I'm a SWE at Google, and we're hitting this bug while trying to improve accessibility for an internal app we're building. My ldap is rajivprab@, if you'd like to chat further.

**Comment by gkalpak** [comment]
Wrong repo. Please reopen on https://github.com/angular/material.
