### ISSUE TITLE
angular.copy behaves differently in iOS devices

### ISSUE THREAD

**Issue by mcenkbatman** [angular/angular.js#16152]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

I am using angular.copy function in one of my projects in a function I use for file uploading. This project is being used in both mobile and desktop. I figured out that in iOS devices (I only tested it with iOS 10) angular.copy doesn't copy the files property of input element on neither Safari nor Chrome appropriately. It works perfect with other platforms like Android Chrome and MacOS safari and chrome
**Expected / new behavior:**

angular.copy should behave similary on iOS browsers as would behave in Android browsers

**Minimal reproduction of the problem with instructions:**

Here is a plunker , demonstrating length of files of input element before and after copy. Please try it on an iOS device to see the bug. http://plnkr.co/edit/7EBbitlnY8TRL7dD2QUe

**Angular version:** 1.4.x

**Browser:** [Mobile Chrome 59 | iOS 10 Safari ]

only on iOS devices

**Anything else:**

**Comment by frederikprijck** [comment]
This doesn't look like a direct issue with AngularJS. As you're providing an HTML node, this code is going to be triggered: https://github.com/angular/angular.js/blob/master/src/Angular.js#L1010

This is making use of [https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode](Node.cloneNode), which looks like to have issues on Safari.

You can try it by running this fork on IOS: http://plnkr.co/edit/yal7FE7bBnMhhddwtvLp?p=preview

Make sure to read https://github.com/angular/angular.js/issues/14352 as well.

**Comment by gkalpak** [comment]
(As explained in https://github.com/angular/angular.js/issues/14352#issuecomment-207063928, `angular.copy()` does not (and will not) handle all possible edge-cases. Its primary purpose is facilitating AngularJS's internal needs.)
