### ISSUE TITLE
i have update angularjs from 1.4.8 to 1.6.0 and get this error

### ISSUE THREAD

**Issue by constantinosergiou** [angular/angular.js#16151]
i have update angularjs from 1.4.8 to 1.6.0 and get this error
``TypeError: a is not a function
    at d (angular-animate.js:2132)
    at angular-animate.js:2122
    at I (angular-animate.js:3210)
    at Array.fn (angular-animate.js:3058)
    at c (angular-animate.js:403)
    at b (angular-animate.js:373)
    at Array.<anonymous> (angular-animate.js:3080)
    at Scope.$digest (angular.js:17851)
    at Scope.$apply (angular.js:18066)
    at done (angular.js:12207)```

**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**Angular version:** 1.6.

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
There's little information to know what's causing the issue. Please provide a reproduction.

Anyway, a wild guess: Are all your libraries being updated to 1.6.0? Or do you still have some 1.4.8?

Other than that, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by constantinosergiou** [comment]
yes i use the correct libraries ok  will try it to make reproduction soon

**Comment by frederikprijck** [comment]
It also looks like some parts are minified, it might be a good idea to avoid minification when trying to interpret the stacktrace.

**Comment by constantinosergiou** [comment]
hmm i get this error TypeError: $$animateJs is not a function

**Comment by gkalpak** [comment]
As @frederikprijck said, it is impossible to tell what is wrong without a reproduction. In any case, this doesn't look like an issue in AngularJS. (Mismatched versions sounds like a possible cause indeed).

Also, make sure you read about the breaking changes introduced between 1.4 and 1.6 ([Migration Guide][1], [Changelog][2]). Finally, the [general support channels][3] are a good place to get help with these types of problems.

[1]: https://docs.angularjs.org/guide/migration
[2]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md
[3]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
