### ISSUE TITLE
Fatal error: Unable to find local grunt.

### ISSUE THREAD

**Issue by hhb19900618** [angular/angular.js#16153]
xuetianhhbdeMac-mini:angular.js-master xuetianhhb$ grunt package
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

**Comment by frederikprijck** [comment]
@hhb19900618 It's almost impossible what you're trying to say here. It looks like you copied an error without any further clarification. 

This looks (and it clearly states so) like it's not a problem with AngularJS itself.

This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). But keep in mind, if you need some assistance it's a good idea to provide some clarification.
Thanks!

**Comment by Narretz** [comment]
You probably haven't installed the local grunt. Try `yarn install`.
