### ISSUE TITLE
Dynamic NgClass not updating classes of DOM element

### ISSUE THREAD

**Issue by qpascualsola** [angular/angular.js#16158]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

When using ng-class with a dynamic expression  (built by a controller function) the classes are not updating if the DOM element does not render again.

**Expected / new behavior:**

The ng-class built and updated by de controller should update de classes of the DOM element without the need to render it again.

**Minimal reproduction of the problem with instructions:**

The button _Yellow_ should change the background of the input to yellow. 
The background color of the input only change if you press the _Visible_ button twice.
Plunker: http://plnkr.co/edit/qS3rfFEKSZavoGx9BT4z?p=preview

**Angular version:** 1.6.5

**Browser:** [all]

**Anything else:**

Suggestion how to fix: in the _ngClassDirective_ add a watch to the attribute _ngClass_. Now there is only a watch to the $parse expression.

`var watchInterceptor = isOneTime ? toFlatValue : toClassString;`
`var watchExpression = $parse(expression, watchInterceptor);`
`var watchAction = isOneTime ? ngClassOneTimeWatchAction : ngClassWatchAction;`
		
`// This Watch fix the issue.`
`scope.$watch(function() { return attr[name].trim(); }, function(expression) { `
`      watchExpression =  $parse(expression, watchInterceptor);`
`      scope.$watch(watchExpression, watchAction, isOneTime);`
`});`

**Comment by Narretz** [comment]
You don't need the extra interpolation - it's worse for performance and harder to follow, and we don't explicitly support cases where expressions and interpolated expressions are mixed. This plnkr http://plnkr.co/edit/jRw3aRgzjI74AYSXIgcR?p=preview should do the same as yours did.
