### ISSUE TITLE
ng-include works weird on IOS

### ISSUE THREAD

**Issue by abbymrs** [angular/angular.js#16156]
Hi,

I use `ng-include` to import some html, it works well almost all the time, but occasionally works weird in IOS platform.

```
<div class="form-group username">
    name:
    <input type="text" >
</div>
<ng-include src="'/src/contacts/edit-phone.html'"></ng-include>
<div class="form-group password">
    password:
    <input type="password" >
</div>
```
The `ng-include` occasionally takes the place of `password div` and occurs in its bottom in the first time content loaded on `IOS` platform, something like this:
```
<div class="form-group username">
    name:
    <input type="text" >
</div>
<div class="form-group password">
    password:
    <input type="password" >
</div>
<ng-include src="'/src/contacts/edit-phone.html'"></ng-include>
```
May i know why this happens?

**Comment by Narretz** [comment]
I would tell you why it happens if I knew it ;)
Maybe it's because ng-include is used as an element, and this somehow messes with Safari's HTML parser. Does it also happen when you put it on a div?

**Comment by abbymrs** [comment]
will try later, thanks!

**Comment by abbymrs** [comment]
After i change ng-include tag to div tag attribute, it works, thanks a lot!

**Comment by abbymrs** [comment]
@Narretz Strange, only when ng-include tag is under form directly, this issue occurs; ng-include as a tag works well in other situation
