### ISSUE TITLE
issue with crud methodnot allowed 404 and 405 in console 

### ISSUE THREAD

**Issue by aamirkhan37557** [angular/angular.js#16172]
iam laravel deveolper i want to perform crud in angularjs but iam facing an issue when i click on the button to send post request 
main page
![a](https://user-images.githubusercontent.com/24594319/29271599-1f1ad3a0-80b1-11e7-81b5-7b0183b7aacc.png)

this is my controller
![controller](https://user-images.githubusercontent.com/24594319/29271609-28f3db9c-80b1-11e7-9576-50648a4abbcc.png)

this is my routes
![routes](https://user-images.githubusercontent.com/24594319/29271621-355b8704-80b1-11e7-9fe8-ca255edfd05d.png)

this is my page before click on button

![before](https://user-images.githubusercontent.com/24594319/29271635-49c5aa30-80b1-11e7-934e-86e2666ed38f.png)

this is after clicking on the button
![after](https://user-images.githubusercontent.com/24594319/29271640-51b1fb90-80b1-11e7-8e4c-3f1ff5eb52b3.png)

**Comment by frederikprijck** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by Narretz** [comment]
Additionally: it looks like you are having problems with your Laravel code, not with your AngularJS code.
