### ISSUE TITLE
Expose function to get all angular form classes from a form control instance

### ISSUE THREAD

**Issue by kyletheninja** [angular/angular.js#16178]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Currently, we can fairly easily reproduce the form control classes (`ng-valid`, `ng-dirty`, etc) with the corresponding exposed properties (`form.control.$valid`, `form.control.$dirty`, etc).

**Expected / new behavior:**

However, I believe we could have even cleaner, less redundant code if one additional property was added to form control objects. It could be called `$getClasses()` for example, and this method would then return an object with the class keys, such that it could be used directly in an `ng-class` within the same template. I will illustrate further in my example.

**Minimal reproduction of the problem with instructions:**

Below is what I have done with what we have to get what I want. It works fine.

In my controller I have
```javascript
$scope.formControlClasses = function(control) {
    return {
	'ng-dirty' : control.$dirty,
	'ng-pristine' : control.$pristine,
	'ng-touched' : control.$touched,
	'ng-untouched' : control.$untouched,
	'ng-valid' : control.$valid,
	'ng-invalid' : control.$invalid
    };
};
```
And in my template I have
```html
<form name='myForm'>
    <div class='radio-group' ng-class='formControlClasses(myForm.willy)'>
        <label class='radio-input'>
            <input type='radio' name='willy' ng-model='silly.willy' value='foo'>
        </label>

        <label class='radio-input'>
            <input type='radio' name='willy' ng-model='silly.willy' value='bar'>
        </label>
    </div>

    <div class='submit-btn' ng-click='submit()'>Submit</div>
</form>
```

This works fine, but I feel like I am unnecessarily reproducing functionality that I will have to redo wherever I need, or else port around in a custom service. It would be nice if I could simply write my template like so ~

```html
<form name='myForm'>
    <div class='radio-group' ng-class='myForm.willy.$getClasses()'>
        <label class='radio-input'>
            <input type='radio' name='willy' ng-model='silly.willy' value='foo'>
        </label>

        <label class='radio-input'>
            <input type='radio' name='willy' ng-model='silly.willy' value='bar'>
        </label>
    </div>

    <div class='submit-btn' ng-click='submit()'>Submit</div>
</form>
```

**AngularJS version:** 1.6.5

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
Using functions as bindings is generally not a good idea as CD can't decide things have changed without re-executing the method.

This would resultin unneccesary execution of the method, have a look at the following plunk: https://plnkr.co/edit/HjMT76gC35bhMdeSz46Y?p=preview

Just type some stuff in the input and inspect the browsers console.

I do understand the overhead in this case is limited, but I'm not sure I'm a fan of implementing this the way you're proposing.

It might be a better idea to use a property instead of a method: `myForm.willy.$classes` which allows CD to decide whether or not changes occured without (unnecesary) executing the method.

**Comment by kyletheninja** [comment]
That makes sense, a property would be better I think. I was only thinking method because without it being integrated into angular using a custom function was the simplest way I could figure out how to do it.

**Comment by Narretz** [comment]
I'm not convinced that this is a very common use case that we need to support.

**Comment by gkalpak** [comment]
> I'm not convinced that this is a very common use case that we need to support.

Even more so, since it is very easy to implement outside core.

**Comment by Narretz** [comment]
Closing because it's outside of core scope.
