### ISSUE TITLE
feat-req: ng-revert directive to revert intercept and cancel ng-change

### ISSUE THREAD

**Issue by awiebe** [angular/angular.js#16170]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
If an ng-change occurs there is no point at which this can be intercepted, and cancelled.  One work around for strings is to call a function e.g. `promptRevert('{{currentValue}}')`  to grab the current value of the field and then revert on cancellation.  This does not work for objects because it produces a string representation.

**Expected / new behavior:**
Add directive `ng-revert="revertChangeIfTrue()"` which reverts ng-model to previous value which clearly you know since there is a watcher.

**AngularJS version:** 1.4.8

**Browser:** all

**Anything else:**
There is logic where ng-change occurs, to know that there was a change there must have been a change event, which means somewhere in that code it knows the scope is not its previous value.  Recover the value from this and set it back if the revert directive triggers.

I would write it in but I just use angular, I don't know anything about its core and consequently where to put it without seriously breaking a very important part of it.

**Comment by gkalpak** [comment]
I don't really understand what this is about. Can you add more details? Do you want `ng-change` to be able to revert a change? That would be quite unconventional. Wouldn't a validator be more suitable for this?

**Comment by awiebe** [comment]
Suppose 

- You have an ng-select which represents a list of documents
- Selecting another document in the list requires that you save the first document by talking to the server
- If the user selects another document from the list and you have that the currently open document is not dirty, you're fine.  But **if you want to ask the user whether they want to save before changing the active document because it is dirty, there is no facility for this**.

- You only know when the ng-model has changed for that select after it has changed, but when the model changes the reference to the previously selected in the list document is lost(short of doing some nonsense using $index).

- Also angular refuses to allow the current $viewValue to be passed as a parameter to a revert function which could be provided to ng-change, so we can't recover the value in the $scope before change occurred.

- Consequently I propose a simple change that allows a user to inject a function that cancels a change.

I have been digging in the codebase and I think the logic needs to go here
https://github.com/angular/angular.js/blob/7c876285cbfebf69a2ea64a216f903cf8d3803ee/src/ng/directive/ngModel.js#L766


 ## Option 1 : ng-revert="cancelChangeIfTrue"
```
$$writeModelToScope: function() {
   if(should_revert_because_revert_directive_for_this_ng_model_returned_true)
  {
    return;
  }
    this.$$ngModelSet(this.$$scope, this.$modelValue);
    forEach(this.$viewChangeListeners, function(listener) {
      try {
        listener();
      } catch (e) {
        // eslint-disable-next-line no-invalid-this
        this.$$exceptionHandler(e);
      }
    }, this);
  }
```

 ## Option 2 : ng-pre-chage="cancelChangeIfTrue"
Give the user a change to read old scope variables before the model is written back to scope.
```
$$writeModelToScope: function() {
//NEW PRECHANGE
forEach(this.$viewPreChangeListeners, function(listener) {
      try {
        listener();
      } catch (e) {
        // eslint-disable-next-line no-invalid-this
        this.$$exceptionHandler(e);
      }
    }, this);

    this.$$ngModelSet(this.$$scope, this.$modelValue);
    forEach(this.$viewChangeListeners, function(listener) {
      try {
        listener();
      } catch (e) {
        // eslint-disable-next-line no-invalid-this
        this.$$exceptionHandler(e);
      }
    }, this);
  }
```

**Comment by awiebe** [comment]
I think these would make a handy convenience method but I've found an alternative implementation.  The problem I was having before was that ng-repeat creates a new variable scope, which confuses angular if you try to restore the old reference to the  active document ng-model, because that is no longer a valid reference in the values being read by ng-repeat.  It seems as long as I use the select directive the reference is valid, because a new scope is not created.

**Comment by gkalpak** [comment]
What you describe sounds to me as a perfect candidate for an [async validator][1] (make sure you check out the docs in case you haven't already).

##
>which confuses angular if you try to restore the old reference to the active document ng-model

It rather porbably confuses you, not Angular 😛 
Joking aside, there is this great resource on [understanding scopes][2] (and prototypal inheritance in general).

[1]: https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$asyncValidators
[2]: https://github.com/angular/angular.js/wiki/Understanding-Scopes
