### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by speedsters** [angular/angular.js#16177]
userForm.email.$invalid is false for spswain.14@gmail  
Still, xxxx@xxx is a invalid email format. Please let me know. Thank you.

**Comment by gkalpak** [comment]
This is intentional. These emails are valid.

**Comment by speedsters** [comment]
@gkalpak please give me an example, as i had been asked to replace with regex. Examples of email xxxx@xxx

**Comment by frederikprijck** [comment]
E.g. somename@local would be valid. 

Ensure to read https://github.com/angular/angular.js/issues/16022#issuecomment-305097807 regarding an email address an it's validation.

**Comment by gkalpak** [comment]
Also, #14719 has some discussion as well as more info (and a lot of good resources) in the commit messages.
