### ISSUE TITLE
isArray and isString evalulation bug

### ISSUE THREAD

**Issue by Andersama** [angular/angular.js#16171]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

isArray and isString have issues handling an array of strings and/or referencing scope properties. At the moment it seems that when used from ng-show or ng-if the properties are transformed into strings which breaks the expected type checking behavior.

**Expected / new behavior:**

isArray and isString when used from ng-show or ng-if should evaluate the expression and leave it untouched.

**Minimal reproduction of the problem with instructions:**

http://plnkr.co/edit/rGDKCeol363kXf8V06UB

**AngularJS version:** 1.x.y

1.6.5 is the code I tested, however I've noticed this behavior in 1.6.x versions. 1.6.6 breaks the syntax of my example, however I'm fairly certain that the behavior is reproducible in the latest version.

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Anything else:**

Evaluate the object before transformations like .join() or .tostring() are used which would change the type of the object.

**Comment by thorn0** [comment]
Scopes don't have such methods as `isArray` and `isString`. For your code to work, you could add them:
```js
  $scope.isArray = angular.isArray;
  $scope.isString = angular.isString;
```

**Comment by gkalpak** [comment]
@thorn0 is right ([updated plnkr][1]).

[1]: http://plnkr.co/edit/hRBOV7MA5uku6DfmjqbY?p=preview
