### ISSUE TITLE
Suggested alternative for deprecated angular.merge doesn't behave exactly like the deprecated method.

### ISSUE THREAD

**Issue by absrd** [angular/angular.js#16187]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**

It's more a misguided suggestion in documentation. It is with regards to deprecation of angular.merge and the suggested alternative, Lodash.merge. Lodash doesn't handle defined keys with undefined values, i.e. if I have an object `a = {b: 1}` and merge it with another object ` Lodash.merge(a, {b: undefined})` then the result is `{b: 1}`, which would be `{b: undefined}` in angular.merge.

**Expected / new behavior:**

The alternative library should be as close to the deprecated method.

**Minimal reproduction of the problem with instructions:**

Look above.

**AngularJS version:** 1.x.y

**Browser:** all

**Anything else:**

Suggest another library, e.g: https://www.npmjs.com/package/deepmerge
I'm not associated with the above library other than I'm now using that instead of Lodash.

**Comment by frederikprijck** [comment]
Interesting, looks like it's idd not the same behavior, see: https://plnkr.co/edit/zVoIVIz52ZAUTUsN133T?p=preview

I guess this should be changed: https://github.com/angular/angular.js/blob/464dde8bd12d9be8503678ac5752945661e006a5/src/Angular.js#L426

Not sure `deepmerge` is the best approach as I'm not familiar with it so I can't realy tell.

**Comment by gkalpak** [comment]
I don't think we need a function that is 100% compatible with `angular.merge()`. Maybe we should make it more clear that we recommend using a similar (not identical) general purpose merge function and that `lodash.merge` is a popular example, not necessarily the "officially recommended" replacement.
