### ISSUE TITLE
Missing reference in ng-class documentation to binding a function 

### ISSUE THREAD

**Issue by maxchernin** [angular/angular.js#16183]
**I'm submitting a ...**

- [ ] bug report
- [ x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
The ng-class documentation refers to 3 expression evaluations.
however, you can pass a function expression which evaluates to any of the 3.
e.g. `ng-class="$ctrl.doSomething()"`

Since this is deprecated in Angular, there should be at least a mentioning that this is deprecated and users who would like to upgrade should stop using this.
there is also no reference to performance issues caused by using evaluated function expression.

**Expected / new behavior:**

documentation should add a recommendation that this usage is possible but should not be applied in case the app would be upgraded
also should add that this causes performance issues\memory leaks

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.5.0 ^

**Browser:** All [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:** id like to submit a PR

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
