### ISSUE TITLE
Possible to create some config json files that no build in js file?

### ISSUE THREAD

**Issue by abbymrs** [angular/angular.js#16186]
Hi,

Is it possible to create some config json files that not build in js file?
Now we use grunt + browserify to bundle and compress, and want to create some config json files to change some actions in angular app without building with js files, i.e: if we change the config json file, then we can hide/show some pages immediately.

Thanks.

**Comment by frederikprijck** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

--- 
You'll probably want to fetch the json file using `$http.get`, this allows to leave it out of your broserify bundle and also allows you to change the content without rebuilding.

**Comment by abbymrs** [comment]
Thanks, but `$http.get` not the way we want.

**Comment by frederikprijck** [comment]
@abbymrs I'm not sure what other way you can have to leave it out of your bundle. Anyway, this is not the place to ask these kind of things.

Note: `$http.get` works fine, it's what I'm using for a long time and does exactly what you want. Afaik there's no other, decent, way to achieve this.

**Comment by abbymrs** [comment]
@frederikprijck We will reconsider `$http.get` , thanks a lot!

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by abbymrs** [comment]
thanks
