### ISSUE TITLE
ngAnimate with Angular 1.4.3 giving error

### ISSUE THREAD

**Issue by adeelasghar88** [angular/angular.js#16191]
I am trying to add ngAnimate in my project but it is giving me error on console `angular-animate.js:4122 Uncaught TypeError: q.module(...).info is not a function`.

I am using Angular 1.4.3

What I did?
`bower install angular-animate`
index.html
`<script src="../bower_components/angular-animate/angular-animate.min.js"></script>`

Controller:
`angular.module('myApp.myController', ['ngAnimate'] `

Can someone please suggest me?

**Comment by frederikprijck** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
----
AngularJS doesn't support the usage of different versions between the different javascript files. Ensure `angular` and `angular-animate` are on the same version.

**Comment by Narretz** [comment]
It looks like you have mismatching version of angular and angular-animate. Make sure they all have the same version. How to ensure this is dependant on your package manager.
