### ISSUE TITLE
Installing angularjs NuGet package for my .Net Core 2.0 project doesnt appear to install the scripts

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [angular/angular.js#16198]
**I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Firstly does the angularjs nuget package support being installed in a .Net Core 2.0 project?  I just installed the package to my project and while the Nuget package is installed, the scripts did not actually appear anywhere for me to reference.

**Expected / new behavior:**
Installing the package should have added the angularjs scripts to my project

**Minimal reproduction of the problem with instructions:**
Latest version of visual studio 2017 (15.3.2)
Create new .Net core web project
Create empty project
Manage nuget packages
Search for angularjs and install it
The package is installed, but the scripts do no appear 

**AngularJS version:** 1.6.5

**Browser:** [all ]

**Comment by frederikprijck** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

----

>  does the angularjs nuget package support being installed in a .Net Core 2.0 

I guess it does.

But I don't think this repository has anything to do with package available on Nuget. You should probably contact the nuget package owners: https://www.nuget.org/packages/angularjs/

**Comment by Narretz** [comment]
We don't release the NuGet packages. You should report this with NuGet.
