### ISSUE TITLE
problem in sending POST body

### ISSUE THREAD

**Issue by raha1923** [angular/angular.js#16193]
i need to send a request using the ngResource in angular.
this request must be in the `POST` method and it's body must be right `{name: "mike", age: 14}` to the `http://there.com/api/user`.

i use the bottom codes to do this, but this codes doesn't send body.
```
	$scope.testRequest = $resource('http://there.com/api/user',
		null,
		{send: {method: 'POST'}}
	);

	console.log($scope.testRequest.send({}, {name: "mike", age: 14}));
```

**Comment by raha1923** [comment]
also i test `console.log($scope.testRequest.send({}, {name: "mike", age: 14}));` and still body doesn't send.

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
