### ISSUE TITLE
would be nice for <select> to support ng-size or size="{{expression}}" so we can set the size to the actual size for dynamic multiple selects

### ISSUE THREAD

**Issue by jstrachan** [angular/angular.js#1619]
I've tried 1.0.2 and it seems any expression of the form <select size="{{something}}" which just gets set to size="0". I ended up having to hack around this with jquery which made me feel dirty ;) so wondered if there was a way of just allowing a size expression to be specified (or even defaulting it as the ng-options knows the size).

e.g. something like this...

```
      <select id="attributes" ng-size="whatnot.length" multiple ng-multiple="true" ng-model="selectedThings" ng-options="foo for foo in whatnot"></select>
```

**Comment by jibwa** [comment]
+1 @caitp data-ng-attr-size worked fine.

**Comment by JonahJ** [comment]
+1
