### ISSUE TITLE
$q.all() promises are resolving first promise only

### ISSUE THREAD

**Issue by GokuSSL5** [angular/angular.js#16209]
**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
Issue is with $q.all(). 
I pass in an array of multiple $http.post() promise calls to $q.all(). In my case, they're all the same URL for a SendEmail function. The first one in the array works and fires off the email. The 2nd and all the other promise calls in the array fail with error:
data: "An asynchronous call is already in progress. It must be completed or canceled before you can call this method."
status: 500
statusText: "Internal Server Error"

**Expected / new behavior:**
The docs say that all the promise calls should resolve first before q.all() returns, so that's what I would expect. In my case, the URL is the same for each REST call since its a POST to an email endpoint. 

**Minimal reproduction of the problem with instructions:**

I can't do a pluker because this uses internal REST calls. 

**AngularJS version:** 1.x.y
v1.6.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE 11

**Anything else:**
controller looks like this:
					var promise = Files.sendEmailToMultipleAddresses("",to,body ,subject)
					promise.then(function(stuff){
						console.log(stuff);
					}
					,function(err){
						console.log(err);
					});

Service looks like this:
function sendEmailToMultipleAddresses(from, to, body, subject){
			// 'to' should be an array of recipients
			from = "noreply@company.com";
			var arryEmails = [];
			var urlTemplate = "http://company.com/IntranetServices/Company.svc/SendEmailOnBehalfOf";
			var config = {
				headers :  {
					'content-Type': 'application/json'
				}
			};			
			if(to.length>0){
				for(var i =0; i< to.length;i++){
					arryEmails.push(
					$http.post(urlTemplate,
					JSON.stringify({
						from: from, 
						to: to[i], 
						body: body, 
						subject : subject 
						}),
					config));
				};// End of For
				return $q.all(arryEmails)
				.then(function(results){
					return JSON.stringify(results);
					console.log("Emails sent: " + results);		
				},function(err){
					console.log(err);
					return err;
				});
			};// End of If
		}// End of Function

**Comment by Narretz** [comment]
$q.all immediately rejects the derived promise when one of its promises is rejected. Same as normal Promise API: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

This happens in your example.

 The 500 error from your server is also not an AngularJS problem.

**Comment by GokuSSL5** [comment]
Yea, I did some more research and found out the error was because of the server's .net command for sending smtp email on the web api side. The web api can only handle one SendEmail command at a time and has to wait for that first one to complete before hitting it for another "SendEmail" command.
