### ISSUE TITLE
Offensive language in documentation

### ISSUE THREAD

**Issue by zsiegel92** [angular/angular.js#16201]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

Offensive, backwards language in documentation for ngChecked! The words "slave" and "master" are used offhandedly. This term was dropped for "database followers", and should be dropped from web development lingo altogether. How do you expect Black developers to feel upon using this documentation? If you are Black, can you answer for all Black folks? If not, please consider the question rhetorical!

**Expected / new behavior:**

Change the words "slave" and "master" to "leader" and "follower" in this documentation.

**Minimal reproduction of the problem with instructions:**

See documentation at https://docs.angularjs.org/api/ng/directive/ngChecked

The example at the end is: 

    <label>Check me to check both: <input type="checkbox" ng-model="master"></label><br/>
    <input id="checkSlave" type="checkbox" ng-checked="master" aria-label="Slave input">

**AngularJS version:** 1.x.y

It is present.

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers.
**Anything else:**

Please change this as soon as is possible. Thank you so much. I love angular, I love the documentation, I love everything that you all do, and am extremely grateful. I hope you continue to impress me with grace in this case. Thank you always.

**Comment by petebacondarwin** [comment]
Happy to oblige @zsiegel92.
Thanks to @frederikprijck for the PR.
Closed via #16202

**Comment by zsiegel92** [comment]
Thank you! I am hopeful in the engineering community.

Best wishes.
