### ISSUE TITLE
Nested directives and API when scope is declared (breaking angular modules like angular-ui-tree) 

### ISSUE THREAD

**Issue by dgasparri** [angular/angular.js#16208]
**I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
When scope is declared, nested directives (that is, directives inside another directive's template) cannot call functions on the "main" controller, not even with the '&' symbol.

The function is not defined in the scope, and AngularJS goes into a loop trying to find the function.

 
**Expected / new behavior:**
The behavior of a directive should be unaffected by where it is placed. 

If I have a directive `<input-box>` and a directive `<submit-button>`, the latter should work both if placed inside the input-box template, or outside of it. 

Either make the directives "transparent" to child directives, or implement a method to "cascade" the api calls.
 

**Minimal reproduction of the problem with instructions:**
See example here: https://plnkr.co/zchRzM

**AngularJS version:** 1.6.4

**Browser:** 
Chrome - but it should not be browser dependent

**Anything else:**

**Comment by frederikprijck** [comment]
This is working as expected, here's a plunkr which does allow you to do what you want: https://plnkr.co/edit/7M9VVoe39TrOBZFGLKOy?p=preview

When using an `isolated` scope, you can not access anything from the parent scope. This has nothing to do with nested directives.

**Comment by dgasparri** [comment]
Thank you Frederik, that works as intended.

This "upward chaining" of function calls is not really documented. I didn't find any explanation in: 

https://docs.angularjs.org/guide/scope
https://docs.angularjs.org/guide/directive#isolating-the-scope-of-a-directive

Maybe we could propose a change to the documentation to make it more intuitive.

Just to be sure, can you confirm that I got it right?

```HTML
<outer outer-function>
    whose template contains a
        <middle middle-function>
            whose template contains a
                <inner inner-function>
```
We have 

  outerController
  outerDirective with scope: { outerFunction: '&' }

  middleController
  middleDirective with scope: { middleFunction: '&' }

  innerController
  innerDirective with scope: { innerFunction: '&' }

and in the parent controller, there's a function 

` $scope.innerButtonPressed(valueOfButton);`

## PLAIN CALLING

```HTML
<inner inner-function="innerButtonPressed(valueOfButton)"></inner>
```

## NESTED CONSTRUCT:

```HTML
<outer outer-function="innerButtonPressed(valueOfButton)"></outer>
```

and in outerTemplate:

```HTML 
    <middle middle-function="outerController.outerFunction({valueofButton: What goes in here? })"></middle>
```

and in middleTemplate:

```HTML
        <inner inner-function="middleController.middleFunction({valueofButton: 'PRESSED'})"></inner>
```


Is there a clever way for the middle-function to pass a value without having to declare a function in the middleController? 


(as I moved part of the tree inside directives with isolated scope, angular-ui-tree started to throw an exception "TypeError: scope.beforeDrag is not a function at dragStart (angular-ui-tree.js:800)". And indeed, there's no beforeDrag declared in the scope.  I'll look at it considering what you just told me to see if it's linked, and in case I'll post an example).

**Comment by dgasparri** [comment]
I managed to recreate the angular-ui-tree error

Dragging not working, and scope.beforeDrag undefined exception https://embed.plnkr.co/HBDimNwC3eBV1RC70vha/

**Comment by frederikprijck** [comment]
@dgasparri This is unrelated to the issue you logged above. The main difference here is that the `ui-tree-node` does not make use of an isolated scope, hence it does have access to the function on parent scope.

Here's a working plunkr: https://plnkr.co/edit/nBIp6jErstSw0dBzzN90?p=info

All I did was change the

**Comment by Narretz** [comment]
Looks like this resolved. Thanks @frederikprijck for the answers.
Please open a new issue if there's indeed a bug here.
