### ISSUE TITLE
**Feature Request** CLI for angularjs

### ISSUE THREAD

**Issue by icenold** [angular/angular.js#16204]
**Feature Request**
Can we give the same love to angularjs as much as angular2+?

It would be good to have a cli for angularjs that can have commands like 'build', 'g component', 'g factory'

**Comment by Narretz** [comment]
We don't have the capacity for this, and I think that in contrast to Angular, the benefits of a CLI wouldn't be that huge, because AngularJS doesn't have an involved build / pre-compile step.
