### ISSUE TITLE
angularjs.org and subdomains down

### ISSUE THREAD

**Issue by GrosTon1** [angular/angular.js#16205]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] other (Please do not submit support requests here (see above))

**Current behavior:**
Accessing "angularjs.org" and his subdomains returns ERR_CONNECTION_TIMED_OUT

**Expected / new behavior:**
Accessing "angularjs.org" and his subdomains should load correctly the appropriate website

**Minimal reproduction of the problem with instructions:**
Try to access "angularjs.org" or any subdomain in any navigator

**AngularJS version:** 1.x.y
N/A

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Anything else:**
http://isup.me/angularjs.org

**Comment by Narretz** [comment]
Until we get it back up:

Master Docs:
https://code-angularjs-org-338b8.firebaseapp.com/snapshot/docs

Code:
https://code-angularjs-org-338b8.firebaseapp.com/

**Comment by petebacondarwin** [comment]
It could be related to this network issue: https://status.cloud.google.com/incident/cloud-networking/17002

**Comment by GrosTon1** [comment]
@Narretz The docs were working fine when you linked it, but it's not anymore and instead shows {{ variables }}, pinged you just to let you know.

**Comment by Narretz** [comment]
@GrosTon1 not sure where you are seeing this. Did you maybe switch from master docs to tagged docs version? Because these are linked back to code.angularjs.org and won't work.
Other possible cause is maybe that the connection for a single file timed out.

**Comment by GrosTon1** [comment]
@Narretz I was seeing this from the direct link you commented, my co-workers were also seeing this, didn't checked if I got 404 but it's back now.

**Comment by Random90** [comment]
Main site is not working for me, neither the docs, but [https://material.angularjs.org/](https://material.angularjs.org/)  is working. Strange

**Comment by Narretz** [comment]
@GrosTon1 I think this is because this backend has problems handling the requests. Unrelated to the outage.

**Comment by petebacondarwin** [comment]
It looks like it was the Google Load Balancer outage that caused the failures. The sites are back up now. Sorry for any problems this caused you all.
