### ISSUE TITLE
Why angular-translate-loader-url.js v2.7.2 uses a .success and .error as they are depreciated?

### ISSUE THREAD

**Issue by muzammil90** [angular/angular.js#16217]
angular-translate-loader-url.js uses .seccess and .error in its http call which causes an error. Is it a bug or I am doing some thing wrong. I have update these to "then" and error removed and everything works fine.

**Comment by gkalpak** [comment]
This repo is for the core AngularJS project (which `angular-translate` is not a part of). Please, reopen on https://github.com/angular-translate/angular-translate.

**Comment by muzammil90** [comment]
I cant reopen this issue as it is not closed by me.

**Comment by gkalpak** [comment]
I meant, you should open an identical issue on the correct repo (https://github.com/angular-translate/angular-translate) :smiley:

**Comment by muzammil90** [comment]
oh ok thanks, I am new to github :)
