### ISSUE TITLE
How to use openXML in Node and Angularjs hybrid Application

### ISSUE THREAD

**Issue by dinesh93** [angular/angular.js#16213]
Hi,
I am new in Development, I am working in nodejs and angularjs Hybrid application.

I want to to view or Read a Office document in an application.

I got some Know information from outside. Using OpenXML we can able to read these documents.

Can any one please Suggest me How to use OPENXML in the application 

Thanks
Dinesh

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by dinesh93** [comment]
@Narretz  Okay Thanks
