### ISSUE TITLE
not working on ie 11

### ISSUE THREAD

**Issue by s-senguttuvan** [angular/angular.js#16229]
HTML1300: Navigation occurred.
File: prototype
SCRIPT1028: Expected identifier, string or number
File: angular.js, Line: 4118, Column: 3
SCRIPT5009: 'angular' is undefined
File: event.min.js, Line: 7, Column: 26
--------------------------------------------------------
line:4118
---------------------------------------------------------
     // Support: IE11
    // Do not `return this` to simulate the partial IE11 implementation
  },
  delete: function(key) {
    key = this._transformKey(key);
    var idx = this._idx(key);
    if (idx === -1) {
      return false;
    }
    this._keys.splice(idx, 1);
    this._values.splice(idx, 1);
    this._lastKey = NaN;
    this._lastIndex = -1;
    return true;
  }
};

only on ie11 ,others works fine help me

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
