### ISSUE TITLE
$locationChangeStart triggers twice

### ISSUE THREAD

**Issue by dhisharma** [angular/angular.js#16220]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

$locationChangeStart  event is triggering twice.
this is my code:--

(function () {
    "use strict";

    var appRoot = angular.module("app.top");
    appRoot.directive('confirmationOnExit', ['$location', 'ConfirmModal', '$timeout', '$location', function (location, ConfirmModal, $timeout, $location) {
        return {
            link: function ($scope, element, attrs, ctrl) {
                $scope.next = "";
                $scope.$on('$locationChangeStart', function (event, next, current, e) {
                    $scope.next = next;
                        $scope.DirtyForm = ($scope.componentAddForm.$dirty ? $scope.componentAddForm.$dirty : $scope.resourceForm.$dirty)
                        if ($scope.DirtyForm) {
                                event.preventDefault();
                                ConfirmModal.show({
                                    okButtonCaption: "OK",
                                    cancelButtonCaption: "Cancel",
                                    title: "Pending Changes",
                                    text: "Any unsaved data to this record will be lost. Click ‘Continue’ to proceed with this action."
                                }).then(function () {
                                    event.preventDefault();
                                    $timeout(function () {
                                        window.location = next;
                                        $scope.$apply()
                                    });
                                })
                            } else {
                            };
                });         
            }
        };
    }]);
})();

**Expected / new behavior:**

It should trigger once and after completing it should stop.

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.4.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by gkalpak** [comment]
I can't reproduce it with your code. There is probably more to it. What are the values of `next` and `current` for each event?

**Comment by dhisharma** [comment]
Its Fixed,  thanks

**Comment by Ranjan3355** [comment]
Hi @dhisharma ,
Can you please provide the fix here. Thanks
