### ISSUE TITLE
Error while Running npm start

### ISSUE THREAD

**Issue by jabbar86** [angular/angular.js#16228]
$ npm start

> angular@1.0.0 start C:\Users\Jabbar Memon\Downloads\Angular-2-Tutorials-master\Template
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/@angular/core/index.d.ts(26,1): error TS1128: Declaration or statement expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jabbar Memon\AppData\Roaming\npm-cache\_logs\2017-09-15T06_58_41_281Z-debug.log

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular 2. Please open in the Angular 2 [repository](https://github.com/angular/angular/issues). This repo is only for AngularJS.

It also looks like a very old Angular version (1.0.0), so you should make sure that you are using an up-to-date tutorial. If it's not an official tutorial, you must contact the original author.
