### ISSUE TITLE
Issue with Bullet Points (unordered lists)

### ISSUE THREAD

**Issue by soniurvashi11** [angular/angular.js#16230]
**I'm submitting a ...**
- bug report

**Current behavior:**
Following steps must be followed to reproduce the bug -

1. Click inside the writing area/ text area of the text-editor.
2. Type something inside the area.
3. Remove whatever you typed.
4. Now click on the unordered-list toolbar.
5. You will get two bullet points instead of one.(though the text area is empty).
6. Type something inside the area.
7. Remove whatever you typed.
8. Now click on the unordered-list toolbar.

> You will get two bullet points instead of one.(though the text area is empty).

**Expected / new behavior:**
When you click on unordered-list toolbar when area is empty or without any bullet-points, only one bullet point must be shown at a time.

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.3

**Browser:**
All

**Comment by gkalpak** [comment]
It i notcler what you are referring too. Probably some 3rd-party rich editor component. In any case, it is not something that is part of the core AngularJS project (i.e. this repo).

Try identifying what is the repository/issue tracker for the particular component you are using and post an issue there. (If you need help identifying that, feel free to ask for help on one of the [general support channels][1].)

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by soniurvashi11** [comment]
My bad, post into wrong repository!
