### ISSUE TITLE
AngularJS asynchronous json messages browser header title shows untranslated key and then takes time to display actual value

### ISSUE THREAD

**Issue by kpat143** [angular/angular.js#16234]
**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

using $translateProvider with default language 'en' although body loads fine, browser header title is not resolving quickly and shows untranslated key as title and after few seconds the actual value of the key loads. Please let me know if there's a solution for this issue/bug.
**Expected / new behavior:**

The browser header title also should have shown the translated value similar to page body.
**Minimal reproduction of the problem with instructions:**

Use 
$translateProvider.useStaticFilesLoader(mention prefix and suffix details here);
$translateProvider.preferredLanguage('en');
**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome and Edge
**Anything else:**

**Comment by Narretz** [comment]
I assume you want to post this here: https://github.com/angular-translate/angular-translate
