### ISSUE TITLE
Allow module.run and module.config to accept multiple blocks in one call

### ISSUE THREAD

**Issue by jrencz** [angular/angular.js#16232]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

module.run and module.config currently accept single argument.
The only way to register many run/config blocks is to put many chained calls:

```js

angular.module('myModule', [])
  .config(someConfigBlock)
  .config(someOtherConfigBlock)
  .run(someRunBlock)
  .run(someOtherRunBlock)

```

**Expected / new behavior:**

I'm having an issue with number of run/config blocks in my app and the number of manual operations required to add another if needed.
I'm using ES modules and the approach I decided to take assumes that there's one ES6 module for each run/config block.
Recently I decided to start using [novemberborn/babel-plugin-import-glob](https://github.com/novemberborn/babel-plugin-import-glob) to reduce overhead required to add another run/config block module so that I could be able to write something like:

```js
import * as configBlocks from './lib/**/*.config.js';
import * as runBlocks from './lib/**/*.run.js';
```

exemplary `configBlocks` created by the plugin is:

```js
{
  someKeyDerivedFromFileName: runBlockFunctionBeingTheDefaultExportOfMatchingFile
  ...
}
```

If no module is matched then the dictionary is empty.

The objective of such approach is to be able to limit number of manual operations required to add new run block to exactly 1: create new module named properly. 

I'm aware that this particular example it depends heavily on a non-standard babel extension, but I'd like to put the idea under discussion anyway (see other syntax variants below)

I thought of a possibility to pass just that dictionary I described above right to `module.run`/`module.config`

```js
import * as configBlocks from './lib/**/*.config.js';
import * as runBlocks from './lib/**/*.run.js';

angular.module('myModule', [])
  .config(configBlocks)
  .run(runBlocks)
```

Other possible syntax would be to pass many functions as consecutive positional parameter of `module.run`/`module.config` like this:

```js
const configBlocks = [
  function () {},
  function () {},
  function () {},
];
const runBlocks = [
  function () {},
  function () {},
  function () {},
]

// either
angular.module('myModule', [])
  .config(configBlocks)
  .run(runBlocks)

// or
angular.module('myModule', [])
  .config(...configBlocks)
  .run(...runBlocks)
```

**Minimal reproduction of the problem with instructions:**

n/a

**AngularJS version:** 1.6.6

**Browser:** irrelevant

**Anything else:**

I thought of achieving described behaviour with current api but it needs a helper for defining modules (one of possible implementations):

```js
import * as configBlocks from './lib/**/*.config.js';
import * as runBlocks from './lib/**/*.run.js';

const defineAngularJsModule = (name, dependencies, {
  runs = {},
  configs = {},
} = {}) => {
  const module = angular.module(name, dependencies);

  Object.values(configs).forEach(configBlock => {
    module.config(configBlock);
  });

  Object.values(runs).forEach(runBlock => {
    module.run(runBlock);
  });
  
  return module
}

defineAngularJsModule('myModule', [], {
  runs,
  configs,
})
```

I'm using a helper like this for now, but I thought it might be a good idea to expand the api - it may be inspiring for others

**Comment by Narretz** [comment]
Hmmm

Pro:
- we already have overloads for other module() apis, e.g. directive, component

Contra:
- the overloads are not consistent, e.g. there are none for the provider varieties
- The helper is so straightforward that I don't think it's necessary to provide this in core
- The requirement isn't very frequent (yet)

**Comment by jrencz** [comment]
ok: the 1st of array-based syntaxes I suggested collides with annotated function syntax so it has to be ruled out instantly. So: only spread stays on table

**Comment by jrencz** [comment]
The syntax accepting dictionary loosens control over the order of registered run blocks which may be a problem. The multi-argument syntax does not seem to have this flaw.

**Comment by Narretz** [comment]
Closing as it's too infrequently needed and can be accomplished with a helper outside core.
