### ISSUE TITLE
[1.6.5] ngModel sets value undefined on input number more granular than input step

### ISSUE THREAD

**Issue by douglasg14b** [angular/angular.js#16231]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
When a number input has it's `step` set, any values more granular than the step are set as undefined in the `ngModel`

**Expected / new behavior:**

I expected that I would get a `0.5` in my model, which I could then validate. Instead the value is no longer defined.

**Minimal reproduction of the problem with instructions:**

Set an input to number, and `step` to `1` then type on `0.5`.

Example:

https://jsfiddle.net/9w0bztt7/

**AngularJS version:** 1.6.5

**Browser:** [Chrome 60.0 ]

**Anything else:**

Related to: https://github.com/angular/angular.js/issues/15257 ?

**Comment by gkalpak** [comment]
This is by design. When you use `step` there is a new validator that checks whether the value is valid based on the minimum and the step. And by default, `ngModel` will set the model value to undefined if there are validation errors.

See #16218 for a more in-depth expalnation and work-arounds.

**Comment by douglasg14b** [comment]
@gkalpak 

I don't really want a custom-validator on the field for step, I just want to value in my model regardless of input so I can then validate it there. Is that possible?

**Comment by Narretz** [comment]
you can set  `ng-model-options="{ allowInvalid: true}"` and then the invalid value will be set on your model.

**Comment by gkalpak** [comment]
> I don't really want a custom-validator on the field for step, I just want to value in my model regardless of input so I can then validate it there. Is that possible? I still want the stepping the vanilla input field has, without angular trying to validate it.

Quoting myself:
> See #16218 for a more in-depth expalnation and work-arounds.
