### ISSUE TITLE
ng-bind is working fine but {{}} doesn't 

### ISSUE THREAD

**Issue by zyc017** [angular/angular.js#16243]
in my code , {{}} doesn't display the value ,but ng-bind works ,even it does't occur every time,any idea help?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
