### ISSUE TITLE
how to render two or more components on an SPA App with angularJS 1.6

### ISSUE THREAD

**Issue by dcu-sharepoint** [angular/angular.js#16248]
**I'm submitting a ...**
- [X] Question
**Current behavior:**

I'm unable to render two or more components on a single page

**Expected / new behavior:**
my expected behavior is for each component to render on the page based on CSS positioning

        <div layout="column">
            <main-page />
            <page-one /> 
        </div>

**AngularJS version:** 1.6.4
`module myApp{
   
    export class MainPageController {
        static $inject = ['mainPageService']; 
        constructor(public mainPageService: MainPageService) {  }
    }
    /*
    **  Register the component for use
    */
    let componentOptions = {
        controller:     MainPageController,
        controllerAs:   'vm',
        templateUrl:    './src/html-views/page-header.html'
    }
    angular.module('myApp').component('mainPage', componentOptions);
}
module myApp{
    export class PageOneController {
        static $inject = ['pageOneService'];
        constructor(private pageOneService: PageOneService) { }
    }
    /*
    **  Register the component for use
    */
    let componentOptions = {
        controller  :   PageOneController,
        controllerAs:   'vm',
        templateUrl :   './src/html-views/pageOne.html'
    }
    angular.module('myApp').component('pageOne', componentOptions);
}
`

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**
have read the docs but can't find anything related to this issue.

Any help is greatly appreciated.

Thank you

**Comment by frederikprijck** [comment]
Custom components are **not** self closing, you need to use:

```
<main-page><main-page/>
<page-one><page-one/> 
```

But your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by petebacondarwin** [comment]
@frederikprijck - I think you meant:

```
<main-page></main-page>
<page-one></page-one> 
```

But yes, thanks for dealing with this.

**Comment by frederikprijck** [comment]
Oops, sorry ... Updated!

**Comment by dcu-sharepoint** [comment]
thank you all; re-install all of my software in the project and that solved the problem;
