### ISSUE TITLE
Cant empty my form

### ISSUE THREAD

**Issue by Gawdadi** [angular/angular.js#16244]
my code is :

function addCallCenterEmployee($scope, swaggerService, $state, $cookies, $rootScope,$mdDialog,toastr,apiBase,$filter,$q ,$mdMedia,utilityService,mixService){
      
          console.log('addcallcenter');
          $scope.employee = {};
          $scope.user = {};
          $scope.isLoading = false; 
.
.
.
if(data.obj.success===true) {                
                    $scope.employee= {};
                    $scope.user ={};
                    $scope.isLoading = false;
                    alert("added");

$scope.employee=={}; not working after the vale is true.Nor $scope.user ={};. Alert is working fine but fields of my form are still their.

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
