### ISSUE TITLE
scope not updating

### ISSUE THREAD

**Issue by bcheriyan1** [angular/angular.js#16257]
**I'm submitting a ...**

- [x] bug report

**Current behavior:**

**Expected / new behavior:**

Value should be updated when changes comes 

**Minimal reproduction of the problem with instructions:**

scope is not updating in wdk modal window. I use Angularjs1.5.5 with ui-bootstarp (1.3). Inside wdk modal window I have called bootstrap modal window ($uibModal ), Inside bootstrap modal window  there is a button to set a value depending on selected value from html multi select box. The issue is the value not updated on view. If we console or inspect we can see that value. But in user view it will not show up. This issue only inside wdk modal window. 
If anyone face this issue and found a solution for this please let me know. 

Is it possible to integrate angular with wdk?? 

**AngularJS version:** 1.5.5

**Browser:** IE 11 and below

**Anything else:**

**Comment by petebacondarwin** [comment]
Please clarify what WDK is - a link would be useful. Even better a Plunker that demonstrated the problem would be ideal.

**Comment by bcheriyan1** [comment]
Web Development Kit (WDK) [wdk](https://developer-content.emc.com/developer/what_is_a_wdk_component.html)

**Comment by petebacondarwin** [comment]
Link to this modal window component?

**Comment by bcheriyan1** [comment]
Its in my local server not yet published

**Comment by petebacondarwin** [comment]
I'm sorry without more information it is impossible to help with this issue.
