### ISSUE TITLE
Uncaught TypeError: angular.module(...).info is not a function     at angular-messages.js:275     at angular-messages.js:740 (anonymous) @ angular-messages.js:275 (anonymous) @ angular-messages.js:740

### ISSUE THREAD

**Issue by 1993Aniket** [angular/angular.js#16258]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by 1993Aniket** [comment]
what is this error?

**Comment by frederikprijck** [comment]
You have to ensure all AngularJS libraries are using the same versions, it's not supported to combine (for example) 1.4 of ngAnimate with 1.5 of ngRoute.
