### ISSUE TITLE
Able to use ES6 classes for Angular 1.x components

### ISSUE THREAD

**Issue by piller187** [angular/angular.js#16252]
**I'm submitting a ...**

- [ ] bug report
- [ x] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
We can use a class for a service or controller. Would be nice to be able to use a class for component as well. This would probably help people migrate to Angular 2 as well as the syntax (even though it's Typescript in Angular 2) could be similar.

**Expected / new behavior:**
The feature would make Angular 1.x seem more object oriented. For me I use C# for my back-end so it's easier if the front-end looks similar with classes.

**Anything else:**
I'm not 100% sure it would play out but something from a users point of view like:

```
class TestComponent {
	constructor() {
  }
}
app.component("testComponent", TestComponent);

```

Example of using classes for the other things:

https://jsfiddle.net/gtrwzsn1/299/

**Comment by frederikprijck** [comment]
You can use classes for components, all you need to do is:

`app.component("testComponent", new TestComponent());`

**Comment by petebacondarwin** [comment]
I think you can go one step further and use a class type directly, as long as the properties are statics on the class:

```typescript
class TestComponent {
  static bindings = {
    value: '<'
  };
  static controller = TestComponentController;
  static template = 'test-component: {{$ctrl.value}}
}
```

and so on.

Also you could consider @Hotell's [ngMetadata](https://github.com/ngParty/ng-metadata) project.

**Comment by piller187** [comment]
OK, those are nice alternatives to just using 1 normal non static class. Ideally it would be just like you could use services or controllers but I understand why it's not. Consistency is just always nice.

**Comment by gkalpak** [comment]
For the record, there is nothing stopping  you from using the controller class itself for the static properties:

```ts
class MyTestComponent {
  static template = 'Hello, world!';
  static controller = MyTestComponent;

  $onInit() {
    console.log('onInit');
  }
}

.component('myTest', MyTestComponent)
```

The difference between directives and services/controllers is that directives require more statically available metadata. Services and controllers only require the identifier (e.g. the name), which is provided as the first argument. 

But for directives, we need other stuff, such as the `restrict`, `transclude`, `template`, `priority` values. Some of them might not apply to components, but some do, so you need to provide that metadata along with the component's controller constructor. (Note that the same is true in Angular, where you provide them via the `@Component(...)` decorator.)

##
So, you can either use a 3rd-party library (such as [ngMetadata][1]) to emulate the `@Component()` decorator, or provide the metadata in a static object (along with the controller constructor).

I tend to think of...

```js
{
  template: '...',
  bindings: { ... },
  controller: class MyTestComponent { ... }
}
```

...as the AngularJS equivalent of Angular's...

```ts
@Component({
  ...
  template: '...',
  inputs: [ ... ],
  ouputs: [ ... ],
})
class MyTestComponent { ... }
```

##
On top of that, you can use static fields on the controller constructor itself to provide the metadata (as proposed above), which is as close to service/controller registering as you can get.

I like to take it a step further and also provide the `selector` on the controller :grin::

```ts
class MyTestComponent {
  static selector = 'myTest';
  static template = 'Hello, world!';
  static controller = TestComponent;

  $onInit() {
    console.log('onInit');
  }
}

.component(MyTestComponent.selector, MyTestComponent)
```

[1]: https://github.com/ngParty/ng-metadata

**Comment by piller187** [comment]
Using the controller class itself (your first and last example) is brilliant! It makes more sense to me now that those properties are static since those are values that each component instance share, and it puts them all into one class which is great! Thank you for those examples!

**Comment by piller187** [comment]
Wait, it doesn't seem possible to define static class variables that way in ES6. So that doesn't work for me.

**Comment by gkalpak** [comment]
My examples were in TypeScript (which does support static properties). If you are using ES6, then you need to either define them as static getters (as you already found out) or attach them to the class itself:

```js
class MyTestComponent {
   ...
}
MyTestComponent.selector = '...';
MyTestComponent.template = '...';
MyTestComponent.controller = MyTestComponent;
```
