### ISSUE TITLE
Angular with jquery 

### ISSUE THREAD

**Issue by rainnaren** [angular/angular.js#16261]
I have done a project with bootstrap along with jquery and I decided to choose angular what is the major problem iam Gng to face.. Kindly reply to this post

**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
Hi!

Your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

---

AngularJS works abit different as to how jQuery apps are built. You probably want to ensure you have a decent knowledge of AngularJS (see the docs, examples, google, ...) and some of it's MVC concepts to limit the amount of actual `problems` you'll encounter during development. Nevertheless, this repo is not for these kind of support!
