### ISSUE TITLE
Random behaviour

### ISSUE THREAD

**Issue by Oliv** [angular/angular.js#16274]
Hello there,

I have an extranet app running in Angular 1.6.x and websockets.
It is a fairly big app, and the user experiences some random behaviours while using it.

### Problems

- Some popup templates show without variables replacements (staying like {{var}})
- Consistant app slowdown (around 10 or 20 seconds to execute an action), even just after a refresh.
- UI grid sometimes freezes while scrolling the list (around 7k lines shown).

### Context

There seem to be no pattern to reproduce them. 
They are using Chrome.

### What I have done

I can't reproduce any of this myself.
I found no consistant memory leaks.
Heap snapshot is around 24-35mo.
Heap peaks for heavy loops reach 100mo.
The server seems fine all the way.
Their internet connection seems fine, but they are testing with another one now.

### To conclude

I am running out of ideas to find a solution here. 
Do you guys have some hints for some more testing, or did you already experience this kind of behaviour ?

Best Regards, Olivier

**Comment by petebacondarwin** [comment]
Can you get them to report any messages in the browser console when their templates don't get rendered correctly? It might be worth talking to the developers of the ui-grid.
Can you get them to check what Chrome extensions they have installed. Sometimes these can affect performance, etc. They could try running the app in incognito mode if that is possible.

When you say consistent app slow down. Does it really happen consistently? If so then it ought to be reproducible on your side. Or at least the could let you remote onto their machine when this is happening to allow you to debug.

**Comment by Oliv** [comment]
They tried in incognito mode, but the same problems appeared, so no plugin guilty. 

When I say consistant slow down, I mean a big slow down, but still random.

I will try to have them send the console error and will keep this thread updated,
Regards, Olivier

**Comment by Narretz** [comment]
Does this only happen on pages where UI grid is included? Or is basically the app built around ui-grid? I feel like this is the biggest area where problems could happen. Are the popups part of the grid?

**Comment by Oliv** [comment]
ui-grid is included in all list pages (one by object category), but popups are not part of the grid.

I suspect the problem comes either from 8k entries ui-grid, or from the planning page, which is js heavy.
But what bugs me is that I can't reproduce the behaviour.

Theirs mac specs are : DDR3 4Go RAM, 1600MHZ.

**Comment by Narretz** [comment]
Maybe it's simply memory / CPU pressure that only shows if they have other pages / apps running? 
Are the popups custom coded or part of a lib?

Anyway, I begin to suspect that this is not a core issue.

**Comment by Oliv** [comment]
I am using angular-strap for popups.

Good idea, I will ask them how many tabs they have running

**Comment by Narretz** [comment]
I will close this issue, but you can update it when you have new information. Thanks for your understanding.
