### ISSUE TITLE
can i get any help

### ISSUE THREAD

**Issue by saisindhoor** [angular/angular.js#16280]
[problem.docx](https://github.com/angular/angular.js/files/1385968/problem.docx)
PS C:\Project> npm install -g @angular/cli
C:\Users\SAI BABA\AppData\Roaming\npm\ng -> C:\Users\SAI BABA\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
C:\Users\SAI BABA\AppData\Roaming\npm
`-- @angular/cli@1.4.7

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (curre
nt: {"os":"win32","arch":"x64"})
PS C:\Project> npm install -g @angular/cli
C:\Users\SAI BABA\AppData\Roaming\npm\ng -> C:\Users\SAI BABA\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
C:\Users\SAI BABA\AppData\Roaming\npm
`-- @angular/cli@1.4.7

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (curre
nt: {"os":"win32","arch":"x64"})

**Comment by frederikprijck** [comment]
I'm not sure what kind of help you're exactly looking for. However, it looks like you're using Angular, and not AngularJS.
Please note this repository is for AngularJS projects.

For assistance with Angular, you can always try https://gitter.im/angular/angular
For bugs/feature requests you can also try the Angular github repository: https://github.com/angular/angular. For specific issues regarding Angular-CLI, you might want to checkout https://github.com/angular/angular-cli .
