### ISSUE TITLE
issue with sanitizing input

### ISSUE THREAD

**Issue by nikitpatel24** [angular/angular.js#16295]
I am trying to secure my app by preventing xss attack. I used ng-bind-html directive with a div tag. Follwed all the ngSanitize guidelines. But still the div tag executes a script tag. With the sanitize library it should escape it.
This also happens to me when i used it with input tag along with ng-model.
I have attached a fiddle that explains the problem. 
Appreciate for your response

(https://jsfiddle.net/0c0ee472/21/)

**Comment by gkalpak** [comment]
This happens because (probably as part of how jsfiddle tries to escape your JS) the page breaks. So, you end up with something like:

```html
<head>
  ...
  <script type="text/javascript">//<![CDATA[
    var app = angular.module('myApp', ['ngSanitize']);

    app.controller('MainCtrl', function ($sce, $scope) {
      $scope.text = " <script>alert(222)
  </script>
  <script>alert(222)</script>
</head>
```

You can avoid that by using string concatenation and see `ngSanitize` work in this [updated demo][1].

<sub>Closing since everything works as expected.</sub>

[1]: https://jsfiddle.net/0c0ee472/23/

**Comment by nikitpatel24** [comment]
but i still have the same problem in my app. The user enters` <script>alert(1)</script>` instead of sanitizing, it script is executed.

**Comment by gkalpak** [comment]
I am pretty confident this is not a problem with `ngSanitize`, but possibly with how you use it. Still, there is not much we can do without a proper minimal reproduction.

**Comment by petebacondarwin** [comment]
@nikitpatel24 - maybe your app is suffering from the same problem as JSFiddle. I.E. that you are hard coding the script tags in your HTML, which is breaking the way the browser parses the HTML.

For example if you look at the source of the result from for your JSFiddle, you will see the following:

```
<script type='text/javascript'>//<![CDATA[

var app = angular.module('myApp', ['ngSanitize']);

app.controller('MainCtrl', function ($sce, $scope) {
    $scope.text = " <script>alert(222)</script> <script>alert(222)</script>";
});

//]]> 

</script>
```

You can see that the closing `</script>` after the `alert(222)` is actually closing the original script tag that contains the app code. This means that the second script tag is being executed by the browser  (and the final closing `</script>` tag is being ignored).
