### ISSUE TITLE
View template is not refreshing when model values got changes in angular 4

### ISSUE THREAD

**Issue by RajendraPrasadP** [angular/angular.js#16305]
model values are appending every time in the template when modifying the model,
but when I print the model in the console it is giving the updated values only, in view previous model values and new values both are showing.
How can I fix this issue. 
I am new to angular 4. Please help.

**Comment by frederikprijck** [comment]
@RajendraPrasadP This is the repository for angular.js (v1), you probably want to move your issue to the Angular (v2+) repository which can be found here: https://github.com/angular/angular

However, this reads more like a support question. You can ask support questions regarding Angular (v2+) here: https://gitter.im/angular/angular

**Comment by RajendraPrasadP** [comment]
@Narrez, By default it got created under AngularJS, I have raised the same in V2 repository. Thank you !!
