### ISSUE TITLE
String literals are not being assigned to a parent directive's isolate scope

### ISSUE THREAD

**Issue by simook** [angular/angular.js#16307]
**I'm submitting a ...**
- [ X] bug report

**Current behavior:**
When using two-way binding between directives, string literals are not being assigned to the parent directive's isolate scope when the child most scope has changed. However, when a change is made in the parent scope, those changes are correctly assigned to siblings and children scopes.

**Expected / new behavior:**
The expected behavior would correctly propagate the changes to all parent scopes when a string literal changes.

**Minimal reproduction of the problem with instructions:**
http://plnkr.co/edit/Jq7AvmRPaNfI8RaGqvTu?p=preview

In that plnkr, I have a working demo of the expected behavior using object literal types. Below that is the demo of the broken behavior using string literals.

**AngularJS version:** 
This issue exists in 1.5.x, 1.6.x, and in master.

**Browser:**  
I tested this in the latest stable builds of Chrome, Firefox, and Safari on OSX Seirra.

**Anything else:**
I'm first working on a spec test to isolate this issue and hopefully, I will be able to contribute back a fix. In the meantime, I would appreciate any insight or knowledge anyone has around the expected behavior of data being sharing between isolate scopes. I think I've isolated the issue to the compile.js file around line 3458 but I'm also unfamiliar with this area of the codebase and only have a couple hours invested into understanding the code.

**Comment by gkalpak** [comment]
You have fallen victim of Scopes' reliance on JavaScript's prototypal inheritance (in combination with that fact that `ngRepeat` creates a new scope for each repeated element). You can read more about Scopes and prototypal inheritance [here][1].

In a nutshell, here is what's happening:

```js
// In controller:
this.items = [...];
```

```html
<!-- In template: -->
<input ng-repeat="item in $ctrl.items ..." ng-model="item" />
```

`ngRepeat` will create a new scope and `ngModel` with two-way-bind to that scope's `item` property. Updating the input value will change the `ngRepeat` child scope, but there is nothing to map that change back to the `items` array.

You can achieve what you want by binding to the `items` array directly:


```html
<input ng-repeat="item in $ctrl.items ..." ng-model="$ctrl.items[$index]" />
```

Here is an [updated demo][2].

[1]: https://github.com/angular/angular.js/wiki/Understanding-Scopes
[2]: http://plnkr.co/edit/TiKGFJ2p9y7Ylj08g7Wx?p=preview
