### ISSUE TITLE
using ng-src Image and ng-submit  is not loaded in IE broswer but mozila and chrome its working working fine 

### ISSUE THREAD

**Issue by pawanupr16** [angular/angular.js#16300]
if i use

in controller i use assign
img ng-src="{{titleimage}}
$scope.titleimage="img/abc.png"

Mozilla and chrome working fine
but in IE its not loading image please suggest me what should i do

**Comment by frederikprijck** [comment]
@pawanupr16 You probably want to elaborate a bit more when creating issues, there's not much one can do with so little (there's even no description) information.

However, your issue reads like a support question / general question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by pawanupr16** [comment]
if i use
<img ng-src="{{titleimage}}">
in controller i use  assign

 $scope.titleimage="img/abc.png"

Mozilla and chrome working fine 
but in IE its not loading image please suggest me what should i do

**Comment by frederikprijck** [comment]
I'm sorry, this repository is only for bug reports and feature requests, please try one of the channels listed in the link I mentioned above (and provide a reproduction sample).
