### ISSUE TITLE
#IE 11 links transition color issue

### ISSUE THREAD

**Issue by lycan2017** [angular/angular.js#16301]
I am facing issue in Internet explorer related to links transition style. 
When a link is clicked, color of that link should be changed. I have used :visited class for that. It works perfectly in chrome and Mozilla but in IE its not working.
I have searched for behavior but didn't got anything reasonable. please find plunker for this 
http://plnkr.co/edit/jJ6i5765ir57YbcaF6pX?p=preview

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
