### ISSUE TITLE
Weird, not consistent result when multiplying in ng-value

### ISSUE THREAD

**Issue by ZinaEhr** [angular/angular.js#16309]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (see above))

**Current behavior:**
While multiplying ng-model by 10 or 100 to get ng-value, most numbers behaves normally, but 0.07 * 100 gives a weird result. and 0.07 * 10 and  0.09 * 10 too.  

**Expected / new behavior:**
Expected 0.07 * 100 to result 7 but it results 7.0000001

**Minimal reproduction of the problem with instructions:**
https://www.w3schools.com/code/tryit.asp?filename=FL2PHQACK2K0

**AngularJS version:** 1.x.y
I tried 1.5.5 and 1.6.4 

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, IE, and FF

**Anything else:**

**Comment by petebacondarwin** [comment]
This has nothing to do with AngularJS. It is a feature of the floating point number system that JavaScript uses. See http://plnkr.co/edit/UxjGxTq5R4oQq3cck4ht?p=preview
