### ISSUE TITLE
GUIDE FOR FILLING AND SELECTING THE COMBOBOX(ANGULARJS)

### ISSUE THREAD

**Issue by ramezani583** [angular/angular.js#16302]
Hello,
To use Combobox, radiobutton and checkedlistbox in web project(angular JS ), I need a sample (fill data and select the row for edit mode)
Can you provide * .js and * .cshtml samples for me?
Thank you for providing guidance.

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
