### ISSUE TITLE
Not able to bind ng-repeat values in my custom directives?

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular.js#16313]
Hi,

I have created custom-directive called **_displayId_**. Using ng-repeat rendered custom-directive and bind id from ng-repeat data. Unfortunately not able to get id of element within custom directive.

        app.directive('displayId', function(){
              return {
                      restrict: 'EA',
                        compile: function(element){
      	                      alert(element.attr("id"));  //id displaying as op.id
                         }
             };
            });`

find the issue reproducible plnkr below.

https://plnkr.co/edit/3a8HBApCtbmYlGIfWyzM?p=preview

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

**Comment by AbinayaSubbiah** [comment]
@Narretz  yes i have tried and i can get id of element but can't view id in my dom element.

      app.directive('displayId', function(){
    return {
      restrict: 'EA',
      compile: function(){

        return {
          pre: function ($scope, $elm, $attrs) {

          },
          post: function ($scope, $elm, $attrs, controllers) {
            console.log($elm);
          }
        }

      }
    };
     });


 i m getting element as like `<display-id id="{{op.id}}"> </display-id>` but i need like `<display-id id="Title1"> </display-id>` how to achive this at sample side
