### ISSUE TITLE
How to restrict an exe file from uploading without considering its extension using angularjs and java.

### ISSUE THREAD

**Issue by JanKrish** [angular/angular.js#16318]
How to restrict an exe file from uploading without considering its extension using angularjs and java.Is there any std lib function?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
