### ISSUE TITLE
File Upload Time Angular Error

### ISSUE THREAD

**Issue by venkatsamuthiram** [angular/angular.js#16323]
**AngularJS version:** 1.6.6
**Browser:** [ Version 62.0.3202.62 (Official Build) (64-bit) 

**Current behaviour:**
  `xhr.send(isUndefined(post) ? null : post);` 

> I got this error While I upload my File. Anything I Missed my Code?

**Doc block Mentioned**
```
@description
* HTTP backend used by the {@link ng.$http service} that delegates to
* XMLHttpRequest object or JSONP and deals with browser incompatibilities.*
* You should never need to use this service directly, instead use the higher-level abstractions:
* {@link ng.$http $http} or {@link ngResource.$resource $resource}.
*
* During testing this implementation is swapped with {@link ngMock.$httpBackend mock
* $httpBackend} which can be trained with responses.
```

**suggestions how to fix??**

**Comment by frederikprijck** [comment]
@venkatsamuthiram What kind of error are you talking about? You probably want to add more information.

Keep in mind, this github repo is only for bug reports and feature requests (regarding AngularJS). Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). But keep in mind, if you need some assistance it's a good idea to provide some clarification to what you're experiencing.

**Comment by venkatsamuthiram** [comment]
@frederikprijck 

> Angular Function name createHttpBackend, This function not passed below that line (mentioned below). And also Not getting any error exception, Then only I posted my issue here. 

**I did not get any exception.**
I Guessing $http response undefined?

`xhr.send(isUndefined(post) ? null : post);`

May I ask you one? How I fixed this issue can you suggest me?  how to find out that error?

**Comment by frederikprijck** [comment]
I have no clue what problem you are facing.

Anyway, move to the appropriate channel to get support, as mentioned above.

**Comment by jthemaster** [comment]
hi @venkatsamuthiram, i have a similar problem, if your fixed it, could you tell us?

**Comment by 18853477039** [comment]
I also have a similar problem who can help me? It's work well in the production, but error locally

**Comment by vgalejandro** [comment]
> I also have a similar problem who can help me? It's work well in the production, but error locally

I had this exact problem on a laravel+angularjs project.... turns out i just had to enable debug on laravel .env to be able watch the full error (in my case a missing sql table in my local db)
