### ISSUE TITLE
Tour of Heros Issue

### ISSUE THREAD

**Issue by phishncode** [angular/angular.js#16322]
I'm not sure where I should put this.  If someone knows a better place I just want to save some noobs a little time and frustration :-)

ERROR in src/app/heroes/mock-heroes.ts(1,22): error TS2307: Cannot find module './hero'.

import { Hero } from './hero';
should be 
import { Hero } from '../hero'; <- this is referring to heros in the parent directory

![image](https://user-images.githubusercontent.com/2036042/32529948-32605e08-c3f0-11e7-807f-0621e2517222.png)

ERROR in src/app/heroes/heroes.component.ts(3,24): error TS2307: Cannot find module '../mock-heroes'.

import { HEROES } from '../mock-heroes';
should be
import { HEROES } from './mock-heroes'; <-- referring to the mock data array inside the component itself

![image](https://user-images.githubusercontent.com/2036042/32530008-7db11d16-c3f0-11e7-8e94-ff769a02bca2.png)

**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

tutorial does not compile
**Expected / new behavior:**

tutorial should compile

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

5
**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular. Please open in the [ Angular repository](https://github.com/angular/angular/issues). This repo is only for AngularJS. Thanks!
