### ISSUE TITLE
$transclude() commenting out ng-repeat in transcluded source

### ISSUE THREAD

**Issue by hernan-almeida** [angular/angular.js#16321]
**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
When using $transclude() in the directive function to obtain the source html, ng-repeat is coming in commented out. This doesnt seem to be a problem when using ng-transclude.

**Expected / new behavior:**
$transclude() exposes source html without making any changes.

**Minimal reproduction of the problem with instructions:**
Source html using tabs directive:
```html
<tabs>
    <div class="panel">
        <div class="panel__title">Tab 1</div>
        <div class="panel_content">
            <div ng-class="{'test' : true}" ng-repeat="item in $ctrl.tagList">{{item}}</div>
            <pre><code>{{$ctrl.tagList}}</code></pre>
    </div>
    </div>
    <div class="panel">
        <div class="panel__title">Tab 2</div>
        <div class="panel_content">
            <p>Tabs 2 content</p>
        </div>
    </div>
    ...
</tabs>
```

I then manually use $transclude() to create an array of panels and iterate through them inside my template. The issue is that when I run the following:

```javascript
var panels = Array.from($transclude());
```
The html above with the ng-repeat comes in commented out though, so I'm not able to compile the content:

```html
<div class="panel_content">
    <!-- ngRepeat: item in $ctrl.tagList-->
    <pre><code class="ng-binding">{{$ctrl.tagList}}</code></pre>
</div>
```
Scope doesn't seem to be an issue here since compiled transcluded content only is showing unexped results for the ng-repeat only. $ctrl.tagList is rendering correctly in the `pre` element.

```html
<div class="panel_content ng-scope">
    <!-- ngRepeat: item in $ctrl.tagList-->
    <pre><code class="ng-binding">["Tag 1","Tag 2","Tag 3","Tag 4"]</code></pre>
</div>
```
**AngularJS version:** 1.6.6

**Browser:** 
All

**Comment by frederikprijck** [comment]
Hi, any chance u got a reproduction sample using plunkr?
Atm it's kinda cryptic to me to fully understand what it is exactly you're doing.

**Comment by Narretz** [comment]
When calling $transclude() you already receive a compiled and linked DOM fragment. If your repeat source is empty at that point, then you'll get the placeholder comment that is generated by ngRepeat.
