### ISSUE TITLE
Potential bug in recursive linking

### ISSUE THREAD

**Issue by cary-smith** [angular/angular.js#16329]
Hello angular folks! Really enjoy the library and I am glad you maintain the older one even though the new trucks onwards.

We have recently been experimenting with ShadyDOM as we start preparing for the next iterations of our internal component library. We have run into an issue where the introduction of ShadyDOM to an angular application seems to break `ng-switch` statements but not all the time and is related to shadyDOM modifying functionality on the browser. In some instances, their code [adds an 'item' function to the childNodes array](https://github.com/webcomponents/shadydom/blob/cb84c2ef9fe126a7d707e634c44b6079c8bdf335/src/patch-accessors.js#L197) object (not into the array so it does not affect length) which seems to throw things off. 

We have a [ticket logged with ShadyDOM](https://github.com/webcomponents/shadydom/issues/182) with a simplified example of this. 

I did a bit of digging and found it is failing when angularjs attempts to access the [childNodes of an undefined object](https://github.com/angular/angular.js/blob/f876ab71913e17e9126baad19ab795f28b61bfe6/src/ng/compile.js#L2825). Naively the fix is:

```javascript
if (childLinkFn && linkNode) {
  childLinkFn(scopeToChild, linkNode.childNodes, undefined, boundTranscludeFn);
}
```
This fixes the failure allowing `ng-switch` to function in the limited scenario but I know there is far more to it than that. 

I am unfortunately unable to submit a PR or verify the testing because we sit behind a firewall and do not use bower. Are there deeper ramifications to placing this fix? Seems that a non-node should not be compiled.

Thanks!

**Comment by Narretz** [comment]
I think I've seen this before in other circumstances, but so far we've never had a good repro for it. Obviously third party code can be tricky to work with, especially if it manipulates the DOM additionally to AngularJs.

**Comment by daniarora17** [comment]
I am also seeing the same issue. I can see error "Cannot read property "0" of undefined". Is it under progress

**Comment by Narretz** [comment]
> Is it under progress

What do you mean? If we're working on it? No, because we don't have a reproduction.

**Comment by cary-smith** [comment]
I apologize that I cannot create an example without adding the external library but the ShadyDOM ticket does have a reproduction of it:

http://jsbin.com/cicujedimi/1/edit?html,js,output

**Comment by frederikprijck** [comment]
@cary-smith It looks like the jsbin is working fine for me, any chance you can link a jsbin which throws the error you talk about?

**Comment by Narretz** [comment]
I haven't investigated closely, but maybe this is because we assume / require that the DOM does not change during linking. Checking if an element actually exists in the nodeList would introduce a performance penalty.

**Comment by gkalpak** [comment]
TBH, it ShadyDOM seems the most likely suspect. If I had to guess, I would say it is because ShadyDOM monkey-patches `.childNodes` and returns a plain ol' Array object, instead of a `NodeList` (which is "live"). This means that when an element is removed `.childNodes` should be updated, but ShadyDOM breaks.
<sub>(While the above is true, I can't be 100% sure that this is what causes the error, but seems very likely.)</sub>

E.g.:

```js
const div = document.createElement('div');
div.innerHTML = '1<span>2</span>3';

const childNodes = div.childNodes;
div.removeChild(childNodes[0]);

console.log(childNodes);
  // Without ShadyDOM: ['<span>2</span>', '3']   (correct)
  // With ShadyDOM: [1, '<span>2</span>', '3']   (incorrect)
```

##
I understand tht ShadyDOM sacrifices correctness/completeness for speed, but I am not sure if this falls under that umbrella. In any case, I don't think there is much we can do in AngularJS.
