### ISSUE TITLE
vendor.js:108 TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by adildosani** [angular/angular.js#16324]
$scope.sss=function(){
            var changeDateFormat = function(currDate) {
                var day = currDate.getDate();
                var month = currDate.getMonth() + 1;
                var year = currDate.getFullYear();

                return year + '-' + month + '-' + day;
            };

                    $scope.chartdat1 = [];
                    $scope.chartdat2 = [];
                    $scope.datefield = [];
                    $scope.ex = [];
                   
                   $http({
                method: "GET",
                params: {
                    mid : $stateParams.mid,
                    period:"day",
                    selectdate: changeDateFormat($scope.selectDate4)
                }
                })
             .success(function (data, status, headers, config) {
                            $scope.charData = data;

                           
                
                if(data[0]!= undefined)
                {
                        console.log(data[0]);
                        
                     for(var j=0;j<data[0].length;j++)
                     {
                         $scope.datefield[j]= data[0][j][0];
                     }

                    for(var i=0;i<data[0].length;i++)
                    {
                       
                        if(data[3][i]!=0)
                        {
                            $scope.chartdat2[i] = data[0][i];

                            // if(data[0][i+1]==0)
                            //  {
                            //   $scope.chartdat2[i+1] = data[0][i+1];    
                            //  }

                            //  if(data[0][i-1]==0)
                            //  {
                            //   $scope.chartdat2[i-1] = data[0][i-1];    
                            //  }

                           // $scope.chartdat1[i-1] = data[0][i-1];
                            if($scope.chartdat1[i]==null|| $scope.chartdat1[i] == undefined)
                            {
                                $scope.chartdat1[i] = null;
                            }
                        }
                        else
                        {
                             $scope.chartdat1[i] = data[0][i]; 

                             if(data[0][i+1]!=0)
                             {
                              $scope.chartdat1[i+1] = data[0][i+1];    
                             }

                            if(data[0][i-1]!=0)
                             {
                              $scope.chartdat1[i-1] = data[0][i-1];    
                             }
                            // $scope.chartdat2[i-1] = data[0][i-1];
                            // $scope.chartdat2[i+1] = data[0][i+1];
                            if($scope.chartdat2[i]==null|| $scope.chartdat2[i] == undefined)
                            {
                                $scope.chartdat2[i] = null;
                            }   
                        }
                    }

            Highcharts.chart('container', {
            chart: {
                                zoomType: 'x',
                           
                type: 'area',
                spacingBottom: 30
            },
            title: {
                text: 'power'
            },
            subtitle: {
                floating: true,
                align: 'right',
                verticalAlign: 'bottom',
               // y: 15
            },
            legend: {
                layout: 'vertical',
                align: 'left',
                verticalAlign: 'top',
                x: 150,
                y: 100,
                floating: true,
                borderWidth: 1,
                backgroundColor: '#FFFFFF'
            },
            xAxis: {
               // type: 'datetime', 
               // categories: $scope.datefield,
               showLastLabel: true,
               labels: {
                enabled: true,
                formatter: function() { 
                    var  a = $scope.datefield[this.value];
                    var b ;
                    if(a!= undefined)
                    {
                        b = a.substr(0,16);
                    }
                    else
                    {
                        b= ' ';
                    }
                    return b;},
                },
               
            },
            yAxis: {
                title: {
                    text: 'Power KWh'
                },
                labels: {
                    formatter: function() {
                        return this.value;
                    }
                },
                min:0
            },
            tooltip: {
                  useHTML: true,
               //pointFormat: this.point.name+'<br>'+ '<br/><span style="color:{this.point.color}">\u25CF</span> ' + this.series.name+":" + this.y + '</br>'
                  formatter: function() {
                      //var s= '<br/><span style='+'"color:{'+this.point.color+'}">\u25CF</span>';
                      if(this.series.name=='power')
                      {
                        return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>' ;
                      }
                      else if(data[3][this.x]==1)
                      {
                        return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Dry Run';
                      }
                      else if(data[3][this.x]==2)
                      {
                        return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Short Circuit';   
                      }
                      else if(data[3][this.x]==3)
                      {
                        return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Open Circuit';
                      }
                      else if(data[3][this.x]==4)
                      {
                        return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Motor Jam';   
                      }
                      else if(data[3][this.x]==5)
                      {
                        return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ 'Power'+":" + this.y + '</br>'+ 'Motor Off';
                      }
                      else if(data[3][this.x]==6)
                      {
                        return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Over Temperature';   
                      }
                      else
                      {
                        return this.point.name+'<br/><span style='+'"color:#7cb5ec">\u25CF</span>'+ 'Power'+":" + this.y + '</br>';
                      }
                 }
            },
            plotOptions: {
                // area: {
                //     fillOpacity: 1
                // },
                
            },
            credits: {
                enabled: false
            },
            legend: {
                layout: 'vertical',
                align: 'left',
                verticalAlign: 'top',
                x: 50,
                y: 0,
                floating: true,
            },            
            series: [{
                name: 'power',
                data: $scope.chartdat1,
                fillColor: {
                    linearGradient: {
                        x1: 0,
                        y1: 0,
                        x2: 0,
                        y2: 1
                        },
                        stops: [
                        [0, Highcharts.getOptions().colors[0]],
                        [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                                ]
                            },
            }, {
                name: 'fault',
                data: $scope.chartdat2,
                color:'#FF8784'
            }]
        });
        }
        else
        {
            $scope.data = []
        }
        }),function (err) {
                alert("failed to get data from server");
            }
                    // return $scope.selectDate;

            };
            //Power Button

            $scope.power = function(){
                $scope.isPower = true;
                $scope.isLPM = false;
                $scope.isEnergy = false;
                $scope.day()
            }
                var changeDateFormat = function() {
                var currDate = new Date();
                var day = currDate.getDate();
                var month = currDate.getMonth() + 1;
                var year = currDate.getFullYear();

                return year + '-' + month + '-' + day;
            };

            $scope.isPower = true;
               $scope.chartdat1 = [];
              $scope.chartdat2 = [];
              $scope.datefield = [];
             $scope.selectDate3 = changeDateFormat($scope.todaydate);

             $http({
                method: "GET",
                params: {
                    mid : $stateParams.mid,
                    period:"day",
                    selectdate: $scope.selectDate3,
                }
                })
             .success(function (data, status, headers, config) {
                     
                     alert("Welcome to Server");

                     $scope.charData = data

                          for(var j=0;j<data[0].length;j++)
                     {
                         $scope.datefield[j]= data[0][j][0];
                     }

                    for(var i=0;i<data[0].length;i++)
                    {
                       
                        if(data[3][i]!=0)
                        {
                            $scope.chartdat2[i] = data[0][i];

                            // if(data[0][i+1]==0)
                            //  {
                            //   $scope.chartdat2[i+1] = data[0][i+1];    
                            //  }

                            //  if(data[0][i-1]==0)
                            //  {
                            //   $scope.chartdat2[i-1] = data[0][i-1];    
                            //  }

                           // $scope.chartdat1[i-1] = data[0][i-1];
                           
                            if($scope.chartdat1[i]==null|| $scope.chartdat1[i] == undefined)
                            {
                                $scope.chartdat1[i] = null;
                            }
                        }
                        else
                        {
                             $scope.chartdat1[i] = data[0][i]; 

                             if(data[0][i+1]!=0)
                             {
                              $scope.chartdat1[i+1] = data[0][i+1];    
                             }

                            if(data[0][i-1]!=0)
                             {
                              $scope.chartdat1[i-1] = data[0][i-1];    
                             }
                            // $scope.chartdat2[i-1] = data[0][i-1];
                            // $scope.chartdat2[i+1] = data[0][i+1];
                            if($scope.chartdat2[i]==null|| $scope.chartdat2[i] == undefined)
                            {
                                $scope.chartdat2[i] = null;
                            }   
                        }
                    }
            Highcharts.chart('container', {
            chart: {
                zoomType: 'x',
                type: 'area',
                spacingBottom: 30
            },
            title: {
                text: 'power'
            },
            subtitle: {
                floating: true,
                align: 'right',
                verticalAlign: 'bottom',
               // y: 15
            },
            legend: {
                layout: 'vertical',
                align: 'left',
                verticalAlign: 'top',
                x: 150,
                y: 100,
                floating: true,
                borderWidth: 1,
                backgroundColor: '#FFFFFF'
            },
            xAxis: {
                labels: {
                enabled: true,
                formatter: function() { 
                    var  a = $scope.datefield[this.value];
                    var b ;
                    if(a!= undefined)
                    {
                        b = a.substr(0,16);
                    }
                    else
                    {
                        b= ' ';
                    }
                    return b;},
                },
                
              // type: 'datetime', 
               // categories: $scope.datefield,
               // minTickInterval: count,
              // dateTimeLabelFormats: {
                                     // day: '%e of %b'
               //                      hour: '%H:%M'
                //                  }
            },
            yAxis: {
                title: {
                    text: 'Power KWh'
                },
                labels: {
                    formatter: function() {
                        return this.value;
                    }
                },
                min:0
            },
            tooltip: {
                useHTML: true,
               //pointFormat: this.point.name+'<br>'+ '<br/><span style="color:{this.point.color}">\u25CF</span> ' + this.series.name+":" + this.y + '</br>'
                                  formatter: function() {
                      //var s= '<br/><span style='+'"color:{'+this.point.color+'}">\u25CF</span>';
                                  //console.log(data[3][this.x]); 
                                  if(this.series.name=='power')
                                  {
                                    return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>' ;
                                  }
                                  else if(data[3][this.x]==1)
                                  {
                                    return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Dry Run';
                                  }
                                  else if(data[3][this.x]==2)
                                  {
                                    return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Short Circuit';   
                                  }
                                  else if(data[3][this.x]==3)
                                  {
                                    return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Open Circuit';
                                  }
                                  else if(data[3][this.x]==4)
                                  {
                                    return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Motor Jam';   
                                  }
                                  else if(data[3][this.x]==5)
                                  {
                                     return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ 'Power'+":" + this.y + '</br>'+ 'Motor Off';
                                  }
                                  else if(data[3][this.x]==6)
                                  {
                                    return this.point.name+'<br/><span style='+'"color:'+this.point.color+'">\u25CF</span>'+ this.series.name+":" + this.y + '</br>'+ 'Over Temperature';   
                                  }
                                  else
                                  {
                                    return this.point.name+'<br/><span style='+'"color:#7cb5ec">\u25CF</span>'+ 'Power'+":" + this.y + '</br>';
                                  }
                                // formatter: function() {
                                //     return '<b>'+ this.series.name +'</b><br/>'+
                                //     this.x +': '+ this.y;
                               }
                // }
            },
            plotOptions: {
                // area: {
                //     fillOpacity: 1
                // },
                
            },
            credits: {
                enabled: false
            },
            legend: {
                layout: 'vertical',
                align: 'left',
                verticalAlign: 'top',
                x: 50,
                y: 0,
                floating: true,
            },            
            series: [{
                name: 'power',
                data: $scope.chartdat1,
                fillColor: {
                    linearGradient: {
                        x1: 0,
                        y1: 0,
                        x2: 0,
                        y2: 1
                        },
                        stops: [
                        [0, Highcharts.getOptions().colors[0]],
                        [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                                ]
                            },
            }, {
                name: 'fault',
                data: $scope.chartdat2,
                color:'#FF8784'
            }]
        });
        }),function (err) {
                alert("failed to get data from server");
            }

             

             $http({
                method: "GET",
                url: $scope.server + "/api/v1/due_to/",
                params: {
                    mid : $stateParams.mid
                }
                })
                 .success(function (data, status, headers, config) {
                    
                    if ((data == undefined)|| (data.length==0)) 
                        {
                            $scope.fault_data = 0
                        }
                    else{

                        $scope.fault_data = data
                        } 
                    })
            }, function (err) {
                var err_msg = 'Something went wrong. Please try again.';
            }

            );

here my code pleas show me correct answer

**Comment by frederikprijck** [comment]
> here my code pleas show me correct answer

This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). But keep in mind, if you need some assistance it's a good idea to provide some clarification to what you're experiencing.

**Comment by Narretz** [comment]
It's not possible to determine if this is a bug or a user error with this information.
