### ISSUE TITLE
Cannot read property '-1' of undefined : I am getting this error when I select a item from list, below is the code of selection

### ISSUE THREAD

**Issue by user1359** [angular/angular.js#16327]
$scope.selectTestValue = function(test,index){
                  $scope.display.selectedItems.forEach(function(o) {
                        if(o.name=="INSULIN - FASTING"){
                        if(test.name=="INSULIN - PP"){
                        popupFactory.showAlert("INSULIN - FASTING and INSULIN - PP both tests can not be taken at a time");
                        out();
                    }
                    }
                    else if(o.name=="INSULIN - PP"){
                        if(test.name=="INSULIN - FASTING"){
                        popupFactory.showAlert("INSULIN - FASTING and INSULIN - PP both tests can not be taken at a time");
                        out();
                    }
                    }
                }, this);    
                
                if(test.selected == true){
                    var alreadysettestflag = false;
                    $scope.display.selectedItems.forEach(function(m){
                        if(m.name == test.name){
                            alreadysettestflag = true;
                        }
                    });
                    if(test.loadData == true){
                        $scope.display.tests[$scope.display.tests.indexOf(test)].selected = true;
                        $scope.display.tests[$scope.display.tests.indexOf(test)].originType = "test";
                    }
                    if(alreadysettestflag == false){
                        $scope.display.selectedItems.push(test);
                        $scope.display.test[$scope.display.tests.indexOf(test)].selected = true;
                        $scope.display.test[$scope.display.tests.indexOf(test)].originType = "test";
                    }
                    $scope.display.testsearchText.name = "";
                    $scope.display.test = [];
                }
                 if(test.selected == false){
                    if(test.originType == "test"){
                        $scope.display.tests.forEach(function(testName){
                            if(test.code == testName.code){
                                testName.selected = false;
                                //$scope.display.selectedItems.splice(index , 1);
                            }
                        })
                        var selectedObjIndex = undefined;
                        $scope.display.selectedItems.forEach(function(o,i){
                            if(o.code == test.code){
                                selectedObjIndex = i;
                            }
                        })
                        if(selectedObjIndex >= 0)
                            $scope.display.selectedItems.splice(selectedObjIndex, 1);
                    }
                    $scope.display.testsearchText.name = "";
                    $scope.display.test = [];
                } 
            }

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
