### ISSUE TITLE
ng-checked broke in 1.4

### ISSUE THREAD

**Issue by tsteuwer** [angular/angular.js#16333]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
When using ng-checked with angular 1.4+, it no longer recognizes truthy values as an indicator on whether or not a value should be checked. Even though it says this in [the documentation](https://docs.angularjs.org/api/ng/directive/ngChecked) and has been this way prior to 1.4.

**Expected / new behavior:**
At 1.4, angular broke this behavior and only recognizes true/false. Please see the following fiddle:

http://jsfiddle.net/h8to34ux/169/

This is the last version of 1.3 (1.3.20). Now, change angular to v 1.4.0. Or any other version after this. It no longer recognizes 1 is checked and 0 is false, contrary to the documentation or previous usage.

**AngularJS version:** 1.4.0+

**Browser:** all

**Comment by frederikprijck** [comment]
The same documentation page mentions:

> Note that this directive should not be used together with ngModel, as this can lead to unexpected behavior.

Removing ngModel makes ngChecked work as expected: http://jsfiddle.net/nd1kjv07/

**Comment by Narretz** [comment]
@frederikprijck is right, you shouldn't use ng-checked and ng-model together. It simply isn't designed to work together (and not necessary either)
