### ISSUE TITLE
ng-controller

### ISSUE THREAD

**Issue by Metallingus7** [angular/angular.js#16337]
http://errors.angularjs.org/1.6.4/$injector/modulerr?

angular.module('app',[]);

var MainController = function($scope){
    $scope.val="123"
}

**Comment by petebacondarwin** [comment]
This looks like a support question; although it is difficult to tell as it has very little information. 
Please use one of the support channels for help: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

Github issues are for bug reports.
