### ISSUE TITLE
Can not display angularjs JSON data in firefox

### ISSUE THREAD

**Issue by masoudk1990** [angular/angular.js#16345]
**I'm submitting a ...**

- [X ] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
Although I am able to display my AngularJS JSON data in chrome, but for some reason I can not display it in firefox.
I checked firefox console log but it displays me some no helpful logs. I'm pretty sure reading the console log is not the way to troubleshooting this problem.

**Minimal reproduction of the problem with instructions:**
`    $http({
        url: "home/getData",
        dataType: 'json',
        method: 'GET',
        headers: {
            "Content-Type": "application/json"
        }
    }).then(function success(response) {
        $scope.Details = response.data;
        }, function error(response) {
            $scope.Details = response.statusText;
        })`

`            <ul>
                <li ng-repeat="x in Details">
                    {{x.Text}}
                </li>
            </ul>`

**AngularJS version:**
1.6.5

**Browser:** Firefox 57.0

**Comment by frederikprijck** [comment]
Hey!

Your issue reads like a support question / general question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

It's beneficial to provide more information when trying one of the listed supper channels, it's always a good idea to create a reproduction of the problem using something like [Plunkr](https://plnkr.co).

**Comment by masoudk1990** [comment]
Its definitely a bug on Firefox 57.0 because it works fine on Google Chrome.
Just try to get a complex JSON array with $http service and display it with ng-repeat to produce same bug.

**Comment by masoudk1990** [comment]
I'm really sorry, it was a bug of another development tool not AngularJS.
