### ISSUE TITLE
[BUG] Input[date|time|datetime-local] min & max attributes ignore ngModelOptions timezone

### ISSUE THREAD

**Issue by Swiftwork** [angular/angular.js#16342]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Using `ngModelOptions` developers can set timezone for `input[date|time|datetime-local]` for parsers and formatters. However this does not affect min and max validation.
https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1475
https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1486
Parsers and formatters take timezone into account.
https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1445

**Expected / new behavior:**

Take timezone into account when validating minimum and maximum date spans.

**Minimal reproduction of the problem with instructions:**

Select 2013-12-31 if you aren't on UTC it should be invalid.
https://plnkr.co/edit/i88I219Wke77tdUSA3XF?p=preview

**AngularJS version:** 1.6.6

**Browser:** [all]

**Comment by Narretz** [comment]
This has been reported before: https://github.com/angular/angular.js/issues/11221

Let's keep this issue because it's more succinct.

**Comment by Narretz** [comment]
I've updated your demo to make it a bit easier to see - https://plnkr.co/edit/zHwbOVw5uI1f8xl9a7RY?p=preview
If you have timezone: UTC and a UTC date, then max should not be true, but in the demo it is.
