### ISSUE TITLE
On assigning response array to scope im getting undefined 

### ISSUE THREAD

**Issue by sudhakar216** [angular/angular.js#16355]
I'm trying to send and receive data from node
I'm getting the response from the server in form of array when I use console.log(resp.data) I'm able to see it but on assigning to scope I'm getting undefined please go through below code

var app = angular.module('ECMapp',[]);
app.controller('con',['$scope','$http',function($scope,$http){
  $scope.result;
  $scope.test = function(){
    $http.post('/test',$scope.inputs).then(function(resp){

        console.log((resp.data));  // here im able to see data in console

      $scope.result= resp.data;
      console.log($scope.result);   // here im able to see data in console
      alert($scope.result); // here im able to see data in alert
      alert($scope.result.location); // here im trying to get a particular able to see data in console
      console.log($scope.result.location);

    //  console.log(location);

    });
  };

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
