### ISSUE TITLE
Angularjs1.6.6 can't update the model value with $setViewValue

### ISSUE THREAD

**Issue by huhaoGitHub** [angular/angular.js#16356]
## # **On the problem**
Unable to update Model;

Using the set function can change the ngModel value, and through the pipeline function $parsers, however, the Del function uses splice to process the array, but it can not pass the pipeline function and realizes the update model value.

I tried to use $scope.$apply () to execute after ngModel.$setViewValue ($scope.images) and still can't be solved.

The version of the angular used is 1.6.6.

Online code, <a href="http://embed.plnkr.co/GaFWZdmJBilvbHxpLHPi/">plnkr code</a>

## # **View code**
    <div ng-controller="appController">
        <div image-uploads ng-model="files"></div>
        <p style="display: block; color: red">{{files}}</p>
    </div>

## # **Javascript code**
    var app = angular.module('app', []);
    app.controller('appController', function ($scope) {
        $scope.files = '1,2,3,4';
    });

    app.directive('imageUploads', function () {
    return {
    require: '?^ngModel',
    restrict: 'EA',
    template: '<div class="image-upload-box"><p class="image_upload" ng-repeat="image in images track by $index"><button ng-click="set()">setModel</button><button ng-click="del($index)">{{image}}</button></p></div>',
    link: function ($scope, element, attrs, ngModel) {
        ngModel.$formatters.push(function (modelValue) {
            var images = new Array();
            if (!ngModel.$isEmpty(modelValue)) {
                var values = modelValue.split(",");
                for (var j = 0; j < values.length; j++) {
                    images.push({
                        'id': values[j]
                    });
                }
            }
            return images;
        });

        ngModel.$parsers.push(function (viewValue) {
            var s = "";
            for (var j = 0; j < viewValue.length; j++) {
                if (viewValue[j].id != null) {
                    if (j > 0) {
                        s += ",";
                    }
                    s += viewValue[j].id;
                }
            }
            return s;
        });

        ngModel.$render = function () {
            $scope.images = ngModel.$viewValue;
        };

        $scope.del = function (i) {
            $scope.images.splice(i, 1);
            ngModel.$setViewValue($scope.images);
        };
        $scope.set = function () {
            console.log('set');
            $scope.images = [{id: 5}, {id: 6}, {id: 7}];
            ngModel.$setViewValue($scope.images);
        }
    }
    };
    });

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

It's also quite difficult to see what you are trying to achieve here. In general, ngModel should be on elements that react directly to user interaction, such as inputs.
