### ISSUE TITLE
Version 1.5.11 - Providers must be declared in correct sequence or injection fails

### ISSUE THREAD

**Issue by zortnac** [angular/angular.js#16363]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
Providers declared on the module must be declared in a sequence that fits their (non-cyclical) dependency graph.

**Expected / new behavior:**
Provider declaration order should not matter, as the declaration order for post-config entities (service, factory, etc) does not matter.

**Minimal reproduction of the problem with instructions:**
http://plnkr.co/edit/xfusk4lIevLngt7DAzQO?p=preview

**AngularJS version:** 1.5.11

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**
I tried to find out whether or not this behavior is as intended by checking documentation, but couldn't find an answer.

**Comment by gkalpak** [comment]
It seems to have been the case since forever (at least as back as 1.2.x). Off the top of my head, I can't think a reason why (other than complicating the implementation a bit). Does anyone know?

cc @petebacondarwin, @Narretz

**Comment by Narretz** [comment]
Can't remember that this ever came up. I think we put config calls in order or something a few years back, but that must have been post 1.2, too

**Comment by zortnac** [comment]
For what it's worth with respect to priority and frequency: injecting providers into other providers is rare enough of a thing that this is literally the first time I've tried to do it in five years.

**Comment by petebacondarwin** [comment]
By the time we arrive at using any service, all the services have been registered (via their providers, etc), so we never have a problem with resolving their dependencies.

Compare to providers, which are run as soon as they are registered:

```
function provider(name, provider_) {
    ...
    if (isFunction(provider_) || isArray(provider_)) {
      provider_ = providerInjector.instantiate(provider_);
    }
    ...
  }
```

I guess that it would be quite an upheaval to make providers "lazy" so that we only ran their factory function when the service that they provide is requested?

**Comment by Narretz** [comment]
I think we should document this and leave it as is.
