### ISSUE TITLE
Angular html5Mode + ng-include break navigation

### ISSUE THREAD

**Issue by samuelmartineau** [angular/angular.js#16369]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Impossible to navigate when html5Mode enabled and ng-include/ng-transclude used in the page.

**Minimal reproduction of the problem with instructions:**

[complete demo](https://codepen.io/samuelmartineau/pen/vWqPrJ?editors=1011)

app.js :
```
angular
  .module('AngularApp')
  .config(function($locationProvider) {
    $locationProvider.html5Mode(true);
  });

```
index.html :
```
...
<body ng-app="AngularApp">
  <a href="./about.html">internal link breaks</a>
  <ng-include src="'templateId.html'"></ng-include>
</body>
...
```

**AngularJS version:** 1.6.y

**Browser:** [all]

**Anything else:**
[stackoverflow issue](https://stackoverflow.com/questions/47714665/angular-html5mode-ng-include-break-navigation)

[codepen demo](https://codepen.io/samuelmartineau/pen/vWqPrJ?editors=1011)

**Comment by samuelmartineau** [comment]
@gkalpak Do you need more info from me or from your core team? Otherwise what do you need to help?

**Comment by gkalpak** [comment]
Not sure what you mean by "impossible to navigate". It works fine [afaict][1].
Closing, but feel free to provide more info below if you still think there is an issue.

[1]: https://codepen.io/ExpertSystem/pen/GyKEPE?editors=1011

**Comment by gkalpak** [comment]
I just added `ngRoute` as an easy way to show that the path is changing (as should happen). It works fine without it. MAke sure you read and understand how things work with `html5` mode ([dev guide][1]). If you want to be able to differentiate between specific sub-paths (some of which are part of your app and some not), you need to set up an appropriate `base[href]` (also explained in the guide mentioned above).

[1]: https://docs.angularjs.org/guide/$location
