### ISSUE TITLE
[CDN] Google Hosted Libraries still offer angular 1.6.4 as the newest version.

### ISSUE THREAD

**Issue by Mlocik97-issues** [angular/angular.js#16368]

**Comment by Narretz** [comment]
It's at 1.6.7 now

**Comment by Mlocik97-issues** [comment]
Thanks, but now (I believe it's only a few minutes) I can't see anything concerning AngularJS on Google Hoster Libraries.
![screenshot_68](https://user-images.githubusercontent.com/31345346/34201793-fa23274e-e575-11e7-8778-1dbe2c6aee3f.png)

**Comment by Narretz** [comment]
That's correct. Since this page must be updated manually and separately from adding a new version to the CDN, we decided to remove the info from this page. The CDN will still get updated, but you might be better off by using a CDN that updates automatically when npm is updated.

**Comment by Mlocik97-issues** [comment]
I think it's not good solution,...
If it suggest older version (few month old), it's not big problem, but better than nothing.... And when I use a lot of google's frameworks, it's better to copy from one site, than go over every sites.

**Comment by Narretz** [comment]
Like I said, the CDN still gets updated with the actual version and like before,  we can't guarantee that the CDN gets updated when the version is released to CDN. But now you don't have outdated info on the CDN page.

**Comment by Mlocik97-issues** [comment]
if I did not even want to write this issue

**Comment by sabousha** [comment]
I'm confused; @Narretz Are you saying that the resource is still available on CDN ?  We simply removed the wiki ?

**Comment by Narretz** [comment]
> if I did not even want to write this issue

@Mlocik97-issues I don't understand what you mean by that

@sabousha Yes, the script files are still available. If we removed the actual files we would have a riot on our hands ;)

**Comment by jt2190** [comment]
@Narretz The Google Developer CDN doesn't have AngularJS > 1.6.7., so the following URL doesn't work:

`https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js`

It _seems_ like we should update our CDN urls to [https://code.angularjs.org/](https://code.angularjs.org/), i.e:

`https://code.angularjs.org/1.6.9/angular.min.js`

Is this preferred/recommended? (I searched for an announcement about this but I haven't been able to find one. My apologies if I missed it.)

**Comment by Narretz** [comment]
@jt2190 No, don't use code.angularjs.org. That's not a CDN, that's just storage.

Putting the code and the Google CDN is a manual process and sometimes lags behind.

If you need the code ASAP on a CDN, you should use another one, for example https://cdnjs.com/libraries/angular.js/1.6.9
