### ISSUE TITLE
Routing encoding changed by 1.6.7 

### ISSUE THREAD

**Issue by melgish** [angular/angular.js#16361]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

**Current behavior:**

route parameters that are URI's are encoded twice in 1.6.7

**Expected / new behavior:**

encoding of route parameters has changed between 1.6.6 and 1.6.7.  I've added a plunker to demonstrate.  Prior to 1.6.7 a colon appearing in a routing parameter isnot encoded.  Now it appears to be double encoded from ':' to '%3A' to '%253A'

**Minimal reproduction of the problem with instructions:**

https://plnkr.co/edit/WUhkuQ2TU0WG43rqO0Nx?p=preview

**AngularJS version:** 1.6.7

**Browser:** [ Chrome 62 | Firefox 57 | probably all]

**Anything else:**

**Comment by Narretz** [comment]
@petebacondarwin looks like this is another effect of the encoding change. Can you see if this would be fixed by your follow-up PR(s)? Imo, it won't because they only affect .path(), right?

**Comment by petebacondarwin** [comment]
I'm hoping that this will be fixed by #16354

**Comment by upeshdesai** [comment]
Have a similar issue regarding '@' and thought it might be a ui-router bug. Initial http call to our spring app works correctly, '/whatever@dom.com' => '/whatever%40dom.com'. But then for some reason it fires again, '/whatever%2540dom.com'. Might be a combined issue with ui-router as well.

**Comment by melgish** [comment]
Issue does seem to be resolved in 1.6.8-build.5518 though my own testing has been limited.

**Comment by gkalpak** [comment]
Hm...where did you get 1.6.8-build.5518 from? I currently see snapshot at v1.6.8-build.5517+sha.2c1e589 😕

**Comment by melgish** [comment]
That was the version in https://code.angularjs.org/snapshot/angular.min.js 2 days ago.  
Today it's 1.6.8-build.5519  Time flies :-)

**Comment by gkalpak** [comment]
Interesting. So the build numbers for `snapshot/angular.js` and `snapshot/angular.min.js` do not match 😳

**Comment by petebacondarwin** [comment]
I think you had a caching issue @gkalpak - looking right now we have:

**angular.js**:

```
/**
 * @license AngularJS v1.6.8-build.5519+sha.5c38fb7
 * (c) 2010-2017 Google, Inc. http://angularjs.org
 * License: MIT
 */
```

and 

**angular.min.js*:

```
/*
 AngularJS v1.6.8-build.5519+sha.5c38fb7
 (c) 2010-2017 Google, Inc. http://angularjs.org
 License: MIT
*/
```

**Comment by gkalpak** [comment]
Indeed 😕 Thx for checking :smiley:
(Good thing I didn't spend time looking into the build number mismatch 😛)

**Comment by robscotts4rb** [comment]
Looking at the changelog it seems 1.6.8 has been released but is not yet on npm. Any idea when it is going to get published?

**Comment by Narretz** [comment]
We wanted to release 1.6.8 on Monday, but encountered a problem we're trying to fix. I can't promise it'll be done this week.

**Comment by petebacondarwin** [comment]
We have an infrastructure issue in our release jobs @robscotts4rb - sorry. Working on it.

**Comment by petebacondarwin** [comment]
Release is in progress... fingers crossed it will complete :-)

**Comment by Narretz** [comment]
1.6.8 is out on npm :)
