### ISSUE TITLE
Parsing fails when using an html escaped single quote (&#39;)

### ISSUE THREAD

**Issue by johannesjo** [angular/angular.js#16372]
- [x ] bug report

**Current behavior:**
When using a htmle scaped single quote in an expression, angular fails:
```
{{ ' xxx &#39; ' }}
``` 
See this plunkr: https://plnkr.co/edit/6myQ5I?p=preview

**Expected / new behavior:**
It should escape such quotes to `\'` or at least parse them as simple string `&#39;`.

**Minimal reproduction of the problem with instructions:**
See this plunkr: https://plnkr.co/edit/6myQ5I?p=preview

**AngularJS version:** 1.6.x

**Browser:** all

**Comment by petebacondarwin** [comment]
Well remember that AngularJS gets to parse the content of an interpolation after the browser has "rendered" it (even if that only means converting the HTML to a DOM node tree and not actually displaying it on the screen). So what the Angular parser receives is actually `'a ' b'`.

**Comment by johannesjo** [comment]
Hmhm I'll have to investigate that a little further. Meanwhile is there any recommended way to work around that?

**Comment by Narretz** [comment]
Well, if you store the string in a vairable and do `{{ val }}` where `val = ' xxx &#39; '` instead of `{{ ' xxx &#39; ' }}` then it works.

**Comment by johannesjo** [comment]
@Narretz Thanks for the recommendation, but that's unfortunately not an option as the values are filled in by a CMS directly into the html.

**Comment by Narretz** [comment]
This is generally not a very good idea. I hope you control the values, because user-provided values in expressions could lead to XSS: https://code.angularjs.org/1.6.7/docs/guide/security#angular-templates-and-expressions
BTW, if the values are set by the CMS on the server, why do you need interpolation anyway? You could set them normally as the content.

**Comment by johannesjo** [comment]
The use case is passing (multi language) strings to dynamic components as translation is handled by the backend. I'm still a little confused, because using '@` in the directive definition instead of `=` or `<`, leaves the string as it is.

**Comment by Narretz** [comment]
I don't know what do you mean by "leaves the string as it is" because I can see that `&#39;` gets decoded to `'`

**Comment by johannesjo** [comment]
@Narretz my bad. Locally I had an example that transformed `&#39` to `&amp;#39`. So I would conclude using `@` for external template strings is the best work around for this problem, at least when dealing with directives.

**Comment by Narretz** [comment]
Well, if you are doing `msg="&amp;#39"` with `@` then there's not expression parsing happening. The compiler takes the attribute content directly. With `=` the compiler parses the expression and will get confused if a string delimiter appears at a position that the parser can't handle.
So, yes you can use it, but please be aware of the security implications.
