### ISSUE TITLE
data-ng-include doesn't work (in a lot of situations) or work incorrectly (in a lot of situations)

### ISSUE THREAD

**Issue by Mlocik97-issues** [angular/angular.js#16370]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

In name issue
**Expected / new behavior:**

Work correctly
**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.6

**Browser:** [tested in ff and chrome but I suggest problems are in all browsers)

**Anything else:**

**Comment by Narretz** [comment]
Please define these situations. Such a broad description without a demo is not actionable.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Leave a comment if you can provide new feedback.

**Comment by Mlocik97-issues** [comment]
I was used AngularJS 1.4.x on my older project, and I create new project on new AngularJS, I did not notice changes from data-ng-include="[some URL]" to data-ng-include=" '[some URL]' " , but also a few situations is ng-include bugged, (one was subbmited in #16369 but also, I found bug, when you use AngularJS in electron app, and you create function to modify URL, and URLs are "inside electron" and URLs are "outside electron". It has different behavior.

**Comment by Narretz** [comment]
Okay, if you have found a legitimate issue, then please open an issue with a good description and ideally a minimal (runnable) example. Runnable on the web is probably not possible for electron, but without any code or explanation, there is simply nothing we can do.

**Comment by kbhuvana** [comment]
I accept there are numerous more pleasurable open doors ahead for people that took a gander at your site. We are providing AngularJs training in velachery.
For more details: http://www.zerobugacademy.com/angularjs-training-in-chennai
