### ISSUE TITLE
ci.angularjs.org fails to load (SSL error)

### ISSUE THREAD

**Issue by dguo** [angular/angular.js#16393]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
I was browsing the [docs](https://docs.angularjs.org/guide/ie) and tried to load the [ci.angularjs.org](https://ci.angularjs.org/) link, but I am getting a SSL error (NET::ERR_CERT_AUTHORITY_INVALID).

**Expected / new behavior:**
The site should load.

**Minimal reproduction of the problem with instructions:**
Open the link.

**AngularJS version:** 
N/A

**Browser:** 
Chrome 63.0.3239.132
Firefox 58.0b14

**Comment by frederikprijck** [comment]
Looks like there's an issue with the certificate idd.

/cc @gkalpak @petebacondarwin @Narretz

**Comment by Narretz** [comment]
Yes, there's an issue with the certificate, but you can still access the server via the IP directly. Since the CI is mostly useful for the core team, I don't think we are going to fix the certificate.

**Comment by Narretz** [comment]
We don't use ci.angularjs.org at all anymore.
