### ISSUE TITLE
how do a component with a name as floating-button

### ISSUE THREAD

**Issue by jefer94** [angular/angular.js#16398]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [X] other 

**Current behavior:**

Floating-button is not render

**Expected / new behavior:**

Do a component with a name as floating-button

**Minimal reproduction of the problem with instructions:**

```js
angular
  .module('anything', [])
  .component('floating-button' /* or floatingButton */, {
    ...
  });
```

```html
<!-- not work -->
<floating-menu/>
```

**AngularJS version:** 1.6.7

**Browser:** [ Chrome 65 ]

**Comment by frederikprijck** [comment]
When u use

```
angular
  .module('anything', [])
  .component('floatingButton' /* or floatingButton */, {
    ...
  });
```

You can use
```
<floating-menu></floating-menu>
```

Note: components/directives should not be self-closing.

**Comment by Narretz** [comment]
It would also help if the html used the same name as the component definition :D

**Comment by frederikprijck** [comment]
Haha @Narretz , Looks like I was a bit lazy on the c/p there 🙈

**Comment by jefer94** [comment]
Great, with an englosing tag it work, but I think that a short syntax should be good for our framework, thanks

**Comment by jefer94** [comment]
Ironically the name is the same that my element.

**Comment by frederikprijck** [comment]
> Ironically the name is the same that my element.

In the code u pasted here, it isn't.

> I think that a short syntax should be good for our framework, thanks

Afaik, this won't work (yet) as this needs changes in the HTML parsers, which is unrelated to AngularJS. However, I'm not aware of the current status of the HTML parser, but IIRC AngularJS can't really do anything about that.
