### ISSUE TITLE
$onInit not fire

### ISSUE THREAD

**Issue by virtual-marat** [angular/angular.js#16405]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

**Current behavior:**

I am using CoffeeScript in project. CoffeeScript compile this code:
```
angularApp.component 'widget',
    template: '<h1>Hello world!</h1>'
    controller: ->
        ctrl = this
        ctrl.$onInit = ->
            console.log '$onInit executed'
```
into:
```
angularApp.component('widget', {
    template: '<h1>Hello world!</h1>',
    controller: function() {
        var ctrl;
        ctrl = this;
        return ctrl.$onInit = function() {
            return console.log('$onInit executed');
        };
     }
});
```
And after compile this code and run, "ctrl.$onInit" function not execute.
But, if I delete "return" statement before "ctrl.$onInit", then "ctrl.$onInit" function execute.

**Expected / new behavior:**

ctrl.$onInit function must execute, have or missing "return" statement before function.

**Minimal reproduction of the problem with instructions:**

Demo, where "ctrl.$onInit" not execute (have "return" statement):
https://jsfiddle.net/bamvg7dk/1/

Demo, where "ctrl.$onInit" execute (missing "return" statement):
https://jsfiddle.net/e0t5w6aa/8/

**AngularJS version:** 1.6.7, 1.6.8

**Browser:** [Chrome 63 | Firefox 57]

**Comment by frederikprijck** [comment]
That behavior is expected, you do not want to have a return statement as that's not what a constructor function should do in JavaScript.

**Comment by virtual-marat** [comment]
Oh, I am forgot, that if returned object in constructor, that this object set as class instance.

From https://medium.com/javascript-scene/javascript-factory-functions-vs-constructor-functions-vs-classes-2f22ceddf33e:
> In JavaScript, any function can return a new object. When it’s not a constructor function or class, it’s called a factory function.

@frederikprijck Thank you!
