### ISSUE TITLE
Instalation Errors

### ISSUE THREAD

**Issue by wings77** [angular/angular.js#16402]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

npm install

Errores

bower install

Errores

**Expected / new behavior:**

Se instalaria sin problema

**Minimal reproduction of the problem with instructions:**

PS C:\wamp64\www\htdocs\angular-phonecat> npm install

> angular-phonecat@0.0.0 postinstall C:\wamp64\www\htdocs\angular-phonecat
> bower install

bower angular-animate#1.5.x     ENOGIT git is not installed or not in the PATH
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Juan Carlos C\AppData\Roaming\npm-cache\_logs\2018-01-10T16_08_43_848Z-debug.log

**AngularJS version:** 1.6.6

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

No

**Comment by petebacondarwin** [comment]
> ENOGIT git is not installed or not in the PATH

Perhaps you need to install git?

**Comment by Narretz** [comment]
Yes, looks like GIT is missing. Git as a prerequisite is listed in the readme: https://github.com/angular/angular-phonecat

If you encounter installation problems after installing GIT, you should open an issue in the phonecat Github repository.
