### ISSUE TITLE
Adding an `ng-click` to a `a` tag always trigger a page reload when $location is in html5 mode

### ISSUE THREAD

**Issue by mdarveau** [angular/angular.js#16410]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
With $location in html5 mode, the following triggers a full page reload while it does not in non html5:
```a(ng-href="'game/1'" ng-click="$event.stopPropagation();")```
Even if `ng-click` is empty, I get the same behavior. Note that I can't change le location in the `ng-click` handler as I need to support control click to open the link in a new tab.

**Expected / new behavior:**
The new route should be applied and the page should not reload just like in non html5 mode.

**Minimal reproduction of the problem with instructions:**
Add a ng-click attribute to a `a` tag in an app that uses the angular router.
Set `$locationProvider.html5Mode(true)`.
Click the link: it will trigger a full page reload but it should not.

**AngularJS version:** 1.6.4

**Browser:** Chrome 63.0.3239.132

**Comment by frederikprijck** [comment]
@mdarveau Why are u using both `href` and `click` on the same element?
If you wanna use an ng-click, you probably want to go with a button.

> Note that I can't change le location in the ng-click handler as I need to support control click to open the link in a new tab.

So why do u need ng-click at all?

**Comment by mdarveau** [comment]
I need to stop propagation of the click event as there is ng-click handler on the parent dom element as well. Adding `ng-click="$event.stopPropagation();"` did the trick, but it does not work anymore after I switched $location from non html5 to html5.

**Comment by mdarveau** [comment]
I also tried to implement the stopPropagation using a directive instead of `ng-click` and got the same result (page reload).
So it looks like the problem is not with `ng-click` but with `stopPropagation`. Is it possible that angular's URL rewriting requires handling the event as it propagates up?

**Comment by Narretz** [comment]
I don't see a difference for html5Mode false / true in this plunker (last link): https://plnkr.co/edit/oEraGgFaGWvDcBAcgLHj?p=preview

The logic in the a directive is quite simple: if the anchor has no href set or it's empty, then we prevent the default.
You could use $event.preventDefault() to stop the normal link behavior.

However, I'd say that mixing anchor links and click events is a bad idea, especially when you want to support accessibility in your app. If you click a thing, it should be clear what happens, either a navigation change or an interactive event.

I'd also argue that having ngClick element inside another click element violates the HTML5 spec about the nesting of "interactive content", for example nesting a elements with href is not allowed: https://stackoverflow.com/a/9883044/787333

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Leave a comment if you can provide new feedback.

**Comment by mdarveau** [comment]
Sorry for the delay. In my case, the outer element is using an `ng-click` and the inner one is using a `a`:

```
<table>
    <tbody>
      <tr ng-repeat="game in games" ng-click="viewGame()" ng-controller="GameRowCtrl">
        <td>
            <a href="{{getGameURL()}}" ng-click="$event.stopPropagation();"> {{ game.date }} </a>
        </td>
      </tr>
    </tbody>
</table>
```
`getGameURL()` returns something like:
* `html5Mode = false`: `#/game/221?someParam=true&basedOnContext=123`
* `html5Mode = true`: `game/221?someParam=true&basedOnContext=123`

`viewGame()` does `$location.path( "/game/#{$scope.game.id}" )` and set some search params based on game state.

The goal is that the row can be clicked and the route is changed to the game detail.
The link (within the row), it does the same thing but can be control-clicked so the game detail is opened in a new tab. The `ng-click` on the `a` is there so we can `stopPropagation` so the parent ng-click is not executed. Otherwise, the game detail would open in a new tab, but the original tab would also navigate to the game detail.

When `html5Mode = false` everything works fine. When `html5Mode = true` the page is reloaded even with a simple click on the link (no control-click).

**Comment by Narretz** [comment]
Thanks for the explanation, but it would still be good to have a fully functional demo. If it doesn't work in a plnkr (because that runs in an iframe, which messes with the routing), you can still put the code in there, and I can then run it locally.

Btw, any reason you're not using ngHref? You should use it.

**Comment by mdarveau** [comment]
I could not have plunker work with the routes, but I have deployed a simple reproduction page to my prod server.

Use the two following links to see the problem:
* https://www.maligue.ca/issue16410/nonhtml5/#/: in this case, when you click the `See game` link, you will see that the `Page loaded at` does not change and the mock game content is displayed thus proving that the route was applied. You can also see that control click works as well and that the original page stays at the original route. This is why I have a `ng-click="$event.stopPropagation();"` on the `a` tag since I do not want the `ng-click` executed on the parent row.
* https://www.maligue.ca/issue16410/html5/: in this case, the `Page loaded at` date changes as soon a you click the `See game` link. This proves that a full page reload was done instead of a route change.

Here is the backend code in jade/pug. `html5mode` changes based on the selected route (`/nonhtml5/` or `/html5/`).

```
doctype html
html(ng-app="plunker")
  head
    base(href="/issue16410/#{html5mode ? 'html5' : 'nonhtml5'}/")
    meta(charset='UTF-8')
    title Issue 16410

    script(type='text/javascript').

  body(ng-cloak)
    p
      | Page loaded at {{pageLoadedAt | date: 'medium'}}
    p
      | html5Mode: !{html5mode == true}
    div(ng-view)

  script(src="//code.angularjs.org/snapshot/angular.js")
  script(src="//code.angularjs.org/snapshot/angular-route.js")

  script(type='text/javascript').
    var app = angular.module( 'plunker', ['ngRoute'] );

    app.config( ['$routeProvider', '$locationProvider', function ( $routeProvider, $locationProvider ) {
      $routeProvider.when( '/', {
        template: '<table><tbody><tr ng-click="viewGame()" ng-controller="GameRowCtrl"><td><a ng-href="{{getGameURL()}}" ng-click="$event.stopPropagation();">See game</a></td></tr></tbody></table>'
      } ).when( '/game', {
        template: '<b>Game content</b>'
      } ).otherwise( {redirectTo: '/'} );

      $locationProvider.hashPrefix( '' );
      $locationProvider.html5Mode( #{html5mode} );
    }] );

    app.controller( 'GameRowCtrl', ['$scope', '$location', function ( $scope, $location ) {
      $scope.getGameURL = function () {
        return "#{html5mode ? '' : '#/' }game";
      };
      return $scope.viewGame = function () {
        $location.path( "/game" );
      };
    }] );


    app.run( ['$rootScope', function ( $rootScope ) {
      $rootScope.pageLoadedAt = new Date()
    }] );
```

I hope it helps!

**Comment by Narretz** [comment]
Could you please put this in a plunker and then do the following:
HTML5 mode needs the base href to be set. In plunker, this is the the address of the run server: 
`<base href="//run.plnkr.co/INSERT_ID/">`
You can get the id from the dev tools network panel - just search for the first request to run.plnkr ... and extract the id, and insert it into the html.
Then it should work.
Btw, if you want someone to test something for you, please make sure that you at least provide full formed HTML and not something that must be processed.

**Comment by gkalpak** [comment]
@mdarveau, the reason why `stopPropagation` breaks stuff is that HTML5 relies on a `click` hander we set on the `$rootElement`. Hitting that handler is essential for having the correct behavior.

I suggest you modify your code, so that clicking on the link does not stop the event propagation, but just make it be ignored by the parent listener. E.g.:

```pug
tr(... ng-click="$event.skipViewGame || viewGame()")
  td
    a(... ng-click="$event.skipViewGame = true") See game
```

**Comment by gkalpak** [comment]
Alternatively, you can make the anchor cover the whole row, so you don't need to duplicate logic or do obscure things to prevent behaviors :smiley:
(That is probably a better solution.)

**Comment by mdarveau** [comment]
@Narretz Sorry about that. I thought the version above was more readable (maybe I'm just used to jade/pug!) and that you would prefer a functional example rather than a HTML dump. Point noted, my bad.

@gkalpak Thanks for the explanation. I'll try the `$event.skipViewGame` trick for science, but you are right, having the anchor cover the whole row is the way to go. I didn't think it was possible.

Thanks to both of you for your help and patience!

**Comment by mdarveau** [comment]
Thanks, the strategy to attach a state to the event worked BUT only in my simple example because JQuery is not loaded. When JQuery is loaded, each `ng-click` get a different `$event` instance. I had to attach the state to `$event.originalEvent`.

**Comment by gkalpak** [comment]
That's weird. Glad you worked it out.
@mgol, @jbedard: Any idea why jQuery passes a different instance to each element's handler?

**Comment by gkalpak** [comment]
@mgol: But why not pass the same instance of wrapped event to all listeners?

**Comment by jbedard** [comment]
@gkalpak it should be the same instance, you can see the same `event` is used throughout [the dispatch method](https://github.com/jquery/jquery/blob/3.3.1/src/event.js#L299)

**Comment by jbedard** [comment]
I see. What I was looking at only covers handlers on the same element.

But why? I guess because jQuery is half native events and half not. Each element has a [single native event listener](https://github.com/jquery/jquery/blob/3.3.1/src/event.js#L186-L199) per event type. Then [invokes each jQuery handler](https://github.com/jquery/jquery/blob/3.3.1/src/event.js#L321) on the event manually. But the event bubbling happens natively, which repeats this handler invocation process again (including ["fixing"](https://github.com/jquery/jquery/blob/3.3.1/src/event.js#L299) the event). That is an interesting mix...

**Comment by gkalpak** [comment]
Interesting indeed 😛
I guess it makes sense to take advantage of the native bubbling (instead of re-inventing the wheel). Thx for clarifying.

**Comment by kbhuvana** [comment]
I accept there are numerous more pleasurable open doors ahead for people that took a gander at your site. We are providing AngularJs training in velachery.
For more details: http://www.zerobugacademy.com/angularjs-training-in-chennai
