### ISSUE TITLE
ngModel directive in HTML template truncates spaces at the end of input

### ISSUE THREAD

**Issue by ryzhman** [angular/angular.js#16416]
I'm submitting a bug report related to the ngModel directive.

**Current behavior:**
An issue is related to an input value from HTML template that contains spaces at the end of it. If input value contains spaces at the end, they are truncated from the model value. 

**Expected behavior:**
Empty spaces should be included to a model value.

**Steps to reproduce:**
1. use this code snippet to check it out:
```
<div ng-controller="MyCtrl">
<input type="text" ng-model="valueWithBug">Inout here</input>
<br/>
{{valueWithBug}}-value goes here
</div>
```
2. input a value that contains spaces at the end (i.e. "bug goes here ").

**Browser:** [Chrome 63.0.3239.132 | Firefox 56.0]

**AngularJS version:** 1.4.7

**Comment by Narretz** [comment]
You must use `ng-trim="false"' for the model value to keep whitespace.
