### ISSUE TITLE
Unable to access system.js and typescript.js files

### ISSUE THREAD

**Issue by sandeepsukhija** [angular/angular.js#16421]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Unable to access links: https://code.angularjs.org/tools/system.js and https://code.angularjs.org/tools/typescript.js . Are these files moved somewhere

**Expected / new behavior:**

Earlier, we could access this path. The file is used for loading angular2 in angularjs(co-existence)

**Minimal reproduction of the problem with instructions:**

Try accessing the link, it says File or directory not found.

**AngularJS version:** 1.x.y

1.6.5

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Anything else:**

Is there an alternative Link to access the files.

**Comment by frederikprijck** [comment]
@Narretz This might be related to last week's move ?

**Comment by Narretz** [comment]
We intentionally removed these files because these were legacy only (the Angular files were last updated 2 years ago). I suggest you get the files from an actual CDN (code.angularjs.org is not a CDN, it's only a development service).

**Comment by Narretz** [comment]
You can also still get them via the rawgit cdn: https://cdn.rawgit.com/angular/code.angularjs.org/master/tools/system.js
But if you only need those 2 files at these two versions, it's probably better to include them into your project.
