### ISSUE TITLE
Angular build process does not exit non-zero when it fails to load template

### ISSUE THREAD

**Issue by sgleske-ias** [angular/angular.js#16429]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
gulp build on Mac succeeds but fails on Linux build system (due to case sensitivity difference in the filesystem).  Gulp build process returns a successful "zero" exit code.

**Expected / new behavior:**

When the template fails to be read, the `gulp build` command exits with with a zero exit code (successful build).  However, Jenkins handles errors based on process exit code.  So this will be a misreported success and should have failed, instead.

**Minimal reproduction of the problem with instructions:**

Let's pretend a developer on a Mac names their template file `path/to/somedirective.html`.  The following configuration will succeed because Mac has a case insensitive filesystem.

```
angular.module('someModule')
    .directive('someDirective', function (someReportFactory, $timeout, someEventFactory,
                                        notificationService, someConstants, $mdDialog, $q, $window, someConstants, pollingService) {
        return {
            scope: {
                basePath: '=',
                reportOptions: '=',
                reportInvalidRules: '=',
                reportFieldValidation: '=',
                route: '='
            },
            restrict: 'E',
            templateUrl: 'path/to/someDirective.html',

            controller: function( $scope ) {
....
```

However, on Linux (like a Jenkins build system running builds on Linux) the filesystem is case sensitive so `path/to/someDirective.html` is not the same as `path/to/somedirective.html`.

* **AngularJS version:** ??? I didn't see angular version in `npm-shrinkwrap.json` file.
* gulp-angular-embed-templates 2.2.0
* gulp-json-angular-translate 1.0.0

**Browser:** N/A

**Anything else:**

Example stack trace on Linux:

```
gulp-angular-embed-template [Warning] Can't read template file: "path/to/someDirective.html". Error details: Error: ENOENT: no such file or directory, open 'path/to/someDirective.html'
```

**Comment by Narretz** [comment]
These gulp tasks are not from the core development team, you'll have to open an issue with these projects.

**Comment by frederikprijck** [comment]
@sgleske-ias ,

The build you're using is totally up to you, but so are the problems you encounter with them.
There's nothing we can do, other than tell people to not use uppercasing in their file names. If you do, you should be aware of the issues you can encounter on different filesystems.

It's pretty normal that you'll encounter problems when you use `somedirective.html` as the filename but `someDirective.html`as the templateUrl. This is unrelated to angularjs or gulp.
I don't think opening an issue with gulp, as @Narretz tells you, is needed.

**Comment by sgleske-ias** [comment]
I'll follow up with gulp, thanks.

**Comment by sgleske-ias** [comment]
@frederikprijck please note, this is not user error.  Gulp exits "success" even though it failed to process the template.  It is bad POSIX behavior.

**Comment by frederikprijck** [comment]
@sgleske-ias True, my guess it still isn't a gulp issue but an issue with `gulp-angular-embed-templates` (or whatever library you're using for resolving the urls).

Afaik gulp exists depending on the exit code it receives, but it's probably `gulp-angular-embed-templates` that's sending an incorrect exit code.

**Comment by sgleske-ias** [comment]
Ah, thanks for the pointer.  I'll try to find that project.

**Comment by sgleske-ias** [comment]
Okay, I think I finally have the right place for the issue.  Thanks for your guidance @frederikprijck and @Narretz.

**Comment by frederikprijck** [comment]
Fwiw, this is probably where the issue is happening: https://github.com/laxa1986/gulp-angular-embed-templates/blob/master/lib/Angular1Processor.js#L87 :)

**Comment by sgleske-ias** [comment]
Thanks, I updated the project issue with your findings.
