### ISSUE TITLE
Remove $cookieStore (deprecated since 1.4.0)

### ISSUE THREAD

**Issue by mgol** [angular/angular.js#16425]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 
A removal of a deprecated API.

**Current behavior:**

`$cookieStore` still exists even though it's been deprecated since 1.4.0.

**Expected / new behavior:**

`$cookieStore` shouldn't exist.

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.9

**Browser:** all

**Anything else:**

**Comment by Narretz** [comment]
Done in https://github.com/angular/angular.js/commit/73c6467f1468353215dc689c019ed83aa4993c77

**Comment by mgol** [comment]
Oops, I forgot about the issue.

This was done in PR #16465.
