### ISSUE TITLE
Remove all items deprecated for 1.7.0

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#16423]

**Comment by Narretz** [comment]
Since only cookieStore is deprecated and ready for removal (compared to replace: true which won't be removed), I think this can be closed, since there's an extra issue for cookieStore: https://github.com/angular/angular.js/issues/16425

**Comment by peterblazejewicz** [comment]
Hi,

> Since only cookieStore is deprecated and ready for removal

Can someone review documentation for deprecated items information to be aligned with above for 1.7?

For example the FAQ section states:

> When are deprecated features removed from the library?
Most of the time we remove a deprecated feature in a next minor version bump. For example, the **preAssignBindingsEnabled $compileProvider method was defined in AngularJS 1.5.10, deprecated in 1.6 and will be removed in 1.7.**

https://docs.angularjs.org/misc/faq

We are using docs to make some decisions, should we stick to the 1.7.0 milestone only list as the single source of truth?

Thanks!

**Comment by Narretz** [comment]
preAssignBindingsEnabled has already been removed in master branch and will therefore be gone in 1.7. So yeah the milestone should contain every feature removal that goes into 1.7. There's unfortunately no good way to filter only thise issues / PRs though.

**Comment by peterblazejewicz** [comment]
Thx. I hope you understand my stance here. Some will have to make decision based on probably release notes/milestone details.
Thanks!
