### ISSUE TITLE
CWE-79: Improper Neutralization of Input During Web Page Generation (Cross-site Scripting)

### ISSUE THREAD

**Issue by luxuelei** [angular/angular.js#16426]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

**Current behavior:**

We are using Angular.js 4 for a web portal, while submitting the code for SCA, IBM AppScan reported the following findings in Angular.js libraries:

**CWE-79: Improper Neutralization of Input During Web Page Generation (Cross-site Scripting)**

- No Form Validation Allowed(1)
<pre>
* @param {?} ctx
* @param {?} specs
* @return {?}
*/
function registerContext(ctx, specs) {
    for (var _i = 0, specs_1 = specs; _i < specs_1.length; _i++) {
        var spec = specs_1[_i];
        SECURITY_SCHEMA[spec.toLowerCase()] = ctx;
    }
}
// Case is insignificant below, all element and attribute names are lower-cased for lookup.
</pre><p/>
- JQuery Insecure Manipulation of Child Node(1)
<pre>
        }
        if (this._latestValue === this._latestReturnedValue) {
            return this._latestReturnedValue;
        }
        this._latestReturnedValue = this._latestValue;
        return __WEBPACK_IMPORTED_MODULE_1__angular_core__["WrappedValue"].wrap(this._latestValue);
    };
    /**
    * @param {?} obj
    *
</pre><p/>
**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 4.0.0

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
Hi,

This is the incorrect repo, as this one is for AngularJS.
You probably want to reopen an issue at https://github.com/angular/angular

Thanks.

**Comment by luxuelei** [comment]
Thanks for informing:)

**Comment by frederikprijck** [comment]
@luxuelei You're welcome.

Could you please close this issue to keep the issues clean from incorrect issues? 

Thanks!

**Comment by luxuelei** [comment]
Sorry for disturbing.
