### ISSUE TITLE
API documentation pages for 1.0.x are not displaying correctly

### ISSUE THREAD

**Issue by Kayes-Islam** [angular/angular.js#16435]
![capture](https://user-images.githubusercontent.com/9096105/35787576-1e5c5094-0a7f-11e8-86a2-14c95e1c9a51.PNG)

**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
API documentation pages for AngularJS 1.0.x are broken. For example visit: [https://code.angularjs.org/1.0.5/docs/api/ng.directive:ngModel](https://code.angularjs.org/1.0.5/docs/api/ng.directive:ngModel)

**Expected / new behavior:**

Should show documentation info.

**Minimal reproduction of the problem with instructions:**

Visit [https://code.angularjs.org/1.0.5/docs/api/ng.directive:ngModel](https://code.angularjs.org/1.0.5/docs/api/ng.directive:ngModel) to see the issue.
**AngularJS version:** 1.0.x

This is an issue with 1.0.x version.
**Browser:** [Chrome 63 | Firefox 57 | Edge 38]

**Anything else:**
It was working about a month ago, broken from something recent.

**Comment by petebacondarwin** [comment]
This is caused by the HTML partials (that hold the content for the page) failing to be found on the server which results in the `index.html` being returned instead of the partial. That then happens recursively forever!

We need to look into why the partials are not being found...

**Comment by petebacondarwin** [comment]
The files have been re-uploaded and the site should now work.
