### ISSUE TITLE
Migrate release tasks from Jenkins to CircleCI

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular.js#16443]
Apparently CLI project manages to do this

**Comment by Narretz** [comment]
This is not easily possible, as Circle CI doesn't have the option to start a job from the ui with parameters. 
For reference, the Jenkins task currently does:

* runs build and tests
* tags the commit and pushes it to Github
* pushes build artefacts to bower-angular-* Github 
* publishes to bower
* publishes to npm

**Comment by gkalpak** [comment]
How does CLI do it, then?
(For reference, here is a feature request for [parameterized manually triggered builds][1].)

[1]: https://discuss.circleci.com/t/parameterized-manually-triggered-builds/19633

**Comment by Narretz** [comment]
Sorry, what do you mean by CLI?

**Comment by gkalpak** [comment]
From https://github.com/angular/angular.js/issues/16443#issue-295282037:

> Apparently CLI project manages to do this

<sub>(I assume @petebacondarwin meant `@angular/cli`.)</sub>

**Comment by petebacondarwin** [comment]
Perhaps the use Jenkins?
