### ISSUE TITLE
Developer guide is missing navigation controls on iOS

### ISSUE THREAD

**Issue by jessebarnum** [angular/angular.js#16448]
**I'm submitting a ...**

- [x ] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Development guide is not usable on an iPad, because the navigation sidebar on the left is not accessible.

**Expected / new behavior:**

Position navigation sidebar at top, bottom, or both when using an iPad

**Minimal reproduction of the problem with instructions:**

View https://docs.angularjs.org/guide on an iPad. Try to navigate to section on 'directives'

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

iOS 11.2.1

**Anything else:**

I couldn't find a good way to submit feedback specific for documentation. There is a button titled 'Improve this doc,' but that doesn't seem to be a way to provide feedback - it wants you to fork the repository.

**Comment by gkalpak** [comment]
Good spot :smiley:
It turns out some `@media` breakpoints were off-by-one causing the site to not be displayed properly as exactly 767px or 768px. (And it turns out iPad is 768px wide :grin:)
Should be fixed by #16449.
