### ISSUE TITLE
ng-show/hide + scrollTo looks bad on firefox and safari

### ISSUE THREAD

**Issue by Geddard** [angular/angular.js#16444]
Hi there guys, i’m asking for help here because i don’t know where to go anymore.

I’m trying to handle some SPA-ish navigation in a mobile page. Using angular 1.6 and twig mainly.

I have a root page with sections like "description, features, details, etc"
Each link is simply an anchor that adds the hash to the url by clicking.

Then with angular i listen for location change, and swap the root component for one of these sub-pages using ng-show/hide based on variables.

Then the problem is that when i do these swapping and subsequently scroll the page (either to the top for subpages or to the previous scroll position in root) there’s a flicker very visible in firefox and safari, maybe it's because it takes the browser a few milliseconds too long to trigger the window.scrollTo(0,0) after doing $digest().

I've also tried doing this the "angular" way, by trying to swap states and scroll from an ng-click action... same result.

This happens in Firefox and Safari only… chrome handles these steps perfectly smoothly… any suggestions or ideas?

Thanks and regards, Javier.-

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

BTW, for these types of question it is helpful to include a minimal reproduction (e.g. a live example using CodePen, Plnkr, etc).

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
