### ISSUE TITLE
Latest versions missing from Google API CDN

### ISSUE THREAD

**Issue by chet-manley** [angular/angular.js#16440]
**I'm submitting a ...**

- [X] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

Versions 1.6.8 && 1.6.9 are missing from Google CDN.

**Expected / new behavior:**

Current versions of package would load as expected.

**Minimal reproduction of the problem with instructions:**

`https://ajax.googleapis.com/ajax/libs/angularjs/1.6.x/angular.min.js`
[1.6.8](https://ajax.googleapis.com/ajax/libs/angularjs/1.6.8/angular.min.js)
[1.6.9](https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js)
As well as related angular-x related packages are missing for these version numbers.

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

N/A

**Anything else:**

**Comment by petebacondarwin** [comment]
We are waiting on a Googler to push these to the CDN.

**Comment by Narretz** [comment]
The Versions are now on the CDN
