### ISSUE TITLE
angularjs docs SEO results significantly dropped on google.com

### ISSUE THREAD

**Issue by barakd** [angular/angular.js#16447]
Hi, might be connected to #16417 and similar to #16432 but not entirely the same, so I am opening a new issue.

**Current behavior:**
It seems that after the move to use firebase hosting, the google search results for any angularJS related search have significantly dropped.
Any searches for angularJS related stuff will place angularJS website very low at the first page, or not at the first page at all (which makes searching for angularJS docs from google really hard)
![image](https://user-images.githubusercontent.com/7824284/36070815-eedd71a4-0f0b-11e8-93a9-3198284afcfa.png)

**Expected / new behavior:**
AngularJS is back on the top of the first page like it used to be.

**Minimal reproduction of the problem with instructions:**
google "[angularjs ngmodel controller](https://www.google.co.il/search?q=angularjs+ngmodel+controller)"

**Comment by Narretz** [comment]
Hi, it must be related to https://github.com/angular/angular.js/issues/16432. Basically the Crawler can't index the pages like before. We are working on a fix though. Thanks for the head's up.
