### ISSUE TITLE
Ionic 1 push notification not work

### ISSUE THREAD

**Issue by BidhanMaiti** [angular/angular.js#16454]
cli packages: ()

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : not installed

local packages:

    Cordova Platforms : android 6.2.3 ios 4.4.0
    Ionic Framework   : ionic1 1.1.0

System:

    Node : v9.2.0
    npm  : 5.5.1
    OS   : Windows 10
Use Plugin is  ---------com.phonegap.plugins.PushPlugin
code
 var androidConfig = {
              'senderID': '****************'
            };

            $cordovaPush.register(androidConfig).then(function(result) {
              console.log("android success");
            }, function(err) {
              console.log("android failure: "+ result);
            })        

            var onPushReceivedListener = $rootScope.$$listeners['$cordovaPush:notificationReceived'];
            if(onPushReceivedListener && onPushReceivedListener.length > 0)
              return; // in order to avoid multiple calls of listened function

            $rootScope.$on('$cordovaPush:notificationReceived', function(event, notification) {
              var cachedDeviceToken = CacheService.getDeviceToken();
              switch(notification.event){
                    //case where device regid is returned from firebase
                    case 'registered':
                      console.log(notification.regid);
                      console.log(cachedDeviceToken);
                      // if(cachedDeviceToken != notification.regid){
                          DataService.saveToken(notification.regid +"*gcm")
                          .then(function(){
                              CacheService.saveDeviceToken(notification.regid);
                          });
                      // }
                      break;
                    //case where actual message is received
                    case 'message':
                      if(notification.foreground == 1){
                        $cordovaVibration.vibrate(500);
                      }
                      
                      //added because Android adds the extra parameters to the payload object(i think)
                      notification.messageType = notification.payload.messageType;
                      notification.alert = notification.message;

                      PushNotificationService.processPushNotification(notification);
                      
                      if(notification.messageType == PUSH_NOTIFICATION_TYPES.EVENT_INVITATION){
                        $scope.updateBadge(EVENT_STATUS.PENDING, 1);
                        $rootScope.$broadcast(APP_EVENTS.PUSH_INVITATION_RECEIVED);
                      }
                      break;
                    //in case something goes wrong
                    case 'error':
                      console.log('GCM error = ' + notification.msg);
                      break;

                    default:
                      console.log('An unknown GCM event has occurred');
                      break;
              }
            });
everytime notification.event return register not return message. please help me

**Comment by Narretz** [comment]
The repo for ionic is here: https://github.com/ionic-team/ionic-v1

You probably want to look at the plugin you are using, though
