### ISSUE TITLE
Files are now missing (roughly 8 days) from https://code.angularjs.org/

### ISSUE THREAD

**Issue by GregKass** [angular/angular.js#16450]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

There is no CDN access currently available for ```https://code.angularjs.org/tools/``` files or ```https://code.angularjs.org/2.0.0-xxx.xx/``` files. If these files are no longer supported here please provide a link to their current available location.

**Expected / new behavior:**

These files would be available or info would be given pointing to their new location.

**Minimal reproduction of the problem with instructions:**

go to https://code.angularjs.org/ . These files are no longer there.

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Anything else:**

**Comment by Narretz** [comment]
The files are not coming back. These are files for the "new" Angular, but we stopped adding files to this url quite a while ago.
You can find the files in this Github repo: https://github.com/angular/code.angularjs.org and serve them with https://rawgit.com/
Note that code.angularjs.org is not a CDN. It's strictly for development purposes and for hosting old docs only.
