### ISSUE TITLE
input value does not get updated as page loads 

### ISSUE THREAD

**Issue by Sillergeoduck** [angular/angular.js#16462]
**I'm submitting a ...**

- [ ] bug report

**Current behavior:**

When i bind the model value , unless i click inside the input text box the model value is not updated .. 

**Expected / new behavior:**

I would like the model value updated with the current value as the page renders , but instead it renders only when i focus on the input text box 

http://embed.plnkr.co/P5hoQ2/
 please check the above plunk , in that with precision input text box , unless i click inside the text box the value does not show up i.e.. 0.5 

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by petebacondarwin** [comment]
I'm afraid that this looks like a bug in the `numbersOnly` library and not in AngularJS.
From a brief look at their directive it is not rendering correctly until one of its event handlers is triggered.
Please submit a bug at https://github.com/willmendesneto/ng-numbers-only.
