### ISSUE TITLE
Docs - h3 heading misaligned inside div

### ISSUE THREAD

**Issue by SeanPrashad** [angular/angular.js#16468]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
The `h3` heading for "[TypeScript interfaces aren't valid tokens](https://angular.io/guide/dependency-injection#typescript-interfaces-arent-valid-tokens)" is misaligned within its `div`.

**Expected / new behavior:**
The `h3` heading should be visually left aligned within it's `div` to maintain consistency with other sections.

**Minimal reproduction of the problem with instructions:**
Open Angular's documentation for  "[TypeScript interfaces aren't valid tokens](https://angular.io/guide/dependency-injection#typescript-interfaces-arent-valid-tokens)"

GIF of bug:

![angularheadingbug](https://user-images.githubusercontent.com/13009507/36607521-ddb6b7b8-1894-11e8-80a5-7b2ae6715179.gif)

**AngularJS version:** 1.6.9

**Browser:** [ Chrome Version 64.0.3282.167 (Official Build) (64-bit) | Firefox 58.0.2 (64-bit) ]

**Anything else:**
Upon closer inspection inside Chrome's dev tools, it looks like the heading isn't being properly aligned for a CSS reason:

<img width="1203" alt="screen shot 2018-02-23 at 12 34 03 pm" src="https://user-images.githubusercontent.com/13009507/36607834-e6b0ce7a-1895-11e8-8477-02c134630751.png">

**Potential Fix**: A potential fix might be adding `padding-left: 34px;` to `.l-sub-section h3` found in `_subsection.scss:13`. This would result in the following:

<img width="1083" alt="screen shot 2018-02-23 at 12 37 53 pm" src="https://user-images.githubusercontent.com/13009507/36608055-9f8b04c4-1896-11e8-925d-e085e57539de.png">

**Comment by Narretz** [comment]
Hi, please reopen this issue here:https://github.com/angular/angular/issues Thanks!

**Comment by SeanPrashad** [comment]
Reopened [here](https://github.com/angular/angular/issues/22407)
