### ISSUE TITLE
App already bootstrapped with this element '<body class="ng-scope">'

### ISSUE THREAD

**Issue by pcbsytem** [angular/angular.js#16475]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by Narretz** [comment]
https://docs.angularjs.org/error/ng/btstrpd
