### ISSUE TITLE
HashChange events stop firing when an ng-include exists on the page

### ISSUE THREAD

**Issue by chriscalo** [angular/angular.js#1647]
Load the following HTML document into a browser and can click the links to see the `Partial:` string update along with the hash. (Modifying the hash in the location bar also works.) The problem comes in as soon as you uncomment the `div[ng-include]`: the `hashchange` events stop firing.

```
<!DOCTYPE html>
<html ng-app>
  <head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.3/angular.js"></script>
    <script>
      function Router($scope) {
        if (location.hash === "") location.hash = "#/";
        $scope.view = createView(location);
        window.addEventListener("hashchange", function (event) {
          $scope.view = createView(event.newURL);
          $scope.$apply();
        });
      }
      function createView(url) {
        var parser = document.createElement("a");
        parser.href = url.toString();
        var hash = builder.hash;
        return (hash.replace("#/", "/views/") + "/index.html").replace("//", "/");
      }
    </script>
  </head>
  <body ng-controller="Router">
    Navigation:
    <a href="#/one/">one</a>
    <a href="#/two/">two</a>
    Partial: {{view}}
    <!--<div ng-include="view"></div>-->
  </body>
</html>
```

Am I doing something wrong or is this a bug?

**Comment by gkalpak** [comment]
This seems to work fine with 1.6.1 (probably 1.5.10 too - didn't check). In older versions, there should have been some issue with `$location` (which has been fixed at some point). The reason it was affected by `ngInclude` is that `ngInclude` depends on `$anchorScroll`, which in turn depends on `$location`. So, as soon as you uses `ngInclude` in your template, `$location` would be instantiated and mess things up.

Closing as _fixed_.
