### ISSUE TITLE
Find out more link down

### ISSUE THREAD

**Issue by julmot** [angular/angular.js#16472]
This link:

https://github.com/angular/angular.js/blob/master/misc/version-support-status

refers to a 404 page.

![topic](https://user-images.githubusercontent.com/8310677/36670570-0c5793ce-1af9-11e8-8067-f0fde71a59d9.png)

**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Comment by frederikprijck** [comment]
The url that's supposed to be loading is: https://github.com/angular/angular.js/blob/master/docs/content/misc/version-support-status.ngdoc

Navigating throughout the [docs](https://docs.angularjs.org/api) site works fine and navigates to [the status page](
https://docs.angularjs.org/misc/version-support-status).

However, the readme is incorrect.

/cc @petebacondarwin
