### ISSUE TITLE
My issue

### ISSUE THREAD

**Issue by ss-saranya** [angular/angular.js#16487]
I used directive to reuse the code. Here is my html form
<md-input-container
            class="phx-ic"
            flex-gt-sm="30"
            flex-offset-gt-xs="15"
        > <label data-translate="{{label}}"></label> <input
            id="phx_address_{{$id}}"
            name="phx_address_{{$id}}"
            type="text"
            autocomplete="off"
            ac-address-complete
            md-no-asterisk
            phx-model="ngModel"
            ng-model="addressLabel"
            required
            phx-pobox-allowed="phxPoboxAllowed"
        >
		
        <div ng-messages="this['phx_address_{{$id}}'].$error" >
            <div
                ng-message="required"
                data-translate="lapp.loc.error.required"
            ></div>
            <div
                ng-message="nopobox"
                data-translate="lapp.loc.nopobox"
            ></div>
        </div>
        </md-input-container>

This is my directive used
angular.module('cccgatewayApp').directive('phxAddress', phxAddress);
	phxAddress.$inject = [ '$translate', '$translatePartialLoader' ];

	function phxAddress($translate, $translatePartialLoader) {
		var directive = {
			restrict : 'EA',
			require : '^form',
			transclude : true,
			scope : {
				ngModel : "=ngModel",
				label : '@label',
				ngRequired : '&ngRequired',
				phxPoboxAllowed : '=phxPoboxAllowed'
			},
			templateUrl : 'app/components/util/phx.address.tmpl.html',
			link : function($scope, $element, $attrs, $formCtrl) {
				$scope.form = $formCtrl.$name;
				
				console.log('=========', $scope.form);

				$translatePartialLoader.addPart('summary');
				$translatePartialLoader.addPart('lapp');
				$translate.refresh();
				
			
			}
		};
		return directive;
	}
})();

ng-messages are not working. Could anyone help me with this?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
