### ISSUE TITLE
How to search data from Elastic search using angularjs 1.6.4 

### ISSUE THREAD

**Issue by digitalaapt** [angular/angular.js#16483]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

I tried elastic search with angularjs 1.6.4  Elastic search documentation
**Expected / new behavior:**

if elastic search with angularjs well documented 
**Minimal reproduction of the problem with instructions:**
 Here is my code:
const elasticsearch = require('elasticsearch');

const hostname = process.argv[2] || 'localhost';
const password = process.argv[3] || 'password';
const host = `http://user:${password}@${hostname}/elasticsearch`;

var client = new elasticsearch.Client({
  host: host,
  log: 'trace',
  header: {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Allow-Headers':'Origin, Content-Type, X-Auth-Token',
    'Access-Control-Allow-Methods':'GET, POST, PATCH, PUT, DELETE, OPTIONS',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
  }
});

client.ping({
  // ping usually has a 3000ms timeout
  requestTimeout: 1000
}, function (error) {
  if (error) {
    console.trace('elasticsearch cluster is down!');
  } else {
    console.log('All is well');
  }
});

client.search({
  index: 'myindex',
  q: 'title:test'
}, function callback(error, response) {
  if (error) {
    client.create({
      index: 'myindex',
      type: 'mytype',
      id: '1',
      body: {
        title: 'test',
        tags: ['y', 'z'],
        published: true,
        published_at: '2013-01-01',
        counter: 1
      }
    }, function (error, response) {
      if (error) {
        console.trace(error);
      } else {
        console.log(`Created myindex: ${JSON.stringify(response)}`);
      }
    });
  } else {
    console.log(`Found myindex: ${JSON.stringify(response)}`);
  }
});

**AngularJS version:** 1.6.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

![els1](https://user-images.githubusercontent.com/37169638/37135769-dac85a22-22c4-11e8-8072-39cfed7a175f.png)
![els2](https://user-images.githubusercontent.com/37169638/37135774-df0bd21c-22c4-11e8-975e-2039f44de812.png)
![els3](https://user-images.githubusercontent.com/37169638/37135778-e1e05e68-22c4-11e8-8371-c0ef481659e2.png)

Thanks in advance,
Subrata Nandi

**Comment by frederikprijck** [comment]
This looks like either something that belongs to the elastic-search repo/community or just a CORS issue.
Nevertheless, it doesn't seem to be related to AngularJS. 

Please do note, GitHub issues are reserved for bug reports and feature requests related to AngularJS. If you need assistance regarding AngularJS, please try one of the [appropriate channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).
