### ISSUE TITLE
require is undefined in angularjs any solution for this?

### ISSUE THREAD

**Issue by aizen27** [angular/angular.js#16484]
i'm using angularjs 1.6 version, and im going to add a sms feature. i was going to add twilio or nexmo while in the process of research i stumbled that they are coded in node.js .
i tried to put it in my code what i find in their docs. and though it would work.
but, i can't make it work the thing is "require = ('nexmo or twilio')" is getting error message that require is undefined. how do i resolved this? i search the web for this any i found many that are having the same issues as i do. but, i hav'nt seen any solutions yet.
is there a way to make require work in angularjs 1?
![require](https://user-images.githubusercontent.com/34813460/37248826-073bbb28-2516-11e8-8466-ac4639f09fe0.PNG)

**Comment by frederikprijck** [comment]
Hey, GitHub issues are reserved for bug reports and feature requests related to AngularJS. If you need assistance regarding AngularJS, please try one of the [appropriate channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).

---
The issue you're facing doesn't seem to be related to AngularJS. The information you provide is very limited, and this is not the best place to find appropriate support for this kind of issues.

Using `require` in your code (whether it's an AngularJS, React of VanillaJS project) require's the use of a module loader, as by using `require` you're basically loading a certain module.

Have a look at things like `webpack`, which are created for this kind of things. (you can have a look at https://github.com/frederikprijck/angularjs-webpack-starter , which uses webpack together with TypeScript and ES6 `import/export`. This isn't alot different from `require`when it comes to webpack configuration.

Anyway, not much we can do from AngularJS side to resolve this issue. Be sure to also have a look at stackoverflow, as you've noted there's plenty of people having the same issue (even without using angularjs): https://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined
