### ISSUE TITLE
how to retrieve data via an url and display it

### ISSUE THREAD

**Issue by leslie971** [angular/angular.js#16499]
I would like to recuperate the data sent by url http://127.0.0.1:8000/api/entry/?format=json  and be able to display them in the geonode home page.(index.html)
  url call with JQUERY AJAX?
my api file is like https://django-tastypie.readthedocs.io/en/latest/tutorial.html

I tried something like this:

<script> $(document).ready (function () { $("div1").load( URL); }); </script>
<div id="div1">  </div>
how to get each object and display each ?
with ng-repeat ?

thanks

**Comment by leslie971** [comment]
this is the data format send by url 


{"meta": {"limit": 200, "next": null, "offset": 0, "previous": null, "total_count": 3}, "objects": [{"body": "corps admin", "id": 1, "pub_date": "2018-03-16T10:24:52", "resource_uri": "/api/v1/entry/1/", "slug": "1ere-entry", "title": "1ere entry"}, {"body": "corps tesla\r\n", "id": 2, "pub_date": "2018-03-16T10:25:16", "resource_uri": "/api/v1/entry/2/", "slug": "2eme-entry", "title": "2eme entry"}, {"body": "corps admin3", "id": 3, "pub_date": "2018-03-16T10:27:57", "resource_uri": "/api/v1/entry/3/", "slug": "3-eme-entry", "title": "3 eme entry"}]}

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
