### ISSUE TITLE
Controller not registered

### ISSUE THREAD

**Issue by HoogleyBoogley** [angular/angular.js#16497]
**I'm submitting a ...**

- [X ] bug report
- [   ] feature request
- [   ] other 

**Current behavior:**
I get an error saying my controller is not registered

**Expected / new behavior:**
That the controller would be registered

**Minimal reproduction of the problem with instructions:**
```
(function () {
    var app = angular.module('Portfolio', []);
    app.controller('RegisterController', ['$scope', '$state', '$http', 
        function ($scope, $state, $http) {
            $scope.generateUser = function() {
                console.log($scope.createUser);
                $http.post('api/user/register', $scope.createUser).success(function(res) {

                }).error(function(error) {
                    console.log(error);
                })

            }

    }]);
}); 

```
**AngularJS version:** 1.6.9

**Browser:** Chrome

**Anything else:**
None

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

btw you probably have a typo somewhere in your template

**Comment by HoogleyBoogley** [comment]
By template do you mean my HTML file?

**Comment by Narretz** [comment]
Yes. You probably have the wrong name in the template or in the controller registration itself.
