### ISSUE TITLE
HTML5 File API support and XHR progress

### ISSUE THREAD

**Issue by sduduzog** [angular/angular.js#16508]
**I'm submitting a ...**

- [ ] bug report
- [ X] feature request
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

Basically one has to use a hack in listening for an onchange event and then reading a file from user input. Also uploading files could show progress just like the XHR2
**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
Have you tried something like https://github.com/danialfarid/ng-file-upload ?

Also, be sure to read 
- https://github.com/angular/angular.js/issues/1375#issuecomment-43820650
- https://github.com/angular/angular.js/issues/1236
