### ISSUE TITLE
Have been wrong when installing ngx-admin

### ISSUE THREAD

**Issue by jsjjl** [angular/angular.js#16509]
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!.
/node_modules/sass-loader/lib/loader.js??ref--8-3!./src/app/@theme/styles/styles
.scss
Module build failed:
undefined
        ^
      Mixins may not be defined within control directives or other mixins.
      in E:\ngx-admin\node_modules\@nebular\theme\components\checkbox\_checkbox.
component.theme.scss (line 8, column 10)

**Comment by frederikprijck** [comment]
@jsjjl I don't see any reason why this would be related with angularjs.

/cc @Narretz @gkalpak @petebacondarwin  This can be closed.

**Comment by gkalpak** [comment]
@jsjjl, this sounds related to `ngx-admin`. Try asking on their repository or support channels.
