### ISSUE TITLE
Ui-Select AutoClose outside issue on iPhone/iPad

### ISSUE THREAD

**Issue by mayankagrawal-newgen** [angular/angular.js#16513]
**I'm submitting a ...**

- [x] bug report
- [x] feature request
- [x] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by gkalpak** [comment]
This issues is not related to core AngularJS. Try posting on `ui-select`'s repo or support channels.
