### ISSUE TITLE
Tutorial Issue

### ISSUE THREAD

**Issue by jknepfle** [angular/angular.js#16524]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

If you follow the instructions on https://docs.angularjs.org/tutorial and have Chrome 65 installed, you get an error when executing "npm run protractor".

Error:
 Message:
    Failed: unknown error: call function result missing 'value'
      (Session info: chrome=65.0.3325.181)
      (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)

**Expected / new behavior:**

No error. 
**Minimal reproduction of the problem with instructions:**

Take the tutorial on a Windows machine using Windows 10 64bit and Chrome 65. When you get to the step npm run protractor, you'll get the above error message.

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

Changing \angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\config.js from:
{
  "webdriverVersions": {
    "selenium": "2.53.1",
    "chromedriver": "**2.26**",
    "geckodriver": "v0.11.1",
    "iedriver": "2.53.1",
    "androidsdk": "24.4.1",
    "appium": "1.6.0"
  },
  "cdnUrls": {
    "selenium": "https://selenium-release.storage.googleapis.com/",
    "chromedriver": "https://chromedriver.storage.googleapis.com/",
    "geckodriver": "https://github.com/mozilla/geckodriver/releases/download/",
    "iedriver": "https://selenium-release.storage.googleapis.com/",
    "androidsdk": "http://dl.google.com/android/"
  }
}

to 

{
  "webdriverVersions": {
    "selenium": "2.53.1",
    "chromedriver": "**2.37**",
    "geckodriver": "v0.11.1",
    "iedriver": "2.53.1",
    "androidsdk": "24.4.1",
    "appium": "1.6.0"
  },
  "cdnUrls": {
    "selenium": "https://selenium-release.storage.googleapis.com/",
    "chromedriver": "https://chromedriver.storage.googleapis.com/",
    "geckodriver": "https://github.com/mozilla/geckodriver/releases/download/",
    "iedriver": "https://selenium-release.storage.googleapis.com/",
    "androidsdk": "http://dl.google.com/android/"
  }
}

Appears to fix the problem.

**Comment by glenpike** [comment]
Ditto for me, except the files were in node_modules\protractor\node_modules\webdriver-manager\built\config.json and I updated Chromedriver to 2.40
