### ISSUE TITLE
Tutorial steps/chapters not corresponding to tutorial description/Live Demo/branches

### ISSUE THREAD

**Issue by pmyszkier** [angular/angular.js#16534]
**I'm submitting a ...**

> - [x] bug report
> - [ ] feature request
> - [ ] other 

**Current behavior:**

> **See for example: https://code.angularjs.org/1.3.15/docs/tutorial:** 
> **Tutorial: 3** - Filtering Repeaters ( https://code.angularjs.org/1.3.15/docs/tutorial/step_03 ) says: "The app now has a search box" . But in Live Demo ( http://angular.github.io/angular-phonecat/step-3/app/ ) there is no search box . Branch step-3 (`git checkout -f step-3`) is wrong for this chapter 3.
> **Tutorial: 4** - Two-way Data Binding ( https://code.angularjs.org/1.3.15/docs/tutorial/step_04 ) says: "In addition to the search box, the app displays a drop down menu..." . But in Live Demo ( http://angular.github.io/angular-phonecat/step-4/app/ ) there is no dropdown menu and no search box . Branch step-4 (`git checkout -f step-4`) is wrong for this chapter 4.
> **Tutorial: 5** - XHRs & Dependency Injection ( https://code.angularjs.org/1.3.15/docs/tutorial/step_05 ) says: "There is now a list of 20 phones..." . But in Live Demo ( http://angular.github.io/angular-phonecat/step-5/app/ ) there is a list of 3 phones, not 20 phones . Branch step-5 (git checkout -f step-5) is wrong for this chapter 5.
> **Tutorial: 6** - Templating Links & Images( https://code.angularjs.org/1.3.15/docs/tutorial/step_06 ) says: "There are now links and images of the phones in the list." . But in Live Demo ( http://angular.github.io/angular-phonecat/step-6/app/ ) there is no links and images of phones . Branch step-6 (git checkout -f step-6) is wrong for this chapter 6.
> **etc...**

**Expected / new behavior:**

> Can You fix it? It is needed to change the Live demo and branches numbers.

**Minimal reproduction of the problem with instructions:**

> It is needed to change the Live demo and branches numbers. 

**AngularJS version:** 

> 1.3.15

> Tested in tutorial version 1.3.15, but bugs are also in other versions

**Browser:** 

> [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
> Tested in Chrome and FF but it is not a bug depending on browser

**Anything else:**

> No, thanks.

**Comment by Narretz** [comment]
Well, two things are strange here. First, you are using a very old version of angulat (1.3.15) to check the tutorial. The tutorial has changed since this version, so you should definitely start with the version that is shown here: https://docs.angularjs.org/tutorial. Second, where did you get the link to the live demo? As far as I know, this isn't really "advertised". The tutorial is supposed to be done as a learning experience, so a live version isn't really useful.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Leave a comment if you can provide new feedback.
