### ISSUE TITLE
Unable to use ng-model-options on the same tag as ng-app when ng-app is on html tag

### ISSUE THREAD

**Issue by mdelorimier** [angular/angular.js#16535]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

When using ngModelOptions on the same tag as the ngApp, the value of defaultModelOptions gets set to undefined. This causes errors for every ngModel directive in the template.
The error seems to come from NgModelOptionsController $onInit where the parentOptions is undefined and the createChild method can't be executed.

**Expected / new behavior:**

There should not be an error when a ngModelOption is defined on the same tag as an ngApp.
Or, it should be present in the migration documentation.

**Minimal reproduction of the problem with instructions:**

https://plnkr.co/edit/jOmVWDvIFuOyOWB2

**AngularJS version:** 1.6.10

**Browser:** Chrome 65, probably in all browsers

**Anything else:**

**Comment by Narretz** [comment]
Hi, thanks for the report. From which version did you upgrade to 1.6.10?

**Comment by mdelorimier** [comment]
15.11

Le sam. 21 avr. 2018 08:38, Martin Staffa <notifications@github.com> a
écrit :

**Comment by Narretz** [comment]
Marke it as a regression. I'm not sure we'll do another 1.6. release, though - maybe you'll have to upgrade to 1.7 straight.

**Comment by mdelorimier** [comment]
Ok, nous problème. I have found a workaround by moving the ngModelOptions
elsewhere

Le mar. 24 avr. 2018 09:50, Martin Staffa <notifications@github.com> a
écrit :

**Comment by Narretz** [comment]
Just noticed that this only happens when ngApp is on the html tag - maybe that's because this is the top most tag in an html document.
