### ISSUE TITLE
Two time API call on server using Angular Js Code

### ISSUE THREAD

**Issue by jaiminrockersinfo** [angular/angular.js#16536]
Hello,

We have using angularJS for front-end and Laravel api for backend.
In Local server API successfully call but in my live server first API call with **Request Method: OPTION** 
and another **API** call with **Request Method: GET** 

Using this process loading take too much time in my server 
How to solve two time api call issue in my server?

Please check below screen short for more details.
**Request Method: OPTION**
![2018-04-22 1](https://user-images.githubusercontent.com/11418918/39109347-234405b4-46ea-11e8-8b41-86f26cbad932.png)

 **Request Method: GET**
![2018-04-22-getmethod](https://user-images.githubusercontent.com/11418918/39109411-74f2ed08-46ea-11e8-9eda-a63a700b7b0c.png)

**Comment by frederikprijck** [comment]
Hi,

This is expected behavior and has nothing to do with AngularJS. Please have a look at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS, especially the part about **preflight** requests.

**Comment by jaiminrockersinfo** [comment]
My backend and frontend served form different origin and I have allready CORS define in backend using .htaccess

**Comment by frederikprijck** [comment]
@jaiminrockersinfo Please read the article, this is how CORS works. CORS does an OPTION call prior to your actual call to detect the call is allowed from another origin.
