### ISSUE TITLE
RequireJS + AngularJS

### ISSUE THREAD

**Issue by LegitSoulja** [angular/angular.js#16538]
I've been trying to figure out a way around this but, I am creating a fully module site which I am using requirejs to load libraries cause I hate working in one javascript file for everything.

So, I figured I cannot load modules before dom is loaded, but after. So I tried putting my require script in head hoping it'll load all the libraries, angular module and controllers, but apparently that doesn't work, even just requiring one file....

Any way that I can register my controllers when libraries has loaded? I've read about the lazyLoader but honestly what if all controllers requires this one library, and it'll be a hassle loading all files with proper directory when with requirejs you define the library folder, and require the name of the lib you want which makes everything easier.

Any thoughts? Thanks.

If using lazyLoader is the only option, then i may have to ditch requirejs and make like a requirejs for php in which grabs all *.js files and put script tags in header before angular and controller. 

I also wanted to put all scripts before the body tag (For faster page loading). Is that even possible with angularjs?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by gkalpak** [comment]
> Why shall I go ask some random person for help on something that is so simple to be explained?

[This][1] is why.

> Clearly, I don’t think you know how stackoverflow and the reputation works.

I clearly don't know, but [this guy][2] might have a rough idea :wink:

> Guess I won’t use angularjs then.

That is clearly up to you :smiley:
(In fact, AngularJS (v1.x) is about to enter [Long Term Support mode][3] and not receive any new features, etc. So, if you are starting now, it is not recommended to invest into learning AngularJS. [Angular][4] (v2+) is the new and shiny version you should look into, if you decide to go that way.)

Good luck!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://stackoverflow.com/users/2341938/gkalpak
[3]: https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c
[4]: https://github.com/angular/angular

**Comment by LegitSoulja** [comment]
@gkalpak 

> So, if you are starting now, it is not recommended to invest into learning AngularJS. Angular (v2+) is the new and shiny version you should look into, if you decide to go that way.)

I like the regular angularjs, I don't really like the new era nodejs. But there's no need for me to invest in learning angular because it's a waste of my time. I'd rather make something of my own similar to angular that does that job I need instead of all of this extra stuff.
