### ISSUE TITLE
View not loading css and js

### ISSUE THREAD

**Issue by DaoFof** [angular/angular.js#16532]
Hi guy, I have created a simple angularjs app with component and view
When I include directly component in index.html everything work fine but as my app requires multiple view, I am shifting to view but my view when loaded does not get affected by css and js

Index.html 
![index](https://user-images.githubusercontent.com/26028753/38792291-ea56e49a-4169-11e8-88c5-6d32137177de.png)

App.js

'use strict';

// Declare app level module which depends on views, and components
angular.module('myApp', [
  'ngRoute',
  'myApp.view1',
  'myApp.view2',
  'sidebar',
  'topnavbar',
])

view1.module

'use strict';

angular.module('myApp.view1',
 ['ngRoute',
 'knob',
 'slider',
 'select2',
 'rangeslider',
 'pickers',
 'inputswitcher',
 'cropper',
 'btscheckbox']);

View1 Template
![view1](https://user-images.githubusercontent.com/26028753/38792345-2e47e5dc-416a-11e8-8ae3-b72bb161bde7.png)

A part of page when component include directly to index
![withcss](https://user-images.githubusercontent.com/26028753/38792443-9bfa3f62-416a-11e8-9996-c553077fcb71.png)

When component loaded from view 
![without](https://user-images.githubusercontent.com/26028753/38792458-abeafb0a-416a-11e8-9186-bb3ec487187b.png)

Help plz

**Comment by frederikprijck** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) for these types of questions.
GitHub issues are reserved for bug reports and feature requests.

Thx!
