### ISSUE TITLE
Component bindings with validators and default values

### ISSUE THREAD

**Issue by madflow** [angular/angular.js#16530]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

```angular.component()``` bindings can only contain a scalar definition (```<, @, &```). 

**Expected / new behavior:**

The bindings definition can be a "map" of types, validators and default values. For an example please see the Vue component ```Props```:

https://vuejs.org/v2/guide/components-props.html#Prop-Validation

**Currently**: 
```JS
let com = {
  bindings: {
    active: '<'
  }
}
```
**New Feature:**
```JS
let com = {
  bindings: {
    active: {
         type: '<',
         required: true,
         default: false,  
         validator: function (value) {}
    }
  }
}
```

**AngularJS version:** >= 1.6

**Comment by gkalpak** [comment]
This is similar to #11657 and #13698. I don't think it makes sense to implement this in AngularJS at this point given that:

1. It is heading towards [LTS/maintainance mode][1].
2. Angular (v2+) components (which `.component()` and `bindings` are supposed to resemble) does not have a similar feature.
3. It would require significant changes to the codebase and introduce new paradigms.

If you think it is a useful feature, it might make sense to open a discussion about it for Angular (v2+) here: https://github.com/angular/angular

[1]: https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c
