### ISSUE TITLE
sameSite cookie support

### ISSUE THREAD

**Issue by arkadiyt** [angular/angular.js#16543]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

Right now the angular [cookie options](https://docs.angularjs.org/api/ngCookies/provider/$cookiesProvider#defaults) support setting domain, expiration, and secure flags, but do not support the `sameSite` flag. 

**Expected / new behavior:**

I'd like to request that support be added for the `sameSite` flag - this would help protect against CSRF attacks using cookies created by angular.

**Minimal reproduction of the problem with instructions:**

N/A

**AngularJS version:** 1.6.11

**Browser:** [Chrome >= 63 | Firefox >= 60 | Mobile Chrome >= 64]

Pulled via https://caniuse.com/#search=samesite

**Anything else:**

**Comment by petebacondarwin** [comment]
Here is some background info: http://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/

**Comment by petebacondarwin** [comment]
This seems like a reasonable request. I would say that changes need to go here: https://github.com/angular/angular.js/blob/master/src/ngCookies/cookieWriter.js#L35
With the new option being documented appropriate throughout the `ngCookies` module.

**Comment by arkadiyt** [comment]
Thanks so much for getting this merged!

>  is only implemented by Chrome (since 2016) and soon Firefox (currently in Firefox beta)
Edge has also announced support now: https://twitter.com/MSEdgeDev/status/997145602474430464
