### ISSUE TITLE
Multiple directives [mdTabs (module: material.components.tabs), ngSortable] asking for new/isolated scope on:

### ISSUE THREAD

**Issue by GNSubrahmanyam** [angular/angular.js#16540]
Hi,
I am  trying to use [ng-sortable](https://github.com/RubaXa/Sortable/) with md-tabs.

Error: [$compile:multidir] http://errors.angularjs.org/1.5.3/$compile/multidir?p0=mdTabs&p1=%20(module%3A%20material.components.tabs)&p2=ngSortable&p3=&p4=new%2Fisolated%20scope&p5=%3Cmd-tabs%20ng-sortable%3D%22%7Bgroup%3A%20'ng'%2C%20animated%3A%20250%7D%22%20md-border-bottom%3D%22%22%3E

code:
https://codepen.io/GNSubrahmanyam/pen/BxLmwV?editors=1111

Please help me to fix this error. 

Thanks in advance :-) 

**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

**Current behavior:**

ng-sortable is not working with md-tabs

**Expected / new behavior:**

ng-sortable should work with md-tabs

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.x

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by frederikprijck** [comment]
Hey @GNSubrahmanyam ,

When debugging, it's a good idea to make use of the none-minified AngularJS files. This gives a readable error message, in your case:

> "Error: [$compile:multidir] Multiple directives [mdTab (module: material.components.tabs), ngSortable] asking for new/isolated scope on: <md-tab ng-sortable='sortableConfig' ng-repeat='tab in tabs' ng-click='tabClick(tab)'>

Looks like you can't use both md-tab and ng-sortable together on the same element.
However, note that none of those two directives are part of AngularJS core, so there's nothing we can do about that.

If you need help please, use one of the [appropriate support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question).
GitHub issues are reserved for bug reports and feature requests.
