### ISSUE TITLE
$log service, request for more methods like: group, time, profile, assert, trace and many more 

### ISSUE THREAD

**Issue by Loksly** [angular/angular.js#16549]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

$log service provides log, info warn error and debug methods.

**Expected / new behavior:**

Would it be possible to provide methods that the console provided by navigator already has?
These might include:
* assert
* time, timeEnd
* count
* group, groupEnd, groupCollapsed
* profile, profileEnd
* trace
* dir, dirxml

**Comment by frederikprijck** [comment]
Hey @Loksly 

You could easily create your own wrapper for the mentioned methods, AngularJS' `$log` service isn't meant to be a wrapper around all of the browser's `console` methods.

Given the ease to integrate the methods your self and the fact that with Angular the built-in logging service has been removed, I don't think it's beneficial to add these to the core of the framework. I'd also argue it might, unnecessary, bloat the service.

**Comment by gkalpak** [comment]
I agree with @frederikprijck. Taking into account that:
1. few people will use these methods
2. it is easy to add them yourself (e.g. by decorating `$log`) or use `console` directly

...I don't think it i a good idea to add them into core.
(They can't be easily distributed as a 3rd-party package though :wink:)
