### ISSUE TITLE
clientHeight doesn't work in chrome

### ISSUE THREAD

**Issue by Nicram01** [angular/angular.js#16542]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

When I try to get the clientHeight in Chrome it is always 0, but when I access it in Firefox the right clientHeight is shown. I tried to access it with

 $("#id")[0].clientHeight
angular.element($("#id"))[0].clientHeight
document.getElementById("id").clientHeight
angular.element(document.getElementById("id"))[0].clientHeight

, but nothing works.

**Expected / new behavior:**

The clientHeight should be greater than 0, like in Firefox

**Minimal reproduction of the problem with instructions:**

angular.element(document.getElementById(id))[0].clientHeight

In Chrome!!!

**AngularJS version:** 1.x.y

1.6.9

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 66.0.3359
**Anything else:**

**Comment by Narretz** [comment]
clientHeight has nothing to do specifically with AngularJS, it's a built in property.
