### ISSUE TITLE
json data is not loading into the table from the cloudant

### ISSUE THREAD

**Issue by amosingh** [angular/angular.js#16568]
contents of  controller.js

/**
 * @author v.lugovsky
 * created on 16.12.2015
 */
(function () {
  'use strict';

  angular.module('BlurAdmin.pages.dashboard')
      .controller('DashboardTablesPageCtrl', DashboardTablesPageCtrl);

  /** @ngInject */
  var smartTableDatanew={};
  function DashboardTablesPageCtrl($scope,$http) {

    $scope.smartTablePageSize = 1;
    $scope.smartTableData = [];

    $http.get('https://a47f02a1-ab4f-4a08-ad57-db1b46cd15da-bluemix.cloudant.com/mydatabase/ab9155fd7a259c52a9357ed1d690302d')
    .success(function(data){  
          console.log(data); 
      data = data.data;
     $scope.smartTableData.push(data); 
     // smartTableDatanew.data=data;   
     console.log($scope.smartTableData);
   })    
   .error(function(data,status){    
          console.log("error")
     console.error('Fail to load data', status, data);    
     $scope.smartTableData = {};     
   });    
    
        
  }

})();

content of html file

<div class="horizontal-scroll">
  <div class="form-group select-page-size-wrap ">
    <label>Rows on page
      <select class="form-control selectpicker show-tick" title="Rows on page" selectpicker
              ng-model="smartTablePageSize" ng-options="i for i in [5,10,15,20,25]">
      </select>
    </label>
  </div>
  <table class="table" st-table="smartTableData">

    <thead>
       <tr>
      <th><input st-search="" placeholder="Search..." class="input-sm form-control search-input"
                 type="search"/></th>
       </tr>
    <tr class="sortable ">
      
      <th st-sort="support">App Name</th>
      <th st-sort="summary">App Name</th>
      <th st-sort="phase">App Name</th>
      
    </tr>
    
    </thead>
    <tbody>
    	<p>{{smartTableData}}</p>
    <tr ng-repeat="item in smartTableData">
     
      <td>{{item.support}}</td>
      <td>{{item.summary}}</td>
      <td>{{item.phase}}</td>
     
    </tbody>
    <tfoot>
    <tr>
      <td colspan="6" class="text-center">
        <div st-pagination="" st-items-by-page="smartTablePageSize" st-displayed-pages="5"></div>
      </td>
    </tr>
    </tfoot>
  </table>
</div>

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
