### ISSUE TITLE
Angular.js 1.5.9 support post July 1st 2018

### ISSUE THREAD

**Issue by girishacharya** [angular/angular.js#16571]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

We use Angular JS 1.5.9 at this point. It's not clear from the documentation if this will be supported after July 1st, 2018. Can someone make it clear?

**Comment by gkalpak** [comment]
As [documented][1], v1.5.x is not developed any more, which means it will not receive any new features or bug fixes. We might make exceptions for severe security vulnerabilities, but it is decided on a case-by-case basis.

Only the versions documented in the [version support status][1] guide are guaranteed to fixes (subject to the LTS policy).

[1]: https://docs.angularjs.org/misc/version-support-status
