### ISSUE TITLE
Can no longer set a default option as shown in the documentation

### ISSUE THREAD

**Issue by Portical** [angular/angular.js#16572]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
If you go to the docs here: [https://code.angularjs.org/1.6.5/docs/api/ng/directive/ngOptions](https://code.angularjs.org/1.6.5/docs/api/ng/directive/ngOptions)
Scroll to the bottom and click the bogus button where is says "Select bogus."
You'll notice the "Color (null allowed)" is blank instead of "-- choose color --"

**Expected / new behavior:**
If you go to the docs here: [https://code.angularjs.org/1.6.4/docs/api/ng/directive/ngOptions](https://code.angularjs.org/1.6.4/docs/api/ng/directive/ngOptions)
Scroll to the bottom and click the bogus button where is says "Select bogus."
You'll notice the "Color (null allowed)" correctly shows "-- choose color --"

**Minimal reproduction of the problem with instructions:**
See Current vs Expected behaviour above.

**AngularJS version:** 1.6.5+

**Browser:** [all]

**Comment by Narretz** [comment]
This is an expected and intentional change: 
https://github.com/angular/angular.js/commit/17d34b7a983a0ef63f6cf404490385c696fb0da1

The previous behaviour was not logical. The null option should only be selected when the model value is null. "Bogus" in the example is neither an existing option nor null so it adds the unknown option.

**Comment by Narretz** [comment]
That said, you can achieve the previous behavior with the selectController methods that check the state of the empty and unknown options. https://docs.angularjs.org/api/ng/type/select.SelectController.  You can use the in a custom formatter to force the display of the empty / null option.
