### ISSUE TITLE
Allow multi transclude directives like ngIf - expose $$tlb

### ISSUE THREAD

**Issue by IMM0rtalis** [angular/angular.js#16574]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**
If I want to create an ngIf-like directive I have to use a **private** property $$tlb. But ngIf-like directives are sometimes needed and there are used already by many developers.
Example:
```javascript
module.directive('customIf', ['$animate', function($animate) {
            return {
                multiElement: true,
                transclude: 'element',
                priority: 100,
                terminal: true,
                restrict: 'A',
                $$tlb: true,
                link: function($scope, $element, $attr, $ctrl, $transclude) {
                    var $unWatch,
                        clonedElem,
                        childScope
                    ;

                    $scope.$on('$destroy', function() {
                        if ($unWatch instanceof Function) {
                            $unWatch();
                        }
                    });

                    $unWatch = $scope.$watch($attr.customIf, function customIfWatchAction(value) {
                        [...]
                    });
                }
            }
        }]);
```

**Expected / new behavior:**
$$tlb should be official introduces so nobody has to fear the removal since it is atm private and actually should not be used by any custom directives. As far as I know by my google research multi-transclusion is possible now, but still it is not possible to make a directive like the ngIf without `multElement=true & $$tlb=true`

**AngularJS version:** 1.5.x, 1.6.x

**Browser:** [all]

**Anything else:**
It is told to not use $$tlb but no alternative is given: #6042
Already asked here with many many comments and somehow implemented partly but asked to open new issue instead of using closed one: #4357

**Comment by Narretz** [comment]
We are not going to make this property public, but since we are in LTS mode, it won't be removed or changed either, so you can basically use it safely.
