### ISSUE TITLE
404 when doing `npm i angular`

### ISSUE THREAD

**Issue by rainabba** [angular/angular.js#16579]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
`npm i angular` logs a 404 on install. NPM log shows ` http fetch GET 404 https://registry.npmjs.org/angular/-/angular-1.7.0.tgz 117ms`

**Expected / new behavior:**
I expect the package to download/install

**Minimal reproduction of the problem with instructions:**
`npm i angular`

**AngularJS version:** 1.x.y
Any version I try throws a similar 404 (with appropriate versions in the GET)

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Not relevant

**Anything else:**
This JUST started and I can install other packages fine so I have no reason to think it's specific to me or my machine though I haven't tried elsewhere yet.

**Comment by pll33** [comment]
I am also encountering this issue as described.

**Comment by tcrite** [comment]
This is also occurring on ms build server

**Comment by xwraith27** [comment]
All of the tarballs in https://registry.npmjs.org/angular/ seem to be missing and can't be downloaded even through accessing directly via browser (e.g., https://registry.npmjs.org/angular/-/angular-1.6.4.tgz). Angular2 packages are downloadable.

**Comment by rainabba** [comment]
Looks to be working again.
