### ISSUE TITLE
10 $digest() iterations reached using $sce.trustAsResourceUrl with angularjs 1.7.0

### ISSUE THREAD

**Issue by einarstubhaug** [angular/angular.js#16593]
- [X] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
10 $digest() iterations reached using $sce.trustAsResourceUrl inside isolate scope directive 1.7.0

**Minimal reproduction of the problem with instructions:**

Markup in template:  
`<img ng-src="{{getThumbnailImageUrl(imgId)}}">`
Corresponding controller function:
`scope.getThumbnailImageUrl = function(id) {return $sce.trustAsResourceUrl(someService.someUrl(id)); }}`

**AngularJS version:** 1.7.0

**Browser:** Tested in Version 67.0.3396.79 of Chrome

**Anything else:**
Seems like this regression has happened before: https://github.com/angular/angular.js/issues/3932
Is it a breaking change in version 1.7.0 or is it a regression that will be fixed?

**Comment by gkalpak** [comment]
This is probably a result of 1e9eadcd. Not sure if it is an intentional change or not.
@petebacondarwin should know more :grin:

**Comment by petebacondarwin** [comment]
As described in #3932 this is because the trusted object is newly created every time and we are checking the object identity in the `ngSrc` watcher.

**Comment by petebacondarwin** [comment]
Although Chirayu "fixed" this for `ngBindHtml` (it was still called `ngBind` that time) it was accepted that people would be careful when binding trusted values.   I think that the workaround given here is safer.

**Comment by Narretz** [comment]
We should probably still add this to the CL, as it didn't happen before 1.7.0
