### ISSUE TITLE
AngularJS with ngRoute + AdBlock = error in Chrome

### ISSUE THREAD

**Issue by Mlocik97-issues** [angular/angular.js#16609]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [X] other 

**Current behavior:**

```
Uncaught SyntaxError: Identifier 'chunkSize' has already been declared
    at VM[...] adblock-datacollection-contentscript.js:1
(anonymous) @ VM[...] adblock-datacollection-contentscript.js:1
```
**Expected / new behavior:**

no error

**Minimal reproduction of the problem with instructions:**

if I use ngRoute and click on any button [ul>li>a] with attribute href="#!something", it always create error in console.

**AngularJS version:** 1.6.10 but also 1.7.2

**Browser:** Chrome 67.0.3396.87

**Anything else:**

Adblock by BetaFish v3.31.2 [ID: gighmmpiobklfepjocnamgkkbiglidom]
error point to file https://gist.github.com/Mlocik97-issues/4d5e392a8cb1b547a25e2a55206620ce

**Comment by gkalpak** [comment]
Sorry, but this doesn't sound related to AngularJS. May be an issue with AdBlock.

**Comment by Mlocik97-issues** [comment]
but it happend only with angularJS and ngRoute

**Comment by gkalpak** [comment]
It also only happened with AdBlock 😛 
Happy to be proven wrong, but based on the provided info there is no indication that this is an AngularJS issue.
