### ISSUE TITLE
Docs: Internal hash-links' hrefs on docs.angularjs.org all lead to the docs home page

### ISSUE THREAD

**Issue by mgol** [angular/angular.js#16608]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Internal hash-links on all doc pages (i.e. ones that are meant to just scroll the user to a section on the same page) are all broken, leading to the docs home page instead of the current one.

This seems to work - clicking on the links scroll to the correct place and the URL updates properly - but that's because Angular.js intercepts the native browser navigation. 

This is caused by the `<base>` tag that points to the main page, causing seemingly harmless hash-links like `#migrating-from-1-6-to-1-7` to resolve against the `document.baseURI` instead of the current URL path name.

**Expected / new behavior:**

All the links should work when opened in a new tab.

**Minimal reproduction of the problem with instructions:**

If you try to open one of the links on a new page, e.g. via Ctrl+click (Windows/Linux) or Cmd+click (macOS) you'll get to the incorrect:
https://docs.angularjs.org/api#migrating-from-1-6-to-1-7
instead of the expected:
https://docs.angularjs.org/guide/migration#migrating-from-1-6-to-1-7

See e.g. how at https://docs.angularjs.org/guide/migration the "Migrating from 1.6 to 1.7" link behaves.

**AngularJS version:** N/A

The docs for older AngularJS versions don't suffer this issue, compare a correct:
https://code.angularjs.org/1.6.6/docs/guide/migration
with a broken:
https://code.angularjs.org/1.6.7/docs/guide/migration 

**Browser:** all

**Anything else:**

**Comment by petebacondarwin** [comment]
The problem is with the generated Table of Contents rather than links in general. Previously the manual ToCs had full paths with their hashes.

The generated ToC has always failed in this way. Here is the line that is at fault https://github.com/angular/angular.js/blob/2c7aa68ca8c60663529e4f423bc73e448c3441b1/docs/app/src/directives.js#L94

**Comment by petebacondarwin** [comment]
I updated the commit message. Thanks @mgol
