### ISSUE TITLE
escaping a string value inside a ng-init directive

### ISSUE THREAD

**Issue by yriiarutiunian** [angular/angular.js#16619]
Hey guys!
i use a ng-init directive to set a value for my input field, but the problem is that my string value is kinda specific and content some symbols like '�'. So, seems i have to use some escaping function inside a ng-init directive, so how can i do that? thank you in advance.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
