### ISSUE TITLE
sanitizeUri function throws an error when ng-href gets an integer

### ISSUE THREAD

**Issue by szabobgabor** [angular/angular.js#16626]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

if i write 
`<a ng-href="{{ user.id }}">bla</a>`
in a template and user.id is an integer
sanitizeUri function (angular.js:19343) throws an error, that uri.trim is not a function (well it is obviously not)

**Expected / new behavior:**

probably the uri should be casted to string

**Minimal reproduction of the problem with instructions:**

http://plnkr.co/edit/sd1UHVd8iHF1rPXNL3Z0

**AngularJS version:** 1.7.2

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by petebacondarwin** [comment]
Obvious workaround is to call `toString()` on the value: http://plnkr.co/edit/9qijamnI6UhJK1DP77kU?p=preview

```
<a ng-href="{{ user.id.toString() }}">bla</a>
```

**Comment by szabobgabor** [comment]
that's true, but not "sexy", and usability breaks

a nicer solution would be to

replace this
var normalizedVal = urlResolve(uri && uri.trim()).href;

into this
var normalizedVal = urlResolve(uri && uri.toString().trim()).href;
