### ISSUE TITLE
The localization example for Slovenia on your website is wrong.

### ISSUE THREAD

**Issue by aleksander351** [angular/angular.js#16634]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

The example for localization on the Angular.js website is wrong for Slovenia.

You are displaying results for Slovakia.

Slovenia !== Slovakia // is not the same.

Look it up on Wikipedia or here:
https://countryeconomy.com/countries/compare/slovenia/slovakia

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by gkalpak** [comment]
Can you add more info? What example are your referring to? What is the page URL?

**Comment by Narretz** [comment]
On the Homepage maybe? We do use the "SK" locale, but there is no mention of "Slovakia" or "Slovenia".

**Comment by gkalpak** [comment]
Yes, `SK` is a hard-coded locale (for demonstation purposes). We don't try to detect the user's locale.
