### ISSUE TITLE
ng-move in nganimate not working in angular version 1.5.8

### ISSUE THREAD

**Issue by archanab26** [angular/angular.js#16630]
I am using angular version 1.5.8 and angular animate version 1.5.8.  I am applying animation in ng-repeat but **ng-move** is not applying when  I am trying to apply transition while changing position of item in ng-repeat.

Does angular version 1.5.8 support **ng-move** of **ng-animate** ?
Is there any other changes required ?

If you have any solution then please suggest.

Thanks,
Archana

**Comment by Narretz** [comment]
This is a known issue which we're probably not going to fix as the impact on performance is too big: https://github.com/angular/angular.js/issues/5160

**Comment by Narretz** [comment]
Duplicate of #5160
