### ISSUE TITLE
URL causes an "$digest already in progress" error on code.angularjs.org website

### ISSUE THREAD

**Issue by AlexisJJ** [angular/angular.js#16635]
**I'm submitting a ...**

- [ x] bug report

**Current behavior:**

Having the ' character in the URL seems to break code.angularjs.org website, which shows in the console a "$digest already in progress" error

**Expected / new behavior:**

The code.angularjs.org website should not throw errors

**Minimal reproduction of the problem with instructions:**

*STEPS TO REPRODUCE*
Go to the URL https://code.angularjs.org/1.7.2/docs/error/$rootScope/infdig?Alzheimer%27s%20disease and see the errors in the console

**AngularJS version:** 1.7.2

**Browser:** [Chrome 67 | Firefox 52]

**Anything else:**

Uncaught Error: [$rootScope:inprog] http://errors.angularjs.org/1.7.0/$rootScope/inprog?p0=%24digest
    at angular.js:88
    at p (angular.js:19181)
    at m.$digest (angular.js:18511)
    at m.$apply (angular.js:18923)
    at Worker.a.onmessage (search.js:158)

**Comment by jbedard** [comment]
I'm pretty sure this is the same as #16592 and was just fixed aee7d53a6b5d3d7bc0a1124fd3df9b263777e72e
