### ISSUE TITLE
ngAnimate: memory leak in disabledElementsLookup Map

### ISSUE THREAD

**Issue by vertazzar** [angular/angular.js#16637]
All begins with this line of the code:

https://github.com/angular/angular.js/blob/494277e3d3668699133fc796e5bf632258e34802/src/ngAnimate/animateQueue.js#L306

**Reproducable:** always
**Browsers:** Any
**Operating system:** Any
**Versions**: All that use the hash map

**Steps to reproduce:**

Available in codepen: https://codepen.io/anon/pen/yqVwwE

click on "leaker" **n** times to get **n** detached nodes as seen in the screenshot

![screen shot 2018-07-20 at 12 37 41](https://user-images.githubusercontent.com/1160605/42998282-efd520bc-8c19-11e8-8079-79f4bab18618.png)

**Solution**: listen for element scope destroy event, or ``element.on('remove')`` and delete the node from ``disabledElementsLookup`` Map ?

**Note**: If this is "working as intended" at least provide public api to ``disabledElementsLookup`` so we can cleanup after directive exits

**Comment by gkalpak** [comment]
If we only had WeakMaps :smiley:

I am not sure, but I guess the reason for choosing a map over storing the value on the DOM element itself was speed. Since we only set a value when calling `$animate.enabled(element, true/false)` - which is not very common I presume - I think it would be fine storing that info on the node (instead of a Map).

(Note to self: This should be independent of `.data()`, so that it is not affected by `.removeData()` and also so that it can be independently optimized for speed.)

##
Listening for the element's `$destroy` event might also work. (Not the scope's `$destroy`, because not all elements have a scope and not the element's `remove` because it does not cover all cases (e.g. `replaceWith()`).)

**Comment by vertazzar** [comment]
You are right about trying to tap into weird environments ($destroy, .data() etc). Then it would be something that must be explicitly called, eg:

``$animate.unregisterEnabledState(element)``

``$animate.enabled(element, null) ``

**Comment by gkalpak** [comment]
For the record, I said listening for the element's `$destroy` event might work :grin:
Exposing a public API to "unregister" the element would be very straight forward to implement, but feels weird. Ideally, we shouldn't be introducing memory leaks in the first place :grin:

Let's see what others think. (Cc @Narretz who has more experience with `ngAnimate`.)

**Comment by vertazzar** [comment]
aha, I misunderstood what you meant (exhaustion :D)

**Comment by Narretz** [comment]
I would probably go with the event listener. I assume that setting on the node directly is pretty slow on older IEs.

**Comment by gkalpak** [comment]
Note that adding an event listener also assigns stuff on the node under the hood :grin:
But given that `$animate.enabled(element, true/false)` is rare, I think this is a good trade-off.

@vertazzar, would you be interested in taking a stub at fixing this?

**Comment by vertazzar** [comment]
@gkalpak 

Easiest solution was just to write something like:

```
            if (!element.data('hasAnimateDestroyListener')) {
                element.data('hasAnimateDestroyListener', true);
                var scope = element.scope();
                scope.$on('$destroy', function () {
                    disabledElementsLookup.delete(node);
                });
            }

```
the .data() is to avoid constant listener registration when running the ``$animate.enabled``.

For the element lifecycle I'm not sure if the value of ``element.scope();`` can change for the ``element`` at any point in runtime before the $destroy event. If that's the case, you might want to add ``element.data('hasAnimateDestroyListener'  + scope.$id)`` to add support for multiple scopes grabbing the element.

**Comment by gkalpak** [comment]
As mentioned in https://github.com/angular/angular.js/issues/16637#issuecomment-406623496, the scope's `$destroy` event is not a good option (because not all elements have their own scope).

I created a PR that bind to the _element's_ `$destroy` event: #16649
