### ISSUE TITLE
error while pusing interceptor into httpprovider in angularJS

### ISSUE THREAD

**Issue by vikkylu** [angular/angular.js#16655]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

**Current behavior:**
I am receiving following error while pushing interceptor:
angular.js:68 Uncaught Error: [$injector:unpr] Unknown provider: AuthTokenProvider <- AuthToken <- AuthInterceptor <- $http <- $uiRouter
http://errors.angularjs.org/1.4.8/$injector/unpr?p0=AuthTokenProvider%20%3C-%20AuthToken%20%3C-%20AuthInterceptor%20%3C-%20%24http%20%3C-%20%24uiRouter
    at angular.js:68
    at angular.js:4334
    at Object.getService [as get] (angular.js:4482)
    at angular.js:4339
    at getService (angular.js:4482)
    at invoke (angular.js:4514)
    at Object.instantiate (angular.js:4531)
    at Object.<anonymous> (angular.js:4391)
    at Object.invoke (angular.js:4523)
    at Object.enforcedReturnValue [as $get] (angular.js:4375)

**Expected / new behavior:**
I should have not got an error because, interceptor is can be injected/pushed successfully into httpProvider. 

**Minimal reproduction of the problem with instructions:**

function mainConfig($urlRouterProvider, $locationProvider,$httpProvider) {
	$locationProvider.html5Mode(true);
	//$urlRouterProvider.otherwise('/');
	$httpProvider.interceptors.push('AuthInterceptor');
}
mainConfig.$inject = ['$urlRouterProvider', '$locationProvider','$httpProvider'];
export default mainConfig;

**AngularJS version:** 1.4.2

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome XX

**Anything else:**

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
