### ISSUE TITLE
@Input not work when there is a list of child-components in the parent HTML all the instanstaces of the child component  get the value of the last one.  what is my problem?

### ISSUE THREAD

**Issue by zivias** [angular/angular.js#16659]
arent HTML

   <div class="form-group">

      <ul>

        <li  *ngFor="let item of ProductOfMealIAte">

          <div *ngFor="let product of item.products " >  

            <app-new-product [dailyMenuNameProduct]="IAteNameProductFunc(product)" ></app-new-product>

          </div>

        </li>

      </ul>

    

    </div>

 Parent-ts

dailyMenuNameProductFunc(dailyMenu:Dailymenu){

  let i;

 

for(i=0;i<this.products.length&&this.products[i].id!=dailyMenu.idProduct;i++);

if(this.dailyMenuNameProduct!=undefined&&this.products[i]!=undefined)

{this.dailyMenuNameProduct.name=this.products[i].name;

this.dailyMenuNameProduct.id=this.products[i].id;

this.dailyMenuNameProduct.calory=this.products[i].calory;

 

return this.dailyMenuNameProduct;

}}

child-ts

@Input() dailyMenuNameProduct: Product;

ngOnInit() {

console.log(this.dailyMenuNameProduct)

}

**Comment by Narretz** [comment]
This is a question about Angular. Please she the Angular Repo for support options.
