### ISSUE TITLE
Any unauthorized user can tweak the client side code and see the Admin UI

### ISSUE THREAD

**Issue by preban** [angular/angular.js#16651]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
Currently an unauthorized user who does not have access to admin features can by pass the client side code and see the Admin UI. There is no way to prevent him to see the admin functionalities.

**Expected / new behavior:**
No lower privileged user should be able to see the admin UI by bypassing the client side code.

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y
1.x

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Anything else:**

**Comment by gkalpak** [comment]
This doesn't sound related to AngularJS.

**Comment by preban** [comment]
It is related to AngularJS. We are facing this issue in all our angular based apps. There is no way to hide client side code so as to stop an attacker from modifying it and gaining unwanted access.

**Comment by gkalpak** [comment]
This is how client side code (JavaScript in this case) works. You can't rely on client side code for security (exactly because the client has full access to the code).

This is not an AngularJS specific issue.

Your security layer must be implemented on the server side.

**Comment by preban** [comment]
Even the server side controls do not prevent a user to "View" the UI.

**Comment by gkalpak** [comment]
It depends on what the server sends to the client :wink:
In any case, as I mentioned above, there is nothing AngularJS can do about it. This is not an AngularJS specific issue. Once something is sent to the client, you must assume the client has full access to it. (They can even intercept the HTTP requests before reaching AngularJS.)
