### ISSUE TITLE
Error URLs from AngularJS 1.5.11 are not redirecting; gives 404 error

### ISSUE THREAD

**Issue by laurence-myers** [angular/angular.js#16661]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
Errors triggered in AngularJS 1.5.11 produce an error URL in this form:

`http://errors.angularjs.org/1.5.11/$interpolate/interr?p0=foo&p1=bar`

Going to this URL gives a 404 page and does not redirect.

![2018-08-10 10_11_40-page not found](https://user-images.githubusercontent.com/6336048/43932211-0e7591c4-9c86-11e8-8da4-a472b13a29d3.png)

**Expected / new behavior:**

This URL is the new docs location:

`https://code.angularjs.org/1.5.11/docs/error/$interpolate/interr?p0=foo&p1=bar`

**Minimal reproduction of the problem with instructions:**
Using AngularJS 1.5.11, write some code that causes an error. Maybe add an invalid expression to your template like this:

`<p>{{  foo.bar() | date }}</p>`

**AngularJS version:** 1.5.11

**Browser:** all

**Anything else:**
N/A

**Comment by shaoran** [comment]
I can confirm this. I prepared a [jsfiddle][1] example that generates an error by requiring a controller that doesn't exist. Open the JS console and click on *Show directive*, which leads to the error.

The error URL is http://errors.angularjs.org/1.4.8/$compile/ctreq?p0=dash&p1=someDir but if you follow the link, then 404 page is displayed instead. The HTML of the 404 is even wrong, the `DOCTYPE` line is missing the opening `<` of the HTML tag.


[1]: https://jsfiddle.net/shaoran/kxzv7nmb/9/

**Comment by petebacondarwin** [comment]
Looks like we need to do more work on the `errors.angularjs.org` hosting to ensure the redirect to `docs.angularjs.org/error/` happens correctly... @Narretz any ideas?

**Comment by Narretz** [comment]
I included these redirects, and they are also still in the code. Maybe something changed in Firebase, or something in the error is throwing off the pattern matching,

**Comment by Narretz** [comment]
Curious, I just tested http://errors.angularjs.org/1.5.11/$interpolate/interr?p0=foo&p1=bar again, and now I get redirected to code.angularjs.org. Maybe it was an internal error with Firebase.

**Comment by codymikol** [comment]
I've also seen this same behavior.

**Comment by Narretz** [comment]
I believe this problem has been resolved.
