### ISSUE TITLE
1.7.3 angularMocks makes test cases that worked earlier with 1.7.2 fail with Unknown provider: $$taskTrackerFactoryProvider <- $$taskTrackerFactory ... )

### ISSUE THREAD

**Issue by gkrishnaks** [angular/angular.js#16660]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
After update to 1.7.3 AngularMocks, test cases that worked earlier started failing with 
[$injector:unpr] Unknown provider: $$taskTrackerFactoryProvider <- $$taskTrackerFactory <- $browser <- $rootScope <- $browser
	
**Expected / new behavior:**
Test cases that worked earlier in 1.7.2 should continue to work 1.7.3 of Angular mocks. 

**Minimal reproduction of the problem with instructions:**
Any test case that worked with 1.7.2 

This example code from (http://www.bradoncode.com/blog/2015/05/17/angularjs-testing-controller/)

```
angular.module('calculatorApp').controller('CalculatorController', function CalculatorController($scope) {  $scope.z = 0;
  $scope.sum = function() {
    $scope.z = $scope.x + $scope.y;
  };
});
// models x and y are taken from template
```

```
describe('calculator', function () {
		
	beforeEach(angular.mock.module('calculatorApp'));

	var $controller;

	beforeEach(angular.mock.inject(function(_$controller_){
	  $controller = _$controller_;
	}));

	describe('sum', function () {
		it('1 + 1 should equal 2', function () {
			var $scope = {};
			var controller = $controller('CalculatorController', { $scope: $scope });
			$scope.x = 1;
			$scope.y = 2;
			$scope.sum();
			expect($scope.z).toBe(3);
		});	
	});
});

```

**AngularJS version:** 1.7.2
**Angular-mocks version:** 1.7.3 from NPM
 Checked, no similar issue found in this repo.

**Browser:** Chrome (maybe others too). Debian

**Comment by Narretz** [comment]
I think you need to update the angular core package to 1.7.3. There has always been a soft requirement that all packages have the same patch version.

**Comment by gkrishnaks** [comment]
@Narretz Ok.. 
 angularjs.org still provides 1.7.2 on the download button.. and even directly loading this link doesn't work (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.3/angular.min.js) throws 404

**Comment by Narretz** [comment]
That's true, the homepage and the CDN are always a bit behind. However, if you are getting angular-mocks from npm, why not get the core angular from it as well?

**Comment by martinoppitz** [comment]
I have the same problem ...

    "angular": "1.7.3",
    "angular-i18n": "1.7.3",
    "angular-mocks": "1.7.3",
    "angular-sanitize": "1.7.3",

**Comment by Narretz** [comment]
Something must have gone wrong during installation. Probably angular hasn't actually been updated or you are including an old version. This problem cannot happen if everything is 1.7.3

**Comment by alancnet** [comment]
Reopen. Occurs with new projects with angular and angular-mocks 1.7.4

**Comment by gkalpak** [comment]
Unlikely to be the case if all AngularJS modules (including `angular-mocks`) are on 1.7.4 :smiley:
