### ISSUE TITLE
Angular 6 in existing asp.net application.

### ISSUE THREAD

**Issue by navanee24** [angular/angular.js#16668]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

Hi,
We need to migrate the existing asp.net application to angular 6.this is not mvc application fully asp.net application.We are going to add new .aspx page with angular 6.How can we do that.anyone achieved.do we have any work around for these scenario.   

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by Narretz** [comment]
Hi, your issue sounds like an issue for Angular. Please go to the [Angular repository](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question). This repo is only for AngularJS. Thanks!
