### ISSUE TITLE
angular.copy() documentation is not correctly formatted

### ISSUE THREAD

**Issue by YMIndustries** [angular/angular.js#16671]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
On the documentation page for [angular.copy()](https://docs.angularjs.org/api/ng/function/angular.copy), some of the formatting is hard to read and inconsistent with the rest of the AngularJS documentation. In particular, the raw JSDoc is being formatted as markdown and included at the end of the Overview section. The Usage section is very bare, not including the function arguments or return value.

**Expected / new behavior:**
The documentation page should be correctly formatted, with the function arguments and return value being nicely formatted in the Usage section. See [angular.equals()](https://docs.angularjs.org/api/ng/function/angular.equals) for an example of how a function documentation page should look.

**Minimal reproduction of the problem with instructions:**
Navigate to https://docs.angularjs.org/api/ng/function/angular.copy.

**AngularJS version:** 1.7.2
The issue did not exist in 1.7.1. The issue still exists in 1.7.x-snapshot and master-snapshot.

**Browser:** Chrome v68.0.3440.106 (64-bit), Firefox v61.0.2 (64-bit), probably all other browsers too

**Anything else:**
No

**Comment by gkalpak** [comment]
This seems to be caused by a bug in `dgeni`/`dgeni-packages`. Started happening since the update in c387e0d79.

I worked around it with aecd551bd. @petebd, any idea what might have caused this?

**Comment by petebacondarwin** [comment]
This should be fixed by https://github.com/angular/dgeni-packages/pull/271 although we will need to put a blank line between the `<br/>` and the `<div>` to indicate to the parser that these need to be processed independent of each other.
