### ISSUE TITLE
Angularjs 1.3.4 gives Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by kj1981** [angular/angular.js#16678]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
Using datepicker-popup with angular 1.3 and angular.animate 1.3 gives error: Cannot read property 'parentNode' of undefined

**Expected / new behavior:**
Using datepicker-popup with angular 1.3 and angular.animate 1.3 should not give error

**Minimal reproduction of the problem with instructions:**
Error shown in codepen demo: https://codepen.io/anon/pen/wEaoLG

**AngularJS version:** 1.x.y
Angularjs version being used is 1.3.4

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Anything else:**
At this moment we cant upgrade to higher version of angular js which may have the fix. So looking to find some workaround with which we can get rid of this error. Previous issues does not mentions any workaround.

**Comment by petebacondarwin** [comment]
This has appeared elsewhere and seems to be some kind of bug in a recent release of Chrome. (I am assuming that it is only happening on Chrome?)

**Comment by kj1981** [comment]
Yes I can see similar issue: https://github.com/angular/angular.js/issues/10205 but everyone has just suggested to upgrade angular. We cannot upgrade at this moment so wanted to find a workaround.  Yes we are using chrome only.

**Comment by petebacondarwin** [comment]
I read there that it was fixed at 1.3.18, are you on an early version than that?

**Comment by kj1981** [comment]
We are using Angular 1.3.4

**Comment by petebacondarwin** [comment]
You should really try upgrading at least to the latest 1.3.x release (1.3.20) or at least 1.3.18. There should be no breaking changes for you in that upgrade.

**Comment by kj1981** [comment]
We would like to upgrade but at this moment there are many dependencies. Would you be knowing any workaround that works . Or if you are aware of any other calendar that works with angular 1.3.4 which we can look into maybe.

**Comment by Narretz** [comment]
You can try to apply the changes in in https://github.com/angular/angular.js/commit/6b72598b87022e1dd96bddc4451e007ef0601579 as a patch to your AngularJS version.

**Comment by kj1981** [comment]
@Narretz my app is inheriting from all the JS, css extra from a parent app so I have to see if the change you have suggested can be done or not as its not under my control. If it was my app this could have been an easy fix. Are you aware if any workaround can be done other than this. Thanks
