### ISSUE TITLE
flickering issue in ie 11 with ng-hide 

### ISSUE THREAD

**Issue by ankitappuria** [angular/angular.js#16675]
Please take a look at this (https://dev.smartbothub.com/4444/v1/api/Dev-master_bot/getBot) in IE 11.Click on a dropdown button on the right side of the webchat screen on sliding down the webchat flickers.

Here is the css used for animation.

```
.animate-slide.ng-hide-remove.ng-hide-remove-active {
    -webkit-animation: 0.5s slide-up;
    animation: 0.5s slide-up;
}

.animate-slide.ng-hide-add.ng-hide-add-active {
    -webkit-animation: 0.5s slide-down;
    animation: 0.5s slide-down;
}

@-webkit-keyframes slide-up {
    from {
        height: 0;
    }
    to {
        height: 80%;
    }
}




@keyframes slide-up {
    from {
        height: 0;
    }
    to {
        height: 80%;
    }
}



@-webkit-keyframes slide-down {
    from {
        height: 80%;
    }
    to {
        height: 0;
    }
}




@keyframes slide-down {
    from {
        height: 80%;
    }
    to {
        height: 0;
    }
}
```

This only seems to happen in IE11. I'm using angular 1.5 Please help me with what is the issue.

**Comment by petebacondarwin** [comment]
AngularJS 1.5 is no longer supported. Please try upgrading to 1.7.

Furthermore, AngularJS is now in LTS mode, so we are only fixing significant issues now and it is unlikely that we there will be a fix for an IE11 issue. I am sorry about that. Hopefully 1.7 will help you.
