### ISSUE TITLE
While binding method within the Interpolation it raises twice 

### ISSUE THREAD

**Issue by thirukumarangceb** [angular/angular.js#16676]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other 

**Current behavior:** 
When am trying to check the interpolation  i had some concerns related to that. check the below demo link https://plnkr.co/edit/nMay1GJHOao6ATfJq6fT?p=preview. In this the method is called twice. How it triggers the function twice it an behavior ?

**Expected / new behavior:**
It should be raised once.

**Minimal reproduction of the problem with instructions:**
https://plnkr.co/edit/nMay1GJHOao6ATfJq6fT?p=preview 

**AngularJS version:** 1.x.y
v1.7.4 

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Anything else:**

**Comment by petebacondarwin** [comment]
This is expected behaviour. AngularJS has to trigger each interpolation at least twice per digest to ensure that the value of the interpolation has not changed (is stable). You should avoid side effects in interpolations. Instead you could setup a watch that is triggered only once per change.

**Comment by thirukumarangceb** [comment]
@petebacondarwin  Thanks.
