### ISSUE TITLE
Angular does not load when ng-app/ ng-controller is named

### ISSUE THREAD

**Issue by Koviac** [angular/angular.js#16679]
index.html
`<!DOCTYPE html>`
`<html lang="en-US" ng-app="app">`
  `<head>`
    `<link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css" />`
    `<script src="node_modules/jquery/dist/jquery.min.js"></script>`
    `<script src="node_modules/angular/angular.min.js"></script>`
    `<script src="node_modules/angular-ui-router/release/angular-ui-router.min.js"></script>`
    `<script src="app.module.js"></script>`
    `<script src="modules/home/Home.js"></script>`
    `<script src="modules/home/HomeConfig.js"></script>`
    `<script src="modules/home/HomeController.js"></script>`
  `</head>`
  `<body>`
  `<section class="container" ng-controller="HomeController as vm">`
    `<input type="text" placeholder="Enter Your name" ng-model="name" />`
    `<p>Welcome {{ name }} </p>`
    `</section>`
  `</body>`
`</html>`

app.module.js
`angular.module('app', ['ui.router]);`

Problem: 
When I load the page I get {{ name }} instead of the input given but found that if I removed the name passed to both ng-app and ng-controller ( and sometimes totally removing the ng-controller directives), the page works as intended. 
```

**Comment by Koviac** [comment]
here is the plunkr url:
https://run.plnkr.co/TlTDmaleMJ6sB2LZ/

**Comment by petebacondarwin** [comment]
@Koviac the plunker you link to does not seem to exist.

**Comment by Koviac** [comment]
@petebacondarwin

**Problem Fixed.**
Using Chome DevTools I was able to find the source of the problem. It was because angular could not find the module which I was referencing to and therefore could not load itself. After correction, Angular and other modules work well now.

Thanks @petebacondarwin for trying to help out.

**Closing the issue**
