### ISSUE TITLE
Is it possible to enable/disable cssClassDirectivesEnabled for specific controllers

### ISSUE THREAD

**Issue by ali-bugdayci** [angular/angular.js#16689]
I tried to disable class directives in general but enable it for specific controllers:

```
angular.module(ApplicationConfiguration.applicationModuleName).config(
    function ($compileProvider) {
        $compileProvider.cssClassDirectivesEnabled(true);
   }

```

But even though the specific page I am visiting (e.g. landing page) does not have any "Class" directives, the page renders blank.

Is there a way to enable/disable cssClassDirectives for specific controlers/directives etc?

**Comment by gkalpak** [comment]
Since [AngularJS services][1] (like `$compile`) are singletons, configuration applies to the whole app. So, no, it is not possible to disable class directives only for specific parts of the app (modules/controllers/...).

[1]: https://docs.angularjs.org/guide/services

**Comment by ali-bugdayci** [comment]
The reason that I saw blank page was that I was using "ng-cloak" through class directive. I found it by debugging inside angular.js where it founds the class directive.

@gkalpak  I can inject Angular Services inside controllers. Being singleton means that they are refrencing the same object. Hence why not something like this would not work:

```
  angular.module('module').controller("CssClassController", function($scope, $compile) {

    $compile.cssClassDirectivesEnabled(true);

    $scope.$on('$destroy', function() {
         $compile.cssClassDirectivesEnabled(false);
    });

```

but unfortunately I could not access "cssClassDirectivesEnabled()" via $compile injection.

**Comment by gkalpak** [comment]
The `cssClassDirectivesEnabled()` method exists on the `$compileProvider`, not on `$compile`. Thus, you can use it to configure it before actually instantiating `$compile`. Once `$compile` is instantiated, `cssClassDirectivesEnabled` cannot be changed any more and the current value applies for the whole app (that uses the same `$compile` instance).

**Comment by ali-bugdayci** [comment]
Yeah I figured it out too. 

I even tried to cache $compileProvider on window.$compileProvider and call cssClassDirectivesEnabled() in the future but the value is set once in the compiler creation phase only:

https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L2004

Unfortunately it is quite important for us to make Angular 1.x performant, since we can not shift to another Library (Angular 2+ is completely different library for us) where we already have unit tests, protractor test and production tested source code.

So is it possible to address this and let cssClassDirectivesEnabled() to change the variable used at the following line instead of caching it where results in setting it only once.

https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L2728

**Comment by gkalpak** [comment]
> So is it possible to address this and let cssClassDirectivesEnabled() to change the variable used at the following line instead of caching it where results in setting it only once.

If you are asking if we are willing to make this change in AngularJS, then I'm afraid the answer is no :grin:
The current behavior is deliberate (to avoid unexpected and undeterministic behavior). Properly scoping a `$compile` configuration option (e.g. per module) would require a significant amount of work (and probably introducing new concepts).

(Keep in mind that things can get pretty complicated with lazy loaded templates (that delay compilation), lazy compilation of transclude directives, etc.)

##
If you have a simple usecase (e.g. you only need the setting to take effect synchronously and not deal with asynchronous operations), you can easily fork AngularJS and make the necessary changes. At this point, (now that AngularJS has [enter LTS mode][1]), updates to the source code will be rare, so keeping your fork up-to-date won't be a big burden.

[1]: https://docs.angularjs.org/misc/version-support-status

**Comment by ali-bugdayci** [comment]
Yeah I already hacked Angular to use it from global. Tried my best to make it official so that I would not have to update it for every new release :)
