### ISSUE TITLE
IPv6 address returned from $location.host() does not include the brackets in IE/Edge

### ISSUE THREAD

**Issue by kelvinau** [angular/angular.js#16692]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

For example, when the URL is `https://[fd12:3456:789a:74::27]`, `$location.host()` returns `fd12:3456:789a:74::27` in IE/Edge.

This is because `host` and `hostname` of `a` tag element returns the address without bracket, when we use `urlParsingNode`, and we use it in `urlResolve` directly:
https://github.com/angular/angular.js/blob/eb0ccc625f27e6ae550f8c5e0186bd99f986e80b/src/ng/urlUtils.js#L75-L86

**Expected / new behavior:**

`$location.host()` should return the IPv6 address with the brackets. i.e. [fd12:3456:789a:74::27]

**Minimal reproduction of the problem with instructions:**

Call $location.host() at a IPv6 address using IE/Edge

**AngularJS version:** 1.7.4

**Browser:** [ Edge 42.17134.1.0 | IE 11.228.17134.0 ]

**Anything else:**

I suggest that we can check if the address is in IPv6 format, and add brackets to it if it doesn't exist. Not necessary to check if it's IE/Edge.

**Comment by mgol** [comment]
Thanks for the report, I confirm the issue. This is an IE/Edge bug, EdgeHTML 17 still has it but it's fixed in the Edge preview (future 18), see https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16476907/

**Comment by mgol** [comment]
PR: #16715

**Comment by kelvinau** [comment]
great!
