### ISSUE TITLE
Latest versions not available on CDN

### ISSUE THREAD

**Issue by wolfet** [angular/angular.js#16696]
I'm submitting a ...

- [x] bug report
- [x] feature request
- [ ] other

**Current behavior:**
The latest versions of AngularJS, 1.7.3 and 1.7.4, are unavailable on Google and CDNJS CDN.

**Expected / new behavior:**
The latest versions of AngularJS, 1.7.3 and 1.7.4, should be available on CDN.

**Minimal reproduction of the problem with instructions:**
Visiting these URLs results in a 404:
https://ajax.googleapis.com/ajax/libs/angularjs/1.7.3/angular.min.js
https://ajax.googleapis.com/ajax/libs/angularjs/1.7.4/angular.min.js

The listing on CDNJS also does not have the latest versions available when visiting this page:
https://cdnjs.com/libraries/angular.js/

**AngularJS version:** 1.7.3 - 1.7.4

**Browser:** all

**Comment by Narretz** [comment]
We'll try to get the latest versions to Google CDN as soon as possible but CDN JS is outside our control. I'm not sure how they get updated.

**Comment by Narretz** [comment]
Cdn. Js issue. https://github.com/cdnjs/cdnjs/issues/12937#issuecomment-422322849

**Comment by petebacondarwin** [comment]
We have Googlers working on getting the releases onto the Google CDN.

**Comment by CTassisF** [comment]
Copies in Google CDN seems to be live already.

https://ajax.googleapis.com/ajax/libs/angularjs/1.7.3/angular.min.js
https://ajax.googleapis.com/ajax/libs/angularjs/1.7.4/angular.min.js

Btw why is angular.min.js pretty printed?

**Comment by petebacondarwin** [comment]
hmm, the versions here are correct:
*  https://code.angularjs.org/1.7.3/angular.min.js
*  https://code.angularjs.org/1.7.4/angular.min.js

**Comment by mgol** [comment]
Ouch, that's not good. Having the same version differ between CDNs kills security features like Subresource Integrity. :/ Do we send different files to the Google CDN than what's put on https://code.angularjs.org?

**Comment by CTassisF** [comment]
Given that Google CDN uses 1y cache-control headers maybe it is better to release 1.7.5 as a bugfix to the now SRI-broken 1.7.3 and 1.7.4 releases?

```
$ lynx -head -source https://ajax.googleapis.com/ajax/libs/angularjs/1.7.4/angular.min.js | grep Cache-Control
Cache-Control: public, max-age=31536000, stale-while-revalidate=2592000
```

**Comment by IgorMinar** [comment]
I've just looked into this and I see that the code got reformatted via an automatic pre-submit hook in the internal code repo. We'll need a new patch version that we can publish without the auto-formatting to fix this. Sorry about the confusion.

**Comment by Narretz** [comment]
1.7.5 is now on Google CDN, properly minified
