### ISSUE TITLE
ng-change triggered at init with step and invalid value

### ISSUE THREAD

**Issue by NeelLargeronGroupeEram** [angular/angular.js#16705]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other

**Current behavior:**
When using the combinaison of :
- input type="number"
- ng-change
- step
- ng-model with a value not multiple to the step (thus an invalid value).

Then the ng-change is triggered, even if the value didn't change.

**Expected / new behavior:**
The ng-change event shouldn't be triggered because the value didn't change (even if it's invalid), neither by the user or programmatically.

**Minimal reproduction of the problem with instructions:**
<input type="number" ng-model="order.amount" ng-change="amountChanged(order)" step="500">
If the value of order.amount equals 500.01, then the function amountChanged is called.

**AngularJS version:** 1.7.4

**Browser:** [all]
Tested with Chrome 69 and Firefox 62.

**Anything else:**
N/A

**Comment by NeelLargeronGroupeEram** [comment]
I guess it is at compile/linking time of the input.
Here is a test-case :
[bug-case.zip](https://github.com/angular/angular.js/files/2428150/bug-case.zip)

**Comment by petebacondarwin** [comment]
I believe that this is working as expected. When the input is invalid, its value is set to `undefined` thus triggering `ng-change`.

**Comment by NeelLargeronGroupeEram** [comment]
That leaves me to other questions :
- This seems not to be triggered without the "ng-repeat" loop, why ?
- Shouldn't the initial value be undefined ?
- (or shouldn't the value set to Number.NaN ?)

**Comment by NeelLargeronGroupeEram** [comment]
Here is a test-case without the ng-repeat :
[bug-case-without-ng-repeat.zip](https://github.com/angular/angular.js/files/2428794/bug-case-without-ng-repeat.zip)

**Comment by NeelLargeronGroupeEram** [comment]
For now I don't need to have the same behavior, so I close the issue, but might (unlikely) reopen it later.

**Comment by petebacondarwin** [comment]
Thanks
