### ISSUE TITLE
Angular Sanitize with some problems

### ISSUE THREAD

**Issue by Odravison** [angular/angular.js#16703]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

After execute `bower install -f` and downloaded angular-sanitize#1.7.4
I got this error in browser console:
```
Failed to instantiate module kscFinaluserApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngSanitize due to:
TypeError: lowercase is not a function
    at arrayToMap  [...]
```

**Expected / new behavior:**

The correct behavior it's without this error on calling this function.

**Minimal reproduction of the problem with instructions:**

Update any project with angular-sanitize#1.7.4

**AngularJS version:** 1.6.10

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 69.0.3497.92 (Official Build) (64-bit)

**Comment by gkalpak** [comment]
See https://docs.angularjs.org/misc/faq#what-is-the-version-compatibility-between-angularjs-main-and-optional-modules-.
