### ISSUE TITLE
$http cant send large string (base64) correctly --> is set to undefined after call

### ISSUE THREAD

**Issue by EddieSmurfy** [angular/angular.js#16711]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
I'm trying to figuring out how to store a large base64 String (something like "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAYAAAB5fY51AAAgAEl...") into my mongoose-schema. The $http request can't send the String correctly and it is undefined.

**Expected / new behavior:**
The large string should be valid after send.

**Minimal reproduction of the problem with instructions:**

My mongoose-schema :

```
var userSchema = new Schema({
  username: {
    type: String,
    required: true,
    unique: true
  },
  password: {
  type: String,
  required: true
  },
  profilPathImg: String
});
```
My editProfilImg put-function

```
    //router
    router.put('/edit/profilImage', _update.editProfilImg);

    //function in seperate file
    module.exports.editProfilImg = function (req, res) {

      console.log("IMG : " + req.body.profilPathImg); //here it is undefined

      var query = { 'username': req.body.username }

      UserSchema.update(query, {'profilPathImg':req.body.profilPathImg}, function (err, doc) {
        if (err) {
            res.status(401).json(err);
        }
        res.status(201).json(doc);
      })
    }
```

My $http request in angular

```
$scope.SubmitProfilImg = function (croppedDataUri) {

        console.log(croppedDataUri); //here it is valid not undefined

        $http({
            method: "PUT",
            url: "/user/edit/profilImage",
            headers: {'Content-Type': undefined},
            data: {
                "username": $rootScope.decodedToken.username,
                "profilPathImg": croppedDataUri
            }
        }).then(function success(response) {


        }, function myError(response) {
            alertService.showNotificationErrorEditProfilImg();
        });

    }
```
 In my angular function (SubmitProfilImg) the param croppedDataUri is recieved and not null or undefined.

**AngularJS version:** v1.3.20

**Browser:** [all]

**Anything else:**

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!

Also, AngularJS 1.3.20 is no longer supported. You can try upgrading to 1.7.5
