### ISSUE TITLE
Step-8 : E2E test got error code:  ELIFECYCLE

### ISSUE THREAD

**Issue by sunling** [angular/angular.js#16739]
**I'm submitting a ...**

- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

Followed up [Step- 8 - Templating Links & Images](https://docs.angularjs.org/tutorial/step_08),  when I tried to run 'npm run protractor' this command. Browser opened with url http://localhost:8000/index.html but couldn't open the index page 
When I checked the log , I got error code  **ELIFECYCLE**. 
![selection_015](https://user-images.githubusercontent.com/4172600/47226004-60a3d800-d38d-11e8-9791-11718e362dd6.png)

**Expected / new behavior:**

E2E test should run properly 

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.7.x-snapshot

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 70.0.3538.67 (Official Build) (64-bit)

**Anything else:**

Is something wrong with protractor. should we install protractor first?  (tried, failed,same error) 
In this tutorial, it didn't mention about installing protractor. if we need to , what's the version ?

**Comment by Narretz** [comment]
It looks like we need to update protractor, which will then update the Chromedriver. 
In the mean time you can do `npm install protractor@5.4.1` and then re-run, which should install the latest Chromedriver.

**Comment by sunling** [comment]
I updated protractor to 5.4.1 and installed the latest chromedriver. `package.json` look like this. 
![phonecat package json](https://user-images.githubusercontent.com/4172600/47505916-0dbe9a80-d83d-11e8-98cb-d56cfee939de.png)

1. run `npm run start  ` command first

1. Open a new terminal window, run `npm run protractor.` it worked. But the test failed because i guess the logic is not right. 
![image](https://user-images.githubusercontent.com/4172600/47506370-e6b49880-d83d-11e8-9294-3286b53669eb.png)

**Comment by Narretz** [comment]
The tests work for me (in Windows). Did you change something in the code?

**Comment by sunling** [comment]
No. I reset the workspace to step 8 by running `git checkout -f step-8`. I am using Linux(to be specifc gLinux).

**Comment by gkalpak** [comment]
I am in the process of upgrading the tutorial (on last time :cry:) to v1.7.x. I will ensure the tests pass with the upgraded deps.
In the mean time, can you try running the tests a few times and see if you get the exact same failures consistently?

**Comment by sunling** [comment]
I tested for 3 times , same as the first time(the screenshot showed at previous comment).

**Comment by sunling** [comment]
Why there is a `scenariosbk.js` file ? It seems it is not the same as `scenarios.js` file.

**Comment by gkalpak** [comment]
No idea where the `*bk.js` file came from :grin:

**Comment by sunling** [comment]
I changed a little bit on the `scenariosbk.js ` . Two of tests passed. There is only a warning left which says `browser.getLocationAbsUrl()` is deprecated

**Comment by sunling** [comment]
No. My apologies. It works! What all I need to do is to update protractor. 
1. I re-cloned the phonecat repo
2. `npm install protractor@5.4.1`
3. `npm run start`
4. `npm run protractor`

**Comment by gkalpak** [comment]
Awesome! Glad you got it working.
I'll go ahead and close this issue then (since we are in the process of upgrading our tutorial dependencies as mentioned above).
