### ISSUE TITLE
Reset event listener defined on $rootScope to not called multiple times.

### ISSUE THREAD

**Issue by jainanuj0812** [angular/angular.js#16732]
As defining any event listener on the rootScope called multiple times (called as it is not destroyed, need to destroy manually). Is there any way to define events in such a manner that the listener gets reset and not called multiple?

**Comment by gkalpak** [comment]
No, there no built-in way to ensure a listener is only called once. But it is easy to create your own helper that does that (i.e. unregistering the listener once it is called).

**Comment by jainanuj0812** [comment]
@gkalpak, thanks for the reply. I am able to envoke the event listener that is unregistered, is it known behaviour? 

If not, then what would be expected? 

If yes, Is it good practice to unregister listener and then again re-envoking it by emitting an event?

**Comment by gkalpak** [comment]
If you unregister a listener that it should be called again by emitting events.
But it is not 100% cleat what you are doing. If you think there is a bug in AngularJS, please create a minimal reproduction (e.g. using CodePen, Plnkr, etc), to ensure we are on the same page :wink:
