### ISSUE TITLE
New Google browser uploads caused the browser to crash

### ISSUE THREAD

**Issue by neikami** [angular/angular.js#16731]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 
**Current behavior:**

 New Google browser uploads caused the browser to crash. I used angularjs 1.4.6 in  Chrome  69.0.3497.92 
**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.4.6

**Browser:** [all | Chrome  69.0.3497.92 | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by neikami** [comment]
New Google browser uploads caused the browser to crash

**Comment by gkalpak** [comment]
This doesn't sound like an AngularJS issue. Try upgrading to the latest version and if you believe this is a bug in AngularJS, please open a new issue providing a minimal reproduction.
