### ISSUE TITLE
I wants 12 parameter from the server in Firefox but it unable to do so , same thing running fine in chrome browser

### ISSUE THREAD

**Issue by avne31** [angular/angular.js#16736]
I'm working on Angular application, In Firefox browser I'm unable to download PDF file but the same code is running fine in Chrome browser and I'm also able to download the PDF file too.

The Reason might be:

In case of Firefox browser, I am only getting content type name of file as 'jpeg/image' from HttpEventType.Response.
![firefox](https://user-images.githubusercontent.com/38249841/47148531-8cbc4c00-d2ee-11e8-9596-84dab6fcef8b.PNG)

And in case of Chrome browser, I am getting name of file as 'xyz.png' from HttpEventType.Response
![google](https://user-images.githubusercontent.com/38249841/47148548-9e055880-d2ee-11e8-8b03-186744f1c428.PNG)

Also chrome passes 12 file-size while Firefox passes only 1 as file-size.

please help me in this.

Thanks

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
