### ISSUE TITLE
Hide the Browser Address Bar

### ISSUE THREAD

**Issue by timusiiit123** [angular/angular.js#16747]
Hello,
I am new to Angular. I am learning to create responsive web app in Angular. And I have a problem with the browser address bar. I want to hide the browser (any browser on any mobiles) address bar when the page is scroll down. I don't know how to do this.

**Comment by gkalpak** [comment]
This question is not related to AngularJS. You could ask such question on [StackOverflow][1] or [Gitter][2].
<sub>(That said, I don't think it is possible for web-apps to hide the browser address bar like this.)</sub>

[1]: https://stackoverflow.com/
[2]: https://gitter.im/
