### ISSUE TITLE
Page rendered blank with geneated component using cmd - "ng generate @angular/material:material-nav --name=app-nav"

### ISSUE THREAD

**Issue by NLSrikanth** [angular/angular.js#16741]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
I've generated a component using command - "ng generate @angular/material:material-nav --name=app-nav". Now when I run the app with <app-app-nav></app-app-nav> the page is rendered blank. Following is the  default content in app-nav.component.html :

"<mat-sidenav-container class="sidenav-container">
  <mat-sidenav #drawer class="sidenav" fixedInViewport="true"
      [attr.role]="(isHandset$ | async) ? 'dialog' : 'navigation'"
      [mode]="(isHandset$ | async) ? 'over' : 'side'"
      [opened]="!(isHandset$ | async)">
    <mat-toolbar>Menu</mat-toolbar>
    <mat-nav-list>
      <a mat-list-item href="#">Link 1</a>
      <a mat-list-item href="#">Link 2</a>
      <a mat-list-item href="#">Link 3</a>
    </mat-nav-list>
  </mat-sidenav>
  <mat-sidenav-content>
    <mat-toolbar color="primary">
      <button
        type="button"
        aria-label="Toggle sidenav"
        mat-icon-button
        (click)="drawer.toggle()"
        *ngIf="isHandset$ | async">
        <mat-icon aria-label="Side nav toggle icon">menu</mat-icon>
      </button>
      <span>myBuddy</span>
    </mat-toolbar>
    
  </mat-sidenav-content>
</mat-sidenav-container>"

I'm using the latest angular core, material and cdk.

**Expected / new behavior:**
Content of sidenav should be displayed properly.

**Minimal reproduction of the problem with instructions:**
1. Generate a component using cmd - "ng generate @angular/material:material-nav --name=app-nav"
2. use that selector in app.component.html '<app-app-nav></app-app-nav>'.
3. start the app.

**AngularJS version:** 1.x.y
    "@angular-devkit/build-angular": "^0.10.1",
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "ngx-perfect-scrollbar": "^6.3.1",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Anything else:**
No error reported on console. Compilation is successful.

**Comment by NLSrikanth** [comment]
Another observation:

When I replace the default content of 'app-nav.component.html' with simple html paragraph code then it's rendering the content properly. Seems like the issue is with the code generated by default.

**Comment by petebacondarwin** [comment]
This repository is for AngularJS. You want to report this one https://github.com/angular/angular.
