### ISSUE TITLE
Problem with ngSrc and src order (with 1.7.x)

### ISSUE THREAD

**Issue by cadilhac** [angular/angular.js#16766]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
With angularjs 1.6.10, this code was working correctly:
`<img ng-src="{{$ctrl.image}}" src="pathToDefaultImage" />`

I was able to invert src and ng-src for the same result.

Starting with angularjs 1.7.0, I **must** ensure that the src attribute appears before the ng-src attribute or ng-src will have no effect.

**Minimal reproduction of the problem**
http://next.plnkr.co/edit/pnBZfbhJurl9jHRR

In this sample, I also noted that it works again if you remove the link to angular-sanitize.js

**Comment by gkalpak** [comment]
I wonder if this would be also fixed by #16737.
cc @petebacondarwin

**Comment by petebacondarwin** [comment]
I suspect it would. I'll check now.

**Comment by petebacondarwin** [comment]
Yes, it does fix it. I added a test to that PR to prove it: https://github.com/angular/angular.js/pull/16737/commits/0687a4f70a16315aacd9e74edaaac466208bb86d

**Comment by gkalpak** [comment]
Fixed by #16737 (merged into v1.7.x as 90a41d415).
