### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by sameeakhtar** [angular/angular.js#16785]
My angular 2 application giving performance Issue in IE where as it's working fatser in chrome,
Could you please help me what caused performance issue in IE and Edge?

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question). Thanks!
