### ISSUE TITLE
What type of support i will get once LTS period gets over for AngularJS 1.7.x

### ISSUE THREAD

**Issue by Kaliyani** [angular/angular.js#16787]
Hi Team,

Currently my application is running in AngularJS 1.7.x. What type of supports i will get once LTS period gets over (after June 30th 2021) for AngularJS 1.7.x. Do i really need to upgrade to Angular 7 and above. 

Already LTS period got over for other versions like Angular 2 and Angular 4. So shall i expect some support for that versions too.

**Comment by frederikprijck** [comment]
I'm not aware of what's gonna happen once LTS is over. 

However, It's encouraged to not wait until then to move to Angular. It's a good idea to already take steps towards migration so you can use the latest and greates, which will eventualy benefit your application.

**Comment by petebacondarwin** [comment]
Hi @Kaliyani

When the AngularJS LTS period runs out there will be no more official support for AngularJS. That means that there will be no more releases of AngularJS: so no more features or bug fixes.

This does not mean that you must stop using AngularJS: it will continue to work for you as it does now. AngularJS has not received many new features in the last year or so. It is a very mature and stable product. As a consequence of that and the many many projects using it in production, the vast majority of bugs have been identified and fixed. Therefore it is unlikely that new bugs will be discovered during and after the LTS period.

Nor does it mean that you must upgrade to Angular: indeed many projects will never upgrade, they simply work as they are and do not need to be modified to use Angular. If you are actively developing your application, and you determine that AngularJS will not support your current or future requirements then that would be a good time to consider upgrading to Angular. If you do upgrade then there is no benefit in going through each of the Angular versions (2, 4, 5, 6, ...) - instead you would go straight to the current version (e.g. 7.2).
