### ISSUE TITLE
how to build a barchart using angularjs(version 1.x.x) with json data

### ISSUE THREAD

**Issue by Hema55** [angular/angular.js#16782]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.x.y

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
