### ISSUE TITLE
Dynamic ngInclude inside ngRoute is not working

### ISSUE THREAD

**Issue by raghuveersubbarao** [angular/angular.js#16784]
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-animate.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-sanitize.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-route.min.js"></script>

                <uib-tabset active="active" >             
                    <uib-tab ng-repeat="tab in tabs" id="{{tab.id}}" index="$index+ 1">                                                   
                        <uib-tab-heading>
                            <i class="{{tab.class}}"></i>{{tab.title}} 
                        </uib-tab-heading>                            
                        
                        <ng-include src="{{tab.temp}}"> </ng-include> 
                    </uib-tab>
                    <uib-tab active="inactive">
                        <uib-tab-heading>Testing</uib-tab-heading>
                        
                        <ng-include src="'../Party/PartyCreation.html'"> </ng-include>
                    </uib-tab>

**Comment by Narretz** [comment]
ngInclude expects an expression, not an interpolation. Try with `<ng-include src="tab.temp"> </ng-include>`

**Comment by raghuveersubbarao** [comment]
> ngInclude expects an expression, not an interpolation. Try with `<ng-include src="tab.temp"> </ng-include>`

In my example, i put 2 different types of <ng-include>

1.  <ng-include src="'../Party/PartyCreation.html'"> </ng-include>
2.  <ng-include src="{{tab.temp}}"> </ng-include> 

#1 is working, #2 is not working. I want to load html page dynamically... For that, i am using the ng include inside the ng repeat, but it is not working ...

**Comment by raghuveersubbarao** [comment]
@Narretz Thank you... :-)
