### ISSUE TITLE
Sanitizer cannot sanitize xss locator (polyglot)

### ISSUE THREAD

**Issue by harsharora001** [angular/angular.js#16791]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
AngularJS sanitizeProvider unable to sanitize xss locator (polyglot)

**Expected / new behavior:**
The code should ideally clean this.

**Minimal reproduction of the problem with instructions:**
The code can be seen here https://plnkr.co/edit/kehOWg7NJfxI1zc8Xl8N?p=preview

**AngularJS version:** 1.7.1 / 1.5.2

**Browser:** all 

**Anything else:** no

**Comment by gkalpak** [comment]
Not sure what you have in mind. The `alert(12345)` is executed in the controller JS code (before it ever gets to `ng-bind-html`). This is not a sanitization issue.
If an attacker can execute JS code, then there is nothing you can do about it :grin:
