### ISSUE TITLE
The URI is malformed. ng V.7.1.3

### ISSUE THREAD

**Issue by dvsingh9** [angular/angular.js#16794]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

Making reqeuest to zoho mail api for auth token, here is code 👍 

 ```
 getAuthToken(code: string): void {
    
    const params = new HttpParams()
    .append('code', code)
    .append('grant_type', 'authorization_code')
    .append('scope', 'messages.READ')
    .append('clientId', '1000.3BU2UYF4F2S9MGZKOPSBYMU')
    .append('client_secret', '953c68cf3ab913e13afd8a0935d2e1193c5')
    .append('redirect_uri', 'http://localhost:4200/main/dashboard');
    
    this.http.post('http://accounts.zoho.com/oauth/v2/token', {}, {params: params})
    .toPromise()
           .then(this.extractData)
           .catch(this.handleErrorPromise);
  }
```

My params are encode as below 👍 

`code=1000.2809fccf40407db65fd2d2cc32160c.84b7d61b8db9b37957aeb5bd75b0b8&grant_type=authorization_code&scope=messages.READ&clientId=1000.3BU2UYF4F2S9MGZKOPSBYMU&client_secret=953c68cf3ab913e13afd8a0935d2e1193c5&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fmain%2Fdashboard`

Getting The URI is malformed.

**Comment by simplesethia** [comment]
I think you are using wrong parameter name for client id. It should be client_id instead of clientId. Please see if this helps.

**Comment by Narretz** [comment]
Hi, your issue reads like a support question. This github repo is only for bug reports and feature requests. Please try one of the listed [Support Channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question). Thanks!
