### ISSUE TITLE
Erro ao utilizar ui.router.

### ISSUE THREAD

**Issue by Bergsonjr** [angular/angular.js#16792]
Erro no console;

![image](https://user-images.githubusercontent.com/44247346/50005079-338c3400-ff90-11e8-9eff-115cae80f92d.png)

Código do index:

![image](https://user-images.githubusercontent.com/44247346/50005108-4868c780-ff90-11e8-9f13-bce512c76dc5.png)

**Comment by petebacondarwin** [comment]
The syntax error is in your `app.js` file. Perhaps you have misspelled its path and the web server is returning `index.html` instead?
This is more of a support issue and not an issue with AngularJS itself. Please try StackOverflow or the mailing list for more help.
