### ISSUE TITLE
Locale Information for locale de-at is wrong

### ISSUE THREAD

**Issue by RainerNeunteufel** [angular/angular.js#16803]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

The angular locale information for the locale de-at is wrong.
At the moment the GROUP_SEP is an empty string.
Locale information is generated from locale spec version 29, which contains wrong locale information for austrian locale.

see: https://unicode.org/cldr/trac/browser/tags/release-29/common/main/de_AT.xml

**Expected / new behavior:**

 GROUP_SEP should be a dot.
Locale information is fixed in spec version 30.

see: https://unicode.org/cldr/trac/browser/tags/release-30/common/main/de_AT.xml

**Minimal reproduction of the problem with instructions:**

Use angular-locale_de-at.js and format number with number pipe.

**AngularJS version:** 1.x.y

^1.6.2

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]

all

**Anything else:**

**Comment by gkalpak** [comment]
AngularJS uses the [Google Closure I18N library][1], to generate its own I18N files. This means that any changes should be made there first and then pulled into AngularJS.

That said, from a quick look at https://unicode.org/cldr/trac/browser/tags/release-30/common/main/de_AT.xml, the locale seems to use a different group separator for numbers vs currency (which is not supported by AngularJS anyway

[1]: https://github.com/google/closure-library/tree/master/closure/goog/i18n
