### ISSUE TITLE
Request: add an option to ngModelOptions directive, so that emptying an input would uninitalize whole model's object, instead of keeping it with empty string

### ISSUE THREAD

**Issue by mr-moon** [angular/angular.js#16805]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other 

**Current behavior:**

When model is bound via `<input type="text" ng-model="obj.prop">` then `obj.prop` is populated with value of the input. If `obj` was uninitialized on scope, typing anything to input makes angular to initialize it. But then, if you remove the value from the input (read revert it to visually pristine state) `obj.prop` remains populated with empty string. This defeats the purpose `angular.equals` in this scenario, and `ngForm` stays in `$dirty`.

**Expected / new behavior:**

`<input type="text" ng-model="obj.prop" ng-model-options="{purgeOnEmpty: true}">` could `delete obj['prop']` completely, if input's value is set to empty string. Additionally it could unset whole `obj` from scope, if `obj` doesn't have other properties, or this could be controlled via additional flag to ngModelOptions.

This simplifies controllers a logic in cases when initial state of manipulated object is retrieved from db and given to `ngFormController` for manipulations.

**Comment by petebacondarwin** [comment]
I'm afraid that we are now in LTS mode for this project, so we are not adding any new features. You could possibly achieve this behaviour by creating a custom directive that hooked into the `$parser` and converted empty string to `undefined`.
