### ISSUE TITLE
Error on production build but okay in development build

### ISSUE THREAD

**Issue by flashery** [angular/angular.js#16819]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

I am currently taking over a project created in laravel with angular js. If I try to build it in development mode its fine. But I got error if we build the app in production.

**Expected / new behavior:**

It should load the webpage
**Minimal reproduction of the problem with instructions:**

I already tried this 

https://stackoverflow.com/questions/31779615/angular-in-rails-throws-an-error-in-production-error-injectorunpr-unknown

and it gives me an error
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.config due to:
Error: [$injector:unpr] Unknown provider: NotificationConfig
```

Here is my code
```js
import {RoutesConfig} from './config/routes.config';
import {NotificationConfig} from './config/notification.config';
import {LocalstorageConfig} from './config/localstorage.config';
angular.module('app.config')
    .config(NotificationConfig)
    .config(RoutesConfig)
    .config(LocalstorageConfig)
    .config(['$httpProvider', function ($httpProvider) {
        $httpProvider.interceptors.push('httpErrorsInterceptor');
    }])
```

**AngularJS version:** 1.5.8

**Browser:** all

**Anything else:** None

**Comment by frederikprijck** [comment]
Are you injecting `NotificationConfig ` somewhere?

**Comment by gkalpak** [comment]
It is impossible to tell what might be wrong without a reproduction (and we can only make guesses - which is fun, but not necessarily productive 😛).

In any case, this sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by flashery** [comment]
Here is the code for the NotificationConfig

```
export function NotificationConfig(NotificationProvider) {
	'ngInject';

    NotificationProvider.setOptions({
        delay: 2000,
        startTop: 50,
        startRight: 0,
        verticalSpacing: 0,
        horizontalSpacing: 50,
        positionX: 'right',
        positionY: 'top'
    });
	
}

```
