### ISSUE TITLE
angular 使用ocLazyLoad 按需加载后，url地址一直有#/tab1，刷新后怎么用原来没有#的地址

### ISSUE THREAD

**Issue by HuZhuangQiang** [angular/angular.js#16811]
angular 使用ocLazyLoad 按需加载 html和js代码，点击这个加载事件后，再次刷新页面，url地址后面加上了“#   ”，我想刷新页面后，地址还是原来的地址，不要# ，这个怎么解决

**Comment by gkalpak** [comment]
I am not sure what you are saying, but (according to Google translate) you seem to be having some issue with ocLazyLoad (which is not part of this repo) and handling the URL hash (which sound like two unrelated things tbh). In any case, this sounds like a general support question, so please use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
