### ISSUE TITLE
MdDatepicker of angular material does not work with most recent version 1.7.7

### ISSUE THREAD

**Issue by dohomi** [angular/angular.js#16829]
**I'm submitting a ...**
- [ x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
MdDatepicker stopped working on Angular Material with the most recent version of AngularJs 1.7.7

**Expected / new behavior:**
MdDatepicker was working on v1.7.5

**Minimal reproduction of the problem with instructions:**
https://codepen.io/anon/pen/jdGwLK?editors=1111

**AngularJS version:** 1.x.y
1.7.7

**Browser:** [all]

**Comment by mgol** [comment]
Thanks for the report. It seems the pen loads non-existing files from the Google CDN, doesn't it? All the AngularJS files return 404. If you upgrade AngularJS please make sure new URLs return expected files; it may take a while for the CDN to pick up a new release.

Now, for testing purposes (it's not the CDN!) the files should be available at https://code.angularjs.org/1.7.7/, similarly how there's a folder at https://code.angularjs.org/1.7.6/. Our deploy job failed so the files didn't get there, we're fixing it now.

In the meantime, you can take files from npm or unpkg.com which also hooks into npm, e.g. AngularJS itself is available at https://unpkg.com/angular@1.7.7/angular.min.js

See the fixed Pen at https://codepen.io/mgol/pen/MLEGdj?editors=1111.

Is there anything else that doesn't work for you here?

**Comment by dohomi** [comment]
@mgol I mainly reported it because in my current project after upgrading to 1.7.7 all datepicker stopped to work as well. But I can't do a reproduction repo for it. Will investigate further and will report back here

**Comment by petebacondarwin** [comment]
Files are now on https://code.angularjs.org/1.7.7/

**Comment by gkalpak** [comment]
Closing, since everything seems to work fine.
@dohomi, please open a new issue if you find problems with 1.7.7 and `MdDatepicker`.
