### ISSUE TITLE
Wrong generate href

### ISSUE THREAD

**Issue by Zadvornyi** [angular/angular.js#16821]
I have created an issue (I have migrated for AngularJS 1.6.10 to 1.7.5. After migration almost, all links are broken. A href is not generated.) [#16809](https://github.com/angular/angular.js/issues/16809). The answer was, that it is This is a duplicate of #16734. It will be included in the next release.

However, after updating to new release 1.7.6. I encountered the same bug.

```
<a href="" ui-sref="app.state1.substate">Link</a>
Expected Result:
<a href="/app/state1/substate/" ui-sref="app.state1.substate">Link</a>

But after migration:
<a href="wrong url" ui-sref="app.state1.substate">Link</a>
```

**Comment by frederikprijck** [comment]
I might be wrong here, but this looks like to be related to `angular-ui`, not `angularjs` ?

**Comment by biggieman** [comment]
Yes, it's ui-router behaviour. You need to remove empty href attribute:
`<a ui-sref="app.state1.substate">Link</a>`

**Comment by Zadvornyi** [comment]
I tried to delete href. It does not work

**Comment by Zadvornyi** [comment]
Problem was with @uirouter/angularjs. I have used @uirouter/angularjs": "1.0.21. But solution was downgrate to @uirouter/angularjs": "1.0.18
