### ISSUE TITLE
should i create one page angular 6 application without use ng new myapp command ?

### ISSUE THREAD

**Issue by JigneshPatel04** [angular/angular.js#16855]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [x] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.7.x

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]

**Anything else:**

**Comment by JigneshPatel04** [comment]
I need to create one page in angular 6 but i donot need to use ng new myapp command. i donot need more files on projects. plz guide me hows to use on one html page ?

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by petebacondarwin** [comment]
Also this repository is for AngularJS not Angular.
