### ISSUE TITLE
The back end received multiple posts

### ISSUE THREAD

**Issue by liuzhipeng1234** [angular/angular.js#16864]
I used http.post() function to create something.
In my server, I used firewall to drop everything.
Then,I found that there are same post come in about 4 times.
Next,I used wireshark and I found angularjs post many times.

I only want to post once.How should I do?

My coding:
```
return this.http.post<Rule>(url, {
            "project_id": this.localUser.project_id,
            "name": name,
            "protocol": protocol,
            "source_ip_address": source_ip_address,
            "source_port": source_port,
            "destination_ip_address": destination_ip_address,
            "destination_port": destination_port,
            "description": description,
            "action": action,
            "enabled": enabled
        }, this.getHttpOptions());
```

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
