### ISSUE TITLE
Add the label "good first issue" for newbie

### ISSUE THREAD

**Issue by SunflowerPKU** [angular/angular.js#16867]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.7.x

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]

**Anything else:**

**Comment by gkalpak** [comment]
As mentioned in the issue template:

> We are no longer accepting changes that are not critical bug fixes into this project.
> See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

Therefore, there is no point in adding a "good first issue" label.
You might want to checkout the Angular repo instead: [hotlist: community-help][1]

[1]: https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22hotlist%3A+community-help%22
