### ISSUE TITLE
Custom Parsers on Input with ngModel does not add 'ng-invalid-parse' class for invalid data.

### ISSUE THREAD

**Issue by ChaitanyaBabar** [angular/angular.js#16866]
# Custom Parsers on Input does not add 'ng-invalid-parse' class for invalid input.

For invalid input to input box it should add class `ng-invalid-parse` instead of `ng-invalid-[inputType]` , as mentioned in docs [here](https://code.angularjs.org/1.7.0/docs/guide/migration#-ngmodel-input-) & also as per commit [here](https://github.com/angular/angular.js/commit/74b04c9403af4fc7df5b6420f22c9f45a3e84140) ,

**I'm submitting issue...**

- [x] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ ] other 

**Current behavior:**
For Invalid input data the class 'ng-invalid-parse' class is not present.

**Expected / new behavior:**
For Invalid input data the class 'ng-invalid-parse' class should be added.

**Minimal reproduction of the problem with instructions:**
Issue can be seen on jsFiddle link [here](https://jsfiddle.net/10hoLb82/13/). 

**AngularJS version:** 1.7.x
Yes it is present with AngularJS version 1.7.x.

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]
**N/A**

**Comment by gkalpak** [comment]
I don't see any custom parsers in the provided examples. (And even in `ngMaterial`, the only relevant custom parser I can see is [this one][1], which can't fail.)

This sounds like a `ngMaterial` issue (but I don't think it is related to custom parsers).
In any case, please open an issue in the [AngularJS Material repo][2].

[1]: https://github.com/angular/material/blob/22d773966610d6b97c49f4430d41dd00e16cede6/src/components/input/input.js#L405
[2]: https://github.com/angular/material
