### ISSUE TITLE
URL query string value encoding

### ISSUE THREAD

**Issue by AmarjitMindtree** [angular/angular.js#16871]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ x] other 

**Current behavior:**

If we pass data in query string in GET method with param value of HTTP PARAMS, by default it is not converting '@' symbol to %40 or any other reserved symbol with is corresponding UTF-8 code. It should convert '@' to %40, because of this I am not able to use http get with querystring.
eg, http://localhost:4200/api/usersData?userName=xxx.xxx@xxx.com&password=xxx@xxx
above request is failing.

**Expected / new behavior:**

function standardEncoding(v: string): string {
  return encodeURIComponent(v)
      .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, '=')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/');
}

this code is not able to convert @ to %40. It should do that.
If is write replace('@', '%40') then it is working.

**Minimal reproduction of the problem with instructions:**

Below mentioned code is the service code which is making a GET request with query string.

data passed is,
userName = xxx@xxx.com
password = pwd@#

const options = {
  headers: new HttpHeaders({
    'Content-Type': 'application/json',
  }),
  observe: 'response' as 'body',
  params: null,
  reportProgress: true,
  responseType: 'json' as 'json',
  withCredentials: true
};

@Injectable({
  providedIn: 'root'
})
export class AuthenticationService {

  constructor(private http: HttpClient) {
  }

  // login user
  login(requestParam: { userName: string, password: string }): Observable<HttpResponse<object>> {
    options.headers = options.headers.set('Content-Type', 'application/x-www-form-urlencoded');
    options.params =  new HttpParams({ fromObject: requestParam, encoder: this.httpParameterCodec });
    console.log(options.params);
    return this.http.get<HttpResponse<Observable<object>>>
    (`${environment.API_URL}usersData`, options)
    .pipe(
      // retry(3),
      catchError(this.handleError)
    );
  }

**Angular version:** 7.0 +

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]

**Anything else:**

I am using in-Memory-Api for making request.

**Comment by petebacondarwin** [comment]
@AmarjitMindtree - this is the repository for the old AngularJS framework, not the Angular framework, which is at https://github.com/angular/angular. You should post your issue there.

That being said, I assume from your reproduction what you are using `HttpUrlEncodingCodec` for `this.httpParameterCodec`, which as you suggest calls `standardEncoding()`.  In that method it appears that this function converts `%40` back to `@` (after I assume that `encodeURIComponent()` had previously converted the `@` to `%40`.  This seems to be intentional. We could ask @alxhub why he did that. But in the meantime if you don't like it, it is fairly straightforward for you to provide your own `HttpEncodingCodec` implementation that works as you require.

**Comment by AmarjitMindtree** [comment]
> @AmarjitMindtree - this is the repository for the old AngularJS framework, not the Angular framework, which is at https://github.com/angular/angular. You should post your issue there.
> 
> That being said, I assume from your reproduction what you are using `HttpUrlEncodingCodec` for `this.httpParameterCodec`, which as you suggest calls `standardEncoding()`. In that method it appears that this function converts `%40` back to `@` (after I assume that `encodeURIComponent()` had previously converted the `@` to `%40`. This is intentional (see [angular/angular@1620426](https://github.com/angular/angular/commit/16204263939944a04e717f4dd44fdb9eb63119c5)) and it is also the implementation used in [other areas of Angular](https://github.com/angular/angular/search?q=.replace%28%2F%2540%2Fgi%2C+%27%40%27%29).
> 
> In the meantime if you don't like it, it is fairly straightforward for you to provide your own `HttpEncodingCodec` implementation that works as you require.

-----------------------
But I am sending a direct request, with param(username, value contained @), it is showing me error 404 and without @ symbol in value request is passing.

I understood framework is converting %40 back to @, but with @ request is not processing
