### ISSUE TITLE
angular.js 1.3.13 script is truncated at https://code.angularjs.org/1.3.13/angular.js

### ISSUE THREAD

**Issue by gudovich** [angular/angular.js#16870]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ X] other 

**Current behavior:**
Code that uses the script by loading it from https://code.angularjs.org/1.3.13/angular.js is now broken as the script at that location is truncated (not complete)

**Expected / new behavior:**
Expected that the script for that version of Angular is complete at <https://code.angularjs.org/1.3.13/angular.js> so that the application code could use it as required when loading in browser.

**Minimal reproduction of the problem with instructions:**
Launch https://code.angularjs.org/1.3.13/angular.js in any browser to view the script at that location and scroll to the bottom of the page.

**AngularJS version:** 1.3.13
Not an issue in the current version of Angular.

**Browser:** all

**Anything else:**

**Comment by petebacondarwin** [comment]
Hmm, when I browse the file in question it is not truncated. But I think we may have had a problem similar to this before where the Firebase CDN does not proliferate correctly across its nodes and leaves some node with partial files? @Narretz  or @gkalpak do you recall that and what we did to fix it?

**Comment by gudovich** [comment]
It appears to be working now even for me... not sure if anything was done, but I am seeing the full script at that location and the issue can now be marked resolved. @petebacondarwin thank you for your help and taking a look!

**Comment by petebacondarwin** [comment]
Glad it is working. Perhaps it was a flaky internet moment :-)

**Comment by gkalpak** [comment]
BTW, @gudovich, `code.angularjs.org` is not a supposed to be used a CDN in production. (It is more for demos/examples/issue reproductions.)
For production, you are better off using an actual CDN (see https://docs.angularjs.org/misc/downloading).

**Comment by gudovich** [comment]
@gkalpak thanks for the suggestion, we are going to be switching to local storage of scripts shortly, so that dependency will be removed. This is just to get us over the hump :)
