### ISSUE TITLE
$eval of angular returning undefined in Edge

### ISSUE THREAD

**Issue by kogoel** [angular/angular.js#16881]
Using $eval of angular js in edge returning undefined for the first time.
While refreshing the page, the $eval value is evaluated and page is rendered.

**Comment by gkalpak** [comment]
This sounds like either an application error or a browser bug. In any case, you didn't provide enough information (e.g. a minimial reproduction) for us  to investigate and there is no indication that this is a bug in AngularJS.

BTW, AngularJS is now in [LTS mode][1], so we are not actively fixing issues unless they fall under specific categories (see the linked page for more details).

[1]: https://docs.angularjs.org/misc/version-support-status
