### ISSUE TITLE
Failed to instantiate module ng due to: TypeError: Cannot set property 'aHrefSanitizationWhitelist' of null when code migrating from 1.4.8 to 1.7.8

### ISSUE THREAD

**Issue by sivasatyababu** [angular/angular.js#16884]
I am getting the error when I try to migrate from 1.4.8 to 1.7.8.  When I debugged it $$SanitizeUriProvider getting null when below method executed.
function instantiate(Type, locals, serviceName) {
      // Check if Type is annotated and use just the given function at n-1 as parameter
      // e.g. someModule.factory('greeter', ['$window', function(renamed$window) {}]);
      var ctor = (isArray(Type) ? Type[Type.length - 1] : Type);
      var args = injectionArgs(Type, locals, serviceName);
      // Empty object at position 0 is ignored for invocation with `new`, but required.
      args.unshift(null);
      return new (Function.prototype.bind.apply(ctor, args))();
    }

Please help me if any dependencies I missed in this scenario. 
Below are my bower.json, package.json files.
Bower.json
{
  "name": "test",
  "authors": [
    "Test",
    "IT Development",
    "testfds"
  ],
  "license": "proprietary",
  "dependencies": {
    "angular": "1.7.8",
    "angular-resource": "1.7.8",
    "angular-route": "1.7.8",
    "angular-bootstrap": "^1.0.0",
    "ng-prettyjson": "^0.1.9",
    "spin.js": "^2.0.1",
    "angular-sanitize": "1.7.8",
    "angular-spinner": "^0.6.1",
    "angular-apimock": "^0.3.3",
    "moment": "^2.19.2"
  },
  "resolutions": {
    "angular": "1.7.8"
  }
}
Package.json
"devDependencies": {
    "angular-mocks": "1.7.8",
    "chai": "^3.2.0",
    "grunt": "^0.4.5",
    "grunt-bowercopy": "^1.2.3",
    "grunt-cli": "^0.1.13",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-connect": "^0.11.2",
    "grunt-contrib-copy": "^0.8.0",
    "grunt-contrib-jshint": "^0.11.3",
    "grunt-contrib-less": "^1.0.1",
    "grunt-contrib-uglify": "^0.9.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-env": "^0.4.4",
    "grunt-karma": "^0.12.0",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.1.1",
    "karma-junit-reporter": "^0.3.3",
    "karma-mocha": "^0.2.0",
    "karma-mocha-reporter": "^1.1.1",
    "karma-phantomjs-launcher": "^0.2.1",
    "karma-sinon": "^1.0.4",
    "mocha": "^2.2.5",
    "phantomjs": "^1.9.18",
    "phantomjs-polyfill": "0.0.2",
    "sinon": "^1.15.4"
  }

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
