### ISSUE TITLE
newly opened uib-modal hides behind already opened uib-modal in angularjs

### ISSUE THREAD

**Issue by nazirmohd2006** [angular/angular.js#16887]
t.selectCompany = function () {
        console.log("Check this message company!");
        var n = r.open({
            scope: t,
            templateUrl: "template/company-selector.html",
            controller: "CompanySelectorCtrl",
            controllerAs: "ctrl",
            size: "md",
            backdrop: "true",
            transclude: true,
            resolve: {
                data: ["CompanyService", function (e) {
                    console.log("Data : "+e.all());
                    return e.all()
                }]
            }
        });
        n.result.then(function (r) {
            console.log("Data : "+r.id+" : "+ r.name);
            e.currentCompanyId = r.id, e.currentCompanyName = r.name, t.flushData()
        })
    }, t.$on("trash:selectCompany", function () {
        console.log("bind success!!"), t.selectCompany()
    })
}]), app.controller("MachineEditCtrl", ["$rootScope", "$scope", "$uibModal", "$uibModalInstance", "$translate", "MachineService", "machine", "companyResp", function (e, t, r, n, o, a, i, s) {
    t.machine = angular.copy(i), t.selectCompany = function () {
        console.log("Check this message!");
        var e = r.open({
            scope: t,
            templateUrl: "template/company-selector.html",
            controller: "CompanySelectorCtrl",
            controllerAs: "ctrl",
            size: "md",
            transclude: false,
            backdrop: "static",
            resolve: {
                data: function () {
                    return s.data
                }
            }
        });
        e.result.then(function (e) {
            t.machine.companyId = e.id, t.machine.companyName = e.name
        })
    }, this.ok = function () {
        return t.machine.name ? t.machine.companyId ? (e.promise = a.update(t.machine), void e.promise.then(function (e) {
            toastr.success(o.instant("operation-success")), n.close()
        })) : void toastr.error(o.instant("company-tip")) : void toastr.error(o.instant("machine-edit-dialog-name-tip"))
    }, this.cancel = function () {
        n.dismiss("cancel")
    }
}])

--------------------------------------------------------------
this modal need to open over already opened modal ----

    <div class="modal-header" >
        <h4 class="modal-title">{{'company-select' | translate}}</h4>
    </div>
    <div class="modal-body">
        <div class="dialog_container clearfix" style="height:400px; overflow-y:auto;">
			<div class="company-selector-tree" company-selector-tree></div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-warning" ng-click="ctrl.cancel()">{{'quit' | translate}}</button>
    </div>
-------------------------------------------------

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
