### ISSUE TITLE
Facing issue while importing JS file in Angular 1.x version with typescript support

### ISSUE THREAD

**Issue by sangeethapriyaM** [angular/angular.js#16886]
Hi Team,

Our requirement is to build angular 1.x with typescript support with bundle all files into one using webpack. And we are facing issues while importing the javascript files in TS file, but it is working when we use CDN files. Please find the sample below.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/button_sample-1693428658

Could you please check the above sample and do the needful.

Regards,
Sangeetha M

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
