### ISSUE TITLE
Authentication Header not working from Angular 1.1.x to1.5.x versions while working with postman

### ISSUE THREAD

**Issue by akinfo06** [angular/angular.js#16899]
My Web API 2.-0 code is -
OnValidateClientAuthentication = async context =>
{
.......string clientId;
........string clientSecret;
........if (context.TryGetBasicCredentials(out clientId, out clientSecret))
........{
..................if (clientId == "client1" && clientSecret == "secretKey1")
................{
....................context.Validated();
................}
...........}
}

I am using Bearer Authentication here.
Now I am calling this from angular-

tried two approaches -
approach 1. in module configure -

app.config(['$httpProvider', function ($httpProvider) {
.........$httpProvider.defaults.headers.common['Authorization'] = 'Basic ' + window.btoa("Client1:secretKey1");
}

approach 2.
app.service('memberService', function ($http) 
{

var headers = 
{ 

'Access-Control-Allow-Origin': true, 

'X-Requested-With': 'XMLHttpRequest', 

'Content-Type': 'application/x-www-form-urlencoded', 

'Authorization':'Basic ' + window.btoa("Client1:secretKey1") 

}

this.GetTocken = function (data) 
{

    var response = $http({

        method: "Post",

        url: window.g_baseUrl + "accesstoken",

        headers: headers

    });
    return response;
};
}

I tried with Angular 1.1.x, to 1.5.x with no luck.
Google is telling that HttpClient class is totally. dumb
after setting Authorization header, two keys : access-control-request-method & access-control-request-headers are increasing but no key with the name of 'Authorization'.
while sending request from postman its adding Authorization key in request header.
can someone help with angular sample code with version ...

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by akinfo06** [comment]
@gkalpak :  this is not a general support question. HttpClient class is full of bugs. all versions of anular I mention here that is not supporting array type header update. assign someone to fix this bug.

**Comment by gkalpak** [comment]
@akinfo06, you mentioned Angular 1.1.x to 1.5.x, but there is no `HttpClient` in Angular 1.x.
`HttpClient` is a service of Angular 2.x, so the right repo is https://github.com/angular/angular.
