### ISSUE TITLE
Angularjs md-select with html formated text input

### ISSUE THREAD

**Issue by true-doc** [angular/angular.js#16892]
I have a select box which I want its text to be edited into this specific format.
	<md-option ng-repeat="staff in staffs" 
			ng-value="employee_id">
		pix		**Staff Name**
		<i>Dept</i>					<i>employe_id</i>
	</md-option>
	
so the result would be 

		passpt		**Staff Name1**
		<i>Dept</i>					<i>employe_id</i>

		passpt		**Staff Name2**
		<i>Dept</i>					<i>employe_id</i>
		
		passpt		**Staff Name3**
		<i>Dept</i>					<i>employe_id</i>

What I have done so far is 
	
	<md-option ng-repeat="staff in staffs" 
			ng-value="employee_id">
		<h4>{{staff.name}}</h4>
	</md-option>
	
This is not working. I have been confused as to how to go about it.

I have looked at md-autocomplete but I do not want the search field. 
I want to be able to display all the items, autocomplete does show all the items

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
