### ISSUE TITLE
CSP issue caused by new Function('')

### ISSUE THREAD

**Issue by AymenMou** [angular/angular.js#16905]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [X] security issue
- [ ] issue caused by a new browser version
- [ ] other 

**Current behavior:**  I got csp-report: {"blocked-uri": "eval"} pointing on 2 lines of Code from angular.js

1.  function noUnsafeEval() {
    try {
      // eslint-disable-next-line no-new, no-new-func
      new Function('');
      return false;
    } catch (e) {
      return true;
    }
  }

2. // eslint-disable-next-line no-new-func
    var fn = (new Function('$filter',
        'getStringValue',
        'ifDefined',
        'plus',
        fnString))(
          this.$filter,
          getStringValue,
          ifDefined,
          plusFn);

**Expected / new behavior:** Not having "new Function('')" in the code and so not having csp-reports

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.7.8

**Browser: All 

**Anything else:**

**Comment by gkalpak** [comment]
See https://docs.angularjs.org/api/ng/directive/ngCsp.
