### ISSUE TITLE
Module parse failed for class controller

### ISSUE THREAD

**Issue by joseabraham99** [angular/angular.js#16903]
I was upgrading angularjs version form 1.4.x to 1.7.x and I have tried to use component way to represent the controllers. 

To make controller as component I have added selector, template, bindings and controller. for controller I have used below code and it throws error when  build.

`let legalComponent = {
  selector:'legal',
  template:'',
  bindings:{},
  controller: class legalController{
    public searchValue='';
    public isSearchValue = true;
    constructor(){}
  }
}`

It gives the error like below screenshot.
![image](https://user-images.githubusercontent.com/848620/65671891-b8e75d80-e065-11e9-83c6-c8865fd81db7.png)

Please help me to resolve this.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by joseabraham99** [comment]
It is happened due to webpack config file has loader and rules within module
