### ISSUE TITLE
Why is pushState disrupted when using ng-include?

### ISSUE THREAD

**Issue by shafiee-mj** [angular/angular.js#16907]
All information is in the link: [https://stackoverflow.com/questions/58297035/why-is-pushstate-disrupted-when-using-ng-include](https://stackoverflow.com/questions/58297035/why-is-pushstate-disrupted-when-using-ng-include)

**Comment by petebacondarwin** [comment]
I have added a comment to the StackOverflow question. I'll follow up there when I have clarification of the problem. Meanwhile closing this as it is a support request rather than an issue.

**Comment by shafiee-mj** [comment]
Thanks. I answered your question on StackOverflow.
