### ISSUE TITLE
1.7.9 release

### ISSUE THREAD

**Issue by jaydiablo** [angular/angular.js#16919]
It appears that the build on travis is failing (https://travis-ci.org/angular/angular.js), so the 1.7.9 security release that was cut 3 days ago (https://github.com/angular/angular.js/releases/tag/v1.7.9) hasn't been deployed, so isn't available on any CDNs yet.

The build failures seem to be a timeout issue (or lack of timeout I suppose):

>1) ngRoute promises should time out if the promise takes long enough
>[chrome 48 OS X 10.11 #01]   Message:
>[chrome 48 OS X 10.11 #01]     Failed: waitForAngular() should have timed out, but didn't
>[chrome 48 OS X 10.11 #01]   Stack:
>[chrome 48 OS X 10.11 #01]     Error: Failed: waitForAngular() should have timed out, but didn't

Do these jobs just need to be re-tried?

**Comment by petebacondarwin** [comment]
The primary release is on npm. The release is not gated on the Travis build. We need a Googler to push the release to the Google CDN.

**Comment by jaydiablo** [comment]
@petebacondarwin thanks for the reply, know how long that typically takes?

**Comment by petebacondarwin** [comment]
Can be up to a week depending upon the availability of an appropriate
Googler to run the scripts.

**Comment by gkalpak** [comment]
Of course, you can still get it from another CDN, e.g.:
- https://unpkg.com/browse/angular@1.7.9/
- https://www.jsdelivr.com/package/npm/angular

**Comment by gdsotirov** [comment]
The new version is already available from Google's CDN (see https://ajax.googleapis.com/ajax/libs/angularjs/1.7.9/angular.min.js).
