### ISSUE TITLE
How to make Youtube video with autoplay and with sound on page load? 

### ISSUE THREAD

**Issue by suryamraju** [angular/angular.js#16914]
Dear All,

Today i got one requirement from client that we have an Youtube video in our page with help of iFrame we are rendering. But i'm unable to autoplay when page loads with sound. 

Any one can help on this? 

i. Able to do auto play with out sound i.e. muted.
ii. Able to enable the sound icon but not auto play.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
