### ISSUE TITLE
two input fields but one ng model

### ISSUE THREAD

**Issue by vishwaspaikra007** [angular/angular.js#16928]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [x] other 

**Current behaviour: **
i have two input fields with the same input model. so when i type in the first input it also appears in the second input field but when i do the same with second input field it doesn't appear in the first input field and after when i try the same with first input field again it stops updating the value in second input field.

**Expected / new behaviour:**
what i want is that if i change value in the second input field than it should also appear in the first input field too

**Minimal reproduction of the problem with instructions:**
https://photos.app.goo.gl/dAYHNGZfYYGvJJWeA

**AngularJS version:** 1.7.x

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]

**Anything else:**

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
