### ISSUE TITLE
How to create File object in AngularJS ?

### ISSUE THREAD

**Issue by sjain1992** [angular/angular.js#16924]
In javascript it is very simple to create file object just like that :

var assetLocalPath="C:/Users/Pictures/flower..jpg";

var file = new File([""],assetLocalPath);

alert(file);

It will alert [object File]

Same as above I would like to create in AngularJS, but I am getting an error " TypeError: File constructor cannot be called in nwdisabled frame "

Please suggest some solution for **[AngularJS](https://www.sevenmentor.com/angularjs-training-in-pune.php)**.

**Comment by gkalpak** [comment]
This doesn't sound related to AngularJS. AngularJS does not not do anything that would prevent you from creating `File` objects. Based on the error message, it sounds related to [NW.js](https://nwjs.io/).

**Comment by luzpaz** [comment]
@gkalpak FYI, this is spam
