### ISSUE TITLE
angularjs 1.7.8 ng-model values are not updated when using select2 library 4.0.2 feature in templates

### ISSUE THREAD

**Issue by manjunathmofs** [angular/angular.js#16925]
angularjs 1.7.8 ng-model values are not updated when using select2 library 4.0.2 feature in templates

![select2](https://user-images.githubusercontent.com/20864819/70055853-647dd280-1600-11ea-9989-21c75966f196.PNG)

**Comment by gkalpak** [comment]
This issue lacks crucial info for us to identify the issue. It is most likely either an incompatibility of select2 with Angular 1.7.8 or an issue in the app. In any case, it is impossible to tell based on the provided info.

Furthermore, AngularJS is in LTS mode, which means we will only work a very specific types of bugs. See [here][1] for more details.

[1]: https://docs.angularjs.org/misc/version-support-status#long-term-support

**Comment by manjunathmofs** [comment]
I have attached my sample in plunker for your reference for any clarity

https://plnkr.co/edit/uQM1lOAUJRO8aLnNyxNN?p=preview

**Comment by gkalpak** [comment]
Oh, then it has nothing to do with 1.7.8. This hasn't been working since 1.6.0-rc.0, so it is probably caused by one of the breaking changes in that version. If you want to investigate this further, take a look at the "Breaking changes" section for the [1.6.0-rc.0 version][1].

[1]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rc0-bracing-vortex-2016-10-26

**Comment by manjunathmofs** [comment]
@gkalpak  I was able to set model value based on directive model invoke. do we need to handle select model update when any change in option is added to the select element. I hope there no change detection happening when select option is dynamically added to the select element. Is there any break up changes done for model update change detection after angularjs 1.5x release version. due to this we have impact in our project migration to latest version based on angularjs upgradation.
