### ISSUE TITLE
Feature: Set URL base on $httpProvider

### ISSUE THREAD

**Issue by alexalannunes** [angular/angular.js#16923]
On `axios` has an option that allow set `baseUrl`

```javascript
const instance = axios.create({
  baseURL: 'https://some-domain.com/api'
});

// use

axios.get('/me/info');
```
I'd like to know if angularjs have this option.

I tried to put it on `Interceptior` but the url affected my `tamplates`

```javascript
...

config.url = '/api/v1/public/' + config.url;
return config;

...
```

**Comment by petebacondarwin** [comment]
I'm afraid that this is not an option on `$httpProvider` and since we are in LTS mode now, it will not be implemented. You could consider implementing a wrapper service in your own project that prepends this base url to urls that are passed to it before delegating to `$http`.
