### ISSUE TITLE
AngularJs version Deprecation

### ISSUE THREAD

**Issue by drashti-b-patel** [angular/angular.js#16939]
Hi,

I have some queries related to your future plan to give support for the different versions.

We have been working in one of the client's projects having Angular JS version 1.5 for the last 2.5+ years and still that project is under development. That project is live but the client is working to promote the application so more users will come now onwards. This application will be continuing more than 3-4 years or more.

Do you guys have any future plans to deprecate the Angular Js completely or deprecation of existing functionalities? If you have any such plan then please inform us so that we can start to migrate the existing Angular Js functionalities.

Thanks.

**Comment by gkalpak** [comment]
@drashti-b-patel, have you seen [this][1]? It should answer your questions.

[1]: https://docs.angularjs.org/misc/version-support-status

**Comment by drashti-b-patel** [comment]
Thanks for the reply. What will happen after support will be finished for the 1.7 version?

**Comment by gkalpak** [comment]
I guess all development on the AngularJS project will cease. You will still be able to use existing versions, of course.
