### ISSUE TITLE
`angular-translate` (where `$translateProvider` comes from) is not an official package.

### ISSUE THREAD

**Issue by Raghuveer-wu** [angular/angular.js#16936]
`angular-translate` (where `$translateProvider` comes from) is not an official package.
The `angular-translate` repository is [here][1].

[1]: https://github.com/angular-translate/angular-translate

_Originally posted by @gkalpak in https://github.com/angular/angular.js/issues/16933#issuecomment-571671895_

**Comment by gkalpak** [comment]
Still wrong repo 😕
