### ISSUE TITLE
AngularJS1.6.2 - IE9 compatibility slow rendering for Translate Provider Static File Loader

### ISSUE THREAD

**Issue by Raghuveer-wu** [angular/angular.js#16933]
Below code is causing issue in IE9 compatibility mode with IE11 browser . Its taking around 2mins to render in IE9 compatibility mode (with IE11), also getting message about long running query.

In IE11 this code is taking around 40 seconds.  

$translateProvider.useStaticFilesLoader({
    prefix: `${root}langs/locale-`,
    suffix: '.json',
})

**Comment by gkalpak** [comment]
`angular-translate` (where `$translateProvider` comes from) is not an official package.
The `angular-translate` repository is [here][1].

[1]: https://github.com/angular-translate/angular-translate
