### ISSUE TITLE
`angular-translate` (where `$translateProvider` comes from) is not an official package.

### ISSUE THREAD

**Issue by Raghuveer-wu** [angular/angular.js#16937]
`angular-translate` (where `$translateProvider` comes from) is not an official package.
The `angular-translate` repository is [here][1].

[1]: https://github.com/angular-translate/angular-translate

_Originally posted by @gkalpak in https://github.com/angular/angular.js/issues/16933#issuecomment-571671895_

@gkalpak , we are using package.json like below

  "dependencies": {
    "@uirouter/angularjs": "^1.0.8",
    "angular": "^1.6.2",
    "angular-cookies": "^1.6.2",
    "angular-moment-picker": "^0.10.2",
    "angular-toastr": "^2.1.1",
    "angular-translate": "^2.15.1",
    "angular-translate-loader-static

in app.module.js like below

import angularTranslate from 'angular-translate';
import angularTranslateLoaderStaticFiles from 'angular-translate-loader-static-files';
import angularTranslateLocalStorage from 'angular-translate-storage-local';

in translation we using like this
const root = DEVELOPMENT ? '/' : '';

export default ($translateProvider) => {
    $translateProvider.useStaticFilesLoader({
        prefix: `${root}langs/locale-`,
        suffix: '.json',
    })
        .useSanitizeValueStrategy('escape')
        .preferredLanguage('en')
        .fallbackLanguage('en')
        .useLocalStorage();
};

do you see any issue here? the translateProvider is coming from ahgular node modules only.

**Comment by gkalpak** [comment]
What I meant in https://github.com/angular/angular.js/issues/16933#issuecomment-571671895 is that `angular-translate` is a third-party library (not developed/maintained by the AngularJS team) and thus we cannot offer help/support regarding its usage.

This repository (https://github.com/angular/angular.js) is for the official packages only (those published by the AngularJS team). For third-party packages, you need to contact the package author. In case of `angular-translate`, you can try opening an issue on the project's issue tracker: https://github.com/angular-translate/angular-translate
