### ISSUE TITLE
[Non Critical] - Animations no longer working after Chrome update.

### ISSUE THREAD

**Issue by jfreynik** [angular/angular.js#16946]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [x] issue caused by a new browser version
- [ ] other 

**Current behavior:**

We have a progressive web app that uses AngularJS and Animate.css to render transitions between views - these animations are still rendering properly in FireFox however they do not render in the latest update to Google Chrome. They simply flash into view or disappear instead of fading out or in. Everything was working properly until this latest update. 

**Expected / new behavior:**

The view should should be animated when changing.

**Minimal reproduction of the problem with instructions:**

You can see an "in progress" version of the app running here https://catering.gerritys.com/client/app.html - all links and buttons are simply causing the view to "jump" to the next view instead of showing an animation. The same link in firefox looks to work properly.

**AngularJS version:** 1.7.x

1.7.8

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]

Chrome - Version 80.0.3987.87 (Official Build) (64-bit)

**Anything else:**

I realize this is not a security issue - but would greatly like to better understand why the animations have broken in the newest update to chrome and am not sure where to start looking.

**Comment by gkalpak** [comment]
It seems to work for me on Chrome 80.0.3987.87 (64-bit, Windows 10) 😕
Hard to tell what might be wring without being able to reproduce the issue.

If it only fails on Chrome v80 for you, it might be a bug in that version (e.g. there is a [bug affecting `Array#reduce()`][1] in Chrome 80 - although this is not used in AngularJS animations afaict, it could be something similar).

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=1049982

**Comment by jfreynik** [comment]
Thank you so much for the response and taking the time - I'm going to close this because you're right - after closing my browser (and clearing my history / cache) - it's working again. It probably had to do with something else.
