### ISSUE TITLE
support sameSite cookie "None"

### ISSUE THREAD

**Issue by crhistianramirez** [angular/angular.js#16941]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [x] issue caused by a new browser version
- [ ] other 

**Current behavior:**
Cookies can be set with two [samesite options](https://docs.angularjs.org/api/ngCookies/provider/$cookiesProvider#defaults):
- `strict` -  never load cookies on cross origin requests
- `lax` -  allow few exceptions to load cookies on cross origin requests (such as top-level links)

Currently if neither value is set, the value is implicitly "None". Which means, load cookies on cross-origin requests. This is needed in certain scenarios (for example loading an angularjs app in an iframe). 

In May 2019 Chrome announced a secure-by-default model for cookies, and plans to implement it in February 2020. This means that going forward if no value is set, the value is implicitly "Lax" which means it will break angularjs apps that expect to be able to load cookies while in an iframe. 

Read [here](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) for more info on the changes.

**Expected / new behavior:**

Introduce new samesite cookie option: `none`

This option will give angularjs developers an escape hatch to revert to current defaults that allow reading cookies from an app loaded in an iframe.

**Minimal reproduction of the problem with instructions:**
Steps to reproduce:
1. Create a website that loads an angularjs app in an iframe. The app loaded in an iframe sets cookies with default options set
2. (On Chrome) Navigate to chrome://flags/ and enable `SameSite by default cookies` and `Cookies without SameSite must be secure` to emulate the behavior that will be effective in February
3. Note that cookies in angularjs are broken

**AngularJS version:** 1.7.x

**Browser:** [Chrome XX | Firefox XX | Edge XX | IE XX ]

**Anything else:**

N/A

**Comment by crhistianramirez** [comment]
It actually turns out that while the docs state the samesite cookie option accepts "lax" and "strict" it actually accepts a string so you can just pass in "none". 

I was going to make a pull request to update the documentation but doesn't look like that would get merged in based on the new LTS rules for code changes.

Closing as this has an easy workaround

**Comment by gkalpak** [comment]
FWIW, we do accept simple docs-only fixes. They don't require another release to be deployed to the docs website.
