### ISSUE TITLE
Dynamically load factory

### ISSUE THREAD

**Issue by drashti-b-patel** [angular/angular.js#16940]
Hi,

I have created one factory service for the common functions. I am using that factory in multiple controller using 

app.controller('manageDashboardController', function ($scope, $rootScope, $http,[Factory]

But I want to load factory conditionally instead of load it every time only loaded or include when needed. Is there any other option for this?

Thanks.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
