### ISSUE TITLE
Polynomial Interactive graph - Angular 7 with option for editing co ordinates

### ISSUE THREAD

**Issue by karthikvaidhya** [angular/angular.js#16944]
Hi Team ,

Please answer the below query.

I have to develop the Polynomial graph as attached based on the dynamic datasets in angular 7.

Another thing this polynomial graph should be very interactive such as plotted co ordinates point should be shown where we can modify and update, the graph should be refreshed. 

Kindly advise which polynomial graph having this options and need less efforts to implement in angular 7. Even if is paid , no issues.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
