### ISSUE TITLE
Security issue: $interpolate / $parse allows access to constructor

### ISSUE THREAD

**Issue by maxbilbow** [angular/angular.js#16983]
https://github.com/angular/angular.js/blob/ff963de73ab8913bce27a1e75ac01f53e8ece1d9/src/ng/parse.js#L1792

```javascript
// Translation key containing malicious code
scope.translationKey = "{{constructor.constructor('alert(document.cookie)')()}}"
```

```html
{{ translationKey | translate }}
```

The best workaround I have found so far is `$parseProvider.addLiteral("constructor", null)` but this doesn't feel right to me.

**Comment by gkalpak** [comment]
It is the developer's responsibility to ensure that the content that ends up in Angular expressions (and thus parsed by the `$parse` service) is sanitized. There used to be an "expression sandbox" trying to prevent accidental access to arbitrary JavaScript code and to discourage business logic from appearing in templates, but it was never supposed (nor able) to be a full-proof security mechanism.

The Angular expression sandbox has been removed in v1.6; you can read more about it [in this blog post][1] and the [security guide][2].

[1]: http://blog.angularjs.org/2016/09/angular-16-expression-sandbox-removal.html
[2]: https://docs.angularjs.org/guide/security#angularjs-templates-and-expressions
