### ISSUE TITLE
$uibmodal.open partially opening on internet explorer angularjs v1.6.9

### ISSUE THREAD

**Issue by chinmoydutta** [angular/angular.js#17011]
On IE 11, The modal sometime does not open fully and shows like faded pane. 
![Faded Pane](https://user-images.githubusercontent.com/14882104/78591566-9e125480-7811-11ea-8cfa-d3f3e92dd002.jpg)
This happens 1 in 3 times. 

We are calling below method to open and close the modal

For open:

$scope.Submit = function (row){
        var uibModalInstance = $uibModal.open({
            templateUrl: '/SiteAssets/ERAssets/EditMasterData.html',
            controller: 'editController',
            windowClass: 'app-modal-window',
            backdrop: 'static',
            resolve: {
                details: function () {
                    return row;
                }
            }
        });
        }

For closing

 $scope.close = function () {
    
        $uibModalInstance.close();
        $uibModalInstance.destroy();
          $scope.$emit('UpdateERMasterPlan');
    }

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ ] other 

**Current behavior:**

**Expected / new behavior:**

**Minimal reproduction of the problem with instructions:**

**AngularJS version:** 1.6.9

**Browser:** [IE 11  ]

**Anything else:**

**Comment by gkalpak** [comment]
`$uibModal` is part of [angular-ui/bootstrap][1], which is a 3rd-party package (i.e. not maintained by the AngularJS team). You could try asking on their issue tracker.

[1]: https://angular-ui.github.io/bootstrap/
