### ISSUE TITLE
Cross-site scripting vulnerability in code.angularjs.org-firebase

### ISSUE THREAD

**Issue by imanoracle** [angular/angular.js#17010]
Hello,

It seems there is an XSS bug in file `/scripts/code.angularjs.org-firebase/functions/index.js`, line number 158 (`.send(directoryListing)`).
Step 1:  `/scripts/code.angularjs.org-firebase/functions/index.js (line number 136)`
Step 2: `/scripts/code.angularjs.org-firebase/functions/index.js  (line number 144)`
Step 3: `/scripts/code.angularjs.org-firebase/functions/index.js (line number 138)`
Step 4: `/scripts/code.angularjs.org-firebase/functions/index.js (line number 158)`

**Comment by gkalpak** [comment]
Can you give more details? How is this an XSS attack?

**Comment by imanoracle** [comment]
I guess the user has control over `request.originalUrl`, so the user can inject script in `<base href="${base}">` and then the code could be injected into `.send(directoryListing);`.

**Comment by gkalpak** [comment]
I still don't follow. How could that lead to an XSS, since `request.originalUrl` should be a valid directory URL (otherwise it will not yield any files and a 404 will be returned instead of the listing).

**Comment by imanoracle** [comment]
Thanks, it seems that it's false positive.
