### ISSUE TITLE
Update jQuery to v3.5.0

### ISSUE THREAD

**Issue by aryehb** [angular/angular.js#17020]
**I'm submitting a ...**

- [ ] regression from 1.7.0
- [x] security issue
- [ ] issue caused by a new browser version
- [ ] other 

[jQuery v3.5.0](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) has been released to patch a possible XSS vulnerability.

Will AngularJS receive an update to use this new version of jQuery?

**Comment by gkalpak** [comment]
FYI: https://github.com/angular/angular.js/pull/17021#issuecomment-621760853

**Comment by mgol** [comment]
Closing per the discussion in #17021. We'll update to 3.5.1 but to make sure AngularJS works with it, not due to security issues.
