### ISSUE TITLE
My sessionContoller.jr made some #404 output for me

### ISSUE THREAD

**Issue by LorddXknowsy** [angular/angular.js#17037]
Hello, my sessionController.js gave my debug console code 404,
Anyone any idea?

angular.module('app').controller('sessionController', [ 'sessionService',
function sessionController(sessionService) {
    var vm = this;
    vm.getServiceSession = function () {    
        vm.model = {
            name: sessionService.get('name'),
            nickname: sessionService.get('nickname'),
            status: 'Retrieved by service on ' + new Date()
    };
    }
    vm.setServiceSession = function() { 
        sessionService.save('name', vm.model.name);
        sessionService.save('nickname', vm.model.nickname);
        vm.getServiceSession();
    } 
    vm.clearServiceSession = function() {
            sessionService.clear();
    vm.getServiceSession();

     }

}

]);

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
