### ISSUE TITLE
Documentation website error...

### ISSUE THREAD

**Issue by marcoslaredo** [angular/angular.js#17032]
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [x] other 

**Current behavior:**
Can't access any documentation at the website...

**Expected / new behavior:**
Can read all the documentations APIs...

**Minimal reproduction of the problem with instructions:**
1 - write at the browser URL: https://docs.angularjs.org/api/
2 - open the inspector (DevTools) and check the errors.

**AngularJS version:** 1.7.x
not relevant

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView | Opera XX ]
ALL

**Anything else:**
![image](https://user-images.githubusercontent.com/32306920/82759365-b3f5cc00-9df5-11ea-8393-99b8c90a3a37.png)

**Comment by gkalpak** [comment]
Duplicate of #17031. But I think the problem had been solved already (see https://github.com/angular/angular.js/issues/17031#issuecomment-633264425).

@marcoslaredo, can you let us know whether you are still seeing the issue on (by commenting on #17031)?

**Comment by marcoslaredo** [comment]
> Duplicate of #17031. But I think the problem had been solved already (see [#17031 (comment)](https://github.com/angular/angular.js/issues/17031#issuecomment-633264425)).
> 
> @marcoslaredo, can you let us know whether you are still seeing the issue on (by commenting on #17031)?

You are right. The issue was solved. Thank you....
