### ISSUE TITLE
Missing version 1.8.0 on CDNJS

### ISSUE THREAD

**Issue by lscorcia** [angular/angular.js#17049]
Hi, just wanted to mention that the distribution at CDNJS ( https://cdnjs.com/libraries/angular.js/ ) is still at version 1.7.9. In case these publishings are not by your team and are therefore to be considered as unofficial please let me know!

**Comment by gkalpak** [comment]
Indeed, our team does not manage the releases on CDNJS. You can open an issue on [their repo][1].

[1]: https://github.com/cdnjs/cdnjs
