### ISSUE TITLE
How to build or generate dist folder in Angular 1.5 project?

### ISSUE THREAD

**Issue by AmruthaSushanth** [angular/angular.js#17052]
# AngularJS  build command
What is the command for build or generate dist folder in Angular JS (version 1.5 ) project?
In this project I can see a Gruntfile also.. i don't know how to build this project.. I run this project with http-server.. Anyone please help me t build this project.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
