### ISSUE TITLE
callback url with HTTP Post not working using ui.router

### ISSUE THREAD

**Issue by santoshpatro** [angular/angular.js#17085]
Hi Team,

Need help on how to handle the scenario mentioned with all details at https://stackoverflow.com/questions/64050474/callback-url-with-http-post-not-working-using-ui-router

Any help on this is much appreciated.

Thanks,
Santosh

**Comment by gkalpak** [comment]
This sounds like a general support question. Github issues are not appropriate for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Besides, `ui-router` is not maintained by the AngularJS team. It is a 3rd-party package. Maybe try asking on their repo/support channels.

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
