### ISSUE TITLE
version 1.8.1 mutually-supporting (2020-09-30) - Deprecation Notices are not correct!

### ISSUE THREAD

**Issue by korengal** [angular/angular.js#17088]
**I'm submitting a ...**

- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [ X] other 

**In the new release docs:**
Deprecated _aHrefSanitizationWhitelist_. It is now aHrefSanitizationTrustedUri

When I try changing **aHrefSanitizationWhitelist** to **aHrefSanitizationTrustedUri**  it I'm getting "TypeError: $compileProvider.aHrefSanitizationTrustedUri is not a function".

For now, aHrefSanitizationWhitelist still works fine.

![444444444444444444444444444](https://user-images.githubusercontent.com/5110512/95678201-d7b68480-0bd3-11eb-8828-84df02b8d2c5.png)

**AngularJS version:** 1.8.1

Thanks.

**Comment by mgol** [comment]
Yeah, the changelog is incorrect. It should say `aHrefSanitizationTrustedUrlList` & `imgSrcSanitizationTrustedUrlList`.

Fortunately, at least the docs are correct:
* https://docs.angularjs.org/api/ng/provider/$compileProvider#aHrefSanitizationTrustedUrlList
* https://docs.angularjs.org/api/ng/provider/$compileProvider#imgSrcSanitizationTrustedUrlList
