### ISSUE TITLE
OKTA Session closing API is failing in angularjs

### ISSUE THREAD

**Issue by subdharan** [angular/angular.js#17096]
Hi Team,

I am using OKTA default APIs( /api/v1/users/${userId}/sessions) for closing session across all the devices. The functionality is working as expected but the status is showing the API call is failed.
And also when we validate through Postman the 204 response code is returning but in angularjs the API call is failing.

Below is the API reference page which I have used in my application
https://developer.okta.com/docs/reference/api/users/#user-sessions

Please find the attached screenshot for your reference
![session_API_Failed](https://user-images.githubusercontent.com/17308882/100606574-a6367b80-332f-11eb-8620-c95678da67bc.jpg)

Postman Response
![Postman_close_session_with_204_status](https://user-images.githubusercontent.com/17308882/100607191-94a1a380-3330-11eb-99be-f6c2d4c27889.png)

Thanks & Regards,
Subash.E

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
