### ISSUE TITLE
Release update of nuget package

### ISSUE THREAD

**Issue by Mek7** [angular/angular.js#17094]
**I'm submitting a ...**
- [ ] regression from 1.7.0
- [ ] security issue
- [ ] issue caused by a new browser version
- [x] other 

**Current behavior:**
Latest version on Nuget is too old - 1.7.8.1 - https://www.nuget.org/packages/angularjs

**Expected / new behavior:**
Latest version of angularjs is 1.8.2 - https://github.com/angular/angular.js/blob/master/CHANGELOG.md
Please release an update for the nuget package.

**Minimal reproduction of the problem with instructions:**
Create a new project in Visual Studio and install nuget package named "angularjs", observe that there is no later version than 1.7.8.1 available

**AngularJS version:** 1.8.x

**Browser:** [all]

**Anything else:**
no

**Comment by gkalpak** [comment]
Thx for opening an issue, @Mek7. However, the nuget package you mentioned in not owned/maintained by the AngularJS team.
[fitzchak][1] and [dlandau][2] and listed as owners on that page; maybe you could try to get in touch with them.

[1]: https://www.nuget.org/profiles/fitzchak
[2]: https://www.nuget.org/profiles/dlandau
