### ISSUE TITLE
(Some) documentation website is broken

### ISSUE THREAD

**Issue by heidemn-faro** [angular/angular.js#17111]
https://docs.angularjs.org/guide/directive

`Runtime nodejs6 is no longer available. Please redeploy your function to a newer version.`

EDIT: Okay sorry, this seems to be an outdated doc website URL.
New URL: https://code.angularjs.org/1.6.10/docs/guide/directive

However, your own company's search engine directed me there ;-) 
Maybe improve your SEO?

![image](https://user-images.githubusercontent.com/66078329/106999353-54263200-6786-11eb-928c-5d840d5488d9.png)

**Comment by rasmuslp** [comment]
To me, it looks like anything other than the front-page of https://angularjs.org is broken. Please fix. Docs shouldn't be hard to find on the official page.

**Comment by gkalpak** [comment]
Thx for reporting this @heidemn-faro et al.

https://docs.angularjs.org/guide/directive is actually the right URL (not an outdated one).

The issue should have been fixed now.
I am also working on PR to prevent the error in future deployments.
