### ISSUE TITLE
erro ao criar um projeto no angular

### ISSUE THREAD

**Issue by maisajessicalopes** [angular/angular.js#17131]
PS C:\Users\T-Gamer> ng new proj1                                                                              ng : O arquivo C:\Users\T-Gamer\AppData\Roaming\npm\ng.ps1 não pode ser carregado. O arquivo
C:\Users\T-Gamer\AppData\Roaming\npm\ng.ps1 não está assinado digitalmente. Não é possível executar este
script no sistema atual. Para obter mais informações sobre como executar scripts e definir a política de
execução, consulte about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.
No linha:1 caractere:1
+ ng new proj1
+ ~~
    + CategoryInfo          : ErrodeSegurança: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\T-Gamer> ng new proj1
ng : O arquivo C:\Users\T-Gamer\AppData\Roaming\npm\ng.ps1 não pode ser carregado. O arquivo
C:\Users\T-Gamer\AppData\Roaming\npm\ng.ps1 não está assinado digitalmente. Não é possível executar este
script no sistema atual. Para obter mais informações sobre como executar scripts e definir a política de
execução, consulte about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.
No linha:1 caractere:1
+ ng new proj1
+ ~~
    + CategoryInfo          : ErrodeSegurança: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by gkalpak** [comment]
This repository is for AngularJS (i.e. the old v1.x). The repository for Angular (v2+) is [angular/angular](https://github.com/angular/angular).

However, the issue you are reporting does not seem related to Angular itself, but rather your system configuration.
