### ISSUE TITLE
Não consigo instalar angular, o node já instalei

### ISSUE THREAD

**Issue by maisajessicalopes** [angular/angular.js#17130]
Segue o erro, a versão do node é: npm -v: 6.14.12

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code EEXIST
npm ERR! path C:\Users\T-Gamer\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm ERR! dest C:\Users\T-Gamer\AppData\Roaming\npm\ng
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\T-Gamer\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng' -> 'C:\Users\T-Gamer\AppData\Roaming\npm\ng'
npm ERR! File exists: C:\Users\T-Gamer\AppData\Roaming\npm\ng
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\T-Gamer\AppData\Roaming\npm-cache\_logs\2021-05-10T19_41_17_936Z-debug.log
PS C:\Windows\system32>

**Comment by gkalpak** [comment]
This repository is for AngularJS (i.e. the old v1.x). The repository for Angular (v2+) is [angular/angular](https://github.com/angular/angular).

However, the issue you are reporting does not seem related to Angular itself, but rather your system configuration.
