### ISSUE TITLE
Why not just include the gtag script in your header?

### ISSUE THREAD

**Issue by bruJMIR** [angular/angular.js#17159]
Why not just include the gtag script in your header?

_Originally posted by @AlexKopen in https://github.com/angular/universal-starter/issues/681#issuecomment-501396519_

I like what I did:

Before when getting error:
export default {
    props: [‘error’],
    data: () => ({
        drawer: false,
    }),

to this with no error:

<script>
export default ({
    props: ( { 'error': String('Sorry, this request could not be processed {$error.}.'),
        data: ({ 'drawer': String('true') } ({ Boolean: String('true') })) })
})
</script>

**Comment by mgol** [comment]
This repository contains AngularJS - i.e. 1.x - and not Angular - i.e. 2+ - code.

**Comment by bruJMIR** [comment]
whoops..i pasted the wrong chunk anyway...that was intermittnent:
```
export default ({
    props: ( { ‘error’: String(‘Sorry, this request could not be processed. Error Code:  {$error.statusCode}.’),
        data: ({ ‘drawer’: String(‘true’) } ({ Boolean: String(‘true’) })) })
})
```

**Comment by bruJMIR** [comment]
but I wont paste it then...my bad...lol
