### ISSUE TITLE
Transition Rejection :  while upgrading angularjs from 1.5 to 1.8 

### ISSUE THREAD

**Issue by ajaiswal595** [angular/angular.js#17167]
Transition Rejection($id: 0 type: 6, message: The transition errored, detail: TypeError: this.parent.parameters is not a function)

![image](https://user-images.githubusercontent.com/8745632/147666710-03d0b52b-2252-492b-b6c1-8fc85b469230.png)

here we are using 

 $stateProvider
            .state('mobile-login',
                {
                    url : "/mobile-login",
                    templateUrl : "assets/myorg/mobile/login/login.html",
                    controller:   "loginController",
                    authenticate: false
                })
            .state('mobile-main',
                {
                    url:          "/mobile-main",
                    templateUrl:  "assets/myorg/mobile/main/main.html",
                    controller:   "MainController",
                    authenticate: true
                })
            .state('login',
                {
                    url : "/login",
                    templateUrl : "assets/myorg/login/login.html",
                    controller:   "loginController",
                    authenticate: false
                })
                .
                .
                .
                
                
                
                Can someone help me, what could be the issue?

**Comment by gkalpak** [comment]
It seems you are using a 3rd-party library (most probably `ui-router`). Since this is a 3rd-party project (not maintained by the AngularJS team), there is not much we can help with. You could try asking on their issue tracker.
