### ISSUE TITLE
AngularJs 1.7.0 Upgrade Issue.

### ISSUE THREAD

**Issue by SankarMurali** [angular/angular.js#17184]
Hello,

I am new to AngularJS. I am doing AngularJs Upgrade from version 1.2.9 to 1.8.2,  while upgrading to 1.7.0 version getting below issue.

In profileController.js after **app.controllerProvider.register** code nothing happening (didn't get any error on console too).

Kindly help on this.

define(['app', 'App/Shared/Controllers/appRoleModalTemplateController', 'dataService'], function (app, dataService) {
    debugger;
    app.controllerProvider.register('profileController', function ($scope, $rootScope, $modal, $window, $document, $location, dataService, $timeout) {
        var participantId = app.context.getValue("CERT_ParticipantId");

**Comment by gkalpak** [comment]
This tracker is not suitable for support requests. Please see [here][1] for more details.
Additionally, this project is currently [End-Of-Life][2].

Finally, keep in mind that 1.2 to 1.8 is a big leap and there are many breaking changes in between. Make sure to check out the [migration guide][3] to find out what breaking changes there are in each version and how to cope with them.

[1]: https://github.com/angular/angular.js/blob/757d56ea9c3de6245df7e5cac025dbf7077082ff/CONTRIBUTING.md#question
[2]: https://blog.angular.io/discontinued-long-term-support-for-angularjs-cc066b82e65a
[3]: https://docs.angularjs.org/guide/migration
