### ISSUE TITLE
Don't clear initial content in ng-view until resolve is complete

### ISSUE THREAD

**Issue by ewinslow** [angular/angular.js#1769]
Right now I have something like:

``` html
<div ng-view>
  <div>PHP-rendered content for faster initial-load experience + SEO</div>
</div>
```

The experience when loading the page is to
1. See that initial content before the javascript runs.
2. Once the javascript runs, a blank section that possibly changes height if the initial content is long enough (this is quite jarring)
3. Then the Angular-rendered content once the resolve callbacks are complete.

I was expecting Angular to behave more like it does when transitioning between pages, where it waits until the next page is ready to load before it clears the current content.

See http://jsfiddle.net/7tnDN/ for an example of this behavior.

**Comment by Narretz** [comment]
I don't think proper support for server-side rendered html is coming to AngularJS, so this workaround must suffice
