### ISSUE TITLE
Cookie path not settable using $cookies service

### ISSUE THREAD

**Issue by kgj** [angular/angular.js#1786]
When using the $cookies service, there is no easy way to set the path of the cookie to match every path on the domain.

On line 3137 of angular.1.0.2.js the path of all cookies created is set as self.baseHref()
When trying to write the same cookie from different paths this results in additional cookies being created due to the different path.

With no facility implemented to pass in a path, the path needs to be hard coded in order to be changed.

**Comment by FraGoTe** [comment]
:+1:

**Comment by afc163** [comment]
:+1:

**Comment by jaoued** [comment]
:+1:

**Comment by simonykq** [comment]
+1

**Comment by priyanka-codaemon** [comment]
@ajspera thank u so much ... u save me .. <base href="/"> really works for me :)
