### ISSUE TITLE
Angular doesn't seem to work in Win8

### ISSUE THREAD

**Issue by jchannon** [angular/angular.js#1853]
In my attempt at evaluating JS frameworks, I copied the TODO MVC Angular demo and put it into a Win8 app but it throws an exception when the app starts up:

    JavaScript runtime error: Unable to add dynamic content. A script attempted to inject     
    dynamic content or elements previously modified dynamically that might be unsafe. For 
    example, using the innerHTML property to add script or malformed HTML will generate this 
    exception. Use the toStaticHTML method to filter dynamic content or explicitly create 
    elements and attributes with a method such as createElement.

It stops on `a.appendChild(c)`

I referenced jQuery 1.8.2 separately but same error and also the same error with https://github.com/appendto/jquery-win8

**Comment by dkarzon** [comment]
Have a look at winstore-compat.js its a library build by MSOpenTech which lets you use libraries such as this inside a Windows Store javascript app. It allows for safe usage of some DOM functions that are used by angular, ie. `innerHTML` and `outerHTML` etc.

Include that js file in your project and you will stop getting that error.

https://github.com/MsopenTech/winstore-jscompat

**Comment by petebacondarwin** [comment]
It seems like there is some movement from you guys in the Window community to push this forward. It would be great if you could come to a consensus of the best solution, whether it is a change to Angular (PR required) or a workaround using 3rd party code. Let's leave this issue open in the Backlog for a bit and see what you can come up with.

**Comment by petebacondarwin** [comment]
You might be interested to hear that we are close to merging a PR that allows you to specify the JQuery version you want to use: https://github.com/angular/angular.js/pull/10761

**Comment by gkalpak** [comment]
FWIW, this [article][1] also seems to indicate that [winstore-jscompat][2] does indeed enable Angular apps to run on Windows.

[1]: http://randolphburt.co.uk/2014/11/20/running-an-angularjs-app-in-the-windows-store/
[2]: https://github.com/MsopenTech/winstore-jscompat

**Comment by dkarzon** [comment]
I have an app in the Windows Store using Ionic with winstore-compat so I can confirm that they work well together. This file actually comes packaged in when you create a new cordova project with the Visual Studio tools so they are pushing it a bit.

**Comment by lgalfaso** [comment]
https://github.com/angular/angular.js/issues/1853#issuecomment-70720117 shows a solution to this issue. Closing

**Comment by dkarzon** [comment]
For those interested here is a link to the project: https://github.com/MSOpenTech/winstore-jscompat
