### ISSUE TITLE
Ability to react to progress events of $http XHR

### ISSUE THREAD

**Issue by ryankshaw** [angular/angular.js#1934]
I would like to be able to bind to the progress event of the xhr upload.

for example (in plain javascript):

var xhr = new XMLHttpRequest();
xhr.upload.addEventListener("progress", uploadProgress, false)

(so I can show a progress meter for uploaded files)

I want to be able to do the same thing by doing $http.post...

for this and any other case edge case where you need to interact with the raw XHR object itself it might be nice to provide something that lets you just get at the original xhr object.

**Comment by ajwhite** [comment]
It would be nice if we could just use the promise's progress callback

From [kriskowal/q](https://github.com/kriskowal/q/wiki/API-Reference#promisethenonfulfilled-onrejected-onprogress) docs

#### promise.then(onFulfilled, onRejected, onProgress)
The `then` method from the [Promises/A+ specification](http://promises-aplus.github.com/promises-spec/) with an additional progress handler.

I see no reason why we can't use `.then` here and expect `onProgress` to be reported to

```js
$http({
  method: 'POST',
  data: jsonData
}).then(function () {
  // on succes
}, function () {
  // on error
}, function () {
  // on progress
});
```

Or better yet, using [promise.progress](https://github.com/kriskowal/q/wiki/API-Reference#promiseprogressonprogress) 
```js
$http.post(url, data).success(function () {
  // success
}).error(function () {
  // error
}).progress(function () {
  // progress
});
```

**Comment by benjamingr** [comment]
@ajwhite I humbly disagree, it would be horrible to use the progress event, not only is it being removed from Kris Kowal's Q (check the v2 branch) and the Q authors are themselves against it - it will not be included in native promises (ever) and is a generally poor idea.

Please refer to the above discussion starting here:

https://github.com/angular/angular.js/issues/1934#issuecomment-41469790

**Comment by ajwhite** [comment]
@benjamine please refresh, I noticed the depreciation notice in the docs & redacted

**Comment by ajwhite** [comment]
@benjamine also caught up on your conversation. With the points being made towards the deprecation of all progress events (even in `.then(null, null, progress)`), it makes less sense to build support for it this way. With Bluebird & Q moving away from that support, a configuration property seems to make a bit more sense, and leave promises to their responsibility

**Comment by benjamingr** [comment]
Glad we agree promise progress events are not the way forward :)

**Comment by caitp** [comment]
the progress api from promises is certainly not the way to do this (we've known this for some time, for instance, it would kind of suck to have to always register a progress listener for XHR, and we'd still not know whether we're talking about XHRUpload or just XHR, it doesn't map well to this api at all!)

Sooooo, basically, we need some other way to do this that plays nice with the current promise-y way of doing things, and don't really have that yet. :(

**Comment by benjamingr** [comment]
@caitp  what's wrong with allowing optional callbacks to the options object of the $http call?

**Comment by arcanis** [comment]
About this :

```
should progress notification handlers automatically trigger $digest cycle (if they don't than the whole feature is a bit useless and if they do we need to be careful about not causing perf problems - maybe we should debounce those events and call handlers + $digest only every x ms?)
```

I think the debounce is a good solution. We don't need them to be called often, we just need them to be called enough to give some kind of feedback to the user. Even something like once per second would be enough, by adding some css transitions here and there.

**Comment by chrisirhc** [comment]
Since there are a number of progress events that can fire `loadstart`, `progress`, `load`, `timeout`, `abort`, `error`, … How about allowing the user to specify an object to attach the events (`eventName: eventListener`)?
For example the object could look like the following:
```js
var eventCallbacks = {
  loadstart: function onLoadStart() {},
  progress: function onDownloadProgress() {},
  upload: {
    progress: function onUploadProgress() {}
  }
};
```

Then the $httpBackend, would call `xhr.addEventListener(<eventName>, <function>);` with the callbacks. Callbacks defined under the `upload` attribute would be bound to the `xhr.upload`.

This also allows for users to bind to `readystatechange` if they need to react to `readyState == 3` loading events.

**Comment by chrisirhc** [comment]
Added a PR #11547 to illustrate what I meant above.

**Comment by benatkin** [comment]
[Here's a directive that has a clever but terrible hack to get around it.](https://github.com/danialfarid/ng-file-upload/blob/master/dist/ng-file-upload.js#L10)

**Comment by liukanghui** [comment]
Is there any consensus on how best to achieve this for the time being?

**Comment by ryanki1** [comment]
This topic is already 2 years old - have we already made a start on implementing it?

**Comment by Orthocenter** [comment]
+1

**Comment by nastakhov** [comment]
+1

**Comment by nicolas-alie** [comment]
+1

**Comment by weisk** [comment]
+1

**Comment by petebacondarwin** [comment]
Moved this to 1.5 - let's discuss the implementation at  #11547
