### ISSUE TITLE
Server side rendering discussion

### ISSUE THREAD

**Issue by ashtuchkin** [angular/angular.js#2104]
I would like to create a module that will make server-side rendering in node.js possible. I've done this before in my own project and wanted to discuss technical details.

So, the goals of the module:
- Make server return fully rendered html on first request, then move to client side rendering seamlessly.
- Support html5 routing defined through $routeProvider on the server.
- As little changes to client-only rendering as possible.

How do I want to do that:
1. Module will be a Connect/Express middleware that you can app.use().
2. Use [jsdom](https://github.com/tmpvar/jsdom) to create & work with DOM.
3. To enable client-side rendering, developer will need to provide all html code as templates and use only `<ng-include>` and `<ng-view>` in main html file.
4. On request, a new DOM is created and these `<ng-include>`-s are filled with rendered html. When ready (see below), the full DOM is serialized and sent to the browser (or crawler). In browser, the contents of `<ng-include>`-s are discarded and re-rendered, creating all services and controllers, binding all needed event handlers.
5. When rendering on server, $http requests are re-routed to use the same server.
6. If $routeProvider didn't match anything, the middleware will yield back to Express to serve later middleware or a 404 page.

Problems to solve:
1. jsdom will need to be extended with sufficient userAgent and location/history APIs.
2. The 'page ready' event is something to think about. I could use the $browser.notifyWhenNoOutstandingRequests() internal API, but maybe it could be better to introduce a $ready event on $rootScope.
3. I'll need a way to intercept angular bootstrapping to be able to catch this 'page ready' event. It is currently done in ngScenario, but I think it could be better (for example, it doesn't support asynchronous bootstrapping).
4. If we find a way to cleanly intercept angular bootstrapping on the page, we could have a single angular codebase residing in node process, serving all pages by just creating injectors. This should make page serving performance comparable to more traditional template-based servers.
5. $routeProvider will need to be extended to provide an event when no routes are matched. Currently it's an `otherwise` clause which usually redirects to base, but in server environment it's bad practice. Preferably even on the client side if a route is unknown, we should redirect the browser to new url, as the server can have something else there (statics, etc), or 404 page.
6. It would be nice to cache all $http requests that are done on the server, and package them together with html, so that first render in browser would not ask for the same information again.
7. I don't know how to test this whole endeavor. I can make e2e and unit tests to prove that jsdom is nice behaving browser, but I'm not sure what to do about ensuring that the browser will always get correct state when served with this method. 

So, what do you think? Is it viable? Did you plan to do something similar?

**Comment by jeffwhelpley** [comment]
So, the problem with running Angular 1.x apps on the server fundamentally is that you either need to use a headless browser or a framework built on top of a headless browser (i.e. like @apparentlymart's Angular Server project) which can be hard to make performant OR you can use something like the Jangular library I created (https://github.com/gethuman/jangular) which only supports a subset of Angular and you need to be really careful about how you implement it (but on the plus side it is extremely fast).

Fortunately, there is a much better solution that is in the works in Angular 2. I know that doesn't help with your Angular 1.x apps right now but if you are interested in learning more about what is coming, tune in to the livestream for our AngularU talk next week: https://angularu.com/ng/session/2015sf/angular-2-server-rendering

Btw, @kevinSuttle regarding the Google search crawler indexing HTML rendered on the client side, just realize that:

1. Google is getting better at it, but it is still not perfect. Server rendering is still a safer bet to guarantee what will actually get indexed.
2. Other search engines are not as good as Google at this. Also, you have other services like Facebook link preview that is purely server side only.
3. Indexing is different than ranking. Even if Google indexed your content perfect, that doesn't mean it will rank. And one of the biggest on-page factors for ranking is:
4. Initial page load performance. Even if you don't care about search ranking initial page load performance is really important for good UX, especially on low powered mobile devices.

**Comment by marcysutton** [comment]
Just wanted to add that Google has since deprecated their AJAX crawling scheme, making server-rendered apps even more important. https://googlewebmastercentral.blogspot.com/2015/10/deprecating-our-ajax-crawling-scheme.html

**Comment by gkalpak** [comment]
I'm all for having server-rendering capabilities, but how does deprecating Google's AJAX crawling scheme make this even more important ?

**Comment by marcysutton** [comment]
More important if you're currently only serving up a client-rendered app with no static HTML on the server. From that post: "Since the assumptions for our 2009 proposal are no longer valid, we recommend following the principles of progressive enhancement." How often do you see progressively enhanced Angular apps?

**Comment by jaydiablo** [comment]
In the same article though:

> Times have changed. Today, as long as you're not blocking Googlebot from crawling your JavaScript or CSS files, we are generally able to render and understand your web pages like modern browsers. 

Yes progressive enhancement is good, yes server rendering is good, but the removal of the AJAX crawling scheme from google bot shouldn't be the motivation.

**Comment by marcysutton** [comment]
It's not just for that purpose...it's also important for performance and for users that don't have the latest and greatest (hello progressive enhancement). But we could probably argue the motivations all day, so I'll leave it at that.

**Comment by a-lucas** [comment]
Hello guys, I would like to notify you about ng1-server : https://www.npmjs.com/package/ng1-server

This is my pet project, it uses a headless browser to pre-render any angular 1 web-app.

The main functionalities are : 

- An angular module that detects the IDLE status, augment the $cacheFactory and tigger preboot.
- An advanced caching system, that greatly boost headless rendering by caching every dependecies into redis
- The possibility to cache $http calls to
- Also once pre-rendered, it is possible to cache the pre-rendered page
- And for a last cache bonus, all $http calls on the server are injected into teh client and replayed instantly.
- All $logs are server side stored, and can be forwarded to Graylog 
- I am sure I forgot to mention some other interesting stuff.


I'd really appreciate if you guy have a look at it, and let me know what you think.

Cheers and great new 2017 year for Angular 1 & 2 !

**Comment by jeffwhelpley** [comment]
Very cool @a-lucas. I like that you have preboot integrated. I don't have a lot of experience with slimer.js, but the challenge with any angular 1.x SSR solution has always been that you either have to:

1. Emulate the browser on the server side (you are using slimer.js to do this which seems similar to phantom, but another option would be something like [Angular.js Server](https://github.com/saymedia/angularjs-server) which has built their own custom phantom-like shim.
2. Heavily restrict Angular 1.x template syntax and force custom APIs everywhere so you can properly abstract out client/server rendering (this is the approach I took with [Jangular](https://github.com/gethuman/jangular) and [Pancakes](https://github.com/gethuman/pancakes-angular))

Option number 2 is almost certainly going to scale and perform better, but I gave up trying to make it generalized so other people can use it. There is so much custom stuff in there that in retrospect I would have been better off not even attempting to open source it. So, definitely your path is superior as an OSS solution and it looks like you added a lot of great caching options. I also like that users can take an existing app and just add this on top.

**Comment by a-lucas** [comment]
Hi @jeffwhelpley , 

Thanks for the quick answer. I had a look at angular.js server you mentionned few month ago, and it seems lile they chose JSDOM to emulate a browser  environment. I went jsdom initially, but it came  as very unstable and has limited functionality. I haven't tested slimer performances yet, but it seems lile a better alternative than phantomjs. It uses the latest gecko engine which supports ES6 almost completly, and the same api as phantomjs. I though of going the electron way too, but I couldn't find a way to capture all http requests. 

Concerning scaling, I intentionally separated the 3 servers , making it easier to scale it in the future (if needed). A good scaling strategy would be imo to modify the bridge_pool so it can span slimer process on severall servers. 

As of preboot, I haven't tested it, I am not sure if document.body is the correct way of setting the Approot. I will get this tested soon.

**Comment by a-lucas** [comment]
@jeffwhelpley pancakes seems lile a very cool concept. I am an absolute fan of code generators.

**Comment by verishal** [comment]
I am using angular js and phantomjs driver to crawl google careers - https://example.com
I tried in the service_args = ['--ignore-ssl-errors=yes','--ignore-ssl-errors=true','--ssl-protocl=any']
Phantomjs version 2.1.1.
I tried in the service_args ,but is same ssl error. google crawl not accept the https://example.com/?_escaped_fragment_= request,In https but it still working in http.Like http://example.com/?_escaped_fragment_= .i don't understand why not take request https ?
please help me...

when i request the service_args:

    phantomjs --disk-cache=no  --ignore-ssl-errors=yes --ignore-ssl-errors=true --ssl-protocol=any /opt/bitnami/apache-tomcat/stt/ROOT/js/angular-seo.js 9090 https://example.com/

**Comment by verishal** [comment]
Issue has fixed. Problem was in  port and SSL. thanks
