### ISSUE TITLE
ngRepeat performance on removing item

### ISSUE THREAD

**Issue by offsky** [angular/angular.js#2107]
If you remove the last item in an ngRepeat, it is really fast. If you remove the first item in an ngRepeat it is really slow.  I believe that this can be optimized so that it is constant speed regardless of the position of the item being deleted.

From what I can tell, when you remove an item in an ngRepeat, Angular iterates over the items that come after it, and for each one it runs this line "cursor.after(last.element)" to move each DOM element up one position.  All these DOM removals and inserts are really not necessary if the order of the remaining items is the same. It should be possible to optimize this to do a single .remove() when items are removed by not reordered.

This optimization may also apply to adding items without reordering.

**Comment by neolace** [comment]
@CMCDragonkai, It all depends on where your opinion of the middle is and the amount of data your loading. 

Is this still an issue?

**Comment by Narretz** [comment]
If someone has a specific idea to speed this up, PRs are welcome.
