### ISSUE TITLE
Select ng-multiple not working with ng-options

### ISSUE THREAD

**Issue by Conorrr** [angular/angular.js#2113]
Multiple items cannot be selected from a multiple select menu when using ng-multiple and ng-options.I have tested with an object source and an array source, neither work.

It does appear to work if you use multiple (it acts quite differently though)

see http://jsfiddle.net/Spf22/8/

**Comment by gkalpak** [comment]
Support for `ngMultiple` (and dynamically changing `multiple` i general) has been removed since [v1.2.0-rc.1][1] (see d87fa00).

Closing...

[1]: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#120rc1-spooky-giraffe-2013-08-13
