### ISSUE TITLE
WP8 Cordova routing issue due to url formatted with x-wmapp0

### ISSUE THREAD

**Issue by corrydiehl** [angular/angular.js#2303]
Angular throws an error in the function "matchUrl(url, obj)" due to the URL being formatted as such: "x-wmapp0:www/index.html".

Apparently the URL scheme is specific to Cordova/WP. This happens when attempting to use routing.

**Comment by Narretz** [comment]
The correct way to handle this is to add `x-wmapp0` to the `$compileProvider.aHrefSanitizationWhitelist`
