### ISSUE TITLE
mozSystem parameter for window.XMLHttpRequest on FirefoxOS

### ISSUE THREAD

**Issue by colinfrei** [angular/angular.js#2318]
To be allowed to do Cross-Domain requests in FirefoxOS you need the permission, and window.XMLHttpRequest has to be passed a constructor parameter like this:

    new window.XMLHttpRequest({mozSystem: true}); 

See https://developer.mozilla.org/en-US/docs/DOM/XMLHttpRequest#XMLHttpRequest()

I currently patch Angular in the creatHttpBackend function to get this working, would be nice to not have to do that.

**Comment by frekele** [comment]
+1

**Comment by DaAwesomeP** [comment]
Yay!
