### ISSUE TITLE
ngMobile doesn't override ng-click with faster touch-based event when JQuery is loaded

### ISSUE THREAD

**Issue by elirov** [angular/angular.js#2548]
http://plnkr.co/edit/fnJCUMn2fMZy9cIunfFj

If we leave the jquery include commented out, the ng-click responds quickly on my ipad.
If we add the jquery include back in, then the click seems to revert back to the slow click behavior.

**Comment by chrisnicola** [comment]
This still doesn't appear to be fixed in 1.4. Due to conflicts with ngTouch and FastClick that have appeared (particularly with hover styles) I've simply removed ngTouch altogether and gone with Fastclick alone as the solution. This doesn't seem like it's going to get fixed.

**Comment by Narretz** [comment]
I have reason to assume that this was fixed by 06a9f0a95f0e72fa2e9879fe8a49e9bf69986a5f
