### ISSUE TITLE
Option not selected in select with data-ng-options, unless binding or $watch is added

### ISSUE THREAD

**Issue by provegard** [angular/angular.js#2828]
I have a SELECT element bound to a model and with options from the scope. See the following fiddle:

http://jsfiddle.net/provegard/Xetdr/6/

In Chrome and Firefox, when I select "Team 2" I get "Team 2". In IE9, I instead get "Team 1".

After having made the initial selection in IE9, I can select Team 2.

I have found two workarounds:
1. Bind to the model using {{}} in the HTML - not really feasible.
2. Watch the model using a $watch - my current choice.

**Comment by Narretz** [comment]
This works in >= 1.3.16 and >= 1.4.0
