### ISSUE TITLE
bug($location): incorrect URL parsing when (1) angular app lives under a subdirectory (2) HTML5 routing is off and (3) there's no trailing slash when accessing app root

### ISSUE THREAD

**Issue by chibicode** [angular/angular.js#2833]
Suppose you turned off HTML5 routing and your app lives at

~~~
http://localhost:5000/angular-app/
~~~

On version 1.1.5, if you navigate **instead** to a URL with no trailing slash, e.g.

~~~
http://localhost:5000/angular-app
~~~

then it redirects to:

~~~
http://localhost:5000/angular-app/#angular-app
~~~

I tracked down the problem - it's on this line:
https://github.com/angular/angular.js/blob/v1.1.5/src/ng/location.js#L158

* If there's trailing slash (i.e. `http://localhost:5000/angular-app/`), `beginsWith(appBase, url)` returns `/`. So `withoutBaseUrl` is set as `/`.
* However, if there's no trailing slash (i.e. `http://localhost:5000/angular-app`), `beginsWith(appBase, url)` returns an empty string, and it evaluates `beginsWith(appBaseNoFile, url)`, which returns `angular-app`.  So `withoutBaseUrl` is set as `angular-app`.

As a result, when HTML5 route is off, `this.$$parse` behaves differently for `http://localhost:5000/angular-app` (no trailing slash) and `http://localhost:5000/angular-app/` (trailing slash), even though they should return the same thing.

The change is introduced on this commit (cc @mhevery) https://github.com/angular/angular.js/commit/58ef32308f45141c8f7f7cc32a6156cd328ba692 

This is not a problem when (1) HTML5 routing is on (e.g. `$locationProvider.html5Mode(true).hashPrefix('!')`) and (2) `<base href="/angular-app/"` is added to `<head>`.

**Comment by Narretz** [comment]
Location has seen some major changes since 1.1.5, so this probably has been solved. If somebody encounter this problem again, please open a new issue.

**Comment by Varunprakas** [comment]
I am facing some issues when i enabled html5mode. It's working fine without nested urls but when i try to refresh a page url contains nested states. it's showing some error in the console. when i check in the console the file path is wrong. but in normal url i am not facing any issues. i am giving my code details below

1. app.js


```
$locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    }); 
```
	
```
	.state('/contactus', {
    url: '/contactus',
    template: '<ui-view></ui-view>',
     abstract: true,
    authenticate: true,}
	
	state('/contactus.contactuspage', {
    url: '/contactuspage',
    templateUrl: 'views/contactus-planning.html',
    controller: 'contactusCtrl'}

```
	
2. index.html

`<base href="/alp/member/">`

3. server 

```
  <Directory /var/alp/app/member>
    #for angular pretty URL
    RewriteEngine on
 
    # Don't rewrite files or directories
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
 
    # Rewrite everything else to index.html to allow html5 state links
    RewriteRule ^ /alp/member/index.html [L]
  </Directory>

```
