### ISSUE TITLE
No $location API for setting the location as a URL

### ISSUE THREAD

**Issue by hlship** [angular/angular.js#3074]
I'm working on a general directive to help with navigation away from a view that contains a dirty form. If the form is dirty, then a modal dialog is triggered before the navigation is allowed.

```
module.directive "dirtyNavProtection", (ConfirmMessageBox, $location) ->
  restrict: "A"
  require: "^form"
  priority: 100
  link: ($scope, element, attrs, formController) ->

    allowLocationChange = false

    $scope.$on "$locationChangeStart", (event, newUrl, oldUrl) ->
      # Did we just confirm the URL change?
      if allowLocationChange
        allowLocationChange = false
        return

      return if formController.$pristine

      # Prevent the location change from happening at this time.
      event.preventDefault()

      ConfirmMessageBox
        title: "Discard unsaved data?"
        message: attrs.dirtyNavProtection or "You have unsaved changes that will be lost."
        okLabel: "Discard"
        ok: ->
          allowLocationChange = true
          $location.url newUrl // <-- problem here
```

My issue is that `$locationChangeStart` event provides the new and old URL, as in, a complete URL.

However, $location.url(value) expects the value to really be just the path.  It prefixes the supplied path with the scheme, host, and port (e.g., "http://localhost:8080/").

I need a method that I can pass the full URL to. Currently, I'm looking at a couple of kludges, such as guessing what prefix I can strip with an RE, or calling the private method $$parse().

Issue #62 seemed to address this, but those changes seem long lost.  I'd like to see some sanctioned function (a writable absURL() perhaps) for this purpose.

**Comment by gkalpak** [comment]
I am not sure how things worked "back then", but now it is possible to use `$location.url()` for your purpose:

```coffeescript
    allowLocationChange = false

    $scope.$on "$locationChangeStart", (event) ->
      # Did we just confirm the URL change?
      if allowLocationChange
        allowLocationChange = false
        return

      return if formController.$pristine

      # Prevent the location change from happening at this time.
      event.preventDefault()

      newUrl = $location.url()
      ConfirmMessageBox
        title: "Discard unsaved data?"
        message: attrs.dirtyNavProtection or "You have unsaved changes that will be lost."
        okLabel: "Discard"
        ok: ->
          allowLocationChange = true
          $location.url newUrl // <-- no problem here```
```

[Demo][1]

[1]: https://codepen.io/ExpertSystem/pen/MJWENx?editors=1011
