### ISSUE TITLE
e2e test - click on href="javascript:void(0)" actually takes the browser to that URL

### ISSUE THREAD

**Issue by astoev** [angular/angular.js#3088]
JS urls should be evaluated instead and then to follow the link if any. Unable to test such URL. Fix need to be applied in angular-scenario.js, the method is named "chain.click" about line 25951.

**Comment by petebacondarwin** [comment]
The `ngScenario` module is deprecated and we are not accepting further code changes for it. Please look at using Protractor for your e2e testing.
