### ISSUE TITLE
completeRequest() and XHR.status conversion for x-wmapp0 protocol

### ISSUE THREAD

**Issue by dakr0** [angular/angular.js#3103]
The completeRequest() function works proper for 'file' protocol but it doesn't work for 'x-wmapp0'. The reason of this is that the completeRequest() converts XHR.status for 'file' protocol only but an application run on Windows Phone 8 from the local folder (using PhoneGap Cordova wrapper) uses 'x-wmapp0' protocol instead. Therefore, the additional condition is needed to proper operation, e.g.:

status = (protocol == 'file' || protocol == 'x-wmapp0') ? (response ? 200 : 404) : status;

**Comment by Narretz** [comment]
The line in completeRequest doesn't exist anymore, so it's possible that this has been resolved. Also possible that this was basically a variation of https://github.com/angular/angular.js/issues/2303
