### ISSUE TITLE
IE9 Backspace bug in compatibility mode

### ISSUE THREAD

**Issue by OliverBreuer** [angular/angular.js#3110]
The IE9 Backspace bug was fixed for the standards mode of the IE9 (see issue #879). Unfortunately the bug is not only present in the standards mode but also in compatibility mode.

Even worse IE8 normally doesn't have the input event. IE9 in IE8 mode however provides the input event.

The current workaround checks for the value of the msie variable. In case of the IE9 in IE8 mode msie is set to 8 and the workaround is not triggered.

Proposal: Since the real IE8 doesn't provide the input element, the check for msie==9 could be changed to msie<=9:

The line
        if (event == 'input' && msie == 9) return false;
could be changed to
        if (event == 'input' && msie <= 9) return false;

**Comment by Narretz** [comment]
Compatibility mode is not supported.
