### ISSUE TITLE
Unable to use <span> within directive transcluded content

### ISSUE THREAD

**Issue by bkuhl** [angular/angular.js#3111]
I created a fiddle and can't get it to run, but I thought it'd be helpful anyways: http://jsfiddle.net/Webnet/HkXNc/3/

I can't use span tags within the transcluded content.  If I do, it really messes with the scope.  With the fiddle example, should it run correctly, you'll end up seeing: 

```html
<button class="buttonL bGreen" ng-transclude="" color="green" ng-click="createWorkstation()" ng-class="{disabled: disableSave()}">
   <span class="ng-scope">{{disableSave() && "</span>
   <span class="ng-scope">Saving...</span>
   <span class="ng-scope">" || "Save"}}</span>
</button>
```

**Comment by Narretz** [comment]
As far as I can see, this is expected behavior. $compile wraps textNodes in span elements: https://github.com/angular/angular.js/blob/v1.5.0-rc.1/src/ng/compile.js#L1497
