### ISSUE TITLE
Browser Back on IE when running within an iFrame, reloads the page first

### ISSUE THREAD

**Issue by inuwan** [angular/angular.js#3119]
There is an issue with using the browser back button (deep linking) on IE when the app is running in an iFrame.  On IE 9 and IE 8, the proper view will be displayed when the back button is clicked but if first reloads the page (deleting any state stored in singletons).  On IE 11, it simply reloads the page and goes to the default route.

**Comment by Narretz** [comment]
This works in 1.2.27 and all higher versions.
