### ISSUE TITLE
Executing a route without a template

### ISSUE THREAD

**Issue by logicbomb** [angular/angular.js#3138]
This has been opened and closed a few times 
- https://github.com/angular/angular.js/pull/1901
- https://github.com/angular/angular.js/issues/1838

I may have found a use case where it's a valid to execute a route that doesn't have an associated template.  Imagine a page that launches various modal windows with the requirement to be able to deep-link directly to the page with a dialog open.  

The only difference between the modals are the title & text, so the `$rootScope` is responsible for setting up and launching a modal, and the controller simply provides route specific content.

A workaround is to set `{ controller: 'fooCtl', template: '&nbsp;' }`, but it'd be nice to leave the template property out altogether.

Here's a fiddle that shows the problem and workaround: http://jsfiddle.net/EGfAX/5/

**Comment by joseluisq** [comment]
For example when `templateUrl` is `false`:

```js
var app = angular.module('myApp.foo', ['ngRoute']);

app.config(['$routeProvider', function($routeProvider) {
  $routeProvider.when('/foo', {
    templateUrl: false,
    controller: 'fooCtrl'
  });
}]);
```

Angular loads all controllers again and then the console throws this:

![image](https://cloud.githubusercontent.com/assets/1700322/7540016/bbec1e38-f570-11e4-854e-ee34287eafc9.png)

Finally the browser tab is frozen.

**Comment by caitp** [comment]
well that's messed up and worth investigating, but setting `templateUrl` to false doesn't accomplish what you want, so why are you doing that?

**Comment by joseluisq** [comment]
Maybe, but sometimes I need angular route don't load by default an template. Because I can load manually my custom template and compile it on the fly.

**Comment by caitp** [comment]
Right, but you could just use `template: ""` to achieve that.

**Comment by caitp** [comment]
in particular, setting `templateUrl` to false will try to resolve the string "false" as a URL, which should be resolved relative to the current location of the frame (which is almost certainly not what you want)

**Comment by joseluisq** [comment]
Thanks, I will try this

**Comment by Narretz** [comment]
The problem with having an empty or false templateUrl is tracked here: https://github.com/angular/angular.js/issues/12176
Since you can do template: '', it's very easy to have a route "without" a template
