### ISSUE TITLE
Unexpected result when using select#options

### ISSUE THREAD

**Issue by tgkokk** [angular/angular.js#3154]
When you have this HTML:
```html
<select ng-model="select" multiple style="width:10%;">
	<option value="foo" selected>Foo</option>
	<option value="bar">Bar</option>
	<option value="baz">Baz</option>
</select>
<span id="select-length">{{select.length}}</span>
```
and this JavaScript test code:
```javascript
describe('E2E select bug', function () {
	beforeEach(function() {
		browser().navigateTo('/index.html');
	});

	it('should fail when using inner text and not value', function () {
		select('select').options('Foo', 'Bar');
		sleep(5);
		expect(element('#select-length').text()).toEqual('0');
	});

	it('should succeed when using value', function () {
		select('select').options('foo', 'bar');
		sleep(5);
		expect(element('#select-length').text()).toEqual('2');
	});
});
```
, both tests succeed. select#options probably changes the status of the options whose value is in the given arguments, so that's why ('Foo', 'Bar') doesn't work, while ('foo', 'bar') works. However, select#option works with both value and inner text.

If I'm not clear, feel free to ask me anything. Thanks!

**Comment by petebacondarwin** [comment]
The `ngScenario` module is deprecated and we are not accepting further code changes for it. Please look at using Protractor for your e2e testing.
