### ISSUE TITLE
Feature:  $debounce

### ISSUE THREAD

**Issue by dcherman** [angular/angular.js#3175]
It should function pretty much the same as http://lodash.com/docs#debounce, but it seems like it might be a common enough need that a function that uses $timeout should be provided.

Thoughts?

**Comment by lgalfaso** [comment]
#2129 landed, this can now be closed

**Comment by Narretz** [comment]
I guess this was more a request about a general debounce service, but that's probably not something we need.

**Comment by caitp** [comment]
instead of saying "that's probably not something we need", lets throw it on the mailing list and twitter and get users to decide if it's something we need or not

**Comment by Narretz** [comment]
I wrote "probably" based on the fact this is there hasn't been much demand for this feature in core. We have this thread and another one (with low participation): https://github.com/angular/angular.js/issues/9384. It's also pretty trivial to wrap an existing implementation with an $apply block, so "not core" seemed about right to me.
