### ISSUE TITLE
Export htmlParser in ngSanitize

### ISSUE THREAD

**Issue by natefaubion** [angular/angular.js#3346]
I have a need to do some custom html parsing in an app, and `htmlParser` in ngSanitize would work great but it's currently private. Can we export it as `$htmlParser` or is there a reason for keeping it private? I'd be happy to work up a PR.

**Comment by wesleycho** [comment]
Given how #3377 was closed, I think this is safe to close.

**Comment by lgalfaso** [comment]
Given that the html parser is no longer present, it is safe to close this.
