### ISSUE TITLE
Reverse use of "angular.mock.e2e.$httpBackendDecorator" in a module with "ngMockE2E" as a dependency

### ISSUE THREAD

**Issue by xiehan** [angular/angular.js#3385]
Hi:

I ran into a situation where I (as the front-end dev) was getting to the point where I couldn't make much more progress without a working back-end API. So, I implemented Vojta's suggestion to use ngMockE2E to make a fake backend:
https://groups.google.com/forum/#!topic/angular/grbwk-VehDE
http://jsfiddle.net/vojtajina/DQHdk/
I set this up in a separate "dev" module that depends on the main app module so that the backendless development mode could be kept separate from the regular app, and can be seamlessly removed once the real back-end API is ready.

I think I also referenced a couple of other blogs/posts on the same topic because one difference is that I specified 'ngMockE2E' as a dependency for my dev module. So essentially my code looked like:

```javascript

angular
  .module('AppDev', [
    'ngMockE2E',
    'App'
  ])

  .config(function($provide) {
    $provide.decorator('$httpBackend', angular.mock.e2e.$httpBackendDecorator);
  })

  .run(function ($httpBackend) {
    // templates
    $httpBackend.whenGET(/partials\/.*/).passThrough();

    $httpBackend.whenGET('http://localhost:8080/api/users/1').respond(200, { ... });
    ...
  })
;
```

However, when I was doing that, the call to `passThrough()` was failing. I eventually discovered that including the call to `.config(function($provide) { ... })` was causing the `$httpBackend` inside of `run()` to be initialized with the unit test version of `$httpBackend` (which doesn't have `passThrough()`) instead of the E2E version. Removing the whole `.config()` block, however, caused the code to run just fine.

I figured I'd mention it because 1) it seems counter-intuitive, and 2) someone else could be stuck on the same thing, so hopefully this will help them.

**Comment by Narretz** [comment]
Not sure if this was ever a rea issue. ngMockE2E provides the decorator itself.
