### ISSUE TITLE
Need API to officially perform full page reload to an arbitrary URL

### ISSUE THREAD

**Issue by dlmiles** [angular/angular.js#3386]
The documented way of doing this is to use raw HTML API:

`$window.location.ref = '<url_here>';`

However when you have $routeProvider.otherwise() setup, invoking this URL causes the new route to be instantiated, new view to be instantiated and new controllers to be instantiated.  That can cause unwanted hits on the target server concerning the setup of the $routeProvider.otherwise() route.

The closest thing I have toyed with is configuring:

```
$routeProvider.
    otherwise({redirectTo: function(params, currentPath, currentSearch) {
        console.log('otherwise redirectTo params=' + angular.toJson(params));
        // where is the desired target ?  is it inside this angularJS application ?
        // if not mess with the return value!
        if(magicCheck(params, currentPath, currentSearch))
            return undefined;   // inhibit route change ?
        return '/home';
    }});
```

But it would be much cleaner to just have official API for informing Angular JS not to instantiate a new route and view and controllers etc... when preforming a full page reload.

`$location.reload(url);   // taking 'string'`

This should perform clean up of current route and inhibit setup of new route, while then making the browser perform a full page reload of the new URL (there should be no restriction on the URL, external, same site outside this angular app, back into this angular app [although this does not make sense]).

My use case is that my login page is not inside angular and I intercept $http looking for HTTP/401 Unauthorized and other such Session Cookie Timeout detection to then perform a full page reload.

However it tries construct my $routeProvider.otherwise() view, which in turn uses $http, which in turn causes another unauthorized hit on the server.  Which in turn maybe intercepted to perform a full page reload (as Angular JS currently documents how to achieve this) to the external and outside of Angular JS login page.

**Comment by gkalpak** [comment]
Since `html5Mode` now requires a `baseHref`, this shouldn't be an issue anymore when navigating away from the app. I am going to close this now.

<sub>(Happy to reopen and invetigate in case I've missed something and this is still an issue. Just let me know :smiley:)</sub>

**Comment by dlmiles** [comment]
@mderazon Yes target="_self" works when you have markup.  But my request is about using an API driven full page reload, entirely code based solution.
@gkalpak So this should not be a problem now with the baseHref set, maybe I upgrade angular 1.x to latest and see.
