### ISSUE TITLE
$sanitize does not support non latin alphabet

### ISSUE THREAD

**Issue by istarkov** [angular/angular.js#3396]
Every time i use $sanitize service i manually change
NON_ALPHANUMERIC_REGEXP to this
NON_ALPHANUMERIC_REGEXP = /([^\#-~| |!|а-яА-Я])/g; (Cyrillic support)
this change prevents $sanitize from all Cyrillic letters conversion to &# format.
You need to add some configuration method for $sanitize or add Cyrillic support 
(see change above)

**Comment by guymahieu** [comment]
+1

**Comment by redgenie** [comment]
+1

**Comment by babakhanov1** [comment]
+1

**Comment by zigzag-way** [comment]
+1
Just a simple case: $sanitize('Привет') = "&#1055;&#1088;&#1080;&#1074;&#1077;&#1090;"

**Comment by mikolesnikov** [comment]
+1

**Comment by mmartinez4** [comment]
+1

**Comment by lgalfaso** [comment]
Angular 1.5 has a new sanitizer that should solve this issue. It should also be possible to use the 1.5 sanitizer with older versions of Angular. If someone can check that the new sanitizer does support this use case, then we can close this issue.

**Comment by katemihalikova** [comment]
Unfortunately no change in behaviour between 1.4 and 1.5.5, see [codepen](http://codepen.io/katemihalikova/pen/PNvwKp?editors=1010).

**Comment by lgalfaso** [comment]
@katemihalikova the output from `$sanitize` is meant to be used with `ngBindHtml` as the output is meant to be handled as html

**Comment by katemihalikova** [comment]
That makes this issue invalid as the problem of it is using it with `ng-bind` / `{{ }}`.

**Comment by lgalfaso** [comment]
The version of `$sanitize` that is present in 1.4 and older is not able to handle non latin characters. The version present in 1.5 and newer is a complete rewrite that is able to handle non-latin characters. Closing this issue.
