### ISSUE TITLE
make ng-switch-when more powerful

### ISSUE THREAD

**Issue by skivvies** [angular/angular.js#3410]
Programming languages with switch statements allow associating several cases with the same block, e.g.:
```javascript
switch (value) {
case 0:
  foo();
  break;
case 1: // fall through
case 2: // fall through
case 3:
  bar();
  break;
}
```

It would be useful if ng-switch-when similarly allowed matching on multiple values, e.g.
```html
<div ng-switch-on="value">
  <div ng-switch-when="foo">foo</div>
  <div ng-switch-when="/bar|baz/">bar or baz</div>
</div>
```

**Comment by jharaphula** [comment]
Its wise to use Switch Case in place of if then else if you have more the 5 to 6 Conditions. Nice to read this article. Well described about in-build Switch directives. To make your larningg easier here I am sharing one more link http://jharaphula.com/how-to-use-switch-case-in-angularjs. These are the pure examples.

**Comment by ChauskinRodion** [comment]
Hey there
Guys, does it works with numbers as well? On my experience it doesn't  😢 
[see plnkr](https://plnkr.co/edit/beacPuiLNNvcAhuST6QI?p=preview)

**Comment by Narretz** [comment]
Since attribute values are strings in HTML, all values that are in the ng-switch-when attribute are considered strings and matched with strict equality against the value of ng-switch. So, no numbers. :(
