### ISSUE TITLE
Multi-level array causing TypeError: Object #<Resource> has no method 'push'

### ISSUE THREAD

**Issue by blackgun** [angular/angular.js#3412]
If the server responded a 1 level array, everything is OK. But if the server responded a 2 level array, it is broken. I have set isArray:true.

    TypeError: Object #<Resource> has no method 'push'
        at V (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:10:185)
        at new Resource (http://code.angularjs.org/1.1.4/angular-resource.js:392:9)

This is the 2 level array I am using:

    [ [ { _id: 201, users: 0 },
        { _id: 202, users: 10 },
        { _id: 203, users: 7 },
        { _id: 204, users: 0 },
        { _id: 205, users: 0 },
        { _id: 206, users: 0 },
        { _id: 207, users: 0 },
        { _id: 208, users: 0 },
        { _id: 209, users: 0 },
        { _id: 210, users: 0 },
        { _id: 211, users: 0 },
        { _id: 212, users: 0 } ],
      [ { _id: 202, users: 0 },
        { _id: 203, users: 17 },
        { _id: 204, users: 0 },
        { _id: 205, users: 0 },
        { _id: 206, users: 0 },
        { _id: 207, users: 0 },
        { _id: 208, users: 0 },
        { _id: 209, users: 0 },
        { _id: 210, users: 0 },
        { _id: 211, users: 0 },
        { _id: 212, users: 0 } ],
      [ { _id: 203, users: 0 },
        { _id: 204, users: 0 },
        { _id: 205, users: 0 },
        { _id: 206, users: 0 },
        { _id: 207, users: 0 },
        { _id: 208, users: 0 },
        { _id: 209, users: 0 },
        { _id: 210, users: 0 },
        { _id: 211, users: 0 },
        { _id: 212, users: 0 } ] ]

**Comment by Narretz** [comment]
Looks like we never got back to this. Problem is probably not relevant anymore; closing.
