### ISSUE TITLE
BlanketJS support?

### ISSUE THREAD

**Issue by dbones** [angular/angular.js#3449]
Hi, 

I am working on a project which uses AngularJS and we are looking into how to get code coverage on our Jasmine tests.

We use Visual studio with a plug-in called Chutzpah, and we can get the tests to run locally in the IDE.

However when we run the code coverage ( Chutzpah uses BlanketJS ) it returns an error. "Instrumentation error, you cannot redefine the 'window' variable"

the issue has been raised with BlanketJS here: https://github.com/alex-seville/blanket/issues/311, which has been closed, as not a BlanketJS issue.

Bit of a long shot, is there any thing which the AngularJS team could do?

Regards
David

(apologies if this has been raised before, I could not find a existing ticket)

**Comment by lgalfaso** [comment]
With the information from https://github.com/angular/angular.js/pull/4498#issuecomment-27179643, this issue is no longer valid
