### ISSUE TITLE
Trailing slash - Shouldn't "/home/" and "/home" be equivalent for matching purposes?

### ISSUE THREAD

**Issue by danieljsinclair** [angular/angular.js#3451]
I seem to required double the rules for routeProvider whereas routes with or without trailing '/' ought to be equivalent. Eg;

        .when("/:controller/:action", {
            templateUrl: function ($routeParams) {
                console.log("$routeProvider::Controller/Action rule");
                var controller = '/' + ($routeParams.controller.length ? $routeParams.controller.toLowerCase() : 'home');
                var action = '/' + ($routeParams.action.length ? $routeParams.action.toLowerCase() : 'index');
                return '/ng/app/views/partials' + controller + action + '.htm';
            }
        })
        .when("/:controller", {
            templateUrl: function ($routeParams) {
                console.log("$routeProvider::Controller rule");
                var controller = '/' + ($routeParams.controller.length ? $routeParams.controller.toLowerCase() : 'home');
                return '/ng/app/views/partials' + controller + '/index.htm';
            }
        })

The second rule is almost identical, except that it matches "/home" whereas the first rule would only match "/home/"

**Comment by wesleycho** [comment]
Would this be a good thing to change in ngRoute at this point? It would be a breaking change, and one I think doesn't add much at this point for the impact a change would cause.

**Comment by gkalpak** [comment]
This [works already]. I only tried it on 1.5.7, but I am pretty sure it has been working for quite some time.

[1]: https://codepen.io/ExpertSystem/pen/RRKqXM?editors=0010
