### ISSUE TITLE
Checking userAgent is not enough to determine, whether createEvent is defined

### ISSUE THREAD

**Issue by apsk** [angular/angular.js#3486]
Here's the problematic place: [ngScenario/browserTrigger.js#L64](https://github.com/angular/angular.js/blob/master/src/ngScenario/browserTrigger.js#L64)
This goes wrong, when IE >= 9 is used in IE < 9 modes,
because createEvent is undefined, but userAgent is still > 8.
Maybe it's better to do something like
```javascript
if (msie < 9 || !document.createEvent) { ...
```
or even

```javascript
if (!document.createEvent) { ...
```
or to change setting of msie in such a way that it will reflect current browser mode, not just userAgent.

**Comment by Narretz** [comment]
We are using document.documentMode nowadays: a84480affb1d2714ebd4a03dd656a4bc516b8ceb
