### ISSUE TITLE
$httpBackend leaks memory in IE8 by not cleaning up event handler reference

### ISSUE THREAD

**Issue by derekschaab** [angular/angular.js#3504]
An application that makes many $http requests will experience memory leaks over time in IE8. Based on [this advice](http://milan.adamovsky.com/2012/02/javascript-memory-leaks-in-internet.html), I was able to prevent the leak by adding

```javascript
xhr.onreadystatechange = (typeof CollectGarbage === 'undefined' ? null : CollectGarbage);
```

to the end of the `if (xhr.readyState == 4)` block in the `onreadystatechange` event handler in httpBackend.js. Without this line, IE8 memory usage grows on each request without (apparent) limit. (A very simple test that makes approximately one $http request per second, when run overnight, increased IE8 memory usage to more than 1GB.)

IE9 does not appear to exhibit this issue. Not tested in IE10.

In Chrome, the above line assists the GC in cleaning up the event handler so that the event listener count stays low. Without it, when running the simple test described above, Chrome's dev tools timeline shows the event listener count as growing in stairstep fashion until a GC event cleans up the old handlers.

I apologize for not being able to provide a Fiddle or other example; firewall restrictions here are preventing me from doing so.

**Comment by Narretz** [comment]
Does look like this has been resolved.
