### ISSUE TITLE
What about offset() method in jqLite?

### ISSUE THREAD

**Issue by allaud** [angular/angular.js#3644]
One thing I need in built in jQuery is offset function with same result:

    angular.element(elem).offset() == {
      width: 100,
      height: 100,
      top: 23,
      left: 400
    }

Now we have to use our own service for calculating element offset, but it would be great to have it inside of Angular. Any thoughts?

**Comment by maxazan** [comment]
+1 
it will be very useful

**Comment by brunowego** [comment]
+1

**Comment by sreekumarp** [comment]
+1

**Comment by Yonn-Trimoreau** [comment]
+1

**Comment by mgol** [comment]
See https://github.com/angular/angular.js/pull/3799#issuecomment-212379662
