### ISSUE TITLE
Re-work $q a bit to better support decorators

### ISSUE THREAD

**Issue by dcherman** [angular/angular.js#3659]
Currently, $q uses the `defer()` function in several places rather than referencing something like `$q.defer()`

This causes problems when you try to decorate promises because internally, $q is not calling the `defer` method that's defined/overriden in a decorator.

http://jsfiddle.net/3V2Xn/

**Comment by lgalfaso** [comment]
With 1.3 `$q` uses prototypes for promises, so this is already possible
