### ISSUE TITLE
bindJQuery is called too early

### ISSUE THREAD

**Issue by 4vanger** [angular/angular.js#3716]
When jQuery is loaded after angular.js, JQLite methods like inheritedData is not added to jquery elements. Comment says that "try to bind to jquery now so that one can write angular.element().read() but we will rebind on bootstrap again." but actually it is never called again.
http://plnkr.co/edit/HWfGszpeM0rMgnXg36Gm

**Comment by petebacondarwin** [comment]
Perhaps we need to change the line in https://docs.angularjs.org/api/ng/function/angular.element which says:

> To use jQuery, simply load it before DOMContentLoaded event fired.

to something like:

> To use jQuery, simply ensure it is loaded before the angular.js file.
