### ISSUE TITLE
In Firefox when a model is changed, other elements are re-rendered

### ISSUE THREAD

**Issue by yeukhon** [angular/angular.js#3753]
Foxandxss on IRC helped me to verify this issue.
Try this on Firefox http://plnkr.co/edit/MziozEZq9KBhYsyuZas9?p=preview (I am using FF-23 stable, but other versions should have the same issue) 

If you let the ``<select>`` element open,  move your cursor to a lower item, wait a few seconds, you will see the highlight cursor moves back to the top as the number on the right changes.

In my application, I have a table and a ``<select>``. Each is bind to a model, but ``<select>`` is initialized once whereas the table gets updated every 3 seconds using ``$timeout`` (we poll). 

In Chrome (Google Chrome	27.0.1453.93 (Official Build 200836)) I don't see this problem.

**Comment by Narretz** [comment]
This is actually fixed since at least 1.2.28
