### ISSUE TITLE
$location.path() change fails in Android 2.3 (1.2.0rc1)

### ISSUE THREAD

**Issue by doup** [angular/angular.js#3814]
Route change ends in an $digest error in Angular 1.2rc1 + Android 2.3.6 default browser when changing the location. This is the message:

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [
    ["fn: $locationWatch; newVal: 9; oldVal: 8"],
    ["fn: $locationWatch; newVal: 10; oldVal: 9"],
    ["fn: $locationWatch; newVal: 11; oldVal: 10"],
    ["fn: $locationWatch; newVal: 12; oldVal: 11"],
    ["fn: $locationWatch; newVal: 13; oldVal: 12"]
]
    at http://code.angularjs.org/1.2.0rc1/angular.js:60:12
    at Object.$digest (http://code.angularjs.org/1.2.0rc1/angular.js:9860:19)
    at Object.$apply (http://code.angularjs.org/1.2.0rc1/angular.js:10039:24)
    at HTMLHtmlElement.<anonymous> (http://code.angularjs.org/1.2.0rc1/angular.js:7613:22)
    at http://code.angularjs.org/1.2.0rc1/angular.js:2246:10
    at Array.forEach (native)
    at forEach (http://code.angularjs.org/1.2.0rc1/angular.js:196:11)
    at HTMLHtmlElement.<anonymous> (http://code.angularjs.org/1.2.0rc1/angular.js:2245:19)
```

Plnkr with the bug:
http://plnkr.co/edit/Rx6SDx

I've tried, changing the route via `ng-click="$location.path('/b')"` and `ng-href="#/b"`. Both ways fail.

Might be related issues (now closed): https://github.com/angular/angular.js/issues/1417 https://github.com/angular/angular.js/issues/2815

This comment fixes the issue for me (but it does not work in a phonegap app): https://github.com/angular/angular.js/issues/1417#issuecomment-10716856

**Comment by gkalpak** [comment]
Closing as v1.2.x only receives critical security fixes and Android 2.3 is pretty old.
If the problem persists with newer versions of Angular, please open a new issue (specifying the exact versions of Angular/Android/Browser that are know to be affected).

Thx !
