### ISSUE TITLE
injecting $location into directive with ng-view messes it up

### ISSUE THREAD

**Issue by cybrcodr** [angular/angular.js#3818]
See http://plnkr.co/edit/SUgKElAOsFLLBYIOJ1Q6 for example.

Directive wraps ng-view in its template file.  Note that it works if directive uses template instead of templateUrl.  See comment in code.

Also, it also affects module.run function, i.e. if $location is injected, ng-view fails to display.

**Comment by Narretz** [comment]
This will work in the upcoming 1.6 release.
