### ISSUE TITLE
Please add an option for not re-rendering ng-view or ng-include

### ISSUE THREAD

**Issue by e-oz** [angular/angular.js#3825]
Please make it possible to disable views re-rendering on each change of ng-include src at least (if it's not possible for ng-view). Otherwise for tabs I have to put content of ALL views (huge views) in one page. Please, don't just close this issue, it's a very very important thing for me and (I think) for some other users.

**Comment by Narretz** [comment]
AngularJS ngRoute doesn't cache html or data. It's not as easy as keeping the ngView / ngInclude html around, you'd need to keep the scopes, the controllers etc. Aggressive caching can also impact performance, as this is kept in memory. I don't see a chance for this at this point - the best bet is to cache the view / include data when the route / scope changes, and restore it when it switches back.
