### ISSUE TITLE
Custom headers in HTTP response headers are not available in E2E scenario

### ISSUE THREAD

**Issue by duckmole** [angular/angular.js#3906]
In my E2E tests, the only HTTP response headers available are 
- content-type
- cache-control
I do not have access to my custom HTTP response headers.

I do not have any problem with the HTTP request headers.

My E2E configuration :
- angular 1.1.5
- Grunt-karma 0.7.0
- phantomjs 1.9.0
- karma-ng-scenario 0.1.0

**Comment by Narretz** [comment]
This is a very old issue without any further activity, so I'm gonna close it.
