### ISSUE TITLE
10 $digest() iterations reached using $locationWatch

### ISSUE THREAD

**Issue by fraywing** [angular/angular.js#3915]
Oh noes! Not this issue again!

I'm using the Zombie headless browser, Nodejs, Angular 1.2.0rc1 and i'm getting the same iteration loop error.

It seems as though this issue is related to https://github.com/angular/angular.js/issues/2815
as well as this thread: 
https://groups.google.com/forum/#!topic/angular/mRIo8LaTh4M

and the recent change for Boxee Box.  

My thought is that there has to be some sort of universal fix instead of making exceptions for each instance where this comes up? 

Anybody?

**Comment by wesleycho** [comment]
Sounds like this issue probably can be closed now.

**Comment by petebacondarwin** [comment]
Thanks
