### ISSUE TITLE
The view doesn't refresh correctly in IE when multiple input source link to same model

### ISSUE THREAD

**Issue by khtwo** [angular/angular.js#3926]
angular-1.2.0-rc.2

	<span data-ng-controller="Control1">
		<input id="a" data-ng-model="model1.input1">
		<input id="b" data-ng-model="model1.input1">
		The input is: <span id="c">{{model1.input1}}</span>
		The input is: <span id="d">{{model1.input1}}</span>
	</span>

The above code, when input in either of the `<input>`, both `<input>` are updated, but the views don't, untill double click the page, or highlight the `<input>` content. This happen in IE9, didn't test other version. Using `ng-bind` behaves the same.

**Comment by Narretz** [comment]
The fiddle works in Win7 / IE9
