### ISSUE TITLE
Get ngMock $httpBackend response to accept promises.

### ISSUE THREAD

**Issue by sebv** [angular/angular.js#3949]
Right now It accepts static data or a function, it would be good to be able to put a promise there.  

For instance this particular use case,  which happens with Karma unit tests, where your fixtures are accessible via http. You need to prefetch all the fixtures before the test start, then reference them when you setup your response in the mock httpBackend. It would be easier and more logical, just to do it once and have the response wait for a promise.

Edit: Here is my Fixture loading service https://gist.github.com/sebv/6509524#file-fixture-app-js I would like to be able to avoid the `prefetch` phase.

**Comment by Narretz** [comment]
Closing because it's a very rare use case
