### ISSUE TITLE
ng-touch, mouse event and 'ng-click-active' 

### ISSUE THREAD

**Issue by graynote** [angular/angular.js#3999]
I am building angularjs app that works on both touch and mouse environment. I am pleased to use ng-touch for touch support. I am using 'ng-click-active' for styling pressed state and it works well on touch device. But it does not works well on desktop and mouse environment. 'ng-click-active' is work differently from a  :active selector.

- 'ng-click-active' should not be disappeared if mouse down and hold on the element. (chrome and ie)
- 'ng-click-active' should not be disappeared if mouse down and move on the element.

below code makes the problem. 

    element.on('mousemove mouseup', function(event) {
       element.removeClass(ACTIVE_CLASS_NAME);
     });

chrome trigger mousemove event even if mouse does not move.

**Comment by elsom25** [comment]
Is there any progress on this? Or is it dead in the water?
