### ISSUE TITLE
ng-click and jquery-ui draggable

### ISSUE THREAD

**Issue by notbenj** [angular/angular.js#4000]
If you apply ng-click on a draggable element (using jquery-ui draggable), the ng-click is called when the element is dropped (onmouseup).

It would be nice not to fire the click event in this situation.

**Comment by bpirtle** [comment]
I am using a different DnD plugin (http://interactjs.io/) and I get the same behavior, so I don't think it's just with jQueryUI draggable (Which I also tried and get the identical behavior).

To make this work in my application, I created a global scoped model variable and use it to track state - In the dragend event (which fires first) I assign this to true and then check the state in the click handler (Which fires second) to see if I should return early or process the click, then reset in the click handler.

It is hackish, but it works until the real fix comes.

**Comment by Narretz** [comment]
I don't think this is a bug in either angular or draggable, it's simply the way the events work. If you want draggable and click on the same element, I think it's reasonable to assume you are going to provide your own solution for that.
