### ISSUE TITLE
angular-touch with jQuery fails to "fastclick"

### ISSUE THREAD

**Issue by mkadan** [angular/angular.js#4001]
If jQuery is loaded before AngularJS it uses it and fails to get proper touches/changedTouches properties from TouchEvent in 

angular-touch.js:1.2-RC2
353:element.on('touchstart', function(event) {
380:element.on('touchend', function(event) {

adding
event = event.originalEvent;
solves the issue

**Comment by andrezero** [comment]
+1

**Comment by petebacondarwin** [comment]
There is a PR #8584 as noted above but until it has a valid unit test proving the patch then we are not able to merge it.  Anyone want to help with this?
