### ISSUE TITLE
A universal resolve object on RouteConfigs?

### ISSUE THREAD

**Issue by xml** [angular/angular.js#4010]
This would mostly be sugar, but can possibly relieve an awful lot of repetition, while also permitting us to think in terms of 'route-specific data' and 'app-wide-data'. 

Assume that we're making as much of the app data-driven as possible, including things like navigation contents. There is essential async data that has to load out before _any_ route loads, in the event that the user deep-links straight into the middle of the app. So, we can't just put that essential data onto "/" and assume it'll be available when needed elsewhere.

The answer? `resolve:` to the rescue. But, if you have an app with 30 routes, and you need a promise that's resolved before _any_ of them load, you're going to repeat your `everywhere` promise 30 times in the routeConfigs, and then your route-specific `onlyHere` promises along with it. It works, of course, but all that redundancy just... looks wrong. It's not the Angular Way. 

Suggestion: some form of configuration option that specifies a `resolve` object that is applicable on all routes.

(The only clean alternative I've been able to suss out so far: use manual bootstrap and resolve that universal data source before bootstrap, then inject as a constant and reference in a service.)

**Comment by Narretz** [comment]
Universal resolve isn't coming to ngRoute at this point. It would require an actual tree parent / child structure of routes to be really useful, which is very complex to implement.

Fortunately, you can work around this issue by adding the "global" resolve to every route. It's not clean, but it works.

And fortunately, the ui router https://ui-router.github.io/ng1/docs/latest/index.html has global resolves available.
