### ISSUE TITLE
Composition of error handler + interceptors should be more flexible

### ISSUE THREAD

**Issue by mkotsur** [angular/angular.js#4013]
For `ngResource` there are 3 places to handle HTTP errors:

- Interceptor on global level defined via `$httpProvider` (further _global interceptor_),
- Interceptor defined for every action of every `$resource` (further _local interceptor_),
- Error handler specified within the call of the action (as a second error handler argument).

The demo of all 3 ways is here: http://plnkr.co/edit/wWGzbEUj1Gr2KwmxTrmx

There are 2 problems with this:
- The order is kind of illogical: global interceptor -> error handler -> local interceptor;
- There is no way to let know from the _error handler_ that interceptors should not handle that error anymore.

Now the use-case: I want to make user aware of every failed request. But:
* Some of them I'll handle in my controllers where I call the action. Let's say show very nice error message, or implement the fall-back logic;
* Some of them are resource specific. Like if I have `User` resource and it returns me 404 not found, I always want to redirect somewhere;
* And finally _all other errors_. I want no silent failures to happen and I write a global interceptor which will handle all error responses (_if they are not handled yet_) and show growl-style notification with HTTP code and error message from server.

Currently it's only possible to talk from error handler to local interceptor by setting some `response._handled = true` (not really nice), but global interceptor is always executed first and thus completely out of control.

The solution could be:
1. Add a an _order_ attribute to interceptors. Error handler can have some default value and interceptors get order assigned relative to that;
2. Some way of preventing interceptors of being called from the error handler.

**Comment by gkalpak** [comment]
I think this is one of those cases were you can't make everyone happy. (Some people would want to one order, some the other and making every detail configurable will just make the API unleasant for everyone.)

Also note that there are two distinct interceptor pipelines at play here (the one for `$http` and the one for `$resource`) that should not be intermixed.

Considering that the current implementation was a conscious decision and that it is already possible to achive what you want (in a reasonable - if not ideal - way), I am going to close this.

--
That said, I admit that the current interceptors/tranformRequest/transformResponse story for `$resource` needs improvement. Let's move the discussion to #9334.
