### ISSUE TITLE
DOM Spec Input - Virtual MutationRecords

### ISSUE THREAD

**Issue by bmeck** [angular/angular.js#4018]
This is a request for input on data binding and web component state:

With respect to <input> <select> and <textarea> elements, change events do not currently map to MutationRecords, please see https://www.w3.org/Bugs/Public/show_bug.cgi?id=23226 , please make any comments that you find relevant.

IRC recommended I make an issue

**Comment by Narretz** [comment]
Looks like we never got around to participate and the discussion is closed. Oh well!
