### ISSUE TITLE
Can't use custom element directives in IE with templates

### ISSUE THREAD

**Issue by jardilio** [angular/angular.js#4020]
The IE documentation (here: http://docs.angularjs.org/guide/ie) states that for custom element directives, you need only to call document.createElement('my-element') for support. 

This is only partially true as it appears that this fix will only work if the element was natively added to the DOM (example: It was already in your index.html page or you used document.createElement('my-element') and appended the result to another element). 

It doesn't appear to work if you are appending the value to innerHTML or using jQuery to wrap an HTML string representing the markup which contains the custom element. In this case, it fails in the same way that the working example does if you didn't do the document.createElement shim. The DOM is now corrupted.

Where this all ends up breaking is lets say you have 2 directives (directive-a and directive-b) which are both registered as custom elements. In this example, directive-a has a template and that template contains a reference to directive-b. Angular will jQuery wrap this template, but in IE8, the template is corrupted and in advanced combinations of replace/transclude with multiple elements, items can become reparented to the wrong item.

See following plnkr (http://plnkr.co/edit/lYN0YeYJaDmTvEdMtzn1?p=preview). This example will work fine in browers other than IE8 (you'll need to run the output directly in IE8 as plnkr doesn't support IE8 - http://run.plnkr.co/plunks/lYN0YeYJaDmTvEdMtzn1/).

**Comment by Narretz** [comment]
IE8 is no longer supported.
