### ISSUE TITLE
Inconsistent behaviour on IE8

### ISSUE THREAD

**Issue by purcell** [angular/angular.js#4029]
I'm not sure if this is a supported case, but I can use a directive to merge attributes into a DOM element, so given

```html
<input class="typeahead-input" name="query" placeholder="Search" required>
```

and

```js
angular.module('myapp').directive('typeaheadInput', ["$timeout", function($timeout) {
  return {
    restrict: "EAC",
    replace: true,
    template: '<input autocomplete="off" ng-model="term" ng-change="query()">',
    link: function(scope, element, attrs, controller) {
       ...
    }
  }
});
```

I'll get this in the DOM:

```
<input autocomplete="off" ng-model="term" ng-change="query()" class="typeahead-input" name="query" placeholder="Search" required="required">
```

This is handy because the directive can "plug in" the ng-model and ng-change directives on my behalf.

However, in IE8 I get an unhelpful error: "This command is not supported.undefined". Sigh.

Am I doing something stupid (most likely), or is this a bug?

(This is all with Angular 1.2.0-rc.2.)

**Comment by lgalfaso** [comment]
This issue is specific to IE8 that only has support in the 1.2.x branch, but this branch is open only for regressions and security issues. Closing this
