### ISSUE TITLE
ngTouch: ng-click directive is broking default behaviour of child elements

### ISSUE THREAD

**Issue by tromex** [angular/angular.js#4030]
With ngTouch module included, ng-click directive is breaking the default behaviour of child elements like anchor `a` and form elements like `input`. The problem is only with touch devices, on mouse devices everything works as expected.

Here is an example:
http://plnkr.co/edit/BFhC6n

**Comment by Sankluj** [comment]
The issue is still present in ```1.3.16```
Plunkr: http://plnkr.co/edit/WVOA1R2xpUqvs0HgDPBO
with angular-ui modal: http://plnkr.co/edit/gyNF9BhiaBuMtonPXYKS
