### ISSUE TITLE
$cookie service should allow setting cookies that last longer than a session

### ISSUE THREAD

**Issue by jan-molak** [angular/angular.js#4069]
Hi and thanks for all your awesome work on angular.js so far!

It seems like the `browser` service that's being used by the `$cookie` service hardcodes the expiration time of any cookie set with it: https://github.com/angular/angular.js/blob/master/src/ng/browser.js#L287

It would be great if it was made possible to specify expiration time as a parameter when setting a cookie.

**Comment by poliveira89** [comment]
This issue is inactive for almost 1,5 years, anyone has a solution, other than jQuery plugins or "pure" Javascript?

**Comment by lgalfaso** [comment]
@poliveira89 #10530 should make it into 1.4

**Comment by Narretz** [comment]
It has made it into 1.4!
