### ISSUE TITLE
Migrate ngResource to use a $resourceProvider similar to $httpProvider for Configuration

### ISSUE THREAD

**Issue by kevinastone** [angular/angular.js#4109]
the `$resource` factory involves a lot of defaults and other assumptions that would be nice to customize across all instances.  For example, you could set the `DEFAULT_ACTIONS`, configure interceptors or URL routes.

**Comment by gkalpak** [comment]
There is now a [`$resourceProvider`][1] and certain things are globally configurable (e.g. actions). Hopefully, that is sufficient. Not everything lends itself for being globally configurable though.

If there are more things that you would like to be configurable, open specific issues to get the discussion started.

[1]: https://docs.angularjs.org/api/ngResource/provider/$resourceProvider
