### ISSUE TITLE
Binding text to <option> does not work in an ng-if/ng-switch-when block in IE8

### ISSUE THREAD

**Issue by gsmith85** [angular/angular.js#4147]
Binding to an `<option>` in a `<select>` box does not work in IE8 if the `<select>` box is in an `ng-switch-when` block of a `ngSwitch` directive.  This issue is consistent for both double bracket binding and `ng-bind`.

The exact same markup outside of an `ng-switch-when` will result in the binding being correctly resolved.  This is even the case if the `select` is outside of an `ng-switch-when` but still wrapped by the `ng-switch`.

In other browsers the `<option>` correctly binds whether the `<select>` is in or out of  `ng-switch-when`.  I tested in Chrome 29 and Firefox 23 and 9.

I created a jsbin demonstrating this behavior: http://jsbin.com/oqeNUdU/2/

Similar behavior is exhibited by the `ng-if` block: http://jsbin.com/UfitehO/1/

What's most maddening about this issue is that if you look at the text node on the '<option>' block using developer tools you'll see that the text is correctly set.  IE8 seems to simply not redraw the text in the '<select>'.

Apologies for not using plnkr per the issue guidelines, but for this issue IE8 compatibility for the live example is essential.

**Comment by lgalfaso** [comment]
Support of IE8 is only present in 1.2.x, and this branch is only open for regressions and security issues. Closing this issue
