### ISSUE TITLE
orderBy speed optimization

### ISSUE THREAD

**Issue by agentcooper** [angular/angular.js#4177]
I made a speed optimization to the orderBy filter utilizing the schwartzian transform.

Here is the jsPerf: http://jsperf.com/orderby-speed-optimization

And here is the diff: https://github.com/agentcooper/angular.js/commit/d20a9e65eb2a4fdf9f935636c5c278212e3d09cc (not sending a pull request yet, because tests are currently broken in master :-( Can we fix it?)

**Comment by Narretz** [comment]
Fixed in https://github.com/angular/angular.js/commit/48e1f5605edd32a63318fd78f5165c7d1f1a20f9
