### ISSUE TITLE
Broken anchor link when directive replaces its markup

### ISSUE THREAD

**Issue by plaflamme** [angular/angular.js#4262]
A simple directive that replaces markup with an anchor surrounded by a div. This is broken when the markup being replaced is an anchor itself.

There are 2 workarounds:

* don't use an anchor tag to be replaced
* don't surround the replacing anchor with a div

See here for a reproduction of the issue: http://plnkr.co/edit/sYqXhe3gcBicmR1tSECN

**Comment by caitp** [comment]
the cause of this is that event listeners are copied, and the replacement `div` element does not have an href attribute, so it gets removed.
