### ISSUE TITLE
Fast DOM

### ISSUE THREAD

**Issue by karol-f** [angular/angular.js#4296]
Does Angular use techniques such as that used in FastDOM ( https://github.com/wilsonpage/fastdom )? Does that apply to Angular?

Hope this idea might be helpful. Regards.

**Comment by wesleycho** [comment]
I'm not sure how useful it is to keep this issue open - perf improvement tasks are probably better tracked with more granular issues.

**Comment by petebacondarwin** [comment]
I agree. Thanks @wesleycho
