### ISSUE TITLE
Pdf files doesn't render properly when using pdf.js directly in HTML5 view (pdf.js passed by $scope variable)

### ISSUE THREAD

**Issue by bl4de** [angular/angular.js#4299]
Hi,

I've reported this issue previously to Mozilla/pdf.js project, but I think it may be the problem with Angular.js rather.

Details:
I use pdf.js in some application. HTML5 views are generated by Java-based backend (JSP, Spring), where I've integrated AngularJS to manipulate client-side code directly in web browser.

I've got an Angular service, which is simple wrapper for pdf.js basic functionality:
```javascript

application.service("PdfjsService", [ function() {
	// reference to service for callbacks
	var __service = this;
	
	this.url = "";
	
	this.canvasId = "";
	
	// initial values
	this.page = 1;
	this.scale = 1.0;
	
	this.init = function(canvasId, page, scale) {
		this.canvasId = canvasId;
		if (scale) {
			this.scale = scale;
		}
		
		if (page) {
			this.page = page;
		}
	};
	
	this.render = function(url) {
		if (PDFJS) {
			PDFJS.getDocument(url).then(function(pdf) {
				pdf.getPage(__service.page).then(function(page) {
                var scale = __service.scale;
                var viewport = page.getViewport(scale);
            
                var canvas = document.getElementById(__service.canvasId);
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;
            
                var renderContext = {
                  canvasContext: context,
                  viewport: viewport
                };
                page.render(renderContext);
              });
			});
			
		}
		
	};
}]);
```

I can call this service in two different ways:

- only in controller, like this:

```javascript
// other code in Angular controller

PdfjsService.init('the-canvas', 1, 1);
PdfjsService.render('${contextPath}/resources/img/somefile.pdf');

// other code in Angular controller
```

or

- directly in JSP HTML5 code, after passing reference to PdfjsService as $scope var:

controller:

```javascript

// other code in Angular controller


            PdfjsService.init('the-canvas', 1, 1);
            $scope.pdfservice = PdfjsService;

// other code in Angular controller

```

and view:

```HTML
<!-- other HTML -->

 <div class="span4">
    <canvas id="the-canvas" style="border:1px solid black; width:350px;"/>
  </div>
  {{pdfservice.render('${contextPath}/resources/img/somefile.pdf')}}

<!-- other HTML -->


```

${contextPath} is Spring variable, which has no impact for whole situation (it's only a part of path to pdf file).

Pdf file is visible in both cases, only in the second one is diverted vertical and mirrored :/

I can't attach this specific pdf file, because it's confidential (it's a part of commercial project and only for internal use)

I created working example, including all elements (Angular, pdf.js lib and some sample pdf file) - and the problem occurs exactly the same way as described above.

https://github.com/bl4de/pdfjs_angularjs

Reference to the issue in Mozilla/pdf.js repo:
https://github.com/mozilla/pdf.js/issues/3758

**Comment by Narretz** [comment]
Closing because the issue doesn't seem to have anything to do with angular,
