### ISSUE TITLE
Proposal for multiple transclusion targets

### ISSUE THREAD

**Issue by ravinggenius** [angular/angular.js#4350]
When transcluding into a directive, it would be super useful to specify multiple targets. Polymer makes this easy with the [`<content />` element](http://www.polymer-project.org/platform/shadow-dom.html#basic-usage), together with the `[select]` attribute.

What I'm proposing is to allow `[ng-transclude]` (in the target directive template) to take an optional CSS selector, which would select content from the source (where the directive was used) and stick it into the appropriate place in the template. For instance:

```html
<!-- foo directive usage -->
<foo>
  <p>Regular content goes here.</p>
  <foo-footer>
    <p>I show up in the footer.</p>
  </foo-footer>
</foo>
```

```html
<!-- foo directive template -->
<div class="foo">
  <div class="foo-body" ng-transclude />
  <div class="foo-footer" ng-transclude="foo-footer" />
</div>
```

```html
<!-- foo directive dom (after rendering) -->
<div class="foo">
  <div class="foo-body">
    <p>Regular content goes here.</p>
  </div>
  <div class="foo-footer">
    <p>I show up in the footer.</p>
  </div>
</div>
```

**Comment by dgroomes** [comment]
+1

**Comment by fernandopasik** [comment]
Web Components have this awesome feature, it would be awesome to have it in angular! :)

**Comment by Narretz** [comment]
A feature like this will land in 1.5: https://github.com/angular/angular.js/commit/a4ada8ba9c4358273575e16778e76446ad080054 :)
