### ISSUE TITLE
$stylesheet and $stylesheetCache 

### ISSUE THREAD

**Issue by jpolo** [angular/angular.js#4363]
Hi,

When I saw the way that the styles for 'ng-cloak' were injected in the DOM, I thought that it might be a good idea to manage those CSS snippet just like the $templateCache does.

In consequence, I wrote a $stylesheet and $stylesheetCache component that helps to "normalize" the way that the CSS snippet are written and injected.
(the code can be found here : https://gist.github.com/jpolo/6918250 )

I use it mostly when I have to embed some "ng-cloak like" style information into a directive file. I hope you'll like the idea.

**Comment by jpolo** [comment]
Anything new on this issue ? I recently saw that Angular material project is managing their themes with generated CSS at runtime.
This kind of feature could help to normalize those behaviors.

**Comment by wesleycho** [comment]
I'm not a fan of this being in core - it seems like a potentially significant amount of code that many users will not leverage. This is better off released as an open source module.

**Comment by gkalpak** [comment]
I agree with @wesleycho that this is out of scope for core. It's fine as a 3rd-party module though :smile:
