### ISSUE TITLE
ngWith directive

### ISSUE THREAD

**Issue by jamie-pate** [angular/angular.js#4368]
Has there been consideration for an ng-with directive? similar to django's 'with' tag https://docs.djangoproject.com/en/dev/ref/templates/builtins/#with

See also:
http://stackoverflow.com/questions/16124645/shouldnt-there-be-an-angularjs-ngwith-directive

**Comment by gambala** [comment]
+1

**Comment by jackvsworld** [comment]
+1

**Comment by S-YOU** [comment]
How can technically possible to have inheritance from two objects (loop variable and $scope) and have better performance?

**Comment by jamie-pate** [comment]
The performance savings comes from evaluating fewer watch expressions (If there's a common (expensive? probably still not a good idea) expression that would be repeated in the template, caching the value on the scope reduces how often it's evaluated).

Also, JS prototype inheritence isn't /that/ costly.

**Comment by S-YOU** [comment]
making fewer watchers is different thing, its like third-party __-repeat out there.

**Comment by Narretz** [comment]
[This answer](http://stackoverflow.com/a/16124931/787333) to the original SO question explains well why this is not somthing that  will come to Angular. If you start changing the template context, then it's gonna get confusing real quick.

**Comment by jamie-pate** [comment]
In practice it doesn't. The post you reference doesn't reply to the comments I left ;) It seems pretty clear to me that the assigned alias is not assignable in any meaningful way, but if your model is several layers deep and you want a reference to say `abcde.fghi.jkl() as jkl` in a template where `jkl` is referenced frequently it's a time saver. 

Of course if there is that much complexity I have lately come to rely more on the holy trinity of  directive, bindtocontroller and controlleras to define solid decoupled interfaces between moving parts anyways and the `with` helper becomes less useful in that context.

**Comment by Narretz** [comment]
The holy trinity is probably the way to go. :) Thing is if you are collaborating on some project and somebody uses ngWith and you don't know about it.

**Comment by jamie-pate** [comment]
The same kind of rules apply to this as to regular scope variables, you can update properties of the aliased object, but can't reliably assign to the object itself as you may be assigning to an inner scope unintentionally. No different

**Comment by krnlde** [comment]
If would suggest `ng-init="item = vm.data.item"`

**Comment by jamie-pate** [comment]
From the docs for ng-init: https://docs.angularjs.org/api/ng/directive/ngInit
>This directive can be abused to add unnecessary amounts of logic into your templates. There are only a few appropriate uses of ngInit, such as for aliasing special properties of ngRepeat

**Comment by krnlde** [comment]
So basically exactly what I am doing.
