### ISSUE TITLE
Can't use class attribute interpolation together with addClass

### ISSUE THREAD

**Issue by juliemr** [angular/angular.js#4383]
The element

```
<span class="prefix-{{foo}}"> {{bar}} </span>
```

should be given a class `ng-binding`, since it contains the binding 'bar'. However, this is not the case, as shown here: http://jsfiddle.net/5UyD2/1/

**Comment by thorn0** [comment]
Why wasn't this marked as "type: bug"?

**Comment by gkalpak** [comment]
We've accepted (and [documented][1]) this as a known issue (which also affects directives like `ngClass`, `ngStyle`, etc).

[1]: https://github.com/angular/angular.js/blob/841feb0a05f0b716d0628c2341820893bda5f929/docs/content/guide/interpolation.ngdoc#L120-L129
