### ISSUE TITLE
angular ngRoute breaks when using base tag

### ISSUE THREAD

**Issue by jimmywarting** [angular/angular.js#4442]
Demo:
http://plnkr.co/edit/TkADpfgchYVdvNTqRPFT?p=preview

Apparently it's because of the new changes to this: https://github.com/angular/angular.js/commit/b019a48bb1176f3c9ce29b628a321b6ffe873393

It dose not complain when you are actually on that same url as the base href

**Comment by levarberry** [comment]
Using  AJS 1.3.4   when  HTML5mode is true  ...   AngularJS doesn't work at all.. Getting Error  TypeError:  Url is undefined.

**Comment by caitp** [comment]
@levarberry do you have a stack trace? please file a bug with more information, thanks!

**Comment by Narretz** [comment]
Basically this is a request for the ngAppRoot directive: https://github.com/angular/angular.js/issues/3102
