### ISSUE TITLE
ng-class is not working properly ie8 + document mode: IE7 standards after 1.2.0-rc.3

### ISSUE THREAD

**Issue by ValeriiVasin** [angular/angular.js#4517]
Assume we have a snippet:
```html
<div ng-class="{'red': model.isRed,'blue': model.isBlue}">Hello</div>
```

and we have a meta on the page:
```html
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
```

`model` preperties updates correctly, but nothing changes.

Demo: http://jsbin.com/IDexoga/5/edit?html,js

You could try to open it in IE8/9/10.

In RC2 it works fine.

**Comment by Gargaroz** [comment]
+1

**Comment by Narretz** [comment]
1.2.28 is unsupported, and IE8, too.
