### ISSUE TITLE
Allow $anchorScroll.scroll() independent of location.hash

### ISSUE THREAD

**Issue by hasdavidc** [angular/angular.js#4568]
I'm wondering if there is a specific reason $anchorScroll can only scroll to the hash location and if this could be extended to simply allow an ID to be passed in to the scroll() function to override hash.

https://github.com/angular/angular.js/blob/master/src/ng/anchorScroll.js#L72-L86

**Comment by siva3378** [comment]
Do we have any solution for this..??

**Comment by gkalpak** [comment]
This functionality is already available since recently (since v1.4.0-rc.0 iirc).

**Comment by siva3378** [comment]
@gkalpak, can I have any ref link where can I check more about it... plz..

**Comment by gkalpak** [comment]
@siva3378, not sure what you mean. You can check out the [docs][1].

[1]: https://docs.angularjs.org/api/ng/service/$anchorScroll

**Comment by siva3378** [comment]
@gkalpak, In the docs, it is said, "set the $location.hash to `newHash` and $anchorScroll will automatically scroll to it", but I don't want to change the URL in the address bar and I want to scroll it to particular div which has certain Id like category-{{index}}.
Is there any other methods like $anchorScroll("category-21"); scrolls to a div of id="category-21"

**Comment by gkalpak** [comment]
@siva3378, are you viewing an older version of the docs ? (Like I said, the feature was only recently added).

In the latest docs (linked above) it mentions clearly:

> When called, it scrolls to the element related to the specified hash or (if omitted) to the current value of `$location.hash()`, according to the rules specified in the HTML5 spec.

> It also watches the `$location.hash()` and automatically scrolls to match any anchor whenever it changes. This can be disabled by calling `$anchorScrollProvider.disableAutoScrolling()`.

And in _Usage_ and _Arguments_ sections:

> **Usage**
   $anchorScroll([hash])

> **Arguments**
   hash (optional) | string | The hash specifying the element to scroll to. If omitted, the value of $location.hash() will be used.

**Comment by s134319** [comment]
@gkalpak Is there any (plunker) example for the usage of $anchorScroll independently of location.hash? Didn't get it to work as expected.

**Comment by rebelliard** [comment]
This works for me:

```js
$rootScope.$on('$routeChangeSuccess', function(event) {
    var old = $location.hash();
    $location.hash('my-new-hash');
    $anchorScroll();
    $location.hash(old);
});
```

**Comment by gkalpak** [comment]
@s134319: Here is a [working demo][1]. Basically, all you got to do is call `$anchorScroll('some-hash')`.

[1]: http://codepen.io/ExpertSystem/pen/RPKrXj?editors=101

**Comment by vippatel90** [comment]
@rebelliard   : This is not ideal solution of temporary putting hash and then scroll to that hash and again changing to old hash to just to stay as it is in address bar.

IF you put temporary hash and you are running SPA with router which is most likely the case,  then you will get immediately redirected to error page as all good SPA website make redirection to page not found  kind page for invalid hash.

**Comment by gkalpak** [comment]
@vippatel90, (just in case you missed it) there is a simpler, safer alternative (see https://github.com/angular/angular.js/issues/4568#issuecomment-106621383).
