### ISSUE TITLE
`$eval` assignment expression and locals

### ISSUE THREAD

**Issue by caiotoon** [angular/angular.js#4664]
We can't use a `local` variable in the left side of an assignment without enclosing it in parenthesis to ensure it to be resolved first.

I tried to raise a discussion [here](https://groups.google.com/forum/#!searchin/angular/eval$20locals/angular/rEvNHJ9x5jI/CraUhwCMOsMJ) in order to understand whether it's a bug or not but had not much success. 

Basically, this test case won't succeed:

```javascript
it('should allow passing object as locals to the left part of an assignment expression', inject(function($rootScope) {
  var ob = {};
  $rootScope.scopedValue = 1;
  $rootScope.$eval('a.value = scopedValue', {a: ob});
  expect(ob.value).toBe(1);
  expect($rootScope.a).toBeUndefined();
}));
```

While changing the expression to `(a).value = scopedValue` the test will succeed. Assembled a [Plnkr here](http://plnkr.co/edit/OymAjMSdGXjwqifesxKD?p=preview) to illustrate it.

As I said before, I'm not sure if this is a bug or a limitation. If it's the later, then I think I could change the documentation to exemplify it. So, is this a bug or a expected limitation?

**Comment by lgalfaso** [comment]
This was fixed as part of #10592
