### ISSUE TITLE
IE10 Expression in placeholder attr causes input to be dirty

### ISSUE THREAD

**Issue by sngan** [angular/angular.js#4781]
Hi all,

http://jsfiddle.net/S73bF/

In IE10, when you have a {{ }} expression in the placeholder attribute of an input (in example, a textarea), it is getting marked as dirty before user interacts with it.

Thanks,
Sun

**Comment by havenchyk** [comment]
@sngan just use ng-attr-placeholder https://docs.angularjs.org/guide/directive#-ngattr-attribute-bindings. I guess the problem can be closed.

**Comment by Narretz** [comment]
This is fixed in 1.4. For 1.2, there's always the `ng-attr-placeholder` workaround.
