### ISSUE TITLE
Cannot send Array data in request body using $Resource action without setting 'isArray' to true

### ISSUE THREAD

**Issue by ardpx** [angular/angular.js#4795]
If 'isArray: false' is set for the $Resource action which sends out only Array data in request body and expects non-Array data in response, the exception 'TypeError: Object #<Resource> has no method 'push'' will be issued when the action is invoked. It seems 'isArray' affects both return type and request type, which should not be reasonable.

Suggest to fix the code in angular-resource.js 
from
var value = isInstanceCall ? data : (action.isArray ? [] : new Resource(data)); 
to
var value = isInstanceCall ? data : ((action.isArray || toString.apply(data) == '[object Array]') ? [] : new Resource(data));

**Comment by gkalpak** [comment]
Closing as we don't have a reproduction.
