### ISSUE TITLE
Angular ng-select bug in Chrome when using tab navigation and no default empty option

### ISSUE THREAD

**Issue by vilmosioo** [angular/angular.js#4836]
There seems to be a weird bug when selecting values in Chrome on Windows using the keyboard only.

    function MyCtrl($scope) {
        $scope.d = '';
        $scope.options = [1,2,3];
        $scope.d2 = '';
        $scope.options2 = [1,2,3];
    }
    
    <input><br>
    <select ng-options="d for d in options" ng-model="d"></select><br>
    <select ng-options="d for d in options2" ng-model="d2"></select><br>
    <input>

JSFiddle:
http://jsfiddle.net/DrTCZ/4/

Steps to replicate:

 1. Click on first text field
 2. Press tab
 3. Using the keyboard, select 2
 4. Press tab
 5. Using the keyboard, select 2

Notice the value of the first dropdown. 

Any help would be appreciated!

**Comment by david0603** [comment]
Any eta for this?  Thanks.

**Comment by vilmosioo** [comment]
This is not an angular bug but a Chrome bug.

**Comment by risingfish** [comment]
I believe this is related to this bug: https://code.google.com/p/chromium/issues/detail?id=415505

**Comment by Narretz** [comment]
Fixed in chrome 47: https://bugs.chromium.org/p/chromium/issues/detail?id=415505
