### ISSUE TITLE
Invalid templateUrl in $routeProvider should throw an exception

### ISSUE THREAD

**Issue by gaurish** [angular/angular.js#4867]
````javascript
App.config(function ($routeProvider){
  $routeProvider
    .when('/',{ templateUrl: './dssd/partials/view1.html', controller: controllers.SimpleCtrl })
    .otherwise({redirectTo: '/'});
});
````

if you have given the `templateUrl` such as `./dssd/partials/view1.html` for which server returns 404 or any non-200 error. currently angular will fail silently without any error. 

I am wondering, if its a good idea to throw an exception or add some warning for this?

**Comment by Narretz** [comment]
This throws the tpload error in 1.4 (and probably before that). It should be catchable by an interceptor, too.
