### ISSUE TITLE
jQuery.detach negating ngSubmit event handling

### ISSUE THREAD

**Issue by arciisine** [angular/angular.js#4887]
In angular 1.2, inside of ngSubmit, there is a work around for IE9 that adds an event listener (to prevent form submission), and removes it when the form is 'destroyed' (removed from DOM). Calling jQuery.detach should remove the node from from the DOM, but should retain all event listeners. 

The problem here is that when the contents of jQuery.detach are readded to the DOM, the removed listener is not being added back.  So after the first time the jQuery.detach is called on the form, the ngSubmit will always do a proper html form submit.

**Comment by mgol** [comment]
Closing because of no response & the age of this report.
