### ISSUE TITLE
feat(ngTouch): Add unbind() for $swipe service

### ISSUE THREAD

**Issue by robinboehm** [angular/angular.js#4991]
Should this service provide an e.g. unbind() method?
I don't want to remove/recreate the DOM element to handle this.

Anyone else got this need?

**Comment by je-dimedis** [comment]
any update on this?
see #3939 too

**Comment by Rleahy22** [comment]
+1

**Comment by danemacaulay** [comment]
To do this manually
```js
$scope.$on('$destroy', function () {
    // where $element is the element $swipe is bound to
    $element.unbind('mousedown mousemove mouseup touchstart touchmove touchend touchcancel');
});
```

**Comment by aegrey** [comment]
+1 - would like to be able to unbind to swipeRight but not SwipeLeft and visa versa.

**Comment by Rouche** [comment]
+1 unbind but a lot of other options could be usefull.

Might as well have to rewrite it too based on @mcasimir 

-MOVE_BUFFER_RADIUS option
-A way to let client control this part of code. if i want to preventDefault / cancel the active myself. 

```
if (totalY > totalX) {
            // Allow native scrolling to take over.
            active = false;
            if (eventHandlers.cancel) {
              eventHandlers.cancel(event);
            }
            return;
          } else {
            // Prevent the browser from scrolling.
            event.preventDefault();
            if (eventHandlers.move) {
              eventHandlers.move(coords, event);
            }
          }
```

**Comment by Narretz** [comment]
I'm closing this issue since the ngTouch module will be deprecated in AngularJS 1.7.0, and we will not do any more work on it. This is because touch handling is a complex topic, and there are stand-alone libraries that are better equipped to handle all the nuances and edge cases. For example, https://hammerjs.github.io/, which is also used by Angular.
