### ISSUE TITLE
browserTrigger doesn't support TouchEvent.

### ISSUE THREAD

**Issue by munet9** [angular/angular.js#4997]
browserTrigger in ngScenario is very useful to triggering UIEvent and used in many spec files.
But ```browserTrigger(element, 'touchstart');``` is triggering ```MouseEvent``` instead of ```TouchEvent```.

This causes ```ngTouch``` tested uncorrectly.
```TouchEvents``` has no clientX, clientY, But ```MouseEvent``` has these. So ngClick(ngTouch) with current browserTrigger will pass successfully, but with real touch-enabled device won't work.

I know Chrome, Firefox needs special flags in desktop.
Is it difficult to support TouchEvent in current browsers?

I think this fixes some issues(#2548, #3556, #4001, #4428, #4583).

**Comment by petebacondarwin** [comment]
This was fixed by https://github.com/angular/angular.js/commit/06a9f0a95f0e72fa2e9879fe8a49e9bf69986a5f
