### ISSUE TITLE
IE8 Transclude (JQLite Bind) Bug

### ISSUE THREAD

**Issue by orlandohohmeier** [angular/angular.js#5023]
The following error is thrown in IE8 while compiling directives, which transclude images. 

	TypeError: Object doesn't support this property or method <div data-ng-transclude ng-1384854293898="4">

After a short investigation, I guess the error is thrown due to binding events on blank text nodes. Maybe the list of child nodes should be filtered in the directive compiling process (compileNodes, nodeLink). I also suggest to test elements before binding the events in the JQLite event binding function.

## Example

You find an example, of the described behavior, under the following url:

[http://jsfiddle.net/2bNSx/](http://jsfiddle.net/2bNSx/)

### JavaScript

	// Create app module
	var app = angular.module('app', []);

	// Register directive with template and transcluding enabled
	app.directive('parent', function () {
    	return {
       		template:'<div data-ng-transclude></div>',
        	transclude:true,
        	link: function (scope, element, attributes, controller) {}
    	}
	});

	// Bootstrap app
	angular.bootstrap(document, ['app']);

### HTML

	<div data-parent>
    	<img data-ng-src="http://angularjs.org/img/AngularJS-small.png" />
	</div>

**Comment by lgalfaso** [comment]
IE8 is only supported in 1.2.x, and this branch is only open for regressions and security issues
