### ISSUE TITLE
No simple way to listen for the NgModelController loading

### ISSUE THREAD

**Issue by chrisnicola** [angular/angular.js#5042]
When the NgModelController loads it may silently set the value on an input. So, for example, if I have another directive which bases it's behaviour on whether or not the input has a value in it than the only way to trigger it is with a general `$scope.$watch` which will run on all scope changes and not just when this input is set.

I'm open to suggestions on how else I might approach this, but it feels as if the `$viewChangeListeners` or some other listener should be called around here: https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js#L1173

**Comment by petebacondarwin** [comment]
I believe that this can be solved now using one-time bindings.
