### ISSUE TITLE
iPhone: ng-options selects next element first time

### ISSUE THREAD

**Issue by AlphaGit** [angular/angular.js#5132]
**Description:** a select with `ng-options` that generates a empty first element will select the element next to the one that the user selected.

**Angular Version(s):** Tested on 1.2.2. Doesn't seem to be a regression since I was able to verify the same issue in 1.1.1 and 1.2.0-rc3.

**Browsers and Operating System:** iOS7 (iPhone), tested with Safari and Chrome, latest versions.

**Reproducing the error:**
1. Browse this URL: http://jsfiddle.net/MTfRD/537/embedded/result/
2. Select "Feature" (first element)
3. Observe that the selected value in the select box is now "Bug" (second element).

**Workaround:**
http://jsfiddle.net/MTfRD/3/embedded/result/
Has the exact same configuration as the example that reproduces the error, except that a first element is forced in the select box.

(Code adapted from: http://stackoverflow.com/questions/12654631/why-does-angularjs-include-an-empty-option-in-select)

**Related issues:** Not that I'm aware of. Investigating this I arrived to [this issue](https://github.com/angular/angular.js/issues/1091), but I cannot tell if they are actually related or not.

**Comment by jcesarmobile** [comment]
The bug is still present if the sample is loaded on a UIWebView, even on iOS 8

**Comment by ghadeerrahhal** [comment]
@Magomogo's fix works great. Thanks!

**Comment by Narretz** [comment]
Can't repro in 1.4.9 or 1.5.3 (1.2.x is legacy and only receives critical bug fixes)
