### ISSUE TITLE
ngResource does not apply request interceptor

### ISSUE THREAD

**Issue by prettynatty** [angular/angular.js#5146]
ngResource removed transformRequest support but does not apply interceptor.request provided in actions. Shouldn't it?

**Comment by jtheoof** [comment]
:+1: This would be great feature added. I need this to convert query params from camel case to snake case, per request. I can't do it with `transformRequest` unfortunately.

**Comment by gkalpak** [comment]
@jtheoof, why can't you do it with `transformRequest` ?

**Comment by jtheoof** [comment]
Because `transformRequest` passes the payload of the request, not the whole config object.

```
GET /somepath/objects/aa0094f040120f708144e5f09d51978a?id_type=deviceid HTTP/1.1
Host: localhost
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
X-CSRF-TOKEN: blabla
...
```

In the `ObjectsResource`:

```
get: {
    method: 'GET',
    url: url + '/:id',
    transformRequest: function(request) {
        console.log(arguments);
        return request;
    },
}
```

Prints out: `[undefined, function, undefined, callee: (...), caller: (...)]`. 

The query params are gone, no way to do anything with it.

**Comment by gkalpak** [comment]
How are you setting the query params ?

**Comment by jtheoof** [comment]
In the service. Our backend only supports snake case, but our jshint rules are not happy about it. So I would like to create a transformer but `ngResource` does not allow to transform the query params in `transformRequest`.

In `objectService`: 
```
        /**
         * Fetches an object based on id and and id type.
         * @param {String} id The id of the object to get.
         * @param {String} idType The type corresponding to the id. Could be 'objectid' by default
         * or 'deviceid'.
         * @return {Resource} An angular $resource instance.
         */
        this.get = function(id, idType) {
            var options = {
                id: id
            };

            if (_.isString(idType)) {
                options.idType = idType;
            }

            // Converting `idType` to `id_type`. This should be done in transformRequest.
            var resource = ObjectsResource.get(utilsService.camelCaseToSnakeCase(options));

            return resource;
        };
```

**Comment by gkalpak** [comment]
@jtheoof, I see what you mean. (Although, it sounds much simpler to fix the jshint rules, that adding an interceptor.)

It is probably not the case, but if the query params where fixed, you could do:

```js
var ObjectsSource = new $resource('/some/url?id=:id&id_type=:idType', ...);
```

**Comment by jtheoof** [comment]
Good point, but they are not fixed... In my opinion, `transformRequest` should allow to transform the whole request, not only the payload. Or the function should be named `transformRequestPayload`. :wink:

**Comment by philBrown** [comment]
FYI, it's undocumented but each *action* config can add the `paramSerializer` which you can use to transform query parameters, eg

    {
        get: {
            method: 'GET',
            paramSerializer: function(params) {
                // do stuff to params
                return $httpParamSerializer(params);
            }
        }
    }

**Comment by dmcquillan314** [comment]
I'm using the paramSerializer for now until the feature is there.  Seems to be working fine.  Any reason why this is undocumented?  I'm assuming this is presumably a private function to angular?

**Comment by gkalpak** [comment]
The `paramSerializer` is not private. It's part of `$http`'s configuration (documented [here][1] and the available built-in serializers [here][2] and [there][3]).

The key-point is that the properties defined in the declaration object of custom `$resource` actions (with few exceptions, such as `interceptor`) are passed to `$http(config)`.
This is admittedly underdocumented (_"The declaration should be created in the format of $http.config"_ being a small step into the right direction :smiley:).

[1]: https://docs.angularjs.org/api/ng/service/$http#usage
[2]: https://docs.angularjs.org/api/ng/service/$httpParamSerializer
[3]: https://docs.angularjs.org/api/ng/service/$httpParamSerializerJQLike

**Comment by dmcquillan314** [comment]
Gotcha, that makes sense to me.  Thanks for the explanation.

**Comment by lpsBetty** [comment]
hmmm it doesn't work for me with angular $resource (I am using angular 1.4)
I also saw in the angular code that the ``paramSerializer`` will get passed to the http config, but the params in my custom function are always ``undefined``? 

Any help would be much appreciated!!

code snippet:
````
// RESOURCE
angular.module('app').factory('User', function ($resource, $httpParamSerializer) {
  var serializer = function (params) {
    console.log(params); // => is always undefined
    if(params && params.encodedEmail) {
      params.encodedEmail = decodeURIComponent(params.encodedEmail);
    }
    return $httpParamSerializer(params);
  };

  return $resource('.../user/:encodedEmail', {encodedEmail: '@encodedEmail'}, {
    get: {paramSerializer: serializer}
  });
});

// CALL in controller
User.get({encodedEmail: '2312'});
````

**Comment by dmcquillan314** [comment]
Here's the implementation that I used made:

.factory('BVReviewFactory', [ '$q', '$http', '$resource', '$httpParamSerializer', 'BV_CONFIG', function($q, $http, $resource, $httpParamSerializer, bvConfig) {
    return $resource( bvConfig.apiUrl + '/data/:method', {
        apiVersion: bvConfig.apiVersion,
        passKey: bvConfig.apiKey
    }, {
        'submit': { 
            method: 'POST',
            isArray: false,
            withCredentials: false,
            paramSerializer: function(params) { // TODO: This should not be necessary
                if(angular.isUndefined(params.userNickname) || angular.isUndefined(params['AdditionalField_viewName'])) {
                    delete params.userNickname;
                    delete params['AdditionalField_viewName'];

                    return $httpParamSerializer(params);
                }

                params.userNickname = params.userNickname + bvConfig.nicknameSeparator + params['AdditionalField_viewName'];
                delete params['AdditionalField_viewName'];

                return $httpParamSerializer(params);
            },
            params: {
                method: 'submitreview.json',
                userEmail: '@userEmail',
                userId: '@userId',
                action: '@action',
                rating: '@rating',
                title: '@title',
                reviewText: '@reviewText',
                productId: '@productId',
                userNickname: '@userNickname',
                'AdditionalField_viewName': '@viewName'
            }
        },
        'retrieve': { // https://developer.bazaarvoice.com/docs/read/conversations/reviews/display
            method: 'JSONP',
            isArray: false,
            interceptor: {
                response: function(response) {

                }
            },
            params: {
                callback: 'JSON_CALLBACK',
                method: 'reviews.json',
                include: 'Products,Categories,Authors,Comments', // TODO: This list could be slimmed down
                limit: '@limit',
                offset: '@offset',
                sort: '@sort',
                stats: 'Reviews' // Used to get rating distribution
            }
        }
    });
}]);
Although, I ended up not having to transform the request anyways.

**Comment by gitnik** [comment]
What happens when you log the `arguments`? maybe params is not the first argument

**Comment by lpsBetty** [comment]
@gitnik arguments is also undefined..
````
console.log(arguments); // => [undefined]
````

**Comment by philBrown** [comment]
@lpsBetty the param serialiser is for query parameters, not those interpolated into the path.

**Comment by lpsBetty** [comment]
@philBrown ah thanks! Does anyone know how I can change params before they get interpolated into the path?

**Comment by weisk** [comment]
+1 for the feature request..

Not sure if it's exactly my case though.

I have a global $http interceptor that does some data transformations, and then I have a few particular $ngResources that need particular transformations, what I'd like to be able to do is to specify an array of interceptors in the $ngResource as its done in the $http.defaults service.

```javascript
module.factory('globalInterceptor', function($q) {
  return {
    'request': function(config) {
      return config;
    }
  }
});

module.factory('localInterceptor', function(){
  ...
});

module.config(function($httpProvider){
  $httpProvider.interceptors.push('globalInterceptor');
});

module.service('myService', function($resource){
  return $resource('/something', null, {
    someAction: {
      method: 'POST',
      interceptors: ['globalInterceptor', 'localInterceptor']
    }
  });
});
```

**Comment by qstrahl** [comment]
+1 for this feature request. In my case, I need to fetch a token (which may or may not be cached) from a 3rd party REST service and send it with each request made by the resource. Intercepting the request seems like the obvious answer.

**Comment by phil-hachey** [comment]
+1 for this feature request

**Comment by acbabis** [comment]
+1

**Comment by webpartisan** [comment]
+1
I need request interceptor in resource too

**Comment by Zemke** [comment]
+1

**Comment by gitnik** [comment]
@qstrahl just FYI, but what you're trying to achieve does not depend on this non-existent feature but can be achieved via `$http` interceptors like so:
```javascript
$httpProvider.interceptors.push(
        ($injector, $q) => {
            return {
                request(config) {
                    $injector.invoke((UserService) => {
                        config.headers = config.headers || {};

                        config.headers['x-token'] = UserService.getToken();
                    });
                    return config;
                }
            };
        }
    );
```

**Comment by qstrahl** [comment]
@gitnik You misunderstand my problem. Your suggestion will call the interceptor for every request ever made by `$http`. That's exactly what I want to avoid. I need the interceptor on the resource method only.

**Comment by gitnik** [comment]
Ah sorry misread some parts of your question

**Comment by qstrahl** [comment]
No worries

**Comment by jdrorrer** [comment]
+1

**Comment by k3v3n** [comment]
You get my vote for this one +1

**Comment by almothafar** [comment]
+1 for BASIC feature asked from 3 years !!!!

**Comment by romankierzkowski** [comment]
+1

**Comment by Potseluiko** [comment]
+1

**Comment by bencpeters** [comment]
+1

**Comment by alexeden** [comment]
+1

**Comment by dinu88** [comment]
Will this be implemented anytime ?

**Comment by gkalpak** [comment]
It will be in 1.6.x (not sure about 1.5.x). You can track #13273 as well.

**Comment by qstrahl** [comment]
@gkalpak That's awesome to hear, big thanks to everyone involved :D
