### ISSUE TITLE
Make $routeProvider redirectTo injectable

### ISSUE THREAD

**Issue by jr314159** [angular/angular.js#5150]
I would like to add dependency injection support for the ```redirectTo``` function, but I can't see a way to implement this without breaking the existing API.  

I frequently need services available when determining where to redirect, and as a workaround, I end up defining routes with empty templates purely for handling redirect logic, and calling ```$location.path()``` from within a resolve function on that route.  It seems messy and would be much nicer to just keep this logic contained inside ```redirectTo```.

Would this be welcome as a PR and if so, any suggestions on implementation so as to avoid breaking existing code that expects normal function parameters on this method?

**Comment by basvanmeurs** [comment]
jviotti, great idea. I used your workaround but I think you should change the event to '$routeChangeSuccess' because otherwise 'resolve' functions won't be run. You usually need these resolve functions to run in case of a dynamic redirection (at least, I did need the dependencies to load to be able to make a redirection decision)

**Comment by rinatio** [comment]
+1

**Comment by christian-kocke** [comment]
+1

**Comment by sgwatgit** [comment]
+1

**Comment by syrianadus** [comment]
+1 THANKS

**Comment by se3000** [comment]
+1

**Comment by tmgarcia** [comment]
+1

**Comment by petebacondarwin** [comment]
How about we add a new option to the route config called `resolveRedirectTo`?
This would be an injectable function that could return a promise to a redirection path.

**Comment by gkalpak** [comment]
What's wrong with using `$location.path(...)` in `resolve` (as suggested by @worldspawn in https://github.com/angular/angular.js/issues/5150#issuecomment-33544838) ?

Here is a (kind of bloated) [example][1]. The interesting part is:

```js
$routeProvider.
  otherwise({
    resolve: {
      _: function ($location, User) {
        return User.
          isAuthenticated().
          then($location.path.bind($location, '/admin')).
          catch($location.path.bind($location, '/guest'))
      }
    }
  });
```

[1]: http://codepen.io/ExpertSystem/pen/OyVzxv?editors=101

**Comment by petebacondarwin** [comment]
@gkalpak that is a perfectly reasonable and effective workaround. I like it.

So the question is, is this good enough (and intuitive enough) or do we need to add some sugar?

**Comment by gkalpak** [comment]
Just to have a reference, we are talking about:

```js
otherwise({
  resolveRedirectTo: someInjectableFn(someDep) {
    return someDep.getPathPromise();
  }
})

// vs

otherwise({
  resolve: {
    _: someInjectableFn($location, someDep) {
      return someDep.getPathPromise().then($location.path.bind($location));
    }
  }
})
```

It's intuitive enough for me, but probably not so for people less familiar with all involved concepts (`$routeProvider.resolve, $location).

That said it falls well under the _"can be done as an external module"_ category.
Then again, `ngRoute` isn't in the core either. Puzzling... :P

--
BTW, here is [some sugar as external module][1]. Now you can just write:

```js
$routeProvider.
  ...
  otherwise(RESOLVE_AND_REDIRECT(myInjectablePromiseReturningPathGetter));
```

[1]: http://codepen.io/ExpertSystem/pen/OyyMXj?editors=001

**Comment by alakratt** [comment]
@worldspawn why would that be in the otherwise? Probably I'm missing something. Not doubting your approach, the code works great but I'm using it in specific routes atm.

**Comment by gkalpak** [comment]
@alakratt, there is no specific reason - it's just an example.
(I used `otherwise`, because that is where `redirectTo` is used most of the time.)

**Comment by petebacondarwin** [comment]
Can we document this approach in the `ngRoute` docs and then close this issue?

**Comment by alakratt** [comment]
@gkalpak Got it. Thanks for clarifying!

**Comment by gkalpak** [comment]
@petebacondarwin, now that `redirectTo` stops processing of the current route, the `resolve` approach isn't exactly equivalent to an injectable `redirectTo` function. Should we add an actual injectable `redirectTo` (e.g. `resolveRedirectTo`), instead of documenting ?

**Comment by petebacondarwin** [comment]
OK.  It's a shame that just making redirectTo injectable would be a
breaking change

**Comment by gkalpak** [comment]
Indeed :disappointed:

`resolveRedirectTo` should also support asynchronously determining the redirection path (i.e. returning a promise and deferring further route processing/redirecting until it is resolved, right ?
`resolveRedirectTo` == `redirectTo` + di + async

**Comment by petebacondarwin** [comment]
Sounds like an interesting solution. Do you want to give it a go @gkalpak ?

**Comment by gkalpak** [comment]
My PR is half-baked :smiley:

**Comment by gkalpak** [comment]
Submitted #14695.
