### ISSUE TITLE
Module dependencies not loading properly. Getting i.e. $animate is not defined in directive even if  $animate was available during factory init.

### ISSUE THREAD

**Issue by whyvez** [angular/angular.js#5154]
angular 1.2.2, angular-animate 1.2.2 in Chrome on Maverick

I have been having issue with using ngAnimate but have found that I can reproduce the issue with ngTouch as well. I have made a very simple "bare-bones" app to make sure I don't have any conflicts with any other js libs and the problem persists. Here is my case:

The following app was scaffolded by yo, I only added the test directive to the app. I have added angular-animate.js script to my html.

````
angular.module('nganimateTestApp', ['ngRoute', 'ngAnimate'])
  .config(function ($routeProvider) {
    $routeProvider
      .when('/', {
        templateUrl: 'views/main.html',
        controller: 'MainCtrl'
      })
      .otherwise({
        redirectTo: '/'
      });
  })
  .directive('test', function ($animate) {
    return {
      restrict: 'A',
      link: function (scope, element, attrs) {
        scope.clickHandler = function () {
          var t = '';
        };
      }
    }
  });
````

````
<div class="jumbotron">
  <h1>'Allo, 'Allo!</h1>
  <p class="lead">
    <img src="images/yeoman.png" alt="I'm Yeoman" test ng-click="clickHandler()"><br>
    Always a pleasure scaffolding your apps.
  </p>
  <p><a class="btn btn-lg btn-success" ng-href="#">Splendid!</a></p>
</div>
````

Here is my issue: (hopefully i'm not doing anything stupid here or I owe you a beer ;)

During the directive initialization (i.e. breakpoint on the return statement of the directive factory function) the $animate service is defined which indicates that the ngAnimate module was loaded and initialized properly. But if I step into the clickHandler which is triggered by a simple ng-click on the directive's element $animate is "not defined"...  I have also duplicated this issue with ngTouch as a test using the $touch service.

I originally stepped into this debug spree when I could get animations working. I could publish the app shortly if you need some solid proof. If I am indeed doing something stupid please provide your beer of choice. ;)

**Comment by Narretz** [comment]
Closing because there was never a demo of the problem, and it seems to be resolved since approx. two years ago :)
