### ISSUE TITLE
ngAnimate: ng-view animation doesn't work in some cases

### ISSUE THREAD

**Issue by kamilkp** [angular/angular.js#5177]
Hi.
I'm using an ng-view transitions with ngAnimate. I have the $routeProvider configured that in default view the ng-view doesn't display anything. I want to achieve an effect: that when a ng-view enters i have a ng-enter transition, and when it leaves a ng-leave transition. But when it switches between view i don't want any transitions.

See this fiddle for the example app: http://jsfiddle.net/p7mfU/1/

I achieved this effect by adding a :only-child css pseudo class selector to transition classes. The above example only works when you "Run" the fiddle, and switch between "no view" and "view 1" or "no view" and "view 2". But when i switch from "view  1" to "view 2" (or the other way around) it breaks, i.e. when i then click "no view" there is no transition.

Replacing line 886
```
var data = cacheKey ? lookupCache[cacheKey] : null;
```
in angular-animate.js with
```
var data = null;
```
fixes the issue. 

Try to comment
```
<script src="http://code.angularjs.org/1.2.2/angular-animate.js"></script>
```
and uncomment
```
<!-- <script src="http://kamilkp.co.nf/angular-animate.js"></script> -->
```
in CSS jsfiddle section to see the effect.

**Comment by Narretz** [comment]
The original example now works in 1.4.7: http://jsfiddle.net/p7mfU/5/
