### ISSUE TITLE
$resource nesting response 'data' attribute

### ISSUE THREAD

**Issue by joseandrespg** [angular/angular.js#5245]
Hi,

In Resource when I do a request and I have a response (with a HTTP code error) as:

    {"status":"409","data":{"error":"system_error"},"errorCode":409}

The error callback is returning this response object:

    config
    data
    -> data
    ->-> error: "system_error"
    ->errorCode: 409
    ->status: "409"
    headers
    status 409

As you can see the object returned an incorrect nesting if I want to access "response.data.error" property I need to do "response.data.data.error".

**Comment by joseandrespg** [comment]
:O Sorry I miss this for what a long time!

And yes, this is not a bug. But is difficult to understand why the server response has been manipulated in a different way in both callbacks.

So, closing this issue now.

**Comment by sanskith** [comment]
Hi,

I am using ngResource to communicate with RESTful web services. Below is the code that I am using.

angular.module('medicineService', [ 'ngResource' ]).factory('Medicine',
		function($resource) {
			return $resource('rest/medicines/:medicineId', null, {

				'get' : {
					method : 'GET'
				},
				'save' : {
					method : 'POST'
				},
				'query' : {
					method : 'GET',
					isArray : true
				},
				'remove' : {
					method : 'DELETE'
				},
				'delete' : {
					method : 'DELETE'
				},
				'update' : {
					method : 'PUT'
				}
			});
		});

I am able to call GET and POST on Medicine service but getting 409 error on PUT method.

Please help me where I am doing wrong.

**Comment by gkalpak** [comment]
It's probably a server configuration issue. Not related to Angular.

**Comment by sanskith** [comment]
I am getting this error in browser console not at the server side

**Comment by gkalpak** [comment]
Still :smiley: It's the respinse from the servet that gets logged in the browser.

**Comment by Shawn-Cao** [comment]
@sanskith, To verify the issue comes from server, you can use tools like Postman to make same request to your server API
