### ISSUE TITLE
Inconsistent behavior of $q notify

### ISSUE THREAD

**Issue by torifat** [angular/angular.js#5277]
I have opened an issue in the original Q repo too. Angular implementation also has the same problem.

kriskowal/q/issues/445

**Comment by lgalfaso** [comment]
with https://github.com/kriskowal/q/issues/445#issuecomment-35825749, it looks like if we want to stay with `notify`, then we will have to live with this issue. If at a later point in time we want to follow `Q` use of *estimates*, then we should use another issue. At the moment, I think it is ok to close this issue
