### ISSUE TITLE
Support HTML5 contentEditable attribute

### ISSUE THREAD

**Issue by vojtajina** [angular/angular.js#528]
We should do two-way binding even for other elements than inputs, if there is contentEditable attribute.

**Comment by webhat** [comment]
:+1:

**Comment by emilioplatzer** [comment]
+1

**Comment by srikrishnacj** [comment]
+1

**Comment by miclaus** [comment]
+1

**Comment by INHack20** [comment]
+1

**Comment by shakhrillo** [comment]
+1

**Comment by dabush-eliel** [comment]
+1

**Comment by shyamal890** [comment]
+1

**Comment by akshaysinghi** [comment]
:heavy_plus_sign:  1

**Comment by tylercreller** [comment]
+1

**Comment by Synoon** [comment]
+1

**Comment by b264** [comment]
:+1:

**Comment by fengthedroid** [comment]
👍

**Comment by redgenie** [comment]
+1

**Comment by Narretz** [comment]
Hi everyone,
binding to contenteditable is not something we are going to support in core:
- handling contenteditable in a robust and comprehensive way is very complex
- Official support would take away a lot of resources from the (small) team that is handling AngularJs 1.x nowadays. 
- However, even with a larger team, contenteditable would be a huge project that would demand constant attention
- We would have to duplicate / include a lot of code that has already been written by others that handles the various browser differences and quirks.
- "binding to contenteditable" is not a clearly delineated concept. Support for "simple" binding will grow bigger as browser differences need to be handled, and might raise demand for complete WYSIWYG / rich text editors

Fortunately, there are already projects that handle contenteditable and rich text editors, some that are wrapped to integrate with Angular, and some that are specifically written for it. I didn't have time to test all projects, I just want to highlight[ textAngulars](https://github.com/fraywing/textAngular) taBind directive, which handles "simple" contenteditable two-way binding with ngModel. This is as far as I can say the scope of this issue: no fancy editor, but simply a way to have a robust contenteditable that handles different input techniques and browser differences. I've created a plunker that shows a simple contenteditable that has been enhanced with taBind: http://plnkr.co/edit/kKPfk0LCXWrMpZ1gkblb?p=preview (textAngular also provides a full editor if you need one).
