### ISSUE TITLE
Document timeout behavior of $http

### ISSUE THREAD

**Issue by martinburger** [angular/angular.js#5291]
There is no documentation for the concrete timeout behavior of `$http`. For instance, there is no specification for the arguments passed into the `error` callback in the case of a timeout. It seems that the status would be `0`, but it is not described anywhere.

**Comment by nosus** [comment]
happen to see this old post, but I think the status return from a timeout is -1?

**Comment by Narretz** [comment]
We now provide the xhrStatus as text in the response, which is documented and should help with these issues.
