### ISSUE TITLE
Override mouseDown with touchstart

### ISSUE THREAD

**Issue by rtimothy** [angular/angular.js#5334]
It would really be helpful and awesome if there was a directive for touchstart, even better would be if mousedown would overridden with touchstart just like touch does for click.

**Comment by JimTheMan** [comment]
So how can you listen for "mousedown" equivalent event in ngTouch?

**Comment by Narretz** [comment]
Messing with the touch events isn't something that should be in core, in fact we even removed the NgClick touch / mousedown override, so let's close this. Hammer.js and FastClick are still around for people who need touch specific handling (not to mention ionic does it on its own for hybrid apps)
