### ISSUE TITLE
limitTo filter should have a left and right bound.

### ISSUE THREAD

**Issue by xieranmaya** [angular/angular.js#5355]
using like this:
`{{'abcdefg' | limitTo:2:5}}`
output:
`cde`
useful when paging sth..

**Comment by remisb** [comment]
+1 for new slice filter, but here coms few questions. 

Should it follow:
a)  javascript array slice arr.slice([begin[, end]]) 
b) php array_slice(int $offset [, int $length = NULL]) and  string substr ( int $start [, int $length])
c) python has great slice(start, stop, [,step])  https://docs.python.org/2/library/functions.html#slice

**Comment by pkozlowski-opensource** [comment]
So, we should land some form of this simple but very often used filter. Reading through various issues / PRs opened for this topic I think that we've got few simple decisions to take: 
* [ ] - should we extend the existing `limitTo` filter or introduce a new one?
* [ ] - if we introduce a new filter what should be it's name and API?
* [ ] - if we introduce a new filter should we depreciate / remove the `limitTo` one?

My take would be to introduce a new `slice` filter with the API matching the JavaScript one as it:
* does the job and is familiar to JS developers
* works for both [arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) and [strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice)

Does anyone objects to the above plan? How do people feel about depreciating / removing the `limitTo` filter? I'm going to raise this during the team meeting tomorrow so it would be great to have feedback from the community.

**Comment by jlmagee** [comment]
@pkozlowski-opensource Introduction of a new slice filter and leaving limitTo alone seems right to me

**Comment by pkozlowski-opensource** [comment]
@jlmagee the slight problem with leaving both `limitTo` and `slice` is that the impl of the 2 would be almost identical so we would be duplicating bytes for nothing. But maybe we can make one filter calling the other, to be seen.

**Comment by mgcrea** [comment]
Would love a new slice filter matching the JS API. I don't really like the idea of having redundant filters, so `limitTo` should ideally be deprectated. But there is so many examples out there using it that it might be best to leave it as it is, just maybe flag it as an alias in the docs.

**Comment by pkozlowski-opensource** [comment]
Thnx for the input @mgcrea. Yup, there might be slight perf impact (one more function call), but not sure if it would matter in practice. The other idea of making it easier on people:
* depreciate `limitTo` in 1.4 and only remove in 1.5
* remove in 1.4 and publish a compatibility module

**Comment by stryju** [comment]
:+1: for
> remove in 1.4 and publish a compatibility module

**Comment by jamm** [comment]
removing `limitTo` is terrible idea! it's breaking change just because somebody likes how new word (`slice`) sounds - I can't believe you can be so irresponsible! Thousands of projects will be forced to spend thousands of man-hours just because `mmm... you know... slice sounds more suitable for this case`. You already can do filter with limit and offset and just for syntax sugar you want to add breaking change? I can't understand your motivation and not sure you understand consequences.

**Comment by pkozlowski-opensource** [comment]
@jamm the current `limitTo` filter doesn't do what `slice` does. So it is not about finding a different name for the same thing. And hey, naming things [is important](http://martinfowler.com/bliki/TwoHardThings.html)

BTW: it would be really great if we could focus on the technical merits pros & cons and tune down the language a bit - calling people irresponsible in the very moment  when we are reaching out to the community for feedback sounds odd...

**Comment by jamm** [comment]
@pkozlowski-opensource so add argument and it will. If you want to add breaking change just because of naming - it's irresponsible. If you want to hear only positive feedback, without criticism - it's naive expectation. I'd glad to be less mean, but if we all will keep silence just to be "polite", breaking changes like this will ruin trust to Angular API at all.

**Comment by pkozlowski-opensource** [comment]
@jamm not sure why are saying that this change is only about a name... The crux of the "problem" is that:
* `limitTo` filter only accepts one argument (limit)
* proposed `slice` should accept 2 arguments (start and end index, as in JS)

So the 2 are functionally related but not the same. Could you please elaborate what you mean by:
>  You already can do filter with limit and offset and just for syntax 

Are you referring to `collection | limitTo:start | limitTo:-offset` or something else?

**Comment by jamm** [comment]
@pkozlowski-opensource but if you will add second argument to `limitTo` filter, it will not break anything and will work. It's even proposed by author of this thread :)

> Are you referring to `collection | limitTo:start | limitTo:-offset`
 
yes, but it's not so important. I agree `limitTo:2:3` looks shorter and more handy, I only arguing about breaking change, nothing more.

**Comment by pkozlowski-opensource** [comment]
@jamm ok, cool, I think I got all your answers to my [previous questions](https://github.com/angular/angular.js/issues/5355#issuecomment-71373227). Thnx for the feedback!

**Comment by Narretz** [comment]
So basically, if I use `limitTo:2:3`, then it behvaes like a normal slice filter? Sounds good to me. We could also alias `slice` to `limitTo`, althought that has no precedent.

**Comment by pkozlowski-opensource** [comment]
Guys, we are leaning towards merging https://github.com/angular/angular.js/pull/10899 - if anyone is interested in this feature it is time to speak up now

**Comment by pkozlowski-opensource** [comment]
Woooohaaa! One of the most voted (and easiest to fix!) issues just got solved :-)

**Comment by revolunet** [comment]
:+1:

**Comment by tameraydin** [comment]
nice! it was my first contribution:)

**Comment by Hendrixer** [comment]
nice

**Comment by reissr** [comment]
:+1:
