### ISSUE TITLE
Feature: apply directive to node without re-compiling

### ISSUE THREAD

**Issue by caitp** [angular/angular.js#5366]
Based on this (from @OliverJAsh)

> i have a directive which should add the `contenteditable` attribute to the element when it is compiled. i then have a `contenteditable` directive. however, adding the attribute dynamically means the contenteditable directive never gets linked https://gist.github.com/58a46c8e06cc3c3b528b

I was thinking it might be cool to let people apply directives to nodes (which were possibly already compiled) without recompiling the entire thing.

Now, clearly you'd have to be careful with an approach like that, but it seems like it could be useful in certain cases.

I'm not sure if this is a use case worth supporting, but I think it might be something to look at, and I could probably put together an initial implementation if it seems like something worth haing.

I do realize fully well that this sort of issue really belongs on the mailing list.

**Comment by Narretz** [comment]
This is out of scope at this point of AngularJS development, as it would require considerable re-engineering. It would also be quite a radical deprature from core AngularJS principles.
