### ISSUE TITLE
ngViewController to fix controller as issues for $route

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.js#5383]
I'm not keen on the way controller as syntax affects route definition and expressions in views. The disconnect between the two is annoying.

On the other hand defining controller in the template is not ideal because it delays the controller constructions until the template is fetched - (if defined via route definition this currently happens in parallel with the request to the template and enables async route resolution via the resolve property of the route definition object).

we could however create a directive that would just grab the controller from the current route and publish it onto the scope:

```
.when('/foo', {controller: 'MyController'})
```

```
<div ng-view-controller="myController">
  {{myController.foo}}
</div>
```

`ngViewControllerDirective` would simply do: `$scope[attr.ngViewController] = $route.current.controller;`

**Comment by petebacondarwin** [comment]
I think that we are now at a point where `controllerAs` and the linkage between the route definition and the template is well accepted. Also given that we have a new Router on the way, I don't think that we are going to make this change.
