### ISSUE TITLE
Keep interpolation information in DOM so that bootstrapping from prerendered html is possible

### ISSUE THREAD

**Issue by dai-shi** [angular/angular.js#5406]
I hesitated to submit this issue, since it may be not for many people.
(and because it will be done by angular.js itself in the future. cf. #2104)

[connect-prerenderer](http://github.com/dai-shi/connect-prerenderer) is one of my projects, which allows to prerender html pages with angular.js on server side, and even bootstrap angular.js from the prerendered pages.

One of the biggest problems is how to keep interpolation in prerendered pages.
For example, `<div>{{name}}</div>` will be replaced with `<div>John</div>`,
but `<div ng-bind-template="{{name}}"/>` will be replaced with `<div ng-bind-template="{{name}}">John</div>`, at compilation.
The latter form allows to bootstrap from it, whereas the former does not.

My hack was to patch angular.js so that it keeps interpolation information in DOM and allows boostrap from a prerendered page.
The patch for angular-1.2.5 is [here](https://github.com/dai-shi/connect-prerenderer/commit/32d8003b857abb13bb02fb5cfbee771efeca47a8#diff-730e612c33000dc848a26bdf2443340e)

However, I don't feel like I did it in a very nice way.
It would be really nice if angualr.js includes this functionality (not this patch) and
keep interpolation information in DOM (might be as comments?)

**Comment by mhogerheijde** [comment]
+1

I know this is quite an old issue, but I am looking for this exact thing to be solved.

**Comment by Narretz** [comment]
This is out of scope at this point of AngularJS development, as it would require considerable re-engineering. The new Angular supports server side rendering, and hydration of server side rendered templates.
