### ISSUE TITLE
Support expressions on ng-switch-when

### ISSUE THREAD

**Issue by leog** [angular/angular.js#5409]
I tried myself to do this and I was able to implement it but I couldn't make the test to work. Please refer to this Stackoverflow question: http://stackoverflow.com/questions/20482653/testing-angularjs-scope-variables

**Comment by lgalfaso** [comment]
This is not going to happen, the main reason is that allowing expressions into ngSwitchWhen will requiere a watch on the expression, and this defeats the entire purpose of ngSwitchWhen

**Comment by adambuczynski** [comment]
> This is not going to happen, the main reason is that allowing expressions into ngSwitchWhen will requiere a watch on the expression, and this defeats the entire purpose of ngSwitchWhen

What about interpolated values which are resolved once (and not watched)? E.g.:

```html
  <p ng-switch-when="{{errors.courtNotAvailable}}"></p>
```

I have string constants in my errors object and want to use those strings to match against with ng-switch-when. Is this not possible?

**Comment by greymind** [comment]
Yeah, would be awesome to have just once-resolved values. Similar use-case for me.

**Comment by tsemer** [comment]
Also useful for supporting TypeScript enums exposed via controller

**Comment by StatikVerse** [comment]
Even an NgIf/NgElse would solve this, I think.
