### ISSUE TITLE
Mock httpBackend does not support blobs for passThrough.

### ISSUE THREAD

**Issue by michaelkrog** [angular/angular.js#5415]
I have tried to use the Mock httpbackend with passThrough for some audio files retrieved from a server.

It works fine when not using the Mock httpBackend, but when I switch to the Mock backend the data returned are not blobs, but strings. The data is there is seems because chrome freezes when debugging and watching the variable - like the data contained in the string is just to big for it to handle.

The way I use $http is like this:
```Javascript
$http({method: 'GET', url: url, responseType: 'blob'}).success(...);
```

**Comment by brphelps** [comment]
Is this fix being deferred for some reason?
