### ISSUE TITLE
1.2.5 angular-mocks copy change breaks tests using XML datatype 

### ISSUE THREAD

**Issue by matthughes** [angular/angular.js#5429]
Apparently the XML datatype in Chrome/Firefox (and others?) contains pointers to itself.  The change here (https://github.com/angular/angular.js/commit/f69dc16241c8b631123ad0b09674f0a5e0ff32fe) copies the HTTP response.

If you are mocking an HTTP service with XML datatype as the return type, copy() never terminates.

**Comment by petebacondarwin** [comment]
`angular.copy` now handles cyclic structures (from 1.4.1 onwards - see https://github.com/angular/angular.js/commit/0e622f7b5bc3d5d0ab0fbc1a1bc69404bd7216d5) so I think we can close this.

**Comment by petebacondarwin** [comment]
Oh but I just realised that there are two issues here. The cyclic one is fixed. The XML one is not.
I'll knock up a PR for the XML fix using @matthughes commit https://github.com/matthughes/angular.js/commit/205637e15ee863a39bf5840f16ed422ffd0def72.
