### ISSUE TITLE
angular 1.3 suggestion: adopt angular.js to work with modular loaders (amd and commonjs like browserify.js)

### ISSUE THREAD

**Issue by rnikitin** [angular/angular.js#5474]
Actually we can make the modular extension by our own, but we still need a support of noConflict() function.

And according to the sources there are a lot of hard links to window.angular instead of shorthand $angular which causes bugs when we are trying to make noConflict() function.

So, would be great to have this hard links fixed and working noConflict() function and would be ideal to have angular fully modular compatible with AMD or browserify/commonjs.

My +1 here.

**Comment by Narretz** [comment]
This should work since https://github.com/angular/angular.js/commit/c5686c5271b4172a4004a8ce34754117807a816a
