### ISSUE TITLE
errors.angularjs.org fails on long urls

### ISSUE THREAD

**Issue by drewpca** [angular/angular.js#5476]
I got an error url that was 18k chars long, starting like this:
http://errors.angularjs.org/1.2.5/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A%20function%20()%7Be%3Dh(c)%3Bvar%20a%2Cb%3Bif(U(e))if(pb(e))for(d!%3D%3Dl%26%

That made an error page saying:
414 Request-URI Too Large
nginx

It would be nice if your server let that through to be rendered as an error page. The error page might want to truncate the long string. It would also be ok if the error url _generator_ truncated giant strings.

**Comment by leegee** [comment]
:+1:

**Comment by txavier** [comment]
+1

**Comment by megabyzus** [comment]
+1

**Comment by rossigee** [comment]
To be honest, whoever thought it would be a good idea for AngularJS errors/stacktraces to be produced as ridiculously long, URL-encoded (not readily human-readable) strings, that link to a single site ('errors.angularjs.org') that is *not configured to handle long URLs* - ought to be shot. Even if you're lucky enough to get a short-enough URL that the site *will* display, this still relies on you having an Internet connection to figure out what's wrong with your code! <facepalm>

**Comment by rossigee** [comment]
So, has anyone found a workaround for this they can share? I have hit this again today and *still* can't determine the cause of the latest error.

**Comment by rossigee** [comment]
In case it helps anyone else, the only way I've found so far to stop the injector from calling the broken 'minErr' function is to actually remove the 'try...catch' block from the 'angular.js' file, and have my application use the non-minified version temporarily. The error logged to the console is simple, concise and tells me exactly what I was missing.

The 'minErr' approach is bloated, complex, unnecessary and clearly broken. Just remove it and stop wasting people's time!

**Comment by Narretz** [comment]
The max url length will be made configurable (and capped to something sane) in the near future: https://github.com/angular/angular.js/pull/15707

**Comment by DustinJSilk** [comment]
Absolutely ridiculous. Still the worst decision ever made, ever!
I cant believe i have to even Google this issue when regular error logging works just fine and then they could link to the page with the description about it afterwards if they really wanted to.

:(
