### ISSUE TITLE
Optimized production release: without try/catch statements (feature request for 1.3)

### ISSUE THREAD

**Issue by g00fy-** [angular/angular.js#5506]
It would be awesome if we could have a version of angular that would be optimized for production (similar to how ember does it) by removing some parts of the code that are only for debugging purposes and are useless if the app runs fine.

I suppose change like that would bring much performance gains since dev tools profiler says JIT can't optimize some expensive functions i.e. `$apply`, `$digest` or `nodeLinkFn` -  `Not optimized: TryFinallyStatement`/`Not optimized: TryCatchStatement`

**Comment by petebacondarwin** [comment]
Closing as such a configuration would cause the application to run differently in "production" mode and potentially kill the application if an error was thrown.
