### ISSUE TITLE
$resource doesn't provide any options to transform/serialize parameters when calling an action.

### ISSUE THREAD

**Issue by Sean-Der** [angular/angular.js#5521]
I am using $resource heavily, and am having a hard time finding a way to serialize params when calling actions. I can transform the body with transformRequest, but there is no facility like this for params.

Right now https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L416  just sets the values, and it would be nice to have a way to just case off of the type!

My use case is that I pass dates when calling .query, and I don't want to implement a service OR replace toString on my dates.

I have this implemented on a personal project, but is this something that would be welcomed to angular? If so, how would you like it implemented?

A.) Do you want the function to operate on all params, or serialize one at a time.
B.) Do you want this custom function to handle JUST serialization, or should it take over building the query string as well.

I would really like to fire off the pull request myself, seems like a good start to get involved.

**Comment by yordis** [comment]
:+1: 
This was in Oct 3, 2014. Today, Jan 26, 2015 still without at least response about it. I am using Angular 1.2.26 and hopefully upgrade to 1.3 and I need this feature too. I am building some application who needs a lot of dates in the URL so is a pain to do it without something like this ... I can patch, I can create my own module but we need that in the core.

@btford @caitp someone, @Sean-Der did a pretty good job, testing and updating the documentation so I don't see the problem with this PR.
