### ISSUE TITLE
Moving aliasing special properties of ngRepeat from ngInit to ngRepeat

### ISSUE THREAD

**Issue by vucalur** [angular/angular.js#5623]
Currently the only one appropriate use of [ngInit](http://docs.angularjs.org/api/ng.directive:ngInit) is aliasing `$index` and [other special properties of ngRepeat](http://docs.angularjs.org/api/ng.directive:ngRepeat#description).

I'd like suggest moving this functionality to ngRepeat.
It could look like:

    <li ng-repeat="city in cities track by $index, $index as cityIndex, $middle as isCityMiddle">

### Pros:
* Aliasing is needed for ngRepeat, not ngInit.

### Cons:
* Will add more functionality to ngRepeat.  
Right now it's one of the biggest directives if LoC is concerned.

Also, just to make writing hello-worlds on plunker a little tougher, removing ngInit entirely could be considered.
Yes, I know I'm crazy, but this could be only done if there are really few hackish solutions which employ ngInit.
Just wanted to know that you guys think of this.

**Comment by petebacondarwin** [comment]
I don't think we should be changing or removing `ngInit`. It is there and it does a few jobs well, even if it can be abused. Moreover, I now agree with @gsklee that we should moderate the tag line in the docs to something not quite so severe.

Regarding `ngRepeat`, I am torn...

**Comment by petebacondarwin** [comment]
Adding these extra clauses to the `ngRepeat` expression is adding too much burden to an already overburdened syntax. For now I think we should stick with `ngInit` and make the note about it in the docs a bit clearer.

**Comment by petebacondarwin** [comment]
Changed the note in the `ngInit` docs: 010d9b6853a9d2718b095e4c017c9bd5f135e0b0
