### ISSUE TITLE
Exception 'App Already Bootstrapped with this Element' is thrown even when element hasn't been bootstrapped

### ISSUE THREAD

**Issue by paolodm** [angular/angular.js#5653]
Getting this error:

Error: [ng:btstrpd] App Already Bootstrapped with this Element

This is even though I haven't `angular.bootstrap` yet.

This commit comment will give more context:

https://github.com/angular/angular.js/commit/3ee744cc63a24b127d6a5f632934bb6ed2de275a#commitcomment-4246366

**Comment by panwenchao** [comment]
I am doing chrome extension Development, I also encountered a similar problem, how to solve?

**Comment by petebacondarwin** [comment]
It seems that if you use manual bootstrapping only, do not use `ngApp` and also use `ngNonBindable` then it is possible to workaround this.

**Comment by NickHeiner** [comment]
Yeah, in any event, I'd say this is old enough to close. The issue may not even exist with modern versions of Angular.
