### ISSUE TITLE
Allow providers in resolve routing

### ISSUE THREAD

**Issue by marcalj** [angular/angular.js#5683]
There's some StackOverflow and GoogleGroups discussions about this:

https://groups.google.com/forum/#!topic/angular/QtO8QoxSjYw

http://stackoverflow.com/questions/16711637/angularjs-routeprovider-resolve-calling-a-service-method
http://stackoverflow.com/questions/18341584/angular-routeprovider-resolve-not-called

Route resolve should accept providers as are not singleton, and can return dynamic data based on route params.

This seems a basic functionality to me. Thanks!

**Comment by Narretz** [comment]
As the SO answers describe, this is definitely already possibly (although not super straightforward)
