### ISSUE TITLE
ng-repeat emit event on complete

### ISSUE THREAD

**Issue by uehondor** [angular/angular.js#5768]
It would be supercool to have the ng-repeat emit an event to notify listeners when it starts and finish rendering.

**Comment by karamfil** [comment]
+1

**Comment by Narretz** [comment]
As the  more broad concept of emitting events after the view finishes, this has been discussed and decided against here: https://github.com/angular/angular.js/issues/734

**Comment by gaojianzhuang** [comment]
+1
