### ISSUE TITLE
Support "new instance" injection without the use of factories. 

### ISSUE THREAD

**Issue by Davidhanson90** [angular/angular.js#5826]
There appears to be no way to tell AngularJS to create a new instance of a type on each injection. Using factories are not ideal as require an invocation to instance the type. 

It would be good if you could support this injection type which is the standard injection pattern in a large number of IOC containers.

**Comment by Narretz** [comment]
Looks like this is a very uncommon request - probably because the pattern is possible, even though inconvenient.
