### ISSUE TITLE
perf(Scope): watcher deduplication

### ISSUE THREAD

**Issue by kseamon** [angular/angular.js#5829]
scope.$watch('foo', function() {do.this()});
scope.$watch('foo', function() {do.that()});
scope.$watch('foo', function() {do.theOther()});

At present, this would add three dirty checks to the digest cycle.  Since they are all watching the same scope expression, we could instead add one dirty check that fires all three change functions as appropriate.

The impact of this change should probably be tested before committing it.  It might not be worthwhile in practice.

**Comment by Narretz** [comment]
Same idea with a bit more discussion: https://github.com/angular/angular.js/issues/13731
