### ISSUE TITLE
FeatureRequest: support for ordered initialization of an angular app with asynchronous data

### ISSUE THREAD

**Issue by leifhanack** [angular/angular.js#5854]
Hi there, 

again and again I see people asking for a solution to do things after the app is initialized. 

E.g. this [latest thread](https://groups.google.com/forum/#!topic/angular/V3IMon_LdiI) or this [thread](https://groups.google.com/forum/#!topic/angular/6CxwIL4QSfY/discussion) which we created. 

We have had the same issue and solved it with a 'init-service'. Here is the [sample init service](https://github.com/hypoport/angularjs-initservice) and it's [detailed documentation](http://blog-it.hypoport.de/2013/10/28/angularjs-ordered-init-async-promise/).

It would be awesome if we have a build-in support for this reoccurring request. Or should it be sufficient to use the routeprovider and it's resolve block?

Regards, Leif

**Comment by Narretz** [comment]
This is trivial with `ui.router`, which should probably be used by most bigger projects.
With ngRoute you can define a general resolve that all your routes use. While not as comfortable, it does the job as well.
