### ISSUE TITLE
Making templateUrl hit different end-points or modifying it programmatically?

### ISSUE THREAD

**Issue by cesarandreu** [angular/angular.js#5867]
# Problem

I want to use third party directives that allow me to customize their template. But the folder structure in the templateUrl might be completely different. For example:

Templates in my app might be organized like this:
`/templates/name/name.html`

But templateUrl in ui-bootstrap looks like this:
`template/name/name.html`

However, it's not just limited to this one use-case. As you start adding on more libraries it's very likely tons of people will have different url patterns. And since I'm using bower for everything, I can't just edit the file locally.
## Idea

It'd be cool if I could do something like this multiple times for each library:

```
myModule.config(function($templateProvider){
  var from = 'template/**/*.html'
  var to = '/templates/**/*.html'
  $templateProvider.route(from, to);
});
```

(Not sure of the best way to do this. I think globbing makes sense.)

The idea is that this would allow me to set something up in my application's config or run block. And it would function both in production and development as if I used the same folder structure. 

If I decide I want to embed these templates with $templateCache, I can just use my normal URL and it'll work, I won't have to change my build step, I can change configuration inside my app. Every time I add on a library, if it uses some weird folder structure for their templates, I can just add a config block. 

It seems like it should be something part of the AngularJS core. Perhaps there's a better solution, or it's already in the works, or it's solved already! I'd love to know.
## How to approach the problem?

Maybe you can change the templateUrl of a directive in a config or run block? The $compile file is 2,000 lines long, so it's not an easy read :(. And I'm not certain where or how I could hook into it.

Another alternative could be building this outside of core. I'm guessing one could make an http interceptor for .html files that does what I wrote on top. It'd also have to add a decorator on top of templateCache to function with embedded templates. 

I'd be interested in looking into this if someone would point me in the right direction. 
## Extra comments

This is solvable with Grunt by just specifying that it should take some files and place them as certain strings in $templateCache. It's annoying for development, though.

Another way to solve this is pulling in the file locally and modifying the templateUrl. But then you can't take advantage of package managers like Bower. 

It seems like similar issues would be encountered with [Polymer-Project](www.polymer-project.org). If a lot of people make "directives" that allow customizing their HTML, and distribute them, it'll basically fall into this same issue. Do they have this problem solved? I'll admit I haven't looked at Polymer in depth.

**Comment by Narretz** [comment]
You can use a http request Interceptor to change the url on the fly.
