### ISSUE TITLE
feat(directive): Add ability to inject required controllers into the controller function

### ISSUE THREAD

**Issue by maklemenz** [angular/angular.js#5893]
**quick overview**
You have the directives A, B and C
B requires A, 
C requires B

The methods in C need to call methods in the controller of B.
The methods in the controller of B need call methods in the controller of A.

The controller of B cannot know the controller of A because it can only be passed into the link-function of B.

**more details**
http://stackoverflow.com/questions/21231294/angularjs-inject-required-directive-controller-into-the-controller-instead-of-t/21231428

Actually there is a workaround that is too complicated for such an easy problem.

Even the ngModelController does use another workaround with a feature that seems to be undocumented: the binding of directive controllers to the directive-elements data property:
https://github.com/angular/angular.js/blob/5adea0ba64b758f8f5700da73f6faca8ae1983be/src/ng/directive/input.js#L969

**Comment by thorn0** [comment]
> I feel like that is a reasonable api and it doesn't complicate the DDO further.

Actually, it simplifies the DDO. Compare the two snippets I wrote above.

**Comment by ewinslow** [comment]
@kentcdodds see #2095

**Comment by kentcdodds** [comment]
@thorn0, I was referring to it making the DDO more complex for `module.directive` users, not `angular.component`. Either way :+1:

@ewinslow, I decided against asynchronous directives. There are several reasons it just wouldn't work well.

**Comment by piernik** [comment]
I think that injecting required controller as local is "have to" in new version.

**Comment by SonofNun15** [comment]
:+1:
We are wrestling with this same issue. We try to do very little in link functions because they are harder to test. We tried putting `scope.myController = requiredController` in the prelink function so that the controller of the required directive would be available in the child directive's controller, but it turns out that the controller runs before both the pre AND post link functions, so this isn't going to work.

**Comment by piernik** [comment]
Any news on this?

**Comment by programmist** [comment]
+1.

As a work-around I'm constructing the controller and adding it to the scope within the link function, but that's pretty ugly.  It still beats unit testing link functions though.

**Comment by programmist** [comment]
+1

**Comment by djdmbrwsk** [comment]
+1

**Comment by hardsetting** [comment]
+1

**Comment by thorn0** [comment]
To simplify the implementation, we can introduce a restriction that only the controllers from the element's parents (`^^` and `?^^`) can be injected.

**Comment by ciccia** [comment]
+1

**Comment by abyx** [comment]
:+1:

**Comment by DumboJet** [comment]
+1

**Comment by ifeltsweet** [comment]
+1

**Comment by poshest** [comment]
+1, and also for it to be added to the new .component

**Comment by petebacondarwin** [comment]
@hannahhoward had an interesting take on doing this in https://github.com/angular/angular.js/issues/12342
