### ISSUE TITLE
Enhancing ngSanitize whitelists

### ISSUE THREAD

**Issue by bradyisom** [angular/angular.js#5900]
There needs to be a way to extend the ngSanitize whitelists of elements and attributes. In our project, we need to add additional valid HTML5 elements to the list of valid elements (like `video` and `audio`). We also need to add some of our custom elements to the list.

I am willing to do the work and submit a PR. However, I want to make sure I do it the right way.

I was thinking of adding something similar to `$compileProvider`'s `aHrefSanitizationWhitelist` and `imgSrcSanitizationWhitelist` that manages the `voidElements`, `optionalEndTagBlockElements`, `optionalEndTagInlineElements`, `blockElements`, `inlineElements`, `specialElements`, `uriAttrs`, and `validAttrs` lists within the $sanitize implementation. 

I would probably make them as methods that take an array of additional whitelisted elements or attributes. These would then be used to extend the current whitelists. This could be implemented on `$compileProvider` or on a new provider inside the `$sanitize` module.

Another option would be to make the new methods take the entire whitelist. This would allow the caller to remove some elements or attributes that are already in the existing whitelists. However, the current whitelists would then have to be documented. The caller would also have to pass in the entire existing whitelist with their additions if all they wanted to do was add and element or attribute.

**Comment by saiichihashimoto** [comment]
+1

Is this still being worked on?

**Comment by SyntaxRules** [comment]
+1

**Comment by basco-johnkevin** [comment]
+1

**Comment by vontobel** [comment]
+1

**Comment by jordajm** [comment]
+1

**Comment by hellsan631** [comment]
+1

**Comment by Anaphase** [comment]
+1 I'd love to be able to set my own whitelist. I want to bind HTML with `<span>` tags and nothing else.

**Comment by petebacondarwin** [comment]
Moving to 1.5 - as noted in https://github.com/angular/angular.js/pull/6252#issuecomment-138239948 the solution would be implemented via provider methods.

**Comment by manuel-di-iorio** [comment]
+1

**Comment by cciatti** [comment]
+1
I added it on my own copy but I hate to do that... please add this to the core soon. Also, add a method to extend the attribute list.

**Comment by gkalpak** [comment]
The [PRs plz!] label is there !
Just saying... :stuck_out_tongue:

**Comment by jmanico** [comment]
This is a very critical feature for enhancing security of angular and I would be glad to offer a financial bounty or place to crash in Hawaii where I live for anyone who gets it done...

**Comment by jmanico** [comment]
@bvaughn is there a way to pull this off today, albeit in a non graceful way? If so would you be so kind as to provide an example here? Thank you!

**Comment by bvaughn** [comment]
Sorry @jmanico. No clue. This is pretty far back in my memory and I haven't worked with an Angular 1.x tech stack in over a year. ☹️

**Comment by chris-denning** [comment]
+1

**Comment by jlopezr** [comment]
+1

**Comment by wangfengming** [comment]
+1

**Comment by nikuelias** [comment]
+1
