### ISSUE TITLE
bug: User prevented from scrolling down on page refresh (in Chrome).

### ISSUE THREAD

**Issue by zfarrell** [angular/angular.js#5916]
Hi angular team,

I am experiencing an issue where on page refresh, the user is prevented from scrolling down (unless they first scroll up).

Conditions required to reproduce this:
1. ngView is used to load a template.
2. The content of the page extends past the bottom of the viewable window.
3. The refresh happens from a "pageYOffset" below the viewable window. (i.e. the user scrolled down before refreshing).

**Reproducable:** always
**Browsers:** Chrome 32 (_I'm only able to reproduce in Chrome (32.0.1700.77). Firefox (26.0) and Safari ( 7.0.1) both work as expected_).
**Operating system:** Mac OSX 10.9.1

Apologies in advance, I haven't had time to fully debug this and instead am only able to provide a plunker which reproduces the issue: http://plnkr.co/edit/zLGLBiAoXCM7RejTzzmv

To reproduce (in Chrome 32.0.1700.77):
1. Go to http://plnkr.co/edit/zLGLBiAoXCM7RejTzzmv, and "launch the preview in an external window".
2. Scroll down to the bottom of the page.
3. Refresh page.

**Expected result:**
Window scrolls to bottom of page (or at least, window allows immediate downward scroll).
**Actual result:**
Window is at top of page, and user is unable to scroll down without first scrolling up.

**Comment by Narretz** [comment]
I cannot repro this anymore in Version 45.0.2429.0 canary. The above bug is also marked as fixed.
