### ISSUE TITLE
Add support for ng-options with comprehension_expression supporting (group, (key, value)) object structure

### ISSUE THREAD

**Issue by tomzx** [angular/angular.js#5979]
Hi,

It would be nice if the ng-options comprehension_expression supported the option to iterate through objects such as the following example:

``` javascript
var data = [
    'group_label_1': {
        'value_1': 'label_1'
        'value_2': 'label_2'
    },
    'group_label_2': {
        'value_3': 'label_3'
    }
];
```

which would generate

``` html
<select>
    <optgroup label="group_label_1">
        <option value="value_1">label_1</option>
        <option value="value_2">label_2</option>
    </optgroup>
    <optgroup label="group_label_2">
        <option value="value_3">label_3</option>
    </optgroup>
</select>
```

I'd expect the comprehension syntax (open to debate) to be something such as

```
k as v group by g for (g, (k, v)) in data
```

**Comment by Narretz** [comment]
I'm gonna close this based on the following reasons
- it's not a very common use case
- there are easy workarounds available
- it would further complicate ngOptions
