### ISSUE TITLE
angular-touch breaks click events

### ISSUE THREAD

**Issue by scheffield** [angular/angular.js#6001]
Hi,

**Overview of the issue**:
Without jQuery, all click listeners got an empty ```event``` object if the link is annotated with ```ng-click```.

```
<a data-ng-click="reportClick()" data-test-listen-to-click>Link with directive</a>
```

Leads to:

```
testListenToClick#onClick; event: 
Object {preventDefault: function, stopPropagation: function}
```

**Motivation for or Use Case**
This for example breaks angular-ui-router: https://github.com/angular-ui/ui-router/issues/827

**Angular Version(s)**
1.2.10

**Browsers and Operating System**
Chrome 32 with touch emulation, Chrome Mobile 32

**Reproduce the error**
http://jsfiddle.net/scheffield/55Skr/

**Related issues**
I might be wrong, but this issue looks like it has the same reason: #5307

**Comment by scheffield** [comment]
Today, I stumbled over a solution in this bug: https://github.com/angular/angular.js/issues/9872

The suggested solution is it to update the line containing

```
element.triggerHandler('click', [event]);
```

by

```
element[0].dispatchEvent(new MouseEvent('click', event));
```

A first (quick) run indicates that the provided event object now looks like a full blown MouseClick event. I'm not absolutely sure whether this is the solution but I'm very confident that.

Just a quick roundup on `dispatchEvent` according to http://help.dottoro.com/ljrinokx.php and http://msdn.microsoft.com/en-us/library/ie/ff975247(v=vs.85).aspx it is supported since IE9 (and of course in all other browsers). In particular the first side states:

> [...] the main difference between the dispatchEvent and fireEvent methods is that the dispatchEvent method invokes the default action of the event, the fireEvent method does not.

**Comment by devourment77** [comment]
I am running into this same issue, using an anchor to close drop down nav, but also go to the new state.  Sounds like it is a still an issue.

**Comment by JonWallsten** [comment]
I also have troubles with this. When I add a click listener with jquery in a directive the click only fires if I longpress and let go right before the longpress function fires on my device.

**Comment by omegascorp** [comment]
I think it is related. When add ng-click on submit button. On mobile it will fire only ng-click but will not fire ng-submit. Example and steps to reproduce here:
http://jsfiddle.net/omegascorp/egtaL3x8/3/

It is related to lines 355, 356 in angular-touch.js (https://github.com/angular/bower-angular-touch/blob/master/angular-touch.js)
