### ISSUE TITLE
ngModel(filter): When using phonetic(pinyin) input method, the behaviour is changed. (e.g: Chinese)

### ISSUE THREAD

**Issue by imgarylai** [angular/angular.js#6010]
I found this issue when I use filter in order to implement search. To show the phonetic input method, I recorded the process of Chinese input methods and English input methods as gif. You can see the those file below.

When we use English, the filter is triggered each alphabet typed. There're no problems in English.
![Imgur](http://i.imgur.com/T79vrJT.gif)

However, Principles of zhuyin(e.g: Traditional Chines) input method of general character : select consonant , sound and then rhyme and then select the character desired and press " enter(return) ". 

General principles of pinyin(e.g: Simplified Chinese) input method : input consonant , single vowel and then compound vowel and then select the character desired and press " enter(return) ".

Thus, the behaviour is different from using English. Looks the gif below and you can know what's the different.

In the previous angularjs version, it works fine like using English.
![Imgur](http://i.imgur.com/aahpK0p.gif)

But the latest angularjs version(since 1.2.2), the behaviour was changed. 
![Imgur](http://i.imgur.com/WNQpTap.gif)
> There is a mistake in the image. This issue happened since version 1.2.2, not 1.2.10

As a zhuyin user, It make sense for me when typing Chinese like what previous version angularjs done. Will the behaviour be changed like before? Or Is there any reason the behaviour changed.

Here is an example code on plnkr: 
1.2.1
http://plnkr.co/edit/4T0lhFNzyhSfhLZEidUy?p=preview
1.2.2
http://plnkr.co/edit/QWqS4Jys2sWz8dbI6cd8?p=preview

And actually, I don't know whether it is the filter or the ngModel's issue. This issue also happened in this two-way binding example. 
1.2.1
http://plnkr.co/edit/MijiAdt9FnThCf0Xj0Ox?p=preview
1.2.2
http://plnkr.co/edit/7TirMEXEOJUUIHjJkbAR?p=preview

**Comment by Narretz** [comment]
I think this is expected behavior. When the IME is composing, the model should not be updated.
