### ISSUE TITLE
Add warning message when a module is reset/replaced

### ISSUE THREAD

**Issue by mark0978** [angular/angular.js#6034]
Right now if you do something stupid like

```
foo.js:  angular.module('modname', []).directive(......

bar.js:  angular.module('modname', []).directive(......
```

The second statement wipes the first one from memory without any warning.  It would be good if you could get some clue that something has been done wrong.  Like

```
$log.warn("Module modname is being replaced");
```

**Comment by Narretz** [comment]
Same as https://github.com/angular/angular.js/issues/1779
