### ISSUE TITLE
 ngRepeat iterates over object in alphabetical order

### ISSUE THREAD

**Issue by cztomsik** [angular/angular.js#6210]
This is very unexpected, all major browsers retain order of inserted keys and it is not going to change in any way in future as it would break a lot of existing code. 

No matter of that, angular does it its own "way".

Basically it makes this feature **completely useless** as you can't use it for example for iterating computed averages, and similar great things.

This is major flaw in design and fixing it involves removing **one line**:

    collectionKeys.sort();

Can we at least discuss this? I am highly convinced this (possibly) breaking change should affect minimum people and if orderBy worked on objects too, fixing may be very simple on their side.

**Comment by dustinrjo** [comment]
i really don't care either way on this though I'm more with the +1's but just put it in the documentation!  I shouldn't have spent 2 hours today trying to sift through why my objects are out of order, finding that it wasn't the json serializer on my server, it wasn't expressjs, it wasn't mongoose, it wasn't the browser, it wasn't angular ui-router but it was the core of angular!  I like things that don't break but I like building things fast even more and fixing them when they break if and when my project has the budget for it.

**Comment by petebacondarwin** [comment]
+1 for documenting this in 1.3.10

**Comment by trollboy** [comment]
+1, undocumented "features" that aren't intuitive.

**Comment by petebacondarwin** [comment]
@trollboy this has been documented at 7fab29fbe1606f4d1f00ec38b03c325975a1ee21

**Comment by trollboy** [comment]
Thanks I see that now.  Just the same though, looks like it was out for a while before it was documented (1.3 released in October, this doc change dated 25 days ago) and it isn't very intuitive.  It cost me a lot of time as I was doing server side sorts and finally tried a hail mary of returning an array, as it violates FIFO.  I'm glad it's being removed for 1.4 due out in march.  The only reason I mentioned the lack of documentation and intuitiveness is simply to express the dissatisfaction such causes as to hopefully curtail such in the future.  Thanks!

**Comment by petebacondarwin** [comment]
Actually, I this sorting of keys was the behaviour since before Angular 1.0.0!

**Comment by cztomsik** [comment]
A very unexpected behaviour :-)
But it's already fixed in 1.4, so what's this discussion about anyway?

**Comment by rakeshjuyal** [comment]
@cztomsik I am using 1.3.11 and it is sorting the keys alphabetically. Let me try 1.4 now :+1:

**Comment by jainarpit014** [comment]
+1

**Comment by geoidesic** [comment]
+1

**Comment by niemyjski** [comment]
+1

**Comment by petebacondarwin** [comment]
What are the +1s for? This is fixed in master. It would be a breaking change for 1.3 so it will not be fixed there.

**Comment by niemyjski** [comment]
Maybe people want to see this in 1.5.. Community decides what goes into 1.5 and it looks like they are speaking.

**Comment by pkozlowski-opensource** [comment]
@niemyjski this _is_ part of 1.4 so I'm not sure what is the story with 1.5 and votes.... In other words: this is already fixed in master and part of 1.4 releases....

**Comment by niemyjski** [comment]
odd, I thought I just came across this issue a few hours ago and thus when looking and +1'ed... Maybe it was just an issue with track by that made me think this was happening...

**Comment by kris-o3** [comment]
yep, just noticed that an object i created for a dropdown was being rendered, unexpectedly and quite undesirably, in alphabetical rather than in as-is object order.

**Comment by kmukku** [comment]
+1

**Comment by aegiz** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
@aegiz: https://github.com/angular/angular/pull/2583

**Comment by Narretz** [comment]
I'm going to lock this issue, because this is fixed. To recap:

Starting with 1.4, the keys are not sorted alphabetically anymore. This is documented as a breaking change here: https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-6  Any behavior that might look like the keys are still sorted alphabetically is possibly a different bug (for which you can open a new issue), or a usage error. 

In 1.3.x and before, the keys are still sorted alphabetically, as changing it in these versions would be major breaking change. The docs outline how to work around this problem: https://code.angularjs.org/1.3.16/docs/api/ng/directive/ngRepeat
