### ISSUE TITLE
Filters for nested objects not working

### ISSUE THREAD

**Issue by anirvan-majumdar** [angular/angular.js#6222]
Hi,

I recently changed my applications angular dependency from `1.2.10` to `1.2.12`. And the first thing I observed is that some of the *filters* I'm using for a data table have stopped functioning. A closer inspection revealed that the filters have stopped working for all those properties which are nested one level. 

For example, if the object being rendered for every row is such—

    {  
       p1: "...",
       p2: "...",
       p3: { name: "..." },
       p4: { name: "..." }
    }

Then the filters on `p1` and `p2` work just fine, but those for `p3` and `p4` stopped working.

Reverting the version to `1.2.10` fixes the issue.

**Comment by lgalfaso** [comment]
with https://github.com/angular/angular.js/issues/6222#issuecomment-60473945, this can be closed
