### ISSUE TITLE
Network activity indicator stuck on iOS Mobile Safari

### ISSUE THREAD

**Issue by mrobrian** [angular/angular.js#6233]
Using version 1.2.12 (also saw this issue with previous versions but didn't document which exact versions) I'm seeing an issue when using Safari on iOS 7.0.3 and 7.1 beta.  When a user is browsing a single page app and uses the browser's Back or Forward button, the network activity indicator activates, and the stop/refresh button in the url bar displays as stop.  This makes it look like network activity is pending, but the site has already fully loaded.
To replicate the problem, using iOS Simulator or an iPhone running iOS 6.1 or higher navigate to http://docs.angularjs.org.  Navigate the site by tapping any of the links in the menu on the left, then use the browser's Back button.  Notice the network activity indicator remains visible.
I'm not sure if this is a Safari bug, but it seems to only happen with sites using Angular.

**Comment by Narretz** [comment]
As this is an old issue with no updates, I'm gonna close it. I'm sure if this was a widespread problem, we'd have many more reports about it.
