### ISSUE TITLE
Duplicated style attribute in directive with template and replace: true

### ISSUE THREAD

**Issue by vrutberg** [angular/angular.js#6239]
**Browser:** Chrome
**Component:** $compile
**Regression:** no

Plunkr that demonstrates the problem: http://plnkr.co/edit/UMhmjGS3XW84d7zctujo?p=preview

**Comment by Narretz** [comment]
Basically the same as https://github.com/angular/angular.js/issues/5695
Note that this is unlikely to get fixed, since replace is deprecated.
