### ISSUE TITLE
Async directives lose definition prototype due to implementation of `derivedSyncDirective`

### ISSUE THREAD

**Issue by connec** [angular/angular.js#6262]
If you have a directive definition object with a prototype, some configuration on the prototype is lost if the directive has a `templateUrl`.  E.g.:

```js
var isolateDirective = function isolateDirective() {};
isolateDirective.prototype.scope = {};

angular.module('app').directive('whatever', function() {
  var d = new isolateDirective();
  d.templateUrl = '...';
  return d;
});
```

An element with the `whatever` directive will not have an isolate scope because `compileTemplateUrl` copies only the object properties and not the prototype when creating its `derivedSyncDirective` [here](https://github.com/angular/angular.js/blob/4f84f6b3e4210ae1eb14728a46d43dd961700a0c/src/ng/compile.js#L1684).

Some properties make it across because of the self-assignments around [here](https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L545).

It feels like the most correct fix would be to ensure the `derivedSyncDirective` has the prototype chain that the `origAsyncDirective` has, possibly by making `origAsyncDirective` the prototype of `derivedSyncDirective`:

```js
// https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L1655
derivedSyncDirective = Object.create(origSyncDirective);
extend(derivedSyncObject, { templateUrl: null, transclude: null, replace: null, $$originalDirective: origAsyncDirective });
```

Alternatively, it should be documented that only 'own' properties can be relied upon when defining directives.

**Comment by Narretz** [comment]
This is fixed since 1.3.12: http://plnkr.co/edit/gbTsJhzAaOZ94pju2Cg0?p=preview
