### ISSUE TITLE
ngRepeat: property names starting with "$" will not be rendered

### ISSUE THREAD

**Issue by mgmeyers** [angular/angular.js#6266]
When using ngRepeat to iterate over an object, it will not output any key-value pair where the key starts with a dollar sign ($).

Here is a demo:
http://jsfiddle.net/takvg/4/

And, the actual code in question can be found here: https://github.com/angular/angular.js/blob/master/src/ng/directive/ngRepeat.js#L284

``` javascript
if (isArrayLike(collection)) {
  collectionKeys = collection;
  trackByIdFn = trackByIdExpFn || trackByIdArrayFn;
} else {
  trackByIdFn = trackByIdExpFn || trackByIdObjFn;
  // if object, extract keys, sort them and use to determine order of iteration over obj props
  collectionKeys = [];
  for (key in collection) {
    if (collection.hasOwnProperty(key) && key.charAt(0) != '$') {
      collectionKeys.push(key);
    }
  }
  collectionKeys.sort();
}
```

Specifically:

``` javascript
key.charAt(0) != '$'
```

I'm assuming this is to prevent angular's internal properties from being iterated over by ngRepeat. I would suggest removing this limitation, but I don't know enough about the internals or the reasoning behind this to know what effect that might have.

**Comment by sunnypatel** [comment]
Has anyone found a workaround to this?

**Comment by frfancha** [comment]
@sunnypatel Workaround is easy: just make your ng-repeat on Object.keys(myObject)

**Comment by Dhumez-Sebastien** [comment]
@sunnypatel here is example of @frfancha : https://jsfiddle.net/takvg/5/

**Comment by startswithaj** [comment]
+1

**Comment by uriva** [comment]
+1

**Comment by gaurav5430** [comment]
is there a workaround for key-value pairs , where one of the keys is $ , and we want to display both key and value. 

(in the example fiddle provided by Dhumez, we are only displaying keys)

**Comment by augimidge** [comment]
@gaurav5430 here is a workaround for key-value pairs.
https://jsfiddle.net/takvg/8/

**Comment by Narretz** [comment]
This would require a change in angular.equals, which could possibly affect many apps negatively at this point of the AngularJS lifecycle. Closing as wontfix

**Comment by Padge91** [comment]
In case anyone else stumbles upon this issue, this is my workaround:

I just added a null character at the front of the String value used for the key...
`if (keyName.length > 0 && keyName[0]==="$"){
keyName = keyName.replace("$", "\0$");
}`

Seems to work just fine.
