### ISSUE TITLE
`select` with `required` and only 1 option fails to validate (and set ng-model) until `change` event is manually triggered

### ISSUE THREAD

**Issue by himdel** [angular/angular.js#6288]
I have a select element, using ng-option over an array of integers

    <form name="form">
        <select ng-model="bar.foo" ng-options="foo as foo|filter for foo in fooarray"  required>
            <option ng-if="fooarray.length > 1" value="" selected>Choose</option>
        </select>
        <input type="submit" ng-disabled="form.$invalid" />
    </form>

When the `fooarray` has only 1 option, it should be chosen by default. Visually, it indeed is.

The DOM looks like this:

    <select ng-model="bar.foo" ng-options="foo as foo|filter for foo in fooarray" class="ng-pristine form-control ng-invalid ng-invalid-required" required="">
        
        <option value="0">filtered foo</option>
    </select>

But:
   * the select is considered invalid, thus the submit is *always* disabled
   * the ng-model bar.foo is not set
   * furthemore clicking on the select and re-choosing the same option doesn't trigger an onchange event (presumably because there was indeed no change)

So the form is never actually valid.
Triggering a `change` event manually (`$('select').trigger('change')`) indeed sets the model and makes the form valid.

It would seem it's related to the conditional `<option>`, since when I remove it in the source, the select  magically gets another (empty and default) option - but then the only option I wanted is no longer longer default, nor ..the only one. Which is IMHO a second bug.

Version: 1.2.13

**Comment by vcardins** [comment]
Quite old thread but the solution posted here: https://github.com/angular/angular.js/issues/2365 (romario333) worked for me, in short:
`
module.directive('select', HackedSelect);
    /* @ngInject */
    function HackedSelect() {
        return {
            restrict: 'E',
            require: '?ngModel',
            link: function(scope, element, attr, ngModelCtrl) {
                if (ngModelCtrl) {
                    ngModelCtrl.$isEmpty = function(value) {
                        return !value || value.length === 0;
                    }
                }
            }
        }
    }
`

**Comment by Narretz** [comment]
The second version in original plunker works now (ngIf in the empty option is supported since 1.4.9 at least). The third version works as intended. If you want the first and only option to be auto-selected, you have to set it in the model. That's how angular works.

**Comment by vaske** [comment]
Is there any way to remove red line in first example where it's required select and have default value which have value="" ?
