### ISSUE TITLE
ng-model boolean value binding behaviour between jQuery and jqLite (ng-value with option problem)

### ISSUE THREAD

**Issue by chatellier** [angular/angular.js#6297]
Hi,

We are using following code to bind ng-model on boolean value:
```
    <select ng-model="filter.active">
        <option value=""/>
        <option value="true">True selected</option>
        <option value="false">False selected</option>
    </select>
```

Here is a fiddle explaining different behaviour if jquery is present or is not present on page:
working : http://jsfiddle.net/8byx5/
broken with jquery : http://jsfiddle.net/8byx5/1/

What do you think about this behaviour ?

**Comment by petebacondarwin** [comment]
We need to work on getting `ngValue` working for the `select` directive (including with `ngRepeat`. @Narretz and @matsko this is an area you might be interested in?

Can we discuss this at a forthcoming 1.x meeting?

**Comment by Narretz** [comment]
We can talk about it, sure.  Although since ngOptions works pretty well now I would like to limit cycles for this.

**Comment by Narretz** [comment]
I have a PR for that: #13962 13962
