### ISSUE TITLE
Treat <option value=""> and <option> the same for null select

### ISSUE THREAD

**Issue by TehNrd** [angular/angular.js#6351]
If the value attribute in an option tag does not exist angular will not show the value for null. Here is an example: http://jsfiddle.net/MTfRD/673/ . 

The obvious answer would be to make sure option includes a value="" like so:

`<option value=""></option>`

This makes perfect sense but there are some platforms that will strip out the value attribute if it has no value. There are work arounds and some of those are discussed here, http://salesforce.stackexchange.com/questions/28310/angular-option-for-null-not-working-in-visualforce , but they just feel hacky and not right.

I'd like to propose treating:
`<option value=""></option>`

and

`<option></option>`

...as the same for null values.

This may be considered a bug or feature request and I am open this this being not implemented at all as there are workarounds, albeit ugly ones, but I wanted to at least start the discussion.

**Comment by Narretz** [comment]
This is resolved, see https://github.com/angular/angular.js/issues/6519
