### ISSUE TITLE
Binding / Expression Namespaces (better BindOnce alternative)

### ISSUE THREAD

**Issue by ProLoser** [angular/angular.js#6354]
So lots of people are asking for 'BindOnce' but I actually don't believe this is the best approach to handle performance. Not only does it require specific directives, it also doesn't properly tackle the 'bind-occasionally' scenario, or when it does, it requires a completely different directive. Instead I propose:
# Expression Namespaces

**Examples:**
- `ng-bind="{ personNamespace: person.name }"`
- `{{personNamespace:: person.age}}`
- `ng-if="personNamespace:: person.alive"`
- `ng-repeat="personNamespace:: child in person.children "`
- `$scope.$watch('personNamespace:: person.height', ... )`
- `{{i18n:: i18n['welcome.message']}}`
- `ng-if="login:: hasPermission('DeleteUsers')"`

**These would all be handled by:**

`ng-namespace="{ personNamespace: person }"` or `$scope.$namespace({ personNamespace: 'person' })`

_Only the `ng-namespace` expression is evaluated on every $digest_. When the expression changes in value, all namespaced bindings get re-evaluated. 

The `person` value would be watched normally, and every time it changes, the `personNamespace` bindings throughout the rest of the application would be refreshed.

This is pretty much JUST 'bind-occasionally' since if the 'occasional' occurance is only once, then you are getting the same benefit of a bind-once.
## Benefits:
- You can intermix multiple namespaces together, unlike bindonce which sections off groups of bindings
- Completely backwards compatible with the old syntax
- Simplistic syntax that can be used anywhere expressions are used
- All bindings are bind-occasionally
- Problems such as internationalization, permission restrictions, etc can all be tackled with traditional bindings without needing to create workaround directives
- Additional edge-cases for undeclared namespaces (if the namespace isn't declared in ng-namespace)
  - If namespace is undeclared, behave like bind-once?  
    `{{once:: person.name}}`
  - If namespace is undeclared, fall back to normal watching behavior?  
    `{{always:: person.selected}}`
## Issues:
- Using `ng-namespace` (a directive) may be confusing alongside namespaces in watchers (controllers). I am not 100% sure the watcher version is necessary however.
## Implementation

I was discussing how the best way to write an efficient translation solution and we realized that instead of using watchers, it's better to use `$broadcast()` to signify that a namespace digest has been triggered. I'm not necessarily saying this is how it should be implemented in the core, but this was one idea we came up with.

**This separates the expression being WATCHED from the expression being ECHO'd**

It's like saying "Although I want to spit out `person.age` I want you to just monitor `person` for changes". However what is being 'monitored' is defined in your `ng-namespace`. Each binding or expression is no longer being watched. Instead they are waiting for some sort of `$broadcast('namespace-person')` instead, and only 1 watcher is ever actually used.
# TL;DR:

Using expression 'namespaces' we no longer deal with turning off / on bindings. Instead, only 1 expression is 'watched' and all the other bindings are tied to this one expression. **There is no toggling on and off of bindings**.

``` html
<div ng-namespace="person:: person.id">
  <h1>{{person:: person.name}} ({{person:: person.age}})</h1>
  <h2>{{person:: person.title}}</h2>
  <p>Gender: {{person:: person.gender}}, Company: {{person:: person.company}}</p>
</div>
```

**Comment by ProLoser** [comment]
I think the level of complexity applications (and developers) are getting into in order to circumvent performance issues with AngularJS might merit reconsidering this solution (as over these past several months, I still feel this is a highly viable solution). Just like the 'dot' binding and $scope.$apply confusions, it may simply be a matter of clear instruction and documentation.

**Comment by lgalfaso** [comment]
@ProLoser there is a proposal in place at https://docs.google.com/document/d/1XIng9nC_8G48AJ9Pbq8gYSWYvS1dnhiFxpugIKAPBhY/edit
That said, this is not in the radar for 1.4

**Comment by ProLoser** [comment]
I don't expect to see it in v1.x but I just was hopeful that it saw it's way into v2.x

**Comment by ProLoser** [comment]
@lgalfaso Actually reading that proposal, that's not what I envisioned namespaces to be. That simply uses a namespace to turn watchers on and off, but that means when they are on, they are extremely inefficient. I was instead proposing that the namespace is a way of lumping watchers together. In other words, namespace bindings are in fact ALWAYS active, however there is only 1 watcher for all of the bindings.

**Comment by ProLoser** [comment]
Would it be at all possible to add this as a note as an alternative proposal? I feel there is too much focus on this 'one-time' binding behavior or turning watchers on and off instead of using namespaces as a way to lump multiple bindings into 1 watcher.

In other words, if the namespace watcher `person` changes, then all view-bindings `person.name`, `person.age`, `person.gender`, `person.company`, `person.address` would then update. You could reserve namespaces to view-only or something, but the point is the namespace (`person`) is always 'active' and monitoring. We just have 1 watcher instead of 5.

**Comment by ProLoser** [comment]
I think if the reasons that it was felt this api may lead to implementation confusion was because watchers are either listening or not-listening, then perhaps thinking of it in terms of watcher-lumping the api would in fact not be confusing at all.

**Comment by lgalfaso** [comment]
> Actually reading that proposal, that's not what I envisioned namespaces to be. That simply uses a namespace to turn watchers on and off, but that means when they are on, they are extremely inefficient. I was instead proposing that the namespace is a way of lumping watchers together. In other words, namespace bindings are in fact ALWAYS active, however there is only 1 watcher for all of the bindings.

This is still in the drawing board, and all feedback is good. If you would like to comment on the proposal, please do so (same goes if you would like to write a new proposal).

One thing that is important to keep in mind is that you cannot have two sets of watchers that are both active (but only checked under specific circumstances) as this would imply that there is a need for an inconsistency resolution mechanism (there is one in place now, but it is very simple, adding two disjoin sets of watchers that are active would imply that there is a need for a much more complex algorithm to handle this). Also it is a lot harder to explain.

**Comment by ProLoser** [comment]
I feel like there's still a misunderstanding. I don't think I'm necessarily proposing circumstantial watchers.

I'm talking about separating the listeners/watchers (the checks) from the bindings (the evaluations/results/callback/render/output).

Essentially, the ng-namespace expression would be added to the watchers list and dealt with normally. All of the namespaced bindings would in fact NOT have watchers whatsoever. Instead, the callback of the namespace watcher would simply trigger the update.

It'd be more like having the namespaced bindings listen to a broadcast event that is triggered by the namespace watcher. Like, uh...

```
// ng-namespace=" person: person.id "
directive('ngNamespace', fn(){
  return fn($scope, $elm, $attrs){
    var ns = $attrs.ngNamespace.split(':');
    $scope.$watch(ns[1], function(){
      $scope.$broadcast('$namespace-' + ns[0].trim()); // $namespace-person
    })
  }
});
```
And then all expressions that have `{{ namespace: ... }}` would actually not add watchers but instead simply subscribe to `$namespace-person` using `$scope.$on()` and bam, you're done, move on with life.

**Comment by ProLoser** [comment]
I'm also unable to comment on that proposal document.

Is there seriously an issue with this logic ^?

**Comment by lgalfaso** [comment]
I think that what you are saying and what the proposal is, are very similar. The only reason why there is a need for a one-time binding is the async nature of an app. Say you have an expression `:namespace:foo[bar]` you have full control of `foo`, but `bar` is something you do not have control (say, it is something that is reflected in your directive from a parent scope). Every now and then you change `foo`, and given that you have full control of `foo` then you generate the right event. Given that you do not have control over `bar`, you do not know if this value was initialized or not.

If we do not use one-time binding, then we would need to add a watcher to `bar`. This would be error-prone as you will need to keep track of all the expressions and know everything they depend on.

If we use one-time binding, then life is easier, as we do not have to keep track of `bar` at all.


Maybe I am missing something, that would make your solution work better in this scenario.

**Comment by ProLoser** [comment]
I just sort of figured you wouldn't track updates to `bar`.

So we're monitoring `bar` right? Lets say it changes a lot:

`{{ foo[bar] }}`

Done. You are deciding between foo and bar? Which one changes more often? Lets say that foo is tied to the page render, but bar is not (tied to something on the page:

`{{ :bar-ns: foo[bar] }}` where as other places you might bind to simply `{{ :foo-ns: foo.whatever }}`

My point is I think you're overcomplicating it and ruling out ways of improving performance because we can't cover all 100% use cases, even though we're expanding coverage to 80%.

Simply imposing a 1 namespace restriction, and let the dev figure out what namespace (if any) he chooses to use. If all the variables are subject to change, he can simply to forego namespacing. I mean that's all there is to it really. If you want the data to change MORE often than your namespace changes, then DONT namespace.

I really don't think it's that complicated.

I toyed with the idea of multi-namespace bindings:

```
{{ :foo-ns bar-ns: foo[bar] }}
```

Which would then just add a `$scope.$on` to each namespace (I realize this may create redundant processing) but I don't even think THAT level of complexity is really necessary.

The main use-case for one-time binding is something like static-like rendering.

2 examples are 1: translation and 2: logs.

But lets say instead of a timestamp for logs, we use time-ago, so we want to update this value every minute, or every hour, or something. Lets also say we want the user to change the translation on-the-fly. This turns what the developer initially thought would be bind-once into a bind-occasionally scenario.

Also, lets say we've got 100s of bind-once bindings on the page, and absolutely none of them are getting values. This would mean that UNTIL they get their initial value, their killing performance and quite possibly reducing the initial page render-time. Namespace binding could very well give BETTER performance in more situations than bind-once.

**Comment by ProLoser** [comment]
Btw, if the expression was an object, you could even create more namespaces as necessary:
```
ng-namespace=" foobar-ns: foo[bar] "

{{ :foobar-ns: foo[bar].name }} {{ :foobar-ns: foo[bar].age }}
```
Or even `ng-namespace="foobar-ns: foo && bar"` or iunno something.

The point is NOT to think of namespaces as wether or not watchers are on or off. The point is to think of namespaces as watcher-lumping. We would now have a concrete API for saying that all these expressions on all these different scopes are all actually really just using 1 expression to check for value change.

**Comment by danieljsinclair** [comment]
I totally get this, and think it would be tremendously valuable. Not least for DRYing out expressions you want to bind in more than one place in the HTML but you don’t want to call a function().

 

+1 for namespace aliases to watched expressions.

**Comment by lgalfaso** [comment]
Hi,
  First let me make this clear that I am speaking for myself and not for the entire team.

> My point is I think you're overcomplicating it and ruling out ways of improving performance because we can't cover all 100% use cases, even though we're expanding coverage to 80%.

Once a feature is out, it is very hard to make a breaking change to it. This implies that if we know that a specific feature does not cover a reasonable amount of the use cases, then it is better to keep on working than to release something that will break *soon*. Whenever you state that a simpler solution would cover 80% of the use cases, what scientific method you used to be sure that this simplified version covers 80% of the case? Would you be comfortable if a simplified version is merged and based on community feedback we have to break it in a way that you will need to use a substantial amount of time to accommodate to a new behavior?

I am sure that whatever solution we implement, there will be use cases that were not taken into consideration, but I think it is not the same when a solution is build when all the use cases known at the time are covered than having a solution that is known to be a compromise. I see the simplified solution as  a compromise that will cause severe headaches to developers.

Now, given that this is not in the scope for 1.4, then we have the time to think this thru. Your feedback is greatly appreciated, and it would make the solution better.

**Comment by kasperlewau** [comment]
I'd like to pitch in with a solution I cooked up, heavily inspired by **[a draft](https://docs.google.com/document/d/1fTqaaQYD2QE1rz-OywvRKFSpZirbWUPsnfaZaMq8fWI/edit#)** (signed(?) by Karl Seamon, Igor Minar, Caitlin Potter) on the subject from August 2014.

Scroll down to the very end and you'll end up in the `labeled binding` section, where the proposed syntax looks something like so: 

```html
<div binding-notifier="{ u: user }">
  {{u: user.name}}
</div>

<div binding-notifier="{ watch: users, notify: 'u' }">
  <div ng-repeat="user in u:users">{{u: user.name}}</div>
</div>
```

The 'proposal' outlines some issues on using an event bus for refreshing binds, I'm not so sure I've come around those issues or not (will verify, soon™).

> 1. Its functionally is limited only to interpolation like one-way bindings (like ngBind) and thus can't be composed with existing directives (e.g. ngRepeat or custom component directives).
2. The bindings when processed and reprocessed are eager and strictly one-time per signal occurrence which makes them vulnerable in cases when model requires several digest loops to settle.
3. Since the solution depends on Scope events which propagate into isolate scopes by default, we could be accidentally triggering bindings in unrelated isolate scopes.
4. They also execute out of order within the digest cycle but that should generally not be an issue.  

---

#### [my solution to the "problem"](https://github.com/kasperlewau/angular-bind-notifier)
> no, not the four problems listed above.

```html
<section bind-notifier="{ u: user, l2: exp2 }">

  <header bind-notifier="{ headingLabel: someOtherExpr }">
    <h1>{{:headingLabel:h1Expr}}</h1>

     <span>{{:u:l2:headingLabel:iUpdateOnAllThree}}</span>
  </header>

  <span ng-bind=":u:user.name"></span>

  <img ng-src=":l2:someImageSrc">

  <!-- my favorite... -->
  <div bind-notifier="{ ns: data.length }">
    <span ng-repeat="d in :ns:data track by $index">{{:ns:d}}</span>
  </div>
</section>
```

Where every `label` (or, `namespace`) watches an `expression` in the `bind-notifier` directive. The above example is using four *(barring the ones that a [oneTimeWatchDelegate](https://github.com/angular/angular.js/blob/master/src/ng/parse.js#L1823) adds/removes at eval time).* 

When a watched expression changes, an event is sent down through the descendant $scope's letting every expression with the `:namespace:exp` syntax know that it is time to re-evaluate themselves (assuming they match up).

An expression can have multiple namespaces attached like so: `:ns1:ns2:ns3:exp`, where either of the three would trigger a refresh of the expression. 

*One could forego the `bind-notifier` directive altogether and manually broadcast a `$$rebind::namespace` event (which is all that's going on behind the scenes).*

I've tested this with most/if not all the built in `ng-` directives and it appears to be *working just fine™*, and we are currently using it in our production environment seeing some good results for the times when we need an occasional refreshment of an expression.

--- 

Naturally, I would love for *this* to land in core - but given the rough around the edges state of the current implementation, and the additional complexity that comes with such a system *(I personally don't see it)*, I am prepared for it to remain a third party solution.

Is this *somewhat close* to what you are looking for @ProLoser? I'd love to hear your thoughts on the solution.

**Comment by ProLoser** [comment]
Your _"solution"_ is pretty much what I stated in the very beginning, where as your original example doesn't make a whole lot of sense to me (you're binding an object to the same namespace as a collection, which is wrong). Yes this is close though to what I prescribed. The one note I might add is that multi-namespaced bindings may be adding unnecessary complexity, but I guess they are worth exploring. I think though your example for a multi-namespace binding is a little confusing and possibly unnecessary.

Lets say we drop support for multiple namespaces, the api becomes simplified as the user is told to just make a new namespace that encompasses all 3 values: `bind-notifier="{ subheader: user+exp2+someOtherExp }"` although that's also a bad example.

Anyway, TL;DR: You pretty much seem to be implementing things pretty close to how I originally proposed them with some minor tweaks.

**Comment by ProLoser** [comment]
@kasperlewau I've updated my original post at the top to incorporate more recent trends in binding syntax and your object notation for `bind-expression` to reflect what I feel should still be relevant today as a namespaced binding.

**Comment by kasperlewau** [comment]
The original example was only ever 'stolen' from the August 2014 draft, whereas the second example showcase the current state of things over at camp Kasper. Sorry about any confusion caused there.

Don't get me wrong here - I never meant to hijack your proposal with *"my solution"*, I think it's a problem as much as you do that needs solving. I only ever wanted to highlight how it *could* be done (from an implementation point of view) utilising oneTimeBinds over and over again and hooking into $parse, as opposed to a lot of the current solutions that recompile DOM nodes and/or use custom `bind-` directives.

In regards to multiple namespaces, I quite like the power you get from being able to 'chain' them (I'm currently working on a solution so as to *compose* them aswell). 

I'll admit that the example on multi namespaces I've given doesn't make much sense, I'll go get some chow and come back with a more senseful example so as to showcase *why* I think it should stay. 

I suppose you could take your example of `subheader: user+exp2+someOtherExp` and define it as either a method or an object.getter on the parent scope, but I don't see that being promoted as *the way of doing things*, if a solution like this were ever to land in core. Would probably have to support the `+` notation in a nify way, I've only ever gotten in trouble when doing so because of naive string concatenation not playing well with observed values.

**Comment by kasperlewau** [comment]
@ProLoser I've updated my reply with a multiple namespaces example that I feel is a little easier to reason about.

**Comment by ProLoser** [comment]
@kasperlewau Sorry for the tardy response but I was responding weird. Your solution is awesome!

**Comment by Narretz** [comment]
We are trying to add https://github.com/angular/angular.js/pull/10658 as a general way to detach / re-attach scope listeners on demand. Bind / Expression namespaces will not be implemented.

**Comment by Narretz** [comment]
If you want to help out with https://github.com/angular/angular.js/pull/10658, please ping us in the PR.
