### ISSUE TITLE
select model not reset if valid options changed by ng-options 

### ISSUE THREAD

**Issue by clkao** [angular/angular.js#6379]
If a select's options (from ng-options) are changed, and the current value is no longer in the list, the model value should probably be cleared.

tested on chrome and 1.2.13.

Demo to reproduce this issue:  http://plnkr.co/edit/T4RMMfFGP2lHndqBH1aK?p=preview

**Comment by munkychop** [comment]
Any updates on this? I'm still seeing the bug in Angular 1.3.8

**Comment by Narretz** [comment]
This works now in 1.4.x http://plnkr.co/edit/W16slPNhU55zMa802Mv8?p=preview

**Comment by Narretz** [comment]
Since this works in 1.4, we've decided not to fix this in 1.3.x, as the effort required would far outweigh the gains (upgrading from 1.3 to 1.4 is easier than 1.2 to 1.3)
