### ISSUE TITLE
Support disabling options in select with ng:options

### ISSUE THREAD

**Issue by esprehn** [angular/angular.js#638]
Need a way to construct

    <select>
      <option disabled>A</option>
      <option>B</option>
      <optionC</option>
    </select>

There's no way to express the disabled state of a specific option with ng:options

**Comment by lebster** [comment]
+1

**Comment by gcardosostep** [comment]
+1

**Comment by jBox** [comment]
+1

**Comment by janeklb** [comment]
+1

**Comment by knivets** [comment]
Made up a quick directive here - https://github.com/knivets/angular-options-disabled

**Comment by giladbeeri** [comment]
+1

**Comment by jparmar** [comment]
+1

also It good to have some functionality to skip particular option

For eg.

ng-options="page.id as page.name for page in pages" ng-option-skip="page.id === 100"

the above code should skip rendering an option html when particular psge.id value is 100 in this case.

**Comment by greglockwood** [comment]
@jparmar: Wouldn't you use a filter in that case to modify the collection that ng-options is rendering? This enhancement is needed because you still want to render an item in the collection as an option, but have it be disabled, which a filter won't help you with.

**Comment by rutwick** [comment]
@chadreed-intl Did you find a solution to make it work for dynamic options? I'm having a hard time figuring it out!

**Comment by ivkremer** [comment]
I think this is applicable while there is no way to this via `ng-options`:
```html
<option ng-repeat="option in myOptions" value="{{ option.key }}" ng-disabled="option.disabled">
    {{ option.label }}
</option>
```

**Comment by ivkremer** [comment]
I think this is applicable while there is no way to do this via `ng-options`:
```html
<option ng-repeat="option in myOptions" value="{{ option.key }}" ng-disabled="option.disabled">
    {{ option.label }}
</option>
```

**Comment by ivkremer** [comment]
I think this is applicable while there is no way to do this via `ng-options`:
```html
<option ng-repeat="option in myOptions" value="{{ option.key }}" ng-disabled="option.disabled">
    {{ option.label }}
</option>
```
```js
$scope.myOptions = [{
    key: 'key1',
    label: 'Key #1'
}, {
    key: 'key2',
    label: 'Key #2',
    disabled: true
}];
```

**Comment by Xartok** [comment]
ng-repeat on option doesn't work in IE (at least IE8). It was mentioned here https://github.com/angular/angular.js/issues/638#issuecomment-51002615

**Comment by premboyapati** [comment]
@alalonde 

In this example: http://jsfiddle.net/alalonde/dZDLg/9/

Set value from test to null for selectedPort variable like this $scope.selectedport = null;
The code will broke...It does not disable untill we select some value...
Could you help me how to fix this issue?

Thanks
Prem.

**Comment by dishantgniit** [comment]
you can fix this bug like
<md-option>Test 1<md-option>
<md option ng-disabled="true">Test 2</md-option>

**Comment by anilkganhari** [comment]
When the this directive http://jsfiddle.net/alalonde/dZDLg/9/

is used inside ag-grid,The disbled property is not applied to he options until we do a selection in the select box. 

could you please help on this?

**Comment by gkalpak** [comment]
@anilkganhari, since you seem to be using [angular-options-disabled][1], you should probably ask the question in their repo. This is not related to core Angular.

BTW, the `ngOptions` DSL now supports "disable when" for disabling specific options ([see docs][2]).
(Make sure that your Angular version has this feature, before using it.)

[1]: https://github.com/knivets/angular-options-disabled
[2]: https://docs.angularjs.org/api/ng/directive/ngOptions

**Comment by fredericlam** [comment]
Still nothing native to Angular ?

**Comment by gkalpak** [comment]
@fredericlam, see https://github.com/angular/angular.js/issues/638#issuecomment-170361383.

**Comment by fredericlam** [comment]
@gkalpak Wow, sorry, and thanks

**Comment by LucasFrecia** [comment]
funka capo! bien ahi alto team...estoy sin celular no me funcionan los
botones, calculo que el sabado como mucho lo cambio, mientras tanto nos
comunicamos por este medio

2015-11-25 13:35 GMT-03:00 Dishant Mehta <notifications@github.com>:
