### ISSUE TITLE
Require ngModel in directive inside ngTransclude on IE

### ISSUE THREAD

**Issue by treyrich2001** [angular/angular.js#6457]
This definitely seems to be an edge case but I spent a good amount of time yesterday attempting to figure out what was wrong with my application on IE and I finally found the problem.

In IE if you have a directive that implements ngTransclude and within the transcluded content is another directive which has 
```javascript 
require: 'ngModel'
```
and the value in ngModel is an object's child like
```html
<textarea ng-model="myModel.attribute" my-inner-directive></textarea>
<input type="text" ng-model="myModel.secondAttribute">
```
where myInnerDirective is the directive requiring ngModel, both the input and the textarea will have no value and the binding will be broken to the model. The only way to work around this that I found is to modify the code to the following
```html
<textarea ng-model="$parent.myModel.attribute" my-inner-directive></textarea>
<input type="text" ng-model="myModel.secondAttribute">
```
No other browsers require that $parent be present so I'm assuming that this is a bug with IE.

**Comment by Narretz** [comment]
Closing this due to lack of response.
