### ISSUE TITLE
$httpBackend .respond() method fails when responding with angular.element()

### ISSUE THREAD

**Issue by facultymatt** [angular/angular.js#6461]
**Overview of the issue**
Since 1.12.5 changes to `$httpBackend` have caused failures when `respond()` is used with angular element and `flush()` is called. This might effect all non-string `respond()` values too (not verified). It makes sense that $httpBackend should always respond with a string, however it's not noted as a breaking change in the changelog.

```
PhantomJS 1.9.7 (Mac OS X) Widget test should pass	
    at forEach (/bower_components/angular/angular.js:305)
    at copy (/bower_components/angular/angular.js:836)
    at copy (/bower_components/angular/angular.js:821)
    at copy (/bower_components/angular/angular.js:838)
    {{ repeats over 100 times, then ends with }}
    at handleResponse (/bower_components/angular-mocks/angular-mocks.js:1135)
    at /bower_components/angular-mocks/angular-mocks.js:1466
    at /scripts/my-widget-spec.spec.js:78
    at invoke (/bower_components/angular/angular.js:3720)
    at workFn (/bower_components/angular-mocks/angular-mocks.js:2124)
undefined
Expected undefined to be defined.
```

**Motivation for or Use Case**
Breaking change not noted in the change log which will likely break many tests. We tend to write our tests like this: 

```
directiveElement = angular.element('<div widget></div>');
directiveTemplate = angular.element('<h1>Widget<input ng-model="widgetValue"/></h1>');
$httpBackend.when('GET', 'views/widget.html').respond(directiveTemplate);
$compile(directiveElement)(scope);
$httpBackend.flush();
expect(directiveElement.find('input').length).toBe(1);
```

**Angular Version(s)**
1.2.5 and up

**Browsers and Operating System**
Verified running tests with PhantomJS

**Reproduce the error**
http://plnkr.co/edit/fGzXVe?p=preview

**Related issues**
None found

**Suggest a Fix**
Besides updating changelog and providing note in documentation, I have't yet looked into a code fix.

**Comment by gkalpak** [comment]
I tried this in 1.5.5 and it works as expected, i.e. it fails, but for a different reason (as mentioned by @lgalfaso). Returning a jqLite/jQuery instance (and expecting it to become the directive's template) is not the intended behavior for `.respond()` anyway.
