### ISSUE TITLE
Implement filtering on object-based ng-repeat

### ISSUE THREAD

**Issue by yaycmyk** [angular/angular.js#6490]
Currently if you are using the ng-repeat directive to walk over the properties of a non-array object, filters will not work as they test immediately if the collection is an array and reject anything not matching.

This behavior can be seen here: https://github.com/angular/angular.js/blob/06f2ba899fac8ad004bf65dce39a3b05e2387c0f/src/ng/filter/filter.js#L118 (thanks @caitp !)

This is an undocumented and - per #6215 - potentially unwanted behavior, since the syntax is the same for iterating over arrays and objects. Plus, it's just darn useful!

Opening up the lines of discussion here to see if it's worth implementing filter functionality for objects and not just straight array/array-like structures.

**Comment by lgalfaso** [comment]
this looks like a perfect solution for a third-party module. BTW, just by adding https://github.com/petebacondarwin/angular-toArrayFilter you can do and more

**Comment by Philzen** [comment]
+1

**Comment by Narretz** [comment]
WE've decided that the filterFilter should only work on arrays. It'll throw in 1.4 and beyond if it is passed an object, see cea8e751

**Comment by Philzen** [comment]
@Narretz - throwing an error will help newbies a lot, as it indicates unintended use straightaway instead of wondering at some later point in time why it doesn't work as expected.

> WE've decided that the filterFilter should only work on arrays.

Could you maybe shed some light on the arguments behind this decision, so us "consumers" can embrace it better and understand why it makes sense not to have an object-based ng-repeat filter?

**Comment by gkalpak** [comment]
It's been discussed in several places/issues, but I believe https://github.com/angular/angular.js/issues/2694#issuecomment-71328638 sums it up nicely.

Basically, it's not something that can be done reliably and without loss of information and the usecase shouldn't be common (plus it can be very easily implemented as a 3rd-party module and not contribute to the size of the core).
