### ISSUE TITLE
Make localization operation optional

### ISSUE THREAD

**Issue by porschelau** [angular/angular.js#6546]
We have an application which operates solely on UTC time despite of the fact that we have works in PST as well as EST. We are running into issues where we really just want the date picker to show the date in UTC mode rather than localizing it by default.

I am proposing that we offer this as a parameter option.

**Comment by dromerop** [comment]
+1 to optional transform

**Comment by landed1** [comment]
We have this scenario I think as well...$http is localising the BST british summer time in a post request and this is getting stored without a Zone. So the inteligence is lost and the time is actually incorrect. As tynman said its the context understanding here. We must keep the timezone info in the date string.

**Comment by gkalpak** [comment]
@landed1, I think yours is a different problem. Also, I don't think `$http

**Comment by gkalpak** [comment]
@landed1, I think yours is a different problem. Also, I don't think `$http` is doing any date manipulation, so it might be something not Anguar-related. Please open a new issue, describing you issue in more detail.

BTW, if I read this correctly, the usecase mentioned by the OP is now covered by the `timezone` argument of the `date` filter. I'm closing this (but feel free to re-open, if I'm wrong).
