### ISSUE TITLE
ngRoute: handle error when template loading fails

### ISSUE THREAD

**Issue by provegard** [angular/angular.js#6594]
If I have a `templateUrl` in my route definition, and the URL is wrong, no particular error/exception handler is called. The code in ngRoute is:

```
  template = $http.get(templateUrl, {cache: $templateCache}).
        then(function(response) { return response.data; });
```

It would be convenient to be able to deal with an error at this point.

**Comment by Narretz** [comment]
This throws the tpload error since 1.3, which can be accessed as the 4 parameter of $routeChangeError.
It's catchable by an interceptor, too.
