### ISSUE TITLE
Select Value Does not update when typing a second char 

### ISSUE THREAD

**Issue by MissingHandle** [angular/angular.js#6652]
When I focus on a text field, then tab over to a select field, then type the value of a valid option which starts with the same letter as another option that comes alphabetically first, I expect that angular will record the value of the option i typed, and which is also displayed in the UI.  Instead, the angular value is the non-typed option which comes first alphabetically.

Fiddle: http://jsfiddle.net/Missinghandle/vFX9n/

Select the text box
Tab
type "i", "l"
UI shows IL
select value is ID

**Comment by Narretz** [comment]
this is the same as https://github.com/angular/angular.js/issues/9134
