### ISSUE TITLE
textarea ng-model is not updated in IE with Korean IME.

### ISSUE THREAD

**Issue by tourscrap** [angular/angular.js#6656]
if I type the english, it is ok.
 but if I try to type korean, I can't get text value from ng-model.
I think that compositionend event does not fired by IE

**Comment by azack** [comment]
noticed that I get ng-change events when typing with the MS Korean IME w/ IE11, but the model isn't updated. If I introduce a Latin character by toggling the character set in the IME the model gets updated with all the text (Korean and all), and if I use common characters such as space or numerical digits, or hit the delete key, it also updated the model.  Tested with angular 1.3.14.

**Comment by azack** [comment]
Looking at it more, my results agree with @iDevSK .  On IE 11 with Hangul input, Composition start and update events are fired while typing Korean, but Composition end is not fired until some other type of input occurs (enter, tab, space, etc, basically anything non-hangul).  I thought this was an IE11 bug but after [reading the spec on compositionend](https://dvcs.w3.org/hg/dom3events/raw-file/tip/html/DOM3-Events.html#event-type-compositionend) I'm not so sure.  I think its valid that compositionend only gets fired when the IME is dismissed.  If someone with a better understanding of the spec and browser quirks can take a look at this maybe we can come up with a solution.

**Comment by azack** [comment]
FWIW this workaround seems to work for me.  I add a top-level decoration on the input directive that creates fake compositionend events:
```javascript
.config(function ($provide) {
        $provide.decorator('inputDirective', function($delegate, $log) {
            $log.debug('Hijacking input directive');
            var directive = $delegate[0];
            angular.extend(directive.link, {
                post: function(scope, element, attr, ctrls) {
                    element.on('compositionupdate', function (event) {
                        $log.debug('Composition update, faking end');
                        element.triggerHandler('compositionend');
                    })
                }
            });
            return $delegate;
        });
```
This is probably wrong somehow and not robust or anything, but is maybe a first step towards a more solid workaround until it can be fixed/worked-aroudn in core angularjs.   Here's a fork of @sylvhama 's plunkr with this added: http://plnkr.co/edit/4TY55ozh1D62sBDeUQxk?p=preview

**Comment by tlvjfjstor** [comment]
use this

myApp.directive('krInput', [ '$parse', function($parse) {
    return {
        priority : 2,
        restrict : 'A',
        compile : function(element) {
            element.on('compositionstart', function(e) {
                e.stopImmediatePropagation();
            });
        },
    };
} ]);

i found it
http://118k.tistory.com/135

**Comment by Narretz** [comment]
I have tested this (to my ability) in Chrome, IE Edge, and IE11.
I have entered 'a,b,c,d' with the built-in Korean IME active. Pressing a, b, c, d transforms the first character in the input.
In Chrome, Edge and IE11, the model isn't updated until I press 'd'. Then, also a second character gets added to the input.
However, in Chrome and Edge, this second character is not yet part of the model, while it is added to the model in IE11.
I assume that Chrome and Edge do the right thing here, as the second charater isn't yet composed correctly. I'm not sure if there's anything Angular can do about this in IE10, though.

**Comment by prksean** [comment]
@azack Hi, thank you for your solution! It seems to work fine for input boxes in IE. However, this solution does not seem to work in textarea tags. Does anyone have any idea on this? Thanks in advance.

**Comment by azack** [comment]
@prksean sorry I don't

**Comment by jileeon** [comment]
Hi, I'm having same issue on 1.2.32.

Does it fixed yet right?

**Comment by Narretz** [comment]
It's not fixed unfortunately. If it gets fixed, it'll  not happen in the
1.2.x branch because that one is in security fix only mode.

Am Do., 12. Okt. 2017 11:07 schrieb Jae Ik, Lee <notifications@github.com>:

**Comment by jileeon** [comment]
@Narretz Thank you for telling me this. I made the pull request #16273 to fix this. So It works fine in IE for any characters made by composition.
