### ISSUE TITLE
ngView link touch (no mouse) bypasses interceptor

### ISSUE THREAD

**Issue by quijibo** [angular/angular.js#6658]
I'm using 1.2.14 and am testing in IE 11.  I'm using an ngView with various routes and template definitions.  when using the mouse to click on links everything is working and angular is intercepting, loading the template, etc.  When using the touchscreen to touch a link I believe the interceptor is being bypassed and a direct request to the resource is being made to the server.

I'm developing and testing on a Surface Pro 2 using IE 11.  I have not tested on anything else yet.

**Comment by Narretz** [comment]
1.2.x is unsupported at this point, and it's not clear if this was ever an issue with Angular (or ngTouch specifically) to begin with. Closing.
