### ISSUE TITLE
Angular guide doesn't work on Ipad 1 - Safari

### ISSUE THREAD

**Issue by winsik** [angular/angular.js#6696]
There is a problem with loading guide (http://docs.angularjs.org/guide) on Ipad 1 iOS 5.1.1 - Safari 

I see only "loading" and nothing else - there is an error in console (particular referred line depends on guide version):

Javascript: Error on line 86 - http://code.angularjs.org/1.2.14/angular.min.js - TypeError: 'undefined' is not a function

Last working version is - http://code.angularjs.org/1.1.5/docs/guide

**Comment by winsik** [comment]
Today I have realised, that documentation now works on Ipad 1. It has to been fixed by some change last month. Thank you :)

**Comment by armyofda12mnkeys** [comment]
I'm testing on Ipad (Safari5) and an Iphone (Safari6), with Angular 1.3.14. and get this same error. 
When I removed the console.log statements, it works.

What do you mean "the documentation now works on Ipad 1"?

**Comment by winsik** [comment]
Reported problem referred to ability to display http://docs.angularjs.org/guide on Ipad 1 when 1.4 beta came, it started to work.

**Comment by CusProjects** [comment]
Wich version can i use on Ipad(safari5)

Regards...
