### ISSUE TITLE
Decouple $q in AngularJS 2.0 (and/or switch to bluebird)

### ISSUE THREAD

**Issue by mgcrea** [angular/angular.js#6697]
AngularJS currently uses a shim of [q](https://github.com/kriskowal/q). I haven't dug into the actual implementation, but I think it might be interesting to review a possible change for the 2.0 milestone.

I think AngularJS should use an agnostic `$Promise` service accross the framework, and extract the current `$q` shim out of the core. Letting user choose their Promise framework. Thanks to the unified promise spec, this should be doable.

Also, I would strongly advise to pick [bluebird](https://github.com/petkaantonov/bluebird) over [q](https://github.com/kriskowal/q) for the future.

I've been doing NodeJS work for a couple of years, and switching from [q](https://github.com/kriskowal/q) to the very well-crafted [bluebird](https://github.com/petkaantonov/bluebird) has been a really pleasant experience. The [API](https://github.com/petkaantonov/bluebird/blob/master/API.md) is far superior and the performance is unmatched.

Regarding performance, have a look at [this article](http://spion.github.io/posts/why-i-am-switching-to-promises.html#but-you-said-promises-are-slow-).

>
But you said promises are slow!
Yes, I know I wrote that. But I was wrong. A month after I wrote the giant comparison of async patterns, Petka Antonov wrote Bluebird. Its a wicked fast promise library, and here are the charts to prove it.

file | time(ms) | memory(MB)
--- | --- | ---
callbacks-original.js | 316 | 34.97
callbacks-flattened.js  | 335 | 35.10
callbacks-catcher.js  | 355 | 30.20
promises-bluebird-generator.js  | 364 | 41.89
dst-streamline.js | 441 | 46.91
callbacks-deferred-queue.js | 455 | 38.10
callbacks-generator-suspend.js  | 466 | 45.20
promises-bluebird.js  | 512 | 57.45
thunks-generator-gens.js  | 517 | 40.29
thunks-generator-co.js  | 707 | 47.95
promises-compose-bluebird.js  | 710 | 73.11
callbacks-generator-genny.js  | 801 | 67.67
callbacks-async-waterfall.js  | 989 | 89.97
promises-bluebird-spawn.js  | 1227  | 66.98
promises-kew.js | 1578  | 105.14
dst-stratifiedjs-compiled.js  | 2341  | 148.24
rx.js | 2369  | 266.59
promises-when.js  | 7950  | 240.11
promises-q-generator.js | 21828 | 702.93
promises-q.js | 28262 | 712.93

**Comment by lgalfaso** [comment]
Angular 2.0 has its own repository and is not going to use $q nor reimplement their own version of Promise/A+. I think this can be closed now

**Comment by metamatt** [comment]
BTW it turns out to be quite easy to use Bluebird with Angular 1.x; [Bluebird has a setScheduler hook](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisesetschedulerfunction-scheduler---void) that supports exactly this ([example via StackOverflow](http://stackoverflow.com/a/23984472/275581)). I just started using this and am impressed at how easy it was to drop in and how big the benefits are.

**Comment by benjamingr** [comment]
@metamatt actually more like http://plnkr.co/edit/ggMzDwnkzMOc0MccdVEu?p=preview in order to really decouple $q.

**Comment by metamatt** [comment]
@benjamingr oh yes even better. Thanks for educating everyone on this.

**Comment by metamatt** [comment]
Hmm. I tried (a riff on) that and found it does indeed work, but there are a bunch of places both in my own code (mostly related to `$timeout` and `$timeout.cancel()`) and library code I don't control ([ui-router](https://github.com/angular-ui/ui-router)) that were assuming it's fine to not handle promise rejection. That's a silent problem in $q, and a noisy one in Bluebird, and that noise is one of the benefits of using Bluebird, but it's got a nonzero switching cost for an existing codebase. [More info here](https://gist.github.com/metamatt/6ab462818114833b7ee1).

**Comment by sariyu** [comment]
+1

**Comment by thefabulousdev** [comment]
+1

**Comment by yoeen** [comment]
+1

**Comment by lgalfaso** [comment]
https://github.com/angular/angular.js/issues/12533#issuecomment-129262925 provides a way to replace `$q` with bluebird. All the necessary pieces will be part of 1.5. On top, Angular 2 uses native Promises, so there is nothing else actionable. For these reasons I am locking this issue
