### ISSUE TITLE
Add `drop` to angular events

### ISSUE THREAD

**Issue by danse** [angular/angular.js#6712]
Hi, i am using an handler for the native `drop` event in my application, and i wrote a directive for that.

Looking at the problem later, i realised that a good directive would probably have the same appearance of the "standard" angular directives handling events, and thus i think that `drop` should be added to the [list of auto-generated event handling directives](https://github.com/angular/angular.js/blob/master/src/ng/directive/ngEventDirs.js#L41).

This looks like a quick win, but i am having some troubles running the test suite, so i write the issue in order to have feedback from others before investing more time

**Comment by Narretz** [comment]
Will be fixed by https://github.com/angular/angular.js/pull/16614
