### ISSUE TITLE
Angular Profile Mode + Caching tools (ngRepeat default behavior issue)

### ISSUE THREAD

**Issue by kosz85** [angular/angular.js#6764]
This subject may be a bit controversial, but I hope someone will share my idea.
I think Angular should have built in profile module or good toolkit for that, which would report slow parts of user defined code (ignoring core modules) or parts of templates in angular way (preserving scope hierarchy and similar things).

Also I request to disable some of default caching, like in ngRepeat. And this is the controversial part.
Why you ask? Shouldn't it be blazing fast out of the box? My answer is NO! It should be working correctly, this is main goal!
I was doing very simple paginator, for big project with dynamically loaded modules using requirejs. Very simple, just ng-repat="p for pages" then ng-class="{current: p == page}", and it doesn't work correctly! It start desynchronize after heavy use, because of internal caching. Adding "track by p + '_' + page" solved issue, but developers spent quite some time to find what was not working, and caching in that place wasn't really needed, as it wasn't really expensive to rerender it.
Caching should be explicit, enabled on demand (for example by using track by). I think there is enough magic for simple programmer that he need to deal with using angularjs.

In addition, there should be available easy caching tools and support for them in directives. This would solve most of performance problems which are currently solved in same way but using external tools.

**Comment by Narretz** [comment]
This is a pretty broad topic and it's unclear what exactly is requested here, as a few different concepts are touched upon. We'll likely don't have the resources for a full profiling app, the ngRepeat problem sounds suspicious, but has no demo, and wrt to caching and native toolkit, it's unclear what exactly is meant.
