### ISSUE TITLE
ngCloak with preloader template as value

### ISSUE THREAD

**Issue by cameronjroe** [angular/angular.js#6805]
Since ngCloak is managing view state before the data is loaded, would it be possible to add the ability to pass a preloader template or function from the $rootscope to the directive? Something like:

```
// index.html

<body ngCloak="appPreloader">
</body>

// AppCtrl

angular.controller('AppCtrl', function ($rootScope) {
  $rootScope.appPreloader = function () {
    return {
      templateUrl: 'partials/preloader.html'
    }
  };
});
```

**Comment by Narretz** [comment]
I agree with @btford
