### ISSUE TITLE
Anchor tag with empty href behaviour breaks when a child element destroys the element through ngClick

### ISSUE THREAD

**Issue by mbykovskyy** [angular/angular.js#6808]
According to the documentation `<a href="">Item</a>` doesn't not reload a page, however, this behaviour is broken when an anchor tag has a child which destroys the element like so `<a href="">Item <span ng-click="destroy()">Remove</span></a>`. The child element can be anything.

The observed behaviour is that it destroys the element but the page refreshes. It looks like this only happens when it removes itself i.e. the link is hovered when a `Remove` is pressed.

This plunker http://plnkr.co/edit/6us80oxIahkZnHgMXxpD illustrates the behaviour.

**Comment by Narretz** [comment]
In this setup, the click listener on the anchor element is removed when the element is destroyed, but the browser still registers the click and reloads the page. You can fix this by injecting the $location service anywhere in your app, which has an additional click busting behavior.

However, interactive elements inside anchor elements are discouraged. The html spec disallows buttons (natively clickable) inside anchors, and putting a click handler on a span is basically the same. It's also a nightmare for accessibility.

Closing as wontfix
