### ISSUE TITLE
Focus lost when item in ng-repeat moves to an earlier position in an array

### ISSUE THREAD

**Issue by karl** [angular/angular.js#6859]
See this jsFiddle:

http://jsfiddle.net/2gfka/1/

Changing the value in an input to move an item later in the list correctly preserves focus on the input. Changing the value to move an item earlier in the list loses focus.

This happens with both 1.2 and the 1.3 beta.

**Comment by wolf123450** [comment]
So does anyone have a workaround for this?  I'm experiencing the same behavior with inputs inside an ordered ng-repeat.

**Comment by maxwellito** [comment]
As I said, it seems to be a browser behavior, and not related to Angular.
Maybe try to add some logic to the controller to reattribute the focus to
the correct input after $digest

**Comment by Narretz** [comment]
Closing since this is a browser issue.
