### ISSUE TITLE
angular directive templateUrl should allow "text/html" Accept and content-type headers

### ISSUE THREAD

**Issue by geoidesic** [angular/angular.js#6860]
templateUrl is generally going to be expecting to receive HTML back from the server. To inform the server of that (according to RESTful best practices) it would be useful to be able to specify the headers for the $http request that fetches the actual template.

The default being used by angularJS is "application / json". It would be useful to be able to specify "text/html" instead for templateUrl. In addition I submit that should be the default for any request that expects HTML back from the server.

**Comment by giosh94mhz** [comment]
:+1: faced the same issue.

**Comment by toninofox** [comment]
Same Issue following the REST Convention.
Adding .html as suffix of the templateUrl parameter it works but it is a little bit confusing to understand that it is a endpoint...
