### ISSUE TITLE
Rename minErr and make it accessible from outside

### ISSUE THREAD

**Issue by tkrotoff** [angular/angular.js#6913]
Would be nice to have [minErr](https://github.com/angular/angular.js/blob/332e935048/src/minErr.js) accessible from outside.

The URL `'http://errors.angularjs.org/...'` should be configurable:

``` JavaScript
// minErr => internal AngularJS function
function minErr(module) {
  // ngMinErr (or another name) => accessible from outside
  return ngMinErr(module, 'http://errors.angularjs.org/"NG_VERSION_FULL"/');
}
```

**Comment by kasiriveni** [comment]
1+

**Comment by Narretz** [comment]
Out of Scope for AngularJS development at this point.
