### ISSUE TITLE
ngInclude should not treat its argument as an expression

### ISSUE THREAD

**Issue by airbornemint** [angular/angular.js#6947]
On multiple occasions I have wasted an unacceptable amount of time trying to track down a bug that turned out to be due an ngInclude value not being single-quoted. I want to make three points:

1. I believe that majority of use cases for ngInclude will use a constant parameter
2. At least on Safari 7, ngInclude with constant parameter that is not single-quoted leads to a silent failure (nothing gets included, no error gets reported)
3. Writing ng-include="foo.html" completely naturally arises from having written basically every HTML attribute ever that way.

So, you have a feature which a. has an API similar to other related things but b. differs just enough that years of experience cause users to use the feature wrong and c. using it wrong in that particular way yields a silent failure. This is a horrible design, all for the dubious benefit of being able to ngInclude a variably-named partial.

The behavior of ngInclude should have been to accept one of two forms:

1. ng-include="foo.html"
2. ng-include="{{ 'foo.html' }}"

Neither of those is weird or misleading.

Unfortunately, it might be too late to fix because of backwards compatibility. It might be worth adding another directive that behaves better (as in, the way I just described). ngImport might be a good name for it.

Love the product otherwise, though. Solid work.

**Comment by altryne** [comment]
I wish I could come this every time this taken me 2 hours to "remember" and do a :+1: 
I treat ngInclude as I treat a `<script src=""` or a css.
99% of the cases I want it to load a url.

**Comment by frfancha** [comment]
The current behavior of ng-include is perfect for us.

**Comment by Narretz** [comment]
It's too late for this change in 1.x.
