### ISSUE TITLE
Ng-href with mailto isn't working consistently

### ISSUE THREAD

**Issue by wlingke** [angular/angular.js#6967]
Let me preface this issue by saying that I am not sure if this issue is specific to my setup and would like to hear if anyone else is seeing this issue.

I am using the Chrome Version 33.0.1750.154 m and I just noticed this issue though I can't really say for certain when it began occurring since I have not changed anything major in my app - which is using angular v1.2.9 - for quite a while.

When I click on a link such as the below

```
//where some_email is 'test@gmail.com'
<a ng-href="mailto:{{some_email}}" target="_blank">test</a> 
```

I expect a new tab to open up and direct to my gmail (which is the case for normal mailto anchor tags). However, with the above, that only occurs some of the time and most of the time, it opens up a new tag with the address bar filled in as `mailto:test@gmail.com`

If I inspect the html, when it works it will show an event handler on the tag:

```
onclick="window.open('https://mail.google.com/mail/?view=cm&amp;tf=1&amp;to=test@gmail.com&amp;cc=&amp;bcc=&amp;su=&amp;body=','_blank');return false;"
```

and when it doesn't work as expected, that handler is not there.

Thanks for the help.

**Comment by istvanpuskas** [comment]
This still seems to be a problem. self workaround does not work for me

**Comment by czebe** [comment]
Chrome on Mac, version 42.0.2311.90 (64-bit)

**Comment by Narretz** [comment]
I assume this was a Chrome bug that has been fixed in the meantime.

**Comment by jiggy2204** [comment]
Sorry, I know I'm waaaaaaaaaaay late - I also had this issue and noticed I was doing '<a ng-href="mailto: {{email}}">'; the way I fixed the issue was to put the entire line in {{email}}:

in export Component{
email = "mailto:name@email.com";
}

Then in the html:
'<a ng-href="{{ email }}">'

Hope this helps some people.
