### ISSUE TITLE
form.FormController behaves differently inside ngRepeat

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/angular.js#6990]
[Example](http://plnkr.co/edit/qbWHbYdbpYqD3HfRA99P?p=preview)

If I place ngForm inside ngRepeat the underlying `form.FormController` behaves strange. Say I have an input field with a `required` attribute I would expect that `form.FormController.$error` is `{"required":false}`, but it is just `{}`.

Because of this I can't use my custom validation handler inside ngRepeat.

**Comment by Narretz** [comment]
This works in 1.3.16 / 1.4.0. If the error ist set, in both cases the whole ngModelCtrl is available in the error array.
