### ISSUE TITLE
delay on $routeProvider in main controller

### ISSUE THREAD

**Issue by plong0** [angular/angular.js#7053]
Assuming I have in my index.html file:

    <html ng-app="MyModule" ng-controller="MainCtrl">

and a MainCtrl looking like:
```
angular.module('MyModule')
  .controller('MainCtrl', function ($scope, $routeParams) {
      console.log('routeParams:'+JSON.stringify($routeParams));
  });
```

$routeParams is coming up empty... unless I wrap it in a very short timeout:
```
angular.module('MyModule')
  .controller('MainCtrl', function ($scope, $routeParams, $timeout) {
    $timeout(function(){
      // do stuff with $routeParams
      console.log('routeParams:'+JSON.stringify($routeParams));
    }, 20);
  });
```

I didn't experience the problem when I used yo cg-angular to generate my project, but started experiencing it after I rebuilt my project using yo angular-fullstack

A couple others having similar trouble: http://stackoverflow.com/questions/17519937/routeparams-is-empty-in-main-controller/22955711

**Comment by gabn88** [comment]
when using multiple nested controllers, it seems the $routeChangeSucces function may hit multiple times and I seem to need the last one. So, for every nesting I need to wait for one more hit. It would be nice if this could 'somehow' be fixed I think.

**Comment by petebacondarwin** [comment]
I don't think this is a bug in Angular. Routing is inherently async. @elliterate is correct here. Either listen to the route change success event or put your route param dependent code in a route controller.
