### ISSUE TITLE
ng-resource and ng-repeat memory leak

### ISSUE THREAD

**Issue by bweston92** [angular/angular.js#7063]
I am currently creating an application that will have a few users 8-9 hours a day, preferably without page reload. (how point of using Angular with push state)

I use ng-resource in order to call my API server for a collection of items. With these items in my included template from the router config I use ng-repeat in order to iterate over each item. When a user clicks and item the $destroy event is called where I clear the collection data from the scope it doesn't get removed. If I go to the "show" view and back to the "list" view over and over I see that all the listeners etc are still there memory from the timeline tab on Chrome.

How I clear the collection. $scope.collection in an array of results from the ng-resource query.
```
$scope.$on('$destroy', function()
{
  $scope.collection = [];
}
```

Is this a bug that they're not being removed? If not, can anyone point me in the right direction to learn a bit more about memory management in Angular

Edit: I am using AngularJS v1.2.16 and NG-Resource v1.2.16

**Comment by Narretz** [comment]
Closing this as no reproduction was provided.
