### ISSUE TITLE
input type="number" is valid when a non numeric value is entered in IE 11

### ISSUE THREAD

**Issue by brik** [angular/angular.js#7070]
When entering text or a combination of text and numbers, form.number.$valid" does not always validate to false.

Examples:
"ddd" validates to true (not OK)
"ddd3" validates to true (not OK)
"3ddd" validates to false 
"33" validates to true

When using the required attribute, it works as expected.

Tested OK in Chrome and Firefox 28.0

Plnkr: http://plnkr.co/edit/uqOkCPxNYQWg8xog1IKi?p=preview

Looks like it is a similar issue to #2144

**Comment by Narretz** [comment]
Tracked in https://github.com/angular/angular.js/issues/10981 with more info
