### ISSUE TITLE
animation bugs / unexpected behaviours

### ISSUE THREAD

**Issue by fxck** [angular/angular.js#7105]
### need of ng-leave on state transition animations
The effect itself doesn't need any manipulation with the state that is being removed, it just needs to stay where it was until the new state is on position, but if I don't specifiy `ng-leave`, it's gonna disappear right away, so I have to specify it

So I thought no problem, I'll specify it, but with the same property on both `ng-leave` and `ng-leave-active`(like opacity: 1), so it visually stays the same, see http://plnkr.co/edit/QsUxRYCH1lpXhywPCNLg?p=preview so the element that was being removed stayed on the place just fine, but didn't get removed at the correct time(I assume) so both enter and leave elements are at one point visible at the same time!

The only way to make it working was to actually set different opacity on `ng-leave-active` see http://plnkr.co/edit/6VRykxIOBr3Tz6FWxViM?p=preview old state still seems to flash there, but only very briefly. But it still sucks having to change that opacity.

### ng-repeat animation not working on initial load
From this(http://plnkr.co/edit/jtXu7ZioEdA4yYxPSSFB?p=preview) example from @matsko I got the impression repeater animation would work on init, but when using it along ui-router, it just does not http://plnkr.co/edit/WHicNh8m22HArcfogbBC?p=preview .. I could make it work by adding a `$timeout` before setting the object.. which kind of sucks

### ng-repeat animation not working after state change
See http://plnkr.co/edit/49WX9PsGbHmGTkQYfHOd?p=preview click on page b and the back to page a.. I have encoutered this quite a few times, it doesn't seem to be able to perform two different animation at the same time..

These angular animation are pretty damn useful.. if only I did not encounter a problem everytime I try to do like anything..

cc @matsko

**Comment by petebacondarwin** [comment]
@matsko - Is this issue now outdated and ready to be closed?

**Comment by Narretz** [comment]
Problem 1) is inconvenient, but I don't think we should include a new state / class for this rare case. If the value ng-leave-active is very similar to the value in ng-leave, there should be no visual difference.

Problem 2) is solves by using $animate.enabled() when appropriate, see https://code.angularjs.org/snapshot/docs/guide/animations

Problem 3) is solved by using https://code.angularjs.org/snapshot/docs/api/ngAnimate/directive/ngAnimateChildren
