### ISSUE TITLE
Why does angularjs include an empty option in select using directive with transclude and replace

### ISSUE THREAD

**Issue by jansoren** [angular/angular.js#7130]
I have recreated the issue here - http://plnkr.co/edit/efaZdEQlNfoDihk1R1zc?p=preview 
Is this behavior a bug? It looks like a rendering timing issue.

See an extended explanation here - http://stackoverflow.com/questions/23103743/why-does-angularjs-include-an-empty-option-in-select-using-directive-with-transc

**Comment by Narretz** [comment]
This will be fixed in the upcoming 1.4.8 and 1.5.0-beta.2
