### ISSUE TITLE
httpbackend header example in doc

### ISSUE THREAD

**Issue by gmoulin** [angular/angular.js#7132]
for methods like "when(method, url, [data], [headers]);"
please add an example for the [headers] possible content in the doc

For instance I try to mock a 400 ish error and I have no idea how to.
Responses in google use an old version of angular mock where the parameters are not identical.

**Comment by gkalpak** [comment]
There are several examples that pass headers and at least one that uses the function version of the `headers` argument of `when/expect`. Hopefully they are sufficient.

If anyone feels like adding more, go ahead :smile:
