### ISSUE TITLE
Using AngularJS inside Firefox addon causes infinite $digest loop

### ISSUE THREAD

**Issue by dannysu** [angular/angular.js#7171]
Calls to history.replaceState errors out with:

```
Message: [Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://jid1-1qqtvsfpouxjea-at-jetpack/angularjs-firefox-seed/data/angular-seed/bower_components/angular/angular.js :: Browser/self.url :: line 4409"  data: no]
```

Somehow because of that any angular app gets into an infinite $digest loop where $locationWatch always thinks the URL is changing.

It seems that history API when running on Firefox isn't usable. However, if I disable using history API by detecting !$window.addon, then angular is usable inside FF addon.

```
history: !!($window.history && $window.history.pushState && !(android < 4) && !boxee && !$window.addon),
```

**Comment by Narretz** [comment]
Lots of people use Angular in FF addon ( see the recent problem with it being banned), so I assume this issue is mute.
