### ISSUE TITLE
ngTransclude: Do you plan to allow default value in case no content is supplied?

### ISSUE THREAD

**Issue by Wizek** [angular/angular.js#7195]
In `ngTranscludeDirective` there is an `$element.empty()` call. Are you planning to make it depend on whether `clone` contains any contents? Then ng-transclude could be used as a hole in the directive's template that could be filled optionally.

**Comment by dmaslov** [comment]
Hi @Wizek @Narretz !
PR #11839 solves this issue

**Comment by Narretz** [comment]
Solved by https://github.com/angular/angular.js/commit/c3ae6ed78e145a9b0c13de7ef95852ba3c467551
