### ISSUE TITLE
Proposal for 'ng-where'

### ISSUE THREAD

**Issue by bwiklund** [angular/angular.js#7208]
A really simple directive I find myself using a lot, particularly for arrays that have a 'current' index, like a slideshow, It would be cool to have some realtime variable assignment without having to write a whole directive each time.

```html
<div ng-where="slide = slides[slideIndex]">
  <h1>{{slide.title}}</h1>
  <p>{{slide.body}}</p>
</div>
```

```javascript
angular.module('ng')

.directive( 'ngWhere', function($parse){
  return {
    scope: true,
    link: function(scope,el,attr){
      var fn = $parse(attr.ngWhere);
      scope.$watch( function(){
        fn(scope);
      });
    }
  }
});
```

This replaces a hack I used to do to achieve the same thing:

```html
<div ng-repeat="slide in [slides[slideIndex]]">
  <h1>{{slide.title}}</h1>
  <p>{{slide.body}}</p>
</div>
```

An alternate syntax, which would need a different implementation:

```html
<div ng-where="{slide: slides[slideIndex], foo: bar()}">
  <h1>{{slide.title}}</h1>
  <p>{{slide.body}}</p>
</div>
```

The downsides would include stuff like people putting expensive things, or real logic, inside the attribute. But overall I think it would be a cool feature for templates.

Thoughts? If there is any interest at all I can put together a real PR with tests and jazz.

**Comment by Narretz** [comment]
We don't want to add more syntactic sugar to core. It's good as a 3rd party directive for people who need it.
