### ISSUE TITLE
Links with bindings not working on WP8 - Wants to download app in store

### ISSUE THREAD

**Issue by Martinspire** [angular/angular.js#7247]
Hi all,

I'm having this issue when using Angular in my project which has a Cordova Windows Phone 8 app. Now when running the app i noticed an issue. Whenever there is an hyperlink with a binding (either in a expression, as {{myVar}} in the href or other) instead of following the new link, i get a popup if i want to look for an app in the store to open such URL. Apparently WP8 is not correctly handling the new link and adds another prefix to your url which it then not recognizes (weird right?) and asks to download it in the WP Store.

When i change the link to use a ng-click handler and use $location.path() inside that handler to redirect the user it works normally but obviously thats something that shouldn't be needed. So whenever i have a url which has parameters to fill, i need to work around this in order to get WP8 working.

**Comment by Gijobs** [comment]
You have to add this :    
 $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|ghttps?|ms-appx|x-wmapp0):/);

in your app.config()
