### ISSUE TITLE
As a big project developper, I want to use only $digest instead of $apply

### ISSUE THREAD

**Issue by XavierBoubert** [angular/angular.js#7298]
In a big project containing a central page with many features, it's not possible to refresh the entire page with $apply everytime because of working time for filters, $watchers, etc. We need to refresh just parts of the UI and it's okay because we are the developers and have the control of these. $apply is not designed for big projects.
So, maybe I'm wrong but I think we really need to change the behavior of AngularJS dirty-checking updates. We need to use $digest most of the time and $apply rarely. For me, ng-click should call the $digest of the current scope and not for the $rootScope, like all of the ng- directives and $http, ectc.

I have wrote a big post on the subject with examples to explain why: https://groups.google.com/forum/#!topic/angular/tswtLq9xbwU

**Comment by gkalpak** [comment]
At this point, I don't think it is reasonable to consider changing the framework's internal `$apply` calls to `$digest` calls, as that would be a huge breaking change (of course you are free to use `$digest` in your own directives/services if you understand the implications).

FWIW, Angular 1 applications have been designed with that assumption for years and breakages for such a change would be too difficult to test for and debug (especially for large apps).

Furthermore, most calls to `$apply` inside the codebase are on the `$rootScope`, which means that there is no overhead compared to `$digest`.
The few places that `$apply` is called on a child scope is for directives (e.g. `ng-event-*`, `ng-model`) and I believe that it is the correct behavior: A change in an input's value is likely to affect much more than it's closest scope (escpecially if wrapped in an `ngIf`/`ngSwitch` or being part of a custom control component directive). Similar for a click handler.

--
That said, if anyone has a compelling usecase for using `$digest` in `ngClick` or any other directive, you can always overwrite it (although I wouldn't recommend it) or create your own.

This feature is certainly not suitable for most apps (thus not suitable for core) and the overhead of rolling out your own `ngClick` directive for a big project is minimal.

--
Closing this as _won't fix_/_not core_.
