### ISSUE TITLE
HTML5 mode exception and possible fix

### ISSUE THREAD

**Issue by kneeclass** [angular/angular.js#7299]
When using a URL in this format `http://localhost:17000/whatever?q=words&s=j` using `$locationProvider.html5Mode(true);` Angular crashes in a `"Cannot read property 'indexOf' of undefined"` exception.

If I add a slash to the URL like this `http://localhost:17000/whatever/?q=words&s=j` everyting works fine.

The reason is that  the `$$rewrite` function inside `LocationHtml5Url` matches none of the "if" or "if else" criterias and returns an `undefined` creating the exception.

I made i quick and dirty hack inside the `$$rewrite`

```javascript
if (url.indexOf("?") !== -1 && url.charAt(url.indexOf("?") - 1) != "/") {
          url = url.replace("?", "/?");
}
```

//Niklas Emevi

**Comment by Narretz** [comment]
I'm gonna close this, as we have no reproduce scenario.
