### ISSUE TITLE
Javascript animations fail to fire within content instantiated by ngRoute

### ISSUE THREAD

**Issue by jamiecopeland** [angular/angular.js#7338]
I've created a simple example where a directive triggers a javascript animation within its link function. If this is placed directly into index.html, with an app on the html tag of the document, the animation is triggered fine, but if the directive is included within a template that is specified for a route, the directive code executes, but the animation is not triggered. I've done this using $animate.addClass(element, 'test') within the directive and inside the animation's addClass handler I've got the conditional if(check className === 'test'). I've even added a timeout as I thought it might be a race conditions thing, but that didn't seem to fix it.

The strange thing is that the test class is being added to the element in question, but that in the case where it fails, ng-animate is not. I've also experienced situations where the animation does work, but only intermittently, although I couldn't seem to recreated this in Plunkr. If you need a code sample of this I can zip and send.

http://plnkr.co/edit/MUUbiKureqatyoG9HKHQ?p=preview

**Comment by Kikketer** [comment]
I have a similar issue, and perhaps it's just my inexperience with angular-animate.  Here's the plunker of a cut down version of what I'm trying to do:

http://plnkr.co/edit/h04DoFrxfnU3DO3M2LWr?p=preview

For some reason the `$animate.addClass` does not trigger.  The `.animation` configuration is never run for the first time either (on load or when the `.fade-out` class is added).

**Comment by Narretz** [comment]
The original issue works in latest 1.4.8 / snapshot.
@Kikketer your animation doesn't work because you need to wrap the $animate call into a scope.$apply.
