### ISSUE TITLE
` or escaping quotes in angular expressions

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular.js#7340]
Sometimes we need to use extra type of quotes in angular expressions
```html
<input type="email"
           required
           form-errors="{
             required: '{{`errorRequired` | translate}}',
             email: '{{`errorEmail` | translate}}'
}">
```

**Comment by danemacaulay** [comment]
@tamtakoe, had this use case as well, i ended up assigning the translateID to a scope variable and reference it in the template

```js
$scope.errorRequiredTranslateID = 'errorRequired';
$scope.errorEmailRequiredTranslateID = 'errorEmail';
```

```html
<input type="email"
           required
           form-errors="{
             required: '{{errorRequiredTranslateID | translate}}',
             email: '{{errorEmailRequiredTranslateID | translate}}'
}">

```

**Comment by Narretz** [comment]
You really shouldn't embed interpolated strings into expressions, see https://code.angularjs.org/snapshot/docs/guide/interpolation#embedding-interpolation-markup-inside-expressions - if you do have to, @tamtakoe has a good workaround.
