### ISSUE TITLE
transclude bug in IE

### ISSUE THREAD

**Issue by maxisam** [angular/angular.js#7388]
Here is the example: [plunker][0] 

It shows nothing in IE all version.

the way to walk around this bug is add space between "}}" and "</"

[0]:http://plnkr.co/edit/1Zetuy?p=info

**Comment by Narretz** [comment]
This is the same issue as described here: https://github.com/angular/angular.js/issues/8659#issuecomment-156267569 and the next two comments.
Bottom line: don't compile the same node twice. It leads to unexpected results, and IE even throws.
