### ISSUE TITLE
In the $routeProvider when using redirectTo, the redirect doesn't wait for the promise to resolve with using the 'resolve' option

### ISSUE THREAD

**Issue by Shazwazza** [angular/angular.js#7394]
For example if I have this:

```
     .when('/logout', {
         redirectTo: '/login/false',             
         resolve: doLogout()
     })
```

Currently it performs the redirect to /login/false without waiting to see if the promise returned from resolve was successful. When using templateUrl, it of course does wait to get a successful result from the resolve option.

**Comment by Narretz** [comment]
Fixed via https://github.com/angular/angular.js/commit/e9865654b39c71be71034c38581a8c7bd16bc716
