### ISSUE TITLE
ngIncludeDirective template src not passed through $sce.getTrustedResourceUrl

### ISSUE THREAD

**Issue by ghengeveld** [angular/angular.js#7399]
$compileProvider uses $sce.getTrustedResourceUrl() to validate a templateUrl before fetching the file: https://github.com/angular/angular.js/blob/8d180383014cbe38d58ff3eab083f51cfcfb8dde/src/ng/compile.js#L1698

The ngInclude directive on the other hand does not, despite the fact that the ngdoc block says it does: https://github.com/angular/angular.js/blob/8d180383014cbe38d58ff3eab083f51cfcfb8dde/src/ng/directive/ngInclude.js#L208

**Comment by aeharding** [comment]
The docs make this clear to me, and the section on ngInclude references the SCE docs for further reading. Is there anythinng in specific in terms of documentation that you think is needed here?

**Comment by Narretz** [comment]
Closing due to lack of feedback, and since the info seems to be present.
