### ISSUE TITLE
Extract ISO date processing from dateFilter

### ISSUE THREAD

**Issue by kasajian** [angular/angular.js#7403]
Currently, someone has to use the moment library or some other 3rd party library to convert an ISO date to a JavaScript date.   Interestingly, Angular already does this, but you can't get to it externally -- not optimally anyway.

Given an iso 8601 date string, you can ask Angular to parse like so:

            var d = $filter('date')(isoDateString);

The Problem is that, d is a string, not a Date object.   If you look at the Angular code, you will see that an actual Date object is, in fact, created, but it's not returned.   Instead, toward the end of the function, it converts it to a string and returns that.    This makes sense, of course, since the whole point of a filter is to convert it to text so it can be displayed in HTML..   But considering that the code is all there, and just needs to be exposed, it might be a good idea to do so.

Now, you can work around this whole thing by doing something like this:
            var asLocalString = $filter('date')(isoDateString, 'medium');
            return new Date(asLocalString);

Basically, you use $filter to convert it to "medium" format, which contains all the information you need, and is compatible with JavaScript's Date() constructor.   Then turn around and create a new Date object using the string.

Converting an iso date string to a JavaScript object is such a useful feature, and missing from JavaScript, that I think we should consider adding it as a utility function:
angular.toDate() that's something like:

    var toDate = function(value) {
        var R_ISO8601_STR = /^(\d{4})-?(\d\d)-?(\d\d)(?:T(\d\d)(?::?(\d\d)(?::?(\d\d)(?:\.(\d+))?)?)?(Z|([+-])(\d\d):?(\d\d))?)?$/;

        if (typeof value === 'string' && value.match(R_ISO8601_STR)) {
            value = $filter('date')(value, 'medium');
        }
        return new Date(value);
    }

But obviously factor the existing code so that you don't have to convert to text then back to date.

Thoughts?

**Comment by gkalpak** [comment]
As has been stated many times, exposing more helper/utility function is not good for the core.
The utility function as primarily used for Angular's internals needs (and unfortunately exposed for the developers' conveninence), but we wouldn't want to have to continue maintaining a helper function or a specific API when the core's needs change.
(Especially for dates which are one of the toughest things to get right and cover all corner-cases.)

There are plenty of dedicated libraries that are very good in what they do and should be used instead.
If it is something very simple, one could also write their own utility method (or small library) for easy inclusion in all their projects (and copy-pasting from the Angular source code is totally fine :stuck_out_tongue: ).

Closing as won't implement.
