### ISSUE TITLE
ngAnimate leave class removed before element is removed from the DOM

### ISSUE THREAD

**Issue by dpogue** [angular/angular.js#7404]
When running `$animate.leave(element)` (in Angular 1.2.16), the following events occur in order:

1. `.ng-animate` is added to the element.
2. `.ng-leave` is added to the element.
3. `.ng-leave-active` is added to the element.
4. The element animates.
5. `.ng-leave-active` is removed from the element.
6. `.ng-leave` is removed from the element.
7. `.ng-animate` is removed from the element.
8. The element is removed from the DOM.

On mobile, this ordering is causing the element to flash to a pre-animation state between steps 5 and 8 due to the `.ng-leave` classes being removed.

Particularly in the case of `ng-leave`, since the element is being removed from the DOM it should be possible to avoid removing those classes to ensure that the element is removed from the DOM without there being any point in time where the classes are not applied.

**Comment by Narretz** [comment]
Closing due to lack of feedback.
