### ISSUE TITLE
feat(http): Please make buildUrl public

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/angular.js#7429]
Feature Request:
It would be great if [`buildUrl`](https://github.com/angular/angular.js/blob/ad4336f9359a073e272930f8f9bcd36587a8648f/src/ng/http.js#L942) would be public. It is a function which was copied nearly identical into [Restangular](https://github.com/mgonto/restangular/blob/master/src/restangular.js#L694) and I had to do the same for a private module.

**Comment by parliament718** [comment]
+1 for pkozlowski's solution ... moving buildUrl into a $urlBuilder sevice seems like a good solution to me. Need this functionality

**Comment by donaldpipowitch** [comment]
Sounds good to me. +1 for a `$urlBuilder` service.

**Comment by jmendiara** [comment]
I hope is not too late for debate...
@pkozlowski-opensource  and mates, here you have another approach that solves the same issues and addresses @petebacondarwin concerns, giving more control to userland and keeping core simpler, IMHO.

**Comment by jmendiara** [comment]
@donaldpipowitch @junhanamaki @ivanff Here you have another approach ready to be used in angular > v1.2
http://codepen.io/jmendiara/details/bdGbPN/
