### ISSUE TITLE
$resource: support data defaults (similar to params)

### ISSUE THREAD

**Issue by fiznool** [angular/angular.js#7473]
Right now, you can add default `params` to a $resource action. These `params` will be automatically added to the resulting `params` object if they are not explicitly specified when making the request. It would be great if this could also be the case for the postBody when making a POST.

At the moment, if you want to add in any default body properties, you have to do the following:

``` js
$resource('/api/cats/:id', {}, {
  create: {
    method: 'POST',
    transformRequest: function(data) {
      data.name = data.name || 'Chester';
      return angular.Json(body);
    }
  }
}
```

It would be great if you could do this instead:

``` js
$resource('/api/cats/:id', {}, {
  create: {
    method: 'POST',
    data: {
      name: 'Chester'
    }
  }
}
```

**Comment by ilanbiala** [comment]
Defaults would be nice, but does it make more sense to handle this in the next major `$resource` update?

**Comment by Narretz** [comment]
Closing because of low demand and easy workaround / implementation with current APIs.
