### ISSUE TITLE
jqLite injection makes some functionality unusable

### ISSUE THREAD

**Issue by zachsnow** [angular/angular.js#7585]
See:

https://github.com/angular/angular.js/blob/d71dbb1ae50f174680533492ce4c7db3ff74df00/src/jqLite.js#L622

Roughly, we check if the first argument is an object, and assume that we are dealing with a setter. But some methods, for instance `inheritedData`, can take an array (which is an object) when acting as a _getter_.

We could check for `isObject(arg1) && !isArray(arg1)` instead perhaps, to expose the extended functionality of `inheritedData` and any other such methods, probably without breaking much, at least within Angular.

I will try it and test it, if it is something that could conceivably be accepted. Cheers.

**Comment by mgol** [comment]
I don't think we want to change the behavior of `inheritedData` at this point (especially taking into account age of this issue) so I'm closing this.

Please comment if you disagree.
