### ISSUE TITLE
ngModel is not updated when selection in <select /> is done with keyboard up/down arrows

### ISSUE THREAD

**Issue by Crimscent** [angular/angular.js#7600]
jsFiddle: http://jsfiddle.net/Crimscent/wj3rC/

AngularJS version 1.2.16
Affected browsers: Chrome 35.0.1916.114, FF 29.0.1 (didn't test on earlier versions).
Not affected browsers: IE 9, IE 10, IE 11.

Steps in Chrome:
1. Select Item 1 -> $scope.selectedItem.Id === 1
2. Without losing focus press keyboard down arrow -> $scope.selectedItem.Id === 1
3. Without losing focus press keyboard down arrow ->  $scope.selectedItem.Id === 3
After this 3 steps $scope.selectedItem starts updating as it should

Steps in FF:
1. Select Item 1 -> $scope.selectedItem.Id === 1
2. Without losing focus press keyboard down arrow -> $scope.selectedItem.Id === 1
3. Without losing focus press keyboard down arrow ->  $scope.selectedItem.Id === 1
It doesn't work at all, $scope.selectedItem is updated only when items are selected with mouse.

In IE 9-11 $scope.selectedItem is always updated as it should.

**Comment by Narretz** [comment]
Closing as duplicate of #9134
