### ISSUE TITLE
Angular Select select as label for value in array syntax broken for nullable

### ISSUE THREAD

**Issue by basarat** [angular/angular.js#7605]
`select as label for value in array` shows an empty box if we drive the nullable from the model 

For example for model 
```
$scope.colors = [
      {name:'nothing', shade:null},
      {name:'red', shade:'dark'}
    ];
```
compare good version (`color.name for color in colors`)

![image](https://cloud.githubusercontent.com/assets/874898/3100347/60889e7e-e615-11e3-8956-3a7ff6c97afa.png)

with bad version (`color.shade as color.name for color in colors`)

![image](https://cloud.githubusercontent.com/assets/874898/3100348/64d9456e-e615-11e3-83e9-391637748829.png)

Sample : http://plnkr.co/edit/MLgOTj9tjd9HF56Jm5RU?p=preview

**Comment by petebacondarwin** [comment]
This is fixed by #10639. See http://plnkr.co/edit/pf0EIrZbb9qXa7Oqy6kc?p=preview
