### ISSUE TITLE
Scope changes unexpectedly when added to DOM before parser

### ISSUE THREAD

**Issue by snadrus** [angular/angular.js#7621]
http://plnkr.co/edit/i24uDLodMNI9CSwwN5BO?p=preview
Adding a .run(function(myFactory){}); causes factory-created scopes to be ignored on items added to the DOM.

I presume it's because the HTML parser reparents it. 
Use Case: display library errors, which could occur before or after the parser. (Though in this case it's explicitly before, for simplicity).

**Comment by Narretz** [comment]
I agree with @caitp
