### ISSUE TITLE
enhance($q): log exceptions generated from 'finally' callbacks

### ISSUE THREAD

**Issue by tdakhla** [angular/angular.js#7624]
Exceptions that occur inside of a `$q finally` callback should be logged via `exceptionHandler(e);`, just as is done inside of other `$q` callbacks.  The `exceptionHandler` line should be added here right before the `return`: https://github.com/angular/angular.js/blob/58f5da86645990ef984353418cd1ed83213b111e/src/ng/q.js#L308.

Here's a simple example that shows current state (snapshot) behavior, and I would expect undefinedB to be shown in the console as well:
http://jsfiddle.net/e8EAv/

**Comment by NevilleS** [comment]
Hey @pkozlowski-opensource, I'm curious about this one... In my app, I've decorated `$exceptionHandler` to automatically report uncaught exceptions to the mothership, which is quite nice. However, I noticed this discrepancy between `then` and `finally` recently (the former invokes `$exceptionHandler`, the latter quietly rejects the promise and continues). It'd be nice if it was consistent, but I can understand it'd be relatively hard to land a PR for this :smile:

Can you think of a decent workaround that I could use locally to make `finally` handlers also report to `$exceptionHandler`? Theoretically I could just decorate the `$q` service and reimplement `finally` but...

**Comment by Narretz** [comment]
This works as expected since 1.6.0
