### ISSUE TITLE
Angular does not report that multiple directives ask for isolated scope on same tag if one of these directives is ng-controller and other is custom directive with lower priority (less than 500)

### ISSUE THREAD

**Issue by KamilSzot** [angular/angular.js#7629]
Example http://jsfiddle.net/ZqAw3/1/ shows two directives. One has default priority lower than 500 the other has priority 500. Error about "Multiple directives asking for isolated scope on tag" shows up only in case of using second directive with ng-controller not the first one.

**Comment by KamilSzot** [comment]
This behavior is still observed in angular v1.3.15 
http://jsfiddle.net/ZqAw3/3/

@Narretz: BTW, why was that classified as not a bug? Failure to report error when it should be reported is not a bug?

**Comment by Narretz** [comment]
I cannot repro this in Angular 1.3.x and higher. There's only one error thrown, but it happens for d1 and d2

**Comment by KamilSzot** [comment]
I updated the example for new angular.module() parameters: http://jsfiddle.net/ZqAw3/4/

Problem still observed 1.5.0-build.4316 version of Angular.

There's only one error reported:

Error: [$compile:multidir] Multiple directives [ngController, d1 (module: App)] asking for new/isolated scope on: <div ng-controller="C" d1="">

Nothing about d2 directive requesting isolate scope on same tag as ngController.

**Comment by KamilSzot** [comment]
It seems that it works in current version of Angular. Example I gave was not a good one because Angular always displays just the first error. 

Bug manifested itself by not reporting error on d1 but on d2. I mistakenly reported that it's still present on 1.3.x while it was actually it was last present on 1.2.29: http://jsfiddle.net/ZqAw3/5/ (error message Error: [$compile:multidir] Multiple directives [d2, ngController] asking for new/isolated scope on: <div ng-controller="C" d2="">)
and on 1.3.0 it works fine: http://jsfiddle.net/ZqAw3/6/ (error message Error: [$compile:multidir] Multiple directives [ngController, d1] asking for new/isolated scope on: <div ng-controller="C" d1="">)
