### ISSUE TITLE
$cookies doesn't represent current state of document.cookie

### ISSUE THREAD

**Issue by amaltson** [angular/angular.js#7631]
In an `$http` login call that we make, the resulting header has a `Set-Cookie`. While the cookie does get set in the browser, i.e. I can see it in `document.cookie`, it doesn't make it's way to `$cookies`.

Below is the response header setting the cookie:
![response-header-cookie](https://cloud.githubusercontent.com/assets/167443/3122303/ca255f4c-e765-11e3-8248-d459c4e194c0.png)

And here is `document.cookie` indicating the cookie exists but `$cookies` doesn't see it.
![nothing-in-cookies](https://cloud.githubusercontent.com/assets/167443/3122307/d87924d4-e765-11e3-8d62-76ef00cb61c6.png)

The strangest thing is on the next Angular action I take, `$cookies` has the cookie. The example above is already wrapping the `$cookies` check in a `$timeout` to give the browser time to digest.

The workaround right now is to parse `document.cookie` and set `$cookies` manually, but this is super hacky.

**Comment by amaltson** [comment]
If `$browser.cookies()` is the new hotness, I'll close off this issue.

**Comment by mkonecny** [comment]
> If `$browser.cookies()` is the new hotness, I'll close off this issue.

It's not the new hotness. Just upgraded from Angular 1.3 -> 1.4 and the function no longer exists.
