### ISSUE TITLE
ngTouch ngClick 'fast' click not working on IPad

### ISSUE THREAD

**Issue by hecmec** [angular/angular.js#7690]
Hello,

A click on an element with ng-click on iPad will not trigger the 'fast' click behavior.
Angular: 1.2.4
ngTouch 1.2.4 (version 1.2.13 has not changed in the parts concerned)

**Reproducible**: always
**Browsers**: Safari iPad
**Operating system**: iOs 7.1

**Steps to reproduce**:
- ngTouch module is referenced and loads correctly (I can step inside with Safari connected to an iPad)
- put a standard link with a ng-click directive in a template.
```html
<div data-ng-app="testApp">
    <main data-ng-controller="MainController">
        <a data-ng-click="logTime()">Link</a>
    </main>
</div>
```

- set a breakpoint inside the touchend handler of the ngTouch.ngClick directive
   element.on('touchend', function(event) {

- result
    e.clientX will be undefined, as well as e.pageX etc.
    so the calculated distance (dist) is NaN
    and the test 
      if (tapping && diff < TAP_DURATION && dist < MOVE_TOLERANCE) {
    will always fail.

- possible fix: 
    in case that e.clientX is undefined you might try e.changedTouches[0].clientX which is defined (used in the swipe part)

**Comment by liviubunda** [comment]
+1 I having the same problem across IOS devices, the click delay fix is not working.

**Comment by pluff** [comment]
+1 same problem on IOS devises.

**Comment by csbrandt** [comment]
+1 on angular v1.2.4 and iOS 7.0.4

**Comment by vinkla** [comment]
+1 on angular v1.3.0 and iOS 7.0.4

**Comment by jdrouet** [comment]
+1 same problem

**Comment by liviubunda** [comment]
This should not be labeled as frequency: low, it affects all current Safari versions on IOS devices.

**Comment by atroy** [comment]
+1 please remove frequency low iOS 8.2 and still broken!

**Comment by mato75** [comment]
+ 1 any progress, because this is really annoying.

**Comment by liviubunda** [comment]
Managed to implement a fix, but I haven't tried it on any other browser than IOS Safari 8.0 (build 600.1.4) using Angular 1.2.26. It still feels a bit sluggish compared to Chrome on Android.

There are two event handlers that initialize the 'touches' variable using the wrong data.

For 'touchstart' you need to replace the line:
    var touches = event.touches && event.touches.length ? event.touches : [event];
with:
    var touches;
    if (event.touches && event.touches.length) {
        touches = event.touches;
    }
    else if (event.originalEvent && event.originalEvent.touches) {
        touches = event.originalEvent.touches;
    }
    else {
        touches = [event];
    }

For 'touchend' you need to replace the line:
    var touches = (event.changedTouches && event.changedTouches.length) ? event.changedTouches :
        ((event.touches && event.touches.length) ? event.touches : [event]);
with:
    var touches;
    if (event.changedTouches && event.changedTouches.length) {
        touches = event.changedTouches;
    }
    else if (event.touches && event.touches.length) {
        touches = event.touches
    }
    else if (event.originalEvent && event.originalEvent.changedTouches) {
        touches = event.originalEvent.changedTouches;
    }
    else {
        touches = [event];
    }

I'll submit a pull request when I'm done testing.

**Comment by liviubunda** [comment]
I checked 1.4 rc1 and this code is already there. It was fixed by https://github.com/angular/angular.js/commit/06a9f0a95f0e72fa2e9879fe8a49e9bf69986a5f

**Comment by pkozlowski-opensource** [comment]
Thnx @liviubunda

**Comment by glomotion** [comment]
hello there!

We seem to still be noticing 300ms lag with ng-click events on iOS (8.x-9.x). Tested using angular 1.4.7 both with and without angular-touch included:

http://codepen.io/glomotion/pen/meKNqM

**Comment by BonnieDoug** [comment]
As above experiencing the same issue:

`iOS 9.3.1
Angular 1.5.5`
