### ISSUE TITLE
ngStyle ignores properties with underscore only when jQuery is installed

### ISSUE THREAD

**Issue by websirnik** [angular/angular.js#7744]
Default expected behaviour:
 - `ng-style="{background_color:'blue'}"` translates to `style="background-color: blue"`
 - `ng-style="{backgroundColor:'blue'}"` translates to `style="background-color: blue"`
 -  in Plunker(no jQuery): http://plnkr.co/edit/lCBUkbKeqLxtkTpHx0bo?p=preview

When jQuery is installed, the first declaration via undescope is ignored, the output is the following:
 - `ng-style="{background_color:'blue'}"` translates to nothing
 - `ng-style="{backgroundColor:'blue'}"` translates to `style="background-color: blue"`
 - in Plunker(with jQuery): http://plnkr.co/edit/G13qq3ReaMprVnI8p7sv?p=preview

Is there a workaround that would enable properties with underscore to be processed?

**Comment by mgol** [comment]
We'll align jqLite with jQuery here in Angular 1.6.

**Comment by mgol** [comment]
PR to align with jQuery: #15249.
