### ISSUE TITLE
Slow ng-repeat in IE [All versions]

### ISSUE THREAD

**Issue by vko-online** [angular/angular.js#7755]
I have strange ng-repeat behavior, and it exists only in IE, (for sure, it works perfect in chrome, ff, opera)
my ng-repeat is a little heavy, it structured to look good and alive, so i made 4 divs inside 1 li. mm let me show code better
http://pastebin.com/5RTMsW56
as you can see i have 4 divs inside 1 li, all of them are decorated and loaded to dom, turns out that 1 li has 4 images, and i have almost 23 li. Thought i was making mistake and removed 3 divs from 1 li, mean i have 23 li each with 1 div, but it's the same! IE still slow. Btw "slow" i mean really slow, loads data very slower than chrome/ff, and when i drag, (yes i  wrapped it with jquery, it's gridster plugin) it's awefully slow. Is it issue or i might doing something wrong? ask code if needed.
after bootstrapped http://pastebin.com/HPYcMXZh

**Comment by Narretz** [comment]
So I don't think this was / is actionable. There will always be performance differences between browsers, and as soon as we involve 3rd party plugins it's only going to get worse.
