### ISSUE TITLE
Change in decoding URL in routing only when using Firefox. 

### ISSUE THREAD

**Issue by MaissaJabri** [angular/angular.js#7791]
I have this element in the DOM; 
```html
<a class="k-in" href="/index.html#/scenario/DG/CCS/21x3/CCS%20%234%20%28June%2028%29">CCS #4 (June 28) </a>. 
```
When I click on the link above I'm redirected to the following URL; `http://localhost:8085/index.html#/scenario/DG/CCS/21x3/CCS%20%234%20%28June%2028%29#4%20%28June%2028%29`
When I added the following code;

```javascript
$rootScope.$on('$locationChangeStart', function (arg, newl , old) {
   console.log(old , ' TO ', newl);
});
```
In the Firebug console I can see 3 redirections:

```
1- 
http://localhost:8085/index.html#/scenario/DG/TRAD/15x7/TRAD%20Original TO http://localhost:8085/index.html#/scenario/DG/CCS/21x3/CCS%20%234%20(June%2028)
2- http://localhost:8085/index.html#/scenario/DG/CCS/21x3/CCS%20%234%20(June%2028) TO http://localhost:8085/index.html#/scenario/DG/CCS/21x3/CCS%20#4%20(June%2028)
3- http://localhost:8085/index.html#/scenario/DG/CCS/21x3/CCS%20#4%20(June%2028) TO http://localhost:8085/index.html#/scenario/DG/CCS/21x3/CCS%20%234%20(June%2028)#4%20(June%2028)
```

The issue doesn't take place when the element's name doesn't contain the hash character and I only see one redirection like the first one above. The issue doesn't take place in Chrome either. 

Any clues please,
Thanks!

**Comment by Narretz** [comment]
Closing because no info was provided.
