### ISSUE TITLE
Animate causes error if on repeat on a changing array with ng-if

### ISSUE THREAD

**Issue by CILLERt** [angular/angular.js#7821]
This is a bit of an edge case. But when an array changes while ng-animate is evaluating an ng-if, and this happens quickly there is an error:
TypeError: Cannot read property 'ng-leave' of undefined

This only happens when done quickly, but I have a drag an drop implementation that if dragging and dropping quickly triggers the issue.

For a demo of the issue:
http://plnkr.co/edit/FMGx6QOElQvRI5K6cbNq?p=preview

When bashing "toggle" quickly the error will occur.

**Comment by petebacondarwin** [comment]
@matsko can you take a look and see if this issue is still valid?

**Comment by Narretz** [comment]
This is working in 1.4.8. It's not working in 1.2.28, but this branch doesn't receive fixes anymore.
