### ISSUE TITLE
unclear signature for $rootScope.Scope#$watch

### ISSUE THREAD

**Issue by rasenplanscher** [angular/angular.js#7873]
The current signature for `$watch` is `function(watchExp, listener, objectEquality)`, which may lead to confusion, especially when reading the description. See https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L286-L289 – here, the first parameter is called the _listener function_, while the second one is called the _callback handler_. ~~I think the naming in the description is more appropriate – therefore I propose to change the signature to `function(listener, callback, objectEquality)`, or to avoid confusion with the old one: `function(watcher, callback, objectEquality)`~~ I propose `function(watch, callback, objectEquality)` as it seems much clearer.

In the same vein, `listener`should be called `callback` in `$watchGroup` and `$watchCollection` as well.

**Comment by Narretz** [comment]
I don't see *listenerFunction* or *callbackHandler* anymore, so I think we're good now
