### ISSUE TITLE
Better error reports

### ISSUE THREAD

**Issue by bingalls** [angular/angular.js#7896]
Install & run the demo at https://github.com/mcasimir/mobile-angular-ui
Next, rename some of the template files, such as carousel.html.

When the endless loop times out (faster on Firefox, than Chrome), you'll see an error, regarding too much nesting of digest loops.

How can we make these error messages more intelligible?
Keep up the great good!

**Comment by Narretz** [comment]
I don't think this issue is directly related to angular core.
