### ISSUE TITLE
Angular route on IE9 with “compatibility view” crash the browser

### ISSUE THREAD

**Issue by acostaf** [angular/angular.js#7916]
Hi

I am using angular version 1.2.10 (also test it with 1.2.18 and 1.2.10) to create an app that user can go to the main page that it is list of item of some sort and another page for item detail also users can go directly to this page using deep linking.

So the problem it is related with deep linking combine with IE9 "compatibility view", as soon as the user go directly to the detail page IE9 crashes, the symptoms are that browser will reload all the javascript files in a loop will ie dies, I have seen IE9 downloading all the js files more than 500 times or till machine memory runs out

I have already try setting a meta header on the file as name="X-UA-Compatible" value="IE=9", but this change the document mode not the browser mode that will be still on IE9  "compatibility view".

**Comment by Narretz** [comment]
Compatibility mode is not supported.
