### ISSUE TITLE
Routing-Navigation on IE9 different to Chrome

### ISSUE THREAD

**Issue by acostaf** [angular/angular.js#7956]
HI all 

I am trying to migrate to version 1.2.18 from 1.2.16, implementing routing with <base href="/ContainerManagement/"/>.

So clicking /ContainerManagement/ContainersByUnit/1/749 will navgate to /ContainerManagement/#/ContainersByUnit/ContainersByUnit/1/749 on IE9 adding ContainersByUnit twice but the expected on chrome,  if I change the link from /ContainerManagement/ContainersByUnit/1/749 to /ContainerManagement//1/749 the result is the expected on IE9 but failed in chrome navigating to /ContainerManagement//1/749

Help traped on version 1.2.16

**Comment by Narretz** [comment]
This is fixed.
