### ISSUE TITLE
Cannot timeout $resource action more than once

### ISSUE THREAD

**Issue by Hartimer** [angular/angular.js#7974]
$resource uses $http underneath. $http (and $resource by inheritance) supports cancelling requests by passing a number or promise to the timeout parameter of the config object.

The issue is that the $http.config must be defined along side the resource itself. This means that the promise passed to the resource can only be resolved (effectively cancelling the request) once.
This makes the timeout useless for a resource, which conceptually speaking might be long-lasting and have actions called on it multiple times.

My suggestions

Option 1:
Support passing $http configurations with each resource action call, e.g.: 

``` Javascript
myResource.$myAction(
   {/**/}, 
   {timeout: ...}, 
   <success_handler>, 
   <error_handler>
)
```

Disruptive since it effectively changes the signature of the method, unless the new attribute is added as the last arg.

Option 2:
Make the timeout property support number|promise|function, that way we could specify a function that would provide a promise (or number) each time the request was made

It would be my first PR but I would like to implement one or both of the options if you find them valid.

**Comment by gkalpak** [comment]
This has been 98528be.
