### ISSUE TITLE
Passing default parameters to $routeProvider

### ISSUE THREAD

**Issue by darkoromanov** [angular/angular.js#7983]
When two routes uses the same template and the same controller would be useful if we could pass static parameters to $routeParams Look this (real) example:

```
$routeProvider.when('/site/contents/:obj/:parent/:isnew?', {
    templateUrl: '/partials/site/data.html'
});

$routeProvider.when('/site/contents/new-obj', {
    templateUrl: '/partials/site/data.html'
});
```

as you can see the second route should statically set the _isnew_ parameter, but currently it can't be done.

**Comment by Narretz** [comment]
Since this can be implemented with the current API, I'm going to close this feature request
