### ISSUE TITLE
the link with the right mouse button in firefox

### ISSUE THREAD

**Issue by krom-xr** [angular/angular.js#7984]
When i click right mouse button on link with hash in firefox. Brower goes to link url.
This bug occurs when I use $location as param in run function

See jsfiddle http://jsfiddle.net/kromxr/76fKM/12/

angular-version - any
browser - firefox 30.0
os - OS X 10.9.3

**Comment by BrianMcBrayer** [comment]
So... what are the chances that this will make it into 1.3? Our enterprise product is not yet ready to be 1.4-enabled, and this is currently a bug. I can back-patch it, but I'd prefer instead to get it from an official repo.

Thanks!

**Comment by Narretz** [comment]
@BrianMcBrayer have you checked out 1.3.13? It looks like the code is in: https://github.com/angular/angular.js/blob/v1.3.13/src/ng/location.js Maybe it didn't make it to the changelog?

**Comment by BrianMcBrayer** [comment]
You're right. It wasn't in the changelog--didn't think of looking at the source. Everything's peachey! :)

**Comment by petebacondarwin** [comment]
It didn't get officially backported but then sneaked in as part of this commit...

https://github.com/angular/angular.js/commit/939ca37cfe5f6fc35b09b6705caabd1fcc3cf9d3
