### ISSUE TITLE
ng-model does not update displayed select value on Chrome/Android

### ISSUE THREAD

**Issue by jacekwasowski** [angular/angular.js#7986]
Chrome v35.0.1916.141
Android 4.2.2
Angular 1.2.18

When changing the value of select the model is properly updated, however select keeps displaying the old value until it loses focus. 

    <select name="x" ng-model="x">
    <option>1</option>
    <option>2</option>
    </select>

**Comment by risingfish** [comment]
There is a bug filed with the Chromium project for this at https://code.google.com/p/chromium/issues/detail?id=415505 . The more folks who star it the higher it will bubble up.

**Comment by Narretz** [comment]
Dupe of https://github.com/angular/angular.js/issues/4836
@risingfish is right, let's star the issue.
