### ISSUE TITLE
$q reports errors in promise callbacks even when they are caught

### ISSUE THREAD

**Issue by domenic** [angular/angular.js#7992]
Plunker: http://plnkr.co/edit/5vMj4AJibWcnTKYR5z73?p=preview

I have caught the error and used it to display useful information to my user in the UI. However, Angular still logs a big ol' stack trace to the console.

This isn't a spec compliance issue (since the error isn't thrown, just logged), but it's a developer ergonomics issue. I don't understand how using $q on any reasonably large promise project would not just result in a console filled with spurious errors.

As always, the correct time to report a rejection as unhandled is debatable. Bluebird does it at the end of turn, whereas Q doesn't do it at all, relying on `.done()` instead. But this isn't even about unhandled rejections---it's about all rejections!

The Bluebird strategy seems like a pure win: it would remove this spurious reporting, but keep it for any cases that could potentially be real.

**Comment by just-boris** [comment]
Now I can silently rethrow error using `$q.reject()`

```js
$http.get().catch(function(err) {
   if(!canBeHandled) {
       // propagate error to further promises
       return $q.reject(err);
   }
});
```

But that means that all my services/controllers which use `$http` should include `$q`. This is a bit annoying. It would be better to propagate error using `throw` as well as other promise libraries do.

```js
$http.get().catch(function(err) {
   if(!canBeHandled) {
       // causes call to $exceptionHandler
       throw new Error(err);
   }
});
```
Now it calls `$exceptionHandler` and that means that it can't catch and suppress that error in further promises in chain.

**Comment by op1ekun** [comment]
@just-boris I totally agree :+1: 

I run into this problem while simplifying services based on `$http` (I was using Bluebird for a while, but calling `$apply` on consumer's side was cumbersome).

I spent some time to figure out that `throw new Error()` doesn't reject $http promise.
Quite annoying...

Thankfully the project is quite fresh so refactoring is not a major issue.
However I can feel the pain of ppl throwing errors in their `$http` services.

**Comment by xieranmaya** [comment]
What is thought to be the desired behavior is that it only report rejected promises' errors when there is no rejection handler registered on the promise(that is, never called then(*,handler) on it), which is like Q or Bluebird or ES6 primitive Promise.

#13653
