### ISSUE TITLE
Bad performance when selecting an item the first time in select with many items

### ISSUE THREAD

**Issue by floydqwz** [angular/angular.js#8019]
When having many items in a <select> (more than a couple of thousand items), selecting an item becomes really really slow the first time. In this example I add 25000 items. Selecting an item the first time takes around 12s.

http://jsfiddle.net/2W7Kx/1/

Seems like "function render()" is responsible for almost all execution time, with these two lines being suspicious:

    // TODO(vojta): can't we optimize this ?
    scope.$watch(render);

I also initially added a stackoverflow question about the issue: http://stackoverflow.com/questions/24470563/angularjs-performance-for-select

**Comment by petebacondarwin** [comment]
#10639 improves this performance dramatically http://plnkr.co/edit/CBwddTL3WTwEVjAWCOQQ?p=preview
