### ISSUE TITLE
ng-hide does work when using css keyframe sprite animations

### ISSUE THREAD

**Issue by michelalbers** [angular/angular.js#8033]
When using CSS3 keyframe animations ng-hide does not work instantaneously but delayed. 

**CSS Sprite animation Code (stylus):**
```css
.spinner
  width 100%
  height 30px
  background-image url("../assets/images/spinner_sprite.png")
  animation play 1s steps(19) infinite
  background-repeat no-repeat
@keyframes play
  from 
    background-position center 0px
  to 
    background-position center -570px
```

**Dirty Fix**
```css
.ng-hide { display: none !important; }
```

fixes the issue but does not feel right :/

**Comment by samccone** [comment]
Just a note, this bit me and ate a few hours of time :pizza: :clock10: , perhaps elevating a note about this in the `ng-if`, `ng-show`, `ng-hide` directive docs would prevent the pain for others. 

More than willing to add the docs just let me know, thanks again for this great lib :palm_tree:

**Comment by samccone** [comment]
thanks @Narretz :clap:
