### ISSUE TITLE
Bug: $watches doesn't bind starts off as undefined

### ISSUE THREAD

**Issue by funkjunky** [angular/angular.js#8084]
In my example I didn't defined $scope.document, then in my directive added a $watch on $scope.binding, which was bound to $scope.document.government [keep in mind, at this time $scope.document is undefined], then when $scope.document is finally filled in from the return of a $http call, the watch still doesn't work.

However if I set $scope.document = {} initially, then set the watch, everything works, which leads me to believe Angular is doing magic parsing of properties ANYWAYS, so why the heck does it matter if I set it to {} or undefined, your algorithms ignore the reference anyways.

Here is the SO I wrote in more detail of the issue I came up with:
http://stackoverflow.com/questions/24578453/watch-is-triggered-on-controller-but-not-directive

As I said, I've resolved the issue by setting document={}, but I feel I shouldn't need to do that and that others will be confused when their $watches don't work.

**Comment by Narretz** [comment]
Very old issue, but out of curiosity, I tried to reproduce this problem, but couldn't: http://plnkr.co/edit/kcPfnblUOR1GSejit7Eo?p=preview Maybe you had something very special in your directive or this was actually a bug and has been fixed.
