### ISSUE TITLE
ngMessage and ngBind do not work together

### ISSUE THREAD

**Issue by 43081j** [angular/angular.js#8089]
If you have a custom validation key (such as `server` in this case), and try bind the `ngMessage` element to some object you presumably have the error message in, it does not work.

```html
<div ng-if="myForm.test.$dirty" ng-messages="myForm.test.$error">
    <span ng-message="server" ng-bind="errors.test"></span>
</div>
```

The above does not work, the span remains empty but visible and `errors.test` is indeed populated (and visible in scope, by trying `angular.element($0).errors.test`).

If you use a child, like so:

```html
<span ng-message="server">
    <span ng-bind="errors.test"></span>
</span>
```

This works correctly. 

Is this expected functionality or a bug? I have no issue with having to use a child if it is expected to behave this way.

Example [here](http://jsfiddle.net/U3e2t/).

**Comment by OliverKK** [comment]
Same here. Any news on this?

**Comment by matsko** [comment]
This should work now in 1.4

**Comment by matsko** [comment]
https://github.com/angular/angular.js/commit/c9a4421fc3c97448527eadef1f42eb2f487ec2e0

**Comment by vedraan** [comment]
Note that it also works like this: ```<span ng-message="server">{{errors.test}}</span>```

**Comment by matsko** [comment]
Closing this for now since it is working in 1.4.

**Comment by parliament718** [comment]
I'm experiencing this bug in 1.4.5.

**Comment by Narretz** [comment]
It seems like ng-message + ng-bind was never actually solved. It really doesn't work in 1.4.7: http://plnkr.co/edit/bubtiS5bULNiCw5ach6Y?p=preview

**Comment by yerol** [comment]
You can place the message in a separate span inside ng-message until this issue is resolved. As in:
```
<span ng-message="required">
    <span ng-bind="errors.required"></span>
</span>
```
