### ISSUE TITLE
IE8: Unable to get property '1' of undefined or null reference (problem with paren-wrapped functions)

### ISSUE THREAD

**Issue by nlwillia** [angular/angular.js#8109]
```
var f = (function(){});
console.log(f.toString());
```
In most browsers, this will return `function(){}`, but in IE8, it returns `(function(){})`.  In angular's injector `annotate` method, when it tries to parse the function for injection references, the regular expression does not allow for the possibility of enclosing parentheses in the string representation of the function, and the [`argDecl[1]`](https://github.com/angular/angular.js/blob/36831eccd1da37c089f2141a2c073a6db69f3e1d/src/auto/injector.js#L100) expression fails as a result.  I know that angular is moving away from IE8 support, but this is still in the 1.2.x branch.

Why is this a problem?  I ran into it because the output generated by traceur does a lot of function wrapping.  Traceur is also incompatible with IE8, but a lot of that is its runtime include which isn't necessary if you're just using it for translation of syntax like arrow functions.

Verified in angular 1.2.19 and IE8.  A workaround is to run your code through a minifier that will strip out the extraneous punctuation.

**Comment by lgalfaso** [comment]
IE8 is no longer supported, and no more bug fixes are going to 1.2.x
