### ISSUE TITLE
ng-strict-di error should point to the code that wasn't annotated

### ISSUE THREAD

**Issue by mzgol** [angular/angular.js#8119]
Currenly `ng-strict-di` errors like like that:
```
Error: [$injector:strictdi] http://errors.angularjs.org/1.3.0-build.2906+sha.cf4f85f/$injector/strictdi?p0=BadController
    at Error (native)
    at https://docs.angularjs.org/angular.min.js:6:472
    at Kb (https://docs.angularjs.org/angular.min.js:33:247)
    at e (https://docs.angularjs.org/angular.min.js:35:473)
    at Object.instantiate (https://docs.angularjs.org/angular.min.js:36:262)
    at https://docs.angularjs.org/angular.min.js:69:294
    at https://docs.angularjs.org/angular.min.js:55:66
    at q (https://docs.angularjs.org/angular.min.js:7:416)
    at E (https://docs.angularjs.org/angular.min.js:54:435)
    at g (https://docs.angularjs.org/angular.min.js:48:319)
```
(see the example on this page: https://docs.angularjs.org/api/ng/directive/ngApp)

This doesn't help to find the place which wasn't annotated; this is especially important in production code that is often a huge few-lines file. Seeing line & column where the problem appears would make it much easier to alleviate the problem.

**Comment by mzgol** [comment]
I agree it'd be difficult to do sth else here and using `ng-strict-di` with unminified code produces readable error messages so I guess I'll just close the issue.

**Comment by gamebox** [comment]
I'd like to poke at this a little bit.  I'm using `ng-strict-di` in development on unminified(but concatenated) code and the error message is very unhelpful:

```
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module ng due to:
Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.5.11/$injector/strictdi?p0=function(%24provide)
```

Which makes it seem like the Angular injector itself is the item without annotation.  I am using gulp-ng-annotate(with add: true, single_quote: true), and gulp-concat.  I'm refactoring this application to follow the Angular Style Guide and using the `/* @ngInject */` annotation for the items that have been refactored.

**Comment by gamebox** [comment]
Following the init logic it seems that when we are bootstrapping the 'ng' module and get here
```js
runInvokeQueue(moduleFn._configBlocks);
```
it ends up with a very curious thing in _configBlocks
```js
[
  [
    "$injector",
    "invoke",
    {
      "0": [
        "$provide",
        function($provide {...}
      ]
    }
  ],
  [
    "$injector",
    "invoke",
    {
      "0": function($provide) {...}
    }
  ]
]
```
Notice how this function that wants $provide injected is here twice, but once without an annotation.  Looking through the same source, their is not one instance of a function that has $provide as an argument where it is **not** annotated.  So what is going on here?

**Comment by gamebox** [comment]
Let me leave a note for people who run into this, the problem came from the (unofficial) Batarang extension.  Thank you Chrome Dev Tools and watch expressions!
