### ISSUE TITLE
Make it possible to set different HTML class per select option

### ISSUE THREAD

**Issue by apuchkov** [angular/angular.js#8138]
I would be handy to be able to set different HTML classes for options out of the box when ng-options is used.

Currently it is only possible to set class for entire select element.

This SO question has a solution: http://stackoverflow.com/q/15264051/1689049

**Comment by lgalfaso** [comment]
This is possible using

```html
<div ng-init='options = ["a", "b", "c"]'>
  <select>
    <option ng-repeat="o in options" value="{{o}}" ng-class="o">{{o}}</option>
  </select>
</div>
```

This will not work with IE8, but 1.2.x is not open for bug fixes nor features

**Comment by Narretz** [comment]
The feature request was specifc to `ngOptions`, though, but I am not sure if it's a necessary feature.
