### ISSUE TITLE
Directive with 'replace: true' and template duplicates classes in the attrs parameter of the link fn

### ISSUE THREAD

**Issue by jstrength** [angular/angular.js#8159]
When I create a directive with a template that has a class attribute and `replace: true`. The attrs parameter in the link function duplicates the classes. They are also duplicated when I look at the element in the HTML. 

This appears to only happen when the tag that the directive is replacing also has a class attribute.

Here is some example code, along with the output I see in the console.

```html
<test class="btn-block"></test>
```

```javascript
directive("test", function () {
        return {
            restrict: 'E',
            replace: 'true',
            link: function(scope, element, attrs) {
                console.log(attrs);
            },
            template: '<div class="center-block"></div>'
        };
    })
```

![screen shot 2014-07-11 at 3 57 28 pm](https://cloud.githubusercontent.com/assets/4017654/3559188/765f6a6c-0946-11e4-8a36-7eabd18f6d80.png)

**Comment by gkalpak** [comment]
Although it shouldn't really affect much (and `replace` is indeed deprecated for quite some time), I believe this is a bug.

More specifically, in [mergeTemplateAttributes()][1], we are first merging the source attributes with the destination attributes, joining values if both have the same key. Right after that we are copying the keys in source that are not present in destination, but for some reason we are special-casing `class` and `style` and always re-appending the source value (even if the key is present in destination, meaning the source value has already been appended in the previous loop).

[1]: https://github.com/angular/angular.js/blob/cfc8b41771e6f2f5bcf692400e960144009b1f18/src/ng/compile.js#L2747-L2778

**Comment by Narretz** [comment]
So this only duplicates the attributes internally. It'll probably be an easy fix, but without much impact.

**Comment by gkalpak** [comment]
Exactly. I'm putting this in the backlog, but since `replace` is deprecated this is really low priority.
PRs are welcome though :smiley:
