### ISSUE TITLE
bug: ng-switch animation doesn't work 

### ISSUE THREAD

**Issue by intellix** [angular/angular.js#8166]
**Request Type:** bug

**How to reproduce:**
 - Visit http://plnkr.co/edit/IctQYWhERYUBfzLkFq43?p=preview
 - Switch between slides 1 and 2

**Component(s):** ngAnimate

**Impact:** small

**Complexity:** small

**This issue is related to:** ngAnimate and ngSwitch animation

**Detailed Description:**
It seems when you try to `ngAnimate` the `ngSwitch` component on a `form` element, only the `ng-leave` item is animated. The `ng-enter` contains inline styling to remove the animation. If I alter the classes manually then I can see that the entering form should be able to be animated

**Other Comments:**

**Comment by havenchyk** [comment]
@intellix @Narretz can this issue be closed? It looks like @matsko already merged a fix.

**Comment by intellix** [comment]
Yep, works for me :)
