### ISSUE TITLE
ngSelect sometimes falls out-of-sync with its backing ngModel

### ISSUE THREAD

**Issue by appsforartists** [angular/angular.js#8249]
[Reduction /w Steps to Reproduce](http://embed.plnkr.co/ZGHephQmSUP5hZQZRGHp/preview)

Tested on Mac OS X (10.9.2) using: 
 - Chrome 35.0.1916.153 (Official Build 274914)
 - Firefox 24
 - Safari 7.0.2

**Comment by petebacondarwin** [comment]
This is fixed in 1.3.8 : http://plnkr.co/edit/ACMdz1jFsDJTCeh91XSh?p=preview
