### ISSUE TITLE
IE10+, Firefox: "Invalid calling object" on properties after angular.copy of a File object

### ISSUE THREAD

**Issue by nlwillia** [angular/angular.js#8312]
Given a [file object](https://developer.mozilla.org/en-US/docs/Web/API/File), calling angular.copy and trying to access properties like "name" and "size" on the copy will result in a "Invalid calling object" error being thrown in IE 10+.  In Firefox, the error is "Illegal operation on WrappedNative prototype object".  Tested in angular 1.3 beta 15.  ([Demo](http://plnkr.co/edit/SAD1IOm4ERkCklvngPn1?p=preview))  The problem does not occur in angular 1.1.5 or in Chrome.

**Comment by gkalpak** [comment]
Let's track the issue in #14352.
