### ISSUE TITLE
ng-src problems in Firefox OS

### ISSUE THREAD

**Issue by aziflaj** [angular/angular.js#8335]
While developing a Firefox OS application, I saw that images with ng-src would not load into the view

**Comment by genius50** [comment]
Hello there ! Can you please clarify how you managed to fix the problem ?

**Comment by oardi** [comment]
@genius50 
Dude, I described it above.
Wasn´t that clear enough?

**Comment by Narretz** [comment]
I think @oardi is right and you need to add app:// to the whitelist, so it's not a bug.

**Comment by surdu** [comment]
But why only in FF ?

**Comment by oardi** [comment]
Hi @ninjarails,
take a look at my solution from "10 Oct 2014".

you need to set the following inside your module´s config:
$compileProvider.imgSrcSanitizationWhitelist(/^\s*(https?|ftp|mailto|file|tel|**app**):/);
