### ISSUE TITLE
Feature request: provide HTTP status to the success callback of $resource

### ISSUE THREAD

**Issue by 97jaz** [angular/angular.js#8341]
When a $resource request fails, you get the response object passed to the error callback, and you can retrieve that HTTP status from that. When the request succeeds, however, the success callback is given only the payload and the headers.

It's often important to be able to distinguish between different success cases using the HTTP response code. It's not uncommon to have POST requests that either create and return a new resource (HTTP 201) or find and return an existing one that will fill the present need (HTTP 200). Or, say, the difference between a 201 ("your resource was created, and here it is") vs. a 202 ("we'll try to create this resource; check back later").

**Comment by eddiemonge** [comment]
Its only in the header object if the server passes it back as a header property, which most don't do by default, instead passing them back as a status code.

**Comment by giggio** [comment]
+1. It is important to have the status code.

**Comment by eddiemonge** [comment]
If the status code was added into the headers that might be acceptable

**Comment by giggio** [comment]
Changes proposed on #8841 seem simple enough. Why wasn't that integrated?

**Comment by glebv** [comment]
+1. e.g. I received 204 "No Content", it's successful code, but to understand what kind of code I received I have to check returned data e.g. ! data.hasOwnProperty(id), then ... 
it's very inconvenient and is not stable solution.

**Comment by dalsh** [comment]
@97jaz 
> the claim that you shouldn't care about HTTP status codes at the resource level does not seem credible to me, since it implies that there is only one way for a resource-related request to succeed for any given HTTP verb

+1 to this

**Comment by giggio** [comment]
There has been no replies from the angular team on this issue. There is a pending PR to fix this, with accepted CLA, also with no replies.
Is there anyone looking at this?

**Comment by gkalpak** [comment]
I'm looking at this (now) :smiley: Thx for bringing it to our attention.

The feature-set for the eminent `1.5.0` release is currently locked down, but we'll look into getting this into a subsequent release.

**Comment by giggio** [comment]
@gkalpak Thanks! ;)

**Comment by franDayz** [comment]
+1 as I deal with same situation as @glebv

**Comment by BBlackwo** [comment]
+1 I have the same problem. Need to check for a 203. Workaround is here http://stackoverflow.com/a/29435961/2443005

**Comment by artisom** [comment]
20th june 2016
