### ISSUE TITLE
jqLite destroys IE8's stopPropagation polyfill

### ISSUE THREAD

**Issue by ondras** [angular/angular.js#8369]
Hi,

my tiny harmless one-liner for IE8 looks like this:

```js
Event.prototype.stopPropagation = function() { this.cancelBubble = true; }
````

but gets eaten away by Angular's jqLite event handling subsystem: https://github.com/angular/angular.js/blob/master/src/jqLite.js#L735

I would argue that my polyfill is not creating any memory leaks and thus does not need to be removed without a word of warning. My code expects `stopPropagation` in event handlers; this "feature" makes the assumption wrong and breaks existing code.

**Comment by lgalfaso** [comment]
this issue is no longer valid, the code in question was removed
