### ISSUE TITLE
Provide parameter to disable response data assigning to $resource instance

### ISSUE THREAD

**Issue by Antontelesh** [angular/angular.js#8370]
Now when you call <code>item.$save()</code> (where item is an instance of $resource), the response data from server will be assigned to <code>item</code>.

This is important for GET requests but in some cases for POST/PUT requests it shouldn't behave like this.

For example I have a form, which stresses the invalid inputs when they are dirty. If my backend doesn't return the instance on POST request, these inputs will be alerted because whole my model changed to the response data.

Please, provide some parameter to disable such behaviour.

**Comment by Narretz** [comment]
This behavior is essential to $resource. If your API behaves differently, you are better off with plain $http or a 3rd party module.
