### ISSUE TITLE
Support recursive trees of directives

### ISSUE THREAD

**Issue by caitp** [angular/angular.js#8379]
I had some ideas about implementing this during the meeting, so I might have a go at bikeshedding something over the next few weeks.

What it comes down to is basically conditionally inserting DOM into a compiled template, based on some state. Sort of an implicit `ng-if` that gets resolved at compile-time, or else prevents `ng-if` from recursively linking the same template.

Anyways, I'd like to sort out a way to do that because it's a pretty cool and useful structure, and other implementations (like http://caitp.github.io/ui-comments/#/) have depended on some ugly hacks which are better to avoid.

I'm sure this has been proposed already, but I can't find any of those issues right now.

Anyways, I'll throw something together and people can see what they think

**use cases**

- Comments
- Org-charts
- Graphs
- Product charts
- etc...

**Comment by caitp** [comment]
this is too hard to accomplish in this codebase

**Comment by Narretz** [comment]
Dupe of https://github.com/angular/angular.js/issues/8536

**Comment by jeme** [comment]
We are still happily using https://github.com/dotJEM/angular-tree allot (yes, i created that)... Optimizations, improvements etc. are more than welcome btw...
