### ISSUE TITLE
Per-domain configuration in $httpProvider

### ISSUE THREAD

**Issue by jimbru** [angular/angular.js#8381]
Dear Angular,

This is a feature request! It would be great if `$httpProvider` supported configuring defaults (e.g. headers, etc.) on a per-domain basis, rather than just globally.

It's been suggested to me that this is not an uncommon feature in other HTTP client implementations. One of my colleagues pointed me to [Apache's HTTP stack](http://hc.apache.org/httpclient-3.x/preference-api.html) (`HostConfiguration`, in particular).

I imagine an Angular-ish interface for this might look something like this:

``` javascript
angular.module('foo', [])
  .config(function($httpProvider) {
    $httpProvider.domain['example.com'].defaults.headers.common.Authorization = 'Basic aGVsbG86YW5ndWxhcg==';
  })
  .controller('FooCtrl', function($http) {
    $http.get('http://example.com/');    // Would include 'Authorization' header.
    $http.get('http://evil.com/');       // Would _not_ include header.
  });
```

Thanks!

**Comment by Narretz** [comment]
Seems like this isn't a very frequently requested thing. Closing.
