### ISSUE TITLE
Understanding scopes not up-to-date

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular.js#8420]
```
ng-view

TBD, but I think it acts just like ng-include.
```

Shouldn't it be determined already?

**Comment by Narretz** [comment]
It's actually pretty mind-boggling that the Wiki is a parallel docs project to the official docs. We should really try to bring these two together. I'll open a new issue for that.

**Comment by ilanbiala** [comment]
@Narretz can you link to that issue?

**Comment by Narretz** [comment]
@ilanbiala https://github.com/angular/angular.js/issues/12140

If you want to help, we can work something out.
