### ISSUE TITLE
Directive attribute – referencing self on isolate scope

### ISSUE THREAD

**Issue by dalgard** [angular/angular.js#8427]
I can't seem to find a shorthand for binding the value of the directive attribute itself to the scope, though it seems an obvious idea? Having to maintain the name of the directive in several places is a bit of a code smell.

Just for diversion, I've tried putting in keywords such as this/self, but no luck – so far, anyway ;) Should be an easy win for the framework.

```
scope: {
  foo: "=this",  // no luck
  self: "="      // nope
}
```

**Comment by matthewjh** [comment]
One problem with this is what if you want to bind `this` or `self` to actual attributes? Not sure using either of those is any better/clearer that just using the directive name.

Also, wrt having to maintain the name of the directive in several places, wouldn't you already be doing this across every single template using the directive? If so, having the maintain the name within the DDO doesn't seem like an issue.
