### ISSUE TITLE
$$raf would be useful if it were public

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular.js#8435]
Could the requestAnimationFrame provider ($$raf) be made a public API? It would be useful for things that can't be `ng-animated` very easily such as SVG.

**Comment by ilanbiala** [comment]
@caitp @matsko Not that I need this anymore, but I don't see any progress on it, should this be closed?

**Comment by matsko** [comment]
Closing for now. Thanks for the heads up.

**Comment by ilanbiala** [comment]
@caitp @matsko does this cause any issues if it were made public? I'm using rAF/setTimeout again and it seems dumb for me to rewrite what was already written by Angular core and could be made public for others to use as well.
