### ISSUE TITLE
$httpBackend expectations with undefined URL

### ISSUE THREAD

**Issue by Kapaacius** [angular/angular.js#8442]
Using : Angular-1.3.0-beta.17

$httpBackend.expect methods return true when URL is undefined or missing, even though the documentation states that the URL is not optional.

This is because of the following code in angular-mocks.js (class MockHttpExpectation):
```
this.matchUrl = function(u) {
    if (!url) return true;
```

A Plunkr to illustrate the point: http://plnkr.co/edit/k1bntn?p=preview

Is this an undocumented feature or a bug?

**Comment by pkozlowski-opensource** [comment]
This is roughly the same as https://github.com/angular/angular.js/issues/10934
