### ISSUE TITLE
vol 2. ng-swipe (1.2.21) crashes Safari and Chrome on iOS devices when swipe exposes input field and then you swipe on the field

### ISSUE THREAD

**Issue by xtrail** [angular/angular.js#8448]
I have the same issue https://github.com/angular/angular.js/issues/4318

**Comment by petebacondarwin** [comment]
@xtrail - is this still a problem for you? We are not pushing non-security bug fixes to 1.2.x. So it would need to be a reproducible problem on 1.4.x or later to get looked at.
