### ISSUE TITLE
filter and orderBy should also work with objects in ngRepeat

### ISSUE THREAD

**Issue by nodecode** [angular/angular.js#8458]
<code>filter</code> and <code>orderBy</code> should work with objects within <code>ngRepeat</code>. My use case for this, I have already written recently in #1286, but the issue only refers to <code>oderBy</code> and has previously been rejected seemingly because no concrete use case has been found for this. 

Here is my use case where I absolutely need an object instead of an array:

> I'm currently developing a real-time browser game with AngularJS, in which I have a room list. To update individual entries in this list, the server sends a notification with the new version of this single entry when it changes. Thus, a single entry can be by ID, provided by the server, updated, I need to use an object instead of an array.

> I would like to sort these entries with AngularJS, which, however, currently not working. I would be happy if this feature will be implemented soon. Otherwise, I had to write such a function myself, which I however come back in the boilerplate code hell.

A support of objects in <code>filter</code> and <code>orderBy</code> of AngularJS for me would be really helpful as I would otherwise have to try myself to implement such a function.

**Comment by wesleycho** [comment]
Given that this has been rejected for filterFilter in #2694, this probably should be closed as won't support since orderBy suffers the same issues.

**Comment by petebacondarwin** [comment]
Yes, I agree - and we have a performance workaround.
