### ISSUE TITLE
Multiple "as" for ng-repeat

### ISSUE THREAD

**Issue by 23tux** [angular/angular.js#8502]
Hi,

I'm not sure if I do something wrong, but it seems that you can't have multiple as assignments in one ng-repeat. For example this doesn't work:

```
<span ng-repeat="actor in actors | filter:{name: name_search} as firstResults | filter:{gender: gender_search} as secondResult">
  {{actor}}
</span>
{{firstResult.length}}
{{secondResult.length}}
```

In this case, `firstResult` and `secondResult` are undefined. Is this a bug, or is "as" not intendet to be used this way?

It would be useful in cases where you need access to the specific filtered results, for example a pagination is used on all actors, but you want to know the length of the search results from the filter.

EDIT:
I created a plnkr to demonstrate this issue: http://plnkr.co/edit/6r3iWEJl37kgUnPO6nkC?p=preview

**Comment by lgalfaso** [comment]
have to agree with @petebacondarwin
