### ISSUE TITLE
ngResource doesn't copy properties of array created by TransformResponse

### ISSUE THREAD

**Issue by joeljeske** [angular/angular.js#8509]
I am using ngResource to fetch an array of items. In my transform response function, I am pulling select headers and adding them as properties of the array (not adding them to the array but as metadata properties, similar to `.length`. The way that ngResource then copies the array to the shell array it initially returned, it does not copy these metadata properties. It is understandable why it does not get copied but I believe it should copy everything within the response object.

```
var service = $resource('/list.json', {}, {
   custom: {
      method: 'GET',
      isArray: true,
      transformResponse: function(data, headers){
         data.metadata = headers('custom-metadata');
         return data;
      }
}

var result = service.custom();
result.$promise.then(function(response){
   response.metadata // undefined
   result.metadata // undefined
});
```

**Comment by connorbode** [comment]
+1 for this.

**Comment by a-bronx** [comment]
+1. I hoped to use the `transferResponse` to add pagination metadata to the array instance (e.g. a `.total()` function), but found that this metadata was not preserved down the pipeline as expected.

**Comment by Falci** [comment]
+1

**Comment by jirojo2** [comment]
+1
@a-bronx, could you please elaborate the `interceptor` workaround? 
Thanks!

**Comment by a-bronx** [comment]
@jirojo2 : In my case I wanted to convert a "paginated" response in a form of `{ total: 123, items: [...]}` to a simple array with a `.total()` method attached:
```
function PostResource($resource)
{
    var Post = $resource(..., ..., {
        query: { 
            method: 'GET',
            url: ...,
            // note that we receive a "page" object, and array of items is buried in its "items" property
            isArray: false,
            // but we want to return an array like a regular "$resource.query" does
            interceptor: { response: transform },
        },
        ...
    }
    return Post;

    // Converts a "paged" items container to an array of items, augmented with a .total() function.
    function transform(response) {
        var data = response.resource;
        if (data.total != null && data.items != null) {
            // augment the array of items with paging metadata function(s)
            data.items.total = function() { return data.total; }
            // convert each item to the resource object, so they support $save, $delete etc.
            angular.forEach(data.items, function(item, i, items) {
                items[i] = new Post(item);
            });
            return data.items;
        } else {
            return new Post(data);  // a single item with no paging data, just convert it to a resource object
        }
    }
}

**Comment by jirojo2** [comment]
@a-bronx: thanks! that helped a lot

**Comment by jirojo2** [comment]
In the end I chose the following solution, hoping ng-resource's array supports this REST-like collections soon:

```javascript
app.controller('UsersCtrl', ['$scope', 'User',
    function($scope, User) {
        User.list(function(items, headers) {
            items.total = headers('total');
            items.page = headers('page');
            $scope.users = items;
        });
    }
])
```

```javascript
User = $resource(
            '/api/admin/user/:id_user',
            {
                id_user: '@id'
            },
            {
                get: { method: 'GET' },
                list: { method: 'GET', isArray: true,
                        transformResponse: function(res, headers) {
                            var data = angular.fromJson(res).data;
                            var list = data.items;
                            headers()['total'] = data.total;
                            headers()['page'] = data.page;
                            return list;
                        }
                },
                save: { method: 'POST' },
                update: { method: 'PUT' },
                delete: { method: 'DELETE' }
            }
        );
```

**Comment by kaidokert** [comment]
Thanks for the last one, looks most straightforward. I used the same approach and shoveled the pagination fields through a single header as in :

    headers()['pagination'] = {
           total: data.meta.total  , page : data.meta.page , data.meta.page_size : ...
    }

And on the controller side i stuff it in a separate `$context.pagination` variable to make markup side more consistent.

**Comment by inwaar** [comment]
+1

**Comment by andrefarzat** [comment]
+1

**Comment by gkalpak** [comment]
Sice this is already possible through an interceptor, I am going to close this as `won't fix`.
For more info, read about the `interceptor` property of an `action` in [the docs][1].
For reference, here is how you can use the interceptor ([demo][2]):

```js
const Thing = $resource('/api/things', null, {
  list: {
    method: 'get',
    isArray: true,
    interceptor: {
      response: resp => {
        resp.resource.foo = headers('foo');
        return resp.resource;
      },
    },
  },
});
```

[1]: https://docs.angularjs.org/api/ngResource/service/$resource#$resource-arguments
[2]: https://codepen.io/ExpertSystem/pen/wyrYBx?editors=0012
