### ISSUE TITLE
Sanitizer re-orders strong and ins tags

### ISSUE THREAD

**Issue by kentskinner** [angular/angular.js#8513]
e.g. `$sanitize('<strong><ins>Foo</ins></strong>')` returns `"<strong></strong><ins>Foo</ins>"`

This is because 'ins' is listed as a block tag (and an inline tag): https://github.com/angular/angular.js/blob/master/src/ngSanitize/sanitize.js#L189. Upon encountering a block tag, previous inline tags are closed, but should this happen for a tag that can be a block or inline like 'ins'?

**Comment by Narretz** [comment]
This is fixed in 1.5 with new sanitizer.
