### ISSUE TITLE
Placeholder text doesn't work well with ngTrim

### ISSUE THREAD

**Issue by rwlogel** [angular/angular.js#8529]
By default text elements are trimmed by angular.  This can have weird results when used with placeholder because the view value is empty, but the element isn't which hides the placeholder.  An example can be seen here:
http://plnkr.co/edit/M8dJYA?p=preview

One possible solution could be something like this:

``` javascript
element.on('blur', function() {
    if(  /* ngTrim enabled */) {
        var value = element.val(),
            trimValue = trim(value);

        if(value !== trimValue) {
            element.val(trimValue);
        }
    }
});
}
```

But I'm not sure where it would go in the source code?

**Comment by Narretz** [comment]
Due to the converns raised by @caitp and the fact that this is not a very frequent feature, I'm gonna close this as wontfix.
It's also possible to use a custom directive to disallow trimming by default, but have it still overridable: http://plnkr.co/edit/bYx3fGHqVVnhqGokkk32?p=preview
