### ISSUE TITLE
memory leak in tests with jQuery 2

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular.js#8532]
I don't think that we properly considered the impact of the jQuery 2 upgrade on angular-mocks.

relevant code: https://github.com/angular/angular.js/blob/7df7d1a9bc9362fea657fbeb95bc9ff53740062d/src/ngMock/angular-mocks.js#L2004-L2023

this means that if a test doesn't trigger jQuery data/event handler deallocation, these objects will remain in the jQuery cache forever or at least until karma captured browser window doesn't crash.

I'm unsure how to fix this without patching jQuery :-/

@mzgol any ideas? :)

**Comment by mgol** [comment]
The just released [jQuery 3.0.0](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) now attaches data directly to the elements so the issue should no longer exist.
