### ISSUE TITLE
ngModelCtrl pollutes child scope

### ISSUE THREAD

**Issue by Izhaki** [angular/angular.js#8539]
There seems to be a bug with `ngModelController` $parsers - instead of updating the model (on the parent scope), they create a new property on the local (child) scope. Oddly, this doesn't happen with an isolated scope.

With this html [(plunk)](http://plnkr.co/edit/CwECyI?p=preview):

```
<body ng-controller='main'>
    <p>{{appCount}}</p>
    <input dir ng-model='appCount'>
</body>
```

And this script:

```
.controller( 'main', function( $scope ) {
  $scope.appCount = '0';
})

.directive( 'dir', function() {
  return {
    require: 'ngModel',

    scope: true,

    link: function( scope, element, attributes, modelCtrl ) {
      modelCtrl.$parsers.unshift( function ( aInputValue ) {
        console.log( scope );
        return aInputValue;
      });   
    }
  }  
})
```

The actual model value never update on the controller level. Instead, a property called 'appCount' is created on the scope of the directive.

It seems that the issue is on this line (it sets the model on the child scope, not parent scope):

```
      ngModelSet($scope, ctrl.$modelValue);
```

within the following `ngModelController` code:

```
  this.$$writeModelToScope = function() {
    var getterSetter;

    if (ctrl.$options && ctrl.$options.getterSetter &&
        isFunction(getterSetter = ngModelGet($scope))) {

      getterSetter(ctrl.$modelValue);
    } else {
      ngModelSet($scope, ctrl.$modelValue);
    }
    forEach(ctrl.$viewChangeListeners, function(listener) {
      try {
        listener();
      } catch(e) {
        $exceptionHandler(e);
      }
    });
  };
```

**Comment by FesterCluck** [comment]
Could someone check if this still needs discussing? 

I believe the core description of this discussion could be "Directive child scopes prototypically inherit from one another with parent scope as the prototype. The behavior of base owned properties can be confusing. Should something be done?"

My vote is no and that this issue be closed.

**Comment by Izhaki** [comment]
Seeing as this has been around for nearly 3 years with little activity - closing.
