### ISSUE TITLE
`this` context inside directive functions are undefined, should be bound to definition object

### ISSUE THREAD

**Issue by pocesar** [angular/angular.js#8549]
In Typescript, you can define a directive like this (since angular.directive doesn't support constructors like controller, service, etc):

```typescript
module stuff {
  export class MyDirective implements ng.IDirective {
     restrict = 'A';
     constructor(public injectSome: ngSome.injectSome) {}
     link(){
        this.injectSome(); // this is undefined
     }
     static instance(){
       return ['injectSome', (injectSome) => new this(injectSome)];
     }
  }
  angular.module('stuff', []).directive('myDirective', MyDirective.instance());
}
```
the `link`, `compile`, `template` and `templateUrl` functions should be called within the directive definition object context. this will make constructors work as they should.

Typescript enforces good practices and modularization, so you can even test stuff decoupled from angular itself (through the classes definitions), don't ruin the fun for us :)

(also happening on filters)

**Comment by wesleycho** [comment]
Given that #9306 landed, this issue can be closed.
