### ISSUE TITLE
IE11 not getting new promise data

### ISSUE THREAD

**Issue by Martinspire** [angular/angular.js#8565]
Perhaps i found an IE Bug?
I'm using a repeated promise (via $timeout to a resource) with some data i need to get. Its an external api (which can change stuff too so i need it somewhat fresh) and when i change values in IE it switches me back to the original value, even though in Chrome i see the new value appear. When i open IE Devtools it shows me the correct values and works as expected.

Situation:
Data from API>Data from service->Data from Controller which is repeated by making a $timeout loop it->Data in view
Change data in view reverses the path and its being submitted (i can see new values in Chrome) but doesn't reflect on IE11. When i hit refresh or open Devtools it shows me the new value though. When i alert the value, it shows the old one (unless i open devtools)

I've already tried disabling resource cache (globally and locally) and that doesn't help. I've also checked to see if the timeout is running properly (if i can set new values via timeout in controller) and that also works. It just doesn't get the new values.

No issues in Safari, Chrome, Firefox. Only IE11 (or perhaps lower too) have these issues. And only when devtools isn't open.

I've checked to see if its related to console.log or something but that doesn't seem the case (i've got a version running minified and without console) and that also works normally. But IE11 shouldn't have a problem anyways.

I'll see if i can work up a jsfiddle or example but i need to do some work on that as it requires me to pick some code from my project. Alternative would be that i make a small video to explain it. But before i do that, perhaps others have had this issue?

**Comment by pdeveltere** [comment]
+1

**Comment by gilangaramadan** [comment]
+1. Yeah thanks it solved the problem but it faced another, I can't load the font awesome on IE8-IE11 but working normally in EDGE :(

**Comment by ianlyons** [comment]
@gilangaramadan suspect you've already solved this, but webfonts won't load in IE8-11 with a `Cache-Control: no-cache` header -- you'll need to exempt your font file extensions from that. (And while you're at it, exempt other statics too, like images.)

**Comment by Narretz** [comment]
This looks like an IE bug / a server config issue.

**Comment by jrthompson33** [comment]
+1, this was a great fix! I had the exact same issue, and couldn't figure it out for the better half of a day.

**Comment by Dani2688** [comment]
+1 Thanks! I had the same issue, now its gone :)

**Comment by Gallyket1** [comment]
Where do I have to put the codes @Martinspire  provided ? in the JSP (HTML) page ? 

Thanks in advance
