### ISSUE TITLE
angular.extend does not copy getters/setters

### ISSUE THREAD

**Issue by mschwartz** [angular/angular.js#8573]
```
var o = angular.extend( {}, { 
  get x() { 
    return 'x';
  } 
});
```
resulting o object does not have the get x() method, it has 'x'

**Comment by trisys3** [comment]
`extend` actually *does* work with getters and setters, you just have to make them `enumerable`. I'm not sure if there is a way to make the function work without loops, which is what you'd have to do to support non-enumerable getters and setters, but if you have getters and setters you want to merge with another object, you probably want them to be enumerable anyway.

**Comment by trisys3** [comment]
Actually, if you make a getter or setter `enumerable` when defining the property with `defineProperty`, which is one of the only ways to add a getter or setter after the object is created, it is merged into the other object. However, if you create the first object with a getter or setter, it is not copied over. I am not sure why this is, as in both cases the object is not `writable` and with `defineProperty` the getter/setter is not `configurable` but when creating with a getter/setter it is `configurable`.

**Comment by mschwartz** [comment]
Here's how it's done right.

https://github.com/decafjs/decaf/blob/master/builtins/decaf.js#L47

**Comment by trisys3** [comment]
I was not proposing an alternative to `angular.extend`, I was mentioning a way to use `angular.extend` with getters and setters without changes to `angular`. Sorry if I was not more clear.

**Comment by mschwartz** [comment]
defineProperty() isn't the only way to define a getter or setter.

var o = { _x: 10, get x() { return this._x; } };

I'm reasonably sure you don't want angular.extend() to copy this._x (10)
 into the extended object, but rather the get() function.

IMO

**Comment by trisys3** [comment]
I am aware that `defineProperty` is not the only way to define a getter or setter. The Mozilla network's site mentions it as the only way to define one after the object is already created. Additionally, `defineProperty` allows you to change the enumerability, which was key to the method I mentioned to successfully extend an object with getters &/or setters. Then again, when a getter/setter is created when the object is, it is already enumerable, so I don't know why these getters/setters can not be extended, but they can't.

**Comment by mschwartz** [comment]
The angular implementation of extend() is calling the getter and/or setter
of the source object instead of detecting it is a getter/setter and
creating a getter/setter function on the destination.  The enumeration is
finding the member as a variable (e.g. return value from the get method).

A true copy means it copies the members: variables and functions.  A getter
or setter is a function.

Getters and setters are pretty slick.  If you want to do a true extend(),
you're going to have to call angular.extend() then call defineProperty() or
equivalent as many times as you have setters and getters and you're going
to have to know the name of each, etc.

The key to making extend() work is in that decafjs code.

**Comment by lgalfaso** [comment]
Angular exposes some of the helper functions that it uses internally. This
is the case for `extend`, `copy` and many others.
There are other libraries that specialize in these functions, keep their
focus is there and can do a better job. Eg, angular.copy does not handle
many of the browser specific quirks with native objects and probably will
never do.
It is not in the best interest of most users to make these helper functions
big nor slow, as these are used internally and any change in that direction
can have a direct impact in download size and performance. At the same
time, apps that need the most accurate version, should be better served
with other libraries.

Now, anybody is welcome to create a PR that adds support for
getters/setters. If the changes are small and the performance is about the
same, then it should get merge without any issues. If the change makes some
function big or slow, then it will need an excellent use case or a large
community supporting this trade off  (in these later cases, it should get
eventually solved).

Anybody who is interested in getting this fixed, create a PR and let's move
the discussion there.

**Comment by StephanBijzitter** [comment]
So why does angular provide an `extend` function if it does not work as advertised? You're telling us to use different libraries, fine, but then remove the function from your own library and depend on those others libraries as dependencies.

**Comment by trisys3** [comment]
I think what @Igalfaso is trying to say is that angular tries to make its built-in functions as small and fast as it needs for its own internal purposes. For example, it does not need its `extend` function to be as accurate as the one that decafjs defines, because internally none of the things it is doing need an extremely accurate `extend` function. If angular depended on a library like decafjs, that would make it bigger & slower, in addition to functions like `extend`, from decafjs, being bigger and slower than it needs. If the end developer needs a more accurate function for extending objects, and does not mind the performance penalty, he/she can use decafjs.

**Comment by vinogradov** [comment]
Related to https://github.com/angular/angular.js/issues/5085

**Comment by egidiocs** [comment]
@mschwartz thank you for this: var o = { _x: 10, get x() { return this._x; } };

**Comment by wesleycho** [comment]
Given the Angular team's general stance about the utility functions it provides, would it make sense to close this issue or maybe have a doc update that warns that it should not be relied upon as a robust solution for all conditions?

**Comment by trisys3** [comment]
I'm really just a user, but I for one would have appreciated a doc reference pre-empting my comment here.

**Comment by gkalpak** [comment]
@wesleycho is right. Closing as _won't fix_.
PRs updating the docs are always welcome, if anyone feels like it :smiley:
