### ISSUE TITLE
bug($location): When route changes, js in application chrome get reloaded

### ISSUE THREAD

**Issue by borgdylan** [angular/angular.js#8576]
Everytime the route changes, the javascript files included outside the ngView directive are being downloaded again. Angular is also appending a strange number query to teh end of the paths forcign the browser to ignore the cached copies. This issue will force more bandwidth to be consumed.

The only workaround I have found so far is to include the js files in the head of the document which is not always optimal.

**Comment by Narretz** [comment]
@chazzlabs bug seems fixed in latest 1.3 and 1.4, and since the OP never answered, I'm gonna close this issue.
