### ISSUE TITLE
Elements filled by ngBind don't bind to onTouchStart

### ISSUE THREAD

**Issue by jamidwyer** [angular/angular.js#8600]
When ngTouch is bound to the html element, swipe works, except on child elements generated by ngBind. For example, the h2 element below never fired the onTouchStart function in angular-touch:
`<div class="header">`
`<h2 ng-bind="card.term"></h2>`
`</div>`

This also happened with another div populated by ngBind.

I see this on a 10.1" Samsung Galaxy Tablet running 4.1.2 and not on a 7" Dell running KitKat. I have a hacky workaround, but I'm filing this in hopes of a (much) better solution. 

Thank you!

**Comment by Narretz** [comment]
Closing because there's no repro / activity.
