### ISSUE TITLE
Feature request: Pass params object to $resource param if it's a function

### ISSUE THREAD

**Issue by philBrown** [angular/angular.js#8608]
The doco for ngResource states that _paramDefaults_ and action `params` may be functions however there is no useful data passed to these functions.

It would be handy to at least have the `actionParams` passed in. For example, change this line in `extractParams`

```
if (isFunction(value)) { value = value(); }
```

to

```
if (isFunction(value)) { value = value(actionParams); }
```

**Comment by philBrown** [comment]
@SekibOmazic you don't have to use the function argument. You can just leave it as

    group: function() {
        return currentGroup;
    }
    
The point is that the action parameters would be there if you do need to use them.

**Comment by SekibOmazic** [comment]
@philBrown Yes, in that case they'd be useful.

**Comment by gkalpak** [comment]
I don't see the usefulness in passing `actionParams`. It's just a definition object (saying where to look up the values for each param) usually.

@philBrown, what's the usecase for this ?
IMO, it would much more interesting to pass the actual `data` and/or the `params` passed to the method call as arguments. WDYT ?

**Comment by philBrown** [comment]
@gkalpak it's been a while now so I can't remember exactly what my original use-case was but it was something along the lines of creating dynamic param values based on the other params, ie having the param function aware of the call-time state.

I agree that having access to the `data` as well could be beneficial.

**Comment by gkalpak** [comment]
@philBrown, `actionParams` (as you suggested) does not really contain "call-time state". It's the static params (usually just references to item properties).

Passing the `params` and `data` should give some "call-time" context. Luckily, there is a PR for this #14003 :smiley:

**Comment by Narretz** [comment]
We have changed this a long time ago to pass the `data`. Not the params though. But since this is a low frequency issue, I'm going to close it.
