### ISSUE TITLE
browserTrigger doesn't support keydown with a specific keycode

### ISSUE THREAD

**Issue by jintoppy** [angular/angular.js#8688]
if I do browserTrigger(element, 'keydown'), there is no option to give keyCode. It is going to line 127, to initMouseEvent, even though this is a keydown event.

**Comment by gonzaloruizdevilla** [comment]
For PR https://github.com/angular/angular.js/pull/10193 I had to do exactly this. 

I had to make two different commits:
https://github.com/gonzaloruizdevilla/angular.js/commit/2f0d4fb36d440d9b109360a1c81c7aaf8f7add4a to allow key events 
https://github.com/gonzaloruizdevilla/angular.js/commit/d70e0d4b51933dfe2ef87116e40be3d568ae7f0f to force artificially event bubbling in trees detached from the document (bubbling don't work in these cases in some browsers like chrome)
