### ISSUE TITLE
Implement $cacheFactory.Cache#has method

### ISSUE THREAD

**Issue by caitp** [angular/angular.js#8692]
When checking in #8214 I was honestly surprised we don't expose a way to check if a key is in the cache.

It would be helpful to have a simple implementation, like `has: function(key) { return key in data; }` or something.

@IgorMinar this is a public API change so I didn't just write a patch, but what do you think? It's pretty trivial and better than testing if the value of a key is `undefined`

**Comment by Narretz** [comment]
See https://github.com/angular/angular.js/pull/14035#issuecomment-242978847
