### ISSUE TITLE
Compile / Controller / Link shared functions/variables

### ISSUE THREAD

**Issue by Izhaki** [angular/angular.js#8714]
It is often desired to share either functions or variables between a directive's compile, controller and link functions. Although one can essentially achieve whatever one wants, there seem not to be an 'elegant' (clean? concise? logical?) way of achieving this.

This is an issue i've struggled with a few times lately, and I think an improvement to the framework is possible.

# Current sharing options

## compile
`this` within compile is the actual definition object.
compile and link can share variables and functions as the link function returned from compile is within the latter closure.
There is no clean way to share functions/variables between compile and controller (you could just add properties to the element, but that's rather ugly).

## controller
The controller `this` is itself.
The way for it to call functions or use variables defined on the link function are only via the scope, which is provided to both. But that seems to me a rather dirty way of doing things.

## link
If defined as a property of the definition object, `this` within the link function is undefined.
The link function can use variables/functions from the controller as it gets the controller as a parameter.
If returned from the compile function, the link function is within its closure, thus it can access any functions or variables defined in compile.

Visually speaking, the visibility looks like this:

![image](https://cloud.githubusercontent.com/assets/880132/4004928/cbd2f20e-2988-11e4-8644-99e0f9dd3dc0.png)

# Some assumptions

## Controller

Should be used primarily for:

 - cross-directive communication
 - scope initialisation

## Link

Should be used for:

 - Hook on DOM events
 - Set scope watches
 - Inspect children if needed

## Internal directive variables / functions

A fairly elementary point, but directive often define their own helper functions (just a function declarations) and internal variables. Point is that not everything goes on the scope and I don't believe the scope (particularly as sometimes directive use parent scope) should be used for communication between the various directive functions.

# Possible solution to a common problem

Most commonly, I have a directive that communicate with other directives, and define helper functions which naturally go in the controller. But then something that happens in the link function require the same function (or variable) that are part of the controller.

The most reasonable solution to this seems to be to put nearly everything in the controller, since the link function can easily access it.

One caveat here is that, unlike the link function, the controller has no access to anything in the compile function.

Yet this seems like the best solution, but looking at the angular code (and many other's people code) it seems that the link function is where most code is.

# Improvement

In light of this, what could be nice if a directive had a central place where one defines all internal function and variables and compile, controller, link can all access that place.

Either using `this` (which, in the case of the controller will have to be provided as a parameter) or by other means.

Visually, something like this:

![image](https://cloud.githubusercontent.com/assets/880132/4004926/c3d46ba0-2988-11e4-9a88-9fe649b6f1da.png)

**Comment by wesleycho** [comment]
This seems like this could potentially get leaky in ng1, and some unsuspecting developers might go down the wrong path.

The current workaround is to have the linking function register stuff in the controller (including any relevant compile variables/functions/etc.). IMO, this doesn't really make sense as far as trying to keep the overhead of working in ng1 smaller goes, as it introduces a potentially complex vector of state management.

**Comment by gkalpak** [comment]
I agree with @wesleycho that this would add unnecessary overhead/complexity.

The way we build directives has drastically changed over the last couple of years, so this is probably less of a concern atm. You should be able to do most of the work from a controller. In the very uncommon situations, where you do need to use a `compile` function, there are already ways to share state with the controller and the little extra boilerplate is acceptable imo.

Closing as _won't fix_.
