### ISSUE TITLE
Question about ngMessage's "when" attribute. Multiple properties support?

### ISSUE THREAD

**Issue by gnrlbzik** [angular/angular.js#8730]
In case of mix/max validation on number there is sometimes a need just for one message which would state for example: "Please enter valid number between 1 and 99.". As I understand right now, you would need to create two ngMessage(s) in markup to listen to two separate properties but display the same message, duplicating the code.

Is it supported now in some other way or will it be in future?

AngularJS v1.3.0-build.3029+sha.7df7d1a

**Comment by matsko** [comment]
1.4 Will support assigning multiple error keys to a single message.

**Comment by gnrlbzik** [comment]
Thank you guys.
