### ISSUE TITLE
Docs need sitemap.xml

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular.js#8740]
Since upgrading to Dgeni, the docs don't have a sitemap.xml at docs.angularjs.org/sitemap.xml (see sitemap <1.2.10: https://code.angularjs.org/1.2.9/docs/sitemap.xml). A Dgeni processor should be created to create one.

**Comment by jelbourn** [comment]
- [ ] Change docs site to use html5Mode routing
- [ ] Change servers (local and production) to do URL-rewriting to support html5Mode
- [ ] Change URLs from entire module name to just component name (e.g., `material.components.button` to just `button`).
- [ ] Generate and upload a `sitemap.xml` file

**Comment by Narretz** [comment]
We do have one now! 😁
