### ISSUE TITLE
stacked directive not executed if ng-if is present

### ISSUE THREAD

**Issue by godmar** [angular/angular.js#8748]
When stacking directives on top of a template-expanding directive, the stacked directive may or may not be executed depending on the template. The presence of ng-if, in particular, appears to influence whether stacked directives are applied. Occurs in 1.2.20 and 1.3.0beta16

See pluncker: http://plnkr.co/edit/7gs4uRP5PDHRKj6MLu2s

**Comment by lgalfaso** [comment]
this is not related to the fact that there are multiple directives that apply to the same element, in fact, if you move the `link` function to make it one directive you get the same result.
Anywhere that there is a directive with `replace=true`, then the content is delegated to this other directive. In this case, the directive `ng-if` is a directive with `replace=true`, so at link time you cannot modify the content any more. In a strict sense, you can still do it, but that would be a poor practice. What you should be doing is
* Adding content after the element
* Use another directive to add the extra content

**Comment by godmar** [comment]
So does this mean that directives that use 'replace=true' cannot be stacked?

In our actual use case, the vendor directive uses replace=true. We cannot add other directives in the way you suggest (unless we completely override the vendor directive, which would make stacking less practical).

**Comment by lgalfaso** [comment]
there are many things you can still do:
* Attach to some other element inside the template
* Add another directive that modifies the DOM on `compile`
* Override the template

Without some extra information, it is impossible to know what the best solution would be. Now, this is getting out of topic, so I think it is better to continue the conversation in StackOverflow
