### ISSUE TITLE
New directive to catch image errors?

### ISSUE THREAD

**Issue by aj0strow** [angular/angular.js#8759]
Image errors do not propagate, so directives can't use delegation to catch dynamic image load failures. I've found the following pretty helpful. 

```javascript
angular.module('ng')

.directive('img', function () {
  return {
    restrict: 'E',
    link: function (scope, el, attr) {
      el.on('error', function () {
        if (attr['ngError']) {
          scope.$eval(attr['ngError'])
        }
      })
    }
  }
})
```

Then directive templates can specify what happens when the image doesn't come thru.

```html
<!-- for example -->
<img ng-src="{{ flaky.image }}" ng-error="tellServerItsBroken(this)">
```

It's basically a scoped `onerror`. I'm still pretty new to angular, so perhaps all this is foolish, but was curious what you guys think. Should probably expose an `$event` too for the expression but I wouldn't have the first clue how to do that. 

Anyway, thanks for all the great work, and would love to hear your thoughts.

**Comment by Nitad** [comment]
Been searching for a directive like this for hours! Even had to go to google page 2 to finally find it. Since the normal onerror doesnt work with the scope this is amazing. Thank you!

**Comment by aj0strow** [comment]
@Nitad mad useful eh. I packaged it a bit ago just for me, but cleaned it up if you want to use it too https://github.com/aj0strow/angular-image

**Comment by RsanabriaZ** [comment]
Looking I found this code, but It doesn't work with Angular JS 1.5.8, someone knows why?

**Comment by gkalpak** [comment]
It should work. In any case, you should not attach stuff to the `ng` module. You should create a new module and add it as a dependency to yours.

Here is an example of a generic `onError` directive that also exposes the error `event` as `$event`: [Demo][1].

I agree with @btford that this is something that does not need to live in core. It can be an external module.

https://codepen.io/ExpertSystem/pen/qaQKAx?editors=0011
