### ISSUE TITLE
Element with ng-show=false animates initially when it's in a bootstrap-ui modal

### ISSUE THREAD

**Issue by Narretz** [angular/angular.js#8812]
This is a follow-up to https://github.com/angular/angular.js/issues/5262 It turns out that the issue I described is different from the original issue described. In my case, I have a ng-show animation inside a bootstrap-ui modal that is initially set to false. When the modal opens, however, the element is animated from shown to hidden, while it should simply be not shown. I have posted a workaround here: https://github.com/angular/angular.js/issues/5262#issuecomment-41692920

**Comment by petebacondarwin** [comment]
This is still a problem on master. Moving to 1.4.x milestone.

**Comment by asoules** [comment]
:+1: same issue here.

**Comment by Narretz** [comment]
I believe this is not something that ngAnimate can be expected to solve. the bootstrap modal (at least in this version) doesn't use ngAnimate to trigger then moving / fading in of the modal, so ngAnimate has no chance to detect that there's an animation going on. If ngAnimate knew that there was an animation, it would not anmate stuff in the modal. I think in recent versions, the modal actually uses $animate, so this issue should be moot. Otherwise, the modal service could disable animations on the modal elements with $animate.enabled(el, false) until the opening animation has finished.
