### ISSUE TITLE
Allow multiple optional key/value parameters in $routeProvider

### ISSUE THREAD

**Issue by binarykitchen** [angular/angular.js#8884]
Would be great to support this

```
.when('/reply(/to/:to)?(/subject/:subject)?', {
```

so that URLs like these will be processed altogether:

`/reply`
`/reply/`
`/reply/to/somebody`
`/reply/subject/anything`
`/reply/to/somebody/subject/anything`
`/reply/subject/anything/to/somebody`

**Comment by Narretz** [comment]
Closing because it's not a very frequent feature request, as seen by the age and activity. ;)

This can also be done with multiple when() statements - while it's more boilerplate, it's definitely possible.
