### ISSUE TITLE
Remove or depricate ngClassEven/Odd?

### ISSUE THREAD

**Issue by jimmywarting** [angular/angular.js#8887]
I have never used it... I believe ngClassEven/Odd isn't so wildly used. I can be wrong here.
but there is alternative method to it like 

Every browser out there now support nth-child() it won't need any binding so I assume it has better performance so why wouldn't you use it?

```
li:nth-child(odd) {
    color: green;
}

li:nth-child(even) {
    color: blue;
}
```

if you desire the old behavior you could just do:

```
ng-class="{even: $even, odd: $odd}"
```

**Comment by realityking** [comment]
I took a look at this a while back, it would save only ~15 lines of non-comment code. That said, given the existence of `$even` and `$odd` it would be one less place where there are two ways to achieve the same thing, which would be nice.

**Comment by Narretz** [comment]
It's too late to deprecate or remove it now.
