### ISSUE TITLE
$scope.$watchOnce?

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#8930]
**TL;DR** - I wrote the [$watchOnce](https://github.com/kentcdodds/watchOnce) module. Do you want a PR to have it implemented in the core?

The end result would be:

```javascript
$scope.$watchOnce(function watcherGet() {
  return SomeFactory.values.length;
}, function watcherFn(value) {
  console.log(value); // <-- will only print once and will never be undefined.
});
```

This is shorthand for:

```javascript
var stopWatching = $scope.$watch(function watcherGet() {
  return SomeFactory.values.length;
}, function watcherFn(value) {
  if (!value) {
    return;
  }
  stopWatching();
  console.log(value);
});
```

You can also use `$watchGroupOnce` and `$watchCollectionOnce`

I realize that we now have the `::` prefix for expressions, so you could put that `watcherGet` on the `$scope` and `::watcherGet()`, but I feel this is a useful convenience, which is why I'm suggesting this.

Let me know if this type of thing is something that would possibly be merged. If so, I'll make a PR.

**Comment by lgalfaso** [comment]
I have to agree with the rest of the contributors, this is in very low demand and can be done with a third-party module

**Comment by kentcdodds** [comment]
After considering it further, I agree. Thanks!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
