### ISSUE TITLE
Feature request : Handling child directives from parent scope

### ISSUE THREAD

**Issue by DumboJetEngine** [angular/angular.js#8966]
Probably not the best place to post this, but I would like Angular to have a way to call from the parent scope a function defined at the child scope of a directive.
I know that you have events that one can use, but I see people on the web demonizing them. I don't know if they are right, but I think I would like to be able to get hold from the parent scope of a JS object representing my child directive and call (public only?) methods defined on it.

Let's face it: Angular's success is based on the fact that it brings the logic of desktop programming (with isolated components, etc) in a programming world that had no logic at all (at least that's my biased opinion). So, I think it would be nice if you could just inherit this concept as well, that is allowing a parent scope to control its child directives via some public interfaces, just like an instance of a class in C++/C# can call the public methods of instances of other classes instantiated inside them.
I know that JS and access modifiers (plus various other important programming aspects) have no direct link between them, but I think it's worth trying to make your library better by any means.

For example, if I have a modal dialog directive, that accepts some parameters to use when it gets loaded, I would like to do it like that:

```
  //$scope.$directives should hold the immediate child directives of the scope, named after a "ngName" attribute.
  $scope.$directives.myModal.show(params); // myModal should be the object representation of a directive and show() is a public method on it.

  //I think that this will also eliminate the need of using watches in MANY cases, thus improving performance.
```

Instead of :

```
$scope.$broadcast("showModal", params); // I have no idea who is listening to this event. Perhaps I only want the DIRECT children of my scope to get this event, not all the branch. Or what if I only want one instance of a directive to receive this event?
```

or

```
// Polluting the scope without a good reason...
$scope.modalParams = params;
$scope.modalShowTrigger = Math.random(); // From its name, you know that some directive observes this value, but it is very easy to loose track of what each variable does in a complex UI...
```

Looking forward to hearing your thoughts on this. :)

**Comment by Narretz** [comment]
In 1.7.1, you can use `ngRef` to publish directive controllers to the containing scope 😮
