### ISSUE TITLE
Re-introduce the possibility the refer the scope in filters

### ISSUE THREAD

**Issue by twwwt** [angular/angular.js#9009]
Starting from 1.3.0-beta19, `this` does no longer refer to the corresponding scope in a filter implementation, see this [commit](https://github.com/angular/angular.js/commit/8863b9d04c722b278fa93c5d66ad1e578ad6eb1f) and the [CHANGELOG](https://github.com/angular/angular.js/blob/master/CHANGELOG.md). The possibility to get a reference to the scope inside a filter should be re-introduced; whether implicitly or by other means is something that can be discussed (within this issue). I will explain this in the following.

I see the point in getting towards *pure functional* filters (though they aren't, as explained below); i.e., making all its input explicit rather than allowing for implicit input by the possibility to refer state such as the scope, which results in the possibility of side effects). Nevertheless, the possibility to (implicitly) refer the scope as the context of a filter, irrespective of whether this can be done by means of `this`, is a very valid use case. Consider a scope-specific filter. Such a filter depends on state in the scope (as an implicit input) that cannot be moved somewhere else; e.g., into a service, which is the only other possibility for filters to make them depending on something different than its input and optional arguments. As an example, consider *private* state that you want in the scope only. Also, consider the case where you need to access a scope-specific property; i.e. a property that might exist in many scope instances with different values. How would you externalize that property and make it identifiable without knowing the scope? The only possibility is to make it an argument of the filter (which may get a cumbersome lengthy list if a filter needs to access many properties of a scope).

In contrast to the [commit comment](https://github.com/angular/angular.js/commit/8863b9d04c722b278fa93c5d66ad1e578ad6eb1f), there is significant code that depends on this behavior. For instance, the `translate` filter of [angular-translate](http://angular-translate.github.io). In fact, it already suffers from this change, see this recent [issue](https://github.com/angular-translate/angular-translate/issues/694). In addition, we have also developed a filter the needs to reference a scope-specific property, and we could no longer use it with 1.3.0.

Proposal (more of an idea than thoroughly thought through): 
Introduce a new modifier such as `~` as an optional prefix for filter expressions. If present then `this` refers to the scope inside the filter. If not, then `this` is undefined.

Example:
`{{ 'foo' | ~blah }}` - `this` refers to the scope within `blah` filter.
`{{ 'foo' | blah }}` - `this` is undefined within `blah` filter.

Using a modifier (such as `~`) makes the fact that we depend on scope explicit and it is also more concise than writing `{{ 'foo' | blah:this }}` all the time.

Btw, with the possibility to inject services into filters, they are not pure functional (because services can have state). Therefore, one could argue, why bother with the scope being implicitly available if they are not pure functional anyway? Just because of 10% performance gain measured in Chrome only?

**Comment by lgalfaso** [comment]
This was a conscious modification. Even when this breaks filters that have a strong dependency on `$scope`, I doubt that this is going to be reverted
