### ISSUE TITLE
Accessing Angular documentation by something.ng/topic

### ISSUE THREAD

**Issue by jankoprowski** [angular/angular.js#9014]
I love the way how PHP documentation is easy accessible. You are writing:

  php.net/your-topic

and you are redirected to appropriate topic. Might be concept, function name, or data structure.
I'd love to see some short *.ng/your-topic domain/app redirecting you to appropriate part of the documentation.

**Comment by Narretz** [comment]
We never got round to this feature, and at this point it's out of scope. But you get suggestions when you enter a url that doesn't exist, though :)
