### ISSUE TITLE
enabled multiple urls for $routeProvider 

### ISSUE THREAD

**Issue by calidion** [angular/angular.js#9041]
```
.when('/activities/:page') 
````
=>
```
.when(['/activities/:page', '/activities'],
````

**Comment by calidion** [comment]
When would this feature be integrated and released? i have to use my own variant for this feature currently.

**Comment by wesleycho** [comment]
This router has been deprecated for a little while - I would personally recommend using [UI Router](https://github.com/angular-ui/ui-router) over ngRoute, it is a far more powerful router which would allow for multiple state definitions for each route, accomplishing the desired semantics.

I would assume that this isn't going to be added to core though, so I would recommend looking elsewhere.

**Comment by wesleycho** [comment]
This router has been deprecated for a little while - I would personally recommend using [UI Router](https://github.com/angular-ui/ui-router) over ngRoute, it is a far more powerful router which would allow for multiple state definitions for each route, accomplishing the desired semantics.

I would assume that this isn't going to be added to core though, so I would recommend looking elsewhere.

**Comment by gkalpak** [comment]
`ngRoute` is definitely not deprecated. Sure it is not as powerful and `uiRouter`, but it is a viable alternative for plenty of simpler usecases.

In any case, as far as I understand, the requested feature is only about adding some syntactic sugar and is trivially "polyfilled" on `$routeProvider`, e.g. via decorators.

Based on that and the fact that this hasn't gain much traction, I'm going to close this as _won't fix_.

**Comment by calidion** [comment]
@gkalpak 
Would you please show me an example on who to polyfill with decorators?
Thanks.

**Comment by gkalpak** [comment]
My fault; it is not possible to do it with decorators, since you want to augment a provider, not a service.
You can do it in a config block: [demo][1]

[1]: https://codepen.io/ExpertSystem/pen/dXXYEa?editors=0010
