### ISSUE TITLE
Slow and unresponsiveness in Firefox

### ISSUE THREAD

**Issue by pocesar** [angular/angular.js#9084]
My app used to work normally with beta 19, now it doesn't anymore, the "busy script" popup always come up. I'm using rc1 on Firefox 32

It's very hard to pinpoint the problem, since nothing was changed, only the angular (and the other libraries) were updated.

A simple "click" yields the following callstack (massive number of calls for a simple ngClick)
![clipboard01](https://cloud.githubusercontent.com/assets/461084/4267708/41d10a56-3ca1-11e4-9aac-18f0aea0329e.png)

Around 7-8 seconds to be able to click again

**Comment by Narretz** [comment]
This is covered by the current docs imo.
