### ISSUE TITLE
Change route.js to load templates after a route gets resolved

### ISSUE THREAD

**Issue by schmitch** [angular/angular.js#9091]
Currently we have the following implementation of route.js:

https://github.com/angular/angular.js/blob/master/src/ngRoute/route.js#L536-L582

That is somewhat dump since we can't change the template in a resolve of a Router. (Currently a controller is changeable by $route.current.controller = 'MyNewController')
So it would be great to have all template loading functions in a seperate then(function()) like here:
https://gist.github.com/c-schmitt/10ae22be266c39410327

So I could create a resolve function that resolves me to either Ctrl1 + template1 or to Ctrl2 + template2.
And change the Controller / Template on a runtime base via $route.current.controller and $route.current.tempalteUrl.

**Comment by Narretz** [comment]
ui-router can do that, and at this point, it's reasonable to expect that you use an external lib if you have this requirement.
