### ISSUE TITLE
Windows Phone 10 / IE 10 bugs with displaying opt groups with ngOptions

### ISSUE THREAD

**Issue by likesjx** [angular/angular.js#9094]
Windows Phone browser object will not display the contents of the opt group without a non-empty value. Any opt group created by ngOptions will not be displayed.

**Comment by Narretz** [comment]
> Has there been any movement around this? you can try m.att.com and try paying your bill...

No that's an interesting comment.
So I was actually able to reproduce this in IE10. It seems to me that this is a pretty low-impact bug, as most people will disable browser form validation when using angular.

**Comment by Narretz** [comment]
Closing as low frequency bug. As a workaround, a regular select can be used.
