### ISSUE TITLE
issue with ngOptions an IE 

### ISSUE THREAD

**Issue by vivalaakam** [angular/angular.js#9113]
If I push the button to add a row is added to the unused OPTION. in chrome it is work in chrome it works fine, but in IE9 if i add row and change her, previous options changed too.
I've done it in different ways, and always the same result
http://jsfiddle.net/vivalaakam/bmLvjsqo/ 
http://jsfiddle.net/vivalaakam/y4q48v2a/

**Comment by Narretz** [comment]
I just tried to reproduce with the instructions, but couldn't. Since this is a rather old issue with not very much activity, I'm going to close it. ngOptions has had a lot of fixes since 1.2.x, so maybe the problem is fixed. If not, please reopen this issue with clear reproduce steps.
