### ISSUE TITLE
Show template name + line number for JS errors from called functions

### ISSUE THREAD

**Issue by mtaran-google** [angular/angular.js#9121]
index.html:

```
1  Hello world
2  <button ng-click="doSomething()">Do it</button>
```

an error like:

```
"Error: undefined is not a function @ index.html:2
    at <anonymous>:2:5
    at Object.InjectedScript._evaluateOn (<anonymous>:730:39)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:669:52)
    at Object.InjectedScript.evaluate (<anonymous>:581:21)"
```

**Comment by Narretz** [comment]
This is something that Angular can do, but the cost of doing it in AngularJs is too high compared to the value at this point. Also note that the expression in the OP wouldn't ever throw as the parser doesn't consider undefined an error. If you had a syntax error e.g` `doSomething(/)`, then parse throws and includes the expression in the error.
