### ISSUE TITLE
Request: Human-readable alternatives to '@=&' in custom directive scope:{} definitions

### ISSUE THREAD

**Issue by colllin** [angular/angular.js#9125]
I've been using Angular part-time for over a year, and I still have to look up the meaning of `@`, `=`, and `&` in the `scope: {}` definitions every time I read or write it.

How about:
```
scope: {
    // These four are equivalent
    title: '@',
    title: '@title',
    title: 'text',
    title: 'text title',

    // These four are equivalent
    model: '=',
    model: '=model',
    model: 'property',
    model: 'property model',

    // These four are equivalent
    onMessage: '&',
    onMessage: '&onMessage',
    onMessage: 'expression',
    onMessage: 'expression onMessage'
    
}
```
Obviously, the syntax and naming is up for debate.  You guys will have a much better understanding of the bigger picture.

**Comment by lgalfaso** [comment]
based on https://github.com/angular/angular.js/pull/9137#issuecomment-57872070, this is not moving forward

**Comment by colllin** [comment]
Bummer.  Thanks @shahata (https://github.com/angular/angular.js/pull/9137#issuecomment-66857523) for your clear-headed support.
