### ISSUE TITLE
select/ngOptions fails to update model after keyboard selection

### ISSUE THREAD

**Issue by 43081j** [angular/angular.js#9134]
See here:
http://plnkr.co/edit/9VymegmYt3tZPTH65Gj8?p=preview

Follow these steps:
- Enter the first input
- Tab to select
- Press `a`
- Press down

See that `foo` is now incorrect. If you use the mouse to select another and then reselect the same one, it then updates correctly.

Seems a rather odd, specific issue so im not entirely sure where in the chain this is occurring.

**Comment by Narretz** [comment]
I just closed some duplicates of this issue, so here's a quick recap:

Chrome (Blink) / Safari (webkit) has a bug not firing change when an option is removed. Bug filed as https://code.google.com/p/chromium/issues/detail?id=415505

Firefox basically follows the "spirit of the spec" by not firing change when the select value is changed via keyboard, but Chrome and IE do it, so it coud be considered a bug. Tracked as https://bugzilla.mozilla.org/show_bug.cgi?id=126379.

As a workaround, you can add a directive that fires the change event on keyup (thanks to @gkalpak for this):

```js
directive('changeOnKeyup', function changeOnKeyupDirective() {
  return function changeOnKeyupPostLink(scope, elem) {
    elem.on('keyup', elem.triggerHandler.bind(elem, 'change'));
  };
});
```

[Fixed plnkr][1]

[1]: http://plnkr.co/edit/PcD55HqECuJrSC9usUFv?p=preview

**Comment by doug65536** [comment]
@Narretz Isn't that a memory leak? You need a $destroy handler to remove the `.on` event handler.

**Comment by Narretz** [comment]
The Chrome has been fixed: https://code.google.com/p/chromium/issues/detail?id=415505

**Comment by Narretz** [comment]
Wrt the Firefox behavior, we have to accept that this is a browser quirk that must be fixed by Firefox, or worked around as specified. I have added a note in the select docs (https://github.com/angular/angular.js/commit/dcc57f1718b1b52a22ad833de4d093bcb418064b) and will close this issue.

**Comment by adrian-gheorghita** [comment]
- sdsa
