### ISSUE TITLE
Video "Fundamentals in 60 minutes" on angularjs.org outdated

### ISSUE THREAD

**Issue by farbgeist** [angular/angular.js#9174]
At 

https://docs.angularjs.org/guide

The link to "Fundamentals in 60 Minutes (video)" ( https://www.youtube.com/watch?v=i9MHigUZKEM ),
leads to a introduction to angular.js predating 1.2.

The code examples will not work with 1.3 at all and only in part with 1.2(routing).

My suggestion:
- Remove that video until it is redone with the current stable version (1.3) (send an according note to the author)
- Use a diagram similar to https://www.youtube.com/watch?v=i9MHigUZKEM#t=2010 in a central part of the documentation.

**Comment by Narretz** [comment]
This has come up again here: https://github.com/angular/angular.js/issues/12591 @petebacondarwin WDYT?  Remove the video or try to annotate it? Personally, I think we should remove it. It's probably too much work to get it in shape for 1.4.

**Comment by petebacondarwin** [comment]
This video was originally made by @DanWahlin - perhaps we could see if he could update it or suggest an alternative? In the meantime we should probably remove it or modify the link to indicate that the video is for 1.2

**Comment by DanWahlin** [comment]
I wish YouTube allowed video updates - they don't though. Everything that has changed has been annotated in the video and the samples they can download have been updated. The main changes over the years (that are covered in the video anyway) are:

1. Stand-alone controller functions are shown initially and then plugged into a module later in the video. An annotation is there about how stand-alone functions can't be used (even though they were used just to keep things simple initially in the video - modules are used later as mentioned).
2. Routing changed and there's an annotation there.

While I still get tons of people giving positive feedback and saying how it helped them learn Angular quickly, some people don't read the annotations which does make it a challenge (especially with routing). If you guys want to pull if from the Angular site I completely understand - a lot has changed in 2 years. :-)

**Comment by Narretz** [comment]
It looks like there are still people who find the video helpful (see recent comments), so we'll keep it
