### ISSUE TITLE
ngAnimate: ngInclude not applying first enter animation when the template is defined inline

### ISSUE THREAD

**Issue by alainjacomet** [angular/angular.js#9223]
Following the example in the [AngularJS docs for ngInclude and ngAnimate](https://docs.angularjs.org/api/ng/directive/ngInclude#example) , I've made a simple modification to it so that templates are loaded from script tags instead of from urls.

[See Plunkr here](http://plnkr.co/edit/XmsGdXbqcToOEV2a7uIz?p=preview)

The problem is that if we define our templates inline, like so:

```
   <!-- inline templates 
   Comment this to see the enter animation again:-->

   <script type="text/ng-template" id="template1.html">
       Content of template1.html defined inline
   </script>
   <script type="text/ng-template" id="template2.html">
       Content of template1.html defined inline
   </script>
   <!-- /templates -->
```

Then the content is added correctly, but the first enter animation stops working (animations from subsequent changes seem to work though).

I tried this on Chrome 37.0.2062.122 and on Firefox 32.0 and the example uses `angular#1.3.0-rc.2` and `angular-animate#1.3.0-rc.2`

Any workarounds to this problem?

**Comment by Narretz** [comment]
@manudurgoni Yes, but only globally. Add this:

```
.run(function($animate) {
     $animate.enabled(true);
   });
```
