### ISSUE TITLE
directive restrict attribute(may not be a issue)

### ISSUE THREAD

**Issue by HughGrant** [angular/angular.js#9230]
I accidentally changed the restrict attribute of one of custom directive from "E" to "e".

since the my app didn't show up anymore, like angular is totally ignoring that directive and giving out no warning or error at all.

When changed it back to capital "E", everything works fine now.

I think this is not very friendly to a developer, maybe I just forget to turn on some warning setting?

Anyway, I think this worth a mention.

Close this if I went wrong.

**Comment by Narretz** [comment]
We actually throw since 1.6 if this is not one of EACM
