### ISSUE TITLE
es-us Number Group and Decimal Separator Incorrect

### ISSUE THREAD

**Issue by mgallag** [angular/angular.js#9232]
The number group and decimal separators are incorrect for the es-us locale in [angular-locale_es-us.js](https://github.com/angular/angular.js/blob/6a96a8200a/src/ngLocale/angular-locale_es-us.js)

These locale files are generated using rules defined in [Closure Library](https://github.com/google/closure-library).

Once google/closure-library#350 is closed, regenerate the locale files in angular.js to correct the group and number separators for the es-us locale.

Expected 
- Decimal: `.`
- Group: `,`

Actual
- Decimal: `,`
- Group: `.`

**Comment by Narretz** [comment]
Looking good: https://github.com/angular/angular.js/blob/71f437c15a606b542536e70c392808e84d982078/src/ngLocale/angular-locale_es-us.js
