### ISSUE TITLE
ng-click should do some helpful accessibility things by default 

### ISSUE THREAD

**Issue by ewinslow** [angular/angular.js#9254]
I often see naive developers doing this:

```html
<a href="" ng-click="...">Click me</a>
<div ng-click="...">Click me</div>
```

What would really be better is this:

```html
<button ng-click="..." class="link">Click me</button>
<button ng-click="..." class="reset">Click me</button>
```

plus css styles to make the classes do the right thing.

However, it seems that this is too much to ask of developers. We are a lazy bunch and don't want to define new classes and reset styles for the sake of accessibility. To help folks out would be nice if `ng-click` automatically assigned the correct accessibility attributes if not already specified (`role="button" tabindex="0"`) and handle all the right input handling (e.g. pressing enter, spacebar) to communicate to assistive technology that this element is actually a button , unless a role is explicitly specified already.

This would likely increase code size a little bit, so maybe it makes sense to put this extra logic into the `ngAria` module so that it is opt-in.

**Comment by joe-watkins** [comment]
@DmitryEfimenko I've yet to think up a good reason to not use a real element when needed eg. `button` or `anchor` etc. and if I did I sure wouldn't sleep well that night :) But giving it some thought you could draw up a directive to handle such with ngAria: http://codepen.io/joe-watkins/pen/azzraM
