### ISSUE TITLE
One-time binding functions

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#9275]
This may be possible, but I haven't seen it documented.

Currently I have this:

```javascript
$scope.$watch(function() {
  return foo.bar;
}, function(newVal, oldVal) {
  // do something awesome
});
```

if I want to use the new bindonce syntax, I have to do this:

```javascript
$scope.myWatchFunction = function() {
  return foo.bar;
}

$scope.$watch('::myWatchFunction()', function(newVal, oldVal) {
  // do something awesome
});
```

I've already suggested adding $watchOnce (#8930), but maybe there's another less imposing way to do this without forcing the user to add a function to the scope. Something like this:

```javascript
function myWatchFunction() {
  return foo.bar;
}
myWatchFunction.oneTimeWatcher = true;

$scope.$watch(myWatchFunction, function(newVal, oldVal) {
  // do something awesome
});
```

All of this, of course is just sugar for:

```javascript
var stopWatching = $scope.$watch(function() {
  return foo.bar;
}, function(newVal, oldVal) {
  if (!angular.isDefined(newVal) {
    return;
  }
  stopWatching();
  // do something awesome
});
```

Looking at it, it doesn't seem like it's sugar coating much, but at least it keeps stuff off of my scope and I still think it's nice to not have to worry about managing when a watch is stopped when this is a pretty common use case I believe (at least, I've seen it plenty). Just curious if this is a more acceptable approach to my suggested [$watchOnce](https://github.com/kentcdodds/watchOnce) functionality. (Which I still believe would be valuable to include in the core).

**Comment by lgalfaso** [comment]
#8930 is not going to land, so there is no need to keep this open
