### ISSUE TITLE
Feature request: Custom attribute prefix registration

### ISSUE THREAD

**Issue by hon2a** [angular/angular.js#9276]
AngularJS supports various formats when using directives in templates, including prefixes `x-` and `data-`. It would be nice to have an option to register an additional prefix to easily distinguish own directives in templates from native elements/attributes and third-party directives using other prefixes.

---

An obvious way to achieve the desired result without any additional functionality is to register the directives with the prefix and use it in directive implementation. It's not good enough, for multiple reasons:
- Our codebase is very modular and we have strict naming policy - if there's a `foo` widget consisting of a service and a directive, they are in modules `foo.service` (service `foo`) and `foo.directive` (directive `foo`), and placed in files with the same names. Adding prefixes everywhere would ruin the schema.
- Aforementioned modularity allows to easily pick a module and release it (or internally share it) as a separate package. It should not need to know about the prefix.
- Prefixing adds clutter everywhere. If a directive uses isolate scope bindings, it needs to either use prefixed properties on inner scope or prefix all binding configurations.

---

I'd envision something like:

``` javascript
$compileProvider.registerPrefix('abc');
```

``` javascript
angular.module('foo.directive', []).directive('foo', function () {
    return {
        scope: {
            foo: '&',
            bar: '='
        },
        link: function ($scope) {
            $scope.$watch('bar', function (val) {
                // ... (property is not prefixed)
            });
        }
    };
});
```

``` html
<div abc-foo="doSomething()" abc-bar="withThisOption"></div>
```

What do you think?

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
This would be great to avoid naming conflicts. Even with isolate scope variables, there can be conflicts like trying to use a directive with isolate scope variable named `title`, but you don't want that darn tooltip to pop up.

Easy to work around in my own code, harder to work around in third party code.

**Comment by Narretz** [comment]
Ok, so the idea is that you should be able to register custom prefixes that the compiler ignores, similar to x and data. I don't think that's a common use-case. Ideally, directives should always be prefixed, so that conflicts are minimized. If there's a conflict with other 3rd party directives, you should reach out to them and ask them to change the directive name.

@807811b0-1373-11e5-b60b-1697f925ec7b Could you give an example? I'm not sure I understand what you mean.

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
Perhaps two directives conflict because the HTML attributes the authors chose to use for configuration are the same.

**Comment by Narretz** [comment]
Namespacing is not coming to AngularJS at this point. :(
