### ISSUE TITLE
Syntax improvement: separating module definition from its dependencies

### ISSUE THREAD

**Issue by userpixel** [angular/angular.js#9294]
One of the most common forms of defining an angular module is this:

```
angular.module('app', [])
  .controller('Ctrl', ['$scope', function Ctrl($scope) {
    //body...
}]);
```

Array to me is something that contains elements of the same type so the syntax is not very intuitive. How about having the list of dependencies in an array like [AMD](http://requirejs.org/docs/api.html#define):

```
angular.module('app', [])
  .controller('Ctrl', ['$scope'],
          function Ctrl($scope) {
            //body...
          });
```

Of course that dependency array is optional.

This way the whole array will contain only string elements (maybe it simplifies Angular core too) each of which refers to a module. The array matches the function parameters one by one. (kinda like `arguments`) so it is even easier to write the function right under it.

**Comment by Narretz** [comment]
I agree, not a worthwhile change.
