### ISSUE TITLE
ngMessages blows up when there are duplicate child ngMessage keys

### ISSUE THREAD

**Issue by niallsmart** [angular/angular.js#9338]
The `ngMessages` directive gets into an invalid state and throws an exception when there are duplicate `ngMessage` child keys specified. For example:

```html
<div ng-messages="form.id.$error">
  <div ng-message="required">
    User ID is required.
  </div>
  <div ng-message="required">
    User ID is required.
  </div>
</div>
```

The issue seems to be a bug in the re-ordering logic in `registerMessage` which is attempting to preserve the ordering from an included template, but in this scenario inserts `null` into `messages`.

Test case here: http://plnkr.co/edit/7u4oFTGbeLqa1tmfMNlJ (look at the console log).

**Comment by matsko** [comment]
#10676 will fix this for 1.3 and 1.4
