### ISSUE TITLE
Allow query parameter values with equals signs in them

### ISSUE THREAD

**Issue by 4578395263256** [angular/angular.js#9357]
Currently if you have a URL such as example.com/a?b=c=d, then the URL gets converted to example.com/a?b=c. It would be nice if this didn't happen, though some would argue that having un-encoded equals signs in the parameter value is bad.

If you wanted to fix this, then in function parseKeyValue in angular.js, instead of calling .split('=') you would have a function that does at most one split.

**Comment by tsteur** [comment]
At Piwik we have a similar problem as we have URLs like `&segment=entryPageUrl==value%200,entryPageTitle==value%201;pageTitle==value%202` which results in `&segment=entryPageUrl`.

**Comment by gkalpak** [comment]
This has been fixed. `parseKeyValue` now uses `.indexOf('=')`, so `?a=b=c` will be parsed as `{a: 'b=c'}`.
