### ISSUE TITLE
dateFilter uses locale timezone offset for "Z" even when UTC timezone is specified

### ISSUE THREAD

**Issue by niallsmart** [angular/angular.js#9359]
I would expect the following expression to be a no-op:

```
{{ '2012-01-01T00:00:00Z' | date:'yyyy-MM-ddTHH:mm:ssZ':'UTC' }}
```
However, the "Z" format specifier always uses the locale timezone offset – i.e., ignores the timezone specified to the filter – so in my browser this evaluates to:

```
2012-01-01T00:00:00-0500
```

**Comment by igcarun07** [comment]
Thanks @niallsmart
