### ISSUE TITLE
Proper line numbers in $log output in Chrome

### ISSUE THREAD

**Issue by lookfirst** [angular/angular.js#9377]
Right now, output of $log in Chrome shows the line number from where [the .apply() function is being called] (https://github.com/angular/angular.js/blob/95c2738244172ab3aff215e622a610dbb30631d6/src/ng/log.js#L152) within Angular.

It would be nice if the line number is where the $log was called in my source code.

I'm not super clear on how [loglevel](https://github.com/pimterry/loglevel) does it, but it would be nice to replicate that behavior:

```Log output keeps line numbers: most JS logging frameworks call console.log methods through wrapper functions, clobbering your stacktrace and making the extra info many browsers provide useless. We'll have none of that thanks.```

The reason why I'm asking for this in Angular is because there is [another project](https://github.com/lwhiteley/AngularLogExtender) which just extends $log to provide more functionality vs. replacing it entirely. It would gain from having the line numbers be equal to where $log was called in my code.

Thanks!

**Comment by wesleycho** [comment]
I think this can be closed given prior issues on logging.

**Comment by lookfirst** [comment]
@wesleycho Please enumerate these prior issues you speak of. =)

**Comment by gkalpak** [comment]
@lookfirst: #2975, #11660 and #14224 to name but a few :smiley:
There is more context/background on why why can't/won't "fix" `$log` in these issues. That said, it is trivial to write your own `console` wrapper.

@wesleycho: Thx for the awesome work on issue clean-up :clap:
