### ISSUE TITLE
#8761 don't work if key is object

### ISSUE THREAD

**Issue by Delagen** [angular/angular.js#9383]
#8761 does not work when ngModel value is object
Look at console
http://jsbin.com/buvowimipale/5/
I think optionsMap should be array of values.

**Comment by Narretz** [comment]
In 1.3.9, there was a huge update to ngOptions, please test again.

I also have problems seeing what's wrong in the jsbin, it looks good to me.

**Comment by Narretz** [comment]
Sorry, correction - the big update is in the unstable branch (1.4.0-beta.0). Anyway, please feel free to reopen with a reproduction that clearly shows the issue. Thank!
