### ISSUE TITLE
Add ng-enter-end ng-leave-end to handle final animation states

### ISSUE THREAD

**Issue by rlucha** [angular/angular.js#9397]
Currently all animation helper classes (ng-enter, ng-enter-active, etc.) dissapear when the element ends the animation. 

In the case you need an element hidden in its natural state but shown after the animation ends you have no way to control this but to add additional classes. This makes animation classes less reusable as you depend on the controller or custom directives to control final animation state.

Adding _and keeping_ ng-enter-end, ng-leave-end or similar only when present in the css should do the trick.

This or another way where you can define inverse animations (in which the final state is the actual state you want) should be present.

**Comment by havenchyk** [comment]
@rlucha could you please provide an example on plnkr or jsbin?

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got any feedback. Feel free to reopen this issue if you can provide new feedback.
