### ISSUE TITLE
ng-minlength-valid class is applied even when it should be invalid, when ng-pattern is applied (1.2.x)

### ISSUE THREAD

**Issue by clarkdever** [angular/angular.js#9399]
**Why it matters:** I work for a company that validates forms related to Healthcare Information, we do serverside validation - but it makes some data entry person's life easier if we can get the submission correct the first time.

**Reproducable:** Always
**Browsers:** Chrome 37, Firefox 32 and IE 11
**Operating System:** Windows 7

Here's a plunk showing the issue: http://plnkr.co/edit/wrfUGUdjBJcv7pu2zTTY

# Steps to reproduce:
* Load Plunker
* Type in the input and exceed the min length of 2, then delete to empty the input 
* Inspect element > input > ng-minlength-valid class is applied even though it should be invalid

**Comment by kentcdodds** [comment]
I'm not sure this is a bug. The [`minlength` validator](https://github.com/angular/angular.js/blob/v1.2.25/src/ng/directive/input.js#L611) will pass if it's given nothing OR if the length of what is given is less than the minlength. This is true of [master](https://github.com/angular/angular.js/blob/8a6cbb3c94ab7530e6e2bf97e8c05cbd02b76cad/src/ng/directive/validators.js#L87) as well. So I believe that your example is behaving as expected.

**Comment by Narretz** [comment]
Regardless, as 1.2.x only receives security fixes, I'm gonna close this.
