### ISSUE TITLE
'file': noop <- useless code preventing reading/rewriting of file display code

### ISSUE THREAD

**Issue by djvs** [angular/angular.js#9427]
This is currently on line 18615 in 1.3.0-rc4.  I've been deleting this line from updates since ~1.2.8, because it needlessly breaks directives which are used to rewrite file controls.  Example:

    app.directive('filestyle', function() {
      return {
        restrict: 'A',
        scope: {
            "filestyle": "="
        },
        transclude : true,
        link : function($scope,$element,$attrs){
            $attrs.$observe('filestyle',function(value){
              if(typeof $scope.filestyle == "string"){
                $element.fileinput("<button type='button' class='btn btn-default'>" + $scope.filestyle + "</button>");
              } else {
                $element.fileinput("<button type='button' class='btn btn-default'>Choose file...</button>");
              }
            });
        }
      };
    });

    <div>
      <input type="file" filestyle="'Choose image...'" ng-model="content.image" name="image" />
      <br>{{ stripfilename(content.image) }}
    </div>

where $element.fileinput uses this:

http://plugins.jquery.com/fileinput/

**Comment by wesleycho** [comment]
Wasn't there an explicit decision made not to support file inputs due to their one way nature?

The previous behavior caused tickets filed that Angular should support them fully with ng-model, which clashes with not being able to edit the value of a file input due to the spec.  Fulfilling this issue would open that can of worms again.

**Comment by djvs** [comment]
So what?   Don't try to set them, they're not even settable.

**Comment by wesleycho** [comment]
That still goes against what ng-model was meant for - two-way binding.  If one wanted, it should be easy on the user side to implement desired support for file inputs.

In addition, the previous "support" that was in Angular for file inputs was highly flawed, running the normal text input $parsers and $formatters even though the value is a file object.  IIRC, IE9 support is also sketchy, which Angular officially supports - hacking around IE9 issues for this typically involves using a flash plugin or an iframe, which are highly undesirable options for what needs to be a slimmer core.

**Comment by djvs** [comment]
So then what is the support for displaying or parsing a file input?  None at all?  Copy and paste all the code for ng-model?  What if I need client-side validations for checking file extensions?  Doesn't make much sense to me...

**Comment by wesleycho** [comment]
Correct, it is none at all - IIRC, IE9 support is the deal breaker, since the File API support didn't land in IE until IE10.

None of the existing validations make sense for validating file objects also.

**Comment by djvs** [comment]
Then you leave people like me monkey-patching this noop thing every time they upgrade their Angular release.

**Comment by wesleycho** [comment]
The correct solution given the Angular team explicitly not supporting this is to create your own directive with the appropriate usage of NgModelController - it would not be difficult for a user to implement.

**Comment by gkalpak** [comment]
What @whesleycho said !

**Comment by wesleycho** [comment]
Given that there is a special mention in the docs already about input[type="file"] [here](https://docs.angularjs.org/api/ng/directive/input), I think this issue can be closed as a won't support given prior decisions made.

**Comment by gkalpak** [comment]
Agreed.
