### ISSUE TITLE
Feature Request: allow for additional attributes in getterSetter methods

### ISSUE THREAD

**Issue by sqwk** [angular/angular.js#9442]
At the moment an input can be bound to a getterSetter method via `ng-model-options`:

    <input data-ng-model="somevalue" data-ng-model-options="{getterSetter: true}" />
    
    …
    somevalue: function(newValue) {
        if (angular.isDefined(newValue)) {
            // Set something
        }
        // Return something
    }, …

However, one cannot pass additional variables to the getterSetter, which might be useful when using `ng-model` inside a `ng-repeat` to identify which row is being updated:

    <input data-ng-model="somevalue" data-ng-model-options="{getterSetter: true, attrs: ['foo': 'bar']}" />
    
    …
    somevalue: function(newValue, attrs) {
        if (angular.isDefined(newValue)) {
            // Set something
        }
        // Return something
    }, …

**Comment by Narretz** [comment]
I agree with both @lgalfaso and @btford; closing.
