### ISSUE TITLE
More powerful $cookies service

### ISSUE THREAD

**Issue by reichart** [angular/angular.js#950]
I want to set a cookie on the root path `/` so it's available everywhere on the domain.

But the `$cookies` service only accepts `name` and `value`, and always sets the cookie `path` to the current page via `self.baseHref()`.

Could the `$cookies` service be extended to provide access to additional cookie properties like `path`, `expires`, `domain` and `secure`?

I quite like the API of the `jquery.cookie` plugin: https://github.com/carhartl/jquery-cookie#usage. It keeps the common `name=value` use case simple and allows to set additional cookie properties via a third `options` object parameter.

I'm not very proficient in Javascript but I might try to implement something over the weekend.

**Comment by zoltantarcsay** [comment]
+1

**Comment by gelus** [comment]
I'd love to take this one if it is available.  however it looks like it has already been taken care of by this commit: d4567891b8616596d125b4dd5560dc9471d2ed63

Can any one verify this?

**Comment by catindev** [comment]
+1

**Comment by stevermeister** [comment]
I've updated my module fix - [ng-biscuit](https://github.com/stevermeister/ng-biscuit), but of course [ngKookies](https://github.com/voronianski/ngKookies) looks more mature
