### ISSUE TITLE
Set a user defined value for the "undefined"-Option of a select

### ISSUE THREAD

**Issue by 0815fox** [angular/angular.js#9548]
It should be made possible for the user to set a value for the option representing the "undefined"-State of a select when using ng-options.

In my case I would like to use an empty string, as thats the way it is represented in my model. I have the following select:

```
<select ng-model="data.local.data[modelVariantGUID][activeLocalizationGUID][textelementGUID].LinkedModelVariantGUID" ng-options="modelVariantGUID as modelVariant.name for (modelVariantGUID, modelVariant) in modelVariants">
    <option value="">none</option>
</select>
```

Our model expects, that data.local.data[modelVariantGUID][activeLocalizationGUID][textelementGUID].LinkedModelVariantGUID is set to an empty string if no element is selected. Of course we could change the model to fix this (and change all other places where it is used in that way), but thats a big effort.

So it would make this feature much better, if the user could choose, what to be returned in case of the empty selection. Even more flexible would be, to allow multiple "nothing"-Options with different values, which are set up in addition to the existing options. I suggest, that for an option without value-Attribute the value undefined is assumed.

**Comment by Narretz** [comment]
We recently decided in another issue that this will not be included in core, as it can be added via 3rd party directive: http://plnkr.co/edit/S9XHqf?p=preview
