### ISSUE TITLE
baseHref() function tries to run .replace() on non-string object

### ISSUE THREAD

**Issue by lucian303** [angular/angular.js#9561]
AngularJS v1.2.26: angular.js:4607: The ```href.replace()``` function call runs when href itself is a non-string Object (type: jQuery.fn.jQuery.init), resulting in an error and failure to initialize angular. This seems to be a race condition as many times the href variable in this case is a string while at other times it's not. Most likely, it's related to the ```baseElement.attr('href')``` call on the previous line which is either not returning a proper attribute. In fact, the ```baseElement.attr('href');``` call returns baseElement itself and ```href == baseElement``` then.

A quick solution would be to check that href is a string before running replace, although that really ignores the problem with the ```.attr()``` call above.

**Comment by Narretz** [comment]
Closing because we don't have a reproduction.
