### ISSUE TITLE
Strange issue with $watch on controller with variables set from isolated scope

### ISSUE THREAD

**Issue by Holocene** [angular/angular.js#9651]
Hi,

I am having a strange issue when creating a custom directive in angular JS. I have created a small sample program that demonstrates the issue:

    <!DOCTYPE html>
    <html lang="en" xmlns="http://www.w3.org/1999/xhtml" ng-app="sample">
    <head>
        <meta charset="utf-8" />
        <title>Sample</title>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js"></script>
        <script>
            angular.module('sample',[])
            .controller('SampleController', function ($scope) {
                $scope.$watch('evenTest', function (value) {
                    console.log(value ? "Is Even!" : "Isn't Even!");
                })
            })
            .directive('isValueEven', function ($compile) {
                var directive = {
                    restrict: "E",
                    template: "<input ng-model='searchQuery' />",
                    scope: {
                        isValueEven: '=',
                    },
                    controller: function ($scope) {
                        $scope.$watch("searchQuery", function (value) {
                            console.log("search query changed.")
                            if (value !== "" && value % 2 === 0)
                                $scope.isValueEven = true;
                            else
                                $scope.isValueEven = undefined;
                        })
                    }
                }

                return directive;
            })

        </script>
    </head>

    <body ng-controller="SampleController">
        <is-value-even is-value-even="evenTest"></is-value-even>
    </body>
    </html>

There is a small directive and a controller. The directive creates an `input` element. When the user types into the input element, `$scope.$watch('searchQuery',...)` is called. If the input value is even, the `$scope.isValueEven` field on the directive is set to `true`. Otherwise, it is set to `undefined`.

At this point the bug arises. We would expect the watch function on the controller to be fired now, and the console to output `Is Even!` or `Isn't Even!` as appropriate. However, this function is not called. When the user presses the key a second time, the function is called twice.

Here is the console output:

    [[initial load]]
    Isn't Even!
    search query changed.
    [[user presses '2']]
    search query changed.
    [[user presses '1']]
    Is Even!
    search query changed.
    Isn't Even!

As you can see, the watch function is not called as it should be, after the user presses '2'. Instead, it's called once the user presses another key - followed then by another execution of the function.

There are two strange workarounds. You can set `isValueEven` to `null` instead of undefined:

                            if (value !== "" && value % 2 === 0)
                                $scope.isValueEven = true;
                            else
                                $scope.isValueEven = null;

Or, you can bind an element in the HTML to the value of `evenTest`:

    <body ng-controller="SampleController">
        <is-value-even is-value-even="evenTest"></is-value-even>
        {{evenTest}}
    </body>

Doing either of these things makes the `watch` function execute as expected.

This issue has had me scratching my head for several hours! I was particularly perplexed by how it behaves differently if you have something bound in the HTML. In my actual code, I am using a directive called `system-search` to help me apply typeahead to search fields.

    <input data-system-search="searchSystem"
            class="form-control input-sm"
            placeholder="Find system" />
    <span class="glyphicon glyphicon-ok form-control-feedback"
            ng-show="searchSystem"></span>

I tried to remove the glyphicon, and suddenly my search box didn't work anymore!

I would appreciate any insight on this issue, as I have only been using AngularJs for 2 weeks. Am I using the isolated scopes in directives in an unintended fashion, or is this a legitimate bug?

**Comment by petebacondarwin** [comment]
This is fixed at 1.3.18 (http://plnkr.co/edit/GhhSPYq0fHXBiawOXPQZ?p=preview) and 1.4.5 ( http://plnkr.co/edit/NuadmRrLibBeEayDFobO?p=preview)
