### ISSUE TITLE
Docs end to end tests should test against production index

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular.js#9656]
The end to end tests for the docs application don't test against the production build, which led to erroneous code being deployed to production from [build 3437](https://ci.angularjs.org/job/angular.js-angular-master/3437/). This build was trying to load `null` version numbers from Google CDN for all versions of Angular.

**Comment by Narretz** [comment]
16d915c0458b36b19b8a0993d8a9f28cccd572d0 changed tests to run against index-production.html
