### ISSUE TITLE
$location.path() in $routeChangeStart causes infinite loop

### ISSUE THREAD

**Issue by sylouuu** [angular/angular.js#9665]
Hi,

I didn't have this issue with 1.2.26. Extract of my code:

```js
app.run(['$rootScope', '$location', 'config', function ($rootScope, $location, config) {
    $rootScope.$on('$routeChangeStart', function (event, next, current) {
        // Maintenance mode
        if (config.project.maintenance === true) {
            event.preventDefault();

            // The redirect must be inside this method since angular 1.3.0
            $rootScope.$evalAsync(function () {
                $location.path('/maintenance');
            });
        }
    });
});
```

The `/maintenance` route has an empty controller. This code is causing an infinite loop, but not with 1.2.26. Got [this error](https://docs.angularjs.org/error/$rootScope/infdig?p0=10&p1=%5B%5D).

I understand why there is an infinite loop as I don't test the current route before redirecting. Why it worked before?

Is it a bug or something that I skipped from the changelog?

Bests

**Comment by Narretz** [comment]
Explicite Infinite redirection is not a bug, I agree.
