### ISSUE TITLE
Max Digest Iteration loop triggered by using ng-bind with a filter that returns an Array

### ISSUE THREAD

**Issue by btesser** [angular/angular.js#9717]
When ng-bind is used, and the expression includes a filter that returns an array, angular enters an infinite digest loop and eventually cuts out after the 10 digest limit.  I looked at the source and the issue is caused by the fact that ng-bind never uses object equality (angular.equals) to compare the new value and the old value in the watcher, rather since the filter is returning a new array, the old array is never equal and an infinite digest loop is caused.

The same expression will work if you use double curlies for binding rather than ng-bind

See plnkr which shows the bug in action.

http://plnkr.co/edit/t6B3uz

**Comment by Narretz** [comment]
Instead of binding the array directly, convert it to a string with a filter first.
