### ISSUE TITLE
ngMessages - allow custom class for Active and Inactive modes

### ISSUE THREAD

**Issue by arnoldsimha** [angular/angular.js#9719]
ngMessages directive uses hard coded class names for different modes:

```
var ACTIVE_CLASS = 'ng-active';
var INACTIVE_CLASS = 'ng-inactive';
```

It would be great to have custom class names for the modes. This way the HTML developer will be able to crate his own class name conventions in the application

**Comment by matsko** [comment]
@arnoldsimha can't you just add a CSS class to the container element and then target it in CSS using `.my-class.ng-active`? What did you have in mind?

**Comment by arnoldsimha** [comment]
It also an option, but It creates a dependency on angular class names on the project's style sheet.

**Comment by matsko** [comment]
Sorry, there isn't a good usecase for this feature aside from saving some CSS code. We'll need to close it. If you do find another good reason then please reopen.
