### ISSUE TITLE
ng-click working wrong when -webkit-overflow-scrolling: touch

### ISSUE THREAD

**Issue by christopher5106** [angular/angular.js#9744]
Dears,
I have a page full of links ng-clicks, that we can scroll down : 

overflow-y: scroll;
-webkit-overflow-scrolling: touch

I've noticed something strange (both iPhone 4 and Android Samsung Galasy S4) : 

when you touch the page to scroll (touchstart on a first ng-click directive)
and the scroll has enough speed
and you touch again to stop the scroll (touchstart on a second ng-click directive)

then it opens the first ng-click default action on the touchend.

We would expect nothing or the second ng-click to take action. Because the first one has been forgotten for a while.

Could you please give any help on this issue ?

Thanks

**Comment by AviFix** [comment]
I have the same problem.
