### ISSUE TITLE
(feat) Remove requirement of controller when controllerAs and bindToController are true

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular.js#9774]
For context, conversation started [here](https://github.com/angular/angular.js/commit/5f3f25a1a6f9d4f2a66e2700df3b9c5606f1c255#commitcomment-8290642)

I want to be able to do this:

```javascript
angular.module('foobar', []).directive('foo', function() {
  return {
    template: '<div>this is bar: {{vm.bar}}</div>'
    scope: {
      bar: '='
    },
    controllerAs: 'vm',
    bindToController: true
  };
});
```

However, for `bindToController` and `controllerAs` to work, I must add `controller: angular.noop` otherwise they are ignored because there is no controller. I realize this is primarily useful for directives that have no model functionality (template and dom functionality only). But I have plenty of directives that have no need of a controller function and would prefer to avoid the boilerplate.

I believe that this functionality could be accomplished by adding `|| angular.noop` to [this line](https://github.com/angular/angular.js/blob/5f3f25a1a6f9d4f2a66e2700df3b9c5606f1c255/src/ng/compile.js#L1612), however I'm not sure what the implications would be here. I imagine if we made it conditional on the presence of `bindToController` and `controllerAs` then there would be 0 people impacted.

@caitp is unsure whether this use case merits a change and so we're seeking out the opinion of others. I would be happy to submit a tested PR to get this in.

**Comment by mickdelaney** [comment]
+1 for BindTo

**Comment by Tobbe** [comment]
@kentcdodds You're not the only one :smiley: I just came here after trying to do what you wrote in the first post and realizing it doesn't work.

So actually making it work, or implement BindTo gets a :+1: from me!

**Comment by gitnik** [comment]
+1 for being able to use `bindToController`without a controller. I can't count how many times I've used this.

**Comment by gkalpak** [comment]
Not exactly the requested feature, but you can now use the new [`.component()` helper][1] (which has `controller: function () {}` by default):

```js
.component('myComponent', {
  // Look, 'ma, no `controller: ...`
  template: '{{ ::myComponent.message }}',
  bindings: {message: '@'}
});
```

[1]: https://docs.angularjs.org/api/ng/type/angular.Module#component

**Comment by gitnik** [comment]
wow this is pretty neat! Why does this not appear in any changelog?

**Comment by gkalpak** [comment]
Ooops, sorry, it hasn't been released yet. (I got excited, because it was just merged into master.)
It will be available in the upcoming `1.5.0-beta.2` release :smiley:

**Comment by gitnik** [comment]
Sweet! Really looking forward to 1.5!

**Comment by Narretz** [comment]
@petebacondarwin Do you think we want this now that the new component
helper is available? I tend to say "no"
Am 29.10.2015 12:31 schrieb "Nik Karbaum" <notifications@github.com>:

**Comment by petebacondarwin** [comment]
I agree.
