### ISSUE TITLE
Collection of `filterFilter` related issues (with regard to #9757)

### ISSUE THREAD

**Issue by gkalpak** [angular/angular.js#9788]
Following #9757, I tried to gather open `filterFilter`-related issues (bugs, PRs, feature requests) and investigate if/how they relate to #9757 (e.g. if they are resolved or contain test-cases that can be incorporated etc).

Listing my "findings" here to avoid duplication of effort.
<sub>
Kudos to @Narretz for the idea (https://github.com/angular/angular.js/pull/9757#issuecomment-60278402) :smiley:.
</sub>

*\* Updated by Pete with what is left **

---
###### PRs:
- PRs that should be probably closed anyway: ~~#6623~~
- PRs that will need to get updated if ~~#9757~~ lands: ~~#5451, #6695, #8750~~
- PRs that will be obsolete if ~~#9757~~ lands: ~~#7329~~
###### Bugs / Feature Requests:
- Issues that should be probably closed anyway: ~~#1780, #5055, #6222~~, ~~#6655~~
- Issues that are irrelevant to ~~#9757: #2694~~, ~~#6490~~, ~~#8458~~
- ~~Issues that will be resolved if #9757 lands: #7323, #9698, #9984~~

---
#### Bugs / Feature Requests
- **[#6490: Implement filtering on object-based ng-repeat][6490]**  
  This is about adding support for filtering objects (not only arrays) for use with `ngRepeat`.  
  **Irrelevant to #9757.**  
  <img />
- **[#6655: Call stack exceeded error on objects with circular references][6655]**  
  Based on the conversation (and the referenced #6319) it seems to have been decided not to support objects with circular references.  
  **Should be probably closed.**  
  <img />
- **[#8458: `filterFilter` and `orderByFilter` should also work with objects][8458]**  
  This is about adding support for filtering objects (not only arrays).  
  **Irrelevant to #9757.**  
  <img />

**Comment by Narretz** [comment]
@gkalpak Did we handle all of these?

**Comment by gkalpak** [comment]
@Narretz, I don't. think so :(

#9757 has landed and the related issues/PRs have been closed, but there are issues in this list that are unrelated to #9757 (e.g. ones that should (imo) be closed), which aren't handled yet.

**Comment by petebacondarwin** [comment]
So we are left with #6490 #6655 and #8458.

**Comment by Narretz** [comment]
I've just closes the last open issue in this list (#6655), which was declared wontfix here 3 years ago: https://github.com/angular/angular.js/pull/6319#issuecomment-48421085, so I'm gonna close this issue.
