### ISSUE TITLE
Lacks a way to prevent listener from firing

### ISSUE THREAD

**Issue by lookuptable** [angular/angular.js#9805]
Right now there is no way to explicitly prevent a listener from firing for certain event. For example, when a variable being watched is updated internally by our own code, it is desirable to have a way to prevent firing the listener of the variable.

**Comment by Narretz** [comment]
Calling watchers whenever a values changes in a digest is a fundamental part of angular. I don't think there's anything in core that we can do to change this. In v1 watch's action fn you could check if the the value of v1 is already set to the same value before setting it.
