### ISSUE TITLE
Data Persistence in Angular 2.0 Does not support view model

### ISSUE THREAD

**Issue by Izhaki** [angular/angular.js#9813]
Many MVC frameworks fail to accommodate for the fact that view data often need to be persisted (along the usual business model).

One source that does make a reference to this is [IBM's Graphical Editing Framework (GEF)](http://www.ibm.com/developerworks/library/os-eclipse-gef11/) - see 'A tale of two models'.

To give a concrete issue I had when using [ExtJS](http://www.sencha.com/products/extjs/), nodes in a tree model have their `collapse` property as part of the model - which can be persisted to the server along the rest of the model. The problems was that I had the same tree model shown in many views, so collapsing a node on one view, would mean it would be collapsed in all other views.

Perhaps also important to mention that with web applications, one often wish to save the business model to the server, while the view model to local storage.

I had a look at [Data Persistence in Angular 2.0](https://docs.google.com/a/clearbooks.co.uk/document/d/1DMacL7iwjSMPP0ytZfugpU4v0PWUK0BT6lhyaVEmlBQ/edit#heading=h.9wn52ezaxvab) and there seem to be no reference to this.

I'm flagging this as an issue hoping the team may account for such requirements in the design.

**Comment by lgalfaso** [comment]
I think this can just be closes as this is specific to angular 2
