### ISSUE TITLE
event.preventDefault() does not work in $routeChangeStart after $route.reload()

### ISSUE THREAD

**Issue by LudovicGuillaume** [angular/angular.js#9824]
**Angular version 1.3.0**

**Failing code**

``` javascript
	$rootScope.$on('$routeChangeStart', function(event, curr, prev) {
		if (...condition1...) {
			event.preventDefault();
			// do something to get condition1 == false
			$route.reload();
		}
		
		if (...condition2...) {
			event.preventDefault(); // <-- this is not preventing
			// do something to get condition2 == false
			$route.reload();
		}
	});
```

**Issue in source**

          reload: function() {
            forceReload = true;
            $rootScope.$evalAsync(function() {
              // Don't support cancellation of a reload for now...
              prepareRoute(); // <-- param is empty
              commitRoute();
            });
          },

...

    function prepareRoute($locationEvent) {
      var lastRoute = $route.current;

      preparedRoute = parseRoute();
      preparedRouteIsUpdateOnly = preparedRoute && lastRoute && preparedRoute.$$route === lastRoute.$$route
          && angular.equals(preparedRoute.pathParams, lastRoute.pathParams)
          && !preparedRoute.reloadOnSearch && !forceReload;

      if (!preparedRouteIsUpdateOnly && (lastRoute || preparedRoute)) {
        if ($rootScope.$broadcast('$routeChangeStart', preparedRoute, lastRoute).defaultPrevented) {
          if ($locationEvent) { <-- is undefined
            $locationEvent.preventDefault();
          }
        }
      }
    }

**Comment by naomiblack** [comment]
adding a tag because this is an issue for one of our larger internal teams...

**Comment by petebacondarwin** [comment]
Is it possible to provide a running example of this issue?
Or even better a failing unit test?
