### ISSUE TITLE
Strange conflict between ngAnimate and ngRoute

### ISSUE THREAD

**Issue by gerbsen** [angular/angular.js#9836]
I've noticed a very strange bug (or maybe I did something wrong) between ngAnimate and ngRoute. If I try to reload the current route without reloading the full page, something goes wrong and I can't reinitialize my leaflet map. I've created a plunker to demonstrate this behaviour.

If I/you don't load the ngAnimate module everything goes as planned. Am I doing something wrong or is it bug/feature?

Also see the SOF post [here](http://stackoverflow.com/questions/26634365/strange-conflict-between-nganimate-and-ngroute)

**Comment by Narretz** [comment]
I'm sorry that no-one ever looked at your issue :( But at least it works in 1.4.8! Not in 1.2.28 though, but that branch does not receive fixes anymore.
