### ISSUE TITLE
ngTouch ngClick doesn't bubble

### ISSUE THREAD

**Issue by willlma** [angular/angular.js#9872]
When using ngClick on mobile, ngTouch
>prevents the following click event from propagating.

And the custom click event it triggers doesn't propagate.

This creates inconsistent behavior in that on a computer, the click event continues to bubble/propagate, but on mobile, it stops. This means that any directives higher in the dom that listen for element clicks fail.

See [my SO question](http://stackoverflow.com/questions/26685498/ngtouch-ngclick-doesnt-bubble) for more details.

**Comment by AddoSolutions** [comment]
This doesn't make any sense, so for someone to use this, it has to be written for the sole purpose of a mobile app-only?

Couldn't there be a configuration option for this?
