### ISSUE TITLE
Javascript animations broken using angular 1.3.x and form with required fields

### ISSUE THREAD

**Issue by chatellier** [angular/angular.js#9886]
I'm trying to update a working application from angularjs 1.2.26 to 1.3.1.
This application uses javascript animation based on jquery animations.

There is maybe a problem using this animation on a form containing required fields.

This can been seen in following fiddle : http://jsfiddle.net/myj3G/17/

This issue is related to previous issue #6536. This issue contains a workarround that doesn't work anymore.

**Comment by petebacondarwin** [comment]
The bug with `foo` was that multiple classes were being added or removed at the same time. So the value passed to `beforeAddClass` and `removeClass` looked like: `ng-valid ng-valid-required ng-hide`.
Using a regular expression to match the class solves the problem: http://jsfiddle.net/peLe9hj8/
