### ISSUE TITLE
ngModelOption timezone

### ISSUE THREAD

**Issue by jimmywarting** [angular/angular.js#9920]
Thought this would be a discussion about how we can show a date object in another timezone other then local or UTC.

It could be easy to just change the offset with `ng-model-option="{timezone: -1200}"` but that wouldn't be right with DST, Gregorian cut-off time and all that stuff that can make a different.

In order to support anything else you would need to import the [timezone database](http://www.iana.org/time-zones) to show the right time in another timezone. Similar to what [momenjs dose](http://momentjs.com/timezone/)

We are likely never going to see the light of that database in angular core. That's why i think we would need 
- extra module with all this information that hooks into angular core and lets us use `{timezone: 'america/new_york'}` 
- or some kind of callback function that lets us adjust the offset.
  you could do a custom filter & parser/formater to change it yourself. But i feel like that is not the way to go

**Comment by 0xsven** [comment]
I have an issue with that. Solved it with a dirty solution that could have side effects.

See: http://stackoverflow.com/questions/27967621/angular-1-3-how-to-handle-timezones-in-date-and-time-input-fields

**Comment by jimmywarting** [comment]
Fixed already?

**Comment by andrea-spotsoftware** [comment]
any update on this?

**Comment by Narretz** [comment]
This can be handled outside of core, by way of adding custom formatters, and if needs be by disabling the built-in parsers.
