### ISSUE TITLE
Default route missing slash before #

### ISSUE THREAD

**Issue by mudbugz** [angular/angular.js#9941]
I have a case where a slash is not being put between the url and the hash for the default route.  I'm using the same files in two different folders on my local machine hosted by IIS and run in IE 11.  In one case, $browser.url() is returning "http://localhost/app1/" and the other case it is returning "http://localhost/app2".  Notice the missing slash for app2.  This makes the default route "http://localhost/app1/#/sets" and "http://localhost/app2#/sets".  The missing slash causes the url for the views to be wrong, returning a 404.

I'm not the only one to have this issue: http://stackoverflow.com/questions/20690127/angularjs-default-route-missing-slash-before

Example route setup:

```js
$routeProvider
	.when('/sets', {
		templateUrl: 'sets/sets.html',
		controller: 'setsController'
	})
	.otherwise({
		redirectTo: '/sets'
	});
```

I've tracked it down to the this.$get function in angular.js. Adding a check to make sure appBase ends with a slash fixes the issue for me.

```js
if (html5Mode.enabled) {
      if (!baseHref && html5Mode.requireBase) {
        throw $locationMinErr('nobase',
          "$location in HTML5 mode requires a <base> tag to be present!");
      }
      appBase = serverBase(initialUrl) + (baseHref || '/');
      LocationMode = $sniffer.history ? LocationHtml5Url : LocationHashbangInHtml5Url;
    } else {
    	appBase = stripHash(initialUrl);
// make sure appBase ends with a slash!
    	if (appBase.indexOf('/', appBase.length-1) == -1)
    		appBase = appBase + '/';
      LocationMode = LocationHashbangUrl;
    }
```

**Comment by RichardJECooke** [comment]
I think I'm having the same problem.  How do you add your code to Angular without altering the source code: if (appBase.indexOf('/', appBase.length-1) == -1)  appBase = appBase + '/';  ?

**Comment by nuCleaRR** [comment]
I have fixed this issue by modifying HomeController. The result looks a bit ugly, but it does not require altering angular source code.
```csharp
        [Authorize]
        public ActionResult Index()
        {
            if (!Request.Path.EndsWith("/"))
            {
                return RedirectPermanent(Request.Url.ToString() + "/");
            }

            return View();
        }
```

**Comment by RichardJECooke** [comment]
Thanks!

**Comment by petebacondarwin** [comment]
Is this to do with the browser / Angular not understanding that paths that end in `.cshtml` are to be considered as HTML files?

**Comment by petebacondarwin** [comment]
OK, so I am thinking that this is really a problem on the server and not a bug in Angular. It seems that the 
Microsoft ASP.NET Web Optimization Framework is modifying the URLs and removing the trailing slash.

`$browser.url()` is returning exactly what is in `window.location.href`.

A URL that ends in a slash is fundamentally different from one that does not. It is not reasonable for Angular to try to guess whether a slash is expected or not.

To arbitrarily add a slash to the end of URLs would cause other problems. For example, it is very common to have URLs that point to resources that do not have an extension: `http://domain.com/a/b/c`. In this case there is no reason to assume that `/a/b/c` is a "folder" that contains other path elements. In fact the browser does exactly the opposite: it assumes that the `c` path segment refers to a resource inside a folder of `/a/b/`. So when referring to a relative URL within this absolute URL the browser will strip off the `c`: `d/e` -> `http://domain.com/a/b/d/e`.

Therefore the "fix" for this needs to occur on the server, perhaps using a fix similar to that suggested by https://github.com/angular/angular.js/issues/9941#issuecomment-74098280.
