### ISSUE TITLE
testing $q with mocha + chai + chai as promised does not work

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular.js#9954]
I have been trying for days to get `$q` to work with Mocha + Chai + Chai As Promised in Unit Tests, but for some reason, the `afterEach` hook gets called after the Mocha timeout expires, thus my test fails.

The following is a simple example I have been trying out:

```js
"use strict";


describe.only("Promise", function () {

	var $rootScope,
		$scope,
		$q;

	beforeEach(angular.mock.inject(function (_$rootScope_, _$q_) {
		$rootScope = _$rootScope_;
		$q = _$q_;
		$scope = $rootScope.$new();
	}));

	afterEach(function () {
		$scope.$apply();
	});

	it("should resolve promise and eventually return", function () {

		var defer = $q.defer();

		defer.resolve("incredible, this doesn't work at all");

 		return defer.promise.should.eventually.deep.equal("incredible, this doesn't work at all");
	});

	it("should resolve promises as expected", function () {

		var fst = $q.defer(),
			snd = $q.defer();

		fst
			.promise
			.then(function (value) {
				value.should.eql("phew, this works");
			});

		snd
			.promise
			.then(function (value) {
				value.should.eql("wow, this works as well");
			});

		fst.resolve("phew, this works");
		snd.resolve("wow, this works as well");

	 	var all = $q.all([
			fst.promise,
			snd.promise
		]);

 		return all.should.be.fullfiled;
	});

	it("should reject promise and eventually return", function () {
 		return $q.reject("no way, this doesn't work either?").should.eventually.deep.equal("no way, this doesn't work either?");
	});

	it("should reject promises as expected", function () {

		var promise = $q.reject("sadly I failed for some stupid reason");

		promise
			["catch"](function (reason) {
				reason.should.eql("sadly I failed for some stupid reason");
			});

	 	var all = $q.all([
			promise
		]);

 		return all.should.be.rejected;
	});

});
```

The first, third and last tests are failing because of `Error: timeout of 2000ms exceeded`. I really cannot figure out what is the issue, but I've also opened up two more issues on both [Mocha](https://github.com/mochajs/mocha/issues/1421) and [Chai As Promised](https://github.com/domenic/chai-as-promised/issues/68).

It might be just me not calling the digest in the right place or might be the `$q` implementation or the other I mentioned that are not accounting for something inside the `$q` implementation.

**Comment by lgalfaso** [comment]
@rolandjitsu this is working as expected.
@telekosmos read https://docs.angularjs.org/api/ngMock/service/$timeout on how to use timeout in tests

**Comment by blacksonic** [comment]
Can we mention it in the docs? Consumed hours from my life

**Comment by lukeapage** [comment]
I've modified the plinkr to work - 

http://plnkr.co/edit/WAvvu99uLhVRmdlwRWDv?p=preview

So that is one way you can use them together

**Comment by rolandjitsu** [comment]
@lukeapage thanks :+1:

**Comment by aiham** [comment]
@lukeapage Thanks, that did the trick.
@blacksonic is right, documentation would have been nice.

**Comment by mhawila** [comment]
Not that this adds any value but I find it funny that part of developer struggles this days is to make tests work!! May be it is time we re-examine how we are doing things.

**Comment by ShababShahriar** [comment]
Hi @pkozlowski-opensource! I ran into the same problem and could make it work after I created a new scope for the test and did `scope.$apply()` like you suggested. Can you please explain or point me to resources that explain why it was needed? Thanks!
