### ISSUE TITLE
Set Up Performance CI Server

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular.js#9988]
Create a jenkins instance on a local workstation to run full suite of performance benchmarks on every commit to master. Results should be reported to an external server with a basic UI for tracking performance progress for each component over time.

Pending [some changes](https://github.com/angular/benchpress/milestones/Q4%202014) to the benchpress runner.

Backport of Issue https://github.com/angular/angular/issues/176 (though 1.x should be completed prior to Angular 2 implementation).

**Comment by petebacondarwin** [comment]
I suspect that we are unlikely to get round to doing this. What do you reckon @jeffbcross ?

**Comment by jeffbcross** [comment]
Yeah, this was before the great refactor of benchpress, and the automated infrastructure we've set up for Angular2 is all internal.
