### ISSUE TITLE
Generate error when attempting to use filter on objects

### ISSUE THREAD

**Issue by justincy** [angular/angular.js#9992]
Currently it fails silently if you try to use `filter` on objects, as in the example below, because it only supports arrays.

````
<div ng-repeat="item in object | filter:{display:true}">stuff</div>
````

I blew a ton of time on this because it's not very intuitive since `ng-repeat` supports objects. I fully expect to make the same mistake again. A simple error message would save a world of hurt.

**Comment by mgcrea** [comment]
This type check broke promise usage with filters, the following expression is now throwing errors before resolving the promise: This broke AngularStrap typeahead with remote source example.

```
getAddress() | filter:"Al" | limitTo:6
```

```js
  $scope.getAddress = function() {
    return $q(function(resolve, reject) {
      resolve(['Alabama', 'Alaska', ...]);
    });
  }
```

Is there another way to achieve this?
If not, I think we should revert this & remove the check/error (or at least allow promises).
